### ISSUE TITLE
`pnpm install` fails on optionalDependencies

### ISSUE THREAD

**Issue by grigasp** [pnpm/pnpm#1004]
### pnpm version
1.30.1

### Code to reproduce the issue:
Create an empty package with the below package.json:
```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {},
  "optionalDependencies": {
    "something_that_does_not_exist": "1.0.0"
  },
  "license": "ISC"
}
```
Then `pnpm install` 

### Expected behavior: 
`pnpm install` succeeds with a warning about optional dependency not found

### Actual behavior:
```batch
ERROR  404 Not Found: something_that_does_not_exist
at 0\node_modules\pnpm\node_modu…  pnpm/npm-resolver/lib/pickPackage.js:102
at next
at fulfilled                       …@pnpm/npm-resolver/lib/pickPackage.js:4
at _tickCallback                   internal/process/next_tick.js:188
```

### Additional information:
 - `node -v` prints: v8.9.1
 - Windows, OS X, or Linux?: Windows 10

**Comment by zkochan** [comment]
fixed in [v1.31.0](https://github.com/pnpm/pnpm/releases/tag/v1.31.0)
