### ISSUE TITLE
`pnpm bin` is too slow

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1006]
### pnpm version:

1.30.2

### Code to reproduce the issue:

Enter this command:

```sh
(
date; yarn global bin;
date; npm --global bin;
date; pnpm --global bin;
date
) 2> /dev/null
```

Result: `npm --global bin` and `yarn global bin` responses almost immediately but `pnpm --global bin` takes 2-3 seconds.

![image](https://user-images.githubusercontent.com/11488886/35238684-d178c5b2-ffe0-11e7-9d85-f86954a9de6e.png)

### Expected behavior:

`pnpm bin` should be at least as fast as `npm`'s

### Actual behavior:

`pnpm bin` takes more than 2 seconds to display the result

### Additional information:

 - `node -v` prints: v9.4.0
 - Windows, OS X, or Linux?: Linux

### Why is this a problem?

I use `nvm` to manage Node.js versions so executable directory (`node_modules/.bin`) is always changing. In order to use globally installed packages, I must get its exact address and add it to $PATH. It is done in `.bashrc`/`.zshrc` like this:

```sh
export PATH="$PATH:$(pnpm --global bin)"
```

If `pnpm bin` slows, my shell takes longer to load.

**Comment by zkochan** [comment]
The reason it is so slow currently is because we use npm's programmatic API to read all the npm configs. We should probably implement our own config reader but that is not easy. npm allows really complex configurations.

Maybe for simple commands like this once, we can skip reading the configs

**Comment by etamponi** [comment]
I would rather implement faster startup for all the use cases. I observed that if we can make pnpm startup faster, most of pnpm invocations would be basically instantaneous.

**Comment by zkochan** [comment]
Use the [pnpm executable](https://www.npmjs.com/package/@pnpm/exe), it works faster than both npm and Yarn.

`pnpm bin -g` runs 190.88 millis
npm - 305 millis
yarn - 187 millis
