### ISSUE TITLE
Not working with Jest

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1007]
### pnpm version:

1.30.2

#### Step 1: Use pnpm

* Clone [this repo](https://goo.gl/73Xb2c)
* Run `pnpm install`
* Run `pnpx jest`

#### Step 2: Use yarn

* Delete `node_modules`
* Run `yarn`
* Run `yarn jest`

### Expected behavior:

Step 1 doesn't fail

### Actual behavior:

Step 1 fails while Step 2 doesn't

```
TypeError: environment.setup is not a function
```

### My speculation:

Flat `node_modules` doesn't fail.

### Additional question:

How to force pnpm create flat `node_modules`?

### Additional information:

 - `node -v` prints: v9.4.0
 - Windows, OS X, or Linux?: Arch Linux

Related issue: https://github.com/facebook/jest/issues/5369

**Comment by nickpape-msft** [comment]
When working on our project, we noticed that jest had a couple problems correctly resolving symlinked paths. First, we had to [upgrade Jest to ~21.2.1](https://github.com/Microsoft/web-build-tools/pull/466), where they weren't missing dependencies in their package.json. Then, I noticed an issue with jest-resolve not properly resolving symlinks, so I created [a PR ](https://github.com/facebook/jest/pull/5085) for them, but don't yet have a CLA to fix the issue. We ended up doing [a patch ](https://github.com/Microsoft/web-build-tools/blob/master/core-build/gulp-core-build/src/tasks/JestTask.ts#L65) in our tools instead. You might be experiencing similar issues. First, I would definitely advice upgrading Jest, if possible.

**Comment by KSXGitHub** [comment]
I just discovered a workaround for this yesterday: Replace `jest` with `jest-cli`. It worked.

This is the [repo](https://goo.gl/KPjX7s) that I worked on.

**Comment by KSXGitHub** [comment]
I just discovered that the jest will fail if --preserve-symlinks flag is provided

Create a `jest.js`:

```javascript
require('jest-cli/bin/jest')
```

If I execute `node jest.js`, it works

If I execute `node --preserve-symlink jest.js`, it doesn't work.

If I execute `pnpm test` with `node jest.js` being test script, it doesn't work. (No idea why)

If I execute `pnpx jest`, it doesn't throw an irrelevant error message if I add a test to fail (e.g. `expect(0).toBe(1)`), but it passes if all tests pass

**Comment by zkochan** [comment]
A node_modules created by pnpm won't work with Node ran with `--preserve-symlinks` (https://github.com/pnpm/pnpm#limitations). It is a limitation of pnpm because we use symlinks. Though this flag will most probably be deprecated

**Comment by KSXGitHub** [comment]
@zkochan I have no intention of using `--preserve-symlinks` either, the point that I wanna make here is that `pnpm test` and `pnpx test` still fails while `node jest.js` works.

**Comment by dandv** [comment]
Jest doesn't work for me either, but the error is `SyntaxError: Unexpected token import` on the line that imports my module (`import { MyModule } from '..';`). If I run `npm install; npm run test` instead of `pnpm install; pnpm run test`, Jest works. I'm using the latest Jest, 22.3.0.

@KSXGitHub's workaround didn't work (same error). My `.babelrc` is `{ "plugins": ["transform-es2015-modules-commonjs"] }` because [Jest doesn't support native ES6 modules](https://github.com/facebook/jest/issues/4842).

**Comment by wmertens** [comment]
for me the error is `Cannot find module 'jest-environment-jsdom'` - v22.4.3

**Comment by wmertens** [comment]
It does work when doing `--shamefully-flatten`, which is good news I suppose, but of course Jest should be fixed to work with hierarchical modules.

**Comment by wmertens** [comment]
Jest works now, v23.6.0

**Comment by zkochan** [comment]
Cool!

**Comment by KSXGitHub** [comment]
@wmertens It works even without `--shamefully-flatten`?

**Comment by wmertens** [comment]
@KSXGitHub 	Yes! And if you want to use Babel 7 you need to override the dependencies as I explain in #1475

**Comment by mudlabs** [comment]
@wmertens I still get error with `v23.6.0`

```console
Cannot find module 'jest-environment-jsdom'
at node_modules/.registry.npmjs.org/jest-runner/23.6.0/node_modules/jest-runner/build/run_test.js:39:29
```

**Comment by saritvakrat** [comment]
I stil get an error jest 29.3.1

**Comment by behnamazimi** [comment]
Same here, jest v29.7.0

**Comment by lucas-reap-hk** [comment]
Same here, jest v29.7.0
