### ISSUE TITLE
Feature: interactive update

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1012]
It might be useful to support `-i` flag for `pnpm update`. Similar to `npm-check`.

**Comment by matt3224** [comment]
Any news on this feature, pnpm doesnt seem to gel with npm-check despite my many attempts.

This is something that i would use daily too!

**Comment by zkochan** [comment]
Actually, I created a PR to npm-check: https://github.com/dylang/npm-check/pull/294

I would love this feature but I won't be able to work on it in the near future. I currently concentrate my work on making pnpm the best pm for monorepos.

**Comment by ExE-Boss** [comment]
**Yarn** supports this: https://yarnpkg.com/en/docs/cli/upgrade-interactive

**Comment by shirshak55** [comment]
Yes it would be great if we have interactive upgrade that updates package.json file also.

**Comment by Bessonov** [comment]
From my point of view it is one of most important features. For example, I use canary version of micro and therefore cant't update it to the latest:

```
$ pnpm outdated
┌───────────────────┬────────────────┬────────┐
│ Package           │ Current        │ Latest │
├───────────────────┼────────────────┼────────┤
│ micro (dev)       │ 9.3.5-canary.3 │ 9.3.4  │
└───────────────────┴────────────────┴────────┘
```

Yarn does it in very handy way, especially for monorepos.

**Comment by ExE-Boss** [comment]
@Bessonov That’s #2101

**Comment by Bessonov** [comment]
@ExE-Boss it just an example. We have often some dependencies, which we don't want update to the latest. Most notably are plugin-able tools like webpack. It takes days or months until plugin authors support the new version. Therefore an interactive update is a time saver for us.

**Comment by Bessonov** [comment]
While support same way like yarn it does would be perfect, I think [npm-check](https://www.npmjs.com/package/npm-check) could be a short-cut instead of own implementation: https://github.com/pnpm/pnpm/issues/2110#issuecomment-546075560

**Comment by zkochan** [comment]
Unfortunately, the creator of npm-check has switched to Yarn and doesn't support the lib anymore. So we have to either fork it or do our own thing

**Comment by matt3224** [comment]
It would be great to do this in pnpm directly, i use npm-check everyday and would love to have it all handled in a single place

**Comment by zkochan** [comment]
At first, I thought that I can just combine the outdated command and the update command to do this. It appears that `yarn upgrade-interactive` respects the specs in `package.json` (when not used with `--latest`). So seems like we should add `--latest` support for the outdated command. Of course, it will be `true` by default but it'll be possible to do `pnpm outdated --no-latest` or something similar (`--respect-specs` maybe).

I wonder if this should be a separate plugin or part of `@pnpm/plugin-commands-installation`. If it will be executed through `pnpm update -i` then it will have to be part of `plugin-commands-installation`, which is probably fine.

**Comment by zkochan** [comment]
:ship: 4.8.0-0

```
pnpm update --interactive [--recursive] [--latest] [--prod] [--dev]
```
