### ISSUE TITLE
Duplicate downloads/logging for identical package?

### ISSUE THREAD

**Issue by nickpape-msft** [pnpm/pnpm#1013]
### Code to reproduce the issue:

Not quite sure, we have a pretty massive package.json

### Expected behavior:

Package is only downloaded once, and is only logged once.

### Actual behavior:

Package appears to be downloaded twice? This doesn't really make sense since a single version of a package is only installed once (in the store).

### Additional information:

![image](https://user-images.githubusercontent.com/17131271/35301646-f062463c-0040-11e8-98ec-5bce2f021ba2.png)

 - `node -v` prints: 6.10.2
 - Windows, OS X, or Linux?: Windows

**Comment by etamponi** [comment]
I am pretty sure this is a problem with the default logger, the package is not actually downloaded twice. To double check, can you try installing with `--reporter append-only`? You should only see one message per package (perhaps split into started/downloading/done).

**Comment by zkochan** [comment]
Sometimes fetching fails and the package is re-downloaded. It confuses the reporter because the `fetching_started` is logged twice for the same package

**Comment by zkochan** [comment]
:ship: [1.35.8](https://github.com/pnpm/pnpm/releases/tag/v1.35.8)
