### ISSUE TITLE
pnpm has too high of a refresh rate, may be a perf issue

### ISSUE THREAD

**Issue by nickpape-msft** [pnpm/pnpm#1017]
### Code to reproduce the issue:

Install a lot of dependencies (especially ones that have a redirect and are very large).

### Expected behavior:

pnpm smoothly updates with progress every second or so.

### Actual behavior:

pnpm causes a ton of flickering because it updates the screen extremely often. Not only does this look bad, it may also be a perf problem.

![image](https://user-images.githubusercontent.com/17131271/35423232-a5a00464-0201-11e8-9edc-4a537bb00989.png)

![image](https://user-images.githubusercontent.com/17131271/35423243-ae34284e-0201-11e8-8e98-b567631771b9.png)

![image](https://user-images.githubusercontent.com/17131271/35423247-b3fe1b68-0201-11e8-8731-d09650326446.png)

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
We can use throttle to make fewer updates in the terminal.
Also, we can use [my fork](https://github.com/sindresorhus/log-update/pull/27) to log-update for reducing flickering

**Comment by zkochan** [comment]
🚢 [1.32.0](https://github.com/pnpm/pnpm/releases/tag/v1.32.0)
