### ISSUE TITLE
What's with the name?

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1019]
Now I have been using PNPM far too much & I love how it saves disk space since I work on too many projects & `node_modules` consumes too much space. 

Thanks to `pnpm`, it saved my space a lot. 

But whats with the name? How did you come up with it?

**Comment by zkochan** [comment]
@rstacruz came up with the name. It means "performant npm"

**Comment by deadcoder0904** [comment]
Cool
