### ISSUE TITLE
Feature Request: Show time required to finish

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1021]
Like `npm` prints time at the end of `npm install`, it would be cool to see how much time `pnpm` requires to finish

**Comment by zkochan** [comment]
I wonder if it makes sense to print the time if it was faster than 2-3
seconds?

**Comment by DanielRuf** [comment]
> I wonder if it makes sense to print the time if it was faster than 2-3

For me it is always useful and any information about this is crucial to know if there are too many packages or any issues and I just see it after switching to the tab. So I can also compare the results with and without filled cache.

**Comment by deadcoder0904** [comment]
I think you should show if its more than a second so as to not deter UX but also people care about seconds now

You see all those Twitter threads where people complaining VSCode opens up slow (it only takes 3-5 seconds) 😂 so you get the point, people care if anything greater than a second. Still it wouldn't hurt if you show in decimal point like 3.5s or 0.7s

**Comment by DanielRuf** [comment]
> I think you should show if its more than a second so as to not deter UX but also people care about seconds now
> 
> You see all those Twitter threads where people complaining VSCode opens up slow (it only takes 3-5 seconds) 😂 so you get the point, people care if anything greater than a second. Still it wouldn't hurt if you show in decimal point like 3.5s or 0.7s

Especially WPO. Everything above 1s, especially 2-5 seconds feels like there is something happening (perceived performance and so on).

Definitely useful if more than 1 second.

**Comment by zkochan** [comment]
ok then. If it is more than 1 second, it will be printed out. Seems like it will take less than a second only when everything is up-to-date (https://github.com/pnpm/node-package-manager-benchmark)

**Comment by shellscape** [comment]
Ran into needing this today. Subtask times would also be useful. We're measuring metrics of different deployment methods today.

**Comment by cat-walk** [comment]
Hope for support, it has been 4 years...

**Comment by shellscape** [comment]
@zkochan how heavy a lift would this be to implement? If you can point me in the right direction, I can try adding it

**Comment by zkochan** [comment]
Here is a PR: https://github.com/pnpm/pnpm/pull/5468

**Comment by shellscape** [comment]
@zkochan would adding `run` here (https://github.com/pnpm/pnpm/pull/5468/files#diff-21662b58f1e2bb7d4b341b32cf53f0420886668b78f2c19a5a8bd8e56dc3fd9aR27) allow the same output for `pnpm run X`? at the moment we've got `time` littered all over our package scripts, would be happy to submit a PR to add that.

side question: what would be the proper place to add this for `pre` and `post` scripts with the `enable-pre-post-scripts` setting enabled?

**Comment by matthew-dean** [comment]
I would love to see this added to `run`

**Comment by matthew-dean** [comment]
@shellscape I wish you had mentioned what tool you use to time scripts 😢

**Comment by shellscape** [comment]
the bash `time` command

**Comment by matthew-dean** [comment]
@shellscape Thanks! I found it after trying for a long time to find an NPM script and then eventually presuming their must be something built-in if no one had solved in in the module space.

**Comment by magoz** [comment]
Showing execution time for `run` would be awesome. Any chance of this happening, @zkochan?

**Comment by zkochan** [comment]
I am not sure it is a good idea because the output of the script may be analysed by some tools.
