### ISSUE TITLE
Add a FAQ: Doesn't work with X

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1022]
I've submitted 2 issues (#940 & #991) myself & someone posted #968 that has same problem, so rather than explaining it everytime, users can be directed to this FAQ. 

Currently `parcel`, `gatsby` & `create-react-native-app` (got solution for `create-react-native-app` in #940) doesn't work with this AFAIK.

The solution must provide steps on how to add a hook file `pnpmfile.js` & debugging process for the packages that need to be added. 

@zkochan what do you think? This will help me embrace `pnpm` completely rather than switching between `npm` & `yarn` & I think many will find this useful.

**Comment by zkochan** [comment]
If someone wants to document it, I have no objections

**Comment by deadcoder0904** [comment]
I can't do it myself as I get issues myself when I debug & I think you might be the best person for the job. Idk who else is on the core team though & if they know how to debug. Sorry, if its a lot to ask. But as much as I start adding dependencies to my project using `pnpm`, there is always this same error which I try to figure it out but then give up because it doesn't work & switch back to `yarn` again

**Comment by zkochan** [comment]
So basically what you ask for is, some know-hows about how to investigate issues when something does not work with pnpm. Maybe also examples of workarounds.

I can do that.

**Comment by deadcoder0904** [comment]
Yes rather than telling it to everyone everytime, a simple FAQ will do. Literally check my issues, its all the same for different projects. Just teach us how to debug & I think this is the final nail in the coffin.

**Comment by zkochan** [comment]
@deadcoder0904 in [pnpm@1.34.0](https://github.com/pnpm/pnpm/releases/tag/v1.34.0) a new flag was added to pnpm called `--shamefully-flatten`. When used, pnpm will create a flat `node_modules`

**Comment by x8x** [comment]
```
git clone https://github.com/MyCryptoHQ/MyCrypto
cd MyCrypto
pnpm i
npm run build
```
last command fails, works fine if install is run with `npm i` or `pnpm --shamefully-flatten i`

**Comment by x8x** [comment]
```
npm install -g vue-cli
vue init nuxt-community/starter-template test
cd test
npm run dev
```
last command fails, works fine if install is run with npm i or pnpm --shamefully-flatten i

**Comment by deadcoder0904** [comment]
Hey @x8x did you try adding `hooks` with `pnpmfile.js`❓

It should have a structure like https://github.com/pnpm/pnpm/issues/1043#issuecomment-365409320 & how will you find dependencies is given at https://github.com/pnpm/pnpm/issues/1043#issuecomment-365710275

So read the thread https://github.com/pnpm/pnpm/issues/1043 & I think you will find the solution & if not, then create a new issue 😃

I will send a PR for this question as a FAQ as it gets asked so many times

**Comment by deadcoder0904** [comment]
PR sent at #1059
