### ISSUE TITLE
shrinkwrap.yaml gets created when `package-lock=false` in `~/.npmrc`

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#1025]
### Code to reproduce the issue:

1. `echo "package-lock=false" >> ~/.npmrc`
2. `pnpm install` in a project without `node_modules` or `shrinkwrap.yaml`

### Expected behavior:

No `shrinkwrap.yaml` is created within the project directory.

### Actual behavior:

A `shrinkwrap.yaml` file is created in the project directory.

### Additional information:

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
That config is for directory locking. There is no config for not generating
shrinkwrap.yaml. just gitignore them if you don't want them in the repo

**Comment by jsumners** [comment]
I don't want the file at all.

**Comment by jsumners** [comment]
Just went to look at the code to investigate fixing this myself. Unfortunately I'm not a TS person.

**Comment by zkochan** [comment]
We can have such config but the name should be different. `lock` is currently used for store/project directory locking (https://pnpm.js.org/docs/usage/configuring.html#lock)

yarn has `--no-lockfile`, npm has `--no-package-lock`/`--no-shrinkwrap`

we can have `--no-shrinkwrap` as well

**Comment by jsumners** [comment]
In my `~/.npmrc` I have `package-lock=false` that disables npm from looking for, or creating, a lock file.

**Comment by zkochan** [comment]
🚢 [1.32.0](https://github.com/pnpm/pnpm/releases/tag/v1.32.0)

**Comment by jsumners** [comment]
Excellent. Thank you for implementing this.
