### ISSUE TITLE
Cannot install global dependencies with multiple drives mounted.

### ISSUE THREAD

**Issue by ckiee** [pnpm/pnpm#1026]
### pnpm version:
1.3 (it printed "1.31.3" for some reason)
### How to reproduce:
Run `pnpm i -g` with / mounted on one drive and /home on another drive. 
### Expected behavior:
It updates all of the globally installed deps.
### Actual behavior:
![This error](https://i.ronthecookie.me/1F5Pvun.png)
### Additional information:

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: Linux (Ubuntu)

**Comment by zkochan** [comment]
This was fixed.
