### ISSUE TITLE
feat: preferring local packages when installing inside a monorepo

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1027]
This is a follow-up to #825, cc @paulpflug 

With [pnpm@1.32.0](https://github.com/pnpm/pnpm/releases/tag/v1.32.0) `pnpm recursive link` was published, which is good for installing dependencies in a monorepo.

However, when doing installation in one of the packages of the monorepo, dependencies will be installed from the registry, not linked from the monorepo.

The solution might be to keep an index of the locally available packages. A new config can be added (called `prefer-local`). If the config is `true`, locally available packages are linked during installation. The packages that are not available locally are downloaded from the registry.

**Comment by zkochan** [comment]
I mean, if there is a multi-package repo like this:

```
packages
+- foo
+- bar
```

and you cd to `packages/foo` then when you do `pnpm install bar` inside `foo`, `bar` will be downloaded from the registry. The expected result would be to link bar from `packages/bar` to `packages/foo/node_modules/bar`

**Comment by vjpr** [comment]
> The expected result would be to link bar from `packages/bar` to `packages/foo/node_modules/bar`

Not so sure I would expect this, without explicitly using a flag such as `--link`. This is what the `lerna bootstrap` command takes care of when run at the project root. 

`yarn` I think might do this automatically if workspaces config is present.

**Comment by zkochan** [comment]
but in a multi-package repo you always want to use the package from the repo, right? Currently, to do it, you'd need to manually edit the `package.json` of `foo` and then run `pnpm recursive link` in the root of the repo.

**Comment by vjpr** [comment]
At present with lerna, I have to run `lerna add bar --scope=foo`. This is not such an issue.

**Comment by zkochan** [comment]
I agree it should be explicit.

So maybe it can be a new option. Like `pnpm install bar --prefer-local`

additionally, if you run install in a monorepo w/o this flag, a warning can be printed. Something like:

`WARN: foo is being installed from the registry although it is available locally at packages/foo
To link the local version, run install with the --prefer-local flag`

**Comment by zkochan** [comment]
After thinking about it more. It seems like the `link` command would be a better place to implement this.

Two things should be done:

1. `pnpm link foo` should look for `foo` inside the monorepo, before searching it in the global packages
2. `pnpm link foo -S` should add `foo` to `package.json` as a semver dependency (ref #871). Maybe it should work only if the package is from the same monorepo.

**Comment by nionis** [comment]
Looking forward to this feature, properly and deterministic managing monorepos using npm / yarn is not possible, with pnpm node_modules structure it makes it possible.

**Comment by donaldpipowitch** [comment]
Follow up from https://github.com/pnpm/pnpm/issues/1253:

I really would like to set some `prefer-local true` flag in some `pnpmfile.js`/`.pnpmrc`/whatever per project to use `pnpm recursive install` instead of `pnpm recursive link` to link local packages, but install everything else.

Goals:
- We have several monorepos and non-monorepos and several developers who only occasionally need to run/build one of these projects. I'd like to tell them to only use `pnpm recursive install` for all projects instead of per project.
- Ease the migration from yarn (where `yarn install` already prefers local packages in workspaces).
- Do not confuse it with `yarn/npm/pnpm link` where the current package is linked to the global folder. (One could think `pnpm recursive link` will link every local package to the global folder.)

(While writing this I wonder, if `prefer-recursive` would make sense as well 🤔So `pnpm install` would be `recursive` in the monorepo root, but not in a leaf package.)

**Comment by zkochan** [comment]
> I really would like to set some prefer-local true flag in some pnpmfile.js/.pnpmrc/whatever per project to use pnpm recursive install instead of pnpm recursive link to link local packages, but install everything else.

Sounds good

> One could think pnpm recursive link will link every local package to the global folder.

Good point. Somehow I did not think about it in the past. Maybe we'll have to change this.

> While writing this I wonder, if prefer-recursive would make sense as well thinkingSo pnpm install would be recursive in the monorepo root, but not in a leaf package. But this is as different topic.

I think I like this idea. A config like `prefer-recursive` could be specified in an `.npmrc` in the root of the repo.

**Comment by vjpr** [comment]
> Good point. Somehow I did not think about it in the past. Maybe we'll have to change this.

Tricky to find a good command name. `pnpm multi link-local` is more accurate and unambiguous.

**Comment by zkochan** [comment]
`prefer-local` might be a bit too vague. Maybe a more specific config should be used. Like `prefer-packages-from-workspace`

**Comment by zkochan** [comment]
> While writing this I wonder, if prefer-recursive would make sense as well thinkingSo pnpm install would be recursive in the monorepo root, but not in a leaf package. But this is as different topic.

after thinking about it more. I don't know if this would work. We have many recursive commands and it might cause confusion.

For instance, if you have a `package.json` in the root of your monorepo, you may want to list all of its dependencies. Currently, you can run `pnpm list` to do that. But with this option, `pnpm list` will behave like `pnpm recursive list`, so `pnpm list` will list dependencies of every package in the monorepo.

**Comment by donaldpipowitch** [comment]
Amazing!😍

**Comment by donaldpipowitch** [comment]
Can you explain how this works now? Was it solved via a command now instead of a preference in some config file? Thank you and have a nice day 😊

**Comment by zkochan** [comment]
Check it here https://pnpm.js.org/docs/en/workspace.html
