### ISSUE TITLE
Getting rid of drivelist

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1036]
pnpm has one native dependency - [drivelist](https://www.npmjs.com/package/drivelist). It is a great package that allows detecting all the disks on a machine. However, because it is native, it makes a lot of issues during pnpm's installation.

**Comment by pgonzal** [comment]
Just curious -- why does PNPM need to enumerate the disks?

**Comment by zkochan** [comment]
See related issue #712
