### ISSUE TITLE
pnpm install is replacing existing packages in node_modules

### ISSUE THREAD

**Issue by HarshulSharma000** [pnpm/pnpm#1037]
### Code to reproduce the issue:
pnpm install --no-lock
pnpm install --no-lock wordwrap(any indivisual package)

### Expected behavior:
Only a new package(wordwrap here) should have been installed along with other packages already present in node_modules.
### Actual behavior:
The newly installing package is installed but all the previous packages are removed from the project .
### Additional information:
OS: Windows 10
Node: 9.4.0
Yarn: 1.4.0
npm: 4.6.1
Watchman: 4.9.1

**Comment by zkochan** [comment]
Do you have `package-lock=false` or `shrinkwrap=false`? This might be the same issue as #1029

**Comment by HarshulSharma000** [comment]
Actually I install with --no-lock flag since I get the error unable to lock within stale threshold.

**Comment by zkochan** [comment]
no-lock is not the same as no-package-lock/no-shrinkwrap. #1029 had a bad title. The issue there is because of `no-shrinkwrap` not because of `no-lock`.

Could you check the value of those two configs in your project?

`npm get shrinkwrap`

and

`npm get package-lock`

**Comment by HarshulSharma000** [comment]
Yes both are returning true 
By the way something weird is occuring getting this error
Error: Cannot find module 'C:\Program Files\nodejs\pnpm-global\1\node_modules\pnpm\lib\bin\pnpm.js'
tried deleting npm cache, reinstalling pnpm. But folder is not generating.

**Comment by zkochan** [comment]
I don't think this error exists in the latest pnpm.
