### ISSUE TITLE
During named install, update all usages of the package

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1041]
Lets' say a project has this dependency graph:

```
dependencies:
a -> b@1.0.0
b@1.0.0
```

as of `pnpm@1.32`, `pnpm install b@1.1.0` will result in this graph:

```
dependencies:
a -> b@1.0.0
b@1.1.0
```

b will be updated only in the root.

Expected behavior: b should be deduplicated during the update. So the new graph should be

```
dependencies:
a -> b@1.1.0
b@1.1.0
```

**Comment by Djaler** [comment]
This is still relevant on pnpm 5.0.2
duplicate-package-checker-webpack-plugin always find and error because of this
