### ISSUE TITLE
Allow disabling of the "Strict." behavior... Causes problems with ESLint (and not only).

### ISSUE THREAD

**Issue by olstenlarck** [pnpm/pnpm#1042]
### pnpm version:

latest

### Additional information:

 - `node -v` prints: 8.9.4, but it is no matter, problem is always
 - Windows, OS X, or Linux?: Linux, ofc. ArchLinux

Currently, because it is "Strict" we have problems using AirBnb (it will for anything other than that). The problem is that ESLint throws error that it can't load the `eslint-import-resolver-node` which is actually dependency of `eslint-plugin-import`. 

No, it's not a problem with AirBnB. And yes, it works with Yarn/npm. And no, it is not the only issue that i had last few days (and will have such issue if i start using Pnpm), exactly because that "Strict" thing.

**Comment by zkochan** [comment]
Here's the related issue at `eslint-plugin-import`: https://github.com/benmosher/eslint-plugin-import/issues/828

They admit that it is an issue on their end and they'd accept a PR

**Comment by olstenlarck** [comment]
Yup, currently, installing the resolver where installing the import plugin, it works.

I pray for new release of `eslint-plugin-import` as soon as possible, because last is very old (october).

**Comment by olstenlarck** [comment]
It's not the only issue.

Installing and using `babel-eslint`, it reports that it can't find `estraverse` module, which is dependency of `babel-eslint`..

**Comment by zkochan** [comment]
@olstenlarck in [v1.34.0](https://github.com/pnpm/pnpm/releases/tag/v1.34.0) there is now a flag called `--shamefully-flatten`

**Comment by olstenlarck** [comment]
Cool, will try it. ;]

**Comment by olstenlarck** [comment]
And yea. After few months, i got to this again.

Shamefully flatten isn't really a good way to go. Can you think for something that fixes this problem with ESLint, specifically?

I really won't go using shamefully flatten, only because my flow requires ESLint... that's ridiculous?

**Comment by olstenlarck** [comment]
Or at least, is there possibility to add `shamefully-flatten` option to some config file? global `npmrc` or local, or some specific pnpm config?

It would be `shamefully-ridiculous` ;d if i should add it to every command or force my contributors to do that.

**Comment by olstenlarck** [comment]
The problem. It's pretty easy.

You have package that has `eslint` and some config as devDependencies, and eslint just could not find some of the deps which are included in the config (usually some other configs and plugins).

**Comment by olstenlarck** [comment]
Oookey, that sounds good, i'll try it.
