### ISSUE TITLE
Not working with Webpack Dashboard

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1043]
### Expected behavior:

Webpack Dashboard must work

### Actual behavior:

Webpack Dashboard does not work

### Additional information:

 - `node -v` prints: v9.5.0
 - Windows, OS X, or Linux?: OS X High Sierra 10.13.3

### Things that I tried doing

After running I got error - 

```
Error: Cannot find module 'babel-traverse'
```

so I created `pnpmfile.js` with following contents - 

```js
"use strict";
module.exports = {
  hooks: {
    readPackage
  }
};

function readPackage(pkg) {
  if (pkg.name === "webpack-dashboard") {
    Object.assign(pkg.dependencies, {
      "babel-traverse": "6"
    });
  }
  return pkg;
}
```

But it still throws error. Also this time, the dependency `babel-traverse` exists in the `package.json`

Also take a look at #1022 if you haven't already as it will reduce huge number of issues & save me & others a ton of disk space 😉 otherwise I have to keep deleting projects after completing 😂

**Comment by deadcoder0904** [comment]
For now I am using [Jarvis](https://github.com/zouhir/jarvis) which works perfectly fine with `pnpm` but its in the browser whereas [Webpack Dashboard](https://github.com/FormidableLabs/webpack-dashboard) is in the Command Line.

**Comment by deadcoder0904** [comment]
Yep I'll put it on Github

**Comment by deadcoder0904** [comment]
I just made one with the tiniest configuration 👉 https://github.com/deadcoder0904/webpack-pnpm

After installing, just run `pnpm start`

**Comment by zkochan** [comment]
this hook seems to help:

```js
module.exports = {
  hooks: {
    readPackage (pkg) {
      if (pkg.name === 'inspectpack') {
        pkg.dependencies['babel-traverse'] = '^6.26.0'
      }
      return pkg
    }
  }
}
```

**Comment by zkochan** [comment]
inspectpack should add babel-traverse to its package.json because it is used here 

https://github.com/FormidableLabs/inspectpack/blob/1fa1c0f7052e28e61d4ac8448234e9d34516124a/lib/actions/parse.js#L6

**Comment by deadcoder0904** [comment]
Ahh, so you basically traverse all the code or is there a script that finds `packages` that are not in `package.json` ?

**Comment by deadcoder0904** [comment]
It works now without `pnpmfile.js`. Zoltan can you answer the above question?

**Comment by zkochan** [comment]
> So you basically traverse all the code or is there a script that finds packages that are not in package.json ?

there is no such script. I wanted to make one but didn't finish it yet. Here's the code: https://github.com/pnpm/node-modules-check

it is not hard to find these errors when code fails. Basically there was an error message like this:

```
Error: Cannot find module 'babel-traverse'
  at /node_modules/.registry.npmjs.org/inspectpack/2.2.3/node_modules/inspectpack/lib/actions/parse
```
