### ISSUE TITLE
Different behavior across package managers when no `package.json` present

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1049]
`yarn add glob` - adds to ~/.quokka/package.json.
`pnpm install glob` - fails if there is not a `package.json` in the data dir.
`npm install glob` - installs into data dir and creates `package-lock.json` in the data dir but no `package.json`.

I came across this here: https://github.com/wallabyjs/quokka/issues/160

To fix my issue Quokka needs to make its behavior more consistent.

But still, this difference might impact other usages of pnpm.

**Comment by zkochan** [comment]
I like the way Yarn does it. We can do the same in pnpm. Creating a package.json file and a shrinkwrap.yaml file

**Comment by zkochan** [comment]
:ship: `1.35.3`
