### ISSUE TITLE
Files within node_modules are not accessible

### ISSUE THREAD

**Issue by HarshulSharma000** [pnpm/pnpm#1051]
### pnpm version:
1.35(including 1.33.0 and above)

### Code to reproduce the issue:
Simply install node_modules within **Windows** and use some file within node modules in the project. 

Or try to create an expo(react native) project because it loads its main file(as specified within package.json) from node_modules, which is not found as mentioned including axios, babel and other packages.

### Expected behavior:
Files should have been imported as usual without any problems.

### Actual behavior:
Files are shown within explorer(as shortcuts of course) and within editor (vscode) project folder also. But they are not found when they are used within project. Might be that either nodejs or npm scripts or maybe some js runtime is not able to load them. 

The above mentioned problem does not appear when installing with yarn or npm. 

Looks like there is some problem with pnpm's linking.

**Note-** I am using an external store within E: drive and referencing it via a .npmrc file since the normal way was giving errors.

### Additional information:

 OS: Windows 10
  Node: 8.9.4
  npm: 4.6.1
  pnpm: 1.35
  Watchman: 4.9.1
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

### Images

![image](https://user-images.githubusercontent.com/25546227/36440313-771eb36c-1695-11e8-8e1e-330b95063a06.png)

#### Files
[package.zip](https://github.com/pnpm/pnpm/files/1756605/package.zip)

**Comment by etamponi** [comment]
Hi! pnpm 1.34.0 has a new experimental flag `--shamefully-flatten`, which emulates what npm and yarn do with dependencies, that might solve your issue.

So try to update to 1.34.0 and run `pnpm install --shamefully-flatten`.

**Comment by HarshulSharma000** [comment]
@etamponi Still no benefit, tried using shamefully-flatten flag, setting shamefully-flatten=true in .npmrc file. Still it is not able to find modules within node_modules. I tried several times and in one install I found several relinking going on but still not benefit.

One more thing I use pnpm with --no-lock flag since it is not able to lock within stale threshold so I tried removing it, switching it's position with --shamefully-flatten yet nothing changed. Although what I noticed was --no-lock operation also somewhat broke when used with --shamefully-flatten because it may give unable to lock error at once but then using same command again might fix it.

**Comment by HarshulSharma000** [comment]
**Update:** Upgraded to pnpm: 1.35 got install completing successfully but watchman(facebook's file watcher) is giving strange, permissions and not able to read sort of erros and also. On trying to on project with expo cli it gives entry file not found error. Yarn and npm seem to work fine.

Also added package.json file to text install exp npm package and enter 'exp start' within project directory.

**Comment by vjpr** [comment]
@HarshulSharma000 `react-native` doesn't support symlinks. `--shamefully-flatten` still uses symlinks so it doesn't solve the problem.

Its a long outstanding request that `react-native` support symlinks, but it doesn't look like they will for a while.

This is why I suggested having a `--no-symlink` pnpm option on Gitter.

**Comment by etamponi** [comment]
@vjpr can you show me some issue or relevant documentation on why `react-native` doesn't support symlinks? I would like to investigate a bit! Thanks!

**Comment by vjpr** [comment]
@etamponi See https://github.com/facebook/react-native/issues/18156

There are some links to issues in react-native there.

**Comment by vjpr** [comment]
@etamponi Did you make any progress on this. I was thinking of taking another stab at it soon.

**Comment by etamponi** [comment]
Unfortunately I didn't have the time to dig into it, so feel free to go :)

Il mar 13 mar 2018, 15:47 Vaughan Rouesnel <notifications@github.com> ha
scritto:

**Comment by vjpr** [comment]
I traced the point at which it fails to locate modules to `metro-resolver` > `resolveSourceFileForExt`

https://github.com/facebook/metro/blob/cf5a431388bded8f47d560528175a43dd89fba13/packages/metro-resolver/src/resolve.js#L449

```js
const filePath = `${context.filePathPrefix}${extension}`;
console.log({filePath, exists: require('fs').existsSync(filePath)})
if (context.doesFileExist(filePath)) { // Returns false for files which exist on disk.
  return filePath;
}
```

**`context.doesFileExist.toString()`**

```js
filePath => {
  return this._hasteFS.exists(filePath);
}
```

So `this._hasteFS` isn't aware of symlinked files.

The question is how difficult it is to make it aware. Feels like it can't be easy or someone would have already done it.

I will try briefly...

**Comment by zkochan** [comment]
Looks resolved.

In worst case, use the [`node-linker=hoisted`](https://pnpm.io/npmrc#node-linker) setting
