### ISSUE TITLE
PNPM update fails at times

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1052]
I've tried this before too while updating `pnpm` so this is an issue.

I am on version `1.31.6` & it prompted me to install a new version `1.33.2` which was published yesterday.

But when I try `npm i -g pnpm` or `pnpm i -g pnpm` it doesn't do anything 😭

Here's the output of `pnpm i -g pnpm` 👇

```console
WARN  The store is not on the same device on which the installation is done. Store is on /dev/disk0, device is on /dev/disk1
Resolving: total 1, reused 0, downloaded 0
```

I also tried `pnpm i -g pnpm@1.33.2` but it still gives the same message as above 👆

I don't know if its `npm` problem or `pnpm` but it doesn't update as I'm still on `1.31.6` rather than `1.33.2` as it was published yesterday & I was prompted to install that when I typed `pnpm start` to run my program

**Comment by deadcoder0904** [comment]
I tried `npm r -g pnpm` & `npm i -g pnpm` too but it still installs `1.31.6`

**Comment by zkochan** [comment]
Have you tried the standalone script?

```
curl -L https://unpkg.com/@pnpm/self-installer | node
```

**Comment by deadcoder0904** [comment]
Wait I'll try

**Comment by deadcoder0904** [comment]
But it still gives `pnpm -v` to `1.31.6`. Not sure what is the problem❓

**Comment by zkochan** [comment]
can you check what location pnpm is currently executed from? I mean, the `1.31.6` version. Then you could either manually remove it from there or specify `PNPM_BIN_DEST` for `@pnpm/self-installer`.

```
curl -L https://unpkg.com/@pnpm/self-installer | PNPM_BIN_DEST=/current-pnpm-bin-location node
```

**Comment by deadcoder0904** [comment]
`which pnpm` gives `/usr/local/bin/pnpm`

**Comment by zkochan** [comment]
We don't need a new command. We already have `pnpm i -g pnpm`. It should just be fixed.

Initially, do you remember how you installed the previous version of pnpm?

**Comment by zkochan** [comment]
@deadcoder0904 `which node` on your machine returns `/usr/local/bin/node`, right?

We currently use `process.execPath` as the target of the pnpm bin. As far as I understand, from the npm repo, they rewrite `process.execPath` with the location of Node.

https://github.com/npm/npm/blob/5e426a78ca02d0044f8dd26e0c5f881217081cbd/lib/npm.js#L252

That is probably what we have to do as well

**Comment by deadcoder0904** [comment]
> Initially, do you remember how you installed the previous version of pnpm?

Well, it depends bcz I have installed `pnpm` multiple times just for fun 😜

So I have used `self-installer` & `npm i -g pnpm`. Nowadays its `self-installer`.

> `which node` on your machine returns `/usr/local/bin/node`, right?

Yes

**Comment by deadcoder0904** [comment]
Confirming yet again it fails for the new `1.35.1` too when I do `pnpm -v` it gives `1.33.2`

Output after doing `pnpm i -g pnpm`

```console
➜  ~ pnpm i -g pnpm
Packages: -1 +1
-+
Downloading registry.npmjs.org/pnpm/1.35.1: 6.55 MB/6.55 MB, done
Resolving: total 1, reused 0, downloaded 1, done
 WARN  EXDEV: cross-device link not permitted, link '/Volumes/Coding/.pnpm-store/2/registry.npmjs.org/pnpm/1.35.1/node_modules/pnpm/LICENSE' -> '/usr/local/Cellar/node/9.5.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/1.35.1/node_modules/_tmp_4667_9c2156c72072c8d734eaee3f5267abeb/LICENSE'
Falling back to copying packages from store
dependencies:
- pnpm 1.33.2
+ pnpm 1.35.1
```

**Comment by zkochan** [comment]
the standalone script should work now

`pnpm i -g pnpm` not fixed yet

**Comment by zkochan** [comment]
The fix has been published with `pnpm@1.35.6`. So when you'll have a version `>=1.35.6` you should be able to update pnpm to the next version. I guess you could test it earlier by downgrading pnpm from `v1.35.6`

**Comment by deadcoder0904** [comment]
Nope its not working.

I did the following - 

```console
npm r -g pnpm
npm i -g pnpm@1.35.6
pnpm -v 
# 1.35.6
pnpm i -g pnpm@1.35.2
pnpm -v
# 1.35.6
```

**Comment by zkochan** [comment]
what does `which pnpm` return?

**Comment by deadcoder0904** [comment]
`/usr/local/bin/pnpm`

**Comment by zkochan** [comment]
and what is the content of `/usr/local/bin/pnpm`?

**Comment by deadcoder0904** [comment]
Its not a directory. Its an executable.

**Comment by zkochan** [comment]
yes, and it should contain a reference to the globally installed pnpm. What is the content of the executable?

**Comment by deadcoder0904** [comment]
```console
➜  ~ ls -al /usr/local/bin/pnp*
lrwxr-xr-x  1 deadcoder0904  admin   40 Mar  8 12:39 /usr/local/bin/pnpm -> ../lib/node_modules/pnpm/lib/bin/pnpm.js
-rwxr-xr-x  1 deadcoder0904  admin  258 Feb 21 19:23 /usr/local/bin/pnpm.cmd
lrwxr-xr-x  1 deadcoder0904  admin   40 Mar  8 12:39 /usr/local/bin/pnpx -> ../lib/node_modules/pnpm/lib/bin/pnpx.js
-rwxr-xr-x  1 deadcoder0904  admin  258 Feb 21 19:23 /usr/local/bin/pnpx.cmd
➜  ~
```

**Comment by deadcoder0904** [comment]
> What is the content of the executable?

How to get that?

**Comment by zkochan** [comment]
I see, so it is a symlink executable. Thanks, it helped. I'll look into it

**Comment by deadcoder0904** [comment]
Any updates on this? 

The release cycle of `pnpm` is so fast that I would prefer this to work. Rather than uninstalling & installing again :)

**Comment by deadcoder0904** [comment]
Yo @zkochan I currently uninstall & install everytime I get a notification about new release. But today after I installed new version 2.10.3 then I still got a notification to install a previous version as the latest version like 2.4.* something something so Idk if the `update-notifier` is working correctly. 

After that I didn't get a message like that. But I think this should be high priority as existing users have an issue updating `pnpm` or Idk if its just me LOL 😂

**Comment by zkochan** [comment]
I did a fix that might solve this: https://github.com/pnpm/pnpm/commit/e4b667e7fba5b190e232fb9db037d1d4b2eb99c3

That one is shipped in 5.2.3

And there's another one on review: https://github.com/pnpm/pnpm/pull/2637

It can be installed through `pnpm i -g pnpm@dev`

**Comment by zkochan** [comment]
This shouldn't happen in pnpm v7 anymore.

**Comment by vltansky** [comment]
Happening to me with pnpm v 7.27.0.

```
❯ pnpm -v
7.27.0

❯ pnpm i -g pnpm@latest
Packages: +1
+
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: .../Library/pnpm/store/v3
  Virtual store is at:             .pnpm

.../Library/pnpm/global/5:
+ pnpm 8.0.0

Progress: resolved 1, reused 0, downloaded 1, added 1, done
Done in 1.4s

❯ pnpm -v
7.27.0

❯ which pnpm
/usr/local/bin/pnpm
```

tried to uninstall with npm & pnpm. tried to install via corepack and curl. Didnt work


```
curl -L https://unpkg.com/@pnpm/self-installer | PNPM_BIN_DEST=/usr/local/bin node
❯ pnpm -v
8.0.0
```
worked for me.
