### ISSUE TITLE
Feature Request: Provide a way to configure how NPM is discovered

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#1053]
### Code to reproduce the issue:

Run a command such as `pnpm publish` which passes through to the NPM implementation.

### Expected behavior:

We should have some way to control *which* NPM implementation processes this command.

### Actual behavior:

PNPM invokes the globally installed NPM tool.  This causes nondeterministic behavior.

For example, in January I clone a specific Git branch, and I install a specific release of PNPM (e.g. as specified in [rush.json](https://github.com/Microsoft/web-build-tools/wiki/Rush-~-Setting-up-your-repo#step-1-create-rushjson)), and then I install everything from the shrinkwrap file, and build everything using only tooling specified in that shrinkwrap file.  Everything works great.  Then in February, I try to repeat this exact process, but the `pnpm publish` step now fails because the dev machine happens to have a different version of NPM installed.

### Additional information:

Maybe we could provide an environment variable or command-line switch that specifies the folder where NPM is installed.

(In an ideal world, we'd like to expunge all references to NPM from our ecosystem.  So it would be even better if PNPM could reimplement these commands or pass through to some alternative tool such as yarn.)

**Comment by zkochan** [comment]
:ship: 4.8.0-0
config setting: npm-path

https://github.com/pnpm/pnpm/pull/2275
