### ISSUE TITLE
Incremental installs seem to ignore "file://" dependencies

### ISSUE THREAD

**Issue by pgonzal** [pnpm/pnpm#1054]
### Code to reproduce the issue:

I have attached an archive [issue-1054.zip](https://github.com/pnpm/pnpm/files/1750155/issue-1054.zip) which repros the issue.  It's based on the way that the [Rush](https://aka.ms/rush) tool invokes PNPM for real world projects, using `file://` references like this:

```json
{
  "dependencies": {
    "@rush-temp/project-1": "file:./projects/project-1.tgz",
    "@types/adal": "^1.0.20",
    "adal-angular": "1.0.15"
  },
  "description": "Temporary file generated by the Rush tool",
  "name": "rush-common",
  "private": true,
  "version": "0.0.0"
}
```

The [issue-1054.zip](https://github.com/pnpm/pnpm/files/1750155/issue-1054.zip) archive contains three separate folders:

1. **step-1**: This shows a *package.json* and *project-1.tgz* which both refer to `adal-angular@1.0.15`.

2. **step-2**:  In this folder, the *package.json* and *project-1.tgz* files were updated to reference `adal-angular@1.0.16`.  The shrinkwrap file has not been upgraded yet.

3. **step-3**: This folder is a copy of **step-2** after running `pnpm install`.  Inspecting *shrinkwrap.yaml*, we see that *package.json* was upgraded to `adal-angular@1.0.16`, but *project-1.tgz* is incorrectly mapped to `adal-angular@1.0.15`.  Apparently PNPM ignored it.

> NOTE: We also observe that `"@types/adal": "^1.0.20"` remains on version 1.0.20, even though there is now a 1.0.26 available.  This is the desired behavior for that dependency.

### Expected behavior:

Expected:  In **step-3**, both  *package.json* and *project-1.tgz*  should have been upgraded to `adal-angular@1.0.16`. 

### Actual behavior:

Actual:  The SemVer constraint from *project-1.tgz*  was not solved correctly.

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by pgonzal** [comment]
@nickpape @zkochan FYI

**Comment by zkochan** [comment]
Thanks, @pgonzal, now it makes sense to me.

So seems like pnpm does not check whether the tarball has been modified and so does not try to update its dependency graph.

The solution should be probably to add the tarball's integrity to `shrinkwrap.yaml` and verify it on each install/update. If the shasum has changed, the dependency graph has to be updated.

**Comment by pgonzal** [comment]
If I remember right, @adisbladis was proposing something similar to add integrity checks for tarballs obtained from GitHub. If there is a separate issue for that, maybe they can be combined.

**Comment by zkochan** [comment]
Yes, [here](https://github.com/pnpm/pnpm/issues/1035). Lets' keep both though. The format in the shrinkwrap will be similar but the implementations will be different

**Comment by zkochan** [comment]
The implementation is a bit confusing to me but maybe its fine.

We store the integrity checksums in `resolution.integrity`, so for the local tarballs, I want to put the checksum there. However, the expected behavior for a checksum mismatch is currently an error.

For instance, if foo v1.0.0 was installed with integrity X and during installation it has integrity Y, installation fails.

For a local tarball though, an integrity mismatch will mean that the tarball should be re-installed and updated in the `shrinkwrap.yaml`

**Comment by pgonzal** [comment]
Makes sense to me. I'm not even sure it's necessary to track integrity for local files. For example if we regenerate a tarball with different but equivalent contents, should that really require churning the shrinkwrap file in Git?

This is related to my other philosophical question about the goal of shrinkwrap files beyond ensuring that installs produce deterministic outcomes.

**Comment by zkochan** [comment]
A repacked tarball with the same content would have a different integrity? I don't know how to solve that issue on pnpm side.

**Comment by pgonzal** [comment]
What is the problem we are solving? Integrity is for detecting corrupted downloads or a server that returns inconsistent output, which would be a concern for determinism or security. My point was just that these concerns may not apply to a local file, because local build operations usually are trusted and deterministic. (Although I'm not sure how other people are using tarballs - maybe their scenario is different.)

**Comment by zkochan** [comment]
yeah, I think this solution should be fine

we can also add a `--frozen-shrinkwrap` flag in the future that will fail installation if an update will be needed to `shrinkwrap.yaml` (similar to Yarn's `--frozen-lockfile`)

**Comment by pgonzal** [comment]
Cool, let me know when you publish something, and I'll try it out.  There is a Rush improvement waiting for this fix.

**Comment by zkochan** [comment]
It is harder than I initially thought but maybe it will be ready this week.

**Comment by pgonzal** [comment]
Interesting, so if the package.json file have changed, then pnpm will silently update the shrinkwrap.yaml file?  + @nickpape-msft FYI 

I guess that makes sense, but for Rush we definitely would want this `--frozen-shrinkwrap` behavior since our shrinkwrap.yaml is a generated copy.  @zkochan should we track that feature as a separate issue?

For issue #1054 I would be happy if PNPM simply ignored integrity completely for tarballs.

**Comment by zkochan** [comment]
yes, lets' make a separate one for `--frozen-shrinkwrap`.

The solution for this issue is the same as what we discussed above. It just required a little bit more changes than I expected. But it might be ready today :tada:

**Comment by zkochan** [comment]
:ship: `1.35.2`

**Comment by pgonzal** [comment]
Awesome, thanks! 😄

**Comment by pgonzal** [comment]
Confirmed that it works as expected.  Thanks again!
