### ISSUE TITLE
Does not install `pre-commit` module correctly

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#1055]
### Code to reproduce the issue:

1. `mkdir foo`
2. `cd foo`
3. `git init`
4. `echo '{"precommit": ["echo hello"], "devDependencies": { "pre-commit": "^1.2.2" }}' > package.json`
5. `pnpm i`
6. `git add package.json && git commit -m 'testing'`

### Expected behavior:

The word "hello" will be echoed to `stdout` after issuing `git commit -m 'testing'`.

### Actual behavior:

The pre-commit hook is not run because `pnpm` doesn't seem to run, at least run correctly, the `install` script from the `pre-commit` package.

### Additional information:

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: macOS

**Comment by etamponi** [comment]
Thanks for reporting! I've checked the source code of `pre-commit`, and it expects the "root" to be two directories above the directory in which pre-commit is installed. Unfortunately, in the case of pnpm, this does not happen, because pnpm has a different node_modules structure.

I'll open an issue in the pre-commit repo to see if they can fix it

**Comment by jsumners** [comment]
Until this issue is fixed upstream, you can use the feature introduced in #1106 to solve this.

1. `npm set pnpmfile ~/.pnpmfile.js`
2. Add the following to `~/.pnpmfile.js`

```js
'use strict'

module.exports = {
  hooks: {readPackage}
}

function readPackage (pkg, context) {
  if (pkg.name === 'pre-commit') {
    delete pkg.dependencies['pre-commit']
    pkg.dependencies['@jsumners/pre-commit'] = '1.2.2-fork.1'
    context.log('pre-commit => @jsumners/pre-commit')
  }
  return pkg
}
```

It could be tweaked to check for a maximum (hopefully the currently published) `pre-commit` package. But given the lack of movement around the issue upstream, I don't think it's worth it.

**Comment by shellscape** [comment]
FWIW husky + pnpm is broken again. https://github.com/typicode/husky/issues/854

**Comment by zkochan** [comment]
Closing because there is https://github.com/observing/pre-commit/issues/121
