### ISSUE TITLE
Does pnpm support path: or link: protocols?

### ISSUE THREAD

**Issue by donaldpipowitch** [pnpm/pnpm#1061]
### pnpm version:

1.35.1

### Code to reproduce the issue:

`bar/package.json`:

```json
{
    "name": "bar",
    "version": "1.0.0",
    "dependencies": {
        "foo": "link:../foo"
    }
}
```

`foo/package.json`:

```json
{
    "name": "foo",
    "version": "1.0.0"
}
```

`$ cd bar && pnpm install` 

### Expected behavior:

Either install succesfully or trigger a warning that `link:` is not a supported protocol.

### Actual behavior:

``` 
$ pnpm install
 ERROR  ENOENT: no such file or directory, open '/mnt/c/Users/foo/workspace/test/pnpm-link-protocol/bar/link:../foo/package.json'
```

### Additional information:

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: Win 10 Enterprise Insiders 17074 with Ubuntu WSL

---

I think `path:` is deprecated from npm's perspective, but AFAIK `path:` and `link:` _both_ work in npm and yarn.

**Comment by zkochan** [comment]
So `link:` should be a synonym of `file:` but for directories only.

For `path:` I would just throw a meaningful error. Both `npm@5` and Yarn throw an error for it. Here's what I got from npm:

```console
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "path:": path:../foofoo
```

**Comment by zkochan** [comment]
:ship: `v1.35.4`

**Comment by irisjay** [comment]
Hi! Is `link:` really a synonym for `file:`? I installed a local dependency with pnpm, which added a `link:` to my `package.json`, but unfortunately when testing the package, it was unable to install on npm with the error ```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:X                                               
```

I've looked around and have yet been able to find a source elsewhere that says `link:` really a synonym for `file:`.

**Comment by zkochan** [comment]
Did you use the latest npm?

**Comment by irisjay** [comment]
v6.4.0

**Comment by zkochan** [comment]
Do you need it to work inside a multi-package repository?

**Comment by irisjay** [comment]
No, not really. It really is a very simple package. I can even take the temporary workaround of changing the `package.json` myself, but I found it strange that what pnpm installs into `package.json` would be rejected by npm. Is this not an issue for you?

**Comment by zkochan** [comment]
Weird because according to [this issue](https://github.com/npm/npm/pull/15900) npm migrated to using the `link:` protocol as well

**Comment by irisjay** [comment]
Hmm. Can you reproduce what I'm saying? Should we open a new issue?
