### ISSUE TITLE
Regression? strict-ssl false ignored

### ISSUE THREAD

**Issue by donaldpipowitch** [pnpm/pnpm#1062]
### pnpm version:

1.35.1
### Code to reproduce the issue:

`.npmrc`:

```
strict-ssl=false
@my-scope:registry=https://npm-registry.my-company.lan/repository/npm-registry/
```

Missing public repo to reproduce this :(

### Expected behavior:

Installation works.

### Actual behavior:

`ERROR  request to https://npm-registry.my-company.lan/repository/npm-registry/@my-scope/my-module/-/my-module-3.2.2.tgz failed, reason: unable to verify the first certificate`

### Additional information:

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: Windows Enterprise Insiders 17074 with Ubuntu WSL

**Comment by donaldpipowitch** [comment]
Maybe this is the problem: https://github.com/pnpm/fetch-from-npm-registry/blob/master/src/index.ts#L46

This function seems to be called twice in my case and `defaultOpts.strictSSL` is `true` the second time. When I set `defaultOpts.strictSSL` to `false` manually here I don't get  `unable to verify the first certificate` errors.

**Comment by zkochan** [comment]
Throw an exception if strictSSL is true and post the stack trace here. I wonder if this happens during resolution or fetching. Seems like it is passed to both the resolvers and fetchers properly:

https://github.com/pnpm/pnpm/blob/1b86b3294aa8e58376c9c0336fd928b50c1e2a7e/src/createStore.ts#L37-L38

**Comment by zkochan** [comment]
I've found the issue.

**Comment by zkochan** [comment]
:ship: `1.35.3`

**Comment by donaldpipowitch** [comment]
Cool, Thank you. I'll try this. And sorry for not providing a stack trace. I had no time yesterday.
