### ISSUE TITLE
pnpmfile.js `readPackage` hook should allow modifying root package

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1063]
If I want to programmatically decide whether to include a top-level package.

My use case was trying to run CRNA, and I couldn't tell which dep was missing `json-schema-traverse`, so I want to add it to the top-level with a comment. But I don't want to necessarily add it to `package.json`.

**Comment by zkochan** [comment]
:ship: `1.35.6`

**Comment by xbtsw** [comment]
@zkochan this seems regressed in 5.5.1. readPackage is no longer called for workspace root. Is that intentional?
