### ISSUE TITLE
`--save-peer`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1064]
When working with Lerna and React, I find myself having to install `react` and `react-dom` as peer deeps often.

https://github.com/npm/npm/pull/3994

**Comment by vjpr** [comment]
Seems like yarn supports it.

https://github.com/yarnpkg/yarn/issues/5287

**Comment by wintercounter** [comment]
I have to `npm i module`. Move entry added to `package.json` to `peerDependencies` and `npm un module`. Ridicolus!

**Comment by zkochan** [comment]
So running `pnpm i foo --peer` should

1. install foo
2. add foo to `peerDependencies`
3. add foo to `devDependencies`

correct?

**Comment by wintercounter** [comment]
I think it varies between different use cases. For example in my current workflow where this is necessary when I'm adding my entry to peers I don't need to intall also. I'd give manual control:
- `pnpm i foo --peer` adds entry with correct semver.
- `pnpm i --peer` installs peers w/o changing lock file.

**Comment by zkochan** [comment]
TBH, not installing the dependency and not adding to the lockfile requires a lot of development.

This is fast to implement:

Running `pnpm i foo --save-peer` adds foo to peerDependencies and devDependencies

**Comment by zkochan** [comment]
:ship: [3.2.0-1](https://github.com/pnpm/pnpm/releases/tag/v3.2.0-1)

**Comment by gluons** [comment]
I need an alias for `--save-peer`. It's too long to type.

**Yarn** has `-P` as shorthand version.  
Need something like this for **pnpm**.

**Comment by zkochan** [comment]
`-P` is currently `--save-prod`.

I guess we could do it the same way as Yarn. Yarn doesn't have `--save-prod`, `yarn add foo` means adding foo to prod deps. But this is a breaking change.
