### ISSUE TITLE
Use fs.copyFile with UV_FS_COPYFILE_FICLONE flag when ready

### ISSUE THREAD

**Issue by langpavel** [pnpm/pnpm#1066]
Hi, You may be interested in new flag `UV_FS_COPYFILE_FICLONE` which will be available soon:

### Prerequisites
- [x] [libuv#1491 — unix: add UV_FS_COPYFILE_FICLONE support](https://github.com/libuv/libuv/pull/1491) (merged)
- [x] [node#19152 — Support UV_FS_COPYFILE_FICLONE](https://github.com/nodejs/node/issues/19152)

### Summary
There is new awesome upcoming feature which can dramatically improve copying files on Copy on Write file systems: `UV_FS_COPYFILE_FICLONE`
File copied (cloned) this way will not occupy additional disk space until first modification, but it also have all the properties that standalone file has.

<details>
<summary>Cloning from <a href="https://en.wikipedia.org/wiki/Btrfs#Cloning">Btrfs at Wikipedia.org</a> (+)</summary>

Btrfs provides a clone operation that atomically creates a copy-on-write snapshot of a file. Such cloned files are sometimes referred to as reflinks, in light of the associated Linux kernel system calls.

**By cloning, the file system does not create a new link pointing to an existing inode; instead, it creates a new inode that initially shares the same disk blocks with the original file.** As a result, cloning works only within the boundaries of the same Btrfs file system, but since version 3.6 of the Linux kernel it may cross the boundaries of subvolumes under certain circumstances. **The actual data blocks are not duplicated**; at the same time, due to the copy-on-write (CoW) nature of Btrfs, **modifications to any of the cloned files are not visible in the original file and vice versa**.

**Cloning should not be confused with hard links**, which are directory entries that associate multiple file names with actual files on a file system. **While hard links can be taken as different names for the same file, cloning in Btrfs provides independent files that share their disk blocks.**

Support for this Btrfs feature was added in version 7.5 of the GNU coreutils, via the `--reflink` option to the `cp` command.

---

</details>

<details>
<summary>Relevant paragraph from <a href="https://github.com/libuv/libuv/blob/v1.x/docs/src/fs.rst">libuv docs</a> (+)</summary>

> .. c:function:: int uv_fs_copyfile(uv_loop_t* loop, uv_fs_t* req, const char* path, const char* new_path, int flags, uv_fs_cb cb)
>     Copies a file from `path` to `new_path`. Supported `flags` are described below.
>    —————————————————————————————
>     - `UV_FS_COPYFILE_FICLONE`: If present, `uv_fs_copyfile()` will attempt to
>       create a copy-on-write reflink. If the underlying platform does not
>       support copy-on-write, then a fallback copy mechanism is used.
>     —————————————————————————————
>     .. versionchanged:: 1.20.0 `UV_FS_COPYFILE_FICLONE` is supported.

</details>

**Comment by langpavel** [comment]
I also opened same feature requests on https://github.com/npm/npm/issues/19970 and https://github.com/yarnpkg/yarn/issues/5456

**Comment by zkochan** [comment]
This was done

https://github.com/pnpm/pnpm/blob/e40ce033b720618e3908bc48434b4217240cc8eb/packages/package-store/src/storeController/createImportPackage.ts#L97-L99

**Comment by cristianl** [comment]
`COPYFILE_FICLONE` has been failing silently (it performs a normal copy instead of cloning the file) and `COPYFILE_FICLONE_FORCE` fails with `ENOSYS: function not implemented`.

**pnpm falls back to hardlinking, so there's no performance degradation.**

It was [removed due to a permissions bug](https://github.com/libuv/libuv/pull/2233) and there's an open PR to [bring it back without the permissions bug](https://github.com/libuv/libuv/pull/2578)

**Comment by langpavel** [comment]
@cristianl `COPYFILE_FICLONE` is file system feature available only on some configurations. It should work on `btrfs`
