### ISSUE TITLE
pnpm fatally errors when a package contains a whitespace-only license field.

### ISSUE THREAD

**Issue by Tellan** [pnpm/pnpm#1067]
### Code to reproduce the issue:

https://gist.github.com/Tellan/e76e9f58acc7afb71fe67368772de1d8

### Expected behavior:

`pnpm install` should successfully complete. 

### Actual behavior:

`pnpm install` throws because of the empty license field.

### Additional information:

 - `node -v` prints: v9.3.0
 - Windows, OS X, or Linux?: Linux

npm handles this situation just fine, but pnpm exits with an error. I tracked the error down to [these lines in normalize-package-data](https://github.com/npm/normalize-package-data/blob/9948ecf3d97cffcaab8f914522a0f3953edac6e4/lib/fixer.js#L296-L311) which fails to check for a whitespace string before passing it to the spdx parser.

**Comment by zkochan** [comment]
Can you publish such package to the npm registry?

**Comment by Tellan** [comment]
It errors even when calling pnpm install in a package directory with an empty license, but here's a package anyway:

https://www.npmjs.com/package/pnpm-license-test

**Comment by zkochan** [comment]
Seems to work as of v2.25.2
