### ISSUE TITLE
Do not automatically create a log file when a running process is killed

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1068]
### Code to reproduce the issue:

1. Install the following project

# package.json

```js
{
  "name": "pnpm-testy",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

# index.js

```js
const http = require("http");

http
  .createServer((req, res) => {
    res.write(`hey yo`);
    res.end();
  })
  .listen(8000);
```

3. Run start script (only `pnpm run start` spits log file; `pnpm start` doesn't)

```console
pnpm run start
```

4. Close the server

```console
Ctrl+C
```

### Expected behavior: 

No log file produced aka no `pnpm-debug.log`

### Actual behavior: 

Creates `pnpm-debug.log` with very little content

```console
---
  0 debug pnpm:cli: "command_done"

```

### Additional information:

 - `node -v` prints: v9.5.0
 - Windows, OS X, or Linux?: OS X

This is a weird bug but it constantly annoys me to check when a new file gets added. In this case, `pnpm-debug.log` file gets added whenever I close a running process. Its not that big of a bug but its annoying.

**Comment by zkochan** [comment]
We currently give SIGINT and SIGTERM exit code 1 in order to remove locks

https://github.com/pnpm/pnpm/blob/eb65d73c54990ed9f1afb1c973c1cf553d046b87/src/main.ts#L1-L5

if we remove that code, `pnpm-debug.log` will not be created

**Comment by zkochan** [comment]
:ship: 3.3.0-1
