### ISSUE TITLE
../bin/some_executable should have correct permissions

### ISSUE THREAD

**Issue by ngmariusz** [pnpm/pnpm#1075]
Hi there,

Is it expected behaviour or a bug?

My workaround is `chmod +x  PATH_TO_EXECUTABLE`

### pnpm version:
1.35.10

### Actual behavior:

i get my excecutable path in this way

![screenshot from 2018-03-14 17-59-27](https://user-images.githubusercontent.com/3337832/37418323-3da37d88-27b2-11e8-9aee-04bc19ceb9e2.png)

i am getting

![screenshot from 2018-03-14 18-01-00](https://user-images.githubusercontent.com/3337832/37418322-3d6a64bc-27b2-11e8-8109-1cc5087204e9.png)

because of wrong permissions

![screenshot from 2018-03-14 17-58-49](https://user-images.githubusercontent.com/3337832/37418324-3dc94644-27b2-11e8-9071-2224f591cd65.png)

### Additional information:

 - `node -v` prints:
v8.9.4

 - Windows, OS X, or Linux?:
Linux

**Comment by zkochan** [comment]
I guess we could make those files executable during installation.

pnpm doesn't really need them to be executable because pnpm always creates shell scripts in `.bin` folders (related: #1282)

As a workaround, you can use `spawn('node', [bin, ...args])`

**Comment by aquark** [comment]
I'm curious, since using `spawn('node', [bin, ...args])` bypasses the generated wrapper script which sets `NODE_PATH`, wouldn't this break programs which rely on undeclared peer dependencies (plugins)?

**Comment by zkochan** [comment]
It might.
I think that would be an edge case but if you have it, you may use the `shamefully-flatten` flag.

**Comment by zkochan** [comment]
:ship: 2.25.3
