### ISSUE TITLE
@pnpmfile npm org

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1079]
Wanted to gather thoughts on this idea.

I created an org called `@pnpmfile`.

The plan is to publish packages there to use as `readPackage` hooks to fix broken packages.

E.g:

```js
function readPackage(pkg) { 
  require('@pnpmfile/create-react-native-app').default(pkg) 
}
```

---

I also plan on having a package called `pnpmfile-check` which will inform you if there are incompatible packages in your tree.

```js
function readPackage(pkg) { 
  require('@pnpmfile-check').default(pkg)
}
```

Or:

```js
scripts: {
  postinstall: './node_modules/.bin/pnpmfile-check'
}
```

**Comment by vjpr** [comment]
I think this is a bad idea. A package manager requiring installing packages to run is not going to work.

Copy and paste feels like the only approach that could work.

**Comment by vjpr** [comment]
@zkochan Do you think it would be possible to have a hook to install dependencies before `pnpmfile.js` is run? Or would you prefer to keep `pnpmfile.js` dependency-free?

Without this, it doesn't seem like its easy to extend `pnpmfile.js`. E.g. Say you want to use the `semver` package, you would have to include to source code in your project via copy-paste.

---

Or, we could use `preinstall` to install into a subdirectory called e.g. `pnpmfile`? But this might slow things down...

**Comment by vjpr** [comment]
Unfortunately a `preinstall` script adds ~1s to `pnpm install`.

Without preinstall:

```
pnpm install  1.99s user 0.36s system 108% cpu 2.172 total
```

With `"preinstall": "pnpm install --prefix=pnpmfile --no-verify-store-integrity"`:

```
pnpm install  2.89s user 0.54s system 102% cpu 3.344 total
```

**Comment by zkochan** [comment]
It is possible to configure `pnpm recursive install` to do installation in `project/pnpmfile/` then in `project/`. It should be faster than the preinstall script.

But `project` should depend on `project/pnpmfile`. Otherwise, pnpm will do installation in both projects concurrently. So you can create a package.json like this:

```json
{
  "name": "pnpmfile",
  "version": "1.0.0"
  ...
}
```

and then in `project/package.json`, add pnpmfile as a dep:

```json
{
  ...
  "pnpmfile": "^1.0.0",
  ...
}
```

**Comment by vjpr** [comment]
@zkochan Awesome. Didn't think of that!

**Comment by zkochan** [comment]
A dependency can influence the installation of the dependent package if it is used in a lifecycle script.

I believe lerna installs this way as well

**Comment by vjpr** [comment]
> I believe lerna installs this way as well

Hopefully. I will test this tomorrow. If so, its the perfect solution.

**Comment by zkochan** [comment]
oh, the right command will probably be `pnpm recursive link` because `pnpm recursive install` will try to install pnpmfile `project/` from the npm registry

**Comment by vjpr** [comment]
I think it might even be a good idea to have this functionality built into pnpm, primarily because you don't want to have to rely on a preinstall script to install dependencies for a dependency manager to work.

We could have a central github repo with a json file that pnpm could optionally query.

Then when you install it could check if there are custom resolutions available for packages, and ask you if you want to merge them in.

Maybe we could have a separate file called `pnpm-resolutions.json`. Related https://github.com/pnpm/pnpm/issues/1082.

**Comment by hulkish** [comment]
@vjpr I am not opposed to the basic idea described in OP. But, there should definitely be strong emphasis on having the real packages having these issues corrected.

In the event that one of the real packages fixes their issue - i would hope that the matching `@pnpmfile` package would be deprecated.

**Comment by vjpr** [comment]
Maybe a funny name and shame website of broken packages to raise awareness of this issue.

**Comment by hulkish** [comment]
@vjpr Agreed. I think that is a better way to resolve this. Basically we need to tell the truth as it is - "you are using node incorrectly"

**Comment by zkochan** [comment]
I think it is enough to have something like a [json](https://gist.github.com/zkochan/41329d68cbd74862225dc462a69674fa) with the overrides

**Comment by zkochan** [comment]
Now Yarn 2 has the same issues as pnpm in strict mode.

They create a database of "replacement, seems like similar to what this issue suggests: https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/sources/extensions.ts

**Comment by vjpr** [comment]
> I think it is enough to have something like a json with the overrides

@zkochan Is there any existing work on this?

**Comment by zkochan** [comment]
I did not work on this.

**Comment by zkochan** [comment]
We will use Yarn's compat database https://github.com/pnpm/pnpm/pull/4676
