### ISSUE TITLE
`$ pnpm install dep1 dep2` logs only dep1, swallowing evertyhing else while installing both though

### ISSUE THREAD

**Issue by iamstarkov** [pnpm/pnpm#108]
It seems like pnpm logs only first target modules to install. Simple test case for `pnpm 0.17.0` are no-deps packages as `inherits` and `ramda`:

``` sh
$ pnpm i inherits
  inherits                                                          2.0.1 ✓
$ pnpm i ramda
  ramda                                                            0.19.1 ✓
$ pnpm i inherits ramda
  inherits                                                         0.19.1 ✓
$ pnpm i ramda inherits
  ramda                                                            0.19.1 ✓
```

**Comment by rstacruz** [comment]
how about `pnpm-install ramda inherits`?

**Comment by iamstarkov** [comment]
nope:

```
$ pnpm-install ramda inherits
  ramda                                                             2.0.1 ✓
```
i looked into that cli switch, nope `installMultiple` gets both packages and `logger` with `getTask` get both packages to act on as well .

**Comment by rstacruz** [comment]
shame, I can't believe I missed this.

**Comment by iamstarkov** [comment]
its fine, i just didn't find yesterday exact lines where this missing happens, so i decided to share this problem
