### ISSUE TITLE
Allow linking subdeps

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1081]
Related: https://github.com/pnpm/pnpm.github.io/pull/8#issuecomment-373373182

I agree relative links are a bad idea, but it would be really great to support linking to project root.

E.g:

```
"lodash": "link:<project>/patched-modules/lodash"
```

Then whenever you need to patch a module, you can copy it into your project (or use git subtree), and add this to your `pnpmfile`.

Absolute paths would be useful too when you want to link to repo outside project tree during development.

**Comment by zkochan** [comment]
This will be possible to implement in pnpm v5.

Related changes are here: #2554

**Comment by zkochan** [comment]
This is now possible with [pnpm.overrides](https://pnpm.js.org/en/package_json#pnpmoverrides)

For instance:

```json
{
  "pnpm": {
    "overrides": {
      "lodash": "link:../lodash"
    }
  }
}
```
