### ISSUE TITLE
`prepare` not run on git dep install

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1085]
See https://github.com/pnpm/pnpm/issues/810#issuecomment-374011712

I would like it if we used `yarn` semantics.

`prepare` would run for git installs so that transpilation could be run.

Currently only preinstall, install, and postinstall are run on git dep install.

**Comment by vjpr** [comment]
Related: https://github.com/pnpm/pnpm/issues/855

**Comment by zkochan** [comment]
See my proposed solution [here](https://github.com/pnpm/pnpm/issues/855#issuecomment-384445131)

**Comment by zkochan** [comment]
:ship: `1.43.0`
