### ISSUE TITLE
If packed.tgz contains a directory without the executable flag, install fails

### ISSUE THREAD

**Issue by etamponi** [pnpm/pnpm#1087]
As in the issue subject. How to reproduce:

1. `pnpm install kitsu`

Expected: it works
Actual:
```
Packages: +11
+++++++++++
 ERROR  Fetching registry.npmjs.org/kitsu/5.0.6 failed!
 ERROR  EACCES: permission denied, open '/Users/etamponi/.pnpm-store/2/registry.npmjs.org/kitsu/5.0.6/_tmp_6630_8477206cd0ae0e1203631ce668995a68/CHANGELOG.md'
at Error
Resolving: total 11, reused 8, downloaded 1
```

When I try to unpack manually the downloaded file, `packed.tgz`, it contains a directory without the executable flag (permissions 644), this is why we get a permission denied.

Solution: apparently we need to make sure all the unpacked directories are accessible... :/

**Comment by zkochan** [comment]
:ship: `1.36.2`
