### ISSUE TITLE
`afterAllResolved` pnpmfile hook

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1088]
Continuing from this Gitter discussion:

```
Vaughan Rouesnel @vjpr Mar 15 16:13
@zkochan is there a hook that can run after all readPackagecalls?
I want to have a hook running on readPackage that will collect up all the packages that there are available patches for, and then print install instructions to console.

Zoltan Kochan @zkochan Mar 15 16:17
why not just a postinstall script?
with that, the only issue is that the shrinkwrap.yaml is saved after the postinstall scripts run

Vaughan Rouesnel @vjpr Mar 15 16:17
i want to use an in-memory list in same process as pnpmfile.js

Zoltan Kochan @zkochan Mar 15 16:18
there is no such hook currently
```

I want to add another use case for this hook.

Say you modify a specific version of a package's manifest. If the package version is updated, the modified manifest may break the package, or the package may stop working.

So you need a way to be warned when your modification stops being used.

The only way to know if your modification ran is in the pnpmfile.

```js
let modified = []
let expected = ['foo']
let ignored = [] // Allows user to acknowledge that a fix for a package is no longer needed. Could also comment out the modification too.

function readPackage(pkg) {
  if (pkg.name === 'foo') {
    if (pkg.version === '1.0.0') {
      modified.push('foo')
    }
  }
}

function afterReadPackages() {
  // compare modified with expected
  // print unmodified packages warning
}
```

**Comment by zkochan** [comment]
@vjpr why does the `afterReadPackages` have a pkg argument?

I think I'd call the hook: `postResolution`.

**Comment by vjpr** [comment]
> @vjpr why does the afterReadPackages have a pkg argument?

Mistake.

> I think I'd call the hook: postResolution.

Sounds good.

**Comment by zkochan** [comment]
to reduce ambiguity, I'll call it `afterAllResolved`
