### ISSUE TITLE
Run `prepare` on `pnpm recursive install`?

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1089]
From https://github.com/lerna/lerna#bootstrap:

> When run, this command will:
> 1. npm install all external dependencies of each package.
> 1. Symlink together all Lerna packages that are dependencies of each other.
> 1. npm run prepublish in all bootstrapped packages.
> 1. npm run prepare in all bootstrapped packages.

Should `recursive install` replicate Lerna's behaviour?

Aside: Should it support Lerna flags too?

**Comment by zkochan** [comment]
I assume it would make sense if we would bootstrap the packages in random order. However, we install them concurrently in chunks and each chunk has all of its dependencies bootstrapped before.

**Comment by zkochan** [comment]
This is a good idea because we'll be able to run installation in every package concurrently. Currently, we can run installation concurrently in independent groups (chunks). One group at a time
