### ISSUE TITLE
Shrinkwrapfile gets updated incorrectly during pnpm install for pnpm@1.35.2

### ISSUE THREAD

**Issue by thomabr** [pnpm/pnpm#1092]
### Code to reproduce the issue:
There is an issue that started in pnpm version 1.35.2 where the version of some dependencies in a shrinkwrap file are getting updated when "pnpm install" is run.

I’ve put basic example on a public github: https://github.com/tipbruley/pnpmdebug 

You can repro the issue by simplying installing the rush module then doing a "rush install" in the root. If you compare the shrinkwrap file in the common/config/rush folder and the common/temp folder, the temp file revs the version of office-ui-fabric-react that both packages use. Rush coppies the shrinkwrap over to the temp folder and runs `pnpm install --no-optional --store <repopath>\common\temp\pnpm-store --no-lock`. Pnpm changes the shrinkwrap file durring it's execution.

Changing the version of pnpm in the rush.json file to 1.35.1 fixes the issue if you run “Rush install -c”. I've also verified that if I manually run an pnpm@1.35.1, the shrinkwrap file is not changed and the correct version is installed.

Let me know if you need any more details.

### Expected behavior:
Shrinkwrap file is unchanged and version 5.64.4 of office-ui-fabric-react is installed
### Actual behavior:
Shrinkwrap file is updated to point to the 5.67.0 (or latest version) of office-ui-fabric-react
### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?: windows

**Comment by zkochan** [comment]
> version 5.64.4 of office-ui-fabric-react is installed

this I will fix

> Shrinkwrap file is unchanged 

Only the integrity of `file:projects/newtestpnpm.tgz` and `file:projects/oldtestpnpm.tgz` will be updated in the shrinkwrap file. I don't have a solution for that currently

**Comment by zkochan** [comment]
:ship: `1.37.2`
