### ISSUE TITLE
Read package-specific `.npmrc` settings during `pnpm recursive`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1093]
From Gitter:

```
Vaughan Rouesnel @vjpr Mar 22 22:17
@zkochan is there a way to pass pnpm flags per package.json not from cli?
when running lerna bootstrap, some packages need to be —shamefully-flattened
is it .npmrc?
yeh i thiink i answered my own questtion

Zoltan Kochan @zkochan 22:38
I guess it will work with lerna bootstrap but pnpm recursive will read the configs only once
not per package
```

Also, is a package-specific `pnpmfile.js` used during recursive?

**Comment by zkochan** [comment]
**Regarding npmrc.** We can update `pnpm recursive` to make it read the `.npmrc` file of each package. And it will work with `shamefully-flatten=true`. Some configs will be ignored though. We initialize the store controller once for `pnpm recursive`, so any store-related configs will be ignore in subpackages.

**Regarding pnpmfile.js.** As of now, package-specific `pnpmfile.js` are used. However, I assume that in a monorepo, most of the hooks would be shared. So I think it would make more sense to read one pnpmfile in the root of the monorepo. We can update the pnpmfile format. It can return a function that accepts the package location. In that case the pnpmfile can return different configurations for different subpackages

```js
modules.exports = (projectDir) => {
  if (projectDir === 'packages/foo') {
    return {
      // some hooks
    }
  }
  return {
    // some default hooks for all the other projects
  }
}
```

**Comment by zkochan** [comment]
What would be the expected behavior if one runs `pnpm recursive install --no-shamefully-flatten`? Currently, configs passed via the CLI args have priority over configs in `.npmrc`. But I am not sure that would be expected in a monorepo, if one of the packages has a custom configuration.

**Comment by vjpr** [comment]
Maybe require postfixing `-all` or `-recursively` to any cli options that should be applied when using `pnpm recursive X`?

E.g.

`pnpm recursive install --shamefully-flatten-recursively`

Overrides local package configs.

`pnpm recursive install --no-shamefully-flatten`

Shows warning that option will not take effect unless appending `-recursively`.
