### ISSUE TITLE
retain --shamefully-flatten in shrinkwrap

### ISSUE THREAD

**Issue by wmertens** [pnpm/pnpm#1097]
`pnpm` is awesome, but the Node ecosystem is vast and there are many packages that are buggy in their assumption of `node_modules` layout. (for example Jest)

So, for some projects you simply have to use `--shamefully-flatten` until all used packages are fixed (if ever :-/ ).

Would it be possible to keep that setting in `shrinkwrap.yaml` so it doesn't have to be repeated every time? It is part of the description of how modules have to be installed, after all.

Just another step towards world domination ;)

**Comment by zkochan** [comment]
Configs should be in `.npmrc`. So you can just created a `.npmrc` with `shamefully-flatten=true` in the root of the problematic project.

Maybe we could create the config file automatically in such cases? There is this idea: #820

**Comment by wmertens** [comment]
Ah yes, good idea, so this is a duplicate of that. Closing.
