### ISSUE TITLE
pnpm recursive publish

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1098]
...to publish all packages in a monorepo.

**Comment by zkochan** [comment]
what would be the best strategy for publishing? lerna seems to be the most popular publishing tool for monorepos. There is also oao with a similar approach to lerna's. And there is also rush which forces to describe every change in a json file if I understand it correctly.

**Comment by KSXGitHub** [comment]
By default, I prefer it to be simple:
* pnpm should only consider packages without `"private": true`.
* pnpm should only consider packages with a name.
* pnpm should only consider packages whose version is available in registry (a.k.a. yet to be published).

User may tweak behaviour via `pnpm-workspace.yaml`.

**Comment by zkochan** [comment]
This sounds good to me. More complex logic can potentially be implemented in something like `pnpm recursive version`.

**Comment by ericclemmons** [comment]
I was just experimenting with this, and I think the biggest issue is with interactive prompts.

Using the excelling [`np`](https://github.com/sindresorhus/np) utility:

```diff
diff --git a/packages/hot-module/package.json b/packages/hot-module/package.json
index f2f9d97..9696e13 100644
--- a/packages/my-package/package.json
+++ b/packages/my-package/package.json
@@ -2,8 +2,14 @@
   "name": "my-package",
   "version": "1.0.0",
   "main": "src/index.js",
+  "scripts": {
+    "release": "np"
+  },
   "dependencies": {
     "is-builtin-module": "^3.0.0",
     "node-watch": "^0.5.8"
+  },
+  "devDependencies": {
+    "np": "^3.0.4"
   }
}
```

It looks like I could leverage `pnpm multi run`, since it will skip packages that don't have that script:

```
pnpm m run release

packages/my-package                      |     release$ np
packages/my-package                      |     release: Publish a new version of my-package (current: 1.0.0)
```

Perhaps `np` isn't ready for a monorepo, but it raises an interesting dilemma for anything that requires `stdin`.

But this hangs, since I can't provide input to interactive prompts.

**Comment by aschultz** [comment]
Does `pnpm publish` perform any dependency analysis to make sure that any workspace dependencies (explicit or implict) are themselves published first?

**Comment by KSXGitHub** [comment]
@aschultz I don't think it is necessary

**Comment by zkochan** [comment]
As far as I know, this is how lerna does it and we can do the same. 

1. all packages are published with some temporary dist-tag
2. if all the packages are successfully published, the versions get a regular dist-tag (latest by default)

**Comment by KSXGitHub** [comment]
How lerna handles it when, not all succeeded (published versions are not yet official), user tries again (successfully this time) without changing versions? I expect it to simply mark those versions as official.

**Comment by zkochan** [comment]
I don't know how lerna behaves in that case. We can implement our own logic.

**Comment by zkochan** [comment]
See also #2225
