### ISSUE TITLE
Optimize the dependencies build step

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1109]
[pnpm@1.37.5](https://github.com/pnpm/pnpm/releases/tag/v1.37.5) added a slowdown to the dependencies build step.

Dependencies should be built in correct order, dependencies before dependents. However, sorting the dependency graph is a costly operation. Graph sorting added 1.6 seconds to installation time to a project with 741 packages. The delay seems to increase exponentially for bigger projects.

Possible solutions:
* sort only a subgraph of dependencies with lifecycle hooks
* add some additional info to the shrinkwrap that will boost sorting

**Comment by zkochan** [comment]
Seems like to do optimize this, we have to add some of the lifecycle hooks to `shrinkwrap.yaml` as described in #1101

**Comment by etamponi** [comment]
I would need a clarification on Point 3, the package has native addon modules: what does it mean? npm checks for binding.gyp, is it that?

**Comment by zkochan** [comment]
yes, correct

**Comment by zkochan** [comment]
as a fast solution, I am now requesting the full metadata from the registry, which contains the `scripts` field.

Later we can switch back to non-full metadata and read the `package.json` from the unpacked tarball.

**Comment by zkochan** [comment]
:ship: 1.40.0
