### ISSUE TITLE
pnpm sometimes says an update is available when it isn't

### ISSUE THREAD

**Issue by sleeparrow** [pnpm/pnpm#1111]
### pnpm version:

`1.38.3` _i think_

### Code to reproduce the issue:

explain this, atheists:

----

![screen shot 2018-04-10 at 1 11 25 pm](https://user-images.githubusercontent.com/6981186/38572337-d9a39d8a-3cc0-11e8-8947-c91e2eb60089.png)

----

### Expected behavior:

pnpm shouldn't say there's an update available when you have the latest version

### Actual behavior:

pnpm said there's an update available when i had the latest version

### Additional information:

 - `node -v` prints: `v8.6.0`
 - Windows, OS X, or Linux?: MacOS

**Comment by o2dazone** [comment]
I've seen this happen on other versions of pnpm as well. Looks as though pnpm relies on an under version of `update-notifier`. A wild guess, but I'm assuming bumping it to the latest could fix it

https://github.com/yeoman/update-notifier/pull/130

**Comment by zkochan** [comment]
@sleeparrow I think the issue is that pnpm did not successfully update itself. Check `pnpm -v`. We have this issue: #1052

**Comment by sleeparrow** [comment]
```
$ pnpm --version
1.38.3
```

i don't believe it failed to update. i didn't run `pnpm i -g pnpm` again and it says it's at `1.38.3`

**Comment by zkochan** [comment]
This was fixed.
