### ISSUE TITLE
too many symbolic links encountered error

### ISSUE THREAD

**Issue by RandallFlagg** [pnpm/pnpm#1112]
### pnpm version:

> 1.38.3

### Code to reproduce the issue:
`pnpm install -g @adonisjs/cli`

### Expected behavior:

> A success result

### Actual behavior:

> Packages: +317
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>  ERROR  ELOOP: too many symbolic links encountered, stat 'E:\Tools\nodejs\node-v9.8.0-win-x64\pnpm-global\1\node_modules\.registry.npmjs.org\@adonisjs\ace\5.0.1\node_modules\mustache'
> at org\
> Resolving: total 317, reused 0, downloaded 317

### Additional information:
[pnpm-debug.log](https://gist.github.com/RandallFlagg/cc03346a41d098a7de9925c6c16c81e6)
 - `node -v` prints:

> 9.8.0

 - Windows, OS X, or Linux?:

> Windows 10 x64

**Comment by zkochan** [comment]
This works with the latest pnpm.
