### ISSUE TITLE
Caveat when using webpack/bundlers etc

### ISSUE THREAD

**Issue by wmertens** [pnpm/pnpm#1113]
I found a problem when using webpack: my project was configured to transpile e.g. `tapable` by telling webpack that it should use babel for any path under `./node_modules/tapable`.

However, when webpack looks at a path it will resolve symlinks on directories first and then the path is really `./node_modules/.registry.npmjs.org/tapable/1.0.0/node_modules/tapable/`.

So this is something worth mentioning in the readme.

I wonder if it could be avoided by symlinking all files instead of hardlinking them: make all the directories where they would be expected, and where you would normally hardlink, make a symlink to .registry, which symlinks or hardlinks to the cache.

**Comment by zkochan** [comment]
> I wonder if it could be avoided by symlinking all files instead of hardlinking them: make all the directories where they would be expected, and where you would normally hardlink, make a symlink to .registry, which symlinks or hardlinks to the cache.

I don't understand what you mean. That is what we currently do, symlink the folder from `.registry.npmjs.org/...`. I would love to symlink directly to the store, here's an issue about it: #1001

However, some packages rely on their location and they expect to be in a subfolder of `project/node_modules/...`, so I think we should increase adoption of pnpm before symlinking from store. It is already hard with the strict node_modules :-(
