### ISSUE TITLE
Shrinkwrap file gets updated incorrectly during pnpm install when we have dependencies with different registry urls

### ISSUE THREAD

**Issue by ddlbrena** [pnpm/pnpm#1121]
### Code to reproduce the issue:

When we have a package.json with dependencies with different registry urls the generated shrinkwrap.yaml file after running "pnpm install --no-optional --store <repopath>\common\temp\pnpm-store --no-lock" seems to be wrong.
The scenario is as follows we have the following two devDependencies in our package.json file:

`"devDependencies": {`
        `"@scope1/dependency1": "^0.4.0",`
	`"@scope2/dependency2": ">=1.0.14 <2.0.0"'`
`}`

Our .npmrc looks like this:

`@scope1:registry=https://depRepo1.pkgs.visualstudio.com/_packaging/Tools/npm/registry/`
`//depRepo1.pkgs.visualstudio.com/_packaging/Tools/npm/registry/:always-auth=true`
`@scope2:registry=https://depRepo2.pkgs.visualstudio.com/_packaging/Tools/npm/registry/`
`//depRepo2.pkgs.visualstudio.com/_packaging/Tools/npm/registry/:always-auth=true`
`registry=https://registry.npmjs.org/`
`always-auth=true`

The generated yaml ends up having something like this:

`dependencies:`
  `'@scope1/dependency1'`: `depRepo1.pkgs.visualstudio.com/@scope1/dependency1/1.0.14`
  `'@scope2/dependency2'`: `depRepo2.pkgs.visualstudio.com/@scope2/dependency2/0.4.0`

Then when we do npm install, we get the following error:
  
`ERROR: Invalid Version: depRepo1.pkgs.visualstudio.com/@scope1/dependency1/1.0.14`
  
I think this is because the yaml is expected to have:
 
`'@scope1/dependency1': 1.0.14`

Since  `'depRepo1.pkgs.visualstudio.com/@scope1/dependency1/1.0.14'` is not a valid dependency number.

If I change the scenario and the dependencies share the same url as the registry entry in the .npmrc file then everything works well.

### Expected behavior:

shrinkwrap yaml file lists dependency like:
`'@scope1/dependency1': 1.0.14`

### Actual behavior:

shrinkwrap yaml file lists dependency like:
` '@scope1/dependency1': depRepo1.pkgs.visualstudio.com/@scope1/dependency1/1.0.14`

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?: Windows

**Comment by ddlbrena** [comment]
Thanks Zoltan, I looked more and I think it might be a bug in Rush, since the error comes from there being unable to parse the `depRepo1.pkgs.visualstudio.com/@scope1/dependency1/1.0.14` version format. I will follow up there. 

Also I was trying to find more info regarding the shrinkwrap yaml format, is there any?

thanks.

**Comment by zkochan** [comment]
There is this https://github.com/pnpm/spec/blob/master/shrinkwrap/3.4.md. And here are some utils for manipulations with shrinkwrap: https://github.com/pnpm/pnpm-shrinkwrap

**Comment by ddlbrena** [comment]
Thank you, my bad for missing that. There is no issue here then. I will close the issue. Thank you for the help.
