### ISSUE TITLE
pnpm run-script exit status is always 0

### ISSUE THREAD

**Issue by josephschmitt** [pnpm/pnpm#1123]
### Code to reproduce the issue:

Reproducible example can be found here: https://github.com/josephschmitt/pnpm-run-script-exit-status

### Expected behavior:

Running a script via run-script that has a non-zero exit status should result in a non-zero exit status.

### Actual behavior:

run-script results in an exit-status of 0

**Comment by josephschmitt** [comment]
@zkochan you're fast!

**Comment by zkochan** [comment]
:rocket:

**Comment by zkochan** [comment]
:ship: `1.41.0`
