### ISSUE TITLE
`--warnings-as-errors`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1126]
Show warnings as errors once the install finishes.

Use case from @pgonzal:

> In our case we do a single install for over a hundred projects, and many of the developers know very little about NPM or peer dependencies. We would want the build to fail, so they will go ask for help from someone knowledgable, and then if it's really okay then they can suppress the error for that specific library only. In this scenario we definitely would NOT want wrong versions getting silently ignored, because it's counterintuivie and could lead to a complicated investigation before they figure out what's going on.

> Also as soon as any warnings start accumulating in the logs, we would quickly get into a situation where people always ignore the warnings because "those are normal" and "it's probably from someone else's code"

If https://github.com/pnpm/pnpm/issues/1125 was implemented, I would use this all the time.

**Comment by pgonzal** [comment]
Since #1125 has a workaround, `--warnings-as-errors` seems like a higher priority.

**Comment by pgonzal** [comment]
Here are examples of genuine problems that were being ignored by everybody because pnpm treats them as warnings:

> WARN @ms/plannerweb-ui: @ms/react-advanced-grid@8.1.5 requires a peer of moment@^2.22.0 but version 2.21.0 was installed.
> WARN @ms/searchux-sphome@36.0.3 requires a peer of react-router@>=2.6.1 but none was installed.
> WARN Cannot find file at C:\agent\3\_work\1\s\common\temp\node_modules\@rush-temp\react-bundle although it was listed by readdir
> WARN Cannot find file at C:\agent\3\_work\1\s\common\temp\node_modules\@rush-temp\react-dom-bundle although it was listed by readdir


Here are some example warnings about situations that are 100% intentional.  We will have no plans to fix them.  These false alarms lead people to never take any warnings seriously:

> WARN  using --no-lock I sure hope you know what you are doing
> WARN  webpack > watchpack > chokidar: Skipping failed optional dependency fsevents@1.2.0
> WARN  deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by zkochan** [comment]
> WARN  using --no-lock I sure hope you know what you are doing

This warning I have removed. Maybe we even have to make `--no-lock` the default behavior because it is really buggy #594

> WARN  webpack > watchpack > chokidar: Skipping failed optional dependency fsevents@1.2.0

I think there is no need to print anything about skipped non-direct optional dependencies. And we can print info messages about skipped direct optional dependencies.

> WARN  deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

I would keep it a warning but I don't think the app should fail on this

**Comment by zkochan** [comment]
@vjpr I created #1142. So you'd want the installation to be finished, the node_modules created but the process to return a non-zero exit code? And an error to be printed?

It would be easier to implement just an exception throw.

Also, what about optional dependencies? I guess in case of optional dependencies, an unsatisfied peer dep should mean that the optional dependency should be skipped

**Comment by vjpr** [comment]
> So you'd want the installation to be finished, the node_modules created but the process to return a non-zero exit code? And an error to be printed?

Yep.

> It would be easier to implement just an exception throw.

You mean not waiting until the end? Or throwing an exception at the end?

> Also, what about optional dependencies? I guess in case of optional dependencies, an unsatisfied peer dep should mean that the optional dependency should be skipped, right?

Sorry, I don't follow.

**Comment by pgonzal** [comment]
In our scenario, the idea is that for a local developer, the install succeeds and simply prints a warning in yellow. Whereas for a production build or PR build, the install should fail with a nonzero exit code. I think we'd want it to fail as early as possible, so the person can get notified and go fix their branch. I don't even think it's useful to complete the installation, although perhaps some people might want to continue building to collect other errors. For us that wouldn't be very helpful because our full build is an hour long, and nobody wants to wait for that when they know the result will be unusable.

**Comment by pgonzal** [comment]
We skip all optional dependencies because they don't make sense when developers are using different operating systems. For example, a shrinkwrap created on Windows would be missing optional dependencies for Mac, but then if a Mac user happens  to generate the shrinkwrap file then those dependencies will get added. This whole model seems incompatible with the premise of a shrinkwrap file. Also, if they are truly optional then why should there be a "warning" when they don't get installed -- the system is behaving as intended.

**Comment by vjpr** [comment]
> Also, if they are truly optional then why should there be a "warning"
when they don't get installed -- the system is behaving as intended.

What if installation of an OS specific package fails they should be
installed. User needs to know. Optional can mean many things.

Should be installed only on specific environment. Or that user can opt in
for some functionality.

I think it's best that these warning can be silenced explicitly per
package.

**Comment by vjpr** [comment]
> For us that wouldn't be very helpful because our full build is an hour long, and nobody wants to wait for that when they know the result will be unusable.

What if your the error is at the end of your build...and then there is another error right after it. Then you have to wait ~2 hrs to see all the errors.

We should have a flag to `--fail-on-first-error`. This would not be default behavior IMHO.

**Comment by vjpr** [comment]
> optional dependencies...don't make sense when developers are using different operating systems...This whole model seems incompatible with the premise of a shrinkwrap file.

Ideally the shrinkwrap should not change after it has been installed on multiple platforms. That is, if an optional dep installs on Linux, it should not be removed when `pnpm i` is ran on macOS.

Maybe this is already how it is?

**Comment by pgonzal** [comment]
Oh I see your point. I was assuming pnpm needed to complete to see later build errors (which might not be worth it). Yes we definitely would want to see the full list of *pnpm* errors/warnings. If we have to complete the install operation to get that, then it makes sense.

**Comment by pgonzal** [comment]
> What if installation of an OS specific package fails that should be installed? 

You haven't addressed my question above. Suppose "mac-notifier" package should be installed for Mac users. If a Windows user makes the shrinkwrap file, my understanding is that Mac users won't get that package installed. In a multi-OS ecosystem, it's a coin toss which OS will be used to make the shrinkwrap file. How is this "optional package" model workable at all?

A sinpler model would be e.g. a "notifier" package that has drivers for Mac and Windows and maybe does nothing for Linux if the native support isn't available. That way the installation tree is the same for everyone.

**Comment by zkochan** [comment]
> Ideally the shrinkwrap should not change after it has been installed on multiple platforms. That is, if an optional dep installs on Linux, it should not be removed when pnpm i is ran on macOS.

Correct, pnpm will generate the same `shrinkwrap.yaml` regardless of the system. Even if some dependencies are not installed on Windows, they will be resolved and added to the `shrinkwrap.yaml`

**Comment by zkochan** [comment]
>>  Also, what about optional dependencies? I guess in case of optional dependencies, an unsatisfied peer dep should mean that the optional dependency should be skipped, right?
>
> Sorry, I don't follow what you mean.

I mean if we implement a flag like [--strict-peer](https://github.com/pnpm/pnpm/issues/1142) and an optional dependency has unresolved peer dependency, then the optional dependency should skipped during installation.

> What if your the error is at the end of your build...and then there is another error right after it. Then you have to wait ~2 hrs to see all the errors.
>
> We should have a flag to --fail-on-first-error. This would not be default behavior IMHO.

One bad apple spoils the whole bunch. If there is one error, how do you know that the subsequent errors are not caused by the first one? I would suggest to terminate the installation on the first error.

**Comment by pgonzal** [comment]
> Correct, pnpm will generate the same shrinkwrap.yaml regardless of the system. Even if some dependencies are not installed on Windows, they will be resolved and added to the shrinkwrap.yaml. It is how it currently works.

That's great!  I'm pretty sure NPM did not work that way.

**Comment by iclanton** [comment]
What would it take to get this implemented? Our repos are collecting a lot of warnings about pnpm violating semver during install.

**Comment by zkochan** [comment]
We can implement the [strict-peer](https://github.com/pnpm/pnpm/issues/1142) config first. Seems like that's what you need

**Comment by zkochan** [comment]
I don't think it is a good idea to fail installation on all warnings (for instance, a warning is printed when a request is failed, but it may pass on a retry). But adding separate settings for specific warnings is OK, like `fail-on-deprecated for failing on deprected packages. Or like `strict-peer-dependencies`, which was already added.
