### ISSUE TITLE
Can't install aframe: invalid specifier dmarcos/document-register-element#8ccc532b7

### ISSUE THREAD

**Issue by etamponi** [pnpm/pnpm#1127]
To reproduce:

```
pnpm install aframe
```

Error:
```
ERROR  Could not resolve 8ccc532b7 to a commit of git://github.com/dmarcos/document-register-element.git.
```

The aframe package specifies this dependency:

```
"document-register-element": "dmarcos/document-register-element#8ccc532b7"
```

Which seems to fail in pnpm, but not in npm

**Comment by 5310** [comment]
I'm still getting this with PNPM 2.13.5 and A-Frame 0.8.2 

Any ideas what I could do to get it to install?

**Comment by 5310** [comment]
The dependency is now expanded to its full hash in A-Frame itself, and the package can be installed directly in PNPM now (from the GitHub repository for now, and perhaps from NPM by 0.8.3)

:crossed_fingers: for shorthash resolution in pnpm/git-resolver someday!

**Comment by jnoortheen** [comment]
the same error appears when installing bokeh in version pnpm-4.6.0

**Comment by zkochan** [comment]
This was not implemented yet. So if you use the whole commit hash when installing a git-dependency.

**Comment by zkochan** [comment]
:ship: 6.7.2
