### ISSUE TITLE
pnpx --quiet is not honoured when run from bash script

### ISSUE THREAD

**Issue by qlonik** [pnpm/pnpm#1128]
### Code to reproduce the issue:

create bash script:

```bash
#!/usr/bin/env bash

pnpx -q -p webpack@4 -p webpack-cli webpack-cli test.js -o packed.js
pnpx -q google-closure-compiler-js packed.js > minified.js
```

### Expected behavior:

Lines that correspond to output of pnpm about installing `google-closure-compiler-js` would not be shown in `minified.js`

### Actual behavior:

These lines show up in the beginning of `minified.js`:
```
Packages: +21
+++++++++++++++++++++
Resolving: total 21, reused 21, downloaded 0, done

dependencies:
+ google-closure-compiler-js 20180402.0.0

```

### Additional information:

 - `node -v` prints: v9.11.1
 - `npm -v` prints: 5.8.0
 - `pnpx -v` prints: 9.6.1
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
@qlonik  you use the wrong flag. Try `--silent`

**Comment by cprecioso** [comment]
I had the same issue. If `--silent` is the correct flag, could `pnpx --help` be updated to reflect this. Currently it says to use `-q`.

**Comment by irisjae** [comment]
+1
