### ISSUE TITLE
Failed to install dependencies in Travis CI

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1129]
[This build](https://travis-ci.org/ksxnodemodules/nodemonorepo/builds/372582622) (commit https://github.com/ksxnodemodules/nodemonorepo/commit/02426132ebe5c153235e77c14c2968f48f836d95) was my attempt to use `pnpm` in Travis CI. It failed during install step:

```yaml
install:
  - pnpm recursive link --shamefully-flatten
```

```
/home/travis/build/ksxnodemodules/nodemonorepo:
 ERROR  EINVAL: invalid argument, readlink '/home/travis/build/ksxnodemodules/nodemonorepo/node_modules/@types/events'
at Error: EINVAL: invalid argume…
```

Normally, I use `yarn` in the CI, it always succeed in installing dependencies (e.g. [this build](https://travis-ci.org/ksxnodemodules/nodemonorepo/builds/372581548) for [this commit](https://github.com/ksxnodemodules/nodemonorepo/commit/9c8ec0676b10372082b586aec55fbbf7e45d0c98))

### pnpm version

Latest (Travis CI)

**Comment by zkochan** [comment]
@KSXGitHub I think it happens because you cache node_module. Try removing https://github.com/ksxnodemodules/nodemonorepo/blob/02426132ebe5c153235e77c14c2968f48f836d95/.travis.yml#L21-L22

**Comment by KSXGitHub** [comment]
@zkochan It's solved, thanks.
