### ISSUE TITLE
Jest dependency can not be found

### ISSUE THREAD

**Issue by solsson** [pnpm/pnpm#1130]
### pnpm version:

pnpm@1.41.2

### Code to reproduce the issue:

```
  "devDependencies": {
    "@types/jest": "22.2.3",
    "jest": "22.4.3",
    "ts-jest": "22.4.4",
    "ts-node": "6.0.0",
    "typescript": "2.8.3"
  }
```

### Expected behavior:

A Jest ts spec that runs after `npm install` also runs after `pnpm install`

### Actual behavior:

```
  ● Test suite failed to run

    Cannot find module 'jest-environment-jsdom'
      
      at node_modules/.registry.npmjs.org/jest-runner/22.4.3/node_modules/jest-runner/build/run_test.js:31:29

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.101s
Ran all test suites.
```

### Additional information:

 - `node -v` prints: v9.11.1
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
@solsson This is an issue with `jest-runner`. They use `jest-environment-jsdom` but it is not in its `package.json`.

You can create a `pnpmfile.js` with this content in the root of your package to hack the manifest of `jest-runner`:

```js
module.exports = {
  hooks: {
    readPackage (pkg) {
      if (pkg.name === 'jest-runner') {
        pkg.peerDependencies = pkg.peerDependencies || {}
        pkg.peerDependencies['jest-environment-jsdom'] = '*'
      }
      return pkg
    }
  }
}
```

Note: you'll have to remove node_modules and shrinkwrap.yaml and rerun `pnpm install`.

If there other issues, you could also create a flat node_modules

```
pnpm install --shamefully-flatten
```

Also, I'd create a PR to jest-runner to add jest-environment-jsdom to its package.json

**Comment by solsson** [comment]
The referencing jest issue seems to confirm that pnpm is not at fault here.

**Comment by aleclarson** [comment]
The workaround is specifying an explicit `testEnvironment` in your project's Jest config, or provide `--env=node` when running the Jest CLI.

**Comment by aleclarson** [comment]
I opened https://github.com/facebook/jest/pull/7476 to get this fixed.

**Comment by rickyras** [comment]
Follow the guide  here.   https://www.npmjs.com/package/jsdom-global

Worked for me.
