### ISSUE TITLE
"pnpm install" sometimes creates broken symlinks

### ISSUE THREAD

**Issue by pgonzal** [pnpm/pnpm#1133]
### Code to reproduce the issue:

This was happening occasionally on our CI machines.  I was able to obtain a deterministic repro for the issue, but it relies on a complex private repo that uses `file://*.tgz` references from the Rush tool.  It goes like this:

1. Clone branch # 1 and run a clean "pnpm install".
2. Checkout branch # 2 and do an incremental "pnpm install".
3. Checkout branch # 3 and do another incremental "pnpm install".

I'm pretty sure that if we delete the node_modules after step 2, the problem still occurs in step 3.  If we delete the PNPM store and node_modules folder after step 2, then step 3 succeeds.

I've sent a private email with debug logs and config files from each step.

### Expected behavior:

A valid node_modules folder.

### Actual behavior:

Although step 3 succeeds with a zero exit code, we end up with a broken  symlink:

> D:\GitRepos\spc2\common\temp\node_modules\.local\D%3A%2FGitRepos%2Fspc2%2Fcommon%2Ftemp%2Fprojects%2Foffice-ui-fabric-react-bundle.tgz\node_modules\react-dom

...which is pointing to this folder, which does not exist:

> D:\GitRepos\spc2\common\temp\node_modules\.onedrive.pkgs.visualstudio.com\react-dom\15.6.2\react@15.6.2\node_modules\react-dom

But note that this folder DOES exist and contains a valid react-dom install:

> D:\GitRepos\spc2\common\temp\node_modules\.onedrive.pkgs.visualstudio.com\react-dom\15.6.2\node_modules\react-dom

See **TheBrokenLink.txt** from my zip file for more detailed directory listings.

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by pgonzal** [comment]
BTW step 3 does print a warning `There's a directory in node_modules without package.json`.  So if we can't fix this bug easily, converting that warning to an error would be a fine mitigation.  It will cause Rush to delete everything and start over, which is no big deal for an occasional glitch.

**Comment by pgonzal** [comment]
CC @nickpape-msft @iclanton

**Comment by zkochan** [comment]
At first sight, it seems like it is related to peer dependencies resolution. But in that case, I am not sure why removing of node_modules does not solve the issue.

**Comment by zkochan** [comment]
I think I've found the issue. Pruning of node_modules removes too much. I will work on it

**Comment by zkochan** [comment]
@pgonzal please try `pnpm@1.41.3`

**Comment by pgonzal** [comment]
Yes, this fixes it.  The symlink is no longer broken, and the `node_modules without package.json` warning is no longer displayed. Thanks very much for the quick turnaround!!!

**Comment by zkochan** [comment]
No problem, I've been seeing this issue myself. The steps and the shrinkwrap files you provided helped to figure out the cause.
