### ISSUE TITLE
shrinkwrapping documentation

### ISSUE THREAD

**Issue by gilly3** [pnpm/pnpm#1136]
I can't find much information in your documentation about how shrinkwrap.yaml actually works, but I can infer a bit from options like `--frozen-shrinkwrap` and `--prefer-frozen-shrinkwrap`.  That these options exist implies to me that this isn't truly shrinkwrapping.

I'm trying to decide if pnpm is suitable for use in my production environments and build servers.  I need to be able to publish a build with entire dependency tree locked down, so that it is impossible to install the package with anything other than the prescribed dependencies.  This is the functionality I get from `npm shrinkwrap` with npm 4.

From reading issue comments, it looks like the purpose of `shrinkwrap.yaml` is, first and foremost, for performance sake, but not so much to lock down dependencies.  But, maybe I can get the same functionality if I always use `--frozen-shrinkwrap`?  This seems error prone.

I work on multiple apps that share libraries, each in their own package and repo.  I make heavy use of `npm link` (npm 4) to facilitate development.  So do my coworkers.  I certainly don't want these local dev links to be "shrinkwrapped" (in the npm 4 sense), however I'm fine with them being locally cached/optimized for performance sake.  I think it wouldn't make sense to commit `shrinkwrap.yaml`, since paths may differ between developers, and we wouldn't be using these paths on servers where my apps are installed.

I think the answer for me today is to continue using npm 4 (or maybe 5 or 6) on my build server and production servers, but that using pnpm for dev would work, as long as we add `shrinkwrap.yaml` to `.gitignore`.  But, hopefully you will consider my teams use case.  I would love to see dependency resolution caching (for performance sake) separated from locking down the dependency tree (for stability's sake).

**Comment by zkochan** [comment]
`shrinkwrap.yaml` locks down the dependency tree if the shrinkwrap file is up-to-date with the `package.json` file.

If someone edits a package.json manually and runs `pnpm install`, then pnpm will update the shrinkwrap.yaml. But then it is locked down. If you use the `--frozen-shrinkwrap` flag then pnpm will fail on out-of-date `shrinkwrap.yaml`. It is an option that you could use on a CI server.

The biggest proof that `shrinkwrap.yaml` does lock down the dependency graph is that we implemented a separate installation algorithm ([@pnpm/headless](https://github.com/pnpm/headless)) which is used when `shrinkwrap.yaml` satisfies the `package.json`. Headless installation doesn't even contain the resolution algorithms, all it can do is fetch the dependencies and create the node_modules folder using info from the shrinkwrap.yaml file

**Comment by gilly3** [comment]
Ok, that's better than I thought.

As far as linking dependencies on devloper machines via `npm link` or `pnpm link`, but _not_ doing so for servers, am I correct in assuming it best to list `shrinkwrap.yaml` in `.gitignore` and `.npmignore`?  Or is there some other means whereby differences in paths can be resolved?

**Comment by zkochan** [comment]
Your use case seems non-trivial. Usually using `pnpm link` is a temporary thing to check some changes before publishing. In that case, one would link a dependency from a local directory and once all the checks are done, `pnpm dislink` would restore the package from the registry.

If packages are linked to each other all the time, during development, I would suggest using a multi-package repo. pnpm has a special command called [pnpm recursive link](https://pnpm.js.org/docs/en/pnpm-recursive.html#pnpm-recursive-link), which links package in a monorepo and installs their deps. In this case you could commit the `shrinkwrap.yaml` files.

But returning to your initial question, in your situation ignoring the shrinkwrap.yaml files is the only solution as of now.

**Comment by zkochan** [comment]
Actually, you could still use `pnpm recursive link` in your environment. You can run `pnpm recursive link` in your `src/` folder and it will link-up everything.

**Comment by gilly3** [comment]
Well, that is handy!  I will take a look at `npm recursive link`.

Thanks for clarifying everything for me.
