### ISSUE TITLE
Skipped optional dependencies should not print warnings

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1140]
It is not an issue if an optional dependency's installation fails. However, currently pnpm prints a warning.

Changes:
- only info messages are printed when an optional dependency is skipped
- nothing is printed if the skipped optional dependency is not a direct dependency of the project

ref #1126

**Comment by vjpr** [comment]
This should be able to be silenced completely. The user should verify that a failing optional dependency is acceptable but specifying the dep in a config file.

**Comment by zkochan** [comment]
You mean not printing an info message even for the skipped root optional deps? I think that's too match. There could be different reasons for a failing optional deps. Maybe it just requires Node.js 10. I would like to see that printed and maybe I'd just switch to Node.js 10 to satisfy the dependency.
