### ISSUE TITLE
Run hooks against all nested packages to ensure manifest modifications occur

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1151]
If I modify a `pnpmfile.js` its not guaranteed to affect nested deps unless I use `pnpm update --depth=99`.

But most of the time I don't want to `update` my deps, just have the missing one installed.

## Example

Say I want to add a missing dep `bar` of `foo` which is a package I depend on...

Is it correct that `pnpm update foo` updates to the latest version of `foo` satisfying the range in `package.json`?

If there is an update, the missing dep will be added.

If not, nothing will change.

If I add `pnpm update foo --depth=99` it will install the missing dep `bar`...but will also update its sub-deps too which might not be what I want because it could introduce new problems - especially if running this command in a monorepo with potentially 100s of usages.

So what is missing is the ability to target a specific sub-dep.

Otherwise, you can't be certain pnpmfile modifications have occurred and it makes it frustrating to use. Your co-workers can't just checkout your code and run `pnpm i` and expect it to work. I the pnpmfile has changed, they must run `pnpm update --depth=99` (or `pnpm i --force`?) which would break stuff.

Ideally, `pnpm install` should make sure `pnpmfile.js#addPackage` hooks are always run, but of course this would be very slow.

What about a command to run all dependencies against the `pnpmfile.js` to check for changes. Something like: `pnpm install --run-hooks-against-all-nested-packages`.

This would still be slow...so how about a more declarative approach instead of the programmatic addPackage hook. Allowing you to specify the paths to each dep you want to modify, instead of having to run the hook at every nested package?

I think this might be why yarn `resolutions` make you specify the nested location of the dep you want to modify.

**Comment by zkochan** [comment]
I don't have objections against the declarative format.

Also, I have an idea how to make this work with pnpmfile as well. pnpmfile may return a field (something like `id` or `integrity`). This field will be added to `the shrinkwrap.yaml`. Every time the values mismatch, the lockfile is recreated with the pnpmfile.

So you can either bump the value of this id field every time you make modifications or you can implement some smarter logic.

**Comment by zkochan** [comment]
Use [packageExtensions](https://pnpm.io/package_json#pnpmpackageextensions) they work as you described.
