### ISSUE TITLE
Shortcut for --shamefully-flatten

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1156]
After some time, it gets really boring to type `--shamefully-flatten` all the time.

So I think a shortcut might be preferred like `pnpm i -SF` or something more suitable :)

**Comment by deadcoder0904** [comment]
Also one question - does `--shamefully-flatten` save space too❓

**Comment by zkochan** [comment]
yes, it does save space but it is slower.

Did you know that you could create a `.npmrc` file in the root of your project and set `shamefully-flatten = true` in it. In that case you won't need to run `pnpm install` with the flag.

**Comment by deadcoder0904** [comment]
Didn't know that, thanks

Close it if you want

**Comment by zkochan** [comment]
ok, I am closing it because there is no good available shortcut. `-f` is for `--force`
