### ISSUE TITLE
install of some packages giving invalid modification timestamps on resulting files

### ISSUE THREAD

**Issue by davetpet** [pnpm/pnpm#1164]
### pnpm version:
1.41.3
### Code to reproduce the issue:
create package file:
{
      "name": "packageName"
      "dependancies": {
           "regexpp": "1.0.1"
       }
}

do 
pnpm install 
### Expected behavior:
files in node_modules would have valid dates

### Actual behavior:
modified dates of files are "unknown".   If you TAR them, they show as 1969-12-31 17:00

### Additional information:

same package file with npm installs with modified dates being set to date/time the npm install occurred

 - `node -v` prints: 9.8.0
 - Windows, OS X, or Linux?: Linux - ubuntu 18.04.

**Comment by dianasaurio** [comment]
I have the same issue in OS X. I'm adding a screenshot.
<img width="576" alt="pnpm" src="https://user-images.githubusercontent.com/3301324/43405633-df77d53e-93df-11e8-819b-a35ac9fa893b.png">

**Comment by mcmxcdev** [comment]
Cannot reproduce this with pnpm v7.5.0

The modification timestamps of `regexpp` show up with today's date.
