### ISSUE TITLE
Side effects cache is not used when packageImportMethod is hardlink (default)

### ISSUE THREAD

**Issue by etamponi** [pnpm/pnpm#1167]
`packageImportMethod: "hardlink"` uses a manifest of the files to copy to the destination node_modules directory. This manifest is not updated with the content of the side effects cache, causing the cache to be completely ignored.

Other import methods are not affected as they use a variant of `cp -R` instead of relying on the manifest.

Two possible solutions:

1. Create a manifest of the files in the cache and use it.
2. Ignore the manifest when the cache is available.

**Comment by zkochan** [comment]
Not sure what this is about. Probably not an issue in the latest pnpm.
