### ISSUE TITLE
Breaking changes for v3

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1173]
-  ~changing the way packages are installed globally. Their node_modules should be separated. Like when they are installed with npm~
- ~when a package is installed globally and it has a `shrinkwrap.yaml` published by itself, use the `shrinkwrap.yaml` to install~
- [ ] by default, don't verify store integrity on CI servers
- ~only read `pnpmfile.js` when there is a pnpmfile config specified~
- [x] deprecate the `--scope` flag
- [x] use ES2017 as target for typescript
- [x] `-r` is not an alias of `--registry`
- [x] make breaking store server API changes
- ~pnpm storage should have the same format as the verdaccio storage~
- ~typescript code is compiled to dist folder (optional)~
- ~`--` filter works with all commands~ - the community votes against this

**Comment by vjpr** [comment]
> changing the way packages are installed globally. Their node_modules should be separated. Like when they are installed with npm

Can you explain this one again?

**Comment by zkochan** [comment]
:ship: 3.0.0
