### ISSUE TITLE
pnpm link causing permission errors on Windows where npm link does not

### ISSUE THREAD

**Issue by ghost** [pnpm/pnpm#1175]
I wanted to do a `pnpm link` in one private package to use it in another one of my private packages. However I got the following error:
```
C:\Program Files\nodejs\pnpm-global\node_modules\test-package -> C:\Source\test-package
 ERROR  EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\pnpm-global\node_modules'
```
I tried the very same with `npm` and noticed it stores the link in the `AppData` folder which ends up like this:
```
C:\Users\Near\AppData\Roaming\npm\node_modules\test-package -> C:\Source\test-package
```
I'd like to know how I can setup `pnpm` s.t. it stores global packages somewhere where I have actual write access.

**Comment by zkochan** [comment]
Related: #928

**Comment by zkochan** [comment]
The global dir is change in pnpm v7, should not be an issue anymore.
