### ISSUE TITLE
ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1178]
### pnpm version:

2.0.0

### Code to reproduce the issue:

1. Install Node.js v10.1.0
2. Run `pnpm install anypackage`

### Expected behavior:

No warnings.

### Actual behavior:

This warning appears:

```
(node:16514) ExperimentalWarning: The fs.promises API is experimental
```

### Additional information:

 - `node -v` prints: v10.1.0
 - Windows, OS X, or Linux?: Linux

**Comment by paulpflug** [comment]
updating fs-extra to 6.0.1 should fix this
https://github.com/jprichardson/node-fs-extra/pull/578

**Comment by paulpflug** [comment]
I know.
I didn't write that info for you, but for @zkochan, so he knows how to resolve this issue without researching for himself.

**Comment by zkochan** [comment]
seems like we have that fix already in pnpm, so the warning is printed by mz https://github.com/normalize/mz/issues/63

**Comment by Ore4444** [comment]
For anyone this might be useful for:

https://stackoverflow.com/questions/50441890/experimentalwarning-the-fs-promises-api-is-experimental/52915615#52915615
