### ISSUE TITLE
pnpm link doesn't resolve path properly

### ISSUE THREAD

**Issue by paulpflug** [pnpm/pnpm#1180]
### pnpm version:
2.1.0
### Code to reproduce the issue:
```
pnpm link
```

### Expected behavior:
Create link to `~/.npm-global/pnpm-global/node_modules/pkgname`

### Actual behavior:
Creates link to `{{cwd}}/~/.npm-global/pnpm-global/node_modules/pkgname`

### Additional information:

 - `node -v` prints:
v10.1.0
 - Windows, OS X, or Linux?: 
Linux

( I tried it with pnpm@1 - same problem, maybe it is node 10.1 related?)

**Comment by paulpflug** [comment]
I pinpointed the problem to a wrong `globalPrefix` coming from `npm-conf`
But that package didn't change, so I'm not sure why the problem comes now.
I have a `~/.npmrc` with `prefix:'~/.npm-global'`
To test I did the following
```sh
mkdir tmp && cd tmp
npm i npm-conf
node
```
```js
t = require("npm-conf")()
t.globalPrefix // {{cwd}}/~/.npm-global
t.prefix // {{cwd}}
```
I tested reverting to node@9 and npm@5, but this didn't change. I'm using n for version management.

**Comment by zkochan** [comment]
This won't be an issue with pnpm v7
