### ISSUE TITLE
Error UKNOWN for readlink on windows machine

### ISSUE THREAD

**Issue by xbtsw** [pnpm/pnpm#1193]
### pnpm version:
2.0.0, also observed with 1.41.3
### Code to reproduce the issue:
N/A

### Expected behavior:
pnpm should install the dependencies as expected.
### Actual behavior:
pnpm will occasionally fail on `pnpm install` with following error:
```json
2018-05-29T21:25:38.8582361Z{  
   "time":1527629138858,
   "hostname":"APP-VSTSBP-075",
   "pid":4152,
   "level":"error",
   "name":"pnpm",
   "message":{  
      "errno":-4094,
      "code":"UNKNOWN",
      "syscall":"readlink",
      "path":"C:\\_work\\19\\s\\node_modules\\.registry.npmjs.org\\@webassemblyjs\\wasm-parser\\1.4.2\\node_modules\\@webassemblyjs\\wasm-parser"
   },
   "err":{  
      "name":"Error",
      "message":"UNKNOWN: unknown error, readlink 'C:\\_work\\19\\s\\node_modules\\.registry.npmjs.org\\@webassemblyjs\\wasm-parser\\1.4.2\\node_modules\\@webassemblyjs\\wasm-parser'",
      "code":"UNKNOWN",
      "stack":"Error: UNKNOWN: unknown error, readlink 'C:\\_work\\19\\s\\node_modules\\.registry.npmjs.org\\@webassemblyjs\\wasm-parser\\1.4.2\\node_modules\\@webassemblyjs\\wasm-parser'"
   }
}
```
### Additional information:

 - `node -v` prints: 8.11.1
 - Windows, OS X, or Linux?: Windows

**Comment by xbtsw** [comment]
Encountered a new kind of failure just now:
```
Error: EPERM: operation not permitted, rename 'C:\_work\21\s\node_modules\.registry.npmjs.org\@webassemblyjs\wasm-parser\1.4.2\node_modules\@webassemblyjs\_tmp_8_f104fbf47d03cc225f36a0d94f262dc7' -> 'C:\_work\21\s\node_modules\.registry.npmjs.org\@webassemblyjs\wasm-parser\1.4.2\node_modules\@webassemblyjs\wasm-parser'
```

**Comment by xbtsw** [comment]
@zkochan when these error happens pnpm doesn't seem to produce a `pnpm-debug.log` in the current working folder. And these seems only occasionally happens in our CI machines. Do you have any pointers for me if I want to look into it?

**Comment by zkochan** [comment]
The second issue that you described happens [here](https://github.com/pnpm/package-store/blob/master/src/fs/linkIndexedDir.ts#L13).

**Comment by xbtsw** [comment]
The second case smells like a file system race condition. `stage` should indeed exist on the disk at line 13. Out of few hundreds CI run the second case only happened one time though.

Aside from adding a retry around line 13 I don't see what else can be done at pnpm level.

**Comment by xtuc** [comment]
Has this something to do with `webassemblyjs`? We had issues in the past with cyclic deps, pnpm and windows.

**Comment by zkochan** [comment]
@xtuc I believe we fixed the issue with `webassemblyjs`. If there are still issues, feel free to file a new issue

**Comment by zkochan** [comment]
@xbtsw did you run pnpm with the `--shamefully-flatten` flag or do you have it set to true? (You can check via `pnpm get shamefully-flatten`)

**Comment by xbtsw** [comment]
Just to add some information, out of the ~120 CI runs that failed, it looks like the issue always happen when `pnpm` trying to operate on `@webassemblyjs\wasm-parser`. I am not sure if that's coincidence.

**Comment by zkochan** [comment]
This happens on a clean install or when a node_modules already exists?

Can you attach the `pnpm-debug.log` file?

**Comment by xbtsw** [comment]
When this happens there seems to be no `pnpm-debug.log` file generated. The CI machines always start from a clean slate with fixed nodejs version (8.11.1) and pnpm version (2.0.0) and empty working folder.

I install pnpm with this command:
```
npm install -g --registry https://registry.npmjs.org/ --always-auth false pnpm@2.0.0
```

and run it with
```
pnpm install --frozen-shrinkwrap --reporter=silent --store=.\bin\pnpm
```

I will bump the pnpm to latest version (2.13.5) today and see if the problem goes away.

**Comment by xbtsw** [comment]
@zkochan Thanks for the suggestion. I tested couple of versions, with 2.16.2 (latest). It consistently fail with a `pnpm-debug.log` file produced and always fail with the same package (enzyme)
```
2018-09-28T23:36:39.7083012Z   23747 error pnpm: 
2018-09-28T23:36:39.7083189Z     message: 
2018-09-28T23:36:39.7083300Z       errno: -4094
2018-09-28T23:36:39.7083411Z       code: "UNKNOWN"
2018-09-28T23:36:39.7083574Z       syscall: "readlink"
2018-09-28T23:36:39.7083745Z       path: "C:\\_work\\1\\s\\node_modules\\@types\\enzyme"
2018-09-28T23:36:39.7085401Z     err: 
2018-09-28T23:36:39.7086717Z       name: "Error"
2018-09-28T23:36:39.7089908Z       message: "UNKNOWN: unknown error, readlink 'C:\\_work\\1\\s\\node_modules\\@types\\enzyme'"
2018-09-28T23:36:39.7092650Z       code: "UNKNOWN"
2018-09-28T23:36:39.7094514Z       stack: "Error: UNKNOWN: unknown error, readlink 'C:\\_work\\1\\s\\node_modules\\@types\\enzyme'"
```

With 2.13.5 it reliably worked and installed the dependencies successfully.

**Comment by zkochan** [comment]
:ship: [2.17.5](https://github.com/pnpm/pnpm/releases/tag/v2.17.5)
