### ISSUE TITLE
Enhance error messages by removing stack trace (?)

### ISSUE THREAD

**Issue by donaldpipowitch** [pnpm/pnpm#1194]
### pnpm version:

v2.0.0

### Code to reproduce the issue:

```
$ pnpm install typescript@17
```

### Expected behavior:

```
 ERROR  No compatible version found: typescript@>=17.0.0 <18.0.0
Versions in registry:
0.8.0, 0.8.1, 0.8.1-1, 0.8.2, 0.8.3, 0.9.0, 0.9.0-1, 0.9.1, 0.9.1-1...
```

### Actual behavior:

```
 ERROR  No compatible version found: typescript@>=17.0.0 <18.0.0
Versions in registry:
0.8.0, 0.8.1, 0.8.1-1, 0.8.2, 0.8.3, 0.9.0, 0.9.0-1, 0.9.1, 0.9.1-1...

at Error: No compatible version …
at at /home/pipo/n/lib/node_modu…  pnpm/npm-resolver/lib/index.js:87
at next
at fulfilled                       …dules/@pnpm/npm-resolver/lib/index.js:4
at _tickCallback                   internal/process/next_tick.js:68
```

---

_Personal opinion_ here, but from my personal experience I believe that these "expected errors" (e.g. no runtime errors, because of unknown bugs in your code) can be more user friendly and easier to read if the stack trace isn't included in the output. (Especially because it is included in the `pnpm-debug.log`, if you _really_ need it.)

Maybe we can have a community vote here? (If needed.)

**Comment by zkochan** [comment]
I agree, for known error codes pnpm does not print the stacktrace (https://github.com/pnpm/pnpm/blob/master/packages/default-reporter/src/reportError.ts#L15)

This error shouldn't print a stacktrace as well

**Comment by zkochan** [comment]
:ship: v2.5.0

**Comment by zkochan** [comment]
I don't guarantee that all known errors were fixed but now if the error has a code prefixed with `ERR_PNPM_` stacktrace won't be printed.

**Comment by donaldpipowitch** [comment]
Man you work too much. Kudos for you and this project 😍

**Comment by aleclarson** [comment]
@zkochan Could you add an environment variable that shows all stack traces, please? 😄

**Comment by zkochan** [comment]
there should be `pnpm-debug.log` file with the stacktrace. Probably in the global folder, when you install globally
