### ISSUE TITLE
Enhance "404" error

### ISSUE THREAD

**Issue by donaldpipowitch** [pnpm/pnpm#1196]
### pnpm version:

v2.0.0

### Code to reproduce the issue:

```
$ pnpm install @foo/bar
```

### Expected behavior:

```
$ pnpm install @foo/bar
 ERROR  Could not found "@foo/bar" in "https://registry.npmjs.org".
```

### Actual behavior:

```
$ pnpm install @foo/bar
 ERROR  404 Not Found: @foo/bar
```

---

There are probably at least two main cases for 404s:
- Wrong registry was used.
- Misspelled package name.

The first case can be covered quite easily I think by including the used registry name in the error output. For the 2nd case we would probably need a npm API to find packages with similar names (like `$ pnpm install reatc` -> `Did you mean "react"?`), but I don't know if such an API exists...?

**Comment by zkochan** [comment]
:ship: v2.5.0

**Comment by donaldpipowitch** [comment]
Wow 😍
