### ISSUE TITLE
Cannot create shrinkwrap.yaml because raw manifest wasn't fetched

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1201]
```
 ERROR  Cannot create shrinkwrap.yaml because raw manifest (aka package.json) wasn't fetched for 
"registry.npmjs.org/@babel/plugin-syntax-class-properties/7.0.0-beta.49/@babel!core@7.0.0-beta.49"
```

Just encountered this. Not sure how it could happen...

### Additional information:

 - `node -v` prints: 8.9
 - Windows, OS X, or Linux?: macOS

**Comment by vjpr** [comment]
This happened after upgrading. I deleted the `shrinkwrap.yaml` and it works now.

**Comment by zkochan** [comment]
I think I know why this happens. I will try to fix it this weekend

**Comment by zkochan** [comment]
:ship: 2.2.2
