### ISSUE TITLE
Module that works with npm fails with pnpm

### ISSUE THREAD

**Issue by NetOperatorWibby** [pnpm/pnpm#1205]
### pnpm version:

2.2.2

### Code to reproduce the issue:

Just `pnpm i vne` and start your Node server.

### Expected behavior:

Retrieve `.env` file and its contents

### Actual behavior:

Error by `pnpm` looking in my project's dependencies for an `.env` file that does not exist.

### Additional information:

node version 10.3.0 on macOS High Sierra (latest "stable"...lol)

**Comment by zkochan** [comment]
@NetOperatorWibby I could not reproduce your issue.

I created a project with this `.env` in the root:

```
FOO=foo1
BAR=bar1
BAZ=1
QUX=
```

and this `index.js`:

```js
const env = require("vne")

console.log(env);
```

I executed `node index.js` and everything worked:

```
{ FOO: 'foo1', BAR: 'bar1', BAZ: '1', QUX: '' }
```

**Comment by NetOperatorWibby** [comment]
@zkochan What if your `.env` file looks like this?

```
FOO-BAR=foo1
BAR-FOO=bar1
BAZ-ZAB=1
```

**Comment by zkochan** [comment]
it prints:

```
{ FOO: { BAR: 'foo1' }, BAR: { FOO: 'bar1' }, BAZ: { ZAB: '1' } }
```
