### ISSUE TITLE
`Cannot read property 'prefix' of undefined` with no stack trace during `pnpm recursive link`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1206]
```
$ pnpm recursive link
Cannot read property 'prefix' of undefined
(node:19649) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

The second time it worked fine.

The issue is that it is not possible to see where the error came from. And because its recursive, its hard to find which package the `pnpm-debug.log` file is in.

1. Show the package of the error.
2. Maybe create symlinks to each pnpm debug file in the root dir `.pnpm/logs/package-foo.log`

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
`pnpm recursive link` is deprecated. If there are similar issues with `pnpm recursive install` + `link-workspace-packages` then we'll fix it
