### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [pnpm/pnpm#1207]
... at least on Windows.

Tried out pnpm for the first time today and found that it felt somehow... laggy.
So I benchmarked execution times for all package managers I have installed (100x the same command per manager) using powershell:

```
Measure-Command { For($i=0; $i -le 100; $i++) { npm run doesntexist 2> $null } }
# 64 sec.

Measure-Command { For($i=0; $i -le 100; $i++) { pnpm run doesntexist 2> $null } }
# 187 sec.

Measure-Command { For($i=0; $i -le 100; $i++) { yarn run doesntexist 2> $null } }
# 46s sec.


Measure-Command { For($i=0; $i -le 100; $i++) { npm info react 2> $null } }
# 112 sec.

Measure-Command { For($i=0; $i -le 100; $i++) { pnpm info react 2> $null } }
# 222 sec.

Measure-Command { For($i=0; $i -le 100; $i++) { yarn info react 2> $null } }
# 64 sec.
```

Considering how speed is the thing you focus on aside from saving disk space when it comes to marketing for pnpm, I figured that you might want to be aware of this.

 - `npm -v` prints: v6.1.0
 - `pnpm -v` prints: v2.2.2
 - `yarn -v` prints: v1.7.0
 - `node -v` prints: v10.4.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
there are some commands that are currently passed through to npm. These are the commands that currently have implementations in pnpm: https://github.com/pnpm/pnpm/blob/1a9dbf87f2d62e4a404d97d7c74c79a387521188/packages/pnpm/src/main.ts#L32-L49

Also, you can check/use this project to compare performance: https://github.com/pnpm/node-package-manager-benchmark

**Comment by zkochan** [comment]
Except for `run`, it is also passed through to npm https://github.com/pnpm/pnpm/blob/1a9dbf87f2d62e4a404d97d7c74c79a387521188/packages/pnpm/src/cmd/run.ts#L1-L11

Currently we mostly concentrate on install/update speed

**Comment by s-h-a-d-o-w** [comment]
Personally, I'm more irritated by laggy simple commands than install speed because when I run `npm/yarn/pnpm install`, I'm not sitting there waiting. But I am when I use commands like `run`, `info`, etc.
But... that's my opinion.

What makes me suspicious is why simply piping something through takes that long. (Merely spawning something with inherited io causes an overhead of ~80ms on my machine.)
Anyway... as I said in my very first post - it's just an observation. :smile:
