### ISSUE TITLE
Use realpath for symlink source and target when running `pnpm recursive link`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1208]
I have two projects and one symlinks a directory of packages (a partial monorepo) from the other.

```
- /app1
  - packages
    - public
      - foo (depends on `bar`)
        - node_modules
          - bar -> symlinked to `../../bar`
      - bar
        
        
- /app2
  - packages
    - public -> symlinked to `/app1/packages/public`
      - foo
      - bar
```        

After running `pnpm recursive link` in `/app2`, `bar` is now symlinked to `/app1` like so:

```
- /app2
  - packages
    - public -> symlinked to `/app1/packages/public`
      - foo
        - node_modules
          - bar -> after `recursive link`, it links to `../../../../../app1/packages/public/bar`
      - bar
```

My goal is to be able to run `pnpm recursive link` in `/app1` or `/app2` and the symlinks for `packages/public` are always the same.

### Expected behavior:

The link target should not use the realpath (instead using the normal symlinked path).

### Actual behavior:

The link target uses the realpath.

So,

`/app2/packages/public/foo/node_modules/bar` creates a relative link to `/app1/packages/public/bar` which resolves to `../../../../../app1/packages/public/bar`.

`/app2/packages/public/foo/node_modules/bar` should target `/app2/packages/public/bar` which should resolve to `../../bar`.

### Additional information:

 - `node -v` prints: 8.9.0
 - Windows, OS X, or Linux?: macOS

**Comment by vjpr** [comment]
I think a workaround might be to relatively symlink `packages/public` instead of using an absolute symlink.

```
- /app2
  - packages
    - public (symlink to `../../../app1/packages/public` instead of `/app1/packages/public`)
```

**Comment by vjpr** [comment]
The fix is to use realpaths for symlinks.

https://github.com/pnpm/pnpm/blob/b546581dd385d8032bc9680c0714d89a51e28fb0/packages/supi/src/api/link.ts#L154-L158

```
async function linkToModules (pkgName: string, linkFrom: string, modules: string) {

  modules = require('fs').realpathSync(modules)
  linkFrom = require('fs').realpathSync(linkFrom)

  const dest = path.join(modules, pkgName)
  linkLogger.info(`${dest} -> ${linkFrom}`)
  await symlinkDir(linkFrom, dest)
}
```

https://github.com/pnpm/pnpm/blob/b546581dd385d8032bc9680c0714d89a51e28fb0/packages/supi/src/link/index.ts#L452-L455

There also seems to be a bug that during `pnpm recursive link`, `symlinkDir` is called twice for the same package from two different locations/stages(?).

**Comment by zkochan** [comment]
I think only the 1st change is needed. The other two should not be a problem if this will be fixed:

> There also seems to be a bug that during pnpm recursive link, symlinkDir is called twice for the same package from two different locations/stages(?).

**Comment by zkochan** [comment]
Currently, I have a few other issues in priority, so if you could create a PR, it would be great

**Comment by vjpr** [comment]
@zkochan This seems to have broken after `shared-workspace-packages`.
