### ISSUE TITLE
Allow filtering which packages to run `recursive link` on

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1213]
At present it seems that `pnpm-workspace.yaml` is the only way to specify what packages to install/link.

**Use case**

If you have a large monorepo with several apps. 

If you want to deploy only one app, you may not want the other apps in install and link during `recursive link` because it would be time consuming

Or, you may not want to copy the other apps to a server during deploy (if you are running `pnpm recursive link` remotely).

For this, there needs to be a way to filter which packages to run `recursive link` on.

**Possible solution**

`pnpm-workspace.yaml` is used to indicate where to search for packages.

Then, `pnpm recursive link foo bar` would locate packages `foo` and `bar`, and if there are local dependencies available, they would install/link those too.

`pnpm recursive link` would still run install/link on all packages in `pnpm-workspace.yaml`.

**Comment by zkochan** [comment]
Lerna has a flag called `--scope <pkg>`. With `--include-filtered-dependencies` it will include the dependencies. Maybe we could have a similar flag but I think we should include dependencies by default.

**Comment by zkochan** [comment]
IMHO, it wouldn't make sense for the `pnpm recursive link` command to scope packages w/o their dependencies.

 Maybe we could have some other flag that would work on other commands, like `pnpm recursive rebuild --only-package smth`

**Comment by zkochan** [comment]
:ship: 2.6.0
