### ISSUE TITLE
Request: Use Windows links when in WSL

### ISSUE THREAD

**Issue by Conduitry** [pnpm/pnpm#1215]
I'm not sure how feasible this is, but - It would be really nice if, when pnpm detects that it is running under WSL in a `/mnt/...` directory, that it would create whatever type of links it creates when running natively on Windows, as opposed to the WSL symlinks (which creates a file that is completely opaque to Windows). This would, among other things, hopefully let editor plugins see the installed node modules in a project.

It _appears_ that there is already some special WSL handling, because when I use pnpm from a `/mnt/...` directory in WSL (even if I'm accessing it from a symlink under e.g. `/home/...`), the `.pnpm-store` automatically ends up in a special place on the Windows disk (i.e., not in WSL `~/.pnpm-store` and not in `%USERPROFILE%\.pnpm-store`).

**Comment by zkochan** [comment]
So you'd like pnpm to create junctions when running inside WSL?

@etamponi you also use WSL, do you have issues with symlinks?

I think what we could do is adding a config for choosing between symlinks and junctions. I am not sure junctions are available on non-windows filesystems. Do they work inside WSL?

**Comment by Conduitry** [comment]
Yes, I suppose that I would like pnpm to create junctions when run in WSL and when it's installing to a directory that's inside a mounted host filesystem drive. What it's doing now (creating a Linux symlink) works fine from within WSL - but on the host filesystem this just creates an unreadable file. This is inconvenient when something running under Windows (e.g. an editor) expects to be able to see certain packages for its own typescript/prettier/eslint/etc plugins.

**Comment by HyperBrain** [comment]
@Conduitry One workaround (not a solution) is, to use linux tools instead of windows ones. E.g. I use VSCode in WSL (together with VcXsrv) which works perfectly.

**Comment by etamponi** [comment]
I think that on WSL we should behave exactly as if we were on Linux, using
Unix links. It might be annoying in certain cases, but I don't think we
should change this.

Il sab 7 lug 2018, 16:38 Frank Schmid <notifications@github.com> ha scritto:

**Comment by Conduitry** [comment]
@HyperBrain Interesting. I'm certainly willing to give that a try for a bit. I think I've sort of gotten this working, but what I had to do to get vscode installed inside WSL (along with dependencies) didn't feel great, and I'm running into some other flakiness. Could you give the steps you used to install vscode inside a fresh WSL (running xenial)? And then I assume you're running vscode with `DISPLAY=:0 code`. Thanks!

**Comment by HyperBrain** [comment]
@Conduitry The steps mentioned in the issue description here https://github.com/Microsoft/WSL/issues/2760 worked for me -> In short: add the VSCode PPA, Install "code" (I don't remember if I installed the mentioned libs before) and start dbus with "sudo service dbus start". The dbus startup is best in the startup. The only thing for me is, that I could not use LIBGLINDIRECT but software rendering because my Intel graphics driver does not support OpenGL correctly.

**Comment by Conduitry** [comment]
Oh huh I'm not sure when it happened, but I just noticed that as of pnpm 2.11.3 it looks like the links created under WSL are now Windows links as opposed to WSL's own links. Was this intentional?

**Comment by Conduitry** [comment]
Okay interesting - Windows 10 developer mode was enabled on one machine but not the other (probably left over from when it was necessary to have it on to use WSL?). When I turn developer mode on on the other machine, the symlinks that pnpm creates are now Windows links there too.

**Comment by Conduitry** [comment]
I'm going to close this. I'm quite happy with the solution of having developer mode on.

I'm actually not sure there's any non-developer-mode solution that could exist. IIRC one of the things that developer mode changes is to make it so that Windows directory links can be created as a non-administrator.

**Comment by nareddyt** [comment]
Thanks for updating this issue! Also confirmed that enabling developer mode allows for WSL to create windows directory links. This means tools like Webstorm will be able to read the packages!

I'll look into updating the FAQ in /pnpm/pnpm.github.io

**Comment by squareloop1** [comment]
This does not seem to work for WSL2. Symlinks are not working in my IDE and therefore pnpm is unusable, even with developer mode on.

**Comment by Conduitry** [comment]
It's working for me in WSL2. I can create a relative symlink within `/mnt/c/` and it appears as a Windows directory link.

**Comment by squareloop1** [comment]
> It's working for me in WSL2. I can create a relative symlink within /mnt/c/ and it appears as a Windows directory link.

You're right. It is indeed working when creating the symlink in /mnt/c/. However, creating the links anywhere else inside WSL2 does not create a symlink thats usable from the windows host. But to profit from WSL2 file speeds the code has to be inside WSL2 (e.g. ~/projects) instead of /mnt/c.

The speed difference is too huge to just neglect in favor of usable symlinks. Projects are loading super slow outside WSL2 file system.
