### ISSUE TITLE
Support yarn’s resolutions package.json field

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#1221]
Yarn defines the `resolutions` field to allow overriding the sub-dependencies of dependencies.

eg. if you depend on package `foo@1`, which has a dependency on `bar@1`, and you set the value of `bar` in `resolutions` to `2`, then all dependencies which depend on `bar` will get `bar@2`, regardless of which version they have defined in their `package.json` file.

Yarn does this to allow for fully flat `node_modules` to emulate how [Bower](https://bower.io) works.

**Comment by zkochan** [comment]
This is currently possible to achieve with pnpm, using [hooks](https://pnpm.js.org/docs/en/hooks.html)

```js
module.exports = {
  hooks: {
    readPackage
  }
}

function readPackage (pkg) {
  if (pkg.dependencies && pkg.dependencies.foo) {
    pkg.dependencies.foo = '2'
  }
  return pkg
}

```

**Comment by ExE-Boss** [comment]
While I get that pnpm’s hooks are more powerful, the issue is that when using pnpm to install a yarn project, forgetting to convert the `resolutions` key to pnpm hooks beforehand can potentially lead to unexpected behaviour.

**Comment by zkochan** [comment]
You can write a hook that will use Yarn's resolutions, I guess.

But pnpm cannot adhere all the resolutions that are possible to declare by Yarn's resolution syntax.

For instance, you can set:

```json
  "resolutions": {
    "d2/left-pad": "1.1.1",
    "c/**/d2/left-pad": "1.1.2"
  }
```

However, pnpm only allows one dependency set for a package/version inside node_modules. So in one `project/node_modules` there cannot be `d2@1.0.0` with `left-pad@1.1.1` and `left-pad@1.1.2`

**Comment by errorx666** [comment]
This feature is the main reason I use yarn, and without it I'm not going to switch.
I don't need the sub-submodule edge case that's shown as problematic, but I definitely need to be able to force submodules to specific versions.  I.e., just the `"foo": "1.0.0"` and `"foo/bar": "1.0.0"` models.
If you run into a combination that can't be satisfied, throw an error.

**Comment by errorx666** [comment]
I also want to point out that using a hook script to handle this rather than a declarative format violates the rule of least power.

https://en.wikipedia.org/wiki/Rule_of_least_power

**Comment by zkochan** [comment]
There is actually a way to do it in a declarative way already. Though it won't throw an error.

When resolving dependencies, pnpm will prefer a version that satisfies the range declared in the root `package.json`. So if you would like pnpm to prefer installing version 1.0.0 or 2.1.0 in node_modules, you can add foo to the dependencies with this spec:

```json
"foo": "1.0.0 || 2.1.0"
```

**Comment by aleclarson** [comment]
I'm a little confused. Do I need to use hooks to override a sub-dependency? Or am I missing something?

**Comment by yuyaryshev** [comment]
I've made a pnpmfile.js for the ones who want "restrictions" in package.json.
Just extract it and place pnpmfile.js near package.json.

[pnpmfile.zip](https://github.com/pnpm/pnpm/files/2935985/pnpmfile.zip)

**Comment by PabloSzx** [comment]
> I've made a pnpmfile.js for the ones who want "restrictions" in package.json.
> Just extract it and place pnpmfile.js near package.json.

I guess that script is outdated, so I updated it and made a better version of it with some feedback.



`pnpmfile.js`
```js
const { resolutions } = JSON.parse(
  require("fs").readFileSync("./package.json", "utf-8")
);

if (resolutions) {
  module.exports = {
    hooks: {
      readPackage,
    },
  };

  function readPackage(pkg, context) {
    if (pkg.dependencies) {
      for (const k in resolutions) {
        if (pkg.dependencies[k] && pkg.dependencies[k] !== resolutions[k]) {
          context.log(
            `"${k}@${pkg.dependencies[k]}" overriden in "${pkg.name}" to "${k}@${resolutions[k]}"`
          );
          pkg.dependencies[k] = resolutions[k];
        }
      }
    }

    return pkg;
  }
} else {
  module.exports = {};
}

```

**Comment by zkochan** [comment]
npm also works on its own format: https://github.com/npm/rfcs/pull/129

**Comment by ianwalter** [comment]
Another benefit to the static resolutions approach vs pnpmfile hooks is that they are used by third parties like dependency management (hosted Renovate) which will ignore the pnpmfile because they don't want to run untrusted code.

**Comment by zkochan** [comment]
I'll work on this

**Comment by zkochan** [comment]
:ship: 5.10.0-0

**Comment by zkochan** [comment]
I just realized that the way I implemented this behaves more like npm's "overrides" spec. Might be better to rename the field to "overrides" instead.

Unlike the Yarn resolutions, pnpm resolutions allow using ranges or even aliases to override a version. So this is valid in the resolutions I implemented:

```json
"resolutions": {
  "foo@1": "npm:bar@2",
  "zoo": "^1.0.0",
  "qar": "1.0.0"
}
```

**Comment by zkochan** [comment]
I created a new PR #2946 to implement `pnpm.overrides` instead.

**Comment by tnzk** [comment]
I understand this is not right place to ask, but hoping someone here with context answer: so, pnpm doesn't support and _does_ ignore "resolutions" field in package.json?

**Comment by paulius-valiunas** [comment]
> I understand this is not right place to ask, but hoping chances are someone here with context answer: so, pnpm doesn't support and _does_ ignore "resolutions" field in package.json?

I came here looking for an explanation too. I was using `npm-force-resolutions` before, and I just removed the preinstall hook when moving to pnpm. Now I have this in my pnpm-lock.yaml, so I assume it worked:

```yaml
overrides:
  glob-parent: 5.1.2
  nanoid: 3.1.31
```

I can't find anything about this behavior in the documentation, so I'll probably move my `resolutions` object to `pnpm.overrides`.

**Comment by zkochan** [comment]
`resolutions` will work also but prefer to use `pnpm.overrides`.
