### ISSUE TITLE
Show a diff with/without `pnpmfile.js` when running `pnpm ls`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1222]
After I run an install I want to see what packages are being overridden, and which packages are no longer being overridden (which may need to be patched again).

Maybe a good reason to move to a declarative readPackage api (https://github.com/pnpm/pnpm/issues/1082).

**Comment by zkochan** [comment]
We are trying to make everything declarative. Hooks are still supported but I don't think they need to be frequently used.
