### ISSUE TITLE
`pnpm recursive exec`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1227]
Same as lerna.

Maybe we can make use of https://www.npmjs.com/package/@lerna/exec

**Comment by zkochan** [comment]
@vjpr I wonder if it would be better if worked as `pnpx`.

Then you could do something like `pnpm multi exec rimraf`

**Comment by vjpr** [comment]
Maybe we could use `pnpx multi rimraf` for that?

I'd prefer to keep them separate. `pnpx` relies on connectivity to registry, whereas `exec` does not. Could be problematic in some offline deploys.

**Comment by zkochan** [comment]
:ship: 2.9.0

**Comment by vjpr** [comment]
@zkochan Can we add `concurrency` setting to this command? I need to run script in series.
