### ISSUE TITLE
The installation statistics sometimes show double the expected count

### ISSUE THREAD

**Issue by pgonzal** [pnpm/pnpm#1233]
This issue does not repro with 1.43.1.  I first encountered it with PNPM 2.2.2, and it is still reproing in 2.6.1.  I have observed the behavior in 3 separate repos.  Although mildly annoying, the install completes successfully now that Issue https://github.com/pnpm/pnpm/issues/1217 has been fixed.

### Code to reproduce the issue:

Run `pnpm install`

### Expected behavior:

The "Resolving..." statistics line should show correct counts for the number of installed packages.

### Actual behavior:

It reports twice the actual number.  For example, this repo had 3,530 packages get installed, but the statistics show 7060:

```
Packages: +2379
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading <registry>.visualstudio.com/@ms/odsp-shared-react/40.19.24: 13.4 MB/13.4 MB, done
Downloading <registry>.visualstudio.com/@ms/odsp-shared-sharing/25.1.83: 6.19 MB/6.19 MB, done
Resolving: total 7060, reused 6502, downloaded 558, done
```

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
I have a fix but let's keep it open till I add a test

**Comment by zkochan** [comment]
:ship: 2.6.2

**Comment by pgonzal** [comment]
I tested 2.6.2 in 3 different repos and confirmed that the issue is fixed.  Thanks @zkochan !
