### ISSUE TITLE
When a network connection fails, PNPM incorrectly reports a tarball integrity error

### ISSUE THREAD

**Issue by pgonzal** [pnpm/pnpm#1235]
### Code to reproduce the issue:

This was first observed as part of https://github.com/pnpm/pnpm/issues/1230 where the tarball download is failing due to ECONNRESET.  However, looking at the code, the misleading message should be straightforward to reproduce for any networking error.

### Expected behavior:  

Failed network operations should be reported as such.

### Actual behavior:

A misleading `"integrity checksum failed when using sha1"` error is shown instead.

The bug is pretty easy to spot in this file:
https://github.com/pnpm/tarball-fetcher/blob/a7dc4725d41b0130c9a3cceb778672d10a79ea57/src/createDownloader.ts#L155

When the `reject()` callback is called to reject the promise, the function should return immediately. Instead the code continues performing other operations.  For example, if the tarball fails to download because the socket fails with ECONNRESET, this code will save a truncated file to disk and then attempt to untar it, which doesn't make sense.  Doing so hides the original error, and instead shows a misleading error about an incorrect file hash value.

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by pgonzal** [comment]
@nickpape-msft @iclanton

**Comment by pgonzal** [comment]
FYI we still get reports of this issue a couple times per month.  In most cases it can be worked around by telling the person to specify `--network-concurrency=1`.  However people interpret the error message `"integrity checksum failed when using sha1"` to be a data corruption bug in PNPM itself, versus a network connectivity issue.  It would be great to fix that.

**Comment by zkochan** [comment]
There are a couple of possible scenarios and we should print different messages:

1. `fetch-retries` is set to 1 (it is 2 by default). In this case, we should print something like: 

   > Seems like there are network connectivity issues. Try setting the "fetch-retries" config a value bigger than 2 (E.g. "pnpm set fetch-retries 2") or rerunning the command.

2. `fetch-retries` is set to 2 or more:
   1. the actual checksum was the same on every fail. In this case, someone force-pushed a new tarbal to the registry. We should print the error that is printed currently but we can add more details:

      > ... integrity checksum failed when using sha1 ...
      > Seems like <package id> was force-pushed to the registry. If you are OK to accept the new content, remove your lockfile and run installation again
   2.  the actual checksum is different on every fail. In this case it is a network failure.
        > Package download failed. Try rerunning the command. If you have network connectivity issues, setting a lower network-concurrency may help ("pnpm install --network-concurrency 1" or "pnpm set network-concurrency 1 && pnpm install")

**Comment by pgonzal** [comment]
Doesn't the network library already allow you to distinguish these two cases?

1. The download completed successfully, but the checksum tells us that the binary contents are corrupted somehow.
2. The download was interrupted due to a network failure, so it doesn't make any sense to calculate a checksum.

i.e. `fetch-retries` isn't necessary or relevant for distinguishing these two cases.

**Comment by zkochan** [comment]
Unfortunately, sometimes the server tells us that all went well, the tarball was downloaded successfully but in reality, the tarball is corrupted. I don't know the reasons but it may happen. Maybe some bad do it

**Comment by pgonzal** [comment]
You mean the registry server returns an incorrect `Content-Length` header in its response?  Or that the NodeJS network stack ignores the `Content-Length` header when reading the tarball?

(I wonder if this might suggest what is the underlying problem that is causing these failures.)

Since `--network-concurrency` is really just a workaround, perhaps PNPM could provide a diagnostic option that would help us better understand how this happens.  Rush supports telemetry hooks, e.g. we could configure our internal monorepo to collect logging information whenever this sort of failure occurs, if PNPM could somehow tell us about it.

**Comment by zkochan** [comment]
oh, indeed, we content-length mismatch should tell us if the connection was dropped. We already check it

https://github.com/pnpm/tarball-fetcher/blob/8c474b644c3a115ac59f82c03c4a17a1c763127e/src/createDownloader.ts#L207-L212

Probably the verification fails earlier. I'll rewrite that code a bit. pnpm will wait for the size check before throwing the error

**Comment by pgonzal** [comment]
Awesome! :-D

**Comment by zkochan** [comment]
:ship: 2.25.1
