### ISSUE TITLE
Require of non-existent file in pnpmfile doesn't throw an error

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1247]
No error is thrown, it just silently proceeds.

Something like:

```js
module.exports = require('../../../../packages/public/tools/pnpm')
```

NOTE: I am using `.npmrc#pnpmfile` option with custom location for `pnpmfile.js`.

### pnpm version: 2.9.0

**Comment by zkochan** [comment]
🚢 [v2.10.0](https://github.com/pnpm/pnpm/releases/tag/v2.10.0)
