### ISSUE TITLE
link: protocol not working for `../`?

### ISSUE THREAD

**Issue by donaldpipowitch** [pnpm/pnpm#1253]
### Code to reproduce the issue:

1. `$ git clone https://github.com/Mercateo/ws.git`
2. `$ pnpm recursive install`

### Expected behavior:

Installs runs without errors.

### Actual behavior:

```
/Users/pipo/workspace/ws/packages/example-browser-js:
 ERROR  Path must be a string. Received undefined
at assertPath     path.js:28
at join           path.js:1236
at                …b/node_modules/supi/lib/api/link.js:155
at next
at                …lib/node_modules/supi/lib/api/link.js:7
at new Promise
at __awaiter      …lib/node_modules/supi/lib/api/link.js:3
at linkToModules  …b/node_modules/supi/lib/api/link.js:120
at <anonymous>    …b/node_modules/supi/lib/api/link.js:101
at next
```

### Additional information:

The failing dependency can be found here: https://github.com/Mercateo/ws/blob/master/packages/example-browser-less/package.json#L14. So far we use yarn in all our projects, but every now and than I try if we can finally switch to pnpm without errors ^___^

 - `node -v` prints: v8.11.2
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
I fixed the issue (not published yet)

You'll have to run `pnpm recursive link` though. `pnpm recursive install` tries to install everything from the registry. And it fails with "not found" errors because the packages in that monorepo are not in the registry.

**Comment by zkochan** [comment]
@timfish if your monorepo also contains private packages in dependencies of other private packages, then you should probably use `pnpm recursive link`.

`pnpm recursive link` works kind of like `lerna bootstrap`, so that is the command you probably needed anyway.

**Comment by donaldpipowitch** [comment]
I do not deserve those bug fixes within 24 hours! 😍Thank you so much.

So I just installed `2.10.4` and run `pnpm recursive install` against https://github.com/Mercateo/ws. I now get `ERROR  404 Not Found: example-node-ts (via https://registry.npmjs.org/example-node-ts)` (and thanks to https://github.com/pnpm/pnpm/issues/1196 I really see that it tries to find my package in the registry 😍).

`pnpm recursive link` seems to run without problems.

Could you explain why `pnpm recursive install` tries to install everything from the registry and using the `link:` protocol doesn't trigger the `pnpm recursive link` behavior for this particular package? Is there anything which could lead to undefined behavior or something like that? I thought `link:` would make it already explicit. 🤔I actually liked yarns behavior a lot in this case and it helped with the adoption here at our company as we had not had to explain something like `lerna bootstrap`. `lerna bootstrap` always felt like a workaround because npm doesn't support monorepos natively.

Would you structure https://github.com/Mercateo/ws in a different way? (My goal is to test the local `ws` package against a couple of standalone private examples which could depend on each other as well.)

Regarding the initial issue I think everything is solved so I close it. Thank you again. ❤️ Looking forward to hear about some background between `install`/`link.`

**Comment by zkochan** [comment]
@donaldpipowitch directory dependencies (so the ones with `link:..`) work the same with `pnpm recursive link` and `pnpm recursive install`.

The issues that you experience are because "example-node-ts-2" depends on "example-node-ts" via a range

https://github.com/Mercateo/ws/blob/f58e3742a0b870c39a9d8b5e491aaf290bc82948/packages/example-node-ts-2/package.json#L16

When you use ranges, `pnpm recursive install` will install the dependency from the registry.
`pnpm recursive link` on the other hand, will check if a package is available locally. If it is and it satisfies the range, then it will link it from the local directory.

So you either have to use instead of 

```
"example-node-ts": "*"
```

this

```
"example-node-ts": "link:../example-node-ts"
```

or run `pnpm recursive link`

**Comment by donaldpipowitch** [comment]
Thank you so much for the explanation. And sorry, because I haven't read the error correctly.  I didn't notice that the error was thrown, because I used `"example-node-ts": "*"` even though the error clearly said that. My bad.

I think I can live with using `pnpm recursive link`, but I wonder if it was ever discussed if `pnpm recursive link` could prefer local dependencies (similar to yarn) - maybe configurable in a `pnpmfile.js`? Like `preferLocal: true` to ease the adoption and to not explain on a per project basis if `link` or `install` should be used. Or could this behavior be achieved with hooks only? 🤔

**Comment by zkochan** [comment]
Probably related: #1027

I would keep `pnpm recursive install` as is. Seems like in some monorepos it is the desired behavior. Like cyclejs is migrating to pnpm and they want `pnpm recursive install` to work as it works now.

A property, maybe. Or even a new command? Feel free to create a new issue or start a discussion in the chatroom

**Comment by aleclarson** [comment]
Does __npm__ support the `link:` protocol?
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../../../../plugins/tslint-mango

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-12-10T00_06_47_963Z-debug.log
```
I'm using `npm v6.4.1`.

**Comment by zkochan** [comment]
There is an issue about it https://github.com/pnpm/pnpm/issues/1332
