### ISSUE TITLE
Ignore packages by file path `pnpm multi link --ignore-fs`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1255]
I need to ignore a certain path containing packages.

[Bolt](https://github.com/boltpkg/bolt#commands) has a command for this:

```
bolt ws ... --only-fs [file glob] | Filter workspaces by file path
bolt ws ... --ignore-fs [file glob]
```

Also, I think Bolt's commands are well thought out for working with multi-package repos. Maybe we should try to support them and borrow naming.

Related to #1213.

**Comment by zkochan** [comment]
@vjpr what if they have dependencies that are in other folders of the repo? Should they be included? I assume - yes, because that is how `--scope` works at the moment.

**Comment by vjpr** [comment]
My specific use-case is having two folders containing the same packages. In my case one is symlinked to another app in dev.

I want to be able to run `pnpm m link` against either of them.

But since they contain the same packages, I want to completely ignore them. E.g. If something in `private` depends on `public/foo`, I want to use either `public/foo` or `public-symlink/foo`, but never both.

```
- app1
  - packages
    - private
    - public
    - public-symlink -> /app2/packages/public

- app2
  - packages
    - private
    - public
```

**Comment by zkochan** [comment]
So if they should be so isolated, why not just `cd app1 && pnpm m link`?

**Comment by vjpr** [comment]
Yeh thats what I do. I mean I need to link `packages/public` or `packages/public-symlink` inside `app1`.

**Comment by zkochan** [comment]
It is supported. For instance, this will ignore everything inside the packages folder:

```
pnpm --filter !{packages/**} list
```
