### ISSUE TITLE
Support a config that makes `pnpm recursive install` link packages from the workspace

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1259]
As noted by @donaldpipowitch, https://github.com/pnpm/pnpm/issues/1027#issuecomment-402725483

> One could think pnpm recursive link will link every local package to the global folder.

Seems like some users expect `pnpm recursive install` to behave like `yarn install` or `lerna bootstrap`. To support these users, we can add a config called `link-workspace-packages`.

If `link-workspace-packages` is `true`, `pnpm recursive install` links packages in the monorepo and installs the rest of the dependencies (the current behavior of `pnpm recursive link` as of pnpm v2.10)

* * *

### Changes in `pnpm install`

This config will alter the behavior of `pnpm install pkg` when executed inside a multi-package repository. `pkg` will be first searched inside the repository. If a local `pkg` that satisfies the wanted range is found in the repository, it is linked. If not, it is installed from the registry.

If the package is installed without a spec and the latest version of the installed package does not equal the version in the workspace, then the package is downloaded from the registry.

### Changes in `pnpm update`

If a newer version of a linked package is available in the registry, `pnpm update` may unlink the package and install the newer version from the registry

**Comment by vjpr** [comment]
Also good idea to have a cli flag to override the config behavior.

**Comment by zkochan** [comment]
yes, there will be a CLI flag.

Also, this config will alter the behavior of `pnpm install pkg` when executed inside a multi-package repository. `pkg` will be first searched inside the repository. If a local `pkg` that satisfies the wanted range is found in the repository, it is linked. If not, it is installed from the registry.

**Comment by zkochan** [comment]
This will be possible to implement after #1313 is done

**Comment by zkochan** [comment]
:ship: 2.14.0-0

**Comment by zkochan** [comment]
A more stable version is out with some fixes: 2.14.0
