### ISSUE TITLE
`--scope` should not apply `run` and `exec` action to dep graph

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1270]
`link` should (optional disable), but `run` and `exec` not.

**Comment by zkochan** [comment]
why not keeping it as is and adding a new config/flag called `--include-dependencies`? If you prefer, you may set it to false in your `.npmrc`.

**Comment by zkochan** [comment]
So every command will have its own defaults? It is not that straightforward to me what should be the default for which command. As I mentioned in gitter, in my use case I need `--include-dependencies` with `pnpm recursive run tsc`.

I would prefer the users to decide what they want but I understand that it is inconvenient to do with lots of flags that you should always use. What if there is another way?

Like this would mean including dependencies: `--scope ..foo`
This would mean including dependents: `--scope foo..`
And this would mean just the foo: `--scope foo`

**Comment by vjpr** [comment]
> So every command will have its own defaults?

I don't think so. I think `link` is a special case. When running `link --scope=foo` or `link --prefix=packages/foo`, it doesn't make sense not to include deps...because that is the whole point of `link`. They might as well run `install` if they don't want to local link anything.

> in my use case I need `--include-dependencies` with `pnpm recursive run tsc`.

It should be run with `--include-dependencies`, because I don't think its as common and the default shouldn't produce unexpected things.

Say someone wants to delete `node_modules` for a package. `pnpm multi exec --scope=foo -- rm -rf node_modules`. This would unexpectedly wipe our more `node_modules` dirs than they were expecting. 

It should be opt-in for `run` and `exec`, and default for `link` only because `link` doesn't make sense without it.

> Like this would mean...

I would prefer `--scope-with-deps`. I have a few scripts that generate the `--scope` options and this would add lots of complexity.

And what about glob support? This would interfere with that. I think it already takes a glob.

**Comment by zkochan** [comment]
Yes, it takes globs but parsing of dots would go first `..@scope/**`

>  I think link is a special case. 

I would rather make it the default behavior for `link` as well.

> I have a few scripts that generate the --scope options and this would add lots of complexity.

Why would it add more complexity? It will work the way you wanted it to work. When you set `--scope=foo` only foo will be included. If you need all dependencies, adding `..` before `foo` is not harder then adding a new flag

**Comment by zkochan** [comment]
Or another alternative. `--scope-to` includes dependencies. `--scope-from` includes dependents. `--scope` includes only what has been matched

**Comment by vjpr** [comment]
Make sure to checkout [boltpkg/bolt](https://github.com/boltpkg/bolt) for some command inspiration. From creators of `lerna`.

I'd like to scope by package name glob and also file path glob.

`--scope-to` is confusing. Someone might say that you "scope a command TO a single package". I think be verbose.

**Comment by vjpr** [comment]
I think it would be fine to separate the flags `--scope=foo --include-dependencies --include-dependents`

**Comment by zkochan** [comment]
`--filter` flag implemented in [v2.13.0](https://github.com/pnpm/pnpm/releases/tag/v2.13.0)
