### ISSUE TITLE
A package called "foo" already has its bin linked.

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1274]
If `next: npm:@vjpr/next@^6.1.0-vjpr.1` is already installed and in the package.json

```
$ pnpm i -S npm:@vjpr/next@^6.1.0-vjpr.1

WARN  Cannot link bin "next" of "@vjpr/next" to "/Users/Vaughan/dev-xxx/dev-xxx/xxx/node_modules/.bin". A package called "@vjpr/next" already has its bin linked.
```

I think this is happening because some code is not handling the aliasing case.

**Comment by vjpr** [comment]
False alarm, I was actually installing `@vjpr/next` separately.

**Comment by zkochan** [comment]
but the warning seems confusing
