### ISSUE TITLE
`packages/pnpm/lib/bin/pnpm.js` does not have executable permissions after build

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1276]
Cannot symlink to `packages/pnpm/lib/bin/pnpm.js` because it is not executable.

It should be made executable as part of the build. Or, there should be another file that points to it that is always executable permissions.

E.g. `bin/pnpm.js` which requires `lib/bin/pnpm.js`.

**Comment by zkochan** [comment]
Related: #1276

**Comment by zkochan** [comment]
Use `packages/pnpm/bin/pnpm.cjs`
