### ISSUE TITLE
When using a different version of pnpm to install, it prints dependencies even if all up-to-date

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1280]
Say I work in dev with my fork `pnpm-local i`, then use `pnpm i`. When I switch between commands it prints out the added deps:

```
readPackage hook is declared. Manifests of dependencies might get overridden
Performing headless installation
Already up-to-date

dependencies:
+ @babel/core 7.0.0-beta.49
+ @babel/plugin-proposal-class-properties 7.0.0-beta.49
+ @babel/plugin-proposal-decorators 7.0.0-beta.49
+ @babel/plugin-proposal-object-rest-spread 7.0.0-beta.49
+ @babel/plugin-transform-flow-strip-types 7.0.0-beta.49
...
```

Then when I run again with same version/command:

```
readPackage hook is declared. Manifests of dependencies might get overridden
Performing headless installation
Already up-to-date
```

**Comment by zkochan** [comment]
This happens when the shrinkwrap version is updated https://github.com/pnpm/spec/tree/master/shrinkwrap

So, for instance, you used pnpm v2.7.0 and updated it to pnpm v2.10.0. In that case pnpm updates the `shrinkwrap.yaml` format

**Comment by zkochan** [comment]
Expected behavior
