### ISSUE TITLE
Allow `pnpm-workspace.yaml` path/contents to be passed in to CLI

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1291]
`--ws-config-file=tools/pnpm-workspace.yaml`

`--ws-config-json='{workspace: {packages: ['.', 'packages']}}'`

This would provide so much flexibility. Otherwise, for my use cases, it would require a very complicated set of cli flags. The `..dep` syntax will be good for some things, but I think this would be best.

Alternatively to `--ws-config-json` you could allow `--config-json` which would allow you to override all the different configurations for `pnpm`:

- pnpmfile
- workspace (pnpm-workspace.yaml)
- npmrc (.npmrc)
- flags (all existing flags could be passed in as json)

I think this would help with testing too, and help people build tooling around it.

I would argue that this cli flag is better/more-needed than a programmatic API, because pnpm is usually installed globally and its better to keep it in a separate process, instead of having a wrapper script that has to load it.

**Comment by vjpr** [comment]
Cypress does it like this: https://docs.cypress.io/guides/references/configuration.html#Plugins

**Comment by zkochan** [comment]
If the workspace will not contain a `pnpm-workspace.yaml` in the root, how will we know that commands are executed inside a workspace? We have different behavior of `pnpm link`, when it is executed inside a workspace.

**Comment by vjpr** [comment]
So `pnpm-workspace.yaml` would always be in the root. Alternatively we could use `.npmrc#pnpm-workspace` or `package.json#pnpm-workspace`.

This issue talks about the actual config info being defined elsewhere.

**Comment by zkochan** [comment]
I think there should be only one way to define the root of the workspace. If `pnpm-workspace.yaml` is not OK, we can change it in a major update but this is something that will be searched up on most pnpm commands executions. Adding many possibilities will cause a slowdown of all commands

**Comment by vjpr** [comment]
> I think there should be only one way to define the root of the workspace.

Agree with "define the root".

But the actual config should be able to be overridden.

**Comment by zkochan** [comment]
I see. At the moment there is only a "packages" field and you'll be able to filter by fs path if we implement the specs (https://github.com/pnpm/spec/pull/1).

You want to rewrite that field because filtering only allows to narrow down the set. Is your intention to add packages that are not matched by the globs of `pnpm-workspace.yaml`?

**Comment by vjpr** [comment]
> Is your intention to add packages that are not matched by the globs of pnpm-workspace.yaml?

Here is my current file:

```
packages:
  - '.'
  - 'packages/**'
  - '!**/babel7-test/**'
  #- '!**/react-leaflet-draw/**'
  # We disable this because it can be slow.
  - '!**/apps-templates/mobile-crna/**'
  - '!**/apps-templates/docz/**'
  #- '!**/apps-templates/gatsby/**'
  # Potentially slow
  #- '!**/pages/map-mapbox/**'
  #- '!**/apps/playground/**'
  # ---
```

See how I exclude some dirs?

Basically I want to unexclude some dirs sometimes. And I would also like to exclude/unexclude by package name too.

**Comment by zkochan** [comment]
maybe we could support it in the specs

```
pnpm multi install -- !./**/apps-templates/mobile-crna/**
```

**Comment by vjpr** [comment]
But what about the use case where I want to use everything from `pnpm-shrinkwrap.yaml#packages` but unignore one glob.

**Comment by zkochan** [comment]
Maybe we could create some groups?

```
packages:
  - '.'
  - 'packages/**'
  - '!**/babel7-test/**'
  # This was breaking. Want to leave in repo, but ignore for now.
  #- '!**/react-leaflet-draw/**'
  # We disable this because it can be slow and is not needed all the time unless modifying the framework.
  - '!**/apps-templates/mobile-crna/**'
  - '!**/apps-templates/docz/**'
  - '!**/apps-templates/gatsby/**'
  # Potentially slow apps.
packages:slow:
  - '!**/pages/map-mapbox/**'
  - '!**/apps/playground/**'
```

I don't know yet how it would work

Of course, rewriting the workspace file would be the easiest solution
I am not sure it would be a better DX though

**Comment by vjpr** [comment]
> Maybe we could create some groups?

Wouldn't work for my use case.

The `gatsby` package is an app template. I don't want this to install normally, but say I want to update the template, I would want to enable it as a one-off.

> rewriting the workspace file

I want to do this at the cli though as opposed to on disk:

```
pnpm multi --workspace-config='{packages: [a,b,c]}'
```

**Comment by zkochan** [comment]
Maybe you could do some tooling of your own. You'd have several `pnpm-workspace.yaml` files. A command like `change-workspace slow` and it would symlink the `pnpm-workspace.yaml` with the needed globs. Like this package for npmrc: https://www.npmjs.com/package/npmrc

**Comment by vjpr** [comment]
> it would symlink the pnpm-workspace.yaml with the needed globs.

Too hacky for my liking.

Even something like this might work:

```
--packages={glob1,glob2,glob3}
```

**Comment by zkochan** [comment]
This feature with the [custom modules directory](https://github.com/pnpm/pnpm/issues/2471) feature, might be actually useful.

**Comment by zkochan** [comment]
I guess, we could add a CLI option called `--workspace-packages` (I would prefer `--workspace-projects` but we already use "packages" in `pnpm-workspace.yaml`)

**Comment by vjpr** [comment]
What would be passed in to the flag?

**Comment by zkochan** [comment]
the globs. Like

```
pnpm install --workspace-packages=packages/* --workspace-packages=utils/*
```

**Comment by vjpr** [comment]
Would this override the `pnpm-workspace.yaml`? What if you want to add/remove some items.

**Comment by zkochan** [comment]
Yes, this would override the values in `pnpm-workspace.yaml`.

**Comment by zkochan** [comment]
After thinking about this again. I don't think this would be a good feature.

I think from the description of your problem, what you'd really want is some filter that exclude projects by directory?

**Comment by vjpr** [comment]
I would rather `--workspace-packages` flags. This would solve my use case. Exclude would make it rather complicated.

If I am going to have a script create the cli flags to exclude some packages, then this script would have to store the logic to determine which dirs to exclude and which not to. But because the packages are defined in `pnpm-workspace.yaml`, there would be two places now that define the packages.

I would rather be able to generate the workspace file entirely from my script. Then I would have the source-of-truth for which packages to include in my own `.js` config file.

So I really like the current feature and hope it goes in.

---

Could a `pnpmfile.js` hook be possible?

What would be great is if most inputs were configurable through a programmatic api. That is, every input/option would be dynamically configurable. This would give full customization, and would allow experimentation which would then help us figure out the best flags to expose to the user in the CLI api.

**Comment by vjpr** [comment]
Since its implemented, could we expose it as an experimental feature at least?

**Comment by zkochan** [comment]
I don't have objections to add a pnpm hook for options

**Comment by vjpr** [comment]
Could we have the `pnpm-workspace.yaml` object as a hook?

```
function readWorkspaceConfig(config) {
	config.packages = [...config.packages, 'foo']
	return config
}
```

**Comment by zkochan** [comment]
That's too complicated, I'll merge this but I need to add a test

**Comment by vjpr** [comment]
I have a use-case for configurable `pnpm-workspace.yaml` file name.

When using a `git subtree` you may want to export part of your codebase as a monorepo containing your open source packages.

```
- packages
  - open-source-pkgs
    - package.json
    - pnpm-workspace.yaml
    - packages
      - foo
  - private-pkgs
    - package.json
    - packages
      - bar
- package.json
- pnpm-workspace.yaml
```

When using `subtree` it exports a dir as a repo that you can push to github. So you want it to contain the tooling to allow people to build and contribute. So it should have its own `pnpm-workspace.yaml` file.

But this workspace file should only be used when you are not developing in your internal monorepo.

So when running install commands inside open source pkgs it will only install inside the `open-source-pkgs`. But what you want is it to install in the root pnpm-workspace.

The open source pkgs dir will be updated in a separate workflow.
