### ISSUE TITLE
Allow specifying monorepo singletons / enforce certain packages to be peerDeps throughout monorepo

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1299]
Allow specifying monorepo singletons so that user is warned if they install them for local packages.

E.g. `react` and `graphql` should be `peerDeps` in all sub-packages. Warn if a sub-package has one that is not a peer dep.

I want this to run during `pnpm multi install`, and also `cd packages/foo && pnpm install react`.

A global pnpmfile would solve this I think. https://github.com/pnpm/pnpm/issues/1137

**Comment by zkochan** [comment]
Seems like we need some type of linting. There's a related discussion at #2713
