### ISSUE TITLE
Flag for latest in pnpm update

### ISSUE THREAD

**Issue by matt3224** [pnpm/pnpm#1307]
I would really like to get the latest updates rather than the latest within the range. Perhaps a simple flag such as `pnpm update --latest` for long hand and `pnpm up -l` for short?

Thoughts welcome

**Comment by zkochan** [comment]
What about something like `pnpm update *@latest`?

**Comment by matt3224** [comment]
If you feel that makes sense then sure! Could have a shorthand too?

**Comment by zkochan** [comment]
What would be the shorthand?

**Comment by matt3224** [comment]
`pnpm up -l` ?

**Comment by matt3224** [comment]
Ok and will `pnpm up *@latest` work?

**Comment by zkochan** [comment]
Not at the moment. It should be implemented

**Comment by zkochan** [comment]
We can use `-L` for short. That's what Yarn uses.

**Comment by zkochan** [comment]
PR is in progress https://github.com/pnpm/pnpm/pull/1786

**Comment by zkochan** [comment]
:ship: 3.2.0-0
