### ISSUE TITLE
`Ignoring file dependency because it is not a root dependency [object Object]`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1312]
I have a transitive dep that I want to symlink inside my workspace to patch it for multiple packages.

I use something like this:

```js
function readPackage(pkg) {
  //console.log(pkg.name)
  if (pkg.name === 'foo') {
    pkg.dependencies['bar'] = '*'
  }
  if (pkg.dependencies && pkg.dependencies['args']) {
    const workspaceRoot = process.env.PNPM_WORKSPACE_ROOT
    const newPkgPath = require('path').join(workspaceRoot, 'packages/args')
    // If its a subdep, this relative path won't be correct.
    //const newPkgPathRel = require('path').relative(process.cwd(), newPkgPath)
    console.log('args', newPkgPath)
    pkg.dependencies['args'] = `link:${newPkgPath}`
    console.log(pkg)
  }
  return pkg
}
```

But I get:

```
 WARN  Ignoring file dependency because it is not a root dependency [object Object]
```

https://github.com/pnpm/pnpm/blob/d966515c6c52244536351d43254b1ee6aeca1f00/packages/supi/src/resolveDependencies.ts#L321-L328

1. `[object Object]` should not be
2. Can we allow non-root file deps if they are absolute?

This would help to quickly patch any dep during dev. Yarn has something similar in resolutions.

Maybe a quick solution would be to have a cli flag?

**Comment by zkochan** [comment]
Sounds good to me

**Comment by zkochan** [comment]
This works with [overrides](https://pnpm.io/package_json#pnpmoverrides). Use relative path in an override

```json
{
  "pnpm": {
    "overrides": {
      "local-dep": "link:packages/local-dep"
    }
  }
}
```

With the hook it should work as well. The path should be relative to the project root.
