### ISSUE TITLE
`ENOENT: no such file or directory, lstat '/xxx/node_modules'`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1318]
```
 ERROR  ENOENT: no such file or directory, lstat '/xxx/node_modules'
at Error: ENOENT: no such file o…
at realpathSync                    fs.js:1649
at                                 …/pnpm/packages/supi/src/api/link.ts:205  export async function linkFromGlobal (
at next
at                                 …ve/pnpm/packages/supi/lib/api/link.js:7
at new Promise
at __awaiter                       …ve/pnpm/packages/supi/lib/api/link.js:3
at linkToModules                   …/pnpm/packages/supi/lib/api/link.js:154
at <anonymous>                     …/pnpm/packages/supi/src/api/link.ts:126  await saveCurrentShrinkwrapOnly(opts.prefix, updatedCurrentShrinkwrap)
at next
at fulfilled                       …ve/pnpm/packages/supi/lib/api/link.js:4
Resolving: total 2282, reused 2282, downloaded 0
```

I added '.' to my `pnpm-workspace.yaml`, then ran `pnpm m link`.

There is a shrinkwrap file in this root dir.

https://github.com/pnpm/pnpm/blob/master/packages/supi/src/api/link.ts#L213

---

However, `linkFromGlobal` being used here seems odd. I don't want anything linked from global when running `pnpm m link`. Only local stuff from `pnpm-workspace.yaml`.

---

Also, I had `bcrypt` as a root dep, and when running `pnpm m link` it didn't build it. Any reason that wouldn't happen?

**Comment by zkochan** [comment]
`pnpm m link` is deprecated. Use `pnpm m i` + `link-workspace-packages=true`.
