### ISSUE TITLE
Resolve error: unable to load resolver "node"

### ISSUE THREAD

**Issue by frontendnote** [pnpm/pnpm#1326]
### Code to reproduce the issue:
1.pnpm install
2.npm run build

Resolving: total 1057, reused 1057, downloaded 0, done

### Actual behavior:

``` bash
[1m[31mERROR in ./src/components/breadcrumb/index.jsx

  ✘  https://google.com/#q=import%2Fno-duplicates  Resolve error: unable to load resolver "node"  
  src/components/breadcrumb/index.jsx:1:1
  import React from 'react';
   ^

✘ 1 problem (1 error, 0 warnings)

```

All modules can be not found，just like:
``` bash
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'autoprefixer'
```
use npm or yarn is ok

### Additional information:

 - `node -v` prints: v8.10.0
 - Linux

**Comment by zkochan** [comment]
Try to run `rm -rf node_modules && pnpm install --shamefully-flatten`

**Comment by frontendnote** [comment]
@zkochan Thank you, this problem has been solved.
