### ISSUE TITLE
The "--lockfile-only" flag still downloads the full tarball for every dependency

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#1328]
### Code to reproduce the issue:

Run `pnpm install --shrinkwrap-only`.

My understanding was that this feature allows people to update their **shrinkwrap.yaml** file very quickly, in situations where they aren't going to be building anything locally, so they don't need their **node_modules** folder to be updated.  (For example, I'm going to push the updated **shrinkwrap.yaml** to a PR branch, and I optimistically expect the PR build to succeed, so there's no reason to build it locally.)

### Expected behavior:

Run `pnpm install --shrinkwrap-only` runs very quickly.

### Actual behavior:

Run `pnpm install --shrinkwrap-only` takes about the same amount of time as a regular `pnpm install --shrinkwrap-only`.

If that's by design, perhaps we should deprecate the `--shrinkwrap-only` flag?  Or perhaps I am misunderstanding its purpose?

### Additional information:

This is apparently a recent regression due to the work with corgi headers.  See @nickpape-msft 's comments on https://github.com/pnpm/pnpm/pull/1177#issuecomment-413724593 for background.

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by pgonzal** [comment]
For reference, I've pasted Nick's comment below:
> > **@zkochan:**
> > yes, it is still faster than w/o --shrinkwrap-only. Packages are not hardlinked into the project's node_modules. No node_modules is created at all.
> 
> **@nickpape-msft:**
> Right, but this isn't really the expensive part of the operation. From what I can tell pnpm still downloads the tarballs, stores on disk, unzips, etc. If you have an empty cache this takes almost as long as when not using the flag. In the case where you have a perfectly good cache, it still takes almost nearly as long. If it really isn't significantly faster, why have the flag around at all? It will just be bait for more GitHub issues when it doesn't really do what people are thinking (e.g. have a significant speed improvement). Is there anything creative we can do to make the flag work the way it did before, where it WAS significantly faster?
> 
> For some context, we wanted to add a flag to Rush that would utilize this PNPM flag. The idea was that someone could quickly (i.e. in 30 seconds) merge master into a branch with an outdated shrinkwrap and generate a new valid shrinkwrap that could be pushed to the CI to be built. In one case, we have a branch that a bot creates that we are trying to get merged quickly. Every time someone updates dependencies (often), it creates a merge conflict on this branch. Many times, we simply need to re-generate the shrinkwrap, as the CI would likely pass once this is updated. However, it takes quite a while to do this on a computer that has an empty pnpm cache or has a slow disk (20 minutes). Sometimes a couple people try running it at the same time and waste their time. Sometimes you are trying to do other things on your disk, but having to do the full install puts a lot of load on your disk. In these cases, we were hoping for a quick, "fix my shrinkwrap in 30 seconds" solution (which is what we thought --shrinkwrap-only was).

**Comment by nickpape-msft** [comment]
@zkochan any thoughts on this? We may be able to contribute some effort to this, as it would save us a lot of time in our daily workflow (especially when we need to regenerate a shrinkwrap for 2000+ dependencies after a merge).

**Comment by zkochan** [comment]
At the moment I see only one way to optimize it: skip unpacking the tarball.

We cannot avoid downloading the tarball because:

1. we need to get the real `package.json` from the tarball (the packed `package.json` may differ from the `package.json` returned in the metafile 😞)
1. we need to check if there is a `.hook` folder in the package

Maybe skipping tarball downloads would be possible if we'd change the `shrinkwrap` format and remove fields like `requiresBuild`. However, I don't think we should spend time on that.

An alternative solution might be to create a smart proxy (maybe contributing to verdaccio), that would return all the necessary information to create the `shrinkwrap.yaml` w/o downloading the tarballs

**Comment by zkochan** [comment]
> Maybe skipping tarball downloads would be possible if we'd change the shrinkwrap format and remove fields like requiresBuild. 

As far as I remember they were added to fix some performance issues but it might be possible that it would be enough to store that additional info in `node_modules/.modules.yaml`.

In any case, this change would require a lot of work

**Comment by pgonzal** [comment]
I vote to abandon https://github.com/Microsoft/web-build-tools/pull/766 and forget about this feature:

In my experience, the primary pain here is due to slowness when downloading multi-megabyte tarballs, and @zkochan is saying `--shrinkwrap-only` cannot skip these downloads (due to limitations of the NPM protocol).

If someone's going to invest in this area, it seems like the better investment would be to make the downloads themselves go faster.  We have a very fast internet connection at work.  Our investigation for https://github.com/pnpm/pnpm/issues/1131 suggests that a massive speed improvement is possible, by fixing whatever NodeJS issue is causing the network operations to be severely throttled.

**Comment by sunilsurana** [comment]
@zkochan Does the latest version also have same behavior or it is fixed?

**Comment by sunilsurana** [comment]
Curious to know what is requiresBuild? Couldnt find anything to read on web

@nickpape Were you able to have any workaround for this?

**Comment by zkochan** [comment]
The issue name is misleading. `--lockfile-only` is not "not useful". Even though it downloads the tarballs, it does not create hard links of dependencies and it does symlink them to node_modules. Installation is still faster with this flag than without it.

**Comment by sunilsurana** [comment]
Hi @zkochan 
Is tarball required just for requiresBuild property? Can you please explain what is meaning of this property? I tried searching of web but could not find helpful information

**Comment by zkochan** [comment]
Probably for `requiresBuild` only but I am not 100% sure.

`requiresBuild=true` means that the packages has a postinstall script or the package is a native dependency. So it should be build.

**Comment by GiriB** [comment]
@zkochan  As per your comment above, do you think documented [here](https://pnpm.js.org/en/cli/install#lockfile-only) should be updated?

**Comment by sanmai-NL** [comment]
Is there an update on this issue? It seems @GiriB's comment hasn't been addressed and the implementation has moved on since this issue was opened. I still use this flag under CI, but I hope that its applications will be well-documented or it should be removed.

**Comment by octogonz-proxy** [comment]
> An alternative solution might be to create a smart proxy (maybe contributing to verdaccio), that would return all the necessary information to create the `shrinkwrap.yaml` w/o downloading the tarballs

This problem might be easy if `npm pack` always stored **package.json** at the start of the tarball. Then you could simply abort the HTTP GET stream after **package.json** was decompressed.

But `npm pack` doesn't do that. It packs the files in seemingly random order. 🙃

**Comment by octogonz** [comment]
> The issue name is misleading. `--lockfile-only` is not "not useful". Even though it downloads the tarballs, it does not create hard links of dependencies and it does symlink them to node_modules.

I clarified the issue title.

> An alternative solution might be to create a smart proxy (maybe contributing to verdaccio), that would return all the necessary information to create the `shrinkwrap.yaml` w/o downloading the tarballs

This is a good suggestion and could fix other longstanding problems of the NPM protocol.  

Most large companies already use a commercial registry (Artifactory, GitHub, Azure DevOps, etc) rather than using `npmjs.com` directly.  If there was an open source smart proxy that served as a reference implementation of a protocol extension that improved install times, and people adopted it, commercial registries might feel market pressure to implement the feature to stay competitive.  In the same way, Yarn would probably be eager to implement it as well.

**Comment by zkochan** [comment]
The npm registry has an experimental API for getting the index of a package tarball and individual files for it. Using this API we can avoid the download of package tarballs. Related PR: https://github.com/pnpm/pnpm/pull/7177

**Comment by octogonz** [comment]
Great to see this progress! 🚀

**Comment by zkochan** [comment]
We had to revert the usage of that experimental API as it was not supposed to be used by npm clients.

We will remove the `requiresBuild` field from the lockfile in pnpm v9: https://github.com/pnpm/pnpm/pull/7710

This will allow us to skip fetching of tarballs when resolving the lockfile: https://github.com/pnpm/pnpm/pull/7715
