### ISSUE TITLE
Local dependency install incompatible with npm

### ISSUE THREAD

**Issue by irisjae** [pnpm/pnpm#1332]
### Code to reproduce the issue:
Per #1061, installing local dependencies with pnpm, adds `link:`s to `package.json`, making the package uninstallable on npm (tested with 5.6.0, 6.4.0) with the error
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:X                                               
```

Maybe change to install local dependencies by `file:`s instead? I opened a [corresponding issue](https://npm.community/t/is-link-or-file-supported/1577) on the npm issue tracker.

**Comment by irisjay** [comment]
npm has [spoken](https://npm.community/t/is-link-or-file-supported/1577). They say `link:` is not supported, onlly `file:`

**Comment by Worthaboutapig** [comment]
Will this issue be fixed?

**Comment by zkochan** [comment]
pnpm supports both `file:` and `link:`. Same way as Yarn.
