### ISSUE TITLE
feature request: support .pnpmfile.js (dotfile)

### ISSUE THREAD

**Issue by techieshark** [pnpm/pnpm#1339]
Currently `pnpm` allows some advanced customization (i.e. hooks to fix third party packages) via the pnpmfile.js (see [FAQ](https://pnpm.js.org/docs/en/faq.html#solution-2)).

It seems like many tools use dot files to store in-repo config like this, so it's a little more obvious what is the repo's source code and what is a config file (example: `.eslintrc.js`). 

Could `pnpm` be modified to support, by default, `.pnpmfile.js` in addition to the current `pnpmfile.js`? 

I've seen that there's a way to change where the file is through the NPM config system, but it seems like a dotfile might be a more ideal default for most people -- especially since the .js extension could otherwise make people think it's part of the repository's source code rather than its config.

### Expected behavior:

pnpm looks for (hidden) `.pnpmfile.js` in addition to (not hidden)`pnpmfile.js`.

### Actual behavior:

pnpm only looks for `pnpmfile.js`.

**Comment by zkochan** [comment]
I think pnpm should look only for one file. Additional filesystem operations are not good because we really fight for performance.

I don't have objections renaming the default name of the pnpmfile if most of the pnpm users will vote for it. I know @vjpr and @andreineculau thought that pnpmfile was a bad name and wanted something like pnpmconfig instead

**Comment by zkochan** [comment]
but I was also thinking about not looking for a pnpmfile at all if there is no config. That would save one filesystem operation and make the pnpmfile naming up to the user

**Comment by techieshark** [comment]
>  not looking for a pnpmfile at all if there is no config

That actually seems fine. I think it'd be good to update the FAQ / docs with a description/example of how one would use the npm config settings to tell pnpm to look in `~/` or a repo's 'tools/`.  

> ... thought that  pnpmfile was a bad name and wanted something like pnpmconfig instead

Maybe "pnpmhooks.js"? (Or is it supposed to be used for general config too?)

**Comment by jayvdb** [comment]
> ... thought that pnpmfile was a bad name and wanted something like pnpmconfig instead

Also wanted it to be a declarative format https://github.com/pnpm/pnpm/issues/1082

**Comment by zkochan** [comment]
We have to change the extension of the file to `.cjs` in pnpm v6, so we might as well add the dot
