### ISSUE TITLE
Install from `npm-shrinkwrap.json`

### ISSUE THREAD

**Issue by microadam** [pnpm/pnpm#134]
Does this respect the `npm-shrinkwrap.json` file like npm does (i.e installing the specific version as specified in the shrinkwrap, ignoring whats in the package.json)? I can't see anything reading the shrinkwrap anywhere in the code, nor do I see anything about shrinkwrapping on the roadmap.

Thanks

**Comment by neemzy** [comment]
I'm interested in this as well

**Comment by markerikson** [comment]
I'd be interested in knowing if this will successfully handle installing from a shrinkwrap file that has updated file paths, namely, the modified shrinkwrap files created by https://github.com/JamieMason/shrinkpack .

**Comment by zkochan** [comment]
No, `npm-shrinkwrap.json` is ignored. But we do have now something similar to yarn's lockfile. It is created on every pnpm install.

**Comment by zkochan** [comment]
It might be nice to have if it won't add too much complexity

**Comment by aletandilero** [comment]
As someone who likes pnpm, and wants to vouch for it to my fellow npm-using colleagues, the lack of this option is a no-go for me.

Having two different lock files turns into two different sets of version resolutions. I can't (and shouldn't) force pnpm adoption, but pnpm would have a lot more "appeal" if it were compatible with npm lock files.

Thanks in advance, excellent tool!! 😄

**Comment by zkochan** [comment]
in [2.15.0](https://github.com/pnpm/pnpm/releases/tag/v2.15.0) there is now a command `pnpm import` that converts a `package-lock.json` or `npm-shrinkwrap.json` into a `shrinkwrap.yaml`
