### ISSUE TITLE
integrity checksum failed when using sha1

### ISSUE THREAD

**Issue by akggang** [pnpm/pnpm#1343]
npm ERR! code EINTEGRITY
npm ERR! sha1-ygGZsyqa4wxm73E235g8hFEL4W8= integrity checksum failed when using sha1: wanted sha1-ygGZsyqa4wxm73E235g8hFEL4W8= but got sha1-bs7J1APGeQwHL3fPuwAwDRqs4Ho=. (29398 bytes)

We are using - "node": "8.9.4",

**Comment by zkochan** [comment]
What version of pnpm do you use?

a [similar error](https://github.com/pnpm/pnpm/issues/1230) was recently fixed in v2.13.4

**Comment by zkochan** [comment]
if you use the latest pnpm, check what this returns `npm get fetch-retries`
it should be either not set or a value 2 or bigger

**Comment by akggang** [comment]
we were facing issue with npm install .. i think i raised this issue at wrong place for pnpm.
i saw your previous closing comment.
npm get fetch-retries value is coming as 2

**Comment by zkochan** [comment]
alright, if this is npm, you have seek for help here: https://npm.community/
