### ISSUE TITLE
Lumo fails to resolve its dependencies under pnpm.

### ISSUE THREAD

**Issue by jarcane** [pnpm/pnpm#1350]
I've been working to get ClojureScript working on Glitch, using the Lumo REPL/compiler, which is provided as an npm package and can consume npm modules. Glitch uses pnpm to save disk space for project instances.

Unfortunately, while my project appears to be able to build, dependency resolution fails, apparently due to incompatibilities with how pnpm operates. 

I get the following error (or one like it) in the Google Closure library on all my builds when trying to include npm libraries:

```
Uncaught Error: Undefined nameToPath for left_pad
    at visitNode (base.js:1357)
    at Object.goog.writeScripts_ (base.js:1369)
    at Object.goog.require (base.js:706)
    at (index):24
```

There is otherwise no visible errors from pnpm or the lumo compiler when running on Glitch, but running locally with pnpm I get the following in the log from Lumo:
```
module.js:529                                                  
    throw err;                                                 
    ^                                                          
                                                               
Error: Cannot find module 'resolve'                            
    at Function.Module._resolveFilename (module.js:527:15)     
    at Function.Module._load (module.js:476:23)                
    at Module.require (module.js:568:17)                       
    at require (internal/module.js:11:18)                      
    at [eval]:4:19                                             
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)  
    at Object.runInThisContext (vm.js:139:38)                  
    at Object.<anonymous> ([eval]-wrapper:6:22)                
    at Module._compile (module.js:624:30)                      
    at evalScript (bootstrap_node.js:461:27)                   
```

I can confirm compilation and dependency resolution works fine locally with npm (which sadly isn't an option on Glitch as the instance space is too small).

### pnpm version: 
Local: 2.14.5
Glitch: 2.14.4

### Code to reproduce the issue:
Clone this repo and do `pnpm install` and `pnpm start`: https://github.com/jarcane/cljs-on-glitch-2
Open page in browser at port indicated, and check console log.
Links to misbehaving Glitch examples are also on the corresponding issue I made for lumo-cljs: https://github.com/anmonteiro/lumo/issues/421

### Expected behavior:
Dependencies are resolved and libraries work.

### Actual behavior:
Dependencies fail to resolve, causing run time errors on library references.

### Additional information:

 - `node -v` prints: v8.11.4 for Glitch. Locally I have tested v8.6 and v9.11. 
 - Windows, OS X, or Linux?: Linux (but also occurs under Windows)

**Comment by zkochan** [comment]
Seems like some of the subdependencies use modules that are not declared in their `package.json`

Try to run `pnpm install --force --shamefully-flatten`. 

With flat node_modules I've got a different error: `RangeError: "port" argument must be >= 0 and < 65536`

**Comment by zkochan** [comment]
I get the same error with npm, so I can confirm that the `pnpm install --force --shamefully-flatten` workaround works.

**Comment by jarcane** [comment]
The port error is probably something with the express server. I've not encountered that.

I can however confirm that `--force --shamefully-flatten` fixes the issue locally. Awesome!

I haven't been able to work around it on Glitch yet but that's probably down to their automation not allowing me to trigger the install with flags when it restarts an instance. I'll bring that up with them.

Is there something lumo-cljs can do to fix this issue on their end, to prevent needing the workaround?

**Comment by jarcane** [comment]
I discussed this with @anmonteiro and the issue seems to be a problem between Lumo or CLJS, and the symlinks pnpm makes in the .node_modules dir. Lumo isn't copying over dependencies properly when the target directory is a symlink instead of a normal directory.

Since this doesn't seem to be pnpm's fault, can probably close this.

**Comment by zkochan** [comment]
ok, thanks for looking into it!
