### ISSUE TITLE
PNPM should prioritize linking local (private) packages in repo instead of installing external packages

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1358]
I created a repo for this issue: https://github.com/KSXGitHub/pnpm-issue-0.git

**Comment by zkochan** [comment]
ok, if they are all private, that might make sense

but why not just scoping them? It would reduce complexity that need to be supported by pnpm

**Comment by zkochan** [comment]
wait, if they are private, why don't you just install them as link dependencies?

You can just add foo to bar as `"foo": "link:../bar"`. There is no reason to use semver at all if they are never published

**Comment by KSXGitHub** [comment]
Oh, I never knew that! (I should've noticed when I read shrinkwrap.yaml)

**Comment by KSXGitHub** [comment]
There's a thing though: Does `link:../foo` syntax only works with pnpm? I want my repo to compatible with yarn also.

**Comment by zkochan** [comment]
yes, `link:` works with yarn
but doesn't work with npm. There's an issue about it #1332

**Comment by zkochan** [comment]
you can use `file:` instead of `link:` it will work the same way (and will work on npm as well)

**Comment by KSXGitHub** [comment]
Great! I guess this issue is no longer necessary.
