### ISSUE TITLE
"pnpm import" moves packages to .ignored

### ISSUE THREAD

**Issue by ncoden** [pnpm/pnpm#1368]
### Code to reproduce the issue:

Call `pnpm import` with packages that were not installed by pnpm.

```sh
# install/uninstall a package
npm i -s <package-name> 
# update the pnpm lockfile "shrinkwrap.yaml"
pnpm import
```

This produce the following log the first time:
```
 WARN  Moving @babel/core that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving @babel/preset-env that was installed by a different package manager to "node_modules/.ignored
 (...)
```

And produce the following log if a dependency has been reinstalled by an other package manager ([full log](https://gist.github.com/ncoden/ef795d15895da53f511f38e16d9ffe82)):
```
 WARN  Moving @babel/core that was installed by a different package manager to "node_modules/.ignored
 ERROR  ENOTEMPTY: directory not empty, rename '/Users/(...)/node_modules/@babel/core' -> '/Users/(...)/node_modules/.ignored/@babel/core'
```

### Expected behavior:

> pnpm import generates shrinkwrap.yaml from an npm package-lock.json (or npm-shrinkwrap.json) file.

I expect `pnpm import` to only generate `shrinkwrap.yaml` for pnpm without touching dependencies.

We could argue that this is not the _role_ of `pnpm import` and that it is intended to be used only with packages installed by pnpm, but in this case we should update the documentation and provide an other command to generate `shrinkwrap.yaml` without impact on installed packages.

### Actual behavior:

pnpm affetcts the `node_modules` folder by moving packages that were installed by an other package manager to `node_modules/.ignored`.

**Note**: There is the same bug with `pnpm i --shrinkwrap-only`.

> When used, only updates shrinkwrap.yaml and package.json instead of checking node_modules and downloading dependencies.

### Additional information:

 - `node -v` prints: v8.11.3
 - Windows, OS X, or Linux?: macOS 10.13.6 (17G65)

**Comment by zkochan** [comment]
Thanks for reporting, we'll probably fix it this week

**Comment by ncoden** [comment]
By the way, take a look at our new [GitHub templates](https://github.com/zurb/foundation-sites/tree/develop/.github). You can use them for pnpm if you like them 😄

**Comment by zkochan** [comment]
Wow, cool! I did not know that GitHub now allows several templates for issues :+1:

**Comment by ncoden** [comment]
Yeah, it's really useful. Also we simplified the way we show help in comments, so they look lighter and render better with non-monospace fonts.

**Comment by zkochan** [comment]
:ship: 2.15.3
