### ISSUE TITLE
418 ERROR, when run pnpm install package

### ISSUE THREAD

**Issue by tauruswang** [pnpm/pnpm#1371]
### Code to reproduce the issue:

 pnpm install react-slick --save

 WARN  Moving react-slick that was installed by a different package manager to "node_modules/.ignored
 ERROR  418 I'm a teapot: react-slick (via http://registry.npmjs.org/react-slick)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/react-slick
 ERROR  418 I'm a teapot: classnames (via http://registry.npmjs.org/classnames)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/classnames
 ERROR  418 I'm a teapot: lodash.debounce (via http://registry.npmjs.org/lodash.debounce)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/lodash.debounce
 ERROR  418 I'm a teapot: enquire.js (via http://registry.npmjs.org/enquire.js)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/enquire.js
 ERROR  418 I'm a teapot: resize-observer-polyfill (via http://registry.npmjs.org/resize-observer-polyfill)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/resize-observer-polyfill
 ERROR  418 I'm a teapot: json2mq (via http://registry.npmjs.org/json2mq)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/json2mq
 ERROR  418 I'm a teapot: string-convert (via http://registry.npmjs.org/string-convert)
Using cached meta from /Users/jerryw/.pnpm-store/2/registry.npmjs.org/string-convert
Already up-to-date
Resolving: total 7, reused 7, downloaded 0, done

dependencies:
+ react-slick 0.23.1

 - `node -v` prints:
v10.5.0

 - Windows, OS X, or Linux?:
OS X

**Comment by zkochan** [comment]
Related: #2650

**Comment by zkochan** [comment]
:ship: 5.2.6
