### ISSUE TITLE
Typescript cant find declaration files installed using pnpm

### ISSUE THREAD

**Issue by Gee5ive** [pnpm/pnpm#1375]
### pnpm version:
2.15.3
### Code to reproduce the issue:
Using tsc version 3.0.3 , and electron 2.09 , Ubuntu 18.04

pnpm i -D electron

create a main.ts file

import { app } from 'electron'

### Expected behavior:

Expected the module to be imported with type declarations for use.

### Actual behavior:

> Could not find a declaration file for module 'electron'. '/home/gee5ive/CODE/learn electron/bookmarker/node_modules/.registry.npmjs.org/electron/2.0.9/node_modules/electron/index.js' implicitly has an 'any' type.

### Additional information:

Not actually sure if this is a bug on the pnpm side or an issue with typescript itself, so please excuse me  if I am posting this in the incorrect place..

**Comment by KSXGitHub** [comment]
I think you should share your files in form of a repo.

**Comment by earksiinni** [comment]
The root issue appears to be on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/29221

**Comment by Gee5ive** [comment]
Hey guys. Sorry for not updating this issue, my work for the past 6 months has been in Go and most likely will be for the next year or so, haven't touched pnpm or Typescript in a while so I cant provide any info on the issue at this point.

**Comment by hejjzaeN** [comment]
For me the issue was that I was using _pnpm install_ rather than _pnpm add package_
