### ISSUE TITLE
How to use latest master as a global installed package?

### ISSUE THREAD

**Issue by pomek** [pnpm/pnpm#1390]
Hello,

I am a developer working on CKEditor 5. In our development environment, we're using `Lerna@^2.0.0`. Lerna published version 3.0.0 which contain some breaking changes. We're considering switching to another tool. I'm checking the available tools. One solution is your tool - pnpm.

I would like to use the code from `master` instead of the latest published version on npm. I want to use https://github.com/pnpm/pnpm/pull/1373 to set-up CKEditor 5 environment.

I cloned this repository, then I wanted to call a command `npm link` in order to make `pnpm` installed globally. But firstly, the package should be built. So I called `npm run build`.

Unfortunately, it won't work. NPM informs that `pnpm` package is missing:

![image](https://user-images.githubusercontent.com/2270764/45947482-b8505d00-bff4-11e8-98d0-c18742d90e0b.png)

So, I installed `pnpm` from npm – `npm install pnpm` and called again `npm run build`:

![image](https://user-images.githubusercontent.com/2270764/45947527-e3d34780-bff4-11e8-9f19-633fb302b323.png)

Ok, dependencies aren't installed. Because I needed to uninstall `pnpn` globally, I used a local version installed a moment ago:

```bash
node_modules/.bin/pnpm install
```

But it also ends with an error:

![image](https://user-images.githubusercontent.com/2270764/45947577-0f563200-bff5-11e8-841d-70b8eadd5093.png)

Am I doing anywhere anything wrong? Could you help me with my problem?

**Comment by pomek** [comment]
I forgot to mention about my Node's and npm's versions:

```bash
$ node -v
v10.10.0
$ npm -v
6.4.1
```

**Comment by zkochan** [comment]
Thanks for reaching out. 

To bootstrap the repo, run:

```bash
npm i -g pnpm
pnpm recursive install # or "pnpm m i"
pnpm run build
```

To use it locally, I usually just run it directly.
So in your case it would be something like

```
node /Users/pomek/Projects/ckeditor/pnpm/packages/pnpm/lib/pnpm.js recursive install
```

***

but I can publish the change tonight.

Also, if you post the repository and branch on which you want to test pnpm, I can check it tonight and see if there are any issues.

Thanks for trying out pnpm! We'll help to solve any issues that may happen

**Comment by zkochan** [comment]
oh, in the meantime, you can also check [rush](https://rushjs.io/). It can be used with pnpm. It creates a single `node_modules` and it also handles publishing.

cc @pgonzal

**Comment by pomek** [comment]
`node /Users/pomek/Projects/ckeditor/pnpm/packages/pnpm/lib/pnpm.js recursive install` won't work. But I found this file inside `bin/` directory which is inside the `lib/`.

```bash
node /Users/pomek/Projects/ckeditor/pnpm/packages/pnpm/lib/bin/pnpm.js
```

I am checking how it works.

**Comment by zkochan** [comment]
yes, you are correct with the path. I fixed the path in my message

**Comment by zkochan** [comment]
@pomek if you want to use the new shared shrinkwrap feature, don't forget to add this to the `.npmrc` in the root: `shared-workspace-shrinkwrap = true`

**Comment by pomek** [comment]
Because you helped resolve my issue, I would like to close the issue. Thanks for the helping!
