### ISSUE TITLE
When pnpm-lock.yaml contains invalid syntax

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1395]
There're few occasions where merge conflict happens in `pnpm-lock.yaml` files, causing pnpm (or js-yaml) to yield syntax errors.

## Current workaround

Manually delete every invalid `pnpm-lock.yaml` file.

## Proposal

Unless user specifies `--no-lockfile` or `--frozen-lockfile`, pnpm should ignore the error and continue installing dependencies as if `pnpm-lock.yaml` does not exist.

**Comment by jayvdb** [comment]
If it is merge conflicts, the workaround should be to fetch the last master shrinkwrap.yaml and then rerun `pnpm install` to add anything new in `package.json`.

What would be great is if pnpm couldnt load the yaml, it detected a merge conflict, internally created two yaml files for each of the conflicted versions, and automatically resolved it by merging them, similar to https://www.npmjs.com/package/npm-merge-driver (and perhaps asking them to support pnpm)

**Comment by zkochan** [comment]
This was done.

**Comment by zkochan** [comment]
I was not right. This will be done by this PR: #3217

**Comment by zkochan** [comment]
:ship: 5.18.3
