### ISSUE TITLE
When a package's install script fails, delete the package

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1397]
## Why?

Although `pnpm install` yields error and returns non-zero status when a package's `install` script fails. The second attempt doesn't, which is a false positive.

### Example

```sh
# First attempt
pnpm install package-that-cannot-be-installed # Errors, Non-zero status, expected!

# Second attempt
pnpm install package-that-cannot-be-installed # "up-to-date", not expected!
```

**P.S.** [package-that-cannot-be-installed](https://www.npmjs.com/package/package-that-cannot-be-installed) is a real package that I created specifically for this bug report.

**Comment by zkochan** [comment]
The fastest way to fix this is to save `package.json` and `pnpm-lock.yaml` after running the lifecycle scripts.

**Comment by zkochan** [comment]
:ship: 3.1.1
