### ISSUE TITLE
Feature request: Make pnpm available on semver.io

### ISSUE THREAD

**Issue by onlywei** [pnpm/pnpm#1400]
I can go to these URLs to find out what is the latest version of each of these things:

https://semver.io/yarn
https://semver.io/npm

But I cannot do the same for https://semver.io/pnpm

It seems like it should be somewhat simple to contribute to that repo and get pnpm working there?

**Comment by zkochan** [comment]
I never heard of that service but you can use unpkg at the moment

https://unpkg.com/pnpm/package.json

**Comment by KSXGitHub** [comment]
Why don't you use npm registry directly?

```url
http://registry.npmjs.org/pnpm
http://registry.npmjs.org/pnpm/latest
http://registry.npmjs.org/pnpm/<version>
```

**Comment by zkochan** [comment]
semver.io was archived 
https://github.com/heroku/semver.io
