### ISSUE TITLE
`--filter` doesn't work with symlinked workspace dirs

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1407]
```
/app-1
  packages
    foo
      baz
    bar
/app-2
  packages
    foo-linked -> foo-local
	foo-local -> /app-1/foo
	foo
```

_/app-2/pnpm-workspace.yaml_

```
packages
  - '!packages/foo'
  - '!packages/foo-local'
  - 'packages/foo-linked'
```

```
cd /app-2
pnpm m i --filter baz...
No packages matched the filters in "/app-2"
```

**Comment by vjpr** [comment]
Was a bad symlink on my part.

**Comment by vjpr** [comment]
Actually no, it seems like its still an issue.

Maybe `--filter` uses real paths from `pnpm-workspace.yaml#packages`...this would break my use case.

**Comment by vjpr** [comment]
So the packages are not being found by [`find-packages`](https://github.com/zkochan/find-packages).

**Comment by vjpr** [comment]
So `fast-glob` uses `micromatch`. After fiddling around it appears this fixes it:

`!packages/(foo)`. Adding brackets seems to work.

Its strange. Maybe its a bug in micromatch...

**Comment by zkochan** [comment]
> So fast-glob uses micromatch. After fiddling around it appears I can get the behavior I want using !packages/(foo). Adding the brackets seemed to work. Its strange. Maybe its a bug in micromatch...
>
> Its strange. Maybe its a bug in micromatch...

If something works with glob but does not with `fast-glob`, we should file an issue in `fast-glob`
