### ISSUE TITLE
node-sass postinstall fails with pnpm but works with npm

### ISSUE THREAD

**Issue by baywet** [pnpm/pnpm#1414]
### Code to reproduce the issue: 
`pnpm i node-sass` (also tried with flatten)
https://gist.github.com/baywet/294f8c4b2bcdbec04098caadec3ab4d6

### Expected behavior:
post installation to succeed

### Actual behavior: 
main error message `node-sass@4.9.3 postinstall: `node scripts/build.js` and in the log first error `gyp ERR! stack Error: Command failed: C:\\Python37\\python.EXE -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];`

### Additional information:
- node: 10.11.0
- Windows 10 1803
- python 3.7.0

**Comment by ayan4m1** [comment]
Pretty sure `node-gyp` is still requiring Python 2, as referenced [here](https://github.com/electron-userland/electron-forge/issues/585) and [here](https://github.com/nodejs/node-gyp/issues/1337) and [here](https://github.com/llSourcell/sirajcoin/issues/24) and [here](https://github.com/sass/node-sass/issues/1176#issuecomment-322797617)

**Comment by baywet** [comment]
Thanks for double-checking, I do have Python 2 installed as well.

**Comment by ayan4m1** [comment]
But your error indicates that the Python 3 interpreter is being called during `node-gyp` build. Changing your `%PATH%` around should resolve the issue.

**Comment by baywet** [comment]
upgraded pnpm today to retry, cleared my shrinkwrap and node modules, retried and it works fine now even though environment variables still point to 3.7. Thanks for the help!
