### ISSUE TITLE
Self installer fails to install pnpm@2.17.0

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1434]
My CI suddenly fails: https://travis-ci.org/nodejs-monorepo-templates/typescript-monorepo/builds/445012094

I use `curl -L https://unpkg.com/@pnpm/self-installer | node` to install pnpm

**Comment by zkochan** [comment]
it should work now. I will fix `@pnpm/self-installer` tonight and make `2.17.0` latest again

**Comment by zkochan** [comment]
fixed in latest `@pnpm/self-installer`. No need to do any actions just rebuilding the job next time will work
