### ISSUE TITLE
EINVAL in travis CI

### ISSUE THREAD

**Issue by jvanbruegge** [pnpm/pnpm#1436]
### pnpm version:
2.17.0

### Code to reproduce the issue:
See CI script here: https://github.com/cyclejs-community/one-fits-all/pull/106

### Expected behavior:
Normal installation

### Actual behavior:
ERROR  EINVAL: invalid argument, readlink '/home/travis/build/cyclejs-community/one-fits-all/node_modules/@cycle/dom'

### Additional information:
See CI log here: https://travis-ci.org/cyclejs-community/one-fits-all/jobs/445074038

 - node version 6 and 8
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
It happens probably because `node_modules` was cached.

**Comment by jvanbruegge** [comment]
let me check...

**Comment by jvanbruegge** [comment]
ok, yeah I am dumb. Thank you

**Comment by zkochan** [comment]
no problem
