### ISSUE TITLE
Latest package release on npm has yet to be registered in pnpm

### ISSUE THREAD

**Issue by jmanlapid** [pnpm/pnpm#1441]
pnpm version `2.16.1`

When I run command `pnpm install html-webpack-plugin` - it fails with the following message:

```
ERROR  No matching version found for he@>=1.2.0 <1.3.0

The latest release of he is "1.1.1".
```

Looking on https://www.npmjs.com/package/he, the latest package version `1.2.0` is published. 

How can this be fixed?

**Comment by zkochan** [comment]
I looked into it and I did not find any problems on pnpm's side. Though I did notice that sometimes the npm registry does not update the latest for a long time. That might be the issue, though in this case `he` was published a whole month ago. So unlikely would the registry still not return the new version in meta
