### ISSUE TITLE
pnpm outdated gives no output

### ISSUE THREAD

**Issue by plesiecki** [pnpm/pnpm#1447]
Hello,

Looks like `pnpm outdated` prints nothing. Tested on clean repo with just one outdated dependency. No errors occurred. Exit status is `0`.

### Code to reproduce the issue:
`pnpm

### Expected behavior:

Print information about latest deps versions. 

### Actual behavior:

No output

### Additional information:

 - `node -v` prints: v11.0.0
 - Windows, OS X, or Linux?: Ubuntu 18.04.1 LTS

Peace

**Comment by plesiecki** [comment]
Now I noticed `pnpm outdated` doesn't work if you don't have outdated dep from `dependencies`. Looks like `devDependencies` are not taken into account. In other words `outdated` works only if you have outdated dependency from `dependencies`.

**Comment by zkochan** [comment]
I'll look into it

**Comment by zkochan** [comment]
Please provide a repro
I could not reproduce it

**Comment by plesiecki** [comment]
Steps to reproduce:
```
#inside empty directory
pnpm init
pnpm i -D camelcase@4.0.0 #installing devDep, 5.0 is the latest version
pnpm outdated #no output
pnpm rm camelcase
pnpm i camelcase@4.0.0 #installing same dep but as regular dependency
pnpm outdated #this time it gives an output 
```

**Comment by zkochan** [comment]
:ship: 2.17.6
