### ISSUE TITLE
Workspace linking inside a symlinked dir broken

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1451]
In `supi/src/linkToModules.ts`:

from = /xxx/packages/babel-preset-live-babel-7
to = /xxx/packages/bar/node_modules/@live/babel-preset-live

```
dest = path.resolve(dest);
src = resolveSrc(src, dest);
console.log('symlinkDir', src, dest)
```

```
function resolveSrcOnNonWin(src, dest) {
    return path.relative(path.dirname(dest), path.resolve(src));
}
```

In `symlink-dir`:

from = ../../../../../../../public/babel/babel-preset-live-babel-7 
to = /xxx/packages/bar/node_modules/@live/babel-preset-live

---

A recent change to `symlink-dir` is preventing workspace linking inside a symlinked dir broken. #1204

**Comment by vjpr** [comment]
I think its actually related to the linking of packages to the root .registry dir.

**Comment by zkochan** [comment]
:ship: 2.17.8

**Comment by tomcon** [comment]
pnpm install appears to be hanging on windows just after upgrading to this release

**Comment by vjpr** [comment]
@tomcon What do you mean by hanging? At what stage? What command are you running?

Can you post your `pnpm-debug.log` if one is created.

**Comment by tomcon** [comment]
@vjpr every single pnpm cli command just sits there, cursor blinking, no msgs at all
cannot locate a pnpm-debug.log

**Comment by zkochan** [comment]
I don't know what could cause the hanging (works for me on Windows)

You can try running `pnpm install --reporter ndjson` to see more logs in the console

The changes in 2.17.8 were only these:

4ad43d8480b2da9c7345a6479fefb4850eb73472
fabc5410dcdb8f7663b03de54c4a5d29c6a53221

**Comment by tomcon** [comment]
must have been a local machine issue .... restarted - aok
