### ISSUE TITLE
Dependencies are not installed

### ISSUE THREAD

**Issue by arcanis** [pnpm/pnpm#1460]
### pnpm version:

2.17.6

### Code to reproduce the issue:

**package.json**

```
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
      "@arcanis/trash-react15": "1.0.0"
  }
}
```

### Expected behavior:

I'd expect to have both `react` and `react-dom` in the `node_modules` folder, since `@arcanis/trash-react15` depends on them.

### Actual behavior:

None of them are there

### Additional information:

 - `node -v` prints: 10.10.0
 - Windows, OS X, or Linux?: OSX

**Comment by zkochan** [comment]
You might not understand the node_modules structure that pnpm creates.

Dependencies of `@arcanis/trash-react15` are in `node_modules/.registry.npmjs.org/@arcanis/trash-react15/1.0.0/node_modules`

`node_modules/@arcanis/trash-react15` is a symlink to `node_modules/.registry.npmjs.org/@arcanis/trash-react15/1.0.0/node_modules/@arcanis/trash-react15`

More about the node_modules created by pnpm in [this article](https://dev.to/zkochan/flat-nodemodules-is-not-the-only-way-mo2)

**Comment by arcanis** [comment]
Ohh I actually saw these files, but I missed that `node_modules/.registry.npmjs.org/@arcanis/trash-react15/1.0.1/node_modules/` also had symlinks for `react` and `react-dom`, my bad 👍 

One question you might be able to answer (I'm trying to build a repro to check it by myself but it's a bit convoluted 😅): does pnpm support multiple peer dependencies? For example, let's say I have this:

- A depends on B, C
- B has a dependency on D and E@1.0.0
- C has a dependency on D and E@2.0.0
- D has a peer dependency on E

Will the tree generated by pnpm be able to properly give E@1.0.0 to the version of D used by the B branch, and E@2.0.0 to the version of D used by the C branch?

**Comment by zkochan** [comment]
> Will the tree generated by pnpm be able to properly give E@1.0.0 to the version of D used by the B branch, and E@2.0.0 to the version of D used by the C branch?

yes, it will be as you described.

pnpm solves peer dependencies correctly. The way these peers are saved in the filesystem is described [here](https://pnpm.js.org/docs/en/how-peers-are-resolved.html)

**Comment by arcanis** [comment]
Awesome 👍
