### ISSUE TITLE
`pnpm i foo` is slow with `shared-workspace-shrinkwrap`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1467]
Warnings are printed for all sub-packages.

What causes this and is there a way to speed it up?

**Comment by zkochan** [comment]
:ship: 2.19.0-0

Now when the shared workspace will be up-to-date with all the package.json files, a "Performing headless installation" info message will be printed and installation will be faster

**Comment by zkochan** [comment]
Seems like I have to work on this a bit more

**Comment by zkochan** [comment]
should work fine with v2.19.0-1
