### ISSUE TITLE
Error installing rollup

### ISSUE THREAD

**Issue by ruifortes** [pnpm/pnpm#1477]
### pnpm version:
2.17.8

### Code to reproduce the issue:
pnpm i rollup

https://gist.github.com/ruifortes/f41410c9a8b3ca4383c56dcc22f174fc#file-pnpm-debug-log

### Actual behavior:

EPERM: operation not permitted, link

### Additional information:

 - `node -v` prints: v10.10.0
 - Windows, OS X, or Linux?: Linux

Is it just me?

**Comment by zkochan** [comment]
This was fixed.
