### ISSUE TITLE
Some deps are not installed when peer is resolved in a sub-package and also monorepo root

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1483]
Repro: https://github.com/vjpr/pnpm-issue-1483-babel-preset-env

### Code to reproduce the issue:

```
pnpm m i
cd packages/foo
../../node_modules/.bin/babel index.js
```

### Expected behavior:

Should work.

### Actual behavior:

```
{ Error: Cannot find module 'browserslist'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at _browserslist (/Users/Vaughan/dev-scratch/pnpm-issue-1483-babel-preset-env/node_modules/.registry.npmjs.org/@babel/preset-env/7.0.0/@babel!core@7.1.0/node_modules/@babel/preset-env/lib/normalize-options.js:20:39)
    at Object.<anonymous> (/Users/Vaughan/dev-scratch/pnpm-issue-1483-babel-preset-env/node_modules/.registry.npmjs.org/@babel/preset-env/7.0.0/@babel!core@7.1.0/node_modules/@babel/preset-env/lib/normalize-options.js:80:50)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12) code: 'MODULE_NOT_FOUND' }
```

![screen shot 2018-11-09 at 10 43 35 am](https://user-images.githubusercontent.com/281413/48255212-5749e080-e40c-11e8-8544-8cdb84b15d70.png)

Notice how `browserslist` is missing from the dep set with babel core 7.1.0.

### Additional information:
 
 - `node -v` prints: v8.9.0
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
There is an invalid `shrinkwrap.yaml` in the root
`/@babel/preset-env/7.0.0/@babel!core@7.1.0` doesn't have all the deps. I wonder what are the steps to get a `shrinkwrap.yaml` like that

**Comment by vjpr** [comment]
Try clearing `node_modules` and `shrinkwrap.yaml` and `.npmrc` then run `pnpm m i`. Then add `.npmrc` with:

```
shared-workspace-packages = true
link-workspace-packages = true
```

**Comment by vjpr** [comment]
It was something like as follows:

```
npm init -y
pnis @babel/core@7.0.0
pnis @babel/preset-env@7.1.0 --save-exact
mkdir packages
cd packages
mkdir foo
cd foo
npm init -y
pnis @babel/preset-env@7.0.0 --save-exact
pnis @babel/core@7.0.0 --save-exact
```

pnis = `pnpm i -S`

A sub-package with a different version of an already installed package, with a different peer dep.

**Comment by vjpr** [comment]
@zkochan Can you take a look at this? It's one of those issues that causes strange sporadic failures.

**Comment by zkochan** [comment]
I could not reproduce it yet.

**Comment by vjpr** [comment]
Ok, I will try find the steps to reproduce it in my repro.

**Comment by vjpr** [comment]
Can't reproduce it anymore.

**Comment by zkochan** [comment]
It makes sense because there were some serious fixes and refactorings in the patches of `2.17.x`.

Maybe you started with an earlier version

**Comment by vjpr** [comment]
Cool. I played around with many different orderings of commands and couldn't get it to break.

**Comment by zkochan** [comment]
Unfortunately, I reproduced it.

Steps are:
1. remove `@babel/core` from `packages/foo/package.json`
1. run `pnpm m i`
1. add `@babel/core` to `packages/foo/package.json`
1. run `pnpm m i`

**Comment by zkochan** [comment]
:ship: 2.19.2
