### ISSUE TITLE
RFC: Re-evaluate all dependencies

### ISSUE THREAD

**Issue by wmertens** [pnpm/pnpm#1484]
### pnpm version: 2.18.2

When using hooks via a `pnpmfile.js`, it would be nice to be able to re-evaluate all dependencies.

Even removing node_modules and recreating it is not enough: the existing cached deeper dependencies are still used as-is with their old modules.

**Comment by wmertens** [comment]
I see now that I had a typo in my pnpmfile, so I didn't get the changes I wanted, and I also see that to re-evaluate all deps, I need to delete the `shrinkwrap.yaml` file, correct?

Maybe that should be in the documentation?

**Comment by wmertens** [comment]
No, I was wrong, to re-evaluate deps, you need to `rm -r node_modules`.

Is that acceptable, or should there be some CLI flag that re-evaluates all dependencies?

**Comment by evanleck** [comment]
@wmertens in my experience, removing both is necessary after changing your pnpmfile.js. I'm not sure if that's "correct", but it seems to work. I kind of agree that a simpler way to re-evaluate dependencies would be nice. I wonder if `pnpm rebuild` does that... I haven't used that command with npm before.

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/7662
