### ISSUE TITLE
Support optional peer dependencies

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1486]
As described in https://github.com/yarnpkg/rfcs/pull/105
See also implementation in Yarn https://github.com/yarnpkg/yarn/pull/6671

***

It is important to implement this before making `independent-leaves` `true` by default

**Comment by arcanis** [comment]
@zkochan not in the plans anymore?

**Comment by zkochan** [comment]
@arcanis was it implemented in Yarn?

[The RFC](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md) is in the "accepted" folder (not the "implemented" one). Also, there is no Yarn issue referenced from the RFC

**Comment by ExE-Boss** [comment]
Well, https://github.com/yarnpkg/yarn/pull/6671 has been merged.

**Comment by arcanis** [comment]
Yep, it's implemented and shipped! I've also implemented it in the v2.

The rfc folders aren't super useful... It was a bad idea to have them in retrospect because moving files from one to the other breaks any link that's been made to the initial version 😕

**Comment by zkochan** [comment]
I see. Yep, in that case we'll implement it in pnpm as well

**Comment by arcanis** [comment]
For the record here's the documentation link for `peerDependenciesMeta` and its `optional` key:

https://yarnpkg.github.io/berry/configuration/manifest#peerDependenciesMeta

**Comment by zkochan** [comment]
Thank you! I will work on this soon. I will probably also add a `--save-optional-peer` flag

**Comment by zkochan** [comment]
:ship: [3.2.0-1](https://github.com/pnpm/pnpm/releases/tag/v3.2.0-1)
