### ISSUE TITLE
Some packages appear to not be installed or linked (tslint-microsoft-contrib)

### ISSUE THREAD

**Issue by nickpape-msft** [pnpm/pnpm#1487]
### Code to reproduce the issue:

Install `gulp` globally.

Clone the following repository: https://github.com/nickpape-msft/pnpm-install-issue.git

Run `pnpm install`

Run `gulp`

### Expected behavior:

The build completes successfully.

### Actual behavior:

The build fails with error:

```
Error - [tslint] Failed to load Z:\webpart-test\tslint.json: Could not find custom rule directory: tslint-microsoft-contrib
```

When looking deeper, the root `tslint.json` references `@microsoft/sp-tslint-rules/base-tslint.json`.

When looking at that package, we see this file attempts to bring in rules from `tslint-microsoft-contrib`.

However, this fails because that package (and nothing actually) is in the `node_modules` for `@microsoft/sp-tslint-rules`, despite being listed in the `package.json`:

```json
{
  "name": "@microsoft/sp-tslint-rules",
  "version": "1.7.0",
  "description": "SharePoint Framework tslint rules",
  "license": "SEE LICENSE IN \"EULA\" FOLDER",
  "homepage": "http://aka.ms/spfx",
  "main": "lib/index.js",
  "typings": "lib/index.d.ts",
  "scripts": {
    "build": "gulp test --clean"
  },
  "dependencies": {
    "@microsoft/rush-stack-compiler": "0.1.18",
    "tslint-microsoft-contrib": "~5.2.1",
    "tslint": "~5.9.1",
    "tsutils": "~2.11.2"
  },
  "devDependencies": {
    "gulp": "~3.9.1",
    "@microsoft/sp-build-node": "~1.7.0-dev.8",
    "chai": "~3.5.0",
    "typescript": "~2.4.1"
  }
}
```

![image](https://user-images.githubusercontent.com/17131271/48453841-e8e98300-e769-11e8-89b8-0eafd17cd47f.png)

Interestingly, the shrinkwrap file that gets generated does say this dependency should be installed:

```yaml
  /@microsoft/sp-tslint-rules/1.7.0:
    dependencies:
      '@microsoft/rush-stack-compiler': 0.1.18
      tslint: 5.9.1
      tslint-microsoft-contrib: /tslint-microsoft-contrib/5.2.1/tslint@5.9.1
      tsutils: 2.11.2
    dev: true
    resolution:
      integrity: sha512-fGpvKPEwRLA8ZZKGCnDKFbGglwNmUrG7cb+tc40QK6bIBHyw9wOdu7njdMfh7Jeb9f5Tin4OX361An0u8jHsRw==
  /@microsoft/sp-tslint-rules/1.7.0/typescript@2.4.2:
    dependencies:
      '@microsoft/rush-stack-compiler': 0.1.18
      tslint: /tslint/5.9.1/typescript@2.4.2
      tslint-microsoft-contrib: /tslint-microsoft-contrib/5.2.1/tslint@5.9.1+typescript@2.4.2
      tsutils: /tsutils/2.11.2/typescript@2.4.2
    dev: true
    id: registry.npmjs.org/@microsoft/sp-tslint-rules/1.7.0
    resolution:
      integrity: sha512-fGpvKPEwRLA8ZZKGCnDKFbGglwNmUrG7cb+tc40QK6bIBHyw9wOdu7njdMfh7Jeb9f5Tin4OX361An0u8jHsRw==
```

This seems similar to this issue: https://github.com/pnpm/pnpm/issues/1305

[Related issue for SPFx: SharePoint/sp-dev-docs/issues/2916 ]

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
You are looking at the wrong place for the dependencies of `@microsoft/sp-tslint-rules`.

`node_modules/@microsoft/sp-tslint-rules` is just a symlink to `node_modules/.registry.npmjs.org/@microsoft/sp-tslint-rules/1.7.0/node_modules/@microsoft/sp-tslint-rules/`

dependencies of `@microsoft/sp-tslint-rules` are in `node_modules/.registry.npmjs.org/@microsoft/sp-tslint-rules/1.7.0/node_modules/`

Seems like tslint preserves symlinks when searching for custom rules, which is incorrect. Symlinks should not be preserved when resolving dependencies.

There is nothing we can do on pnpm side. pnpm works correctly in this case.

**Comment by nickpape-msft** [comment]
Thanks @zkochan ! Apologies, this was pnpm outside of Rush (where we have slightly different behaviors and I know to look in different places).

I'll re-file this issue with tslint.
