### ISSUE TITLE
Suggestion for initial installation in the documentation

### ISSUE THREAD

**Issue by qlonik** [pnpm/pnpm#1492]
Hello, 

I'm submitting an improvement for documentation. Right now website suggests to install `pnpm` via `npm` as `npm i -g pnpm`. After this, the website suggests to update pnpm with pnpm for new version. There is slight problem, that there is still one instance of pnpm dangling in the global npm installation folder.

What if instead, the website would suggest to use `npx pnpm i -g pnpm` to install pnpm on the first install? This way, there is no dangling pnpm inside npm and pnpm installed in a standalone way.

**Comment by zkochan** [comment]
Looks like a good idea
