### ISSUE TITLE
PNPM breaks lint-staged?

### ISSUE THREAD

**Issue by aleclarson** [pnpm/pnpm#1496]
It seems that @pnpm is breaking `lint-staged` somehow.

Repro: https://github.com/aleclarson/repro/tree/lint-staged-416

Related: https://github.com/okonet/lint-staged/issues/416

**Comment by morganfree** [comment]
I have the same issue with pnpm. None of the workarounds (fresh node_modules installation, installing rxjs-compat, downgrading list-staged version or switching pnpm version) has worked for me. What has worked for me is installing deps with bare npm.

Versions:
-  lint-staged: 8.0.5 (tried with 7)
- husky: 1.2.0
- pnpm: 2.18.2 (tried with 2.15.3 and 2.19.2)

**Comment by zkochan** [comment]
There is some issue not related to pnpm but seems like it works with flat node_modules, so you can add a `.npmrc` in the root of the repo with the following content:

```
shamefully-flatten=true
```

and once you reinstall node_modules, it will work

**Comment by zkochan** [comment]
you lose the strictness that pnpm provides by default: https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308

and it might make pnpm slightly slower.

**Comment by aleclarson** [comment]
So the problem is that a dependency of `lint-staged` expects a flattened `node_modules`?

**Comment by zkochan** [comment]
either that or some tooling tries to resolve a dependency preserving symlinks.

Node's resolution algorithm does not preserve symlinks. That is why pnpm's symlinked node_modules works

**Comment by morganfree** [comment]
Another workaround which has worked for me - installing rxjs explicitly.

**Comment by aleclarson** [comment]
@morganfree I've tried that already. What versions are you using?

**Comment by aleclarson** [comment]
@morganfree I've tried `pnpm i rxjs -D` to no avail.

**Comment by morganfree** [comment]
Yes, I ran `pnpm i -D rxjs` and the lint-staged script worked.

`package.json` after pnpm install:
```
{
  "name": "lint-staged-416",
  "version": "0.1.0",
  "devDependencies": {
    "husky": "^1.1.4",
    "lint-staged": "^8.0.5",
    "rxjs": "^6.3.3"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "echo"
    ]
  }
}
```

**Comment by aleclarson** [comment]
It's weird. Even though `listr` imports `rxjs`, we still get the error from `any-observable`. Is it possible that two `any-observable` versions are being loaded?

**Comment by aleclarson** [comment]
This is an issue with `listr`. Closing.

**Comment by aleclarson** [comment]
Oh jeez. Looks like `listr` is unmaintained. I'll talk to the `lint-staged` maintainer to see what we should do.

**Comment by nieltg** [comment]
Hi @aleclarson,

I've tried your `lint-staged` fork, but, unfortunately, it didn't work on my machine. I used pnpm 3.4.1 and I suspected that [pnpmfile.js](https://github.com/aleclarson/lint-staged/blob/d8cf58262fb8181a8815b4b4ab6a26e8622b6a2c/pnpmfile.js) wasn't being read. So, I reforked your `lint-staged` with no `pnpmfile.js`, [here](https://github.com/nieltg/lint-staged/commit/22a506569737f4d937d13aa641115db124da088d), and now it works on my machine.

Why do you use `pnpmfile.js` on your repository? Is this behavior intended?

**Comment by aleclarson** [comment]
@nieltg I don't remember. I don't use `lint-staged` anymore, because `pretty-quick` fits my needs and is better maintained.

**Comment by emily-curry** [comment]
For anyone that may be following this, it is no longer an issue in pnpm@^4.0.0.

**Comment by damiangreen** [comment]
Im trying to migrate from yarn to PNPM but  lint-staged isnt working
```
"lint-staged": {
    "*.{js,ts,tsx}": [
      "pnpm eslint --fix",
      "prettier --write",
      "git add --force"
    ],
    "*.{ts,tsx}": [
      "pnpm run find-dead-code"
    ],
    "*.{md,graphql}": [
      "prettier --write",
      "git add --force"
    ],
    "*.css": [
      "stylelint --fix",
      "git add --force"
    ]
  },
  ```
  ive tried both the npmrc  fix above and adding rjxs
  but get [91m[91m×[91m pnpm eslint --fix:[39m
'pnpm' is not recognized as an internal or external command,
operable program or batch file.
