### ISSUE TITLE
`pnpm outdated` should request meta for scoped packages from correct registry

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1504]
It is possible to specify a custom registry for a scope (scope is `@foo` in `@foo/bar`).

As of `v2.19.0` `pnpm outdated` always requests meta via the default registry.

**Note:** the scope of the real package name should be used. This is important to remember because pnpm supports aliases (`"@foo/bar": "npm:@baz/qar@^2.0.0"`)

**Comment by aparajita** [comment]
Now that the github registry is active, this is causing `outdated` to fail with all packages in that registry. This can be worked around by using `updates` for local projects, but for global packages it's kind of a show stopper.

**Comment by aparajita** [comment]
Thank you! Any chance of making this a 3.6.1 release?

**Comment by zkochan** [comment]
Probably only on Friday. I dont have the env to publish it now

**Comment by zkochan** [comment]
:ship: 3.6.1

**Comment by aparajita** [comment]
🚀 🙏
