### ISSUE TITLE
Suggestion: Use clonefiles on APFS

### ISSUE THREAD

**Issue by jrz** [pnpm/pnpm#1505]
The apple file system APFS supports a concept called "clonefiles". These are almost the same as hardlinks, with the exception that they use copy-on-write when the contents (not metadata) of the file is being changed.

This might add an extra level of security against packages or people who like to edit files in the node_modules directory

**Comment by zkochan** [comment]
it is supporter: https://pnpm.js.org/docs/en/pnpm-install.html#package-import-method

run `pnpm set package-import-method reflink`

**Comment by jrz** [comment]
Actually on AFPS, it does not work.

Mac cp doesn't support --reflink

The suitable option for mac is:
     -c    copy files using clonefile(2)

**Comment by zkochan** [comment]
I don't have objections to support this. I don't know what would be the best way. Maybe a new config that uses reflink on Linux and AFPS on Mac?

the change would need to be done mostly [here](https://github.com/pnpm/pnpm/blob/master/packages/package-store/src/storeController/createImportPackage.ts)

cc @etamponi

**Comment by etamponi** [comment]
I am ok with the change as long as we still use --reflink on Linux. Unfortunately the --reflink path is not well tested because it needs a reflink-capable filesystem (btrfs, basically).

**Comment by jrz** [comment]
As an option `clonefile` instead of `reflink` can be used, as this is what it's called, and we don't need to do platform detection.

Smart stuff should be done in `auto`: platform detection in addition to the hardlink check.

**Comment by chpio** [comment]
or we could use [copyfile](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_copyfile_src_dest_flags_callback) with the `COPYFILE_FICLONE` flag, that would be platform independent, but we would need to copy file by file, currently it's just using `cp $fromdir $todir` to copy the whole dir structure.

**Comment by zkochan** [comment]
That sounds good to me

**Comment by zkochan** [comment]
I think for v4 we can do the following changes:

1. `auto` config will try to clone first. If it fails, then hard links will be created. If it fails, then file will be copied.
2. if `clone` is set, copyfile is used with the `COPYFILE_FICLONE_FORCE` config

**Comment by zkochan** [comment]
:ship: 4.0.0-6
