### ISSUE TITLE
pnpm does not support multiple file-systems

### ISSUE THREAD

**Issue by nareddyt** [pnpm/pnpm#1515]
### Overview:

When a developer's computer has multiple drives, pnpm cannot make hard links if the `pnpm-store` and `node-project` are not located on the same hard drive. This happened for me when I configured `pnpm-store` on my SSD but my `node-project` was located on my HDD.

This is an underlying limitation of the OS. I thought this was fixed in #712, but it doesn't seem to work on WSL for me.

I would like to update the docs on https://pnpm.js.org to make this apparent for first-time users (like me)!

### pnpm version: 

2.19.2

### Code to reproduce the issue:

```bash
npm config set store /mnt/c/path_to_pnpm_store
cd /mnt/d/path_to_project
pnpm install
```

Sample Error:

```
 WARN  EXDEV: cross-device link not permitted, link
'/mnt/c/path_to_pnpm_store/2/registry.npmjs.org/source-map/0.5.7/node_modules/source-map/package.json' 
-> 
'/mnt/d/path_to_project/node_modules/.registry.npmjs.org/source-map/0.5.7/node_modules/_tmp_349_ce6ddf902e5b1f75a68455b356324d5d/package.json'
```

### Expected behavior:

- `pnpm install` to be successful.
- Hard link to be successful between the `pnpm store` on my C drive (SSD) and the node project on my D drive (HDD).

### Actual behavior:

It seems like `pnpm` does not support cross-filesystem hard links. This is a limitation of the underlying operating system, as described in [this article](https://medium.com/@meghamohan/hard-link-and-symbolic-link-3cad74e5b5dc):

> Hard links cannot span across filesystem. Why? Hard links are sharing the same inode — they point to the hardware location, instead of directory tree. This means that if you were to try to make hard link between ext3 and ext4, then you’d have some problems — these filesystems are different, so they can’t share the inode.

### Documentation Updates:

I would like to update the documentation on https://pnpm.js.org to make this clearer. I can submit a PR with updates to the following sections:

- `configuring.html`
- `limitations.html`
- `faq.html`

### Additional information:

Running on Windows Linux Subsystem on Windows 10

**Comment by zkochan** [comment]
I don't have objections

here's the website source https://github.com/pnpm/pnpm.github.io
