### ISSUE TITLE
command for listing packages from workspace

### ISSUE THREAD

**Issue by morganfree** [pnpm/pnpm#1519]
It would be nice to have a command which list all found packages from pnpm-workspace.yaml and their related package.json files - something like `pnpm list-packages` - similar to https://github.com/azz/get-monorepo-packages.

In my monorepo I run some scripts and I need to detect which packages have changed before commit. Currently I use `findWorkspacePackages()` function from `'pnpm/lib/findWorkspacePackages` but it would be very convenient to expose that function to a CLI api.

**Comment by zkochan** [comment]
:ship: 2.20.0

**Comment by fdc-viktor-luft** [comment]
In case someone wants to process the result, here is an example command just using plain `node` together with `pnpm`:

```
pnpm m ls --json --depth=-1 | node -e "const path = require('path'); console.log(JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf-8')).map((m) => path.relative(__dirname, m.path)))"
```

Will print you a list of relative paths to all workspace members.

**Comment by towry** [comment]
With jq, sed

`pnpm m ls --json --depth=-1 | jq '.[] | .path' | sed 's?'$PWD/'??'`

To filter some packages, like @pnpm/pnpm

`pnpm -F @pnpm/pnpm m ls --json --depth=-1 | jq '.[] | .path' | sed 's?'$PWD/'??'`

**Comment by ameinhardt** [comment]
pnpm with filter itself
`pnpm --filter "backend..." exec pwd`
