### ISSUE TITLE
Find local projects that depend on packages in store

### ISSUE THREAD

**Issue by nareddyt** [pnpm/pnpm#1527]
# Feature Request

This has already been approved by @zkochan via Gitter. I am currently implementing this feature. Just spelling out use cases and requirements in this issue.

## Overview

Users should be able to find all projects on their local computer that are linked to packages in the pnpm store.

## Use Case

This feature is motivated by the recent security vulnerability found in [flatmap-stream](https://github.com/dominictarr/event-stream/issues/116).

A user should be able to find all node projects on their computer that uses `flatmap-stream`. They should be able to specify version number of do a generic search for the package.

## User Experience

The following outlines the intended user experience

### Input

```bash
pnpm store usages [package]...
pnpm store usages ansi-regex is-odd@2.0.0 is-odd@3.0.0 @babel/core
```

### Output

```text
Query: ansi-regex (any version)
├─┬ Package in store: registry.npmjs.org/ansi-regex/2.1.1
│ ├── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm.github.io/website
│ └── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm
├─┬ Package in store: registry.npmjs.org/ansi-regex/3.0.0
│ ├── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm.github.io/website
│ └── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm
├─┬ Package in store: registry.npmjs.org/ansi-regex/0.2.1
│ └── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm
└─┬ Package in store: registry.npmjs.org/ansi-regex/4.0.0
  └── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm

Query: is-odd@2.0.0
└─┬ Package in store: registry.npmjs.org/is-odd/2.0.0
  └── No pnpm projects using this package

Query: is-odd@3.0.0
└── Not found in store

Query: @babel/core (any version)
└─┬ Package in store: registry.npmjs.org/@babel/core/7.1.6
  └── Project with dependency: /mnt/d/tejun/Github/pnpm/pnpm.github.io/website
```

## Implementation Thoughts

Here are some initial thoughts on implementation:

- The pnpm `store` already stores a map of `package id` -> `project usages`
- Expose API in `SUPI` to directly search this store for the queries packages
- Difficult because user may want to search for just a package name (without version). Cannot just look up in the `store`, have to manually check all keys in the store.
- Must also support looking up non-npm packages, such as tarballs and github links

**Comment by zkochan** [comment]
:ship: 2.21.0
