### ISSUE TITLE
Notify user about scope of the command

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1551]
pnpm commands may affect one package, a subset of packages, many packages. To avoid confusion, an info message should be printed about the scope of the command.

### Inside a workspace

Inside a workspace, when a command affects 1 package (e.g. `pnpm i`), the next message should be printed:

```
Scope: current workspace package
```

When a subset of packages is affected (e.g. `pnpm i -- foo...`), the next message should be printed:

```
Scope: 2 of 10 workspace packages
```

When all workspace packages are affected (e.g. `pnpm m i`):

```
Scope: all 10 workspace packages
```

### Not in a workspace

When not inside a workspace and non-recursive commands are used (e.g. `pnpm i`), no message should be printed about the scope of command.

Recursive command on a subset of packages (e.g. `pnpm recursive install -- foo bar`):

```
Scope: 2 of 10 packages from directory /home/src
```

Recursive command on all packages (e.g. `pnpm m i`):

```
Scope: all 10 packages from directory /home/src
```

### Affected commands

- install
- update
- uninstall
- link
- unlink
- prune
- rebuild

related issue: #1444

cc @vjpr, @KSXGitHub

**Comment by zkochan** [comment]
:ship: 2.22.0

**Comment by vjpr** [comment]
Very useful!
