### ISSUE TITLE
Support directory symlink

### ISSUE THREAD

**Issue by ratson** [pnpm/pnpm#156]
`npm i cordova-icon` will create symlinks correctly, but pnpm does not.
This ls probably because the following in its `package.json`

```
  "directories": {
    "bin": "./bin"
  },
```

Not sure if this is `npm` feature, but would be great if it is supported.

**Comment by rstacruz** [comment]
i guess it's an npm feature, i don't recall making provisions for this.

https://docs.npmjs.com/files/package.json#directoriesbin

thanks for the heads up, in ever knew this was a thing. `cordova-icon@0.7.0` is the package in question.

**Comment by zkochan** [comment]
Landed in [v0.57.0](https://github.com/pnpm/pnpm/releases/tag/v0.57.0)
