### ISSUE TITLE
tsc-watch fails because bin files are not mode a+x

### ISSUE THREAD

**Issue by aquark** [pnpm/pnpm#1577]
### Code to reproduce the issue:

```
pnpm install tsc-watch
./node_modules/.bin/tsc-watch
```

### Expected behavior:

Succeeds.

### Actual behavior:

Fails with this output:
```
.../node_modules/tsc-watch/lib/tsc-watch.js:147
tscProcess.stdout.on('data', buffer => {
                  ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (.../tsc-watch/1.0.31/node_modules/tsc-watch/lib/tsc-watch.js:147:19)
    ...
```

Looking at the source code, `tsc-watch` is using `require.resolve('typescript/bin/tsc')` and then attempting to directly execute the resolved file with `spawn`. This works with `npm` because `npm` does the equivalent of `chmod a+x typescript/bin/tsc` (it does this for all `bin` scripts declared in `package.json`.

### Additional information:

 - `node -v` prints: `v10.13.0`
 - Windows, OS X, or Linux?: macOS

**Comment by aquark** [comment]
I'm working around this by essentially duplicating the `tsc` bin with `chmod a+x` in my package root:
```
#!/usr/bin/env node
require('typescript/lib/tsc.js')
```
and then invoking `tsc-watch --compiler "$(pwd)/tsc"`.

**Comment by jayvdb** [comment]
Relevant source is

```js
..
compiler = 'typescript/bin/tsc';
..
bin = require.resolve( compiler );
..
const tscProcess = spawn(bin, [...args]);
..
tscProcess.stdout.on('data', buffer => {
  ..
}
```

https://github.com/gilamran/tsc-watch/blob/master/lib/tsc-watch.js#L145

**Comment by jayvdb** [comment]
This appears to be a dup of https://github.com/pnpm/pnpm/issues/1075

**Comment by aquark** [comment]
Agreed, resolving
