### ISSUE TITLE
pnpm recursive run: second and later subprocesses hang without output

### ISSUE THREAD

**Issue by aquark** [pnpm/pnpm#1578]
### Code to reproduce the issue:

Here is a minimal example:

```
mkdir -p workspace
cd workspace

for package in foo1 foo2; do
    mkdir -p $package
    cd $package
    pnpm init -y
    sed -i -e 's/"test": .*/"test": "while true; do echo beep; sleep 1; done"/' package.json
    cd ..
done

pnpm recursive test
```

### Expected behavior:

Both packages should output beeps concurrently, like this:

```
Scope: all 2 packages
tmp/workspace/foo1 test$ while true; do echo beep; sleep 1; done
│ beep
│ beep
│ beep
└─ Running...
tmp/workspace/foo2 test$ while true; do echo beep; sleep 1; done
│ beep
│ beep
│ beep
└─ Running...
```

### Actual behavior:

Only the first package outputs beeps:

```
Scope: all 2 packages
tmp/workspace/foo1 test$ while true; do echo beep; sleep 1; done
│ beep
│ beep
│ beep
└─ Running...
tmp/workspace/foo2 test$ while true; do echo beep; sleep 1; done
└─ Running...
```

I originally ran into this problem in a more complex project with subpackages using angular and jest. The way it manifested in that case is that e.g. `pnpm recursive run --no-sort watch` would start the watch process only the first subpackage

### Additional information:

 - `node -v` prints: `v10.13.0`
 - Windows, OS X, or Linux?: macOS sierra

**Comment by zkochan** [comment]
It is great that you've found the reason. I thought it was just a reporting
issue

**Comment by aquark** [comment]
I'm working around this using `lerna run` instead, but I prefer `pnpm`'s output and it would be nice to avoid the extra dev dependency.

**Comment by zkochan** [comment]
:ship: 2.23.1
