### ISSUE TITLE
Unexpected inability to resolve a dependency without flattening

### ISSUE THREAD

**Issue by josephschmitt** [pnpm/pnpm#1579]
### Code to reproduce the issue:

https://github.com/josephschmitt/pnpm-dep-resolution-demo

### Expected behavior:

Application console.log's a list of todos

### Actual behavior:

Unable to resolve the axios dependency of the todos package.

---

This is a bit of an edge case I think, but I'm wondering if you have a recommended solution. I don't want to set axios or node-fetch as dependencies of the base level adapters package since they provide multiple framework adapters. However, I _do_ set it as a dependency of the higher-level todos package. So I would expect that requiring the todos package would successfully be able to use axios. Thoughts? Is this just not something that's possible?

**Comment by zkochan** [comment]
Seems like you need to declare axios and node-fetche as optional peer dependencies.
but we did not implement it yet #1486

Regular peer dependencies will also solve your issue but then you'll get warnings if axios or node-fetch are not present.

Once we implement optional peers, you'll be able to add this to the package.json of `@joe-sh/pnpm-api-adapters`:

```json
"peerDependencies": {
  "axios": "^0.18.0",
  "node-fetch": "^2.3.0"
},
"peerDependenciesMeta": {
  "axios": {
    "optional": true
  },
  "node-fetch": {
    "optional": true
  }
}
```

**Comment by josephschmitt** [comment]
@zkochan the _optional_ part would be nice, since you'd only ever really want one and not the other. Without an optional, you'll always get a warning for the one you're not using.

**Comment by zkochan** [comment]
Closing it in favor of #1486

Also, see an alternative solution described [here](https://github.com/yarnpkg/rfcs/pull/105#issuecomment-451694130)
