### ISSUE TITLE
"pnpm unlink" does not remove global bin

### ISSUE THREAD

**Issue by aleclarson** [pnpm/pnpm#1584]
### Code to reproduce the issue:

- use `pnpm link` in a package with a `bin` field
- confirm the `bin` was properly installed
- use `pnpm unlink`
- confirm the `bin` is still there

### Expected behavior:

The linked `bin` should be removed.

### Additional information:

 - `node -v` prints: v11.3.0
 - macOS v10.14.1

**Comment by kevmt** [comment]
Hey @aleclarson, @zkochan: https://gist.github.com/kevmt/f3efa99fa315f019bc57d26a8e498917

**Comment by alexkuang0** [comment]
Still not working for me on
- pnpm 5.15.3
- Node v15.6.0
- macOS 11.1

**Comment by Lpbzzz** [comment]
use pnpm 8.6.0、node v16.18.1、macos 13.4 . ```pnpm unlink``` does not remove global bin.

**Comment by iDestin** [comment]
`pnpm 7.14.2`、`node v14.21.3` does not work
