### ISSUE TITLE
link-workspace-packages = true has no effect in monorepo?

### ISSUE THREAD

**Issue by dandv** [pnpm/pnpm#1585]
If I'm reading https://pnpm.js.org/docs/en/pnpm-recursive.html correctly, `link-workspace-packages` and `shared-workspace-shrinkwrap` are both false by default. The apparent bug I'm seeing is that after setting `link-workspace-packages = true` in `.npmrc` and running `pnpm recursive install` in [this monorepo](https://github.com/dandv/webstorm-pnpm-eslint-jest), there is no difference in the amount of disk space taken, or the directory structure vs. not setting `link-workspace-packages`.

Regardless of `link-workspace-packages`, each of the two workspaces has a `node_modules` directory with a `.registry.npmjs.org` subdirectory inside it. If I *only* `echo "shared-workspace-shrinkwrap = true" > .npmrc` and reinstall, I get `node_modules` directories with soft links into the repo's `node_modules`.

It appears that "shared-workspace-shrinkwrap = true" does what `link-workspace-packages = true` should do, and `link-workspace-packages = true` alone doesn't do anything regarding dependencies. In this monorepo, the packages don't depend on each other.

I'm on Ubuntu 18.04, node 11.6.0.

### pnpm version: 

2.23.1

### Code to reproduce the issue:

Please see https://github.com/dandv/webstorm-pnpm-eslint-jest and create the `~/space-taken` script.

```sh
$ git clone https://github.com/dandv/webstorm-pnpm-eslint-jest.git
$ cd webstorm-pnpm-eslint-jest
$ echo "" > .npmrc
$ rm -rf **/node_modules node_modules **/shrinkwrap.yaml shrinkwrap.yaml
$ ~/space-taken pnpm recursive install
Scope: all 2 workspace packages
a                                        | +522 ++++++++++++++++++++++++++++++++++++++++++++++++++++
b                                        | +522 ++++++++++++++++++++++++++++++++++++++++++++++++++++
a/node_modules/.registry.npmjs.org/fsevents/1.2.4/node_modules/fsevents: Running install script, done in 60ms
Resolving: total 1044, reused 1044, downloaded 0, done
25840

$ rm -rf **/node_modules node_modules **/shrinkwrap.yaml shrinkwrap.yaml
$ $ ~/space-taken pnpm recursive install --shared-workspace-shrinkwrap
Scope: all 2 workspace packages
.                                        | +522 ++++++++++++++++++++++++++++++++++++++++++++++++++++
node_modules/.registry.npmjs.org/fsevents/1.2.4/node_modules/fsevents: Running install script, done in 59ms
Resolving: total 522, reused 522, downloaded 0
12992
```

### Expected behavior:

Same disk space usage in both situations, or more disk space used when only `shared-workspace-shrinkwrap` was passed.

### Actual behavior:

`shared-workspace-shrinkwrap = true` leads to less disk space, which is [not documented](https://pnpm.js.org/docs/en/pnpm-recursive.html#shared-workspace-shrinkwrap).

**Comment by zkochan** [comment]
When link-workspace-packages is true, packages are symlinked from the
workspace when available. So if there is a foo@1.0.0 in the workspace and a
workspace package has foo@1.0.0 in dependencies then foo@1.0.0 is symlinked
from the workspace not fetched from the registry and hardlinked from the
store

**Comment by dandv** [comment]
Thanks for clarifying.

1. Do I understand correctly that `link-workspace-packages` only makes a difference if packages within the workspace depend on other packages within the workspace? In [my monorepo](https://github.com/dandv/webstorm-pnpm-eslint-jest), the two packages are completely independent from each other, but have the same npm dependencies.

2. I've updated my OP after reading #794 and understanding hard links better. My issue turns out to be really about why `shared-workspace-shrinkwrap = true`, and I've left a [related question on Gitter](https://gitter.im/pnpm/pnpm?at=5c2c642dab910e7d3a0bd34b).

**Comment by dandv** [comment]
PS: I've edited my comment on GitHub and I saw that you replied via email, so you might have seen an older version of it.

**Comment by zkochan** [comment]
it is not true that `shared-workspace-shrinkwrap` = `true` leads to less disk space usage.

Even when `shared-workspace-shrinkwrap` is not true, and every workspace package has all its dependencies in a dedicated `node_modules`, those dependencies are just hard links to packages in the store. So in your repo you'd have eslint hard linked both into the node_modules of a and b but the hardlink in both a and b would point to the same physical files in the same store.

I explained on our FAQ page why it seems as if dependencies consume more space:
https://pnpm.js.org/docs/en/faq.html#why-does-my-node-modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store

**Comment by zkochan** [comment]
> Do I understand correctly that link-workspace-packages only makes a difference if packages within the workspace depend on other packages within the workspace and those depended-on packages are also published to the registry? 

yes and no. It is not a requirment that those packages should be in the registry. The packages may be private or not yet published

**Comment by undefined-moe** [comment]
Yarn links all workspace package into node_modules by default, even no package are depending on them.
I think it's easier to access package by name in this way, instead of locating them by checking all workspace paths.
