### ISSUE TITLE
Incompatible with keyv, but only in monorepo

### ISSUE THREAD

**Issue by dandv** [pnpm/pnpm#1592]
### pnpm version

2.23.1

### Code to reproduce the issue

Please see https://github.com/lukechilds/keyv/issues/70

### Expected behavior

`node a/index.js` should run with no output.

### Actual behavior

> "Error: Cannot find module '@keyv/mongo'".

### Additional information

 - `node -v` prints: v10.13.0 or v11.6.0
 - Linux

**Comment by dandv** [comment]
[Turns out](https://github.com/lukechilds/keyv/issues/70#issuecomment-451620354) the culprit is [this `require` line](https://github.com/lukechilds/keyv/blob/master/src/index.js#L18):
```js
return new (require(adapters[adapter]))(opts);
```

What could be added to the ["Does not work with X" FAQ entry](https://pnpm.js.org/docs/en/faq.html#pnpm-does-not-work-with-your-project-here) to help module authors ensure compatibility with pnpm in cases like these?

**Comment by zkochan** [comment]
Related: #1486

**Comment by zkochan** [comment]
If there is still an issue, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
