### ISSUE TITLE
pnpm and $SASS_BINARY_SITE

### ISSUE THREAD

**Issue by DennisD2** [pnpm/pnpm#1598]
### pnpm version:
2.24.2

### Code to reproduce the issue:
Some transitive dependencies in my package.json depend on Node Sass. I have configured the
environment variable $SASS_BINARY_SITE that prevents building Node Sass during installation.

### Expected behavior:
 This works with no issue for npm. The binary version is downloaded and used.

### Actual behavior:
Using pnpm, I get the following errors:

ERROR in ./node_modules/.somehost.here.com/bootstrap/4.1.2/jquery@3.3.1/node_modules/bootstrap/scss/bootstrap.scss
Module build failed: Error: Missing binding C:<path removed>\ng-frontend\src\node_modules\.somehost.here.com\node-sass\4.11.0\node_modules\node-sass\vendor\win32-x64-59\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (C:<path removed>\src\node_modules\.somehost.here.com\node-sass\4.11.0\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:<path removed>\src\node_modules\.somehost.here.com\node-sass\4.11.0\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.sassLoader (C:<path removed>\src\node_modules\.somehost.here.com\sass-loader\7.1.0\webpack@4.8.3\node_modules\sass-loader\lib\loader.js:46:72)

### Additional information:

 - `node -v` prints:
v9.5.0
 - Windows, OS X, or Linux?:
Windows Server 2008

**Comment by zkochan** [comment]
Have you tried the same with npm? I'd be surprised if this fails only with pnpm as we use the same library for building dependencies as npm: https://www.npmjs.com/package/npm-lifecycle

**Comment by DennisD2** [comment]
Hi, 
of course I tried it with npm as I wrote ('This works with no issue for npm'). You mean you do use the env variable SASS_BINARY_SITE  and a prebuild Node Sass and this works in your environment?
Dennis

**Comment by lonix1** [comment]
@DennisD2 Did you get sass to work with pnpm? I have the same problem (on linux, but same problem with same error)

**Comment by DennisD2** [comment]
No we did not get it to work and reverted to npm.
Maybe your approach will work. 
We simply decided in our projects not to use pnpm but give it a try in some months again. Hopefully the packages having the issue will be fixed then.

**Comment by zkochan** [comment]
@wmertens do you have ideas about this by any chance? I've seen you opened an issue about SASS once.

@DennisD2 I tried setting SASS_BINARY_SITE to a custom location. For instance, I tried 

```sh
SASS_BINARY_SITE=fooooooooooo pnpm i node-sass --reporter append-only
# or using the cross-env npm package on Windows
cross-env SASS_BINARY_SITE=fooooooooooo pnpm i node-sass --reporter append-only
```

When building, node-sass printed: `Invalid URI "fooooooooooo/v4.11.0/linux-x64-59_binding.node"`

So pnpm correctly passed thru the env variable to node-sass.

Let me know if I tried to reproduce it incorrectly (I tried on Windows 10 and Linux)

**Comment by wmertens** [comment]
No ideas 😕

**Comment by zkochan** [comment]
If there is still an issue, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
