### ISSUE TITLE
Non-installable optional deps should be skipped during headless installation

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1600]
As of pnpm v2.25.0, no dependencies are skipped during headless installation.

edit:
~seems like it is also an issue when running installation on a subset of workspace packages that use a shared `shrinkwrap.yaml`~
not an issue

**Comment by jayvdb** [comment]
I suspect this might be the fix for https://github.com/pnpm/pnpm/issues/1384

**Comment by zkochan** [comment]
:ship: 2.25.2
