### ISSUE TITLE
eslint can't find plugins when run from pnpm binstubs

### ISSUE THREAD

**Issue by dandv** [pnpm/pnpm#1602]
I'm trying to use eslint plugins (e.g. eslint-plugin-jest) with pnpm and WebStorm. `eslint` works fine from the command line and can use the plugins, but when Webstorm runs the `eslint` binstub, it fails with

> Failed to load plugin jest: Cannot find module 'eslint-plugin-jest'

Since this seemed like a WebStorm issue, I've filed https://youtrack.jetbrains.com/issue/WEB-36548. WebStorm developers replied there, saying it might be a pnpm issue. @zkochan, can you please take a look?

The issue is rather critical because it essentially makes it impossible to use `eslint` with pnpm in WebStorm (since most projects use an eslint plugin or config).

**Comment by zkochan** [comment]
at first glance it seems like when they require eslint, it is resolved to eslint in the `root/node_modules`

so eslint will search for plugins in `root/node_modules` instead of `root/a/node_modules`. Maybe there's a way to pass the directory in which the plugins are to eslint's programmatic API

Alternatively, you could try to install the plugin (eslint-plugin-jest) in the root of the repo. If we implement (#1355, you'll be able to move even eslint to the root)

**Comment by dandv** [comment]
I can reproduce the problem without WebStorm. When calling `node_modules/eslint/bin/eslint.js *.js` from the `a` directory, eslint can't find the plugin:

```
$ git clone git@github.com:dandv/webstorm-pnpm-eslint-jest.git
Cloning into 'webstorm-pnpm-eslint-jest'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (13/13), done.
Receiving objects: 100% (19/19), 36.86 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (4/4), done.
remote: Total 19 (delta 4), reused 17 (delta 2), pack-reused 0
~/prg$ cd webstorm-pnpm-eslint-jest
~/prg/webstorm-pnpm-eslint-jest$ pnpm multi install
Scope: all 2 workspace packages
Performing headless installation
.                                        | +522 ++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 522, reused 503, downloaded 19, done
node_modules/.registry.npmjs.org/fsevents/1.2.4/node_modules/fsevents: Running install script, done in 55ms
~/prg/webstorm-pnpm-eslint-jest$ cd a
~/prg/webstorm-pnpm-eslint-jest/a$ node_modules/eslint/bin/eslint.js *.js

Oops! Something went wrong! :(

ESLint: 5.11.1.
ESLint couldn't find the plugin "eslint-plugin-jest". This can happen for a couple different reasons:

1. If ESLint is installed globally, [...]

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-jest@latest --save-dev

Path to ESLint package: /home/dandv/prg/webstorm-pnpm-eslint-jest/node_modules/.registry.npmjs.org/eslint/5.11.1/node_modules/eslint

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

pnpm 2.25.2.

**Comment by dandv** [comment]
Still and issue in v3, wondering if there's an easy workaround. Thanks for keeping making pnpm better!

**Comment by skegel13** [comment]
I was running into this issue as well, but I believe I have it working now by going into the ESLint settings in PHPStorm (should be the same) and setting the 'ESLint Package' to `\project\folder\node_modules\.ignored_eslint`.

I am on Windows using WSL but I don't think that should make a difference.

**Comment by shellscape** [comment]
I'm getting the same situation manifesting itself. Additionally, binaries for dependencies are not propagating up to the root node_modules level. Our issues stem from  https://github.com/rollup/eslint-config-rollup. Consider the post-install structure of `node_modules` below:

![Imgur](https://imgur.com/lXsEq0s)

When running `eslint .` from a package script with `pnpm run`, we receive:

```console
sh: eslint: command not found
Scope: current workspace package
 ERROR  Command failed.
```

When running `pnpx eslint .` in a target repo which extends that eslint configuration, we receive an error message about the missing plugin, though it is there. This does not happen with a typical npm setup.

For context, Rollup as an org is evaluating pnpm for a new plugins monorepo that will contain all of the official org plugins.

**Comment by zkochan** [comment]
> binaries for dependencies are not propagating up to the root node_modules level.

Only the binaries of the direct dependencies will be propagated to the root of node_modules. So if eslint is not a directed dependency of your project, it will not be there. If you need a flat node_modules then you can set `shamefully-flatten` to `true`.

> Also observable is that eslint-plugin-import is a direct dependency of eslint-config-rollup yet it is not in node_modules for eslint-config-rollup. It looks very much like things are being left behind.

If you want to see the dependencies of `eslint-config-rollup`, you need to look in `node_modules/.registry.npmjs.org/eslint-config-rollup/0.1.0/node_modules/`

`node_modules/eslint-config-rollup` is just a symlink to 
`node_modules/.registry.npmjs.org/eslint-config-rollup/0.1.0/node_modules/eslint-config-rollup`

More details about this structure you can read at [Flat node_modules is not the only way](https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3).

***

[This RFC in eslint](https://github.com/eslint/rfcs/pull/14) claims that it will fix all the issues with pnpm.

In the meantime, maybe it is possible to hack the dependencies of some of these plugins via [pnpmfile.js](https://pnpm.js.org/en/pnpmfile).

Setting [shamefully-flatten](https://pnpm.js.org/en/npmrc#shamefully-flatten) would also help but that seems like an overkill as only the eslint plugins need to be flattened.

Where can I find the repository with the issue? Is it public?

**Comment by shellscape** [comment]
I've just pushed the WIP branch to https://github.com/rollup/plugins/tree/setup to browse. Thanks for the various links.

I had stumbled across that RFC, but it didn't seem like there was much forward momentum on that, so I wasn't banking on it being something that's going to get done anytime soon.

I had looked into `shamefully_flatten` but I'd like to let pnpm doing its thing, and it didn't seem ideal considering this note:

> Please only use this option when there is no other way to make a project work with pnpm. 

While thinking on this last night, I started to wonder if some configuration on pnpm's side of the works might make sense. Perhaps a config value that would specify which dependencies to "hoist," or which modules' dependencies to "hoist" along with a module. Creating symlinks for deps of top-level deps seems a bit more true to the original intent of the top-level dep, and I'd wager less room for error, over installing the same deps as additional top-levels to get around the issue. Thoughts?

**Comment by zkochan** [comment]
I think what we could do for now is hoisting by some pattern.

Something like `flatten=eslint-*` (https://github.com/pnpm/pnpm/issues/1938#issuecomment-521999312)

**Comment by shellscape** [comment]
Yeah I'd be down for that. I'm working on a local script to do something similar at the moment. Is that something which would drop soon, or should I continue with my stop-gap script?

**Comment by shellscape** [comment]
In the meantime, to get that repo up and running, we've reverted to use `shamefully-flatten` and we are ashamed. But that gets everything working.

FWIW here's my hoisting solution which _almost_ worked:

```js
// scripts/hoist.js

const { existsSync } = require('fs');
const { readlink, symlink, unlink } = require('fs').promises;
const { join } = require('path');

const chalk = require('chalk');

const { hoist } = require('../package.json');

const { log } = console;
const nodeModules = join(__dirname, '../node_modules');

(async () => {
  const packages = Object.keys(hoist);

  for (const parentName of packages) {
    const parentLinkPath = join(nodeModules, parentName);
    const parentLinkTarget = await readlink(parentLinkPath);
    const linkBase = join(nodeModules, parentLinkTarget, '..');

    for (const hoistPkg of hoist[parentName]) {
      const linkTarget = join(linkBase, hoistPkg);
      const linkPath = join(nodeModules, hoistPkg);

      if (existsSync(linkPath)) {
        log(linkPath, 'exists');
        await unlink(linkPath);
      }

      await symlink(linkTarget, linkPath);

      log(chalk`{blue Hosting Package}: ${hoistPkg}`);
    }
  }
})();
```

```json
{
  "name": "@rollup/plugins",
  "private": true,
  "scripts": {
    "lint": "eslint scripts/*",
    "test": "pnpm recursive run test",
    "test:pkg": "pnpm run test --filter"
  },
  "devDependencies": {
    "chalk": "^2.4.2",
    "eslint-config-rollup": "^0.1.0",
    "execa": "^2.0.4",
    "pnpm": "3"
  },
  "hoist": {
    "eslint-config-rollup": [
      "eslint",
      "eslint-plugin-import",
      "eslint-plugin-prettier",
      "prettier"
    ]
  }
}
```

This works fairly well. All of the plugins resolve correctly. But ESLint kind of freaks out and doesn't seem to be able to resolve builtin node requires like `path` and `fs`. It's bizarre, but there's probably a reason for it that I'm not aware of.

**Comment by zkochan** [comment]
Well, this feature will be better if integrated into pnpm. I was working on it a few weeks ago. I guess I can try to finish it. https://github.com/pnpm/pnpm/commit/f1fdcd1c2787d29982795a90ea0c0c75d65d8806

**Comment by zkochan** [comment]
This is probably fixed in pnpm v4

**Comment by shellscape** [comment]
When I have the chance I'll remove the `shameless-hoist` option and give it a try.

**Comment by zkochan** [comment]
`shamefully-hoist` is config name

**Comment by shellscape** [comment]
Hahaha oh well then yes it works, because I'm using that now.
