### ISSUE TITLE
Why can't I install "node"?

### ISSUE THREAD

**Issue by jnardone** [pnpm/pnpm#1608]
### Code to reproduce the issue:
Have a package that installs a discrete version of node.  

This can be simplified with a package.json that looks like this:

```
{
  "dependencies": {
    "node": "10.4.1"
  }
}
```

There's a pre-install step that does most of the heavy lifting, but that apparently isn't happening?  The output is:

```
$ pnpm install 
Packages: +2
++
Resolving: total 2, reused 2, downloaded 0, done
 ERROR  ENOENT: no such file or directory, lstat '/Users/foo/zz/node_modules/.registry.npmjs.org/node/10.4.1/node_modules/node/bin'

```

When installed via `npm` the preinstall step runs correctly and creates the `bin` folder in the `node_modules/node` directory.

### Expected behavior:
package is installed

### Actual behavior:
error

### Additional information:

$ node -v
v10.11.0

This is on MacOS

**Comment by zkochan** [comment]
pnpm links the bin files before running lifecycle hooks.
in this case, node runs a preinstall hook to create the bin.

seems like we should change the sequence of operation in pnpm. Run the preinstall script before linking the bins

**Comment by zkochan** [comment]
or the reason might be that npm and yarn create the symlinks to bin files w/o checking whether the target exists

**Comment by zkochan** [comment]
PR is in progress #1764

**Comment by zkochan** [comment]
:ship: 3.1.1-0

**Comment by 5310** [comment]
Installed pnpm@3.1.1-0 and everything's working! Hurray!
