### ISSUE TITLE
Option for not mutating shrinkwraps with link dir when link-workspace-packages = true

### ISSUE THREAD

**Issue by morganfree** [pnpm/pnpm#1610]
### Actual behavior:
In a monorepo I work with `link-workspace-packages = true` option to install local versions of packages. When this option is set it modifies shrinkwraps from, e.g.:
```
dependencies:
  'foo-module': 1.0.2
  ...
```
into
```
dependencies:
  'foo-module': 'link:../foo'
  ...
```
After that the git directory is dirty with changes which should not be commited.

### Expected behavior:
An option which causes shrinkwraps to not be filled with link to directory but the version of the current local packages.

### Additional information:
I guess shrinkwraps could be overwrite with pnpm hooks, or maybe there is other option to do that?

**Comment by zkochan** [comment]
In the current pnpm (v4), `link-workspace-packages` is `true` by default and this is the way the lockfile should be committed. So I don't think this is an issue.
