### ISSUE TITLE
No warning if peer dep not satisfied in monorepo

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1618]
### Code to reproduce the issue:

https://github.com/vjpr/pnpm-issue-1616-nested-peer-deps/commit/b1c7630e1a1b4534efafe9a49c52e5cf4ac560fc

### Expected behavior:

Warning should print about missing peer (lodash@4) for baz.

`node_modules` should be created for foo, bar, baz and their peer deps should link to the repo root `node_modules`.

### Additional information:

 - `node -v` prints: 11
 - Windows, OS X, or Linux?: macOS

**Comment by vjpr** [comment]
`--strict-peer-dependencies` is not working either...

**Comment by vjpr** [comment]
My bad, I didn't use this deps with peers in a package.json.

**Comment by vjpr** [comment]
This repo reproduces the problem: https://github.com/vjpr/pnpm-issue-1616-nested-peer-deps/commit/684a8fe3eab881db3e1f276fca40450a88e8fc55

**Comment by earksiinni** [comment]
I've confirmed this bug, here's my own repo to reproduce: https://github.com/earksiinni/pnpm-issue-1618-demo/tree/master

**Comment by mcmxcdev** [comment]
Peer dependency warnings are working great with pnpm v7:

![Screenshot from 2022-10-21 19-25-09](https://user-images.githubusercontent.com/16797721/197253890-81e8a163-97f3-4b6d-93a9-6308ef3590bd.png)

All the required `peerDependencies` from `react-apollo` are reported as missing as intended:

```
  /react-apollo/2.5.8:
    resolution: {integrity: sha512-60yOQrnNosxU/tRbOxGDaYNLFcOKmQqxHPhxyvKTlGIaF/rRCXQRKixUgWVffpEupSHHD7psY5k5ZOuZsdsSGQ==}
    peerDependencies:
      apollo-client: ^2.6.3
      graphql: ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0
      react: ^15.0.0 || ^16.0.0
      react-dom: ^15.0.0 || ^16.0.0
    dependencies:
      apollo-utilities: 1.3.4
      fast-json-stable-stringify: 2.1.0
      hoist-non-react-statics: 3.3.2
      lodash.isequal: 4.5.0
      prop-types: 15.8.1
      ts-invariant: 0.4.4
      tslib: 1.14.1
    dev: false
```
