### ISSUE TITLE
pnpm install exact version

### ISSUE THREAD

**Issue by aleclarson** [pnpm/pnpm#1633]
### Code to reproduce the issue:

```sh
pnpm install @types/react@16.7.20
```

### Expected behavior:

The `@types/react` version in `package.json` should be `16.7.20` exactly

### Actual behavior:

A caret is prepended to the version in `package.json` (eg: `^16.7.20`).

When I explicitly declare the version, it should use exactly what I give it, no?

Same with `pnpm install @types/react@~16.7.20`, which currently uses `^16.7.20` instead.

**Note:** The version that's actually installed is correct. Only the `package.json` version is incorrect.

**Note:** The same issue occurs for non-scoped packages, too.

**Note:** The `shrinkwrap.yaml` file also has this issue in its `specifiers` field.

### Additional information:

 - `node v11.7.0`
 - `macOS v10.14.3`

**Comment by zkochan** [comment]
The current behavior was copied from npm. I agree that it would make more sense to preserve the specs.

**Comment by vjpr** [comment]
Good to see this happening!

**Comment by zkochan** [comment]
:ship: 3.0.0-alpha.2 (dist-tag: next-major)
