### ISSUE TITLE
Rename `shrinkwrap.yaml` to `pnpm-lock.yml` or similar for v3

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1635]
Related: https://github.com/pnpm/pnpm/issues/1380

Just an idea as we approach v3. Very minor issue though.

Why?

- Shrinkwrap is dated.
- IMHO config files should include the name of the tool.

**Comment by zkochan** [comment]
Would `pnpm-shrinkwrap.yaml` work?

**Comment by zkochan** [comment]
shrinkwrap might be dated but I like that it does not overlap with file locks. We use file locks to lock the store and node_modules during installation.

Other possible names could be pnpm-snapshot.yaml/pnpm-resolutions.yaml/pnpm-versions.yaml/pnpm-dependencies.yaml

In any case, I am fine with the proposed rename if most people will vote for it

**Comment by jhabdas** [comment]
Remember when bower was forced to rename `package.json` to `bower.json`. Those were the days.

**Comment by jhabdas** [comment]
What do other package managers do?

- Ruby `Gemfile.lock`
- CocoaPods `Podfile.lock`
- Composer `composer.lock`
- Cargo `Cargo.lock`

What should `pnpm` do? `pnpm.lock`

**Comment by jpickwell** [comment]
@jhabdas,
* Yarn `yarn.lock`

**Comment by zkochan** [comment]
It is a yaml file, so we need to keep the appropriate extension. `pnpm-lock.yaml` or `pnpm-lock.yml`

**Comment by jpickwell** [comment]
+1 to `pnmp-lock.yml`

**Comment by jhabdas** [comment]
What if someone wants to use TOML?

**Comment by jhabdas** [comment]
I'm not a user so I just wanted to throw that out there as Node seems to not follow convention.

**Comment by zkochan** [comment]
@KSXGitHub recommends keeping the `.yaml` extension for better backward compatibility, so naming the file `pnpm-lock.yaml`.

Any objections?

**Comment by KSXGitHub** [comment]
Actually, I'm just against `.yml` extension. I don't really care whether it is `pnpm-lock.yaml` or `pnpm.lock`, as long as it does not use `.yml` extension.

**Comment by zkochan** [comment]
:ship: 3.0.0-alpha.3
