### ISSUE TITLE
Move `.registry.npmjs.org` etc. inside `node_modules/.pnpm/` in v4

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1636]
E.g. `node_modules/.pnpm/.registry.npmjs.org`, `node_modules/.pnpm/.github.com`

- This makes a clear separation between the root package's `node_modules` and the monorepo registry.
- For monorepo with multiple Docker images (https://github.com/pnpm/pnpm/issues/1637), `node_modules/.pnpm` could be mounted as a data volume and shared across all Docker builds.
- I've written some logic at some point (I think a workaround for a tool) that reference's `.registry`. If there are other registries, then its hard to write a function that will return all pnpm registry folders. But if all the folders inside `node_modules/.pnpm` were registries, then this logic is easier.

**Comment by zkochan** [comment]
I can make it configurable. We call it the "virtual store".

**Comment by ExE-Boss** [comment]
If they’re inside `.pnpm`, they could be renamed so that they don’t have the leading `.` (e.g.:&nbsp;`node_modules/.pnpm/registry.npmjs.org`, `node_modules/.pnpm/github.com`)

**Comment by zkochan** [comment]
If the virtual store is inside the `node_modules` dir, it should have a leading dot because otherwise, Node will think it is a module dir. But it may be a sibling dir in the same directory where node_modules is, without the dot

**Comment by zkochan** [comment]
@vjpr this was done in v4.0.0-1. You can try it via `pnpm@next`

I wonder if this should be configurable.
Personally, I would prefer it to be in an adjusent directory to `node_modules`. It would make the stacktraces nicer.
