### ISSUE TITLE
In `@pnpm/shrinkwrap-file`:  `Error: Cannot find module '@pnpm/logger'`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1638]
```
import shrinkwrapFile from '@pnpm/shrinkwrap-file'
```

```
    at Object.<anonymous> (/xxx/node_modules/.registry.npmjs.org/@pnpm/shrinkwrap-file/1.0.1/node_modules/@pnpm/shrinkwrap-file/src/logger.ts:1:1)
```

---

Ah, its a peer dep. I just ignored the peer dep warnings...

**Comment by zkochan** [comment]
yep, `@pnpm/logger` is a peer dependency of most of the pnpm packages 

https://github.com/pnpm/pnpm/blob/52046a31b9fb57e8c17f43551e6d507b960c6029/packages/shrinkwrap-file/package.json#L35-L37
