### ISSUE TITLE
`recursive run` does not run scripts on GitLab CI

### ISSUE THREAD

**Issue by borowski-9ld** [pnpm/pnpm#1644]
### pnpm version:
Latest available from https://unpkg.com/@pnpm/self-installer. Probably: 2.25.4

### Code to reproduce the issue:
https://gitlab.com/borowski9ld/pnpm-monorepo

### Expected behavior:

What I'm trying to achieve is to run a script from each package with GitLab CI. 

I've created script `x` in my [workspace package](https://gitlab.com/borowski9ld/pnpm-monorepo/blob/master/package.json)

It should try to run recursively script `x` from packages [app1](https://gitlab.com/borowski9ld/pnpm-monorepo/blob/master/apps/app1/package.json), [app2](https://gitlab.com/borowski9ld/pnpm-monorepo/blob/master/apps/app2/package.json) and [lib1](https://gitlab.com/borowski9ld/pnpm-monorepo/blob/master/libs/lib1/package.json)

Script `x` from  [app2](https://gitlab.com/borowski9ld/pnpm-monorepo/blob/master/apps/app2/package.json) raises an error, so it should break the recursive execution and in result fail the CI job.

I've recreated expected behavior using `exec` command. ([code](https://gitlab.com/borowski9ld/pnpm-monorepo/tree/26e9f4c1b15099477aaaa0eaddc8fd0f5307266c) | [job)](https://gitlab.com/borowski9ld/pnpm-monorepo/-/jobs/155283690)

### Actual behavior:

It looks like none of the scripts were run. ([job](https://gitlab.com/borowski9ld/pnpm-monorepo/-/jobs/155283894))

### Additional information:

I've been running the script on Unix and Windows machine. In both cases it acted according to expectation. Problem appears only when I run it on GitLab CI.

**Comment by zkochan** [comment]
Seems like this works: `"x": "pnpm recursive exec -- pnpm run x"`

**Comment by zkochan** [comment]
Here's the piece of code that exits the run for some reason

https://github.com/zkochan/lifecycle/blob/ec87afa663a6f281a9a5850c2801bfb05aaff3eb/index.js#L72-L76

Using `--unsafe-perm` seem to help

```
pnpm recursive run x --unsafe-perm
```

**Comment by zkochan** [comment]
OK, so the issue is that unsafePerm should be always true when running `pnpm run`. That's easy to fix

**Comment by zkochan** [comment]
:ship: 2.25.6
