### ISSUE TITLE
pnpm should warn on mispelt unrecognized flags

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1645]
```
pnpm m ls --procelain
```

Command runs, but no porcelain output (mispelling), and no error of invalid flag.

```
pnpm m ls --porcelain
```

Command runs with porcelain.

**Comment by zkochan** [comment]
yes, pnpm should fail on invalid flags.
let's make it in v3

**Comment by zkochan** [comment]
I want this to be even smarter (I did not find any existing libs that can help). I want pnpm fail if a flag from another command is used. Like `pnpm update --save-dev` should fail
