### ISSUE TITLE
Filtering via -- for the test/run/exec commands

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1646]
There are two ways to filter workspace packages:

1. via the `--filter` flag
2. via `--`

However, as of pnpm v2 filtering via `--` is not supported in the following commands: test/run/exec. Those three commands use `--` to separate args of the command from args that are passed down to the child processes.

Suggested solution: consider every argument that is after the command name (if the command name is test/run/exec) to be arguments of child processes.

```
pnpm <flags of pnpm run> run <flags that are passed to the subprocess> -- <filters>
```

So the next command from pnpm v2:

```
pnpm recursive exec --workspace-concurrency 1 --filter foo... -- rm -rf node_modules
```

Would look like this in pnpm v3:

```
pnpm recursive --workspace-concurrency 1 exec rm -rf node_modules -- foo...
```

cc @vjpr

**Comment by zkochan** [comment]
I use it all the time with pnpm.

I think it will cause no harm as `--` is rarely used with `pnpm test/run` and I don't even know what flags are supported by test/run.

Also, exec looks nicer w/o the `--`.

**Comment by vjpr** [comment]
It's slightly confusing/non-standard for je community though because of the
'npm run foo -- bar' convention.

**Comment by zkochan** [comment]
Only advanced users of npm know about the `--` in run commands. On the other hand, with this change, `--` would behave the same on all pnpm commands. I think it is a good idea but that's my personal opinion.

cc @DanielRuf @etamponi @KSXGitHub @aleclarson

**Comment by aleclarson** [comment]
I'm a fan of quotes:
```
pnpm recursive exec "rm -rf node_modules" --workspace-concurrency=1 -- foo...
```
..but could live with any of the options here! (thanks for the mention)

**Comment by KSXGitHub** [comment]
I don't like this:
  * npm already use `--` as a way to pass arguments (and not only advanced npm/pnpm users know that), don't change it unless npm changes it.
  * This would go against traditional POSIX convention.

I think `--filter` alone is enough:
  * Folder names (subjects of filtering) are rarely (if at all) start with a '-' character, so there're no needs for filtering to support such unusual names.
  * `--filter` is already consistent, only advanced pnpm users use `--` for filtering.

> Also, exec looks nicer w/o the `--`.

I agree, in fact, npm/yarn already did that. But this does not mean `--` should be used for filtering.

> Only advanced users of npm know about the `--` in run commands.

By "advanced" you meant "used npm for long enough"? Then that's the majority of users! How many users do you think that know about pnpm and yarn but aren't already "advanced" enough with npm? None! That's what I think.

**Comment by DanielRuf** [comment]
I agree with @vjpr and @KSXGitHub.

This would make it a bit harder for my team to understand how it works as `--` to pass arguments to the underlying process is often used but would not be used for filtering. Yarn also filters packages like `yarn list --pattern`.

**Comment by zkochan** [comment]
I have an alternative solution. Using single dash instead of double dash. See #2012
