### ISSUE TITLE
better CLI docs?

### ISSUE THREAD

**Issue by tomByrer** [pnpm/pnpm#1647]
`pnpm` / `pnpm --help` gives only bare-bones switch listing, can a few extra descriptive words after each be added the the CLI output please?

Also, `pnpm link --help` (etc) with a longer description could help, but perhaps this should be covered by [tldr CLI help system](https://tldr.sh/).

For that matter, the website's docs are a bit sparse.  I'm not an expert at `npm`, but the docs seems to assume users are.  (Perhaps a separate issue, but I was going to copy/paste short descriptions from the website into the CLI. & submit a PR myself, but seems I won't have enough info.)

Thanks for your great tool!

**Comment by zkochan** [comment]
Sure

**Comment by rajasegar** [comment]
Can I pick this up? @zkochan If yes, can you please assign it to me?

**Comment by tomByrer** [comment]
Please do @rajasegar

**Comment by rajasegar** [comment]
@zkochan I have a couple of questions
1. How can I run specific tests inside a package? Like I want to run tests in this file only 
https://github.com/pnpm/pnpm/blob/8dbc71f332b425bc266387934c6e53b13911a5ec/packages/pnpm/test/help.spec.ts
2. Is the above test file is the right place to write tests for this PR?

**Comment by rajasegar** [comment]
For future me, to test the changes locally run 
```
$ cd packages/pnpm
$ pnpm run compile
$ ./bin/pnpm.js --help
```
