### ISSUE TITLE
--filter not documented

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1649]
I couldn't find the documentation for this...

**Comment by zkochan** [comment]
https://pnpm.js.org/docs/en/pnpm-recursive.html#lt-package-selector-filter-lt-package-selector

**Comment by vjpr** [comment]
We should put a link from the `pnpm install` page because of `shared-workspace-shrinkwrap`.

**Comment by zkochan** [comment]
filtering works with and without shared-workspace-shrinkwrap

**Comment by zkochan** [comment]
Here's a separate page about filtering: https://pnpm.js.org/en/filtering

Also, links added to each command that implements filtering
