### ISSUE TITLE
`pnpm i --porcelain --filter` should not print "No packages matched the filter in ..."

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1650]
If you are reading the stdout, this will cause issues.

It should return nothing when porcelain is enabled.

I think its fine for the status code to be kept at success.

**Comment by zkochan** [comment]
Do you mean the `pnpm ls` command?
`--porcelain` doesn't really do anything with the `pnpm i` command

**Comment by zkochan** [comment]
related #2265
