### ISSUE TITLE
`pnpm m ls` command to get dependencies of the package located at a path

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1651]
From https://github.com/pnpm/pnpm/issues/1637#issuecomment-460946814:

Also, if I want to get the dependencies of the root package...

Is something like this possible:

```
pnpm m ls --filter=. ...
```
I want to be able to "get dependencies of the package located at a path".

I looking in `pnpm i --help` and it doesn't seem to have the option.

Maybe we need something like `--filter-by-pkg-at-path-with-dependencies=.` and `--filter-by-pkg-at-path-with-dependants=.`?

**Comment by zkochan** [comment]
Filtering for dependencies/dependents is only possible by package name at the moment. So `foo...`, `...foo`.

new syntax suggestion for filtering by path may be proposed here: https://github.com/pnpm/spec/blob/master/workspace/filtering.md

**Comment by zkochan** [comment]
pnpm v4.6 will have filtering by changed packages. It will use [] to specify the commit/branch. And it supports the `...` syntax. Maybe we could allow putting path in `[]`? In that case we'd be able to do something like `...[.]` or `[../foo]...`

**Comment by zkochan** [comment]
So I think there are 3 ways of doing this

1. Reuse the `[]` syntax. I think we can differentiate git commits/branches from paths.
2. Use some other wrappers. For instance, `()`.
3. Add a flag. For instance, `pnpm t --filter . --include-dependencies`

I think I'd vote for 2 at the moment but we can do 3 in the future as well.

cc @pnpm/collaborators

**Comment by zkochan** [comment]
:ship: [4.7.0-1](https://github.com/pnpm/pnpm/releases/tag/v4.7.0-1)
