### ISSUE TITLE
Node version doesn't impact cached side effects

### ISSUE THREAD

**Issue by wmertens** [pnpm/pnpm#1656]
### Code to reproduce the issue:

0. `npm set side-effects-cache true`
1. install something with Node 8
2. upgrade to Node 10
3. run `pnpm i`

### Expected behavior:

4. everything with side effects gets re-installed

### Actual behavior:

4. `Already up-to-date`

### Additional information:

 - `node -v` prints: `v10.15.0`
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
Related #1394
