### ISSUE TITLE
"pnpm update" is not updating package.json

### ISSUE THREAD

**Issue by ruifortes** [pnpm/pnpm#1657]
"pnpm update" updates  shrinkwrap.yaml but not package.json
Shouldn't it?

**Comment by zkochan** [comment]
`pnpm update` does not update `package.json`, it only updates packages to the latest versions that satisfy the ranges in the current `package.json`.

To update `package.json` with new ranges, currently you have to run something like `pnpm update foo@latest`.

**Comment by Glinkis** [comment]
It would be awesome if you could do something akin to what yarn does, and have a command like -
`update-interactive --latest` which allows you to pick and choose what to update.

**Comment by zkochan** [comment]
That would be great. I was thinking about `pnpm update -i`

See #1012

**Comment by marcelcremer** [comment]
Hey there,

I came here because I tried pnpm update --save and it said "Unknown Option 'save'". Afterwards I used pnpm update and found out, that it didn't update the package.json like the OT already wrote 😃 

Maybe it would make sense to implement --save parameter for update to stay compatible with npm?

Cheers,
Marcel

**Comment by zkochan** [comment]
I plan to make this change in the next minor version. Also, related #2130

**Comment by zkochan** [comment]
:ship: [4.2.0-0](https://github.com/pnpm/pnpm/releases/tag/v4.2.0-0)

**Comment by mbledkowski** [comment]
Use the `--latest` option to update the ranges in `package.json`
`pnpm update --latest`

**Comment by hyezoprk** [comment]
pnpm update -i -L works for me.
(-i = interactive, -L = latest)

**Comment by saurabhsri108** [comment]
Used the above one pnpm update -i -L. It updates pnpm-lock file but not package.json

**Comment by terrablue** [comment]
@zkochan is this really working as expected?

`pnpm update -i -L` only suggests major version updates, and indeed changes `package.json`
`pnpm update -i` updates the installed deps, but not `package.json`
`pnpm update @types/node@latest` *does* update `package.json` (in my case, `@types/node` from `^20.14.6` to `^20.14.9`), but only for this specific package

Is there are no way to reflect all non-major package updates in `package.json`?

**Comment by sk-enya** [comment]
I was also facing the issue, so update the pnpm to latest version and and executed below so reflected the version changes in package.json.

`pnpm add -g pnpm` >> to update pnpm
`pnpm update --latest` >> to update packages.

**Comment by Pnlvfx** [comment]
What is the solution to this issue?
