### ISSUE TITLE
did not install all dependancies 

### ISSUE THREAD

**Issue by tomByrer** [pnpm/pnpm#1661]
### pnpm version: 2.25.6
Windows 10 Home, `node -v` prints: v11.9.0
Using nvm-windows

### Code to reproduce the issue:
Simple repo, with only axios, parcel-plugin-typescript, react, react-dom, & typescript dependencies. 
https://github.com/tvaisanen/parcel-react-webworker-fetch
I ran `parcel` to bundle, & got the error.
I re-ran `pnpm install` to ensure all deps were downloaded; nothing new was.

### Expected behavior:
Bundle with out errors

### Actual behavior:
App would not run/bundle:
```
Build Error
...\node_modules\react\cjs\react.development.js:18:22: Cannot resolve dependency 'object-assign'
> 18 | var _assign = require('object-assign');
```

### Additional information:
I deleted node_modules, `yarn install`, then parcel built fine.  So seems `pnpm` did not install the dependency.

**Comment by SkReD** [comment]
Maybe your case is fit to common cases, described in FAQ
https://pnpm.js.org/docs/en/faq.html#pnpm-does-not-work-with-your-project-here

**Comment by zkochan** [comment]
Seems like it is an issue with the way parcel resolves dependencies. Probably it preserves symlinks, which is not how Node resolves dependencies.

With `pnpm i --shamefully-hoist` it works.
