### ISSUE TITLE
Installing WildDuck with pnpm

### ISSUE THREAD

**Issue by ssimpo** [pnpm/pnpm#1663]
I not sure, which repo I should be raising this as an issue on, but her goes...

_hopefully, you can point me in the right direction and we can either fix this here or raise it elsewhere and close this_

[Wildduck](https://github.com/nodemailer/wild-config) will not install with pnpm.  I have managed to get it working using my own pnpmfile.js:

```javascript
"use strict";

const replacer = {
	"github:openpgpjs/asmcrypto#6e4e407":"github:openpgpjs/asmcrypto#6e4e407b9b8ae317925a9e677cc7b4de3e447e83",
	"github:openpgpjs/elliptic#ad81845":"github:openpgpjs/elliptic#ad81845f693effa5b4b6d07db2e82112de222f48",
	"github:openpgpjs/seek-bzip#3aca608":"github:openpgpjs/seek-bzip#3aca608ffedc055a1da1d898ecb244804ef32209",
	"github:openpgpjs/web-stream-tools#84a4977":"github:openpgpjs/web-stream-tools#84a497715c9df271a673f8616318264ab42ab3cc"
};

function readPackage(pkg) {
	if (pkg.name === "asmcrypto.js") { // Prepare script needs dev deps.
		Object.assign(pkg.dependencies, pkg.devDependencies);
	} 
	
	Object.keys(pkg.dependencies || {}).forEach(pkgName=>{ // pnpm does not like short git refs
		if (pkg.dependencies[pkgName] in replacer) pkg.dependencies[pkgName] = replacer[pkg.dependencies[pkgName]];
	});

	return pkg;
}

module.exports = {
	hooks: {
		readPackage
	}
};
```

Basically, to get it to work, I need two work-arounds that the above implements:
- The pnpm installer does not like short git refs.  This is already raised elsewhere: #1127 
- The other issue is that asmcrypto.js use a prepare script that needs the dependencies in devDependencies.  I am assuming this is a pnpm issue as works in npm/yarn but of course that might be a wrong assumption.  My work-around is mix in the devDependencies into dependencies (using the --dev switch also works but what if you are doing a --production install).

So, basically, I'd expect pnpn to install the devDependencies when a prepare script is used.  I may have got this totally wrong and asmcrypto.js should put the deps in the right place (or just need to refactor their build to something better). It could also be because the asmcrypto.js is a forked version from github that OpenGPGJs uses (ie. not a NPM package).

Hope this is clear enough and makes sense?

If this is not an issue with pnpm, happy to raise it elsewhere.  Keep up the good work, I really like pnpm.

**Comment by zkochan** [comment]
Seems like the second issue is pnpm issue as well. We talked about it here: #855

**Comment by ssimpo** [comment]
Okay, thanks.
 
In that case, probably worth closing this issue as already covered in #855 and #1127.
