### ISSUE TITLE
Proposal: Add packages to store from a shrinkwrap file

### ISSUE THREAD

**Issue by thynson** [pnpm/pnpm#1670]

**Comment by thynson** [comment]
I just realize this could be an easy solution for the problem wanted to be resolved by #2257, w/o changes to lockfile format or introducing new manifest files. 
See https://github.com/pnpm/pnpm/issues/2257#issuecomment-783046124

**Comment by zkochan** [comment]
Looks like this is covered by the [pnpm fetch](https://pnpm.io/cli/fetch) command.
