### ISSUE TITLE
Save Strict not respected when installing dev dependencies recursively

### ISSUE THREAD

**Issue by dschnare** [pnpm/pnpm#1672]
### Code to reproduce the issue:

```bash
mkdir pnpm-test
cd pnpm-test
```

```yaml
# pnpm-test/pnpm-workspace.yaml
packages:
  - 'packages/**'
```

```bash
pnpm init --yes
echo 'save-strict=true' > .npmrc
mkdir packages
mkdir packages/one
cd packages/one
pnpm init --yes
pnpm recursive install eslint -D
```

### Expected behavior:

All dev dependencies installed should be written to the package.json file respecting the `save-strict` NPM config setting.

### Actual behavior:

All dev dependencies written to the package.json file use a semver like: `^5.14.0`.

### Additional information:

 - `node -v` prints: v10.14.1
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
What is `save-strict`? I've never heard about this config. I just tried your steps with `save-exact` and pnpm v3.1.1 and it works as expacted.

**Comment by zkochan** [comment]
Please use `save-exact` instead of `save-strict`.
