### ISSUE TITLE
shamefully-flatten not compatible with @vue/cli-service

### ISSUE THREAD

**Issue by sodatea** [pnpm/pnpm#1678]
### pnpm version:

2.25.6

### Code to reproduce the issue:

Also see https://github.com/vuejs/vue-cli/issues/2703

```
pnpm i -g @vue/cli
vue create -d my-project
cd my-project
rm -rf node_modules
pnpm install --shamefully-flatten
pnpm run serve
```

### Expected behavior:

```
App running at:

* Local:   http://localhost:8080/
* Network: http://192.168.0.218:8080/
```

### Actual behavior:

```
......
ERROR Failed to compile with 1 errors 08:39:15

This dependency was not found:

-!../node_modules/.registry.npm.taobao.org/cache-loader/1.2.2/webpack@4.20.2/n
ode_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/.registry.npm.ta
obao.org/babel-loader/8.0.4/@babel!core@7.0.0-beta.47/node_modules/babel-loader/
lib/index.js!../node_modules/.registry.npm.taobao.org/ts-loader/4.5.0/node_modul
es/ts-loader/index.js??ref--13-2!../node_modules/.registry.npm.taobao.org/cache-
loader/1.2.2/webpack@4.20.2/node_modules/cache-loader/dist/cjs.js??ref--0-0!../n
ode_modules/.registry.npm.taobao.org/vue-loader/15.4.2/css-loader@1.0.0/node_mod
ules/vue-loader/lib/index.js??vue-loader-options!./App.vue?vue&type=script&lang=
ts& in ./src/App.vue?vue&type=script&lang=ts&
To install it, you can run: npm install --save -!../node_modules/.registry.npm.t
aobao.org/cache-loader/1.2.2/webpack@4.20.2/node_modules/cache-loader/dist/cjs.j
s??ref--13-0!../node_modules/.registry.npm.taobao.org/babel-loader/8.0.4/@babel!
core@7.0.0-beta.47/node_modules/babel-loader/lib/index.js!../node_modules/.regis
try.npm.taobao.org/ts-loader/4.5.0/node_modules/ts-loader/index.js??ref--13-2!..
/node_modules/.registry.npm.taobao.org/cache-loader/1.2.2/webpack@4.20.2/node_mo
dules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/.registry.npm.taobao.or
g/vue-loader/15.4.2/css-loader@1.0.0/node_modules/vue-loader/lib/index.js??vue-l
oader-options!./App.vue?vue&type=script&lang=ts&
No type errors found
No lint errors found
Version: typescript 3.1.2, tslint 5.11.0
Time: 3989ms
```

### Additional information:

 - `node -v` prints: v10.15.1
 - Windows, OS X, or Linux?: macOS

This issue could be circumvented by running `pnpm i -D babel-loader --shamefully-flatten` but I don't understand why, so I'm concerning that this may also be broken in the future.

So I'm reluctant to add this workaround in Vue CLI's default setup. And it is now the only remaining blocking issue for us to add pnpm to Vue CLI's officially supported package managers.

**Comment by zkochan** [comment]
I noticed 1 issue, the `@vue/cli-service` runs webpack with some plugins (babel-loader and eslint-loader). babel-loader is a dep of `@vue/cli-plugin-babel` and `eslint-loader` is a dep of `@vue/cli-plugin-eslint`. When node_modules is flat, webpack can resolve these plugins from the root of the node_modules dir. But pnpm creates a non-flat node_modules, so these plugins should be probably resolved by `@vue/cli-service` and passed to webpack

**Comment by sodatea** [comment]
Ah I think I just found the culprit.

It's not the directory structure, but the exclamation mark in the path (`@babel!core`) conflicting with webpack loader syntax.
Should be a duplicate of https://github.com/pnpm/pnpm/issues/1601

Just tested with `pnpm@next-major` and it works perfectly fine.
Now the question becomes: is there any way (such as a command line argument for `pnpm install`) to circumvent this issue in pnpm v2?

**Comment by zkochan** [comment]
I think that is not necessary. pnpm v3 will be the latest soon.

**Comment by zkochan** [comment]
So pnpm v3 is now latest. But you say shamefully-flatten is still needed? It would be great to fix the toolings to make them work without flat node_modules

**Comment by sodatea** [comment]
I would love to make it work without flatten directory structure.
But it is mostly a webpack issue: webpack seems to have been using a different algorithm for loaders. In the case of Vue CLI we utilized the `resolveLoader.modules`  option to make sure a nested depended loader can still be found (e.g. https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-babel/index.js#L24). But this trick does not work well with pnpm and I've no idea how to fix it.

**Comment by clemyan** [comment]
I noticed this problem in the past and ended up switching to Yarn.

I think the best/cleanest/most portable solution is to use `resolveLoader.alias` and `require.resolve` to map loaders directly to absolute paths. (i.e. `config.resolveLoader.alias.set('babel-loader$', require.resolve('babel-loader'))`)

**Comment by zkochan** [comment]
Related: https://github.com/webpack/webpack/issues/5087

**Comment by zkochan** [comment]
This might be resolved by pnpm v4

**Comment by TemaSM** [comment]
@zkochan tested pnpm v4 with brand new Vue CLI 3 app (3.11.0) without applying `shamefully-flatten` or `shamefully-hoist` and build task still fails with messages like:
`Failed to resolve loader ...` or `Failed to resolve dependency ...`
but applying `shamefully-hoist` during `pnpm install` fixes the "problem".
So I updated my answer: https://github.com/vuejs/vue-cli/issues/2703#issuecomment-459908358

**Comment by wbern** [comment]
I just tested with `@vue/cli version@4.1.1` and the steps in this initial issue seem to be working for me. This is my package.json in the vue-cli created package:

```
  "dependencies": {
    "core-js": "^3.4.3",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.6.10"
  },
```

As a bonus, I also tested the same thing in Rush, and it appears to be working without issues.

**Comment by bmarwell** [comment]
For whoever may read this: I downgraded node from 12 to 10.x, and now it works just fine.
