### ISSUE TITLE
global singleton config/resolution?

### ISSUE THREAD

**Issue by jeremy-coleman** [pnpm/pnpm#1683]
i would like to set node to by default check the pnpm global store's most version (without symlinking) In practice, it's doing that anyway.  Basically i don't want any node_modules or package.jsons in my projects. Imo, generating a package.json should be part of the build process - not a requirement of the development process. I think pnpm is likely the best tool for me to set this up, i'm just not sure how. any guidance? 

my initial thoughts on the ideal solution is to integrate a package manager into vscode , or use a self-hosted server that basically acts like a ./vendor.js bundle but instead just point to pnpm://localhost

**Comment by zkochan** [comment]
Sounds like Yarn Plug'n'Play which overrides Node's module resolution algorithm

**Comment by jeremy-coleman** [comment]
great info, thank you. I also had a couple other thoughts , 1) to just use a global like __pnpm.pkgName , as in import 'react' from __pnpm.React , which would also allow for versioning if need be. or 2) just open vscode inside the pnpm store and create a workspace lol

**Comment by zkochan** [comment]
I work on Plug'n'Play support. Closing this in favor of #1628
