### ISSUE TITLE
EEXIST: file already exists

### ISSUE THREAD

**Issue by meesvandongen** [pnpm/pnpm#1685]
### pnpm version:
2.25.6
### Code to reproduce the issue:
pnpm install react-icons-kit
https://gist.github.com/meesvandongen/57cd7f2dcfb3ef87c49c10c7305da9ae

### Expected behavior:
installs correctly
### Actual behavior:
throws error: 

```
EEXIST: file already exists, link 'a:\.pnpm-store\2\registry.npmjs.org\react-icons-kit\1.2.1\node_modules\react-icons-kit\icomoon\pageBreak.js' -> 'a:\Users\M\Documents\projects\test\node_modules\.registry.npmjs.org\react-icons-kit\1.2.1\node_modules\_tmp_720_dd4fe3c80a973e07babf19b0cb9955de\icomoon\pageBreak.js'
```
### Additional information:

 - `node -v` prints: v11.9.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
Reproducible only on Windows. I'll try to fix this.

**Comment by zkochan** [comment]
:ship: 2.25.7

**Comment by HGZwebdesign** [comment]
Hello,
I think I encountered similar problem on Mac`pnpm i check-types-mini` with `pnpm v2.25.7` throws an error:
`EEXIST: file already exists, link '..../.pnpm-store/2/registry.npmjs.org/check-types-mini/5.7.8/node_modules/check-types-mini/CHANGELOG.md' -> '....../<myProject>/node_modules/.registry.npmjs.org/check-types-mini/5.7.8/node_modules/_tmp_6508_c5ca9eec4fb492bde4b2381954df9525/CHANGELOG.md'`

node: v8.10.0
MacOS: 10.14.3

**Comment by wmertens** [comment]
indeed there are 2 changelogs: https://unpkg.com/check-types-mini@5.7.8/

**Comment by zkochan** [comment]
@HGZwebdesign
I did this fix only for Windows. I can make it for Mac as well.

**Comment by wmertens** [comment]
Perhaps the fix should be to first try writing, and if you get EEXIST, stat the destination and see if it has different case, and if it does, overwrite (or not, but I'm thinking `npm` just overwrites)

**Comment by zkochan** [comment]
@wmertens 

>Perhaps the fix should be to first try writing

this is too late as we need to create an index file that will not contain the file duplicates. If the index file will contain files that are not written to the filesystem, then pnpm will always refetch the package from registry, on every installation.

**Comment by zkochan** [comment]
After a bit more investigation I've found out that file systems may be case insensitive on any OS. Also, on Windows, some folders may be case sensitive, others no. So the store may be case sensitive while the project's node_modules  may be case insensitive.

**Comment by zkochan** [comment]
:ship: 3.0.1

**Comment by wmertens** [comment]
That fix looks great, thanks!

> This has a downside though, that the package will always be relinked from the store, as it will miss a file.

Those packages will then stand out and hopefully the authors will fix the case sensitivity.

**Comment by ExE-Boss** [comment]
You could, on Windows 10, enable case sensitivity for the packages which have two files with different case.

## See also:
- https://devblogs.microsoft.com/commandline/improved-per-directory-case-sensitivity-support-in-wsl/

**Comment by wmertens** [comment]
Not possible on Mac tough...

Wout.
