### ISSUE TITLE
Request: Output pnpx messages on stderr

### ISSUE THREAD

**Issue by Conduitry** [pnpm/pnpm#1698]
pnpx currently outputs messages about installing packages, etc. on stdout, which means they'll come through in pipes and redirections, which is typically not what's wanted.

For comparison, npx outputs their corresponding messages on stderr.

**Comment by zkochan** [comment]
As a temporary workaround, you may use `--use-stderr`:

```
pnpm --use-stderr dlx cowsay hi
```
