### ISSUE TITLE
pnpm fails to install some dependencies when run inside docker with userns remapping enabled

### ISSUE THREAD

**Issue by gordz** [pnpm/pnpm#1699]
### Code to reproduce the issue:
On a machine where docker daemon has the '--userns-remap=default' flag set, execute the following 
```
docker run -it node:latest sh
# from inside the newly launched container
npm install -g pnpm
pnpm install jmespath@0.15.0
```

The docker daemon I'm testing against is slight variant of the moby 'docker:18.09.1-dind' image, running inside Kubernetes, where we pass  '--userns-remap=default'  as args to the docker daemon.

### Expected behavior:
The dependency is installed inside the running node:latest container.

### Actual behavior:
```
$pnpm install jmespath@0.15.0
Packages: +1
+
 WARN  Fetching registry.npmjs.org/jmespath/0.15.0 failed!
 ERROR  EINVAL: invalid argument, lchown '/root/.pnpm-store/2/registry.npmjs.org/jmespath/0.15.0/_tmp_35_1a8d9a6bf11d96c5da3cff95936e185e'
Resolving: total 1, reused 0, downloaded 0
Error: EINVAL: invalid argument, lchown '/root/.pnpm-store/2/registry.npmjs.org/jmespath/0.15.0/_tmp_35_1a8d9a6bf11d96c5da3cff95936e185e'
Error: EINVAL: invalid argument, lchown '/root/.pnpm-store/2/registry.npmjs.org/jmespath/0.15.0/_tmp_35_1a8d9a6bf11d96c5da3cff95936e185e'
Error: EINVAL: invalid argument, lchown '/root/.pnpm-store/2/registry.npmjs.org/jmespath/0.15.0/_tmp_35_1a8d9a6bf11d96c5da3cff95936e185e'
Error: EINVAL: invalid argument, lchown '/root/.pnpm-store/2/registry.npmjs.org/jmespath/0.15.0/_tmp_35_1a8d9a6bf11d96c5da3cff95936e185e'
```

Additionally, if I try to pull down the tarball of the failing package (via `npm view jmespath@0.15.0 dist.tarball` then untar it, we also see errors, with tar eventually exiting with the following:

```
tar: package/test/compliance/wildcard.json: Cannot change ownership to uid 1120452788, gid 0: Invalid argument
tar: Exiting with failure status due to previous errors
```

The same package installs without issues via npm install. Wthout looking at code, my hunch is that pnpm is using a similar mechanism as tar to unpack packages, and failing in a similar way when userns remapping is enabled.

I can get the tar command to pass by passing the '--no-same-owner' flag.

### Additional information:

 - `node -v` prints: v11.10.1
 -  Linux (inside kubernetes pod where we are running docker in docker, inside a node:latest container launched from a minor variant of docker 'docker:18.09.1-dind').
```
# uname -a
Linux 5100089aecde 4.19.25-coreos #1 SMP Mon Feb 25 23:59:01 -00 2019 x86_64 GNU/Linux
```

**Comment by zkochan** [comment]
pnpm uses this lib to unpack tarballs https://github.com/zkochan/unpack-stream

It uses tar-fs under the hood.

**Comment by lukescott** [comment]
It looks like `tar-fs` needs to be passed the `chown: false` option:

https://github.com/mafintosh/tar-fs/blob/0f54a78bcc8735c4257177fd004c2f9e55c588bb/index.js#L180

lchown is called here if own or chown is true:

https://github.com/mafintosh/tar-fs/blob/0f54a78bcc8735c4257177fd004c2f9e55c588bb/index.js#L234

The own var set by `opts.chown` and based on the environment. So it looks like that is the option that needs to be set.

Would this mean unpack-stream would need to pass this, or expose it to pnpm?

Looks like npm may already be doing this (issue about changing (`--no-same-owner` to `-o`, the version of npm mentioned uses exec tar):

https://github.com/npm/npm/issues/1128

**Comment by zkochan** [comment]
Is there a way to cover this with tests?

We can make `unpack-stream` pass the option.

Would you like to contribute this?

**Comment by Glinkis** [comment]
I have this same issue when trying to install my dependencies in in my circleci intergration tests.

**Comment by lukescott** [comment]
I haven't had the chance to put together a PR for this yet. But it should, in theory, be as simple as having `unpack-stream` pass `chown: false`. The hard part is producing a test case that reproduces the issue without spinning up a docker container.

I have this on my radar to come back to, but likely won't be able to for at least a few weeks. If anyone wants to take a stab at it in the mean time, feel free.

**Comment by Glinkis** [comment]
This is the only thing preventing us from using pnpm over yarn currently. Unfortunately O don't have the time to fix this myself, but I'm looking forward to migrating once this is done.

**Comment by zkochan** [comment]
@lukescott thanks for providing the solution

**Comment by zkochan** [comment]
:ship: 3.1.0-1
