### ISSUE TITLE
pnpm.js.org/docs should contain information about .npmrc config keys

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1712]

**Comment by zkochan** [comment]
All the configs on [this](https://pnpm.js.org/docs/en/pnpm-install.html) page, for instance, may be specified as flags or configs in `.npmrc`. I don't think a separate page should be created. Maybe it should just be noted somewhere

**Comment by KSXGitHub** [comment]
Not all, few that belong to recursive install don't appear there. It would be convenient to at least create a page for .npmrc and link them to the two commands.

**Comment by zkochan** [comment]
There's a page for [.npmrc](https://pnpm.js.org/en/npmrc) now. The monorepo options are [here](https://pnpm.js.org/en/workspaces#options) though. I would not duplicate them. But adding links is fine.

**Comment by mcmxcdev** [comment]
I think this issue can be closed as https://pnpm.io/npmrc is very detailed and easy to reference.

**Comment by zkochan** [comment]
I actually did move the workspace settings to that page: https://pnpm.io/npmrc#workspace-settings
