### ISSUE TITLE
flatten wrong deps versions

### ISSUE THREAD

**Issue by farfromrefug** [pnpm/pnpm#1713]
I am trying to use ```pnpm``` in [this](https://github.com/farfromrefug/nativescript-carto/tree/master/demo_vue) project folder.

As you can see i use ```shamefully-flatten``` . The reason is that without it i cant get webpack-cli to work.

So first thing first to run the project once you ve run ```pnpm i``` you need to do:
```tns run android --bundle```
This will run webpack but it will fail.
The reason is that in the flatten result we have a mixup of versions beetween ```chalk``` and ```ansi-styles```
It 's seeable within the ```pnpm-lock.yml```. There are 2 versions of chalk: 1.1.3 and 2.4.2
Both require a different version of ansi-styles (2.2.1 for 1.1.3 and 3.2.1 for 2.4.2). But the in the resulted node-modules folders i can see that i end up with chalk 2.4.2 but ansi-styles 2.2.1.

Then chalk wont run because the structure of the ```ansi-styles``` module have changed.

BTW: without the ```shamefully-flatten``` i end up with errors requiring a lot of webpack-cli deps. So i end up having to add them one by one in my package.json. Which makes no sense.

**Comment by zkochan** [comment]
how do I get the tns cli? What package should I Install globally?

the chalk in the root of node_modules is just a symlink to `node_modules/.registry.npmjs.org/chalk/2.4.2/node_modules/chalk`. So it will resolve ansi-styles from `node_modules/.registry.npmjs.org/chalk/2.4.2/node_modules/ansi-styles`, not from `node_modules/ansi-styles`. This is a bit explained in [this article](https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3)

**Comment by farfromrefug** [comment]
@zkochan you need to do ```npm install -g nativescript```.
But honestly would install too much as it is a mobile network env.
I think seeing that we are using ```shamefully-flatten``` you should be able just to run webpack by doing ```./node_modules/.bin/webpack --env.android``` within the ```demo_vue``` folder and see the error.

Thansk for the article will read it. Seems like i understood it right.And ansi-styles is not the right linked one.

**Comment by farfromrefug** [comment]
I ll close this one to cleanup opened issue and seeing it has not had updates for a long time. (from me too as i have not seen the issue recently)

**Comment by yuyez** [comment]
I can reproduce this.

package.json
```
{
  "dependencies": {
    "mocha": "9.2.0",
    "chalk": "1.1.3"
  }
}
```

.npmrc
```
shamefully-hoist=true
```

Then, `node_modules\wrap-ansi\package.json` requires `"chalk": "^4.0.0"`. However, `node_modules\ansi-styles\package.json` has version `2.2.1`.

**Comment by zkochan** [comment]
@yuyez `chalk` is in the dev dependencies of `wrap-ansi`, so it won't be installed by pnpm.

**Comment by yuyez** [comment]
I prepared a simpler repro in #4592 that doesn't involve `chalk`. Thanks for taking a look!
