### ISSUE TITLE
Switch to using `file:` instead of the `link:` protocol for `pnpm` dependencies.

### ISSUE THREAD

**Issue by teehemkay** [pnpm/pnpm#1714]
Installation of `pnpm` when using the `nix` [package manager](https://nixos.org/nix/) fails because of the use of the `link:` protocol for one of the dependency [1] listed in the in `package.json` tarball.

Due to its very nature, Nix has to use a custom installation procedure.

[1 ] `@pnpm/assert-project": "link:../../privatePackages/assert-project" devDependency"`

**Comment by zkochan** [comment]
Could you explain how nix installs pnpm?
Does it download the pnpm package from this repo and run npm inside the `pnpm/packages/pnpm` dir?

Why doesn't download just the pnpm tarball from the npm registry? pnpm is bundled with all its dependencies, so it is enough just to download a single tarball from the registry and unpack it. That's how the [pnpm standalone installer works](https://github.com/pnpm/self-installer)

**Comment by teehemkay** [comment]
[node2nix](https://github.com/svanderburg/node2nix) is the easiest way to install "global" `npm` packages meant to work as command line tools.

Due to the way `Nix` works, the whole process is a little bit involved. The author of the `node2nix` tool wrote [a blog post](https://sandervanderburg.blogspot.com/2017/12/bypassing-npms-content-addressable.html) explaining the process.

`node2nix` does use the pnpm tarball but at some point during the installation, `node2nix` runs [roughly](https://github.com/NixOS/nixpkgs-channels/blob/5d3fd3674a66c5b1ada63e2eace140519849c967/pkgs/development/node-packages/node-env.nix#L394) the command below to ensure that the npm normal installation process is performed.

```sh
npm --nodedir=<some path> --production install
```

This is to ensure, for example, that the `node_modules/.bin` folder of the package is correctly created. If that folder exists, [node2nix] will symlink the _executable_ scripts in that folder to the proper location for them to work with `Nix`. This is the whole point of the installation.

Even thought the pnpm tarball already include all the right bits, they're not in the "standard" location (`node_modules/.bin`) expected by `node2nix`, that why we need to run the `npm install` below. We could of course special-case the installation of `pnpm` but I'd rather not, if at all possible. 

Now, even though the `npm` [documentation](https://docs.npmjs.com/cli/install.html) claims that 
   > With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies

`npm` still errors out complaining about the use of `link:` in the `@pnpm/assert-project` devDependency.

That may very well be a bug in `npm`.
But, since `link:` is not really "standard", I thought that maybe it would be easier to just use the standard `file:` protocol for `pnpm` devDependencies.

I hope this answers your question.

**Comment by zkochan** [comment]
ok,  I suggest an alternative solution. We'll remove the whole "devDependencies" field from pnpm, before publishing it to the registry.

**Comment by teehemkay** [comment]
Thanks, I think that should do the trick.
I’ll test this solution later today and let you know.

**Comment by zkochan** [comment]
try 3.0.1

**Comment by teehemkay** [comment]
I tested 3.0.1 and the Nix install now works perfectly!.

Thank you so much @zkochan !

**Comment by zkochan** [comment]
cool, I did it manually though, before publishing, so I'll have to automate it.

**Comment by teehemkay** [comment]
Ah ah, I was looking through the latest commit and couldn't find the change...

**Comment by teehemkay** [comment]
I'll create a PR on nixos/nixpkgs to upgrade pnpm to v3.0.1.

**Comment by zkochan** [comment]
This will be a change in https://github.com/zkochan/publish-packed
which is used to publish pnpm
