### ISSUE TITLE
Some dependencies in .registry.npmjs.org can't be found

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [pnpm/pnpm#1715]
### Code to reproduce the issue:

https://github.com/s-h-a-d-o-w/pnpm_hiccup

### Expected behavior:

(Works with yarn)
```bash
node .
🚀  Server ready.
```

### Actual behavior:

```bash
node .
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'apollo-server-env'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
```

### Additional information:

 - `node -v` prints: v10.9.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
This is a bug in one of apollo's packages: https://github.com/apollographql/apollo-server/issues/2151

As a workaround, you may set `shamefully-flatten=true` in `.npmrc`.

**Comment by s-h-a-d-o-w** [comment]
Thank you very much for the quick response, good to know!
