### ISSUE TITLE
Document what pnpmfile does

### ISSUE THREAD

**Issue by dandv** [pnpm/pnpm#1726]
I was putting myself in the shoes of a new pnpm user. Started with pnpm.js.org, went to https://pnpm.js.org/docs/en/pnpm-install.html. [There](https://pnpm.js.org/docs/en/pnpm-install.html#ignore-pnpmfile), I saw three options dealing with a "pnpmfile". What is that? There should be a link to more information about `pnpmfile.js`.

**Comment by keerthivasan-r** [comment]
Exactly, i am a new user. I just got stumbling at the same place

**Comment by zkochan** [comment]
Here are the sources of the site https://github.com/pnpm/pnpm.github.io

I don't have objections. Maybe I'll do it this weekend

**Comment by zkochan** [comment]
Done: https://pnpm.js.org/en/pnpmfile?0
