### ISSUE TITLE
Installing @types packages is not working properly

### ISSUE THREAD

**Issue by mdebeus** [pnpm/pnpm#1727]
### pnpm version:
3.0.1
### Code to reproduce the issue:
I don't have code to reproduce this issue, but...
1. I have installed and then built using both npm and yarn - each were successful
2. After installing with pnpm, my build does not work, so I removed node_modules and any lock files and ran pnpm install --shamelessly-flatten. It still did not work.
3. I am building a Typescript library that uses an 'ejected' CRA project/webpack configuration.

I am getting the following errors (these are just a few):

TS2742: The inferred type of 'XXX' cannot be named without a reference to '.registry.npmjs.org/@types/react-redux/6.0.13/node_modules/@types/react-redux'. This is likely not portable. A type annotation is necessary.
 TS2742: The inferred type of 'XXX' cannot be named without a reference to '.registry.npmjs.org/@types/react-router/4.4.5/node_modules/@types/react-router'. This is likely not portable. A type annotation is necessary

I do see that my store has a reference to these:
C:\Users\XXX(me)\.pnpm-store\2\registry.npmjs.org\@types\react-redux\6.0.13\node_modules\@types\react-redux
C:\Users\XXX(me)\.pnpm-store\2\registry.npmjs.org\@types\react-router\4.4.5\node_modules\@types\react-router

My library project node_modules directory is pointing to the leaf directory.

### Expected behavior:
My project builds successfully

### Actual behavior:
By project does not build because of the errors listed above

### Additional information:
node -v: v10.11.0
OS: Windows 10
store: C:\Users\Michelle\.pnpm-store\2

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
So you use the `independent-leaves=true` config? Have you tried w/o it?

Also, you can try to set the `resolution-strategy=fewer-dependencies` config from pnpm v3.1.0. It was added for better `@types` support

**Comment by eexe1** [comment]
I also had this issue. I solved it by using `shamefully-hoist=true`

**Comment by Marvin-Brouwer** [comment]
I am running into a similar issue and none of the above suggestions work.
I am on a Windows 10 machine using the integrated linux bash terminal.
It appears that's where the issue is.
If I run the command on the windows CLI it does  add the expected folders.
The node version doesn't seem to matter.

I hope this helps

**Comment by FDiskas** [comment]
@Marvin-Brouwer you should create `.npmrc` with `shamefully-hoist=true` in it and then `pnpm install`
it should work.

**Comment by Marvin-Brouwer** [comment]
Hi @FDiskas that is more of a patch than a solution though.
I'm not a fan of having to add a step to my readme for anyone who happens to use my library.
For now I can do the Dev by installing via the windows terminal and I'm debugging in both integrated Linux and windows CMD so it's fine for now.

I just figured I'd give some more details as to when it's happening for me

**Comment by aminya** [comment]
Using pnpm without `shamefully-hoist=true` creates a lot of problems. I think it should become the default behavior.

**Comment by zkochan** [comment]
If there's no other way to fix it, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)

**Comment by talik077** [comment]
For those facing the same issue, I found a solution by setting `shamefully-hoist=true`. 
However, a better option is to use `public-hoist-pattern[]=*types*` in the .npmrc file.
According to the [documentation](https://pnpm.io/npmrc#public-hoist-pattern), setting `shamefully-hoist` to "true" is equivalent to `public-hoist-pattern` to "*". So, it's better to use a more specific configuration instead of a general one.
