### ISSUE TITLE
pnpm store add does not respect .npmrc

### ISSUE THREAD

**Issue by dkebler** [pnpm/pnpm#1737]
Here are applicable lines my `.npmrc`

```
@uci-utils:registry=https://npm.xxxxx.net
registry=https://registry.npmjs.org/
use-store-server=true
```
### pnpm version: 3+

```
pnpm store add @scope/package
A store server is running. All store manipulations are delegated to it.
 ERROR  404 Not Found: @uci-utils/byte (via https://registry.npmjs.org/@uci-utils%2Fbyte)
 ERROR  Some packages have not been added correctly
```
where @scope is on private registry

### Expected behavior:

should add package

### Actual behavior:

Looks for package at registry.npmjs.org instead of at my private registry per .npmrc and when it doesn't find it fails

**NOTE:**   `pnpm install` does respect `.npmrc` and does find my private repo packages including the one above.  It is only the direct `pnpm store` command that has this issue

### Additional information:

node 11+  using pnpm server

**Comment by zkochan** [comment]
PR #1741

**Comment by zkochan** [comment]
:ship: 3.1.0-0
