### ISSUE TITLE
Binstubs should not try to execute every binary with Node

### ISSUE THREAD

**Issue by 5310** [pnpm/pnpm#1743]
Binstubs generated by PNPM execute every package.json defined binary with Node, which fails to run anything that isn't JavaScript.

```bash
NODE_PATH="..." "$basedir/node"  "$basedir/../..." "$@"
                 ^^^^^^^^^^^^^
```

This issue arises because the binaries defined under package.json can be anything, not just JavaScript to be executed under Node. This is why they're [required to include a shebang](https://docs.npmjs.com/files/package.json#bin) even if they are JavaScript files. 

There are many packages on NPM, including some popular CLI tools like [Now.sh](https://www.npmjs.com/package/now), that make use of this feature and supply non-Js binaries.

### Code to reproduce the issue:

```bash
$ pnpm i now
$ pnpx now -h # or: ./node_modules/.bin/now -h
```

Same goes if globally installed.

### Expected behavior:

Now.sh prints its help reference.

### Actual behavior:

Instead, Node fails to execute Now's already [Pkg](https://www.npmjs.com/package/pkg)-built binary:
```
/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/now:1
(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

### Additional information:

 - `node -v` prints: v10.15.3
 - Windows, OS X, or Linux?: Linux, Xubuntu 18.04 LTS

### Proposed solution:

Binstubs generated by PNPM should just not execute every binary with Node.

The `NODE_PATH` must stay for those packages that do need to run via Node, but they will continue to do so without being explicitly invoked with Node in the binstubs because they have their own shebangs by default.

The resulting binstub for Now.sh looks like this post edit, with the superfluous `"$basedir/node" ` and `node` invocations removed:

```bash#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  NODE_PATH="/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules:/mnt/Active/Projects/Personal/scratchpad/node_modules:/mnt/Active/Projects/Personal/node_modules:/mnt/Active/Projects/node_modules:/mnt/Active/node_modules:/mnt/node_modules:/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/dist/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/dist/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/node_modules" "$basedir/../now/download/dist/now" "$@"
  ret=$?
else 
  NODE_PATH="/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules:/mnt/Active/Projects/Personal/scratchpad/node_modules:/mnt/Active/Projects/Personal/node_modules:/mnt/Active/Projects/node_modules:/mnt/Active/node_modules:/mnt/node_modules:/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/dist/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/dist/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/node_modules" "$basedir/../now/download/dist/now" "$@"
  ret=$?
fi
exit $ret
```

ESLint, Babel, etc popularly used CLI tools are all JavaScript binaries, and continue to run just fine when the Node invocations are manually removed from their binstubs—as long as the `NODE_PATH` variable is still set when running their binaries.

And everything that doesn't have a Js binary, such as Now.sh, now runs as expected.

**Comment by zkochan** [comment]
cc @ExE-Boss

**Comment by ExE-Boss** [comment]
That’s odd, because I’m getting the exact opposite behaviour with [`dtslint`](https://github.com/Microsoft/dtslint) [<img alt="(on&nbsp;npm)" align="top" src="https://img.shields.io/npm/v/dtslint.svg"/>](https://www.npmjs.com/package/dtslint):
```pwsh
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$env_node_path=$env:NODE_PATH
$env:NODE_PATH="C:\NodeJS\pnpm-global\2\node_modules\.registry.npmjs.org\dtslint\0.5.6\node_modules\dtslint\bin\index.js\node_modules;C:\NodeJS\pnpm-global\2\node_modules\.registry.npmjs.org\dtslint\0.5.6\node_modules\dtslint\bin\node_modules;C:\NodeJS\pnpm-global\2\node_modules\.registry.npmjs.org\dtslint\0.5.6\node_modules\dtslint\node_modules;C:\NodeJS\pnpm-global\2\node_modules\.registry.npmjs.org\dtslint\0.5.6\node_modules;C:\NodeJS\pnpm-global\2\node_modules\.registry.npmjs.org\dtslint\node_modules;C:\NodeJS\pnpm-global\2\node_modules\.registry.npmjs.org\node_modules;C:\NodeJS\pnpm-global\2\node_modules;C:\NodeJS\pnpm-global\node_modules;C:\NodeJS\node_modules;C:\node_modules;C:\NodeJS\pnpm-global\2\node_modules\dtslint\bin\index.js\node_modules;C:\NodeJS\pnpm-global\2\node_modules\dtslint\bin\node_modules;C:\NodeJS\pnpm-global\2\node_modules\dtslint\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
} else {
  $env:NODE_PATH="/mnt/c/NodeJS/pnpm-global/2/node_modules/.registry.npmjs.org/dtslint/0.5.6/node_modules/dtslint/bin/index.js/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/.registry.npmjs.org/dtslint/0.5.6/node_modules/dtslint/bin/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/.registry.npmjs.org/dtslint/0.5.6/node_modules/dtslint/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/.registry.npmjs.org/dtslint/0.5.6/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/.registry.npmjs.org/dtslint/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/.registry.npmjs.org/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules:/mnt/c/NodeJS/pnpm-global/node_modules:/mnt/c/NodeJS/node_modules:/mnt/c/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/dtslint/bin/index.js/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/dtslint/bin/node_modules:/mnt/c/NodeJS/pnpm-global/2/node_modules/dtslint/node_modules"
}
& "$basedir/pnpm-global/2/node_modules/dtslint/bin/index.js"   $args
$env:NODE_PATH=$env_node_path
exit $LASTEXITCODE
```

**Comment by 5310** [comment]
I'm confounded. After I installed `dtslint` PNPM updated Now.sh's binstub entirely. I had it open in the editor, and only noticed it because the editor notified me of the update file. The new binstub not only doesn't have the Node invocation, it also doesn't have the conditional `NODE_PATH` branches!

This is what the Now.sh binstub now looks like:

```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

NODE_PATH="/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/dist/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/download/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/14.2.3/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.registry.npmjs.org/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules:/mnt/Active/Projects/Personal/scratchpad/node_modules:/mnt/Active/Projects/Personal/node_modules:/mnt/Active/Projects/node_modules:/mnt/Active/node_modules:/mnt/node_modules:/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/dist/now/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/dist/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/download/node_modules:/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/now/node_modules" "$basedir/../now/download/dist/now"   "$@"
exit $?
```

The mystery of the opposite behavior is easily solved though. DTSLint CLI does not work with PNPM because, for some reason, PNPM pulls [v0.5.7](https://unpkg.com/dtslint@0.5.7/bin/index.js) (on my machine, and I assume yours) which doesn't have the necessary shebang that the current version [v0.5.8](https://unpkg.com/dtslint@0.5.7/bin/index.js) which fixes this. 

```bash
$ pnpm i dtslint
$ pnpx dtslint
/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.bin/../dtslint/bin/index.js: 1: /mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.bin/../dtslint/bin/index.js: use strict: not found
/mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.bin/../dtslint/bin/index.js: 2: /mnt/Active/Projects/Personal/scratchpad/pnptest/node_modules/.bin/../dtslint/bin/index.js: Syntax error: "(" unexpected
```

0.5.8 works just fine with these newly update binstubs that no longer hardcode Node for every binary invocation.

Going back to the topic of mysteriously updating binstubs. I still have the globally installed packages on my system which haven't been touched and these too have hardcoded Node invocations and conditional `NODE_PATH`s. This test repo I made to report this bug is the only Node project on my drive that has had its binstubs changed by PNPM when I installed another package. And it apaprently fixes the issue.

Now.sh now works just fine with them too! But I don't understand what changed. I didn't even update PNPM or any anything else on my system, whether PM managed or PNPM managed!

**Comment by 5310** [comment]
DTSLint 0.5.8 was published 28 minutes ago! :smiley:

**Comment by 5310** [comment]
I just updated (nothing was available) and then uninstalled and reinstalled Now.sh from my global install. Nothing changed. The global binstub still has the branching `NODE_PATH` and Node invocation, and as such, can't run anything that isn't JavaScript.

**Comment by zkochan** [comment]
This might've been fixed in cmd-shim by [this PR](https://github.com/pnpm/cmd-shim/pull/12). We'll have to write a test for this case and see if it works with the latest cmd-shim (I did not publish it yet)

**Comment by 5310** [comment]
Is cmd-shim used on Linux at all?

**Comment by ExE-Boss** [comment]
> Is&nbsp;cmd-shim used on&nbsp;Linux at&nbsp;all?

It&nbsp;is&nbsp;with pnpm because it&nbsp;needs to&nbsp;set&nbsp;`NODE_PATH`.

**Comment by 5310** [comment]
A small update: Today I updated my system packages (and also P/NPM packages) and noticed Now.sh got updated too. Now the global install of Now.sh also has a new binstub with non-branching `NODE_PATH` or without hardcoded Node, and works fine.

Also noticed that all binstubs that run JavaScript files still retain their branching `NODE_PATH` and hardcoded Node invocation. I assume this is the expected behavior. They work fine too. (Although I still think only the `NODE_PATH` should be necessary and thereby cleaner, but I fully admit to have no idea of the associated complexities :)

Still not sure why installing `dts@0.5.7` (then latest, and without a Node shebang, which caused `cmd-shim` to generate that non-Node binstub, but since fixed in v0.5.8) update my Now.sh binstub on that same local repository (thereby fixing it), but that's a separate concern.

**Comment by zkochan** [comment]
The reason for this issue is the same as in #1608.

The bin file that is packed with now is a js file:

```js
#!/usr/bin/env node

// This file should get overwritten if now installs correctly.
// It only exists to tell users that something went wrong
// and how they might fix it.

console.log('> Error!', 'Now CLI failed to install correctly.');
console.log('> Error!', 'Make sure to set `ignore-scripts` to `false` in your npm config before installing Now CLI.');

process.exit(1);
```

A postinstall script of now overrides this file with an non-js executable. However, pnpm links the bin files before running postinstall scripts. So the fix is to link bins after running lifecycle hooks

**Comment by 5310** [comment]
I see, and on any subsequent change to the package roster PNPM relinks the now postinstall generated bin file, which is why it works again.

**Comment by zkochan** [comment]
ok

**Comment by zkochan** [comment]
PR is in progress #1764

**Comment by zkochan** [comment]
:ship: 3.1.1-0
