### ISSUE TITLE
pnpm install does not respect .gitmodules

### ISSUE THREAD

**Issue by aleclarson** [pnpm/pnpm#1744]
### pnpm version:
3.0.1

### Code to reproduce the issue:

```sh
pnpm i alloc/react-native-svgkit#0.1.0

ls node_modules/@alloc/react-native-svgkit/SVGKit
```

### Expected behavior:
Automatic `git submodule update --init` when a package with `.gitmodules` is installed.

### Actual behavior:
The `.gitmodules` file is ignored.

Both yarn and npm support `.gitmodules`.

### Additional information:

 - node v11.7.0
 - macOS v10.13.6

**Comment by likern** [comment]
@aleclarson I don't think pnpm or other package manager should somehow (or do right now) interact with repository.
But `git-subtree` should work for your use case I think - it directly contains sources for packages.
All dependencies could be installed just as normal `pnpm install -r`.

**Comment by brillout** [comment]
We can now use `pnpm:devPreinstall`, see https://github.com/pnpm/pnpm/issues/3836.

@aleclarson I'd say we can close this.
