### ISSUE TITLE
pnpm packages must be done as root

### ISSUE THREAD

**Issue by MichaelOdumosu57** [pnpm/pnpm#1752]
### pnpm version:
v3.0.1
### Code to reproduce the issue:
pnpm install -g @angular/cli

### Expected behavior:
install
### Actual behavior:
needs  me to be root
### Additional information:
angular is not run with root its run from the executing user how do I configure so I can install and run packages made from pnpm with the executing user
 - `node -v` prints:10.15.3
 - Windows, OS X, or Linux?:Linux

**Comment by zkochan** [comment]
This is not an issue with pnpm v7.
