### ISSUE TITLE
[suggestion] a local .pnpmrc file for localized config

### ISSUE THREAD

**Issue by huochunpeng** [pnpm/pnpm#1754]
I like pnpm's strictness, but I still have some projects need shamefully-flatten.

I don't want to turn on shamefully-flatten on global .npmrc because that forces the unideal option everywhere.

Suggest pnpm to support local .pnpmrc file which I can just turn on shamefully-flatten within one project. The localized .pnpmrc also helps to normalize my shell scripts, so I can just use `pnpm install` in shell script regardless what project it is running against.

**Comment by zkochan** [comment]
pnpm reads the local `.npmrc` file as well. Not only the global one. So you can put `shamfully-flatten` to the local `.npmrc`.

**Comment by huochunpeng** [comment]
Thx!
