### ISSUE TITLE
vuepress install fails

### ISSUE THREAD

**Issue by aparajita** [pnpm/pnpm#1755]
### pnpm version:

3.1.0

### Code to reproduce the issue:

Create `pnpm-workspace.yaml` as documented [here](https://pnpm.js.org/docs/en/pnpm-recursive.html#usage)

```sh
pnpm install -r vuepress@next
pnpx vuepress dev
```

### Expected behavior:

`vuepress dev` runs successfully.

### Actual behavior:

```
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module '@vuepress/shared-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/aparajita/Developer/projects/clients/willsub/apps/subs-help/node_modules/.registry.npmjs.org/vuepress/1.0.0-alpha.46/node_modules/vuepress/lib/checkEnv.js:7:27)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
```

### Additional information:

 - `node -v` prints: v11.13.0
 - Windows, OS X, or Linux?: macOS

Normal install works with both npm and yarn.

**Comment by zkochan** [comment]
I've found a lot of issues in vuepress. These 3 packages are requiring modules that are not declared in their package.json: `@vuepress/core`, `@vuepress/shared-utils`, `vuepress`.

pnpm creates a [strict node_modules](https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308) so packages have only access to those packages that are actual direct dependencies of every package.

Anyway, there are two workarounds. Either use the [shamefully-flatten](https://pnpm.js.org/docs/en/pnpm-install.html#shamefully-flatten) config or put this `pnpmfile.js` in the root of your project (and then remove node_modules, pnpm-lock.yaml and run installation again):

pnpmfile.js:
```js
module.exports = {
    hooks: {
        readPackage (pkg) {
            switch (pkg.name) {
                case '@vuepress/core': {
                    pkg.dependencies = pkg.dependencies || {}
                    pkg.dependencies['escape-html'] = '^1.0.3'
                    break
                }
                case '@vuepress/shared-utils': {
                    pkg.dependencies = pkg.dependencies || {}
                    pkg.dependencies['@vue/component-compiler-utils'] = '^2.5.1'
                    pkg.dependencies['lru-cache'] = '^5.1.1'
                    pkg.dependencies['markdown-it-emoji'] = '^1.4.0'
                    pkg.dependencies['toml'] = '^2.3.3'
                    break
                }
                case 'vuepress': {
                    pkg.dependencies = pkg.dependencies || {}
                    pkg.dependencies['@vuepress/shared-utils'] = '1.0.0-alpha.46'
                    break
                }
            }
            return pkg
        }
    }
}
```

but the packages in vuepress should be fixed. This is only a hack

**Comment by aparajita** [comment]
Thanks for the tips. Is pnpmfile.js documented somewhere? I couldn't find it.

It isn't just vuepress, I had similar problems with Nuxt. See the discussion I started [here](https://github.com/nuxt/nuxt.js/pull/4875).

When the other package managers stop using flattened node_modules (which will probably be this year), a **lot** of packages are going to break because they're unknowingly missing dependency declarations and getting away with it.

**Comment by aparajita** [comment]
Btw there's way more missing dependencies than what you listed above. I'll have to submit an issue with them.

**Comment by zkochan** [comment]
The `pnpmfile.js` currently is only for hooks. The hooks are documented [here](https://pnpm.js.org/docs/en/hooks.html).

**Comment by aparajita** [comment]
Ah, thanks. Unfortunately I had to give up on making it work with pnpm, it was like going down the rabbit hole.

**Comment by bd82** [comment]
I've recently needed to make pnpm (7.x) work with vuepress-next (2.x).
I wanted to **avoid** silencing the peerDepdencies warnings globally for **all** packages
And also wanted to avoid `shamefully-hoist` for **everything**.

What worked for me was:

1. Silence only the specific peerDeps related to vuepress warning via .pnpmfile.cjs
   ```javascript
        module.exports = {
        hooks: {
          readPackage (pkg) {
            // this way we do not need to globally disable the peerDeps error in pnpm.
            // and only for vuepress related deps
            if (/vuepress|sass-loader|@docsearch\/react|@algolia\/autocomplete-preset-algolia/.test(pkg.name)) {
              console.warn(`fixing missing peerDeps for vuepress dep: ${pkg.name}`)
              delete pkg.peerDependencies
            }
            return pkg
          }
        }
      }
   ```
2. Only `shamefully-hoist` `vue` dependency of generated vuepress site via `public-hoist-pattern` in `.npmrc`
```
  public-hoist-pattern[]=vue
```

I assume that with different sets of vuepress plugins this configuration may need to be adjusted.
However it seems simpler than the one above.
