### ISSUE TITLE
Feature request: add ability to let `pnpm recursive run` succeed even when no scripts match

### ISSUE THREAD

**Issue by bdchauvette** [pnpm/pnpm#1763]
Thanks for such a great project!

This issue is just a feature request. If you think it's worth implementing, I'd be happy to take a stab at implementing it.

# Feature

Add the ability to let `pnpm recursive run foo` succeed when no packages contain a script

# Use Case

I'm using PNPM in a monorepo, and I'm using a custom script based on `git diff` that creates filters for PNPM based on packages that have changed. Basically a homegrown version of [Lerna's `--since` flag](https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref). It looks something like:

```sh
pnpm m run build $(since master)

# expands to e.g.
pnpm m run build --filter foo --filter bar
```

With pnpm's current behavior, if none of the packages that have changed include a build script, the command will fail.

In daily use, it's not a big deal, but in CI, it causes the build to fail (somewhat) unexpectedly if not all packages contain a certain CI script. In my case, the build often fails because there's a mix of browser packages, node packages, and TS packages, and only some of them contain a `build` script.

It's currently possible to work around this using `pnpm m exec`, but it's not super pretty:

```sh
pnpm m exec \
  --filter pkgs-that-might-have-script \
  -- bash -c 'if pnpm run | grep "^  build"; then pnpm run build; else true; fi'
```

Ideally, I'd like to be able to do something like:

```sh
pnpm m run build \
  --filter pkgs-that-might-have-script \
  --no-fail-on-missing-script
```

**Comment by zkochan** [comment]
Probably we need to update the [--no-bail](https://pnpm.js.org/docs/en/pnpm-recursive.html#bail) flag to do this.

**Comment by zkochan** [comment]
@bdchauvette have you checked how it works?

Seems like it already works the way you need it.
If a package does not have the `build` script, it is skipped: https://github.com/pnpm/pnpm/blob/master/packages/pnpm/src/cmd/recursive/run.ts#L40

The command only fails if none of the packages had a `build` script: https://github.com/pnpm/pnpm/blob/cc8f95f858327b1f3f3994c1dd164e7c21ababd9/packages/pnpm/src/cmd/recursive/run.ts#L84-L88

**Comment by bdchauvette** [comment]
@zkochan Sorry for the delay in getting back to you on this :cold_sweat: 

> The command only fails if none of the packages had a build script: 

This is the behavior we're trying to avoid.

In our monorepo, enough of our packages have `build` scripts that it takes a while to run if we build everything all the time (i.e. `pnpm m run build`).

We have a script that generates filter flags for changed packages, so we can do something like `pnpm m run $(changed-packages) build`, but because some of our packages _don't_ have build scripts, it fails if we only pushed changes to packages without build scripts.

We could just use dummy scripts (`"build": "echo 'no build script'"`) for the packages that don't have actual build scripts, but it would be nice to avoid having to do that.

**Comment by zkochan** [comment]
This is an interesting use case. Maybe it would make sense to change the behavior of `pnpm run` a bit.

If it only runs on a subset of workspace packages, don't fail if none of the packages has the script.

> We have a script that generates filter flags for changed packages, so we can do something like pnpm m run $(changed-packages) build

Actually, we want a feature like that integrated into pnpm. See #2046

**Comment by bdchauvette** [comment]
> If it only runs on a subset of workspace packages, don't fail if none of the packages has the script.

That would be perfect. If that seems like the right approach, I can take a stab at implementing it.

I think it would require checking against `opts.filter` or `opts.packageSelectors` in the final conditional in `recursive/run.ts`?

https://github.com/pnpm/pnpm/blob/3d8a82c12d4ce4ebf48380983dee3b727ce6449d/packages/pnpm/src/cmd/recursive/run.ts#L87-L89

> Actually, we want a feature like that integrated into pnpm. See #2046

Nice! I'll take a look over there and see if there's any way I can help out. I love the `--since` flag in `lerna`, so having similar functionality baked into `pnpm` would be great :smiley:

**Comment by zkochan** [comment]
This code prints how many workspaces are selected. You can use it for reference

https://github.com/pnpm/pnpm/blob/3d8a82c12d4ce4ebf48380983dee3b727ce6449d/packages/pnpm/src/cmd/recursive/index.ts#L134-L138
