### ISSUE TITLE
pnpm emits 404 on workspace package

### ISSUE THREAD

**Issue by lukescott** [pnpm/pnpm#1769]
### pnpm version:

3.1.0

### Code to reproduce the issue:

I have 2 private dependencies: `@webconnex/director` and `@webconnex/redux-then`. The first is in the npm registry as version `1.0.1`. The second is not in the registry at all.

We started a new project where `@webconnex/director` is version `2.0.0`. Another local package (the app) lists this as a dependency as the same version. I have tried `"@webconnex/director": "^2.0.0"` and `"@webconnex/director": "2.0.0"`. Regardless, I get the following when I do a fresh install:

```
Scope: all 4 workspace packages
Using hooks from: /Users/lukescott/Documents/Go/src/bitbucket.org/webconnex/platform/pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
bacon                                    |  WARN  deprecated @types/aws-sdk@2.7.0
bacon                                    |  WARN  deprecated @types/axios@0.14.0
.                                        | readPackage: sass-loader: fix node-sass dependency
 ERROR  404 Not Found: @webconnex/director (via https://registry.npmjs.org/@webconnex%2Fdirector)
.                                        | readPackage: jest-config: replace babel-core ^6.0.0 with 7.0.0-bridge.0
.                                        | readPackage: jest-runtime: replace babel-core ^6.0.0 with 7.0.0-bridge.0
.                                        | readPackage: jest-runner: add jest-environment-jsdom as a peer dependency
 ERROR  404 Not Found: @webconnex/director (via https://registry.npmjs.org/@webconnex%2Fdirector)
director                                 |  WARN  reflux@0.3.1 requires a peer of react@>=0.12.2 <0.15.0 but version 16.8.6 was installed.
.                                        |    +1432 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 1432, reused 1432, downloaded 0, done
node_modules/.registry.npmjs.org/fsevents/1.2.7/node_modules/fsevents: Running install script, done in 664ms
node_modules/.registry.npmjs.org/date-fns/2.0.0-alpha.27/node_modules/date-fns: Running postinstall script, done in 109ms
node_modules/.registry.npmjs.org/node-sass/4.11.0/node_modules/node-sass: Running install script, done in 6s
node_modules/.registry.npmjs.org/node-sass/4.11.0/node_modules/node-sass: Running postinstall script, done in 143ms
node_modules/.registry.npmjs.org/nodemon/1.18.11/node_modules/nodemon: Running postinstall script, done in 83ms
```

### Expected behavior:

I should not get a 404. The 404 occurs because node isn't setup locally to read the private packages. But pnpm should be resolving the package locally first before reaching out to the npm registry. It seems to try the registry first.

pnpm v2 did not exhibit this behavior.

### Actual behavior:

pnpm v3 seems to reach out to the registry, even though a local version with a matching version is present.

### Additional information:

Oddly enough `@webconnex/redux-then` does not present a 404. It is a dependency of `@webconnex/director`.

 - `node -v` prints: `v10.8.0`
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
Use the workspace protocol

or set [prefer-workspace-packages=true](https://pnpm.io/workspaces#prefer-workspace-packages)
