### ISSUE TITLE
Config option to specify npm location for `pnpm run`

### ISSUE THREAD

**Issue by illarionvk** [pnpm/pnpm#1790]
Pnpm invokes npm for commands like `pnpm run` and silently fails if npm is not in $PATH:

https://github.com/pnpm/pnpm/blob/8132523244fbc1765d13fed7a56959616c974458/packages/pnpm/src/cmd/runNpm.ts#L4

I remove npm from $PATH in my development containers to avoid calling `npm install` accidentally.

Would it be possible to add a configuration option to specify npm location, e.g., `/opt/npm/bin/npm`?

P.S. I have switched to pnpm after suffering through numerous cache issues with yarn. Thanks for a great package manager!

**Comment by zkochan** [comment]
This should be done for other commands. `pnpm run` from `v3.3` does not run npm for `pnpm run`.

**Comment by zkochan** [comment]
:ship: 4.8.0-0
config setting name: npm-path
