### ISSUE TITLE
Optional dependency cannot be loaded (pino/pino-pretty)

### ISSUE THREAD

**Issue by hgossler** [pnpm/pnpm#1791]
### pnpm version:

`v3.0.0`

### Code to reproduce the issue:

See `git@github.com:hgossler/pnpm-issue.git` and follow the steps in the readme. This fails because the `pino-pretty` module cannot be found.

### Expected behavior:

The code in the example should run without errors, i.e. the `pino` package should be able to find the `pino-pretty` package. I am not sure if this is a problem of the `pino` package not listing `pino-pretty` as one of its `optionalDependencies`. However, according to [option 1](https://pnpm.js.org/docs/en/faq.html#solution-1) in the FAQ I would expect this to work.

### Actual behavior:

An error occurs because `pino` cannot find `pino-pretty`:

```
Error: Missing `pino-pretty` module: `pino-pretty` must be installed separately
```

### Additional information:

 - `node -v` prints: `v11.10.1`
 - Windows, OS X, or Linux?: `macOS`

**Comment by zkochan** [comment]
This is an interesting case.

This fails because the real location of pino is in `pnpm-issue/node_modules/.registry.npmjs.org/pino/5.12.3/node_modules/pino`. So pino won't look for `pretty-pino` in `packages/sub-package/node_modules`.

There are two workarounds for this at the moment:

* install `pino-pretty` in the root of the repo
* create this pnpmfile.js in the root of the repo: 
```js
module.exports = {
    hooks: {
        readPackage (pkg) {
            if (pkg.name === 'pino') {
                pkg.peerDependencies = pkg.peerDependencies || {}
                pkg.peerDependencies['pino-pretty'] = '*'
            }
            return pkg
        }
    }
}
```

**Comment by hgossler** [comment]
Thanks for the suggestion.

I suppose there is nothing pnpm can do about this if `pino` doesn't list `pino-pretty` as a `peerDependency`, right?

**Comment by zkochan** [comment]
For now, we can do nothing about it. There should be some way for us to know that pino wants pino-pretty.

Maybe we could support some new field type, like `peerOf`, so that pino-pretty could declare that it is a plugin of pino.

**Comment by wmertens** [comment]
Ok - so I think what's happening with the workspaces modules layout is that it's more strict than the regular layout.

On a regular project, the directly-installed modules can "see" each other, but on a workspace project, they can only "see" their dependencies.

I would argue that the regular behavior is the desired one.

**Comment by zkochan** [comment]
I am not sure. These issues are very easy to fix in userland. They just need to resolve plugins like this:

```js
var prettyFactory = require(
  require.resolve('pino-pretty', { paths: [require.main.filename] })
)
```

**Comment by zkochan** [comment]
Also, these issues are mainly happening with dev dependencies and I recommend installing dev dependencies in the root `package.json` (in which case, they have access to direct deps). All the bin files from the root node_modules/.bin are accessible in all the workspace packages.

**Comment by wmertens** [comment]
Oh wow, that paths option is new to me. Ok, that changes things. I'll fix nps-utils.

Although, putting the dev dependencies in root makes sense for some things like jest, but not really for specific dev deps that are only used by one specific package.

**Comment by zkochan** [comment]
This will be fixed by #1997

**Comment by zkochan** [comment]
:ship: 4.0.0-0

**Comment by zkochan** [comment]
By default, v4 hoists everything. But you can hoist a subset of deps if you want. For instance, in this case, you can set `hoist-pattern=pino-*` in an `.npmrc` in the root of the workspace

**Comment by thunderball1** [comment]
@zkochan could you elaborate?

**Comment by sastan** [comment]
Alternatively you can use the `prettifier` option of pino:

```js
pino({
  prettifier: usePretty && require('pino-pretty'),
  ...options,
})
```

**Comment by TkaczykAdam** [comment]
In my case, this error occurs after migration from Yarn 1 to Yarn 2. This helps in `.yarnrc.yml`

```yml
packageExtensions:
  "pino@*":
    dependencies:
      "pino-pretty": '*'
```
