### ISSUE TITLE
Can't unistall global package, ENOENT: no such file or directory, open '/usr/pnpm-global/2/package.json'

### ISSUE THREAD

**Issue by David-Else** [pnpm/pnpm#1800]
### Code to reproduce the issue:
`pnpm ls -g`

### Expected behavior:
show globally installed typescript

### Actual behavior:
`ENOENT: no such file or directory, open '/usr/pnpm-global/2/package.json'`

### Additional information:

 - `node -v` prints: v12.0.0 (but same problem on earlier versions)
 - Windows, OS X, or Linux?: Linux

In `/usr/pnpm-global` I have a directory called `1`, there is no `2`! Inside `1` is TypeScript, the 

It has a shrinkwrap.yaml file, so is obviously a left over from pnmp < v3, so maybe something went wrong in the update? How do I delete this and fix the problem in a clean way?
```
dependencies:
  typescript: 3.3.3333
packages:
  /typescript/3.3.3333:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-JjSKsAfuHBE/fB2oZ8NxtRTk5iGcg6hkYXMnZ3Wc+b2RSqejEqTaem11mHASMnFilHrax3sLK0GDzcJrekZYLw==
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  typescript: ^3.3.3333
```

**Comment by David-Else** [comment]
Closed due to being ignored 7 months.

**Comment by zkochan** [comment]
> It has a shrinkwrap.yaml file, so is obviously a left over from pnmp < v3, so maybe something went wrong in the update?

The global packages are not migrated automatically. You can remove the `1` dir and reinstall your global versions with the latest pnpm.

> ENOENT: no such file or directory, open '/usr/pnpm-global/2/package.json'

This error should not happen. It should probably print something like "No global packages are installed"

**Comment by David-Else** [comment]
Thanks for the info. 

I since formatted the computer and reinstalled everything, pnpm 4 is working well. It does sound like a good idea to add the error message.
