### ISSUE TITLE
pnpm install recursive fails with `bin` in sub package that must be compiled first

### ISSUE THREAD

**Issue by hgossler** [pnpm/pnpm#1801]
### pnpm version:

`v3.2.0`

### Code to reproduce the issue:

See https://github.com/hgossler/pnpm-issue-1801 and follow the steps in the readme. This fails because pnpm attempts to `chmod` the bin in `sub-package1` before the `prepare` script is run.

### Expected behavior:

`pnpm i -r` should work.

### Actual behavior:

     ERROR  ENOENT: no such file or directory, chmod '... /pnpm-issue-2/packages/sub-package2/node_modules/sub-package1/dist/script.js'

It works if you run

    cd packages/sub-package1
    pnpm i

first.

### Additional information:

 - `node -v` prints: `v11.10.1`
 - Windows, OS X, or Linux?: macOS

**Comment by LukasHechenberger** [comment]
Any progress on this one? Or is there a workaround?

**Comment by zkochan** [comment]
No, this is not and easy to fix issue.

A workaround would be to create a bin file that just requires the compiled bin file. That's how it is done in pnpm repo as well: https://github.com/pnpm/pnpm/blob/master/packages/pnpm/bin/pnpm.js

**Comment by LukasHechenberger** [comment]
Okay, that’s not possible in my case. I did work around it by `touch`ing the bin file in a preinstall script. Works fine as far as I can tell by now... Thanks for the incredibly fast support!

**Comment by develar** [comment]
So, any project that uses Typescript and monorepo is not able to use PNPM without some kind of workaround. Hmm.... 

>  ERROR  ENOENT: no such file or directory, chmod '/home/circleci/project/test/node_modules/electron-builder/out/cli/cli.js'

**Comment by develar** [comment]
And no way to ask to not create bin links... https://github.com/pnpm/pnpm/issues/459

**Comment by zkochan** [comment]
> So, any project that uses Typescript and monorepo is not able to use PNPM without some kind of workaround.

not any project. This is not such a frequent scenario. It only fails if a workspace project with a compiled bin file is used in a postinstall script of another workspace project.

**Comment by develar** [comment]
> not any project. This is not such a frequent scenario. It only fails if a workspace project with a compiled bin file is used in a postinstall script of another workspace project.

No, in my case no `postinstall`. Just regular bin file that not referenced in `postinstall` script. You can find example in https://github.com/electron-userland/electron-builder/pull/5710 (branch `tsc-pnpm`). 

>     "electron-builder": "./out/cli/cli.js",
>      "install-app-deps": "./out/cli/install-app-deps.js"

As workaround, I added plain JS files.

**Comment by zkochan** [comment]
oh, right. You are correct. If it is not used in a postinstall, there is a workaround to put regular js file wrappers. We do that in the pnpm monorepo as well: https://github.com/pnpm/pnpm/tree/main/packages/pnpm/bin

Maybe as a fast workaround, we could make pnpm create the command shims even if the target does not exist yet.

**Comment by develar** [comment]
Correction — looks like indeed "not any project." In my project there is a dependency on `electron-builder`. `test` depends on `electron-builder` and looks like that PNPM tries to create bin links because of that. But were no issues in case of Yarn 2.

**Comment by kashpatel** [comment]
This was a problem in our project monorepo. As a workaround, we started committing built js file that `bin` command point to.

**Comment by estrattonbailey** [comment]
In case it's helpful, [I did similar](https://github.com/sure-thing/presta/blob/main/.github/workflows/ci.yml#L34) in my Github workflows.

```yml
      - name: pnpm - output bin stubs
        run: echo "#! /usr/bin/env node" > ./packages/presta/cli.js
      - name: pnpm - install
        run: pnpm install
```

**Comment by Akryum** [comment]
Still having this issue if a workspace in my monorepo has a `bin` file that doesn't exist yet (and I don't have any postinstall scripts):
https://github.com/Akryum/peeky/runs/4429592483?check_suite_focus=true
https://github.com/Akryum/peeky/blob/fec6b43830ba3d7821c0de7b6327fbc755b7aa37/packages/peeky-cli/package.json#L20

Using PNPM 6.23.1

**Comment by Akryum** [comment]
Ugly workaround in the meantime:

```akryum@Square:~/Projects/peeky$ npm run fix-pnpm-bin

> peeky-mono-repo@0.5.2 fix-pnpm-bin
> mkdir ./packages/peeky-cli/dist && touch ./packages/peeky-cli/dist/bin.js

akryum@Square:~/Projects/peeky$ pnpm i
Scope: all 10 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +957
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 957, reused 957, downloaded 0, added 0, done
node_modules/.pnpm/core-js-pure@3.19.3/node_modules/core-js-pure: Running postinstall script, done in 41ms
node_modules/.pnpm/@apollo+protobufjs@1.2.2/node_modules/@apollo/protobufjs: Running postinstall script, done in 38ms
node_modules/.pnpm/vue-demi@0.12.1_vue@3.2.24/node_modules/vue-demi: Running postinstall script, done in 68ms
node_modules/.pnpm/nodemon@2.0.15/node_modules/nodemon: Running postinstall script, done in 49ms
node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild: Running postinstall script, done in 46ms
akryum@Square:~/Projects/peeky$```

**Comment by ksnyde** [comment]
also still present in `6.24.3`

**Comment by zkochan** [comment]
Installation doesn't fail since [v6.24.4](https://github.com/pnpm/pnpm/releases/tag/v6.24.4), if the target bin doesn't exist. Just a warning is printed. This was change in this PR: https://github.com/pnpm/pnpm/pull/4172

**Comment by AlexAegis** [comment]
Could the "bin linking" step be re-tried for the failed links after the last install hook finished?

Or to expose it as cli, so we could plug it in ourselves as a postbuild step too.

**Comment by trappar** [comment]
I just ran into this issue and submitted a PR for the underlying library (see above) which would fix it 🤞🏻

**Comment by kenbankspeng** [comment]
Having this issue on pnpm 8.6.2 and it prevents me from using pnpm on any NextJS 13 project.

**Comment by eckdanny** [comment]
Me:

1. workspace root depends on a workspace pkg that has a compile step to produce a bin
2. _Uh Oh!_ I have a chicken-and-egg problem that is confounding CI
3. found this thread, looked at diff in #6728 (specifically [here](https://github.com/pnpm/pnpm/pull/6728/files#diff-0aa6b03bfbe25bbadf1970f18a5cffd4e20e116668c58729e9fd55b31c913d10R1918))
4. use a [`prepare`](https://docs.npmjs.com/cli/v9/using-npm/scripts#prepare-and-prepublish) lifecycle script in the bin-producing pkg
5. ✅ all good

FWIW: My bin-producing pkg is written in typescript and my workaround before adding a <samp>prepare</samp>, was to point the <samp>\<pkgJson\>#bin:</samp> at <samp>index.ts</samp>, and add `ts-node` as  <samp>devDependency</samp> to workspace root. This was useful for developing the pkg, but <samp>prepare</samp> is more idiomatic solution for satisfying the chicken-and-egg linking problem.

**Comment by webpro** [comment]
I jotted down a scrap about this: https://www.webpro.nl/scraps/compiled-bin-in-typescript-monorepo. Maybe it's helpful, please let me know it contains errors (it worked for me).

**Comment by stan-stately** [comment]
still seeing this in 9.1.3
