### ISSUE TITLE
Trouble with nativescript

### ISSUE THREAD

**Issue by paxperscientiam** [pnpm/pnpm#1802]
### pnpm version:
3.2.0

### Code to reproduce the issue:
From root of nativescript project, install dependencies: `pnpm install`.

No error results from installation of dependencies. However, `nativescript` indicates a linker error.

[gist](https://gist.github.com/paxperscientiam/c09dbe353a81d281311eefde99dc06f9)

### Expected behavior:
It works.

### Actual behavior:
Linker error :(

### Additional information:

 - `node -v` prints: v10.10.0
 - Windows, OS X, or Linux?: macos 10.14.14

## EDIT
I should add that things work just fine when dependencies are installed with `pnpm install --shamefully-flatten`

**Comment by zkochan** [comment]
Could you create a sample repo that reproduces the issue?

Unfortunately, if it works with `--shamefully-flatten` it means that the issue is not with pnpm.

**Comment by zkochan** [comment]
If nothing helps, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
