### ISSUE TITLE
Support an "extends" field in package.json

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1813]
Similarly to how "extends" work in `tsconfig.json` and `tslint.json`.

Before publishing, extend is removed and the `package.json` is extended with fields

**Comment by jemc** [comment]
@zkochan - GitHub says this ticket was "closed as completed on May 7, 2022", but it's unclear where this ended up.

Can you please point to the relevant feature that was implemented, for those who are finding the ticket later and want to find the feature?

Or, if it wasn't implemented, can you please add a comment explaining why you decided not to do it?
