### ISSUE TITLE
pnpm run doesn't pass arguments

### ISSUE THREAD

**Issue by parsehex** [pnpm/pnpm#1818]
### pnpm version:
**3.3.0**

### Code to reproduce the issue:
package.json:
```
{
  "name": "pnpm-bug-repro",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "arg-script": "node args.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
args.js:
```
console.log(process.argv[2]);
```

Then run `pnpm run arg-script hello` (the fourth argument can be anything)

### Expected behavior:

The script's output should be "hello"

### Actual behavior:

The script's output is `undefined`

### Additional information:

 - `node -v` prints: **v11.14.0**
 - Windows, OS X, or Linux?: **Linux**

This began after updating to 3.3.0 from (I believe) 3.1.0.

**Comment by zkochan** [comment]
:ship: 3.3.1
