### ISSUE TITLE
Install from lock file fails on packages in private registry with base path

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [pnpm/pnpm#1827]
### pnpm version:
Affects: 3.3.0, 3.3.1, 3.3.2
Does not affect: 2.57.7

### Code to reproduce the issue:

1. Create a `~/.npmrc` that notes the url for your scoped private registry, e.g.
  `@mycompany:registry=https://mycompany.jfrog.io/mycompany/api/npm/npm-local/`
1. Create a `package.json` that has a dependency from a scoped package from a private registry
2. `pnpm install` to create `pnpm-lock.yaml`
3. Purge the pnpm store (to simulate e.g. running on someone else's machine that has never installed this before, such as a CI builder): `rm -rf ~/.pnpm-store/`
4. `pnpm install` again

### Expected behavior:
`pnpm` should compute the correct download URL for the package TGZ when installing from the lock file just like it does when installing without a lockfile.

### Actual behavior:
`pnpm` forgets about the base path in the registry and instead tries to download from
`https://mycompany.jfrog.io/@mycompany/mypackage/-/@mycompany/mypackage-1.0.0.tgz`
Which of course results in a 404 error and failed installation, making `pnpm` unusable for such registries.

### Additional information:

 - `node -v` prints: `v10.15.3`
 - Windows, OS X, or Linux?: Linux

Older pnpm (2.x) included more complete path information for the packge in the shrinkwrap in the `resolution` section, e.g.:
```
      registry: 'https://mycompany.jfrog.io/mycompany/api/npm/npm-local/'
      tarball: 'https://mycompany.jfrog.io/mycompany/api/npm/npm-local/@mycompany/mypackage/-/@mycompany/mypackage-1.0.0.tgz'
```
Whereas 3.3.2 is only including:
```
      tarball: /@mycompany/mypackage/-/@mycompany/mypackage-2.0.0.tgz
```

**Comment by zkochan** [comment]
This is the expected behavior. We don't store information about the used registries in the lockfile. So you may use a verdaccio proxy for instance, and the lockfile will stay the same.

If you need to force a specific scope to always resolve to a specific registry, use a `.npmrc` in the root of the package with the following content:

```
@mycompany:registry=https://mycompany.jfrog.io/mycompany/api/npm/npm-local/
```

**Comment by mgabeler-lee-6rs** [comment]
@zkochan I _am_ doing that, as noted in the description, and it _is_ remembering the registry, _but with the wrong path_.

**Comment by zkochan** [comment]
I see. Ok, then it's a bug

**Comment by zkochan** [comment]
So the entry in the lockfile should be:

```
tarball: @mycompany/mypackage/-/@mycompany/mypackage-2.0.0.tgz
```

I'll fix this

**Comment by zkochan** [comment]
:ship: 3.3.4

You'll have to regenerate your lockfile with the new version of pnpm
