### ISSUE TITLE
Insufficient deduping

### ISSUE THREAD

**Issue by cdfa** [pnpm/pnpm#1838]
Hi, I already posted about this in Gitter, but that conversation seems to be dead and I think it might be a bug anyway. The problem is that `styled-components` is not deduped in my dependency tree, which leads to failing styling on my generated documentation site.

### pnpm version:
`3.3.4`

### Code to reproduce the issue:
1. Clone [my project](https://github.com/cdfa/react-turn-reveal)
2. Checkout `develop`
3. `rm pnpm-lock.yaml` to force resolution
4. `pnpm i` or `pnpm i --resolution-strategy fewer-dependencies`

### Expected behavior:
```
$ pnpm list styled-components
react-turn-reveal@0.1.0 /home/cdfa/Projects/react-turn-reveal
├─┬ docz-theme-default@1.2.0
│ └─┬ styled-components@4.2.0
└── styled-components@4.2.0
```
and styled work properly.

### Actual behavior:
```
$ pnpm list styled-components
react-turn-reveal@0.1.0 /home/cdfa/Projects/react-turn-reveal
├─┬ docz-theme-default@1.2.0
│ └─┬ styled-components@4.2.0_b8333fe1de066bcb7f20c3365f51e6fb
│   └─┬ babel-plugin-styled-components@1.10.0_styled-components@4.2.0
│     └── styled-components@4.2.0_b8333fe1de066bcb7f20c3365f51e6fb
└── styled-components@4.2.0
```
and getting this warning in the browser console when running the docz server with `npm run dev`
```
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.

See https://s-c.sh/2BAXzed for more info.
```
and indeed styled not rendering properly.

### Additional information:

 - `node -v` prints: `v10.15.3`
 - Windows, OS X, or Linux?: Linux

**Comment by octogonz** [comment]
@iclanton FYI

**Comment by zkochan** [comment]
:ship: 3.5.0-0
