### ISSUE TITLE
EISDIR when installing into secondary drive

### ISSUE THREAD

**Issue by yume-chan** [pnpm/pnpm#1839]
### pnpm version:
3.3.4

### Code to reproduce the issue:

````shell
cd /d D:\test
pnpm install express
````

### Expected behavior:

Install successfully.

### Actual behavior:

````
ERROR  EISDIR: illegal operation on a directory, symlink 'D:\test\node_modules\.registry.npmjs.org\array-flatten\1.1.1\node_modules\array-flatten' -> 'D:\test\node_modules\.registry.npmjs.org\express\4.17.0\node_modules\array-flatten'
````

pnpm-debug.log: https://gist.github.com/yume-chan/52db850a112e9761c18c87ef5f8f23ab

### Additional information:

Doesn't happen when install into my C drive where the store is located at. I understand pnpm can't create links to my D drive, but I expect pnpm to copy all packages there and install successfully.

 - `node -v` prints: v12.2.0
 - Windows, OS X, or Linux?: Windows 10 1809 x64

**Comment by zkochan** [comment]
Do you set the store path explicitly? By default, the store location would be the root of the disk, so in your case it would be `D:\.pnpm-store`

If it doesn't work, maybe you could test [@pnpm/store-path](https://github.com/pnpm/store-path) and see what's the issue.

Indeed. by default, if creating a hard link fails, the files are copied from the store. Related code:

https://github.com/pnpm/pnpm/blob/03b5267586393c2a3dbbeb57aefbdec3ea25b952/packages/package-store/src/storeController/createImportPackage.ts#L42-L62

This should work, unless you set a different value to the [package-import-method](https://pnpm.js.org/docs/en/pnpm-install.html#package-import-method) config

**Comment by yume-chan** [comment]
> Do you set the store path explicitly?

I didn't remember I set the store path anywhere. From the log file I believe it still used `C:\\Users\\Simon\\.pnpm-store\\2` as store.

----

> maybe you could test @pnpm/store-path and see what's the issue.

Here is the output:

````
D:\test>npm i @pnpm/store-path
+ @pnpm/store-path@2.0.0
added 20 packages from 9 contributors and audited 27 packages in 8.545s

D:\test>node -e "require('@pnpm/store-path').default('D:\\test', 'pnpm-store').then(console.log)"
D:\test\pnpm-store\2
````

----

I retried one more time and this time I got

````
 ERROR  EISDIR: illegal operation on a directory, symlink 'D:\test\node_modules\.registry.npmjs.org\accepts\1.3.7\node_modules\accepts' -> 'D:\test\node_modules\.registry.npmjs.org\express\4.17.0\node_modules\accepts'
````

And here is the structure of my node_modules folder at this time, I can confirm all of them are ordinary files and folders, not hard links.

````
D:\test\node_modules>tree
Folder PATH listing
Volume serial number is E2D3-F179
D:.
└───.registry.npmjs.org
    ├───express
    │   └───4.17.0
    │       └───node_modules
    │           ├───_tmp_3108_769f50459741e1a4b548c76f830fd430
    │           │   └───lib
    │           │       └───middleware
    │           ├───safe-buffer
    │           └───range-parser
    ├───negotiator
    │   └───0.6.2
    │       └───node_modules
    │           └───_tmp_3108_edff7ae802336dff413ab375b37e2eee
    │               └───lib
    ├───body-parser
    │   └───1.19.0
    │       └───node_modules
    │           └───_tmp_3108_d1398f72bee9054f34194848f1d001b1
    │               └───lib
    ├───debug
    │   └───2.6.9
    │       └───node_modules
    │           └───_tmp_3108_f00168d25880d46d2306b7700173c218
    │               └───src
    ├───setprototypeof
    │   └───1.1.1
    │       └───node_modules
    │           └───_tmp_3108_29ff542b24c2ed44f667ef0d75c973ac
    │               └───test
    ├───depd
    │   └───1.1.2
    │       └───node_modules
    │           └───_tmp_3108_088d3b3b1005576ed7132aebe7772182
    │               └───lib
    │                   └───compat
    ├───mime-types
    │   └───2.1.24
    │       └───node_modules
    ├───accepts
    │   └───1.3.7
    │       └───node_modules
    ├───array-flatten
    │   └───1.1.1
    │       └───node_modules
    ├───mime-db
    │   └───1.40.0
    │       └───node_modules
    ├───content-type
    │   └───1.0.4
    │       └───node_modules
    ├───bytes
    │   └───3.1.0
    │       └───node_modules
    ├───ms
    │   └───2.0.0
    │       └───node_modules
    ├───http-errors
    │   └───1.7.2
    │       └───node_modules
    ├───inherits
    │   └───2.0.3
    │       └───node_modules
    └───statuses
        └───1.5.0
            └───node_modules
````

**Comment by yume-chan** [comment]
I suddenly realized that my D drive was in exFAT file system which doesn't support symlinks at all.

I re-formatted it to NTFS and now pnpm works fine.
