### ISSUE TITLE
Upgrading `pnpm` should occur wherever `pnpm` currently is instead of where `node` lives

### ISSUE THREAD

**Issue by binhonglee** [pnpm/pnpm#1859]
I currently use `nvm` to maintain `node` and `npm` versions where I would periodically cleanup old versions of node and `npm` (since I don't see why I need multiple versions locally) which means every time I update `node` and remove the old version, I lose `pnpm` along the way. So instead, I'm trying to install it at a custom path and have it update in that custom path instead (which also helps with the sanity of using a build tool that does not take in default bin config where I will have to update the path value manually every time I updates any one of these moving parts).

### Code to reproduce the issue:

```
$ curl -L https://unpkg.com/@pnpm/self-installer | PNPM_DEST=~/.pnpm/etc PNPM_BIN_DEST=~/.pnpm/bin node
$ pnpm install -g pnpm
```

### Expected behavior:

`pnpm` gets installed and updated at its current bin location. (`~/.pnpm/bin`)

### Actual behavior:

`pnpm` is installed in wherever node was installed. (`~/.nvm/versions/node/v12.3.1/`)

```
$ pnpm install -g pnpm
Nothing to stop. No server is running for the store at ~/.pnpm-store/2
Packages: +1
+
Downloading registry.npmjs.org/pnpm/3.4.1: 5.61 MB/5.61 MB, done
Resolving: total 1, reused 0, downloaded 1, done

~/.nvm/versions/node/v12.3.1/pnpm-global/2:
+ pnpm 3.4.1
```

### Additional information:

 - `node -v` prints: v12.3.1
 - Windows, OS X, or Linux?: Linux Mint 19

**Comment by MohamadKh75** [comment]
Any updates on this?
Plus, whenever i upgrade node via nvm, i lose all my global pnpm packages ☹

**Comment by zkochan** [comment]
We are working on making pnpm a Node.js version manager. So you will not need nvm.

https://github.com/pnpm/pnpm/discussions/3434

https://pnpm.io/cli/env

**Comment by zkochan** [comment]
This should not be an issue with pnpm v7
