### ISSUE TITLE
save-exact=true not respected when updating recursively

### ISSUE THREAD

**Issue by lenovouser** [pnpm/pnpm#1861]
### pnpm version:

`3.4.1`

### Code to reproduce the issue:

`pnpm recursive update --latest`

### Expected behavior:

Saving versions in the `x.x.x` format

### Actual behavior:

It's saving the versions as `^x.x.x`

### Additional information:

 - `node -v` prints: `v11.15.0`
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
I cannot reproduce it with 3.5.0.
Tried by setting save-exact globally, setting it locally and setting it in the root of the workspace.

**Comment by lenovouser** [comment]
Okay, weird. I am still experiencing this when using:

```sh-session
pnpm recursive update --latest
```

in [lenovouser/pnpm-recursive-update](https://github.com/lenovouser/pnpm-recursive-update)

![](https://i.lenovouser.me/OGiDhpfNaIXZ7gkr.jpg)

**Comment by lenovouser** [comment]
With `3.5.0` by the way

![](https://i.lenovouser.me/wp3SafXu5yLody9G.jpg)

**Comment by zkochan** [comment]
:ship: [3.5.3](https://github.com/pnpm/pnpm/releases/tag/v3.5.3)
