### ISSUE TITLE
pnpm install in workspace folder doesn't respect pnpmfile

### ISSUE THREAD

**Issue by johnroot** [pnpm/pnpm#1863]
### Code to reproduce the issue:
https://github.com/johnroot/pnpmfile-repro

### Expected behavior:
While in a workspace, `pnpm install` should respect the `pnpmfile` of that workspace.

### Actual behavior:
`pnpm install` (and other commands) does not respect the `pnpm` file of a workspace. However, `pnpm recursive install` does. ~~`pnpm install --pnpmfile=../../pnpmfile.js` does not work either.~~ 

### Additional information:

 - `node -v` prints: v11.14.0
 - Windows, OS X, or Linux?: Windows

**Comment by johnroot** [comment]
Slight update: it seems `pnpm install --pnpmfile=../../pnpmfile.js` does work. Putting `pnpmfile=./pnpmfile.js` in the `.npmrc` does not. This could be user error; is there a good way of putting the pnpmfile path in the `.npmrc`?

**Comment by zkochan** [comment]
It is great to have a new contributor!🎉🎉🎉

**Comment by zkochan** [comment]
:ship: 3.5.1
