### ISSUE TITLE
Still not installing all dependencies

### ISSUE THREAD

**Issue by paxperscientiam** [pnpm/pnpm#1865]
### pnpm version:
3.5.0-1

### Code to reproduce the issue:
Create fresh project, then `pnpm i nativescript-dev-sass`

### Expected behavior:
node-sass would be linked

### Actual behavior:
node-sass is not linked

### Additional information:

 - `node -v` prints: 10.10.0
 - Windows, OS X, or Linux?: macos 10.14.4

My best guess is that a post-install script is bungling things.

**EDIT** (2019-06-18)
So, I've updated to v3.5.0.

Not entirely sure if this was the case before, but, from what I can tell, the only thing installed in the project (and I tried the above from scratch again), is "node_modules/nativescript-dev-sass/node_modules/.bin/node-sass".

**Comment by paxperscientiam** [comment]
I don't mean to beat a dead horse, but this still isn't resolved. I just tried installing `@symfony/webpack-encore` and `pnpm` fails to install/link its dependencies.

**Comment by zkochan** [comment]
I see node-sass installed and linked inside `node_modules/.pnpm`
