### ISSUE TITLE
`version`

### ISSUE THREAD

**Issue by tomByrer** [pnpm/pnpm#1869]
### pnpm version: 
3.4.1 I think ;)
### Code to reproduce the issue:
`pnpm version`

### Expected behavior:
pnpm's version be listed
### Actual behavior:
```JavaScript
{ npm: '6.5.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.0.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.34.0',
  node: '11.9.0',
  openssl: '1.1.1a',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.25.0',
  v8: '7.0.276.38-node.16',
  zlib: '1.2.11' }
```
Which is handy, but I still don't know pnpm's version.

Win10 Git-Bash

thanks so much!

**Comment by mrkishi** [comment]
The right command is `pnpm --version`. That's in line with npm's `npm --version`. 👍

**Comment by tomByrer** [comment]
OK, cheers

**Comment by tomByrer** [comment]
This helps, cheers!

https://github.com/pnpm/pnpm/commit/55cfc92093a96414f7420579e863bea651cd2fe4

**Comment by zkochan** [comment]
Yeah, I noticed that the TypeScript CLI does this and I thought it was a great idea
