### ISSUE TITLE
Lockfile version upgrade should maintain existing dependency versions

### ISSUE THREAD

**Issue by sachinjoseph** [pnpm/pnpm#1876]
# Lockfile version upgrade should maintain existing dependency versions

**Edit**: the original title of this issue was **`pnpm install` has different behaviors on 3.4.1 and 3.5.1.**

* Using the repo here for repro: https://github.com/sachinjoseph/rush-pnpm-bug

* Before all runs below, `pnpm-lock.yaml` has `react-focus-lock`'s  version as **`1.17.7`**.

### In `(repo-root)/pnpm-only/` 
`$ cd pnpm-only/`

| pnpm version | `$ pnpm install --frozen-shrinkwrap`                                                 | `$ pnpm install`                                                                     | `$ pnpm install --no-prefer-frozen-shrinkwrap`                                |
|:------------:|------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
|     3.4.1    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml` |
|     3.5.1    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | &#x1F534; installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml`        | installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml` |

### Expected behavior: 
For version 3.5.1, **pnpm install** should install `react-focus-lock` version `1.17.7`, like version 3.4.1 does.

### Actual behavior:
For version 3.5.1, **pnpm install** installs `react-focus-lock` version `1.19.1`, unlike version 3.4.1 which installs version `1.17.7`.
### Additional information:

 - `node -v` prints: v10.15.3
 - Windows

**Comment by zkochan** [comment]
This happens because pnpm v3.5 has an update to the lockfile format. When pnpm update the lockfile to a new format, it updates all deps. If you need react-focus-lock v1.17.7, you can install it as a direct dependency of your project. In that case, pnpm will prefer this version. So you can do `pnpm add react-focus-lock@1.17.7 && pnpm up --depth 99`

**Comment by sachinjoseph** [comment]
Thanks @zkochan. If I understand this correctly, this is a breaking change. Shouldn't **pnpm install** simply update the file format without updating the dependencies? Isn't this behavior breaking the determinism promise of **pnpm install**?

**Comment by zkochan** [comment]
> If I understand this correctly, this is a breaking change

I don't consider this a breaking change because prior versions of pnpm will not fail on the new format, so if your ci uses pnpm v3.4 and runs `pnpm install --frozen-lockfile` it will work with the lockfile format 5.1

> Shouldn't pnpm install simply update the file format without updating the dependencies?

Maybe. For me, updating the dependencies was not a big deal. Lockfiles are important but I never used them to lock the whole dependency tree forever.

> Isn't this behavior breaking the determinism promise of pnpm install?

We can only promise full determinism in scope of one pnpm version + lockfile. So if you have a lockfile and you use the same version of pnpm, it should be deterministic. We have an open issue to allow specifying the wanted pnpm version (https://github.com/pnpm/pnpm/issues/1383)

> Is there a way to lock a transitive dependency version without having to declare it as a direct dependency?

Yes, you can lock dependencies via [hooks](https://pnpm.js.org/docs/en/hooks.html).

**Comment by zkochan** [comment]
:ship: [3.5.3](https://github.com/pnpm/pnpm/releases/tag/v3.5.3)

**Comment by sachinjoseph** [comment]
Thanks @zkochan, the behavior is now this:

| pnpm version | `$ pnpm install --frozen-shrinkwrap`                                                 | `$ pnpm install`                                                                     | `$ pnpm install --no-prefer-frozen-shrinkwrap`                                |
|:------------:|------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
|     3.4.1    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml` |
|     3.5.1    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | &#x1F534; installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml`        | installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml` |
|     3.5.3    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.17.7`**,  updates `pnpm-lock.yaml`        | &#x1F534; installs `react-focus-lock` version **`1.17.7`**,  does NOT update `pnpm-lock.yaml` |

I was expecting `pnpm install --no-prefer-frozen-shrinkwrap`  to install react-focus-lock **1.19.1**  but it now installs  **1.17.7**. Not sure if my expectation is inaccurate.

**Comment by sachinjoseph** [comment]
cc: @octogonz

**Comment by zkochan** [comment]
`pnpm install` is not updating dependencies. If you want to update dependencies, you should run `pnpm update`

**Comment by sachinjoseph** [comment]
Thanks so much @zkochan, sorry about the confusion.

**Comment by sachinjoseph** [comment]
Verified that **pnpm install** and **pnpm update** works as expected on my repro repo.

**Comment by sachinjoseph** [comment]
Just FYI, this could be a breaking change for some users who rely on the earlier **pnpm install** behavior.
Rush is broken with this update and needs to be fixed: https://github.com/microsoft/web-build-tools/issues/1339

**Comment by zkochan** [comment]
But this behavior is not new. `pnpm install` was never updating dependencies. The update was only happening if the lockfile was generated by an earlier version of pnpm but I fixed that

**Comment by sachinjoseph** [comment]
Okay, maybe I am wrong about the previous behavior. Let me get back to you on this.

**Comment by sachinjoseph** [comment]
I verified the **pnpm install** behavior on 3.4.1 and 3.5.3 again. The flag `--no-prefer-frozen-shrinkwrap` has different behaviors on 3.4.1 and 3.5.3.

`$ cd pnpm-only/`

| pnpm version | `$ pnpm install --frozen-shrinkwrap`                                                 | `$ pnpm install`                                                                     | `$ pnpm install --no-prefer-frozen-shrinkwrap`                                |
|:------------:|------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
|     3.4.1    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.19.1`**,  updates `pnpm-lock.yaml` |
|     3.5.3    | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | installs `react-focus-lock` version **`1.17.7`**, does NOT update `pnpm-lock.yaml` | &#x1F534; installs `react-focus-lock` version **`1.17.7`**,  does NOT update `pnpm-lock.yaml` |

**Comment by sachinjoseph** [comment]
To clarify, I am not saying that there is a regression in 3.5.3. I am saying that the **pnpm install** behavior has changed with 3.5.3 and looks like it is a breaking change.

**Comment by sachinjoseph** [comment]
Currently, it seems `--prefer-frozen-lockfile` and `--no-prefer-frozen-lockfile` work in the same way.
