### ISSUE TITLE
pnpm install behavior inconsistent with flags

### ISSUE THREAD

**Issue by sachinjoseph** [pnpm/pnpm#1878]
### Repro repo:
https://github.com/sachinjoseph/pnpm-install-lockfile-bug

### Expected behavior:
**pnpm install** should not update the lockfile if the current lockfile satisfies the package.jsons (unless or the lockfile version needs an upgrade

1. If **pnpm install `--frozen-lockfile`** can succeed, then **pnpm install** shouldn't update the lockfile (unless the lockfile version needs an upgrade).

2. If `pnpm install` can succeed without updating the lockfile, then **pnpm install `--lockfile-only`** should not update the lockfile.

### Actual behavior:
Not only does **pnpm install** update the lockfile when it is not necessary, but also the behavior is inconsistent with different flags.

`react-focus-lock` version is `1.17.7` in `pnpm-lock.yaml` before running these commands.

#### In folder `package1`
`$ cd (repo-root/package1`

|                                            | pnpm install `--frozen-lockfile` | pnpm install | pnpm install `--lockfile-only` |
|--------------------------------------------|:------------------------------:|--------------|------------------------------|
| `react-focus-lock` version in `pnpm-lock.yaml` |             1.17.7             |   &#x1F534;1.19.1    |            &#x1F534;1.19.1            |

#### In folder `package2`
`$ cd (repo-root/package2`

|                                            | pnpm install `--frozen-lockfile` | pnpm install | pnpm install `--lockfile-only` |
|--------------------------------------------|:------------------------------:|--------------|------------------------------|
| React-focus-lock version in pnpm-lock.yaml |             1.17.7             |    1.17.1    |            &#x1F534;1.19.1            |

### Additional information:
 - In the above examples in which pnpm-lock.yaml changes, the only change in pnpm-lock.yaml is `react-focus-lock`'s version (and its integrity hash).
 - `node -v` prints: v10.15.3
 - Windows, OS X, or Linux?: Windows 10

**Comment by zkochan** [comment]
:ship: [3.5.2](https://github.com/pnpm/pnpm/releases/tag/v3.5.2)

**Comment by sachinjoseph** [comment]
Thanks Zolchan. Verified that this no longer repros on my repro repo.
