### ISSUE TITLE
When indirect dependencies change, "pnpm install --frozen-lockfile" fails only if node_modules and pnpm-store don't exist

### ISSUE THREAD

**Issue by sachinjoseph** [pnpm/pnpm#1882]
### pnpm version: 3.5.3
Edit: The issue was originally filed for pnpm 3.5.2. The issue repros on pnpm 3.5.3 as well.

### Code to reproduce the issue: https://github.com/sachinjoseph/pnpm-install-frozen-lockfile-bug

Repro code based on @octogonz 's code here: https://github.com/pnpm/pnpm/issues/1362#issuecomment-419235832

1. `projects/sp-application-base.tgz` has dependency on `uifabric/styling` version `5.33.0`.
2. `projects/sp-application-base-step2.tgz` has dependency on `uifabric/styling` version `5.33.1`.

### Repro steps
In the repro repo root:

1. `pnpm i -store pnpm-store --frozen-lockfile`
Lockfile is up-to-date, resolution step is skipped
Packages: +11
+++++++++++
Resolving: total 11, reused 0, downloaded 11, done

dependencies:
+ @rush-temp/sp-application-base 0.0.0
2. `cp .\projects\sp-application-base-step2.tgz .\projects\sp-application-base.tgz`
3. `pnpm i -store pnpm-store --frozen-lockfile`
```
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
```
4. `rimraf .\node_modules\ .\pnpm-store\`
5. `pnpm i -store pnpm-store --frozen-lockfile`
```
Lockfile is up-to-date, resolution step is skipped
Packages: +11
+++++++++++
 WARN  Fetching file:projects/sp-application-base.tgz failed!
 ERROR  sha512-***== integrity checksum failed when using sha512: wanted sha512-***== but got sha512-***==. (262 bytes)
```

### Expected behavior:
1. When indirect dependencies change, **pnpm install `--frozen-lockfile`** should say that the lockfile is out of date.
2. **`pnpm install `--frozen-lockfile`** should fail if the dependencies change.

### Actual behavior:
1. **pnpm install `--frozen-lockfile`** says that lockfile is up-to-date when the dependencies have changed.
2. **pnpm install `--frozen-lockfile`** fails only if node_modules and pnpm-store doesn't exist.

### Additional information:

 - `node -v` prints: v10.15.3
 - Windows, OS X, or Linux?: Windows 10

**Comment by zkochan** [comment]
:ship: [3.5.3](https://github.com/pnpm/pnpm/releases/tag/v3.5.3)

**Comment by sachinjoseph** [comment]
@zkochan This issue still repros for me on **pnpm** 3.5.3 on the same repo. I have updated the repo to simplify the repro steps.

**Comment by sachinjoseph** [comment]
Should I reopen a new issue and point to 1882?

**Comment by zkochan** [comment]
I'll check

**Comment by zkochan** [comment]
Created another issue https://github.com/pnpm/pnpm/issues/1889
