### ISSUE TITLE
`pnpm -g i generate generate-gitignore` not all dependencies installed

### ISSUE THREAD

**Issue by paxperscientiam** [pnpm/pnpm#1884]
### pnpm version:
3.5.2
### Code to reproduce the issue:
`pnpm -g i generate generate-gitignore` 

### Expected behavior:
All dependencies installed in global scope so that package works

### Actual behavior:
Not all global dependencies installed, so doesn't work.

### Additional information:

 - `node -v` prints: v10.10.0
 - Windows, OS X, or Linux?: macos 10.14.5

Note: When you try to reproduce, what's missing on your system will obviously depend on what you've installed beforehand. That said, in my case, the following were missing: `success-symbol`, `warning-symbol`, `info-symbol`, `error-symbol`, `time-stamp`,

**Comment by zkochan** [comment]
Seems like the issues is caused by this library - [lazy-cache](https://www.npmjs.com/package/lazy-cache). It is used by generate and it cannot resolve the deps even though they are in place. Seems like lazy-cache has fix its resolution algorithm

**Comment by paxperscientiam** [comment]
@zkochan Hey, it looks like this is still a problem with version 3.8.1.

Just installed microbundle@next; however, none of its dependencies were installed. This seems like a major issue. Am I missing something?

**Comment by zkochan** [comment]
The dependencies are installed. They are inside `node_modules/.pnpm`.

Read more about the symlinked node_modules created by pnpm: https://pnpm.io/symlinked-node-modules-structure
