### ISSUE TITLE
About conflict when using repo https://github.com/googleapis/google-api-nodejs-client

### ISSUE THREAD

**Issue by naazguu** [pnpm/pnpm#1896]
Hello good afternoon brother

About conflict when using repo https://github.com/googleapis/google-api-nodejs-client

I would like to report the occurrence in the use of repo https://github.com/googleapis/google-api-nodejs-client

![Captura de tela de 2019-06-27 23-56-24](https://user-images.githubusercontent.com/50875553/60314000-706db600-9937-11e9-8065-ec646d78fb03.png)

Removing directories * test * works as expected

**Comment by zkochan** [comment]
This seems to work now.
