### ISSUE TITLE
Can't resolve '@firebase/util'

### ISSUE THREAD

**Issue by mozgbrasil** [pnpm/pnpm#1899]
Hello good afternoon brother

In my environment

    $ node -v
    v12.1.0
    $ npm -v
    6.9.2

If I come to use the commands

    npm install
    npm start

My application works as expected

...

If I come to use the commands

    pnpm recursive install
    pnpm recursive run start

Error is displayed

...

Can you help me

![Captura de tela de 2019-07-01 12-03-08](https://user-images.githubusercontent.com/17202780/60446653-354dda00-9bf8-11e9-974a-aeb8ef3d063d.png)

**Comment by zkochan** [comment]
Can you create a sample repo to reproduce this issue?
Some dependency probably requires a package that is not in its package.json. You may try setting `shamefully-flatten=true` in the root of your repo and running `pnpm recursive install --force`.

**Comment by mozgbrasil** [comment]
Hello good afternoon brother

Thanks for interacting,

For now The use of pm2's "ecosystem.config.js" met my need

Thanks
