### ISSUE TITLE
There are no docs for the "--force" argument

### ISSUE THREAD

**Issue by onlywei** [pnpm/pnpm#1906]
### pnpm version:
3.x

### Code to reproduce the issue:
No code, just do `pnpm i --force`

### Expected behavior:
N/A

### Actual behavior:
N/A

### Additional information:
I know that the `--force` argument allows us to upgrade a `node_modules` directory from pnpm v2 to pnpm v3, but it is not documented on the website and we don't know what else it does. Does it also ignore the `.pnpm-store`? Is there a way to make it only re-do the local `node_modules` but still use the store?

**Comment by josephschmitt** [comment]
No docs on this page: https://pnpm.js.org/docs/en/pnpm-install.html

**Comment by mcmxcdev** [comment]
You can find the `--force` flag documented now under: https://pnpm.io/cli/install#--force
