### ISSUE TITLE
parse-domain postinstall

### ISSUE THREAD

**Issue by Js-Brecht** [pnpm/pnpm#1907]
### pnpm version:
3.5.3

### Code to reproduce the issue:
```
pnpm i -g parse-domain
```
[pnpm-debug.log](https://gist.github.com/Js-Brecht/1d26ca6d6c35406960f5413365b95990) from `parse-domain` global install

### Expected behavior:
Successful install of `parse-domain` in the global context.

### Actual behavior:
```
Packages: +64
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 233, reused 231, downloaded 0, done
node_modules/.registry.npmjs.org/parse-domain/2.3.1/node_modules/parse-domain: Running postinstall script, failed in 1s
.../2.3.1/node_modules/parse-domain postinstall$ run-s build:tries
│  ERROR  Missing script: build:tries
│ ERROR: "build:tries" exited with 1.
└─ Failed in 1s
 ERROR  Command failed with exit code 1.
```
### Additional information:

 - `node -v` prints: v10.13.0, v11.15.0, v12.5.0
 - Windows, OS X, or Linux?: This was run in Windows, but first ran into this in Linux.

This only seems to fail in the global context.  Installing in a local project works just fine.  Not sure why, but I haven't done much investigating.  I do know that the script exists; I can browse to the working directory reported by pnpm and run that postinstall script, and it has no issues.

**Comment by zkochan** [comment]
:ship: 3.6.0-0

**Comment by Js-Brecht** [comment]
👍 Works great.
