### ISSUE TITLE
pnpm link outputs ENOENT: no such file or directory, mkdir '/usr/local/pnpm-global/node-modules'

### ISSUE THREAD

**Issue by cherryblossom000** [pnpm/pnpm#1909]
### pnpm version:
3.5.3

### Code to reproduce the issue:
    $ pnpm link

### Expected behavior:
A symlink would be created.

### Actual behavior:
Outputs

     ERROR  ENOENT: no such file or directory, mkdir '/usr/local/pnpm-global/node_modules'

This might be due to the node_modules folder being in `/usr/local/pnpm-global/2/node_modules`, not `/usr/local/pnpm-global/node_modules`.

### Additional information:

 - `node -v` prints: `v10.15.3`
 - Windows, OS X, or Linux?: OS X

**Comment by VOID404** [comment]
On Linux, same error when calling `pnpm install -g @vue/vli`, fixed by calling with `sudo`.

**Comment by cupcakearmy** [comment]
Same here when running `pnpm -g i pnpm`

Version: `4.1.7`
Node: `12.13.0`
OS: macOS Catalina

**Comment by geea-develop** [comment]
Check pnpm-debug.log
for me this folder was not created /usr/local/pnpm-global
had to create it with sudo and set the owner to your current user with chown
hope it helps

**Comment by gjgd** [comment]
I got the same error. 
```
➜ npx pnpm install --global pnpm
 ERROR  ENOENT: no such file or directory, mkdir

➜ cat pnpm-debug.log
{
  "0 error pnpm": {
    "message": {
      "errno": -2,
      "code": "ENOENT",
      "syscall": "mkdir"
    },
    "err": {
      "name": "Error",
      "message": "ENOENT: no such file or directory, mkdir",
      "code": "ENOENT",
      "stack": "Error: ENOENT: no such file or directory, mkdir"
    }
  }
}%
```

**Comment by gjgd** [comment]
Fixed for me by running:
```bash
sudo mkdir -p /usr/local/pnpm-global
sudo chown -R $(whoami) /usr/local/pnpm-global
```

**Comment by DylanCulfogienis** [comment]
Still encountering this issue in 2021. Any news?

**Comment by cherryblossom000** [comment]
I actually don't get this error anymore (haven't for a long time actually) because I now use [asdf](http://asdf-vm.com/) to install Node.js, and I think the equivalent path to `/usr/local/pnpm-global` is `~/.asdf/installs/nodejs/16.13.0/.npm/pnpm-global`. However, I see that people are still having this issue, so I'll keep this issue open.

**Comment by zkochan** [comment]
This should work with pnpm v7.

**Comment by sethlivingston** [comment]
I was getting `ENOENT` because I had a typo in what I was trying to run.

```bash
pnpm exec ts    # wrong, results in ENOENT
pnpm exec tsc   # correct, runs fine
```
