### ISSUE TITLE
"pnpm make-dedicated-lockfile" should create a dedicated lockfile for a workspace package

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1919]
Currently, when projects are inside a workspace, they share one lockfile and one node_modules. However, sometimes projects from the workspace have to be copied and deployed separately. For this case, there should be a possibility to generated a dedicated lockfile from the shared lockfile for the exported package.

Possible alternative names:
* make-focused-lockfile

cc @vjpr

**Comment by zkochan** [comment]
Covered by #2198

**Comment by diachedelic** [comment]
I think a simple command to generate a lockfile for a single package in a workspace would be very useful for deployments, but it did not seem to me like the discussion in #2198 is heading in that direction.

**Comment by zkochan** [comment]
I implemented it as a separate tool for now. Install it via `pnpm add -g @pnpm/make-dedicated-lockfile`

Run it by just calling `make-dedicated-lockfile`.

**Comment by diachedelic** [comment]
Amazing! Thank you so much!

**Comment by diachedelic** [comment]
It seems to choke if I am using unpublished, workspace-only dependencies - is this to be expected?

```
$ pnpx -p @pnpm/make-dedicated-lockfile make-dedicated-lockfile
Packages: +115
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/me/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Resolving: total 115, reused 115, downloaded 0, done

/Users/me/.npm/_npx/6733/pnpm-global/4:
+ @pnpm/make-dedicated-lockfile 0.1.1
Scope: 1 of 25 workspace projects
 ERROR  404 Not Found: @company/env (via https://npm.company.com/@company%2Fenv)
.                                        | Resolving: total 10, reused 10, downloaded 0
(node:6743) UnhandledPromiseRejectionWarning: Error: Exit code: 1
    at ChildProcess.<anonymous> (/Users/me/.npm/_npx/6733/pnpm-global/4/node_modules/.pnpm/@pnpm/exec@1.1.5/node_modules/@pnpm/exec/lib/index.js:46:35)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
```
// package.json
{
  "name": "@company/images",
  ...
  "devDependencies": {
    "@company/env": "workspace:^3.3.0",
  },
  "publishConfig": {
    "registry": "https://npm.company.com"
  }
}
```

**Comment by zkochan** [comment]
just use a link in this case. Something like

```
   "@company/env": "link:../../env",
```

**Comment by diachedelic** [comment]
Ok, I'll give that a shot. 

Just a note, it also seems to permanently remove the `workspace:` even when it succeeds in generating the lockfile:
```diff
--- a/pkg/env/package.json
+++ b/pkg/env/package.json
@@ -19,8 +19,8 @@
     "test": "echo \"Error: no test specified\" && exit 1"
   },
   "devDependencies": {
-    "@company/config": "workspace:^4.2.0",
-    "@company/xhr": "workspace:^2.3.1",
+    "@company/config": "^4.2.0",
+    "@company/xhr": "^2.3.1",
     "@jkuebart/parseq": "^20180905.2.0",
     "axios": "^0.19.2",
     "color": "^3.1.2",
```

**Comment by zkochan** [comment]
that shouldn't happen. I am writing the old manifest after generating the lockfile:

https://github.com/pnpm/pnpm/blob/e974b7f22eb259096e521b6c9465e17f7ae80e70/packages/make-dedicated-lockfile/src/index.ts#L70

**Comment by diachedelic** [comment]
Using `link:` instead of `workspace:` solved both problems, thanks.

**Comment by aleclarson** [comment]
I noticed `make-dedicated-lockfile` is deprecated. Can I still expect it to work with the latest PNPM version? It's still a preferable solution for me (over `pnpm deploy`) as I'm using [git-subrepo](https://github.com/ingydotnet/git-subrepo) and simply want to generate a lockfile for my subrepos, using the monorepo's lockfile as the "source of truth".

**Comment by zkochan** [comment]
I think it broke with the latest pnpm but I don't know why https://github.com/pnpm/pnpm/commit/1e7349d330ea8b157054ff5a6235121ecd856f7c
