### ISSUE TITLE
issue with ApolloProvider types on monorepo

### ISSUE THREAD

**Issue by hemedani** [pnpm/pnpm#1928]
### pnpm version:
```
 [I] ➜ pnpm -v
3.6.0
```
### Code to reproduce the issue:
```javascript
ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById("root")
);
```
the actual file address on [git repo](https://github.com/hemedani/sefood-tracing-pnpm) is this : `./packages/sefood-tracing-fr/src/index.ts`

the issue is it as say typescript :
```typescript
JSX element type 'ApolloProvider<unknown>' is not a constructor function for JSX elements.
  Type 'ApolloProvider<unknown>' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2605)
```

### Expected behavior:
detect the true type for ApolloProvider
### Additional information:
I create a [github repo](https://github.com/hemedani/sefood-tracing-pnpm) to see the error in action

 - `node -v` prints: `v8.11.2`
 - Windows, OS X, or Linux?: `OS X`

**Comment by zkochan** [comment]
This is probably some bug with how pnpm creates the flat `node_modules`

**Comment by zkochan** [comment]
Create the following `pnpmfile.js` in the root of your monorepo:

```js
module.exports = {
    hooks: {
        readPackage (manifest) {
            switch (manifest.name) {
                case 'react-apollo':
                    manifest.dependencies['apollo-client'] = '^2.6.3' // taken from apollo-boost
                    manifest.peerDependencies['@types/react'] = '*'
                    break
            }
            return manifest
        }
    }
}
```

Run `rm -rf node_modules pnpm-lock.yaml && pnpm m i`. Issue solved

**Comment by hemedani** [comment]
two solution working perfectly fine. which one is better

**Comment by zkochan** [comment]
The one with pnpmfile

**Comment by zkochan** [comment]
Seems like there's a 3rd solution and we can use it for a fix in pnpm. You can create an empty `package.json` in the root of the monorepo.

**Comment by VinceOPS** [comment]
Hi @zkochan! Sorry for raising this (old) issue. I'm encountering the exact same problem with pnpm `7.14.0` and workspaces.

With both `ink-table` (using react ink), on `Table` component, and `nextjs` (`Head` component).

I tried the "solution 1" you gave [here](https://github.com/pnpm/pnpm/issues/1928#issuecomment-515708856) (using `.pnpmfile.cjs`), but I'm still having this error from `tsc`.

Did I miss anything? Ready to try something else, if it can help diagnosing the issue.

Thanks!
