### ISSUE TITLE
ngc binary fails

### ISSUE THREAD

**Issue by farfromrefug** [pnpm/pnpm#1936]
### Code to reproduce the issue:

add ```@angular/compiler-cli``` to your packages.json
add ```node --max-old-space-size=8192 ./node_modules/.bin/ngc``` as script
run the script on macos
### Expected behavior:
to work
### Actual behavior:

i get that error 
```shell
/Volumes/data/dev/nativescript/nativescript-material-components/node_modules/.bin/ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

### Additional information:
I am running this on macOS

**Comment by aparajita** [comment]
This is likely the fault of ngc, not pnpm. Many npm packages do not properly declare their dependencies. Try `npm install -g pnpm@next` and install ngc again.

**Comment by farfromrefug** [comment]
@aparajita @zkochan actually found the reason of the issue. It is because i do ```node --max-old-space-size=8192 ./node_modules/.bin/ngc``` and not ```./node_modules/.bin/ngc```
```node``` does not now that ```ngc``` is actually a shell script. 
maybe pnpm should not create shell script but javascript scripts instead?

This is kind of a big issue cause i need to set ```max-old-space-size```

**Comment by zkochan** [comment]
Sorry, we need the shell scripts currently.

But in thise case you can access the bin file in the package's directory:

```
node --max-old-space-size=8192 ./node_modules/@angular/compiler-cli/src/main.js
```
