### ISSUE TITLE
"shamefully-flatten" is long and not intuitive, consider "flatten" instead

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1938]
## Why not `shamefully-flatten`?

* It is long. I also find typing "shamefully" hard (no muscle memory).
* It is not intuitive: You cannot expect a user just to think of the word "shamefully" when they want it to be "flatten".
* Warning message is enough to discourage user from using it everywhere, "shamefully" is unnecessary.

## Why `flatten`?

* It is reasonably short. I also find typing "flatten" way easier (as it is a more frequent word than "shamefully").
* It is intuitive. User may think of `flatten` immediately if they want a flat tree.

## Suggestion

* Make `flatten` official option.
* Make `shamefully-flatten` an alias (that is going to be deprecated and removed in later versions).

**Comment by zkochan** [comment]
ok

I also thinking about allowing to flatten by pattern. Flattening is mostly needed to fix some broken tooling, so something like `flatten-pattern=eslint-*` should be enough.

**Comment by zkochan** [comment]
`hoist=<pattern>` might be a better config name as flatten has a different meaning in yarn/bower.

cc @shellscape

**Comment by KSXGitHub** [comment]
Hoisting maybe useful for many people but not for me particularly because I prefer to restrict flatten node_modules in a monorepo.
