### ISSUE TITLE
Regression in 3.6, husky postinstall not run

### ISSUE THREAD

**Issue by jvanbruegge** [pnpm/pnpm#1942]
### Code to reproduce the issue:
`pnpm install -D husky@latest`

### Expected behavior:
```
node_modules/.registry.npmjs.org/husky/3.0.2/node_modules/husky: Running install script, done in 150ms
node_modules/.registry.npmjs.org/husky/3.0.2/node_modules/husky: Running postinstall script, done in 72ms
```

### Actual behavior:
Nothing

### Additional information:
This works fine with pnpm 3.5.3

 - `node -v` prints: 11.15.0
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
Seems to work on my machine.

Do you mean the second run? When husky is already in node_modules? Currently, if husky is already installed, the scripts are not rerun

**Comment by jvanbruegge** [comment]
No, when I go to my cloned cyclejs repo, run `pnpm install && pnpm recursive install` husky is not set up

**Comment by zkochan** [comment]
Seems like the regression was introduced in v3.5.5 but I don't know what is going on yet

**Comment by zkochan** [comment]
So this was the commit that caused the regression: https://github.com/pnpm/pnpm/commit/47a9d064f855a8e28852af5ed137016108ff11e6

why don't you use just `pnpm recursive install` instead of `pnpm install && pnpm recursive install`? Also, if you set `use-beta-cli=true`, you may just use `pnpm install`

**Comment by zkochan** [comment]
:ship: 3.6.3
