### ISSUE TITLE
Use snapshot testing when applicable

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1947]
In some parts of pnpm, snapshot tests would work great. For instance, for testing lockfiles or the outputs of reporters.

***

Seems like switching to jest is the best option but [I tried](https://github.com/pnpm/pnpm/pull/1955) and it didn't work out

**Comment by KSXGitHub** [comment]
[Why don't use try snapshot for tape instead?](https://github.com/cdlewis/snapshotter)
