### ISSUE TITLE
eslint unable to find deep configs when installed with pnpm

### ISSUE THREAD

**Issue by kyeotic** [pnpm/pnpm#1951]
When using a shared eslint config that itself depends on another shared eslint config eslint fails. This works with npm, but when installed with npm I get the following error

```
Error: Cannot find module 'eslint-config-prettier'
```

(full stack trace below)

This is similar to #1602 and possiby caused by the same root issue, but I am opening a seperate one because it is not related to plugins.

The package in question is `@kyeotic/eslint-config`, which I am the maintainer of. I am willing to make whatever changes necessary to it to get this working with pnpm, as long as it continues to work with npm.

### Code to reproduce the issue:

1. install `@kyeotic/eslint-config`, set config with

2. update `package.json` 
```
"eslintConfig": {
    "extends": [
      "@kyeotic/eslint-config"
    ]
  }
```
3. run `eslint -c package.json \"{src,test}/**/*.js\"`

### Expected behavior:

eslint runs

### Actual behavior:

```
Error: Cannot find module 'eslint-config-prettier'
Referenced from: /Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/@kyeotic/eslint-config/0.9.0_eslint@5.16.0/node_modules/@kyeotic/eslint-config/index.js
Referenced from: /Users/kyeotic/dev/raviger/package.json
    at ModuleResolver.resolve (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:579:26)
    at configExtends.reduceRight (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:551:22)
    at load (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:587:20)
    at configExtends.reduceRight (/Users/kyeotic/dev/raviger/node_modules/.registry.npmjs.org/eslint/5.16.0/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
```

### Additional information:
Mac OS X
```
node -v
v10.16.1
```

Even if I install the transitive dependencies `eslint-config-prettier` and `eslint-config-recommended`, it just fails on the next level down with `eslint-config-esnext` (a dependency of `eslint-config-recommended`). I might be able to play whack-a-mole with deep dependencies to eventually resolve this, but it shouldn't be necessary.

**Comment by zkochan** [comment]
I am getting a different error (pnpm v3.7 used): ESLint couldn't find the plugin "eslint-plugin-import".

So seems like the plugin resolver issue.

Try setting the `shamefully-flatten=true` config in `.npmrc` in the root of your project. Unfortunately, only this fixes eslint

**Comment by kyeotic** [comment]
@zkochan In the root of `@kyeotic/eslint-config` or the project that depends on it?

**Comment by zkochan** [comment]
on the project that depends on it

**Comment by kyeotic** [comment]
I don't think that's a good solution; I would have to do that in every project that uses `@kyeotic/eslint-config`, and communicate to anyone else using the project that they must do the same. I think either pnpm should handle this correctly, or I should be able to apply to the solution to `@kyeotic/eslint-config` so that its dependants dont need to do anything special.

**Comment by kyeotic** [comment]
@zkochan This is getting too painful. I am going to have to stop using pnpm until this works.

**Comment by kaidjohnson** [comment]
It seems that eslint uses `module.paths` under the hood to determine possible relative paths to resolve eslint configs. `module.paths` appears to get generated based on the directory the file lives in, which is then traversed up to root, appending `node_modules` all the way up. However, pnpm doesn't install dependencies directly to `node_modules`, it installs them to `node_modules/.registry.address.here`.

It's likely eslint could/should update to use something more along the lines of `require.resolve`, which appears to work more consistently with pnpm's philosophy. It's not exactly clear to me why `require.resolve` works so well with pnpm but tapping the internal `module.paths` would not.
 
That said, the use of `module.paths` is tapping node for its resolution strategy, so it's likely this is an issue that could/should be solved by pnpm. I could see `node_modules/.registry.address.here/node_modules` symlinking back to `node_modules/.registry.address.here`, as to avoid a fundamental structural change, while still providing the expected `node_modules` folder from which the resolver paths could match against.

**Comment by zkochan** [comment]
Regarding `module.paths`. As far as I remember, we have this workaround for pluggable CLI tools like eslint, we set the NODE_PATH env variable so that they search for plugins in the right places

https://github.com/pnpm/cmd-shim/blob/2785213014a7dc42e91934543104e030945916e2/src/index.ts#L51

This workaround works only when you call the eslint CLI, not the eslint programmatic API.

***

I am not an expert in eslint but I think it is possible to make it work. standard also uses eslint with some plugins under the hood, and it works fine with pnpm.

**Comment by ExE-Boss** [comment]
If https://github.com/eslint/rfcs/pull/14 gets approved and implemented, this might get solved for us.

**Comment by zkochan** [comment]
This is going to be fixed in v4.
You can try the first beta [4.0.0-0](https://github.com/pnpm/pnpm/releases/tag/v4.0.0-0)

**Comment by KyorCode** [comment]
I am still having issues with this and I am on 4.3.0 at the moment.

Calling the ESLint CLI does work in this version, but plugins like vscode-eslint fail to do so. Still due to the weirdness of the resolve in EsLint I assume.

If you look at lerna, they have an import-resolver for eslint ( https://github.com/Dreamscapes/eslint-import-resolver-lerna). Is this an option?

**Comment by kelly-tock** [comment]
i'm on pnpm 7, and eslint 8. 

it is trying to load the plugin from my app's root, and not resolving to the shareable configs node modules as an option at all. I know this is an old issue, but it seems to be the only one that matches what i'm seeing.

**Comment by kelly-tock** [comment]
i'll try reopening an issue after getting some thumbs up here.....
