### ISSUE TITLE
"pnpm run cmd -- --help" should pass "--help" to "cmd"

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1956]
### pnpm version:

3.6.5

### Code to reproduce the issue:

**Step 1:** Clone https://github.com/KSXGitHub/pnpm-issue-3.git

**Step 2:**

```sh
pnpm run cmd -- --help
```

### Expected behavior:

It prints `ok` (from the script)

### Actual behavior:

It prints help message from `pnpm`

### Workaround:

Use `npm`

```sh
npm run cmd -- --help
```

or `yarn`

```sh
yarn cmd --help
```

**Comment by zkochan** [comment]
:ship: 3.7.0
