### ISSUE TITLE
"pnpm run <interactive script>" does not show text cursor (caret)

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1961]
### Code to reproduce the issue:

Clone https://github.com/KSXGitHub/pnpm-issue-4.git and run the following commands:

```sh
pnpm run node
```

```sh
pnpm run bash
```

### Expected behavior:

Text cursor appears

### Actual behavior:

Text cursor does not appear

### Workaround:

Use `npm`

### Additional information:

The terminal emulator I use is [Tilix](https://github.com/gnunn1/tilix.git).

**Comment by zkochan** [comment]
I guess it would be fine to show the cursor at all times

**Comment by KSXGitHub** [comment]
@zkochan I think it's about how `pnpm`/`npm` call the commands. `pnpx node` suprisingly works fine.

Also, if I use `node` to execute the following script, it shows cursor as well:

```javascript
#! /usr/bin/env node
require('child_process').execSync('bash', { stdio: 'inherit' })
```

**Comment by zkochan** [comment]
pnpm hides the cursor

https://github.com/pnpm/pnpm/blob/2e189f54ef38b9934bea28f1748d08fb18b2dd34/packages/default-reporter/src/index.ts#L42

**Comment by KSXGitHub** [comment]
@zkochan I am not familiar with pnpm's internal working. Is there any particular reason why pnpm must forcefully hide the cursor instead of letting it appears/disappears as it pleases?

**Comment by zkochan** [comment]
The only reason is to reduce visual noise

**Comment by KSXGitHub** [comment]
@zkochan What about introducing a configuration option that decides when to hide cursor? For example: Field `interactive-scripts` in `.npmrc`/`.pnpmrc` that let pnpm knows which script (from `"scripts"` of `package.json`) requires user interaction.

But if you decide that the feature is not worth increasing code's complexity then always showing cursor is fine for me.

**Comment by zkochan** [comment]
I don't feel strongly about the cursor, so I am fine just always showing it.

**Comment by zkochan** [comment]
:ship: 3.7.1
