### ISSUE TITLE
`pnpm add` should require the `<pkg>` argument

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#1970]
### pnpm version:
3.7.4

### Code to reproduce the issue:
```
pnpm add
```

### Expected behavior:
An error is printed to the console, like with `yarn add`, which was also suggested in #864:
```
> yarn add
yarn add v1.17.3
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Actual behavior:
`pnpm add` is just a simple alias for `pnpm install` without a check if the `<pkg>` argument is supplied.

### Additional information:
 - `node -v` prints: v12.8.0

**Comment by zkochan** [comment]
:ship: 3.8.0-0

**Comment by ExE-Boss** [comment]
You should add this to the release notes: https://github.com/pnpm/pnpm/releases/tag/v3.8.0, like you did with https://github.com/pnpm/pnpm/releases/tag/v3.6.0.

**Comment by ExE-Boss** [comment]
@zkochan Will this become the default behaviour in **pnpm v4.0**?
https://github.com/pnpm/pnpm/milestone/4

**Comment by zkochan** [comment]
of course

**Comment by zkochan** [comment]
Should `pnpm install foo` fail like `yarn install foo` does?

**Comment by ExE-Boss** [comment]
Probably not, given `pnpm` is meant to be a mostly direct and CLI compatible replacement of `npm`.

The issue I had with `pnpm add` behaving like `pnpm install` is that it just doesn't make sense, whereas `pnpm install foo` makes sense and keeps `npm` compatibility.

---

Same with requiring `pnpm run customscript` over just `pnpm customscript`, like what `yarn` allows, since the latter can lead to CLI conflicts if `pnpm` were to ever add a `pnpm customscript` command.
