### ISSUE TITLE
Request: Create a GitHub actions that setups pnpm and installs dependencies using pnpm

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1972]
[GitHub actions](https://help.github.com/en/articles/about-github-actions) is now available for public beta. I have tried it in some of my monorepos and noticed it being significantly faster.

Now, it would be nice if I can simply add `uses: pnpm/github-actions-setup@v1` (or something) to my `.github/workflows/nodejs.yml` to setup pnpm for my Node CI.

**Comment by shellscape** [comment]
This would be great. At present trying to use this with Github Actions' windows container is failing hard on what looks like to be an issue with how Github is terminating a process. See the following build for details: https://github.com/rollup/plugins/commit/265f3f8d931fda024ac85e56538f1cef0b19afd8/checks

**Comment by jbergstroem** [comment]
I would love to see `pnpm` find its way to github actions os images. Not sure how to argue for it though (other than saying pretty please).

**Comment by zkochan** [comment]
I am so tired of the buggy Travis and Appveyor. Could someone configure GitHub actions for the pnpm monorepo?

or CircleCI, or Azure Pipelines I guess

**Comment by shellscape** [comment]
@zkochan we have it working for both CircleCI and Github actions on the rollup/plugins repo. You can reference those configs, or I can carve out some time next week to open a PR here.

**Comment by zkochan** [comment]
I don't think I will look into it soon. I have spent a lot of time trying to make Travis or Appveyor work to test Windows. No success. So I am demotivated.

**Comment by KSXGitHub** [comment]
I have created a GitHub Action here: https://github.com/KSXGitHub/github-actions-setup-pnpm

I wish pnpm team to officially support it by cloning it to pnpm/action-setup, what do you think @zkochan?

I can also make a PR to this very repo (pnpm/pnpm) to set up GitHub Action workflow.

**Comment by zkochan** [comment]
@KSXGitHub you can transfer your repository to the pnpm org.

Does it also run on Windows? If yes, a PR would be great because AppVeyor is currently broken.

**Comment by KSXGitHub** [comment]
@zkochan 

> Does it also run on Windows?

I did not use any platform dependent code so I guess it does. Anyway, I will add a test just to be safe.

**Comment by KSXGitHub** [comment]
@zkochan Done: https://github.com/pnpm/action-setup

It still sometimes fails on Windows with `Error [ERR_STREAM_WRITE_AFTER_END]: write after end`. I suspect this is a [self-installer](https://github.com/pnpm/self-installer) error because it printed `Downloading https://registry.npmjs.org/pnpm/-/pnpm-4.11.1.tgz` before displaying the error.

Perhaps I should not rely on self-installer and download pnpm directly instead?

**Comment by zkochan** [comment]
maybe use npm to install pnpm. That should be reliable

**Comment by KSXGitHub** [comment]
> maybe use npm to install pnpm. That should be reliable

This is not only slow, but also make things more complicated. I will try to find other solution first.

**Comment by zkochan** [comment]
isn't npm preinstalled with Node? I don't think it will be slow because pnpm consists only of a single bundled package.

**Comment by KSXGitHub** [comment]
> isn't npm preinstalled with Node?

Not the case with GitHub Actions. I must use `@zeit/ncc` to bundle all dependencies into self-contained script.

**Comment by zkochan** [comment]
maybe self-installer could be fixed

**Comment by shellscape** [comment]
Here's our github action which works well for Windows https://github.com/rollup/plugins/blob/master/.github/workflows/node-windows.yml

I've been trying to find time to get this submitted but it's been a crazy week

**Comment by KSXGitHub** [comment]
@shellscape Your workflow just npm. It is simple for a workflow, but not for a reusable action.

The best I can hope right now is having self-installer fixed.

**Comment by mcmxcdev** [comment]
Can this issue be closed? 

https://github.com/pnpm/action-setup is stable and works really well.
