### ISSUE TITLE
Node v12.9 - MaxListenersExceededWarning

### ISSUE THREAD

**Issue by aparajita** [pnpm/pnpm#1975]
### pnpm version:
3.7.5

### Code to reproduce the issue:
pnpm i -g <anything that requires a download>

### Expected behavior:
No warnings.

### Actual behavior:
When using Node v12.9, I get a ton of these warnings:

`(node:66282) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit`

### Additional information:

 - `node -v` prints: v12.9.0
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
I think this a node js bug
https://github.com/nodejs/node/issues/29239

**Comment by ExE-Boss** [comment]
nodejs/node#29239 has been resolved.
