### ISSUE TITLE
can't down load with cnpm registry

### ISSUE THREAD

**Issue by Akimotorakiyu** [pnpm/pnpm#1977]
### Code to reproduce the issue:
```bash
npm config set registry https://registry.npm.taobao.org

pnpm i 
```

### Expected behavior:
normal, works like npm & yarn .
### Actual behavior:
![图片](https://user-images.githubusercontent.com/31165554/63571193-1b09fa00-c5b2-11e9-974b-7dd7596596a6.png)

### Additional information:

 - `node -v` prints: 12.9
 - Windows, OS X, or Linux?:windows

**Comment by SilverLeaves** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1499

**Comment by KylinLee** [comment]
yes, when I use `pnpm` and set the npm config registry as `https://registry.npm.taobao.org/`, it download slowly and always failed to download. But when I use `npm`, it faster than use `pnpm`. It seems like a problem with pnpm.
