### ISSUE TITLE
Unexpected Behavior with pnpm VS yarn & npm

### ISSUE THREAD

**Issue by armenr** [pnpm/pnpm#1979]
In my repo, I have a package.json file, and a server.js.
With yarn, I can install my packages and run the server without issue. 

## Behavior 1: 

Install packages w/ pnpm and run `pnpm run start`:
```
vagrant@572d5bee72f6:/opt/myproj/src/packages/myproj-proxy$ pnpm run start

> @myproj-monorepo/myproj-proxy@0.0.1 start /opt/myproj/src/packages/myproj-proxy
> NODE_ENV=production node --require 'dotenv/config' server.js | pino-syslog

/opt/myproj/src/packages/myproj-proxy/node_modules/.registry.npmjs.org/index-of-x/2.3.0/node_modules/index-of-x/index.js:27
  var res = attempt.call([0, 1], pIndexOf, 1, 2);
                    ^

TypeError: attempt.call is not a function
    at Object.<anonymous> (/opt/myproj/src/packages/myproj-proxy/node_modules/.registry.npmjs.org/index-of-x/2.3.0/node_modules/index-of-x/index.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/myproj/src/packages/myproj-proxy/node_modules/.registry.npmjs.org/inspect-x/1.9.1/node_modules/inspect-x/index.js:51:15)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
```

## Behavior 2:
Install packages with `npm i` and then `npm run start` ==> Works

## Behavior 3:
Install packages with yarn and then run `pnpm run start` ==> Works

## Behavior 4:
Install packages with npm and then run `pnpm run start` ==> Works

## Behavior 5:
Install packages with `pnpm install --shamefully-flatten -f` and then `pnpm run start` ==> Fails again. Same is  true if I add `iterall` to my dependencies, as mentioned in the pnpm FAQs.

```
vagrant@572d5bee72f6:/opt/myproj/src/packages/myproj-proxy$ pnpm run start

> @myproj-monorepo/myproj-proxy@0.0.1 start /opt/myproj/src/packages/myproj-proxy
> NODE_ENV=production node --require 'dotenv/config' server.js | pino-syslog

/opt/myproj/src/packages/myproj-proxy/node_modules/.registry.npmjs.org/index-of-x/2.3.0/node_modules/index-of-x/index.js:27
  var res = attempt.call([0, 1], pIndexOf, 1, 2);
                    ^

TypeError: attempt.call is not a function
    at Object.<anonymous> (/opt/myproj/src/packages/myproj-proxy/node_modules/.registry.npmjs.org/index-of-x/2.3.0/node_modules/index-of-x/index.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/myproj/src/packages/myproj-proxy/node_modules/.registry.npmjs.org/inspect-x/1.9.1/node_modules/inspect-x/index.js:51:15)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
```

## Findings:
So, I got a little curious. I decided to compare installed modules by packager

### Comparing Diffs Round 1 - YARN VS PNPM 
 

-  I did a CLEAN yarn install in that directory, then listed out all the modules installed in node_modules to a file yarn_node_mods_proxy.txt

- I removed the node_modules and did a clean install of the modules in there with pnpm  shamefully-flatten to a file  pnpm_node_mods_proxy.txt

These are the results:
```
colordiff pnpm_node_mods_proxy.txt yarn_node_mods_proxy.txt
13d12
< ansi-regex
194d192
< fsevents
359d356
< nan
527d523
< strip-ansi
598d593
< yallist
```

### Comparing Diffs Round 2 - NPM VS PNPM 
 

-  I did a CLEAN npm install in that directory, then listed out all the modules installed in node_modules to a file npm_node_mods_proxy.txt

- I removed the node_modules and re-did a clean install of the modules in there with pnpm  shamefully-flatten to a new pnpm_node_mods_proxy.txt file.

These are the results:
```
colordiff pnpm_node_mods_proxy.txt npm_node_mods_proxy.txt
194d193
< fsevents
359d357
< nan
```

### Comparing Diffs Round 3 - NPM VS YARN

I compared the NPM and YARN outputs from the previous set to each other.

These are the results:
```
colordiff npm_node_mods_proxy.txt yarn_node_mods_proxy2.txt
13d12
< ansi-regex
525d523
< strip-ansi
596d593
< yallist
``` 

## Summary:

I have attempted to install all unique differences in the node_modules `ls` output in an attempt to reconcile those and see if pnpm would be happy, but it hasn't worked.

ANYONE'S help would be appreciated...as I'd just convinced the team to migrate away from Yarn to PNPM, and now it looks like I'll be having to revert our codebase and our toolchain back again...

Thank you!

**Comment by zkochan** [comment]
can you create a repo that reproduces this issue?

**Comment by armenr** [comment]
Roger that. I'll do both and get back! Thank you

**Comment by armenr** [comment]
https://github.com/armenr/test-pnpm

@zkochan - as requested. I was able to get `--shamefully-flatten` to work, but only after I removed some dependencies that were in that repo that we weren't using, and minor-version bumped a few other packages to their latest...but I'm not sure why that should matter much.

**Comment by zkochan** [comment]
So `index-of-x` calls `attempt-x` but it doesn't have `index-of` in dependencies, so it fails.

I created this `pnpmfile.js` in the root of your repo and executed `pnpm up --depth 999`:

```js
module.exports = {
    hooks: {
        readPackage (pkg) {
            switch (pkg.name) {
                case 'index-of-x':
                    pkg.dependencies['attempt-x'] = '^1.1.3'
            }
            return pkg
        }
    }
}
```

I did not use the `--shamefully-flatten` flag. After this fix, `pnpm start` worked.

**Comment by armenr** [comment]
Thank you @zkochan - Just learning pnpm currently, so I apologize if this was an amateur mistake.

If I was running this in a monorepo where I do recursive installs, where should I include this hook?

Separately in my individual packages/name-of-api folder? In the package.json of that folder? Or in the root of my project as a separate file, or in the package.json of the root folder? :)

Thanks again!

**Comment by zkochan** [comment]
Place this file in the monorepo root. In the same directory where `pnpm-workspace.yaml` is placed.

**Comment by armenr** [comment]
Would you mind walking me through the diagnostic steps you took, command by command, to get an insight into how you debugged that...in case I run into something like this again in the future? 

Thank you!

**Comment by armenr** [comment]
I figured it out. Nevermind. 

Thank you for all of your prompt and kind help :) 

You think maybe this would be a useful walkthrough/FAQ/blog item to post on?

I'm gonna go ahead and close this out.

**Comment by zkochan** [comment]
Sure. If this is not documented yet, it should be
