### ISSUE TITLE
The output of pnpm outdated becomes unreadable in narrow windows

### ISSUE THREAD

**Issue by nikoladev** [pnpm/pnpm#1984]
## Problem

Currently the output of `pnpm outdated` looks great if the terminal window is wide:

<img width="1071" alt="Results from pnpm outdated when the terminal window is wide enough" src="https://user-images.githubusercontent.com/15011519/63846398-0354bc00-c98c-11e9-99d8-a49dd3c83cad.png">

But if the terminal window is narrow it becomes almost impossible to decipher:

<img width="539" alt="Results from pnpm outdated when the terminal window is too narrow" src="https://user-images.githubusercontent.com/15011519/63846435-18c9e600-c98c-11e9-9b47-0f397b6121ac.png">

## Proposed solution

There's really not an easy way to make the output very readable on narrow screens, but by removing the table and cell borders from the output we can at least reduce the noise.

For example, this is what the output of `yarn outdated` looks like in a wide terminal window:

<img width="1070" alt="Results from yarn outdated when the terminal window is wide enough" src="https://user-images.githubusercontent.com/15011519/63846762-b9200a80-c98c-11e9-8d70-de719feca294.png">

And this is what it looks like on a narrow terminal window:

<img width="536" alt="Results from yarn outdated when the terminal window is too narrow" src="https://user-images.githubusercontent.com/15011519/63846739-ab6a8500-c98c-11e9-99ba-e6aea72ba0db.png">

The output is still not the best on narrow windows, but at least there aren't any misplaced lines all over the place.

Adding an empty line after each dependency could improve readability on narrow screens. So instead of having to guess what information belongs to which package:

```
react-pdf-js        3.0.4         3.0.8         5.1.0  dependencies    http
s://github.com/mikecousins/react-pdf-js.git    
react-scripts       1.1.1         1.1.1         3.1.1  dependencies    http
s://github.com/facebook/create-react-app#readme
source-map-explorer 1.5.0         1.5.0         2.0.1  devDependencies http
s://github.com/danvk/source-map-explorer#readme
standard            10.0.3        10.0.3        14.0.2 devDependencies http
s://standardjs.com                             
```

We can get see by the spacing which information belongs together:

```
react-pdf-js        3.0.4         3.0.8         5.1.0  dependencies    http
s://github.com/mikecousins/react-pdf-js.git    

react-scripts       1.1.1         1.1.1         3.1.1  dependencies    http
s://github.com/facebook/create-react-app#readme

source-map-explorer 1.5.0         1.5.0         2.0.1  devDependencies http
s://github.com/danvk/source-map-explorer#readme

standard            10.0.3        10.0.3        14.0.2 devDependencies http
s://standardjs.com                             
```

**Comment by zkochan** [comment]
I would like to keep the borders because on big monorepos, there can be hundreds of outdated deps and there's a column called `Dependents`, when you run `pnpm recursive outdated`. The dependents column can contain lots of package names and [table](https://dev.to/aryanjnyc/ken-wheeler-and-dan-abramov-deactivate-their-twitter-accounts-302)'s word wrap + borders make it readable.

However, I understand that this needs to be more readable on small screens. The reason the details column is so wide by default is that table has no maxWidth propery, so I had to use the width prop. But I'll make a workaround to reduce the width of `Details`

**Comment by nikoladev** [comment]
Sorry to hear that it's a tricky situation.

> I can also remove the borders between rows if the console has less than X width

This seems like a good idea!

Don't know how much extra work this will be (and what priority it should get) but: is it maybe possible to make 2 versions of the output? Kind of like how websites have desktop and mobile versions.

The wide "desktop" would be for all the heavy lifting and the "mobile" version would be for quick checks and would only have minimal information.

If it's possible (and desired), then I'd like to take a try at the "mobile" version in the near future.

**Comment by zkochan** [comment]
npm has two versions of the output command.

`npm outdated` does not print the URLs of packages
`npm outdated --long` prints it.

What is your idea of the "mobile" version?

**Comment by nikoladev** [comment]
> npm has two versions of the output command

Interesting. Then maybe instead of having the mobile and desktop versions depend on the width of the window they can depend on the arguments? Something like `pnpm outdated --simple`?

> What is your idea of the "mobile" version?

Something like the following:

```
Package               Current  Latest   Details
--------------------  -------  -------  --------------------
really-long-package-  1.2.3    1.3.0    https://github.com/p
name                                    npm/pnpm

@another/package-wit  1.10.0-  1.10.0   https://github.com/p
h-a-long-name         beta0             npm/benchmarks-of-ja
                                        vascript-package-man
                                        agers

short-name            0.20.7   1.0.0    https://github.com/n
                                        pm/cli

also-short            16.8.0   16.9.0   https://reactjs.org
```

- I've chosen a width of 60 characters (`20 + 2 + 7 + 2 + 7 + 2 + 20`) as that seems like a narrow enough view to go for. Less than that and it gets hard to print anything useful
- All the columns would be word wrapped
  - Don't know if this affects the URLs. As in, will they still work?
- This view omits all other info (like if a package is a dev dependency)

Another possibility which is more vertical and is more independent of the width:

```
really-long-package-name
1.2.3 -> 1.3.0
https://github.com/pnpm/pnpm

@another/package-with-a-long-name
1.10.0-beta0 -> 1.10.0
https://github.com/pnpm/benchmarks-of-ja     # simulating a soft wrap caused by
vascript-package-managers                    # a narrow window

short-name
0.20.7 -> 1.0.0
https://github.com/npm/cli

also-short
16.8.0 -> 16.9.0
https://reactjs.org
```

- We can selectively use bolding and colors to make it more readable, but I can't do that here in a comment.
- Even more information could fit here if needed/wanted as there is basically infinite vertical space.

I have no experience with `recursive`, so I can't say if these ideas are useful at all in that situation.

**Comment by zkochan** [comment]
I would vote for the second solution. So the table would be used on screens with at least 80 width, for instance. The vertical output would be used on <80 or with a `--no-table` flag, for instance.

**Comment by zkochan** [comment]
Or it can be something like this

![image](https://user-images.githubusercontent.com/1927579/63886648-a8e74a00-c9e3-11e9-8c33-b874e0078307.png)

**Comment by nikoladev** [comment]
> I would vote for the second solution

I agree, I like it better as well. And the `--no-table` flag is also very clear

> Or it can be something like this

How would this handle very long URLs? We'd have to hard wrap it, right? Would the URLs still work?

Also, the resizing the window to be smaller _after_ `pnpm outdated` is run will mess up the layout again. With the purely vertical method the text can just reflow:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/15011519/63932174-fa7cec80-ca56-11e9-8e3a-cfe655863c44.png">

<img width="210" alt="image" src="https://user-images.githubusercontent.com/15011519/63932209-0a94cc00-ca57-11e9-8232-95f2f9c2f32d.png">

What I also like about this option is that it is not just a narrower table, it's a fundamentally different output.

**Comment by 5310** [comment]
The recent(?) change to the `outdated` output broke my globally installed package update script and I just realized that this morning. I've already updated it to the table format, but I too would prefer something less noisy, or at least a flag to not print the table.

**Comment by zkochan** [comment]
I don't have objections to having this flag.

**Comment by nikoladev** [comment]
I might have some time in the next couple of weeks to tackle this. Though if anyone else feels like taking a go at this before I can, please feel free to do so!

**Comment by aparajita** [comment]
This was addressed by https://github.com/pnpm/pnpm/commit/85faad51388de3fe22445c28385e5a82d458584d.

In the next release, by default the Details column will not be displayed, so you shouldn't have any problems with narrow terminals.

**Comment by aparajita** [comment]
@zkochan I think this one can be closed.

**Comment by ExE-Boss** [comment]
I would still like to also implement `‑‑no‑table`.

**Comment by KSXGitHub** [comment]
How about a `--json` flag that allows us to pipe the result to whatever formatter we want.

**Comment by aparajita** [comment]
@ExE-Boss You mean you would like to see it or you will implement it?

**Comment by aparajita** [comment]
@ExE-Boss I already have `--no-table` mostly working.

**Comment by aparajita** [comment]
https://github.com/pnpm/pnpm/pull/2026
