### ISSUE TITLE
`pnpm i` with a new node version does not rebuild?

### ISSUE THREAD

**Issue by wmertens** [pnpm/pnpm#1992]
I use pnpm everywhere so it's a bit hard to come up with the exact circumstances, but what I think happens is that I first run `pnpm i` on some node version, then upgrade node to one with a new binary version, and then `pnpm i` does not rebuild the packages for the new node version.

Is this possible, or is this due to an old bug that hits old repositories?

**Comment by zkochan** [comment]
See the related issue: #1394

**Comment by wmertens** [comment]
Right, that should cover it
