### ISSUE TITLE
Suggestion: Enable --frozen-lockfile by default on CI environment

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1994]
## Why?

Sometimes user edit dependencies section of `package.json` and forgot to commit lock files into git, causing CI to update its version of the lock files, effectively render lock files useless.

## Suggestion

When environment variable `CI=true` exists, enable `--frozen-lockfile`.

## Additional Suggestion

Make `--ci` an alias of `--frozen-lockfile`.

_(This idea is inspired by `jest --ci`: Test fails when it tries to create new snapshot on CI context)_

---

Also, [rushjs](https://rushjs.io/pages/developer/everyday_commands/) has its `install` command fails when lock file is not updated:

> You will notice that automated CI jobs use `rush install` instead of `rush update`. The difference is that `rush install` won’t update any files. Instead, it will fail your PR build if something is out of date, to let you know that you forgot to run `rush update` or forgot to commit the result. (Some people choose to use `rush install` as their everyday command, in order to catch unintended changes to the shrinkwrap file.)

**Comment by KSXGitHub** [comment]
Also, if `--frozen-lockfile` is enabled by default, I would like an option to ignore lock file error even on CI environment (such as `--ignore-lockfile-error`) and a command to test lock file only (such as `pnpm test-lockfile`): This is useful in situation where I want CI to run other unit tests despise lock file being mismatches.

**Comment by KSXGitHub** [comment]
@zkochan `npm` has a `ci` command. I think you should add `pnpm ci` as well.

**Comment by zkochan** [comment]
I don't know, I think I like the flag idea more. `pnpm install --ci`

Or even `pnpm --ci`. I think making `pnpm` =  `pnpm install` would be a good idea.

**Comment by KSXGitHub** [comment]
I am not suggesting `pnpm ci` as a replacement of `pnpm install --ci`. I was suggesting that `pnpm` should support command that `npm` supports so that it would be a little easier for `npm` users to switch to `pnpm`.

**Comment by thynson** [comment]
One thing I wish to have is to add an option, e.g. `--only-lockfile`, to allow installing packages without package.json. So Dockerfile for node project can be written like:
```Dockerfile
ADD pnpm-lock.yaml ./
RUN pnpm install --ci --only-from-lockfile # Or any other command
ADD package.json ./
RUN pnpm test-lockfile # Need to verify the lockfile is correct
```
instead of the current popular pattern:
```Dockerfile
ADD package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
ADD . ./
```
The new Dockerfile pattern will allow `pnpm install --ci --only-from-lockfile` layer be reused even when package.json is modified, as long as lockfile is not modified, e.g. version bump.

**Comment by zkochan** [comment]
@thynson I think we can support that even w/o a flag. Please create a separate issue for it.

**Comment by zkochan** [comment]
I included this to the 4.10 roadmap.

Some additional things that `pnpm ci` will have to do:
1. the behavior of `pnpm install --force` be applied in many cases. For instance, if the store location changed, installation should not fail, just recreate `node_modules`.
2. if the available node_modules directory was installed by a different version of pnpm, remove it and install from scratch (might make sense to always remove it)

**Comment by zkochan** [comment]
This is partially done in v4.10.0-3. If `pnpm install` is running in a CI environment and a lockfile is present, then `frozen-lockfile` is used.

**Comment by zkochan** [comment]
Published an update in [v4.11.4](https://github.com/pnpm/pnpm/releases/tag/v4.11.4). If someone doesn't want the build to fail in a CI environment when a lockfile is out-of-date, set the `frozen-lockfile` setting to `false`.

**Comment by sachinjoseph** [comment]
@zkochan In CIs, to enable lockfile updates, `--frozen-lockfile=false` works but not `--no-prefer-frozen-lockfile`. There's some confusion around the various lockfile flags - maybe these could be streamlined?

**Comment by zkochan** [comment]
I guess, `--no-prefer-frozen-lockfile` could work as well.

**Comment by zkochan** [comment]
`--no-prefer-frozen-lockfile` works in `v4.12.5`
