### ISSUE TITLE
Issue with module or pnpm?

### ISSUE THREAD

**Issue by IanKemp** [pnpm/pnpm#2001]
One of our explicit dependencies in `package.json` is `@material/react-dialog` which depends on `@material/dialog` which depends on `@material/animation`. However the `@material` modules' SASS files include files using a semi-absolute path, e.g.:

`@import "@material/animation/functions";`

which when used with pnpm causes:

```
./src/App.scss (./node_modules/.registry.npmjs.org/css-loader/2.1.1_webpack@4.39.1/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/.registry.npmjs.org/postcss-loader/3.0.0/node_modules/postcss-loader/src??postcss!./node_modules/.registry.npmjs.org/resolve-url-loader/3.1.0/node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/.registry.npmjs.org/sass-loader/7.2.0_webpack@4.39.1/node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/App.scss)
undefined
^
      File to import not found or unreadable: @material/animation/functions.
      in C:\path\to\my\project\node_modules\.registry.npmjs.org\@material\dialog\2.3.0\node_modules\@material\dialog\_mixins.scss (line 23, column 1)
```

This can be fixed by changing the imports to be

`@import "../animation/functions";`

but obviously I don't want to make this change.

`@material` works fine when I use `--shamefully-flatten`, but obviously that defeats the purpose of using pnpm.

* Is this an issue with `@material`, or pnpm?
* If `@material`, what would need to be changed/fixed to make it work correctly with pnpm?
* If pnpm is at fault, is this a known issue or a new bug?

**Comment by zkochan** [comment]
Try with pnpm [v4.0.0-0](https://github.com/pnpm/pnpm/releases/tag/v4.0.0-0)

**Comment by IanKemp** [comment]
> Try with pnpm [v4.0.0-0](https://github.com/pnpm/pnpm/releases/tag/v4.0.0-0)

Issue remains.

**Comment by zkochan** [comment]
Can you create a small repository that reproduces this issue?

**Comment by merceyz** [comment]
Probably fixed with https://github.com/webpack-contrib/sass-loader/pull/875

**Comment by zkochan** [comment]
This was/is not an issue with pnpm if it works with `--shamefully-hoist`
