### ISSUE TITLE
NOT-A-BUG: What 'p' means in 'pnpm?

### ISSUE THREAD

**Issue by MrBoombastic** [pnpm/pnpm#2002]
I'm just wondering what 'p' means in 'pnpm', because I can't find any explanation on the internet. Portable? Pbetter?

**Comment by zkochan** [comment]
Performant

MrBoombastic <notifications@github.com> ezt írta (időpont: 2019. szept. 7.,
Szo 16:24):

**Comment by CyanCherry** [comment]
I think it's PERFECT actually now.
