### ISSUE TITLE
`pnpm run` when package.json does not have "name"

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#2005]
I am not sure if it was intended behavior, but pnpm displays package name as literally `undefined` when `package.json` has no `"name"` field.

### `npm test`

```
> package-name@0.1.2 test /home/user/repo
> node test.js

...
```

### `pnpm test`

```
> package-name test /home/user/repo
> node test.js

...
```

### `npm test`

```
> @ test /home/user/repo
> node test.js

...
```

### `pnpm test`

```
> undefined test /home/user/repo
> node test.js

...
```

**Comment by zkochan** [comment]
:ship: 4.0.1

**Comment by KSXGitHub** [comment]
## Reopen

https://github.com/pnpm/pnpm/pull/2059 tried to solved this by defaulting "name" to empty string, which causes `pnpm test` to prints this:

```
>  test /path/to/repo
> node test.js
```

_(Notice that there're 2 spaces between `>` and `test /path/to/repo`)_

### Proposal

Do it the way `npm` does: package-name@version, or in my case:

```
> @ test /path/to/repo
> node test.js
```
