### ISSUE TITLE
Unified filtering syntax

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2012]
This is a continuation to #1646.

Filters after -- is confusing because it doesn't work for all commands.

Alternatively, we can deprecate filtering after -- and use - instead. - has no special meaning is script runners, so it can be used for all commands.

For example,

```
pnpm add foo - bar
pnpm run test - ...foo qar -- --option-to-scripts
pnpm install - # same as pnpm multi install
```

### Possible alternatives

1. Instead of single dash, use: +, ^, @, :, /
2. Introduce a shorthand flag (-F) and treat -F/--filter the same way as currently --. So something like `pnpm install -F foo bar...` would work
3. Allow listing of selectors, so this would be possible: `pnpm install --filter foo,bar,...qar`

**Comment by KSXGitHub** [comment]
`-` is not OK either, as it implies "read from stdin":

```sh
# This command print 'hello'
echo hello | cat -

# This command opens VS Code with an opened tab that contains hello
echo hello | code -
```

If you really want to shorten `--filter` that much, why don't you just use a single character alias instead (such as `-F`)?

**Comment by zkochan** [comment]
Isn't this just a convention for CLIs that can read from stdin? pnpm has no features that read from stdin.

IMO `-F` is not as good as some escape character. I'd need to also use double quotes or to print -F a couple of times.

```
pnpm add foo -F ...foo -F bar
pnpm add foo -F="...foo bar"
```

**Comment by KSXGitHub** [comment]
There're plenty other characters too: @, $, %, ^, etc.

**Comment by zkochan** [comment]
I think the dollar and % also have special meanings.

@ is probably overused but I have objections to use it.

We may use also tilda (~) or +

**Comment by KSXGitHub** [comment]
We can turn `--filter` into a command:

```sh
pnpm on dir1 dir2 dir3 -- add typescript
pnpm on dir1 dir2 dir3 -- test
pnpm on dir1 dir2 dir3 -- run build
```

**Comment by KSXGitHub** [comment]
BTW, don't use tilda, most shell converts it to $HOME.

**Comment by zkochan** [comment]
Isn't single dash only significant when it is the last character in the
command?

Khải <notifications@github.com> ezt írta (időpont: 2019. szept. 15., V
18:54):

**Comment by KSXGitHub** [comment]
> Isn't single dash only significant when it is the last character in the command?

I'm not sure. But it would confuse user either way.

**Comment by zkochan** [comment]
What about adding a new command? Something like

```
pnpm only foo bar...
# all subsequent commands will run in scope of foo bar...
pnpm install
pnpm test
...
```

**Comment by KSXGitHub** [comment]
> What about adding a new command?

This was (and is) my idea too. https://github.com/pnpm/pnpm/issues/2012#issuecomment-531575886

**Comment by KSXGitHub** [comment]
And if you add `only`, it only makes sense to also add `except`.

**Comment by zkochan** [comment]
I for now I am fine with the shorthand flag if the selectors will support being listed via comma. So if you could do `pnpm install -F foo,bar,...qar`

**Comment by zkochan** [comment]
>>  pnpm run test - ...foo qar -- --option-to-scripts
>
> this is another useless/painful deviation from npm, which just cost me 10 minutes of "wtf??"

What do you mean? This was never implemented.

>>    Filters after -- is confusing because it doesn't work for all commands.
>
> then lets just drop the -- syntax for filters?

This was in some old version (I think v1 and v2) and was reverted years ago.

**Comment by milahu** [comment]
> What do you mean?

yepp, i noticed after hitting comment ... (sorry for the noise)

im trying to run `pnpm run test:jest -t "some test name"` see #4509
