### ISSUE TITLE
Check outdated recursively without root lockfile

### ISSUE THREAD

**Issue by service-paradis** [pnpm/pnpm#2029]
### pnpm version:
3.8.1

### Code to reproduce the issue:
I have a repo containing multiple packages. I have a `package.json` file at the root to define some `scripts`. Since I do not have any dependencies in this `package.json`, there is no lockfile created.

I want to run `pnpm recursive outdated` to see if there was any outdated dependencies in my packages. Unfortunately, I got the following error:
>  ERROR  No lockfile in this directory. Run `pnpm install` to generate one.

Here's an example of the structure
```
- foo
-- package.json # with dependencies
- bar
-- package.json # with dependencies
package.json # with script but without dependencies
```

### Expected behavior:
Skip the package without lockfile when running the `outdated` command recursively.
Give a warning that no lockfile have been found and continue with the other packages without a hard fail.

### Actual behavior:
The script fails instantly without checking if there are any outdated packages.

### Additional information:

 - `node -v` prints: v8.10.0
 - Windows, OS X, or Linux?: Windows 10

**Comment by nicholasraphael** [comment]
Hey new here and I was just looking through the good first issues. It seems this is on track/done so maybe it should be closed.

**Comment by service-paradis** [comment]
You're right. Cannot test since I'm not using pnpm anymore in this project, but looking at the changes made in #2349, it should be resolved!
