### ISSUE TITLE
pnpm run doesn't handle pass signals onto child processes

### ISSUE THREAD

**Issue by leemhenson** [pnpm/pnpm#2033]
### Code to reproduce the issue:

Add scripts to package.json in the form:

`"long-running-script": "pnpx thing-a && pnpm run thing-b"`

### Expected behavior:

While `pnpx thing-a` is running, I should be able to hit ctrl-c and have the script exit.

### Actual behavior:

Pnpm exits back to the terminal but the processes keep on running in the background, writing to stdout.

### Additional information:

 - `node -v` prints: `v.12.5.0`
 - Windows, OS X, or Linux?: Mac OS 10.14.6

**Comment by zkochan** [comment]
:ship: 4.1.7
