### ISSUE TITLE
Automatically resolve conflicts in lockfile

### ISSUE THREAD

**Issue by alanpearce** [pnpm/pnpm#2036]
npm added this feature in [v5.7.0](https://github.com/npm/npm/releases/tag/v5.7.0).

It would be awesome if pnpm could do the same!

**Comment by znck** [comment]
What does "pinned" mean? Does it mean you're working on it or it means you're seeking contribution?

**Comment by zkochan** [comment]
I plan to work on it.

**Comment by zkochan** [comment]
You can try it out through `pnpm install --global pnpm@0.0.0-20201030124`

**Comment by zkochan** [comment]
:ship: 5.11
