### ISSUE TITLE
Improve output viewing of 'pnpm store usages'

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#2047]
Whenever I type `pnpm store usages @types/node`, pnpm shows me a tree of dense and indistinguishable all-white text which is hard to read.

## Suggestions

1. **Use ANSI color to highlight important details and dim less important ones:**
  * Package name after "Package in store: " should be in bold.
  * Decorations (such as `├──`) should be dimmed.

2. **Shorten the messages:**
  * Change `Package in store: registry.npmjs.org/@types/node/12.7.9` to `@types/node/12.7.9 (registry.npmjs.org/@types/node/12.7.9)`. Package name is highlighted, package location is dimmed.
  * Change `Project with dependency: ...` to `used by ...`. Dim the `used by` part, leave the rest normal.

## Additional Suggestion

`--json` flag to output JSON text.

**Comment by juanpicado** [comment]
@zkochan do you know what happened with this command? I don't see it the source code.

**Comment by zkochan** [comment]
I believe it was removed in one of the major versions.
