### ISSUE TITLE
`--silent` and `-s` flags cause failures

### ISSUE THREAD

**Issue by gsong** [pnpm/pnpm#2058]
### Code to reproduce the issue:

```
$ pnpm i -s
 ERROR  Unknown option 'loglevel'
For help, run: pnpm help recursive
```

### Expected behavior:

To work the same as `--reporter silent`

### Actual behavior:

```
 ERROR  Unknown option 'loglevel'
```

### Additional information:

 - `node -v` prints: v10.16.3
 - Windows, OS X, or Linux?: macOS 10.14.6

**Comment by zkochan** [comment]
:ship: 4.0.1

**Comment by sz-cgt** [comment]
Still broken in 4.3.0

>[cgt-ilab@ldevawsweb0004 ilab]$ pnpm --version
4.3.0
[cgt-ilab@ldevawsweb0004 ilab]$ pnpm -s
 ERROR  Unknown option 'reporter'
For help, run: pnpm help help
[cgt-ilab@ldevawsweb0004 ilab]$ node -v
v10.10.0

**Comment by tunnckoCore** [comment]
@zkochan, no docs on all of that? Or at least through cli. I want to hide warnings, but show the progress and etc.

- `--silent` comletely hides everything
- `--quiet` says that "unknown option --loglevel`
- `--reporter` says that "unknown option --reporter`
- `--loglevel` without value works - doesn't fail. shows progress and fewer warnings.
- `--loglevel info` (with any value) fails with "unknown option --loglevel

So... It seems we should loglevel, but what are the values? And docs on `reporter`s? That would be coooooooool.

**Comment by zkochan** [comment]
> --loglevel without value works - doesn't fail. shows progress and fewer warnings.

no, it doesn't hide warnings. pnpm currently does not filter the log types when you set loglevel

**Comment by tunnckoCore** [comment]
> no, it doesn't hide warnings. pnpm currently does not filter the log types when you set loglevel

yea, seems like it was temporary.
