### ISSUE TITLE
pnpm version didn't shutdown for ctrl-c

### ISSUE THREAD

**Issue by 3cp** [pnpm/pnpm#2060]
### Code to reproduce the issue:

I did `pnpm version minor`. But I soon realized I made a mistake, I actually wanted `pnpm version patch`. So I hit `ctrl-c`, it indeed restored my cursor back to terminal, but somehow pnpm still runs and finishes all build/version/publish commands in the background (with visible logs in my terminal).

### Expected behavior:

Expect `pnpm version ...` to shutdown immediately with `ctrl-c`.

### Actual behavior:

`pnpm version ...` continues to run and finish in background after `ctrl-c`.

### Additional information:

 - `node -v` prints: v12.10.0
 - Windows, OS X, or Linux?: macOS 10.15

**Comment by zkochan** [comment]
Probably related to #2033

**Comment by 3cp** [comment]
Definitely, close this duplicated issue.

**Comment by zkochan** [comment]
:ship: 4.1.7

**Comment by zkochan** [comment]
actually, this is related to some other code. This has to be fixed in https://github.com/pnpm/pnpm/blob/master/packages/pnpm/src/runScript.ts

**Comment by zkochan** [comment]
Maybe it was fixed.
