### ISSUE TITLE
`pnpm up -g` errors out

### ISSUE THREAD

**Issue by gsong** [pnpm/pnpm#2061]
### Code to reproduce the issue:

```sh
pnpm up -g
```

### Expected behavior:

Upgrade globally installed packages.

### Actual behavior:

```sh
 ERROR  Unknown option 'global'
For help, run: pnpm help update
```

### Additional information:

 - `node -v` prints: v10.16.3
 - Windows, OS X, or Linux?: macOS 10.14.6

**Comment by zkochan** [comment]
:ship: 4.0.1
