### ISSUE TITLE
--color=always does not work in v4

### ISSUE THREAD

**Issue by David-Else** [pnpm/pnpm#2062]
### Code to reproduce the issue:
pnpm install --save-dev @types/node@12.7.12 @typescript-eslint/eslint-plugin@2.3.3 @typescript-eslint/parser@2.3.3 mocha@6.2.1 eslint@6.5.1 eslint-config-prettier@6.4.0 rollup@1.23.1 tsc-watch@4.0.0 --color=always

### Expected behavior:
works
### Actual behavior:
Command failed: pnpm install --save-dev @types/node@12.7.12 @typescript-eslint/eslint-plugin@2.3.3 @typescript-eslint/parser@2.3.3 mocha@6.2.1 eslint@6.5.1 eslint-config-prettier@6.4.0 rollup@1.23.1 tsc-watch@4.0.0 --color=always
 ERROR  Unknown option 'color'

### Additional information:

 - `node -v` prints: v10.14.1
 - Windows, OS X, or Linux?: Linux

npm-check uses this option when set to use pnpm, so now it's broken.

**Comment by zkochan** [comment]
:ship: 4.0.1

**Comment by David-Else** [comment]
Cool, I got it to work :) Thanks for quick fix!
