### ISSUE TITLE
ERROR  Unknown option 'color'

### ISSUE THREAD

**Issue by matt3224** [pnpm/pnpm#2063]
### Code to reproduce the issue:
```
$ npm-check -u
```
which runs internally:
```
$ pnpm install --save-dev @babel/preset-env@7.6.3 --color=always
```

### Expected behavior:
Installs update

### Actual behavior:
Fails with `ERROR  Unknown option 'color'`

### Additional information:

 - `node -v` prints: v12.11.1
 - Windows, OS X, or Linux?: macOS 10.15

It's worth noting that using npm-check when the project is using npm rather than pnpm works as expected. No idea why it seems pnpm gets hung up. pnpm is working though i can pnpm i etc

Thanks!

**Comment by zkochan** [comment]
Same as #2062
