### ISSUE TITLE
Peer dependencies are not being installed

### ISSUE THREAD

**Issue by jasonrobson** [pnpm/pnpm#2068]
### Expected behavior:

To install all dependencies and peer dependencies

### Actual behavior:

Installing only dependencies, peer dependencies are not being installed

### Additional information:

![Captura de Tela 2019-10-09 às 16 06 57](https://user-images.githubusercontent.com/40805162/66513027-9a935000-eab0-11e9-96b0-a93c8929eb81.png)

 - `node -v` prints:
OS: macOS HIGH SIERRA version 10.13.6

**Comment by zkochan** [comment]
You should install peer deps yourself. peer deps were automatically installed only in some old version of npm
