### ISSUE TITLE
Crash on pnpm up

### ISSUE THREAD

**Issue by alozytskyi** [pnpm/pnpm#2071]
### Code to reproduce the issue:
`pnpm up`

### Expected behavior:
Packages update

### Actual behavior:
Crashes: 
```
Resolving: total 1719, reused 1717, downloaded 1, done
 ERROR  ENOENT: no such file or directory, chmod '/<nda censored>/node_modules/.pnpm/node_modules/node/bin/node'
```
### Additional information:

 - `node -v` prints: v12.11.1
 - Windows, OS X, or Linux?: Arch Linux

**Comment by zkochan** [comment]
Do you have node in dependencies?

**Comment by alozytskyi** [comment]
@zkochan no, I don't have node in dependencies

**Comment by zkochan** [comment]
This seems to be happening only with hoisting. If you don't need hoisting, you can set `hoist=false` in a `.npmrc` in the root of your project.

**Comment by alozytskyi** [comment]
`node` was pulled by babel-preset-target from my devDependencies, so I've removed it, and it works fine now both with hoisting on and off

Leaving the culprit info here:
```
$ pnpm why node                                   
Legend: production dependency, optional only, dev only     
                                                           
<package name><path here>
                                                           
devDependencies:                                           
babel-preset-target 0.0.5                                  
└─┬ compat-table 0.0.0                                     
  └── node 12.12.0                                         
```

**Comment by zkochan** [comment]
Thanks. I know what the issue is. I am working on a fix
