### ISSUE TITLE
"Store" on Windows

### ISSUE THREAD

**Issue by jeffrson** [pnpm/pnpm#2072]
Hi,

the pnpm store on Windows doesn't work like intended.

1) If I have a working directory on a drive different to that containing my user profile (although that may be hard wired to c: - haven't tested with user profile on d:, for example) the store is created in the first level of this working directory. That means, if I have working directories f:\test1, f:\test2, f:\test3, ... each of them will contain a .pnpm-store.

2) The "hard links" on Windows are in fact "junctions". Which should work, and indeed does. However, the junctions don't point into the store, but into the project's node_modules\\.pnpm. This can be proven by removing node_modules\\.pnpm - the referenced modules (like node_modules\debug) don't exist anymore.

### Code to reproduce the issue:
```
f:\
mkdir test1 test2
cd test1 && pnpm init -y && pnpm add debug
type node_modules\.modules.yaml | findstr store
cd ..\test2 && pnpm init -y && pnpm add debug
type node_modules\.modules.yaml | findstr store
dir node_modules\debug
rmdir /s /q node_modules\.pnpm
dir node_modules\debug
```

 - `node -v` prints: 10.16.3
 - Windows, OS X, or Linux?: Windows 10

**Comment by jeffrson** [comment]
On a further note - after running `pnpm add debug`, shouldn't `pnpm store usages debug` report it?

Instead nothing is printed (it's the same on Linux, btw!).

**Comment by zkochan** [comment]
> The "hard links" on Windows are in fact "junctions". Which should work, and indeed does. However, the junctions don't point into the store, but into the project's node_modules\.pnpm. This can be proven by removing node_modules\.pnpm - the referenced modules (like node_modules\debug) don't exist anymore.

No. Hard links are supported on Windows. And all files under `node_modules/.pnpm` are hard links to the store. There are also symlinks (junctions on Windows) that connect the dependencies into the node_modules of dependent packages.

> If I have a working directory on a drive different to that containing my user profile (although that may be hard wired to c: - haven't tested with user profile on d:, for example) the store is created in the first level of this working directory. That means, if I have working directories f:\test1, f:\test2, f:\test3, ... each of them will contain a .pnpm-store.

So there is no store at `f:\.pnpm-store`?

[This](https://github.com/pnpm/store-path) library is used to get the store location. Maybe it doesn't work correctly on your system. Although it has been tested on Windows

**Comment by jeffrson** [comment]
Okay - I did not know that only files are linked, not directories.

For the second part - no, there is no `f:\.pnpm-store`. It seems, that `can-link`, via `graceful-fs` fails to link a (temporary) file from f:\ to my projects home. So it tries the first sub dir level of the project path.

That's true - mklink, for example, cannot link this file as well. Only admin can do that for me.

But I don't understand why it wants to link this file in order to create the store there. It doesn't need the link. When it finds a path, it creates the ".pnpm-store" directory, which perfectly works in f:\

**Comment by zkochan** [comment]
So you're saying that even though a link cannot be created to `f:\`, it can be created to `f:\.pnpm-store`? In that case, we have to update our code. The way it currently works, pnpm tries to link into each parent directory in order to find the shortest path that allows linking. So it will only create the store in `f:\.pnpm-store` if a link could be created in in `f:\`.

**Comment by jeffrson** [comment]
> So you're saying that even though a link cannot be created to f:\, it can be created to f:\.pnpm-store?

I'm not sure, about "link to"... AFAICT, pnpm tries to create a file link to a temporary file that was created inside the project root.

Usually without disabling UAC or without elevating the command prompt you cannot write files to a drive's root. This includes file links. Only folders can be created. Or junctions.

So `fs.link('F:\projects\p1\_tmp_19768_b95cba0852d5865ae07fdfe5930fe465', 'F:\_tmp_19768_2ab0e1c7b8b028fe09054f157bb72f68')` will fail. 

However, a folder `f:\.pnpm-store` can be created.

**Comment by zkochan** [comment]
OK, we can add a special check for Windows systems [here](https://github.com/pnpm/store-path/blob/1ed2c7f8a0c28795c65fc4fc790bbdcc74435af5/src/index.ts#L41).

If OS is Windows, we can create a `.pnpm-store` in the drive's root and try to link to it.

**Comment by zkochan** [comment]
I think this is also an issue on WSL. I have my projects in `C:\src` and the store gets created in `C:\src\.pnpm-store`

**Comment by jeffrson** [comment]
Yes, indeed. Just checked.

Although my /home/<user> would be on c:\ from the Windows point-of-view, the store is created in /mnt/c/src/.pnpm-store.

Unfortunately, os.platform() in WSL results in "linux".

**Comment by zkochan** [comment]
:ship: 4.1.2
