### ISSUE TITLE
Missing dependencies/symlinks with --shamefully-hoist

### ISSUE THREAD

**Issue by faustbrian** [pnpm/pnpm#2073]
### Code to reproduce the issue:

There is no direct code for reproduction but it is fairly simple, just setup a repository with jest and a workspace that has a few packages with unique dependencies in each. Then instead of having tests in each package you have a `tests` directory at the root of the project, now because of this structure you'll have to use `pnpm multi install --shamefully-hoist` to setup the project because you need a flat `node_modules` structure so that `jest` can find all the dependencies and make use of them.

```
- node_modules
- tests
    - packageA
    - packageB
    - packageC
- packages
    - A
    - B
    - C
jest.config.js
```

### Expected behavior:

It should run tests  with all dependencies available since `--shamefully-hoist` was used to setup the project which results in a flat `node_modules` structure.

### Actual behavior:

The tests run but various dependencies are reported as not found even though they are in the root `node_modules` directory.

This might be a known issue with pnpm and jest?

### Additional information:

 - `node -v` prints: v12.4.0
 - Windows, OS X, or Linux?: macOS Catalina 10.15 (19A583)

**Comment by zkochan** [comment]
Do you mean that you want to `require('A')` from the root tests?

You'd have to add package A as a dependency to the root package for that.

**Comment by faustbrian** [comment]
The problem with that would be that I would have to add all workspace packages and the dependencies of those to the root package.json, or am I wrong with that assumption? I basically want to be able to use all the workspace packages and dependencies of those inside of the root tests as that is where all the tests are placed.

It's a mono repository so the root package.json doesn't really contain anything besides dependencies for linting, testing and alike.

**Comment by zkochan** [comment]
> I would have to add all workspace packages and the dependencies of those to the root package.json

No, there is no need to add the dependencies of workspace packages as well

**Comment by faustbrian** [comment]
Then let me clarify. Currently the setup of the directory structure is as follows.

```
- node_modules
- tests
    - packageA
    - packageB
    - packageC
- packages
    - A
    - B
    - C
jest.config.js
package.json
```

The workspace is bootstrapped with `--shamefully-hoist` to create a flat node module structure. If I know run my tests via `jest tests` they all seem to work fine and import the workspace packages but the dependencies of those workspace packages are missing.

Note that this is without adding `packages/{A,B,C}` to the root package.json but it also won't work if I add them to the root package.json. The dependencies of the workspace packages are simply not available inside of the root tests.

**Comment by zkochan** [comment]
Have you created a [pnpm-workspace.yaml](https://pnpm.js.org/en/pnpm-workspace_yaml) file in the root of the repository?

**Comment by faustbrian** [comment]
Yes, I've followed all the instructions to setup a workspace and the workspace packages itself are available to the root tests but not their dependencies.

Are there any known issues with jest not being able to resolve those symlinks? Based on past issues reported it seemed like this had been resolved both in pnpm and jest.

**Comment by faustbrian** [comment]
Closing as there doesn't seem to be a solution.

**Comment by antonio-malcolm** [comment]
The issue seems to be, if I understand it correctly, that `pnpm` does not use a flat `node_modules` directory structure, which Webpack, and some other projects, expect.

Instead of shamefully-hoist, you might try doing something like this (which worked, for me, on both OS X and Linux), to populate your resolve modules:

```
const path = require('path');

const srcDir = path.resolve(__dirname, '../PATH/TO/SRC');
const rootModulesDir = path.resolve(__dirname, '../PATH/TO/ROOT/node_modules');
const subProjectModulesDir = path.resolve(__dirname, '../PATH/TO/SUBPROJECT/node_modules');
const modules = [srcDir];

if (process.env.NODE_PATH && process.env.NODE_PATH.length) {

  process.env.NODE_PATH.split(path.delimiter).forEach(function(modulePath) {
    
    if (modulePath.startsWith(rootModulesDir) || modulePath.startsWith(subProjectModulesDir)) {
      modules.push(modulePath);
    }
    
  });

} else {
  modules.push(rootModulesDir);
  modules.push(subProjectModulesDir);
}

//...meanwhile, in your webpack config...

resolve: {
  modules: modules
}

```

If you need or want to, you could also filter out some nested packages (such as `babel-watch`), by creating an array of omitted project names, and, inside the innermost conditional block, utilize `String#includes`, to check if the `modulePath` contains the package project name, before adding it to the modules array.

Hope that helps.
