### ISSUE TITLE
PNPM fails to build package with node-gyp

### ISSUE THREAD

**Issue by andykais** [pnpm/pnpm#2075]
Apologies if this is not a bug with pnpm, but I only started seeing the issue after upgrading from pnpm v3.

### pnpm version:
`4.0.1`
### Code to reproduce the issue:
pnpm i better-sqlite3

[pnpm-debug.log](https://gist.github.com/andykais/3fcf3c73968a69b45031c2c5c76d6041)

### Expected behavior:
pnpm installs `better-sqlite3` without issue.

### Actual behavior:
The build crashes with a node-gyp error.

### Additional information:
the build succeeds without issue using npm. E.g. `npm i better-sqlite3`

 - `node -v` prints: `v12.11.1`
 - Windows, OS X, or Linux?: the issue appeared on both OS X and Linux

**Comment by zkochan** [comment]
It is probably because pnpm uses the latest version of node-gyp, which had some breaking changes.

**Comment by andykais** [comment]
Thank you, this does appear to be a problem with node-gyp and the `better-sqlite3` package https://github.com/JoshuaWise/better-sqlite3/issues/304. I am closing this issue since it does not pertain to pnpm.
