### ISSUE TITLE
feat: Update workspace dependencies

### ISSUE THREAD

**Issue by anion155** [pnpm/pnpm#2085]
### pnpm version: 4.0.1

When dependency added through `workspace:` protocol, and it's version was updated to major, all pnpm commands related to dependencies gives error: 
```
ERROR  No matching version found for test_1@^1.0.0 inside the workspace
```

### Code to reproduce the issue:

https://github.com/anion155/pnpm-install-updated-workspace-dependency
There is two scripts in repo: `to_brake_repo.js` and `to_fix_repo.js`, to simplify tests

### Feature request:

~Add abillity to update workspace dependencies, or~ update them automatically with `pnpm [recursive] update`.

### Additional information:

 - `node -v` prints: `v10.16.3`
 - Windows, OS X, or Linux?: `Linux 5.0.0-31-generic GNU/Linux`

**Comment by anion155** [comment]
For the clarification. `pnpm update` and `pnpm recursive update` gives me the same error

**Comment by anion155** [comment]
> As a temporary workaround, you can use `workspace:*`. On publish, pnpm will convert it to the exact version of dependency which is in the repository ([more details](https://pnpm.js.org/en/workspaces#publishing-workspace-packages))

Thanks. But this will mean that I have to stick with exact versions. Not really bad, but not great. I'm considering writing script, that will do this stuff for me (hope, I'll have some time for it).

**Comment by zkochan** [comment]
Related: #1918

**Comment by zkochan** [comment]
What about running `pnpm update --latest`? Does it update the workspace dep?

**Comment by anion155** [comment]
> What about running `pnpm update --latest`? Does it update the workspace dep?

Nope:
```sh
> pnpm update -L
Scope: current workspace package
Already up-to-date
Only the root workspace package is going to have hoisted dependencies in node_modules
ERROR  No matching version found for test_1@^1.0.0 inside the workspace
```

**Comment by zkochan** [comment]
Seems like this is what you propose and I agree with this: `pnpm update` should update all workspace ranges even if there was a major version bump

**Comment by anion155** [comment]
@zkochan, this error also true for minor versions before any major version (0.x.y). But I suppose it is to comply https://semver.org/#spec-item-4.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

And I suppose npm does not update 0 major versions too.

**Comment by zkochan** [comment]
yes, I know about this. `pnpm update` will not care at all what is the current workspace range. It will update the range to whatever is found in the repository.

**Comment by zkochan** [comment]
The PR is ready at #2137

**Comment by zkochan** [comment]
:ship: [4.2.0-0](https://github.com/pnpm/pnpm/releases/tag/v4.2.0-0)

**Comment by anion155** [comment]
@zkochan Does not work with reproduce repo.

**Comment by zkochan** [comment]
We need to add better error messages.
