### ISSUE TITLE
pretest script should not forward tail args from test

### ISSUE THREAD

**Issue by thynson** [pnpm/pnpm#2087]
### Code to reproduce the issue:
1. Suppose a package.json 
```json
{
  "script": {
    "test": "true",
    "pretest": "echo pretest"
  }
}
```
2. Run `pnpm t -- --test-args`
### Expected behavior:
output same with npm
```
pretest
```

### Actual behavior:
output:
```
pretest --test-args
```

### Additional information:

 - `node -v` prints: 10.16.3
 - macOS 10.14
 - npm behaves

**Comment by thynson** [comment]
Not sure weather other pre/post scripts are also affected.

**Comment by zkochan** [comment]
This is one of the places that needs to be changed

https://github.com/pnpm/pnpm/blob/b7e57518f14a80996fb906f989e2290b4f18986b/packages/pnpm/src/cmd/run.ts#L27-L43

and there's a similar piece in `cmd/recursive/run.ts`

**Comment by zkochan** [comment]
:ship: 4.1.5
