### ISSUE TITLE
[outdated] Don't consider pre‑release versions outdated if they’re newer than the latest release

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#2101]
## pnpm version:
v4.0.2

## Code to reproduce the issue:
Run `pnpm outdated` while having a pre‑release package version installed.

## Expected behavior:
**pnpm** doesn’t consider the pre‑release package outdated when the `latest` release tag points to an older version.

## Actual behavior:
**pnpm** considers the pre‑release package outdated.

## Additional information:
 - `node -v` prints: v12.10.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
I would update this to "Don't consider versions outdated if they’re newer than the latest release"

**Comment by zkochan** [comment]
:ship: [4.2.2](https://github.com/pnpm/pnpm/releases/tag/v4.2.2)
