### ISSUE TITLE
Appending parameters to package.json scripts

### ISSUE THREAD

**Issue by KnisterPeter** [pnpm/pnpm#2104]
# pnpm version:

4.1.4

### Code to reproduce the issue:

```sh
pnpm run script -- --parameter
```

### Expected behavior:

The code above should append the `--paramter` to the script named `script` in the package.json.

### Actual behavior:

The `--paramter` is added to the script with the name `prescript` in the package.json.
This in itself may not be a problem, but since pnpm fails with `unknown option --paramter` if that `prescript` contains something like `pnpm run ...` it is a showstopper for managing complex scripts with pnpm.

### Additional information:

 - `node -v` prints: v12.12.0
 - Windows, OS X, or Linux?: Arch Linux

**Comment by zkochan** [comment]
A fix for this is already in master (the last commit). Not published yet

Markus Wolf <notifications@github.com> ezt írta (időpont: 2019. okt. 21., H
14:28):

**Comment by zkochan** [comment]
fixed by #2103

**Comment by zkochan** [comment]
:ship: 4.1.5
