### ISSUE TITLE
Script args are incorrectly conveyed to commands

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2105]
### Code to reproduce the issue:

Please see https://github.com/rollup/plugins/tree/7f16838ddb6730cb8e52dcc4ee3304384d572228 for reproducing the issue. _(That commit is the important once, since we're going to work around this limitation while this bug is being triaged)_

Steps to reproduce:

1. Clone
1. `git fetch && git pull`
1. `git checkout 7f16838ddb6730cb8e52dcc4ee3304384d572228`
1. `pnpm install`
1. Make a change to the `/replace` directory and save.
1. Run `pnpm run ci:test`

I've pasted the `scripts` from `/replace/package.json` below so that you can see how it all ties together:

```json
  "scripts": {
    "build": "rollup -c",
    "ci:coverage": "nyc pnpm run test && nyc report --reporter=text-lcov > coverage.lcov",
    "ci:coverage:submit": "curl -s https://codecov.io/bash | bash -s - -F beep",
    "ci:lint": "pnpm run build && pnpm run lint && pnpm run security",
    "ci:lint:commits": "commitlint --from=${CIRCLE_BRANCH} --to=${CIRCLE_SHA1}",
    "ci:test": "pnpm run test -- --verbose && pnpm run test:ts",
    "lint": "pnpm run lint:js && pnpm run lint:docs && pnpm run lint:package",
    "lint:docs": "prettier --write README.md",
    "lint:js": "eslint --fix --cache src test",
    "lint:package": "prettier --write package.json --plugin=prettier-plugin-package",
    "prebuild": "del-cli dist",
    "prepare": "npm run build",
    "prepublishOnly": "npm run lint && npm run test:only",
    "pretest": "npm run build",
    "security": "echo 'pnpm needs `npm audit` support'",
    "test": "ava",
    "test:ts": "tsc index.d.ts test/types.ts --noEmit"
  },
```

### Expected behavior:

It's expected, and how npm works, that the `--verbose` flag is not passed to `pretest`, which is what is happening at present. `pnpm run ci:test` should run `pnpm run test -- --verbose` and only pass the `--verbose` flag to the `"test"` script. 

### Actual behavior:

We get this:

```console
packages/replace ci:test$ pnpm run test -- --verbose && pnpm run test:ts
[24 lines collapsed]
│ created dist/rollup-plugin-replace.cjs.js, dist/rollup-plugin-replace.es.js in 72ms
│ npm verb lifecycle @rollup/plugin-replace@2.2.0~build: unsafe-perm in lifecycle true
│ npm verb lifecycle @rollup/plugin-replace@2.2.0~build: PATH: /.nvm/versions/node/v12.3.1/lib/node_modules/
│ npm verb lifecycle @rollup/plugin-replace@2.2.0~build: CWD: /code/rollup/plugins/packages/replace
│ npm info lifecycle @rollup/plugin-replace@2.2.0~postbuild: @rollup/plugin-replace@2.2.0
│ npm verb exit [ 0, true ]
│ npm timing npm Completed in 572ms
│ npm info ok 
│ > @rollup/plugin-replace@2.2.0 test /code/rollup/plugins/packages/replace
│ > ava "--verbose"
└─ Running...
packages/strip ci:test$ pnpm run test -- --verbose
│ Scope: current workspace package
│ > @rollup/plugin-strip@1.2.2 pretest /code/rollup/plugins/packages/strip
│ > pnpm run build "--verbose"
│  ERROR  Unknown option 'loglevel'
│ For help, run: pnpm help run
│  ERROR  Command failed with exit code 1.
└─ Failed in 2s
```

See that the `pretest` script seems to be receiving the `--verbose` flag:

```
│ > pnpm run build "--verbose"
│  ERROR  Unknown option 'loglevel'
```

And that short-circuits the entire process.

*Additionally* it appears as though `pnpm` itself thinks that we want console output to be verbose, when in fact we only wanted to pass that along to `ava` in the `"test"` script.

### Additional information:

 - `node -v` prints: v12.3.1
 - Windows, OS X, or Linux?: OSX

**Comment by zkochan** [comment]
This was fixed in pnpm v4.1.5.

You just need to update pnpm in the dependencies of your workspace

**Comment by shellscape** [comment]
`pnpm` reports 4.1.5. is this a conflict between global and local versions?

**Comment by zkochan** [comment]
I would not call it a conflict. your script runs the pnpm from your deps, which is 4.1.4

https://github.com/rollup/plugins/blob/7f16838ddb6730cb8e52dcc4ee3304384d572228/pnpm-lock.yaml#L10

**Comment by shellscape** [comment]
The first thing I did when I ran into this was update my global install - thinking that the global install was running the show (at v4.1.5). I checked the console output and there isn't any content that displays what the version is, or whether or not it's using the locally installed pnpm, or the globally installed pnpm.

I think there's an opportunity for DX improvement here. If the output would have shown `pnpm @ v4.1.4` that would've immediately told me that there was an outdated version somewhere, and to look into that first. If the output would have shown an indicator that pnpm was a local dep - for either the execution of the script or the process as a whole - that would have told me exactly what was going on. 

One might think that `pnpm-debug.log` would be the first stop, and it was. But the debug log at the root of the workspace only had 4.1.5 in the log. It wasn't until just a minute ago that I realized that the debug logs in each package directory had 4.1.4 in the log. That's because those are in `.gitignore` and I had the directories collapsed in my editor. So there again, there's an opportunity for a DX improvement because this kind of situation wouldn't be immediately recognizable to a developer that didn't have an intimate knowledge of the tool's behavior.

Can we reopen and repurpose this as a DX issue?

**Comment by zkochan** [comment]
I think installing pnpm as a dependency is a bad idea but I also understand your motivation.

I think what we really need is the ability to tell pnpm what version needs to be used for the project. pnpm then should install and execute the specified version.

We [have an issue](https://github.com/pnpm/pnpm/issues/1383) about it and we can discuss the details there.

**Comment by zkochan** [comment]
Regarding improvements to DX, it is fine to open a separate issue for every small improvement that you have in mind.

**Comment by zkochan** [comment]
I don't like the idea of always printing the version number. But I think we can do what gulp does. If the global and local pnpm versions differ, we can print a warning or info message about that
