### ISSUE TITLE
First use: pnpx is not hard linking node_module files between two identical projects.

### ISSUE THREAD

**Issue by laurencefass** [pnpm/pnpm#2107]
BUG REPORT

### pnpm version:
4.1.5

### Code to reproduce the issue:
pnpx create-react-app project1
pnpx create-react-app project2

### Expected behavior:
expecting to see identical inode ids on hard links to files in both node_modules folder.

### Actual behavior:

installs exactly the same node_modules folder structure as using npx.

### Additional information:

bash-4.4# node -v
v11.1.0

**Comment by zkochan** [comment]
Why do you think the files in the node_modules are not hard links?

https://pnpm.js.org/en/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store

**Comment by laurencefass** [comment]
test: 

Installed two identical two projects side by side using pnpx.
Check the links an arbitrary file in node_modules folder using **ls -l and find -inum**.

expecting: all files under node_modules to contain two hard links for two identical projects created together.

result: the file only lists one link within the scope.

Im assuming that pnpx is hardlinking ALL of the files under node_modules as it creates them?

thanks

**Comment by zkochan** [comment]
these projects are on the same drive?

**Comment by laurencefass** [comment]
yes installed them next to each-other to test the package.

**Comment by laurencefass** [comment]
thanks so commands like "pnpx create-react-app..." are not going to provide hard links as expected?

**Comment by zkochan** [comment]
`pnpx create-react-app` installs `create-react-app` using hard links to a temporary location. Then it runs `create-react-app` which generates a react app and runs `npm` (or Yarn) to install dependencies.  So pnpx works as expected. If create-react-app would run pnpm to install dependencies, hard links would be used.

**Comment by laurencefass** [comment]
thanks. can i replace npm with pnpm in create-react-app and similar generators?

**Comment by zkochan** [comment]
some generators ask you what pm to use. Like the angular generator has a step where you select npm/pnpm or yarn. This generator seems like does not allow that

**Comment by laurencefass** [comment]
thanks ill open an issue in CRA repo.

to clarify if i pnpm or pnpx install a module will ALL its files be created as hardlinks? is the folder structure also linked or only files?

**Comment by zkochan** [comment]
only files are hard links

**Comment by laurencefass** [comment]
thanks for your help and advice.
