### ISSUE TITLE
 ERROR  Unknown option 'resolution-strategy' broken with pnpm 4.1.0 and up

### ISSUE THREAD

**Issue by Claudiazhaoya** [pnpm/pnpm#2108]
### pnpm version:
4.1.5

### Code to reproduce the issue:
https://github.com/microsoft/rushstack/issues/1598

1. git clone --single-branch --branch rush-issue-1598 https://github.com/wbern/rush-pnpm-issues.git 
2. rush update

### Expected behavior:

Pnpm 4.1.0 should be expected to run **pnpm install** successfully without the  **ERROR  Unknown option 'resolution-strategy'**

### Actual behavior:

**pnpm install** fails because the error **Unknown option "resolutionary-strategy"** occurs. 

### Additional information:

 - `node -v` prints:
10.15.3
 - Windows, OS X, or Linux?:
Windows 10

**Comment by zkochan** [comment]
fixed by d0c30992c7a9201d502386e19a73e3a2af0862b2

will publish soon

**Comment by zkochan** [comment]
:ship: 4.1.6
