### ISSUE TITLE
Request: "binary" release on GitHub releases page

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#2109]
I would like to see a binary release tarball attached to each release on the https://github.com/pnpm/pnpm/releases page. This would make it easier to include `pnpm` in Docker images.

For an example, see https://github.com/yarnpkg/yarn/releases. Notice that they have installable packages for each platform, including a generic `.tar.gz`. Inside that `.tar.gz` are `bin` and `lib` directories that can be directly extracted to `/usr/local` to successfully "install" the package manager.

The same thing is true of `npm` by way of the official Node.js release tarballs.

**Comment by haquezameer** [comment]
@zkochan would like to take this up. From what I understand, the requirement is to also generate a `.tar.gz` release asset which then shows up in the releases section:
![image](https://user-images.githubusercontent.com/20766601/129684398-125649df-8df4-42bb-adfd-c5ca34e766aa.png)

**Comment by zkochan** [comment]
@jsumners is this still needed? At the time this issue was created, there were no release assets attached at all.

**Comment by jsumners** [comment]
@zkochan I see that you're now adding the bare binaries to the releases. That should be sufficient. I'd expect the tarball if the installables were more than a single file. The only benefit that packaging the single binary would provide is some error correction protection while downloading.
