### ISSUE TITLE
What happened to `--save` and `--save-dev`?

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#2110]
### Code to reproduce the issue:

`pnpm i --save foo` or `pnpm uninstall --save-dev bar`

### Expected behavior:

Commands should execute and update `package.json` accordingly.

### Actual behavior:

An error is returned "unknown option".

### Additional information:

 - `node -v` prints: v10.16.3
 - Windows, OS X, or Linux?: OS X

**Comment by Bessonov** [comment]
It saves automatically. To distinguish between `dependencies` and `devDependencies` try to use `-D` flag: `pnpm i -D foo`.

**Comment by Bessonov** [comment]
See also https://github.com/pnpm/pnpm/issues/2020 and https://github.com/pnpm/pnpm/issues/1237.

**Comment by jsumners** [comment]
@Bessonov if you read #1237 you will see that I strongly argued against defaulting to updating `package.json` throughout that issue.

**Comment by Bessonov** [comment]
@jsumners no, I didn't read it (before), because I never run in any situation in which I don't want to save the information in `package.json`. I can't judge on your use case, but well, some projects like webpack already use plugins. For me it's more architectural problem and not a dependency manager problem.

**Comment by jsumners** [comment]
This is a real issue for compatibility with `npm` commands and tools that expect the package manager to be compatible. For example, the [npm-check](https://www.npmjs.com/package/npm-check) tool supports `pnpm` by way of:

```sh
$ NPM_INSTALLER=pnpm npm-check -u
```

However, if you you attempt this with `pnpm@4` in a project with dependencies that have newer versions available you will get:

```sh
$ NPM_INSTALLER=pnpm npm-check -u
? Choose which packages to update. dotenv@8.2.0, nock@11.6.0, tap@14.8.2

$ pnpm install --save dotenv@8.2.0 --color=always
Command failed: pnpm install --save dotenv@8.2.0 --color=always
 ERROR  Unknown option 'save'

For more detail, add `--debug` to the command
```

**Comment by Bessonov** [comment]
Ok, for me that are two separate issues/requests. The first one is to change the default behavior to not to save dependencies in `package.json`. I'm still on the path, that I don't see any reason to not to save them, even the npm has another default. The another one is to provide compatibility with explicit flags, even the flags are no-op. TBH, I didn't know about `npm-check`, but it can resolve this [issue](https://github.com/pnpm/pnpm/issues/1012) for us, if it works with `pnpm` monorepos.

**Comment by jsumners** [comment]
It isn’t a noop in npm; npm still supports disabling the auto save feature and has been set so in my settings since the first day they changed the default behavior. The change in pnpm not supporting `—save` and `—save-dev` is causing me much grief due to the sudden change and the lack of compatibility that existed prior to 4.

**Comment by ExE-Boss** [comment]
**pnpm** does support `--save` and `--save-dev`, just not for `uninstall`.

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/69479105-c4d27000-0dc7-11ea-9bdb-2219dd2094dc.png)

@ExE-Boss you were saying?

**Comment by ExE-Boss** [comment]
Well, `--save` is the default.

**Comment by ExE-Boss** [comment]
Actually, I&nbsp;may be&nbsp;thinking about&nbsp;`‑‑save‑prod`.

`‑‑save`&nbsp;and&nbsp;`‑‑no‑save` is&nbsp;#2020.

**Comment by zkochan** [comment]
Allowing `--save` will also allow `--no-save`, which currently has no effect. 

How should `--save-dev` work on uninstall? It should remove the dependency only from dev deps?

**Comment by ExE-Boss** [comment]
> How should `--save-dev` work on uninstall? It should remove the dependency only from dev deps?

Well, that’s&nbsp;what [`npm uninstall ‑‑save‑dev`&nbsp;does](https://docs.npmjs.com/cli/uninstall.html).

**Comment by jsumners** [comment]
> How should --save-dev work on uninstall? It should remove the dependency only from dev deps?

@zkochan correct

**Comment by matt3224** [comment]
I'm also seeing the behaviour
![Screenshot 2019-11-23 at 15 40 26](https://user-images.githubusercontent.com/2401925/69481248-9a080c00-0e07-11ea-88e5-1aa413fdc030.png)

**Comment by ExE-Boss** [comment]
@matt3224 That’s currently the intended behaviour.

**Comment by matt3224** [comment]
@ExE-Boss i don't understand this behaviour, how can i avoid it? I tried defining `"@neuekit/reboot": "1.9.1"` and `"@neuekit/reboot": "^1.9.1"` both give me that error

**Comment by wmertens** [comment]
Could we at least bring back `--save` as a no-op so it doesn't break scripts?

**Comment by marcelcremer** [comment]
I'm also voting for a noop --save instead of saying, that it doesn't exist:
Since I most of the time just copy the "npm install<something>" and paste it after typing a "p". However, since --save throws an error, the command needs to be modified every time again.

**Comment by ExE-Boss** [comment]
That&nbsp;will be&nbsp;somewhat&nbsp;difficult due&nbsp;to&nbsp;how the&nbsp;**pnpm**&nbsp;arguments parser&nbsp;works.

**Comment by marcelcremer** [comment]
I just looked into it because I thought, that might be a quick fix but tbh - I don't understand, what the parser is doing 😂 

I added the option to the nopt options and updated the tests, but after modification the registry parameter is somehow no longer recognized (and I don't even get why it works before modification😒).

Maybe this one is a no-brainer for @zkochan who wrote this?🤞

**Comment by zkochan** [comment]
Adding `save: Boolean` here should do it

https://github.com/pnpm/pnpm/blob/master/packages/plugin-commands-installation/src/add.ts#L64

**Comment by zkochan** [comment]
`pnpm add --save <pkg>` is not failing in [4.5.0](https://github.com/pnpm/pnpm/releases/tag/v4.5.0)

**Comment by jsumners** [comment]
Excellent. What about `pnpm uninstall --save-dev foo`?

**Comment by zkochan** [comment]
That was not done yet. I work on some other features now, so if someone wants to do it, feel free.

**Comment by zkochan** [comment]
Working on the second part

**Comment by zkochan** [comment]
It appears that this functionality (`rm --save-dev|--save-optional|--save-prod`) was already implemented in the installation engine (and even worked with `pnpm -r rm`). I just needed to pass through the options.

**Comment by jsumners** [comment]
Excellent.

**Comment by jsumners** [comment]
Thank you for fixing this.

**Comment by zkochan** [comment]
:ship: 4.7.2
