### ISSUE TITLE
pnpm add -g seems to be completely broken

### ISSUE THREAD

**Issue by gsong** [pnpm/pnpm#2114]
### Code to reproduce the issue:

`pnpm add -g tldr`

### Expected behavior:

For `tldr` command to work.

### Actual behavior:

```sh
$ tldr
tldr not found. Trying with npx...
not found: tldr
```

### Additional information:

 - `node -v` prints: v12.12.0
 - Windows, OS X, or Linux?: macOS 10.14.6

**Comment by ExE-Boss** [comment]
Well, you&nbsp;need the&nbsp;location where the&nbsp;binstubs are&nbsp;located to&nbsp;be&nbsp;on&nbsp;your&nbsp;`$env:PATH`, and&nbsp;you&nbsp;need what&nbsp;you&nbsp;installed to&nbsp;have&nbsp;a&nbsp;`bin`&nbsp;key in&nbsp;its&nbsp;`package.json`

**Comment by zkochan** [comment]
This must be fixed in pnpm v5, since we now always use directories from the PATH, when doing `pnpm add -g`
