### ISSUE TITLE
Windows - is PNPM store recreated in local project folders, are junctions linking to duplicate stores, and where are the hard links?

### ISSUE THREAD

**Issue by gituboi30** [pnpm/pnpm#2124]
_(updated and annotated with factual corrections)_

Installing project dependencies with PNPM results in the project folder `node_modules/` containing junctions with incorrect paths that link to a duplicated store (also in the project folder).

It would be nice to have the correct paths for the junctions so as to help preserve disk space effectively. The duplicate PNPM stores take up extra memory (checked directly in properties of `C:` drive).

### Code to reproduce the issue:

(Git Bash terminal; inside the project folder)
```
# Set up global store path beforehand (double backslash to output escaped characters properly)
npm config set store C:\\Users\\[my_username]\\.pnpm-store
npm config set -g store C:\\Users\\[my_username]\\.pnpm-store

# Install dependencies in local project folder (like the global store, the project is inside the path "~")
pnpm install

# Prints out "/c/Users/[my-username]"
cd ~
pwd
```

### Expected behavior:

- [X] ~Path `[project-path]\node_modules\` should contain junctions that link to the installations of the dependencies in the global PNPM store.~ **Junction folders are used to shorten paths to files (which are actually hard links to the global store)**.

- [X] ~No duplicate store in `[project-path]\node_modules\.pnpm\registry.npmjs.org\` should be created.~ **The folder structure for the global store is somewhat mimicked, but the hard links are the files inside, which ultimately link to the global store.**

- [ ] Running `pnpm store usages [dependency-name]` should correctly show that the dependency is used in project(s).

- [X] Dependencies are usable without issues.

- [X] `store.json` in global store is updated with dependencies (and a list of projects they are used in for each of them).

### Actual behavior:

~- Junctions in path `[project-path]\node_modules\` link to redundantly installed copies of the dependencies in path `[project-path]\node_modules\.pnpm\registry.npmjs.org\` (checked using terminal command `ls -al`).~

~- A duplicate store in `[project-path]\node_modules\.pnpm\registry.npmjs.org\` should be created. There is also a folder `[project-path]\node_modules\.pnpm\` with more junctions that link to the duplicate store.~

- Running `pnpm store usages [dependency-name]` outputs nothing.

- Dependencies are usable without issues.

- `store.json` in global store is updated with dependencies (and a list of projects they are used in for each of them).

### Additional information:

 - `node -v` prints: **v10.17.0**
 - Windows, OS X, or Linux?: **Windows**

The actual behavior is the same with and without the NPM configuration entry for the store path.

**Comment by zkochan** [comment]
> Junctions in path [project-path]\node_modules\ link to redundantly installed copies of the dependencies in path [project-path]\node_modules\.pnpm\registry.npmjs.org\ (checked using terminal command ls -al).

The files in `node_modules/.pnpm` are not copies of the packages from the global store. Those files are hard links. So the files in `node_modules/.pnpm` and in `~/.pnpm-store` are the same physical files. Also see [this](https://pnpm.js.org/en/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store)

**Comment by gituboi30** [comment]
> Those files are hard links.

They are not supposed to be junctions in Windows anymore?

> The files in node_modules/.pnpm are not copies of the packages from the global store. 

Thought so as well at first, but a quick `dir` inside of the local project's `node_modules` directory showed a junction leading to the duplicated store (not the one from the global `.pnpm-store`).

![junction-to-local](https://user-images.githubusercontent.com/34110559/67853429-29095900-fad4-11e9-8386-441e153655bd.JPG)

And in the project's local `.pnpm` directory, all folders are marked as directories (no junctions).

![not-a-junction](https://user-images.githubusercontent.com/34110559/67853530-59e98e00-fad4-11e9-9aba-21abad344071.JPG)

This is the full tree for the local `node_modules` directory (took some time to check each subdirectory; thankfully, only `axios` is installed for this sample project - no junctions that lead outside the local `node_modules` directory exist):

![full-tree](https://user-images.githubusercontent.com/34110559/67853968-20655280-fad5-11e9-8f72-21715afcb276.JPG)

As seen in the second image, the `registry.npmjs.org` directory is a duplicated folder, not a junction.

**Comment by gituboi30** [comment]
> Those files are hard links.

They are not supposed to be junctions in Windows anymore [as per the FAQ's](https://pnpm.js.org/en/faq#does-it-work-on-windows-it-is-harder-to-create-symlinks-on-windows)?

> The files in node_modules/.pnpm are not copies of the packages from the global store. 

Thought so as well at first, but a quick `dir` inside of the local project's `node_modules` directory showed a junction leading to the duplicated store (not the one from the global `.pnpm-store`).

![junction-to-local](https://user-images.githubusercontent.com/34110559/67853429-29095900-fad4-11e9-8386-441e153655bd.JPG)

And in the project's local `.pnpm` directory, all folders are marked as directories (no junctions).

![not-a-junction](https://user-images.githubusercontent.com/34110559/67853530-59e98e00-fad4-11e9-9aba-21abad344071.JPG)

In case it will provide further insight, this is the full tree for the local `node_modules` directory (took some time to check each subdirectory - thankfully, only `axios` is installed for this sample project - no junctions that lead outside the local `node_modules` directory exist):

![full-tree](https://user-images.githubusercontent.com/34110559/67853968-20655280-fad5-11e9-8f72-21715afcb276.JPG)

As seen in the second image, the `registry.npmjs.org` directory is a duplicated folder, not a junction.

**Comment by zkochan** [comment]
That is not a duplicate store. As I mentioned earlier, that folder has hard links (it is called a virtual store). It is needed to allow different sets of dependencies in different projects.

More about this structure [here](https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3)

symlinks/junctions are used inside the virtual store to connect dependencies with dependents. Files in the virtual store are hard links to files in the global store.

**Comment by gituboi30** [comment]
> symlinks/junctions are used inside the virtual store to connect dependencies with dependents. Files in the virtual store are hard links to files in the global store

Thank you for pointing out this distinction - that hard links and junctions are actually both being used. Was under the impression that only junctions are used in Windows and couldn't tell that the folders were hard links (since `cmd` shows them as "directories").

Would be nice to find out a way to check which files/folders in Windows are hard links and to check actual disk usage.

**Comment by zkochan** [comment]
only files are hard links. So directories are regular dirs but files are hard links. You can compare the inode numbers of files in the global/virtual store. They will match. We have tests that also check this

**Comment by gituboi30** [comment]
Can confirm now that the files are indeed hard links by running `fsutil hardlink list [file-name]`.

Thanks again, and I hope this issue ends up helping someone seeking clarity on `pnpm`. This is a great tool, and now all that's left is to learn how to get Windows to show the actual disk space consumption.

**Comment by gituboi30** [comment]
Might have to rename this issue, could be confusing to others....

**Comment by gituboi30** [comment]
`pnpm store usages [dependency-name]` still outputs nothing, though. Might open a separate issue or link to an existing (open one).

**Comment by hinell** [comment]
@zkochan Please, can you clarify the difference between local `package/registry.npmjs.org` and `global` (stored on the root of the disk/partition)? Why is `registry.npmjs.org` created?

I'm experiencing similar issue with `registry.npmjs.org` containing copies of packages, not hardlinks to the store.

I'm using Linux btw.

**Comment by zkochan** [comment]
They are not copies. They are hard links. Maybe you are checking it not correctly

https://pnpm.js.org/en/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store

**Comment by hinell** [comment]
@zkochan Please, can you clarify the difference between `project/node_modules/registry.npmjs.org` and `global` store (stored at the root of the disk/partition)?

I'm experiencing similar issue with `registry.npmjs.org` containing copies of packages, not hardlinks to the global store which is stored at the root/partition (I clearly see that by running `ls -lh`).

I'm using Linux btw:
* Linux  5.3.0-18-generic #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* pnpm: v4.11.4

**Comment by zkochan** [comment]
In different projects, the same dependencies may dependent on different subdependencies. So there cannot be a central location with dependencies and their subdependencies linked in.

For instance, foo has bar@^1.0.0 in dependencies. In one project, bar might be resolved to 1.1.0 and in another one bar might be 1.20.0. So every project must have its own virtual store. Which contains hard links. If the global store is on a different partition then hard links cannot be created and pnpm copies the files.

**Comment by hinell** [comment]
@zkochan I think you have to reflect this in the documentation. A distinction between `global`-wide and `project`-wide (aka `virtual`) `store`s must be clearly made to avoid confusion. It also would be very useful to explain benefits of virtual stores.

>[...] foo has bar@^1.0.0 in dependencies. In one project, bar might be resolved to 1.1.0 and in another one bar might be 1.20.0. 

I've noticed that global storage keeps different versions of the same package. Why not to do the same for higher-level packages that depends on different lower-level ones (like bar@x.x.x in you example)? I think it's completely possible.  

>[...] If the global store is on a different partition

Well all my projects are stored on the same partition. The problem is that I don't need pnpm to save space if I can simply place `node_modules/` at the top of project's root and use it as sorta global storage for the same deps. But here I face another problem: projects may need different dependency version which would either break or bloat (if using aliases) dependencies .

It looks like the latest update ruined the main point of the `pnpm`.
### Questions
1. Can I safely point [`virtual-dir`][virtual-store-dir] configuration into a global store? 
2. Why exactly it's not possible to interlink packages into each other inside global storage and beam (link) each one exactly into a project dependencies folder without copying actual packages' content (assuming the same disk partition)?

[virtual-store-dir]: https://pnpm.js.org/en/npmrc#virtual-store-dir

**Comment by zkochan** [comment]
> Why not to do the same for higher-level packages that depends on different lower-level ones

That would be probably possible as I described in #1001. However, many tools would break as they use the location of the dependency to find the project's root.

>Well all my projects are stored on the same partition.

In that case, if pnpm is not using hard links, then that's the main problem. Create a separate issue and we'll look into that.

> It looks like the latest update ruined the main point of the pnpm.

No, it worked like this from the beginning. The latest update just introduced a config that may change the location of virtual store. The virtual store existed always.

>Can I safely point virtual-dir configuration into a global store?

No, you cannot share a single virtual store between several projects. The virtual store is tightly coupled with the lockfile.

**Comment by hinell** [comment]
>_[...] create a separate issue and we'll look into that_

@zkochan Oh wait. Looks like I was completely mistaken about hard links.
I just have checked  out some of packages inside `virtual-store` and the output was as following:

```bash
$ vdir node_modules/.pnpm/registry.npmjs.org/figures/2.0.0/node_modules/figures
total 20
-rwxrwxrwx 2 user user 2812 Oct 18  2016 index.js
-rwxrwxrwx 2 user user 1119 Aug 15  2014 license
-rwxrwxrwx 2 user user  831 Oct 18  2016 package.json
-rwxrwxrwx 2 user user 4132 Oct 18  2016 readme.md
```

Meaning the files are actually hardlinked.

**Comment by zkochan** [comment]
`pnpm store usages` will be removed from pnpm v5 which will use a content-addressable storage.

ref #2542

**Comment by tadghh** [comment]
Doesnt this defeat the purpose of the disk saving? If windows still thinks X amount of disk is being used you still dont 'have' that space.
