### ISSUE TITLE
Cannot use private GitHub npm repository

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#2127]
### Code to reproduce the issue:

1. `npm login https://npm.pkg.github.com/a-private-org`
2. `npx nrm add github https://npm.pkg.github.com/a-private-org`
3. `nps nrm use github`
4. `pnpm i tap`

### Expected behavior:

`pnpm` will use the stored credentials to authenticate to the GitHub package repository so that the _public_ `tap` package can be installed via the proxy.

It should also be able to install any of the private packages, but the public one exhibits the full issue.

### Actual behavior:

```
 ERROR  401 Unauthorized: tap (via https://npm.pkg.github.com/a-private-org/tap)
```

### Additional information:

 - `node -v` prints: 12.13.0
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
This might be fixed in the latest pnpm, as we have fixed some issues with github registry: https://github.com/pnpm/pnpm/issues/2687

**Comment by jsumners** [comment]
I'll test it out when I'm back to work later in the week.

**Comment by jsumners** [comment]
Can confirm. This is working in `pnpm 5.5.8`. I am able to install the public `tap` package from npmjs.org and a private package from my GH org.

**Comment by ematipico** [comment]
I still get the same issue :(

**Comment by zkochan** [comment]
Create a new issue with the output you get in the console

**Comment by zkochan** [comment]
The new issue appeared to be not an issue on pnpm's side: https://github.com/pnpm/pnpm/issues/2933
