### ISSUE TITLE
Make peerDependenciesMeta imply peerDependencies

### ISSUE THREAD

**Issue by sodatea** [pnpm/pnpm#2128]
The old optional peer dependency proposal is not purely additive. It requires new entries in both  `peerDependencies` and `peerDependenciesMeta`.
However, for clients that haven't adopted this feature (e.g. the buggy npm cli), new entries in `peerDependencies` would bring warnings and frighten end users.
So for library authors, adopting this syntax of optional peer dependencies comes at some cost. For me, I'm not willing to do it until npm officially supports this feature in their implementation.

So, as a workaround, Yarn 2 recently implemented a feature to make the new entries in `peerDependencies` optional: just adding an entry `peerDependenciesMeta` implies a generic peer dependency (on `*`).
This makes the syntax fully compatible with old clients. I think it could be a great way to move forward under the current circumstances.

See also at https://github.com/yarnpkg/berry/pull/531

> **What's the problem this PR addresses?**
> 
> Some projects are concerned about printing warnings to their users, and prefer not to list their peer dependencies to avoid that. We've solved this a while ago with optional peer dependencies, but the [npm registry has a bug](https://github.com/npm/cli/pull/224#issuecomment-524002488) that prevents the npm client to leverage this information (Yarn isn't affected). Because of this, the field adoption is lower than it should be, which hurts the JavaScript ecosystem.
> 
> **How did you fix it?**
> 
> This diff makes the `peerDependenciesMeta` field imply a generic `peerDependencies` (on `*`). This way, even if the npm installs will still suffer from bogus hoisting (because they'll have no idea about the peer dependencies), at least Yarn won't be hit. And if they fix the bug later down the road, they'll directly benefit from `peerDependenciesMeta` being more widespread.

**Comment by zkochan** [comment]
:ship: [4.2.2](https://github.com/pnpm/pnpm/releases/tag/v4.2.2)
