### ISSUE TITLE
The `v4.1.7` tag points to the wrong commit

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#2129]
It&nbsp;points to&nbsp;the&nbsp;same commit as&nbsp;[`v4.1.6`](https://github.com/pnpm/pnpm/releases/v4.1.6), which&nbsp;is&nbsp;incorrect.

**Comment by zkochan** [comment]
The commits seem to be different on releases page
![image](https://user-images.githubusercontent.com/1927579/68075379-99073000-fdaf-11e9-895d-8cf0e8d0023d.png)

**Comment by ExE-Boss** [comment]
NVM, I&nbsp;was&nbsp;looking at&nbsp;the&nbsp;compare&nbsp;link: https://github.com/pnpm/pnpm/compare/v4.1.7...master, which&nbsp;has&nbsp;the&nbsp;same number of&nbsp;commits as&nbsp;https://github.com/pnpm/pnpm/compare/v4.1.6...master.
