### ISSUE TITLE
Hoisting w/ hardlinks in filtered workspaces

### ISSUE THREAD

**Issue by Js-Brecht** [pnpm/pnpm#2131]
### Question regarding behavior

In a workspaces environment, is it possible for pnpm to hoist packages based on a pattern (plus all of their dependencies), using hardlinks, to a specific workspace (or all workspaces 🤔)?

I already know that if you go into a workspace, you can run an install (filtered by that workspace) and hoist specific packages (or using a pattern).  That works fine.  The issue I'm running into is the symlinks... it hoists every dependency/sub-dependency that matches that pattern into the filtered workspace, but they're all just symlinked to the root; which they kind of have to be, since that's where all of those "hoisted package's" dependencies are.

I'm working on some Sharepoint SPFx projects, and it usually works well in a monorepo using pnpm.  Since a recent update, I've started running into issues starting their local workbench server.  The issue is because of how the symlinks cause the server to try to look outside of its working directory, so it is unable to serve the files that it needs.

I like having all of the packages hardlinked into the workspace root `node_modules/.pnpm`.  That works out nicely 90% of the time.  However, there are just a few packages (basically, everything with a pattern '@microsoft/*') that need to be hardlinked directly into the workspace, so that they can be served.  Since those packages need to be present in the server's `node_modules`, their dependencies also need to be present... which is kind of where this turns into a cluster 🤬.

It would be great to be able to do this:
```sh
pnpm m i --hoist-pattern '@microsoft/*/**'

# or maybe

pnpm i --hoist-pattern '@microsoft/*/**' --recursive
```
to get all of those required packages, and their dependencies, hoisted into every workspace's `node_modules` directory that wants them, instead of them being symlinked to the root.

Or maybe a switch that recreates the `node_modules/.pnpm/registry` pattern, but just for packages that match whatever filter, and their dependencies?  That way, it wouldn't actually be "hoisting" packages, per se, since the strictness that pnpm enforces is a good thing, IMO... just localizing them to the workspace.  And the package filter would be kind of a necessity, so you could limit the performance hit.

It would, of course, be great if Microsoft would fix this issue on their end, and I've opened a ticket, but I'm not sure if it's even possible from there end. 

So, I've been investigating workarounds, and this is where I landed.  I was actually able to get the server working, but the process was labor intensive, and the end result was kind of what pnpm already does... just not in a monorepo. 

If you want more information about what I'm dealing with, check out the issue here: SharePoint/sp-dev-docs#4853.

This kind of feature in pnpm would actually work well for fixing another issue in Microsoft's `rush` repository manager... same kind of problem, with a server trying to serve files that are symlinked outside of its working directory.

### Additional information:

 - `node -v`: v10.16.0 (spfx doesn't support anything higher than v10)
 - Windows, OS X, or Linux?: Windows

**Comment by Js-Brecht** [comment]
See https://github.com/Js-Brecht/pnpm-spfx-workspace-issue

**Comment by Js-Brecht** [comment]
After examining some of `pnpm`'s code, I noticed that it stores the `.pnpm` directory in the same directory as the lockfile.  Since I use `shared-workspace-lockfile = true`, all of the dependency sources are in the root `node_modules/.pnpm`.  Changing that to false fixes the issue.

**Comment by Js-Brecht** [comment]
So, I guess now my question is, is it possible to achieve this like I mentioned in my original post, by only "localizing" specific packages?  In effect, creating a shared lockfile, and then a "partial" lockfile in each workspace for dependencies that match the specified pattern?

**Comment by zkochan** [comment]
No, it is currently not possible. You either have a share lockfile and everything is hard linked into the root of the workspace or you have dedicated lockfiles and in that case, the virtual store is hard linked into each workspace package.

**Comment by Js-Brecht** [comment]
That's unfortunate.  Just ran some metrics, and running without a shared lockfile pretty much quadruples the runtime 😞.  Went from 2 minutes to 8.5 minutes.  And that's only with 7 workspaces.   

With the shared dependency tree, there's ~2k dependencies.  Spread out, there's ~1,200 per package, so it's actually having to link ~8,400 packages, instead of the first 2,000 and the dozen or so symlinks it would be making per package with a shared lockfile.  This becomes more painful because there's actually only two workspaces that I need to have their own lockfile.

This is mitigated by the fact that I should only have to run a full repository bootstrap one time.  After that, managing dependencies for each individual workspace is quick and painless.  I would just need to remember that when trying to do a fresh install in just one workspace, I have to use a filter, otherwise it will try to run the full 10 minute install for the whole repo.

So, really, there's not a good reason for putting any time or effort into a new feature like supporting partial lockfiles alongside a shared lockfile.  Not even sure how much work that would be, but it seems to me like it would add quite a bit of complexity.

----

While testing different methods of managing installs, I was trying them with workspace filters: one thing I encountered was that `pnpm run` does not ignore switches after the ` -- `  So, for example, if I wanted to make it easy to filter an installation by the current workspace (this would be when using a shared lockfile); instead of having to type it out all the time, I could make an npm script that looks like this:

```json
"name": "foo-workspace",
"scripts": {
  "inst": "pnpm install --filter foo-workspace"
}
```

Like this, I can do `pnpm run inst -- bar-package`.  However, if I try to do `pnpm run inst -- bar-package -D`, it will error out, saying that `pnpm run` does not understand the switch `save-dev`.  Shouldn't anything after ` -- ` be passed as is to the script that is being executed?  Should I open a new ticket for this?

**Comment by zkochan** [comment]
It should. You may create an issue if it does not work like that
