### ISSUE TITLE
publish changes file mode of package.json

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2146]
### Code to reproduce the issue:

```console
pnpm publish
```

### Expected behavior:

Publish succeeds, `package.json` is not modified by the process in any way.

### Actual behavior:

Publish succeeds, but the file mode of `package.json` is modified. This leaves `package.json` in a "dirty" state that git recognizes as a file change.

```console
diff --git a/packages/alias/package.json b/packages/alias/package.json
old mode 100755
new mode 100644
```

### Additional information:

 - `node -v` prints: 12.3.1
 - Windows, OS X, or Linux?: MacOS Sierra

**Comment by zkochan** [comment]
Isn't this the same as #2125?

**Comment by shellscape** [comment]
Shit. It is. I had a panic today when I thought I hadn't opened an issue. My fault man, carry on. Nothing to see here but my silly brain.
