### ISSUE TITLE
Flag or Setting to Prevent Collapsing Lines in Recursive Commands

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2147]
### Code to reproduce the issue:

Run a recursive command which outputs many lines of text to `stdio`. For example:

```console
$ pnpm run test --filter ./packages/strip --filter ./packages/replace
```

### Expected behavior:

As this is a feature request, there isn't expected behavior. However, it would be outstanding if there was a flag or `npmrc` setting that could disable the collapsed text, as seen below.

### Actual behavior:

```console
packages/strip test$ ava
[8 lines collapsed]
│   ✔ removes expressions in if blocks
│   ✔ removes methods of this
│   ✔ removes super calls
│   ✔ replaces case body with void 0
│   ✔ rewrtestes inline while expressions as void 0
│   ✔ supports object destructuring assignments with default values
│   ✔ removes labeled blocks
│   ✔ removes multiple labeled blocks
│   ✔ only removes specified blocks
│   17 tests passed
└─ Done in 977ms
```

Note the `[8 lines collapsed]` portion of the console output above. 

### Additional information:

 - `node -v` prints: 12.3.1
 - Windows, OS X, or Linux?: Mac OS

**Comment by zkochan** [comment]
You may use the `--reporter append-only` option. But I would not recommend it setting in `.npmrc` because it will also change the reporting of other commands

**Comment by shellscape** [comment]
I'll give that a shot and report back

**Comment by WhiteR4bbitt** [comment]
I was looking for the same thing, as I have a few projects running, I can not tell what is going on:
![image](https://user-images.githubusercontent.com/5930847/78417305-f832d000-75ed-11ea-8673-a2866556d994.png)

and I tried to run it with `--reporter append-only` which it responds with:
![image](https://user-images.githubusercontent.com/5930847/78417309-008b0b00-75ee-11ea-9d54-9d0de36288e7.png)

It looks like this option is only documented on the [`install` command](https://pnpm.js.org/en/cli/install#reporter-lt-name)

## Commands used
`pnpm run dev -r --reporter append-only`
`pnpm run dev -r --no-bail --no-sort --reporter append-only --filter ./apps`
`pnpm recursive run dev --no-bail --no-sort --reporter append-only --filter ./apps`

## Versions used
```
pnpm 4.12.1 // I updated it to this after running -v
pnpm 4.12.4  // I ran the commands above after updating as well
````

**Comment by zkochan** [comment]
@WhiteR4bbitt that is a regression. `--reporter` will work in the next pnpm version with all commands

**Comment by zkochan** [comment]
Use the `stream=true` option since pnpm v5.1.0
