### ISSUE TITLE
Option for disabling: "pnpm i" in a workspace is "pnpm i -r"

### ISSUE THREAD

**Issue by morganfree** [pnpm/pnpm#2150]
After upgrade to `pnpm@4` `pnpm install` installs all packages inside a workspace.
Is there an option to disable this behavior so `install` will work as in the `pnpm@3`?

Do I need to change something in the `.npmrc` or `pnpm-workspace.yaml`?

**Comment by zkochan** [comment]
This is currently not configurable. You can use filters to scope the command to a single workspace package.
