### ISSUE TITLE
ERROR  EPERM: operation not permitted, rename <folder>

### ISSUE THREAD

**Issue by Dionysusnu** [pnpm/pnpm#2155]
### pnpm version:
4.2.2
### Code to reproduce the issue:
running `pnpm update` from an administrator command prompt

[pnpm-debug.log](https://gist.github.com/Dionysusnu/61f914cce1cb6810597b1457c6579b51)

### Expected behavior:
packages update/get moved correctly without error
(trying to test my library which builds with a `prepare` script)
### Actual behavior:
fatal error
```
 ERROR  EPERM: operation not permitted, rename 'C:\Users\dionn\Programming\TSBlox\node_modules\@typescript-eslint\eslint-plugin' -> 'C:\Users\dionn\Programming\TSBlox\node_modules\.ignored\@typescript-eslint\eslint-plugin'
```
### Additional information:
Asked about this in [older thread](https://github.com/pnpm/pnpm/issues/1015), but was told to make a new issue
 - `node -v` prints:
v10.16.0
 - Windows, OS X, or Linux?:
Windows 10

**Comment by zkochan** [comment]
Seems like you have some packages in node_modules that were installed by npm. pnpm tries to move these packages to `node_modules/.ignored` and that's when it fails. You can try manually removing node_modules and running `pnpm update` then.

**Comment by Dionysusnu** [comment]
I got it working a while ago, but forgot to close this. Sorry for that. It's weird that it fails though, because the CMD prompt was launched as admin and has all permissions etc.
