### ISSUE TITLE
pnpm add uses workspace package by default, unexpected

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2157]
### Code to reproduce the issue:

```console
→ pnpm add @rollup/plugin-json
```

### Expected behavior:

This may be a documentation issue. But what I expected to happen here is that `pnpm add` would default to adding a module from the registry. We're working in a monorepo that doesn't couple dependencies to the workspace, even with the module being added existing in the workspace. It's very loosely coupled. I couldn't find documentation that explained that this was the default behavior, nor a way to turn that off.

I've tried to work around this by specifying my own version range in the meantime, but that didn't work as expected either. Is there no way to force the CLI to install a dependency from the registry, short of adding the entry manually into `package.json`?

```console
→ pnpm add @rollup/plugin-json@^4.0.0
../..                                    |   +7 +
../..                                    | Resolving: total 142, reused 142, downloaded 0, done

dependencies:
+ @rollup/plugin-json 4.0.0 <- ../json
```

This is a pretty big usability and documentation hole. If it's documented somewhere on the site, then it should be copied to https://pnpm.js.org/en/cli/add, since that will be users' first stop. The CLI could also use better UX to notify the user that the dependency was installed from workspace. I would have missed the `<- ../json` bit in the output had I not seen that `package.json` was updated with `workspace:^4.0.0`.

### Actual behavior:

```console
../..                                    |   +7 +
../..                                    | Resolving: total 142, reused 141, downloaded 0, done

dependencies:
+ @rollup/plugin-json 4.0.0 <- ../json
```

### Additional information:

 - `node -v` prints: 12.3.1
 - Windows, OS X, or Linux?: OSX

**Comment by zkochan** [comment]
https://pnpm.js.org/en/workspaces#link-workspace-packages

> link-workspace-packages
> When true, locally available packages are linked to node_modules instead of being downloaded from the registry. This is very convenient in a multi-package repository.

**Comment by shellscape** [comment]
That should really be prominent in the `pnpm add` page documentation. I would have never thought to look at `.npmrc` settings for that.

But that doesn't address the need to do _both_. It really doesn't feel right that it's workspace _or_ registry, and toggling that setting each time that needs to be done isn't very user friendly. There's room for improvement on this one.

**Comment by zkochan** [comment]
If you make this `false`, you can still install dependencies with the [`workspace:` protocol](https://pnpm.js.org/en/workspaces#workspace-ranges-workspace).

**Comment by shellscape** [comment]
> If you make this false, you can still install dependencies with the workspace: protocol.

👏  Excellent. But let's improve the docs so people don't have to have prior knowledge before connecting the dots.

Under `Workspace Ranges`, can we add:

```md
When this protocol is used pnpm will refuse to resolve to anything else than a local workspace package. If setting the `link-workspace-packages = false` as described below, this protocol can be used to force linking to a workspace package, rather than installing from the registry.
```

Under the `link-workspace-packages` section, can we add:

```md
When `false`, packages are downloaded and installed from the registry. However, workspace packages can still be linked by using the `workspace:` range protocol. e.g. `pnpm add batman@workspace:*`
```

On https://pnpm.js.org/en/cli/add, we need another section, preferably before `Options`. Something like:

```md
## Workspaces

Note that when adding dependencies and working within a workspace, packages will be installed from the configured sources, depending on whether or not [`link-workspace-packages`](link) is set, and use of the [`workspace:`](link) range protocol.
```

That ties everything neatly together, gives users multiple ways to discover the information, and leaves no gaps or excuses for missing how they are interlinked.

**Comment by zkochan** [comment]
you can submit edits to the pages. I'll merge them

**Comment by shellscape** [comment]
Will do

**Comment by zkochan** [comment]
I am adding `pnpm audit` to the docs, so I'll add this as well.

**Comment by shellscape** [comment]
I can still totally do that work. It's #2 behind one more Rollup task. Will probably get to it tomorrow afternoon if you'd rather not take that one.

**Comment by zkochan** [comment]
That's fine, just review my changes and submit edits if needed
