### ISSUE TITLE
pnpm prune has no effect

### ISSUE THREAD

**Issue by fengerzh** [pnpm/pnpm#2160]
My `pnpm prune` seems not work now. Everytime I run `pnpm prune`, it will report some old packages with red minus before the package name, which I think means these packages are out of time, and should be deleted. Just like below:

```
- which 1.3.1
- widest-line 2.0.1
- word-wrap 1.2.3
- worker-farm 1.7.0
- wrap-ansi 6.2.0
- wrappy 1.0.2
- write 1.0.3
- write-file-atomic 2.4.3
- write-json-file 2.3.0
- ws 6.2.1
- xdg-basedir 3.0.0
- xmlbuilder 13.0.2
- xtend 4.0.2
- xxhashjs 0.2.2
- y18n 4.0.0
- yallist 2.1.2
```

But pnpm won't delete them, just list out. If you run `pnpm prune` again, it still show these packages. I've also gone to the folder `.pnpm-store/2/registry.npmjs.org/yallist` to check, the old version package did exist there.

```
~/.p/2/r/yallist> ls
2.1.2      3.0.3      3.1.1      4.0.0      index.json
```

Could you please help to verify? Thanks!

**Comment by zkochan** [comment]
`pnpm prune` will not remove anything from the store. So `.pnpm-store/2/registry.npmjs.org/yallist` will not be removed. `pnpm prune` only removes dependencies from `node_modules`.

To prune the store, run `pnpm store prune`.

**Comment by zkochan** [comment]
Seems like there's an issue with `pnpm prune` on projects that use `shamefully-hoist=true`. `pnpm prune` will remove the hoisted dependencies (which it shouldn't), and then it will rehoist them again.

**Comment by zkochan** [comment]
Fixed in scope of https://github.com/pnpm/pnpm/pull/4691

**Comment by cbelsole** [comment]
@zkochan Should this language be removed?

<img width="1017" alt="image" src="https://github.com/pnpm/pnpm/assets/3340414/1295d822-a10b-4c69-bab1-a5aa9d5a227d">
