### ISSUE TITLE
Hooks modify package.json inside a monorepo

### ISSUE THREAD

**Issue by morganfree** [pnpm/pnpm#2164]
### Code to reproduce the issue:
```
.
├── package.json
├── packages
│   └── package.json
├── pnpm-workspace.yaml
└── pnpmfile.js

1 directory, 4 files
```

`.npmrc`
```
save-exact = true
hoist = false
link-workspace-packages = false
shared-workspace-lockfile = false
```
`pnpm-workspace.yaml`
```
packages:
  - 'packages/**'
```

`pnpmfile.js`
```
function readPackage( pkg ) {
  delete pkg.dependencies.lodash;

  return pkg;
}

module.exports = {
  hooks: { readPackage }
};
```

`./packages/package.json`
```
{
  "name": "packages",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "4.17.15"
  }
}
```

`pnpm install`

### Additional information:

 - `node -v` prints: 10.16.3
 - Windows, OS X, or Linux?: OS X

**Comment by Bessonov** [comment]
I had a discussion about it on gitter. It would be nice to control when `package.json` should be save in the hook. But the feedback was that it's very difficult to implement.

**Comment by zkochan** [comment]
I can look into it but I am not even sure what is the expected behaviour here.

Does it make sense to not save the changes that the install hook makes to the project manifests?

cc @pnpm/collaborators

**Comment by zkochan** [comment]
To be clear, I also need a way to modify the manifests of projects without saving the changes.

Specifically, I want to have [an alternative modules directory](https://github.com/pnpm/pnpm/issues/2471) where some of the dependencies are substituted. And I don't want this substitutions in the original `package.json` file. At first I was thinking about doing it with a pnpmfile and I realized that it saves the changes. Now I wonder if that's good or not.

**Comment by znck** [comment]
I would prefer not saving changes to `package.json`. I am using `pnpmfile.js` because I don't want the resolved package/fork in the `package.json`.

**use case:** I want to use `typeorm` as it is except for running tests I need a patched copy which I've put at `znck/typeorm` repo.

**Comment by aparajita** [comment]
For me hooks modifying package.json is quite unexpected behavior. Conceptually (to me at least) a hook is something that modifies existing behavior at runtime without any side effects. If you run a hook, then remove it, and the effect of the hook is still there, it is no longer a hook.
