### ISSUE TITLE
Rollup Build and Dependency Mystery

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2165]
### Code to reproduce the issue:

Check out https://github.com/rollup/plugins/commit/f0055330af3e3f83ed073ae3cfa5f2b6ddfe6f59 on the `add/utils` branch.

- `pnpm install`
- `cd packages/utils`
- `pnpm run build`

### Expected behavior:

We should see a successful build. e.g.

```console
src/index.ts → dist/index.js, dist/index.es.js...
created dist/index.js, dist/index.es.js in 1.5s
```

### Actual behavior:

The build fails citing a module resolution issue. Normally I'd chalk this up to a problem with the rollup configuration, but I've spend considerable time ruling that out. Rather, this looks like it might be a package installation problem specific to `pnpm`. I made that conclusion after running the same process with `npm` without issue:

- `rm -rf node_modules`
- `npm install`
- `npm run build`
- succeeds

### Additional information:

 - `node -v` prints: 12.3.0
 - Windows, OS X, or Linux?: OSX

**Comment by zkochan** [comment]
This works

```ts
import mm = require('micromatch');
```

Have you tried playing with TypeScript configuration? I know there's this `allowSyntheticDefaultImports` config. Maybe it could help

**Comment by shellscape** [comment]
I'll give that a try, but it doesn't explain why it works with `npm`s install method, and doesn't work with `pnpm`s. I'd like to get to the crux of that. If there's a small difference in `pnpm` that might be an opportunity for improvement, or in the opposite direction, it might be `rollup-plugin-resolve` that can't handle something `pnpm` is doing. I'm just not an expert on `pnpm`s data structures.

**Comment by shellscape** [comment]
I gave that option a shot, but `tsc` did not allow it with that module:

```console
3 import mm from 'micromatch';
         ~~

  ../../node_modules/.pnpm/registry.npmjs.org/@types/micromatch/3.1.1/node_modules/@types/micromatch/index.d.ts:625:1
    625 export = micromatch;
        ~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.
```

Talking with my fellow rollup core folks and they suspect it could be an issue with symlinks. Apparently there's history there to support that. I'd like to keep this open to track the issue. If you have an 'upstream' label or some such, please feel free to apply it.

**Comment by shellscape** [comment]
We've managed to track down what the issue is. It _is_ an issue with how pnpm structures `node_modules` versus other monorepo supporting package managers, to a degree, but it's not something that needs to be fixed.

It's actually a problem with the `rollup-plugin-commonjs` plugin while working with pnpm. Because pnpm's root `node_modules` _and_ the package `node_modules` contain symlinked modules, the old standby fix of using a different `include` value (as [laid out here](https://github.com/rollup/rollup-plugin-commonjs#usage-with-symlinks)) doesn't work. Instead, Rollup builds with these types of dependencies need to add `preserveSymlinks: true` to the rollup config.

Once that property was added, the build works fine with pnpm's `node_modules` structure. Another crazy one for a future FAQ or lost soul searching Google. :smile:

**Comment by zkochan** [comment]
this is unusual. I think this might be just a workaround that hides another issue. Normally, preserve symlinks should be false in order for bundler to work properly. I remember browserify had to change a similar option to be compatible with pnpm.

**Comment by shellscape** [comment]
Alternatively, we can `include` the realpath of the registry:

```js
    commonjs({ include: '../../node_modules/.pnpm/registry.npmjs.org/**' }),
```

And that works for the build. But it struggles with the symlinks something awful.
