### ISSUE TITLE
Disable adding workspace: range when installing

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2166]
### pnpm version: 4.3.0

When having a workspace setup like this:

`pnpm-workspace.yaml`
```yaml
packages:
  - 'packages/*'
```

`folder setup`
```
/packages/a
/packages/b
```

Where `b` depends on `a`.

Executing `pnpm update a --filter "b"` updates the `package.json` of `b` like this:

```json
{
  "name": "b",
  "version": "1.0.3",
  "dependencies": {
    "a": "workspace:^1.0.2"
  }
}
```

When I now run `pnpm publish` in `b`, the `workspace:^1.0.2` is also published.
However, I can't rely on my users using a package manager that supports the `workspace:` syntax, so I would like that to be stripped away for publish time.

Is that possible today already?

From my understanding, the [current options](https://pnpm.js.org/en/workspaces) don't support that yet.
Thanks!

**Comment by zkochan** [comment]
Are you sure you did not run `npm publish`? `pnpm publish removes the `workspace:` from `package.json` before publish

**Comment by timsuchanek** [comment]
Well that was a fast reply 😅 I'll double check.

**Comment by timsuchanek** [comment]
Was indeed using `yarn publish` 🙈 
Thanks for the ultra fast response and clarification on this, I was not sure if pnpm does it / should do it.

**Comment by foisonocean** [comment]
@zkochan 
I hope there could be an option to disable the behavior of adding the `workspace:` prefix. Currently my team also use [semver](https://www.npmjs.com/package/semver) to to some check of the version range, and this `workspace:` prefix is not compatible with semver (or not compatible with the standard semantic versioning)

**Comment by zkochan** [comment]
Seems like it was not added to the docs but there is a setting you can set to false: save-workspace-protocol
