### ISSUE TITLE
Add `--scope` to `pnpm update`

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2167]
We're publishing all our workspace related packages under a specific namespace, in our case `@prisma`.

Now when bumping and updating all packages in the workspace while doing a new release, we use `pnpm update @prisma/dep1 @prisma/dep2 --filter "@prisma/my-package"`.

Coming from yarn, there is a convenient option called `--scope` for this situation: https://yarnpkg.com/lang/en/docs/cli/upgrade/#toc-yarn-upgrade-scope-s-scope-latest-pattern

The above statement could be written as `pnpm update --scope @prisma --filter "@prisma/my-package"`.

Is something like this planned?

Thanks!

**Comment by zkochan** [comment]
We'll probably support something like `pnpm update @prisma/*`

**Comment by timsuchanek** [comment]
That sounds great! Would even be more elegant 👍

**Comment by zkochan** [comment]
Also, this seems like related #1918

**Comment by zkochan** [comment]
:ship: 4.9.0-3
