### ISSUE TITLE
Allow "force update" when workspace packages are out of sync

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2170]
When having a workspace with a couple of packages, let's say `a` and `b` and executing

```
pnpm update --filter "a"
```

This will add an entry like so in the `package.json` of `a`:

```json
{
  "dependencies": {
    "b": "workspace:0.1.2"
  }
}
```

However, as soon as I now change the version of `a` let's say to `0.2.1`, I'm not able to perform `pnpm update --filter "a"` anymore:

```
ERROR  No matching version found for b@0.1.2 inside the workspace
```

How can I get out of this situation without manually changing the version of `a` in `b`?

One way I could imagine is basically a `update --force`, or maybe `update --auto-fix-workspace` to make sure that local workspace deps work.

Another option, which would work for me, would be this:
```
    "b": "workspace:*"
```

Thanks!

**Comment by zkochan** [comment]
Have you tried this? It was already done #2085

`pnpm update --filter a` should update b

**Comment by timsuchanek** [comment]
Yes I saw that one.
So should I basically changing it to `"workspace:*"` by hand?
That works. 

However, I have to go into every single package now and change that by hand, as all of them got out of sync.
It would be great to be able to set the default behavior of `update` to use `workspace:*`

![image](https://user-images.githubusercontent.com/1094804/69230106-f7d9f100-0b86-11ea-9ae8-517e4f2976e3.png)

**Comment by timsuchanek** [comment]
I now get this problem, even though `@prisma/photon` is part of my workspace:
```
 ERROR  No matching version found for @prisma/photon@* inside the workspace
```
That is probably a bug I guess? I would need to work on an isolated repro thne.

**Comment by timsuchanek** [comment]
Ok found the problem. This version is not supported: `2.0.0-alpha.323` - then it says it's not able to find it in the workspace. Hmm having this one fixed would be pretty important to us. Could you point me to where one would do a fix for that? I may create a PR then.

**Comment by zkochan** [comment]
This was fixed as far as I understand
