### ISSUE TITLE
`pnpm update` doesn't resolve pre releases

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2171]
This is just a tracking issue for what I described in https://github.com/pnpm/pnpm/issues/2170 so that it can be referenced in a PR.

To summarize the situation again:
I have a package called `@prisma/photon`. Its version is `2.0.0-alpha.123`.

The package `@prisma/lift` depends on it. Its entry looks like this:
```
"@prisma/photon": "workspace:*"
```

When executing
```
pnpm update --filter "@prisma/photon"
```
I get the following error:

```
 ERROR  No matching version found for @prisma/photon@* inside the workspace
```

But as `*` is provided, imo that should work.

**Comment by zkochan** [comment]
:ship: 4.3.1

**Comment by zkochan** [comment]
that might be a broken version. Probably caused by the commands refactoring. The build did not pass with this version

**Comment by zkochan** [comment]
:ship: 4.3.2

**Comment by tunnckoCore** [comment]
Seems like it still doesn't work. Yea, I'm on `4.3.2` from the `next` dist tag.

On the root package.json I have (because it seems Pnpm doesn't link bins from workspace packages?) 

```
"@hela/cli": "workspace:^3.0.0-canary.3"
```

run

```
~/github/tunnckoCore/hela next*
❯ pnpm up             
Scope: current workspace package
 ERROR  No matching version found for @hela/cli@* inside the workspace
```

**Comment by zkochan** [comment]
@tunnckoCore you are right... For some reason, `@pnpm/npm-resolver` did not recompile before publish, so 4.3.2 does not have the fix

**Comment by zkochan** [comment]
Hm, I wonder if [this](https://github.com/npm/npm/issues/15454) was fixed by npm... Probably this is the reason why the published package has old code

**Comment by timsuchanek** [comment]
Note, that there are a bunch of other `semver.maxSatisfying` statements in the code, depending on what your setup is, they may also have to be updated.

I can just confirm that this fixed it for my setup (by linking to my locally built pnpm)

**Comment by zkochan** [comment]
4.3.3 should work

**Comment by tunnckoCore** [comment]
Yup, it works.
