### ISSUE TITLE
Object literal may only specify known properties, and 'schema' does not exist in type 'ApolloServerExpressConfig'

### ISSUE THREAD

**Issue by hemedani** [pnpm/pnpm#2175]
### pnpm version:
```bash
> pnpm -v
4.3.0
````
### Code to reproduce the issue:
```typescript
  const schema = await buildSchema({
    resolvers: [__dirname + "/modules/**/*.resolver.ts"]
  });

  // Create the GraphQL server
  const apolloServer = new ApolloServer({
    context: ({ req }: any) => ({ req }),
    schema // it's not recognized schema as a property for ApolloServer and also other property like introspection
  });
```

it has this types :
<img width="637" alt="Screen Shot 1398-08-28 at 17 36 16" src="https://user-images.githubusercontent.com/6236123/69153254-25755a80-0af3-11ea-8ae7-863841790911.png">

and conifg has thees type :
<img width="756" alt="Screen Shot 1398-08-28 at 17 37 23" src="https://user-images.githubusercontent.com/6236123/69318855-48b71b80-0c53-11ea-9a73-c2c659ed87a1.png">

### Expected behavior:
accepted schema as valid property for ApolloServer || find installed node_modules on pnpm root workspace inside packages node_modules 

<img width="1500" alt="Screen Shot 1398-08-28 at 17 24 09" src="https://user-images.githubusercontent.com/6236123/69152692-248ff900-0af2-11ea-88f7-102e1f3950f5.png">

### Actual behavior:
actually is get Apollo Server types from local node_modules and in local node_modules can't find `apollo-server-core` installed on workspace

<img width="751" alt="Screen Shot 1398-08-28 at 17 25 44" src="https://user-images.githubusercontent.com/6236123/69152822-60c35980-0af2-11ea-8724-33cf2333264a.png">

### Additional information:

my `.npmrc` file has `shamefully-hoist=true`

```bash
> node -v
v10.16.3

> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: AbrFA
      User Name: Syd (syd)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 6:48

> 
```

**Comment by zkochan** [comment]
> my .pnpm.rc file has shamefully-hoist=true

pnpm reads the settings from `.npmrc`, so that's where you should put it

**Comment by hemedani** [comment]
I have my settings in `.npmrc` file . it just a wrong typo in this issue

**Comment by hemedani** [comment]
it's a tiny clone of my [project on GitHub]( https://github.com/hemedani/satek-test)

after a `pnpm install` when we get to `packages/server` and enter `pnpm start` commands it's throw above error

**Comment by hemedani** [comment]
@zkochan please [clone my repo](https://github.com/hemedani/satek-test) and see if you can solve this problem

**Comment by zkochan** [comment]
I have limited time until next week

SydAmir <notifications@github.com> ezt írta (időpont: 2019. dec. 3., K
20:11):

**Comment by hemedani** [comment]
so i wait for it until next week

**Comment by zkochan** [comment]
I checked but I don't know what causes the typescript issue. pnpm installed everything correctly. Maybe it is an issue on typescript's end.

**Comment by hemedani** [comment]
tanks for your answers...

this error also happens whiteout monorepo.

**Comment by hemedani** [comment]
anything new about this ...

**Comment by hemedani** [comment]
i check again this error in version 4.9.1 and solved the issues, so close this if @zkochan allowed me
