### ISSUE TITLE
Store file index.json is missing

### ISSUE THREAD

**Issue by mdatsev** [pnpm/pnpm#2176]
### Code to reproduce the issue:
```
$ cd project1
$ pnpm install -r
$ cd project2
$ pnpm install --offline
ERROR  Failed to resolve busboy@>=3.1.0 <4.0.0 in package mirror /usr/share/pnpm-store/2/registry.npmjs.org/busboy
```
### Expected behavior:
I expect to be able to install dependencies of one project, then they get stored in the store, and then to be able to install with `--offline` in another project.
### Actual behavior:
I get an error `ERROR  Failed to resolve busboy@>=3.1.0 <4.0.0 in package mirror /usr/share/pnpm-store/2/registry.npmjs.org/busboy`.
### Additional information:
I suspect that the problem is with this file: `pnpm-store/2/registry.npmjs.org/busboy/index.json`. Usually it is created upon installation, but is missing sometimes (when I install deps for a large project). I think the function pickPackage is not called at all for this dependency.
What could possibly be a reason for this file to not be created?
Tree:
```
/usr/share/pnpm-store/2/registry.npmjs.org/busboy
└── 0.3.1
    ├── integrity.json
    ├── node_modules
    │   └── busboy
    │       ├── deps
    │       │   └── encoding
    │       │       ├── encoding-indexes.js
    │       │       └── encoding.js
    │       ├── lib
    │       │   ├── main.js
    │       │   ├── types
    │       │   │   ├── multipart.js
    │       │   │   └── urlencoded.js
    │       │   └── utils.js
    │       ├── LICENSE
    │       ├── package.json
    │       ├── README.md
    │       └── test
    │           ├── test.js
    │           ├── test-types-multipart.js
    │           ├── test-types-multipart-stream-pause.js
    │           ├── test-types-urlencoded.js
    │           ├── test-utils-decoder.js
    │           └── test-utils-parse-params.js
    ├── package -> node_modules/busboy
    └── packed.tgz

9 directories, 17 files
```
 - `node -v` prints: v12.8.1
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
> What could possibly be a reason for this file to not be created?

That file is created on the resolution stage. If the project has a lockfile, the resolution stage is skipped.

**Comment by l-abels** [comment]
I am encountering this issue in one of my projects.  Shouldn't `pnpm install --offline` perform the resolution step when no lockfile is present?  

The description of this flag would imply that it fails when dependencies are not already in the store, but what actually happens is that it fails if it has to perform resolution even when all the packages are in the store.

**Comment by zkochan** [comment]
This file is not used anymore in pnpm v5
