### ISSUE TITLE
webpack can't file module installed via pnpm

### ISSUE THREAD

**Issue by watjurk** [pnpm/pnpm#2184]
### Code to reproduce the issue: 
https://github.com/wiwi1212/pnpm-issue, run "pnpm install" and then gulp, if gulp is not working run "npm i -g gulp". The exact rule that causes error is at "config/webpack/rules.js" line 13

### Expected behavior: 
no error

### Actual behavior: error: 
"Error: Cannot find module "@babel/plugin-proposal-object-rest-spread"

### Additional information: 
webpack app when dependencies are installed via pnpm error occurs when webpack tries to load "@babel/plugin-proposal-object-rest-spread" module, when via yarn i have no error

 - node -v: v13.1.0
 - OS X

**Comment by pfrancug** [comment]
I have similar problem with webpack, pnpm cannot install last package of it while npm works fone.

### pnpm-debug.log:
[https://pastebin.com/w9MLpVMW](url)

- noce -v: v12.13.1
- pnpm -v: 4.3.3
- Windows 10 1903

**Comment by zkochan** [comment]
The repro repo is not available anymore. If this still happens with the latest pnpm, then just use the [node-linker=hoisted](https://pnpm.io/npmrc#node-linker) setting.
