### ISSUE TITLE
package.json dependencies of a module are not installed

### ISSUE THREAD

**Issue by milottit** [pnpm/pnpm#2186]
npm version: 4.3.0
Code to reproduce the issue: ```pnpm add firebase```

behavior: dependencies of firebase should be installed in `node_modules/firebase/node_modules` as pnpm is not flattening modules.

### Actual behavior:

Nothing is installed in firebase module

### Additional information:

 - `node -v` prints: v12.7.0
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
the dependencies of firebase are one level up from the real location of firebase. You can read about it here https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3

The article is just a bit outdated. The `.registry.npmjs.org` dir was renamed to `.pnpm/registry.npmjs.org`

**Comment by milottit** [comment]
Yes you are right. My bad, I had my bundler configuration with `preserveLink = true`. When changing from npm or yarn, some suprises can happen.
