### ISSUE TITLE
Updating package versions without being told to do so

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#2188]
### Code to reproduce the issue:

Create a `package.json`:

```json
{
  "dependencies": {
    "dotenv": "^8.0.0"
  }
}
```

Next, run `pnpm i abstract-logging`.

### Expected behavior:

The `abstract-logging` package will be added to the dependencies at `^2.0.0` and the version of `dotenv` **will not be changed**.

### Actual behavior:

`abstract-logging@2.0.0` is added to the dependencies and `dotenv`'s minimum version is updated to `8.2.0`.

### Additional information:

 - `node -v` prints: 12.13.1
 - Windows, OS X, or Linux?: OS X

**Comment by Djaler** [comment]
@zkochan can you check this please?

**Comment by zkochan** [comment]
Looking into it

**Comment by jsumners** [comment]
Thank you.

**Comment by zkochan** [comment]
:ship: [4.5.0](https://github.com/pnpm/pnpm/releases/tag/v4.5.0)
