### ISSUE TITLE
Unpredictable transitive dependencies update

### ISSUE THREAD

**Issue by Djaler** [pnpm/pnpm#2191]
### Reproduction:

1. Dependency `A` on version `1.0.0`
Dependency `B` with transitive dependency `C`: `^1.0.0` (locked as `1.0.0` in pnpm-lock.yaml, but `1.1.0` is available in repo)
2. Change `A` version to `1.0.1`
3. Run `pnpm install`

### Expected behavior:
Only `A` version changed in pnpm-lock.yaml. This is how npm works.

### Actual behavior:
`A` version changed in pnpm-lock.yaml **and** `C` version changed to `1.1.0`.
This was very unexpectedly for me. Also, this cause to so many merge conflicts from renovatebot PRs, because every single updated package also update all transitive dependencies

### Additional information:

 - `node -v` prints: v10.17.0
 - Windows, OS X, or Linux?: Linux

**Comment by Djaler** [comment]
You can see that in your repo too. For example, that commit: https://github.com/pnpm/pnpm/commit/31a701579c605f5273b6abfb15ae59b52dbb9053. You only change `@types/http-proxy-agent` version, but `ts-toolbelt` was updated too without any reason

**Comment by Djaler** [comment]
@zkochan can you check this please?

**Comment by zkochan** [comment]
I'll check

Kirill Romanov <notifications@github.com> ezt írta (időpont: 2019. dec.
11., Sze 14:57):

**Comment by zkochan** [comment]
:ship: [4.5.0](https://github.com/pnpm/pnpm/releases/tag/v4.5.0)
