### ISSUE TITLE
pnpm run-script no longer supports --if-present flag

### ISSUE THREAD

**Issue by josephschmitt** [pnpm/pnpm#2200]
### Code to reproduce the issue:
```
pnpm run some-script --if-present
```

### Expected behavior:
If the script exists in the package.json scripts, it runs it. If not, it does nothing. This is how `npm` itself works: https://docs.npmjs.com/cli/run-script and is useful in a ci context where you want to run a script you're not sure is defined.

### Actual behavior:
```
ERROR  Unknown option 'if-present'
```

### Additional information:
This was working in previous versions of pnpm before 4.x.x. I looked through the [release notes of 4.0.0](https://github.com/pnpm/pnpm/releases/tag/v4.0.0) and nowhere in the breaking changes was the removal of this option documented, so I'm assuming it's a bug and not an intentional removal.

 - `node -v` prints: Happens in all node versions
 - Windows, OS X, or Linux?: So far tested on macOS and Linux, but seems to happen on all platforms.

**Comment by zkochan** [comment]
:ship: [4.5.0](https://github.com/pnpm/pnpm/releases/tag/v4.5.0)

**Comment by josephschmitt** [comment]
@zkochan you’re the best!
