### ISSUE TITLE
Installing a package globally results in a mysterious error

### ISSUE THREAD

**Issue by ghost** [pnpm/pnpm#2218]
### Code to reproduce the issue:

`pnpm i -g pnpm`
```
{
  "0 error pnpm": {
    "message": {
      "errno": -2,
      "code": "ENOENT",
      "syscall": "mkdir"
    },
    "err": {
      "name": "Error",
      "message": "ENOENT: no such file or directory, mkdir",
      "code": "ENOENT",
      "stack": "Error: ENOENT: no such file or directory, mkdir"
    }
  }
}
```

### Expected behavior:

Installs pnpm globally via pnpm

### Actual behavior:

Throws mysterious ` ERROR  ENOENT: no such file or directory, mkdir`

### Additional information:

 - `node -v` prints: `v12.13.1`
 - Windows, OS X, or Linux?: Linux 5.4.2 on Elementary OS 5.1 (Ubuntu 18.04?)

**Comment by makmm** [comment]
Setting a prefix fixed it. Shouldn't it return a better error?

**Comment by Adam-Burke** [comment]
> Setting a prefix fixed it. Shouldn't it return a better error?

Can you explain what you mean by prefix. I'm getting the same issue.

**Comment by rginnow** [comment]
@Adam-Burke apparently pnpm looks for a specific prefix in the config, but it doesn't fallback on the original npm prefix (global directory)

This fixed it for me:
```
# output the global directory
>$ npm config get prefix
/home/MYUSER/.npm-global

# make sure pnpm matches
>$ pnpm config get prefix
/home/MYUSER/.npm-global

# check pnpm specific prefix (may return undefined!)
>$ pnpm config get pnpm-prefix
undefined

# if undefined, set the prefix for pnpm
>$ pnpm config set pnpm-prefix /home/MYUSER/.npm-global

# then run your install
>$ pnpm i -g pnpm
```

**Comment by zkochan** [comment]
This should not be an issue with pnpm v7.
