### ISSUE TITLE
All packages are updated when running 'pnpm update <package>'

### ISSUE THREAD

**Issue by stefano-b** [pnpm/pnpm#2226]
This is possibly related to #2193 and other similar bugs.

Tested on the latest `4.5.0` version, when running `pnpm update <package>`, all packages are updated to their latest version according to ranges in `package.json` instead of only the single selected package.

This does not happen in version `3.x`, which correctly works as supposed.

**Comment by zkochan** [comment]
This is an issue with hoisting, which was turned on by default in pnpm v4. If you don't need hoisting, you may turn it off through `hoist=false` in the config

**Comment by Djaler** [comment]
Same thing when I run `pnpm install <package>` to add new dependency. If I add it to `package.json` manually and run `pnpm install`, it works good

**Comment by zkochan** [comment]
Makes sense, `install` and `update` are the same code. The only difference is that `update` fails if the package is not in `package.json` yet.

**Comment by zkochan** [comment]
:ship: [4.6.0](https://github.com/pnpm/pnpm/releases/tag/v4.6.0)

**Comment by Djaler** [comment]
Awesome, thanks!

**Comment by stefano-b** [comment]
Thank you, should this be considered solved also when running `update`?

And will I need to use the `hoist=false` in the config even after `4.6-0` update?

**Comment by zkochan** [comment]
Solved for add/update. Config changes are not required

Stefano Bartoletti <notifications@github.com> ezt írta (időpont: 2019. dec.
20., P 11:58):
