### ISSUE TITLE
The pnpm CLI should support autocompletion

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2229]
* Autocompletion of command names.
* Autocompletion of command options
* Autocompletion of scripts (in `pnpm run` command)
* Autocompletion of dependency names (`pnpm remove <pkg>`, `pnpm update <pkg>`)
* Autocompletion of workspace packages names when using `--filter`

**Comment by zkochan** [comment]
cc @nikoladev 
related https://github.com/pnpm/pnpm/issues/2169#issuecomment-567457722

**Comment by nikoladev** [comment]
Just to repeat my quick research:

* npm has bash script for completion: https://github.com/npm/cli/blob/797a59797a2e226631f068c912f351ba340581fe/lib/utils/completion.sh
* Here's the documentation on for that bash script: https://github.com/npm/cli/blob/b829d62c98506325d2afb2d85d191a8ff1c49157/docs/content/cli-commands/npm-completion.md

**Comment by zkochan** [comment]
This package might help: [tabtab](https://github.com/mklabs/tabtab)

**Comment by zkochan** [comment]
The first beta version of completion is out (v4.9.0-0)

To setup completion, run `pnpm install-completion`. Note: it will only work with bash. We need to fork tabtab and make some fixes.

**Comment by nikoladev** [comment]
I only recently got a chance to try auto-completion out and it's great! Thanks :)

**Comment by stalinkay** [comment]
Auto-completion works great, I'm on the latest version of PNPM.

I got a small ask, please add a non-interactive version.

Something along this line:

```
pnpm install-completion --shell zsh --config-file ~/.zshrc
```

It could detect the current shell and do what it needs to do without any prompt like this:

```
pnpm install-completion --yes
```

I provision fresh macs with Ansible so it would be nice to be able to automate it in a non-interactive fashion.

**Comment by zkochan** [comment]
I created an issue for your request: https://github.com/pnpm/pnpm/issues/4520

Please don't comment on closed PRs and issues because your comment will most likely not be noticed.
