### ISSUE TITLE
Change pnpmfile without deleting lock

### ISSUE THREAD

**Issue by Djaler** [pnpm/pnpm#2235]
If I need to use pnpfile, then I should drop current pnpm-lock.yaml and regenerate it. Is this neccessary? Because when I drop it, I lost all peer dependencies locked versions

**Comment by zkochan** [comment]
It is currently necessary but we can improve it. We just need a way to find out if the pnpmfile was changed or not.

One solution might be to generate a hash from the content of the pnpmfile and save it in a field inside the lockfile. If the hash changes, we can run an update on the lockfile, keeping the existing versions.

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/7662
