### ISSUE TITLE
Can't install a specific package

### ISSUE THREAD

**Issue by lefb766** [pnpm/pnpm#2264]
### Code to reproduce the issue
```sh
pnpm add dreamopt@0.6.0
```

### Expected behavior:
The package is installed instantly.

### Actual behavior:
pnpm prints following error and exits after approx. 70s

> Packages: +2
 ++
 ERROR  Unexpected end of data
at _final                     .nvm/versions/node/v12.14.1/lib/node_modules/pnpm/lib/node_modules/tar-stream/extract.js:253                                            if (this._partial) retur…
at callFinal                  .nvm/versions/node/v12.14.1/lib/node_modules/pnpm/lib/node_modules/tar-stream/node_modules

`tail -n 20 pnpm-debug.log` gives
```
    "downloaded": 20480,
    "packageId": "registry.npmjs.org/dreamopt/0.6.0",
    "status": "in_progress"
  },
  "82 warn pnpm:package-requester": {
    "message": "Fetching registry.npmjs.org/dreamopt/0.6.0 failed!",
    "prefix": "/home/ec2-user"
  },
  "83 error pnpm": {
    "message": {
      "attempts": 3,
      "resource": "https://registry.npmjs.org/dreamopt/-/dreamopt-0.6.0.tgz"
    },
    "err": {
      "name": "Error",
      "message": "Unexpected end of data",
      "stack": "Error: Unexpected end of data\n    at Extract._final (/home/ec2-user/.nvm/versions/node/v12.14.1/lib/node_modules/pnpm/lib/node_modules/tar-stream/extract.js:253:42)\n    at callFinal (/home/ec2-user/.nvm/versions/node/v12.14.1/lib/node_modules/pnpm/lib/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:586:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
    }
  }
}
```

### Additional information:

 - `node -v` prints: v12.14.1
 - Windows, OS X, or Linux?: repros on all

- not a network or package issue

**Comment by zkochan** [comment]
It seems like a network issue. For me it worked now. Does it work with npm?

**Comment by lefb766** [comment]
Still repros.
`npm i dreamopt@0.6.0` just works. pnpm doesn't.

It could be network-related, but I've seen similar behavior on multiple environments I have access in Japan and a fresh EC2 machine at us-west-2 region.

**Comment by mpiroc** [comment]
I'm seeing the same problem with the same package (dreamopt 0.6.0).

```jsonc
{
  //  ...

  "11675 warn pnpm:package-requester": {
    "message": "Fetching registry.npmjs.org/dreamopt/0.6.0 failed!",
    "prefix": "C:\\Users\\matth\\repos\\util\\common\\temp"
  },
  "11676 error pnpm": {
    "message": {
      "attempts": 3,
      "resource": "https://registry.npmjs.org/dreamopt/-/dreamopt-0.6.0.tgz"
    },
    "err": {
      "name": "Error",
      "message": "Unexpected end of data",
      "stack": "Error: Unexpected end of data\n    at Extract._final (C:\\Users\\matth\\.rush\\node-v12.14.1\\pnpm-4.9.3\\node_modules\\pnpm\\lib\\node_modules\\tar-stream\\extract.js:253:42)\n    at callFinal (C:\\Users\\matth\\.rush\\node-v12.14.1\\pnpm-4.9.3\\node_modules\\pnpm\\lib\\node_modules\\tar-stream\\node_modules\\readable-stream\\lib\\_stream_writable.js:590:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
    }
  }
}
```

**Comment by SkReD** [comment]
Failed to install on version `4.9` and now installed without errors on `5.5`

**Comment by lefb766** [comment]
Confirmed. Now I can't repro this on any environment (including 4.7.1 on a fresh VM).
