### ISSUE TITLE
 ERROR  ENOENT: no such file or directory, open 'C:\Users\dionn\.pnpm-store\2\registry.npmjs.org\static-route\0.1.2\_tmp_4480_510faaf1c9072bafe5321bd3dab33281\test\weird filename$_..         newline'

### ISSUE THREAD

**Issue by Dionysusnu** [pnpm/pnpm#2266]
### pnpm version:
4.7.1
### Code to reproduce the issue:
`pnpm install`

[pnpm-debug.log](https://github.com/pnpm/pnpm/files/4045969/pnpm-debug.log)

### Expected behavior:
pnpm installs dependencies and does not error
### Actual behavior:
pnpm first gets stuck for a while saying
```
Packages: +12
++++++++++++
Resolving: total 12, reused 11, downloaded 0
```
Then exits with the following
```
Packages: +12
++++++++++++
 ERROR  ENOENT: no such file or directory, open 'C:\Users\dionn\.pnpm-store\2\registry.npmjs.org\static-route\0.1.2\_tmp_4480_510faaf1c9072bafe5321bd3dab33281\test\weird filename$_..        
newline'
Resolving: total 12, reused 11, downloaded 0
```
packages were not updated
this still occurs after deleting node_modules
### Additional information:
Package.json dependencies
```
  "devDependencies": {
    "httpserver": "^0.3.0",
    "typescript": "^3.4.3"
  }
```
 - `node -v` prints:
v13.3.0
 - Windows, OS X, or Linux?:
Windows 10

**Comment by zkochan** [comment]
Is the same issue happening with pnpm v4.6.0?

**Comment by zkochan** [comment]
Reproduced on v4.6.0, so this is not a regression. Seems like a bug

**Comment by zkochan** [comment]
This seems to be an issue with tar-fs. Yarn also uses tar-fs for unpacking and has the same issue.

**Comment by zkochan** [comment]
This is probably the same issue as #3229

**Comment by zkochan** [comment]
:ship: 5.18.6
