### ISSUE TITLE
Request: Improve memory footprint and size of binstubs

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#2272]
Whenever pnpm installs a package with a binary, it generates an executable file with the following content:

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  NODE_PATH="<node path>" "$basedir/node"  "$basedir/<bin path>" "$@"
  ret=$?
else 
  NODE_PATH="<node path>" node  "$basedir/<bin path>" "$@"
  ret=$?
fi
exit $ret
```

There is no reason `/bin/sh` should be alive after it has spawned the main process. The above code can be improved by adding `exec`:

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  NODE_PATH="<node path>" exec "$basedir/node"  "$basedir/<bin path>" "$@"
else 
  NODE_PATH="<node path>" exec node  "$basedir/<bin path>" "$@"
fi
```

And since `NODE_PATH` is usually very long, it could save some bytes of disk space by using `export NODE_PATH=`:

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

export NODE_PATH="<node path>"

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/<bin path>" "$@"
else 
  exec node  "$basedir/<bin path>" "$@"
fi
```

**Comment by zkochan** [comment]
I have no objections

This code is currently at https://github.com/pnpm/cmd-shim

**Comment by KSXGitHub** [comment]
Wait, from the description of cmd-shim, pnpm should create a symlink in my machine (Linux), but it created a shell script instead?

**Comment by zkochan** [comment]
No, the description should be updated. It created a script on all systems

**Comment by KSXGitHub** [comment]
I have made a [pull request](https://github.com/pnpm/cmd-shim/pull/26)

**Comment by zkochan** [comment]
:ship: 4.8.0-0
