### ISSUE TITLE
pnpm install --dev

### ISSUE THREAD

**Issue by jjangga0214** [pnpm/pnpm#2278]
`npm install --only=dev` allows only installing devDependencies. This feature is especially useful when building a container image. Therefore I propose `pnpm install --dev`.

**Comment by zkochan** [comment]
It is implemented in pnpm

jjangga0214 <notifications@github.com> ezt írta (időpont: 2020. jan. 18.,
Szo 10:12):

**Comment by zkochan** [comment]
I see we have to document this option at https://pnpm.js.org/en/cli/install

but it is documented in `pnpm help install`. `pnpm install --dev` will work.
