### ISSUE TITLE
`pnpm recursive` does not sort correctly for prelease package

### ISSUE THREAD

**Issue by thynson** [pnpm/pnpm#2279]
### Code to reproduce the issue:

Suppose there are a workspace:
```
|-packages
|  |- bar/package.json # @workspace/foo depends on @workspace/bar@workspace:*
|  |- foo/package.json # @workapace/bar bumped to a prerelease version, e.g. 1.0.0-1
| ...
```
And run `pnpm recursive exec -- pwd`
### Expected behavior:
Command `pwd` runs for `@workspace/foo` before `@workspace/bar`. pnpm sort packages correctly by default, despite the version of packages.
### Actual behavior:
Command `pwd` runs for `@workspace/bar` before `@workspace/foo`. 

### Additional information:
OS: OSX

**Comment by thynson** [comment]
Any updates? I made a minimal reproducible for it. This bug blocks me from using prerelease version number.
[pnpm-bug.tar.gz](https://github.com/pnpm/pnpm/files/4401868/pnpm-bug.tar.gz)

**Comment by zkochan** [comment]
:ship: 4.12.4
