### ISSUE TITLE
Flags passed to add command ignored when used in conjunction with --filter

### ISSUE THREAD

**Issue by amctavish** [pnpm/pnpm#2294]
### Code to reproduce the issue:

`pnpm add --save-dev @types/express --filter <package_name>`

### Expected behavior:

I would expect the `@types/express` to be added to the `devDependencies` of the package(s) specified in the filter.

### Actual behavior:

The `--save-dev` or `-D` flags appear to be being ignore  as`@types/express` is being added to `dependencies` instead of `devDependences`.

I have also tried this with the `--save-peer` flag which is also being ignored. Could be as simple as all flags intended for the `add` command are being ignored.

### Additional information:

 - `node -v` prints: v12:14.1
 - Windows, OS X, or Linux?: Linux (node:erbium docker container)

**Comment by zkochan** [comment]
:ship: [4.9.1](https://github.com/pnpm/pnpm/releases/tag/v4.9.1)
