### ISSUE TITLE
Remove command malforming package.json when used in conjunction with --filter

### ISSUE THREAD

**Issue by amctavish** [pnpm/pnpm#2295]
### Code to reproduce the issue:

`pnpm remove @types/express --filter <package_name>`

### Expected behavior:

I would expect `@types/express` to be removed from the dependencies of the specified package(s) leaving my `package.json` file looking like:

```
{
  "name": "<package_name>",
  "devDependencies": {}
}
```

### Actual behavior:

`@types/express` is being removed from the packages dependencies but it's malforming the package.json file.

```
{
  "0": {
    "rootDir": "<package_path>,
    "manifest": {
      "name": "<package_name>",
      "devDependencies": {}
    }
  }
}
```

### Additional information:

 - `node -v` prints: v12.14.1
 - Windows, OS X, or Linux?: Linux (node:erbium docker container)

**Comment by zkochan** [comment]
Fixed by #2421
