### ISSUE TITLE
_auth key does not work for scope-specific configuration

### ISSUE THREAD

**Issue by rtsao** [pnpm/pnpm#2299]
### pnpm version:

4.8.0 and/or master

### Code to reproduce the issue:

Failing test added here: https://github.com/rtsao/pnpm/tree/failing-test in https://github.com/rtsao/pnpm/commit/d03140e4e73b066e3f403d29bfadb4a7eb3bf8f9

Suppose the username is `foo` and password is `bar`.

```
registry = https://registry.npmjs.org/
@myscope:registry = https://my.registry.com/
//my.registry.com/:_auth = Zm9vOmJhcg==
//my.registry.com/:always-auth = true
```

### Expected behavior:

Packages with `@myscope/` should be fetched from `my.registry.com` using the legacy `_auth` key provided.

### Actual behavior:

401 Unauthorized

### Additional information:

Note that the following (equivalent config) does work:

```
registry = https://registry.npmjs.org/
@myscope:registry = https://my.registry.com/
//my.registry.com/:username = foo
//my.registry.com/:_password = YmFy
//my.registry.com/:always-auth = true
```

**Comment by zkochan** [comment]
Does it work with npm? Maybe this legacy authentication was not added for scoped registries

**Comment by rtsao** [comment]
> Does it work with npm? Maybe this legacy authentication was not added for scoped registries

Yes, this configuration works using the npm client (as well as yarn).

**Comment by zkochan** [comment]
We use [this package](https://github.com/pnpm/credentials-by-uri) to get the auth tokens. Maybe it needs an update

**Comment by zkochan** [comment]
:ship: [4.9.1](https://github.com/pnpm/pnpm/releases/tag/v4.9.1)
