### ISSUE TITLE
Workspace doesn't find module

### ISSUE THREAD

**Issue by jeffrson** [pnpm/pnpm#2315]
Hi,

I set up a repo at https://github.com/jeffrson/pnpm_ws which helps to demonstrate some strange behaviour related to workspace.

I have the same code ("test") inside and outside a workspace. While outside of the workspace everything goes well, inside the workspace typescript complains about a missing module.

### pnpm version:
4.9.0

### Code to reproduce the issue:
https://github.com/jeffrson/pnpm_ws

### Node
12.14.1

### OS
Windows 10

### Addendum

BTW, actually unrelated..., it would be nice if someone could explain, what exactly

> Only the root workspace package is going to have hoisted dependencies in node_modules

means when running `pnpm i -r`. Is this just for information? Is this something I could change if I want to?

Thanks!

**Comment by zkochan** [comment]
This is a bug with hoisting in a workspace. Direct dependencies of workspace projects are not hoisted to the root of the workspace.

> BTW, actually unrelated..., it would be nice if someone could explain, what exactly

I think that info message is outdated. Seems like we hoist everything since v4, so this message should be removed.

**Comment by jeffrson** [comment]
Unfortunately not fixed :-( However, might be a typescript issue as well - doesn't work with yarn2 workspace either.

**Comment by zkochan** [comment]
You might need to remove node_modules and run pnpm install

**Comment by jeffrson** [comment]
See "edit" above ;-)

Nevertheless not working with yarn2 - but that's another story...

**Comment by lorenzodallavecchia** [comment]
Hoisting is still not working in workspaces for me.

- Deleted all `node_modules` directories (in the root and in packages).
- Deleted `pnpm-lock.yaml`
- Ran `pnpm recursive install` (with pnpm 4.9.3)

Still no hoisting. This is the structure I see.

```
<workspace>
  node_modules
    .modules.yaml
    .pnpm
      registry.npmjs.org
        <deps>
          <version>
  package1
    node_modules
      <symlinks to root/node_modules/.pnpm/registry.npmjs.org/<dep>/<version>/node_modules/<dep>
  package2
    ...
  pnpm-lock.yaml
  pnpm-workspace.yaml
```

A bug? Or maybe I am just missing something.
