### ISSUE TITLE
Typescript error in package after using pnpm (which does not occur with yarn or npm)

### ISSUE THREAD

**Issue by jeffrson** [pnpm/pnpm#2317]
Hi,

here's a demo repo to show a bug related to typescript:
https://github.com/jeffrson/pnmp_vs_yarn_typescript

When I use yarn, tsc works without issues.

However, when I install modules with pnmp, tsc complains about missing type annotation.

Of course, I could add the type, but IMO it shouldn't matter, whether I use yarn or pnmp and work the same in both cases.

### pnpm version:
4.9.0

### Code to reproduce the issue:
https://github.com/jeffrson/pnmp_vs_yarn_typescript

### node
12.14.1

### OS
Windows 10

**Comment by zkochan** [comment]
Might be a Typescript issue? (https://github.com/Microsoft/TypeScript/issues/29808)

It also happens with Yarn v2.

And even when using `pnpm install --shamefully-hoist`

**Comment by jeffrson** [comment]
Well, that's interesting. I had tried with ```NODE_OPTIONS="--preserve-symlinks"``` (just in case), but to no avail. But in yarnv2 there are no symlinks.

However, in both cases the actually used modules are located outside of the working directory.

The error goes away, as soon as I set ```"declaration": false``` in tsconfig.json.

**Comment by hemedani** [comment]
I have the same issue with Apollo react hooks

**Comment by jakerr** [comment]
I'm experiencing a similar issue in [nodegui/react-nodegui](https://github.com/nodegui/react-nodegui) where `yarn && yarn build` works but `pnpm i && pnpm build` gives me typescript errors such as:

```bash
node_modules/.pnpm/@types+react@18.0.9/node_modules/@types/react/index.d.ts:3226:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'script' must be of type 'DetailedHTMLProps<ScriptHTMLAttributes<HTMLScriptElement>, HTMLScriptElement>', but here has type 'DetailedHTMLProps<ScriptHTMLAttributes<HTMLScriptElement>, HTMLScriptElement>'.
```

`--shamefully-hoist` did actually cut the errors down from 181 to 4 that are like:

```bash
src/demo.tsx:13:10 - error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ViewProps<QWidgetSignals>'.
13         <View>
```

I'm pretty lost on the how tsc produces different errors based on the node_modules layout. Are we somehow resolving a different tsc version in different cases?


Just thought I'd add the detail of another project where this is reproducible in case it might help in debugging.

**Comment by abubakir1997** [comment]
Error still existing...

**Comment by muratcankaracabey** [comment]
Same issue
