### ISSUE TITLE
pnpx not work on v 4.9.1

### ISSUE THREAD

**Issue by hemedani** [pnpm/pnpm#2331]
### Code to reproduce the issue:
`pnpx create-react-app funny`

### Expected behavior:
throw this error :
```
Install for [ 'create-react-app@latest' ] failed with code 1
```

### Actual behavior:
create a react project by `create-react-app`
### Additional information:

 - `node -v` prints: v13.7.0
 - Windows, OS X, or Linux?: OS X

I test v 4.9.1 in several virtual and real machine and it's throw this error :
```bash
 [I] ➜ pnpx create-react-app funny
Install for [ 'create-react-app@latest' ] failed with code 1
```

**Comment by zkochan** [comment]
This is some regression introduced by v4.9.0
