### ISSUE TITLE
can not link jest

### ISSUE THREAD

**Issue by hemedani** [pnpm/pnpm#2332]
### Code to reproduce the issue:
`pnpm i` on project that have jest on it like `react-app`

[pnpm-debug.log](https://github.com/pnpm/pnpm/files/4154401/pnpm-debug.log)

### Expected behavior:
just install dependencies
 
### Actual behavior:
throwing this error :
```bash
 ERROR  EISDIR: illegal operation on a directory, read
```
it's has this waining too :
```bash
 WARN  Cannot link bin "jest" of "jest-cli" to "/Users/syd/work/sitak/justWeb/node_modules/.pnpm/node_modules/.bin". A package called "jest" already has its bin linked.
```

### Additional information:

 - `node -v` prints: v13.7.0
 - Windows, OS X, or Linux?: OS X

**Comment by hemedani** [comment]
it's not a jest issue, i don't know what it is, but i test in a new react project and everything is very fine

**Comment by hemedani** [comment]
I found it because of `react-barcode` lib
when we wan't to install `pnpm add react-barcode` it's throw this error

**Comment by zkochan** [comment]
Indeed, it is reproducible with `pnpm add react-barcode`.

**Comment by MasonM** [comment]
I see this too in a private repo, and it's not specific to `react-barcode`, because we aren't using that anywhere.

**Comment by MasonM** [comment]
FYI: Here's commands to reproduce this on PNPM 5.1.6: 
```
mkdir test
cd test
pnpm init -y
pnpm add react-barcode
rm -rf node_modules
pnpm i
```

Output:
```
root@78c754242afb:~# mkdir test
root@78c754242afb:~# cd test
root@78c754242afb:~/test# pnpm init -y
Wrote to /root/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


root@78c754242afb:~/test# pnpm add react-barcode
 WARN  react-barcode@1.4.0 requires a peer of react@^16.0.0 but none was installed.
Packages: +7
+++++++
Resolving: total 7, reused 7, downloaded 0, done

dependencies:
+ react-barcode 1.4.0
root@78c754242afb:~/test# rm -rf node_modules/
root@78c754242afb:~/test# pnpm i
Lockfile is up-to-date, resolution step is skipped
Packages: +7
+++++++
Resolving: total 7, reused 7, downloaded 0, done
 ERROR  EISDIR: illegal operation on a directory, read
```

**Comment by mgabeler-lee-6rs** [comment]
This is driving me nuts on a larger project, but can repro with the minimal test case above. Did mucking with strace, and these are the directories from which it tries to read as if they were files:
* `node_modules/.pnpm/jsbarcode@3.11.3/node_modules/jsbarcode/bin/help`
* `node_modules/.pnpm/jsbarcode@3.11.3/node_modules/jsbarcode/bin/exceptions`
* `node_modules/.pnpm/jsbarcode@3.11.3/node_modules/jsbarcode/bin/renderers`
* ...

... ok, I stopped parsing strace output at this point as the pattern is pretty clear, definitely seems to have something to do with processing the bin files from the package.

What's interesting is the strace output implies that it _is_ recursing down these directories, despite this error.

**Comment by zkochan** [comment]
I assume this might be the same as #3263

**Comment by zkochan** [comment]
:ship: 5.18.8
