### ISSUE TITLE
ERROR  Unexpected virtual store location

### ISSUE THREAD

**Issue by panlw** [pnpm/pnpm#2335]
### Code to reproduce the issue:

Project folder path is changed, the following error occurs when installing a module.

```sh
$ pnpm i arg
 ERROR  Unexpected virtual store location
```

#### Error cause

`virtualStoreDir` in `node_modules/.modules.yaml` is a absolute path.

#### Manual solution

Manually to change it to relative path, `pnpm i arg` works and `virtualStoreDir` becomes new absolute path.

#### Questions

- Could `virtualStoreDir` be a relative path ?

### Expected behavior:

`pnpm i arg`

### Actual behavior:

 ERROR  Unexpected virtual store location

### Additional information:

 - `node -v` prints: v12.13.0
 - Windows, OS X, or Linux?: macOS 10.13.6

**Comment by zkochan** [comment]
Yes, I think it may be a relative path if it is in a subdirectory of the project.

**Comment by zkochan** [comment]
Unfortunatly, we cannot do this on Windows as on Windows we use junctions. So if we move the node_modules dir, it will break. But I guess, we can do this for non-Windows.
