### ISSUE TITLE
pnpm install Javascript heap out of memory

### ISSUE THREAD

**Issue by apostolisms** [pnpm/pnpm#2339]
We are using pnpm with rush on large typescript monorepo and during install pnpm errors with FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory. Some of our packages are quite large i.e. ~20mb zipped. This is happening with multiple version of pnpm (including latest). In one of our other repos, the highest version we can use to not run into this issue is 3.3.4. 
Flags used: pnpm install --no-lock --no-prefer-frozen-shrinkwrap 
Unfortunately I cannot post a repro. 

### Additional information: ERROR: Internal Error: Cannot load shrinkwrap at "/common/temp/pnpm-lock.yaml" but this error message is not consistent. 

 - `node -v` prints: 10.16.0
 - Windows, OS X, or Linux?: OS X & Windows

**Comment by apostolisms** [comment]
pnpm 3.3.4 works fine but unfortunately that is the latest version that works.

**Comment by sachinjoseph** [comment]
The commit that introduced this issue: https://github.com/pnpm/pnpm/commit/b6e316c2d0b5e894f00a2e312da24c6fb209c95c

**Comment by apostolisms** [comment]
@zkochan any update on this?

**Comment by zkochan** [comment]
I had no time yet to check this. If you know how to do memory profiling, maybe you could try to find what data uses most of the space. I was not able to reproduce this error even on huge repositories.

**Comment by zkochan** [comment]
I think, at least as a temporary solution, we could increase the max allowed RAM usage for pnpm by calling node with `--max-old-space-size=8192`

**Comment by sachinjoseph** [comment]
@zkochan This issue goes away if I manipulate peerDependencies in pnpmfile.js like below, so it has something to do with peerDependencies and not the package size. Do you think something changed in this [pnpm commit](https://github.com/pnpm/pnpm/commit/b6e316c2d0b5e894f00a2e312da24c6fb209c95c) that can lead to memory "leaks":

```javascript
function readPackage(package) {
    const dependencies = package.dependencies;
    const devDependencies = package.devDependencies;
    const peerDependencies = package.peerDependencies;

    // Peer dependencies are not a thing
    if (peerDependencies) {
        for (const [key, value] of Object.entries(peerDependencies)) {
            dependencies[key] = value;
        }
        package.peerDependencies = undefined;
    }
}
```

**Comment by zkochan** [comment]
I don't think so. I was profiling memory a lot and noticed no leak.

**Comment by zkochan** [comment]
Maybe the logs could help to locate the issue. Try to run `pnpm install --reporter ndjson` and save the output to a file. If it doesn't contain sensitive information attach it to the issue or send it to me in an email.

**Comment by TisnKu** [comment]
I also came across the problem with a super repo. Unfortunately I cannot share the dependency library that caused the failure.
Below is the stack trace.
```
resolvePeersOfNode(aka resolvePeersOfNode) [000003BD7FFDA621] [C:\Users\xxx\AppData\Roaming\nvm\v10.20.1\node_modules\pnpm\lib\node_modules\supi\lib\install\resolvePeers.js:~61]
```

**Comment by zkochan** [comment]
@TisnKu what was the pnpm version with the issue? I wonder if it is still happening with v5

**Comment by zkochan** [comment]
I have steps to repro, thanks to the bits team, so I'll be looking into it now.

**Comment by zkochan** [comment]
:ship: 5.5.6

**Comment by zkochan** [comment]
Seems like there are still a few edge cases. I'll work on them soon.

**Comment by zkochan** [comment]
:ship: 5.5.8 fixes all the use cases
