### ISSUE TITLE
pnpm update --latest does not respect version range specification

### ISSUE THREAD

**Issue by sveyret** [pnpm/pnpm#2342]
### pnpm version:

4.8.0

### Code to reproduce the issue:

With a `package.json` like the following:

```json
{
  "name": "app",
  "version": "0.0.0",
  "devDependencies": {
    "eslint": "6.0.0",
    "prettier": "1.19.1"
  }
}
```

Execute:

    pnpm install
    pnpm update --latest

### Expected behavior:

Should update the version of `eslint`, preserving the _exact_ specification:

```json
{
  "name": "app",
  "version": "0.0.0",
  "devDependencies": {
    "eslint": "6.8.0",
    "prettier": "1.19.1"
  }
}
```

### Actual behavior:

It does not respect the _exact_ specification for `eslint`. Moreover, it updates all packages, even those not concerned by the update, to add a `^` before every version:

```json
{
  "name": "app",
  "version": "0.0.0",
  "devDependencies": {
    "eslint": "^6.8.0",
    "prettier": "^1.19.1"
  }
}
```

Note that with the `--interactive` option, only the concerned packages are updated, but still without respecting the _exact_ specification.

### Additional information:

 - `node -v` prints: v12.14.0
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
I agree, but I think the specs should be changed if the `--save-exact` flag is used.

**Comment by sveyret** [comment]
Sure, but, if I am not mistaken, `--save-exact` is not supported by `pnpm update`.

**Comment by zkochan** [comment]
:ship: 4.11
