### ISSUE TITLE
[bug] pnpx will install a unexpected global package

### ISSUE THREAD

**Issue by Cologler** [pnpm/pnpm#2345]
The `pnpm` document says:

>  The following command installs a temporary create-react-app and calls it, **without polluting global installs** or requiring more than one step!
> `pnpx create-react-app my-cool-new-app`

However:

![image](https://user-images.githubusercontent.com/10906962/74091663-b9ecc900-4af4-11ea-9281-0e51716a90fa.png)

Look like `create-react-app` was installed as a global package.

---

pnpm version: 4.9.3
node version: v13.8.0

**Comment by talentlessguy** [comment]
Having the same problem

**Comment by zkochan** [comment]
This won't happen in pnpm v7.
