### ISSUE TITLE
Suggestion: Enable use of lockfile for pnpm why

### ISSUE THREAD

**Issue by orokanasaru** [pnpm/pnpm#2354]
Running `pnpm why` in our repo takes about two minutes.
After installing the same modules with yarn, running `yarn why` completes within a second.

All of the dependency information should be in the lockfile, so pnpm shouldn't need to scan node_modules to figure this out.

**Comment by zkochan** [comment]
Pnpm why doesn't scan node_modules. The necessary info is in the lockfile. Probably the algorithm is written not optimally

**Comment by zkochan** [comment]
Thanks for your contribution!

I'll be able to publish it only on Tuesday/Wednesday, next week.

**Comment by zkochan** [comment]
:ship: 4.10.0-0
