### ISSUE TITLE
Allow comments in package.json

### ISSUE THREAD

**Issue by muuvmuuv** [pnpm/pnpm#2359]
### pnpm version: 4.9.3

So this came up in npm several times and I would like to hear what you guys think about comments in package.json. I personally think they are VERY helpful and e.g. allow me to create sections in my scripts to clean up the mess. The language extension is `jsonc`, IDE users need to change this to get no warnings and npm would still throw errors for sure.

### Additional information:

 - `node -v` prints: LTS
 - Windows, OS X, or Linux?: latest macOS

**Comment by zkochan** [comment]
Json5 supports comments. We support Json5. Just name the manifest
package.json5

Marvin Heilemann <notifications@github.com> ezt írta (időpont: 2020. febr.
14., P 13:28):

**Comment by muuvmuuv** [comment]
Oh, all right! That works, wasn't aware of json5, but unfortunately prettier nor VS Code supports it properly. I guess I have to stick with the old key:value description hack for now:

```json
{
  "=========== Tools =========": "",
}
```

**Comment by HerbCaudill** [comment]
just noting here for the record that both VS Code and Prettier handle json5 with comments just fine. In VS Code you just need to associate the `.json5` extension with the "[JSON with Comments](https://code.visualstudio.com/docs/languages/json#:~:text=JSON%20with%20Comments,-In%20addition%20to&text=This%20mode%20is%20used%20for,*%2F%20\)%20as%20used%20in%20JavaScript.)" format.
