### ISSUE TITLE
install updates package.json and --no-save is not supported

### ISSUE THREAD

**Issue by lorenzodallavecchia** [pnpm/pnpm#2364]
### pnpm version:

4.9.3

### Code to reproduce the issue:

```sh
pnpm recursive install --no-save
```

### Expected behavior:

I would expect all the packages in my workspace to be installed, without modifying any of the package.json files.

### Actual behavior:

The command fails with `ERROR  Unknown option 'save'`.

### Additional information:

 - `node -v` prints: v10.15.3
 - Windows, OS X, or Linux?: Windows

I have read that `pnpm update` should now update package.json files by default (#2133). That's fine, since npm behaves the same. Is it correct that `pnpm install` now also does the same? Probably yes, because npm does.

The problem for me is that there is no way for disabling the behavior for the install command because `--no-save` is not recognized as a valid option.

**Comment by zkochan** [comment]
This is interesting. I guess we could add this option.

But it also looks weird. Maybe a different option should be added. Like `pnpm install --preserve-version-ranges`.

**Comment by lorenzodallavecchia** [comment]
Hmm, how is it weird? 
Since `npm` supports `--no-save` for its install command too, I was really surprised to find out that pnpm supports it only in the update command.

**Comment by zkochan** [comment]
It is already supported, I believe. We just need to allow the option by adding `'save'` here:

https://github.com/pnpm/pnpm/blob/681d5170dad4cad0b1ee40736943b4dfcbe77d6d/packages/plugin-commands-installation/src/install.ts#L44-L45

and documenting it here:

https://github.com/pnpm/pnpm/blob/681d5170dad4cad0b1ee40736943b4dfcbe77d6d/packages/plugin-commands-installation/src/install.ts#L194-L195

**Comment by zkochan** [comment]
> Is it correct that pnpm install now also does the same? Probably yes, because npm does.

Actually, I just checked, `pnpm install` is not modifying the specs. So there's no reason to have `pnpm install --no-save`.

**Comment by lorenzodallavecchia** [comment]
Weird, I'll double check and let you known.
Thanks @zkochan!
