### ISSUE TITLE
react native in workspace

### ISSUE THREAD

**Issue by hemedani** [pnpm/pnpm#2365]
### pnpm version:
```bash
➜ pnpm --version
4.9.3
```
### Code to reproduce the issue:
```bash
pnpx react-native run-ios
```

### Expected behavior:
run react native project 

### Actual behavior:
error for finding metro modules :
```bash
warn Package react-native has been ignored because it contains invalid configuration. Reason: Cannot find module 'lodash'
Require stack:
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli-platform-ios/3.2.0/node_modules/@react-native-community/cli-platform-ios/build/config/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli-platform-ios/3.2.0/node_modules/@react-native-community/cli-platform-ios/build/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/react-native/0.61.5_react-native@0.61.5+react@16.9.0/node_modules/react-native/react-native.config.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/import-fresh/2.0.0/node_modules/import-fresh/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/cosmiconfig/5.2.1/node_modules/cosmiconfig/dist/loaders.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/cosmiconfig/5.2.1/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/cosmiconfig/5.2.1/node_modules/cosmiconfig/dist/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli/3.2.0_react-native@0.61.5/node_modules/@react-native-community/cli/build/tools/config/readConfigFromDisk.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli/3.2.0_react-native@0.61.5/node_modules/@react-native-community/cli/build/tools/config/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli/3.2.0_react-native@0.61.5/node_modules/@react-native-community/cli/build/commands/install/install.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli/3.2.0_react-native@0.61.5/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/@react-native-community/cli/3.2.0_react-native@0.61.5/node_modules/@react-native-community/cli/build/index.js
- /Users/syd/work/sitak/satekPnpm/node_modules/.pnpm/registry.npmjs.org/react-native/0.61.5_react-native@0.61.5+react@16.9.0/node_modules/react-native/cli.js
error Unrecognized command "run-ios".
info Run "react-native --help" to see a list of all available commands.
```

### Additional information:
[this repo](https://github.com/hemedani/satekPnpm) it's an example of that error 
 - `node -v` prints: 
```bash
➜ node -v
v13.8.0
```
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
React Native currently doesn't work with pnpm because it has issues with symlinks. As far as I know,  @jkolyer is investigating it.

> The problem with react-native is actually due to cocoapods. Apparently the symbolic links are not supported well and the XCode setup is broken. Looking at a workaround.
> 
> I fixed the cocoapods issue with a fork of somebody else's fork. But metro does not play well with pnpm so that's the next rabbit hole.

**Comment by hemedani** [comment]
we can run react native with some dirty tricks but it's has a lot's of problems ...
any way thank's for awesome project.

**Comment by zkochan** [comment]
Could you share those dirty tricks? We could document them in our docs

**Comment by davidcallanan** [comment]
I'll forever miss pnpm when working with react native 😢

**Comment by adelarsq** [comment]
@zkochan Can this issue be reopened as unsolved?

**Comment by zkochan** [comment]
On our side, there is nothing we can currently do to make React Native work with pnpm. React Native doesn't work with a node_modules that contains symlinks. pnpm cannot create a node_modules w/o symlinks. So this should be solved on the React Native side.

**Comment by adelarsq** [comment]
@zkochan Thanks for the quick feedback.

**Comment by ShivamJoker** [comment]
I also tried it and it didn't work :( still

**Comment by zkochan** [comment]
@vjpr said he uses React native with no issues. Related issue: https://github.com/pnpm/pnpm/issues/1252

**Comment by karlhorky** [comment]
More users talking about using pnpm with React Native and workspaces (if I understand correctly, following `pnpm` symlinks is supported in workspaces, without workarounds like `node-linker=hoisted` 🙌):

- https://github.com/facebook/metro/issues/1042

If you're using Expo, you're still going to have problems (even if you use a setup that works for RN / Metro):

- https://github.com/pnpm/pnpm/issues/4286#issuecomment-1913173223
