### ISSUE TITLE
Module not found in create-react-app

### ISSUE THREAD

**Issue by HASSANDL** [pnpm/pnpm#2370]
pnpm: 4.9
Module not found in create-react-app
```Module not found: Can't resolve '@material-ui/styles' in ...```

**Comment by Bessonov** [comment]
Nope. Works for us. Make sure you did everything right and then fill properly issue with reproduction steps.

**Comment by HASSANDL** [comment]
I install with shamefully-hoist problem solved but I dont want install flat modules same npm & yarn. Is other way exist?

**Comment by nikoladev** [comment]
You'd need to contact the authors of the modules that give the error and ask if they can properly set up their projects. Or ask if you can help them with it.

What I usually do when I deal with these problems is set `shamefully-hoist=true` in a `.npmrc` file in the root of my project.

**Comment by zkochan** [comment]
or you can use `shamefully-hoist` with `hoist-pattern` and hoist only those dependencies that you have issues with https://pnpm.js.org/en/npmrc#hoist-pattern

**Comment by joe-bell** [comment]
I solved this by adding an `.npmrc` in the root of my repo with the following:
```
public-hoist-pattern[]=@material/*
public-hoist-pattern[]=material-*
```
