### ISSUE TITLE
pnpm mangles config from environment variables

### ISSUE THREAD

**Issue by mpiroc** [pnpm/pnpm#2387]
### Code to reproduce the issue:

```powershell
# PowerShell
npm i -g pnpm
$env:{npm_config_@my-scope:registry} = "https://npm.pkg.github.com"
$env:{npm_config_//npm.pkg.github.com/:_authtoken} = "my_auth_token"
pnpm config ls
```

```bash
# Bash
npm i -g pnpm
env "npm_config_@my-scope:registry=https://npm.pkg.github.com" env "npm_config_//npm.pkg.github.com/:_authtoken=my_auth_token" pnpm config ls
```

### Expected behavior:
PNPM sets `@my-scope:registry` and `//npm.pkg.github.com/:_authtoken` from environment variables.

### Actual behavior:
PNPM replaces `_authtoken` with `-authtoken`, which results in the token being ignored.

```
PS C:\Users\matth> pnpm config ls
...
; environment configs
//npm.pkg.github.com/:-authtoken = "my_auth_token"
@my-scope:registry = "https://npm.pkg.github.com"
...
```

### Additional information:

 - `node -v` prints: `v12.14.1`
 - Windows, OS X, or Linux?: Windows, Linux

**Comment by zkochan** [comment]
:ship: 4.11.0-0

**Comment by mpiroc** [comment]
Ridiculously fast turnaround. Thank you!

**Comment by zkochan** [comment]
The auth token should be used but this command will continue showing a bad config setting: pnpm config ls

because `pnpm config` is currently passed through to `npm config`.
