### ISSUE TITLE
pnpm recursive remove break all the package.json files

### ISSUE THREAD

**Issue by VitorLuizC** [pnpm/pnpm#2395]
### pnpm version:
v4.11.1

### Code to reproduce the issue:
`pnpm recursive remove [dependency]`

### Expected behavior:
Just removes the dependency from packages that have it.

### Actual behavior:
Breaks the package.json of all the packages, but seems to be removing the dependency.

### Additional information:
 - `node -v` prints: v13.8.0
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
How does it break the package.json files? I can't reproduce this issue

**Comment by VitorLuizC** [comment]
I'll create a repository to reproduce

**Comment by VitorLuizC** [comment]
@zkochan sorry to took so long.

https://github.com/VitorLuizC/pnpm-issue-2395

**Comment by zkochan** [comment]
I see, seems like it happens only when each project uses a dedicated lockfile.
