### ISSUE TITLE
`pnpm prune --prod` doesn't work correctly with workspaces

### ISSUE THREAD

**Issue by jackyef** [pnpm/pnpm#2396]
### Code to reproduce the issue:
Clone this repo: https://github.com/jackyef/pnpm-prune-bug

1. Install all dependencies
	  ```
	  pnpm recursive install
	  ```

2. Check `node_modules` size
	  ```
	  du -sh node_modules # 27M
	  ```

3. Prune devDeps
	  ```
	  pnpm recursive prune --prod
	  ```

4. Check `node_modules` size
	  ```
	  du -sh node_modules # Still 27M!
	  ```

5. Clean up node_modules manually
	  ```
	  rm -rf ./node_modules
	  rm -rf ./packages/*/node_modules
	  ```

6. Install deps without devDeps
	  ```
	  NODE_ENV=production pnpm recursive install
	  ```

7. Check `node_modules` size
	  ```
	  du -sh node_modules # 488K!
	  ```

### Expected behavior:
`node_modules/.pnpm/registry.npmjs.org/webpack` shouldn't exist after pruning.

### Actual behavior:
It still exist after
```
pnpm recursive install
pnpm recursive prune --prod
```

### Additional information:
Node: v10.16.2
OS: OS X

**Comment by zkochan** [comment]
As a temporary solution, you may run `pnpm recursive install --prod` or a shorter version `pnpm install -rP`

**Comment by jackyef** [comment]
@zkochan Would you say this is a doable issue for first-time contributor to the project? If you do, I am interested in helping out. Really liking the project 👍

**Comment by zkochan** [comment]
I do encourage you to contribute but this one is not the best, I think.

**Comment by zkochan** [comment]
This is probably fixed by https://github.com/pnpm/pnpm/pull/4691
