### ISSUE TITLE
PNPM install did work but ProdBuild is failing

### ISSUE THREAD

**Issue by RaghavendraI** [pnpm/pnpm#2400]
I've used pnpm install and it did work for me. But when doing ProdBuild it failed:

![image](https://user-images.githubusercontent.com/47421637/76068251-d591a500-5fb6-11ea-8b9a-bec445fe4641.png)

For the same project earlier using npm install and npm run ProdBuild worked without having any issues. But doing a prod build using pnpm is failing. Can someone help me out, please?

pnpm version : 4.11.1
node version : 6.12.1

**Comment by zkochan** [comment]
I see that you use Angular. Angular projects currently work only when `shamefully-hoist` is `true`. You can create a `.npmrc` file in the root of your project and put `shamefully-hoist=true` there. Then reinstall the dependencies with `pnpm install`.

Also, if typescript is not in you dependencies, you may have to install it with `pnpm add -D typescript`

**Comment by zkochan** [comment]
The conversation is happening on [StackOverflow](https://stackoverflow.com/questions/60559108/pnpm-install-did-work-but-prodbuild-is-failing)
