### ISSUE TITLE
Install package with alias is broken

### ISSUE THREAD

**Issue by paxperscientiam** [pnpm/pnpm#2409]
### Code to reproduce the issue:
`pnpm install lodash@npm:awesome-lodash`

### Error message:
"Cannot read property 'name' of undefined"

### Expected behavior:
Install npm branch of lodash in node_modules/awesome-lodash

### Actual behavior:
Nothing seems to be installed; get error message.

### Additional information:

 - `node -v` prints: v13.8.0
 - Windows, OS X, or Linux?: macos 10.15.3

Thanks!

**Comment by zkochan** [comment]
The error message is broken... but you used the wrong syntax. The real name should be after `npm:`.

So the right command is:

```
pnpm add awesome-lodash@npm:lodash
```

**Comment by paxperscientiam** [comment]
Thank you, @zkochan . That did indeed work. I should note, however, that I pulled that example directly from the website.
https://pnpm.js.org/en/aliases
