### ISSUE TITLE
[FeatureRequest] add option to install with "NOT STRICT"

### ISSUE THREAD

**Issue by ken0x0a** [pnpm/pnpm#2427]
I was using `yarn` long time ( still using it for most repository ), and I'm trying to switch to `pnpm` now, as `pnpm` is **fast** when install and **using disk efficiently**.

As I'm using my shared configuration package "@ken0x0a/configs" to save time to upgrade version separately and improve package.json readability, and it has dependencies like
"@ken0x0a/eslint-config", "@ken0x0a/prettier-config", "@ken0x0a/commit-config", e.t.c, 
eslint & prettier & others throw errors that "config file is not found in node_modules dir", by using `pnpm`.

So I want to see the option to install dependency loosely (NOT STRICT) like `yarn`.

Thank you for great project.
`pnpm` is **fast** and **super disk efficient**.

**Comment by zkochan** [comment]
See the [shamefully-hoist](https://pnpm.js.org/en/npmrc#shamefully-hoist) setting

**Comment by ken0x0a** [comment]
@zkochan Works perfect!! Thank you so much!!

**Comment by ken0x0a** [comment]
@zkochan I found that, "prepare" script is running **before hoist** dependencies, and "prepare" script in my `package.json` is failing.
Is it also, already, possible to hoist before script?

**Comment by ken0x0a** [comment]
I'm currently trying to switch to `pnpm` for other repositories 😎

**Comment by zkochan** [comment]
> I found that, "prepare" script is running before hoist dependencies

From the sourcecode it seems like prepare is executed after installation is done, and hoisting is done

**Comment by ken0x0a** [comment]
@zkochan 

That's interesting.
I can reproduce this error with followings.

```sh
git clone -b dev https://github.com/rich-ken/node-cli-ken
# remove "tslib" & "typescript" from "devDependencies
pnpm i
```

As "@ken0x0a/configs" has "typescript" & "tslib" as dependencies, it should success,
but actually, I received following errors.

```
Resolving: total 101, reused 101, downloaded 0, done

devDependencies:
- tslib 1.11.1
- typescript 3.8.3

> cli-ken@1.0.0 prepare <path_to_my_projects>/my-cli
> tsc --incremental false

sh: tsc: command not found

 ERROR  Command failed.
```

**Comment by zkochan** [comment]
This might be related to https://github.com/pnpm/pnpm/issues/855

**Comment by ken0x0a** [comment]
Is it possible, that `pnpm` doesn't wating until finishing of the linking (async function?).
If not, macos must have delay at some point while linking, or after success of linking.

`pnpm` is really cool, I'm wating for workaround.

As I confront this issue on 2 Macbook pros, so all macos should be affected.
I don't know Linux or Windows.

**Comment by zkochan** [comment]
We'd probably notice that issue earlier because we use linking all over the place. If you could create a sample repository that reproduces the issue, we could look into it

**Comment by ken0x0a** [comment]
@zkochan Thank you so much!

Following procedure must reproduce the issue.
```sh
git clone -b dev https://github.com/rich-ken/node-cli-ken
# remove "tslib" & "typescript" from "devDependencies
pnpm i
```

**Comment by zkochan** [comment]
I don't have issue with this on Linux
