### ISSUE TITLE
pnpm doesn't understand the || (OR) semver operator correctly

### ISSUE THREAD

**Issue by MrJohz** [pnpm/pnpm#2449]
### Code to reproduce the issue:

```prompt
$ pnpm init -y
Wrote to /tmp/testdir/package.json:

{
  "name": "testdir",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
$ pnpm add --save-dev rollup
Packages: +1
+
Resolving: total 2, reused 2, downloaded 0, done

devDependencies:
+ rollup 2.3.0
$ pnpm add --save-dev @rollup/plugin-node-resolve
 WARN  @rollup/plugin-node-resolve: @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but version 2.3.0 was installed.
 WARN  @rollup/plugin-node-resolve@7.1.1 requires a peer of rollup@^1.20.0 but version 2.3.0 was installed.
Packages: +9
+++++++++
Resolving: total 11, reused 11, downloaded 0, done

devDependencies:
+ @rollup/plugin-node-resolve 7.1.1
```

### Expected behavior:
No peer dependency warnings should appear

### Actual behavior:
Peer dependency warnings appear

### Additional information:
`@rollup/plugin-node-resolve` (and `@rollup/pluginutils`) require a peer of `rollup@^1.20.0||^2.0.0`.  The installed version of rollup is 2.3.0, which should match the second part of that requirement, so this should be considered a valid peer dependency, but for some reason pnpm produces a warning.

My guess is that the semver validator does not correctly parse the `||` operator that the dependencies rely on.  Given that this is documented NPM behaviour ([e.g. here](https://docs.npmjs.com/misc/semver)), I assume that this is a bug.

 - `node -v` prints: v13.7.0
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
pnpm works correctly.

As you may see from the warning, the wanted range is `rollup@^1.20.0` and that is the actual range which is present in the published package's package.json ([see the peer dependencies field](https://unpkg.com/@rollup/plugin-node-resolve@7.1.1/package.json))

I don't know why the range in [the repository of rollup](https://github.com/rollup/plugins/blob/5bcc533e195ddc53c077b5fdb4bfd2164f709dad/packages/node-resolve/package.json#L48) differs from the published one but pnpm works as expected here.

**Comment by MrJohz** [comment]
Thanks for the hint!
