### ISSUE TITLE
How to incrementally compile `pnpm`?

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#2459]
I would suggest adding some instructions to the `CONTRIBUTING.md` (or maybe `DOCS/development.md`) about how to compile pnpm.

I tried the following but got an error.

```
$ pnpm m run --filter=supi start

Scope: 1 of 92 workspace projects

> supi@0.38.24 start ~/dev/pnpm/packages/supi
> pnpm run tsc -- --watch

Scope: current workspace package
 ERROR  Missing script: tsc
~/dev/pnpm/packages/supi:
 ERROR  supi@0.38.24 start: `pnpm run tsc -- --watch`
Exit status 1
```

Should this work? I also tried `cd`ing to `packages/supi` and it cannot find `tsc` either. Seems like this npm run script would never work even without `pnpm m`...unless `tsc` is installed globally.

Because `tsc` is only available in the root, its not accessible. Should we make it so that when running `pnpm m run`, we prepend `<root>/node_modules/.bin` to the `PATH`? Maybe behind a flag?

**Comment by zkochan** [comment]
We recently adopted TypeScript project references. So the compilation is a lot easier. There's a compile command in the root. You can run `pnpm run compile`. Or you can compile the CLI (it will also compile all the dependencies, if needed): `pnpm run compile --filter`. This also works with watch. For instance, `pnpm run compile -- --watch`.

**Comment by vjpr** [comment]
```
$ pnpm run compile -- --watch

Scope: current workspace package

> @ compile /Users/Vaughan/dev-live/pnpm
> pnpm run --filter @pnpm/fetch compile && pnpm run --filter pnpm compile && pnpm run update-manifests "--watch"

Scope: 1 of 92 workspace projects

> @pnpm/fetch@1.0.3 compile /Users/Vaughan/dev-live/pnpm/packages/fetch
> rimraf lib && tsc && cpy src/**/*.d.ts lib

Scope: 1 of 92 workspace projects

> pnpm@4.12.4 compile /Users/Vaughan/dev-live/pnpm/packages/pnpm
> rimraf lib tsconfig.tsbuildinfo && tsc --build

 ERROR  Unknown option 'watch'
For help, run: pnpm help run
 ERROR  Command failed with exit code 1.
```

**Comment by zkochan** [comment]
It should work on all except the root one. For root, we can add something like

```
"watch": "pnpm run --filter @pnpm/fetch compile && pnpm run --filter pnpm compile -- --watch",
```

**Comment by vjpr** [comment]
Project references are not being cleaned by `pnpm run compile` which can cause issues. A common one is:

```
# before

- index.js
- foo.js

# after

- index.js
- foo.js (should be cleaned - if not, it gets required when doing `require('./foo')` instead of `foo/index.js`)
- foo
  - index.js
```

**Comment by zkochan** [comment]
I am not sure cleaning is required because there's a buildinfo file in each project, which contains information about whether the dist folder is up-to-date. Maybe you had some old libs, which were created before project references were configured

**Comment by vjpr** [comment]
> Maybe you had some old libs, which were created before project references were configured

Yeh I think that is the issue.
