### ISSUE TITLE
`--no-prefer-frozen-lockfile` does not work on CI machines

### ISSUE THREAD

**Issue by sachinjoseph** [pnpm/pnpm#2463]
On pnpm >= 4.10.0, `--no-prefer-frozen-lockfile` does not work on CI machines to allow lockfile updates. See:
1) https://github.com/microsoft/rushstack/issues/1804
2) PNPM https://github.com/pnpm/pnpm/issues/1994#issuecomment-609222609

**Comment by zkochan** [comment]
:ship: 4.12.5

**Comment by sachinjoseph** [comment]
Thanks, verified that this works in pnpm 4.12.5.

**Comment by Jolg42** [comment]
Indeed many thanks! 🎊 👏
