### ISSUE TITLE
PNPM does not pass arguments when running scripts

### ISSUE THREAD

**Issue by qin-guan** [pnpm/pnpm#2464]
### Code to reproduce the issue:

```
pnpm run start -- --port 3000
```

### Expected behavior:

PNPM will append the argument `--port 3000` to the script

### Actual behavior:

PNPM throws error `Unknown option 'port'`

**Comment by zkochan** [comment]
Seems like you are using PowerShell. With PowerShell, you need to use 

```
pnpm run start `-- --port 3000
```

**Comment by qin-guan** [comment]
@zkochan, thanks! can confirm this works!
