### ISSUE TITLE
Workspace peer dependencies not subtitude to real version when published

### ISSUE THREAD

**Issue by thynson** [pnpm/pnpm#2467]
### Code to reproduce the issue:

Suppose a monorepo with package `foo` and `bar` and `foo` is a peer dependency of `bar` which specified by `workspace:*`. When publishing them to registry, npm will alert you with message like `bar@*.*.* requires a peer of foo@workspace:* but version *.*.* is installed`

### Expected behavior:
No alert abount unmet peer dependencies when install them from registry.

**Comment by zkochan** [comment]
@thynson do you mean that the workspace range is used in peer dependencies? Like bar has this in the package.json:

```json
"peerDependencies": {
  "foo": "workspace:*"
}
```

**Comment by thynson** [comment]
Exactly.
