### ISSUE TITLE
Allow to specify a custom folder for dependencies installation instead of node_modules

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2471]
A new setting should be supported called `modules-dir` that would allow specifying a custom directory for installing modules.

cc @F1LT3R

**Comment by zkochan** [comment]
It appears that Yarn also has this feature (thru the `modules-folder` setting). They only rename the root node_modules directory. Should we do the same? Only rename the root node_modules and keep the other ones unchanged?

cc @F1LT3R @pnpm/collaborators

**Comment by vjpr** [comment]
I like it.

Just thinking about some use cases...perhaps it would allow for multiple installations in the same dir which could be useful for slim docker builds.

Imagine you have a big monorepo that contains two apps, and you want to build a docker image for each app which only contains the deps they need. You could specify a different `modules-folder` and `lockfile` location and have two simulatenous installs, and then just exclude either modules dir.

This could also be good for testing. You could have a `--prod` only install tree, and then run tests against this to make sure that the prod is not depending on a dev dep which would allow bugs to slip through ci into prod.

**Comment by zkochan** [comment]
Actually, I need this feature in scope of a monorepo. Let's say I have a monorepo for UI components. I want to create a variation of a page, where some subcomponent is substituted. So I will probably need some additional features as well but not sure yet. Like an alternative lockfile. Or an alternative `pnpm-workspace.yaml` file.
