### ISSUE TITLE
error while creating react native project in windows 10

### ISSUE THREAD

**Issue by p32929** [pnpm/pnpm#2472]
### pnpm version:
4.12.5

### Code to reproduce the issue:
pnpx react-native AwesomeProject

### Expected behavior:
It was supposed to give me a folder with the react native project but instead its showing the error

### Actual behavior: 
Its showing me this error
![Screenshot (5)](https://user-images.githubusercontent.com/6418354/78877984-7de1d000-7a73-11ea-8413-58eeab03ce98.png)

I read these ( https://github.com/pnpm/pnpm/issues?q=EISDIR ) tried some commands mentioned in these issues but the problem didn't get fixed

### Additional information:

 - `node -v` prints: v12.16.1
 - Windows, OS X, or Linux?: Windows 10

### Temporary solution:
```
pnpm install react-native --global
react-native init AwesomeProject
```

**Comment by p32929** [comment]
Is there any solution for this error??

**Comment by zkochan** [comment]
Try using: this https://github.com/microsoft/rnx-kit/tree/main/packages/metro-resolver-symlinks

**Comment by zkochan** [comment]
This should work in pnpm v7
