### ISSUE TITLE
pnpm add or pnpm install, not working properly - keeps downloading dependencies over and over again

### ISSUE THREAD

**Issue by p32929** [pnpm/pnpm#2475]
### pnpm version:
4.13.0

### Code to reproduce the issue:
pnpm add package-name
or 
pnpm install anything

![Screenshot (7)](https://user-images.githubusercontent.com/6418354/79043100-d6090580-7c1e-11ea-8429-abfd40d2b982.png)

### Actual behavior: 
1. It doesn't add the dependencies in package.json
2. Keeps downloading packages over and over again

### Additional information:

 - `node -v` prints: v12.16.1
 - Windows, OS X, or Linux?: Windows 10

**Comment by zkochan** [comment]
Seems like the first installation crashed because of issues with the lockfile. pnpm locks the store and the node_modules when it run installation and we use the proper-lockfile library for that.

**Comment by p32929** [comment]
I mean, what should I do now? any workaround?

**Comment by zkochan** [comment]
Try `pnpm set lock false`

Fayaz Bin Salam <notifications@github.com> ezt írta (időpont: 2020. ápr.
11., Szo 17:04):

**Comment by zkochan** [comment]
This shouldn't happen with the latest pnpm.
