### ISSUE TITLE
Allow `--filter {.}...` to be the default behaviour of `pnpm install` for monorepos

### ISSUE THREAD

**Issue by keyworks** [pnpm/pnpm#2476]
### Context

I recently migrated my team's monorepo from yarn to pnpm to solve issues caused by node_modules flattening and hoisting. So far it's been working great - we've reduced the number of issues caused by implicit dependencies and installs feel faster. 

Our monorepo is set up with around 24 packages and I have 1 pnpm-workspace.yaml file defined at the root of the repo. 

When our developers work on a package on our monorepo, the package they are working on often only require around 5-6 workspace dependencies, both direct and indirect. However, yarn has conditioned them to run `pnpm install` which installs deps for all 24 packages which can be pretty slow (further exacerbated by the fact that I have `shared-workspace-lockfile` set to `false`). I have been asking our developers to always run `pnpm install --filter {.}...` to reduce installation time however I feel this is not a pit of success.

### Proposal

The feature request here is to allow `pnpm install` to default to `pnpm install --filter {.}...`. This could be implemented as a flag in `.npmrc` like `always-install-indirects=true` or maybe a more flexible approach could be to have a setting that lets us specify default flags like `default-install-flags="--filter {.}..."`. I personally prefer the latter approach

### Current Workarounds

- Educate developers on my team to always use `--filter {.}...`.
    - This is what I'm doing right now. But there will always be one new developer waiting for 15+ minutes to install deps on all 24 packages since they did not realize they can use --filter flag. 
- Define pnpm-workspace.yaml file in each package and whitelist dependencies:
    - Not ideal since dependency knowledge is now duplicated in two places: package.json and now pnpm-workspace.yaml, and requires manual updates to keep them in sync

**Comment by zkochan** [comment]
I think this is the same as #2150

However, I would strongly recommend using a shared lockfile. It provides a lot better user experience. The speed of installation is a lot faster! So developers would just run installation on all packages every time without noticing any difference in speed.

**Comment by keyworks** [comment]
Hi @zkochan. Sorry for commenting so late but #2150 is not exactly the same issue. I tried the v5.4 release and it does not solve my problem. Ideally I would like `pnpm install --filter {.}...` to be the default behaviour of `pnpm install` for my monorepo. `pnpm install` takes too long since our monorepo has many packages (30+ as of today), and `pnpm install` with `recursive-install=false` requires that the developer cd into the folder of each workspace dependency and run `pnpm install`.

It would be great if there was a flag that would enable `--filter {.}...` by default. I'm not sure what the name would be, maybe `only-install-direct-and-indirects=true`? 

If you agree this would make sense in pnpm, I'd be happy to look into implementing this.

**Comment by zkochan** [comment]
I don't think a new flag is needed. Maybe this `recursive-install=false` could behave as you described.

**Comment by keyworks** [comment]
Maybe I'm misunderstanding about something `recursive-install` but I'll try to describe in more detail why I think `recursive-install=false` is not the same

### Scenario 1: Default install behaviour
When I run `pnpm install` with the default install behaviour I get:
```
$ pnpm install
Scope: all 31 workspace projects
```
This installs all 31 packages in my monorepo. It takes a fairly long time but it at least installs everything I need.

### Scenario 2: `recursive-install=false` behaviour introduced in 5.4
When I run `pnpm install` with `recursive-install=false` I get:
```
$ pnpm install
Scope: current workspace package
```
This is much quicker, but it does not install everything I need. So I need follow this up with `pnpm install --filter {.}^...` to get everything else that I need to run my package. This is not ideal since most of the developers that I work with are not familiar with `--filter` semantics. Alternatively they could `cd` into each folder and run `pnpm install` but this a lot of work, especially if you depend on a lot of packages.

### Scenario 3: Preferred install behaviour
When I run `pnpm install --filter {.}...` I get:
```
$ pnpm install --filter {.}...
Scope: 11 of 31 workspace projects
```

In this case, I get everything that I need, but pnpm only installs dependencies for 11 packages. It is much faster this way. 

I would love if Scenario 3 behaviour could be the default behaviour enabled by a flag. If so, developers can just run `pnpm install` and except that their monorepo package would just work.

**Comment by zkochan** [comment]
Yes, so I think `recursive-install=false` should make `pnpm install` work as `pnpm install --filter {.}...` if the `link-workspace-packages` option is true. cc  @yaodingyd

**Comment by keyworks** [comment]
I tried `pnpm install` with `link-workspace-packages` set to `true` (I originally had it set it to `false`) and its still only installing deps for the current workspace package. Here are the settings I used: 
```
engine-strict=true
shared-workspace-lockfile=false
link-workspace-packages=true
recursive-install=false
```
I can provide an example repo if needed.

**Comment by zkochan** [comment]
I was describing how I think it should work. We'll update this.

**Comment by yaodingyd** [comment]
I'll work on this

**Comment by keyworks** [comment]
Thanks @yaodingyd @zkochan.

BTW, not a deal breaker but I'd prefer if we could allow the `--filter={.}...` behaviour even if `link-workspace-packages` is `false`.

I have `link-workspace-packages` set to `false` in my monorepo since I like how it forces you declare workspace packages using `workspace:`. It makes it clearer to developers that this package is another local package in the monorepo instead of installed from a registry.

**Comment by yaodingyd** [comment]
I think it makes sense with `link-workspace-packages=true` otherwise we can't differentiate "only install this package" from "install this package and its dependent workspace packages"

**Comment by zkochan** [comment]
I have to agree with @keyworks, it should work the same with whatever value of `link-workspace-packages`. 

Maybe `{.}...` should work differently when `link-workspace-packages` is `false` and no workspace ranges are declared but that is another issue.

**Comment by yaodingyd** [comment]
Does this mean we won't support #2150? or it just should have the same behavior

**Comment by keyworks** [comment]
My two cents: They seem like separate features to me. #2150 feels like its needed for backwards compatibility for people who are used to `pnpm@3` behaviour. But this issue could be considered a new feature.

**Comment by zkochan** [comment]
no, `pnpm install` worked like `pnpm install --filter {.}...` in `pnpm@3`

**Comment by keyworks** [comment]
Thanks so much @zkochan and @yaodingyd. Works great now.

**Comment by imrim12** [comment]
Hello @zkochan @yaodingyd , is it possible to install only 1 package in the workspace using filter?
Currently i have `recursive-install=false` already, but it keeps adding `node_modules` in all of my workspace packages even when i use `pnpm -F @mycompany/foo-bar`

I have a monorepo which has a main application + a dozen of packages
When i make change to some packages, Github Action would run the test and release them, it would be nice for the installation step to install less, only for the packages because the main application is very big, i would very much appreciate if there're any solution for it, thank you

**Comment by jfirebaugh** [comment]
`pnpm install --filter` is broken in 8.x, it always installs everything: https://github.com/pnpm/pnpm/issues/7242
