### ISSUE TITLE
Crash: Cannot read property 'pkgsStack' of undefined

### ISSUE THREAD

**Issue by orokanasaru** [pnpm/pnpm#2478]
### pnpm version:
4.12.5

### Code to reproduce the issue:
Run `pnpm install` with a dependency that returns 401 from the registry.

### Expected behavior:

Logging issue.

### Actual behavior:

Crashing.

fetch-ts in npm-resolver sets `REGISTRY_META_RESPONSE_401` as the error code.

reportError in default-reporter does not have a specific case for this, and falls to the formatErrorSummary block. This block expects `logObj['message']` to exist, but in this case it's under `err['message']` or `logObj['err']['message']`.

Offending code added in #2394. https://github.com/pnpm/pnpm/commit/e287f5ee927f2854e3df61ca5548ae2691ab6d8a#diff-458283e49af772f0440b7f08f40e0e5aR54

### Additional information:

 - `node -v` prints: v13.9.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
I don't understand how `logObj['message']` can be undefined.

The error object is passed through `logObj['message']`

Here's the related code

https://github.com/pnpm/pnpm/blob/21454aaa9aeef32b49465e04bfd08be81fa5bd58/packages/pnpm/src/err.ts#L9-L12

**Comment by zkochan** [comment]
oh, I see... `npm-resolver` calls `logger.error` and doesn't pass the error object as a message

**Comment by zzxz** [comment]
We are running into the same issue. Is there a current workaround other than manually trying to find the errant dependency?

**Comment by zkochan** [comment]
I already merged a fix. Just need to release it.

**Comment by zkochan** [comment]
:ship: 4.14.0-1
