### ISSUE TITLE
pnpm install registry.npmjs.org in <PROJECT>/node_modules/.pnpm/ why? 

### ISSUE THREAD

**Issue by MariuzM** [pnpm/pnpm#2480]
When i do `pnpm install` i have noticed that its also installing actual (not symlink) folder of `registry.npmjs.org` in `<PROJECT>/node_modules/.pnpm/`

Is this expected i thought that there should be a symlink but not actual files that taking up space. 

### pnpm version:
4.13.0
### Expected behavior:
I understand that there should be symlink but not actual folder?
### Actual behavior:
Expected a symlink to global node_modules `~/.pnpm-store/2/registry.npmjs.org/`
### Additional information:

 - `node -v` prints:
v13.12.0
 - Windows, OS X, or Linux?:
MacOS

**Comment by zkochan** [comment]
Those files are not taking up additional space because they are just hard links to the same files in the global store.

**Comment by MariuzM** [comment]
![Screenshot 2020-04-14 at 17 49 28](https://user-images.githubusercontent.com/36937039/79251624-50809200-7e78-11ea-95e0-ab53049c065b.png)
But these don't look like links, should they have that arrow on them?

**Comment by zkochan** [comment]
hard links look like regular files but two hard links point to the same location on the disk.

https://pnpm.js.org/en/faq#why-does-my-node-modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store
