### ISSUE TITLE
Unexpected package.json changes after pnpm update

### ISSUE THREAD

**Issue by cguglielmo** [pnpm/pnpm#2482]
### pnpm version:
>=4.2.2

### Code to reproduce the issue:
https://github.com/cguglielmo/pnpm-update-issue

### Expected behavior:
pnpm update does not modify dependency version constraints

### Actual behavior:
Running pnpm update with version 4.0.2 did what we expect: Check for the latest versions based on the ranges, download the packages and update the lock file.
With pnpm >= 4.2.2 (maybe even >=4.2.0-0, I did not verify that) it additionally updates package.json files and breaks the constraints. In the above git repository we have two dependencies:
1. One dependency to a workspace module: "pnpm_a": "1.0.0"
2. One dependency to a module that should be downloaded: "@eclipse-scout/core": ">=10.0.2-alpha <10.0.2"

After running pnpm update the versions will be adjusted as follows:
1. "pnpm_a": "1.0.0" to "pnpm_a": "workspace:1.0.0"
2.  "@eclipse-scout/core": ">=10.0.2-alpha <10.0.2" to "@eclipse-scout/core": "^10.0.2-alpha.1"

Lets talk about the second dependency first: As you can see, the version range is changed and now has a different semantic. If I ran the update again it would download version 10.0.8 which would not happen with the original constraint. This must not happen.
Also, updating the first dependency and adding "workspace:" looks wrong too. I always thought the workspace protocol is optional, but now it looks like we have to use it? In your help it is written: "By default, pnpm will link packages from the workspace if the available packages match the declared ranges." This still sounds as I can just use the version without using "workspace:". 

In the attached zip file you find screenshots showing what's going on.

Thank you for having a look into this!

### Additional information:
 - `node -v` prints: 12.12.0
 - Windows, OS X, or Linux?: Windows 10

[pnpm-update-issue.zip](https://github.com/pnpm/pnpm/files/4486460/pnpm-update-issue.zip)

**Comment by zkochan** [comment]
you may run `pnpm update --save` to get the old behaviour. It has a bug now that the lockfile specs are updated, but I am fixing it here: https://github.com/pnpm/pnpm/commit/dea672bc71f8b08ef080347360cf09fffc9e43d2

**Comment by cguglielmo** [comment]
Hi Zoltan,
thank you for the fast response! I was not aware of --no-save, this looks promising and probably solves our problem. Nevertheless, updating the version constraint from ">=10.0.2-alpha <10.0.2" to "^10.0.2-alpha.1" is still wrong, don't you think?

**Comment by zkochan** [comment]
Regarding the second issue, how does it work with npm/yarn?

**Comment by cguglielmo** [comment]
Looks like npm and yarn behave in the same way. I still think it is wrong but it is probably more important to be consistent. So it looks like the issue can be closed, thank you anyway.
