### ISSUE TITLE
How to handle shared peer dependencies

### ISSUE THREAD

**Issue by remorses** [pnpm/pnpm#2483]
I am developing 2 packages in pnpm workspaces, one is a react component library, called `react-library`, the other is a package that consumes it, let's call it `website`

In yarn workspaces i handled dependencies this way:
I install react in the `react-library` as a dev dependency
I also install react in the `website`
Then yarn would use the right react package in `react-library` and `website` because it would hoist react at the root node_modules

```json
{
    "name": "react-library",
    "dependencies": {

    },
    "devDependencies": {
        "react": "*",
        "react-dom": "*"
    },
    "peerDependencies": {
        "react": "*",
        "react-dom": "*"
    }
}
```

```json
{
    "name": "website",
    "dependencies": {
        "react-library": "*",
        "react": "*",
        "react-dom": "*"
    }
}
```

Is this correct?

I tried doing the same with `pnpm` but sometimes the react package is duplicated and i get the `Invalid hook call` error in react

I think this happens because `pnpm` tries to use the right peer version of react for certain dependencies that have an old react peerDependency version, from what i understood reading [how peers are resolved](https://pnpm.js.org/en/how-peers-are-resolved) pnpm resolves the react dependency based on the `peerDependency` version tag

**Comment by zkochan** [comment]
I guess the only reliable way to do this at the moment, is to install the exact version of react in both projects. Or install it in the root package of the repository and don't install it in other projects.

**Comment by thynson** [comment]
> install it in the root package of the repository and don't install it in other projects.

Partially agreed, but besides from put`react` and `react-dom` into workspace root, they should also be listed in `website`'s own dependencies, otherwise it may fails `strict-peer-dependencies`. 

So when you debugging and testing your `react-library`, you're using `react` and `react-dom` from workspace, while when you're building your `website`, webpack (or similar tools) will find them in node_modules of `website`.

This way give you extra flexibility, imagine that you're now using another package with optional peer dependencies, and you want to omit them in `react-library` but include them in `website`.

**Comment by remorses** [comment]
I have made a cli to check if multiple instances of a package exist in the project 
https://github.com/remorses/pnpm-count

If i find duplicates then i will try to update with `pnpm up --latest`

**Comment by zkochan** [comment]
There's also this: https://www.npmjs.com/package/syncpack

**Comment by stabback** [comment]
@zkochan Would you still recommend syncpack in 2022?  I don't see anything in the pnpm docs around ensure workspaces packages share the same dependency versions.

It'd be neat to have a `pnpm add --make-consistent` flag similar to `Rush`.

https://rushjs.io/pages/commands/rush_add/

```
  -m, --make-consistent
                        If specified, other packages with this dependency
                        will have their package.json files updated to use the
                        same version of the dependency.
```

**Comment by zkochan** [comment]
if you run `pnpm add pkg`, pnpm will search for pkg in the workspace. If `pkg@1` is already in the dependencies of a project, `pkg@1` will be added.
