### ISSUE TITLE
Unknown options 'prefer-frozen-lockfile', 'network-concurrency'

### ISSUE THREAD

**Issue by apostolisms** [pnpm/pnpm#2485]
We are getting the below error when --network-concurrency flag is used. Was that dropped from pnpm 4.x ?
Also the below command works fine If I don't use --network-concurrency.

### Additional information:

 - `node -v` prints: 10.19.0
 - Windows, OS X, or Linux?: OS X & Windows

**Comment by zkochan** [comment]
:ship: 4.14.0-2
