### ISSUE TITLE
(feature) Prevent `pnpm-debug.log` generation and/or generate them in a centralized place

### ISSUE THREAD

**Issue by MisterTicot** [pnpm/pnpm#2501]
### Desired behavior:

Providing an option that prevent `pnpm-debug.log` generation, or natively manage them like NPM: https://docs.npmjs.com/generating-and-locating-npm-debug-log-files

### Actual behavior:

pnpm generates a `pnpm-debug.log` in the current directory each time an error happens, which forces devs to clean up manually before committing changes.

**Comment by zkochan** [comment]
I guess, we could write the log file to `node_modules/.pnpm-debug.log`.

**Comment by zkochan** [comment]
What if we just put a try/catch and ignore if the debug file could not be written?

https://github.com/pnpm/file-reporter/blob/11b79f81b903ed2bb7a3fd4f875618974008a553/src/index.ts#L24-L30

**Comment by szegheo** [comment]
Hi,

It seems that with `pnpm v6.28.0` the debug log is still generated in the current dir, not in its `node_modules` dir. In my case, I would like to keep my project (git) dir clean, so I would be fine with the original `node_modules/.pnpm-debug.log` idea.

However, I thought there was some option for `.npmrc` to set a custom directory for debug logs but I haven't found any.
In my `Workspace`, my idea was to set the logging dir to my `workspace root` to collect all the debug logs to one file to make it easier to notice errors, but - AFAIK - this is not supported yet.

So I'm wondering if introducing a new option could solve the above problems?

Something like [Other settings](https://pnpm.io/npmrc#other-settings) / `debug-log-dir` :

`debug-log-dir=./`  <- relative to the `.npmrc` file (workspace root, my case)
`debug-log-dir=node_modules`  <- node_modules of the current dir

> I would like to ask if you could rethink and introduce a flag or a way to prevent the file from being written.

`debug-log-dir=/tmp/whatever` (possible workaround (?))
