### ISSUE TITLE
PNPM stuck for 40min without any feedback

### ISSUE THREAD

**Issue by MoussaAdam** [pnpm/pnpm#2502]
### Code to reproduce the issue:
just install firebase
- `pnpm install 'firebase'`
- `pnpm add 'firebase'`

### Expected behavior:
- try install firebase as a dependency
- report an error otherwise
Alternative:
  - or minimal logging of currently running operation in real-time
    - yarn does that btw, and log when connection is slow

### Actual behavior:
- pnpm resolves packages
- pnpm hang until the user decide stop it (Ctrl-C)
  - (i guess waiting 40min was more than enough)
- the packages is not installed
- no logs
![2020-04-26_07-22](https://user-images.githubusercontent.com/29833334/80300057-3f495680-8791-11ea-85a1-a841be945c28.png)

### Additional information:
 - `node -v` prints:v13.12.0
 - Operating System: Arch Linux
---------
 - Configuration: i set a prefix to follow the XDG standards:
   - `pnpm config set prefix "/home/$USER/.cache/pnpm/"`
 - Network: my internet connection is slow, but even if the problem is from my side, pnpm should tell me if the connection timed out, rather than waiting forever without any comment
**Edit:** i tried with a good internet connection and the problem persist

**Comment by MoussaAdam** [comment]
i guess this is related to #1240 or maybe a more detailed duplicate, sorry about that
but anyways i guess it would be good to have another discussion about this after 2 years of not doing anything about it

**Comment by MoussaAdam** [comment]
just updated to 4.14.2 and the problem fixed, sorry for bothering
i will close the issue but still wish we have realtime logging of currently running operation

**Comment by zkochan** [comment]
track the other issue for progress
