### ISSUE TITLE
pnpm cannot find module '.../package.json'

### ISSUE THREAD

**Issue by sundogya** [pnpm/pnpm#2505]
when i run:
`pnpm install`
`pnpm run dev:h5`
in my project , i get this error:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/Users/sundogya/Documents/Vue/circle/node_modules/.pnpm/registry.npmjs.org/@dcloudio/vue-cli-plugin-hbuilderx/2.0.0-26920200424005/package.json'
```
pnpm version:
4.14.1

but these
`npm install`
`npm run dev:h5`

`yarn install`
`yarn run dev:h5`
can work.
Anybody get some problem with me ?

**Comment by nikoladev** [comment]
I don't know what `dev:h5` does, but if it works in yarn and npm you could try the following:

1. Delete `node_modules` and `pnpm-lock.yaml`
2. Run `pnpm install --shamefully-hoist`
3. Run `pnpm run dev:h5`

Also, check out if the FAQ can help: https://pnpm.js.org/en/faq#pnpm-does-not-work-with-your-project-here

**Comment by sundogya** [comment]
I tried this 
`rm -rf node_modules pnpm-lock.yaml`
`pnpm install --shamefully-hoist`
`pnpm run dev:h5`
And i still get the error above

**Comment by zkochan** [comment]
Looks like not an issue with pnpm

In worst case, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
