### ISSUE TITLE
Question: How to get logs of `postinstall` hook of dependency?

### ISSUE THREAD

**Issue by timsuchanek** [pnpm/pnpm#2507]
When executing `pnpm install` I would like to be able to see the logs of a `postinstall` hook of one of my dependencies.

How can I accomplish that?

I tried `pnpm i --verbose` as well as `pnpm i --reporter ndjson`, both don't give me the logs of the `postinstall` hook of my dependency.

**Comment by zkochan** [comment]
Try `pnpm install --reporter append-only`

**Comment by timsuchanek** [comment]
Thanks, this is indeed what I need.
