### ISSUE TITLE
v4.14.1 throwing EEXIST in CI

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#2508]
### Code to reproduce the issue:

This is where it's muddy.
This run produces the error: https://circleci.com/gh/rollup/plugins/3781
This run on v4.14.0 does not have the issue: https://circleci.com/gh/rollup/plugins/3776

### Expected behavior:

Success installing as in https://circleci.com/gh/rollup/plugins/3776

### Actual behavior:

 ERROR  EEXIST: file already exists, mkdir '/home/circleci/project'

### Additional information:

 - `node -v` prints: 12.16.3
 - Windows, OS X, or Linux?: Linux

**Comment by shellscape** [comment]
This looks like another possible CircleCI issue (they had claimed no service issues, but evidence says otherwise now that it's working). I've rerun the build and everything succeeded this time. I'll close for now and keep an eye on it.

**Comment by zkochan** [comment]
I downgraded latest to 4.14.0
that's probably why it worked.

**Comment by shellscape** [comment]
Ah cool. Should we reopen?

**Comment by zkochan** [comment]
I replaced `make-dir` with `fs.mkdir('', { recursive: true })`. Maybe somewhere I used fs.mkdir, w/o the recursive option but I don't see where.

**Comment by zkochan** [comment]
I don't understand what is the issue. I cannot reproduce it locally.

**Comment by shellscape** [comment]
Later today I'll force install of 4.14.1 on a branch and follow up. It may be something that we have to replicate within a contain on that distro of Linux.

**Comment by zkochan** [comment]
I clone the repo and add `--reporter ndjson`. The error doesn't contain the stacktrace though. I don't understand how's that possible

```
#!/bin/bash -eo pipefail
pnpm install --ignore-scripts --reporter ndjson

{"time":1588062411685,"hostname":"bd78e8e7d5c1","pid":86,"level":"debug","name":"pnpm:scope","selected":26,"total":26,"workspacePrefix":"/home/circleci/project"}
{"time":1588062411692,"hostname":"bd78e8e7d5c1","pid":86,"level":"error","name":"pnpm","message":{"errno":-17,"code":"EEXIST","syscall":"mkdir","path":"/home/circleci/project"},"err":{"name":"Error","message":"EEXIST: file already exists, mkdir '/home/circleci/project'","code":"EEXIST","stack":"Error: EEXIST: file already exists, mkdir '/home/circleci/project'"}}

Exited with code exit status 1
```

I also read the diff between 4.14.0 and 4.14.1 several times and don't see anything that could cause this.

**Comment by shellscape** [comment]
this is a true gremlin! Does the error appear in Node 14?

**Comment by zkochan** [comment]
Seems like it runs Node v10.7.0 for some reason. pnpm needs node v10.12 at least

**Comment by shellscape** [comment]
OK I'll update the container today and will force install 4.14.1 and report back

**Comment by shellscape** [comment]
OK I tracked this down to an errant image that did indeed install 10.7.0. Took me a bit to remember that we had linting and such running off of a base image and not a node version specific image. I'll have to remedy that one. Updated the container and we're good! The old node version was the problem.
