### ISSUE TITLE
pnpm .bin files and compatibility with Nrwl NX?

### ISSUE THREAD

**Issue by iangregsondev** [pnpm/pnpm#2516]
Hi,

I wonder if you can help? I am trying to get nrwl nx working with pnpm - it is supposed to work although I see one issue. When doing an npm install then the ".bin" contains an "nx" file.

but when doing a pnpm install - it doesn't.

I was wondering if it's related to the limitations case that you explain here  (3) https://pnpm.js.org/en/limitations and wondered what I can do about it.

I pasted a GitHub issue here https://github.com/nrwl/nx/issues/2944

Basically on an npm installed system this file is placed in the .bin (called nx) but on pnpm it is missing or located in a different place. (see above GitHub issue) 

```
#!/usr/bin/env node
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// polyfill rxjs observable to avoid issues with multiple version fo Observable installed in node_modules
// https://twitter.com/BenLesh/status/1192478226385428483?s=20
Symbol.observable = Symbol('observable polyfill');
const find_workspace_root_1 = require("../lib/find-workspace-root");
const init_global_1 = require("../lib/init-global");
const init_local_1 = require("../lib/init-local");
const workspace = find_workspace_root_1.findWorkspaceRoot(__dirname);
if (workspace) {
    init_local_1.initLocal(workspace);
}
else {
    init_global_1.initGlobal();
}

```

Thanks in advance

**Comment by zkochan** [comment]
Only the bins of the direct dependencies are included into `node_modules/.bin`.

pnpm also creates a "flat" node_modules inside `node_modules/.pnpm/node_modules` in order to make the broken packages in the ecosystem work. So the bin files of subdependencies are linked to `node_modules/.pnpm/node_modules/.bin`.

**Comment by offwork** [comment]
I had the same problem. I guess **pnpm** doesn't recognize **nx** and **ng** commands. I hope this solves your problem: 

```
pnpm add --global nx
pnpm add --global @angular/cli
```
and then

```
pnpx nx g @nrwl/angular:lib ui --directory shared
```
<img width="893" alt="Screen Shot 2022-02-04 at 13 59 16" src="https://user-images.githubusercontent.com/10039583/152519927-d38dc10c-fceb-4737-b40f-6349f3c04622.png">
