### ISSUE TITLE
Feature Suggestion: Builtin "Only allow pnpm"

### ISSUE THREAD

**Issue by ozum** [pnpm/pnpm#2517]
Hi,

I'm reading pnpm web site and see [only allow pnpm page](https://pnpm.js.org/en/only-allow-pnpm).

Could it be added to pnpm as a builtin feature, so one can have something like below?

```json
{
  "scripts": {
    "preinstall": "pnpm --onlyAllowPnpm"
  }
}
```

Best,

**Comment by zkochan** [comment]
I like this idea. This way, pnpm could even skip running the preinstall script if the content is the builtin command.

**Comment by alexeyten** [comment]
But if one doesn’t have pnpm, he will get a cryptic error message?

**Comment by zkochan** [comment]
indeed... but we could use npx. npx would install pnpm before calling.

Something like `npx pnpm guard`

**Comment by zkochan** [comment]
Actually, we could create a small library for this, something like `npx pnpm-guard`.
