### ISSUE TITLE
Simplify running recursive longer running (watcher) scripts

### ISSUE THREAD

**Issue by rfestag** [pnpm/pnpm#2528]
As a developer using monorepos, I would like to have a simpler workflow for running long-running watcher processes during development. In my use case, I have a `/packages` and an `/apps` directory. My apps (and some packages) depend on packages defined in `/packages`. I want all of my packages and apps to have a `start` script that runs the dev server for them (say, with `babel -w` or `next dev` as appropriate). These processes do not exit. 

Currently, I have this defined in my root package.json:

```javascript
{
  ...
  "scripts": {
    ...
    "start": "pnpm run -r --no-sort --workspace-concurrency Infinity --filter ./apps --filter ./packages start"
  }
}
```

We need the `--no-sort` to ensure that all of the watchers start. Without them, pnpm waits for the dependency scripts to complete before starting the dependent scripts.

We need `--workspace-concurrency` to handle more than the 4 defaults

We need `--filter` because otherwise the "start" script in the root package will be run infinitely. So we need to skip it.

A few things that could be done to make this nicer:
1. [x] Remove the need for the filters. A sane default would probably be to detect cycles in the scripts and not run them (or, at a minimum, detect if the run command would re-execute the current command directly)
2. [ ] A shorthand command to run watchers that basically does the above. Perhaps a `-w` flag indicating that this is a watched run?

**Comment by zkochan** [comment]
We could call this new flag `--parallel`. Lerna has this [flag](https://github.com/lerna/lerna/tree/master/commands/run#--parallel).

**Comment by zkochan** [comment]
I think it might make sense to make `--parallel` the default behavior for `pnpm start -r`

**Comment by rfestag** [comment]
Yea, that definitely makes sense to me.

**Comment by zkochan** [comment]
:ship: [5.1.0](https://github.com/pnpm/pnpm/releases/tag/v5.1.0)
