### ISSUE TITLE
Package name suffix encoding breaks install using rush in CI environment

### ISSUE THREAD

**Issue by jtran19** [pnpm/pnpm#2535]
### Code to reproduce the issue: 
Repro repo: https://github.com/jtran19/pnpm-encoding.git

### Expected behavior:
When using rush (www.rushjs.io) in a CI environment, `pnpm install` is able to link local dependencies having peerDependencies and the package ID suffix is in the format `_<pkgName>@<version>+<pkgName>@<version>`.

```
Checking node_modules in /Developer/pnpm-encoding/common/temp

Deleting: /Developer/pnpm-encoding/common/temp/rush-link.json

Running "pnpm install" in /Developer/pnpm-encoding/common/temp

Using hooks from: /Developer/pnpm-encoding/common/temp/pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
Packages: +55
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 55, reused 55, downloaded 0, done
node_modules/.pnpm/registry.npmjs.org/core-js/2.6.11/node_modules/core-js: Running postinstall script, done in 93ms

dependencies:
+ @rush-temp/subapp 0.0.0
+ react-cosmos-apollo-proxy 4.8.2
+ react-dom 16.8.6 (16.13.1 is available)
+ react-router-dom 5.1.2
Updating /Developer/pnpm-encoding/common/config/rush/pnpm-lock.yaml

Linking projects together...

LINKING: @jtran/app
Purging /Developer/pnpm-encoding/packages/app/node_modules

LINKING: @jtran/core
Purging /Developer/pnpm-encoding/packages/core/node_modules

LINKING: @jtran/server
Purging /Developer/pnpm-encoding/packages/server/node_modules

LINKING: @jtran/subapp
Purging /Developer/pnpm-encoding/packages/subapp/node_modules
Writing "/Developer/pnpm-encoding/common/temp/rush-link.json"

Linking finished successfully. (0.04 seconds)
```

### Actual behavior:
The package directory name in `.pnpm/local/` has the encoded suffix `...subapp.tgz_react-dom%4016.8.6%2Breact%4016.13.1` but `pnpm install` is looking for the un-encoded `...subapp.tgz_react-dom@16.8.6+react@16.13.1` as specified in `pnpm-lock.yaml`.  The bug can be reproduced by setting `BUILD_NUMBER=1` to make `is-ci` think it is running in a Jenkins environment.

```
Checking node_modules in /Developer/pnpm-encoding/common/temp

Linking projects together...

LINKING: @jtran/app
Purging /Developer/pnpm-encoding/packages/app/node_modules

LINKING: @jtran/core
Purging /Developer/pnpm-encoding/packages/core/node_modules

LINKING: @jtran/server
Purging /Developer/pnpm-encoding/packages/server/node_modules

LINKING: @jtran/subapp

ERROR: Internal Error: Cannot find installed dependency "react-cosmos-apollo-proxy" in
"/Developer/pnpm-encoding/common/temp/node_modules/.pnpm/local/%2FDeveloper%2Fpnpm-encoding%2Fcommon%2Ftemp%2Fprojects%2Fsubapp.tgz_react-dom@16.8.6+react@16.13.1/node_modules"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

### Additional information:

- `rush version`
```
Rush Multi-Project Build Tool 5.17.2 - https://rushjs.io
Node.js version is 10.16.0 (LTS)


Starting "rush version"
```
 - macOS 10.15.4 & RHEL7

#### Possible patch:
https://github.com/pnpm/pnpm/blob/fbc7c3552876d219da3d999204070b968e48a991/packages/supi/src/install/resolvePeers.ts#L395-L408
In this function, the package name suffix is hashed if longer than 32 symbols to prevent directory names from becoming too long.  Since the hash is the same encoded or not, having enough peer dependencies to make the package suffix sufficiently long keeps the package from having this issue.  In the local copy of `pnpm` that `rush` downloads, I patched this by always hashing the suffix and the install step succeeds in a CI environment.

```
function createPeersFolderSuffix (peers: Array<{name: string, version: string}>) {
  const folderName = peers.map(({ name, version }) => `${name.replace('/', '+')}@${version}`).sort().join('+')

  return `_${crypto.createHash('md5').update(folderName).digest('hex')}`
}
```

**Comment by zkochan** [comment]
We can fix this by updating `@pnpm/pkgid-to-filename`. Probably plus chars should not be encoded

https://github.com/pnpm/pkgid-to-filename/blob/81f1d9c180a2439317d486335dbeed4131837b06/src/index.ts#L8

**Comment by jtran19** [comment]
Is there a reason to keep the un-encoded suffix?

**Comment by zkochan** [comment]
Just because it gets written to the lockfile and I guess it is more readable when not hashed.
