### ISSUE TITLE
ELIFECYCLE Error: Exit status 3221226356

### ISSUE THREAD

**Issue by TeckFreak** [pnpm/pnpm#2540]
After updating the pnpm to latest 4.14.2 release, I am going to this strange error.

I'm using nodegui in one of my projects. Till 4.12 release it was working fine. After the updating pnpm to 4.14.2 and then using `pnpm install @nodegui/nodegui` everything works fine. But after I use `pnpm start` my application crashes.
I'm sure that this is in pnpm as the project is working fine will older pnpm and latest npm, but not latest pnpm.

Below is my debug log:

```
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 error pnpm": {
    "message": {
      "errno": 3221226356,
      "code": "ELIFECYCLE",
      "pkgid": "engine-automation-tool@1.0.0",
      "stage": "start",
      "script": "webpack && qode ./dist/index.js",
      "pkgname": "engine-automation-tool"
    },
    "err": {
      "name": "Error",
      "message": "engine-automation-tool@1.0.0 start: `webpack && qode ./dist/index.js`\nExit status 3221226356",
      "code": "ELIFECYCLE",
      "stack": "Error: engine-automation-tool@1.0.0 start: `webpack && qode ./dist/index.js`\nExit status 3221226356\n    at EventEmitter.<anonymous> (C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\pnpm\\lib\\node_modules\\@zkochan\\npm-lifecycle\\index.js:302:16)\n    at EventEmitter.emit (events.js:310:20)\n    at ChildProcess.<anonymous> (C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\pnpm\\lib\\node_modules\\@zkochan\\npm-lifecycle\\lib\\spawn.js:55:14)\n    at ChildProcess.emit (events.js:310:20)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
    }
  }
}
```

**Comment by zkochan** [comment]
Which was the last version that worked?

Does it work with pnpm v5?

**Comment by TeckFreak** [comment]
Not tried with pnpm 5 at it's not stable and not showing update from `pnpm start`

To reproduce error, you can try running this project template by running `pnpm install` then `pnpm start`.

https://github.com/RinneganTech/nodegui-mvc-starter

**Comment by zkochan** [comment]
Not reproducible on Linux. With Node.js 12.16.3. Tried pnpm v4.14.2 and v5.0.0-alpha.5

Might be Windows related.

**Comment by TeckFreak** [comment]
Yes, occurring on Windows

**Comment by zkochan** [comment]
Issue is gone?

**Comment by TeckFreak** [comment]
Not yet.
