### ISSUE TITLE
[bug] - Can't execute 2 pnpm commands at the same time

### ISSUE THREAD

**Issue by Olyno** [pnpm/pnpm#2550]
### Code to reproduce the issue:

https://gist.github.com/Olyno/eb2c3b41ecdc3642203d8727a00b21f7

### Expected behavior:

Execute 2 pnpm command at the same time.

### Actual behavior:

When executing ``pnpm run start`` using code I gave above, you should get this message

```
┌────────────────────────────────────────────────────────────┐
│                  pnpm update check failed                  │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\WIN10\.config │
└────────────────────────────────────────────────────────────┘
```

Both codes seems executed, but they are not. If 2 web servers with different ports are running, only the first one will works correctly.

### Additional information:

 - `node -v` prints: 14.0.0
 - Windows, OS X, or Linux?: Windows 10

**Comment by mcmxcdev** [comment]
The gist was deleted and most likely an outdated issue -> pnm v4 vs v7 now

Let me know if you can still reproduce this issue, then I will reopen this ticket.
