### ISSUE TITLE
(cli) outdated help or non working --modules-dir option

### ISSUE THREAD

**Issue by jmlopez-rod** [pnpm/pnpm#2567]
### Code to reproduce the issue:

```
# pnpm install --modules-dir whatever
 ERROR  Unknown option 'modules-dir'
For help, run: pnpm help add

```
### Expected behavior:

should install in `whatever` instead of `node_modules` directory

### Additional information:

 - `node -v` prints: v12.16.2
 - Windows, OS X, or Linux?: OS X

```
# pnpm install --help
Version 4.14.2
Usage: pnpm install [options]

Alias: i

Installs all dependencies of the project in the current working directory. When executed inside a workspace, installs all dependencies of all projects.

Options:
      <removed options>
      --modules-dir <dir>                       The directory in which dependencies will be installed (instead of node_modules)
```

Please note that I wanted to use this flag to make it install in some directory where it can access the pnpm-store mounted in a docker volume.

**Comment by zkochan** [comment]
as a temp solution, set the value of modules-dir in a `.npmrc` file

**Comment by jmlopez-rod** [comment]
Docs on .npmrc file:

https://pnpm.js.org/en/npmrc#modules-dir

Added

```
modules-dir=whatever
```

Worked fine, but if instead of `whatever` i set it to `/pnpm-cache` it doesn't do anything.

But, it does work if we use relative paths.

```
modules-dir=../../../../pnpm-cache/whatever
```

does the trick.
