### ISSUE TITLE
Print an info message about `node_modules/.pnpm`

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2572]
We get lots of questions about why files in node_modules are not symlinked from the global store. People think that we copy files to node_modules.

We need to print some message about `node_modules/.pnpm` after a fresh installation in order to explain why it is needed and that it does not contain copies of files, just hard links.

**Comment by jmlopez-rod** [comment]
Would also help to state when they are copied, this can happen in docker when we mount volumes and the store is placed in a different drive.

**Comment by yaodingyd** [comment]
Maybe we can expand the "Resolving: total XXX, reused XXX, downloaded XXX" a bit more? like "hardlinked (copied) XXX packages in node_modules/.pnpm"
