### ISSUE TITLE
pnpm v5.0.0 raises an error in Rush due to the use of --no-lock

### ISSUE THREAD

**Issue by eozu** [pnpm/pnpm#2581]
Rush fails to install under PNPM 5.0.0 since it uses --no-lock.

I realize this is more of a Microsoft Rush issue (they will need to remove the `--no-lock` flag in their `rush update` process), but I noticed that PNPM v5.0.0 is out of release candidate stage and may be released soon (if not already).

It may be nice to inform users of the known issue (**edit**: you did 👍), or consider deprecating --no-lock in the v4 for a few patch versions or noop in v5.

### Code to reproduce the issue:

```
npm install -g @microsoft/rush
git clone https://github.com/microsoft/rushstack
# Configure rush.json to use pnpm 5.0.0
cd rushstack
rush update
```

### Expected behavior:
PNPM should install the monorepo correctly.

### Actual behavior:

The user receives the following error:

```
 ERROR  Unknown option 'lock'
For help, run: pnpm help install

The command failed:
 /Users/eozu/Sandbox/rushstack/common/temp/pnpm-local/node_modules/.bin/pnpm install --no-lock --no-prefer-frozen-lockfile --strict-peer-dependencies
ERROR: Error: The command failed with exit code 1
```

### Additional information:

 - `node -v` prints: 12.17.0
 - Windows, OS X, or Linux?: macOS Catalina 10.15.5

**Comment by alexeyten** [comment]
May be it should be ignored instead of failing. 
It could print a warning saying the option will be removed in next major release

**Comment by zkochan** [comment]
I will fix that a bit later. I don't think this is a blocker for shipping v5

**Comment by zkochan** [comment]
:ship: 5.0.1
