### ISSUE TITLE
No feedback from pnpm publish, can't tell if it thinks it is working

### ISSUE THREAD

**Issue by nategreen** [pnpm/pnpm#2591]
### Code to reproduce the issue:

`pnpm publish -r --registry=<our-azure-artifacts-registry-url>`

### Expected behavior:

Publish packages in our workspace that haven't been published to the registry yet.

### Actual behavior:

???

PNPM fails predictably in some circumstances, e.g. if I'm not on the `publish-branch`. But at the point when I'd expect to see it doing pre-publish builds, packing, etc. it seems to just show nothing and exit.

I can't really tell if it's doing anything or not. I've tried it in cmd.exe and Git bash with the same results that I saw when adding it to an Azure Pipelines CI setup. It _did not_ publish the packages, but I can't tell if it _thinks_ it did or not, so I can't tell whether I need to rule it out or troubleshoot further.

### Additional information:

 - `node -v` prints: ` v12.13.1 `
 - Windows, OS X, or Linux?: Windows 10 and also Azure Pipelines Linux VM (I think)

**Comment by nategreen** [comment]
I'll also note that I've attempted to pass `--loglevel=debug` and it still showed nothing more than when I ran it without.

**Comment by zkochan** [comment]
Does publish work when going directly to a package's directory and running `pnpm publish --registry-<>"?

**Comment by nategreen** [comment]
Yes; when I do that, it runs through the package's pre-publish scripts and packs the tarball and all that—none of which seemed to happen when doing it recursively.

**Comment by nategreen** [comment]
Not sure what changed, but it seems to be working correctly in 5.4.8.
