### ISSUE TITLE
pnpm vs yarn produced different results

### ISSUE THREAD

**Issue by idkjs** [pnpm/pnpm#2594]
Per [pnpm-tweet](https://twitter.com/_idkjs/status/1266744555011026945?s=21)
### Code to reproduce the issue:

https://github.com/idkjs/pnpm-types-issue

### Expected behavior:

That both dependencies installation produce a working package.

### Actual behavior:

In this example, the yarn package works.

### Additional information:

```sh
~/Downloads/pnpm-types-issue master
❯ pnpm -v
5.0.2

~/Downloads/pnpm-types-issue master
❯ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E287

~/Downloads/pnpm-types-issue master
❯ node -v
v13.11.0
```

**Comment by zkochan** [comment]
So it appears that some projects have issues with types when pnpm is used. These issues are gone if the `shamefully-hoist` setting is set to `true`.

I think we can do the next thing. We can hoist all packages from the `@types` scope to the root of node_modules.

**Comment by zkochan** [comment]
Created a separate issue: #2628

**Comment by zkochan** [comment]
:ship: 5.2.0
