### ISSUE TITLE
pnpm store status: ENOENT integrity.json

### ISSUE THREAD

**Issue by yoursunny** [pnpm/pnpm#2597]
### Code to reproduce the issue:

1. Delete `$HOME/.pnpm-store` directory.
2. Create `package.json` shown below. It must contain a GitHub dependency.
3. `pnpm i`
4. `pnpm store status`

**package.json**
```json
{
  "private": true,
  "dependencies": {
    "mole-rpc": "koorchik/node-mole-rpc"
  }
}
```

### Expected behavior:

```shell
$ pnpm store status
Packages in the store are untouched
```

### Actual behavior:

```shell
$ pnpm store status
 ERROR  ENOENT: no such file or directory, open 'C:\Users\sunny\.pnpm-store\v3\github.com\koorchik\node-mole-rpc\c96cf2db76e85c7927f9e6c6e6fdc483334e3bac\integrity.json'

$ find $HOME/.pnpm-store | grep integrity.json
/c/Users/sunny/.pnpm-store/v3/github.com/koorchik/node-mole-rpc@c96cf2db76e85c7927f9e6c6e6fdc483334e3bac/integrity.json
```

In other words:
* `pnpm install` generates `.pnpm-store/v3/github.com/user/repo@commit/integrity.json`.
* `pnpm store status` is looking for `.pnpm-store/v3/github.com/user/repo/commit/integrity.json`.

### Additional information:

* Node 14.2.0
* Windows 10 version 2004
* Git for Windows 2.26.2

```shell
$ pnpm version
{
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.40.0',
  node: '14.2.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '8.1.307.31-node.33',
  zlib: '1.2.11'
}
```

**Comment by wachunga** [comment]
Still an issue in 5.17.2

**Comment by zkochan** [comment]
:ship: 5.18.9
