### ISSUE TITLE
Fails to install from private registry (bytesafe.dev)

### ISSUE THREAD

**Issue by arikon** [pnpm/pnpm#2602]
### Code to reproduce the issue:

pnpm install anything --registry https://something-on.bytesafe.dev

### Expected behavior:
pnpm installs packages from the private registry on bytesafe.dev.

### Actual behavior:
pnpm fails to install packages from the private registry on bytesafe.dev.

### Additional information:
The reason it pnpm removes auth info on every redirect, but should only remove it on the redirects to other domains. And should preserve auth info on redirects on the same domain.

This was removed here: https://github.com/pnpm/pnpm/issues/1815

 - `node -v` prints:v12.17.0
 - Windows, OS X, or Linux?: OS X

**Comment by arikon** [comment]
Here is the response from the Bytesafe.dev support:

> Hello,
> 
> We have found the cause of the issue that you are experiencing. It is mainly do to two things in the pnpm client:
> ​
> The pnpm client does not send authorization headers on a redirect and our server sends a redirect on package installation. They had an issue where they were sending authorization headers to other domains:
> https://github.com/pnpm/pnpm/issues/1815
> 
> Their solution was to not send authorization headers at all even for the same domain.
> 
> The pnpm does not report back to the user that the server has responded with a "401 Unauthorized" but instead retries and hat is why you are stuck for 20 minutes installing.
> ​
> Because of these things we do not support the pnpm client at the moment as this behavior is very inconsistent with the other package managers npm and yarn. We are looking into how we could fix this issue but my suggestion would be to open an issue with pnpm client on github.
> 
> Best regards,
> Rasmus C.R

**Comment by zkochan** [comment]
I guess, if the target domain is the same as the original one, we may pass the auth token

cc @pnpm/collaborators

**Comment by aparajita** [comment]
Logically auth tokens should be treated like session cookies, thus they should always be passed to requests to the same domain on which they are received.

**Comment by zkochan** [comment]
:ship: 5.1.3
