### ISSUE TITLE
Use base32 in file names inside the store

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2606]
Looks like you have eCryptfs
https://unix.stackexchange.com/a/32834/61540

@zkochan hex is really long. May be consider to use base64/base36/base32?

_Originally posted by @alexeyten in https://github.com/pnpm/pnpm/issues/2605#issuecomment-638061040_

**Comment by zkochan** [comment]
If we do this, we'll have to think about what part of the new base36 file name to use for the directory name. Currently, we use the 1st to letters of the hex to create a folder. E.g., `24/886a9c26ac23dc....`

**Comment by alexeyten** [comment]
base36 is not really easy to use.
I would suggest base32 as it's exactly 5 bits.

Actually I'm not sure how to effectively encode sha512 to base36.

**Comment by zkochan** [comment]
It appears that currently, we use Node's native [buffer](https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html) library which only supports hex and base64. It is probably written in C for speed. So I am afraid that if we'll use javascript, it will be slower.

**Comment by ExE-Boss** [comment]
Most of **Node**’s `Buffer` implementation is actually in **JavaScript**:
- [buffer](https://github.com/nodejs/node/blob/master/lib/buffer.js)
- [internal/buffer](https://github.com/nodejs/node/blob/master/lib/internal/buffer.js)

**Comment by zkochan** [comment]
Interesting. Well I will measure the speed for sure.

**Comment by zkochan** [comment]
I tried with this library: https://github.com/LinusU/base32-encode

speed seems to be the same
disk space usage the same
file names are shorter by 25 chars

**Comment by zkochan** [comment]
The reason there is no speed improvement might be because there are a lot more directories created. The store creates a directory from the two first letters of the hash. With base32 there will be 1024 directories vs 256 directories with base16

**Comment by alexeyten** [comment]
1024 vs 256 doesn’t sound like a big deal. 
Anyway, the original problem was not about speed but too long filenames.

**Comment by zkochan** [comment]
Yes. I don't know why speed is the same. Maybe on windows it'd make a
difference.

Alexey Ten <notifications@github.com> ezt írta (időpont: 2021. febr. 7., V
9:37):
