### ISSUE TITLE
mz/fs

### ISSUE THREAD

**Issue by Pytal** [pnpm/pnpm#2609]
Is there a reason why the `mz/fs` library is used [L7](https://github.com/pnpm/pnpm/blob/fe0eea23c153e736a545645f9bd749a8dc2b1136/packages/npm-resolver/src/pickPackage.ts#L7) in place of the core [`fs/promises`](https://nodejs.org/api/fs.html#fs_fs_promises_api)?

**Comment by zkochan** [comment]
It used to not work on all Node versions that we supported. Maybe it is not the case anymore. We support 10.13 and up

**Comment by zkochan** [comment]
oh, actually there's another reason as well. We use graceful-fs and it does not support fs.promises yet.

**Comment by Pytal** [comment]
Thanks! Good to know 👍

**Comment by zkochan** [comment]
mz/fs is not used anymore.
