### ISSUE TITLE
"link-workspace-packages" not respected when check if lockfile is up to date

### ISSUE THREAD

**Issue by defjosiah** [pnpm/pnpm#2618]
### Code to reproduce the issue:

Set up a project, with some importers using
```
{
  dependencies: {
    "dep-a": "workspace:*"
  }
}
```

Other importer
```
{
    dependencies: {
    "dep-a": "0.0.0-xyzabc"
  }
}
```

Run `pnpm install`
Run `pnpm install` again

It does the full resolution both times, even though nothing changes in the deps.
It does not log "Lockfile is up-to-date, resolution step is skipped"

`pnpm install --frozen-lockfile`
Correctly installs from the lockfile, and doesn't throw an error.

### Expected behavior:
It should not run the resolution step again, the lockfile is up to date.

### Actual behavior:
It runs the resolution step again, and the lockfile doesn't change.

## Where I think the problem is
I think the issue is in 
`pnpm/packages/supi/src/install/allProjectsAreUpToDate.ts`
In this section:
```
// function() linkedPackagesAreUpToDate
const currentSpec = manifestDeps[depName]
      if (!currentSpec) continue
      const lockfileRef = lockfileDeps[depName]
      const isLinked = lockfileRef.startsWith('link:')
      if (
        isLinked &&
        (
          currentSpec.startsWith('link:') ||
          currentSpec.startsWith('file:')
        )
      ) {
        continue
      }
      const linkedDir = isLinked
        ? path.join(projectDir, lockfileRef.substr(5))
        : workspacePackages?.[depName]?.[lockfileRef]?.dir
      if (!linkedDir) continue
      const linkedPkg = manifestsByDir[linkedDir] ?? await safeReadPkgFromDir(linkedDir)
      const availableRange = getVersionRange(currentSpec)
      // This should pass the same options to semver as @pnpm/npm-resolver
      const localPackageSatisfiesRange = availableRange === '*' ||
        linkedPkg && semver.satisfies(linkedPkg.version, availableRange, { loose: true })
      if (isLinked !== localPackageSatisfiesRange) return false
```
I debugged this, and the problem is that it is "not linked" when the import is not the "workspace:*" import. But the "workspacePackages?.[depName]?.[lockfileRef]?.dir" section returns a package, because it is a workspace dep for other packages in the monorepo.

I believe there should be a condition there that checks if "link-workspace-packages" is false and `continues` if the currentSpec is not a "workspace:" ref.

Hopefully this is clear, please let me know if anything needs to be clarified.

**Comment by defjosiah** [comment]
@zkochan I realized my explanation was already most of the way to what I understand the bug to be, so opened up a PR with the fix. I think I followed the contributing rules correctly. Hopefully that's an easier reproduction to understand 😄

**Comment by zkochan** [comment]
:ship: 5.1.5

**Comment by defjosiah** [comment]
Woah, awesome, thanks for the quick turnaround!
