### ISSUE TITLE
Resolving to newer versions of packages in the workspace

### ISSUE THREAD

**Issue by walkerburgin** [pnpm/pnpm#2624]
### Code to reproduce the issue:
I'm working on migrating a large monorepo from yarn (v1) to pnpm. As a result, I'm iterating on a long lived feature branch. Every time a package in the workspace is released from the mainline branch, pnpm starts trying to resolve to the newer version from the registry even though the local version in the workspace still fulfills the declared constraints. 

For example, `foo-app` depends on `foo-lib@^0.1.11` and my branch has `foo-lib@0.1.11`. When `foo-lib@0.1.12` is released from the mainline branch I get the following diff when running `pnpm install`: 

```diff 
-      'foo-lib': 'link:../foo-lib'
+      'foo-lib': 0.1.12
```

### Expected behavior:
I expected to continue resolving to the version in the workspace. 

### Actual behavior:
Pnpm resolves to the newest version from the registry

### Additional information:

 - `node -v` prints: v10.18.1
 - Windows, OS X, or Linux?: OSX

**Comment by zkochan** [comment]
If you want your dependency to be linked from the monorepo, even if the latest is bigger then the one in the repo, you may use [workspace ranges](https://pnpm.js.org/en/workspaces#workspace-ranges-workspace).

**Comment by walkerburgin** [comment]
Hrmm, ok. For what it's worth, It seems like editing `package.json` by hand and then running `pnpm install` instead of using `pnpm add` does closer to what I'm looking for. I do think there's something nice about the way that Yarn naturally pushes you to have fewer distinct versions of a dependency in a monorepo (although not fewer distinct copies 😄 ). It makes `@type` mismatches less likely for TypeScript projects and makes webpack less likely to accidentally bundle multiple compatible copies of a dependency. 

In any case, thanks for the help! The ability to use `--filter` to install dependencies for a subset of the repo is a game changing, killer feature for very large monorepos.

**Comment by walkerburgin** [comment]
I think the original issue here is resolved by https://github.com/pnpm/pnpm/pull/2980. We ended up just mandating the use of the `workspace:` protocol which has been fine as well.
