### ISSUE TITLE
feat: public-hoist-pattern

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2628]
There are still many stacks that don't work well with pnpm without `shamefully-hoist=true`. Making `shamefully-hoist` `true` by default would destroy pnpm's strictness. However, if we could hoist some types of dependencies to the root node_modules by default, we could solve most of the issues.

Currently, we hoist everything to `node_modules/.pnpm/node_modules` by default. It should be possible to hoist some of the packages to the root node_modules but keep hoisting everything else to the virtual store directory.

A new setting should be introduced: `public-hoist-pattern`. This setting will equal `*` when `shamefully-hoist` is `true`. When not set, this setting will be `@types/*`. So by default, all type dependencies will be hoisted to the root. This will solve most of the issues we currently have with typescript projects.

**Comment by aparajita** [comment]
Brilliant solution!

**Comment by zkochan** [comment]
:ship: 5.2.0
