### ISSUE TITLE
outdated command is inefficient

### ISSUE THREAD

**Issue by aparajita** [pnpm/pnpm#2632]
### pnpm version:

5.1.8

### Code to reproduce the issue:

```sh
pnpm outdated
```

### Behavior:

I hope for `pnpm outdated` to be as fast as [updates](https://github.com/silverwind/updates). Here's the results for `pnpm outdated` vs `updates` in a project with 94 top level dependencies:

```sh
$ time pnpm outdated
pnpm outdated  2.44s user 0.60s system 30% cpu 9.856 total

$ time updates
updates  1.19s user 0.15s system 74% cpu 1.810 total
```

`updates` is >2x faster. And it uses 6x less bandwidth!

Since `updates` is open source, why not just use their algorithm (with attribution of course)?

### Additional information:

 - `node -v` prints: v14.3.0
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
We have the fastest installation, so our codebase should be able to have the fastest outdated command. There are probably just some inefficiencies that needs to be fixed.

**Comment by aparajita** [comment]
You might as well look at `update`'s code for clues. 😁

**Comment by zkochan** [comment]
Try 5.2.0

**Comment by aparajita** [comment]
Will do. I'll do a new comparison with `updates` on the same repo.

**Comment by zkochan** [comment]
Maybe we can come up with some other improvements but I don't have more ideas at the moment. There is nothing special in the codebase of "updates". They use npm's package for fetching metadata. But they don't read any of the npm configs (we do). And they probably have less code, so the CLI startup is faster.

Our CLI startup is pretty slow. Probably that's the reason.

**Comment by aparajita** [comment]
It isn't worth worrying about. 56% slower is way better than 200% slower.
