### ISSUE TITLE
ERROR: This version of pnpm requires at least Node.js v10.13

### ISSUE THREAD

**Issue by sahanatroam** [pnpm/pnpm#2641]
### Code to reproduce the issue:
Use nvm to choose your node version
```bash
nvm use 11
npm install -g pnpm

➜  webapp-starter git:(master) node -v
v11.15.0
➜  webapp-starter git:(master) pnpm -v
ERROR: This version of pnpm requires at least Node.js v10.13
The current version of Node.js is v10.6.0
```

### Expected behavior:
There should be no error printed saying `ERROR: This version of pnpm requires at least Node.js v10.13` as the node version is already set to 11

### Actual behavior:
```bash
➜  webapp-starter git:(master) pnpm -v
ERROR: This version of pnpm requires at least Node.js v10.13
The current version of Node.js is v10.6.0
```
### Additional information:
 - OS X, or Linux?:

**Comment by moghaazi** [comment]
I've the same issue.

![image](https://user-images.githubusercontent.com/49992538/95805032-b5705400-0d04-11eb-847c-8ef7e2b600b2.png)

**Comment by jayanthchinap** [comment]
> 
> 
> ### pnpm version: 5.2
> 
> ### Code to reproduce the issue:
> Use nvm to choose your node version
> ```bash
> nvm use 11
> npm install -g pnpm
> 
> ➜  webapp-starter git:(master) node -v
> v11.15.0
> ➜  webapp-starter git:(master) pnpm -v
> ERROR: This version of pnpm requires at least Node.js v10.13
> The current version of Node.js is v10.6.0
> ```
> 
> 
> ### Expected behavior:
> There should be no error printed saying `ERROR: This version of pnpm requires at least Node.js v10.13` as the node version is already set to 11
> 
> ### Actual behavior:
> ```bash
> ➜  webapp-starter git:(master) pnpm -v
> ERROR: This version of pnpm requires at least Node.js v10.13
> The current version of Node.js is v10.6.0
> ```
> ### Additional information:
>  - OS X, or Linux?:
> 

Hmm

**Comment by prophetw** [comment]
Maybe you should downgrade your pnpm by
```bash
npm i -g pnpm@6
``` 
then use pnpm env to switch

**Comment by zkochan** [comment]
You can install the executable version of pnpm and it won't use node.js

You can do that either by using the standalone script as described [here](https://pnpm.io/installation) or by installing `@pnpm/exe`: `npm i -g @pnpm/exe`
