### ISSUE TITLE
RFC: Package Versioning

### ISSUE THREAD

**Issue by lukeed** [pnpm/pnpm#2643]
It recently dawned on me how good `pnpm` is at supporting monorepos. It's so good, in fact, that the only thing keeping it from replacing tools like `lerna` outright is the fact that – as far as I can tell – it doesn't track workspaces changes.

> PS: I can understand why `pnpm` would _not_ want to do this, but I wanted to verify it's at least been discussed.

Currently, I know I can `pnpm -r publish` in my monorepo, but that goes through and publishes all packages, regardless if they've had any changes since the last version. (I think `npm` registry returns an error if you publish the same version).

Part A of this RFC is that `pnpm -r publish` (by default) on publish packages that are dirty since their last version.

Part B of this RFC is that there may be `pnpm -r version` command (and `pnpm recursive version`) that applies the `patch|minor|major|...` to **all dirty packages** since their last release.

For both parts, I would argue the "if change/dirty only" should be default behavior. A flag can be provided (eg, `--all`) to insist on applying the command to all workspace packages.

---

Following this RFC, here's an example monorepo workflow:

```js
// packages/aaa/package.json
{
  "name": "aaa",
  "version": "0.3.0",
  "dependencies": {
    "bbb": "workspace:*",
    "ccc": "workspace:^0.2.0"
  }
}
```

```sh
# Edit ccc/index.js 
$ echo "console.log('major change');" >> packages/ccc/index.js

# Mark all packages (since last version) as w/ new major
$ pnpm -r version major
#=> ccc@0.2.0 -> ccc@1.0.0
```

```js
// packages/aaa/package.json
-- "ccc": "workspace:^0.2.0"
++ "ccc": "workspace:^1.0.0"

// repeat for all other dependents of "ccc"
```

```sh
# version everything that's changed
$ pnpm -r version patch
#=> aaa@0.3.0 -> aaa@0.3.1
#=> ...other ccc dependents

# publish everything that's changed
$ pnpm -r publish
#=> published: aaa@0.3.1
#=> published: ccc@1.0.0
#=> ...other ccc dependents
```

When comparing this workflow to `lerna`, the only thing "missing" is that `lerna publish <patch|minor|major|...>` is a shortcut for the above steps. However, because of this, `lerna` may publish versions more often than is necessary, and does not allow you to have workspace packages point at older versions of each other.

---

Thanks :)

**Comment by zkochan** [comment]
> Currently, I know I can pnpm -r publish in my monorepo, but that goes through and publishes all packages, regardless if they've had any changes since the last version. (I think npm registry returns an error if you publish the same version).

This doesn't seem correct. `pnpm publish -r` publishes only those packages in the workspace that have not yet published versions. So pnpm actually makes a request to the registry for every package, and it checks whether the registry has the version of the package that is in the repository. If the version is not in the registry yet, it is published. If the version is in the registry, it is skipped.

I am currently using [changesets](https://github.com/atlassian/changesets) for publishing and it works perfectly with pnpm. We can document it somewhere. I don't think we should work on versioning. Versioning can be done by changesets. publish can be done by pnpm. It already works. changesets bump the versions, `pnpm publish -r` publishes them.

**Comment by lukeed** [comment]
Ok, thanks.

TBH that's kinda unfortunate but I definitely understand you're reasoning :)

I might put together a monorepo versioning tool (based on pnpm), because [this is completely unacceptable](https://npm.anvaka.com/#!/view/2d/%2540changesets%2Fcli) to me, especially for something as innocuous as incrementing some `package.json` versions.

**Comment by zkochan** [comment]
But have you tried it? I use it for publishing the pnpm repository and it
works good.

Luke Edwards <notifications@github.com> ezt írta (időpont: 2020. jún. 19.,
P 23:48):

**Comment by lukeed** [comment]
I have - it definitely works and does its job well. 
My point is just that I don't want to install a mountain of dependencies just to do a simple task. L

I'm sure I'm in the minority for this topic but that's ok :wink:

**Comment by zkochan** [comment]
You should really not worry about the mountain of dependencies if you use pnpm 😆
