### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by Username-Cant-Be-Blank** [pnpm/pnpm#2645]
There are no build instructions. the readme just says to install pnpm with npm, the very thing it is supposed to replace.
This makes the project pretty useless.
https://i.imgur.com/9ngEGTn.jpg

**Comment by alexeyten** [comment]
And how do you think you could _build_ it without npm?

**Comment by zkochan** [comment]
There are other options to install pnpm. Even without pnpm: https://pnpm.js.org/en/installation

However, installing pnpm with npm is currently the most reliable way. That is why the readme suggests it as the default. But I am not doing open source for getting rude messages, so I am locking this issue. Feel free to create new issues without sarcasm and rudeness.
