### ISSUE TITLE
`workspace:0.0.0` should match `undefined` version

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#2648]
### pnpm version:
5.2.3

### Code to reproduce the issue:

Have a monorepo where a private package [lacks the `version` field](https://github.com/yarnpkg/berry/blob/d851da6cd913b94f72b6c8b4683e66dcc289db50/package.json) and [is referenced using `workspace:0.0.0`](https://github.com/yarnpkg/berry/blob/d851da6cd913b94f72b6c8b4683e66dcc289db50/packages/yarnpkg-shell/package.json#L16-L19).

### Expected behavior:

The private package is linked successfully, like what **Yarn** does.

### Actual behavior:

```
 ERROR  No matching version found for private-package@0.0.0 inside the workspace
```

### Additional information:

 - `node -v` prints: v14.4.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
That seems like an unusual behavior. Why don't you reference the package through `workspace:*`? it works

**Comment by ExE-Boss** [comment]
Because when using **pnpm** to contribute to a primary **Yarn**‑based project, this is likely to come up even outside [the **Yarn v2** repository](https://github.com/yarnpkg/berry).

- <https://github.com/yarnpkg/berry/blob/d851da6cd913b94f72b6c8b4683e66dcc289db50/package.json>
- <https://github.com/yarnpkg/berry/blob/d851da6cd913b94f72b6c8b4683e66dcc289db50/packages/yarnpkg-shell/package.json#L16-L19>

**Comment by zkochan** [comment]
Is this only about private packages or any packages?
