### ISSUE TITLE
v5.2.4 Regression: Couldn't find a suitable global executables directory.

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#2649]
### pnpm version:
v5.2.4

### Code to reproduce the issue:
Have pnpm bins installed in `D:\Programs\NodeJS\pnpm‑global\`

### Expected behavior:
`pnpm --global` commands work correctly.

### Actual behavior:
```
 ERROR  Couldn't find a suitable global executables directory.
```

Caused by <https://github.com/pnpm/pnpm/pull/2637>, `D:\Programs\NodeJS\pnpm‑global\` doesn’t get treated as a valid global bin directory.

### Additional information:

 - `node -v` prints: v14.4.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
ok, we can probably accept directories that start with `pnpm-`, `pnpm_`, `.pnpm-`, `.pnpm_`.

**Comment by zkochan** [comment]
oh, actually, the issue is different. we check for nodejs in the path. But we don't check for NodeJS.

**Comment by ExE-Boss** [comment]
I think we should add support for something like `global‑bin‑dir`, and also use `global‑dir` as the fallback for where global bins get installed, which is the pre‑**v5.2.4** behaviour.

**Comment by zkochan** [comment]
We probably can have something like `global-bin-dir`. However, the fallback solution is bad because the fallback directory is not always in the PATH and as a result, the commands are not available and users are confused.

**Comment by zkochan** [comment]
:ship: 5.2.5

**Comment by talentlessguy** [comment]
Happens to me as well nd I don't know how to fix that:

```
v1rtl@vultr ~> pnpm -g ls
 ERROR  Couldn't find a suitable global executables directory.
For help, run: pnpm help list
v1rtl@vultr ~ [1]> node -v
v14.4.0
```

**Comment by zkochan** [comment]
Maybe you can play with this lib on  your system: https://github.com/pnpm/pnpm/tree/master/packages/global-bin-dir

to see why it cannot find a suitable global dir

**Comment by talentlessguy** [comment]
> Maybe you can play with this lib on your system: https://github.com/pnpm/pnpm/tree/master/packages/global-bin-dir
> 
> to see why it cannot find a suitable global dir

thanks,  I will try it

**Comment by talentlessguy** [comment]
okkk so I just created the `~/.local/pnpm/bin` folder and it worked

**Comment by Clashsoft** [comment]
On macOS, pnpm v5.2.6, I still have this problem.

**Comment by aparajita** [comment]
Same problem on macOS, pnpm 5.2.6, node v14.4.0.

This is rather catastrophic. Everything stopped working. Downgrading to 5.2.3 fixed it.

**Comment by aparajita** [comment]
Here's you problem:

https://github.com/pnpm/pnpm/blob/c3796a71d5b86aa1a3f7704c781cd7b8b62d2b31/packages/global-bin-dir/src/index.ts#L21-L25

You are assuming that the node binary is within one of those directories **under** a PATH directory. That isn't the case at all on macOS. The node binary is usually directly under one of the PATH directories.

**Comment by aparajita** [comment]
@zkochan Please reopen this, it's still broken.

**Comment by zkochan** [comment]
@aparajita but we are also searching for the directory of the currently running node process: https://github.com/pnpm/pnpm/blob/c3796a71d5b86aa1a3f7704c781cd7b8b62d2b31/packages/global-bin-dir/src/index.ts#L25

Maybe it doesn't work because Node has no write permission to that directory. I can add more info to the error

**Comment by intrnl** [comment]
On Arch Linux, with `5.7.6-zen1-1-zen` kernel version

```
PnpmError: No write access to the found global executable directories
    at pickBestGlobalBinDir (node_modules/@pnpm/global-bin-dir/lib/index.js:36:11)
    at Object.default_1 [as default] (node_modules/@pnpm/global-bin-dir/lib/index.js:13:12)

{
  code: 'ERR_PNPM_GLOBAL_BIN_DIR_PERMISSION',
  hint: 'The found directories:\n/usr/bin'
}
```

PATH env is
<pre><code><b>/home/intrnl/.local/npm-global/bin</b>:<b>/home/intrnl/.local/npm-global/bin</b>:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
</code></pre>

**Comment by Clashsoft** [comment]
This issue is some fundamentally breaking it should have been caught by a CI service. It looks like you are using GitHub actions, but only for Windows? Why not add macOS and Linux test runners?

**Comment by zkochan** [comment]
But we can only test it with unit tests. And there are dozens of different use cases. Different OS, different toolings (nvm, nvs, etc). I know for sure that the changes fixed some issues on Windows, that were present for a really long time

**Comment by zkochan** [comment]
`/home/intrnl/.local/npm-global/bin` this is the standard directory created by NodeJS during installation? We can look for this directory as well.

**Comment by Clashsoft** [comment]
You could integrate any kind of test into the GitHub actions CI, even shell scripts. At least the most common use cases should be aimed for. For me, not even `pnpm i -g pnpm` did not work.

**Comment by intrnl** [comment]
Ah, sorry, didn't specify further, I configured my npm config to use that specific location. I was stuck for several hours earlier wondering why pnpm global had stopped working 😅

**Comment by intrnl** [comment]
Is there any reason as to why pnpm doesn't use the `prefix` option anymore? or am I missing out on something? :sweat_smile:

**Comment by aparajita** [comment]
> but we are also searching for the directory of the currently running node process

That test fails when using node version managers like `fnm`, because `/var/folders/1z/fl90zpnx2v36z32z255pf8z80000gn/T/fnm-shell-1190440/bin` is in my PATH but `process.execPath` returns `/Users/aparajita/.fnm/node-versions/v14.3.0/installation/bin/node`, which is not in my PATH.

**Comment by aparajita** [comment]
What was the intention of that commit? We have to find a better strategy to achieve it.

**Comment by zkochan** [comment]
No, revert is not an option. There were too many issues with the previous version.

We can do the next things:
1. search for npm global prefix in the path as well
2. search for the node, npm, or pnpm executable in every directory that is in the path

**Comment by aparajita** [comment]
In my case #2 would work.

**Comment by aparajita** [comment]
I wasn't suggesting to revert, only to find a different strategy for finding the executable.

Why does the directory have to be writable?

**Comment by zkochan** [comment]
> Why does the directory have to be writable?

Because pnpm should be able to add new files to that directory

**Comment by aparajita** [comment]
To the executable directory? Why? On linux, the standard node distribution has to be installed via sudo in /usr/bin, which is not user writeable.

**Comment by zkochan** [comment]
ok, then it will no be used. That is why we check if pnpm has permission.

**Comment by aparajita** [comment]
In addition to checking if `process.execPath` is in PATH, if you check if node is in `process.execPath`, that would solve the problem for me and all others using a node version manager on macOS.

**Comment by zkochan** [comment]
do you mean checking if node is in one of the folders?

**Comment by aparajita** [comment]
Yes, your goal is to find the bin directory where npm-installed binaries are placed, correct? In my case node itself is in the same directory as all of the npm-installed binaries.

**Comment by zkochan** [comment]
Try pnpm v5.2.7

**Comment by Clashsoft** [comment]
pnpm v5.2.7 (which isn't fully released yet, it seems) prints the following:

```
$ pnpm i -g @angular/cli
 ERROR  Couldn't find a suitable global executables directory.
There should be a node, nodejs, npm, or pnpm directory in the "PATH" environment variable
```

Does that mean I need a directory in my PATH that is literally named any of "node", "nodejs", "npm" or "pnpm"? Why? npm itself puts symlinks in /usr/local/bin because that's where homebrew put a symlink for npm. Why do have to create a folder and edit my path when using pnpm?

**Comment by zkochan** [comment]
ok, seems like we need this change as well: 

* search for the node, npm, or pnpm executable in every directory that is in the path

but in v5.2.7 I did add reading of npm's config for the global bin dir

**Comment by aparajita** [comment]
>  search for the node, npm, or pnpm executable in every directory that is in the path

That kind of is the whole point of PATH... 😁

**Comment by zkochan** [comment]
I accidentally pushed directly to master: https://github.com/pnpm/pnpm/commit/245221baa68c893d1b4a501c3f0867ace5101728

If tests will pass, I'll release it.

**Comment by zkochan** [comment]
:ship: 5.2.8

**Comment by Clashsoft** [comment]
Thanks. My problems seem to be solved. However, the releases v5.2.8 and v5.2.7 are not yet visible in GitHub Releases and on npmjs.com

**Comment by zkochan** [comment]
Well, I wanted a confirmation that it works

**Comment by Clashsoft** [comment]
Wouldn't it be better to make an alpha, beta, pre or rc version then? Anyway, I can confirm it works on macOS homebrew-installed node/npm now.

**Comment by aparajita** [comment]
Works here too, thanks. @Clashsoft it was available via the `@next` tag, that is a common convention for beta releases. `npm view <package>` shows the latest versions available under all tags.

**Comment by kawaemon** [comment]
The same problem occurs on macOS 10.15.6(Catalina).
My Node.JS is installed via homebrew, so `/usr/local/bin/node` is just symlink.

```
% pnpm --version
5.5.13

% pnpm list -g
 ERROR  Couldn't find a suitable global executables directory.
There should be a node, nodejs, npm, or pnpm directory in the "PATH" environment variable

% which node
/usr/local/bin/node

$ echo $PATH | tr ":" "\n" | grep "/usr/local/bin"
/usr/local/bin

% ls -l /usr/local/bin | grep node
lrwxr-xr-x  1 kawak  admin    30 Sep  8 00:47 node -> ../Cellar/node/14.9.0/bin/node
lrwxr-xr-x  1 kawak  admin    46 Sep  8 00:47 npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x  1 kawak  admin    46 Sep  8 00:47 npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
lrwxr-xr-x  1 kawak  admin    36 Sep 13 15:34 pnpm -> ../lib/node_modules/pnpm/bin/pnpm.js
lrwxr-xr-x  1 kawak  admin    36 Sep 13 15:34 pnpx -> ../lib/node_modules/pnpm/bin/pnpx.js
```

**Comment by samkcarlile** [comment]
I'm getting the same issue with 5.5.10 on macOS Catalina 10.15.6 :(. I thought it was because pnpm didn't have write access to my prefix in `~/.npmrc`, but after changing the prefix to `~/.pnpm-global` I get the same error here.

**Comment by secretlifeof** [comment]
I'm also having the same issue with macOS Catalina 10.15.6. Also installed Node.JS using homebrew.
pnpm --version : 5.7.0

**Comment by zkochan** [comment]
It seems to work on Windows (which this issue is about). Please track #2885

**Comment by rulatir** [comment]
How do I just do away with the whole complicated logic and **imperatively decree** where I want my binaries to be installed?

**Comment by zkochan** [comment]
set the `global-dir` setting.

**Comment by zkochan** [comment]
no, actually the only way at the moment is to use the `--dir` CLI option. 

For instance: `pnpm install --global --dir=/home/foo`

Related code:

https://github.com/pnpm/pnpm/blob/main/packages/config/src/index.ts#L249-L255

**Comment by woss** [comment]
can we reopen this? 

i'm still getting the ` ERROR  No write access to the found global executable directories` when running `curl -f https://get.pnpm.io/v6.js | node - add --global pnpm `  in wsl2 node 14. 

maybe this helps

```
❯ ll /usr/bin/node*
-rwxr-xr-x 1 root root 73873984 Feb 23 02:00 /usr/bin/node
lrwxrwxrwx 1 root root       24 Sep 25  2020 /usr/bin/nodejs -> /etc/alternatives/nodejs
```

**Comment by zkochan** [comment]
This issue was about a regression on Windows, which was fixed.

**Comment by woss** [comment]
@zkochan thanks for the answer and sorry for the posting on the wrong place, here, new bug report of the mentioned issue https://github.com/pnpm/pnpm/issues/3319
:)
