### ISSUE TITLE
pnpm update unexpected behaviour on exact versions

### ISSUE THREAD

**Issue by Pytal** [pnpm/pnpm#2658]
### Code to reproduce the issue:
``` bash
pnpm add -E express@4.17.0
pnpm update
```

### Expected behavior:
`package.json` should keep the dependency at the exact version you installed it as
``` json
"express": "4.17.0"
```

### Actual behavior:
a caret `^` is prepended to the version in `package.json` after `pnpm update`
``` json
"express": "^4.17.0"
```

a subsequent `pnpm update` will then result in updating the package to the latest version rather than keeping the exact version specified

**Comment by zkochan** [comment]
I couldn't reproduce this issue with the provided steps

**Comment by Pytal** [comment]
Hey @zkochan, I've solved my issue!  I didn't initially install the dependency with the `-E` flag and instead manually edited my `package.json` to remove the caret `^` to make it exact.

**Comment by Pytal** [comment]
Hey @zkochan, this issue seems to only affect `devDependencies`. I got it to work with a: `pnpm add -DE <package>` instead.
