### ISSUE TITLE
Add ability to provide custom UserAgent

### ISSUE THREAD

**Issue by DavyJohnes** [pnpm/pnpm#2664]
### Code to reproduce the issue:

`pnpm install`

### Expected behavior:
I am able to provide either env variable or CLI options to override UserAgent which pnpm will use to make queries to npm registry.

### Actual behavior:
I am not able to override UserAgent which pnpm uses to make queries to npm registry.

### Additional information:

 - `node -v` prints: v12.14.1
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
Do you mean you set a different user agent through settings?

Like `user-agent=something` in a `.npmrc` file?

**Comment by DavyJohnes** [comment]
> Do you mean you set a different user agent through settings?
> 
> Like `user-agent=something` in a `.npmrc` file?

Exactly. Or, like this is done in npm, `npm_config_user_agent` env variable.

**Comment by zkochan** [comment]
I cannot reproduce it. When I set a custom user-agent, pnpm puts it to the user-agent header of the requests.

**Comment by DavyJohnes** [comment]
> I cannot reproduce it. When I set a custom user-agent, pnpm puts it to the user-agent header of the requests.

I'll try to use `user-agent=something in a .npmrc file`, however, it would be nice to be able to set this option globally. In my case (monorepo with 100+ packages) it is not convenient to edit each .npmrc.

**Comment by zkochan** [comment]
you can set the config globally. `npm config set user-agent bla`

but the env variable should also work. Have you tried it?
