### ISSUE TITLE
Consider adding support for Yarn v2’s `patch:` protocol

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#2675]
### pnpm version:
**v5.3.0**

### Additional information:
- <https://yarnpkg.com/features/protocols#table>

**Comment by zkochan** [comment]
I think I can implement patching in Yarn but implementing it with the patch protocol would be nearly impossible. I can implement it like this: https://github.com/pnpm/pnpm/pull/4885#issuecomment-1158366048
