### ISSUE TITLE
Issue passing params

### ISSUE THREAD

**Issue by jmlag** [pnpm/pnpm#2685]
### pnpm version: 
5.3.0

### Code to reproduce the issue: 
`pnpm --vs2015 i -g windows-build-tools`

### Expected behavior: 
Install the package

### Actual behavior: 
```
ERROR  Unknown option: 'vs2015'
For help, run: pnpm help add
```

### Additional information:

 - `node -v` prints: v14.5.1/v12.16.3/v10.19.0
 - Windows, OS X, or Linux?: Windows 10/Ubuntu

I've looked at past issues but they don't seem to solve this problem. I get the error whether I use PowerShell, Command Prompt, Bash from Git for Windows, or Ubuntu (yes, I realize I won't need windows-build-tools on Linux).

**Comment by zkochan** [comment]
You want to pass `--vs2015` as an option to lifecycle scripts?

**Comment by jmlag** [comment]
What do you mean by lifecycle script? It's just installing a package globally.

**Comment by zkochan** [comment]
You can use an env variable to make it work:

```
npm_config_vs2015=true pnpm i -g windows-build-tools
```

**Comment by zkochan** [comment]
in v5.0.0-0 you may use `pnpm --config.vs2015 i -g windows-build-tools`
