### ISSUE TITLE
Recursive publish adds an extra `pnpm-temp` dist-tag to the package

### ISSUE THREAD

**Issue by ifiokjr** [pnpm/pnpm#2686]
### Code to reproduce the issue:

When publishing packages, recursively with a custom tag, in a mono-repo.

```bash
pnpm publish -r --tag next
```

![image](https://user-images.githubusercontent.com/1160934/87238512-17b27380-c3fb-11ea-8175-845428c0f6b5.png)

Publish succeeds but we're left with an extra tag on the NPM registry

### Expected behavior:

Only the `next` tag should be published.

### Actual behavior:

An extra `pnpm-temp` tag is also created for the published version.

### Additional information:

 - `node -v` prints: v14.4.0
 - Windows, OS X, or Linux?: OSX and Linux (`ubuntu-latest` on GitHub actions)

**Comment by zkochan** [comment]
The idea behind this temporary dist tag was to first publish the packages with a temp tag. If all packages are successfully published, we put the final tags.

I guess we may safely publish to the final tag avoiding this pnpm-temp altogether. Issues may happen only if there are cyclic dependencies in the monorepo and the publish process fails halfway. But that is probably a very rare scenario

**Comment by zkochan** [comment]
:ship: 5.5.2
