### ISSUE TITLE
Hoist eslint plugins

### ISSUE THREAD

**Issue by Djaler** [pnpm/pnpm#2688]
What about changing default hoisting pattern for eslint plugins to `*eslint-plugin*`? This will cover, for example, `@typescript-eslint/eslint-plugin`

**Comment by zkochan** [comment]
Those have issues too?

**Comment by Djaler** [comment]
yep. Also, can user somehow append settings to `public-hoist-pattern`, not override it?

**Comment by zkochan** [comment]
There is no way to append at the moment.

**Comment by Djaler** [comment]
Thanks
