### ISSUE TITLE
vscode-eslint needs to read a global setting

### ISSUE THREAD

**Issue by brunoparga** [pnpm/pnpm#2700]
### pnpm version:
5.4.0

### Code to reproduce the issue:
Versions:
Ubuntu 20.04
node v14.6.0
VSCodium v1.47.2
vscode-eslint v2.1.5

I don't know how to pinpoint the exact location of the extension code that causes the issue.

### Expected behavior:
pnpm interacts just fine with vscode-eslint and the linter works

### Actual behavior: 
Whenever the extension tries to do its job, I get this error on the 'Output' tab of VSCodium:
```
UnhandledPromiseRejectionWarning: Error: Command failed: pnpm root -g
 ERROR  No write access to the found global executable directories

    at checkExecSyncError (child_process.js:634:11)
    at Object.execSync (child_process.js:670:15)
    at Object.execSync (electron/js2c/asar.js:696:23)
    at Object.get (/home/bruno/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.1.5/server/out/eslintServer.js:1:33524)
(...)
```

### Additional information:
I was directed to create an issue from Gitter.

I created [an issue](https://github.com/microsoft/vscode-eslint/issues/1018) on the extension repo; the author says:

> Yes, that problem is that I need to know where global package are installed. The interesting thing is that I only need to read a setting not to write to a global location. Has anyone a idea how to solve this. I am not a pnpm expert.

Zoltan, Dirk, please let me know if I'd need to provide any more information about the issue. Thank you both very much!

**Comment by zkochan** [comment]
maybe for this particular command we can return a result even if pnpm doesn't have access to the directory.

**Comment by zkochan** [comment]
this is not fixed yet. Seems like I've made a mistake.

**Comment by zkochan** [comment]
:ship: 5.4.6

**Comment by brunoparga** [comment]
Excellent, this does work. Thank you so much, Zoltan! I appreciate your attention dealing with this issue.

**Comment by zkochan** [comment]
Great!
you're welcome
