### ISSUE TITLE
Support --json for pnpm outdated

### ISSUE THREAD

**Issue by esatterwhite** [pnpm/pnpm#2705]
npm supports json output for the `outdated command, pnpm should also support this kind of output

```javascript
  "sinon": {
    "current": "8.0.0",
    "wanted": "9.0.2",
    "latest": "9.0.2",
    "location": "node_modules/sinon"
  }
```
### Code to reproduce the issue:

```bash
npm outdated --json
```

### Actual behavior:
Error is thrown
```
 ERROR  Unknown option: 'json'
```

**Comment by kaiyoma** [comment]
This would be very useful for dependency upgrade automation.
