### ISSUE TITLE
pnpm import yarn.lock

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#2707]
### Code to reproduce the issue:

> pnpm import yarn.lock

### Expected behavior:

Be able to migrate from yarn to pnpm

### Actual behavior:

>  ERROR  No package-lock.json or npm-shrinkwrap.json found

related https://github.com/pnpm/pnpm/issues/134, happy to see this feature lands to easier to migrate from yarn to pnpm!

**Comment by SukkaW** [comment]
FYI: `yarn.lock` documentation: https://classic.yarnpkg.com/en/docs/yarn-lock#search

**Comment by SukkaW** [comment]
Yarn has published an official `yarn.lock` parser, but I am not sure whether it should be imported as a dependency for `@pnpm/plugin-commands-import`.
