### ISSUE TITLE
Doesn't react to changes in package.json in workspace

### ISSUE THREAD

**Issue by whitecolor** [pnpm/pnpm#2708]
### Expected behavior:

I manually update package.json (remove or add dep) in one of inner workspace packages, expect that `pnpm install` would react to this change (as `yarn` does), but I see no reaction.

### Actual behavior:

pnpm only checks lock file state.

 - `node -v` prints: 14.5.0
 - Windows, OS X, or Linux?:  linux

**Comment by zkochan** [comment]
I am not sure what you mean. pnpm compares the content of package.json to the records in the lockfile. So if a package.json is modified, pnpm will update the lockfile.

**Comment by whitecolor** [comment]
Does it check all inner workspaces with `package.json`? I remove package from package.json, then do `pnpm install` (in the root of the project, or tried in the workspace dir). But symlink to this package still in workspace's node_moidules. If I remove package with `pnpm remove` symlink is removed.

**Comment by whitecolor** [comment]
Well I just changed package.json in root of the project then I do `pnpm install` I what I got:
![image](https://user-images.githubusercontent.com/736697/88413577-d9528680-cdf4-11ea-9a77-3b084e55d7cd.png)

pnpm does nothing with lockfile.

**Comment by whitecolor** [comment]
Hm, probalby some bugs in my setup, not sure why it didn't work. Everything seem to work now, sorry for disturbing.
