### ISSUE TITLE
`pnpm i -P --frozen-lockfile` throws error, if dependencies depend on devDependencies

### ISSUE THREAD

**Issue by patarapolw** [pnpm/pnpm#2711]
### Code to reproduce the issue:

`package.json`

```json
{
  "dependencies": {
    "@typegoose/typegoose": "^7.0.0"
  },
  "devDependencies": {
    "@types/mongoose": "^5.7.12"
  }
}
```

`pnpm-lock.yaml` exists, from previous `pnpm i`.

### Quick solution:

`pnpm list`, and fix the dependencies inside devDependencies group. You will notice that `@types/mongoose` is white, instead of yellow.

### Expected behavior:

`@typegoose/typegoose` is installed somehow. (I don't require `@types/*` to run `node dist/index.js`)

### Actual behavior:

It crashes. Nothing is installed.

### Additional information:

 - `node -v` prints: v12.16.3
 - Windows, OS X, or Linux?: Docker (node:12-alpine) inside macOS

**Comment by zkochan** [comment]
Related or same as https://github.com/pnpm/pnpm/issues/2411

This happens because `@types/mongoose` is a peer dependency of a prod dependency.
