### ISSUE TITLE
Question: location of  .pnpm-store in project dir

### ISSUE THREAD

**Issue by whitecolor** [pnpm/pnpm#2719]
Appologise for asking the question, but could not get from docs/issues:

In my project on windows I see folder `D:/code/my-project/.pnpm-store` and I see this folder in the root of the same drive  `D:/.pnpm-store`

I'm not sure why this store folder is created inside the project dir?

**Comment by whitecolor** [comment]
Ah it is bug of my setup, this folder was created in-container pnpm which used project directory as attached volume.

@zkochan 
So there still the question, in linux container, if I not configure `npm config set store-dir` it uses for storing project dir, is it intended behaviour?

**Comment by zkochan** [comment]
When choosing a location for the global store, pnpm will start with `~/.pnpm-store`. If pnpm cannot create a hard link from your project to that location, then it will try to find the directory with the smallest length to which it can link. It will start from your projects directory. So if your project is at `/1/2/3/project/`, pnpm will try to make a hard link in `/1/2/3/project`. Then in `/1/2/3/`. Then in `/1/2`. Let's say it fails to make one in `/1/2`. In this case the store will be at `/1/2/3/.pnpm-store`.

This code is at: https://github.com/pnpm/store-path
