### ISSUE TITLE
`pnpm audit` ignores the audit level

### ISSUE THREAD

**Issue by ifiokjr** [pnpm/pnpm#2721]
### Code to reproduce the issue:

Run `pnpm audit --audit-level high` in a repository with a `low` severity vulnerability.

### Expected behavior:

The command should not error.

### Actual behavior:

The command results in an error.

[![image](https://user-images.githubusercontent.com/1160934/88698672-410f1700-d0fe-11ea-8d53-3d6bf0a8f588.png)](https://github.com/remirror/remirror/runs/919943139)

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by matiasfs12** [comment]
This is still happening.
