### ISSUE TITLE
workspace `pnpm install` uses npm registry instead of valid local packages when newer version is found

### ISSUE THREAD

**Issue by ifiokjr** [pnpm/pnpm#2725]
### Code to reproduce the issue:

Publish the latest version of your workspace packages. Switch to a new branch without package versions updated and run the command. 

```bash
pnpm install
```

The file `pnpm-lock.yaml` is updated with packages from the registry rather than from the local workspace. 

### Expected behavior:

The workspace should always use workspace packages when the version range is valid.

### Actual behavior:

The workspace prefers the latest version from a remote registry rather than a local semver compliant version when they are different.

### Additional information:

Once I upgrade the versions to the latest in my local workspace, everything works okay again.

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
Just use [workspace ranges](https://pnpm.js.org/en/workspaces#workspace-ranges-workspace) and it will work as you described

**Comment by ifiokjr** [comment]
@zkochan I'll make the change in my codebase soon. I've opened a few issues in third-party repos since they seem to enforce not using the `workspace:` protocol.

**Comment by ifiokjr** [comment]
I think I can close this since there's already a solution via the `workspace:` protocol.
