### ISSUE TITLE
pnpm incompatibile with Angular ivy (ngcc)

### ISSUE THREAD

**Issue by radarsu** [pnpm/pnpm#2730]
Ubuntu 20.04
pnpm version: 5.4.6

### Expected behavior:
`pnpm i` in pnpm workspace should install packages regardless there is angular app with ngcc.

### Actual behavior:
pnpm assumes node_modules contains only directories (quite correctly), but angular compiler generates `__ngcc_entry_points__.json` there which is not directory and pnpm crashes:
```
ERROR  ENOTDIR: not a directory, open '/workspace/app/node_modules/__ngcc_entry_points__.json/package.json'
```

This issue is related to https://github.com/angular/angular/issues/38023
I'm not sure if angular team would like to solve this issue on their side so I decided to open issue here as well.

**Comment by freshtonic** [comment]
This also happens on my project and we've got some ugly build pipeline hacks to work around it. Would be nice if we didn't have to.

**Comment by zkochan** [comment]
Sure, we can fix this on pnpm side

**Comment by freshtonic** [comment]
> Sure, we can fix this on pnpm side

Legend! Thanks 😍
