### ISSUE TITLE
Upgrading PNPM from 4.14.3 to 4.14.4 or 5+ produces a ENOENT error on postinstall

### ISSUE THREAD

**Issue by ghost236** [pnpm/pnpm#2732]
### Code to reproduce the issue:

When upgrading PNPM from 4.14.3 to 4.14.4, I receive a error during `rush install` or `rush update` during the postinstall phase. This error does not occur in 4.14.3 but appears in 4.14.4 and 5+.

### Expected behavior:

PNPM should install the dependencies without error, under 4.14.3.

### Actual behavior:

```
ERROR ENOENT: no such file or directory, chmod '/Users/ghost/projects/my-app
/common/temp/node_modules/.pnpm/npm/detect-libc/1.0.3/node_modules/detect-libc/bin/detect-libc.js'
```

I tested this change by upgrading and downgrading Rush from 5.30.1 (latest) to 5.23.0 and am able to get clean installs under PNPM 4.14.3 but not 4.14.4. The error also occurs in PNPM 5+.

The only change I could find in the release logs that may be pertinent:
* Subdependencies should be resolved after all sibling parent dependencies

Not sure if that is causing the error or not.

### Additional information:

 - `node -v` prints: 10.21.0
 - Windows, OS X, or Linux?: macOS 10.15.1 Catalina

**Edit:** Confirmed the error does not occur in 4.14.3 but starts in 4.14.4 and persists to 5+.

**Comment by zkochan** [comment]
I have experienced this issue the first time.

I was on master, in this repo. I switched to the `renovate/find-up-5.x` branch. When I ran `pnpm i`, the next error happened:

```
 ERROR  ENOENT: no such file or directory, chmod '/home/zoli/src/pnpm/pnpm/packages/make-dedicated-lockfile/node_modules/@pnpm/audit/lib/bin.js'
```

**Comment by zkochan** [comment]
is detect-libc an optional dependency?

Is it in the "skipped" array in `node_modules/.modules.yaml`?

**Comment by eozu** [comment]
I am seeing this bug too. I'll try to find a simple, reproducible example.

**Comment by cantecim** [comment]
hello, @zkochan I have this issue too but with eslint. It's a dev dependency and I'm enforcing production install with -P flag

pnpm@6.2.5
```
node_modules/.pnpm/fsevents@1.2.13/node_modules/fsevents: Running install script, done in 669ms
node_modules/.pnpm/mongodb-memory-server@6.9.6/node_modules/mongodb-memory-server: Running postinstall script, done in 1m 4.4s
node_modules/.pnpm/sharp@0.28.1/node_modules/sharp: Running install script, done in 4.4s
 ERROR  ENOENT: no such file or directory, chmod '/Users/cantecim/Desktop/Projects/venuex-monorepo/node_modules/.pnpm/eslint@7.25.0/node_modules/eslint/bin/eslint.js'
at pnpm/eslint  
```

It is very interesting also in our CI(github actions) getting this with @nestjs/cli

pnpm@6.2.5
```
.../node_modules/@nestjs/core postinstall: Done
.../sharp@0.28.1/node_modules/sharp install: sharp: Downloading lovell/sharp-libvips@v8.10.6 libvips-8.10.6-linuxmusl-x64.tar.br (download)
.../sharp@0.28.1/node_modules/sharp install: Done
 ERROR  ENOENT: no such file or directory, chmod '/app/node_modules/.pnpm/@nestjs+cli@7.6.0/node_modules/@nestjs/cli/bin/nest.js'
at 0/node_modules/   
```

it doesn't generate the debug log file

**Comment by zkochan** [comment]
A temporary fix: https://github.com/pnpm/pnpm/pull/3980

**Comment by zkochan** [comment]
This should work with pnpm 6.21.1

**Comment by mcmxcdev** [comment]
Can be closed imo since there was no feedback from issue creator.
