### ISSUE TITLE
Support custom types of dependencies

### ISSUE THREAD

**Issue by whitecolor** [pnpm/pnpm#2740]
I belive it would be great if pnpm could support custom types of dependencies:

For example in `package.json` it would look like this:

```json
"lintDependencies": {
    "eslint": "^7.6.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-only-warn": "^1.0.2",
    "@typescript-eslint/eslint-plugin": "^3.7.1",
    "@typescript-eslint/parser": "^3.7.1",
    "typescript-eslint-language-service": "^3.0.0"
  },
```

This would make package dependencies more structured and convinient for analysis and maintaince.

It is now somewhat achievable via `readPackage` hook, (to move `lintDependencies` -> `devDependencies`), but it won't work for operations which change `package.json` like update/upgrade, though works for `pnpm install`.

Also pnpm in this case should support adding and saving custom deps as `pnpm add --save-lint`, and in config there should be ablity to point out how those deps should be treated (dev or prod).

**Comment by aparajita** [comment]
Thanks for the suggestion. While it does seem compelling on the surface, unfortunately this is way more complex than it seems. For example, what if the lintDependencies have peer dependencies that are used both by linting and by something else (e.g. typescript)? Where do you put them? Also, can custom dependencies be development and production dependencies? If so, then there has to be a way to mark them as such. As I said, it's way more complex than it seems, and would touch a large surface area of pnpm.

This would also make package.json files used by pnpm incompatible with other package managers and with the whole universe of tools that read package.json files and expect only `dependencies` and `devDependencies`. The effect would be to make pnpm **less** attractive overall, unfortunately.

We have bigger problems with package.json... like the fact that it's json and not json5 (allowing comments), or even better, a js file, which would allow factoring common stuff.

Someday maybe the package.json spec will be extended to allow this kind of thing, and then we will have a compelling reason to consider this.

**Comment by whitecolor** [comment]
> Where do you put them? Also, can custom dependencies be development and production dependencies? If so, then there has to be a way to mark them as such. As I said, it's way more complex than it seems, and would touch a large surface area of pnpm.

As I've said there should be a way to point out how this deps should be treated as `prod` or as `dev`, by default they should be treated as `dev` obviously. But it is not difficult config this thing in `rc` file. This logic is quite simple, nothing to invent.

> This would also make package.json files used by pnpm incompatible with other package managers and with the whole universe of tools that read package.json files and expect only dependencies and devDependencies. The effect would be to make pnpm less attractive overall, unfortunately.

This is the only point, that could make sense, but probably too on the surface. This refers to dev scenarios for some specific cases, most people don't use any tools besides chosen PM. `pnpm` already actually can be easily be made incompatible with other PMs in dev env (using hooks for example). As for other tools like `syncpack` there still PR had to be made to support `pnpm`.

For production (publishing) there should be other way to to ensure `package.json` compatibility if needed. There should be a `hook` that prepares package.json for publishing.

>  The effect would be to make pnpm less attractive overall, unfortunately.

I would say contrary. First, it is a conscious choice of developer whether to use incompatible features or not. And `pnpm` luckily is chosen by more conscious devs in general. But more possibilities and conveniences unlikely to make a tool less attractive compared to its more conservative counterparts.

> We have bigger problems with package.json... like the fact that it's json and not json5 (allowing comments), or even better, a js file, which would allow factoring common stuff.

Hooks could resolve this, really.

So I propose to reconsider this, as I see no serious reason that would block its implementation/usage. The only thing worth considering - that maybe this feature is not really so nice and useful at all. -)

@zkochan

**Comment by zkochan** [comment]
I don't see value in this feature at the moment.

A different feature might be useful. Dependencies that are installed to a different modules directory. For instance, `dependencies` are installed to `node_modules` but `foo.dependencies` are installed to `foo` directory.

**Comment by whitecolor** [comment]
> I don't see value in this feature at the moment.

To me, it just makes dependencies in package.json more structured, readable and convenient for analysis.

> A different feature might be useful. Dependencies that are installed to a different modules directory.

This feature actually could be combined with a proposed one, using config one could point out another directory to install such deps, or not and use the default. Also, some conventions might be introduced, `foo.` with dot would assume `foo` as modules directory.

**Comment by aparajita** [comment]
You're both talking about completely breaking the node ecosystem. I would **strongly** caution against even considering such an idea. It was bad enough begging package maintainers to support pnpm by declaring their direct dependencies before yarn 2 enforced that. But if you start breaking the node ecosystem, it will instantly turn pnpm into niche player and erase all of the progress we've made towards general recognition. Not sure that's what you want.

**Comment by whitecolor** [comment]
> You're both talking about completely breaking the node ecosystem. 
> declaring their direct dependencies before yarn 2 enforced that

And that means that was a step in the right direction. That is moving the ecosystem forward, not breaking.

> it will instantly turn pnpm into niche player and erase all of the progress

Nobody is forced to use additional features that are not supported by other PMs (a fair amount of which already exist in PNPM). And it is not going to introduce some breaking changes for the casual user. So your concern is not really clear.
