### ISSUE TITLE
pnpm asks to update from newer version to older one

### ISSUE THREAD

**Issue by karansapolia** [pnpm/pnpm#2745]
### Screenshot:
<img width="564" alt="Screen Shot 2020-08-02 at 15 27 44" src="https://user-images.githubusercontent.com/10175625/89120821-c61b7700-d4d6-11ea-81a6-64215503081a.png">

### Code to reproduce the issue: 
`pnpm i -g gatsby-cli`
Seems like an edge case. I was installing gatsby-cli just after updating pnpm.

### Expected behavior:
Should install the package and stop.

### Actual behavior:
After installing the package, shows an alert to update from a newer version of pnpm to an older one.
### Additional information:

 - `node -v` prints: v12.8.2
 - Windows, OS X, or Linux?: OS X

**Comment by aparajita** [comment]
Thanks for the report. This seems like a super edge case that probably happened pnpm switched to itself as the recommended way to update. Closing this, if it happens again please let us know.

**Comment by zkochan** [comment]
I think we have an issue about this already. First of all, we'll probably stop using [update-notifier](https://www.npmjs.com/package/update-notifier): #2752
