### ISSUE TITLE
Suddenly some packages are gone from the registry (throw 404 errors)?

### ISSUE THREAD

**Issue by Friksel** [pnpm/pnpm#2753]
### pnpm version:
5.4.12 (and 5.2.9)

### issue

Using pnpm for around a year now without any 404 issues I now suddenly get 404 errors on multiple projects when installing.
Looking at the registry website it seems these packages also throw 'not found' issues there, so these packages seem to be removed, even though they are still available on npm's registry.
After these 404 errors the installation doesn't continue to install the rest.

For example looking for the `svgr/webpack` package by navigating to https://registry.npmjs.org/@svgr%2Fwebpack responds with 
```
{"error":"Not found"}
```

While the package is perfecly available in npm here:
https://www.npmjs.com/package/@svgr/webpack

This is not the only package having this issue. There are more packages throwing 404 errors in the console while installing. This never happened before here.

### Code to reproduce the issue:

``` bash
pnpm install @svgr/webpack
pnpm install ... (more like this)
```
or navigate in browser to for example
`https://registry.npmjs.org/@svgr%2Fwebpack`

### Expected behavior:

Install that works.

### Actual behavior:

See above

### Additional information:

 - `node -v` prints: v12.13.1
 - Windows, OS X, or Linux?: Windows 10

**Comment by andriskaaz** [comment]
There is an npm issue.
https://status.npmjs.org/incidents/cksjqc1w11v5

https://github.com/npm/cli/issues/1626

**Comment by Friksel** [comment]
@andriskaaz  Thanks for the quick response. That makes sense. Great to know that link.

It seems to be 'random' too, as now the url described above suddenly works, but now there is a problem with retreiving another package (` https://registry.npmjs.org/@xtuc%2Flong `).

Guess they are working on it and need to wait a little.

Thanks again!
