### ISSUE TITLE
pnpm 如何实现多个项目共享一个 Virtual store

### ISSUE THREAD

**Issue by vxhly** [pnpm/pnpm#2760]
### Code to reproduce the issue:

我在两个项目中都配置了 .npmrc 文件，例如这样

```
virtual-store-dir=../node_modules/
package-import-method=auto
store-dir=../.pnpm-store
```

想要把两个项目中的依赖先全部安装到指定的目录下

现在有两个项目的 `package.json` 如下

项目一：
``` json
{
  "dependencies": {
    "axios": "^0.18.0"
  }
}
```

项目二
``` json
{
  "dependencies": {
    "axios": "^0.19.0"
  }
}
```

### Expected behavior:

能够顺利的在 virtual-store 中同时安装两个版本的 axios

### Actual behavior:

当我在两个项目中都执行 `pnpm install` 的时候，最新版本的 axios 会替代旧版本的 axios，而导致旧版本在进行创建链接时创建失败

如何进行正确的配置才能同时安装多个项目中的同一个依赖项的不同版本

### Additional information:

 - `node -v` prints: 14.4。0
 - Windows, OS X, or Linux?: all

**Comment by zkochan** [comment]
Use [pnpm workspace](https://pnpm.js.org/en/workspaces) and run `pnpm install` only once. It will install dependencies in all projects.

**Comment by vxhly** [comment]
@zkochan 

How can I use it correctly [pnpm workspace](https://pnpm.js.org/en/workspaces)

**Comment by vxhly** [comment]
@zkochan 

thanks

**Comment by vxhly** [comment]
@zkochan  我运行 `pnpm install` 的时候，某些依赖包不在 `package.json` 中，它不会帮我下载

例如我在 `babel.config.js` 中这样配置
``` javascript
const IS_PROD = ['production', 'prod'].includes(process.env.NODE_ENV)

const plugins = []
if (IS_PROD) {
  plugins.push('transform-remove-console')
}

module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset',
    [
      '@babel/preset-env',
      {
        'useBuiltIns': 'entry',
        'corejs': 3
      }
    ]
  ],
  plugins
}
```

这个 `@babel/preset-env` 这个依赖包不在 `package.json` 中，但是在执行 `npm install` 的时候会自动帮我安装，然而 执行 `pnpm install` 的时候不会自动帮我安装

**Comment by vxhly** [comment]
@zkochan 采用工作区之后，如果我要在某一个子工程里面安装依赖，我该执行哪一个命令

**Comment by vxhly** [comment]
@zkochan 在使用工作区之后，如果我想要在某一个子工程中安装一个依赖项时 ，我应该在工作区中执行什么样的命令方能将依赖项添加到工作区内

**Comment by zkochan** [comment]
To install a dependency in a workspace project, either run `pnpm add foo` in the workspace project's directory, or use filtering. For instance, `pnpm add foo --filter my-project`. https://pnpm.js.org/en/filtering

**Comment by vxhly** [comment]
![image](https://user-images.githubusercontent.com/17906558/89968244-e93be880-dc85-11ea-9fba-724ee5ca8ed7.png)

无论我在工作区的根中执行安装，还是在工作区的项目中执行安装，它都提示以下错误

``` bash
No projects matched the filters in "E:\test-project"
```

我想在工作区中执行某一条命令，就能够为我们的子工程安装它的新的依赖项，但是依赖项是链接到工作区的 virtual-store 下，并不会扩大 子工程的 node_modules 的文件夹大小

**Comment by zkochan** [comment]
Is demo01 the name of the project in `package.json`? If you want to filter by location, use `pnpm add foo --filter ./demo01`

**Comment by vxhly** [comment]
> Is demo01 the name of the project in `package.json`? If you want to filter by location, use `pnpm add foo --filter ./demo01`

好吧，我不知道项目目录名必须和 `package.json` 中的配置一致，如果我采用了不同的名字确实会提示以上错误

**Comment by vxhly** [comment]
@zkochan 
https://github.com/pnpm/pnpm/issues/2760#issuecomment-671671615  
这个有解决方案吗，我需要简化更多的手动操作过程，想让我的项目在自动化构建时能够更加方便，以及在 install 上的耗时不会太大，这也是在降低 node_modules 这一个目录在硬盘上的存储空间

**Comment by vxhly** [comment]
@zkochan 
在工作区根中的`.npmrc`配置 `shamefully-hoist = true` ,并在工作区的根中进行 `pnpm install` 的时候，工作区根下 node_modules 这一个目录确实按照我设置的生成了目录结构，但是在子工程中却不是我要的

**Comment by vxhly** [comment]
@zkochan   `--filter ` 这个选项有没有排除某个工程的，其他工程都执行相同的命令

``` bash
pnpm recursive exec --filter <目录> -- npm shrinkwrap
```

例如上面的命令，我不想让我的所有子工程都去执行 `npm shrinkwrap` 这条命令，只是某些工程，但是这些工程比较多，我又不能一一例举出来，所以我想采用排除的方式，排除掉我不想执行的工程目录，这个可以做到吗

**Comment by Inori-Lover** [comment]
@vxhly 我猜你想要的效果是 shamefully-hoist

**Comment by BlackHole1** [comment]
You must run `pnpm add @babel/preset-env -D`
see: https://github.com/callstack/linaria/issues/700

@zkochan If there are future cases where the issues are in Chinese, you can cc to me and I will do the answering.
