### ISSUE TITLE
when recursive publish fails pnpm don't update package tag

### ISSUE THREAD

**Issue by VitorLuizC** [pnpm/pnpm#2762]
### pnpm version:

5.4.9

### Code to reproduce the issue:

- You need to have multiple packages.
- Bump some packages versions.
- Make sure one of the packages won't publish.
  - Use an already taked package name or remove permissions for one of the packages.
- Execute `pnpm publish -r`.

### Expected behavior:

Publish packages with `latest` tag or check if current version was published as `pnpm-temp` and set it as `latest`.

### Actual behavior:

Packages published before failure use published version as `pnpm-temp` instead of `latest`.

### Additional information:

 - `node -v` prints: 14.7.0
 - Windows, OS X, or Linux?: Ubuntu 20.04 (Windows 10 WSL)

**Comment by zkochan** [comment]
We will remove that temporary tag. See #2686
