### ISSUE TITLE
pnpm audit seems different than npm audit

### ISSUE THREAD

**Issue by soundstep** [pnpm/pnpm#2763]
### pnpm version:
5.4.12

### Expected behavior:
Find the same security vulnerability than npm does

### Actual behavior:
Finding none compared to npm

I seem that pnpm does not quite report the same vulnerabilities than npm.

<img width="703" alt="Screen Shot 2020-08-10 at 9 25 03 AM" src="https://user-images.githubusercontent.com/133293/89764110-be1d9180-daeb-11ea-9e12-7d5081586799.png">

It could be than the audit level is set to high and does not respect the command argument?

I was just testing the newly adding registry argument.

Command ran with npm:
```
npm install --ignore-scripts --package-lock-only && npm audit --production  --registry=https://registry.npmjs.org
```

Commands ran with pnpm:
```
pnpm audit --registry=https://registry.npmjs.org -D --audit-level=low
pnpm audit --registry=https://registry.npmjs.org -P --audit-level=low
```

**Comment by zkochan** [comment]
Checked. `--audit-level` is respected.

Maybe pnpm installed not the set of dependencies, as npm. Try to find the packages listed by npm in `pnpm-lock.yaml`.

**Comment by soundstep** [comment]
Il will try make a clean demo of it, but I'm off for a week. I hope the
ticket will stay open. This is the last thing I need to sort out to only
use pnpm.

Thanks for looking into it.

**Comment by soundstep** [comment]
I tried to create an example but found out that the issue is with npm install.
I think this issue can probably be closed.

If you are curious, here is what I tried.

The setup:

```
mkdir pnpm-test-audit
cd pnpm-test-audit
npm init -y
npm install --save yargs-parser@5.0.0
```

This should have one output with a moderate vulnerability.

An npm install yields:

**Comment by zkochan** [comment]
Thanks for looking into it.
