### ISSUE TITLE
pnpm script run and passing arguments

### ISSUE THREAD

**Issue by wclr** [pnpm/pnpm#2764]
```
pnpm my-script --script-flag
```

### Expected behavior:

Run my-script and add to running cmd `--script-flag` argument

This is behavior is straightforward and `yarn` behaves this way.

### Actual behavior:

```
ERROR  Unknown option: 'script-flag'
For help, run: pnpm help run
```

Currently need to add `--`
```
pnpm my-script -- --script-flag
```
Not sure if this is really intentional. Probably even if `pnpm`  may run scripts with pnpm's flags (are there any flags for this purpose?) it is still probably better to handle it that way:

```
pnpm --pnpm-flag my-script --script-flag
```

**Comment by mcmxcdev** [comment]
The behavior for args forwarding was actually changed in https://github.com/pnpm/pnpm/releases/tag/v7.0.0 release to omit the additional `--` and now works as you want it to.
