### ISSUE TITLE
Dependencies are incorrectly stored in the workspace's root node_modules and reported as "not saved"

### ISSUE THREAD

**Issue by FlorianDold** [pnpm/pnpm#2768]
### pnpm version:
```
$ pnpm -v
5.5.1
```

### Code to reproduce the issue:

Create a simple monorepo with only one package:

- ``package.json``:

```
{
  "private": true
}
```

- ``pnpm-workspace.yaml``

```
packages:
  - 'packages/*'
```

- ``packages/mypkg/package.json``:

```
{
  "name": "mypkg",
  "version": "0.0.1",
  "dependencies": {
    "@types/react": "^16.9.46",
    "react": "^16.13.1",
    "rimraf": "^3.0.2"
  }
}
```

Run
```
pnpm install
pnpm ls
```

### Expected behavior:

Dependencies for the package ``mypkg`` should be installed into ``packages/mypkg/node_modules`` and the workspace root's ``node_modules`` should not contain any packages.

### Actual behavior:

- ``pnpm ls`` claims a dependency as "not saved", even though it is in ``packages/mypkg/package.json``
- ``pnpm ls`` reports an unsaved dependency that has not been directly installed

```
$ pnpm ls
Legend: production dependency, optional only, dev only

/home/dold/pnpm-bug-repro

not saved (you should add these dependencies to package.json if you need them):
@types/prop-types link:node_modules/.pnpm/@types/prop-types@15.7.3/node_modules/@types/prop-types
@types/react link:node_modules/.pnpm/@types/react@16.9.46/node_modules/@types/react               
```

The top-level ``node_modules`` somehow contains dependencies, even though dependencies are only present for ``mypkg``.

```
$ ls ./node_modules
@types

$ ls node_modules/@types/
prop-types  react
```

Interestingly, only the ``@types/react`` dependency is somehow hoisted to the workspace root, whereas the ``rimraf`` dependency is unaffected.

This also happens with other package combinations, but I've tried to produce a minimal example.

### Additional information:

 - `node -v` prints: v14.5.0
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
This is expected. Although, we may update `pnpm list` to show those dependencies as "hoisted" instead of "unsaved".

We need to hoist all the types due to some typescript issues. Hoisted packages in a monorepo are hoisted to the root node_modules of the monorepo.
