### ISSUE TITLE
What is the difference between version suffixes in pnpm-lock.yaml？

### ISSUE THREAD

**Issue by 9aoyang** [pnpm/pnpm#2773]
When I upgrade dependencies，I found following that puzzled me：

It seems version has not been updated, but the suffix has changed：

![hash change](https://user-images.githubusercontent.com/17688032/90210473-a104fd80-de20-11ea-81ae-4d6a9cd85c6c.png)

![hash change to version](https://user-images.githubusercontent.com/17688032/90210696-3ef8c800-de21-11ea-9df8-5d0a87e97cfd.png)

It seems very unstable, and I want to know, what do these suffixes mean, and why do they change？

npmrc
```npmrc
registry = "https://registry.npm.taobao.org"
link-workspace-packages = deep
recursive-install = true
network-concurrency = Infinity
workspace-concurrency = Infinity
```

**Comment by zkochan** [comment]
The suffix is added when the dependency has peer dependencies.

https://pnpm.js.org/en/how-peers-are-resolved
