### ISSUE TITLE
pnpm is hoisting transient @types dependencies

### ISSUE THREAD

**Issue by aleclarson** [pnpm/pnpm#2797]
### pnpm version: `5.4.0`

If this behavior is by design, is there a way to disable it without fixing the upstream dependency?

### Code to reproduce the issue:

```sh
git clone https://github.com/aleclarson/repro -b pnpm-1
cd repro
pnpm i
ls node_modules/@types # should be empty
```

### Expected behavior:

The `node_modules/@types` directory should be empty, since the `package.json` has no dependencies in that scope.

### Actual behavior:

It's not empty, since `vite` has `@types/*` dependencies.

### Additional information:

 - node `12.13.0`
 - macOS `10.14.5`

**Comment by aleclarson** [comment]
As a workaround, I'm using `"types": []` in my `tsconfig.json`.

**Comment by zkochan** [comment]
This is the desired behavior as there are some issues with how typescript resolves dependencies (in some projects).

If you want to turn it off, you may set `shamefully-hoist` to `false` in your `.npmrc`.

**Comment by aleclarson** [comment]
@zkochan That workaround is insufficient, because `@types/node` still exists in `node_modules/.pnpm` and TypeScript is finding it.

**Comment by zkochan** [comment]
You may set `hoist=false` in `.npmrc`
