### ISSUE TITLE
`pnpm publish --no-git-checks` should be documented 

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#2801]
https://pnpm.js.org/en/cli/publish

https://stackoverflow.com/a/62675843/130910

**Comment by zkochan** [comment]
https://pnpm.js.org/en/npmrc#git-checks

**Comment by vjpr** [comment]
Since it only applies to publish might be good to document it there too. I
only found the option via stackoverflow after looking at the publish
command docs.
