### ISSUE TITLE
feature request: skip packages - eg `pnpm test --skip that-package`

### ISSUE THREAD

**Issue by bitliner** [pnpm/pnpm#2804]
Lerna offers the possibility to skip packages when running certain commands.

for example - `lerna run test --skip that-package`

It would be nice to have an analogous functionality in pnpm too.

For example: `pnpm --skip that-package` or `pnpm --filter -that-package`

**Comment by zkochan** [comment]
yes, I think we need something like this. And maybe it can support all the same syntax as `--filter`. So you could do things like `pnpm --skip=foo... test`

cc @pnpm/collaborators

**Comment by jnelson** [comment]
Commenting only to add keywords "exclude" and "except" since "skip" didn't occur to me.

**Comment by zkochan** [comment]
I think `--exclude` would be nice if we had an `--include` flag, not a `--filter` flag.

Alternatively, we may also just use `--filter` and some negation. Like `--filter=!foo` would select everything except foo.

**Comment by jnelson** [comment]
@zkochan I didn't mean to suggest changing the interface, just wanted to add key words to this issue page so others who think like I do will find it more easily. 😅 I'm happy to leave the shape of things to contributors; I'm not opinionated on that point.
