### ISSUE TITLE
pnpm install doesn't refresh lock file

### ISSUE THREAD

**Issue by artemirq** [pnpm/pnpm#2807]
### Code to reproduce the issue: 

(I will update this if I will be able to create minimal reproducible example)

### Expected behavior:

`pnpm install` update lock file and pnpm on CI don't show error

### Actual behavior:

`pnpm install` doesn't update lock file and pnpm on CI show error:

```
Lockfile is up-to-date, resolution step is skipped
 ERROR  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with packages/plugin-webpack-babel/package.json
```

### Additional information:

 - `node -v` prints: v14.8.0
 - Windows, OS X, or Linux?: OS X

### Link to the actual CI output

https://github.com/artemirq/zero-scriptsjs/pull/626/checks?check_run_id=1040346631

### Link to the PR with changes which cause this error

https://github.com/artemirq/zero-scriptsjs/pull/626

**Comment by zkochan** [comment]
Run `pnpm install` and commit the modified `pnpm-lock.yaml`. Then it should pass.

**Comment by artemirq** [comment]
@zkochan I've run the `pnpm install` and `pnpm install -f` many times and nothing new.

<details>
  <summary>pnpm install and git status</summary>

<img width="1680" alt="Снимок экрана 2020-08-28 в 22 57 50" src="https://user-images.githubusercontent.com/17342159/91610587-33a9ae80-e982-11ea-8813-17e0dd3656c6.png">
</details>

<details>
  <summary>pnpm install -f and git status</summary>

![image](https://user-images.githubusercontent.com/17342159/91611084-17f2d800-e983-11ea-9344-97efdecb2d1d.png)
</details>

**Comment by zkochan** [comment]
Interesting, I'll try to look into it this weekend

**Comment by artemirq** [comment]
@zkochan I've created reproducible [repo](https://github.com/artemirq/pnpm-2807) with three PR's and three different cases.

1. In [first one](https://github.com/artemirq/pnpm-2807/pull/1) I make following changes:

```diff
{
  "name": "@some/core",
  "optionalDependencies": {
-   "fork-ts-checker-webpack-plugin": "~5.0.7"
+   "fork-ts-checker-webpack-plugin": ">=5.0.0"
  }
}
```

After this I run `pnpm install`. In this case lock file [is changed](https://github.com/artemirq/pnpm-2807/pull/1/files#diff-4c3931f66cb5c011888ce5114109913f) correctly and `pnpm install` on CI was completed without errors.

2. In [next PR](https://github.com/artemirq/pnpm-2807/pull/2) I make following changes:

```diff
{
  "name": "@some/core",
+ "devDependencies": {
+   "fork-ts-checker-webpack-plugin": "5.1.0"
+ },
  "optionalDependencies": {
    "fork-ts-checker-webpack-plugin": "~5.0.7"
  }
```

Then I run `pnpm install`. In this case lock file wasn't changed. And CI is not failed - what is strange

3. In [next example](https://github.com/artemirq/pnpm-2807/pull/3) I mixed changes from the previous two scenarios:

```diff
{
  "name": "@some/core",
+ "devDependencies": {
+   "fork-ts-checker-webpack-plugin": "5.1.0"
+ },
  "optionalDependencies": {
-   "fork-ts-checker-webpack-plugin": "~5.0.7"
+   "fork-ts-checker-webpack-plugin": ">=5.0.0"
  }
}
```

Again run `pnpm install` and we can see new behavior: lock file [is changed](https://github.com/artemirq/pnpm-2807/pull/3/files#diff-4c3931f66cb5c011888ce5114109913f), but `pnpm install` on the CI shows familiar to us error:
```
Run pnpm i
Scope: all 2 workspace projects
Lockfile is up-to-date, resolution step is skipped
 ERROR  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with packages/core/package.json
##[error]Process completed with exit code 1.
```

@zkochan Let me know if you need something from me else: any logs, other information or my help.

**Comment by zkochan** [comment]
oh, I just realized now that you have the same dependency in both dev and optional dependencies. That's a weird edge case. Why do you need that? Why not enough having it in optional dependencies?

**Comment by artemirq** [comment]
@zkochan Earlier I was thinking that it's pretty different things: `optionalDependency` used to display that this package can be installed by end user or can be not. But `devDependency` needed only for internal using/typings and guarantee that this package doesn't used in final build. Before this situation I doesn't know that pnpm install optional dependencies and seems I can remove this package from `devDependency`

**Comment by lvjiaxuan** [comment]
Oh my goodness, I got same errors after two years?

Maybe i should go to figure it out how to reproduct next..

**Comment by zkochan** [comment]
Anyone having a similar issue, please create a new issue with steps to reproduce.
