### ISSUE TITLE
--stream option changed in v5.5.4

### ISSUE THREAD

**Issue by jason0x43** [pnpm/pnpm#2816]
### pnpm version:

5.5.4

### Code to reproduce the issue:

In a monorepo such as https://github.com/theintern/intern, run a recursive command with streaming enabled, such as `pnpm test` (after running `pnpm build`).

### Expected behavior:

The `--stream` option should output everything from children, or there should be a separate option to allow this behavior.

### Actual behavior:

With v5.5.3, all of the child output is displayed. In 5.5.4 some of the output (a lot for longer outputs) is collapsed.

<details>
<summary>5.5.3</summary>
<pre>
Scope: all 12 workspace projects
packages/cli test$ intern
packages/cli test: ......
packages/cli test: Total coverage
packages/cli test: TOTAL: tested 1 platforms, 6 passed, 0 failed
packages/cli test: -----------|---------|----------|---------|---------|---------------------------
packages/cli test: File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
packages/cli test: -----------|---------|----------|---------|---------|---------------------------
packages/cli test: All files  |   11.83 |     4.73 |    10.2 |    11.9 |
packages/cli test:  src       |       0 |        0 |       0 |       0 |
packages/cli test:   index.ts |       0 |        0 |       0 |       0 | 1-569
packages/cli test:  src/lib   |   29.85 |    10.77 |      20 |    30.3 |
packages/cli test:   util.ts  |   29.85 |    10.77 |      20 |    30.3 | ...68,175,183-196,207-311
packages/cli test: -----------|---------|----------|---------|---------|---------------------------
packages/cli test: Done
packages/common test$ intern
packages/common test: .......................................
packages/common test: Total coverage
packages/common test: TOTAL: tested 1 platforms, 39 passed, 0 failed
packages/common test: -------------|---------|----------|---------|---------|-------------------------
packages/common test: File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
packages/common test: -------------|---------|----------|---------|---------|-------------------------
packages/common test: All files    |    73.6 |    70.47 |   77.92 |   74.07 |
packages/common test:  src         |       0 |      100 |       0 |       0 |
packages/common test:   index.ts   |       0 |      100 |       0 |       0 | 5-15
packages/common test:  src/lib     |   76.67 |    70.47 |   81.08 |   76.27 |
packages/common test:   Evented.ts |     100 |       95 |     100 |     100 | 129
packages/common test:   cancel.ts  |   73.68 |       50 |      75 |   72.22 | 52,58,69-75
packages/common test:   global.ts  |    62.5 |    33.33 |     100 |    62.5 | 4,12-14
packages/common test:   request.ts |   62.96 |    68.57 |   68.75 |   62.96 | ...-251,267,271,288-324
packages/common test:   util.ts    |    87.1 |    71.11 |   86.67 |   86.67 | ...9,90,102,152,157,176
packages/common test: -------------|---------|----------|---------|---------|-------------------------
packages/common test: Done
</pre>
</details>

<details>
<summary>5.5.4</summary>
<pre>
Scope: all 12 workspace projects
packages/cli test$ intern
[2 lines collapsed]
│ TOTAL: tested 1 platforms, 6 passed, 0 failed
│ -----------|---------|----------|---------|---------|---------------------------
│ File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
│ -----------|---------|----------|---------|---------|---------------------------
│ All files  |   11.83 |     4.73 |    10.2 |    11.9 |
│  src       |       0 |        0 |       0 |       0 |
│   index.ts |       0 |        0 |       0 |       0 | 1-569
│  src/lib   |   29.85 |    10.77 |      20 |    30.3 |
│   util.ts  |   29.85 |    10.77 |      20 |    30.3 | ...68,175,183-196,207-311
│ -----------|---------|----------|---------|---------|---------------------------
└─ Done in 4s
packages/common test$ intern
[6 lines collapsed]
│ All files    |    73.6 |    70.47 |   77.92 |   74.07 |
│  src         |       0 |      100 |       0 |       0 |
│   index.ts   |       0 |      100 |       0 |       0 | 5-15
│  src/lib     |   76.67 |    70.47 |   81.08 |   76.27 |
│   Evented.ts |     100 |       95 |     100 |     100 | 129
│   cancel.ts  |   73.68 |       50 |      75 |   72.22 | 52,58,69-75
│   global.ts  |    62.5 |    33.33 |     100 |    62.5 | 4,12-14
│   request.ts |   62.96 |    68.57 |   68.75 |   62.96 | ...-251,267,271,288-324
│   util.ts    |    87.1 |    71.11 |   86.67 |   86.67 | ...9,90,102,152,157,176
│ -------------|---------|----------|---------|---------|-------------------------
└─ Done in 6s
</pre>
</details>

### Additional information:

 - `node -v` prints: `v14.9.0`
 - Windows, OS X, or Linux?: `OS X`

**Comment by zkochan** [comment]
there was a regression in 5.5.4,
in 5.5.5 the output is back to normal.

**Comment by jason0x43** [comment]
Ah, good that's better.

It looks like there's still an issue when filtering is applied. At least, when I run

```
$ pnpm build
```

in my repo, which internally runs `pnpm run --stream -r build`, I get normal streaming output. If I use filtering, however,

```
$ pnpm build --filter '@theintern/cli' --filer '@theintern/common'
```

the output uses the collapsed format. Is there a different syntax I should use when combining streaming and filtering?

**Comment by zkochan** [comment]
You need to use the `--stream` option, so either run it like 

```
$ pnpm build --filter '@theintern/cli' --filter '@theintern/common' --stream
```

or set stream to true in a `.npmrc` file

**Comment by jason0x43** [comment]
Ah, I see.

* `pnpm build` -- runs my top-level "build" script (`pnpm run --stream -r build`) -- this is fine
* `pnpm build --filter whatever` -- runs the "build" script in the filtered project -- this is not what I expected
* `pnpm build -- --filter whatever` -- runs my top level build script, passing it the filter option -- this is fine

**Comment by jason0x43** [comment]
In any case, my original is resolved, so closing this. Thanks!
