### ISSUE TITLE
typescript reference on deep dependency

### ISSUE THREAD

**Issue by farfromrefug** [pnpm/pnpm#2822]
I have a module `@nativescript/types` which has 2 `dependencies` `@nativescript/types-ios` and `@nativescript/types-android`

I cant references `@nativescript/types-ios` or `@nativescript/types-android` from typescript `///<reference path="...">` or `///<reference types="...">` because typescript wont find those plugins as they are not under the root node_modules folder.
Is there a way to solve that without using `shamefully-hoist ` ?

Thanks

**Comment by zkochan** [comment]
You can add this `.npmrc` to the root of the project:

```
public-hoist-pattern[]=@nativescript/types*
```

but the right solution would be probably to install those deps as dependencies of your project. Because if you reference something, it should be in your deps.

**Comment by farfromrefug** [comment]
I see thanks for the quick answer. Now I have 2 solutions!
