### ISSUE TITLE
"Cannot link binary" warning

### ISSUE THREAD

**Issue by Matt-Deacalion** [pnpm/pnpm#2823]
### Code to reproduce the issue:

With the following `package.json`:

```
{
  "name": "moose",
  "version": "1.0.0",
  "dependencies": {
    "jest": "~24.9.0"
  }
}
```
Then: `$ pnpm install`

### Expected behavior:

Install with no errors or warnings.

### Actual behavior:

Installs ok, but with the following warning:

```
 WARN  Cannot link binary 'jest' of 'jest-cli' to '/home/matt/moose/node_modules/.bin': binary of 'jest' is already linked
```

### Additional information:

 - Node: v14.9.0
 - Linux: 5.8.5-arch1-1
 - Does not happen with `$ npm install`

**Comment by zkochan** [comment]
So just converting the warning to an info message would solve this issue?

**Comment by Matt-Deacalion** [comment]
Yes, that would do it.

**Comment by ksnyde** [comment]
I am having this issue in 2021. Not sure what I can do to resolve this. When in a **pnpm** workspace and after a `pnpm install` at the root, I then get this error from `pnpm store status`:

![image](https://user-images.githubusercontent.com/980757/124196194-c1619900-da80-11eb-8dcd-ab5a3b0c9dd7.png)

Running `pnpm install` again at this point results in this error:

![image](https://user-images.githubusercontent.com/980757/124196249-dfc79480-da80-11eb-884c-4c0f28ab5923.png)

**Comment by ksnyde** [comment]
attempted a rebuild but that ended in tears too

![image](https://user-images.githubusercontent.com/980757/124196662-b78c6580-da81-11eb-99f4-5802fa2f4993.png)
