### ISSUE TITLE
[feature request] Provide some indication of progress during pnpm linking

### ISSUE THREAD

**Issue by sachinjoseph** [pnpm/pnpm#2832]
In large package/workspaces, `pnpm install` appears to be frozen during the linking phase. In some of our internal repos, pnpm stops logging once the following output is displayed.

![image](https://user-images.githubusercontent.com/6994498/92315208-6281df00-ef97-11ea-94ee-3fd223e0e5b2.png)

The next output comes only after 3-4 minutes at least. Because there's no visual indication, it's not clear from the ux whether PNPM is hung or if it is still making progress. We should provide some indication of progress during this step.

After about 3-4 minutes, pnpm logs the following: 

![image](https://user-images.githubusercontent.com/6994498/92315272-f8b60500-ef97-11ea-8752-027e3d5baf7b.png)
![image](https://user-images.githubusercontent.com/6994498/92315280-15523d00-ef98-11ea-950f-020801965634.png)

**Comment by zkochan** [comment]
:ship: [5.6.0-0](https://github.com/pnpm/pnpm/releases/tag/v5.6.0-0)
