### ISSUE TITLE
Package duplication in every single project (puppeteer)

### ISSUE THREAD

**Issue by cybairfly** [pnpm/pnpm#2840]
First of all - thank you. `pnpm` is awesome!

I noticed however that it tends to needlessly re-download the whole package and install duplicates of the same in every project in case of `puppeteer`

After comparing the versions, they are identical in multiple places and the executable file bundled with the package (chromium) is exactly the same version as well. Is there any way to avoid this duplication?

Thank you in advance!

**Comment by remorses** [comment]
Do you mean it downloads the chromium instance multiple times? If that’s the case then it should be a issue with the puppeteer postinstall hook not finding previously downloaded chromium

**Comment by cybairfly** [comment]
Thanks for the feedback @remorses yes `pnpm` downloads a new chromium package with the executable every single time. Here are the scripts:
https://github.com/puppeteer/puppeteer/blob/v5.3.1/install.js
https://github.com/puppeteer/puppeteer/blob/v5.3.1/package.json

**Comment by mcmxcdev** [comment]
Doesn't seem to be an issue anymore:

Install `puppeteer` in project X for the first time, which gets downloaded: 
```
$ pnpm i puppeteer    
Packages: +77
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 85, reused 74, downloaded 11, added 77, done
node_modules/.pnpm/puppeteer@19.7.2/node_modules/puppeteer: Running postinstall script, done in 37.3s

dependencies:
+ puppeteer 19.7.2
```

Install `puppeteer` in project Y, which reuses it from the store as expected:
```
$ pnpm i puppeteer
Packages: +78
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/user/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 78, reused 78, downloaded 0, added 78, done

dependencies:
+ puppeteer 19.7.2

Done in 2s
```
