### ISSUE TITLE
[feature request] Run multiple commands in parallel

### ISSUE THREAD

**Issue by Bessonov** [pnpm/pnpm#2846]
I didn't found any feature request or documentation about that. I'm experimenting with [hasura](https://github.com/hasura/graphql-engine/) and I want to run multiple commands in parallel. For example I have following definition:

```
	"scripts": {
		"start": "$_ run --stream --parallel dev",
		"dev": "tsc --build --watch packages/tsconfig.json",
		"console": "$_ run hasura --project hasura console --address 0.0.0.0 --console-port 8081 --no-browser --log-level DEBUG --api-port 8097",
```

With `start` I bootstrap the compiler, but also backend and frontend in other packages. Now, for hasura, I must start the `console`, which is a permanent running process, like other three. It would be nice if pnpm supports the workflow above. I can imagine something like:

```
	"scripts": {
		"start": "$_ run --stream --parallel dev:*",
		"dev:compiler": "tsc --build --watch packages/tsconfig.json",
		"dev:console": "$_ run hasura --project hasura console --address 0.0.0.0 --console-port 8081 --no-browser --log-level DEBUG --api-port 8097",
```

or:

```
		"start": "$_ run --stream --parallel dev,console",
```

**Comment by zkochan** [comment]
I think on Linux you can do something like

```json
"scripts: {
  "start": "$_ run dev:compiler & $_ run dev:console",
  "dev:compiler": "tsc --build --watch packages/tsconfig.json",
  "dev:console": "$_ run hasura --project hasura console --address 0.0.0.0 --console-port 8081 --no-browser --log-level DEBUG --api-port 8097",
}
```

And if we implement #2621, then it will probably work on all platforms

**Comment by Bessonov** [comment]
Hey @zkochan thank you very much for your response. In past I've used [concurrently](https://www.npmjs.com/package/concurrently). It worked, but not very satisfying, because it leads to some problems, at least in my setup. The `--stream --parallel` was a great replacement for that and works without glitches. Therefore I'm looking for pnpm native support to run multiple commands in the same package.json and not only in monorepo modules.

**Comment by zkochan** [comment]
Maybe we can add it. Not sure

I currently use `npm-run-all` for what you described
