### ISSUE TITLE
public-hoist-pattern does not work in workspaced packages

### ISSUE THREAD

**Issue by intrnl** [pnpm/pnpm#2849]
### pnpm version:
5.5.12

### Code to reproduce the issue:
[Example project](https://github.com/intrnl/pnpm-issue-hoist-workspaces)

### Expected behavior:
`public-hoist-pattern` should work in workspace packages

### Actual behavior:
It doesn't, the modules aren't being hoisted.

### Additional information:

 - `node -v` prints: v14.10.1
 - Windows, OS X, or Linux?: Arch Linux 5.8.8-zen1-1-zen

**Comment by zkochan** [comment]
You can add that public-hoist-pattern setting to the `.npmrc` file in the root of the workspace and it'll work.

If you were expecting that `@nodegui/qode` would be hoisted to `pacakges/hello-gui/node_modules` then I should inform that that is not possible. Hoisting is possible only to the node_modules that is in the parent directory of the virtual store directory. The virtual store is at `<workspace root>/node_modules/.pnpm`, so hoisting is possible only to `<workspace root>/node_modules`.

**Comment by intrnl** [comment]
Ah, that's a little unfortunate, should I just close this then?
