### ISSUE TITLE
pnpm not install all dependencies

### ISSUE THREAD

**Issue by zmaoo** [pnpm/pnpm#2860]
### Code to reproduce the issue:
package.json
{
  "dependencies": {
    "@emotion/core": "^10.0.35",
    "axios": "0.19.2",
    "emotion": "10.0.27",
    "normalize.css": "^8.0.1",
    "react": "16.13.1",
    "react-custom-scrollbars": "4.2.1",
    "react-dom": "16.13.1",
    "react-router-dom": "5.2.0",
    "styled-components": "5.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/plugin-syntax-jsx": "^7.10.4",
    "@babel/polyfill": "^7.8.7",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "7.9.4",
    "@craco/craco": "^5.6.4",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@storybook/core": "^6.0.21",
    "babel-loader": "^8.1.0",
    "babel-plugin-emotion": "^10.0.33",
    "babel-plugin-syntax-jsx": "6.18.0",
    "circular-dependency-plugin": "^5.2.0",
    "clean-webpack-plugin": "^3.0.0",
    "connect-history-api-fallback": "1.6.0",
    "copy-webpack-plugin": "^6.0.0",
    "core-js": "3",
    "css-loader": "^3.5.3",
    "eslint": "7.1.0",
    "eslint-plugin-react": "7.20.0",
    "express": "^4.17.1",
    "file-loader": "^6.0.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "happypack": "5.0.1",
    "html-webpack-plugin": "^4.3.0",
    "mini-css-extract-plugin": "^0.9.0",
    "open": "^7.0.4",
    "snazzy": "^8.0.0",
    "style-loader": "^1.2.1",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-hot-middleware": "^2.25.0",
    "webpack-merge": "^4.2.2"
  }
}

### Actual behavior:
pnpm can't install all denpendencies such as webpack. if i use `yarn`, webpack will be installed because it is a dependency of @storybook/core

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:  OS X 10.15.4

**Comment by zkochan** [comment]
Webpack is not in your dependencies, so it won't be installed at `node_modules/webpack`. If you need webpack, you should install it.

This will work the same with Yarn 2, which is strict, like pnpm.

**Comment by zmaoo** [comment]
> Webpack is not in your dependencies, so it won't be installed at `node_modules/webpack`. If you need webpack, you should install it.
> 
> This will work the same with Yarn 2, which is strict, like pnpm.

thx. this will be more clear.
