### ISSUE TITLE
PNPM is not linking matched packages from workspace

### ISSUE THREAD

**Issue by whitecolor** [pnpm/pnpm#2863]
### pnpm version:
5.5.13

version for the package in package.json: "^0.27.11",
package version in WS: "version": "0.27.16",
package version in NPM: 0.27.17

PNPM links version from NPM, not from WS.  If to change WS package version to "0.27.17" it will link WS version.

### Expected behavior:

Link the available package version (that matches) from WS.

In docs it is said: https://pnpm.js.org/en/workspaces#docsNav
By default, pnpm will link packages from the workspace if the available packages match the declared ranges. For instance, foo@1.0.0 is linked into bar if bar has "foo": "^1.0.0" in dependencies. 

### Actual behavior:

Links the latest package version from NPM.

**Comment by zkochan** [comment]
You should use [workspace ranges](https://pnpm.js.org/en/workspaces#workspace-ranges-workspace) and it will work as you expect.

**Comment by whitecolor** [comment]
Yes, but using the workspace protocol will expect to find the package in WS. From docs, it is stated that "By default, pnpm will link packages from the workspace", and only then the statement "Luckily, pnpm supports the workspace:".

**Comment by zkochan** [comment]
> but using the workspace protocol will expect to find the package in WS in any case

not in any case, only if it matches the protocol, otherwise the installation will fail

**Comment by whitecolor** [comment]
I'm not correct about the "exact match" I mentioned.

The situation I observe currently:

If one provides "workspace:" protocol in version then PNPM will look up the WS, and fail if one can not find a matched version.

If not provided "workspace:", just use " "^0.27.11"," it will link from workspace if the version is  "0.27.17" - equals the latest version from NPM. If it less for example " "0.27.16" PNPM grabs and links the latest version from NPM "0.27.17".

**Comment by zkochan** [comment]
This works as expected, I can update the docs to reflect the case with "latest"

**Comment by whitecolor** [comment]
What is the reasoning behind matching in WS only the latest match from NPM?

**Comment by zkochan** [comment]
Because if you will publish your package and someone installs it, the latest dependency will be installed with it, not the one you tested it with.

**Comment by whitecolor** [comment]
@zkochan should it work for all packages or only for workspace

I just have a case with `jest`. `@jest/core` (latest version from NPM in package.json) was in the workspace, I wanted all the packages use this ws version, not from NPM. But `node_modules\.pnpm\@jest\core@26.6.0\node_modules\@jest\core` is from NPM not workspace. Is it expected?

**Comment by zkochan** [comment]
I don't know if it should by default but you can set the `link-workspace-packages=deep` setting to get that behavior.

**Comment by whitecolor** [comment]
Nice, that works.

 So I'll close the issue. I believe the current behavior of installing the latest valid version either from WS or NPM is correct.
