### ISSUE TITLE
pnpm install with `--package-import-method=clone`  fails but 'copy' and 'hardlink' works fine

### ISSUE THREAD

**Issue by hardfist** [pnpm/pnpm#2879]
### pnpm version:
5.5.13

### Code to reproduce the issue:

https://gist.github.com/hardfist/47678583c20cee545b573ea60742393b

### Additional information:

 - `node -v` prints: v12.18.2
 - Windows, OS X, or Linux?: OSX 10.15.6

**Comment by zkochan** [comment]
This is probably a duplicate of #2761
