### ISSUE TITLE
Install failing on chmod of dependency bin file on version >5.5.11

### ISSUE THREAD

**Issue by trevtrich** [pnpm/pnpm#2882]
### pnpm version: >5.5.11

I am currently working in a project that uses [`package-preview`](https://github.com/zkochan/package-preview) which itself always pulls in the latest `pnpm` to install packages as part of package generation. We started seeing test failures immediately upon the release of `v5.5.12`. The failure reports: 

```sh
 ERROR  ENOENT: no such file or directory, chmod 'PROJECT_DIR/node_modules/.pnpm/js-yaml@3.14.0/node_modules/js-yaml/bin/js-yaml.js'
```

`js-yaml` is a direct dev dependency, and is also depended upon by other dependencies in the tree. The `package-preview` tool we use uses `pnpm install --production` [here](https://github.com/zkochan/package-preview/blob/6d4b9fb4b25b2ce3375af7cbe562c3f68fd153b9/src/index.ts#L61-L64). An interesting finding as I was digging into this was that if I manually pin `js-yaml` back to `v3.13.0` the issue also goes away, so I'm quite confused what might be causing it, and am hoping this might spark a thought for you.

The project I'm working in is located [here](https://github.com/trevtrich/github-scaffolder) for reference, and a copy of the `pnpm-debug.log` is in a gist located [here](https://gist.github.com/trevtrich/b14c22000c6d1a06524bb77f5d72b6aa).

### Expected behavior:
This was working (and still works) for versions <5.5.12. No code changes were made, but the install started failing with v5.5.12. I don't think this should be breaking.

### Additional information:

 - `node -v` prints: v10.17.0
 - Windows, OS X, or Linux?: MacOS

**Comment by zkochan** [comment]
For some reason, I cannot reproduce it. I am using WSL on Windows. Tried `pnpm install --prod` and running `pnpx package-preview`

**Comment by zkochan** [comment]
ok, reproduced after checking out the exact commit that failed on CI b3026057e8314f39e3160eea9b503876442175c0

**Comment by trevtrich** [comment]
Awesome, appreciate the quick fix 👍🏼.
