### ISSUE TITLE
5.7.0 : Couldn't find a suitable global executables directory.

### ISSUE THREAD

**Issue by secretlifeof** [pnpm/pnpm#2885]
### pnpm version:
5.7.0

### Code to reproduce the issue:

This is related to #2649 

Thank you for putting the time in to create this library. I was overly excited how fast and easy it is to use. The first issue that I encountered was not being able to use Gatsby.js out of the box due to previously having use yarn (saw that there is an issue trying to fix this). The second was trying to link an existing library using `pnpm link`.

Getting the following error

> Couldn't find a suitable global executables directory.
> There should be a node, nodejs, npm, or pnpm directory in the "PATH" environment variable

```
$ pnpm --version
5.7.0

$ pnpm list -g
 ERROR  Couldn't find a suitable global executables directory.
There should be a node, nodejs, npm, or pnpm directory in the "PATH" environment variable

$ which node
/usr/local/bin/node

$ echo $PATH | tr ":" "\n" | grep "/usr/local/bin"
/usr/local/bin
/usr/local/bin

$ ls -l /usr/local/bin | grep node
lrwxr-xr-x   1 espenfinnesand  admin        30 22 Sep 11:18 node -> ../Cellar/node/14.9.0/bin/node
lrwxr-xr-x   1 espenfinnesand  admin        46  1 Sep 13:06 npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x   1 espenfinnesand  admin        46  1 Sep 13:06 npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
lrwxr-xr-x   1 espenfinnesand  admin        36 21 Sep 10:48 pnpm -> ../lib/node_modules/pnpm/bin/pnpm.js
lrwxr-xr-x   1 espenfinnesand  admin        36 21 Sep 10:48 pnpx -> ../lib/node_modules/pnpm/bin/pnpx.js
```

I notice that I have to /usr/local/bin in my $PATH, but I don't know why. Is that the root of my error?

Node.JS is installed via homebrew.

### Expected behavior:
pnpm link works

### Additional information:

 - `node -v` prints: v14.9.0
 - Windows, OS X, or Linux?: macOS Catalina 10.15.6

**Comment by zkochan** [comment]
try with pnpm 5.8.0, please

**Comment by secretlifeof** [comment]
Thanks a lot 😃 Also for the quick fix. Tested and it works.
