### ISSUE TITLE
pnpm does not work with gatsby.js

### ISSUE THREAD

**Issue by secretlifeof** [pnpm/pnpm#2886]
### pnpm version:
5.7.0

### Code to reproduce the issue:
I am trying to install Gatsby.js using pnpm

1. `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`
2. `cd hello-world`
3. `rm -r node_modules`
4. `pnpm import`
5. `pnpm install`
6. `pnpm develop`

leeds to following error

```
success open and validate gatsby-configs - 0.018s
success load plugins - 0.100s
success onPreInit - 0.030s
success initialize cache - 0.008s
success copy gatsby files - 0.184s
success onPreBootstrap - 0.036s
success createSchemaCustomization - 0.004s
success Checking for changed pages - 0.004s
success source and transform nodes - 0.043s
success building schema - 0.175s
info Total nodes: 18, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.005s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.057s
success update schema - 0.023s
success write out redirect data - 0.002s
success onPostBootstrap - 0.003s
info bootstrap finished - 4.832s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.105s
success write out requires - 0.008s
success run page queries - 0.027s - 2/2 73.98/s

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '@mikaelkristiansson/domready' in '/Users/espenfinnesand/WebDev/TEST_AREA/hello-world/.cache'

If you're trying to use a package make sure that '@mikaelkristiansson/domready' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache/app.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'event-source-polyfill' in '/Users/espenfinnesand/WebDev/TEST_AREA/hello-world/.cache'

If you're trying to use a package make sure that 'event-source-polyfill' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache/polyfill-entry.js
```

also it cannot resolve **gatsby-legacy-polyfills**, **gatsby-link**, **gatsby-react-router-scroll**, **mitt**, **query-string**, **react-error-overlay** and **shallow-compare**.

### Expected behavior:
Gatsby starting without errors

### Actual behavior:
See errors above. I have tried to manually install the packages above using `pnpm add`. This removes the errors but Gatsby build/develop still does not work like expected. With `gatsby develop` the javascript bundle works, but images/thumbnails (tested in other project) aren't present in the public folder. With `gatsby build` the javascript bundle does not work aswell the images. All this was working before using yarn/lerna.

### Additional information:

 - `node -v` prints: v14.9.0
 - Windows, OS X, or Linux?: macOS Catalina

### Versions:
"gatsby": "^2.24.63",
"react": "^16.12.0",
"react-dom": "^16.12.0"

Did anybody manage to install gatsby.js? The packages that gatsby cannot find above (mitt, etc.) are present in pnpm-lock.yaml.

**Comment by zkochan** [comment]
Create an `.npmrc` file in the root of the project with the following content:

```
shamefully-hoist=true
```

Run `pnpm install` and it'll work after that.

**Comment by secretlifeof** [comment]
@zkochan thanks a lot for the quick answer (kudos and wow!).
Reading FAQ would have helped me 🤦‍♂️
