### ISSUE TITLE
pnpm logger fills up narrow terminal windows with a stream of output

### ISSUE THREAD

**Issue by nikoladev** [pnpm/pnpm#2893]
### Code to reproduce the issue:

Make your terminal window narrow. Then add a package to your project, example: `pnpm add classnames`

### Expected behavior:

There is only one line showing the progress and that line gets re-used for updates.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/15011519/94157195-3dd7a380-fe81-11ea-9241-9883a1a54ad8.png">

### Actual behavior:

On narrow terminal windows the output is keeps using new lines. (This gets especially bad when installing multiple packages)

<img width="330" alt="image" src="https://user-images.githubusercontent.com/15011519/94157254-50ea7380-fe81-11ea-8175-c4a2c09e4093.png">

### Additional information:

 - `node -v` prints: v12.18.4
 - Windows, OS X, or Linux?: macOS 10.15.6

**Comment by mcmxcdev** [comment]
Cannot reproduce this by either installing `classnames` or other dependencies which download multiple deps.
