### ISSUE TITLE
The reporter is not working as expected via the `supi.mutateModules` API

### ISSUE THREAD

**Issue by GiladShoham** [pnpm/pnpm#2910]
The reporter is not working as expected via the `supi.mutateModules` API

### pnpm version:
"supi": "0.42.0",

### Code to reproduce the issue:
I wrote a simple reporter for pnpm:
```js
function getReporter(logger: Logger): ReporterFunction {
  return ((logObj) => {
    const num = Math.random()
    logger.console(`------before ${num}-------`)
    logger.console(logObj)
    logger.console(`------after ${num}-------`)
  });
}
```
My `logger.console`, prefixed everything with `console` to make sure it runs via my console function.
here is an example output (partial output)
```
console ------before 0.17845702907905237-------
console { time: 1601802995462,
  hostname: 'gilads-MacBook-Pro-2.local',
  pid: 10714,
  level: 'debug',
  name: 'pnpm:_dependency_resolved',
  resolution: 'registry.npmjs.org/supports-color/7.2.0',
  wanted:
   { dependentId: '/chalk/3.0.0',
     name: 'supports-color',
     rawSpec: '^7.1.0' } }
console ------after 0.17845702907905237-------
console ------before 0.20560865835231956-------
console { time: 1601802995464,
  hostname: 'gilads-MacBook-Pro-2.local',
  pid: 10714,
  level: 'debug',
  name: 'pnpm:progress',
  packageId: 'registry.npmjs.org/supports-color/7.2.0',
  requester:
   '/Users/giladshoham/Library/Caches/Bit/capsules/3d8cee57925083a7dc5d5b188a06771e88a470a9',
  status: 'resolved' }
console ------after 0.20560865835231956-------
console ------before 0.6498964868091517-------
console { time: 1601802995468,
  hostname: 'gilads-MacBook-Pro-2.local',
  pid: 10714,
  level: 'debug',
  name: 'pnpm:progress',
  packageId: 'registry.npmjs.org/supports-color/7.2.0',
  requester:
   '/Users/giladshoham/Library/Caches/Bit/capsules/3d8cee57925083a7dc5d5b188a06771e88a470a9',
  status: 'found_in_store' }
...cee57925083a7dc5d5b188a06771e88a470a9 | Progress: resolved 10, reused 10, downloaded 0, added 0
console ------before 0.1530021086436717-------
console { time: 1601802995594,
  hostname: 'gilads-MacBook-Pro-2.local',
  pid: 10714,
  level: 'debug',
  name: 'pnpm:_dependency_resolved',
  resolution: 'registry.npmjs.org/has-flag/4.0.0',
  wanted:
   { dependentId: '/supports-color/7.2.0',
     name: 'has-flag',
     rawSpec: '^4.0.0' } }
console ------after 0.1530021086436717-------
```

### Expected behavior:
- line `...cee57925083a7dc5d5b188a06771e88a470a9 | Progress: resolved 10, reused 10, downloaded 0, added 0` will be go through my logger function
- when ever there is such line, I still expect to see the after printing.

### Actual behavior:
As you can see places where there is no line like` Progress: resolved 10, reused 10, downloaded 0, added 0`
everything behaves as expected (even there is no message, so I'm not sure how should I use it exactly)
I have `before 0.17845702907905237` and `after 0.17845702907905237`
but in the example of `before 0.6498964868091517` in the middle I have .`..cee57925083a7dc5d5b188a06771e88a470a9 | Progress: resolved 10, reused 10, downloaded 0, added 0`
And there is no after printed. Also, the progress line didn't pass through my own logger (there is no `console` prefix which I added in my logger.console function)

### Additional information:

 - `node -v` prints: 10.22.0
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
That progress part is not logged. It is printed by [pnpm's reporter](https://github.com/pnpm/pnpm/tree/master/packages/default-reporter). If you don't want that to be printed, just don't use pnpm's reporter.

**Comment by GiladShoham** [comment]
How do I override the pnpm reporter when using `mutateModules` and `createStoreController`

**Comment by zkochan** [comment]
Do you run store controller in the same process with pnpm? If so, pnpm will automatically read all the logs and print that output.

The only place where the reporter is initialized is here: https://github.com/pnpm/pnpm/blob/master/packages/pnpm/src/reporter/index.ts#L17

**Comment by GiladShoham** [comment]
I'm not running pnpm at all, just the store controller and mutateModules (directly).
This is my function - https://github.com/teambit/bit/blob/master/extensions/pnpm/lynx.ts#L144

**Comment by zkochan** [comment]
Well, you initialized the default reporter: https://github.com/teambit/bit/blob/a4f75d8a420197dab30bb866d99ed69d55bf2211/extensions/pnpm/lynx.ts#L132

so it prints its output.

**Comment by GiladShoham** [comment]
it's just some old code for trials.. it's not in used anywhere.
I don't know where to use it.

**Comment by zkochan** [comment]
I believe we sorted this out in chat, defaultReporter was initialized and that was the issue as I mentioned above.
