### ISSUE TITLE
pnpm installs the latest version even if it is marked deprecated

### ISSUE THREAD

**Issue by anantoghosh** [pnpm/pnpm#2912]
### pnpm version:
5.8.0
Windows 10
Powershell core
Node v12

### Code to reproduce the issue:
The latest sass release, for example, made a release 1.26.12 then marked it as deprecated.
```
PS C:\Work\package> pnpm add -D sass
 WARN  deprecated sass@1.26.12: JS API regression
../..                                    |  +15 ++
../..                                    | Progress: resolved 16, reused 16, downloaded 0, added 1, done

devDependencies:
+ sass 1.26.12 deprecated
```
 Another package with similar issue https://www.npmjs.com/package/amazon-connect-chatjs
### Expected behavior:
pnpm installs the latest non deprecated version
### Actual behavior:
pnpm installs the latest version even if it is deprecated

**Comment by Zerowalker** [comment]
got this as well, but don't understand why it's deprecated.
if the latest version is deprecated, doesn't that mean anything before that is also deprecated?

**Comment by statianzo** [comment]
npm and yarn (classic) have the same behavior

```
[deptest]$ npm i -D sass
npm WARN deprecated sass@1.26.12: JS API regression
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN deptest@1.0.0 No description
npm WARN deptest@1.0.0 No repository field.

+ sass@1.26.12
added 16 packages from 22 contributors and audited 16 packages in 2.19s
```

```
[deptest]$ yarn add --dev sass
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
warning sass@1.26.12: JS API regression
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 16 new dependencies.
```

> if the latest version is deprecated, doesn't that mean anything before that is also deprecated?

[Deprecations can have version ranges](https://docs.npmjs.com/cli/deprecate), so not necessarily.

**Comment by anantoghosh** [comment]
This is indeed the behavior or npm, yarn 1/2. As I think more about it, the current method seems like it should be the required behavior even though it may be inconvenient sometimes.
