### ISSUE TITLE
pnpm does not include dependencies of dependents when filtering

### ISSUE THREAD

**Issue by devin-fee-ah** [pnpm/pnpm#2917]
### pnpm version:
5.8.0

### Code to reproduce the issue:
have three packages:
- `@mono/a`
- `@mono/b`
- `@mono/c` (depends on `@mono/a`)

Now (assuming you have `jq` installed), try running:
```
pnpm exec --filter ...@mono/b... -- cat package.json | jq '.name'
```

### Expected behavior:
You'd expect to see:
```
@mono/a
@mono/b
@mono/c
```

### Actual behavior:
But you actually see:
```
@mono/b
@mono/c
```

This means, for instance, if you're doing a filtered install, and want to do a filtered build (TypeScript), you'll likely end up in a situation where a dependent package can't be built – because it wasn't "installed" (specifically, `@mono/a` in that case wouldn't have a `node_modules` folder).

### Additional information:

 - `node -v` prints: 12.18.4
 - Windows, OS X, or Linux?: MacOS / Linux

**Comment by devin-fee-ah** [comment]
I can actually see this going both ways as I think more about the problem. Perhaps there's someway additional syntactic sugar that could be used to differentiate these two cases? i.e.:

```
--filter ...<obj> # filters `obj` and things that depend on `obj`
--filter +++<obj> # filters `obj`, things that depend on `obj`, and their dependencies (recursively)

--filter <obj>... # filters `obj` and things that `obj` depends on
--filter <obj>+++ # filters `obj`, and things that `obj` depends on, and their dependents (recursively)
```

or maybe enable a special behavior for `--recursive`?

Maybe I'm reaching to far here. I'm not sure. I just know that it would be nice, when an intermediate package changes, to be able to go and make sure that all upstream packages still compile and lint fine. The alternative is:
- install everything
- make sure that `references` in all of the `tsconfig` files are kept up to date.

**Comment by devin-fee-ah** [comment]
Alternatively, I think that maybe `--filter ...<foo>...` implies the dependencies of dependents vs. `--filter ...<foo> --filter <foo>...` (broken in two).

**Comment by dfee** [comment]
@zkochan if there's anything i can do to help out with a PR, let me know. I couldn't really find which package parses and provides the DSL for filtering, so a pointer to the package would be nice.

Also, figuring out _what the DSL protocol looks like_ for filtering dependents and there dependencies would be important prior to hacking.

**Comment by zkochan** [comment]
It is a pretty complex issue...

I think it might make sense for `pnpm run --filter=...foo build` to work as you described by default.

But the other commands should work as they work now.

Can we somehow describe in package.json, that a given build command depends from another build command?

**Comment by dfee** [comment]
While it makes sense for `pnpm run --filter=...foo build` to use that behavior, it doesn't make sense for `pnpm run --filter=...foo test` to follow that behavior (we'd be testing beyond our change set). My recommendation was for `pnpm run --filter ...foo... <cmd>`, which I think _specifically_ can claim that it should target deps, too.

I don't know how you'd describe that a script in a `package.json` requires dependencies to be executed, too... – are you thinking custom fields? My current approach is to just use `tsconfig.json`'s `references`. Those have a nasty habit of not staying up-to-date, though.

**Comment by zkochan** [comment]
Yes, I was thinking about custom fields

cc @pnpm/collaborators

**Comment by zkochan** [comment]
also, why tsconfig references don't work for you? I use them in pnpm and they seem to work flawlessly.

**Comment by dfee** [comment]
Well, it just requires a user to edit the tsconfig properly alongside every addition to `pnpm add @mono/foo`. This is hard behavior to scale with a team.

**Comment by zkochan** [comment]
oh, I automated that. In the pnpm monorepo, you just run `pnpm run update-manifests` and all the references and some other things are updated automatically.

[This is script](https://github.com/pnpm/pnpm/blob/master/utils/updater/src/index.ts) does that. I was thinking about making it a separate package, so other could use it:

**Comment by dfee** [comment]
Either it can be a separate package (nice!) or everyone is going to need to reinvent it! (I'd definitely use it... and thought about automating it, but haven't gotten around to it yet). Would probably use it as part of a pre-commit hook actually.

That said, the root problem about filtering dependents and their dependencies extends further than just building. That problem also applies to installs! I'm not sure what the overhead will be as my monorepo begins to scale from 2000+ dependencies to an order of magnitude more, though.

**Comment by idan-at** [comment]
Any updates on this one?

Allowing to `install` & `build` only the relevant packages can have great benefits in PR-CI in a large monorepo.

Is there a way I can help?

**Comment by zkochan** [comment]
@idan-at do you need this for TypeScript projects? In that case, I suggest using project references.

**Comment by idan-at** [comment]
we do have typescript, but we have other build steps as well (`babel`, `protoc`, and more)

From my understanding, even without a build step, since partial installs do not include dependencies of dependents, a simple ci flow running `pnpm recursive install --filter ...[origin/master]... && pnpm recursive test --filter ...[origin/master]` will fail. Am I missing something?

(running the commands above (plus the build steps) is basically what I'm aiming for my pr-ci)

**Comment by zkochan** [comment]
@idan-at if you want to contribute this change, the related code is in here: https://github.com/pnpm/pnpm/tree/main/packages/filter-workspace-packages

**Comment by idan-at** [comment]
sure, I will give it a try. what are we aiming for? do we want `...filter...` to include dependencies of dependents ? (tho its a breaking change)

or would you like to introduce a new filtering syntax to specifically target this scenario?

**Comment by zkochan** [comment]
I think changing how `...filter...` works is fine

**Comment by zkochan** [comment]
:ship: 5.13.5
