### ISSUE TITLE
@pnpm/pnpm is not in the npm registry

### ISSUE THREAD

**Issue by 12sam12** [pnpm/pnpm#2921]
### .pnpm-debug.log file data:

"error pnpm": {
    "message": {
      "code": "ERR_PNPM_FETCH_404",
      "hint": "@pnpm/pnpm is not in the npm registry, or you have no permission to fetch it.\n\nNo authorization header was set for the request.",
      "request": {
        "url": "https://registry.npmjs.org/@pnpm%2Fpnpm"
      },
      "response": {
        "size": 0,
        "timeout": 0
      },
      "pkgName": "@pnpm/pnpm",
      "pkgsStack": []
    },
    "err": {
      "name": "Error",
      "message": "GET https://registry.npmjs.org/@pnpm%2Fpnpm: Not Found - 404",
      "code": "ERR_PNPM_FETCH_404",
      "stack": "Error: GET https://registry.npmjs.org/@pnpm%2Fpnpm: Not Found - 404\n    at fromRegistry (.npm-global/lib/node_modules/pnpm/lib/node_modules/@pnpm/npm-resolver/lib/fetch.js:29:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
    }
  }

### Expected behavior:
Installing new packages -> should install fine

### Actual behavior:
Installing new packages ->  ERROR  GET https://registry.npmjs.org/@pnpm%2Fpnpm: Not Found - 404

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:  Linux (Ubuntu)

**Comment by zkochan** [comment]
pnpm is published as pnpm. Why do you want to install `@pnpm/pnpm`?
