### ISSUE TITLE
Changed linking mechanism since 5.9.0

### ISSUE THREAD

**Issue by delanni** [pnpm/pnpm#2925]
### Code to reproduce the issue:
Using this setup as a base for reproducing: https://github.com/prezi/pnpm-monorepo-test

Try out the following routine with the two different versions (pnpm@5.8.0 and pnpm@5.9.0):

```
npm run clean # get a clean slate
npm run init # install dependencies
cd packages/package_27 # probably any package would do
pnpx webpack --version # just access webpack, so the binary can run the check for finding 'webpack-cli'
```

### Expected behavior:
Print the version for webpack in both cases.

### Actual behavior:
Only 5.8.0's installation will work.

### Additional information:

- With PNPM 5.8's installation, this would work. Wepback finds the `webpack-cli` binary installed in `packages/package_27/node_modules`  and it will be happy.
- With PNPM 5.9's installation, this would fail. Webpack's binary tries to find `webpack-cli`and fails, so it prompts you to install it.

Now, I understand this is only going to happen in 4.44.0 for webpack, because after that version, wepback is listing `webpack-cli` as a peer dep, so it will be linked next to webpack.

However, I think this points out something of a difference in the setup, or the way packages are linked, because 5.9 started to break our monorepo setup.

I did some more investigating, and I found a difference in the `require.resolve.paths('wepack-cli')` when in the runnable script for webpack:
[resolution-trace.js.txt](https://github.com/pnpm/pnpm/files/5370932/resolution-trace.js.txt)

On the trace above, you can clearly see, that in version 5.8.0, the package's install dir was also scanned, so libraries that were sitting next to each other in a package's node_modules would find this relationship.

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
Do you use different versions of webpack in your monorepo? If you use one version, you may install it as a dependency of the root package. All CLI commands installed in the root are accessible in the whole monorepo
