### ISSUE TITLE
Allow the use of the current shell environment (example: git-bash in windows) when executing scripts.

### ISSUE THREAD

**Issue by b4git** [pnpm/pnpm#2931]
### pnpm version:
5.9
### Additional information:

 - `node -v` prints: v14
 - Windows, OS X, or Linux?: Windows 10

Unfortunately, setting `shell-emulator = true` works for a small expression, but fails miserably for longer statements. Frankly, there should be no need for that `shell-emulator` if you could simply allow to run the scripts using the current environment the user is using as `git-bash` already provides enough cross-platform scripting support.

**Comment by b4git** [comment]
I found the solution to this problem -- npm now does allow to use custom shells by configuring `script-shell` setting. It's poorly documented feature [here in npm](https://docs.npmjs.com/misc/config#script-shell). 

To enable it, simply run the following command and now npm or pnpm will use `git-bash` to run the scripts.

`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`

**Comment by TigersWay** [comment]
Hi,
This issue should be re-opened as [@yarnpkg/shell](https://pnpm.js.org/en/cli/run#shell-emulator) and git/bash do not have the same features, even for simple commands like mkdir or rm.

And the idea to have clean cross platform scripts is quite a nice thing!

**Comment by b4git** [comment]
> Hi,
> This issue should be re-opened as [@yarnpkg/shell](https://pnpm.js.org/en/cli/run#shell-emulator) and git/bash do not have the same features, even for simple commands like mkdir or rm.
> 
> And the idea to have clean cross platform scripts is quite a nice thing!

If git-bash is not enough for your case, then  I would recommend directly using WSL bash in windows and setting it as the default script-shell. That should provide the full support for cross-platform scripts.

**Comment by TigersWay** [comment]
> If git-bash is not enough for your case, then I would recommend directly using WSL bash in windows and setting it as the default script-shell. That should provide the full support for cross-platform scripts.

Sorry, little misunderstanding that I believe I need to clear:
- git-bash is more than enough, in fact perfect for my needs,
- yarn/shell - once finished/corrected - will probably be too,
- WSL is a hammer to kill a fly.

That's why the **recent option you documented earlier** is a lifesaver and should be available in pnpm too.

**Comment by b4git** [comment]
> > If git-bash is not enough for your case, then I would recommend directly using WSL bash in windows and setting it as the default script-shell. That should provide the full support for cross-platform scripts.
> 
> Sorry, little misunderstanding that I believe I need to clear:
> 
> * git-bash is more than enough, in fact perfect for my needs,
> * yarn/shell - once finished/corrected - will probably be too,
> * WSL is a hammer to kill a fly.
> 
> That's why the **recent option you documented earlier** is a lifesaver and should be available in pnpm too.

Well, regarding `WSL is a hammer` - since `git-bash` comes with `git` installation by default, it will be the lowest overhead solution than using additional packages. So, if WSL is a hammer, that emulator will still be another smaller hammer while `git-bash` will be no extra hammers at all! Also, it will probably take years to implement the full features in that extra emulator which is already present in `git-bash`. 

Having that emulator as an extra optional add-on package (rather than dependency) that can be separately installed by users only if needed could be better choice if you try to optimize the use of system resources.

**Comment by b4git** [comment]
@zkochan @TigersWay  The original intent of this post was to allow the `full use of the current shell environment` when executing scripts -- and the solution was found using `npm configuration` settings as mentioned above. 

Use of emulator is somewhat related to this post, but it might seem misleading to keep this post open given the solution, so emulator might have to be a separate request than this!
