### ISSUE TITLE
Running scripts in cli: Pass the args after `--` to the program called

### ISSUE THREAD

**Issue by aminya** [pnpm/pnpm#2937]
In cli, using `npm` we can pass extra args that will be passed to the actual program that runs. For example, for this script:
```
"lint": "eslint ."
```

I can use:
```
npm run lint -- --fix
```
which passes `--fix` to eslint.

This does not happen in pnpm.

Here is another example: https://jestjs.io/docs/en/cli#using-with-npm-scripts

### Code to reproduce the issue:
See above

### Expected behavior:
Passing args after `--` to the actual program

### Actual behavior:
Does not pass them.

### Additional information:

 - `node -v` prints: 14
 - Windows, OS X, or Linux?: win 10

**Comment by zkochan** [comment]
How is this not working? I use this all the time with pnpm. There are even unit tests that cover this feature.

**Comment by aminya** [comment]
It does not work. For example, 

```
> ❯ pnpm lint

> terminal@0.0.0 lint C:\Users\aminy\Documents\GitHub\JavaScript\terminal
> eslint .
...
```

```
❯ pnpm lint -- --fix
 ERROR  Unknown option: 'fix'
Did you mean 'prefix'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help run
```

**Comment by zkochan** [comment]
Do you use powershell? Try pnpm lint `-- - -fix

**Comment by aminya** [comment]
Yes I use PowerShell. `pnpm lint `-- --fix` works. But I do not need to escape the flag when I use `npm`.

**Comment by zkochan** [comment]
I know, the reason for this issue is that we generate a powershell shims for commands. And the powershell shim works badly with `--`. We should probably make the powershell shims opt-in.
