### ISSUE TITLE
prepublishOnly was executed twice when publish

### ISSUE THREAD

**Issue by VitorLuizC** [pnpm/pnpm#2941]
### Code to reproduce the issue:

```sh
pnpm publish -r
```

### Expected behavior:
`prepublishOnly` of each package is executed once before publishing.

### Actual behavior:
`prepublishOnly` of each package is executed twice before publishing.

### Additional information:

 - `node -v` prints: v14.14.0
 - Windows, OS X, or Linux?: Windows with WSL (Ubuntu).

**Comment by PabloSzx** [comment]
any workaround to this?

**Comment by zkochan** [comment]
This code is in https://github.com/pnpm/pnpm/blob/main/packages/plugin-commands-publishing/src/recursivePublish.ts

if it executes twice, maybe `npm publish` ignores the `--ignore-scripts` option.

**Comment by PabloSzx** [comment]
https://github.com/npm/cli/issues/2755 It seems to be an issue with npm 😞

**Comment by zkochan** [comment]
Indeed, this is a regression in npm v7. Use npm v6 for now.

**Comment by styfle** [comment]
I believe the issue might be related to `pnpm pack` running the `prepublishOnly` script when it should not

**Comment by rafaelliu** [comment]
@styfle is probably right, came here to file an issue about that. OP's issue is probably a consequence to `prepublishOnly` being executed during `pack`.

Here's what I'm seeing:

```
❯ pnpm pack

> mypkg@0.0.0 prepublishOnly <$PWD>
> echo prepublishOnly executed

prepublishOnly executed

> mypkg@0.0.0 prepack <$PWD>
> echo prepack executed

prepack executed
mypkg-0.0.0.tgz

```

**Comment by zkochan** [comment]
ok, it should be fixed.
