### ISSUE TITLE
Generate npm-shrinwrap.json

### ISSUE THREAD

**Issue by raypatterson** [pnpm/pnpm#2948]
First, this tool is awesome, and I really need it for the type of work I'm doing!

I also have a weird requirement where I need to generate an `npm-shrinwrap.json` from my `node_modules` and due to the way PNPM symlinks to a very shallow depth, It's not allowing the file to be generated accurately. It seems that PNPM can produce what nearly looks like an `npm-shrinwrap.json` from `pnpm list --depth -1 --json` and so I'm wondering if it's possible to construct one from that info.

If there's something I can do to make PNPM install to the `node_modules` as NPM or Yarn (without hoisting) would, please let me know, as that would probably do the trick. I've tried various hoisting configuration options but can't seem to get installs to look like the structure that NPM would produce so I may `npm shrinkwrap`.

Thanks!

**Comment by zkochan** [comment]
I don't think that you'll be able to generate a `npm-shrinkwrap.json` from a node_modules created by pnpm.
