### ISSUE TITLE
PNPM is less descriptive about unmet peer dependencies when running with "strict-peer-dependencies" enabled

### ISSUE THREAD

**Issue by D4N14L** [pnpm/pnpm#2950]
### Code to reproduce the issue:

Add a package that has a `peerDependency`, but intentionally do not satisfy the peer dependency.

### Expected behavior:

`./path/to/project    |    ERROR     <package> requires a peer of <required peer dep> but none was installed.`

### Actual behavior:

`ERROR     <package> requires a peer of <required peer dep> but none was installed.`

### Additional information:

The actual behavior appears when running the install with `strict-peer-dependencies` enabled. However, when running with the feature disabled, the `WARN` message is more descriptive and specifies the path to the package (relative to the install root) that must be modified to satisfy the peer dependency. Whenever this issue appears in my repo, I call PNPM with the `strict-peer-dependencies` disabled in order to determine which packages need to be fixed.

 - Windows, OS X, or Linux?: Windows

**Comment by mcmxcdev** [comment]
Looks like this one has been fixed in the meantime. The path to the workspace project shows as expected in both cases:

With `strict-peer-dependencies=true`
```
$ pnpm i --prefer-frozen-lockfile=false
Scope: all 2 workspace projects
Packages: +28
++++++++++++++++++++++++++++
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

packages/package-1
└─┬ prisma-field-encryption 1.4.1
  └── ✕ missing peer @prisma/client@"^3.8.0 || ^4"
Peer dependencies that should be installed:
  @prisma/client@"^3.8.0 || ^4"  

hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.

Progress: resolved 73, reused 72, downloaded 0, added 0
```

***

With `strict-peer-dependencies=false`
```
$ pnpm i --prefer-frozen-lockfile=false
Scope: all 2 workspace projects
Already up to date
 WARN  Issues with peer dependencies found
packages/package-1
└─┬ prisma-field-encryption 1.4.1
  └── ✕ missing peer @prisma/client@"^3.8.0 || ^4"
Peer dependencies that should be installed:
  @prisma/client@"^3.8.0 || ^4"  

Progress: resolved 17, reused 17, downloaded 0, added 0, done
Done in 446ms
```
