### ISSUE TITLE
pnpm fails to install the recursive dependencies properly

### ISSUE THREAD

**Issue by bodqhrohro** [pnpm/pnpm#2952]
### pnpm version:

5.9.3

### Expected behavior:

The dependencies of dependencies are installed in the root of `node_modules` like `npm` and `yarn` do.

### Actual behavior:

I discovered that when trying to install the dependencies for [matrix-bifröst](https://github.com/matrix-org/matrix-bifrost/issues/173) with `pnpm`.

The `@xmpp/component-core` and `@xmpp/reconnect` packages are not listed explicitly in `package.json`, but rather are the dependencies of `@xmpp/component` package. `pnpm` seems to resolve them, as I can find them in `node_modules/.pnpm/` directory:

```
node_modules/.pnpm/@xmpp/component-core@0.11.0/node_modules/@xmpp/component-core
node_modules/.pnpm/@xmpp/component-core@0.6.2/node_modules/@xmpp/component-core
node_modules/.pnpm/@xmpp/component@0.11.0/node_modules/@xmpp/component-core
node_modules/.pnpm/@xmpp/component@0.6.2/node_modules/@xmpp/component-core
node_modules/.pnpm/node_modules/@xmpp/component-core
node_modules/.pnpm/xmpp.js@0.6.2/node_modules/@xmpp/component-core
```

But they don't appear in the root. This behaviour is the same both with `pnpm i` and `pnpm i -r`.

### Additional information:

 - `node -v` prints: v12.19.0
 - Linux

**Comment by zkochan** [comment]
It is not a pnpm issue. I answered in the references issue. 

Also, you wanted `pnpm install --shamefully-hoist`

Recursive is for different purpose.
