### ISSUE TITLE
[workspace] Customizable content directory for distribution steps

### ISSUE THREAD

**Issue by manrueda** [pnpm/pnpm#2958]
Currently using `workspace` pnpm assumes that the distributable content of the package is located the same folder as the source code content. That is not completely true in some cases where the code has to get compiled or manipulated to create the correct distributable, even there are frameworks/tools that enforce that like Angular (Angular creates a whole new directory with 100% of the content ready to get published inside a `dist` folder, even they generate a `package.json` file with extra data that is required).

It will be useful to have a configuration per package that pnpm can ready and change the normal behavior from using the root folder of the package to use a sub-directory. This should be honored during publishing and linking packages across the workspace.

As a reference, Lerna has a similar feature (https://github.com/lerna/lerna/tree/master/commands/publish#publishconfigdirectory), personally I like the use of `publishConfig` for per-package configuration and I know that pnpm already use this pattern.

If I get some directions and guidance I can work on a PR for this feature.

**Comment by aminya** [comment]
This is related to https://github.com/pnpm/pnpm/issues/2959

**Comment by manrueda** [comment]
Yes, the issue is the same. You mentioned a solution but can't find it, or you meant that you suggest a solution?

**Comment by aminya** [comment]
> You mentioned a solution but can't find it, or you meant that you suggest a solution?

I suggested one. It is not implemented yet

**Comment by zkochan** [comment]
so #2959 was implemented.

Is this issue still needed?

**Comment by manrueda** [comment]
I don't think so. The solution on #2959 does the trick
