### ISSUE TITLE
Capability of specifying a path instead of "workspace:*"

### ISSUE THREAD

**Issue by aminya** [pnpm/pnpm#2959]
I already explained the issue in [this issue](https://github.com/pnpm/pnpm/issues/2938#issuecomment-712413592). We "must" add all the packages to `pnpm-workspace.yaml` (even those that are generated). But for this to work. pnpm requires specifying a certain folder instead of `"workspace:*"`.

In short, I use babel to build the folder that includes all the packages (say `pkg`) and write the built packages to the dist-* folder (`dist-pkg`).

This means there will be two folders in the workspace that use the same name, and so, we need to specify a certain folder instead of `"workspace:*"`.

My suggestion is to calculate the path from the root of the workspace. So, something like this:
```
    "pkg1": "workspace:./dist-pkg/pkg1",
```

Normally, pnpm considers this:
```
    "pkg1": "workspace:./pkg/pkg1",
```

**Comment by zkochan** [comment]
I would love it to be a relative path from the monorepo root. However, Yarn supports the same and expects a relative path from the package that has this field.

**Comment by zkochan** [comment]
Before publishing these version specs should be converted to regular version ranges. But what should be the resulting range?

`workspace:*` is converted to the exact version of the package.

Maybe we can convert `workspace:../foo` to the exact version of foo and `workspace:^../foo` to something like `^1.0.0`.

So if foo is 1.0.0 in the repository:

* workspace:../foo => 1.0.0
* workspace:~../foo => ~1.0.0
* workspace:^../foo => ~1.0.0

**Comment by aminya** [comment]
> I would love it to be a relative path from the monorepo root. However, Yarn supports the same and expects a relative path from the package that has this field.

That's fine. That works too

> Before publishing these version specs should be converted to regular version ranges. But what should be the resulting range?
> workspace:* is converted to the exact version of the package.

This feature should not affect the versions. It should fetch the version from the package.json of the given path.

**Comment by zkochan** [comment]
> This feature should not affect the versions. It should fetch the version from the package.json of the given path.

ok, but should the exact version be used then? Should the package.json be published with `"dependencies": { "foo": "1.0.0" }`
or with `"dependencies": { "foo": "^1.0.0" }` ?

**Comment by aminya** [comment]
I personally prefer `^`. I am not sure about others' opinions. Maybe, it is safer to use the exact version 🤷‍♂️

**Comment by ExE-Boss** [comment]
An absolute path (e.g.: `workspace:/packages/foo`) should be the one that’s resolved relative to the workspace root.

**Comment by zkochan** [comment]
Let's discuss the absolute path in a separate issue if it is needed.

**Comment by aminya** [comment]
Thanks for fixing this 🎉
