### ISSUE TITLE
bug: TypeError when modifying the store

### ISSUE THREAD

**Issue by aparajita** [pnpm/pnpm#2963]
### pnpm version:

5.10.3

### Code to reproduce the issue:

pnpm install
pnpm remove

### Expected behavior:

No errors.

### Actual behavior:

I get this message every time I do an operation that modifies the store:

```
TypeError: callback is not a function
    at success (/Users/aparajita/.fnm/node-versions/v15.0.1/installation/pnpm-global/4/node_modules/.pnpm/pnpm@5.10.3/node_modules/pnpm/lib/node_modules/write-file-atomic/index.js:162:5)
```

### Additional information:

 - `node -v` prints: 5.10.3
 - Windows, OS X, or Linux?: macOS

This bug appeared in 5.10.3.

**Comment by zkochan** [comment]
Node.js 5? We only support 10 and newer

**Comment by zkochan** [comment]
I know what is the problem. The wrong version of write-file-atomic was bundled with pnpm during publishing of 5.10.3

**Comment by aparajita** [comment]
Oops, that was the pnpm version, sorry. I figured you would find the cause quickly.

**Comment by zkochan** [comment]
:ship: 5.10.4
