### ISSUE TITLE
Deprecate pnpm-workspace.yaml

### ISSUE THREAD

**Issue by hinell** [pnpm/pnpm#2966]
I propose to deprecate `pnpm-workspace.yaml` in favor of `package.json#workspaces` field.

### Rationale
Other tools tend to use root `package.json` as starting point of configuration for monorepo project. At least two use `workspaces` field for glob patterns (as of November 4, 2020). Here is a small comparison between tools:
| Package Manager | File* | Field |
| - | - | - |
| **pnpm**  | `pnpm-workspace.yaml` | [`packages: ...`][pnpm-w] |
| **yarn**  | `package.json`| [`workspaces: [...]`][yarn-w] |
| **npm**   | `package.json`| [`workspaces: [...]`][npm-w] |
| **lerna** | `lerna.json`  | [`packages  : [...]`][lerna-w] |
| **rush** | `rush.json` | [`projects  : [ {packageName: ... }... ]`][rush-w]  | 

### Pros
- less to learn, quick to grasp
- Interop with existing tools enabling easy bidirectional migration (in case of tool's discontinuation)
- No need for extra file to pollute the project's file tree and
- At least two issues can be closed immediately:  #2614 #1197
- No need for extra YAML dependency, no need for maintenance
(assuming no other `pnpm` features are YAML-bound)

### Cons
- Interop limitations prevented by possible differences in third-party tools's `workspaces:` definitions (highly unlikely)
- Reuse of `workspaces` by third-party tools may cause false-positivie "bug" reports due to false expectations from consumers
- Need for migration  from `pnpm-workspace.yaml` to `package.json#workspaces`

### Steps to deprecate
1. Add deprecation notices, brief guide on migration; continue to use `pnpm-workspace.yaml`
2. Commit as Minor version (per [semver])
3. Refactor all commands to honor `package.json#workspaces` field instead of `pnpm-workspace.yaml` in first place 
4. Commit as Major version: Breaking change

[semver]: https://semver.org/
[pnpm-w]: https://pnpm.js.org/en/pnpm-workspace_yaml
[yarn-w]: https://yarnpkg.com/configuration/manifest#workspaces
[npm-w]: https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md#implementation
[lerna-w]: https://github.com/lerna/lerna#lernajson
[rush-w]: https://rushjs.io/pages/configs/rush_json

**Comment by zkochan** [comment]
There are some issues with Yarn's approach, which npm 7 adopted as well.

First of all, they use the noun "workspace" to call a package inside the monorepo. Which is not what most people expect, according to the polls I did on Twitter. A workspace usually means a set of projects in IDE world.

The second issue is that it is much harder to find the root of the workspace, when that info is declared in package.json. It is not enough to find the first `pnpm-workspace.yaml` in the parent directories, you need to read each package.json file in the parent directories. It would be fine to use `workspace.json` file instead, which would behave similarly to a package.json but dedicated to the root workspace project.

I cannot object if most of the users want this change but then we'll have to do a lot of renamings in the repository.

**Comment by hinell** [comment]
@zkochan  Thank's for speedy answer.

>_A workspace usually means a set of projects in IDE world._

1. Considering that the bad naming is already established and abused by major managers there is little space for maneuver. I'm afraid that suggesting to use `packages: [...]` would cause general hassle in all these project's lol. Doesn't worth efforts.

>_[...] it is much harder to find the root of the workspace, when that info is declared in package.json [...]_

2. The best approach IMO is just to use root at the folder where the `pnpm` was called. The  `private: true` and zero `dependencies` can serve as a hint of root `package.json` for `pnpm-cli` to stop at.

**Comment by hinell** [comment]
@zkochan  Thanks for speedy answer.

>_A workspace usually means a set of projects in IDE world._

1. Considering that the bad naming is already established and abused by major managers there is little space for maneuver. I'm afraid that suggesting to use `packages: [...]` would cause general hassle in all these project's lol. Doesn't worth efforts.

>_[...] it is much harder to find the root of the workspace, when that info is declared in package.json [...]_

2. The best approach IMO is just to use root at the folder where the `pnpm` was called. The  `private: true` and zero `dependencies` can serve as a hint of root `package.json` for `pnpm-cli` to stop at.

**Comment by zkochan** [comment]
I am not convinced yet that Yarn's approach can be considered a standard. Lerna is still very popular and uses a separate file. pnpm uses a separate file and Rush uses a `rush.json` as well.

**Comment by statianzo** [comment]
Reusing the same package.json key could give the expectation that pnpm needs to behave identically to other monorepo managers.

There was a similar backtracking of `resolutions` in https://github.com/pnpm/pnpm/pull/2946

**Comment by zkochan** [comment]
Let's hear what others think

cc @pnpm/collaborators

**Comment by KSXGitHub** [comment]
> * No need for extra YAML dependency, no need for maintenance

Does pnpm still requires YAML for lockfiles?

**Comment by zkochan** [comment]
yes

pnpm-lock.yaml

also, Yarn uses yaml for its lockfile as well.

**Comment by ExE-Boss** [comment]
I personally prefer `pnpm‑workspace.yaml`, [for the reasons highlighted above](https://github.com/pnpm/pnpm/issues/2966#issuecomment-721884274).

**Comment by hinell** [comment]
> _Yarn's approach can be considered a standard. ..._

@zkochan  It may not and should not be in first place. The proposal is for the sake of interoperability/coherence between tools only. 

> _Lerna is still very popular and uses a separate file ..._

@zkochan Primary maintainers [may discontinue][lerna-pr-1887] the project in favor of other tools like `pnpm` etc at any point as more monrepo-like features are getting added over time.


> _could give the expectation that pnpm needs to behave identically. [...]_

@statianzo  Good point. I've updated description, checkout. Such expectations are completely unwarranted. No further compliance with existing tools is required by this proposal.

[lerna-pr-1887]: ../../../lerna/lerna/pull/1887#issuecomment-640285310

**Comment by juanpicado** [comment]
My 0.50 cents. Long story short, I prefer to have a separate file, either is only for workspaces or anything else. 

I'd rather prefer to see a `.pnpmrc`. file or `.pnpm.yaml` in the root of the project or something generic open for other sorts of settings and stop using `.npmrc` as [yarn2 just did](https://yarnpkg.com/getting-started/migration/#dont-use-npmrc-files), not only workspaces. 

One reason is, the `package.json` should contain only the relevant metadata of the package itself, instead of being polluted with third-party stuff. From my perspective (node.js registries) I see this pattern growing in many projects and makes metadata bigger and this information is useless for package managers and registries (I/O has a price). eg:
http://registry.npmjs.org/react
```
  "browserify": {
        "transform": [
          "loose-envify"
        ]
      },
```
There are other examples, as `commitlint`, `opencollective` and a long etc. 

Having a separate file you have more options to scale, avoid collisions, and is way easier to read and recognize the origin. 

I understand is more convenient to have everything in the `package.json`, but is far away to be a standard. Cannot be commented out (I find this useful for contributors or team workmates who want to know more about what X means). 

Having this, you can workout nice stuff like better IDE strategy for autocomplete or stuff like that (vcode extensions), I think this is hardly possible using the `package.json`.

**Comment by hinell** [comment]
> _[...] as yarn2 just did, not only workspaces. [...]_
>_[...] instead of being polluted with third-party stuff. [...]_

@juanpicado Thanks for sharing. My proposal doesn't concern `.rc` files. In fact, [`pnpm` uses two different files][pnpm-cfg] for two different configs pathways. I'm completely fine with `.pnpmrc`. The `workspaces`are not third party stuff now but rather a built-in, native to `npm` ones. Checkout OP's table.

[pnpm-cfg]: https://pnpm.js.org/en/package_json

**Comment by hinell** [comment]
> _[...] as yarn2 just did, not only workspaces. [...]_
>_[...] instead of being polluted with third-party stuff. [...]_

@juanpicado Thanks for sharing. My proposal doesn't concern `.rc` files. In fact, [`pnpm` uses two different files][pnpm-cfg] for two different configs pathways. I'm completely fine with `.pnpmrc`. The `workspaces`are not third party stuff anymore but rather a built-in, native to `npm` ones. Checkout OP's table.

[pnpm-cfg]: https://pnpm.js.org/en/package_json

**Comment by ExE-Boss** [comment]
The issue for supporting `.pnpmrc` is <https://github.com/pnpm/pnpm/issues/2803>.

**Comment by ematipico** [comment]
Personally, I think it would be best to keep everything inside a separate file. The `package.json` ultimately has been abused a lot, where various tools decided to put their own configuration. As a result, the file becomes really big and it contains sections that are not even standard.

**Comment by hinell** [comment]
@ematipico `workspaces` standard already, read thread.

**Comment by tvvignesh** [comment]
@zkochan Rather than worrying about this, I guess you can have a sort of CLI option supporting both 😅 While I personally like `pnpm-workspace`, reading the same config from the `package.json` may be valid for people who wants to have an interop for which they can probably use a non-default CLI flag where you can specify the root folder path. That way, you can probably satisfy both worlds.

**Comment by zkochan** [comment]
There was a discussion about that in this issue: #2255

**Comment by hinell** [comment]
@tvvignesh I also started to rethink the proposal and now think about leaving `pnpm-workspace.yaml` alone and add `package.json#workspaces` as additional source for list of globs which would be preferred over the first if one is not found. That's it.

**Comment by hinell** [comment]
@tvvignesh I also started to rethink the proposal. Especially in light of this [comment]. Now I think about leaving `pnpm-workspace.yaml` alone and add `package.json#workspaces` as additional source for list of globs which would be preferred over the first if it's is not found. That's it.

@zkochan Seems like this issue is raised often and it's reasonable. Will look into it.

[comment]: https://github.com/pnpm/pnpm/issues/2255#issuecomment-640253998

**Comment by jcayzac** [comment]
> The second issue is that it is much harder to find the root of the workspace, when that info is declared in package.json. 

Also, some PNPM monorepos don't have a root `package.json` to begin with (for instance, to prevent Netlify from always trying to install with NPM)

**Comment by pie6k** [comment]
My opinion is that pnpm should be 'transparent' and fully compatible with npm.



We're using npm 7.0+ as supports workspaces and our setup is working well. I don't want to demand other team members to have to use pnpm if they don't want to for any reason. Also I don't want to advocate for it. I think it should be drop-in replacement for npm yielding the same results as regular npm does.

**Comment by jcayzac** [comment]
> My opinion is that pnpm should be 'transparent' and fully compatible with npm.

IMHO no package manager ever has to care about looking like npm or using the same files as npm. I don't think any package manager has even to use `package.json` as it's primary development metadata format. I'm all for killing it and replace it with YAML, for all the reasons the format is better for teamwork than JSON.

The only rightful concerns are the ability to release packages to the npm registry (and that includes generating a valid npm-compatible `package.json` during the publish phase) and the ability to load a package from the npm registry (and so parse npm's `package.json` files).
