### ISSUE TITLE
slow startup, which translates into slow completions

### ISSUE THREAD

**Issue by vemoo** [pnpm/pnpm#2969]
### Code to reproduce the issue:

Tab completions feel very slow, and after some investigation I realized that the issue is slow startup. If we compare the time to show the help on pnpm, yarn and npm, this is what I get on my machine:
```
time pnpm -h
real    0m0,439s
user    0m0,526s
sys     0m0,057s

time yarn -h
real    0m0,095s
user    0m0,087s
sys     0m0,011s

time npm -h
real    0m0,105s
user    0m0,114s
sys     0m0,013s
```
Then I run pnpm with `node --cpu-prof` to get an idea of what was happening and what I found is that most of the time is spent loading modules. So I created `require_prof.js` with this code:
```js
const Module = require('module');
const originalRequire = Module.prototype.require;

const stats = {};
Module.prototype.require = function () {
    stats[arguments[0]] = (stats[arguments[0]] || 0) + 1
    return originalRequire.apply(this, arguments);
};

setTimeout(() => {
    let totalNum = 0;
    const vals = Object.values(stats);
    for (const v of vals) {
        totalNum += v;
    }
    console.log("num of required modules", vals.length);
    console.log("num of require calls", totalNum);
})
```
and if we include by calling each command with `node -r ./require_prof.js <path to bin>` this is what I get:

```
pnpm:
num of required modules 1813
num of require calls 4624

yarn:
num of required modules 21
num of require calls 25

npm:
num of required modules 208
num of require calls 424
```
Because maybe `<command> -h` is not representative, I did the same thing by running `<command> install` in [here](https://github.com/pnpm/benchmarks-of-javascript-package-managers/tree/master/fixtures/medium-size-app), but the values were the same. If I delay printing by 1s it doesn't change much except for npm:
```
pnpm:
num of required modules 1818
num of require calls 4640

yarn:
num of required modules 27
num of require calls 31

npm:
num of required modules 592
num of require calls 1939
```

### Expected behavior:

Tab completion feels instantaneous.

### Actual behavior:

Tab completion is slow, and is not usable to speed up writing commands.

### Additional information:

 - `node -v` prints: v14.15.0
 - Windows, macOS, or Linux?: Linux

I'm thinking that bundling pnpm may speed up startup and work as a short term solution. But I think pnpm should not require so many packages, and that there must be a lot of duplication among the dependencies.

**Comment by zkochan** [comment]
It would be interesting to try out bundling. Any good bundler suggestions? I tried with webpack and rollup but couldn't make them work. Probably needs more investigation but I was disappointed with how hard it is to configure.

**Comment by zkochan** [comment]
Seems like esbuild is the easiest to setup and almost works

**Comment by statianzo** [comment]
> Seems like esbuild is the easiest to setup and almost works

Do you have details on where esbuild is failing?

**Comment by zkochan** [comment]
bundling does not fail. But when I run the bundled file, there is an error. Something like cannot find module (one of the config reader dependencies). I'll check again later.

**Comment by zkochan** [comment]
To try it out, install esbuild globally. Go to the `packages/pnpm` directory.

Run `pnpm compile`.

Run `esbuild --bundle lib/bin/pnpm.js --platform=node  --outfile=lib/bunlde.js`

Run `node lib/bunlde.js -h`

**Comment by vemoo** [comment]
the issue seems to be that esbuild is not able to detect dependencies that are loaded through indirect `require` calls (as the warnings say). Adding those dependencies to `packages/pnpm/package.json` makes `node lib/bunlde.js -h` work. The dependencies are:
```
"resolve-from": "5.0.0",
"node-gyp": "7.1.0",
"xdg-basedir": "4.0.0",
"boxen": "4.2.0",
```
but there may be more when using other commands
