### ISSUE TITLE
Meta: v1.0

### ISSUE THREAD

**Issue by rstacruz** [pnpm/pnpm#297]
Is it time we bump the version to 1.0?

**Comment by rstacruz** [comment]
v0.25 is out by the way!

https://github.com/rstacruz/pnpm/blob/master/HISTORY.md

**Comment by rstacruz** [comment]
Oh and @zkochan, send me your npm username so I can add you there as well.

**Comment by zkochan** [comment]
Great! My username on npm is the same as on github - zkochan.

**Comment by zkochan** [comment]
I am not sure v1,0 is ready. git-hosted packages installation is not ready yet.

Also I think npm link/unlink/prune/update has to be implemented as well.

**Comment by rstacruz** [comment]
re: npm access: done!

also, totally agree on those points.

**Comment by zkochan** [comment]
Out of topic, but could you please add this webhook to the project settings? https://ci.appveyor.com/api/github/webhook?id=i30tealekiaesltb

I don't have access to that. This will trigger the appveyor build. Currently I am triggering it manually.

**Comment by rstacruz** [comment]
Man GitHub really needs a chat of sorts

**Comment by rstacruz** [comment]
enabled for `push`, `pull request` and `status`.

**Comment by zkochan** [comment]
true story.

thanks

We can create a gitter chat by the way, It is pretty good.

**Comment by iamstarkov** [comment]
can we get support for `optionalDeps` in 1.0-beta?

**Comment by iamstarkov** [comment]
it used to be a problem with ava, back then when chokidar was in `optionalDependencies` and after `pnpm install` you couldnt use watch mode for tdd

**Comment by zkochan** [comment]
that should already work since v0.24.0 https://github.com/rstacruz/pnpm/pull/256

**Comment by iamstarkov** [comment]
thats so cool, @zkochan you are doing awsm job here

**Comment by iamstarkov** [comment]
There are several v1 issues open left

**Comment by iamstarkov** [comment]
Like #298, #299 and #300

**Comment by iamstarkov** [comment]
Also #95 bothers me

**Comment by iamstarkov** [comment]
And let me check if it works in my office, last time pnpm didn't work with our local nexus, while npm works as expected

**Comment by iamstarkov** [comment]
I hope that npm-registry packet from #367 can solve a problem

**Comment by iamstarkov** [comment]
Also, what do you think about finishing moving to org before v1?

**Comment by zkochan** [comment]
yeah, I agree on what your saying, lets move to an org first and fix those issues

**Comment by zkochan** [comment]
Guys, I have to tell you, I am really happy with v0.48! It is a huge improvement! This is the first version that I can use at work! Previously I always had some small issues. This one works great!

And also I had some fears regarding `--preserve-symlinks` and the fact that it will probably be deprecated, but with the new design it is not even needed anymore! It is used by defaulf, for now, but you can turn it off with `npm config set preserve-symlinks false`

I am very-very satisfied! I hope more people will discover the project and enjoy it :-)

**Comment by andreypopp** [comment]
Awesome! Will there be a lockfile before 1.0?

**Comment by zkochan** [comment]
yes, there is a lockfile already. It is called `shrinkwrap.yaml`

**Comment by iamstarkov** [comment]
@zkochan yay

**Comment by zkochan** [comment]
Feels like v1 is really close now. I added some points to the breaking changes issue #458.

I wonder if we need to make the breaking changes that npm5 introduced. Like linking `file:` dependencies and the `prepare/prepublish` lifecycle events

**Comment by zkochan** [comment]
I plan to release v1 on 28th of June. I'll try to finish any last breaking changes this Sunday
