### ISSUE TITLE
Support NPM aliases for workspace packages ("npm:example@workspace:*")

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#2970]
### Code to reproduce the issue:

NPM allows you to create arbitrary aliases using the `npm:` version specifier. For example, if I want to import version 1 and version 2 of `@scope/example` as side-by-side versions, I can do this:

**package.json**
```
{
  "dependencies": {
    "@scope/example": "1.0.0",
    "example2": "npm:@scope/example@2.0.0"
  }
}
```

...and now I can do `require("@scope/example")`  for version 1 and use the alias  `require("example2")` for version 2.

But how do I do that with a local workspace package?  I tried embedding the `workspace:*` specifier:

**package.json**
```
{
  "dependencies": {
    "@scope/example": "1.0.0",
    "example2": "npm:@scope/example@workspace:*"
  }
}
```
But I get an error saying:
```
example2@npm:@scope/example@workspace:* isn't supported by any available resolver.
```

### Additional information:

 - `node -v` prints: 12.18.4
 - Windows, macOS, or Linux?: Windows

**Comment by hinell** [comment]
Where do you get second version of the same package if it's monorepo?

**Comment by octogonz** [comment]
From the NPM registry.

**Comment by zkochan** [comment]
I guess this will be covered by #2959

**Comment by zkochan** [comment]
I think we can support something like `"example2": "workspace:@scope/example@*"`, which will be converted to `"example2": "npm:@scope/example@1.0.0` before publish

**Comment by octogonz** [comment]
That seems like an okay design. You should document it prominently though, since otherwise nobody would guess that it is supported. 

It would actually be quite helpful if the PNPM website showed a complete list of all supported version range syntaxes. I usually infer this from the [npm-package-arg](https://www.npmjs.com/package/npm-package-arg) docs, but they are not very accurate nor easy to interpret.

**Comment by zkochan** [comment]
We have such documentation here: https://pnpm.js.org/en/cli/add#supported-package-locations

but maybe it misses some specs

**Comment by dcecile** [comment]
In case anyone is looking for the correct syntax, this worked for me:

```json
{
  "dependencies": {
    "@scope/example": "1.0.0",
    "example2": "workspace:@scope/example:*"
  }
}
```

(The `js.org` link above is no longer active and the [aliases](https://pnpm.io/aliases) page has `npm:` examples but doesn't mention `workspace:`.)

**Comment by krispya** [comment]
> ```json
> {
>   "dependencies": {
>     "@scope/example": "1.0.0",
>     "example2": "workspace:@scope/example:*"
>   }
> }
> ```

For those who come across this, the above didn't work for me and had one little typo, `example:*` needs to become `example@*` where the colon becomes an asterisk. This is with pnpm v9.1.4.  The example that worked for me is below:

 ```json
 {
  "dependencies": {
    "@scope/example": "1.0.0",
    "example2": "workspace:@scope/example@*"
  }
}
```

**Comment by damianobarbati** [comment]
@krispya it's not clear to me honestly, given a project "@project" and this tree:
````sh
package.json ("name":"project")
  /services
    /api
      /src
    /types
      /src
```
How can I import in an `.ts` file in api folder, something inside a `.ts` file in the types folder?
What should I put in the api service package.json?
