### ISSUE TITLE
How to forbid code to require package from devDepedency

### ISSUE THREAD

**Issue by hardfist** [pnpm/pnpm#2974]
### pnpm version:
5.11.1
### Expected behavior:
because I use pnpm install -D in production environment and pnpm install in development, sometimes my code
using package from devDep, which will fail in production environment because it's not installed, How can I forbidden my code
to use package from DevDep so that I can spot the issue early?
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by alexeyten** [comment]
Use eslint
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

**Comment by zkochan** [comment]
Linting is probably recommended. Or you can also try this package: https://github.com/zkochan/package-preview
