### ISSUE TITLE
Using `pnpm i -r`

### ISSUE THREAD

**Issue by idkjs** [pnpm/pnpm#2979]
### pnpm version:nassfd
❯ pnpm -v
5.11.1

### Code to reproduce the issue:

Clone https://github.com/apollographql/ac3-state-management-examples and run `pnpm i -r`

If your `rm node_modules` and `npm install` it works.

Maybe the solution is here: https://pnpm.js.org/en/faq#pnpm-does-not-work-with-your-project-here. Will post anyway for future reference.

### Expected behavior:
Running `npm run start` works.

### Actual behavior:

```sh
Failed to compile.

/Users/mandalarian/Downloads/LearnCache/ac3-state-management-examples/apollo-local-state/src/tests/createMockReactiveVar.ts
TypeScript error in /Users/mandalarian/Downloads/LearnCache/ac3-state-management-examples/apollo-local-state/src/tests/createMockReactiveVar.ts(11,3):
Property 'onNextChange' is missing in type '(newValue?: T | undefined) => T' but required in type 'ReactiveVar<T>'.  TS2741

     9 |   let currentValue: T | undefined = defaultValue;
    10 | 
  > 11 |   return function mockReactiveVar (
       |   ^
    12 |     newValue?: T
    13 |   ) : T {
    14 |     if (newValue) {
```

### Additional information:

❯ node -v
v14.4.0

❯ sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29

**Comment by idkjs** [comment]
Related. Running `pmpn install` directy in https://github.com/apollographql/ac3-state-management-examples/tree/master/apollo-local-state then `npm start` will produce this error:

```sh
Failed to compile.

/Users/mandalarian/Downloads/LearnCache/rac-state-management-examples/apollo-local-state/src/tests/createMockReactiveVar.ts
TypeScript error in /Users/mandalarian/Downloads/LearnCache/rac-state-management-examples/apollo-local-state/src/tests/createMockReactiveVar.ts(11,3):
Property 'onNextChange' is missing in type '(newValue?: T | undefined) => T' but required in type 'ReactiveVar<T>'.  TS2741

     9 |   let currentValue: T | undefined = defaultValue;
    10 |
  > 11 |   return function mockReactiveVar (
       |   ^
    12 |     newValue?: T
    13 |   ) : T {
    14 |     if (newValue) {

```

while running it with `npm install` will not.

I love pnpm and what it does for my install speed and space on my machine. I just need to figure out how to reliably run it on typescript/reasonml repos. It seems i am missing something obvious. Anyone care to teach? Is there some standard config that make this work generally?

Thank you.

**Comment by zkochan** [comment]
In most cases, when there are issues with tooling, the `shamefully-hoist=true` option helps.

**Comment by idkjs** [comment]
Will try it, thanks.
