### ISSUE TITLE
Print warnings if unknown settings are found in .npmrc

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2981]
The pnpm CLI is strict and will fail, when unknown options are used. But if someone makes a typo in a .npmrc, pnpm will just ignore the invalid setting. We should print some warnings.

**Comment by JasonKleban** [comment]
This is too sensitive.  I'm getting ` WARN  Your .npmrc file contains unknown setting:` with no setting names after it.  I have comments, "user-agent", and "registry" in mine.  Maybe it's picking up an empty line?
