### ISSUE TITLE
PNPM will create an empty temporary folder in the root directory of the partition by mistake every time it is used

### ISSUE THREAD

**Issue by zheung** [pnpm/pnpm#2984]
### Code to reproduce the issue:
1. `pnpm i any`
Please watch this GIF to feel intuitive:
![reproduce](https://user-images.githubusercontent.com/894004/99363233-75962100-28ef-11eb-99b9-87e2c9ccb847.gif)

### Expected behavior:
Will not create an empty temporary folder in the root directory of the partition.

### Actual behavior:
Created an empty temporary folder in the root directory of the partition.
Just like that:
`_tmp_12780_416427830a1abde94d85ec2cf6cdc39e`
`_tmp_15904_deca37c91dfd8937b655d07fab820fa4`

### Additional information:

 - `node -v` prints: v10.21.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
Duplicate of https://github.com/pnpm/pnpm/issues/2749

**Comment by zkochan** [comment]
:ship: 5.13.1
