### ISSUE TITLE
Feat: pnpm recursive --reverse

### ISSUE THREAD

**Issue by jonathanmorley** [pnpm/pnpm#2985]
This was discussed in the gitter a while back, but I would like a `--reverse` (or similar) flag to be able to pass to recursive pnpm executions, which would execute the commands in a reverse topological order.

The main driver for this feature is that we have some `ci:setup` scripts that use package dependencies to ensure a correct order of execution, and `ci:teardown` scripts that we would like to execute in the reverse order.

**Comment by zkochan** [comment]
I don't have objections

**Comment by zkochan** [comment]
:ship: 5.17
