### ISSUE TITLE
pnpm 5.13.2 is breaking node-gyp builds

### ISSUE THREAD

**Issue by wesselvdv** [pnpm/pnpm#2988]
### Code to reproduce the issue:

This breaks:

`npx -p pnpm@5.13.2 pnpm i 64 sodium-native`

While this doesn't:

`npx -p pnpm@5.13.1 pnpm i 64 sodium-native`

### Expected behavior:

Should install fine just like on versions < `5.13.2`

### Actual behavior:

Breaks on node-gyp with various errors (differ per package)

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by kidonng** [comment]
Doesn't know if it's actually the same issue, pnpm 5.13.2 in Homebrew is broken:

```
$ pnpm
Error: Cannot find module 'update-notifier'
Require stack:
- /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js
- /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/bin/pnpm.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js:37566:26
    at /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js:11:5
    at /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js:121664:45
    at /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js:11:5
    at /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js:121995:67
    at async runPnpm (/usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js:121995:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/pnpm.js',
    '/usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/bin/pnpm.js'
  ]
}
```

**Comment by zkochan** [comment]
who's maintaining the  homebrew package?

**Comment by kidonng** [comment]
> who's maintaining the  homebrew package?

The Homebrew package ("bottle") is automatically built by bot when people submits a update. I'm not sure if the broken build is related to this issue, just reporting.

> is update-notifier not present in /usr/local/Cellar/pnpm/5.13.2/libexec/lib/node_modules/pnpm/lib/node_modules?

No, you can check the output package here: https://bintray.com/homebrew/bottles/pnpm/5.13.2#files

Now that 5.13.3 is released, I will submit a update and see if it now builds correctly.

**Comment by zkochan** [comment]
The node_modules directory is missing from the tarball that is uploaded to homebrew.

Insdie that tarball, there should be a node_modules at libexec/lib/node_modules/pnpm/lib/node_modules
