### ISSUE TITLE
"pnpm" package on npm registry doesn't point to 5.13.2

### ISSUE THREAD

**Issue by g-plane** [pnpm/pnpm#2989]
pnpm 5.13.2 is released, but the "pnpm" package on npm registry doesn't point to the latest version which is 5.13.2. It points to 5.13.1.

Will this mistake be fixed? Otherwise, ArchLinuxCN repo can't build it because of the wrong version.

**Comment by zkochan** [comment]
it is not a mistake. A regression was reported in 5.13.2: https://github.com/pnpm/pnpm/issues/2988

**Comment by g-plane** [comment]
Okay. Hope to be fixed soon.

**Comment by zkochan** [comment]
Released 5.13.4 and marked as latest
