### ISSUE TITLE
google-auth-library and googleapis can't find modules

### ISSUE THREAD

**Issue by steveja42** [pnpm/pnpm#2992]
pnpm version 5.13.1, windows 10

When using the google-auth-library and googleapis packages, at the build step on pnpm install I get hundreds of "Cannot find module" errors from tsc.  The first few are:
node_modules/google-auth-library/build/src/auth/authclient.d.ts(3,46): error TS2307: Cannot find module 'gaxios' or its corresponding type declarations.
node_modules/google-auth-library/build/src/auth/computeclient.d.ts(1,29): error TS2307: Cannot find module 'gaxios' or its corresponding type declarations.       

gaxios is a dependent of google-auth-library in its package.json and it builds ok when I use npm instead of pnpm.

[package.zip](https://github.com/pnpm/pnpm/files/5578902/package.zip)

**Comment by steveja42** [comment]
Perhaps this is the same as #1933

**Comment by zkochan** [comment]
have you tried with `shamefully-hoist=true`?

**Comment by steveja42** [comment]
I tried it just now and it works ok with shamefully-hoist=true

**Comment by zkochan** [comment]
then it is not an issue with pnpm. Seems like some of the dependencies try to use packages that are not in their dependencies.

**Comment by Countrygrl00** [comment]
[942617]() 

>

**Comment by Countrygrl00** [comment]
#
