### ISSUE TITLE
pnpm publish should get the main branch name from config

### ISSUE THREAD

**Issue by aparajita** [pnpm/pnpm#2995]
### Code to reproduce the issue:

On a repo created in the last few months, where the default branch is `main`:

```
pnpm publish
```

### Expected behavior:

I expect it to figure out that the default is `main`, not `master`.

### Actual behavior:

I get this prompt:

```
✔ You're on branch "main" but your "publish-branch" is set to "master". Do you want to continue? (y/N) · false
```

### Additional information:

First of all, the default in pnpm should be changed to `main`, since that is what the `git` and `github` default is now.

In any case, running `git config init.defaultbranch` returns the default branch name for the current repo.

 - `node -v` prints: 15.0.1
 - Windows, macOS, or Linux?: macOS

**Comment by mghweb** [comment]
Also, for those that are using git-flow, it would be nice to be able to add a wildcard rule. Like: `release/*`

**Comment by zkochan** [comment]
@mghweb for the git-flow, wouldn't you just use `pnpm publish --no-git-checks`

though I am not against supporting wildcards

**Comment by zkochan** [comment]
`git config init.defaultbranch` does not return the default branch name of the current repository. It returns the setting which controls what will be the default branch name of a newly created repository
