### ISSUE TITLE
Shrinkwrap

### ISSUE THREAD

**Issue by Rush** [pnpm/pnpm#30]
I was pretty excited to hear about this project. I can see that shrinkwrap is not supported at the moment but do you plan to support it at later point? And if so, what's the schedule?

**Comment by rstacruz** [comment]
I am not sure. I'd love for it to happen sometime but it's pretty difficult
to do with the current store setup (but not impossible!). Can't commit to a
timeline for that one, sorry.

**Comment by rstacruz** [comment]
I'll have to rescind that... with #38, we now have compatibility with `npm shrinkwrap`. For now, because of npm/npm#11354, you'll need to do:

```
npm shrinkwrap --dev
```

It will land in v0.12.0 which should be out soon.

**Comment by zkochan** [comment]
We cannot support npm's shrinkwrap unfortunately, because pnpm's node_modules structure differs from the one used by npm. However, pnpm has now its own `shrinkwrap.yaml` format created automatically on each installation
