### ISSUE TITLE
feat: Provide option to generate a package-lock.json or yarn.lock for compatibilty when deployment

### ISSUE THREAD

**Issue by redstrike** [pnpm/pnpm#3002]
Currently, `pnpm-lock.yaml` is not supported by many hosting providers (such as Vercel).
We still need to include a lock file (`package-lock.json` or `yarn.lock`) for quickly installing dependencies on server-side while deploying.
I'm working around this issue by introducing an extra step to generate a lock file via `npm i --package-lock-only`.
However, it runs very slow and breaks `package-lock.json` after the first run. (I have to delete the old lock file and re-run)
Therefore, I wonder if pnpm can support generate an extra lock file for better compatibility.

**Comment by zkochan** [comment]
That sounds like a really bad idea. You will have "works on my machine issues" because you'll be using a different package manager in production. I would suggest bundling the app instead. That way, no need in package manager in prod.

**Comment by redstrike** [comment]
I was using `yarn` or `npm` for package management, and the deployment process is very straight forward. Just run `vc --prod` and Vercel CLI can handle the rest.

I think it would be great if we don't need to introduce extra bundling steps for simple use cases. Meanwhile, I will open an issue on Vercel side about supporting deployment with pnpm's lock file.

**Comment by Farenheith** [comment]
@redstrike I fell in a similar problem as you and I'm trying to solve this with a new package.
I just published it and I tested in a few projects with limited scenarios, if someone else could test it so we can find untreated situations, it would be mush appreciated

https://www.npmjs.com/package/anypm

If you can give it a try and open issues for any problem you find, it will be of great help!

**Comment by mjyocca** [comment]
I know this issue is closed but curious of other thoughts/ideas around this particular use case. 

Say you work in a workspace project with multiple packages and a pnpm-lock at the root of the project & you deploy to a serverless environment (aws lambda in this use case) and some of your dependencies cannot be bundled, so you have to resort to using externals. Where your package dependencies are available in the target environment. 

I've gotten around this issue by using npm to install the production dependencies before zipping the build output and node_modules. AWS Lambda NodeJS runtime doesn't support pnpm.

Curious of a safer route to take for this use case.

**Comment by Jack-Works** [comment]
Do you have `npx` in your prod env? You can use `npx pnpm install`

**Comment by mjyocca** [comment]
Majority of the steps I mentioned are through a few packages/plugins I have no control over. 

In lambda nodejs runtime you have to upload your function in a zip along with its package.json & any node modules that are external to your bundle output. Can't really run an extra step to install.

This could be possible with Lambda container image but have not given that a try.

I'm loving pnpm so far and the only issues I keep running into is bundling for a serverless/environment where you have to keep some modules separate.

What would be great, in a workspace/monorepo project, be able to **export** the current package pnpm lock dependencies into a package-lock file for compatibility for the target environment. 

```
/root
  /package-a
  /package-b
  /libs/*
pnpm-workspace.yml
pnpm-lock.yml
```

run
```
cd package-a
pnpm export 
```

and get a package-lock.json file, kind of the inverse of pnpm import

**Comment by ericwooley** [comment]
I needed to convert to package.json, because we are switching away from pnpm. I did this:

```bash
pnpm ls --json > package.extracted.json;
mv package.json package.json.original
node
> const fs = require('fs')
> const pkgJson = JSON.parse(fs.readFileSynce('package.extracted.json'))
> Object.entries(pkgJson.dependencies).forEach(([key, val]) => {pkgJson.dependencies[key] = val.version })
> Object.entries(pkgJson.devDependencies).forEach(([key, val]) => {pkgJson.devDependencies[key] = val.version })
> fs.writeFileSync('package.json', JSON.stringify(pkgJson, null, 2))
> process.exit()

rm -rf node_modules
npm i # now you should have a package-lock.json
mv package.json package.json.exact-packages
mv package.json.original package.json
# cleanup after you are happy
```

**Comment by zkochan** [comment]
Why do you need to switch from pnpm?

**Comment by ericwooley** [comment]
We're just standardizing, and we aren't using any of pnpm's features. Other repos are not using pnpm

**Comment by redwerkz** [comment]
> Currently, `pnpm-lock.yaml` is not supported by many hosting providers (such as Vercel).

Just for the records: [Projects using pnpm can now be deployed with zero configuration](https://vercel.com/changelog/projects-using-pnpm-can-now-be-deployed-with-zero-configuration)

**Comment by akinnee** [comment]
This would be useful for compatibility with tools like https://snyk.io/
