### ISSUE TITLE
pnpm install --prod missing dependency in workspace

### ISSUE THREAD

**Issue by isidrok** [pnpm/pnpm#3006]
### Code to reproduce the issue:

Reproduction repository: https://github.com/isidrok/pnpm-bug-repro

1. Check that the root package.json lists `object-assign` as a `devDependency`
2. Check that packages/foo/package.json lists `object-assign` as a `dependency`
3. Check that `shamefully-hoist=true` is set in `.npmrc`
4. Run the command `pnpm install --prod`
5. Verify that in the root's node_modules folder there is no link to `object-assign`

### Expected behavior:

When using `shamefully-hoist=true` and having the same dependency listed as `devDependency` in the root package of a workspace and in another package as `dependency`, doing `pnpm install --prod` hoist that dependency to the root's node_modules folder.

(That's the behavior I would expect since dependencies are hoisted when they are not set as `devDependency` in the root package, not sure it is the intended behavior though)

### Actual behavior:

When using `shamefully-hoist=true` and having the same dependency listed as `devDependency` in the root package of a workspace and in another package as `dependency`, doing `pnpm install --prod` will not hoist that dependency to the root's node_modules folder but only include it in the package declaring it as a dependency,

### Additional information:

 - `node -v` prints: v14.13.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
I am not sure we should work on this. Hoisting is just a workaround for pnpm, we don't really encourage to use it.

**Comment by isidrok** [comment]
It is a workaround but sometimes necessary and by not working properly requires other workarounds.

I think it should work properly while it's something pnpm supports, even if it's not encouraged.

**Comment by zkochan** [comment]
Just use overrides to add the missing deps: https://pnpm.js.org/en/package_json#pnpmoverrides

**Comment by isidrok** [comment]
Well I'm closing this then, thank you anyway.
