### ISSUE TITLE
Files added into node_modules after "pnpm i 

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [pnpm/pnpm#3009]
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
## Why does my `node_modules` folder use disk space if packages are stored in a global store?

pnpm creates [hard links](https://en.wikipedia.org/wiki/Hard_link) from the global store to project's `node_modules` folders.
Hard links point to the same place on the disk where the original files are.
So, for example, if you have `foo` in your project as a dependency and it occupies 1MB of space,
then it will look like it occupies 1MB of space in the project's `node_modules` folder and
the same amount of space in the global store. However, that 1MB is *the same space* on the disk
addressed from two different locations. So in total `foo` occupies 1MB,
not 2MB.

For more on this subject:

* [Why do hard links seem to take the same space as the originals?](https://unix.stackexchange.com/questions/88423/why-do-hard-links-seem-to-take-the-same-space-as-the-originals)
* [A thread from the pnpm chat room](https://gist.github.com/zkochan/106cfef49f8476b753a9cbbf9c65aff1)
* [An issue in the pnpm repo](https://github.com/pnpm/pnpm/issues/794)

source: https://pnpm.js.org/en/faq#why-does-my-node_modules-directory-use-disk-space-if-packages-are-stored-in-a-global-store

**Comment by Melmoth-the-Wanderer** [comment]
Sorry about the issue, it was a mistake. I didn't mean to publish it. I think my cat must've run on my keyboard :s
