### ISSUE TITLE
update over writing package.json locks

### ISSUE THREAD

**Issue by vorticalbox** [pnpm/pnpm#3012]
### pnpm version: 
5.13.4

### Code to reproduce the issue:
pin a package 
`"mongoose": "~5.10.0",`

run pnpm update

### Expected behavior:

should update package.json to 

`"mongoose": "~5.10.19",` latest 5.10.x at time of writing

### Actual behavior:

`"mongoose": "^5.10.19",` pnpm replaces ~ with ^ which means it no longer pinned to the feature on next update

### Additional information:

 - `node -v` prints: 14.15.0
 - Windows, macOS, or Linux?: linux

**Comment by zkochan** [comment]
Do you have an `.npmrc` file with `save-exact` or `save-prefix` settings?

**Comment by vorticalbox** [comment]
I do not. Do you ahev an example?
