### ISSUE TITLE
cannot read property 'latest' of undefined - pnpm i code-snippet

### ISSUE THREAD

**Issue by GiladShoham** [pnpm/pnpm#3013]
### Code to reproduce the issue:

`pnpm i code-snippet`

### Expected behavior:
getting 404 / not found 

### Actual behavior:
getting `Cannot read property 'latest' of undefined`

### Additional information:

This comes from [here](https://github.com/pnpm/pnpm/blob/main/packages/npm-resolver/src/pickPackageFromMeta.ts#L17

this doesn't happen with other packages that don't exist. only with this. I have no idea what is special about it.

)
 - `node -v` prints: 12.5.0
 - Windows, macOS, or Linux?: mac

**Comment by zkochan** [comment]
Interesting, the registry endpoint actually returns a seemingly malformed JSON file: https://registry.npmjs.org/code-snippet

**Comment by GiladShoham** [comment]
Interesting, I would recommend to catch this weird use case on pnpm code and show a proper error.

**Comment by GiladShoham** [comment]
I guess this is something like a package which were published in the past then unpbulished. (it was allowed in the past, and now it's not allowed but can be done manually by the npm team on request).
probably there are few more packages like this.
