### ISSUE TITLE
feature-request: smarter filter in test command

### ISSUE THREAD

**Issue by idan-at** [pnpm/pnpm#3021]
Hi,

When we run tests with `pnpm`, we use the `...[origin/master]` filter. This basically runs the package tests + all packages that depend on it.

But what if a package only changed a test file? In this case, there's no need to run the dependent tests, since nothing has changed.

The user can provide a regex pattern matching test files, and if all the changed files match this pattern, we can consider this package as it was never changed.

WDYT? I think it can save a lot of time in CI for large monorepos.

**Comment by zkochan** [comment]
Can't you do this with Jest?

**Comment by idan-at** [comment]
> Can't you do this with Jest?

Can you elaborate?


From what I understand, `pnpm recursive test --filter [origin/master]` finds the changed modules using `git`, and runs the test script on the changed modules and its dependents. 

For example, on a monorepo with package `A` which depends on package `B` which depends on package `C`, if any file of `C` was changed, then the test script will be executed for for `A`, `B`, and `C`.

but if only a test file was changed in C, it doesn't really have any effect on B (and therefore no effect on A), so `pnpm` can only run the test script for `C`.

**Comment by zkochan** [comment]
I did not use it yet but as far as I know, Jest has monorepo support and can run only tests upon changed code.

**Comment by zkochan** [comment]
Anyway, I don't have objections but I'd probably use globs instead of regex patterns

**Comment by idan-at** [comment]
can you point me to the relevant places:
- npmrc parsing into flags
- where we build filters (do we have the command accessible there? if not, where can we pass it?)

about the name, `test-path-pattern` ? (inspired by [jest](https://jestjs.io/docs/en/cli#--testpathpatternregex))

**Comment by zkochan** [comment]
Filtering happens here: https://github.com/pnpm/pnpm/tree/main/packages/filter-workspace-packages

Adding a new setting goes here: https://github.com/pnpm/pnpm/tree/main/packages/config
you can look at how "filter" is declared.

**Comment by zkochan** [comment]
:ship: [5.14.0](https://github.com/pnpm/pnpm/releases/tag/v5.14.0)
