### ISSUE TITLE
Feature: Can keep the directories structure like yarn or npm? I get many errors because could not find modules.

### ISSUE THREAD

**Issue by lyne408** [pnpm/pnpm#3022]

**Comment by lyne408** [comment]
We need "NPM NODE_MODULES STANDARD" to prevent some errors like "could not find module".

**Comment by zkochan** [comment]
If you have such errors, try to set `shamefully-hoist=true` in `.npmrc` and run `pnpm install`

pnpm creates a valid node_modules directory. If you need a flat node_modules directory without symlinks, use npm or Yarn.
