### ISSUE TITLE
Issue with "pnpm run nx" (nrwl/cli)

### ISSUE THREAD

**Issue by juliusstoerrle** [pnpm/pnpm#3030]
### Code to reproduce the issue:
Not sure yet, how to reproduce.
Log: https://gist.github.com/juliusstoerrle/3dba6028826626b5b029e6431d95bc5f

### Expected behavior:
Commands are executed without a require problem. In my case the nx command from the @nrwl/nx project in an angular codebase.

### Actual behavior:
When executing `pnpm run nx`, i get the following error.
> Error: Your application tried to access chalk, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

> Required package: chalk (via "chalk")
> Required by: D:\02_HubX\10_Development\hubx-apps\node_modules\.pnpm\@nrwl\cli@10.4.7\node_modules\@nrwl\cli\bin\

> Require stack:
> - D:\02_HubX\10_Development\hubx-apps\node_modules\.pnpm\@nrwl\cli@10.4.7\node_modules\@nrwl\cli\bin\nx.js
    at internalTools_makeError (D:\02_HubX\10_Development\hubx-apps\.pnp.js:25091:34)
    at resolveToUnqualified (D:\02_HubX\10_Development\hubx-apps\.pnp.js:26046:23)
    at resolveRequest (D:\02_HubX\10_Development\hubx-apps\.pnp.js:26144:29)
    at Object.resolveRequest (D:\02_HubX\10_Development\hubx-apps\.pnp.js:26222:26)
    at Function.external_module_.Module._resolveFilename (D:\02_HubX\10_Development\hubx-apps\.pnp.js:25324:34)
    at Function.external_module_.Module._load (D:\02_HubX\10_Development\hubx-apps\.pnp.js:25189:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\02_HubX\10_Development\hubx-apps\node_modules\.pnpm\@nrwl\cli@10.4.7\node_modules\@nrwl\cli\bin\nx.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

Interestingly, I created a new nrwl/nx project in a parallel folder and do not experience the issue there. The lock file versions and hashes of the dependencies (cli, chalk) are the same, as far as I can see the node_modules structure and contents are also the same. (The original project of course has many more dependencies then the new one).

Based on above behavior difference between the projects I decided to open an issue here, as I currently do not believe it's on the side of the @nrwl/cli package. Please let me know how I can further narrow down the issue.

### Additional information:
 - `node -v` prints: v14.15.1
 - Windows (Auch über WSL2 Ubuntu aufgerufen)

I can execute commands of the normal Angular CLI without any issues. This is my first time using pnpm, but I did try several cominations of pnpm configuration options around the hoisting, but nothing seems to help. I did create both projects with the same configuration.

**Comment by Camo30** [comment]
Currently I'm evaluating pnpm as successor of npm and like the issue author I'm also using nrwl/nx in my project. I do not have any problems while executing nx when using these versions:

- `node` 14.15.4
- `pnpm` 5.16.0
- `nrwl/nx` 11.2.11

**Comment by statyan** [comment]
Have you tried to install "chalk" to your package.json dependencies ?

**Comment by juliusstoerrle** [comment]
I have not added chalk as its not a direct dependency of my project. @Camo30 is your nx workspace fairly new or does it exist for more than a year? (Trying to figure out if some update may have gone wrong)

**Comment by Camo30** [comment]
@juliusstoerrle Our nx workspace is about two years old. It has been migrated several times to recent versions.

**Comment by juliusstoerrle** [comment]
Thank you, similar to mine than. It is not an issue with my codebase since it works without issues when I do a git clone inside WSL Ubuntu not, at least with the latest angular version. No idea why this was not working, but it seems to be resolved now.
