### ISSUE TITLE
Installed wrong dependency when install googleapis@39

### ISSUE THREAD

**Issue by siner308** [pnpm/pnpm#3033]
### pnpm version: 

5.13.6

### Code to reproduce the issue: 

```bash
pnpm i googleapis@39
```

### Expected behavior: 

I expected `google-auth-library@3.0.0` must be installed. 

### Actual behavior:

`google-auth-library@3.1.2` was installed

### Additional information:

 - node version `v12.14.1` and `v14.15.1`
 - I'm using `macOS`
 - [googleapis@39 package.json](https://github.com/googleapis/google-api-nodejs-client/blob/v39.2.0/package.json#L11) (39.2.0 actually)

**Comment by alexeyten** [comment]
`^3.0.0` means `>=3.0.0 && < 4.0.0`
so `3.1.2` is perfectly valid

https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

**Comment by siner308** [comment]
I learned one more step about package management. Thank you!!!
