### ISSUE TITLE
--no-bail Doesn't appear to work for pnpm run

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#3036]
### Code to reproduce the issue:

_This may be documentation ambiguity the more I look at it. https://pnpm.js.org/en/cli/run displays `--no-bail`, but it is enclosed within the same brackets as `-r-`. If this doesn't normally work without the recursive flag, it would be immensely useful for it to._

package.json:

```json
"scripts": {
    "fail": "exit 1"
}
```

Run: `pnpm run --no-bail fail`

### Expected behavior:

Process completes without error.

### Actual behavior:

Command fails

### Additional information:

 - `node -v` prints: 14.1.0
 - Windows, macOS, or Linux?: Mac

**Comment by zkochan** [comment]
:ship: [5.14.0](https://github.com/pnpm/pnpm/releases/tag/v5.14.0)
