### ISSUE TITLE
Feature request: automated install of autocompletion

### ISSUE THREAD

**Issue by pdemarino** [pnpm/pnpm#3041]
I use a dockerized development environment, where I automatically install pnpm.

It would be nice if I could invoke `pnpm install-completion` as part of the Dockerfile. Currently that's not possible, as it expects a TTY.

Would it be possible to add CLI parameters to the install-completion module, so that installation proceeds automatically?

**Comment by zkochan** [comment]
We can add the possibility to specify the target shell. For instance, `pnpm install-completion fish`

**Comment by zkochan** [comment]
:ship: 5.15
