### ISSUE TITLE
REMOVE pnpm

### ISSUE THREAD

**Issue by zfranco55** [pnpm/pnpm#3044]
I have installed pnpm with npm, but I can get rid of it completely.
What is the procedure ?
I use Linux Mint 20
i tried uninstall it with: sudo npm unistall -g pnpm, but in a new project it displays me:
 ERROR  command failed: pnpm install --loglevel error --shamefully-flatten

**Comment by zkochan** [comment]
what exactly can't you remove? if you installed pnpm with npm, then `npm uninstall --global pnpm` should work. And you can manually remove the store from `~/.pnpm-store`

**Comment by zfranco55** [comment]
where is .pnpm-store?
I can't find it in my home

**Comment by zkochan** [comment]
If you used pnpm in a non-primary partition, then it will be in the root of that partition, otherwise in the home directory.

**Comment by zfranco55** [comment]
Ok, thanks.
I solved the problem by changing the .vuerc file in home from pnpm to npm

Il giorno sab 26 dic 2020 alle ore 15:25 Zoltan Kochan <
notifications@github.com> ha scritto:

**Comment by zkochan** [comment]
Track https://github.com/pnpm/pnpm/issues/1033 for this

**Comment by mehmeteyupoglu-osf** [comment]
I am having the same issue. When I run the `npm uninstall --global pnpm` it is not removing. Please see the attached image.
![2022-08-09_08h07_32](https://user-images.githubusercontent.com/83695542/183569183-16968a47-e1bd-4592-80b4-3a3785d93689.png)
@zkochan

**Comment by qinhua** [comment]
> I am having the same issue. When I run the `npm uninstall --global pnpm` it is not removing. Please see the attached image. ![2022-08-09_08h07_32](https://user-images.githubusercontent.com/83695542/183569183-16968a47-e1bd-4592-80b4-3a3785d93689.png) @zkochan

I just reinstalled my Operation System，and fixed great
