### ISSUE TITLE
The global installation path in .npmrc is not respected on Linux

### ISSUE THREAD

**Issue by illright** [pnpm/pnpm#3048]
### Code to reproduce the issue:

```bash
mkdir -p ~/.pnpm-global
pnpm config set prefix ~/.pnpm-global
pnpm config set global-dir ~/.pnpm-global
pnpm list -g
```

### Expected behavior:
It should correctly list all packages that are installed globally (or in this case, report that there are none)

### Actual behavior:
```
 ERROR  No write access to the found global executable directories
The found directories:
  /usr/bin
```

### Additional information:

I installed `pnpm` from AUR using `yay`, which means it was likely installed from the superuser

 - `node -v` prints: v15.3.0
 - Windows, macOS, or Linux?: Manjaro Linux, latest

**Comment by Zebradil** [comment]
I have the same issue with pnpm 6.0.2.

**Comment by Theeeus** [comment]
@illright @Zebradil 
Did you have any luck solving this? I have the same issue and can't find a solution anywhere

**Comment by illright** [comment]
No workaround has been found for this, but this issue is for an old version of pnpm and it is no longer affecting me, so I'll close it.
