### ISSUE TITLE
`link` for indirect dependencies

### ISSUE THREAD

**Issue by JasonKleban** [pnpm/pnpm#3049]
Just as an example, I have a sample pnpm-managed repository locally that I would like to work with `ts-node-dev` (typescript watcher and nodemon mashup).  `ts-node-dev` depends on `ts-node`.  I'm trying to debug `ts-node` locally, so I:

* cloned that repo locally, updated the package version to `9.1.2`, and rebuild.  No remaining occurrences of "9.1.1" instead of "9.1.2` in that 
* `pnpm link` in that repo
* `pnpm link ts-node` in my project repo (successful)

When I try to run my project with `ts-node-dev`, it logs that it is still using `ts-node v9.1.1` instead of `ts-node v9.1.2` as I expect.

If I _then_ add

```
  "resolutions": {
      "ts-node": "9.1.2"
  }
```

to my package.json, I'm surprised to get an error during `pnpm install` that `No matching version found for ts-node@9.1.2` even though `pnpm list` shows that indirect dependency `ts-node` in linked to the right local directory.

What of this should have worked, or what step am I missing?

BTW, the `pnpm link` documentation is a little sparse and seems to assume knowledge of `npm link` - especially that you have to run it both directories.  I haven't gotten it all to work yet, but I'm pretty sure that both are critical.

**Comment by zkochan** [comment]
Currently `pnpm link <pkg>` works only for direct dependencies.

**Comment by zkochan** [comment]
@JasonKleban use this resolution:

```json
"resolutions": {
  "ts-node": "link:../../ts-node"
}
```
