### ISSUE TITLE
run command for specific package in workflow AND it dependenc

### ISSUE THREAD

**Issue by georgyfarniev** [pnpm/pnpm#3060]
Hello. I have the following usecase with monorepo:

- Use CI that will rebuild only modified packages (available in GitHub, bitbucket pipelines and git lab ci)
- All packages in monorepo written in typescript
- Packages in monorepo have dependencies to other
- I would like to be able to rebuild modified package and it's dependencies

To achieve it, it would be nice to be able to run some npm command from scripts section of package.json and internal dependencies of this package listed in package.json in appropriate order. Is it possible now? If not, I think it should be easy to implement. Would you consider PR in that case?

**Comment by zkochan** [comment]
Just use TypeScript project references and use pnpm filter changed packages feature: https://pnpm.js.org/en/filtering#filter-lt-since

**Comment by georgyfarniev** [comment]
@zkochan looks like filers is what I need. Will ```

--filter <package_name>^...

```

Respect dependencies order?

**Comment by zkochan** [comment]
yes

**Comment by georgyfarniev** [comment]
Thank you very much, @zkochan
