### ISSUE TITLE
Installing package dependencies in workspace doesn't work

### ISSUE THREAD

**Issue by MKRhere** [pnpm/pnpm#3068]
### Code to reproduce the issue:

```bash
mkdir workspace && cd workspace

echo "link-workspace-packages = true" > .npmrc
echo "recursive-install = true" >> .npmrc

echo "packages" > .pnpm-workspace.yaml
echo "  - 'packages/**'" >> .pnpm-workspace.yaml

mkdir packages
mkdir packages/a
mkdir packages/b
cd packages/a && pnpm init -y
cd ../b && pnpm init -y

pnpm install a@workspace:*
# ERROR  In : No matching version found for a@* inside the workspace
```

### Expected behavior:

Should be able to install per-packages dependencies using pnpm.

### Actual behavior:

Manually adding `"a" : "workspace:*"` to package.json and doing `pnpm i -r` from workspace root does work; but after that trying `pnpm install axios` in `packages/b`, for example, does not work, fails with the same error because we're not in the workspace root. The only way to add dependencies to a single package in the workspace seems to be by editing `package.json`.

However, if we do not have any `"workspace:*"` dependencies in `package/b`, then installing other dependencies works as normally expected.

### Additional information:

 - `node -v` prints: v15.5.1
 - Windows, macOS, or Linux?: Linux, Debian 10.7 (4.19.0-12-amd64)

**Comment by MKRhere** [comment]
It was a mistake on our side, which Zoltan noticed here: https://github.com/pnpm/pnpm.github.io/pull/144#issuecomment-927328242. There should be no dot before `pnpm-workspace.yaml`.

**Comment by devlopersabbir** [comment]
Just use -w flag end of your package name

Like
```console
pnpm add zod -w
```
