### ISSUE TITLE
pnpm audit path

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#3073]
### Code to reproduce the issue:

`pnpm audit` on a package with alerts. e.g. `"ava": "^3.13.0"`

### Expected behavior:

Not necessarily an _expected_ behavior, but a nice to have. I'd like to propose that `pnpm audit` output a path similar to the output for `npm audit`. e.g. 

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ini                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ava [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ ava > update-notifier > latest-version > package-json >      │
│               │ registry-url > rc > ini                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1589                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### Actual behavior:

Dependency audit alerts are displayed without an inherited path. This was something I noticed when working on #3067 that made the location of the offending dependency a little hard to track down.

### Additional information:

 - `node -v` prints: 14.15.3
 - Windows, macOS, or Linux?: MacOS

**Comment by zkochan** [comment]
As a workaround, you may use the `pnpm why <pkg>` command.

For instance, `pnpm why ini`. Works in a monorepo as well via `pnpm why -r ini`. Can accept a version spec as well `pnpm why ini@1`

**Comment by pitgrap** [comment]
Migrating from yarn I recognized the same. 
Switching to the json output, it includes the path. So it would be a nice feature to include it in the default output too.
