### ISSUE TITLE
Install does not use the configured private registry

### ISSUE THREAD

**Issue by stilllife00** [pnpm/pnpm#3086]
### pnpm version:
5.15.1
### Code to reproduce the issue:

I have a custom package to install, to be fetched from a private registry.
I have the .npmrc file in the project folder.

t1$ cat ~/.npmrc
@sitewego/theme1=https://gitlab.com/api/v4/packages/npm/
//gitlab.com/api/v4/packages/npm/:_authToken=XXXX
//gitlab.com/api/v4/projects/XXXX/packages/npm/:_authToken=XXXX

pnpm install

### Expected behavior:
The package @sitewego/theme1 should be fetched from the configured registry and not from registry.npmjs.org

### Actual behavior:
ERROR  GET https://registry.npmjs.org/@sitewego%2Ftheme1: Not Found - 404
@sitewego/theme1 is not in the npm registry, or you have no permission to fetch it.

### Additional information:
node 12.19.0 on Mac OS
npm/yarn install works fine, same problem just by leaving the .npmrc file in the user folder

**Comment by zkochan** [comment]
That is not the correct way to set a registry for a scope.

This is the right way:

```
@sitewego:registry=https://gitlab.com/api/v4/packages/npm/
```

**Comment by stilllife00** [comment]
Thanks for the support and clarification I am still struggling with the configuration of the authToken as a env var.
I get that is more a `.npmrc` topic but I am getting conflicting answers from the docs, stackoverflow and different behaviors between npm, pnpm and yarn, so perhaps you can clarify what should be the good configuration syntax for pnpn.

Case 1:
```
@sitewego:registry=https://gitlab.com/api/v4/packages/npm/
//gitlab.com/api/v4/packages/npm/:_authToken=$NPM_REGISTRY_TOKEN

pnpm install @sitewego/theme tries to fetch from the correct registry but I get a 401 Unauthorized error
An authorization header was used: Bearer $NPM[hidden]

Looks like here the token is not replaced properly ?
```

Case 2 (with brackets)
```
@sitewego:registry=https://gitlab.com/api/v4/packages/npm/
//gitlab.com/api/v4/packages/npm/:_authToken=${NPM_REGISTRY_TOKEN}

pnpm install @sitewego/theme tries to fetch from the wrong registry (it detects a config change, asks first to re-run pnpm install, and uses the wrong registry. It looks like the brackets are a syntax error?)
```

If you could please clarify this it would help a lot to point me to the right direction

**Comment by zkochan** [comment]
with brackets is the right way to do it. So this should work:

```
//gitlab.com/api/v4/packages/npm/:_authToken=${NPM_REGISTRY_TOKEN}
```

**Comment by zkochan** [comment]
Not sure why would it request the package from the wrong registry. Do you use aliases? there a bug with aliases and custom registries: https://github.com/pnpm/pnpm/issues/3103

**Comment by stilllife00** [comment]
Brakets worked indeed thanks. I think the issue was the lack of that environment variable which resulted in pnpm unable to properly substitute the token. That invalidates the whole config and it falls back to the default npm registry. I was wrongly assuming a .env file would suffice, instead now I store my env vars in the .bashrc. Closing this and thanks for the support.

**Comment by zkochan** [comment]
More info added to the docs: https://pnpm.js.org/en/npmrc#registry--authentication-settings

**Comment by haryelramalho** [comment]
Use of @ in front of lib name is necessary? Because, the library name doesn't have the @.

**Comment by matrey** [comment]
(FYI current link is https://pnpm.io/npmrc#registry--authentication-settings )
