### ISSUE TITLE
FAQ wording could be improved

### ISSUE THREAD

**Issue by ocket8888** [pnpm/pnpm#3088]
### pnpm version:

N/A

### Code to reproduce the issue:
N/A

### Expected behavior:
The FAQ says that the package store should be on the same disk *and filesystem* as installations.

### Actual behavior:
The FAQ says that the package store should be on the same "disk" as installations.

### Additional information:

 - `node -v` prints: N/A
 - Windows, macOS, or Linux?: Mostly for the benefit of Linux as Windows treats different file systems as different "disks" - and idc enough about macOS to figure out which metaphor it uses.

Didn't know anywhere more appropriate to bring this up.

Also, note that the Discord server invite in the issue template comments is out-of-date (unless the server no longer exists - couldn't find it on Disboard with search query "pnpm" - in which case it should just be removed)

**Comment by zkochan** [comment]
The discord invite will be fixed next time the site is published
http://bit.ly/pnpm-discord-invite
