### ISSUE TITLE
Incorrect behaviour of `prune --production` command

### ISSUE THREAD

**Issue by ematipico** [pnpm/pnpm#3090]
### Code to reproduce the issue:

- have a package inside `optinalDependencies`
- run `pnpm install --no-optional`
- await installation
- the optional dependencies is correctly NOT installed
- run `pnpm prune --production`

### Expected behavior: 

`pnpm` should not attempt a make a request to an optional dependency that is not installed.

### Actual behavior: 

`pnpm` tries to make a request to the package inside the `optionalDependencies`.

```
Step 38/40 : RUN pnpm prune --production
 ---> Running in 11d2d5c7c643
Lockfile is up-to-date, resolution step is skipped
Packages: -660
--------------------------------------------------------------------------------
Progress: resolved 1, reused 0, downloaded 0, added 0
 WARN  GET npm.pkg.github.com/download/****/****/1.2.0/*** error (ERR_PNPM_FETCH_401). Will retry in 10 seconds. 2 retries left.
 ERROR  GET npm.pkg.github.com/download/****/****/1.2.0/***: Unauthorized - 401
No authorization header was set for the request.

``` 

The reason why there's 403, is because we have an issue in our environment, that's why we decided to move some dep as optional. This is not happening with `npm`

### Additional information:

 - `node -v` prints: v14.7.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
What about `pnpm prune --production --no-optional`?

`--production` means no dev deps. It includes optional deps. Though it shouldn't fail if optional deps have issues.

**Comment by ematipico** [comment]
Oh, do you think it's an npm issue then?? I don't mind opening an issue in their tracker. I will try to use the command you suggested

**Comment by zkochan** [comment]
No, I already did a PR to pnpm #3091

**Comment by ematipico** [comment]
Thank you!! That was really fast!!
