### ISSUE TITLE
[meta] Github issue Discord link invalid

### ISSUE THREAD

**Issue by leaumar** [pnpm/pnpm#3095]
The github issue template refers people to https://discord.gg/mThkzAT for questions. This link is invalid.

Googling got me to the gitter, which in turn links to https://bit.ly/pnpm-discord-invite

Please update the template with the new link.

**Comment by zkochan** [comment]
done https://github.com/pnpm/pnpm/commit/bb93239af2a73e863b3c076beabf6ed1fd47bdc2
