### ISSUE TITLE
CircleCI Integration

### ISSUE THREAD

**Issue by baeharam** [pnpm/pnpm#3100]
I wanna integrate CircleCi with pnpm, but there is no official guide in docs. Only #1648 issue is opened.
Therefore I couldn't solve my problem.

### versioning and private registry

In official guide of pnpm, other CI service uses `znck/pnpm:last` as docker image. However, i**t doesn't use latest version** of pnpm and so compatibility problem could be occurred. I want to keep same version between local and CI.

I used trick to install pnpm which is using npm.

```bash
sudo npm i -g pnpm # in CI container
```

However, it doesn't work when downloading package from private npm registry. (`ERR_PNPM_FETCH_404`) This case didn't occurred with `znck/pnpm`. So, how can I handle this? Requirements are below.

- [ ] Should keep same version with local and CI
- [ ] Should be able to download package from private registry

There are no official docker image for pnpm in docker hub. I hope maintainers give guide for this.

**Comment by statianzo** [comment]
I use the [self-installer](https://github.com/pnpm/self-installer) for CI and it's worked out well.

```
curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=5.16.0 PNPM_DEST="$PWD/.pnpm" node
```

**Comment by zkochan** [comment]
yes, the new way is to use pnpm to install pnpm. `https://pnpm.js.org/pnpm.js` is the dist/pnpm.js file from the pnpm package.

**Comment by baeharam** [comment]
@statianzo Thanks for your guide! I tried second solution. But, it was failed with private registry even if I wrote token into `.npmrc`. 🤔  I cannot find out what is the problem...

**Comment by zkochan** [comment]
Seems related to https://github.com/pnpm/pnpm/issues/3086

**Comment by baeharam** [comment]
@zkochan I checked that issue, but my problem is that impossible to fetch from npm registry. I setup CircleCI like below

```bash
echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
```

Is it wrong configuration? How to solve it?

```
GET https://registry.npmjs.org/@org/some-package/-/some-package-1.0.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
```

**Comment by baeharam** [comment]
@zkochan I think CircleCI configuration should be added to docs? How do you think?

**Comment by zkochan** [comment]
I never had objections to add CircleCI to the docs.

**Comment by baeharam** [comment]
I no longer use CircleCI. So if anyone uses CricleCI with pnpm, please reopen related issue. Thanks.
