### ISSUE TITLE
changes to .npmrc, pnpmfile.js, etc not detected?

### ISSUE THREAD

**Issue by JasonKleban** [pnpm/pnpm#3110]
### Code to reproduce the issue:

I have a hunch but not proof.  Is it possible that making a change like adding to the `hoist-pattern[]` of .npmrc does not get picked up as a change by pnpm?  Pnpm just says 

```
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
```

I think I keep having to delete the lock file and re-`pnpn i` to honor these changes.  Might this even lead to some corruption if unnoticed?

( BTW, there aren't many examples but [it is documented here that multiple string array values are added to .npmrc by repeating the key for each value](https://docs.npmjs.com/cli/v6/configuring-npm/npmrc#files). )

## Update

I'm trying to move to an .npmrc `hoist=false` setup.  This has required me to add a handful of pnpmfile.js hooks:

```
module.exports = {
    hooks: {
      readPackage
    }
}

function readPackage (pkg, context) {
    // This is how we add explicit dependencies when certain packages forgot to
    // do so for themselves

    if (pkg.name === 'lru-cache') {
        pkg.dependencies = {
            ...pkg.dependencies,
            'yallist': '4.0.0'
        }
    }

    ...
```

And even if it's the very first `pnpm i` operation since deleting the pnpm-lock.yaml file, there seems to be some corruption of files already processed to some extent - I'm finding that I'm having to delete node_modules entirely and then I an get a different behavior (hopefully, moving further along).

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/7662
