### ISSUE TITLE
Adding PNPM to package managers

### ISSUE THREAD

**Issue by avi12** [pnpm/pnpm#3112]
It would be handy if PNPM would be available for download via package managers - both on Windows (e.g., [WinGet](../../../microsoft/winget-cli) & [Chocolatey](../../../chocolatey/choco)), macOS (e.g., [Brew](../../../Homebrew/brew)), and Linux (e.g., apt-get).

**Comment by mcmxcdev** [comment]
Adding some links to package managers where pnpm is listed:
- Chocolatey https://community.chocolatey.org/packages/pnpm
- Brew https://formulae.brew.sh/formula/pnpm

Further installation methods are listed at https://pnpm.io/installation

**Comment by russellbanks** [comment]
pnpm is available from winget under the id `pnpm.pnpm`:
```
winget install pnpm
```
