### ISSUE TITLE
Feature request: a new command `pnpm ci` do things like `npm ci` do

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#3113]
It will be very useful to run pnpm on CI environments without figuring out what flags should be set.

**Comment by zkochan** [comment]
You just need to run `pnpm install` on CI. It will configure everything optimally for a CI environment. If we'd make `pnpm ci` it would be just an alias of `pnpm install`.

**Comment by Jack-Works** [comment]
> You just need to run `pnpm install` on CI. It will configure everything optimally for a CI environment. If we'd make `pnpm ci` it would be just an alias of `pnpm install`.

Shouldn't it used with "--frozen-lockfile"?

**Comment by zkochan** [comment]
That setting is automatically set in CI environments if a lockfile is present

https://github.com/pnpm/pnpm/blob/f9befbfb534e4027fd664b335eaf478ee6d890ea/packages/plugin-commands-installation/src/install.ts#L301

**Comment by Jack-Works** [comment]
Cool thanks! Maybe it should be documented more clearly so future people know `install` is already CI ready
