### ISSUE TITLE
[Idea] workspace:^ and workspace:~

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [pnpm/pnpm#3116]
In pnpm there is already one dynamic workspace version alias
- `"foo": "workspace:*"` -> `"foo": "1.1.1"`

What do you think about these aliases?
- `"foo": "workspace:^"` -> `"foo": "^1.1.1"`
- `"foo": "workspace:~"` -> `"foo": "~1.1.1"`

I would find them useful to reduce mismatches and increase the compatibility surface with past versions.

To illustrate the problem that I face with `workspace:*`, let's assume that this has been our release path.

```
foo@1.0.0

bar@1.0.0
  deps: { "foo": "1.0.0" }   # Converted from "workspace:*"
  
foo@1.0.1
```

Now in a third `project` I encounter problems when I consume the latest versions of both packages `foo@1.0.1` and `bar@1.0.0`. If I use a class instance or a symbol from `foo@1.0.1` and pass it to `bar@1.0.0` it will complain that the symbol or class instance is unknown, since `bar@1.0.0` will load `foo@1.0.0` and that is a different package from `foo@1.0.1`.

It's true that this problem could have been avoided with `"foo": "workspace:^1.0.0"` or `"foo": "workspace:~1.0.0"`. But these aliases will run into a conflict sooner or later after a major or minor version is released, while `workspace:^` and `workspace:~` won't.

Also `"foo": "workspace:^1.0.0"` is not automatically reformulated and I think that's dangerous. Let's say I'm writing a patch for `bar@1.2.0` and this package has a dependency on `"foo": "workspace:^1.0.0"`. The dependency on "foo" has not been updated because it's still compatible with version `1.0.0`. The latest `foo` version is `1.8.0`. Since pnpm prefers the workspace version, during development I'm using `foo@1.8.0`. My memory and attention are limited, so when typescript suggests me to use the method `_sumEverything()` I just accept the suggestion without remembering that this method was introduced in `foo@1.4.0`. Theoretically I should have remembered and updated the dependency to `"foo": "workspace:^1.4.0"`, but I know very well that this is unfeasible, people will forget. This would be avoided with `"foo": "workspace:^"`, which would be converted to `"foo": "^1.8.0"` during publishing.

Now someone may say: "both `workspace:^1.0.0` and `workspace:^` are imprecise, since you really wanted `workspace:^1.4.0`". True, but `workspace:^` is always on the safe side while `workspace:^1.0.0` is not.

**Comment by zkochan** [comment]
Interesting idea. What do you think @arcanis?

**Comment by arcanis** [comment]
Sounds like a good idea to me! 👍

**Comment by zkochan** [comment]
This was merged
