### ISSUE TITLE
`pnpm update --interactive` cannot get new packages

### ISSUE THREAD

**Issue by BlackGlory** [pnpm/pnpm#3123]
### pnpm version:
5.16.0

### Code to reproduce the issue:

```sh
$ pnpm update --interactive
All of your dependencies are already up-to-date inside the specified ranges. Use the --latest option to update the ranges in package.json
$ pnpm update
# updated a bunch of packages
```

### Expected behavior:

`pnpm update --interactive` should get the same packages as `pnpm update`.

### Actual behavior:

`pnpm update --interactive` says there are no packages to update, then I have to run `pnpm update`.
The same happens with `--latest`.

### Additional information:

 - `node -v` prints: v14.15.4
 - Windows, macOS, or Linux?: Ubuntu 20.04.1 LTS

**Comment by zkochan** [comment]
Not an issue?

**Comment by BlackGlory** [comment]
I have encountered more strange bugs these days.

I can't believe that pnpm is suitable for production. I am very tired of it and decided to migrate back to yarn.

This interactive option has been added for a while, but I am the first one to report this issue, so maybe it's not a problem for all the other people using pnpm. I decided to close this issue, so that contributors could focus on the other 400+ issues.

**Comment by BlackGlory** [comment]
By the way, when packaging my Node.js project as a Docker image, pnpm uses more space than yarn. I don't know what's going on...

**Comment by zkochan** [comment]
This is the only issue you have opened, what other bugs have you experienced? pnpm does have issues with some stacks but when it works, it works pretty stable and we rarely ship regressions, when we do we fix them fast.

How do you create the dockerfile? By copying node_modules?

**Comment by zkochan** [comment]
Also, in production usually, only `pnpm install` is used. Most of the effort goes into making it stable. And bugs with `pnpm install` are always a high priority. Other commands might be buggier because they have less priority.

**Comment by BlackGlory** [comment]
Just for example: I use `nvm` to install Node.js and use `pm2` to manage several Node.js-based daemons. When I moved the projects of these daemons to other directories (of course, after stopping pm2), I found that the projects were used incorrectly old pm2 binary files, deleting `node_modules` and `pnpm-lock.yaml` cannot solve it.

**Comment by BlackGlory** [comment]
Even `pnpm` is not a good name, the first letters of `yarn` and `npm` can be typed with the index finger, `pnpm` starts with the pinky finger.

**Comment by zkochan** [comment]
pm2 is a dependency of the project? How is it used? Is it called from a package.json script?

> Even pnpm is not a good name, the first letters of yarn and npm can be typed with the index finger, pnpm starts with the pinky finger.

I am not the author of the project name. We can add some alias. That is not hard to do.

**Comment by BlackGlory** [comment]
There are already too many digressions in this issue, I think this issue should be closed. You can create the same issue. If the related issue can be fixed in a short time, then I think more issues are worthwhile.

**Comment by bestickley** [comment]
I'm also experiencing this issue. `pnpm -r up` works but `pnpm -r up -i` says all packages are up to date when they're really not. This used to work, must be a new bug.

```bash
pnpm version
{
  'my-gb-app4-back-end': '0.1.0',
  npm: '8.1.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}```

@zkochan, this is an excellent project. Thank you for your hard work!

**Comment by zkochan** [comment]
`pnpm -r up -i` will only look for the outdated packages in the specified ranges. Try `pnpm -r up -i --latest`

**Comment by bestickley** [comment]
@zkochan, I understand. `pnpm -r up -i` is not updating in the specified ranges of the package.

**Comment by zkochan** [comment]
Do you have a `node_modules` installed? Maybe it doesn't work before a `node_modules` exists.

**Comment by bestickley** [comment]
Yes, I have node_modules installed. It's in a mono-repo.

**Comment by bestickley** [comment]
Example output:
```bash
❯ git status
On branch main
nothing to commit, working tree clean
❯ pnpm -r up -i
Scope: all 4 workspace projects
All of your dependencies are already up-to-date inside the specified ranges. Use the --latest option to update the ranges in package.json
❯ pnpm -r up
Scope: all 4 workspace projects
ui                                       |  WARN  deprecated uuid@3.4.0
ui                                       |  WARN  deprecated uuid@3.4.0
ui                                       |  WARN  deprecated uuid@3.4.0
ui                                       |  WARN  deprecated uuid@3.3.2
ui                                       |  WARN  deprecated uuid@3.4.0
infra                                    |  WARN  deprecated querystring@0.2.0
infra                                    |  WARN  deprecated uuid@3.3.2
ui                                       |  WARN  deprecated uuid@3.4.0
ui                                       |  WARN  deprecated uuid@3.4.0
infra                                    |  WARN  deprecated querystring@0.2.0
ui                                       |  WARN  deprecated uuid@3.4.0
ui                                       |  WARN  deprecated querystring@0.2.0
ui                                       |  WARN  deprecated core-js@2.6.12
.                                        |   +2   -2 +-
Progress: resolved 1350, reused 1330, downloaded 2, added 2, done
 WARN  Issues with peer dependencies found
ui
├─┬ eslint-config-react-app
│ └─┬ eslint-plugin-flowtype
│   ├── ✕ missing peer @babel/plugin-syntax-flow@^7.14.5
│   └── ✕ missing peer @babel/plugin-transform-react-jsx@^7.14.9
└─┬ @aws-amplify/api-graphql
  └─┬ @aws-amplify/api-rest
    └─┬ @aws-amplify/core
      └─┬ @aws-sdk/client-cloudwatch-logs
        └─┬ @aws-sdk/middleware-retry
          └─┬ react-native-get-random-values
            └── ✕ missing peer react-native@>=0.56
Peer dependencies that should be installed:
  @babel/plugin-syntax-flow@^7.14.5          @babel/plugin-transform-react-jsx@^7.14.9  react-native@>=0.56                        
❯ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   infra/package.json
        modified:   package.json
        modified:   pnpm-lock.yaml
        modified:   ui/package.json

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by bestickley** [comment]
You can reproduce creating your own Green Boost repository: https://awslabs.github.io/green-boost/docs/getting-started/installation
