### ISSUE TITLE
pnpm does not seem to work together with tsdx

### ISSUE THREAD

**Issue by peton73** [pnpm/pnpm#3125]
### pnpm version:
5.16.0
### Code to reproduce the issue:
I tried to use tsdx (for trying to create a typescript library) with pnpm/pnpx instead of npm/npx or yarn, 
i.e. replaced npx with pnpx  and replaced yarn with pnpm in the quick start example for tsdx:
https://github.com/formium/tsdx#quick-start
```
pnpx tsdx create mylib
cd mylib
pnpm test
```
### Expected behavior:
It works, i.e. the project was generated and the test could be executed without any failure.
However, even though I used pnpx/pnpm it seemed to have been using npm instead of pnpm, since "node_modules" becomes large as with npm (i.e. the node_modules directory does not contain the hard links you should get from pnpm).

### Actual behavior:
Around 220 MB with normal files in "node_modules" i.e. **not** the so called "[hard links](https://pnpm.js.org/en/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store)" you should get when using pnpm.

### Additional information:
 - `node -v` prints:
     v14.15.4
 - Windows, macOS, or Linux?:
    Windows 10

After the project generation (the above command "pnpx tsdx create mylib") 
I tried to remove the directory "node_modules" and the file "package-lock.json"
and then ran the following command:
`pnpm install`
(which then created a new file "pnpm-lock.yaml")
The output from "pnpm install" resulted in the following warning:

> WARN Failed to find "/fsevents/2.3.2" in lockfile during hoisting. Next aliases will not be hoisted: fsevents

A new "node_modules" directory was created and this time indeed the directory is filled with lots of those pnpm "hard links" instead of the normal files you get when using npm.

But then when trying to run again with "pnpm test" there are lots of errors/failures.

For example, **some** of the first problems:

> jest-haste-map: Haste module naming collision: rxjs/ajax
>   The following files share their name; please adjust your hasteImpl:
>     * <rootDir>\node_modules_original\rxjs\ajax\package.json
>     * <rootDir>\node_modules_original\rxjs\src\ajax\package.json
> ... 
> jest-haste-map: Haste module naming collision: example
>   The following files share their name; please adjust your hasteImpl:
>     * <rootDir>\node_modules_original\tsdx\templates\react-with-storybook\example\package.json
>     * <rootDir>\node_modules_original\tsdx\templates\react\example\package.json
> 
> ts-jest[config] (WARN) Unable to find the root of the project where ts-jest has been installed.
>  PASS  test/blah.test.ts (11.416s)
>  PASS  node_modules_original/cssstyle/lib/CSSStyleDeclaration.test.js
>  FAIL  node_modules_original/gensync/test/index.test.js
>   ● Test suite failed to run
> 
>  Cannot find module 'util.promisify' from 'index.test.js'
> ... 

Is someone else able to use pnpm with tsdx?
Am I doing something wrong?

**Comment by zkochan** [comment]
Have you tried setting `shamefully-hoist=true`?

**Comment by peton73** [comment]
No but I gave up trying to use tsdx

**Comment by leohxj** [comment]
> Have you tried setting `shamefully-hoist=true`?

rushjs install the node_modules in special location `<root>/common/temp/node_modules`, maybe this cause in sub packages, can not found hoist modules?
