### ISSUE TITLE
the dependency in lock file not  installed completely

### ISSUE THREAD

**Issue by HomyeeKing** [pnpm/pnpm#3127]
### lock file
https://github.com/antfu/vite-plugin-components/blob/master/pnpm-lock.yaml

### Expected behavior:
after run `pnpm i`

I think all dependency in lock file should be installed, including the dependency in `example`
### Actual behavior:
only the root one 
### Additional information:

 - `node -v` prints: 15.8.0
 - Windows, macOS, or Linux?: mac

**Comment by zkochan** [comment]
`pnpm install` did not create a `node_modules` directory with symlinks inside the example directory? I could not reproduce this issue.

**Comment by HomyeeKing** [comment]
you mean `pnpm install` in example directory or root?

I think just run  `pnpm install` in root, then I can run example:dev successfully,  is that right?

**Comment by zkochan** [comment]
I was running `pnpm install` in the root and created node_modules in example as well, because it is part of the workspace.

**Comment by HomyeeKing** [comment]
ok, it may be effected by the cache, I always encounter the error before like `esbuild version not match`, but it works fine now

btw, I found the `vscode` directory tree didn't update the `node_modules` after I ran `install` or `remove` command
can you reproduce that?
