### ISSUE TITLE
Display execution time

### ISSUE THREAD

**Issue by BBE78** [pnpm/pnpm#3132]
### pnpm version:
v5.17.1

### Code to reproduce the issue:
any `pnpm` command

### Expected behavior:
display at the end of the command the execution time (such as `yarn` does)

### Actual behavior:
no way to know the command execution time

### Additional information:
 - `node -v` prints: v14.15.5
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
There is already an issue about this https://github.com/pnpm/pnpm/issues/1021
