### ISSUE TITLE
`--filter package^...` does not seem to `excludeSelf` from a package.json script

### ISSUE THREAD

**Issue by JasonKleban** [pnpm/pnpm#3135]
### Code to reproduce the issue:

The calculation in this file seems to me to be correct:

https://github.com/pnpm/pnpm/blob/main/packages/filter-workspace-packages/src/parsePackageSelector.ts

yet, `pnpm all-but-top-most` acts the same as `pnpm all-including-top-most` in that top-most is built too.

```
  "scripts": {
    "all-but-top-most": "pnpm build --filter top-most^..."
    "all-including-top-most": "pnpm build --filter top-most..."
  }
```

Running it from powershell directly as `pnpm build --filter top-most^...` correctly only builds the dependencies and NOT top-most, as expected.

### Expected behavior:

The command line and the package.json script version of the command should behave the same way.  `pnpm all-but-top-most` should not build top-most.

### Actual behavior:

Running it from powershell directly as `$ pnpm build --filter top-most^...` correctly only builds the dependencies.  `pnpm all-but-top-most` builds top-most too, unexpectedly.

### Additional information:

 - `node -v` prints: 14.13.0
 - Windows, macOS, or Linux?: Windows 10

**Comment by JasonKleban** [comment]
Likely because of https://github.com/npm/npm/issues/17692 

Can there be an alternative cross-platform syntax that doesn't involve a problematic escape character?

**Comment by zkochan** [comment]
try

```
  "scripts": {
    "all-but-top-most": "pnpm build --filter \"top-most^...\""
    "all-including-top-most": "pnpm build --filter top-most..."
  }
```

**Comment by JasonKleban** [comment]
Thanks.  Might deserve a mention in the next docs updates.

**Comment by zkochan** [comment]
I recently updated the docs with escapes https://pnpm.js.org/en/filtering

but I did not know that ^ has issues as well.

**Comment by zkochan** [comment]
The double quotes will work on all systems and in all shells
