### ISSUE TITLE
Prepare flag is not installing devDepencies

### ISSUE THREAD

**Issue by galesky** [pnpm/pnpm#3142]
### pnpm version:
Tried with 5.15.1 and 5.17.1

### Code to reproduce the issue:
`pnpm i https://github.com/galesky/rrweb\#test-pnpm`

### Expected behavior:
npm's `prepare` flag states that 

> If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.

So this means the following command using `npm` works as expected (using the reference repo) :
`npm i https://github.com/galesky/rrweb\#test-pnpm`
**Output:**
```
$ npm i https://github.com/galesky/rrweb\#test-pnpm 
npm WARN saveError ENOENT: no such file or directory, open '/mnt/8CCAE44FCAE436DC/Repositorios/galesky/test_install/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/mnt/8CCAE44FCAE436DC/Repositorios/galesky/test_install/package.json'
npm WARN test_install No description
npm WARN test_install No repository field.
npm WARN test_install No README data
npm WARN test_install No license field.

+ rrweb@0.9.14
added 4 packages from 3 contributors and updated 1 package in 34.801s
```

### Actual behavior:
When running the 'same' action with `pnpm` the devDependencies are not installed:

`pnpm i https://github.com/galesky/rrweb\#test-pnpm`
**Oubput:**
```
$ pnpm i https://github.com/galesky/rrweb\#test-pnpm
Packages: +6
++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /mnt/8CCAE44FCAE436DC/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 6, reused 5, downloaded 1, added 6, done
node_modules/.pnpm/github.com/galesky/rrweb@670e5e87f5336dd0b31177node_modules/.pnpm/github.com/galesky/rrweb@670e5e87f5336dd0b31177c8151730f50a0df7cb/node_modules/rrweb: Running prepare script, failed in 157ms
.../node_modules/rrweb prepare$ npm run bundle
│ > rrweb@0.9.14 bundle /mnt/8CCAE44FCAE436DC/Repositorios/gales
│ > rollup --config
│ sh: 1: rollup: not found
│ npm ERR! code ELIFECYCLE
│ npm ERR! syscall spawn
│ npm ERR! file sh
│ npm ERR! errno ENOENT
│ npm ERR! rrweb@0.9.14 bundle: `rollup --config`
│ npm ERR! spawn ENOENT
│ npm ERR! 
│ npm ERR! Failed at the rrweb@0.9.14 bundle script.
│ npm ERR! This is probably not a problem with npm. There is lik
│ npm WARN Local package.json exists, but node_modules missing, 
│ npm ERR! A complete log of this run can be found in:
│ npm ERR!     /home/galesky/.npm/_logs/2021-02-14T19_11_19_903Z
└─ Failed in 157ms
 ERROR  Command failed with exit code 1.
```
Note: I've tried cleaning up the storage (in that example is /mnt/8CCAE44FCAE436DC/.pnpm-store/v3/github) but i get the same error

### Additional information:

I want to use a github Typescript repo that uses a custom bundling process;
In order to run the bundling action i first need to have some devDependencies available, in that case it's `rollup.js` and a couple more.

 - Node v12.17.0
 - DISTRIB_ID=Ubuntu
 - DISTRIB_RELEASE=20.04
 - DISTRIB_CODENAME=focal
 - DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

**Comment by zkochan** [comment]
We have an issue about it already: https://github.com/pnpm/pnpm/issues/855

**Comment by galesky** [comment]
Thanks for linking it, I couldn't find it before. 

I'll take a look at the discussion later and see if I can help
