### ISSUE TITLE
With "type":"modules", pnpmfile.js should be read as ESM (not cjs)

### ISSUE THREAD

**Issue by CxRes** [pnpm/pnpm#3145]
With `"type":"modules"` set in `package.json`, `pnpmfile.js` with ESM code should not throw and instead CJS should throw (or both formats are tolerated). The capability of reading ESM code already exists given that `pnpmfile.mjs` is read without any issues.

### Code to reproduce the issue:

1.  Create a `pnpmfile.js` file with ES modules `export`.
    ```js
    export default {
      hooks: {
        readPackage(pkg) {
          return pkg;
        },
      },
    };
    ```
2. Set in `package.json`
    ```json
    "type": "modules"
    ```
3. Run `pnpm i`

### Expected behavior:

`pnpmfile.js` should be processed, just like `pnpmfile.mjs`.

### Actual behavior 
(file paths sanitized a bit):
```
ERROR  Error during pnpmfile execution. pnpmfile: "~\pnpmfile.js". Error: "Must use import to load ES Module: ~\pnpmfile.js
require() of ES modules is not supported.
require() of ~\pnpmfile.js from C:\ProgramData\nvs\node\14.15.4\x64\node_modules\pnpm\dist\pnpm.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename pnpmfile.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ~\package.json.
".
```

### Additional information:

 - `node -v` prints: 14.15.4
 - Windows, macOS, or Linux?: Windows 10 x64

**Comment by zkochan** [comment]
If I understand correctly the state of ESM in Node.js, pnpm will be able to import an es module only if it will the pnpm CLI will be an es module.

Making the bundled CLI and es module is very hard because we have many dependencies. So there are two way, either use something like babel or only support `pnpmfile.cjs` for now.

**Comment by CxRes** [comment]
I think it might be much simpler than you imagine. If we presume that user e wishing to use ESM is presumably on a version of NodeJS that supports modules, then it is a simple matter putting the `require()` for `pnpmfile.js` in a try-catch, failing which you just use dynamic `import()` to load or throw if `import()` is not supported by the environment. 

If you want to be safer still you can always use a esmodule loader polyfill. Babel is an overkill for this purpose (since you need to support ESM only and not all bleeding edge ES syntax)

**Comment by zkochan** [comment]
For some reason it doesn't work https://github.com/pnpm/pnpm/commit/b768cf4b4376d8c5f4edb099c579bc9c019e9bd6

I think we can for `pnpmfile.mjs` in pnpm v6

**Comment by CxRes** [comment]
@zkochan I checked your commit. It fails because you are importing `import requireOrImport from '../requireOrImport.js'` in `packages/pnpmfile/src/requirePnpmfile.ts` but within `requireOrImports.js` you are using `module.exports`. Use `export default` there instead!

Also, 
```js
return (await import(pnpmfilePath)).default
```

should be:
```js
const result = await import(url.pathToFileURL(pnpmfilePath));
return result.default ? result.default : result;
```

I am putting the full code for the modified file after the failed commit. Please give that another spin. Thanks!

**Comment by zkochan** [comment]
There are too many issues with it. This solution seems to work but I cannot cover it with a test. And after bundling it with esbuild, the import statement is broken, so it doesn't work with the bundled CLI. I suggest proceeding with the commonjs solution suggested in #3149

**Comment by CxRes** [comment]
No problem. Thanks for indulging me!!!

**Comment by danielbayley** [comment]
> only support `pnpmfile.cjs` for now.

@zkochan When is this likely to change?

**Comment by damianobarbati** [comment]
Any news on this? I'm afraid pnpm + ESM + webstorm + debugger is broken due to this pnpm.cjs file being used behind the scenes.
