### ISSUE TITLE
Recommend installation through Volta

### ISSUE THREAD

**Issue by muuvmuuv** [pnpm/pnpm#3146]
I am using [Volta](https://volta.sh/) now for several months, and it's an amazing and superfast alternative to nvm. Even more it can install packages globally directly without using something like `npm --global` through `volta install pnpm`. I think it would be nice to recommend that to users in the installation part of the website; installing Volta for Node version management and pnpm with Volta itself.

What do you think about it?

**Comment by zkochan** [comment]
Volta doesn't seem to support pnpm currently. I see only Yarn in its docs.

**Comment by muuvmuuv** [comment]
I was able to install pnpm through Volta I guess just pinning and choosing a version does not work. Would love those two integrating each other properly :)

**Comment by kamalhm** [comment]
Hi @muuvmuuv do you mind telling me what steps required to able to use pnpm on volta?

**Comment by muuvmuuv** [comment]
@kamalhm sure ^^ you can install every NPM cli tool this way:

```shell
volta install pnpm
```

**Comment by kamalhm** [comment]
@muuvmuuv wait it's that simple? Is this information available in the docs? because I dont think I ever found it

**Comment by zkochan** [comment]
Our current plan is to make pnpm also a Node.js version manager, so it will be basically a replacement to Volta.

See the related discussions:

https://github.com/pnpm/pnpm/discussions/3434
https://github.com/pnpm/pnpm/discussions/3419

**Comment by vnys** [comment]
> @muuvmuuv wait it's that simple? Is this information available in the docs? because I dont think I ever found it

You can’t pin the version though, that’s still not supported as far as I can tell.

**Comment by mikrostew** [comment]
I have an RFC up for adding pnpm support to Volta: https://github.com/volta-cli/rfcs/pull/46, and I welcome any feedback from this community as we work on getting this implemented!

**Comment by muuvmuuv** [comment]
Since pnpm does now support installing different node versions directly, I no longer need Volta and because @zkochan is no longer interested (for reasons, see corepack) I will close this.
