### ISSUE TITLE
pnpm install doesn't get the job done when node_modules is cached by Travis CI

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#315]
I noticed that there were errors of this kind when travis was configured to cache the `node_modules` directory:

```
> node test | tap-spec

module.js:457
    throw err;
    ^

Error: Cannot find module '../tap-spec/bin/cmd.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/rstacruz/pnpm/node_modules/tap-spec/bin/cmd.js:3:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

src: https://travis-ci.org/rstacruz/pnpm/jobs/154566436

Probably not everything is cached and pnpm install doesn't finish the job. From the errors seems like the bin files are not linked.

Edit:
This is probably caused by the same issue: 

```
$ pnpm install --quiet
 ! EINVAL: invalid argument, readlink '/home/travis/build/rstacruz/pnpm/node_modules/istanbul'
```

src: https://travis-ci.org/rstacruz/pnpm/jobs/153994945

Tried to cache just `node_modules/.store` but there were dozens of circular symlink errors

```
adding /home/travis/build/rstacruz/pnpm/node_modules/.store to cache
/home/travis/build/rstacruz/pnpm/node_modules/.store/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d: symlink creates cycle
/home/travis/build/rstacruz/pnpm/node_modules/.store/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es6-symbol/node_modules/d: symlink creates cycle
/home/travis/build/rstacruz/pnpm/node_modules/.store/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es6-symbol/node_modules/es5-ext: symlink creates cycle
/home/travis/build/rstacruz/pnpm/node_modules/.store/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es5-ext: symlink creates cycle
```

src: https://travis-ci.org/rstacruz/pnpm/jobs/154603062

**Comment by rstacruz** [comment]
Maybe just don't cache to begin with? It doesn't help speed up builds much.

**Comment by rstacruz** [comment]
Also, Travis caching is simply uploading node_modules to Amazon S3 (?), and downloading it later. It essence, that's very much like downloading from npm's registry.

**Comment by zkochan** [comment]
Yes, that was my conclusion as well.

* [ ] document that it is not efficient to use travis cache with pnpm
* [ ] maybe even read travis/appveyor yaml and throw an error if caching is used for node_modules

**Comment by iamstarkov** [comment]
> maybe even read travis/appveyor yaml and throw an error if caching is used for node_modules

thats good idea

**Comment by BryanCrotaz** [comment]
We find that downloading node modules (gzipped) from S3 takes seconds rather than minutes for `npm i`
We use shippable.com - caching node modules took 1-2 minutes off the build time

**Comment by zkochan** [comment]
Has to be rechecked with [v0.51.1](https://github.com/pnpm/pnpm/releases/tag/v0.51.1). From v0.51 pnpm doesn't create circular symlinks.

**Comment by zkochan** [comment]
fixed
