### ISSUE TITLE
audit ignores "--prod"/"-P" option

### ISSUE THREAD

**Issue by Liwoj** [pnpm/pnpm#3152]
### pnpm version:
5.17.2

### Code to reproduce the issue:
git clone https://github.com/Liwoj/pnpm-audit.git
pnpm install
pnpm audit --prod
(OR pnpm audit -P)

### Expected behavior:
`node-fetch` package is not listed because it is only dev dependency

### Actual behavior:
`node-fetch` is listed as vulnerability

### Additional information:

 - `node -v` prints: v14.15.5
 - Windows, macOS, or Linux?: Windows 10 x64

**Comment by zkochan** [comment]
:ship: 5.18.2
