### ISSUE TITLE
pnpm publish: false positive "There are no new packages that should be published"

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#3154]
### Code to reproduce the issue:

This is a tough one to explain or provide reproduction for. In a workspace setup, we're running "release notes" scripts using `prepublishOnly`. The goal is to automate release notes, release commits, and release tagging into one command, and the easy target is `pnpm publish`. Using `prepublishOnly` we can do everything we need to before the actual publish is attempted.

Instead, pnpm displays `There are no new packages that should be published` in the console and exits. This appears to be generated here: https://github.com/pnpm/pnpm/blob/249c068dd914b37a6310a7a82be38264aed1ac21/packages/plugin-commands-publishing/src/recursivePublish.ts#L67-L74 and appeared in [5.16.0](https://github.com/pnpm/pnpm/blob/3bf649116154e8fad892b69c2b75366ff2f753ef/packages/pnpm/CHANGELOG.md#5160).

The command we're using is `pnpm publish --filter @scope/name`. We've verified that the scope/name is correct because the same filter works for `pnpm prepublishOnly --filter @scope/name`.

This one is a bit of a show-stopper. 

### Expected behavior:

I'd expect pnpm not to dictate whether or not I should run the publish command.

### Actual behavior:

pnpm inspects (working tree?) to determine wether or not publish should be run.

### Additional information:

 - `node -v` prints: 14.15.3
 - Windows, macOS, or Linux?: MacOS

**Comment by shellscape** [comment]
Looking further, https://github.com/pnpm/pnpm/blob/249c068dd914b37a6310a7a82be38264aed1ac21/packages/plugin-commands-publishing/src/recursivePublish.ts#L60-L65 seems to be the culprit, and doesn't work at all with the workflow we're trying to put together.

An npmrc setting to disable this check would really come in handy

**Comment by zkochan** [comment]
I don't understand this, why don't you run `pnpm prepublishOnly --filter @scope/name` if you don't wan't to publish the packages? If we disable the check, pnpm will attempt to publish everything. It will be slow and each publish will fail with an "version already exists" error from the registry.

**Comment by shellscape** [comment]
> I don't understand this, why don't you run pnpm prepublishOnly --filter @scope/name if you don't wan't to publish the packages?

I think we have our wires crossed here. `prepublishOnly` in our packages perform all of the necessary steps to setup a package for publish: changelog generation, version bump, commiting the version bump, and tagging the commit. Because pnpm won't even allow us to get to that point, we can't run any of our prepublishOnly setup. Given that prepublishOnly is a core lifecycle event and is explicitly for this kind of setup and task running before publish, I'd consider pnpm's behavior a bug without a way to disable the check.

> If we disable the check, pnpm will attempt to publish everything. It will be slow and each publish will fail with an "version already exists" error from the registry.

This is the default behavior of both yarn and npm, so it's reasonable to want the same behavior here. There are situations in which our scripts in prepublishOnly fail for any number of reasons, and we want the publish to fail as well (it will because of the version overwite issue). This is a good thing. I think it's reasonable to ask pnpm to behave in the same way. The convenience of blocking a package publish in the event of an accidental publish request is having unintended consequences. Especially for users that know what they're doing :)

**Comment by zkochan** [comment]
you only need this when filtering for one single package? `pnpm publish --filter @scope/name`

**Comment by shellscape** [comment]
That's the minimum viable case. The usual use case will be using `--filter ...[${{ github.sha }}]` in a Github Workflow for N number of packages.

**Comment by zkochan** [comment]
Would `publish --dry-run` work? `--dry-run` does everything except posting to the registry.

**Comment by shellscape** [comment]
Unfortunately not, because once the tasks in prepublishOnly are complete, we want publish to proceed. While the guard that pnpm had in place, the behavior is unexpected compared to the other package managers. prepublishOnly is explicitly for running tasks _before a publish operation_. I really need to be able to disable pnpm's publish guard so I can use the publish command as per usual.

**Comment by zkochan** [comment]
oh, so you have a script in prepublishOnly that bumps the version of the package?

**Comment by shellscape** [comment]
exactly (and does a few other things as well)

**Comment by zkochan** [comment]
Now I see. We can come up with some workaround for this scenario but it will be pretty slow. pnpm will run all these scripts in each workspace project. If you have hundreds of projects, it will be super slow. It is much more efficient if your tooling will have one script that bumps the version in every project that needs bumping.

**Comment by shellscape** [comment]
Yes, agreed, in the scenario where someone is indiscriminately calling publish recursively that would be very slow. in our use case we are explicitly filtering the packages we want to install. so we have absolute confidence that those the packages that should be installed.

**Comment by zkochan** [comment]
ok, I think we could add something like `pnpm publish --force --filter=blabla`

**Comment by shellscape** [comment]
That would work as well.

**Comment by shellscape** [comment]
thank you!

**Comment by zkochan** [comment]
:ship: 5.18
