### ISSUE TITLE
Non-directory in NODE_PATH

### ISSUE THREAD

**Issue by evanleck** [pnpm/pnpm#3156]
I filed a bug against esbuild recently that the author believes was caused by `pnpx` and its handling of `NODE_PATH`. According to him:

> pnpx inserts a path into NODE_PATH that is actually a file, not a directory.

In short, it appears that `pnpx` adds `node_modules/esbuild/bin/esbuild/node_modules` to the `NODE_PATH` but `node_modules/esbuild/bin/esbuild` is a file, not a directory. This caused esbuild to throw an error because it was not checking that each entry in `NODE_PATH` was a directory. That's now been fixed, but I thought it worthwhile to mention here in case it is a bug worth dealing with.

Here's the full comment on that issue: https://github.com/evanw/esbuild/issues/816#issuecomment-781698863

- pnpm -v: 5.17.2
- npm -v: 7.5.4
- node -v: 14.15.5
- Fedora 33 kernel 5.10.15-200.fc33.x86_64

**Comment by zkochan** [comment]
:ship: 5.18.7
