### ISSUE TITLE
install fails if package url contains port number

### ISSUE THREAD

**Issue by Torvin** [pnpm/pnpm#3182]
### pnpm version:
5.17.3

### Code to reproduce the issue:
I have an private package reference in my `package.json` that looks like this:
`"my-private-package": "http://buildserver.mycompany.com:81/my-private-package-0.1.6.tgz",`

 When I try to do `pnpm i` I get the following error:

`ERROR  ENOENT: no such file or directory, mkdir`

`.pnpm-debug.log` doesn't have any more details:

```
  "5477 error pnpm": {
    "message": {
      "errno": -4058,
      "code": "ENOENT",
      "syscall": "mkdir"
    },
    "err": {
      "name": "Error",
      "message": "ENOENT: no such file or directory, mkdir",
      "code": "ENOENT",
      "stack": "Error: ENOENT: no such file or directory, mkdir"
    }
  }
```

but I'm seeing this in ProcessMonitor:

`CreateFile	C:\Projects\my-app\node_modules\.pnpm\@buildserver.mycompany.com:81@my-private-package-0.1.6.tgz_react-dom@16.14.0+react@16.14.0\node_modules	NAME INVALID`

I believe this happens because on Windows a colon `:` is not allowed in file names

Is there any workaround available?

**Comment by zkochan** [comment]
I think it is easy to fix. I'll look into it.

**Comment by zkochan** [comment]
:ship: 5.18.1
