### ISSUE TITLE
update: choose the correct version of dep

### ISSUE THREAD

**Issue by HomyeeKing** [pnpm/pnpm#3184]
take vue as example:  after running `pnpm up --latest` command, vue is changed to vue@2.x lastest, not the 3.x

it's a issue of vue or `pnpm | yarn | npm` search strategy?

**Comment by zkochan** [comment]
The latest version of vue is 2

3 is the "next" version.

![image](https://user-images.githubusercontent.com/1927579/108688676-da6da280-7500-11eb-8b89-6e708db9780e.png)
