### ISSUE TITLE
[Feature Request] Command to optimize lockfile

### ISSUE THREAD

**Issue by dmichon-msft** [pnpm/pnpm#3187]
I'm looking for a command to `pnpm` that will take a `pnpm-lock.yaml` that has accumulated lots of little changes (e.g. from repeated invocation of `pnpm recursive install --prefer-frozen-lockfile` in a monorepo) and reconfigure it to, without adding any new package versions to the lockfile, optimize the installation layout to prefer the newest versions of each package currently in use.

### Scenario
Imagine there exists a repo with the following:
#### A/package.json
```json
{
  "name": "a",
  "dependencies": {
    "react": "^16.9"
  }
}
```
#### B/package.json
```json
{
  "name": "b",
  "dependencies": {
    "react": "^16.9",
    "event-stream": "^3.3.5"
  }
}
```
Where the `pnpm-lock.yaml` has resolved the `react` specifier to `16.9.0` at the time of installation.

The developer then adds:
#### C/package.json
```
{
  "name": "c",
  "dependencies": {
    "react": "^16.13.1"
  }
}
```
And performs an install with `pnpm recursive install --prefer-frozen-lockfile`, thus adding `react@16.14.0` to the set of known dependencies in the lockfile.

At this point the lockfile now contains `react@16.9.0` and `react@16.14.0`, although a clean install would have only added `react@16.14.0` and used it for all packages.

While deleting the lockfile and performing a fresh install (or using `pnpm update`) would bump all versions of dependencies to latest, it would also have the undesirable side effect of updating unrelated dependencies (the "event-stream" package in this example, which would have introduced the malware version "3.3.6" into the install).

What I am looking for is a command that will take the existing lockfile and optimize it to reduce the total dependency version count, using the same algorithm that would be used for a clean install, but with the set of allowed dependency versions restricted to only those that already exist in the lockfile (as these are known good, approved versions that are already in use in the repository).

### Algorithm
The desired operation can be reproduced exactly by the following steps, though they are a bit cumbersome, and can't be performed on a fresh git clone:
1) Move the pnpm-store metadata cache to a temp directory
2) For each package in the pnpm-store metadata cache, create a new file that contains only the versions that are referenced in pnpm-lock.yaml, and write that file to the original pnpm-store metadata cache
3) Delete pnpm-lock.yaml and all node_modules folders
4) Run `pnpm install --offline` to generate the lockfile

### Goals
Combined with `pnpm install --prefer-frozen-lockfile`, this should result in a world where developers perform minimal shrinkwrap updates to add missing packages in a very traceable manner ("package X was added because the specifier Y in package Z could not be satisfied from the shrinkwrap"), combined with a periodic cleanup job that re-optimizes the lockfile to make more efficient use of the set of accepted dependencies. In practice it might actually make sense to run the lockfile optimizer immediately after the resolution of the aforementioned install.

This combination would have the following properties:
- New package versions only get introduced by developers updating package.json (or possibly pnpmfile.js, directly or indirectly), and thus every added dependency can be traced exactly to a specific developer change to a specifier that brought it into the repo
- Reconciling dependency versions across workspace projects becomes a known safe operation that has no unexpected side effects

**Comment by zkochan** [comment]
I would rather change the install command so that when a developer adds react `^16.13.1`, the reacts of projects a and b are updated to 16.13.1 as well.

Also maybe related #2222

**Comment by dmichon-msft** [comment]
I would find having the new installation footprint after an install be exactly equivalent to the results of the aforementioned operation to be a perfectly acceptable alternative, though it would make changes a little noisier.

It would accomplish the same goal of only bumping versions when expressly required to by an incompatible specifier, essentially updating all compatible specifiers to take advantage of newly added versions immediately?

**Comment by mcmxcdev** [comment]
This is now possible to do with the `pnpm dedupe` command introduced in https://github.com/pnpm/pnpm/releases/tag/v7.26.0
