### ISSUE TITLE
pnpm install on a Git repo uses master by default

### ISSUE THREAD

**Issue by gavinhungry** [pnpm/pnpm#3199]
### pnpm version:
5.17.3 (also tried 5.18.1)

### Code to reproduce the issue:

```sh
pnpm install https://git.my-company.com/org/repo.git # does not work
```

The above only has a `main` branch (no `master` branch). The `main` branch is set to be the default branch, so it's what you get initially when cloning the repository (not sure how this factors in with `pnpm`). It *does* work if specifying `#main`, like:

```sh
pnpm install https://git.my-company.com/org/repo.git#main # does work
```

### Expected behavior:

`pnpm install` should install the module from the configured default branch, rather than `master` being hard-coded.

### Actual behavior:

`pnpm install` fails with:

```
ERROR Could not resolve master to a commit of https://git.my-company.com/org/repo.git
```

### Additional information:

 - `node -v` prints: v15.10.0
 - Windows, macOS, or Linux?: Linux

**Comment by david-fong** [comment]
A reference for how npm implements this can here:
https://github.com/npm/pacote/blob/latest/lib/git.js#L111

**Comment by zkochan** [comment]
:ship: 6.7.2

**Comment by gavinhungry** [comment]
Confirmed working on 6.7.3, thanks!
