### ISSUE TITLE
 Can't resolve '@babel/runtime/regenerator'

### ISSUE THREAD

**Issue by oimmc** [pnpm/pnpm#3214]
### Code to reproduce the issue:
"devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/plugin-syntax-dynamic-import": "^7.7.4",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.7.7",
    "@babel/preset-react": "^7.7.4",
    "address": "^1.1.2",
    "autoprefixer": "^9.7.3",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "cache-loader": "^4.1.0",
    "chalk": "^3.0.0",
    "child_process": "^1.0.2",
    "clean-webpack-plugin": "^3.0.0",
    "cross-env": "^6.0.3",
    "css-loader": "^3.4.2",
    "csv-loader": "^3.0.2",
    "eslint": "^6.8.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.17.0",
    "file-loader": "^5.0.2",
    "html-webpack-plugin": "^3.2.0",
    "image-webpack-loader": "^6.0.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "log-symbols": "^3.0.0",
    "mini-css-extract-plugin": "^0.9.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "os": "^0.1.1",
    "path": "^0.12.7",
    "postcss-loader": "^3.0.0",
    "prettier": "^1.19.1",
    "style-loader": "^1.1.2",
    "thread-loader": "^2.1.3",
    "url-loader": "^3.0.0",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.10.1",
    "xml-loader": "^1.2.1"
  },
  "dependencies": {
    "@babel/plugin-proposal-decorators": "^7.10.5",
    "@babel/polyfill": "^7.8.3",
    "@loadable/component": "^5.11.0",
    "axios": "^0.19.1",
    "classnames": "^2.2.6",
    "html2canvas": "^1.0.0-rc.5",
    "jsencrypt": "^3.0.0-rc.1",
    "mescroll.js": "^1.4.2",
    "moment": "^2.24.0",
    "onfire.js": "^2.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-ga": "^2.7.0",
    "react-router-dom": "^5.1.2",
    "react-transition-group": "^4.3.0",
    "recharts": "^1.8.5"
  },

### Actual behavior:
 Can't resolve '@babel/runtime/regenerator'

### Additional information:

 - node: 12.10.0
 - macOS

**Comment by Nick-Mazuk** [comment]
Check this out: https://pnpm.js.org/en/faq#pnpm-does-not-work-with-your-project-here

**Comment by delanni** [comment]
See my answer at #3215 , this is probably something of a similar nature. But from this little information it's hard to know.

**Comment by Dhentai** [comment]
Tyr add @babel/runtime as a dependency to your package.json.

**Comment by kitsune7** [comment]
Thanks @Dhentai! Adding @babel/runtime as a devDependency in package.json fixed the problem for me.

**Comment by mcmxcdev** [comment]
This ticket can be closed since everything works as expected from pnpm side.
