### ISSUE TITLE
pnpm with vue,This dependency was not found:   regenerator-runtime/runtime.js

### ISSUE THREAD

**Issue by a1245582339** [pnpm/pnpm#3215]
### Code to reproduce the issue:
1. A vue project create by npm
2. remove the node_modules
3. pnpm install
4. npm run serve
![QQ20210302-150643](https://user-images.githubusercontent.com/30924179/109611308-ff998b00-7b68-11eb-89c4-7f29c5a272b5.png)
The pkg regenerator-runtime has been installed in node_modules/.pnpm, but it cannot be found when project running. This pkg be required by node_modules/.pnpm/@vue/babel-preset-app@4.5.11_vue@2.6.12/node_modules/@vue/babel-preset-app/polyfillsPlugin.js, it does not be required by my code. Why the project cannot found this pkg? 

### Expected behavior:
app compiles successfully
### Actual behavior:
This dependency was not found:   regenerator-runtime/runtime.js
### Additional information:
 - `node -v` prints:12.18.4
 - Windows, macOS, or Linux?: macOS
 - vue-cli 4.5.11

**Comment by delanni** [comment]
A `require('regenerator-runtime')` is probably added to your files as a part of `babel`'s `preset-env` transformations. In a `npm`-installed environment, that package would be installed as a transitive dependency, and would be sitting in the flattened `node_modules` directory, so your code would see it.

PNPM is stricter in this sense, you only have access to packages that you declare as dependencies, so you won't have access to `regnerator-runtime`.

You can either add this as a dependency to your package, seeing as how your package's "production runtime" setup requires this package to be available. Or you can [hoist this package](https://pnpm.js.org/npmrc/), so PNPM will link this package to your modules root, so your project, (or any sibling projects in a monorepo setup) would have access to it.

**Comment by mcmxcdev** [comment]
Most likely the situation was exactly what delanni described: pnpm didn't allow the transitive dependency to be used without being installed directly.
