### ISSUE TITLE
pnpm reports deprecation of package's dev dependencies that are not installed

### ISSUE THREAD

**Issue by muuvmuuv** [pnpm/pnpm#3225]
### Code to reproduce the issue:

```
pnpm add -D eslint-plugin-react
```

### Expected behavior:

Does not print deprecations of `eslint-plugin-react` dev dependencies.

### Actual behavior:

Print deprecation warning for babel-eslint

### Additional information:

 - `node -v` prints: 14.x
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
This doesn't seem to happen with the latest pnpm.
