### ISSUE TITLE
In monorepo, when package is not found, `node_modules` will be created in the directory that pnpm is run from instead of monorepo root

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#3226]
![Screen Shot 2021-03-16 at 3 02 49 pm](https://user-images.githubusercontent.com/281413/111321952-b79a5e00-8668-11eb-8a56-81e997108680.png)

### Code to reproduce the issue:

See: https://github.com/vjpr/issue-pnpm-package-not-found

### Additional information:

 - `node -v` prints: 14.2
 - Windows, macOS, or Linux?: macOS

**Comment by autumnblazey** [comment]
can reproduce on windows and linux (ubuntu) c:

**Comment by zkochan** [comment]
Makes sense to me but seems like a breaking change. Probably in v6 we can make this change.

**Comment by zkochan** [comment]
but we for sure don't need to create a new node_modules to write the log file. This we can fix in pnpm v5
