### ISSUE TITLE
"Update available!" banner shows non-working advice on how to update pnpm

### ISSUE THREAD

**Issue by rulatir** [pnpm/pnpm#3227]
### pnpm version:

5.17.2

### Code to reproduce the issue:

1. Run any pnpm command as regular user.
2. Run the suggested upgrade command `pnpm i -g pnpm` verbatim as the same user in the same shell.
3. Run `pnpm -v`.

### Expected behavior:

2. Successful update.
3. `5.18.4` (at the time of this writing)

### Actual behavior:

2. Update fails with `ERROR  EACCES: permission denied, open '/usr/bin/pnpm'`
3. `5.17.2`

Either the "Update available!" banner should suggest an upgrade command that will actually work, or the command should be fixed to actually work. Having pnpm installed globally is a non-exotic setup. Running it as a regular user is a non-exotic practice. These should be supported.

### Additional information:

 - `node -v` prints: v15.11.0
 - Linux

**Comment by zkochan** [comment]
It will be fixed in pnpm v6

https://github.com/pnpm/pnpm/pull/3213

**Comment by rulatir** [comment]
In the interim, **what** is the exact **working** incantation to self-update a globally-for-all-users installed `pnpm`?

**Comment by zkochan** [comment]
you can try to install pnpm with npm
