### ISSUE TITLE
ERROR  ENOENT: no such file or directory, copyfile

### ISSUE THREAD

**Issue by whenjs** [pnpm/pnpm#3229]
ERROR  ENOENT: no such file or directory, copyfile 'G:\.pnpm-store\v3\files\7f\188a9f33488e2f925682fff6cc2d5ec7c6face60dc5c59ef3662fa00f11d1f327ee44167904f4ed2c3a22ff0974fe331a4e9510680d2858da08dc7bf19d86f' -> 'G:\viz\std-3d-charts\node_modules\.pnpm\jsdom@0.2.9\node_modules\_tmp_33624_ce6506f720dd13db6952d1f74e1841d1\test\level3\core\files\orig\index.html?C=D;O=A'
at pnpm\jsdom
Progress: resolved 710, reused 0, downloaded 710, added 661

pnpm --version
5.18.3
node -v
v12.18.3 windows 10

**Comment by whenjs** [comment]
It's no use reinstall by deleting node_modules and G:\.pnpm-store

**Comment by zkochan** [comment]
`?` is not a valid character for a file name in Windows, that is why it fails. Seems like npm is escaping the `?` symbol when unpacking a package on Windows. We should probably do the same, though I am not sure what sanitizer they use.

**Comment by zkochan** [comment]
:ship: 5.18.6

**Comment by vasco3** [comment]
having this issue in v7.1.3

**Comment by zkochan** [comment]
In that case create an issue with steps to reproduce.

**Comment by vasco3** [comment]
I fixed it by deleting the store folder
`rm -rf /Users/jc/Library/pnpm/store/v3/files/78`

**Comment by rdsedmundo** [comment]
Also having this issue after upgrading to v7. I have no idea how to reproduce it though... it works again by nuking the whole store and re-downloading everything.

```
 ENOENT  ENOENT: no such file or directory, copyfile '/Users/work/.pnpm-store/v3/files/68/fd2865a3cee2a68927ffed7c54667b1b3b03710b6a174ad45caa8e05f2e033b51e6d6f55ab22d8207f2fdb286c9dd057cb43171aa793ce9f180da8d7653e6e' -> '/Users/work/redacted/redacted/node_modules/.pnpm/fsevents@1.2.13/node_modules/_tmp_10595_695eb2b63757fc332de5b4c217d64f1d/build/.target.mk'
```

**Comment by gnohj** [comment]
running `pnpm store prune` should fix this

**Comment by BTBMan** [comment]
I have the same issue in v7.3.0

**Comment by bahtou** [comment]
what worked for me was removing two folders:
1. @vasco3 recommendation
2. node_modules

**Comment by rdsedmundo** [comment]
Just faced this again:
```
ENOENT  ENOENT: no such file or directory, copyfile '/Users/work/.pnpm-store/v3/files/4f/c8d1b5a58de08015c783eebc5cbf33d1fd321e21b9664875184ca6df2ac3675d9d1484c79c465a5b9bbc5e64683d8713e41f720ab8a3428794b77b74e23d3f' -> '/Users/work/project/node_modules/.pnpm/fsevents@1.2.13/node_modules/_tmp_4857_5ccadbae63e05a28c386956387c3200e/build/Makefile'
```

It's unfortunate that pnpm has gotten more unstable on the last two major versions or so with those random errors, as this was one of the biggest selling points compared to npm and yarn.

**Comment by zkochan** [comment]
These issues are unrelated to the original issue, which was fixed. You should create a new issue.

**Comment by zkochan** [comment]
New issues #4997
