### ISSUE TITLE
concurrent installs from different directories of the same project yield symlink error

### ISSUE THREAD

**Issue by cdaringe** [pnpm/pnpm#3233]
### Code to reproduce the issue:

I have a project that gets mounted in parallel by jenkins on the same computer, but in different directories. Both jenkins threads call `pnpm install`. I keep observing that on computers that have multiple processes running installation concurrently, that they both ERROR out.

Here's stdio + timestamps from two processes:

Process1
```txt
13:40:55 + pnpm install --ignore-scripts
13:40:57 Using hooks from: /path/to/pnpmfile.js
13:40:57 Lockfile is up-to-date, resolution step is skipped
13:40:57 Progress: resolved 1, reused 0, downloaded 0, added 0
13:40:59 Packages: +3929
13:40:59 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
13:40:59 Progress: resolved 3929, reused 0, downloaded 0, added 0
13:40:59 Progress: resolved 3929, reused 1, downloaded 0, added 0
13:41:38 Progress: resolved 3929, reused 2, downloaded 0, added 0
13:41:38  ERROR  EEXIST: file already exists, symlink '../../../utils@6.2.4_graphql@15.3.0/node_modules/@graphql-tools/utils' -> '/mnt/jenkinspan/workspace/walmart-web/walmart-web-experiment-dedocker/ws/node_modules/.pnpm/@graphql-tools/schema@6.2.4_graphql@15.3.0/node_modules/@graphql-tools/utils'
```

Process2
```txt
13:41:00 + pnpm install --ignore-scripts
13:41:10 Using hooks from: /path/to/pnpmfile.js
13:41:10 Lockfile is up-to-date, resolution step is skipped
13:41:10 Progress: resolved 1, reused 0, downloaded 0, added 0
13:41:10 Packages: +3929
13:41:10 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
13:41:10 Progress: resolved 3929, reused 0, downloaded 0, added 0
13:41:38 Progress: resolved 3929, reused 1, downloaded 0, added 0
13:41:38  ERROR  EEXIST: file already exists, symlink '../../../hoek@8.5.1/node_modules/@hapi/hoek' -> '/mnt/jenkinspan/workspace/walmart-web/walmart-web-experiment-dedocker/ws/node_modules/.pnpm/@hapi/boom@7.4.11/node_modules/@hapi/hoek'
13:41:38 at 11/node_modules/  
```

### Expected behavior:

lock/mutex, or permit concurrency

### Actual behavior:

crash with EEXIST

### Additional information:

 - `node -v` prints: 14.15.1
 - Windows, macOS, or Linux?: linux, centos

**Comment by zkochan** [comment]
Are you sure different directories are used? Why is the symlink pointing to the same directory in both processes? `/mnt/jenkinspan/workspace/walmart-web/walmart-web-experiment-dedocker/ws`

**Comment by zkochan** [comment]
also, please include the stack trace if it is printed.

**Comment by cdaringe** [comment]
Yes, I owe it to you to clarify. I may have pasted the wrong output. I will re-open with more robust output when ready.

Thanks for the input.

**Comment by cdaringe** [comment]
i still cannot reproduce out of a private setting. even creating a worst-case attempt still seems to pass. very feasibly could be postinstall scripts from some package meddling. here's an example of an aggressive race, still succeeding (for more than anything, a breadcrumb, next time i crash into this):

```bash
set -exo pipefail
suffix=$(date +%s)
root=/tmp/pnpm-test-$suffix
dir=$PWD

function prepareDemoApp () {
  mkdir -p $root/$1
  cd $root/$1
  git init
  npm init -y
  pnpm add debug prop-types jest express koa next sharp node-sass level
  rm -rf node_modules
  rm -rf .git
}

function install() {
  cd $root/$1
  pnpm install --verbose
}

rm -rf $root
prepareDemoApp a
cd $dir
cp -r $root/a $root/b

install a &
install b &

wait
```
