### ISSUE TITLE
pnpm find wrong bin version when multiple esbuild version exists

### ISSUE THREAD

**Issue by hardfist** [pnpm/pnpm#3238]
### pnpm version:
5.17.3
### Code to reproduce the issue:
https://github.com/hardfist/neo-tools/tree/add-less
$ pnpm install
$ cd packages/playground && pnpm run build

you can also view vercel log here https://vercel.com/hardfist/neo-tools/BQmhzVcPDcULB3Xutd3FScuvRj5D

### Expected behavior:
not throw error
### Actual behavior:
![image](https://user-images.githubusercontent.com/8898718/111013911-49416b80-83dc-11eb-99f0-c3d2056e47d4.png)

![image](https://user-images.githubusercontent.com/8898718/111013487-9290bb80-83da-11eb-9e2c-647819daf7f8.png)

### Additional information:
node: 15.10.0
macOS: macos bigsur 11.11 , apple m1

**Comment by zkochan** [comment]
Is it the same as https://github.com/pnpm/pnpm/issues/3156?

**Comment by hardfist** [comment]
I don't think it's the same problem

**Comment by hardfist** [comment]
I think it may be related to post-install scripts

**Comment by zkochan** [comment]
You have to versions of esbuild in the monorepo. Seems like they hard link a similar file from the content-addressable store but then one of them modifies it and it gets modified for both.

You could either force one esbuild version or use

```
pnpm i --package-import-method copy
```

**Comment by hardfist** [comment]
> h copies the

how can I tell if I force hardlinks?

**Comment by zkochan** [comment]
Did you set a different value to the [package-import-method](https://pnpm.js.org/npmrc/#package-import-method) setting?

**Comment by hardfist** [comment]
no, I didn't

**Comment by zkochan** [comment]
What happens if you run `rm -rf node_modules && pnpm i --package-import-method=clone` ?

**Comment by hardfist** [comment]
![image](https://user-images.githubusercontent.com/8898718/111035472-bc3af880-8455-11eb-86a3-9acc9384ec61.png)

**Comment by zkochan** [comment]
OK, I don't understand why cloning doesn't work on your Mac but I guess we can do nothing about it.

Seems like your best bet currently is to use a single esbuild in your workspace. We could also ask esbuild to build their files into separate files, not mutate existing ones.

In the long run, we might need to work on some side-effects storage in the pnpm global storage. As a fast fix, maybe we could just copy (not link) any packages that are built.

**Comment by hardfist** [comment]
`--package-import-method=clone` not working but `--package-import-method=copy` works

**Comment by hardfist** [comment]
I remember why clone failed, becaues of node's bug referenced at #2879

**Comment by desmap** [comment]
@hardfist what's the use case for having multiple versions of esbuild?

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/4898
