### ISSUE TITLE
pnpm does not work with a socks proxy

### ISSUE THREAD

**Issue by ufleisch** [pnpm/pnpm#3241]
### pnpm version:
5.18.6

### Code to reproduce the issue:

In ~/.npmrc:
```
registry=https://your-registry
proxy=socks://your-proxy
```

Then run `pnpm i your-package`

### Expected behavior:
Package is installed.

### Actual behavior:
 WARN  GET https://your-registry/your-package error (EAI_AGAIN). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://your-registry/your-package error (EAI_AGAIN). Will retry in 1 minute. 1 retries left.

### Additional information:

 - `node -v` prints: v12.21.0
 - Windows, macOS, or Linux?: Linux

When the registry uses the https protocol and the proxy uses socks, its URL is changed from "socks://" to "https://socks://" in `getProxyUri()`, which will not work. This could be fixed using

```
diff --git a/packages/npm-registry-agent/src/index.ts b/packages/npm-registry-agent/src/index.ts
index 57dad6a92..3af1bee94 100644
--- a/packages/npm-registry-agent/src/index.ts
+++ b/packages/npm-registry-agent/src/index.ts
@@ -125,7 +125,7 @@ function getProxyUri (
     return null
   }
 
-  if (!proxy.startsWith('http')) {
+  if (!proxy.startsWith('http') && !proxy.startsWith('socks')) {
     proxy = protocol + '//' + proxy
   }

```

**Comment by zkochan** [comment]
:ship: 5.18.7

**Comment by ufleisch** [comment]
Thank you very much for this exceptional and fast support!
