### ISSUE TITLE
RenovateBot doesn't update pnpm-lock.yaml

### ISSUE THREAD

**Issue by aminya** [pnpm/pnpm#3243]
Mirrored from https://github.com/renovatebot/renovate/issues/8323#issuecomment-798822838

Because this is a high-priority issue for pnpm and not Renovate, I mirrored that issue here.

### Code to reproduce the issue:

I also have this issue. A reproduction is available in this repository:
https://github.com/AtomLinter/linter-eslint

The error I get:
https://github.com/AtomLinter/linter-eslint/pull/1406#issuecomment-798822175

I use the following in my .npmrc
```js
public-hoist-pattern[]=*
package-lock=false
lockfile=true
prefer-frozen-lockfile=false
```

The relevant part of the renovate config:
```json
{
  // I tried with or without this
  "postUpgradeTasks": {
    "commands": ["pnpm install"],
    "fileFilters": ["pnpm-lock.yaml"]
  }
}
```

The full config is here:
https://github.com/AtomLinter/linter-eslint/blob/master/.github/renovate.json

### Expected behavior:
Update the lock file 

### Actual behavior:
Errors:

### :warning: Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

:recycle: Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you check the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: pnpm-lock.yaml

```

```

### Additional information:

 - `node -v` prints: Renovate's Node
 - Windows, macOS, or Linux?: Renovate's OS

**Comment by kamilic** [comment]
any resolutions?

**Comment by aminya** [comment]
The workaround is to add a `pnpm-workspace.yaml` file. It seems that Renovate only works for workspaces!

```yaml
packages:
  - "."
```

**Comment by kamilic** [comment]
`pnpm-workspace.yaml` works fine, but pnpm workspace mode is not suitable for my project. : (

**Comment by kamilic** [comment]
@aminya I noticed your comment on renovate issues#8323. It was fixed?  Does It work without `pnpm-workspace.yaml`?
Which version you use fixed this issue? 

> I updated the repo. It seems the issue has been fixed recently by other means. This was not the case at [this time](https://github.com/renovatebot/renovate/issues/8323#issuecomment-862800413)

**Comment by mihaicozma** [comment]
I made a test project,  
https://github.com/mihaicozma/RenovateTest/pull/5

running on ubuntu-latest works fine and pnpm-lock was update properly

**Comment by mcmxcdev** [comment]
Thanks for the repo, we are also using renovate together with pnpm without any issues for multiple months, closing.
