### ISSUE TITLE
`pnpm recursive install` stuck in a loop

### ISSUE THREAD

**Issue by arggh** [pnpm/pnpm#3245]
### Code to reproduce the issue:

`pnpm recursive install`

### Expected behavior:

pnpm installs packages and finishes.

### Actual behavior:

I realize that debugging this without a proper repro is going to be a pain. We have a monorepo with lots of packages. They used to be set as "peerDependencies" and installed by the apps that used those packages. As we switched over to pnpm, we started to use workspaces and moved all "peerDependencies" over to "dependencies" and set the package version to "workspace:*".

Then, running `pnpm recursive install` from the monorepo root runs for a while, until the process gets stuck in a loop that pretty much hijacks all cpu %. I waited a good amount of time until interrupted.

```
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 134, reused 21, downloaded 113, added 134, done
. install$ pnpm recursive install
[2078 lines collapsed]
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
│ . install: . install: . install: . install: . install: . install: . install: . install: . install: . inst
└─ Running...
	^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

```
pnpm-workspace.yaml:
-------
packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
```

### Additional information:

 - `node -v` prints: v15.10.0
 - Windows, macOS, or Linux?: MacOS 11.2.2 (M1)

**Comment by arggh** [comment]
I think it was related to the [project root package.json being included in the recursive command](https://github.com/pnpm/pnpm/issues/2769) (sorry, I'm just dipping toes into pnpm).

My project root's package.json looked like this:

```

{
  "name": "my-packages",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "install": "pnpm recursive install",
    "build": "pnpm recursive build"
  }
}
```

If I removed the `install` script from `package.json` and instead run the command `pnpm recursive install` directly, the install went smoothly.

**Comment by Tate-Young** [comment]
一毛一样，的确去掉 install 脚本就好了

　　　∩∩
　　（´･ω･）？？？
　 ＿|　⊃／(＿＿_
　／ └-(＿＿＿_／

**Comment by thynson** [comment]
I think it's not a bug of pnpm.

**Comment by arggh** [comment]
> I think it's not a bug of pnpm.

Me neither.
