### ISSUE TITLE
Forbid executing of not installed packages with `pnpx xxxx`

### ISSUE THREAD

**Issue by wclr** [pnpm/pnpm#3249]
**Describe the user story**

`pnpx xxxx` if `xxx` not available pnpm tries to download `xxxx` package and execute it. It is a potentially insecure operation also it is quite unexpected in most cases.  Currently, it is not possible to forbid executing commands from not-installed packages.

**Describe the solution you'd like**
There should be an explicit global config option and cli flag to enable desired behaviour.

Generally, I would NOT execute such a case by default. Though it is kind of BREAKING.

**Comment by zkochan** [comment]
we can do it in v6. npm did this change in npm v7
