### ISSUE TITLE
support `pnpm init <@scope>` and `pnpm init [<@scope>/]<name>`

### ISSUE THREAD

**Issue by milahu** [pnpm/pnpm#3252]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

npm@6 has this syntax sugar:

```
$ npm init --help

npm init [--force|-f|--yes|-y|--scope]
npm init <@scope> (same as `npx <@scope>/create`)
npm init [<@scope>/]<name> (same as `npx [<@scope>/]create-<name>`)

aliases: create, innit
```

so instead of `npx create-solid` i can call `npm init solid`

currently, pnpm passes all init commands to npm
so when i call `pnpm init solid`, npm will install and run `create-solid`

**Describe the solution you'd like**

pnpm should handle the extended `init` command

**Alternative solutions**

call `pnpx create-solid`

edit: `pnpx create-solid` will still [call](https://github.com/ryansolid/create-solid/blob/801ba7e1d91800d5ef598463f2ae885f99789f2b/createSolid.js#L315) `npm` to install its dependencies : /

**Comment by autumnblazey** [comment]
support!

tho I want to say `pnpx create-solid` installing its dependencies with `npm` is on the `create-solid` package so maybe raise that issue with them

**Comment by milahu** [comment]
> maybe raise that issue with them

done in https://github.com/solidui/create-solid/pull/5

**Comment by milahu** [comment]
the "create-solid calls npm install" issue is solved by

```
mkdir my-app
cd my-app
pnpx create-solid@next # npm init solid@next
pnpm install # npm install
npm run dev
```

**Comment by zkochan** [comment]
This is now supported via the [pnpm create](https://pnpm.io/cli/create) command. It is not an alias of init. So we use the same approach as Yarn, we have a separate `pnpm init` command for generating a `package.json` and a `pnpm create`.
