### ISSUE TITLE
`pnpm m ls webpack` hangs my terminal

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#3255]
### pnpm version: 5.18.7

On a large monorepo with 100s of packages, this command hangs my terminal and after pressing `ctrl+c` it takes ages to respond.

This command used to work fine with not problems.

Is there a way to debug? I tried: `pnpm m ls webpack --loglevel=trace --reporter=ndjson`

### Additional information:

 - `node -v` prints: 14.2.0
 - Windows, macOS, or Linux?: macOS

**Comment by mcmxcdev** [comment]
Can you still reproduce this with pnpm v7 ?

The command takes less than a second on my end.
