### ISSUE TITLE
noproxy config are not present in config after getConfig

### ISSUE THREAD

**Issue by GiladShoham** [pnpm/pnpm#3258]
### Code to reproduce the issue:

run `npm config set noproxy='my-domain'`
use getConfig something like
```js
import getConfig from '@pnpm/config';

export async function readConfig() {
const pnpmConfig = await getConfig({})
```
print the following
```js
pnpmConfig.config.noProxy => undefined
pnpmConfig.config.rawConfig.noproxy => my-domain
```

### Expected behavior:
pnpmConfig.config.noProxy should be `my-domain`

### Actual behavior:

it's undefined

### Additional information:

 - `node -v` prints: 12.15.0
 - Windows, macOS, or Linux?: macos

**Comment by zkochan** [comment]
:ship: 5.18.8
