### ISSUE TITLE
Error on non used optional dependency when using pnpm import

### ISSUE THREAD

**Issue by Farenheith** [pnpm/pnpm#3263]
### Code to reproduce the issue:

```
git clone git@github.com:Codibre/fluent-iterable.git
cd fluent-iterable
pnpm import
pnpm install
```

### Expected behavior:
I expect pnpm to install all the dependencies properly, as ```npm i``` would.

### Actual behavior:
I got the following error:
```
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/thiago/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 527, reused 527, downloaded 0, added 527, done
 WARN  Failed to find "/fsevents/2.3.2" in lockfile during hoisting. Next aliases will not be hoisted: fsevents
 ERROR  EISDIR: illegal operation on a directory, read
```

### Additional information:
It looks like a **pnpm import** problem, as, if I just use **pnpm install** everything works fine

 - `node -v` prints: v10.24.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
Smaller reproduction:

```
pnpm add @codibre/confs@0.0.6
```

This error happens because sinon-chai-calls-assertion has a bin directory field and the bin directory has a directory.
npm seems too link all files from all subdirectories in this case. Although this seems like a bug in the sinon-chai-calls-assertion, we will make pnpm work similarly to npm

**Comment by Farenheith** [comment]
Thank you for your feedback, and your willingness to fix it, even though the error occurs because of a bug in another library.
Sorry I couldn't figure out the cause of the bug before, I'll take a look into this too to fix it in the lib too

**Comment by Farenheith** [comment]
@zkochan I fixed it in sinon-chai-calls-assertion, with this change
https://github.com/Farenheith/sinon-chai-calls-assertion/commit/aaa856f63aba255f0545be7e6b1469405d2191a2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

It was really an unneeded set, and my problem was solved, I just want to inform you of two details I noticed that I found odd:
* According to [npm docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#directoriesbin), directories.bin must be a directory, so, in this case of use, the property was misused, but the value was okay;
* sinon-chai-calls-assertion was a devDependency of confs, so, I think it shouldn't interfere when installing confs in another project;

I hope this help somehow!

Thank you!

**Comment by zkochan** [comment]
I see sinon-chai-calls-assertion in the prod dependencies of `@codibre/confs@0.0.6`

**Comment by Farenheith** [comment]
> I see sinon-chai-calls-assertion in the prod dependencies of `@codibre/confs@0.0.6`

I see, you're right.

Sorry for the confusion

**Comment by zkochan** [comment]
:ship: 5.18.8

**Comment by Farenheith** [comment]
Hello!

@zkochan I'm having the same error again on 6.0.2 but not sure if is the same package
```ts
 ERROR  EISDIR: illegal operation on a directory, read
```
Could you teach me a way to detect which package is causing the problem? Like, idk, there is some debug option that shows the package name who caused the error? I tried --reporter ndjson but it didn't help much

**Comment by zkochan** [comment]
Yes, `--reporter ndjson` is the way. If it doesn't provide you with the needed info, then we don't have such logs now.

**Comment by Farenheith** [comment]
@zkochan thank you. I'll take a deeper look into it
