### ISSUE TITLE
How to silence fsevents warning on linux?

### ISSUE THREAD

**Issue by adamburgess** [pnpm/pnpm#3267]
` WARN  Failed to find "/fsevents/2.3.2" in lockfile during hoisting. Next aliases will not be hoisted: fsevents`
<img alt="pnpm warning" src="https://i.imgur.com/rof7mAR.png"/>

**Assuming this is a warning about fsevents not installing because it is an optional dependency that isn't compatible with linux:**
(otherwise, bug report for this warning, then?)

Older versions of npm used to show a similar warning, but in [npm v7](https://github.com/npm/cli/pull/169#issuecomment-667304732) this warning was removed.

I would like to silence this warning. Best case scenario I would love to see no indication that fsevents was skipped.
This warning adds noise to _every single add/remove/install command_. I tried [pnpm.neverBuiltDependencies](https://pnpm.js.org/package_json#pnpmneverbuiltdependencies) but that didn't seem to help.

I used to use yarn, and in that you still get the warning, but there it is an `info`, and much more subdued.

<img alt="yarn info" src="https://i.imgur.com/ocPPwsJ.png"/>

On Yarn you can also disable this warning entirely with `echo "--ignore-platform true" > .yarnrc`.

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

To repro:

`pnpm init -y && pnpm add rollup` (or any package that has an optional dependency on fsevents)

**Comment by sebastiangug** [comment]
Annoyed by this on windows as well

**Comment by zkochan** [comment]
It probably happens because [during hoisting](https://github.com/pnpm/pnpm/blob/main/packages/hoist/src/index.ts) the skipped optional dependencies is still looked up.

**Comment by adamburgess** [comment]
Fixed by #3454

🎉🎉🎉
