### ISSUE TITLE
Not publishing anymore

### ISSUE THREAD

**Issue by sullof** [pnpm/pnpm#3269]
### pnpm version:
5.18.7

### Code to reproduce the issue:

The problem is during the publishing.

### Expected behavior:

It should publish like it did before for many months and many versions (look at https://www.npmjs.com/package/secrez, at least 40 versions have been published since I moved from Lerna to Pnpm)

### Actual behavior:

I made no changes in the configuration of the package.json files along the monorepo, but it produces this error publishing the first changed package
```
Error: Command failed: cd packages/crypto && pnpm publish 
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string. Received undefined
```

### Additional information:

The monorepo is at https://github.com/secrez/secrez but you can take a look at the package that fails. It is a simple basic package used by the others packages:
https://github.com/secrez/secrez/tree/master/packages/crypto

I don't know if any of the other publish fails or not because that is a basic library that interrupts the entire process.

**Comment by zkochan** [comment]
Might be an issue with npm as pnpm run npm to publish. Try to downgrade npm to v6

**Comment by sullof** [comment]
@zkochan You are right. Downgrading npm to 6.14.11 it worked. Thanks a lot.
Still, I guess that you have to figure out what is going on there.

**Comment by zkochan** [comment]
There are a few issues with npm 7
here's another one: https://github.com/pnpm/pnpm/issues/2941
