### ISSUE TITLE
pnpm install jest links a shell script instead of a javascript to node_modules/.bin/jest

### ISSUE THREAD

**Issue by bingtimren** [pnpm/pnpm#3273]
### Code to reproduce the issue:

1. cd empty_dir
2. pnpm install jest
3. cat node_modules/.bin/jest 
4. rm -fr *
5. npm install jest
6. cat node_modules/.bin/jest
7. rm -fr *
8. yarn add jest
9. cat node_modules/.bin/jest

### Expected behavior:

As npm (see step 6) and yarn (see step 9) did, pnpm (step 3) should link a javascript file under node_modules/.bin/jest, as specified by the package.json of jest package.

### Actual behavior:

pnpm linked a shell script. I don't know where the shell script comes from.

### Additional information:

In my vscode launch.json, I launch ${workspaceRoot}/node_modules/.bin/jest with `node --inspect-brk` to debug. pnpm breaks this.

 - `node -v` prints: v14.16.0
 - `npm -v` prints: 6.14.11
 - `yarn -v` prints: 1.22.10
 - Windows, macOS, or Linux?: Linux

**Comment by bingtimren** [comment]
Just found out it's a duplicate of #1282, closing

**Comment by rdsedmundo** [comment]
Also facing the same issue under the situation reported by @bingtimren, I can't use `debugger` with Jest.

I work around it by referencing the file directly:
```sh
node --inspect-brk ./node_modules/jest/bin/jest.js --runInBand
```

instead of:
```sh
node --inspect-brk ./node_modules/.bin/jest --runInBand
```
