### ISSUE TITLE
pnpm cannot process "https-proxy" and "proxy"-flags

### ISSUE THREAD

**Issue by nils-christian** [pnpm/pnpm#3274]
### pnpm version:

5.18.8

### Code to reproduce the issue:

`pnpm install --https-proxy=http://<myproxy> --proxy=<myproxy>`

### Expected behavior:

pnpm installs the required dependencies.

### Actual behavior:

pnpm reports an error: 

`ERROR   ERROR  Unknown options: 'https-proxy', 'proxy'`

### Additional information:

We are currently using npm in our Maven project via the frontend-maven-plugin. The Maven proxy settings are forwarded to npm. Our understanding is that pnpm in basically a drop in replacement for npm and would behave the same way. However, it cannot process the proxy settings parameters.

**Comment by zkochan** [comment]
you may use this workaround:

```
pnpm install --config.https-proxy=http://<myproxy> --config.proxy=<myproxy>
```

**Comment by nils-christian** [comment]
Hi and thank you. Unfortunately this is not possible for us. The frontend-maven-plugin cannot be configured at this point. It simply uses "https-proxy" as parameter.

**Comment by zkochan** [comment]
ok, setting this through `.npmrc` setting should work as well. Or via env variables.

We will fix this in pnpm CLI for sure.

**Comment by zkochan** [comment]
:ship: 5.18.9

**Comment by nils-christian** [comment]
Thank you very much for fixing this issue so quickly.
