### ISSUE TITLE
I am unable to publish pnpm/action-setup@v2.0.0 to GitHub marketplace, can you help me?

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#3286]
![pnpm must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.
](https://user-images.githubusercontent.com/11488886/112719538-fe6f3a00-8f2b-11eb-9a3c-6ab76df59952.png)

**Comment by zkochan** [comment]
Where do you get this message? On what page?

**Comment by KSXGitHub** [comment]
> Where do you get this message? On what page?

[Release → v2.0.0 → Edit release](https://github.com/pnpm/action-setup/releases/edit/v2.0.0)

**Comment by zkochan** [comment]
ok, you should be able to release now

**Comment by KSXGitHub** [comment]
It's done. Thanks.
