### ISSUE TITLE
pnpm can't run node_modules/.bin scripts directly

### ISSUE THREAD

**Issue by GitGangGuy** [pnpm/pnpm#3297]
**Describe the user story**

I just migrated one project from Yarn v1/Classic to `pnpm` to try it out. I was pleasantly surprised that almost everything continued working (unlike Yarn v2/PnP which I tried before and ultimately gave up on because it felt slower and caused issues all over the place).
Euphorically I continued working as usual, until I tried using `pnpm` as I used to use `yarn` to call a package in `node_modules/.bin` without a dedicated `package.json` script. For example, to call `prettier`s bin from the command-line, with yarn I would do:
```sh
$ yarn prettier [...] # clear, concise, sexy
```
That is, without a `package.json` script called `prettier`, yarn will automatically resolve prettier from `node_modules/.bin`. On pnpm, I would have to do what I used to do back in the days with npm:
```sh
$ ./node_modules/.bin/prettier [...] # objectively ugly
$ pnpx prettier [...] # usable, but this will download prettier again instead of sourcing it from node_modules/.bin
```

**Describe the solution you'd like**

If pnpm can't find a subcommand that matches what follows it, and it can't find a script that is named what follows it, then it should look if the following command starts with a binary from `node_modules/.bin`, and execute that with the provided arguments instead of throwing an error.

**Describe the drawbacks of your solution**

This has been working quite well in Yarn for a long time, I don't think this will break anyone's setup currently using pnpm (as long as `package.json` scripts take precedence over `node_modules/.bin` files).

**Describe alternatives you've considered**

The alternative is to use `pnpx`, which does work and is quite quick, but it's not the same.

**Comment by CxRes** [comment]
I think this is related to #3287, specifically when postinstall script contains command found in `node_modules/.bin`.

**Comment by zkochan** [comment]
@GitGangGuy yes, we will support it https://github.com/pnpm/pnpm/discussions/3191

**Comment by rdsedmundo** [comment]
> usable, but this will download prettier again instead of sourcing it from node_modules/.bin

I don't think this statement is true, `pnpx` first sees if it's available on the `node_modules` and uses it instead of going over the network on every call. I just did a quick test by disconnecting from Wi-Fi and running `pnpx prettier --help` (had installed it previously with `pnpm install`) and it worked. @zkochan as the maintainer probably has more authority to speak about how it works under the hood.

I'm not exactly opposed to this change, but it's worth pointing out that this is not the direction that Yarn has gone (on v2 they also introduced `dlx`) and NPM (they closed the RFC pointed out in the #3191 discussion, and they have `npx`).

**Comment by merceyz** [comment]
> but it's worth pointing out that this is not the direction that Yarn has gone (on v2 they also introduced dlx)

@rdsedmundo Not quite sure what you mean with this, `yarn prettier` will only execute the local version if you directly depend on it, `yarn dlx prettier` will download the latest version and execute it in a temporary environment and once complete delete it
https://yarnpkg.com/cli/dlx

**Comment by rdsedmundo** [comment]
@merceyz thanks for pointing it out, I took that out of my comment.

**Comment by zkochan** [comment]
This is supported since [pnpm v6.6](https://github.com/pnpm/pnpm/releases/tag/v6.6.2)

**Comment by system32uwu** [comment]
This doesn't seem to be working properly with workspaces @zkochan:

![image](https://user-images.githubusercontent.com/29718978/179575980-7f3868c4-d18a-462e-bacf-f1bb2dfb8e08.png)

**Comment by tkrotoff** [comment]
@wiredmatt 

It works properly with workspaces
Use pnpm exec: https://pnpm.io/cli/exec

Examples:
`pnpm --recursive --parallel exec tsc`
`pnpm --filter=utils exec tsc`

This will execute `node_modules/.bin/tsc` in every workspaces

No need to add `tsc` in every package.json like you did for `neu`
