### ISSUE TITLE
lockfile v5.3 may not forward-compatitible with pnpm 5

### ISSUE THREAD

**Issue by thynson** [pnpm/pnpm#3299]
### pnpm version: 
pnpm 5.18.9
### Code to reproduce the issue:
git clone github.com/pnpm/pnpm.github.io.git # the lockfile appears to be generated by pnpm 6
pnpm install --frozen-lockfile 
pnpm run build

### Expected behavior:
build normally

### Actual behavior:
Error: Cannot find module 'prism-react-renderer/themes/github'

I wonder if there are some breaking changes so that the lockfile v5.3 is actually not forward-compatible with pnpm 5

**Comment by zkochan** [comment]
I am not aware of any breaking changes.

**Comment by thynson** [comment]
It works for me now again now. It should be my fault.
