### ISSUE TITLE
EEXIST: file already exists, symlink

### ISSUE THREAD

**Issue by idan-at** [pnpm/pnpm#3308]
### Code to reproduce the issue:
run `pnpm recursive install` in this repository: https://github.com/idan-at/pnpm-sensitive-file-name-bug

This is the output from the command:

```
.                                        |   +3 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/user/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 3, reused 2, downloaded 1, added 3, done
 ERROR  EEXIST: file already exists, symlink '../../../node_modules/.pnpm/registry.npmjs.org/file@0.2.2/node_modules/file' -> '/Users/user/projects/pnpm-bug/packages/p1/node_modules/file'
at com/file
```

### Expected behavior:
installation should complete successfully.

### Actual behavior:
Installation fails.

### Additional information:

 - `node -v` prints: `v14.15.5`
 - Windows, macOS, or Linux?: `macOS`

**Comment by zkochan** [comment]
It should fail because you have two dependencies with the same name: file and File. But it should fail with a meaningful error message.
