### ISSUE TITLE
TypeScript, Prettier, etc are copied to .pnpm instead of being linked

### ISSUE THREAD

**Issue by aminya** [pnpm/pnpm#3310]
### Code to reproduce the issue:

I don't know how to configure this, but a lot of dependencies such as TypeScript, Prettier, etc are copied to .pnpm instead of being linked.

This results in large `node_modules` size:

![image](https://user-images.githubusercontent.com/16418197/113520701-9be4f200-955a-11eb-9443-6bc672b92ac9.png)

### Expected behavior:

Symlink all the dependencies

### Actual behavior:

The dependencies are copied

### Additional information:

 - `node -v` prints: 15
 - Windows, macOS, or Linux?: Win10

**Comment by zkochan** [comment]
Those directories contain hard links to files in the content-addressable store. They are not copies.

https://pnpm.io/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store

![image](https://user-images.githubusercontent.com/1927579/113520905-cb1d5280-959e-11eb-85c2-9e3700d1848d.png)

**Comment by aminya** [comment]
I see. Enabling the following settings in tree-size shows a more realistic size, but still, it is not 0.

![image](https://user-images.githubusercontent.com/16418197/113521977-c5098080-9562-11eb-8a16-74d8da739a69.png)


![image](https://user-images.githubusercontent.com/16418197/113521971-b9b65500-9562-11eb-95ed-9fdfa271ec18.png)

**Comment by aminya** [comment]
@zkochan By the way, it would be nice to have a `pnpm size` command that shows the size of `node_modules`.
