### ISSUE TITLE
Workspace tags for dependency packages

### ISSUE THREAD

**Issue by dmichon-msft** [pnpm/pnpm#3316]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

When working in a large monorepo, there will commonly be one or more external dependencies that are shared across wide swathes of workspace packages (e.g. React, TypeScript, Jest). As a result, adding references to these dependencies in new packages can conflict with PRs that upgrade the version of the dependency used in the repo, and cause them to become unintentionally out of sync. There are tools (e.g. Rush), which can help detect and error on this state, but still depend on manual intervention by developers to express their intent for new versions.

It would be ideal to be able to somehow declare in package.json that a package uses "the version used in this workspace", or more generally "the version this workspace calls X"

**Describe the solution you'd like**

The `workspace:` protocol is currently used to identify that a particular semver expression shall be evaluated against the workspace, and use a local project if it matches, or install it externally otherwise. I propose an extension to this protocol to support a concept of "workspace tags", which look up the tag in a config file (`pnpm-workspace.yaml` or a new, separate one) and replace the specifier during package resolution and during `pnpm pack` with the specifier listed in the config file. For convenience, this step would be applied before normal `workspace:` replacement, such that the tag could refer to a `workspace:<semver>` expression.

Example:
`foo/package.json`
```json
{
  "name": "foo",
  "dependencies": {
    "react": "workspace:react-16"
  }
}
```
`bar/package.json`
```json
{
  "name": "bar",
  "dependencies": {
    "foo": "workspace:*",
    "react": "workspace:react-16",
    "react-dom": "workspace:react-16"
  }
}
```

`pnpm-workspace.yaml` (or other file)
```yml
packages:
  - ./foo
  - ./bar
tags:
  - tag: 'react-16'
    versions:
      react: '16.13.1'
      react-dom: '16.13.1'
```

If a tag is not specified in the config, then the `workspace:` protocol resolution falls through to existing behavior, e.g. tries and fails to resolve `workspace:react-16`. This makes it robust against any other valid expression following the protocol.

**Describe the drawbacks of your solution**

This would potentially interfere with the ability to refer to npm dist-tags in the `workspace:` protocol expressions, but as far as I know that isn't a supported scenario to begin with, and doesn't make a whole lot of sense with respect to how publishing works.
Tools that inspect package.json for version identifiers will no longer see the precise installed dependency version (react lint rules?), but such can be worked around by them loading the package.json of the actual installed dependency, and should probably do so anyway to contend with loose specifiers.

**Describe alternatives you've considered**

This is ultimately a glorified `.pnpmfile.cjs` `readPackage` hook combined with some sort of `readPackageForPack` hook, and if the latter existed, I'd probably just write my own layer to provide this functionality using `pnpmfile`, but it feels like a package manager feature.
Adding an additional protocol feels dangerous, so would rather reuse one that already signifies that the repository is a workspace and has a gap.

**Comment by zkochan** [comment]
I would certainly love a way to keep all dependency versions in a single place, it would reduce the number of git conflicts in monorepos.

We need to come up with a few alternative solutions to pick the best.

cc @arcanis as I think Yarn would probably love to support something like this as well.

**Comment by dmichon-msft** [comment]
Closing in favor of #3816 , which would allow a feature like this to be implemented in user-space, and also addresses the more general class of wanting to customize packing (e.g. to have repo package versions be stored somewhere other than package.json inside of Git)
