### ISSUE TITLE
prebuild/postbuild hook doesn't work

### ISSUE THREAD

**Issue by Camo30** [pnpm/pnpm#3317]
### Code to reproduce the issue:
Add script for `prebuild` or `postbuild` to package.json
Type `pnpm run build`

### Expected behavior:
`prebuild` and `postbuild` scripts should be executed

### Actual behavior:
`prebuild` and `postbuild` scripts are not executed.
This works when using pnpm version 5.18.9

### Additional information:

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
It is a breaking change in v6 https://github.com/pnpm/pnpm/issues/2891

**Comment by Camo30** [comment]
I should have read the changelog more carefully, especially the breaking changes. In my optinion this has the downside of more confusing scripts. Maybe this behavior could be made configurable?

**Comment by Camo30** [comment]
Closing because of #3348
