### ISSUE TITLE
ERROR  No write access to the found global executable directories

### ISSUE THREAD

**Issue by woss** [pnpm/pnpm#3319]
i'm getting the ` ERROR  No write access to the found global executable directories` when running `curl -f https://get.pnpm.io/v6.js | node - add --global pnpm `  in wsl2 node 14. Debian 10

maybe this helps

```
❯ ll /usr/bin/node*
-rwxr-xr-x 1 root root 73873984 Feb 23 02:00 /usr/bin/node
lrwxrwxrwx 1 root root       24 Sep 25  2020 /usr/bin/nodejs -> /etc/alternatives/nodejs
```

**Comment by woss** [comment]
just tested with ` sudo npx pnpm add -g pnpm` and it was working, that is not something that it's encouraged especially when adding the `/usr/pnpm-global` directory. can this be achieved for the user for example int he `~/.pnpm-global` ?

**Comment by woss** [comment]
i managed to get the pnpm working by removing the nodejs and npm i installed via apt and installed the [n](https://github.com/tj/n#installation) witch local prefix like this:

```bash
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
export N_PREFIX=~
bash n 15

# check that things are installed 
node -v
npm-v

# install pnpm
curl -f https://get.pnpm.io/v6.js | node - add --global pnpm 

# check is it installed 
pnpm -v

# if not check the ~/bin ( for me it was there 
❯ ll ~/bin
total 74060
-rwxr-xr-x 1 daniel daniel 75828920 Apr  7 17:27 node
lrwxrwxrwx 1 daniel daniel       38 Apr  7 17:27 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx 1 daniel daniel       38 Apr  7 17:27 npx -> ../lib/node_modules/npm/bin/npx-cli.js
-rwxr-xr-x 1 daniel daniel     1169 Apr  7 17:34 pnpm
-rwxr-xr-x 1 daniel daniel     1169 Apr  7 17:34 pnpx
 
# and that the `~/bin` is in the path
```

**Comment by binarious** [comment]
Same here. Can't install pnpm with `nodejs` and `npm` installed via `apt`.

**Comment by tobia** [comment]
I'm having the same issue.
My node is installed through a Debian package, but I want pnpm to be installed in my home directory.
What is the correct way to do that?
Should it not be using ~/.local or something like that?

**Comment by CoreyVincent** [comment]
Having this issue as well.

**Comment by LaamGinghong** [comment]
![image](https://user-images.githubusercontent.com/33472924/140455981-a80d5b7b-cdf0-43b8-858b-3bb99fcf1e3c.png)
Neither approach worked for me in MacOS BigSur

**Comment by jonrrivera** [comment]
ahh please help, getting same issue

**Comment by zkochan** [comment]
Does standalone script work? 

```
curl -fsSL https://get.pnpm.io/install.sh | sh -
```

You should restart the terminal after running it.

**Comment by jonrrivera** [comment]
<img width="568" alt="Screen Shot 2021-11-21 at 3 45 12 PM" src="https://user-images.githubusercontent.com/18686388/142783816-076dfca2-302e-4c50-9cdf-16e407781949.png">


thanks for the quick reply, this is what I'm getting after restarting the terminal

**Comment by amm834** [comment]
Just exit the current session and test it in new session. It works for me.

**Comment by valerii15298** [comment]
This also happens for me:
```
PS C:\Users\valer\OneDrive\Desktop\projects> pnpm -g list
 ERROR  The CLI has no write access to the pnpm home directory at C:\Users\valer\AppData\Local\pnpm
For help, run: pnpm help list
```

```bash
pnpm -v // => 6.32.3
```

**Comment by amm834** [comment]
> This should work in v7

I just upgrade to the v7 and it working perfectly

**Comment by biro456** [comment]
I'm trying to install PNPM in a Docker image with this (redacted) Dockerfile:

```dockerfile
FROM node:16-alpine
USER node:node
ENV PNPM_VERSION=6.32.9
RUN wget -qO- https://get.pnpm.io/v6.16.js | node - add -g pnpm@${PNPM_VERSION}
```

It fails with:
```shell
 ERROR  No write access to the found global executable directories
The found directories:
  /usr/local/bin
```

Building without `USER node:node` works, so the question is why is it failing to install when not running as `root`.

**Comment by liby** [comment]
@zkochan
As mentioned by @biro456, when installing pnpm on CI, use the following command:
```
curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
```
run `pnpm add -g pkg`, the following error will be encountered(The *~/.local/share/pnpm* file has been created manually):
> ERROR  The CLI has no write access to the pnpm home directory at ~/.local/share/pnpm

Use the `npm install -g pnpm@7` command to install, which solves this issue.

**Comment by alex-vladut** [comment]
When trying to install `pnpm` on the CircleCI CI/CD pipeline with the installation script:

```
curl -fsSL https://get.pnpm.io/install.sh | sh -
```

I get the following error:

```
 ERR_PNPM_UNSUPPORTED_SHELL  Can't setup configuration for "" shell. Supported shell languages are bash, zsh, and fish.
Install Error!

Exited with code exit status 1
```

Did anyone encounter this issues and found a solution already? Thanks

**Comment by valerii15298** [comment]
@alex-vladut having the same problem

**Comment by alex-vladut** [comment]
In case it helps anyone, what happened for us was that CircleCI most likely change the path to bash. We updated the command to pick it up automatically and set it to `SHELL` env var like this:

```
curl -fsSL https://get.pnpm.io/install.sh | SHELL=`which bash` bash -
```

**Comment by braden337** [comment]
```shell
mkdir -p $PNPM_HOME
```

**Comment by sandrotaje** [comment]
> In case it helps anyone, what happened for us was that CircleCI most likely change the path to bash. We updated the command to pick it up automatically and set it to `SHELL` env var like this:
> 
> ```
> curl -fsSL https://get.pnpm.io/install.sh | SHELL=`which bash` bash -
> ```

Thanks @alex-vladut this helps also if you are creating a [buildpack](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/build-app/)

**Comment by wakamsha** [comment]
Why not try `corepack` ?

```console
sudo corepack enable && corepack prepare pnpm@latest --activate
```

I was able to install pnpm on CircleCI this way.

**Comment by Timiyu** [comment]
v7有问题，安装包404 v6好用，怎么各种不兼容，这种东西开发出来有啥意义，糟心的很

**Comment by drnkwati** [comment]
I am having the same issue on m1.
Any workarounds?

**Comment by drnkwati** [comment]
@AisonSu Some distributions are running old versions of bash shell. Update bash or avoid using the newer syntax like [[ ]] etc. Also always check the tools or commands you are using to make sure they are standard and available on all Linux distributions.

**Comment by zkochan** [comment]
This issue was related to the `curl -f https://get.pnpm.io/v6.js | node - add --global pnpm` script. Don't use that script. Use on of the installation methods listed on this page: https://pnpm.io/installation

**Comment by bala-techguy** [comment]
> This also happens for me:
> 
> ```
> PS C:\Users\valer\OneDrive\Desktop\projects> pnpm -g list
>  ERROR  The CLI has no write access to the pnpm home directory at C:\Users\valer\AppData\Local\pnpm
> For help, run: pnpm help list
> ```
> 
> ```shell
> pnpm -v // => 6.32.3
> ```

The same happens for me. How did you resolve this?

**Comment by hyykrish** [comment]
Run the command 

```bash
sudo chown -R $(whoami) /Users/{username}/Library/pnpm
```

Replace ``` {username} ``` with your username
