### ISSUE TITLE
Rushstack linking broken on @6.0.1

### ISSUE THREAD

**Issue by prescience-data** [pnpm/pnpm#3329]
### pnpm version:
6.0.1

Not sure if this a PNPM issue or a Rushstack issue but linking breaks when moving to 6.0.1

https://github.com/microsoft/rushstack/issues/2601

### Code to reproduce the issue:

1. Update `rush.json` to use `"pnpmVersion": "6.0.1"`
2. Run `rush purge && rush update`
3. Rush installs dependencies
4. When attempting to link first package encounters `ERROR: Internal Error: Cannot find installed dependency <first-dependency-of-first-local-package>`

### Expected behavior:

A completed `rush update` linking.

### Actual behavior:

```text
ERROR: Internal Error: Cannot find installed dependency "@rushstack/eslint-config" in
"D:\Dev\<pkg>\common\temp\node_modules\.pnpm\local\D%3A%2FDev%2F<pkg>%2Fcommon%2Ftemp%2Fprojects%2F<local-pkg>.tgz\node_modules"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

### Additional information:

The issue is occurring because the directory referenced in the error above is now using `+` as a seperator instead of `%3A`  `:` and `%2F`  `/`

See: https://github.com/pnpm/pnpm/releases/tag/v6.0.1

| Question | Answer |
| -------- | -------- |
| `useWorkspaces` from rush.json? | false |
| Operating system? |  Windows  |
| Node.js version (`node -v`)? | v14.16.0 |

**Comment by zkochan** [comment]
Probably Rush is looking for the location of local tarball dependencies in `node_modules/.pnpm` but we have changed the path to them in v6

**Comment by prescience-data** [comment]
Rush is working an PR which will fix: https://github.com/microsoft/rushstack/pull/2610

Additional context and temporary workaround here: https://github.com/microsoft/rushstack/issues/2601

The short answer for anyone looking is to migrate to `useWorkspaces: true` which will hand over control of package linking to PNPM rather than using the depreciating Rush handler. 
https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/Linking.20projects.20-.3E.20cannot.20find.20deps.20error/near/234238295

Closing as this is not a PNPM issue. 🕺
