### ISSUE TITLE
Updating to pnpm 6 breaks nextjs / babel

### ISSUE THREAD

**Issue by polesapart** [pnpm/pnpm#3349]
### pnpm version:
6.0.2
### Code to reproduce the issue:
next js 10.0.3 sample

### Expected behavior:

Works the same as with pnpm 5.

### Actual behavior:

pnpm dev prints this:

Module not found: Can't resolve '/home/alex/devel/ceneduc/ceneduc-site/node_modules/.pnpm/@babel/runtime@7.12.5/node_modules/@babel/runtime/helpers/assertThisInitialized' in '/home/alex/devel/ceneduc/ceneduc-site/node_modules/.pnpm/next@10.1.3_3be643bbf620ef4d9241878989fabc20/node_modules/next/dist/next-server/lib'

Seems to be searching for the directory without the '+'.

### Additional information:

 - `node -v` prints:
  v15.11.0
  
- Windows, macOS, or Linux?:

Linux

**Comment by zkochan** [comment]
But this is not installed by pnpm v6.
pnpm v6 would create `home/alex/devel/ceneduc/ceneduc-site/node_modules/.pnpm/@babel+runtime@7.12.5`

**Comment by polesapart** [comment]
> But this is not installed by pnpm v6.
> pnpm v6 would create `home/alex/devel/ceneduc/ceneduc-site/node_modules/.pnpm/@babel+runtime@7.12.5`

And it does, my node_modules was created after the update. The directory with the + is there / but the ghost one being referenced by nextjs doesn't. 

I'm not sure why it tries to find it in the wrong location. Could it be hardcoded in nextjs?

**Comment by nikoladev** [comment]
I'm using pnpm v6 and Next.js without issues. Do you have a minimal reproducible example?

**Comment by polesapart** [comment]
@nikoladev I'll try and get one

**Comment by polesapart** [comment]
I'm closing the issue. I'm using nvm, and after fresh reinstaliing node, everything works and I can no longer reproduce the problem.
