### ISSUE TITLE
This version of pnpm requires at least Node.js v12.17

### ISSUE THREAD

**Issue by xlzy520** [pnpm/pnpm#3359]
### Code to reproduce the issue:
![image](https://user-images.githubusercontent.com/28336270/115013525-bf595680-9ee3-11eb-8b88-6c6c8b2ea4a3.png)

### Additional information:

 - `node -v` prints: 14.16.0
 - Windows, macOS, or Linux?: MacOS

**Comment by thynson** [comment]
Are you using nvm?
Probably you there are multiple nodes in $PATH.

**Comment by xlzy520** [comment]
> Are you using nvm?
> Probably there are multiple nodes in $PATH.

yes, using nvm.

**Comment by xlzy520** [comment]
resolve problem by update nodejs pkg

**Comment by thynson** [comment]
I guess you have `PATH=~/.nvm/versions/14.16.0/node/bin:~/.nvm/versions/12.12.0/node/bin:...` , while pnpm was installed in `~/.nvm/versions/12.12.0/node/bin/pnpm`. 
If that is your case, fix your PATH or reinstall with `curl -f https://get.pnpm.io/v6.js | node - add --global pnpm`(ensure it's v14.16.0)

**Comment by xlzy520** [comment]
thank you.
