### ISSUE TITLE
npm compatibility: add support for including gitHead during publication

### ISSUE THREAD

**Issue by iarna** [pnpm/pnpm#3373]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

Large institutions want to be able to verify that the build environments used to build the open source they use have not been compromised.

When rebuilding packages form source gives the same result one can be fairly certain that the build environment hasn't been compromised.

In order to rebuild packages one needs to know both the repository hosting the source code and the commitid that was published.

The repository published is in user provided metadata in the package.json.

The commitid that was published is added by npm at publish time by adding the `gitHead` property to the copy of the `package.json` that's sent to the registry during publication.

**Describe the solution you'd like**

I'd like to add support to for including this during publication, so that packages published with pnpm can be correlated with a specific git commit in their associated repository.  The npm code for reading this value is in: [read-package-json](https://github.com/npm/read-package-json/blob/latest/read-json.js#L345-L384). The original feature request was [read-package-json#7](https://github.com/npm/read-package-json/issues/7).

As a side note, because npm populates this value when reading the package.json value it becomes available to run scripts. Folks have sometimes taken advantage of this, you can see evidence of that in [yarn#1587](https://github.com/yarnpkg/yarn/issues/1587).

**Describe the drawbacks of your solution**

* It exposes information that wasn't exposed before when publishing with pnpm. That said, commitids don't contain much meaningful information. Further it would be reasonable to only include them when the repository is set in the package.json.
* It adds new (albeit small) work to the publish process.

**Comment by zkochan** [comment]
We have some additional logic that we run before/after publish but under the hood pnpm runs `npm publish` to publish the packages.

https://github.com/pnpm/pnpm/blob/25cea8556740d15d2a77ee139fd4f8fe19a7cd9e/packages/plugin-commands-publishing/src/publish.ts#L185

So I am not sure why gitHead is not added by npm.

**Comment by iarna** [comment]
Yup, the temp directory thing is why it doesn't work:

npm will only read a githead if the package.json is in the root folder.

```
  var dir = path.dirname(file)
  var head = path.resolve(dir, '.git/HEAD')
```

I suppose that made sense when monorepos weren't a thing and no one used workspaces. Seems counter productive now though.

**Comment by iarna** [comment]
I've been digging in with @s-tuli:

1. pnpm's call outs to npm work great outside of workspaces
2. inside workspaces things don't work, we intended to address this by getting npm to support this

If publishing from temp folders lands then it'll need explicit support for this. Without that, this can be closed.

**Comment by zkochan** [comment]
I don't think we will publish from a temp directory. We are adding our own packing implementation (https://github.com/pnpm/pnpm/pull/3608) to avoid the usage of a temp directory.

**Comment by NVolcz** [comment]
It has been a couple of years, and pnpm still does not publish gitHead. I suggest reopening this issue. The fix appears relatively straightforward, and I would be happy to contribute it.
