### ISSUE TITLE
Error during production install of workspace

### ISSUE THREAD

**Issue by helios16017** [pnpm/pnpm#3375]
### pnpm version:
6.0.2

I think the problem started in 5.9.0

### Code to reproduce the issue:
I have a simple workspace layout like
  .
  ├── package1
  │   ├── index.js
  │   └── package.json
  └── pnpm-workspace.yaml

content of package1/index.js:
console.log(require('moment')())

content of package1/package.json:
{
  "name": "package1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "moment": "^2.29.1"
  },
  "devDependencies": {
    "eslint": "^7.24.0"
  }
}

content of pnpm-workspace.yaml:
packages:
  - './**'

Running install for production causes an error

pnpm install -P
Packages: +1
+
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/jbl/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 122, reused 87, downloaded 0, added 1, done
 ERROR  ENOENT: no such file or directory, chmod '/home/jbl/tmp/pnpm/node_modules/.pnpm/eslint@7.24.0/node_modules>/eslint/bin/eslint.js'
at pnpm/eslint

### Expected behavior:
Install of packages in "dependencies". In this case only moment.

### Actual behavior:
Error during install related to package in "devDependencies".

### Additional information:

 - `node -v` prints: v12.18.0
 - Windows, macOS, or Linux?: Linux Ubuntu 20.04

**Comment by zkochan** [comment]
Seems like this only happens when there is no lockfile.

If you commit the `pnpm-lock.yaml` with your changes, `pnpm i -P` will succeed with no issues.
