### ISSUE TITLE
pnpx error: unknown option

### ISSUE THREAD

**Issue by digitalclubb** [pnpm/pnpm#3377]
### pnpm version:

6.0.2

### Code to reproduce the issue:

```
pnpm add @playwright/test -D
pnpx folio --config=config.ts
```

### Expected behavior:

> Running 1 test using 1 worker<br />
1 passed (1s)

### Actual behavior:

> error: unknown option '--config=config.ts'

### Additional information:

I've been trying to setup [playwright-test](https://github.com/microsoft/playwright-test) in a `pnpm` managed repository. The [documentation](https://github.com/microsoft/playwright-test#run-the-test) for playwright-test uses `npx` with [folio](https://github.com/microsoft/folio).

Running `npx folio --config=config.ts` results in the correct expected behaviour.

Running `pnpx folio --config=config.ts` results in an error (actual behaviour).

[Small reproducible repo](https://github.com/digitalclubb/pnpx-playwright-test)

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by digitalclubb** [comment]
I've noticed playwright-test installs an alpha version of folio:

```
"dependencies": {
    "folio": "=0.3.23-alpha",
    "playwright": "=1.10.0",
    "rimraf": "^3.0.2"
  },
```

This alpha version appears to be when the config argument was added:

```
pnpm test:e2e
> ./node_modules/.pnpm/folio@0.3.18/node_modules/folio/cli.js --config=./tests/e2e-config.ts

error: unknown option '--config=./tests/e2e-config.ts'

pnpm test:e2e
> ./node_modules/.pnpm/folio@0.3.23-alpha/node_modules/folio/cli.js --config=./tests/e2e-config.ts

Running 3 tests using 3 workers
```

This suggests to me that `npx` is possibly using the alpha version whereas `pnpx` is installing 0.3.18 which does not have the option.

**Comment by zkochan** [comment]
Both npx and pnpx run the bins from `node_modules/.bin` when they are present. However, `npm install` links all bins of all subdependencies to `node_modules/.bin`. pnpm links only the bins of direct dependencies. I assume when you were testing it with npx, you used `npm install`, so the bin of the alpha folio was hoisted. But when you used `pnpm install`, folio was not hoisted, so pnpx installed the latest folio and executed it.

There are 2 solutions.

The recommended one. If you need to access folio, install it as a direct dependency of your project.

Another solution is to set the `public-hoist-patter[]=folio` setting. This will hoist the folio bin.
