### ISSUE TITLE
[Illegal access] can access package wtih no declaration at package.json. 

### ISSUE THREAD

**Issue by NNNaix** [pnpm/pnpm#3380]
### pnpm version:
**6.0.2**
### Code to reproduce the issue:
_I'm not sure if this is a problem with node's own module resolution policy._

My project structure is liking below:
```
[project root]
 - package.json
 - pnpm-workspace.yaml
 - node_module
 - server
    - package.json
    - node_module
    - main.ts 
```
pnpm-workspace.yaml:
```
packages:
    # all packages are in below directories.
    - 'server'
    # exclude packages that are inside test directories.
    - '!**/test/**'
```
root package.json:

```
"dependencies": { 
  "packageA": "^1.0.0"
}
```

server workspace package.json:
```
// have no 'packageA' dependency declaraion 
"dependencies": { 
   ...
}
```
main.ts: 
```
// can be imported normally
import packageA from 'packageA'
```

### Expected behavior:

can not find the packageA because have no declaration at package.json.

### Actual behavior:
packageA can be imported normally without declaration at package.json.

### Additional information:

 - `node -v` prints:  **v14.16.0**
 - Windows, macOS, or Linux?: **macOs 10.14.6**

**Comment by thynson** [comment]
That is not a bug of pnpm, it's the node's resolve behavior.

**Comment by NNNaix** [comment]
thx

**Comment by thynson** [comment]
You can try the following workspace structure
```
/ # No package.json in workspace root
|-/tools/
| |-package.json # Move all dev tools here
|
|-/packages/
| |...
|
|-pnpm-workspace.yaml
|-.npmrc

```
and put`symlink=false` in .npmrc. 

But with such a structure you cannot use any dev tools in scripts of `packages/**`
