### ISSUE TITLE
ERR_PNPM_FETCH_408 results in a mysterious 5-minute halt during package installation

### ISSUE THREAD

**Issue by kaiyoma** [pnpm/pnpm#3387]
### Actual behavior

I'm a recent convert to Rush / pnpm and only today have I started using both tools in our CI environment. Twice today, I've seen this:

```
16:28:48  Progress: resolved 356, reused 0, downloaded 355, added 0
16:28:48  Progress: resolved 357, reused 0, downloaded 355, added 0
16:28:50  Progress: resolved 358, reused 0, downloaded 358, added 0
16:33:50   WARN  GET https://<redacted>/@types/undertaker/-/undertaker-1.2.0.tgz error (ERR_PNPM_FETCH_408). Will retry in 10 seconds. 2 retries left.
16:33:51  Progress: resolved 359, reused 0, downloaded 358, added 0
16:33:52  Progress: resolved 440, reused 0, downloaded 405, added 0
16:33:52  Progress: resolved 440, reused 0, downloaded 406, added 0
```

For starters, what does `ERR_PNPM_FETCH_408` mean? Searching Google for that turns up 0 results, which is impressive. 😄 

Next, how come the message says that pnpm will retry in 10 seconds, but after a 5-minute delay? I've seen the same 5-minute delay in another CI build.

### Additional information:

 - `node -v` prints: 14.15.5
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
ERR_PNPM_FETCH_408 means that the registry responded with a 408 status code, when the package tarball was requested. Seems like a registry issue.

**Comment by kaiyoma** [comment]
That's definitely a possibility (the 408 timeout, that is) since we sometimes have connection issues to our internal registry. But is the 5-minute pause expected?

**Comment by zkochan** [comment]
I assume the issue is that it waits for the response a couple of minutes before failing with the timout error. Do you want to reduce the timeout wait?

**Comment by zkochan** [comment]
npm has this [fetch-timeout](https://docs.npmjs.com/cli/v7/using-npm/config#fetch-timeout) setting that is 5 minutes by default. We don't have such setting at the moment. We can add I believe. Yarn has a similar setting [http-timeout](https://yarnpkg.com/configuration/yarnrc/#httpTimeout) and their default is 1 minute.

**Comment by kaiyoma** [comment]
Nice! Thanks for the quick fix. Seems like a reasonable approach. :smile:
