### ISSUE TITLE
avoid the message asking confirmation for installing packages (--yes don't seem to work)

### ISSUE THREAD

**Issue by opensas** [pnpm/pnpm#3391]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

As a user I want to execute something with pnpx and let pnpx automatically install needed packages without asking for confirmation.

user enters

```shell
px tailwindcss-cli@latest build -o tailwind-test.css --yes
[...]
   ✅ Finished in 363 ms
   📦 Size: 9.9KB
   💾 Saved to tailwind-test.css
```

And the command is executed assuming "yes"  for the following confirmation

```shell
? Install the following package: tailwindcss-cli@latest? (Y/n) ‣ true
```

**Describe the solution you'd like**

When passing the --yes switch the command is executed assuming "yes"  for the following confirmation

**Describe the drawbacks of your solution**

none

**Describe alternatives you've considered**
Can't think of another option

--

I'm using 

```shell
$ pnpx -v
6.0.2
```

**Comment by zkochan** [comment]
It should work. Just paste the option at the beginning

opensas ***@***.***> ezt írta (időpont: 2021. ápr. 24., Szo
19:28):

**Comment by opensas** [comment]
yes, I can confirm it is working... how silly of me...
