### ISSUE TITLE
The inferred type of 'getAllBooks' cannot be named without a reference to '.pnpm/@apollo+client@3.3.15_graphql@15.5.0/node_modules/@apollo/client/core'. This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by hiepxanh** [pnpm/pnpm#3396]
Yes, I dont know what do do, shameful host and https://github.com/pnpm/pnpm/issues/1928#issuecomment-515708856 not really work. 

### Code to reproduce the issue:
- install `pnpm i @apollo/client graphql -S`

### Expected behavior:
not get error
### Actual behavior:
![image](https://user-images.githubusercontent.com/16970990/116021220-f8c35c00-a671-11eb-8fa1-7bd71331d952.png)

### Additional information:
 - `node -v` prints: 14.15.0
 - Windows, macOS, or Linux?: Windows

**Comment by hiepxanh** [comment]
relate issues https://github.com/microsoft/TypeScript/issues/29221 https://github.com/microsoft/TypeScript/issues/29808
@zkochan  hello sir, if you have time, can you take a look? do you have any suggestion I should try to solve this problem?

**Comment by zkochan** [comment]
Do you have the issue in a workspace?

**Comment by hiepxanh** [comment]
I just invite you to project, can you take a look? https://github.com/small-cosmos/awread on develo channel, after we can fix this issue, I would like to remove you. 
 @zkochan 
 after clone and `pnpm install` can you take a look on this file
 `libs/writer/web/feature-auth/src/lib/apis/books.api.ts`

**Comment by hiepxanh** [comment]
Do you have the issue in a workspace?
Yes, I'm using nx, so maybe the problem because of workspace

**Comment by hiepxanh** [comment]
oh, I dont think I'm using anything with workspace @zkochan

**Comment by zkochan** [comment]
I don't seem to have the error on Windows as well after I ran `pnpm build` and also I installed all the recommended VS code extensions.

**Comment by hiepxanh** [comment]
oh, I see, I install  pnpm v6.2.5 and nodejs 16.1 but on windows https://github.com/microsoft/TypeScript/issues/29808#issuecomment-487813164
it seem windows problem

**Comment by hiepxanh** [comment]
ok, let me try 'pnpm build'

**Comment by hiepxanh** [comment]
it's really weird, I know you are busy, but can you take a little time to teamview for me? 
I can use teamview or gg chrome remote desktop extension

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/117536438-38505780-b025-11eb-90d8-f5562ccc66d1.png)
added `ApolloQueryResult` mute the error

**Comment by zkochan** [comment]
No, I have to go out now. Try on a clean repository. TBH, I don't have a lot of knowledge about how TypeScript or nx works, so I am in the dark as well.

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/117536453-48683700-b025-11eb-8016-d6cffa2cf117.png)

with out the `ApolloQueryResult` it keep yelling. 

Thank for your support. It's really interest error. I will try to fix and report my investment on this issue

**Comment by hiepxanh** [comment]
oh, I'm really happy with your answer. I mean it very sad, but at least I know I try my best, and have someone like me. Hahahaha.
It already take me 3 days. But at least I'm happy now. 
thanks for you support. 
be safe and have a good day

**Comment by zkochan** [comment]
You're welcome

**Comment by hiepxanh** [comment]
https://github.com/microsoft/TypeScript/issues/29808#issuecomment-540292885
Wow, after digging in the typescript, I found that typescript dont know where to find the type of Apollo-angular, so it cannot give a good instruction to vscode. 
If I declare the path of the package on 'tsconfig.base.json' my project tsconfig. It work correctly without anything else. So strange, so I guess it is the library bug instead of `pnpm` bug. I have to admire that it is more perfect than `yarn` or `npm`. thank you for a good library. Close the issues since that find the source of problem.

```
  "apollo-angular": [
        "node_modules/apollo-angular/"
      ],
```

![image](https://user-images.githubusercontent.com/16970990/117537029-ae09f280-b028-11eb-8b95-b4a577cd7187.png)

**Comment by g3tr1ght** [comment]
To those who stumbles upon this while using NX, make sure your library tsconfig doesn't have
`{
    compilerOptions: {
         declaration: true
    }
}`
