### ISSUE TITLE
`pnpm install` --workspace-concurrency? 

### ISSUE THREAD

**Issue by evantahler** [pnpm/pnpm#3399]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))
... if you can guide me to the proper place :D

**Describe the user story**

We've got a large [monorepo](https://github.com/grouparoo/grouparoo) using pnpm.  Sometimes on CI, our `pnpm install` process [runs out of memory](https://app.circleci.com/pipelines/github/grouparoo/grouparoo/8273/workflows/2f777b5f-7b23-4376-aaf4-6ab55326c092/jobs/138148).   Ideally, we'd like to do something to flag to the CI server to only run `pnpm install` with a parallelism of 1 or 2.  

Note: the actual install process always works fine! The problem is when running our `prepare` hooks post-install.  That's when we compile our typescript project, and that's when we run out or memory. 

**Describe the solution you'd like**

```
$ pnpm install --workspace-concurrency 2
```

This would then only run 2 package's `postinstall` hooks at a time. 

**Describe the drawbacks of your solution**

Currently it looks like `--workspace-concurrency` is not supported when running `pnpm install`

```
$ pnpm install --workspace-concurrency 2
 
ERROR   ERROR  Unknown option: 'workspace-concurrency'
Did you mean 'network-concurrency'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help add
```
**Describe alternatives you've considered**

We paid CircleCI more money for bigger build servers.

**Comment by zkochan** [comment]
This might already be supported. Try to set this setting: https://pnpm.io/npmrc#child-concurrency

**Comment by evantahler** [comment]
Interesting!

So that needs to be checked into `.npmrc` then?  It doesn't look like it works as a flag, e.g. `pnpm install --child-concurrency 2` ran 4 at once.  I think this option might be better as a flag for our use-case.  We don't want to limit *all* builds to 2x, as our developer machines can handle 4x at once... we only want the limited behavior in some environments.

**Comment by evantahler** [comment]
Also, thanks for the super-fast reply!

**Comment by zkochan** [comment]
:ship: 6.2.3
