### ISSUE TITLE
`@pnpm/find-workspace-packages` should note on its readme that `@pnpm/logger` is a required peer dep

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#3406]
`@pnpm/cli-utils` requires `@pnpm/logger` as peer.

```
Error: Cannot find module '@pnpm/logger'
Require stack:
- /xxx/node_modules/.pnpm/@pnpm+cli-utils@0.4.40/node_modules/@pnpm/cli-utils/lib/packageIsInstallable.js
- /xxx/node_modules/.pnpm/@pnpm+cli-utils@0.4.40/node_modules/@pnpm/cli-utils/lib/index.js
- /xxx/node_modules/.pnpm/@pnpm+find-workspace-packages@2.3.26/node_modules/@pnpm/find-workspace-packages/lib/index.js
```

**Comment by mcmxcdev** [comment]
`@pnpm/find-workspace-packages` requires `@pnpm/cli-utils` which has the following set:

```
"peerDependencies": {
    "@pnpm/logger": "^4.0.0"
  },
```

So `@pnpm/logger` should pop up as unmet peer dep warning, is that good enough for you? None of the pnpm packages seem to explicitly state required peer deps in the `README.md`

**Comment by vjpr** [comment]
It’s easy to ignore unmet peer messages and the fact it is a transitive peer dep is harder to figure out.

Things have changed with peer deps though lately so maybe the situation isn’t as bad.

**Comment by mcmxcdev** [comment]
Strict peer deps is enabled by default since pnpm v7, so ignoring/silencing missing peer deps is an intentional choice then. I will close this since it's not really an issue per we.
