### ISSUE TITLE
In pnpm v6.2.2, installing git dependencies on a branch fails

### ISSUE THREAD

**Issue by evantahler** [pnpm/pnpm#3407]
### Code to reproduce the issue:

Have a `package.json` that references a github repo + branch ([example](https://github.com/grouparoo/grouparoo/blob/main/plugins/%40grouparoo/marketo/package.json#L32)): 

```
  "dependencies": {
    "node-marketo-rest": "grouparoo/node-marketo#restler_upgrade"
  },
```

See that installing [fails](https://app.circleci.com/pipelines/github/grouparoo/grouparoo/8351/workflows/fd84f940-1a35-45b2-9977-3e24c447f6f2/jobs/140808):

```
pnpm install --prefer-frozen-lockfile
Scope: all 41 workspace projects
Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1959

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/circleci/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1959, reused 0, downloaded 31, added 20
Progress: resolved 1959, reused 0, downloaded 31, added 21

... (snip) ...

Progress: resolved 1959, reused 0, downloaded 1711, added 1711
 ERROR  ENOENT: no such file or directory, open '/home/circleci/.pnpm-store/v3/_tmp_72_171c5145fcf323d3379fdc048eacaecd/lib/api/smartList.js'
```

### Expected behavior:

The package installs, as it does when downgrading to pnpm v6.2.1

### Additional information:

 - `node -v` prints: v14.16.1
 - Ubuntu.

The problem does not seem to appear on OSX

**Comment by evantahler** [comment]
We've mitigated this by finally publishing our package to NPM, which we should have done anyway https://github.com/grouparoo/grouparoo/pull/1717

**Comment by zkochan** [comment]
I'll fix it today

**Comment by evantahler** [comment]
Thank you for the speedy fix!

**Comment by zkochan** [comment]
:ship: 6.2.3
