### ISSUE TITLE
pnpm symlinks with electron.

### ISSUE THREAD

**Issue by ahmadfaraz84** [pnpm/pnpm#3415]
### pnpm version:5.15.2
I am using a rush monorepo with pnpm as package manager. There is a project for electron app, which works well in development mode, but when I try to make a distributable package, there occurs an error for missing modules. For example in the below image, there is a missing dependency for "flatbuffers".
![image](https://user-images.githubusercontent.com/55415567/116891524-3ca4fb00-ac48-11eb-960e-08bb192b4a67.png)

Now, if I copy that module manually into the project level node_modules, this error resolves but another occurs for another dependency. The problem is the symlinks for sub-dependencies of external packages are not created in project_level node_modules.
Plus @zkochan has commented (in the link https://github.com/nodejs/node/discussions/37509#discussion-3240334) that "pnpm doesn't work with electron apps". 
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by italodeandra** [comment]
Try running `pnpm i --shamefully-hoist` to flatten the `node_modules` structure. Electron probably tries to use packages in paths that **pnpm** didn't automatically create symlinks, so you need to run with that flag.

Beware that this flag loses the purpose of using **pnpm** instead of **yarn** or **npm**, so if it works consider switching to one of them instead (at least for this particular project).

**Comment by ahmadfaraz84** [comment]
> Try running `pnpm i --shamefully-hoist` 

Actually I am not using pnpm directly, instead I am using rush which is using pnpm as a package manager. So I can't directly use pnpm. However, rush has the options to use npm or yarn to use as package managers, but as u said, point of efficient use fails here. This is a issue which needs attention from three sides, rush, electron, and pnpm.

**Comment by shrinktofit** [comment]
Bump.

**Comment by ahmadfaraz84** [comment]
> Bump.

Bumb what ? Can you explain it please ?

**Comment by italodeandra** [comment]
> > Bump.
> 
> Bumb what ? Can you explain it please ?

He probably just wanted the issue to get more attention.

**Comment by zkochan** [comment]
There's nothing we can currently do if electron doesn't work with symlinks.

**Comment by alex20465** [comment]
In my case electron is a workspace package `pnpm i --shamefully-hoist` flattens the node_modules only on ROOT.

I have to fallback to yarn in order to build the electron

**Comment by zkochan** [comment]
pnpm now can install a node_modules without using symlinks.

Set `node-liner=hoisted` in `.npmrc`

https://pnpm.io/npmrc#node-linker

**Comment by stewones** [comment]
too bad electron is still not supporting pnpm and symlinks
