### ISSUE TITLE
pnpm list -r will also print the workspace path

### ISSUE THREAD

**Issue by Madvinking** [pnpm/pnpm#3418]
feature request: list workspaces paths in the list command

pnpm version:
6.2.3

Expected behavior:
we trying to migrate to pnpm and we have some task that copy files into some of the workspaces folder
it will be very helpful if the `pnpm list -r` or `pnpm list -r --depth -1` command will print the workspace path as well

Additional information:
node -v prints: v16.1.0
Windows, OS X, or Linux?: OS X

**Comment by amitgilad3** [comment]
Hi @Madvinking  can you please elaborate on what you mean ??

if i run pnpm list -r the output i get is this:

```
@pnpm/test-fixtures@0.0.0 /Users/amit/amit/pnpm/privatePackages/test-fixtures

dependencies:
ncp 2.0.0

devDependencies:
@pnpm/test-fixtures link:
@types/ncp 2.0.4

@pnpm/eslint-config@1.0.0 /Users/amit/amit/pnpm/utils/eslint-config

dependencies:
@typescript-eslint/eslint-plugin 4.22.0
eslint-config-standard-with-typescript 20.0.0
eslint-plugin-import 2.22.1
eslint-plugin-node 11.1.0
eslint-plugin-promise 4.3.1
```

as you can see the workspace path of each package is listed near the package name. 
is this what you  want ?

**Comment by Madvinking** [comment]
@amitgilad3 ops... yes that what i need,
but i meant when i run 
`pnpm list -r --depth -1 --json`

with the json flag it remove the path
