### ISSUE TITLE
Dependencies of workspace dependencies don't get installed

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [pnpm/pnpm#3443]
### Code to reproduce the issue:
Link to example repo: https://github.com/ChocolateLoverRaj/pnpm-bug

### Expected behavior: 
`packages/a/node_modules` should contain `last-element`, and `packages/b/node_modules` should too.

### Actual behavior:
`packages/a/node_modules` contains `last-element`, but `packages/b/node_modules` doesn't.

### Additional information:

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: Windows

**Comment by mcmxcdev** [comment]
Works fine with pnpm 7.28.0:
![image](https://user-images.githubusercontent.com/16797721/221381071-6d948ab1-1759-406c-bbe6-9c58b119d811.png)
