### ISSUE TITLE
Automatically link missing dependency when the dependencies are taken from the registry

### ISSUE THREAD

**Issue by jczapiewski-cksource** [pnpm/pnpm#3447]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer, I often want to link only dependencies that are not in the npm registry. A package contains a dependency in version `1.0.1` but the latest release of this dependency is `1.0.0` because I've made some changes and the dependency module is not released yet. (I'm using `link-workspace-packages = false` in the `.npmrc` file)

**Describe the solution you'd like**

The perfect solution would be to install all of the dependencies from the registry if they exist and link them otherwise (maybe with some kind of log that the dependency is actually linked). I think this can be described as a variation of `prefer-workspace-packages` like `prefer-registry-packages`

**Describe the drawbacks of your solution**

To be honest I don't have a solution for now so any workaround would be great as well.

**Describe alternatives you've considered**

I was trying manual linking of non-existing in the repository package and install the rest of the dependencies but without success, because `pnpm` still wants to install the linked dependency again.

**Comment by zkochan** [comment]
So you want `link-workspace-packages=false` but if the package is not found in the registry, link it from the workspace?

Why not just using the workspace protocol for those packages? That will explicitly tell pnpm to link those packages from the workspace: https://pnpm.io/workspaces#workspace-protocol-workspace

**Comment by jczapiewski-cksource** [comment]
> So you want link-workspace-packages=false but if the package is not found in the registry, link it from the workspace?

Exactly

> Why not just using the workspace protocol for those packages? That will explicitly tell pnpm to link those packages from the workspace: https://pnpm.io/workspaces#workspace-protocol-workspace

It may work as a workaround but this requires manual changes in the `package.json` files because it has to be reverted from `workspace:1.0.1` to `1.0.1` to prevent linking on CI. I was wondering if it is possible to make this work automatically (without adding custom scripts that change the dependency entry in the `package.json` file or changing this manually)

**Comment by zkochan** [comment]
I don't understand. You want it to work one way locally and differently on CI?

**Comment by jczapiewski-cksource** [comment]
I mean, on CI, the new version of the package will be published before installing anything else so there is no problem with CI. I just don't want to change manually (and locally) version of the package eg. from `1.0.1` to `workspace:1.0.1` because I will have to remember about that before the commit/creating a PR.

**Comment by zkochan** [comment]
I assumed you have a monorepository with a pnpm workspace configured in it. So that is no the case? What is your setup?

**Comment by jczapiewski-cksource** [comment]
Yes, I have a monorepo configured using `pnpm`. The repository contains two main directories: `modules` and `services`. 

Starting app flow:
1. install only services `pnpm i --filter {services}`
2. build only services `pnpm i --filter {services}` 
3. Start the services

Working locally with dependencies from `modules` directory flow:
1. Bump a version of a module that should be linked
2. Install dependencies in the module that should be linked (btw if You skip this step, the module dependencies get linked even when `link-workspace-packages = false` is set)
3. Link package from `modules` directory to the package from the `services` directory - `cd services/service1 && pnpm link @company-name/package-name`
4. Rebuild/restart service

This works like a charm if You are the one that makes changes in the `modules` package. The problem is when You checkout a branch with such changes because You were not able to install `services` dependencies unless You change the package from `modules` directory version to `workspace:version` or to last version that was published to the registry.

**Comment by zkochan** [comment]
> install only services pnpm i --filter {services}

I do not recommend using `pnpm install` with filtering if you have a shared lockfile in the root of the repository.

> build only services pnpm i --filter {services}

Do you mean `pnpm build --filter {services}`?

> Bump a version of a module that should be linked

Why is this step needed? You bump the version of a module before making new changes to it? Seems unusual.

***

I still don't get it. Seems like you have some non-standard setup. Why can't you just use the standard workspace ranges that will link modules both locally and on CI? The workspace ranges will be automatically converted to regular semver ranges on publish, if you use `pnpm publish` for releasing.

**Comment by jczapiewski-cksource** [comment]
I've split my problem into two parts:
- I'm getting packages that are not released yet with a newer version and cache them in kind of a config file
- During install I have a custom `readPackage` hook where I replace the dependency version with `workspace:*` during install

Anyway, as You have said, it is a rare case and a non-standard setup. In addition, I've found a working solution so I'm closing this for now. Thanks for Your help.
