### ISSUE TITLE
link --global breaks all global modules

### ISSUE THREAD

**Issue by farfromrefug** [pnpm/pnpm#3462]
### Code to reproduce the issue:
run `pnpm link --global` in yourdep
run `pnpm link --global yourdep` in the project you want to use it
as soon as you do that your global plugins  are broken (like pnpm if you install it globally through pnpm, or yarn...)

was working fine with 6.1.0 though I can't really easily rollback as it would break ally stores.
so can't use link anymore.

**Comment by Kadeluxe** [comment]
Yes, it also doesn't work for me at all.

**Comment by owl-from-hogvarts** [comment]
Had this issue on pnpm 6.8 but updating to lates version seems to fix it

**Comment by owl-from-hogvarts** [comment]
*fix about a half. Still in some cases all things go wrong

**Comment by Coodool** [comment]
same problem

**Comment by zkochan** [comment]
I work on it

**Comment by zkochan** [comment]
:ship: 6.10.1
