### ISSUE TITLE
The result of hoist different with yarn

### ISSUE THREAD

**Issue by GitaiQAQ** [pnpm/pnpm#3466]
### Code to reproduce the issue:

```shell
$ yarn add dom-serializer@0.1.0 domhandler@4.2.0
yarn list v1.22.4
├─ dom-serializer@0.1.0
│  ├─ domelementtype@~1.1.1 -> 1.1.3
│  └─ entities@~1.1.1
├─ domelementtype@2.2.0
├─ domhandler@4.2.0
│  └─ domelementtype@^2.2.0

$ pnpm add dom-serializer@0.1.0 domhandler@4.2.0
dom-serializer 0.1.0
├── domelementtype 1.1.3
└── entities 1.1.2
domelementtype 1.1.3
domhandler 4.2.0
└── domelementtype 2.2.0
```

### Expected behavior:

like yarn, hoisting domelementtype@2.2.0 of domhandler to top

### Actual behavior:

hoisting domelementtype@1.1.3 of dom-serializer to top

### Additional information:

Maybe sort the dependencies at the same layer by package reference after `hoistGraph` sorted can fix it

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by merceyz** [comment]
This isn't a bug, which one getting hoisted to the root doesn't matter since both layouts are valid. The latest version of Yarn (3.0.1) gives this layout:
```
├─dom-serializer@0.1.0
├─domelementtype@1.1.3
├─domhandler@4.2.0
│ ├─domelementtype@2.2.0 - filled by: domelementtype@1.1.3 at .
├─entities@1.1.2
```

**Comment by fortezhuo** [comment]
@GitaiQAQ 

I have similar issue and solve this problem with add ```.npmrc``` file on root of project

```
node-linker=hoisted
```

**Comment by zkochan** [comment]
Yes, this is correct. If you need a hoisting similar to Yarn's one, use `node-linker=hoisted`.
