### ISSUE TITLE
Add shortened alias for --filter

### ISSUE THREAD

**Issue by nategreen** [pnpm/pnpm#3467]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I type `--filter` quite a bit in my monorepo. Some percentage of the time, I type `--filter` instead. Plus, it's just kind of lengthy when I also need to type a package name / folder / etc. I'd love to just type something shorter, like I can for `-f` (force) or `pnpm i`.

**Describe the solution you'd like**

I'm not sure what would be a suitable letter for it. Since `--force` is taking up `-f`, maybe `-F` would be a good shortened version.

**Describe the drawbacks of your solution**

It's fairly close to `-f` for `--force` and if you mess it up that could have bad consequences.

**Describe alternatives you've considered**

Maybe `-i` because it's the next letter in "filter", or `-m` that might mentally map to "match."

**Comment by zkochan** [comment]
I would probably use `-f` but it will be a breaking change.

**Comment by zkochan** [comment]
@pnpm/collaborators should we make `-f` a short alias of `--filter` instead of `--force`? `--force` is not frequently used. But `--filter` is really frequent.

**Comment by kenrick95** [comment]
Mentally, it's true that `-f` generally meant `--force`, however if it's not frequently used in pnpm, then I'm fine with changing it to `--filter`.

**Comment by sodatea** [comment]
The only documented usage of `--force` is in `pnpm publish`: https://pnpm.io/cli/publish#--force
In npm there's a `--force` flag for `npm install` and `npm init`. pnpm also supports it in these commands.

So I think it's fine to make `-f` alias for `--filter` in most cases, but for these 3 commands, it would be ambiguous.

**Comment by nategreen** [comment]
Sorry to butt in, just throwing this out there though because I agree changing -f for install and such might be ambiguous/unexpected. What about:

- providing an argument to recursive / -r? (Would it be weird to provide a value to a shorthand argument? 🤔)
- changing the name to something that doesn't start with F, e.g. "--select," "--packages," etc.?

**Comment by kenrick95** [comment]
> changing the name to something that doesn't start with F

As some examples, Lerna & Turborepo uses `--scope` (with no shortcut)

**Comment by zkochan** [comment]
Is big `-F` OK? Here is a PR: https://github.com/pnpm/pnpm/pull/4342
