### ISSUE TITLE
ESLint + pnpm = Cannot read config file (non-existent path)

### ISSUE THREAD

**Issue by cybairfly** [pnpm/pnpm#3471]
### pnpm version:
+ pnpm 6.4.0

### Expected behavior:
ESLint config be loaded from valid location

### Actual behavior:
ESLint is looking up the config in a location that does not exist in the hierarchy created by `pnpm`
```
[Info  - 4:46:04 PM] Cannot read config file: D:\Apify\apify-robot\node_modules\.pnpm\@apify\eslint-config@0.1.4_eslint@7.26.0\node_modules\@apify\eslint-config\index.js Error: ENOENT: no such file or directory, open 'D:\Apify\apify-robot\node_modules\.pnpm\@apify\eslint-config@0.1.4_eslint@7.26.0\node_modules\@apify\eslint-config\index.js' Referenced from: D:\Apify\apify-robot\.eslintrc.json
```

Path really does not exist, instead there is `.pnpm/@apify+eslint-config@0.1.4_eslint@7.26.0`

### Additional information:
Win 10 / Node v14.16.0
ESLint config (.eslintrc):
```
    "extends": [
        "@apify"
    ],
```

**Comment by zkochan** [comment]
Just remove node_modules and run `pnpm install`.

The paths in virtual store changed in v6, so probably you installed node_modules with pnpm v5 and then switched to pnpm v6

**Comment by partounian** [comment]
I'm having a similar issue, even after uninstall pnpm, clearing pnpm store, clearing node_modules, and running npm or yarn. 

Did this multiple times in different ways, but still eslint is trying to search in a nonexistant `node_modules/.pnpm` location
