### ISSUE TITLE
Download Node.js from nodejs.org

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#3473]
[As noted](https://github.com/pnpm/pnpm/discussions/3434#discussioncomment-752975) by @woss, installing Node.js from the npm registry is not the best solution but it is much faster to implement.

In the future we'll use https://nodejs.org/download/release/index.json to resolve the version of Node.js and download Node.js from the nodejs org, not from the npm registry.

_Originally posted by @zkochan in https://github.com/pnpm/pnpm/issues/3459#issuecomment-843631333_

**Comment by mcmxcdev** [comment]
It seems this ticket was resolved in https://github.com/pnpm/pnpm/pull/3475 but never closed.
