### ISSUE TITLE
pnpx: command not found when trying to run @vue/cli

### ISSUE THREAD

**Issue by rubens-lopes** [pnpm/pnpm#3487]
### pnpm version:
6.4.0
### Code to reproduce the issue:
`pnpx @vue/cli ui`

### Expected behavior:
Need to install the following packages:
@vue/cli
Ok to proceed? (y) y
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
🚀  Starting GUI...
🌠  Ready on http://localhost:8000

### Actual behavior:
pnpx @vue/cli ui                                                                                                                                             127 ✘
✔ Install the following package: @vue/cli@latest? (Y/n) · true

Downloading registry.npmjs.org/typescript/4.1.5: 10.2 MB/10.2 MB, done
Packages: +853
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
Content-addressable store is at: /home/rubens/.pnpm-store/v3
Virtual store is at:             node_modules/.pnpm
Progress: resolved 853, reused 655, downloaded 198, added 853, done
node_modules/.pnpm/ejs@2.7.4/node_modules/ejs: Running postinstall script...
node_modules/.pnpm/core-js-pure@3.13.1/node_modules/core-js-pure: Running postinstall script...
node_modules/.pnpm/@apollo+protobufjs@1.2.2/node_modules/@apollo/protobufjs: Running postinstall script...
node_modules/.pnpm/ejs@2.7.4/node_modules/ejs: Running postinstall script, done in 61mssability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods insteanode_modules/.pnpm/core-js-pure@3.13.1/node_modules/core-js-pure: Running postinstall script, done in 87ms
node_modules/.pnpm/@apollo+protobufjs@1.2.2/node_modules/@apollo/protobufjs: Running postinstall script, done in 69ms

/home/rubens/.pnpm-store/v3/tmp/_npx/46102/5:
+ @vue/cli 4.5.13
npx: command not found: cli
### Additional information:

 - `node -v` prints: 14.16.1
 - Windows, macOS, or Linux?: 
 DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.5
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/4682
