### ISSUE TITLE
pnpx swallow error &  exit code

### ISSUE THREAD

**Issue by hardfist** [pnpm/pnpm#3498]
### pnpm version:
6.0.2
### Code to reproduce the issue:
![image](https://user-images.githubusercontent.com/8898718/120449278-dedc0e00-c3c1-11eb-8319-e71ab5ffd326.png)

### Additional information:

 - `node -v` prints: 15.14.0
 - Windows, macOS, or Linux?: macOS

**Comment by bajtos** [comment]
I checked older versions, apparently the problem was introduced in `pnpm@6.20.4`. AFAICT, the last working version is `pnpm@6.20.3`.

**Comment by zkochan** [comment]
Try to use `pnpm dlx` or `pnpm exec` instead. They should now work as expected.
