### ISSUE TITLE
Implement `pnpm init` (instead of passing through to `npm init`)

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#3505]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

Currently `pnpm init` is just passing through to `npm init`. If we implement our own `pnpm init`, we may add two nice features:

* We can pin the Node.js version automatically via the [use-node-version](https://pnpm.io/npmrc#use-node-version) setting in `.npmrc`
* We can pin the pnpm version via `engines.pnpm` in `package.json`.

**Comment by gbieging** [comment]
relatedly `pnpm init` does not work if node is installed without npm

**Comment by fireairforce** [comment]
Expected~

**Comment by zkochan** [comment]
The `pnpm init` command was implemented.
