### ISSUE TITLE
Cannot authenticate with .npmrc in repository with pnpm publish 6.7.1

### ISSUE THREAD

**Issue by mewhhaha** [pnpm/pnpm#3508]
### pnpm version: 6.7.1
We have a monorepo with a private npm registry (Azure Artifacts) that we publish to. We noticed that publishing started failing when we updated to pnpm version 6.7.1 and we managed to resolve the issue by reverting to the previous version. (6.6.2). We use an Azure Pipeline where we use the [npm authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops) which updates the .npmrc in the downloaded repository that we try to publish from.

It seems to exhibit the same behaviour if I do it locally, by having the authentication in the .npmrc file in the root of the repository.

### Code to reproduce the issue:

I'm sure the --no-git-checks isn't necessary, but that's the command we run.

```bash
pnpm -r publish --no-git-checks
```

### Expected behavior:
Publishing to pass as in version 6.6.2

### Actual behavior:
```bash
npm ERR! code E401
npm ERR! Unable to authenticate, need: Bearer authorization_uri=[AUTHORIZATION_URI], Basic realm="[REALM]", TFS-Federated
```

### Additional information:

npm@6.14.11
node@v14.16.0

Our .npmrc file that gets the authentication appended to it looks like the following
```
registry=[PRIVATE REGISTRY]
always-auth=true
engine-strict=true
recursive-install=true
shell-emulator=true
strict-peer-dependencies=true
```

**Comment by zkochan** [comment]
The regression was caused by this change: #3497

**Comment by zkochan** [comment]
npm 7 has workspace support, maybe if you add the workspaces field that npm understands, to the root package.json, maybe then `npm publish` will read the root `.npmrc` (pnpm run `npm publish` under the hood)

**Comment by zkochan** [comment]
:ship: 6.7.3

**Comment by jarrodjperez** [comment]
I see that this issue has been closed, but we're still having issues publishing after updating to pnpm version 6.7.x. In the example below, we're using node 14.16.1 and npm 7.10.0. If we revert back to pnpm version 6.6.2, all works well. Happy to share any other details that may help. Thanks for all your hard work on this library, it's been great to work with.

<img width="925" alt="Screen Shot 2021-06-14 at 11 44 05 AM" src="https://user-images.githubusercontent.com/1613581/121929469-dc08e380-cd06-11eb-8feb-858fe2ed3fb2.png">
