### ISSUE TITLE
Test library projects by doing normal installs instead of workspace-linking

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#3510]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

## Describe the user story

My PNPM workspace has a project whose package.json looks like this:

**packages/P/package.json**
```js
{
  "name": "P",
  "version": "1.2.3",
  "peerDependencies": {
    "typescript": "3.x || 4.x"
  },
  "devDependencies": {
    "typescript": "4.0.0"
  }
}
```

It is consumed by another project like this:

**packages/A/package.json**
```js
{
  "name": "A",
  "version": "1.2.3",
  "dependencies": {
    "react": "*",
    "W": "workspace:*",   // W is some other local project
    "P": "workspace:*"
  },
  "devDependencies": {
    "typescript": "3.0.0"
  }
}
```

When I run `pnpm install`, `A`'s dependency on `P` is a symlink to the local workspace project.  As a result, `A`'s instance of `P` depends on TypeScript 4.  Whereas a "normal" installation from an NPM registry would satisfy `"typescript": "3.x || 4.x"` using TypeScript 3 as specified by `A`. 

As a result, testing `A` does NOT accurately test the experience of people who install `P` after it is published.

## Describe the solution you'd like

Here are four alternatives I considered:

1. **Separate repos option:** The obvious solution would be to move `A` to a separate Git repo that installs `P` from an NPM registry.  However this defeats the main benefit of monorepos, that ***we want to test a PR before it is merged*** not after it is already merged+published.

2. **Local publishing option:** Another idea would be to make a "unit test" that publishes `P` to [Verdaccio](https://verdaccio.org/), then installs a separate **pnpm-lock.yaml** for `A`.  This is the most authentic test, but it is slow and quite a lot of overhead during a build.  Also **pnpm-lock.yaml** will have `resolution.integrity` hashes that churn with each update.

3. **Tarball option:** Verdaccio could be eliminated by using tarball specifiers like `"P": "file:../P/p.tgz"` that gets created using `pnpm pack`.  Details in the [Discord thread](https://discord.com/channels/731599538665553971/747905674578624633/850538179819733032).  I tried this, but it runs into problems with chains of dependencies on other workspace projects -- they all need to have tarballs, and they all need `pnpmfile.js` fixups to substitute the `file:` path for the SemVer range.  Also **pnpm-lock.yaml** will have `resolution.integrity` hashes that churn with each update.

4. **Normal installs option:**  Imagine instead that `pnpm install` behaves as if  `P` version `1.2.3` exists in the NPM registry, simulated using whatever `pnpm pack` would produce from that folder.  Then `A` would get a copy of `packages/P/` with TypeScript 3 correctly wired up.  The main downside is that this copy would not reflect subsequent changes to `packages/P/`.  In particular, if `packages/P/lib/*.js` does not exist until after that folder has been compiled, then `A/node_modules/P/lib/index.js` will not be created by `pnpm install`.  But we can fix this up relatively easily.

## "Normal installs" option in detail

1. `A` needs to indicate somehow that `P` should be installed differently. We can use the `workspace:` specifier for that:

   **packages/A/package.json**
   ```js
   {
     "name": "A",
     "version": "1.2.3",
     "dependencies": {
       "react": "*",
       "W": "workspace:*",
       "P": "workspace-copy:*"  // <--- request this new feature
     },
     "devDependencies": {
       "typescript": "3.0.0"
     }
   }
   ```

2. With this change, when we invoke `pnpm install` for the workspace, the `node_modules` folder will get installed as follows:

   - `A/node_modules/react/` gets symlinked to `monorepo/node_modules/.pnpm/react@1.2.3/node_modules/react/`    as usual
   - `A/node_modules/W/` gets symlinked to `monorepo/packages/W/` as usual
   - `A/node_modules/P/` now gets symlinked to `monorepo/node_modules/.pnpm/P@1.2.3/node_modules/P/` instead of workspace-linking. The version 1.2.3 is obtained from `packages/P/package.json`.  

   This plan is recorded in `pnpm-lock.yaml` but WITHOUT tracking `resolution.integrity` for `A`'s dependency on `P`.

   The contents of `.pnpm/P@1.2.3/node_modules/P/` are what `pnpm pack` would select, and because `P` has not been compiled yet, the `node_modules/P/lib/index.js` file is missing initially.

3. After `P` is compiled, its build script will run `pnpm workspace-copy` in the `packages/P/` folder.  This proposed new command will copy the `pnpm pack` file set into the appropriate `node_modules` subfolders.

4. Now when `A` is compiled, it can import the current build from `monorepo/node_modules/.pnpm/P@1.2.3/node_modules/P/lib/index.js`

CC @zkochan

**Comment by octogonz** [comment]
The **Tarball option** also has a problem that when `.pnpmfile.cjs` replaces the versions with `file:` specifiers, they must be an absolute path.  If I use a relative path, it gets resolved relative to the `package.json` file location, and this information is not obtainable inside the `.pnpmfile.cjs` hook.  (Maybe the hook could read this from `context.packageJsonPath`?)

When I use absolute paths, they end up in the `pnpm-lock.yaml` the `importers` section like this:

```yaml
lockfileVersion: 5.3

importers:

  typescript-newest-test:
    specifiers:
      '@rushstack/eslint-config': file:C:/Git/rushstack/build-tests/install-test-workspace/temp/tarballs/rushstack-eslint-config-2.3.4.tgz
      '@rushstack/heft': file:C:/Git/rushstack/build-tests/install-test-workspace/temp/tarballs/rushstack-heft-0.31.1.tgz
      eslint: ~7.12.1
      tslint: ~5.20.1
      typescript: ~4.3.2
    devDependencies:
      '@rushstack/eslint-config': file:../temp/tarballs/rushstack-eslint-config-2.3.4.tgz_eslint@7.12.1+typescript@4.3.2
      '@rushstack/heft': file:../temp/tarballs/rushstack-heft-0.31.1.tgz
      eslint: 7.12.1
      tslint: 5.20.1_typescript@4.3.2
      typescript: 4.3.2
```

As mentioned in my writeup, the `resolution.integrity` field also churns this file:
```yaml
  file:../temp/tarballs/rushstack-eslint-config-2.3.4.tgz_eslint@7.12.1+typescript@4.3.2:
    resolution: {integrity: sha512-wC0cVQfZ9LDCtLoYh61T9kPWLI1mGxcBOVE8lzrcIsrvpPvBaojHSwFt1yyC5mIRr2x1HtzkX+m2Gyfkft8fOQ==, tarball: file:../temp/tarballs/rushstack-eslint-config-2.3.4.tgz}
    id: file:../temp/tarballs/rushstack-eslint-config-2.3.4.tgz
    name: '@rushstack/eslint-config'
```

Either way I will need to rewrite the `package-lock.yaml` file to fix these problems, but it is pretty hacky.

I am implementing the **Tarball option** as my workaround for now.  But **Normal installs option** seems like a much cleaner solution.

**Comment by octogonz** [comment]
The **Tarball option** also has a problem that `pnpm install` ignores changes to the .tgz files, even if the `resolution.integrity` has changed or is entirely missing from `pnpm-lock.yaml`.  To work around this, I have to delete `workspace/node_modules/.pnpm/local+*` which matches folder names like `local+C++Git+rushstack+build-tests+install-test-wo_7efa61ad1cd268a0ef451c2450ca0351`.

**Comment by jonathanmorley** [comment]
You might be interested in looking at https://www.npmjs.com/package/package-preview

**Comment by octogonz** [comment]
I looked at `package-preview` but it only links one project at a time, which is the current project.  Also it does another full installation, which is rather expensive compared to **Normal installs option**.  The **Tarball option** also has the problem of essentially doing another full installation.

**Comment by octogonz** [comment]
Here's one more idea:

5. **Tarballs without .pnpmfile.cjs option**:  Okay what if we take the idea of **Local publishing option** but eliminate the need for Verdaccio. You would put a bunch of tarballs in a folder, and then we enable PNPM to treat this folder like a registry proxy.  When `pnpm install`  is querying the NPM registry, it will first look in this tarball folder. Anything in that folder overrides whatever would normally be fetched from the registry. 

The behavior would be functionally similar to Verdaccio, but without the overhead of spinning up the Verdaccio service and configuring authentication and all that.

(With this approach, we'd still need a separate `pnpm install` and workspace, and we'd need to suppress integrity hashes.  But it is simpler than **Tarball option** and avoids Verdaccio problems.)

**Comment by octogonz** [comment]
After discussing this with more people, option 5 ("Tarballs without .pnpmfile.cjs") seems easier to explain, and probably most straightforward to implement.

However all of the "secondary workspace" approaches require `pnpm install` to update `node_modules` without churning `pnpm-lock.yaml`.  In detail, the  `--frozen-lockfile` requirements are like this:

1. I modify a .ts file and recompile
2. I "publish" my results by making a tarball. (Or with Verdaccio, I publish my project to the registry, ***overwriting*** the previous published version.)
3. As long as I didn't modify `package.json`, my update should NOT churn `pnpm-lock.yaml`.  (That would be annoying. Nor is it necessary to guarantee determinism.)
4. `pnpm install` is expected to install my new content, even though `pnpm-lock.yaml` has not changed.  How does that work?  The `pnpm-lockfile.yaml` stores an integrity hash for the tarball's `package.json` only, whereas the `node_modules` folder stores an integrity hash for the entire tarball.

In my prototype, #3 is accomplished by manually rewriting `pnpm-lock.yaml` .  And #4 is accomplished by manually deleting entries from PNPM's cache.  This is the same approach that classic `rush install` used (before PNPM workspaces). But that's a brittle workaround for a feature that PNPM can provide, I think.

So   to summarize the latest proposal, it has two parts:

- **Tarball folder that simulates a registry:**  Designate a folder containing tarballs, which PNPM will consult during installation.  Versions found there will take precedence over the normal NPM registry.
- **Relaxed `--frozen-lockfile` concept:**  For tarballs obtained from this folder, `pnpm-lock.yaml` stores an integrity hash of the **package.json** file.  The full integrity hash is instead tracked in the **node_modules** folder.

@zkochan would you accept PRs to implement these two features?

**Comment by zkochan** [comment]
In my opinion the 5 needs too many changes and it is hard to understand how it works.

I like option 4 more. It basically needs no changes to the lockfile format, just a new protocol.

**Comment by octogonz** [comment]
After merging my prototype, we encountered another issue: When we publish packages, the CI job automatically bumps versions for the various **package.json** files in the monorepo.  But the CI job does not update the secondary workspace, which results in a `--frozen-lockfile` error.

I suspect this problem would also be easier to solve with option 4.  @zkochan lemme see if I can find some time to make a PR to try out option 4.

**Comment by cefn** [comment]
I face a similar/identical issue. 

The libraries under the scope `@lauf` are managed in a monorepo, authored in Typescript but with a publishConfig that transpiles typescript into javascript and makes `dist/index.js` as the main file for each module. The npm registry versions (importable by both Javascript and Typescript) are therefore packaged quite differently from the locally-resolved workspace versions (which are only importable as Typescript). 

This has been fine for the current `apps` folder where they were all authored in Typescript. They got their dependencies resolved to `.ts` files by pnpm through local resolution when running in the filesystem, but they seamlessly resolved to the registry modules when running the app standalone in a Code Sandbox ( e.g. https://codesandbox.io/s/github/cefn/lauf/tree/main/apps/counter?file=/src/index.tsx ) 

The worm in the apple came when I tried to author an example ***javascript*** project in the repo - a `counter-js` equivalent to the Typescript one. When the local modules resolve to a `src/index.ts` main file this of course breaks the javascript interpreter. 

I was expecting was that putting a `.npmrc` with `link-workspace-packages = false` in the package folder of the Javascript app ( https://github.com/cefn/lauf/blob/javascript-counter/apps/counter-js/.npmrc ) would cause it to ACTUALLY RESOLVE to the registry version, rather than resolving to a registry-like version built from local sources. However, this didn't work either. As a workaround is there a way to force resolution to ACTUAL npm? Like the inverse of the `workspace:` protocol?

**Comment by cefn** [comment]
An alternative I attempted was to add the javascript app package to the exclude list. My aim was to stop the package being part of the workspace, so that it might be treated as a standalone package when I ran `pnpm install` and just get dependencies from npm like normal. 

```yaml
packages:
  # include
  - "apps/**"
  - "modules/**"
  # exclude
  - "!apps/counter-js/**"
```

This configuration seems to be broken, as attempting to run `pnpm install` from within the excluded directory attempts to install every package in the workspace (rather than running a standalone install as if the package wasn't in the workspace).

**Comment by bestickley** [comment]
@cefn, this isn't the cleanest solution, but I'm currently using `npm i` for packages "within" a workspace that are ignored in my `workspace.yaml`. For you this is `apps/counter-js`. My use case is I'm building a scaffolding library that adds a whole Node.js project. While developing it, I don't want it to be part of the workspace but I want to be able to test it out. Hope that helps!

**Comment by zkochan** [comment]
You may use pnpm as well to create a "classic" node_modules without symlinks: https://github.com/pnpm/pnpm/issues/4073

Use `node-linker=hoisted` since v6.25.0-2
