### ISSUE TITLE
brew pnpm 6.7.3 - no bottle available

### ISSUE THREAD

**Issue by Valexr** [pnpm/pnpm#3513]
### pnpm version: 6.7.3

![Screenshot 2021-06-08 at 17 27 31](https://user-images.githubusercontent.com/5656366/121203682-f8c49780-c87e-11eb-940c-f1f7b9627123.jpg)

**Comment by mcmxcdev** [comment]
Cannot reproduce this on macOS Big Sur.

If I run the same command, it downloads and installs `pnpm v6.32.3` successfully.
