### ISSUE TITLE
Bad interaction between pnpm, Parcel v2, and Preact hooks

### ISSUE THREAD

**Issue by rhendric** [pnpm/pnpm#3515]
### pnpm version:
6.7.3

### Code to reproduce the issue:

1. Clone https://github.com/rhendric/laughing-octo-potato
2. Run `pnpm i`
3. Run `parcel src/index.html`
4. Open http://localhost:1234 (assuming Parcel didn't tell you that it took a different port)

### Expected behavior:

A working demo. (You can see how the demo is supposed to work by replacing the `pnpm i` step with `npm i`.)

### Actual behavior:

The following error appears in the browser console:

    Uncaught TypeError: can't access property "__hooks", currentComponent is undefined

Furthermore, there are two copies of Preact in the bundled JavaScript that is served: one that has been minified, corresponding to `node_modules/preact/dist`, and one that has not, corresponding to `node_modules/preact/src`. (This would explain the above error.) As you can see from the demo's source code, I'm not importing `preact/src`. If I remove the import of `preact/hooks`, the `preact/src` copy disappears. So something about the resolution of `preact/hooks`, or perhaps the resolution of `preact` from within `preact/hooks`, is going wrong.

### Additional information:

 - `node -v` prints: v16.3.0
 - Windows, macOS, or Linux?: Linux

Also note that I'm using a beta release of Parcel (`2.0.0-beta.3.1`), and that could be where the actual problem is. But because I couldn't reproduce this issue with npm, I'm starting here. If you tell me that the Parcel package is doing something incorrect that npm happens to paper over, I'll believe it.

**Comment by mcmxcdev** [comment]
I assume it was related to the beta version.

I played around a bit to see if I can make this work:

- you can clone https://github.com/metonym/parcel-preact-typescript
- switch `parcel-bundler` with `parcel` v2
- add `type="module"` to `index.tsx` script in `index.html`
- replace code in index.tsx with e.g:

```
import { h, render } from "preact";
import { useReducer } from "preact/hooks";

const Counter = () => {
  const [val, inc] = useReducer((x) => x + 1, 0);
  return <p onClick={inc}>Click to increment: {val}</p>;
};

render(<Counter />, document.getElementById("root")!);
```

and after running `pnpm start` you should see the counter!

**Comment by rhendric** [comment]
Can confirm, the 2.0.0 release of Parcel seems to have fixed it.
