### ISSUE TITLE
Cannot run bin scripts when there are spaces in NODE_PATH (Windows)

### ISSUE THREAD

**Issue by miridius** [pnpm/pnpm#3519]
### pnpm version:

6.7.4

### Code to reproduce the issue:

1. Install Node in a path that includes spaces, in my case it was under "C:\Program Files (x86)\Nodist\bin"
2. Check that $NODE_PATH also has spaces. In my case `echo $NODE_PATH` prints:
    C:\Program Files (x86)\Nodist\bin\node_modules;C:\Program Files (x86)\Nodist\bin\node_modules;C:\Program Files (x86)\Nodist\bin\node_modules;%NODE_PATH%
3. Install dependencies with bin scripts in a pnpm managed project. Here's specifically what I did **(using Git Bash)**:
    ```sh
    pnpm init svelte@next my-app
    cd my-app
    pnpm install
    ```
4. Try to run a bin script (in my case I ran `pnpm dev`)

### Expected behavior:

bin scripts work

### Actual behavior:

bin scripts give this error (personal information replaced with [...]):

```sh
$ pnpm dev

> ~TODO~@0.0.1 dev C:\Users\[...]
> svelte-kit dev

\Nodist\bin\node_modules was unexpected at this time.

C:\Users\[...]>  @SET NODE_PATH=C:\Program Files (x86)\Nodist\bin\node_modules;C:\Program Files (x86)\Noders\[...]\.pnpm\@sveltejs+kit@1.0.0-next.113_svelte@3.38.2\node_modules\@sveltejs\kit\node_m+kit@1.0.0-next.113_svelte@3.38.2\node_modules\@sveltejs\node_modules;C:\Users\[...]\node_modules\.pnpm\@\[...]\node_modules\.pnpm\node_modules;C:\Users\[...]\node_modules;C:\Users\[...]\node_modules;C:\node_modules;C:\Users\[...]\node_modules\@sveltejs\kit\node_modules;C:\Users\[...]
 ERROR  Command failed with exit code 255.
```

### Fix / Workaround

I solved this issue for myself by hotfixing my installed copy of pnpm to add the missing quotes:
1. Edit `pnpm/dist/pnpm.cjs` (in the global node_modules folder), search for `@SET NODE_PATH=`, and add quotes around the right hand side in both places like so:
    ```js
          if (nodePath) {
            cmd += `@IF NOT DEFINED NODE_PATH (\r
      @SET NODE_PATH="${nodePath}"\r
    ) ELSE (\r
      @SET NODE_PATH="%NODE_PATH%;${nodePath}"\r
    )\r
    `;
    ```
2. Delete `node_modules` folder in my project and run `pnpm i` again

### Additional information:

 - OS: Windows 10
 - Shell: Git Bash
 - Node version manager: Nodist
 - Node: v16.3.0
 - npm: v7.15.1

**Comment by zkochan** [comment]
:ship: 6.7.5
you may probably test the fix by installing pnpm this way:

```
(Invoke-WebRequest 'https://unpkg.com/pnpm@6.7.5/dist/pnpm.cjs' -UseBasicParsing).Content | node - add --global pnpm
```

**Comment by zkochan** [comment]
6.7.5 is not correct

Quotes have to be used for the complete assignment, not for the value. (see https://ss64.com/nt/set.html)

So it should be `@SET "NODE_PATH=${nodePath}"\r`

**Comment by miridius** [comment]
Wow, thanks for the fast fix!

You are right that the way I did the quotations was wrong, and I realised this myself because when the command shim runs twice (bin script calling another bin script) it ended up doubling up the quotes and failing.

I actually in the mean time used a different workaround which was just to reinstall nodist in a path without spaces, but this will be helpful in future and for my other Windows using colleagues
