### ISSUE TITLE
pnpm audit process exits before flushing stdout

### ISSUE THREAD

**Issue by drtyh2o** [pnpm/pnpm#3526]
### Code to reproduce the issue:
```js
import { execSync } from 'child_process'

try {
  execSync('pnpm audit --json --audit-level=low')
} catch ({ stdout }) {
  const json = stdout.toString('utf-8')
  console.log('BYTES', json.length)
  console.log('JSON', json)
}
```

### Expected behavior:
The output of the child process running `pnpm audit` is available.

### Actual behavior:
The output of the child process is truncated (if the output is greater than 8192 bytes). 

### Additional information:

This problem only seems to occur on MacOS. I believe it's because the pnpm CLI calls `process.exit()` prior to stdout being fully flushed. See output truncated at 8192 bytes below:

<img width="1065" alt="Screen Shot 2021-06-10 at 9 45 26 AM" src="https://user-images.githubusercontent.com/3439869/121536799-61bc2480-c9d1-11eb-95f4-78b23cb74abc.png">

 - `node -v` prints: v15.11.0
 - Windows, macOS, or Linux?: MacOS

Here's an [example](https://github.com/microsoft/pyright/pull/1905) of how someone else resolved using `process.exitCode = 1` rather than `process.exit(1)`.

**Comment by zkochan** [comment]
Good investigation!

Probably we can do this change

**Comment by m1heng** [comment]
should we define a specific Error for process exit, and have extra logic in packages/pnpm/src/pnpm.ts

**Comment by zkochan** [comment]
I think all the exit calls happen in this file https://github.com/pnpm/pnpm/blob/main/packages/pnpm/src/main.ts

**Comment by m1heng** [comment]
> I think all the exit calls happen in this file https://github.com/pnpm/pnpm/blob/main/packages/pnpm/src/main.ts

I was think all internal exit should be replaced with throw error and being handled in pnpm.ts/pnpx.ts since they already have error handling logics. https://github.com/pnpm/pnpm/blob/918d23de785d45c88db8643a418ed2eac02b99e8/packages/pnpm/src/pnpm.ts#L70-L78

**Comment by zkochan** [comment]
No, that is not a good idea because some commands don't print an error just exit with a 1 exit code.

**Comment by m1heng** [comment]
I made a PR just fixing exit in `packages/pnpm/src/main.ts`.
But there are still exit logic `packages/plugin-commands-publishing/src/publish.ts` and `packages/plugin-commands-script-runners/src/exec.ts`, I am not really sure if these should be changed too.
