### ISSUE TITLE
vscode autocomplete give wrong import path

### ISSUE THREAD

**Issue by liuweiGL** [pnpm/pnpm#3547]
### pnpm version: 
6.7.6

### Code to reproduce the issue:
1. Init the reproduction
```shell
git clone git@github.com:liuweiGL/pnpm-reproduction.git
cd pnpm-reproduction
pnpm install
```
2. Open vscode editor
3. Open the `App.tsx` file
4. Use [autocomplete](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features):
![image](https://user-images.githubusercontent.com/21048878/122661688-85485180-d1bf-11eb-9351-af184954afe7.png)
5. Peek the tip:
![image](https://user-images.githubusercontent.com/21048878/122661706-ae68e200-d1bf-11eb-845e-fb79c92fdcde.png)

### Expected behavior:
The import path should be `react`.

### Actual behavior:
The import path is `.pnpm/@types+react@17.0.11/node_modules/@types/react`.

### Additional information:

 - `node -v` prints: v16.0.0
 - Windows, macOS, or Linux?: Windows

**Comment by mayase** [comment]
Hi, seems like autocomplete is powered by TypeScript project and and it doesn't work properly with typescript ^4.3
But it works as expected in ~4.2

Work is definitely is going on, there are several related issues and PRs like https://github.com/microsoft/TypeScript/pull/44259

**Comment by liuweiGL** [comment]
Thx your answer, there is another problem with `typescript@4.2.3`: #3550

**Comment by liuweiGL** [comment]
> Hi, seems like autocomplete is powered by TypeScript project and and it doesn't work properly with typescript ^4.3
> But it works as expected in ~4.2
> 
> Work is definitely going on, there are several related issues and PRs like [microsoft/TypeScript#44259](https://github.com/microsoft/TypeScript/pull/44259)
