### ISSUE TITLE
vscode autocomplete not working

### ISSUE THREAD

**Issue by liuweiGL** [pnpm/pnpm#3550]
### pnpm version: 
6.7.6

### Code to reproduce the issue:
1. Init the reproduction
```shell
git clone git@github.com:liuweiGL/pnpm-repoduction2.git
cd pnpm-reproduction2
pnpm install
```
2. Open vscode editor
3. Open the `App.tsx` file
4. Use [autocomplete](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features):
![image](https://user-images.githubusercontent.com/21048878/122697968-fb5cbf00-d278-11eb-93da-a19543089f27.png)
5. Move mouse over code:
![image](https://user-images.githubusercontent.com/21048878/122698000-0e6f8f00-d279-11eb-8e02-2dd78a2be138.png)

### Expected behavior:
Give tips like yarn:
![image](https://user-images.githubusercontent.com/21048878/122697620-462a0700-d278-11eb-8937-af5fc473c054.png)

### Actual behavior:
Nothing show me.

### Additional information:

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: Windows10
 - TypeScript: 4.2.3
 - Vscode: 
```node
版本: 1.57.1 (system setup)
提交: 507ce72a4466fbb27b715c3722558bb15afa9f48
日期: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by liuweiGL** [comment]
Working in typescript@4.4.x

**Comment by Maikuh** [comment]
I still have this issue even after installing typescript@4.4 (currently in beta)

**Comment by liuweiGL** [comment]
> I still have this issue even after installing typescript@4.4 (currently in beta)

Restart vscode?

**Comment by Maikuh** [comment]
> > I still have this issue even after installing typescript@4.4 (currently in beta)
> 
> Restart vscode?

Been there, done that. Same behavior as with v4.3.5. If you'd like to see my solution, see [this issue](https://github.com/pnpm/pnpm/issues/3671).

Thanks.
