### ISSUE TITLE
pnpm doesn't respect workspace package `peerDependencies`

### ISSUE THREAD

**Issue by hanford** [pnpm/pnpm#3558]
Hello, first of all, thank you for all of the continued improvements and work on/around PNPM!

I'm building a design system adjacent to an application in a monorepo and I noticed some unexpected behavior around peerDependencies / externals / singletons packages.

Given this situation:

I have many design system components that rely on libraries provided by the host application (react, emotion, next). I'm utilizing Rollup to compile my design system, marking specific libraries as "external" (tl;dr, their require/import statements will remain, so the host can resolve them). But due to the symlink/pointer setup, they're not resolved properly.

It seems like what happens is the design-system and root level `node_modules` are checked for the "external" dependencies, but not app's (where they actually are).

```yaml
packages:
  - 'app/**'
  - 'design-system/**'
```

```
|-- package.json
|-- node_modules
|-- app
    |-- node_modules
		|-- 
		|-- 
    |-- package.json
    |-- pages
    |-- ....
|-- design-system
    |-- dist
        |-- Button.min.js
        |-- Input.min.js
    |-- package.json
    |-- node_modules
    |-- src
        |-- Button
        |-- Input
        |-- ...
```

The situation gets a little more interesting:

In my design system, I actually do have these dependencies for running tests and an application for viewing the design system.

So at App runtime, these dependencies **do** resolve, but to their local `node_modules`, not the hosts. For some dependencies this could be OK, but a lot browser dependencies are stateful, and running many instances of them can be problematic.

...

### Code to reproduce the issue:
https://github.com/hanford/pnpm-peer-deps

### Expected behavior:
When I'm running the `App` I'd like my packaged dependencies (design system) to utilize dependencies from `App`'s node_modules. When I'm working in `design system`, I'd like these modules to resolve to their local node_modules (if they're devDeps).

### Actual behavior:
When I'm in `App`, my packaged dependency (design system) get it's node module peerDependencies from either it's node_module directory OR the root level node_module directory NOT the `App` node_module directory.

### Additional information:

- Node 14+
- Mac OS

This is a possible duplicate of these issues:
https://github.com/pnpm/pnpm/issues/3102
https://github.com/pnpm/pnpm/issues/2174

... Feel free to close if so!

**Comment by hanford** [comment]
I was able to "resolve" this, by removing the external dependencies from both the `app` and `design system` and installing them in the workplace root which feels like hack 🤔

**Comment by ekosz** [comment]
@zkochan It seems this (and the other linked `peerDependencies` issues) are from how pnpm treats `workspace` packages. 

From my understanding when one does `"b": "workspace:*"` from package "a" it creates `link:` from "a"'s `node_modules` to the source code location of "b"? So something like:

```
|-- package.json
|-- pnpm-workspace.yaml
|-- node_modules
    |-- .pnpm
        |-- cors@2.8.5
            |-- node_modules
                |-- cors
                    | -- ...
|-- a
    |-- node_modules
		|-- b -> b (source code)
        |-- cors -> node_modules/.pnpm/cors@2.8.5/node_modules/cors
		|-- ...
    |-- package.json
    |-- ....
|-- b
    |-- package.json
    |-- node_modules
        |-- ...
```

Is there a reason we can't treat workspace packages similarly to npm packages? So we get to use the same node module resolution algorithm that is normally used for all other deps? I.E:

```
|-- package.json
|-- pnpm-workspace.yaml
|-- node_modules
    |-- .pnpm
        |-- cors@2.8.5
            |-- node_modules
                |-- cors
                    | -- ...
        |-- b@1.0.0
            |-- node_modules
                |-- b (sym/hardlink to source?)
|-- a
    |-- node_modules
		|-- b -> node_modules/.pnpm/b@1.0.0/node_modules/b
        |-- cors -> node_modules/.pnpm/cors@2.8.5/node_modules/cors
		|-- ...
    |-- package.json
    |-- ....
|-- b
    |-- package.json
    |-- node_modules
        |-- ...
```

If you think this would be alright, I would be happy to try and open a PR for this change. Where in the pnpm source should I start looking? Thank you!

**Comment by zkochan** [comment]
> Is there a reason we can't treat workspace packages similarly to npm packages?

You can turn symlinking off by setting [link-workspace-packages](https://pnpm.io/cli/recursive#--link-workspace-packages) to `false`. But in that case when you make some local changes in package b, you will not get them in the dependencies of package a.

Your proposed solution could work with hard links. If package b would be hard linked to the node_modules. But I do not think it is justified. It would make everything a lot more complex.

I would suggest to install the dependencies that are used as peer dependencies via exact versions. In that case they will be symlinked from the same place and they will be singletons throughout the monorepository. You can use syncpack or [@pnpm/meta-updater](https://github.com/pnpm/meta-updater) to setup some linting and force the single version of the package in all projects.

**Comment by Measy** [comment]
> You can turn symlinking off by setting [link-workspace-packages](https://pnpm.io/cli/recursive#--link-workspace-packages) to `false`. But in that case when you make some local changes in package b, you will not get them in the dependencies of package a.

@zkochan If a package only exists locally and does not publish to npm registry, set link-workspace-packages to false doesn't work; in some cases, we will extract the public code used in the entire monorepo workspace into a local package and not publish it; In our case, the package is stored locally for sharing public utils, not publish to npm registry, we just share utils code such as `"email-libs": "workspace: *"` between several e-mail related projects in monorepo workspace.

**Comment by zkochan** [comment]
You can set link-workspace-packages to false. And you can use the workspace protocol to force linking some packages from the repository. `"email-libs": "workspace:*"` will work regardless how you set the link-workspace-packages setting

**Comment by Measy** [comment]
@zkochan Thanks!  Yes,  `"email-libs": "workspace:*"` will work regardless how the link-workspace-packages setting；
There are still troubles in my scene and I don't know how to solve them 😣

Let's say I have packages `email-page1-react17`, `email-page2-react16` and `email-libs`

Both `email-page1-react17` and `email-page2-react16` use `email-libs` by `"email-libs": "workspace:*"` from local,

`email-page1-react17/package.json`
```json
{
  "name": "email-page1-react17",
  "dependencies": {
    "email-libs": "workspace:*",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

`email-page2-react16/package.json`
```json
{
  "name": "email-page2-react16",
  "dependencies": {
    "email-libs": "workspace:*",
    "react": "^16.14.0",
    "react-dom": "^16.14.0"
  }
}
```

`email-libs/package.json`
```json
{
  "name": "email-libs",
  "peerDependencies": {
    "react": ">=16.9.0",
    "react-dom": ">=16.9.0"
  }
}
```

In this case, `email-page1-react17` and `email-page2-react16`  run dev/build and can't resolve 'react', because it just link 
pages project's node_modules `email-libs` to the source code location of `email-libs`, and there is no "react" or "react-dom"
Here is the repo show the case: https://github.com/Measy/rush-pnpm-peer-workspace

Related: https://github.com/pnpm/pnpm/issues/2174

Thanks for reply！

**Comment by zkochan** [comment]
I guess the only solution in this case would be to make some script that would copy email-libs to another directory.

So you would have email-libs-react16 with react 16 in dev dependencies.

And you would have email-lib-reac17 with react 17 in dev dependencies. And some script would sync the source code of the two versions of email-lib.

**Comment by Measy** [comment]
@zkochan  Thanks for reply！Yes, I have thought about doing this, but it seems not so monorepo, like reuse the code with some hack skill. Treat workspace packages similarly to npm packages with hard links , does it look more reasonable or cognitive, although it make everything a lot more complex.

**Comment by zkochan** [comment]
This is now possible to do with the [injected feature](https://pnpm.io/package_json#dependenciesmetainjected)
