### ISSUE TITLE
Running similar commands with wildcard selector

### ISSUE THREAD

**Issue by seahindeniz** [pnpm/pnpm#3563]
**Describe the user story**

In a scenario, running multiple commands that has the same prefix, must be done by specifying multiple times unnecessarily.
For example, consider the following command list:
- test:abc
- test:bcd
- test:cde
- test:def
- lint:ts
- lint:style
- lint-ci
- lint-ci:ts
- lint-ci:style
- lint-fix
- lint-fix:ts
- lint-fix:style

In order to run `test`-related commands in one command, I have to declare a command that runs `pnpm test:abc && pnpm test:bcd && pnpm test:cde && pnpm test:def`. For the `lint` commands, I may have to use something like this:
```json
{
  "lint": "pnpm lint:ts && pnpm lint:style",
  "lint:ts": "eslint ./src/**/*.{ts,tsx}",
  "lint:style": "stylelint ./src/**/*.{css,scss}",

  "lint-ci": "pnpm lint-ci:ts && pnpm lint-ci:style",
  "lint-ci:ts": "pnpm lint:ts -- --quiet",
  "lint-ci:style": "pnpm lint:style -- --quiet",

  "lint-fix": "pnpm lint-fix:ts && pnpm lint-fix:style",
  "lint-fix:ts": "pnpm lint:ts -- --fix",
  "lint-fix:style": "pnpm lint:style -- --fix"
}
```

**Describe the solution you'd like**

I prefer running these commands by using a much shorter command, something like `pnpm test:*` to run in sequence or maybe `pnpm test:* --parallel` and even maybe `pnpm -r test:*` to run it across the workspace, or have a structure like this:
```json
{
  "lint": "pnpm lint:*",
  "lint:ts": "eslint ./src/**/*.{ts,tsx}",
  "lint:style": "stylelint ./src/**/*.{css,scss}",

  "lint-ci": "pnpm lint-ci:*",
  "lint-ci:ts": "pnpm lint:ts -- --quiet",
  "lint-ci:style": "pnpm lint:style -- --quiet",

  "lint-fix": "pnpm lint-fix:*",
  "lint-fix:ts": "pnpm lint:ts -- --fix",
  "lint-fix:style": "pnpm lint:style -- --fix"
}
```

**Describe the drawbacks of your solution**

Well,
- the `lint` example might be an awkward case
- a freshman may not figure out the syntax at first and may argue with the wildcard syntax

**Describe alternatives you've considered**

As an alternative, I have considered using [concurrently](https://www.npmjs.com/package/concurrently). It provides a similar solution but after all, it isn't pnpm

**Comment by jcayzac** [comment]
I'd also love this. I've used `concurrently` and `npm-run-all` to achieve this but:

1. It's another thing to learn.
2. Integration has lots of issues (stream management, colors…)
3. Running scripts is part of node package management —I don't _want_ to use another tool.
4. Changes to pnpm would be minimal and have no impact on anybody who doesn't want this.

As for 4, I have to admit I don't understand what Sahin wrote about the `lint` example. I see zero issue with it and it feels idomatic when I compare that to what I've been doing and seen done in the past few years.

**Comment by dominikg** [comment]
I'd love this too. Especially with short `-p` and `-s` flags. `pnpm -r -p test:*` :exploding_head:  
One thing to consider is how additional arguments could/should be passed on

**Comment by arxpoetica** [comment]
This would be amazing!
