### ISSUE TITLE
Does not install links to binaries of dependencies

### ISSUE THREAD

**Issue by kswope** [pnpm/pnpm#3566]
### pnpm version:

6.9.1

### Code to reproduce the issue:
```
npm i @glennsl/bs-jest
```
### Expected behavior:

What npm does
```
> npm i @glennsl/bs-jest
> npx jest --version
26.6.3
```
### Actual behavior:

```
> pnpm i @glennsl/bs-jest
> pnpx jest --version
Install the following package: jest@latest? (Y/n) › true
```

### Additional information:

 - `node -v` prints:
v16.3.0
 - Windows, macOS, or Linux?:
 macOS

**Comment by zkochan** [comment]
`bs-jest` does not have a bin called jest in its package.json: https://github.com/glennsl/bs-jest/blob/master/package.json

Hence, such bin is not added to `node_modules/.bin`.

Unlike npm, pnpm does not hoist everything to the root node_modules.

If you need to run jest, install it as a dependency

**Comment by kswope** [comment]
> Unlike npm, pnpm does not hoist everything to the root node_modules.

Is npm doing the right thing or the wrong thing?  If pnpm is a drop in replacement for npm, shouldn't it have the same functionality?

> If you need to run jest, install it as a dependency

Will this not potentially cause version conflicts?

**Comment by zkochan** [comment]
npm is doing the wrong thing: https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory

Yarn 2 with default configuration will do the same as pnpm.

pnpm can hoist everything as well but it is only a workaround: `pnpm install --shamefully-hoist`.

**Comment by kswope** [comment]
excellent, thx for the info, I'll let the author know.

**Comment by kswope** [comment]
> Yarn 2 with default configuration will do the same as pnpm.

I just confirmed that yarn with the default config does the exact same thing as npm.  Its only pnpm that is acting differently.  Maybe that explains why nobody has noticed this before.

**Comment by orefalo** [comment]
hi, got into the same issue today - 
yes, ` --shamefully-hoist` fixes the issue, yet I find it shameful to have pnpm behave differently from npm or yarn.
These other package manager are most likely to be shamed too,

but at the end of the say, I find it sad that I need to search the web to solve an obscure shameful user experience gap.

my 2c
