### ISSUE TITLE
Support "pnpm r" alias for "pnpm remove" like npm has

### ISSUE THREAD

**Issue by mhatvan** [pnpm/pnpm#3581]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the solution you'd like**

With npm, you don't have to type `npm remove xy` to remove a dependency, `npm r xy` also works.

Since pnpm uses the API of npm, it would be great to have that alias available to save developer time.

**Comment by zkochan** [comment]
I am afraid it would cause confusion. There are a couple of commands that start with "r". Also, you can use `pnpm rm` which is only one char longer.

**Comment by mhatvan** [comment]
Oh I didn't know that, pnpm rm is perfectly fine! Closing ticket as resolved.
