### ISSUE TITLE
Create git tag during changeset + pnpm publish -r workflow

### ISSUE THREAD

**Issue by joeldenning** [pnpm/pnpm#3586]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

When I use changesets and pnpm to manage a monorepo, I'd like git tags to be created for the packages that were published. In a non-monorepo, I generally run `pnpm version patch` which creates a git tag, then `git push --follow-tags` and then go create the Github release.

However, following [this documentation](https://pnpm.io/using-changesets) does not appear to result in git tags being created. Here are the commands I run:

```sh
pnpm exec changeset version
git add .
git commit -m "NPM Publish"
pnpm publish -r
git push --follow-tags
```

The problem is that neither `changeset version` nor `pnpm publish -r` create git tags, as far as I can tell. `changeset publish` or `pnpm version` would do it, but neither of those are executed.

Weirdly, I got this to work a while back on accident but don't know how I did so. See https://github.com/single-spa/create-single-spa/releases/tag/webpack-config-single-spa%402.2.0 as an example

**Describe the solution you'd like**

I'm open to suggestions on best approach, but here's my first thought:

```
pnpm publish -r --git-tag
```

This would first create git tags like `package1@1.0.0` and `package2@1.0.0` before publishing

**Describe the drawbacks of your solution**

There might be a different way that people are already achieving this, in which case the new flag might be unnecessary.

**Describe alternatives you've considered**

I looked at trying to do something like `npm version 3.0.0 --allow-same-version` recursively, but the git tag names are numeric and don't include the name of the package within the monorepo.

**Comment by zkochan** [comment]
It would make sense to create the git tags at the same place where the versions are bumped and committed. In your case it is done by Changesets, so changesets should add the tags.

**Comment by joeldenning** [comment]
Thanks - I will ask in the changesets repo, then. Are you aware of a way to get changesets to create a git tag during `changeset version` (or at least outside of `changeset publish`)?

**Comment by zkochan** [comment]
No, I do not know if they support it currently

**Comment by Hebilicious** [comment]
This issue still exists as of now.

It would be great to update the [docs](https://pnpm.io/using-changesets) with a more complete publish command :

```
"publish:ci": "pnpm run build && changeset tag && pnpm publish -r --no-git-checks --access public"
```
