### ISSUE TITLE
Command not found while running pnpm `xxx`

### ISSUE THREAD

**Issue by Brooooooklyn** [pnpm/pnpm#3596]
### pnpm version:

pnpm@6.10.0

### Expected behavior:

running ava tests 

### Actual behavior:

`/usr/bin/sh: 1: ava: not found`

### Additional information:

https://github.com/Brooooooklyn/canvas/runs/3040713096?check_suite_focus=true

 - `node -v` prints: `14.17.3`
 - Windows, macOS, or Linux?: Linux armv7/arm64 in Docker

**Comment by Brooooooklyn** [comment]
And https://github.com/Brooooooklyn/canvas/runs/3058089904?check_suite_focus=true

**Comment by denenr** [comment]
I can't see what commands you were running, only the output, but I'm guessing it looks a bit like `pnpm add ava`. This installs `ava` into the current directory. If you want to use `ava` when installed like that, try `pnpx ava`.

 `pnpm add` also has a `--global` switch which makes packages available unprefixed in your shell, like this: `pnpm add --global ava`. I would guess this is what you want.

**Comment by zkochan** [comment]
The logs have expired. Is this still an issue? What command did you run?

**Comment by Brooooooklyn** [comment]
This issues disappeared from GitHub actions for a while, so I close this for now.
