### ISSUE TITLE
6.x docs url is broken

### ISSUE THREAD

**Issue by NateScarlet** [pnpm/pnpm#3599]
https://github.com/pnpm/pnpm/blob/a468d2b3f8e4a456b3e57ad8a013af65b29c0484/packages/cli-utils/src/index.ts#L14

`pnpm install --help` shows:

```
Visit https://pnpm.io/6.x/cli/install for documentation about this command. 
```

https://pnpm.io/6.x/cli/install :

![image](https://user-images.githubusercontent.com/21083014/125908640-b0e7feeb-da02-47e8-8677-a174ef343746.png)

**Comment by zkochan** [comment]
Fixed via https://github.com/pnpm/pnpm.github.io/commit/668d7384e61ba133a20ea748a9b59657671e2b95
