### ISSUE TITLE
Can't resolve latest snowpack dependencies

### ISSUE THREAD

**Issue by flosker** [pnpm/pnpm#3603]
### Code to reproduce the issue:
1. Create a new folder
2. Do `pnpm add snowpack`. (v3.8.2)

Other people are also experiencing the same issue: (Only happens with pnpm)
https://github.com/snowpackjs/snowpack/issues/3158#issuecomment-879082772

### Expected behavior:
pnpm should resolve all the dependencies correctly. And after doing `pnpm snowpack dev`, dev server should start.

### Actual behavior:
Some dependencies are not resolved. Snowpack gives error of missing dependency `@npmcli/arborist`. WORK perfectly with snowpack version `3.7.1`.

### Additional information:

 - `node -v` prints: `v16.4.0`
 - Windows, macOS, or Linux?: Linux (Fedora 34)
 - Snowpack version: latest - `3.8.2`.

**Comment by flosker** [comment]
Seems like issue also happens with `npm`. Specific to snowpack it seems. Closing.

**Comment by flosker** [comment]
Actually latest check show only specific to pnpm.

**Comment by rowild** [comment]
This only happens when dependencies are INSTALLED via pnpm. Then `pnpm run dev` as well as `npm run dev` and `yarn dev` fail to run.
Best way to fix: delete node_modules, delete package_lock.json or yarn_lock.json, re-install everything using `npm i` or `yarn`.

**Comment by zkochan** [comment]
This is a duplicate of #3749

**Comment by flosker** [comment]
Yes, I saw it & closed this one.
