### ISSUE TITLE
Request: Bundle pnpm into a self-contained binary and release it to the GitHub release page

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#3624]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

Today, somebody [opens an issue at pnpm/action-setup](https://github.com/pnpm/action-setup/issues/18) expressing that they want to use pnpm@6 in environment with older versions of Node.js.

**Describe the solution you'd like**

Use [@vercel/ncc](https://github.com/vercel/ncc) to create self-contained dependency-free binaries for Windows, Mac, Linux and release them to [the release page](https://github.com/pnpm/pnpm/releases). This would enable installing `pnpm` by a simple `curl` command.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

**Comment by zkochan** [comment]
ncc bundles to an executable? We already use [pkg](https://github.com/vercel/pkg) to create an executable: [@pnpm/beta](https://github.com/pnpm/pnpm/tree/main/packages/beta)

The plan is to ship it with the default system package manager. Which will allow to the also install Node.js using pnpm.

**Comment by KSXGitHub** [comment]
Anything is fine, the point of this issue is releasing the asset to the release page.

**Comment by KSXGitHub** [comment]
Actually, you should try both `pkg` and `ncc` to see which one produces better executable (smaller in size or faster startup or both)

**Comment by zkochan** [comment]
This action may be used: https://github.com/softprops/action-gh-release

But we'll have to use a docker container as seems rpm packages cannot be created on ubuntu and github actions run only on Linux/macOS/Windows.

**Comment by KSXGitHub** [comment]
> But we'll have to use a docker container as seems rpm packages

Why do you create rpm and deb packages? These are the jobs of distro maintainers. Why don't you just upload the binaries instead? This would allow people to simply download them to a `bin` directory to install them.

What I mean is this:

<figure align="center">
<img src="https://user-images.githubusercontent.com/11488886/127756330-e89d814e-d01b-4eae-a44a-aa9407282168.png">
<figcaption align="center">
<a href="https://github.com/sane-fmt/sane-fmt/releases/tag/0.10.1">
<em>Executable binaries are uploaded as-is, without archives or compression</em>
</a>
</figcaption>
</figure>

**Comment by zkochan** [comment]
https://github.com/pnpm/pnpm/releases/tag/v6.12.0-0
