### ISSUE TITLE
prepublishOnly is ignored

### ISSUE THREAD

**Issue by kboda** [pnpm/pnpm#3626]
### Code to reproduce the issue:

add a `prepublishOnly` script to a project

### Expected behavior:
`pnpm publish` runs the `prepublishOnly` script

### Actual behavior:
`pnpm publish` does not run the `prepublishOnly` script

### Additional information:

 - `node -v` prints: v14.17.3
 - Windows, macOS, or Linux?: Windows 10
 - `npm -v` prints: 7.20.2

in 6.10.3 it works as expected. 

I have noticed that `--ignore-scipts` was added here: https://github.com/pnpm/pnpm/blame/bff84dbca25cacc052d02d8324f394f47cb07be9/packages/plugin-commands-publishing/src/publish.ts#L167
Can this be the reason? Is it intended (and so the prepublishOnly script is ignored in the next version) or just accidentally left there?

**Comment by zkochan** [comment]
`--ignore-scripts` was always there. The scripts are executed by pnpm, they should not be re-executed with npm.

**Comment by kboda** [comment]
> `--ignore-scripts` was always there. The scripts are executed by pnpm, they should not be re-executed with npm.

Thanks for your quick feedback!

Sorry I don't get your point, maybe I explained it in the wrong way, let me try it differently.

With the following steps I can reproduce it any time:

1. `npm install pnpm@latest -g`
2. from my project dir:  `pnpm publish`
3. it starts the prepublishOnly script, builds the stuff and publishes it as expected 👍 

4. `npm install pnpm@next -g` (I really like the new `pnpm audit --fix` feature)
5. from my project dir:  `pnpm publish`
6. it does not run the prepublishOnly script, but exits with this error message:
`No package.json (or package.yaml, or package.json5) was found in "<path_to_my_package>\dist"`

I have the following config in `package.json`: 
`
"publishConfig": {
  "directory": "dist"
}
`
I would expect pnpm to run the prepublishOnly script which actually creates the `dist` folder.

Note: my prepublishOnly script creates a `package.json` file inside the `dist` folder, and as I said, it works perfectly with the `latest` version, the problem exists only in `next`, but I would really like to use it to have the `--fix` flag for audit.

Thanks in advance

**Comment by zkochan** [comment]
I see. So I guess the issue happens when using publishConfig

kboda ***@***.***> ezt írta (időpont: 2021. júl. 29., Cs
12:00):

**Comment by kboda** [comment]
Yes, I can confirm this, it does not happen if I remove publishConfig.

**Comment by kboda** [comment]
Thank you very much for fixing it so quickly, you do awesome work here, keep up!
