### ISSUE TITLE
install yields ENOENT: no such file or directory, chmod

### ISSUE THREAD

**Issue by cdaringe** [pnpm/pnpm#3630]
`NODE_ENV=production time pnpm install --no-optional --package-import-method=copy --offline -P `

yields #2882 's failure mode:

```
17:11:55  ERROR  ENOENT: no such file or directory, chmod '/opt/app/node_modules/.pnpm/typescript@4.1.4/node_modules/typescript/bin/tsc'
17:11:55 at pnpm/typescript  
```

Failure is seemingly sporadic. Some (most?) installs appear to pass fine

### pnpm version:

6.4.x

### Code to reproduce the issue:

...will obtain...

### Expected behavior:

- no error
- 
### Actual behavior:

- error

### Additional information:

 - `node -v` prints: 14.x
 - Windows, macOS, or Linux?: alpine linux

**Comment by alber70g** [comment]
Did you find a solution?

**Comment by cdaringe** [comment]
Sorry mate, I didn’t. But, since upgrading many minor versions, I haven’t seen it. I’m not sure if it was the upgrade that addressed it or some other system issue. Good luck!

**Comment by alber70g** [comment]
I have it consistently on our deployment pipeline. Very annoying. Maybe keep the issue open, so it might get some attention
