### ISSUE TITLE
pnpm i fails with unsupported platform error

### ISSUE THREAD

**Issue by mhatvan** [pnpm/pnpm#3640]
### Code to reproduce the issue:

![2021-08-02_19-23](https://user-images.githubusercontent.com/16797721/127900643-e8eb14aa-8036-4b66-aece-e7fbda48132a.png)

`iconv-corefoundation` is not a direct dependency.

Dependency tree is the following: `electron-builder` > `dmg-builder` > `dmg-license` (optionalDependencies) > `iconv-corefoundation`

### Expected behavior:

To my knowledge, unsupported platform / `optionalDependencies` is usually ignored, e.g. `fsevents`

Pass `pnpm i` without error

### Actual behavior:

Cannot finish `pnpm i` due to the error aborting the install.

### Workaround:

It passes when running `pnpm i -f`

### Additional information:

 - `node -v` prints: 14.7.2
 - Windows, macOS, or Linux?: Ubuntu 21.04

**Comment by zkochan** [comment]
Yes, they are ignored. Is icon-corefoundation also a non-optional dependency of some other package?

**Comment by mhatvan** [comment]
Good point, `icon-corefoundation` is a `dependency` of the optional `dmg-license`, so this is not a pnpm issue. 

I opened an issue in the respective repository and linked to this issue.

**Comment by zkochan** [comment]
if `icon-corefoundation` is a dependency of an optional only dependency then it is automatically and optional dependency as well. So in that case it should work as well. In the lockfile, does icon-corefoundation has an `optional: true` field? Like this:

https://github.com/pnpm/pnpm/blob/c8347f6fe3f14a75cb60146ac40bd371a7291207/pnpm-lock.yaml#L7488

**Comment by mhatvan** [comment]
Oh, then let's reopen this issue. 

This is the link to the lockfile: https://github.com/getferdi/ferdi/blob/ee49ef1dcda724cce47f20b786cc019387e006f3/pnpm-lock.yaml

Looks like there is indeed some misbehavior then.

**Comment by mhatvan** [comment]
I just saw that there is a new release that improves optional dependency handling. 

Does it fix this issue?

**Comment by zkochan** [comment]
No, I don't think it fixes this issue.

**Comment by zkochan** [comment]
But I will look into this issue.

**Comment by zkochan** [comment]
@mhatvan as a workaround, use this `.pnpmfile.cjs`:

```js
module.exports = {
  hooks: {
    readPackage: (manifest) => {
      if (manifest.dependencies['iconv-corefoundation']) {
        manifest.optionalDependencies['iconv-corefoundation'] = manifest.dependencies['iconv-corefoundation']
      }
      return manifest
    }
  }
}

```

**Comment by mhatvan** [comment]
Cool, will do thanks!

Is this a temporary workaround until fixed or is this an edge case fix?

**Comment by zkochan** [comment]
I am trying to fix it but it is quite hard, so I am not making promises. This fix is safe to use while this issue is not resolved in pnpm CLI.

**Comment by zkochan** [comment]
It was hard for me to reproduce this issue until I realized that you set `engine-strict=true`

https://github.com/getferdi/ferdi/blob/4cbf03cb5ad0981606682a2b23dbcfcfb18e4e52/.npmrc#L2

With default settings this doesn't works, just prints a warning.
