### ISSUE TITLE
Improve error message command when script is missing but is present in the workspace

### ISSUE THREAD

**Issue by Jolg42** [pnpm/pnpm#3656]
Example:
```
 pnpm run setup
 ERROR  Missing script: setup
But setup is present in the root of the workspace,
so you may run "pnpm -w setup"
```

The problem here is that `setup` is also a pnpm command I think, so my `setup` script is not executed.

I need to add `run` like `pnpm -w run setup` to make the example work.

Maybe a simple fix would be to always render `run` in the help output to avoid conflicts?

Looks like source code is here
https://github.com/pnpm/pnpm/blob/a1a03d1457d8b28bdb8a1bdb9e00288bcb0caf12/packages/plugin-commands-script-runners/src/run.ts#L164-L167

**Comment by zkochan** [comment]
Sounds good.
