### ISSUE TITLE
Full new pnpm install do not call lifecycle scripts after the installation

### ISSUE THREAD

**Issue by wre232114** [pnpm/pnpm#3659]
### pnpm version:
6.10.2 and 6.12.1

### Code to reproduce the issue:
I got this error after pnpm install: Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"

I found that this is caused by pnpm install, which does not execute lifecycle scripts

### Expected behavior:
run lifecycle scripts after install inside pnpm workspaces.

### Actual behavior:
do not call lifecycle scripts, just log done like below:

Packages: +4688
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: xxxx
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 4688, reused 4688, downloaded 0, added 4688, done

### Additional information:

 - `node -v` prints: 14.15.4
 - Windows, macOS, or Linux?: macOS

**Comment by CxRes** [comment]
I can confirm this behaviour on windows with my own library that has lifecycle scripts, that was working fine with pnpm 5.x (running alongside npm 6.x):

```sh
pnpm i -D headright
```

with error:
```sh
node_modules/.pnpm/headright@0.1.0/node_modules/headright: Running postinstall script, failed in 99ms
.../node_modules/headright postinstall$ hr-init --ignore
│ 'hr-init' is not recognized as an internal or external command,
│ operable program or batch file.
└─ Failed in 99ms
 ERROR  Command failed with exit code 1.
```

node:  14.17.1 (LTS)
npm: 7.20.5
pnpm 6.12.1

`pnpm rebuild` as reported by @wre232114  fixes the error.

**Comment by zkochan** [comment]
I don't know if the issue described by @CxRes is the same as the issue described by @wre232114 as the issue has no steps to reproduce.

But for the issue described by @CxRes I have a fix in progress: https://github.com/pnpm/pnpm/pull/3662

I doubt that it worked in v5 or any other version. Maybe in some scenarios it worked.

**Comment by zkochan** [comment]
Overall, I don't think it is a good idea when the package runs its own binaries like that (instead of using a relative path). But seems like it works with npm, so I will fix it.

**Comment by CxRes** [comment]
@zkochan I appreciate you fixing this. Incidentally, could you please elabourate it not being ideal for package to its own binaries. I had picked up this pattern from other libraries that also do the same to add a default configuration file. What would you recommend instead?

**Comment by zkochan** [comment]
:ship: 6.13.0

**Comment by wre232114** [comment]
@zkochan After debuging the source code, I found why this happened. The lockfile entry lacks `requiresBuild` field, so we may need to verify the fields writed to lockfile? please take a look into this

**Comment by zkochan** [comment]
@wre232114 is the package with the problem public? 

Here is the code that sets the value if `requiresBuild`: https://github.com/pnpm/pnpm/blob/ea0c766067374c822b3106e91b69e4d4b22bba23/packages/resolve-dependencies/src/index.ts#L207-L215

**Comment by wre232114** [comment]
> @wre232114 is the package with the problem public?
> 
> Here is the code that sets the value if `requiresBuild`:
> 
> https://github.com/pnpm/pnpm/blob/ea0c766067374c822b3106e91b69e4d4b22bba23/packages/resolve-dependencies/src/index.ts#L207-L215

The problem is that i have a broken lockfile. so the code will never reach here if a lockfile entry already existed. that's the problem, no way to fix my broken lock file(delete lockfile and regenerate is impossible, which will loose all locked versions in my huge monorepo)

**Comment by wre232114** [comment]
@zkochan I opened a PR #3729 , trying to provide a way to fix this kind of problems. please take a look into it, thanks
