### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by markexin** [pnpm/pnpm#3663]
God help me！
### Code to reproduce the issue:
![image](https://user-images.githubusercontent.com/18322323/129126868-8494340f-1e8b-4d4e-91f5-8af49c5f39d7.png)
![image](https://user-images.githubusercontent.com/18322323/129126893-845ef373-a2c3-4d96-bd98-077337920a4e.png)
![image](https://user-images.githubusercontent.com/18322323/129126923-38f2c4f6-7c01-4faf-a988-d8ed4aa5dd22.png)

### Expected behavior:
I wish I could get around this error and allow me to install the dependency correctly, or tell me what caused the error.

### Actual behavior:

Failed to install dependencies。

### Additional information:

 - `node -v` prints:  v14.16.1
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
What package were you installing when you got this error?

**Comment by zkochan** [comment]
How does it work with npm? Does installation succeed?

**Comment by zkochan** [comment]
Seems like npm installs such packages but yarn fails with an error liek "Integrity checked failed for "pkg" (none of the specified algorithms are supported)"

**Comment by markexin** [comment]
> What package were you installing when you got this error?

when I load the NPM package of the company's internal source。
but i am sure that i can download this package by url

**Comment by markexin** [comment]
> How does it work with npm? Does installation succeed?

npm works well ~

**Comment by markexin** [comment]
> > What package were you installing when you got this error?
> 
> when I load the NPM package of the company's internal source。
> but i am sure that i can download this package by url

i also add .npmrc in my workspace to define  where registry is。

**Comment by markexin** [comment]
> > > What package were you installing when you got this error?
> > 
> > 
> > when I load the NPM package of the company's internal source。
> > but i am sure that i can download this package by url
> 
> i also add .npmrc in my workspace to define where registry is。

Finally, thank you for your reply. I hope the problems I encountered will be helpful to your project~~~
