### ISSUE TITLE
VSCode intellisense not working

### ISSUE THREAD

**Issue by Maikuh** [pnpm/pnpm#3671]
### Code to reproduce the issue:
```jsx
import React from 'react'

export default function App() {
  useEffect(() => {
    console.log('Intellisense to import useEffect not working')
  }, [])

  return <h1>Intellisense to import useEffect not working</h1>
}
```

### Expected behavior:
![image](https://user-images.githubusercontent.com/38594993/129432126-9dba51c5-862a-4b64-9b47-a082c0050549.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/38594993/129432075-751feaaf-67d4-4f40-9d96-caa79c30e231.png)

### Additional information:

 - `node -v` prints: v16.5.0
 - OS: Linux
 - React Typescript project, using Vite
 - Similar to https://github.com/pnpm/pnpm/issues/3550, but the solution does not actually work (i.e. using `typescript@4.4` which is currently in beta)

**Comment by Maikuh** [comment]
For anyone wondering, I was able to fix it by adding `"preserveSymlinks": true` under the `compilerOptions` section in the `tsconfig.json` file. After that, I restarted the Typescript Server by doing:
- `Ctrl + Shift + P` to bring up the command palette
- Search for `Restart TS Server` and press `Enter`
- Profit

For reference, look at [this issue](https://github.com/microsoft/vscode/issues/25312), but specifically, [this comment](https://github.com/microsoft/vscode/issues/25312#issuecomment-414792423). That issue talks about the same issue as this one, but with packages installed via `npm link`. My guess is, since `pnpm` and `npm link` both use symlinks or something of the sorts, the fix for that issue also applies here.

PNPM docs talk about the `--preserve-symlinks` flag of **_Node_** (e.g. [here](https://pnpm.io/faq#why-have-hard-links-at-all-why-not-symlink-directly-to-the-global-store) and [here](https://pnpm.io/limitations)) not working, but it doesn't seem to be the case. The description for the `preserveSymlinks` field in `tsconfig.json` says that it correlates to the same flag.
![image](https://user-images.githubusercontent.com/38594993/129459255-305a5797-7aaf-46c2-966c-b58516bc454b.png)

Also, like I mentioned, the fix for the other issue similar to this one (using `typescript@^4.4.0-beta`) does not help. This worked fine with `typescript@^4.3.5`.

I'll be closing this issue now.

**Comment by pot-code** [comment]
Really helpful! they should pin this issue 🙌🏻

**Comment by ktmud** [comment]
Adding `preserveSymlinks` does fix the autocomplete, but now `tsc --noEmit` throws errors (e.g. Module xxx has no exported member xxx). Anyone able to fix the issue?

**Comment by Maikuh** [comment]
> Adding `preserveSymlinks` does fix the autocomplete, but now `tsc --noEmit` throws errors (e.g. Module xxx has no exported member xxx). Anyone able to fix the issue?

@ktmud I think that's normal and would happen with any of the package managers. Try the `--skipLibCheck` flag or setting [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) to `true` in `tsconfig.json`

**Comment by levg34** [comment]
Extremely useful! Thank you very much @Maikuh
