### ISSUE TITLE
Interactive upgrade

### ISSUE THREAD

**Issue by MohamadKh75** [pnpm/pnpm#3676]
### pnpm version:

6.13.0

### Code to reproduce the issue:

`pnpm update --interactive`

### Expected behavior:

To select each dependency and have a nice view!

### Actual behavior:

Rows duplicate each time a select all or one!
![sc](https://user-images.githubusercontent.com/25561893/129756521-735db079-d8e6-481d-aecb-0ec7955f9570.jpg)

### Additional information:

- `node -v` prints: v14.17.5
- Windows, macOS, or Linux?: Linux

```
System:
  Host: ZenBook Kernel: 5.4.0-81-generic x86_64 bits: 64
  Desktop: KDE Plasma 5.18.5 Distro: Ubuntu 20.04.2 LTS (Focal Fossa)
```

**Comment by mcmxcdev** [comment]
I cannot reproduce this with pnpm 7.1.2 on Manjaro Linux.

**Comment by zkochan** [comment]
I also can't reproduce this. If it is still an issue, try to add more details so that other can repro it.

**Comment by MohamadKh75** [comment]
Fixed in 7
Thanks
