### ISSUE TITLE
pnpx pollutes commands' standard output

### ISSUE THREAD

**Issue by jcayzac** [pnpm/pnpm#3687]
### pnpm version:

6.13.0

### Code to reproduce the issue:

```sh
$ pnpx 2>/dev/null --yes -q --package="pnpm@6.13.0" -- pnpm --version
```

### Expected behavior:

Output is:

```text
6.13.0
```

### Actual behavior:

Output is:

```text
Packages: +1
+
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/julien.cayzac/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm

/Users/julien.cayzac/.pnpm-store/v3/tmp/_npx/11072/5:
+ pnpm 6.13.0

Progress: resolved 1, reused 1, downloaded 0, added 1, done
6.13.0
```

### Additional information:

 - `node -v` prints: `v16.5.0`
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
@bendman you are executing `pnpm dlx` incorrectly.

This works:

```
pnpm --package=typescript --package=ts-node dlx ts-node
```

dlx options may only be used before the word `dlx`. Anything that goes after dlx is the executed command.

**Comment by illright** [comment]
@zkochan I've found that out experimentally as I was trying really hard to figure out how to call up the help for `dlx`. In the end, `pnpm -h dlx` was the key, but I find that to be very counter-intuitive. Is there a reason why `dlx` and `exec` skip the parsing and just execute everything after the respective keyword?

I would prefer the following behavior:
```shell
$ pnpm exec -h  # -h is consumed by pnpm
<pnpm exec help string here>

$ pnpm exec echo -h  # -h is consumed by pnpm
<pnpm exec help string here>

$ pnpm exec -h echo  # -h is consumed by pnpm
<pnpm exec help string here>

$ pnpm exec -- echo -h  # -h is consumed by echo
-h

$ pnpm exec --silent echo stuff  # --silent is consumed by pnpm, stuff is consumed by echo
stuff

# alternatively, this could also be acceptable
$ pnpm exec 'echo -h'
-h
```

**Comment by zkochan** [comment]
This is supported now through `pnpm --silent dlx <pkg> <args>`
