### ISSUE TITLE
@types shouldn't be hoisted to the root's .pnpm folder in the monorepo

### ISSUE THREAD

**Issue by stkevintan** [pnpm/pnpm#3693]
### Code to reproduce the issue:
For my project:

```
/ -
  - packages
  - - A
  - - B
```
package A requires `@types/webpack@4.41.0` but B has a customized declare of webpack. it is not expected to be polluted by the type definitions from the `@types/webpack@4.41.0` in the package A.
However, pnpm will always hoist the `@types/webpack@4.41.0` to the root's `node_modules/.pnpm` folder. which will lead to package B's typescript server detect it, and merged that type defines to my customized one.

I tried `hoist =false` but didn't help.

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
You set `hoist=false` in a `.npmrc` file and types are still hoisted to `node_modules/.pnpm/node_modules`? Have you tried removing node_modules and running `pnpm install`?

**Comment by stkevintan** [comment]
@zkochan  Yes, and I didn't see any different when I set the `hoist=false`, the packages are still hoisted. I am confused.

following is my operation:

```
➜  a365-cli git:(ktan/extension) ✗ cat .npmrc
hoist=false
➜  a365-cli git:(ktan/extension) ✗ rm -Fo -R -Path  .\node_modules,packages\*\node_modules
➜  a365-cli git:(ktan/extension) ✗ pnpm i
Scope: all 5 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +481
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                                                                                                                                                                                               +++++++++++++++  
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\ktan\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 481, reused 481, downloaded 0, added 481, done
➜  a365-cli git:(ktan/extension) ✗ ls .\node_modules\@types\webpack\

    Directory: C:\Users\ktan\Projects\a365-cli\node_modules\@types\webpack

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           2021/8/19    20:21         101379 index.d.ts
-a---           2021/5/13    12:01           1141 LICENSE
-a---           2021/8/19    20:21           1497 next.d.ts
-a---           2021/8/19    20:21           4216 package.json
-a---           2021/8/19    20:21           1897 README.md

➜  a365-cli git:(ktan/extension) ✗ ls .\node_modules\.pnpm\@types+webpack@4.41.30\

    Directory: C:\Users\ktan\Projects\a365-cli\node_modules\.pnpm\@types+webpack@4.41.30

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2021/8/21    20:45                node_modules
```

**Comment by zkochan** [comment]
Try to also set `shamefully-hoist=false`. Do you have other hoist-related options in npmrc? See https://pnpm.io/blog/2020/10/17/node-modules-configuration-options-with-pnpm

**Comment by stkevintan** [comment]
Hi, @zkochan  Thanks for your reply. I don't have any config except the hoist. I print the whole ouput of `cat .npmrc` to the previous reply.

Yes, add the `shamefully-hoist=false` will prevent hoisting the package( but actually the option should be default to false, as the doc read, right ? ). however it will break the type inferences, and the worst thing is I even cannot run my project successfully ( a pure node project without any bundler). some packages need follow the symlink to the real path but some packages must not.

**Comment by zkochan** [comment]
Could you remove @types/webpack from dependencies?

Kevin Tan ***@***.***> ezt írta (időpont: 2021. aug. 21., Szo
16:43):

**Comment by stkevintan** [comment]
Yes, I can remove it. but my code will lose type constraint. I just move back to yarn and it works fine now. anyway, thank your help!
