### ISSUE TITLE
Idea: Add node version to the store hash computation

### ISSUE THREAD

**Issue by rstacruz** [pnpm/pnpm#37]
```
node_modules/.store/node-sass@3.4.2
```

This is how modules are stored. However, once you switch node versions (eg, from node 4.2.4 to 5.3.0), you'll be greeted by this:

```
> require('node-sass')
Error: The `libsass` binding was not found in /xxx/node_modules/.store/node-sass@3.4.2/vendor/darwin-x64-47/binding.node
This usually happens because your node version has changed.
```

This sucks. To mitigate this, _compiled_ modules should have the node major version appended to their store ID:

```
node_modules/.store/node-sass@3.4.2@node4
```

While not a complete solution, this allows you to simply run `pnpm install` to rebuild modules as needed.

In addition to this, there should be integrity checks that symlinks are linking to the correct versions... I guess.

**Comment by patrickheeney** [comment]
I think a better solution would be drop a `.node_version` file when initially installed. If the current node version is a mismatch, attempt to instruct the user to re-install the modules as a convenience. I don't know that you have to do anything at all here though. 

Upgrading from npm2 to npm3 would require re-installing them as well. The node-sass error is pretty self explanatory as to what happened. Adding @node4 makes it so you already will have to re-download the packages anyway, but adds more complexity to the system and symlinks.

**Comment by zkochan** [comment]
We're going to have something like this when we implement `Side-Effects Caching`, see #568
