### ISSUE TITLE
Some scripts mysteriously fail in 6.14.2

### ISSUE THREAD

**Issue by mewhhaha** [pnpm/pnpm#3700]
### Code to reproduce the issue:
Repo to reproduce the issue
https://github.com/mewhhaha/repro-pnpm-bug

GIST of the the debug log when the error occurs
https://gist.github.com/mewhhaha/d0586aecd69bb34b32f95581f392fc76

This issue occurs when running the install command (but seems to happen when running other scripts as well, as we have the same issue when running a build script in the pipeline).

### Expected behavior:
The behaviour on 6.13.0 (everything installs without issue=

### Actual behavior:
Command failed on prepare stage (see gist)

### Additional information:
Seems to be working in 6.13.0
Seems that removing "shell-emulator=true" or the workspace dependency on "a" makes it able to run the prepare script?

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: Windows and Linux (at least)

**Comment by zkochan** [comment]
Seems like it is caused by an update in our dependencies.

We updated `@yarnpkg/parsers` from version 2.3.0 to v2.4.0.

**Comment by zkochan** [comment]
Seems like upgrading `@yarnpkg/shell` to v3.0.0 in `@zkochan/npm-lifecycle` also fixes the issue. But probably downgrading is safer.
