### ISSUE TITLE
`pnpm` thinks Github Codespaces is unsafe

### ISSUE THREAD

**Issue by evantahler** [pnpm/pnpm#3709]
Running `pnpm install` inside a Github Codespace does not run `prepare` lifecyles hooks because it thinks the directory is unsafe.  Running `pnpm install --unsafe-perm` works as intended.

### Code to reproduce the issue:

Using the Grouparoo repo (https://github.com/grouparoo/grouparoo): 

```
pnpm install
```

produces

```
root ➜ /workspaces/grouparoo (main ✗) $ pnpm install
Scope: all 44 workspace projects
 WARN  There are cyclic workspace dependencies
Using hooks from: /workspaces/grouparoo/.pnpmfile.cjs
readPackage hook is declared. Manifests of dependencies might get overridden
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
. preinstall$ ./bin/preinstall
└─ Running...
cli prepare$ rm -rf dist && tsc --declaration && chmod 0766 dist/grouparoo.js
└─ Running...
 WARN  "preinstall" script of "@grouparoo/grouparoo@0.0.0" inside "/workspaces/grouparoo" is skipped as the working directory seems suspicious. To run this lifecycle script anyway, use "--unsafe-perm".
 WARN  "prepare" script of "grouparoo@0.5.3-alpha.5" inside "
```

And none of the `prepare` lifecycle hooks fire (which we use to compile typescript)

 - `node -v` prints: `v15.14.0`
 - Windows, macOS, or Linux?: `linux`, `Linux 45cb69da334b 5.4.0-1055-azure #57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 x86_64 GNU/Linux`

**Comment by aminya** [comment]
I also faced this issue in docker files.

**Comment by BlackHole1** [comment]
Please wait and let me have a look, this should be fixed soon.

**Comment by zkochan** [comment]
Can we check if this works with the latest npm without `unsafe-perm`?
