### ISSUE TITLE
pnpm env use command generates incorect *.ps1 files for npm/npx

### ISSUE THREAD

**Issue by ltdu** [pnpm/pnpm#3711]
### pnpm version:

6.14.3

### Code to reproduce the issue:
* Windows OS
* PowerShell command line
* NOT ```WSL``` environment

```powershell
pnpm env use -g lts
npm --version
npx --version
```

### Expected behavior:

```npm``` and ```npx``` versions are printed out

### Actual behavior:

Error message indicating ```node.exe``` could not be found is received

```powershell
& : The term 'node.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\[user]\AppData\Local\pnpm\npm.ps1:24 char:7
+     & "node$exe"  "$basedir/nodejs/14.17.5/node_modules/npm/bin/npm-c ...
+       ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (node.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Possible solution:

I have review generated ```npm.ps1``` and ```npx.ps1``` files and following change solves this problem:

![image](https://user-images.githubusercontent.com/22098043/130865372-62e770f6-acec-4645-b808-729eeedc4ad8.png)

### Additional information:

 - `node -v` prints: v14.17.5
 - Windows, macOS, or Linux?: Windows PowerShell 

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by zkochan** [comment]
I think the easiest solution will be just to remove the powershell command shim. A Windows command script is generated anyway. And it seems to work.

**Comment by ltdu** [comment]
I think this would be viable solution. I don't see ```node``` or ```npm``` providing ```*.ps1``` shims, so maybe ```pnpm``` does not have to either
