### ISSUE TITLE
pnpmfile add postinstall script?

### ISSUE THREAD

**Issue by loynoir** [pnpm/pnpm#3733]
### Code to reproduce the issue:

```js
// .pnpmfile.cjs
function readPackage(pkg, context) {
    switch(`${pkg.name}@${pkg.version}`) {
        case '{{foobar}}@0.0.0-semantically-released':
            context.log('>>> Add postinstall')
            pkg.scripts.postinstall = 'notify-send Msg "pnpm install && pnpm run setup-script"'
            break
        default:
            break
    }

    return pkg
}

module.exports = {
    hooks: {
        readPackage
    }
}
```

### Expected behavior: 

Added postinstall triggered

### Actual behavior: 

Added postinstall not triggered

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

### Scenario

1. Fork git repo to add patch, but upstream git repo's 'dist/' is build by CI. Might be better to add `postinstall` via pnpmfile hook instead of forked git repo.

2. Some author have already to release ESM only package, might be awesome to tweak build script via pnpmfile

**Comment by zkochan** [comment]
You may just add the script to the project's postinstall. Something like

```json
{
  "scripts": {
    "postinstall": "cd node_modules/foobar && notify-send Msg "pnpm install && pnpm run setup-script""
  }
}
```

**Comment by loynoir** [comment]
@zkochan 
Thanks for your reply. That seems working, I will test it later.
Maybe add document on pnpmfile?

As I saw `scripts` field in `pkg`, just a bit confusing.

**Comment by zkochan** [comment]
We have this information in the docs:

> Removing the scripts field from a dependency's manifest via readPackage will not prevent pnpm from building the dependency. When building a dependency, pnpm reads the package.json of the package from the package's archive, which is not affected by the hook. In order to ignore a package's build, use the pnpm.neverBuiltDependencies field.

https://pnpm.io/pnpmfile#known-limitations

**Comment by loynoir** [comment]
Yeah, I saw that, just think add should ok.
Small question, is modify `scripts.postinstall` not allowed, or modify all `scripts.XXX` not allowed?

**Comment by zkochan** [comment]
Modifying scripts in the readPackage will do nothing

**Comment by loynoir** [comment]
Thanks for your reply. Closing. 😃
