### ISSUE TITLE
`No projects matched the filters` in Windows 

### ISSUE THREAD

**Issue by davidseow** [pnpm/pnpm#3739]
### Code to reproduce the issue:
[Example project](https://github.com/davidseow/pnpm-windows-filter) with multiple packages, running Jest tests in Github Action. It is set up to run the same filter `pnpm test --filter "{packages}[$COMMIT_SHA]"` on both [Windows and Linux boxes](https://github.com/davidseow/pnpm-windows-filter/blob/main/.github/workflows/testing.yml#L32). 

### Expected behavior:
<img width="1150" alt="Screenshot 2021-09-01 at 21 42 02" src="https://user-images.githubusercontent.com/502503/131744184-a95801ab-e933-4b7b-8bf1-123c478f4bf8.png">

* Windows - Should find tests in `sub-1` package within packages folder
* Linux - Should find tests in `sub-1` package within packages folder

### Actual behavior:
<img width="1198" alt="Screenshot 2021-09-01 at 21 38 32" src="https://user-images.githubusercontent.com/502503/131744161-93efb2d0-ed24-4b90-ac8f-a50897715904.png">

* Windows - logs out `No projects matched the filters` message. See: [build link](https://github.com/davidseow/pnpm-windows-filter/runs/3488871760?check_suite_focus=true#step:6:6)
* Linux - picks up update in `sub-1` package. See: [build link](https://github.com/davidseow/pnpm-windows-filter/runs/3488871784?check_suite_focus=true#step:6:8)

**Comment by zkochan** [comment]
Is that executed using PowerShell on Windows?

In that case you might need to do it like this:

```
pnpm test --filter "{packages}[$env:COMMIT_SHA]"
```

**Comment by davidseow** [comment]
That was it. Thanks @zkochan!

**Comment by felix-cao** [comment]
##  Same error

I had the same error, but can't solve it .
and can work successfully on macOS. 

`Environment`
OS: Windows 10 Pro
nodejs: V17.0.0
npm: V8.6.0
pnpm: V6.32.6
gitbash:  git version 2.31.1.windows.1

code : https://github.com/superfreeeee/Blog-code/tree/main/front_end/package/pnpm_workspace

`error`
```bash
$ pnpm start

> mono@1.0.0 start C:\code\vue\mono
> pnpm run start --filter '*'

No projects matched the filters in "C:\code\vue\mono"
```
