### ISSUE TITLE
Install --prod tries to resolve devDependencies

### ISSUE THREAD

**Issue by petrzjunior** [pnpm/pnpm#3746]
### pnpm version: 6.14.3

I'm trying to setup linking packages inside monorepo. Let's say I have two packages: `gui` and `tests`. `tests` is only for unit testing, so I added it to `gui` inside `devDependencies`. Inside CI, I run `pnpm i --prod` to install production deps only (i.e. not `tests`). But `pnpm` is still trying to find the package, which is a problem, because I do not want to copy my dev deps to CI.

### Code to reproduce the issue:

Clone example https://github.com/petrzjunior/pnpm-workspace-link-bug
Run `cd gui && pnpm i --prod`

### Expected behavior:

Install production dependencies only. Install neither `tests` nor `non-existent-package`.

```json
"devDependencies": {
    "tests": "link:../tests",
    "non-existent-package": "link:../non-existent-package"
  }
```

### Actual behavior:

pnpm is still trying to resolve both packages:
` ERROR  Could not install from "/usr/app/pnpm-workspace-prod-bug/non-existent-package" as it does not exist.`

If the package existed, pnpm would not _install_ it actually, but trying to _access_ the path is enough for it to crash in case the path doesn't exist.

### Additional information:

 - `node -v` prints: v16.1.0
 - Windows, macOS, or Linux?: Linux

**Comment by gaggle** [comment]
I'm seeing pnpm pulling dev-dependencies into `node_modules/.pnpm`, I think for the same reason as you describe here. That's a major problem because I'm on Heroku and dev-dependencies in my case dev-deps are so big Heroku rejects the deployment. I expect `pnpm install --prod --filter=foo...` to only install production dependencies all the way down the chain, 100% skipping dev-dependencies.

**Comment by gaggle** [comment]
Ah my case sounds covered by #881

**Comment by zkochan** [comment]
I am looking into it.

**Comment by zkochan** [comment]
#3983 will fix your issue but a warning will still be printed.

**Comment by yanickrochon** [comment]
I just had this problem. Running `pnpm link .../some-project` tries to pull a local dev dependency that isn't published on `npm`. It worked fine yesterday, but I have updated a completely unrelated dependency, and now my `postInstall`, which has some `pnpm link` instructions, fail.
