### ISSUE TITLE
Error with Snowpack installation

### ISSUE THREAD

**Issue by rowild** [pnpm/pnpm#3749]
### pnpm version: 6.14.6

There is a problem installing snowpack with pnpm documented here:
https://github.com/snowpackjs/snowpack/issues/3158

Error message:
`Package "@npmcli/arborist" not found. Have you installed it?`

### Reproduce:

```bash
pnpm i -D snowpack

# then run:
npx snowpack run
````

### Additional information:

 - `node -v` prints: 14.7.1
 - Windows, macOS, or Linux?: MacOS Catalina

**Comment by rowild** [comment]
And please check the mobile Version of snowpack.dev. Menu not working, landscape view on mobile mit scrollable.

**Comment by zkochan** [comment]
It is not a bug in pnpm. It works in Yarn because they add a patch to fix it: https://github.com/yarnpkg/berry/pull/2795/files

You can do the same with pnpm using ([packageExtensions](https://pnpm.io/package_json#pnpmpackageextensions)). Put this to your package.json:

```json
{
  "pnpm": {
    "packageExtensions": {
      "license-webpack-plugin@*": {
        "peerDependenciesMeta": {
          "webpack": { "optional": true }
        }
      },
      "snowpack@>=3.3.0": {
        "dependencies": {
          "node-gyp": "^7.1.0"
        }
      }
    }
  }
}
```

**Comment by rowild** [comment]
Ah!!! Thank you so much for this feedback,, this makes me very happy!

**Comment by rowild** [comment]
I keep encountering problems that snowpack issues when running "pnpm run dev":
Package "@csstools/convert-colors" not found. Have you installed it?
Package "@nodelib/fs.scandir" not found. Have you installed it?

**Comment by mcmxcdev** [comment]
Seems to be installation issues that are caused by `snowpack` itself, but never will be solved, because it got deprecated in April: https://github.com/FredKSchott/snowpack#snowpack
