### ISSUE TITLE
[snowpack.dev website] mobile version's menu does not work

### ISSUE THREAD

**Issue by rowild** [pnpm/pnpm#3752]
[This is NOT a pnpm issue]

The mobile version of snowpack.dev does not work:

- menu does not show
- on a mobile phone in landscape mode it is not possible to scroll down.

If this is not the right place to file this issue, please let me know where I can do so. Thank you! :-)

**Comment by TerryRPatterson** [comment]
This issue should probably go to [snowpack's repository](https://github.com/snowpackjs/snowpack).

**Comment by rowild** [comment]
@TerryRPatterson  You are of course totally tight! Absolutely! Sorry about this mix-up and thanks for letting me know!
