### ISSUE TITLE
False positive report for peer dependency warning with experimental value

### ISSUE THREAD

**Issue by mhatvan** [pnpm/pnpm#3753]
### Code to reproduce the issue:
Install `reactfire@3.0.0-rc.0` and `react@17.0.1` as `dependencies`. 

### Expected behavior:
No peer dependency warning since `react@>=16` should be satisfied by `react@17.0.1`

### Actual behavior:

`ERROR  packages/common: reactfire@3.0.0-rc.0 requires a peer of react@>=16 || experimental but version 17.0.1 was installed.`

### Additional information:

 - `node -v` prints: v14.17.1
 - Windows, macOS, or Linux?: Ubuntu 21.04

**Comment by lucas-labs** [comment]
I'm getting a similar warning message with two internal packages in my organization.

` WARN  @my-org/package1@0.0.7 requires a peer of @my-org/package2@^0.0.2 but version 0.0.3 was installed.`

I guess **^0.0.2** should be satisfied by **0.0.3**

**Comment by zkochan** [comment]
@lucas-labs no. A change to the first non-zero integer is always considered a breaking change. So 0.0.3 does not satisfy ^0.0.2
