### ISSUE TITLE
pnpm install successes despite some packages still missing

### ISSUE THREAD

**Issue by xbtsw** [pnpm/pnpm#3754]
### Steps to reproduce the issue:

1. With empty store, empty virtual store and empty node_modules, run `pnpm install --store=<somepath> --frozen-lockfile`
2. Notice that 
    1. The command exited with code 0 with some package not installed, last line of log is:
        `Progress: resolved 2062, reused 1518, downloaded 521, added 2039`
    2. The word `, done` is not printed in the last line of log. 
    3. Any postinstall script was not ran.
    4. Examine node_modules folder and notice some direct dependencies is not present.
3. Without changing lockfile, run the same command as seen in step (1) again.
4. Note that the missing packages got installed this time, the observations in (2) no longer true.
5. Repeat step 1-2 in different machines, note that every time the "added" number changes.

### Additional information:

We recently upgraded from pnpm5 to pnpm6 and noticed above. This is almost 100% reproducible on our CI machines. This reminds me that with pnpm5, we have problem of network issues when downloading packages. Usually in the form of ECONNRESET or checksum mismatch. With pnpm5 the retry (as specified with fetch-retries) works. With pnpm6, we no longer see retry in the logs but observed missing packages after `pnpm install` exits successfully. 

 - `node -v` prints: 14.17.6
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
Could you narrow down which exact version introduced the regression?

Wei Chen ***@***.***> ezt írta (időpont: 2021. szept. 8., Sze
3:34):

**Comment by xbtsw** [comment]
Thanks for the swift fix @zkochan. 🎉
