### ISSUE TITLE
A bunch of warnings, the dependency analyzer is not working properly

### ISSUE THREAD

**Issue by hhaoao** [pnpm/pnpm#3761]
### pnpm version:

> 6.14.7

### Code to reproduce the issue:

```cmd
pnpm install
```

### Expected behavior:

Correctly install dependency packages

### Actual behavior:

There are only a few hints.I can't locate the problem.

```cmd
F:\doc\testing-library-docs>pnpm install

 WARN  kcd-scripts: @rollup/plugin-babel@5.3.0 requires a peer of @types/babel__core@^7.1.9 but none was installed.
 WARN  kcd-scripts > eslint-config-kentcdodds > @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree: tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
 WARN  kcd-scripts: eslint-config-kentcdodds@19.2.0 requires a peer of typescript@^4.0.0 but none was installed.
 WARN  kcd-scripts > jest > @jest/core: @jest/reporters@27.1.1 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none was installed.
 WARN  kcd-scripts > jest > @jest/core > jest-config > jest-environment-jsdom > jsdom: ws@7.5.5 requires a peer of bufferutil@^4.0.1 but none was installed.
Packages: +1721
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 WARN  9 other warnings
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: F:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1718, reused 1709, downloaded 8, added 592
```

### Additional information:

 - `node -v` prints: `v16.6.2`
 - Windows, macOS, or Linux?: `Windows`
 - Relevant details: [testing-library-docs#928](https://github.com/testing-library/testing-library-docs/issues/928)

**Comment by Saiv46** [comment]
Bump, same problem, when using `pnpm i`, following warnings are printed:
```
 WARN  esbuild-vue: @vue/component-compiler@4.2.4 requires a peer of postcss@>=6.0 but none was installed.
 WARN  esbuild-vue: @vue/component-compiler@4.2.4 requires a peer of vue-template-compiler@* but none was installed.
 WARN  esbuild-vue@0.3.3 requires a peer of vue-template-compiler@^2.6.12 but none was installed.
 WARN  eslint-config-standard@16.0.3 requires a peer of eslint-plugin-import@^2.22.1 but none was installed.
 WARN  eslint-config-standard@16.0.3 requires a peer of eslint-plugin-node@^11.1.0 but none was installed.
 WARN  2 other warnings
```
And yeah, it breaks Vue dependencies - `@vue/component-compiler` module can't find `vue-template-compiler`, despite last one **is** actually installed.

**Comment by Saiv46** [comment]
Btw,
PNPM version: `6.15.1`
NodeJS: `v16.8.0`
OS: `Windows`

**Comment by Saiv46** [comment]
The `package.json` of `@vue/component-compiler` have these dependencies (everything else is omitted):
```json
{
  "name": "@vue/component-compiler",
  "version": "4.2.4",
  "devDependencies": {
    "pug": "^3.0.1",
    "sass": "^1.18.0",
    "vue-template-compiler": "^2.5.16"
  },
  "optionalDependencies": {
    "pug": "^3.0.1",
    "sass": "^1.18.0"
  },
  "peerDependencies": {
    "postcss": ">=6.0",
    "vue-template-compiler": "*"
  }
}
```

It's not usual for someone to specify dependencies as dev&peer or dev&optional, this may confuse PNPM and result in these warnings.

**Comment by zkochan** [comment]
> So, PNPM installs vue-template-compiler, but does not create symlinks, despite it was being specified in @vue/component-compiler. Which later results in MODULE_NOT_FOUND runtime errors.

but `vue-template-compiler` is a devDependency of `@vue/component-compiler`, so pnpm will not install it.

you need to install the missing peer dependencies.

if you want to see all the warnings, you may run `pnpm install --reporter=append-only`

**Comment by hhaoao** [comment]
@zkochan Hello, do you know in which version this problem was fixed? Recently I tried to update and found that it can work normally, I want to attach it to the repair branch and then close this issue.

Warning about `peers`:
I read the documentation about [peers](https://pnpm.io/de/5.x/how-peers-are-resolved) warning, this is a normal prompt, pnpm can already handle it perfectly on its own.

**Comment by zkochan** [comment]
I don't remember fixing this specific issue.

**Comment by mcmxcdev** [comment]
I think this issue can be closed, as everything is done properly on pnpm's side.

If you want to avoid peer dependency warnings, either install them yourself or you can probably use the newly introduced auto-installing of peer dependencies: https://github.com/pnpm/pnpm/pull/4776
