### ISSUE TITLE
If `package.json#bin` points to path that doesn't exist, pnpm install errors

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#3763]
I found a package where it pointed the bin to dist, but the dist was generated in a `prepare` script.

### Code to reproduce the issue:

https://github.com/vjpr/issue-pnpm-cannot-find-realpath

Just run `pnpm i`

### Expected behavior:

No error

### Actual behavior:

```
 ERROR  ENOENT: no such file or directory, chmod '/Users/xxx/dev/code/issue-pnpm-cannot-find-realpath/packages/foo/dist/index.js'
```

### Additional information:

 - `node -v` prints: 16.7
 - Windows, macOS, or Linux?: macOS + Windows

**Comment by wre232114** [comment]
I think it is not a bug. bins should be create before the execution of scritps. I think the best solution for this situation is make a persist bin.js, which call dynamic generated code

**Comment by vjpr** [comment]
Sure, but it should be handled by pnpm with a nice warning message and it shouldn't block the install from completing.

**Comment by YunYouJun** [comment]
> I think it is not a bug. bins should be created before the execution of scritps because scripts may use bins. I think the best solution for this situation is make a persist bin.js, which call dynamic generated code

But when we use workspace, `workspace/b` depend on `workspace/a`, use relative link `../a`, a haven't generate `bin`.
This will prevent the installation of the entire project.

**Comment by rxliuli** [comment]
There is also this problem. . .
