### ISSUE TITLE
PNPM standalone script fails with latest Powershell

### ISSUE THREAD

**Issue by maicol07** [pnpm/pnpm#3770]
### Expected behavior:
Install is successful
### Actual behavior:
When using latest Powershell (v7.2.0-preview.9) then the script fails with this error:
```
PS C:\Windows\System32> (Invoke-WebRequest 'https://get.pnpm.io/v6.14.js' -UseBasicParsing).Content | node - add --global pnpm
[stdin]:8258
        const colorCode = " < 8 ? c : "8;5;" + c);
                                       ^

SyntaxError: Unexpected number
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at internal/process/execution.js:77:19
    at [stdin]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:205:5)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
```

### Additional information:

 - `node -v` prints: v14.16.1
 - Windows, macOS, or Linux?: Windows

**Comment by xiaohuoni** [comment]
Encounter the same problem

**Comment by zkochan** [comment]
It looks like a Windows issue. It started happening in GitHub actions. The content of the downloaded script looks good but when running it with node, there is this error.

**Comment by ylemkimon** [comment]
PowerShell has changed the default value of `$PSStyle.OutputRendering` to `OutputRendering.Host`, which strips ANSI codes when piping. Set `$PSStyle.OutputRendering = 'Ansi'` before downloading pnpm.

**Comment by zkochan** [comment]
I guess we need to change it in the docs.

**Comment by ylemkimon** [comment]
Or we could bundle with ASCII only. Maybe a few more bytes, but it'd give wider compatibility.

**Comment by zkochan** [comment]
But I think we bundle with the default configuration of esbuild, which is ascii: https://esbuild.github.io/api/#charset

**Comment by ylemkimon** [comment]
Sorry, the escape character is also ASCII. I meant printable characters only.

**Comment by zkochan** [comment]
I am not sure it is possible.

But it works if the content is not piped but saved to a file instead:

```
Invoke-WebRequest 'https://get.pnpm.io/v6.16.js' -UseBasicParsing -outfile pnpm.js; node pnpm.js add --global pnpm
```

**Comment by zkochan** [comment]
Should we recommend this approach? https://github.com/pnpm/pnpm.github.io/pull/172

The benefit is that it works on older PowerShell as well and doesn't change the value of `$PSStyle.OutputRendering` for the session.

**Comment by zkochan** [comment]
This script is no longer recommended. We have new scripts in our docs.
