### ISSUE TITLE
pnpm workspace imports only dist dir among packages

### ISSUE THREAD

**Issue by linbudu599** [pnpm/pnpm#3773]
### pnpm version:

**6.15.0**

### Code to reproduce the issue:

I have an Nx-based Monorepo project, and I'm migrating it to the pnpm workspace, and in the process I found that pnpm only adds the finished build dist directory to the referrer's node_modules. The project structure is roughly as follows:

```text
packages
  - foo
    - dist
    - src
    - package.json
  - bar
    - dist
    - src
    - package.json
  - baz
    - dist
    - src
    - package.json
```

### Expected behavior:

When I'm executing `pnpm add foo --filter bar -S`, the expected behavior is all of `foo` dir is linked into `bar`'s node_modules like:

```text
packages
  - foo
    - dist
    - src
    - package.json
  - bar
    - node_modules
      - foo
        - dist
        - src
        - package.json
    - dist
    - src
    - package.json
  - baz
    - dist
    - src
    - package.json
```

### Actual behavior:

```text
packages
  - foo
    - dist
    - src
    - package.json
  - bar
    - node_modules
      - foo
        - src
        - package.json
    - dist
    - src
    - package.json
  - baz
    - dist
    - src
    - package.json
```

But in reality, only the content in dist is linked to here, `bar/node_modules/foo/*` is the content inside `foo/dist`.

### Additional information:

- package.json `main` fileds: `dist/src/index.js`
- In nx project
- No more configuration in `pnpm-workspace.yaml` except `packages`

 - `node -v` prints: v14.17.4
 - Windows, macOS, or Linux?: macOS

**Comment by wre232114** [comment]
What is the version of the package foo in the pnpm-lock.yaml?

**Comment by linbudu599** [comment]
> What is the version of the package foo in the pnpm-lock.yaml? Does the version uses link:../foo?

I'm using `workspace:` protocal, which is added automatically by `pnpm add ...`

**Comment by fireairforce** [comment]
I think this behaviour is as normal, because you set the `main` files in foo, so the bar will only linked the foo's dist dir. 
It's the same as publishing the package to the registry
