### ISSUE TITLE
Run scripts without `--`?

### ISSUE THREAD

**Issue by xnuk** [pnpm/pnpm#3778]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
pnpm says `npm run <cmd>`'s equivalent is `pnpm <cmd>`. But because it isn't equivalent of `yarn run`'s behavior, I frequently confuses for double-dashed option arguments (like why it isn't passes `--something` to its argv?).

When package.json is given like:
```json
{ "packageManager": "pnpm@6.15.1"
, "scripts": { "echo": "echo" }
, "engines": { "node": "16.9.1", "pnpm": "6.15.1" }
}
```

This commands are problematic:
```sh
$ pnpm echo --minify
 ERROR   ERROR  Unknown option: 'minify'
For help, run: pnpm help run

$ pnpm run echo --minify

> some-package@0.1.0 echo /path/to/some-package
> echo
```

Adding double dash `--` at the front makes correct:
```sh
$ pnpm -- echo --minify

> some-package@0.1.0 echo /path/to/some-package
> echo "--minify"

--minify

$ pnpm run -- echo --minify

> some-package@0.1.0 echo /path/to/some-package
> echo "--minify"

--minify
```

**Describe the solution you'd like**
- `pnpm run` has its options a lot: `--[no-]color`, `--dir`, `--filter`, etc. Restricting their positions to front could be a way, like: `pnpm --no-color prettier --write` is valid - while `pnpm prettier --write --no-color` is not.
- Make a new command for this
- Make `pnpx` do this kind of job
- console.error("`--minify` is not a valid command. Perhaps you forgot to add `--`?")

I don't want to say this is a _better_ than current behavior (because `npm` has similar behavior as current `pnpm` does), but I think it's considerable.

**Describe alternatives you've considered**
Yarn v1 do this well. This is the output of `yarn echo --minify`:
```
yarn run v1.22.11
$ echo --minify
--minify
Done in 0.05s.
```

**Comment by wre232114** [comment]
I think optimizing the log like `(" ERROR   Unknown option: 'minify', perhaps you forgot to add a '--' before '--minify' if you want to pass it to scripts.")` may be enough, yarn's way makes options in chaos

**Comment by zkochan** [comment]
I don't have objections. `pnpm exec` already works like this. `pnpm exec echo --minify` will work.

**Comment by zkochan** [comment]
I guess making `pnpm exec -h` work shouldn't be a problem.

**Comment by illright** [comment]
True, but the more exceptions we make, the more fragile and unpredictable the CLA parsing becomes. I'm not too keen on this

**Comment by zkochan** [comment]
I agree that using `--` in each commands that run scripts (dlx, exec, run) would be good for options parsing. However, Yarn support these commands without `--` and users will ask us to support the same as it is easier to type. The docker CLI as welll support executing scripts without escaping.

**Comment by zkochan** [comment]
https://github.com/pnpm/pnpm/pull/4290 merged
