### ISSUE TITLE
`pnpm env use --global lts` gets a ERR_PNPM_FETCH_404

### ISSUE THREAD

**Issue by wolfram-fm** [pnpm/pnpm#3786]
### pnpm version:
6.15.1

### Code to reproduce the issue:
`pnpm env use --global lts`

### Expected behavior:
installs Node v14

### Actual behavior: 
```
GET https://nodejs.org/download/release/v14.17.6/node-v14.17.6-darwin-arm64.tar.gz error (ERR_PNPM_FETCH_404)
```

### Additional Details:
- mac Big Sur on M1
- Looks like the [node releases](https://nodejs.org/download/release/v14.17.6/) no longer has the ...arm64.tar.gz file anymore.

**Comment by zkochan** [comment]
Maybe they started adding it only from v16.
Could we use a fallback? Will x64 work with macOS on M1?

**Comment by wolfram-fm** [comment]
Yeah, [looking at nvm](https://github.com/nvm-sh/nvm#macos-troubleshooting), it looks like x64 will work if they have Rosetta 2 installed.

**Comment by zkochan** [comment]
Alternatively, we could probably build Node.js from sources.

**Comment by wolfram-fm** [comment]
Either solution is feasible. It seems like Node v16 is going to be the LTS target soon anyway, so in terms of my specific use case of installing via the `--lts` flag, this will "fix itself". However, anyone that wants to install v14 or below on an M1 machine will see this again.

**Comment by callumlocke** [comment]
Any update on this? Node 14 is still officially supported until [mid-2023](https://nodejs.org/en/about/releases/), so it will still be used by many projects and platforms for a long time. Any fix or workaround for this would be really appreciated.

`nvm` seems to be able to install Node 14 on M1 machines without any issue, but I'm not sure if it's possible/a good idea to use that alongside pnpm?

**Comment by callumlocke** [comment]
For anyone looking for a workaround to use Node 14 with pnpm on Apple Silicon: https://github.com/pnpm/pnpm/issues/4489#issuecomment-1101321063

**Comment by zkochan** [comment]
Should we download node-v14.17.6-linux-arm64 instead?
