### ISSUE TITLE
Could not resolve dependency when commit specified as semver

### ISSUE THREAD

**Issue by watery** [pnpm/pnpm#3789]
### pnpm version:
6.15.1
### Code to reproduce the issue:
Add this dependency
```
...
"@react-native-picker/picker": "git://github.com/react-native-picker/picker.git#1.1.3",
...
```

### Expected behavior:
The installation process goes on installing all the dependencies.

### Actual behavior:
The following error is output:

```
ERROR  Could not resolve 1.1.3 to a commit of https://github.com/react-native-picker/picker.git.

at resolveRefFromRefs         ../../../../AppData/Roaming/nvm/v12.22.0/node_modules/pnpm/dist/pnpm.cjs:84171  throw new Error(`Could n…
at resolveRef                 ../../../../AppData/Roaming/nvm/v12.22.0/node_modules/pnpm/dist/pnpm.cjs:84165  return resolveRefFromRef…
at runMicrotasks
at processTicksAndRejections  internal/process/task_queues.js:97
at async resolveGit           ../../../../AppData/Roaming/nvm/v12.22.0/node_modules/pnpm/dist/pnpm.cjs:84115  const commit = await res…
at resolve                    ../../../../AppData/Roaming/nvm/v12.22.0/node_modules/pnpm/dist/pnpm.cjs:85185  const resolution = (_a =…
at async run                  ../../../../AppData/Roaming/nvm/v12.22.0/node_modules/pnpm/dist/pnpm.cjs:71133  resolve(await operation);

```

### Additional information:

 - `node -v` prints: v12.22.0
 - Windows, macOS, or Linux?: Windows 10 x64 (using [NVM for Windows](https://github.com/coreybutler/nvm-windows))

I've found other issues about this error:

- https://github.com/pnpm/pnpm/issues/1127
- https://github.com/pnpm/pnpm/issues/3501

I guess this is due to the dependency being expressed as _semver_ and not as _commit hash_ (which seems [an alternative syntax](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies)), because if I replace `1.1.3` with `ecd3d47` (from the [v1.1.3 tag / release page](https://github.com/react-native-picker/picker/releases/tag/v1.1.3)) pnpm has no problems finding it.

**Comment by zkochan** [comment]
This works:

```
"@react-native-picker/picker": "git://github.com/react-native-picker/picker.git#semver:1.1.3",
```

**Comment by watery** [comment]
Oops! I just misread the docs, thanks for the clarification.
