### ISSUE TITLE
Use RxJS

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#379]
Currently `pnpm` uses a huge "magic" object called `cmd` which is passed around between all the major functions. I would like to refactor the code to get rid of this object.

`ied` pretty successfully adopted RxJS, so I think it should work out for `pnpm` as well

**Comment by iamstarkov** [comment]
i would like to get rid off magic as much as possible too

**Comment by zkochan** [comment]
This was done, will be released probably in next version
