### ISSUE TITLE
pnpm fails to install some binary packages in Windows with `script-shell`

### ISSUE THREAD

**Issue by BasixKOR** [pnpm/pnpm#3791]
### pnpm version:
6.15.1

### Code to reproduce the issue:
1. `pnpm config set script-shell true`
2. `pnpm add esbuild`. (or `@pnpm/beta`, `@cloudflare/wrangler`)
3. Error happens with this error message:

```
 WARN  Cannot link binary 'pnpm' of '@pnpm/beta' to 'C:\Users\basix\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\@pnpm+beta@0.0.6-6.15.1\node_modules\@pnpm\beta\node_modules\.bin': binary of '@pnpm/win-x64' is already linked
node_modules/.pnpm/@pnpm+beta@0.0.6-6.15.1/node_modules/@pnpm/beta: Running preinstall script...
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type boolean (true)
    at validateString (internal/validators.js:124:11)
    at normalizeSpawnArguments (child_process.js:435:3)
    at spawn (child_process.js:575:13)
    at Object.spawnWithSignal (child_process.js:714:17)
    at spawn (pkg/prelude/bootstrap.js:1835:27)
    at spawn (C:\snapshot\dist\pnpm.cjs)
    at runCmd_ (C:\snapshot\dist\pnpm.cjs)
    at runCmd (C:\snapshot\dist\pnpm.cjs)
    at runPackageLifecycle (C:\snapshot\dist\pnpm.cjs)
    at Array.<anonymous> (C:\snapshot\dist\pnpm.cjs) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Expected behavior:
pnpm installs.

### Actual behavior:
pnpm crashes while installing, and any subsequent installation will fail due to incomplete installation.

### Additional information:

 - `node -v` prints:
   - v16.10.0
 - Windows, macOS, or Linux?:
   - Windows

#### Workaround
* You can remove incorrectly installed packages by hand. Removing the link in `node_modules` seems to work.

**Comment by BasixKOR** [comment]
For some reason I saw the same error while installing `@cloudflare/wrangler`. Maybe not specific to `@pnpm/beta`...

**Comment by zkochan** [comment]
Maybe it happens when running this file: https://github.com/pnpm/pnpm/blob/main/packages/beta/setup.js

But I am not sure at what line the issue might happen.

**Comment by BasixKOR** [comment]
Uhh, it seems like it affects `esbuild` as well. Pretty much anything involving binary fails with this error. I'll edit the issue to reflect this, but I'm not 100% certain what causes this...

**Comment by BasixKOR** [comment]
I confirmed this bug occurs regardless of standalone installation or `@pnpm/beta`. The description and title was edited accordingly to reflect those issues.

**Comment by BasixKOR** [comment]
well it was my problem... I've mistaken `script-shell` with `shell-emulator`. Sorry for the confusion!
