### ISSUE TITLE
pnpm did not respect peerDependencies version requirement in pkg.json

### ISSUE THREAD

**Issue by niyan-ly** [pnpm/pnpm#3796]
### Background:
`puppeteer-cluster` declares `puppeteer` as a `peerDependencies` in `package.json`, and gives it a version requirement with `^1.5.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0`. In `npm@7`, install those two packages without correct version will result an `ERESOLVE` error.

```text
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: pnpm-peer-issue-test@1.0.0
npm ERR! Found: puppeteer@10.4.0
npm ERR! node_modules/puppeteer
npm ERR!   dev puppeteer@"^10.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer puppeteer@"^1.5.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0" from puppeteer-cluster@0.22.0
npm ERR! node_modules/puppeteer-cluster
npm ERR!   dev puppeteer-cluster@"^0.22.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Code to reproduce the issue:
please see this repo: https://github.com/niyan-ly/pnpm-peer-issue-test

### Expected behavior:
should give some npm-like error message, and stop package installation.

### Actual behavior:
it just goes like `peerDenpendencies` version requirement being ignored.

### Additional information:

 - `node -v` prints: `v14.17.5`
 - Windows, macOS, or Linux?: `MacOS 11.6`

**Comment by zkochan** [comment]
Well, if you remove the lockfile and node_modules, then run `pnpm install`, you'll get this warning printed:

```
 WARN  puppeteer-cluster@0.22.0 requires a peer of puppeteer@^1.5.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 but version 10.4.0 was installed.
```

If you want pnpm to fail on such warnings, set the [strict-peer-dependencies](https://pnpm.io/npmrc#strict-peer-dependencies) setting to `true`.
