### ISSUE TITLE
pnpm can't be install on MacOS

### ISSUE THREAD

**Issue by wrzrmzx** [pnpm/pnpm#3810]
### Code to reproduce the issue:

sudo npx pnpm add -g pnpm (npx pnpm add -g pnpm also tried but get same result)

### Actual behavior: Error blow:
 ERROR  No write access to the found global executable directories
The found directories:
  /usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin
/usr/local/bin

### Additional information:

 - `node -v` prints: v16.6.1
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
Try one of these scripts:

https://pnpm.io/installation#nodejs-is-not-preinstalled

**Comment by wrzrmzx** [comment]
> Try one of these scripts:
> 
> https://pnpm.io/installation#nodejs-is-not-preinstalled

Oh it works, thank you
