### ISSUE TITLE
`make-dedicated-lockfile` re-resolves dependency ranges

### ISSUE THREAD

**Issue by gaggle** [pnpm/pnpm#3864]
### pnpm version:
6.14.7

### Code to reproduce the issue:

This is just one example based on how we use this tool, where we delete all dev-dependencies from the monorepo to optimize it for production. I'd like to not take up a lot of space explaining why we use it this way (though happy to elaborate if asked), but here's the command to run:
```
for p in $(pnpm --recursive --parallel exec pwd); do
  cat "$p/package.json" | jq 'del(.devDependencies)' >"$p/~package.json"
  mv "$p/~package.json" "$p/package.json"
done
pnpm exec make-dedicated-lockfile
```
WIth this the monorepo has no dev-dependencies anymore, and the pnpm-lock.yaml file is updated.

### Expected behavior:
`make-dedicated-lockfile` promises "A new lockfile will be generated, using dependencies from the shared workspace lockfile", I read that to mean the generated lockfile will be identical to the original lockfile except only containing dependencies related to the selected packages.

### Actual behavior:
`make-dedicated-lockfile` actually generates a new lockfile with **re-resolved** version ranges, i.e. if package.json specifies `^1.1.1` and the lockfile had resolved to `1.1.1` then the new lockfile could now be resolving to `^1.1.5`. This newly-resolved lockfile must not be used in production because it's now based on untested dependencies (I'm talking about when using `make-dedicated-lockfile` during CI, because it means untested dependencies are pulled in that developers never know about!).

### Additional information:
This conspired to bite us in the ass, with countless man-hours wasted as we chased our own tails to debug a production issue, ruling out every variance until we noticed this tiny version difference in a dependency, and traced that all the back to our use of `make-dedicated-lockfile` 😱😭

Is it a bug? Or by design? If it's by design think it should be highlighted in big letters in the tool's description, but I hope it's a bug because the tool is very useful to prune out dev-dependencies from our mono repository.

 - `node -v` prints:
 v16.1.0

 - Windows, macOS, or Linux?: Mac dev, CI/build environment is Linux (Heroku)

**Comment by zkochan** [comment]
If the lockfile is not modified and install runs with `--lockfile-only`, then I don't think install needs to run at all.

**Comment by bitfrost** [comment]
I see the above referenced commit about introducing frozen, is there problem with that solution / reason it hasn't been merged?   We noticed this behavior and are looking for a way to both use make-dedicated-lockfile and not introduce drift / lock file 'updates' when using it.

**Comment by zkochan** [comment]
I think this whole section should be removed

https://github.com/pnpm/pnpm/blob/fff0e4493b0fac62fd157f05a60100665317e1d3/packages/make-dedicated-lockfile/src/index.ts#L53-L69

I just don't remember why I added installation at all there. If the lockfile should not be modified and the install is running with `--lockfile-only`, then it doesn't do anything.

**Comment by bitfrost** [comment]
Make sense to me.  I will try a PR / local change later without the install at all.  Hopefully it isn't needed for some reason we can't think of atm :)
