### ISSUE TITLE
Cannot globally install a project from a folder

### ISSUE THREAD

**Issue by Toxaris** [pnpm/pnpm#3865]
### pnpm version:

6.17.0

### Code to reproduce the issue:

```
pnpm env use --global 12.22.6
echo 'console.log("world");' > hello.js
echo '{ "name": "hello-world", "version": "1.0.0", "bin": { "hello": "hello.js" }}' > package.json
pnpm add --global . && hello
```

### Expected behavior:

package is installed and "world" is printed.

### Actual behavior:

```
ERR_INVALID_ARG_TYPE  The "path" argument must be of type string. Received undefined
```

### Additional information:

 - `node -v` prints `v12.22.6`
 - Linux
 - `pnpm add --global ./$(pnpm pack)` doesn't work either, see #3866

**Comment by Toxaris** [comment]
Ah nice, that resolves my use casem thanks! Not sure whether you want to close this bug then?

**Comment by wflixu** [comment]
I have the same problem 

![image](https://user-images.githubusercontent.com/37231473/221387855-3197ada7-33fb-4f57-aec6-db3bd1aaf1ea.png)

**Comment by zkochan** [comment]
@wflixu probably you have installed pnpm not using the standalone script. In that case `pnpm env use --global` doesn't work.

One of [these scripts](https://pnpm.io/installation#using-a-standalone-script) should be used to install pnpm if you want to use pnpm for installing node.js
