### ISSUE TITLE
Standardize to package-lock.json

### ISSUE THREAD

**Issue by LifeIsStrange** [pnpm/pnpm#3875]
I am not an expert but I believe that pnpm-lock.yaml and yarn.lock are historical contingencies.
package-lock.json had flaws but they have (all?) been corrected in the v2 format since npm 7.x

> Changes to the lockfile
One change to take note of is the new lockfile format, which is backwards compatible with npm 6 users. The lockfile v2 unlocks the ability to do deterministic and reproducible builds to produce a package tree.
In prior versions, the yarn.lock files were ignored, the npm CLI can now use yarn.lock as the source of package metadata and resolution guidance. If a yarn.lock file is present, then npm will also keep it up-to-date with the contents of the package tree.
Running npm install with npm 7 in a project with a v1 lockfile will replace that lockfile with the new v2 format. To avoid this, you can run npm install --no-save.

more on this [here](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/)
Therefore it could make sense to support package-lock.json v2 and to deprecate pnpm-lock.yaml (could be auto deleted and transformed into a package-lock file)

gains: better interop with npm, and with tools that parse package-lock.json

**Comment by zkochan** [comment]
No, this is not possible. `pnpm-lock.yaml` is one of the reasons pnpm is so fast. `package-lock.json` mimics the structure of the hoisted node_modules created by npm. We can't use `package-lock.json` because we don't create a hoisted node_modules.
