### ISSUE TITLE
`pnpm add --global` destroy pnpm installation

### ISSUE THREAD

**Issue by Toxaris** [pnpm/pnpm#3893]
### pnpm version:

6.18.0

### Code to reproduce the issue:

```
curl -fsSL https://get.pnpm.io/install.sh | sh -
pnpm -v
pnpm env use --global 12.22.6
pnpm add --global typescript
tsc -v
pnpm -v
```

### Expected behavior:

Typescript gets installed and pnpm still works.

### Actual behavior:

Typescript gets installed but pnpm hangs (because the pnpm binary gets overwritten by a shell script that calls itself, like in https://github.com/pnpm/pnpm/issues/3858#issuecomment-946607473).

### Additional information:

 - `node -v` prints: 12.22.6
 - Windows, macOS, or Linux?: Linux

**Comment by ChrisTsou** [comment]
I also bumped on this, any time i 'pnpm add -g pnpm' or install a global package.

**Comment by Toxaris** [comment]
I tried various combinations again and with current pnpm (6.22.2) I cannot reproduce this anymore.
