### ISSUE TITLE
`pnpm up` not installing new minor versions when package range specified with `^`

### ISSUE THREAD

**Issue by jwarby** [pnpm/pnpm#3898]
### Code to reproduce the issue:

I am running the following to try to update my company's private packages to the latest minor versions:

```bash
pnpm up "@my-company-scope/*"
```

### Expected behavior:

`pnpm` installs the latest minor versions of packages which are specified with a `^` range, eg:

```diff
-    "@my-company-scope/my-package": "^0.94.0",
+    "@my-company-scope/my-package": "^0.97.0",
```

### Actual behavior:

All of the dependencies I want to upgrade have the `^` range specifier, but `pnpm` only seems to be installing patch releases for  each package, eg:

```diff
-    "@my-company-scope/my-package": "^0.94.0",
+    "@my-company-scope/my-package": "^0.94.3",
```

This is happening when I run the update command from either a single workspace package or if I try to run recursively for all workspace packages.

Originally discussed on discord here: https://discord.com/channels/731599538665553971/731599538665553975/900040628069597225

### Additional information:

 - `node -v` prints: v14.15.1
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
This works as expected. A minor upgrade is an upgrade to the second number. Leading zeroes are not counted.

Hence:

major.minor.patch
0.major.minor
0.0.major

This works the same way with Yarn and npm.

**Comment by jwarby** [comment]
Wow OK, I did not know that! Thanks for looking into it and writing up @zkochan :+1:
