### ISSUE TITLE
Global binaries are broken after `brew upgrade node`

### ISSUE THREAD

**Issue by prinsss** [pnpm/pnpm#3905]
### pnpm version:

```
6.18.0
```

### Code to reproduce the issue:

1. Install node with Homebrew, and install pnpm with `npm install -g pnpm`
2. Install a global package which has binaries, e.g. `pnpm add -g wscat`
3. pnpm adds the bin `wscat` to global bin path, which on my machine is `/opt/homebrew/bin`. And the bin shim `/opt/homebrew/bin/wscat` are generated as below:

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"/opt/homebrew/Cellar/node/16.10.0_1/bin/node"  "$basedir/../lib/pnpm-global/5/node_modules/wscat/bin/wscat" "$@"
exit $?
```

which is using an absolute path of node executable. However, this node path won\'t be preserved after a version upgrade performed by Homebrew.

For example, if we run `brew upgrade node` that upgrades node from version `16.10.0_1` to `16.11.1` (and also do a `brew cleanup`), the directory `/opt/homebrew/Cellar/node/16.10.0_1` would be removed and a new directory `/opt/homebrew/Cellar/node/16.11.1` are created.

This behavior makes the node executable path in bin shims no longer available.

### Expected behavior:

The global bins should still work after `brew upgrade node`.

Maybe we should use the symlink path `/opt/homebrew/bin/node` instead of the real path `/opt/homebrew/Cellar/node/16.10.0_1/bin/node` in the bin shims that created by `pnpm add -g`?

### Actual behavior:

The global bins stop working after `brew upgrade node`, giving errors:

```
/opt/homebrew/bin/wscat: line 8: /opt/homebrew/Cellar/node/16.10.0_1/bin/node: No such file or directory
```

### Additional information:

`~/.npmrc`:

```
global-dir=/opt/homebrew/lib/pnpm-global
```

`/opt/homebrew/lib/pnpm-global/5/package.json`:

```json
{
  "dependenciesMeta": {
    "pnpm": {
      "node": "/opt/homebrew/Cellar/node/16.11.1/bin/node"
    },
    "wscat": {
      "node": "/opt/homebrew/Cellar/node/16.10.0_1/bin/node"
    }
  },
  "dependencies": {
    "pnpm": "^6.18.0",
    "wscat": "^5.0.0"
  }
}
```

 - `node -v` prints: `v16.11.1`
 - Windows, macOS, or Linux?: `macOS 11.6`

**Comment by wildwestrom** [comment]
I think I'm getting the same issue on my machine despite the fix.
