### ISSUE TITLE
Script arguments quotes not escaped

### ISSUE THREAD

**Issue by zeusdeux** [pnpm/pnpm#3907]
Commit reverts happen often and this issue breaks steps during CI/CD such as publishes and deploys that consume commit messages.

### Code to reproduce the issue:

Given a script defined as —

```json
{
  "scripts": {
     "echo": "echo"
  }
}
```

Then let's export an environment variable containing quotes and parens (to trigger a shell parse error)

```sh
export ENV_VAR='Revert "feature (#1)"'
```

Finally, run —

```sh
pnpm run echo -- $ENV_VAR
```

### Expected behavior:

(As done by `npm`)

![image](https://user-images.githubusercontent.com/635512/138275902-420c368c-1eae-4848-84af-e03524c27097.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/635512/138275983-138fd366-2ecb-4ae4-936c-c82a97d50504.png)

### Additional information:

 - `node -v` prints: v14.17.5
 - Windows, macOS, or Linux?: macOS and Linux

**Comment by ylemkimon** [comment]
IMHO, you should not use scripts to pass the commit title as an argument, as it may contain other special shell characters.

**Comment by zeusdeux** [comment]
Thanks for the fix @leeight and for landing it @zkochan!
