### ISSUE TITLE
Error only in pnpm, but not in yarn. (nesjs & MikroORM project)

### ISSUE THREAD

**Issue by rizchaerul** [pnpm/pnpm#3917]
### pnpm version: 6.19.0

So as the title says, i have a project using pnpm and i got error when i run it, but when i change my package manager to yarn the error is no longer there.

### Code to reproduce the issue:

1. Clone from https://github.com/rizchaerul/bug
2. Run pnpm install
3. Run pnpm run start:dev -> there will be an error
4. Remove dist folder, node_modules folder and pnpm-lock.yaml
5. Run yarn install
6. Run yarn start:dev -> the error is gone

### Additional information:

 - `node -v` prints: v14.17.1
 - Windows, macOS, or Linux?: Windows

**Comment by jmcdo29** [comment]
@rizchaerul  If you do `pnpm i @mikro-orm/knex` and then start your server it will work as expected. I assume this has something to do with having a the dependency actually installed vs installed via peer deps

**Comment by rizchaerul** [comment]
I tried installing @mikro-orm/knex, and it still doesn't work. Are you sure you used pnpm?

What i tried:
1. git clone https://github.com/rizchaerul/bug.git
2. cd bug
3. pnpm i
4. pnpm run start:dev -> error
5. pnpm i @mikro-orm/knex
6. pnpm run start:dev -> still error

**Comment by jmcdo29** [comment]
Yep, that's exactly what I did.
