### ISSUE TITLE
Global script runner in monorepo mode

### ISSUE THREAD

**Issue by m1heng** [pnpm/pnpm#3931]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

In our big monorepo (100+ pkgs), we developed couple of global (repo wide) script in our monorepo.  But It is awkward that have to tell all developers to cd back to `root/of/monorepo` and then run global scripts, and at the same time developer usually run package wide scripts inside `path/to/package`.
p.s. We maintained all our own scripts in root package.json.

**Describe the solution you'd like**

pnpm can provide a command to run monorepo wide scripts. 

1. `pnpm run -g xxxx`, which will act like cd `root/of/monorepo` then run `pnpm run xxxx`.
2. `pnpg xxxx`, which will more similar to `pnpx`

**Describe the drawbacks of your solution**

I am not really sure if this is intuitive enough to be part of pnpm functionality, or this should be done by other higher level tool like rush.

**Comment by zkochan** [comment]
This is already implemented. Run: 

```
pnpm run -w xxxx
```

**Comment by m1heng** [comment]
> This is already implemented. Run:
> 
> ```
> pnpm run -w xxxx
> pnpm -w xxxx
> ```

😯 but I can't find any documentation of this.
Neither in https://pnpm.io/cli/run or https://pnpm.io/workspaces

Btw, since we have this already, is this possible to make this command shorter like `pnpw` ?

**Comment by jayfongs** [comment]
> This is already implemented. Run:
> 
> ```
> pnpm run -w xxxx
> pnpm -w xxxx
> ```

I also encountered the same problem. Can it be like yarn

```
yarn workspace @app/a dev
yarn workspace @app/b dev
yarn workspace @app/c dev
```

**Comment by zkochan** [comment]
> Btw, since we have this already, is this possible to make this command shorter like pnpw ?

You can create an alias yourself, if you want a shorter command.

In your .zshrc/.bashrc/fish:

```
alias pnpw="pnpm -w"
```

**Comment by zkochan** [comment]
> I also encountered the same problem. Can it be like yarn

pnpm uses the `--filter` option:

```
pnpm --filter @app/a dev
```

https://pnpm.io/filtering

**Comment by m1heng** [comment]
I get it, and I just found the doc about `-w` https://pnpm.io/pnpm-cli#-w---workspace-root
