### ISSUE TITLE
Packages without `version` in manifest ignored when sorting dependency graph

### ISSUE THREAD

**Issue by rossng** [pnpm/pnpm#3933]
### Code to reproduce the issue:

Not included, but I can probably put something together if desired. I found the easiest way to see this was to debug `node ../<path-to-pnpm-repo>/pnpm/packages/pnpm/spnpm.js <script> -r` from a pnpm monorepo I had locally.

Breakpoint location: https://github.com/pnpm/pnpm/blob/c54778864671aef171edd812d4c641630077adb1/packages/pkgs-graph/src/index.ts#L85

### Expected behavior:

If a workspace dependency is referenced with `workspace:*`, it should be added to the list of dependencies in the package graph - even if the target dependency is missing the `version` field in its manifest.

### Actual behavior:

pnpm [filters out](https://github.com/pnpm/pnpm/blob/c54778864671aef171edd812d4c641630077adb1/packages/pkgs-graph/src/index.ts#L85) all dependencies without a `version` field. This can cause recursive run to execute in non-topological order.

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by guillaumewuip** [comment]
I've noticed too that with `pnpm@6.19.1` that in a monorepo where every local package dependency is configure via `workspace:latest`, recursive topological order is not respected so the commands using `recursive` or `--recursive` now fail.
