### ISSUE TITLE
Does `pnpm` support installing packages via private repositories using `git+ssh` URLs?

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#3934]
### Discussed in https://github.com/pnpm/pnpm/discussions/3930

<div type='discussions-op-text'>

<sup>Originally posted by **thasmo** October 28, 2021</sup>
We have trouble installing some private packages via `git+ssh` URL. Our `package.json` looks something like this:

```json
{
    "dependencies": {
        "@company/common-styles": "git+ssh://git@gitlab.com/company/libraries/common-styles.git#2.0.1"
    },
    "devDependencies": {
        "@company/babel-preset": "git+ssh://git@gitlab.com/company/tools/babel-preset.git#1.0.0",
        "@company/eslint-config": "git+ssh://git@gitlab.com/company/tools/eslint-config.git#1.0.0",
        "@company/postcss-purge": "git+ssh://git@gitlab.com/company/tools/postcss-purge-plugin.git#1.0.1",
        "@company/prettier-config": "git+ssh://git@gitlab.com/company/tools/prettier-config.git#1.0.0",
        "@company/stylelint-config": "git+ssh://git@gitlab.com/company/tools/stylelint-config.git#1.0.0",
        "@company/typescript-config": "git+ssh://git@gitlab.com/company/tools/typescript-config.git#1.0.0"
    }
}
```

Running `npm install` works as expected and installs these packages without problems.

Running `pnpm install` fails and outputs the following:

```sh
 WARN  HEAD https://gitlab.com/company/tools/postcss-purge-plugin error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/tools/typescript-config error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/tools/eslint-config error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/tools/prettier-config error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/tools/stylelint-config error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/tools/babel-preset error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/libraries/common-styles error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  HEAD https://gitlab.com/company/tools/eslint-config error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  HEAD https://gitlab.com/company/tools/postcss-purge-plugin error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  HEAD https://gitlab.com/company/tools/typescript-config error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  HEAD https://gitlab.com/company/tools/prettier-config error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  HEAD https://gitlab.com/company/tools/stylelint-config error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  HEAD https://gitlab.com/company/tools/babel-preset error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  HEAD https://gitlab.com/company/libraries/common-styles error (undefined). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for 'gitlab.com/company/libraries/common-styles/8521a26311dab1ec459e54ef1d6f4fd4ad449958' in pnpm-lock.yaml
This issue is probably caused by a badly resolved merge conflict.
To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
Progress: resolved 1601, reused 286, downloaded 12, added 0
Downloading registry.npmjs.org/gifwrap/0.9.2: 2.12 MB/5.89 MB
Downloading registry.npmjs.org/image-q/1.1.1: 1.85 MB/9.32 MB
```

Running `pnpm install --no-frozen-lockfile`, as suggested, results in basically the same output.

Does `pnpm` support installing private packages via `git+ssh` URL and if, what may be the problem here?

Thanks a lot for your support! :)

`pnpm@6.19.1`</div>

**Comment by burner03** [comment]
Likewise i'm unable to use a bitbucket url to a private repo.

in package.json: 
"@orgname/packagename": "git+ssh://git@bitbucket.org/orgname/packagename.git#v1.2.1"

just hangs indefinitely

` WARN  HEAD https://bitbucket.org/orgname/packagename error (undefined). Will retry in 10 seconds. 2 retries left.
Progress: resolved 23, reused 21, downloaded 2, added 0`

I noticed it is targeting `https://` now in this error. FWIW I am on Windows and have SSH setup to this repo.

**Comment by cope** [comment]
Same here with gitlab 😞

**Comment by nachoaldamav** [comment]
This issue seems to be fixed in the latest versions. I tried it with this `package.json`, the repo/project is hosted in Gitlab and is private.

```json
{
  "name": "ssh-pnpm",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@ignacioaldama/sample-project": "git+ssh://git@gitlab.com/sr.drabx/sample-project"
  }
}
```

**Comment by qiutian00** [comment]
> This issue seems to be fixed in the latest versions. I tried it with this `package.json`, the repo/project is hosted in Gitlab and is private.
> 
> ```json
> {
>   "name": "ssh-pnpm",
>   "version": "1.0.0",
>   "main": "index.js",
>   "dependencies": {
>     "@ignacioaldama/sample-project": "git+ssh://git@gitlab.com/sr.drabx/sample-project"
>   }
> }
> ```

How to install pnpm workspace below sub package?

**Comment by nachoaldamav** [comment]
> > This issue seems to be fixed in the latest versions. I tried it with this `package.json`, the repo/project is hosted in Gitlab and is private.
> > 
> > ```json
> > {
> >   "name": "ssh-pnpm",
> >   "version": "1.0.0",
> >   "main": "index.js",
> >   "dependencies": {
> >     "@ignacioaldama/sample-project": "git+ssh://git@gitlab.com/sr.drabx/sample-project"
> >   }
> > }
> > ```
> 
> How to install pnpm workspace below sub package?

Probably with #7487
