### ISSUE TITLE
Install fail in MacOS Monterey

### ISSUE THREAD

**Issue by lslvxy** [pnpm/pnpm#3937]
### Additional information:

 - `node -v` prints: v12.22.7
 - Windows, macOS, or Linux?: macOS

**Comment by lslvxy** [comment]
Downloaded file is. `https://registry.npmjs.org/@pnpm/macos-x64/-/macos-x64-6.19.1.tgz`
Intel Mac

**Comment by lslvxy** [comment]
6.17.1. install success

**Comment by zkochan** [comment]
Looks like it was broken by an error in https://github.com/pnpm/pnpm/pull/3896
