### ISSUE TITLE
performance regression for monorepo "pnpm install" in 6.20.0

### ISSUE THREAD

**Issue by youngderekm** [pnpm/pnpm#3949]
We have ~26 directories in listed in the workspace.  Previously, running "pnpm install" would take ~1 second if there was nothing to do.  But in 6.20.0 and higher, it's now taking 1 minute 23 seconds.  I tried different version numbers and narrowed it down to 6.20.0 where this started.  It happens in 6.20.1 and 6.20.2 as well.

I'm not sure how to gather more debugging information.  I tried debug logging but get very little info (.npmrc loglevel=debug).  This is a run that does no work:

```
$ time pnpm install
Scope: all 26 workspace projects
No entry for "/fsevents/1.2.13" in pnpm-lock.yaml
No entry for "/fsevents/2.3.2" in pnpm-lock.yaml

real    1m23.369s
user    0m0.030s
sys     0m0.091s
```

If there is more information I can provide, please let me know.

### Expected behavior:
pnpm install with no work to do should take seconds.

### Actual behavior:
pnpm install with no work to do takes 1:23

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Windows

**Comment by m1heng** [comment]
can you try `pnpm install --reporter=ndjson > .pnpm.debug.log`

**Comment by zkochan** [comment]
Probably something did not go well with https://github.com/pnpm/pnpm/pull/3915

I did fix [one issue](https://github.com/pnpm/pnpm/commit/bc1c2aa624b35e0400af0344c09a4ce91355650f) in 6.20.3 but probably it doesn't fix this issue

**Comment by elitastic** [comment]
I've the same problem, unfortunately 6.20.3 doesn't fix this issue.

**Comment by zkochan** [comment]
Are you sure it is broken since exactly 6.20.0? Or was it broken in an earlier version? I don't see anything that could cause it in 6.20 changes

**Comment by elitastic** [comment]
<= v6.19.1 is working fine
>= v6.20.0 is broken

**Comment by zkochan** [comment]
ok, is there a public repository that reproduces the issue? or could you create a sample repo?

do you have maybe packages that depend on local package? like use the `link:`, `file:` protocol

**Comment by elitastic** [comment]
It seems like it depends on the number of files in the repo. I reduced my package.json to the following and it takes about 15 seconds to complete `pnpm i` (when having 14'000 files in the repo):

`{
    "name": "app",
    "version": "1.0.0",
    "description": "",
    "repository": {
        "type": "git",
        "url": "http://repo.git"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {},
    "devDependencies": {}
}`

**Comment by youngderekm** [comment]
I also have a large number of files in the source tree.  We don't use link: or file:, but do use workspace: dependencies.

**Comment by m1heng** [comment]
I just made an example repo with huge file base https://github.com/m1heng/pnpm-pref-issue.

### with pnpm@6.19.1
Scope: all 2 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
pnpm i  0.21s user 0.02s system 17% cpu 1.291 total

### with pnpm@6.20.3
Scope: all 2 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
pnpm i  1.54s user 0.17s system 107% cpu 1.599 total

It's like 7x difference.

**Comment by zkochan** [comment]
might be an update in one of our dependencies as I couldn't figure out yet what could cause it from the changes in https://github.com/pnpm/pnpm/pull/3915

**Comment by zkochan** [comment]
looks like `pnpm i --ignore-scripts` is fast. I did some changes in that part of code.

![image](https://user-images.githubusercontent.com/1927579/140762276-a6a51936-c767-4e0c-a23b-1547cbcf531a.png)

**Comment by zkochan** [comment]
:ship: 6.20.4
