### ISSUE TITLE
[Security Feature Request] ability to `blacklist` typo package

### ISSUE THREAD

**Issue by loynoir** [pnpm/pnpm#3962]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

Reproduce something, and add typescript.

Got typo `pnpm install typescipt` which is not rejected.

**Describe the solution you'd like**

Ability to globally blacklist some packages using patterns.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

**Comment by loynoir** [comment]
https://www.npmjs.com/~jackwenhy

**Comment by zkochan** [comment]
You can kind of do it yourself, using a hook: https://pnpm.io/pnpmfile#hooksreadpackagepkg-context-pkg--promisepkg

`.pnpmfile.cjs`:
```js
module.exports = {
  hooks: {
    readPackage (pkg) {
      if (pkg.name === 'bad-pkg') throw new Error('this package is not allowed')
      return pkg
    }
  }
}
```

**Comment by loynoir** [comment]
Yeah, confirm working with
```sh
npm_config_pnpmfile=~/blacklist.pnpmfile.cjs pnpm i typescipt
```

Awesome pnpm! 😘
