### ISSUE TITLE
symlink=false broken when pnpm meet multi husky version 

### ISSUE THREAD

**Issue by gxmzjxk** [pnpm/pnpm#3965]
My repository has different husky version，when I start using pnpm,  it works fine，but when i change `symlink=false`, it fails.  After debugging for a while，I find that it was caused by husky@3.1.0 's install script，which time it cannot resolve `please-upgrade-node`.  Unify the husky version maybe the fastest solution，but my project it too big to finish in limited time. Any helps may be appreciated ! 

### pnpm version:

6.20.3

### Code to reproduce the issue:

reproduce Repo: https://github.com/gxmzjxk/pnpm-husky-demo

reproduce steps:
1. git clone git@github.com:gxmzjxk/pnpm-husky-demo.git
2. pnpm i

### Expected behavior:

pnpm i works with no error

### Actual behavior:

![image](https://user-images.githubusercontent.com/16485400/140768124-9b328067-e143-4789-8648-7e8c48f80383.png)

### Additional information:
- OS: macOS
- node: v12.20.0

**Comment by zkochan** [comment]
Your project will not work with `symlink=false`.
You can use `symlink=false` only if you use the PnP feature. So also set `node-linker=pnp`
