### ISSUE TITLE
Set npm_config_user_agent when running pnpx and pnpm create

### ISSUE THREAD

**Issue by cyco130** [pnpm/pnpm#3985]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

In `create-*` packages one often wants to install npm dependencies at the end of project initialization. But this requires determining the preferred package manager of the user. Most packages add a CLI option or prompt for this purpose. But the user has already expressed their choice buy running `npm init`, `yarn create`, or `pnpm create` (or `init`, or `pnpx create-*` etc.). We could determine the package manager choice if there was a way to determine the package manager that launched the `create-*` script. 

**Describe the solution you'd like**

`npm` and `yarn` set the `npm_config_user_agent` environment variable under these circumstances but `pnpm` doesn't. The problem would be solved if it did. The inconsistency with the other package managers even suggests that it may simply be a **bug** and not a missing feature.

**Describe the drawbacks of your solution**

None I can think of.

**Describe alternatives you've considered**

There are no alternatives I can think of but asking the user explicitly for their package manager preference.

**Comment by bestickley** [comment]
Thank you @cyco130 for raising this.
Here is a relevant SO post for others who are curious: https://stackoverflow.com/questions/68133683/is-there-a-cross-platform-way-to-get-the-name-of-the-parent-process-in-node-js

**Comment by cyco130** [comment]
@bestickley Heh, that's also me 😁

**Comment by bestickley** [comment]
😆  well, thank you again!

**Comment by zkochan** [comment]
Not sure why it is not set when `pnpm init` runs. We set it for sure in `pnpm run` and `pnpm install`. We should fix this.

**Comment by vhscom** [comment]
damn that waa quick work. nice job. 👌

**Comment by vhscom** [comment]
damn that was quick work. nice job. 👌
