### ISSUE TITLE
Multiline scripts in package.json 

### ISSUE THREAD

**Issue by ariesclark** [pnpm/pnpm#3988]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A clear and concise description of what workflow is meant to be improved.
Example: "As a developer, I often want to do <something>, but I often face <problem>".

- Right now there's no clean solution for having scripts within the ``package.json``.

**Describe the solution you'd like**
```json
{
    ...
    "scripts": {
        "preinstall": [
            "npx only-allow pnpm &&",
            "git submodule init &&",
            "git submodule update &&",
            "git submodule foreach \"pnpm install\""
        ]
    }
}
```

A clear and concise description of what you want to happen. Consider that pnpm is used
by many people, and your particular use case might not make sense to implement in the core.

**Describe the drawbacks of your solution**
1. Syntax highlights/linters in IDEs like VSCode highlight this syntax as incorrect because ``package.json`` expects it to be a string, not an array. This is a pretty simple fix but rather out of scope?
2. This would make the ``package.json`` incompatible with other package managers.

This section is important not only to identify future issues, but also for us to see whether
you thought through your request. When filling it, ask yourself what are the problems we could
have maintaining what you propose. How often will it break?

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough.

* The traditional alternative is separating the script into another file like ``start.sh`` or using utilities like ``run-all`` and having many different smaller scripts listed in the file.

**Comment by zkochan** [comment]
You may use a `package.yaml`. See an example here: https://github.com/pnpm/pnpm/blob/main/fixtures/package.yaml

**Comment by rubybb** [comment]
> You may use a `package.yaml`. See an example here: https://github.com/pnpm/pnpm/blob/main/fixtures/package.yaml

In this case using the package.yaml causes node not to recognize it as a dependency, perhaps we could have a command which regenerates the package.json the same way it does before publish? I don't publish the package to npm, I just build it and push to GitHub but this doesn't work due to the aforementioned error.
