### ISSUE TITLE
`pnpm import` fails with yarn v2

### ISSUE THREAD

**Issue by hmnd** [pnpm/pnpm#3993]
### pnpm version:
v6.22.1

### Code to reproduce the issue:
Run command `pnpm import` in a yarn v2 project.

[.pnpm-debug.log](https://gist.github.com/hmnd/2c4c8e7d72b887cd18ae6bb886f5a855)

### Expected behavior:
pnpm imports the yarn v2 lockfile successfully.

### Actual behavior:
import fails due to new v2 lockfile format.

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Linux (Ubuntu under WSL2)

Currently, [@yarnpkg/lockfile](https://github.com/pnpm/pnpm/blob/6a54be5a125dbea5c36324dc1509bc74ce9b3b60/packages/plugin-commands-installation/src/import.ts#L20) is being used to parse yarn lockfiles. `@yarnpkg/lockfile` has not been updated in 4 years, so it hasn't been updated to support the latest lockfile format.

A possible solution would be to switch to [snyk-nodejs-lockfile-parser](https://github.com/snyk/nodejs-lockfile-parser/). That package appears to be actively maintained and supports both old and new yarn lockfile formats.

**Comment by fireairforce** [comment]
I will import a yarn2lockParser into it by the snyk-nodejs-lockfile-parser.
