### ISSUE TITLE
`pnpm add` Inconsistent expected behavior

### ISSUE THREAD

**Issue by 0x219** [pnpm/pnpm#3999]
### Code to reproduce the issue: 
package.json:
```json
{
  "dependencies": {
    "react": "16.8.0",
  },
}
```
Suppose I want to update the version of react: 
```
pnpm add react
```

### Expected behavior:
package.json:
```json
{
  "dependencies": {
    "react": "17.0.2",
  },
}
```
### Actual behavior:
package.json:
```json
{
  "dependencies": {
    "react": "16.8.0",
  },
}
```
### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
You can do `pnpm add react@latest` or `pnpm update react --latest`

**Comment by 0x219** [comment]
> You can do `pnpm add react@latest` or `pnpm update react --latest`

Got it, thanks. But can it be consistent with the behavior of yarn and npm?

**Comment by zkochan** [comment]
I don't know. Yarn and npm would install the latest?

Do you run it in a workspace? In a workspace both Yarn and pnpm would install a version of the dependency that is already in the dependencies of any other workspace project.

**Comment by 0x219** [comment]
> I don't know. Yarn and npm would install the latest?
> 
> Do you run it in a workspace? In a workspace both Yarn and pnpm would install a version of the dependency that is already in the dependencies of any other workspace project.

Yarn and npm will install the latest. not a workspace.

**Comment by zkochan** [comment]
cc @pnpm/collaborators

**Comment by nikoladev** [comment]
I just tested this out.

- `npm install react` doesn't update the version
- `yarn add react` does update the version

I used `npm@8` and `yarn@1`

So there is no way for pnpm to "be consistent with the behavior of yarn and npm" because they both handle it differently.

I vote for leaving the current pnpm behavior the way it is unless there's a very good reason to change.

**Comment by 0x219** [comment]
> I just tested this out.
> 
> * `npm install react` doesn't update the version
> * `yarn add react` does update the version
> 
> I used `npm@8` and `yarn@1`
> 
> So there is no way for pnpm to "be consistent with the behavior of yarn and npm" because they both handle it differently.
> 
> I vote for leaving the current pnpm behavior the way it is unless there's a very good reason to change.

Ok, I also think it's better to make a distinction. It may be user inertia that makes me feel uncomfortable.
