### ISSUE TITLE
pnpm fails to install Node.js on 64 bit Raspbian

### ISSUE THREAD

**Issue by doinkythederp** [pnpm/pnpm#4007]
### Code to reproduce the issue:
```
pnpm env use -g latest
```

### Expected behavior:
pnpm downloads and installs the latest version of node

### Actual behavior:
pnpm outputs a error message (ERR_PNPM_FETCH_404) and fails:
```
 WARN  GET https://nodejs.org/download/release/v17.1.0/node-v17.1.0-linux-arm.tar.gz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://nodejs.org/download/release/v17.1.0/node-v17.1.0-linux-arm.tar.gz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://nodejs.org/download/release/v17.1.0/node-v17.1.0-linux-arm.tar.gz: Not Found - 404
```

### Additional information:

 - `node -v` prints: `v16.10.0`
 - Windows, macOS, or Linux?: Linux (64 bit Rasbian OS on a Raspberry Pi 4)

**Comment by zkochan** [comment]
Which tarball from here would be the one for your system? https://nodejs.org/dist/v17.1.0/

the node-v17.1.0-linux-arm64 one?

**Comment by doinkythederp** [comment]
> Which tarball from here would be the one for your system? https://nodejs.org/dist/v17.1.0/
> 
> the node-v17.1.0-linux-arm64 one?

It's actually `node-v17.1.0-linux-armv7l`.

When I download node-v17.1.0-linux-arm64, it exits with "./node-v17.1.0-linux-arm64/bin/node: No such file or directory" (even though it's actually there, I've checked with the `file` command). The other one works perfectly.

![image](https://user-images.githubusercontent.com/75394401/142325864-4c43904f-49a1-497b-9659-f125a1809e65.png)
![image](https://user-images.githubusercontent.com/75394401/142326355-1520865f-757d-43b6-a9d1-adfd0cd6c582.png)
