### ISSUE TITLE
yarn workspaces info in pnpm workspace

### ISSUE THREAD

**Issue by linbudu599** [pnpm/pnpm#4012]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A clear and concise description of what workflow is meant to be improved.
Example: "As a developer, I often want to do <something>, but I often face <problem>".

`yarn workspaces info` is a quite useful command in displaying workspace package dependency graph, which print log like this:

```json
{ "create-subscription": {
    "location": "packages/create-subscription",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  ...
  "react-noop-renderer": {
    "location": "packages/react-noop-renderer",
    "workspaceDependencies": [
      "react-reconciler"
    ],
    "mismatchedWorkspaceDependencies": []
  },
  "react-reconciler": {
    "location": "packages/react-reconciler",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  }, ... }
```

- By `workspaceDependencies` property, we can check package dep graph relation easily and go further in
developer experience in workspace.
- By `mismatchedWorkspaceDependencies` property, we can locate the specific workspace package which has other package declared by `workspace:` protocal but mismatch the required version.

Some extra features may be useful in pnpm workspace:

- Prop `recycleDependencies`: detect packages which are dep of each other.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Consider that pnpm is used
by many people, and your particular use case might not make sense to implement in the core.

**Describe the drawbacks of your solution**

This section is important not only to identify future issues, but also for us to see whether
you thought through your request. When filling it, ask yourself what are the problems we could
have maintaining what you propose. How often will it break?

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough.

**Comment by fireairforce** [comment]
Sounds good, `recycleDependencies` now pnpm can't check it, maybe you need to analyze the project graph by yourself.

**Comment by fireairforce** [comment]
This issue may be dumplicate with https://github.com/pnpm/pnpm/issues/3398, maybe we can discuss there~
