### ISSUE TITLE
pnpm doesn't fail at postinstall step

### ISSUE THREAD

**Issue by zardoy** [pnpm/pnpm#4018]
Hi! Some time ago I'm encountered a weird problem. I installed `quicktype-core` as dependency in some package, before publishing checked via `pnpm link` and package-preview that everything works on the consumer project. Everything worked even when I was using the just published version.

However, on the CI the consumer project was failing to build at `postinstall` script of just published package.

It happened because `quicktype-core` at postinstall step tried to require `lodash`. It was defined in consumer project dependencies, but not of the `quicktype-core`.

I tried to create min-repro repo: https://github.com/zardoy/pnpm-1. If something is unclear from above, you can look into `published` dir.
I will talk about `consumer` directory:

### Code to reproduce the issue:

1. `cd consumer`
2. `pnpm i` it fails
3. `pnpm i lodash` success

The project will work as quicktype-core will use just installed lodash. Also `pnpm i -f` will work. However:

4. Delete node_modules.
5. `pnpm i` now fails again

I can also from step 4 (when lodash is in package.json) run firstly `pnpm i --ignore-scripts` and then `pnpm i -f` to rerun lifecycle scripts.

I don't really understand why the behavior is inconsistent. I mean, how `quicktype-core` got access to lodash at step 3 or after `pnpm i --ignore-scripts`?

### Expected behavior:

always fail?

### pnpm version: 6.22.2

P.S. As a workaround of course I could add this to my consumer project, but it won't solve the problem for other users of package.

```json
"pnpm": {
    "packageExtensions": {
      "quicktype-core": {
        "dependencies": {
          "lodash": "*"
        }
      }
    }
}
```

It seems that I need to publish another version of package to just add `lodash` into `dependencies`

### Additional information:

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: win

**Comment by zardoy** [comment]
Now I can see that adding `lodash` to the package (published dir in my repro) would resolve the error. But it already was in my real package and it [didn't help](https://github.com/zardoy/github-manager/runs/4266339621?check_suite_focus=true#step:4:43). Weird.

**Comment by zkochan** [comment]
Looks like when the lockfile is up-to-date (and installation runs by `@pnpm/headless`) the root dependencies are linked after the postinstall scripts run. That is why it fails on `rm -rf node_modules && pnpm install`. But it would pass on `rm -rf node_modules pnpm-lock.yaml && pnpm install`

We should fix it.

**Comment by zardoy** [comment]
> the root dependencies are linked after the postinstall scripts run.

I was also thinking about it. Thank you so much for looking into it!
