### ISSUE TITLE
The pnpm installation script fails to write to a `.zshrc` because it does not exist

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#4027]
<img width="568" alt="Screen Shot 2021-11-21 at 3 45 12 PM" src="https://user-images.githubusercontent.com/18686388/142783816-076dfca2-302e-4c50-9cdf-16e407781949.png">

thanks for the quick reply, this is what I'm getting after restarting the terminal

_Originally posted by @jonrrivera in https://github.com/pnpm/pnpm/issues/3319#issuecomment-974921964_

**Comment by zkochan** [comment]
I wonder if it would work if pnpm had created this file.

**Comment by jonrrivera** [comment]
any way I could help with this?
I'm using macOS Monterey v12.0.1

**Comment by zkochan** [comment]
try to create `~/.zshrc` with this content:

```
export PNPM_HOME="~/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
```

restart the terminal and see if pnpm will available.

**Comment by jonrrivera** [comment]
so I added the `~/.zshrc` with the content mentioned. Now installing with 
`curl -fsSL https://get.pnpm.io/install.sh | sh -` 

gives me this success message:

<img width="568" alt="Screen Shot 2021-11-21 at 4 45 34 PM" src="https://user-images.githubusercontent.com/18686388/142785998-f991489f-5eca-4c89-9f31-97ba82604ac4.png">

but still failing to use pnpm after restarting the terminal:


<img width="560" alt="Screen Shot 2021-11-21 at 4 46 31 PM" src="https://user-images.githubusercontent.com/18686388/142786030-052ea8e1-87fc-4869-b926-7a434a19d9b8.png">

**Comment by zkochan** [comment]
Does running the CLI directly work? Like `~/Library/pnpm/pnpm --version`?

**Comment by jonrrivera** [comment]
<img width="561" alt="Screen Shot 2021-11-21 at 4 49 49 PM" src="https://user-images.githubusercontent.com/18686388/142786181-bf255bcf-c839-40a3-b493-516c1418040c.png">

**Comment by zkochan** [comment]
ok, maybe in `.zshrc` you need to put the whole path. So change it to

```
export PNPM_HOME="/Users/jonrivera/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
```

**Comment by jonrrivera** [comment]
you did it 😎🤝😎 thank you !

**Comment by zkochan** [comment]
ok, in that case we can fix the `pnpm setup` command so that it creates a file if it does not already exist.

**Comment by raulvictorrosa** [comment]
First run:
`pnpm setup --force`

Then after:
`curl -fsSL https://get.pnpm.io/install.sh | sh -`

**Comment by bryaneaton13** [comment]
I just ran into this and realized it was because I was trying to run an npm script named "setup" 🤦 

### If you're trying to run an npm script called "setup", you need to do `pnpm run setup`

**Comment by changjiaqio** [comment]
希望尽快修复pnpm setup
