### ISSUE TITLE
Support custom mirrors for Node.js downloads

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#4039]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

When `use-node-version` is set in `.npmrc`, PNPM uses a hardcoded download URL pointing to `nodejs.org`.

https://github.com/pnpm/pnpm/blob/d4d7c4aee21f12080793adaa9f96da22569c930c/packages/plugin-commands-env/src/node.ts#L125

There's a few reasons we'd prefer to use an internal mirror:

- We're looking to control outgoing network traffic in our CI build process for security reasons. Although `nodejs.org` is pretty safe, we'd prefer to keep the allowlist as small as possible.
- We'd also like to be good web citizens and avoid lots of repeated downloads to `nodejs.org`.
- If `nodejs.org` ever goes down, our CI builds would fail.
- It'd be slightly faster for our CI builds to hit an internal cached mirror.

**Describe the solution you'd like**

Would it be reasonable for PNPM to support an additional config that allows this URL to be configured? (i.e. A download mirror.)

```ini
# .npmrc
pnpm-node-mirror = https://internal.test/download/<releaseDir>/<nodeVersion>/<pkgName>.<extension>
```

We set `electron_mirror` in our `.npmrc` file for similar reasons: https://www.electronjs.org/docs/latest/tutorial/installation#custom-mirrors-and-caches

**Describe the drawbacks of your solution**

Invalid download mirrors may cause confusion. PNPM does show the full URL it's trying to download Node at if there's a failure, so that mitigates this somewhat.

```
❯ pnpm node
 WARN  GET https://nodejs.org/download/release/v12.18.4/node-v12.18.4-darwin-x64.tar.gz error (SELF_SIGNED_CERT_IN_CHAIN). Will retry in 10 seconds. 2 retries left.
```

**Describe alternatives you've considered**

We can also cache the download dir (`~/Library/pnpm/node` for macOS) between CI builds, but this solution wouldn't work for developers running `pnpm install` locally.

---

Thanks a lot for creating PNPM! It's so lovely.

**Comment by zkochan** [comment]
sounds good. Maybe just call the setting `node-mirror` and use it as the base url

```
node-mirror = https://internal.test/download/
```

**Comment by gluxon** [comment]
Nice. That sounds good. I'll give implementation a shot and open a PR.
