### ISSUE TITLE
Install Stalls with Certain Packages

### ISSUE THREAD

**Issue by ProfessorManhattan** [pnpm/pnpm#4048]
Running `pnpm install @mblabs/prettier-config` just hangs. There must be something wrong with the package but it works with regular `npm`. This is the output I get:

```
Workstation:~$ pnpm install @mblabs/prettier-config
Progress: resolved 476, reused 476, downloaded 0, added 0 # Stalls here
```
Is there a way of seeing what task is taking a long time?

**Comment by ProfessorManhattan** [comment]
I closed this but it should be reopened -- for some reason installing the first time around takes forever -- is there anything I can do? I'd really like to use pnpm

**Comment by zkochan** [comment]
I can't reproduce it. What is your OS? Do you have an antivirus running?

**Comment by ProfessorManhattan** [comment]
Thanks so much @zkochan - I'm not entirely sure what's running on my computer but I do notice that when I close a tab in VS Code that is unsaved, VS Code hangs for about 15s. There must be something wrong with my set up.
