### ISSUE TITLE
Path in registry URL no longer respected if it does not end with a trailing slash

### ISSUE THREAD

**Issue by aholtkamp** [pnpm/pnpm#4052]
### Code to reproduce the issue:

pnpm config set registry https://some.company.com/some-registry
pnpm install

### Expected behavior:

The path "some-registry" is respected.

### Actual behavior:

The path "some-registry" is ignored

### Additional information:

Caused by https://github.com/pnpm/pnpm/pull/4032

This is an undocumented breaking change in a minor version update leading to not being able to upgrade pnpm in our company without adjusting our CI.

**Comment by zkochan** [comment]
I did not consider it to be a breaking because I was trying to make pnpm process the registry configuration the same way as the npm CLI does it. So I guess your current configuration doesn't work with npm as well? Could you check if it works with npm CLI?

**Comment by zkochan** [comment]
I have downgraded latest to 6.23.1 for now.

**Comment by zkochan** [comment]
@aholtkamp what exactly is the problem? What error do you get? Are the requests going to the wrong URL or is this an auth error? How do you set the auth token?

**Comment by aholtkamp** [comment]
Thanks for the quick response!
We recently switched from a (very buggy) npm 7 to pnpm and always provided the registry without a trailing slash. I double checked this using npm 7.x and it still works.

Regarding the question what the actual error is: When setting e.g. https://some.company.com/some-registry I get the error that my packages cannot be found below https://some.company.com/some-package/**. Before 6.23.x the packages very correctly looked up below https://some.company.com/some-registry/some-package/**

**Comment by zkochan** [comment]
ok, I think this PR should fix it: #4053

**Comment by zkochan** [comment]
Do the entries in your lockfile look like this

https://github.com/pnpm/pnpm/blob/8a99a01ff691fc2cc3b6a497c11c4bbcf2155cdb/pnpm-lock.yaml#L9313-L9316

Or does the "resolution" field contain more entries?

**Comment by aholtkamp** [comment]
Our pnpm-lock.-yaml is quite big but flying over the entries it looks like the "resolution" field does only contain "integrity" like in your example.

**Comment by zkochan** [comment]
In that case probably my pull request won't help. I have found an issue but only when the lockfile's resolution fields contain the "tarball" field.

**Comment by zkochan** [comment]
Try 6.23.4. It is not latest, so you'll need to explicitly install it.

**Comment by aholtkamp** [comment]
I have upgraded to 6.23.4 but it didn't fix the issue.

**Comment by zkochan** [comment]
it should work with 6.23.5

**Comment by zkochan** [comment]
@aholtkamp could you verify the fix in the latest version of pnpm?

**Comment by aholtkamp** [comment]
I can confirm that 6.23.5 works, thanks!

**Comment by zkochan** [comment]
I think I know what caused the regression in my change. Try pnpm v6.23.7-202112041634
