### ISSUE TITLE
pnpm prune --prod

### ISSUE THREAD

**Issue by stychu** [pnpm/pnpm#4058]
If I have a multistage build with docker and want to reuse installed node_modules in later stages without copying the .npmrc file throughout all the stages pnpm is trying to fetch dependencies on pnpm prune --prod which to me seems like a bug?
Shouldn't it just remove devDependencies and do not attempt to refetch dependencies??

I have custom auth key and private package scopes in .npmrc thats why it's not being passed way down in the multistage build.

**Comment by zkochan** [comment]
You can try `pnpm prune --prod --offline`.
