### ISSUE TITLE
6.23.5 is not set as latest, but yesterday it was

### ISSUE THREAD

**Issue by PabloSzx** [pnpm/pnpm#4065]
![image](https://user-images.githubusercontent.com/8672915/144688266-d05f6ca0-cae7-4187-8061-944ed2382218.png)

**Comment by zkochan** [comment]
I changed it to 6.23.1 due to this issue: https://github.com/pnpm/pnpm/issues/4064

**Comment by PabloSzx** [comment]
this thing of removing and/or changing the latest tag always breaks CI when using pnpm engines

**Comment by PabloSzx** [comment]
> I changed it to 6.23.1 due to this issue: #4064

understood :+1: but then the deprecated message is outdated

**Comment by zkochan** [comment]
> this thing of removing and/or changing the latest tag always breaks CI when using pnpm engines

good point. I don't know how to prevent it in the future. There are many options. Not sure which would be the best

**Comment by PabloSzx** [comment]
> good point. I don't know how to prevent it in the future. There are many options. Not sure which would be the best

I think making sure that the @ latest doesn't have big regressions should have a bigger priority anyways, at least when the regressions are found within a couple of days/hours.
