### ISSUE TITLE
Create a node modules directory without using symlinks

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#4073]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I want to be able to install a node_modules that doesn't use symlinks

**Describe the solution you'd like**

I want to use Yarn's library for hoisting: https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-nm/sources/hoist.ts

Related PRs:
- https://github.com/pnpm/pnpm/pull/4162
- https://github.com/pnpm/pnpm/pull/4184
- https://github.com/pnpm/pnpm/pull/4185
- https://github.com/pnpm/pnpm/pull/4186

TODO: 
- [x] verify that when a package has both bundled and regular dependencies, the bundled deps are not removed
- [x] installation should work, when a non-empty node_modules already exists

**Comment by semoal** [comment]
This feature will be amazing! I've been exploring a lot of package-manager solutions an PNPM in overall is the best, but building a monorepo with Expo/React Native it's just impossible. Since Metro bundler under the hood uses `jest-haste-map` that doesn't follow symlinks. 
The single package manager that works fine, is Yarn v1, even with hoist enabled.

I would be able to help with this and archive a stable environment with React Native. I think this is a step-blocker for most of us using a monorepo with Expo and some Node, Web resources.

**Comment by zkochan** [comment]
As far as I know there are workarounds for the React Native issues: https://twitter.com/ZoltanKochan/status/1471425994342940673

**Comment by semoal** [comment]
Oh cool, will give it a try Zoltan, and report it back for future users! Anyways I could help with this If you consider =)

**Comment by zkochan** [comment]
If that workaround works, we need to document it on our website.

> Anyways I could help with this If you consider

You want to work on node_modules without symlinks? That would be great. Nobody started to work on it yet.

**Comment by zkochan** [comment]
I work on it now.

**Comment by freakzlike** [comment]
That would be great to come around some issues with WSL and symlinks (https://github.com/microsoft/WSL/issues/5118)

**Comment by zkochan** [comment]
I am not sure how to name this setting.

Yarn has the `node-linker` setting with `pnpm`, `node-modules`, and `pnp` as possible options. We also have this setting but only `pnp` is currently an allowed value (or not set). `pnpm` would be a weird value because it is pnpm in all cases. And node-modules is also weird because the symlinked node-modules is a node-modules as well.

**Comment by zkochan** [comment]
:ship: [6.25.0-1](https://github.com/pnpm/pnpm/releases/tag/v6.25.0-1)

**Comment by freakzlike** [comment]
@zkochan thank you for your work!
I have tested the setting (node-linker=hoisted) within a docker container and receive a warning because of symlink.

```
cross-device link not permitted, link '/home/node/.pnpm-store/v3/files/6a/8011db36b113d52d7173b8904f456cf06021911593bbb767e9c43e60e8eabc1c62d874ecac6b5597a3544772d9798abe491c6fc3bf5ccf542b76cf73588c3f' -> '/var/lib/app/node_modules/_tmp_8_56b51f87cba29360b8c1dc9aa923be54/tslib.es6.html'
Falling back to copying packages from store
Packages are copied from the content-addressable store to the virtual store.
```

Also when I rerun `pnpm install` the number of packages are doubled

Here is a small repo for reproduction: https://github.com/freakzlike/pnpm-node-linker-test/

**Comment by zkochan** [comment]
That warning looks like a warning about hard links, not symlinks. A hard link cannot be created to a file on a different disk.

**Comment by zkochan** [comment]
> Also when I rerun pnpm install the number of packages are doubled

Are they really doubled? Maybe it is an issue with the progress reporter. The reporting might not work well yet.

**Comment by freakzlike** [comment]
I have a project with 1434 packages. When I run `pnpm install` for the first time it shows 1434. If I run again it starts counting from 0 to 2868 (Same in my example repo with 1 and 2). But I cannot tell if it is only the progress reporter. The `node_modules` seems fine.

**Comment by zkochan** [comment]
It is probably just the reporting. I'll check later.

**Comment by zkochan** [comment]
:ship: 6.25.0

**Comment by cefeboru** [comment]
> @zkochan thank you for your work! I have tested the setting (node-linker=hoisted) within a docker container and receive a warning because of symlink.
> 
> ```
> cross-device link not permitted, link '/home/node/.pnpm-store/v3/files/6a/8011db36b113d52d7173b8904f456cf06021911593bbb767e9c43e60e8eabc1c62d874ecac6b5597a3544772d9798abe491c6fc3bf5ccf542b76cf73588c3f' -> '/var/lib/app/node_modules/_tmp_8_56b51f87cba29360b8c1dc9aa923be54/tslib.es6.html'
> Falling back to copying packages from store
> Packages are copied from the content-addressable store to the virtual store.
> ```
> 
> Also when I rerun `pnpm install` the number of packages are doubled
> 
> Here is a small repo for reproduction: https://github.com/freakzlike/pnpm-node-linker-test/

@freakzlike I'm having the same warnings when building in CI, did you figure out how to fix those warnings?
