### ISSUE TITLE
react-scripts does not get the exact webpack version

### ISSUE THREAD

**Issue by bencergazda** [pnpm/pnpm#4076]
### Code to reproduce the issue:

Step 1
`$ npx create-react-app storybook-test`

Step 2
`$ cd storybook-test && npx sb init`

Step 3
`$ rm node_modules -rf && rm yarn.lock`

Step 4
`$ pnpm install`

Step 5
`$ npm run start`

Note
 `react-scripts@4.0.1` needs exactly `webpack@4.44.2`, but `@storybook/react` is less strict, it allows the latest v4 version (v4.46.0 currently).

### Expected behavior:

`react-scripts` should get exactly the required webpack version (4.44.2) even if other dependencies can use other (newer) versions of the same package. `@storybook/react` should get the latest v4 webpack version.

### Actual behavior:

`react-scripts` throws error on preflight check for the invalid webpack version.

```
The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.44.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  C:\localhost\storybook\node_modules\.pnpm\node_modules\webpack (version: 4.46.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.
```

### Additional information:

Creating a pnpm.overrides rule in package.json fixes the issue, but I am not sure if this should be fixed like this.

```
  "pnpm": {
    "overrides": {
      "webpack": "4.44.2"
    }
  },
```

React scripts also throws an error in the preflight check with the original **yarn** installation (yarn@1.22.17). In case of yarn, it complains about the incorrect `babel-loader` version.

 - `node -v` prints: v16.1.0
 - Windows, macOS, or Linux?: Windows 11

**Comment by zkochan** [comment]
Does your project also have webpack in its direct dependencies? if yes, changing it to exact version should help as well. Otherwise, using overrides is the right way to fix it.

**Comment by bencergazda** [comment]
@zkochan Adding webpack@4.44.2 as a direct dependency also fixes the issue. Thanks for the feedback!

**Comment by shezhangzhang** [comment]
Why npm does not have this problem ? What's the point ?
