### ISSUE TITLE
no write access to add or rm global packages

### ISSUE THREAD

**Issue by LaamGinghong** [pnpm/pnpm#4101]
### Code to reproduce the issue:

- `pnpm rm -g pnpm`
- `pnpm add yarn -g`
- `pnpm update pnpm -g`

### Expected behavior:

I can add or remove global packages. 

### Actual behavior:

![image](https://user-images.githubusercontent.com/33472924/145369688-8beb0b59-6b35-4c69-aab4-b6377aff921a.png)

### Additional information:

 - `node -v` prints: v14.18.1
 - Windows, macOS, or Linux?: 
![image](https://user-images.githubusercontent.com/33472924/145369805-dd0f0a67-e9ee-4caa-b74f-b80f3facf893.png)

**Comment by LaamGinghong** [comment]
I had the same problem in the past. At that time, I simply deleted Node to reinstall pnpm.

**Comment by LaamGinghong** [comment]
I use npm to install pnpm

**Comment by LaamGinghong** [comment]
![image](https://user-images.githubusercontent.com/33472924/145373867-d32c1077-c113-4e09-9aff-140f6ecd81a2.png)
Emm...
It looks like PNPM is not going to help me create this directory

**Comment by LaamGinghong** [comment]
@zkochan #4027 It does not work for me.
I have written PNPM_HOME in `.zshrc` but still get issue.
![image](https://user-images.githubusercontent.com/33472924/145376371-f6c76b3d-159b-4d52-910e-c44fcfb5c02d.png)

**Comment by fireairforce** [comment]
How about use `chmod` to get the premission for the directory?

**Comment by zkochan** [comment]
What other directory should we use for the pnpm home directory in order to have permission to it by default?

**Comment by fireairforce** [comment]
@zkochan how about `~/.local/share/xxx`

**Comment by zkochan** [comment]
We use that location on Linux. Is it OK to use it on macOS as well?

**Comment by fireairforce** [comment]
macos is also ok, i used it before

**Comment by zkochan** [comment]
I don't have objection but we should do it in a backward-compatible way.

**Comment by LaamGinghong** [comment]
> I don't have objection but we should do it in a backward-compatible way.

@zkochan Is there any progress on this issue?

**Comment by zkochan** [comment]
No, I think I will reimplement global install in pnpm v7.
