### ISSUE TITLE
option: node-path

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#4103]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

We're using a variation of the `gradle-node-plugin` in a large monorepo at my organization. Much like pnpm's `use-node-version` option, [`gradle-node-plugin` can also be configured to download a copy of Node.js](https://github.com/node-gradle/gradle-node-plugin/blob/c17eb3d839ee3a1cf520c3e2058cd4f10b318640/docs/usage.md#configuring-the-plugin).

From `gradle-node-plugin` docs:

```gradle
// build.gradle

plugins {
  id "com.github.node-gradle.node" version "3.0.1"
}

node {
    // Whether to download and install a specific Node.js version or not
    // If false, it will use the globally installed Node.js
    // If true, it will download node using above parameters
    // Note that npm is bundled with Node.js
    download = true
    
    // Version of node to download and install (only used if download is true)
    // It will be unpacked in the workDir
    version = "12.18.3"
}
```

We're pretty happy with the `use-node-version` option in pnpm, but it does seem strange that both Gradle and pnpm have to download the same version of Node.js during the initial setup of this repo.

**Describe the solution you'd like**

Would it be possible to give pnpm a relative path to the node binary it should use? Much like the existing [`npm-path` option](https://pnpm.io/npmrc#npm-path). 

```ini
# .npmrc
node-path = ./local-nodejs/node
```

Although this may need to be `node-dir-path` since the binary will be named `node.exe` on Windows.

```ini
# .npmrc
node-dir-path = ./local-nodejs/node
```

Could also have this in `package.json`:

```jsonc
{
  "pnpm": {
    "node-path": "./local-nodejs/node"
  }
}
```

**Describe the drawbacks of your solution**

- There may be security concerns with allowing pnpm to be ran with an arbitrary node process.
- We'd want additional errors if both `node-path` and `use-node-version` are set. These seem mutually exclusive.

**Describe alternatives you've considered**

There isn't an urgent need for this feature request since `use-node-version` works well too. 🙂

**Comment by gluxon** [comment]
> I don't know how dangerous it is from security perspective.

Right, I'm similarly unsure if there's large security repercussions. I'm happy to wait and see how many others have similar use cases. Maybe no one else needs this and we can close the issue after some time. 🤷‍♂️

**Comment by gluxon** [comment]
Going to close this out since no one else has asked for this.

**Comment by ribeiropaulor** [comment]
For anyone that arrive here looking for a direction...

Nowadays we have nvm (https://github.com/nvm-sh/nvm). You can easily maintain multiple versions of node in your system. You can activate the version you need and maintain the other versions available for other purposes.

At first, I was looking for a way to configure pnpm. I, then, realized that nvm would do the trick.
