### ISSUE TITLE
Running `pnpm dlx` inside `preinstall` hook fails with `Command failed with ENOENT`

### ISSUE THREAD

**Issue by DrJume** [pnpm/pnpm#4119]
### Code to reproduce the issue:

Add a "preinstall" hook to your `package.json`'s `scripts`: 
```json
"preinstall": "if ! pnpm dlx only-allow pnpm; then rm -rf node_modules/ package-lock.json && exit 1; fi",
```

#### .pnpm-debug.log
https://gist.github.com/DrJume/714e10898d086d09cda4f5008d22b953

### Expected behavior:

Running `pnpm dlx only-allow pnpm` should not fail inside the preinstall hook.

### Actual behavior:

It fails to run `pnpm dlx only-allow pnpm`.

![image](https://user-images.githubusercontent.com/12785972/145876436-5dcf117d-0bdb-4c04-b596-fa9f24f1772b.png)

### Additional information:

 - `node -v` prints: `v16.13.0`
 - Windows, macOS, or Linux?: `Windows`

**Comment by zkochan** [comment]
I don't think that `pnpm dlx only-allow pnpm` makes sense. It will probably always pass because it gets executed by pnpm.
