### ISSUE TITLE
Command to update specific indirect dependencies

### ISSUE THREAD

**Issue by ai** [pnpm/pnpm#4122]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

Users need to update `caniuse-lite` every month to have only actual polyfills in their JS bundle.

`caniuse-lite` is mostly used as indirect dependency (users have only `autoprefixer` in `dependencies`).

Calling `pnpm up caniuse-lite` causes an error:

``` 
 ERR_PNPM_NO_PACKAGE_IN_DEPENDENCIES  None of the specified packages were found in the dependencies.
```

**Describe the solution you'd like**

It will be nice to have a command or extra option for `pnpm up` to update only `caniuse-lite`.

I think the best option will be to not throw `ERR_PNPM_NO_PACKAGE_IN_DEPENDENCIES ` if we have package in lock file.

**Describe the drawbacks of your solution**

I do not see any for now.

**Describe alternatives you've considered**

Right now Browserslist has [a dirty script](https://github.com/browserslist/browserslist/blob/main/update-db.js#L173-L222) to patch pnpm’s lockfile.

In Yarn 2+ we have `yarn up -R 'caniuse-lite'`, which allowed Browserslist to not have direct script for Yarn 2+.

**Comment by zkochan** [comment]
This should be easy. pnpm already updates subdependencies. We just need to remove that check for whether the update pkg is found in the direct dependencies.
