### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by liuliangsir** [pnpm/pnpm#4149]
### pnpm version:
6.22.2

### Code to reproduce the issue:
N/A, happened when upgrading pnpm

![image](https://user-images.githubusercontent.com/8049878/146708379-1db2188c-d5c2-4a8a-94a9-1a438704f565.png)

### Expected behavior:
No warning

### Actual behavior:
Warning

### Additional information:

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: Windows
![image](https://user-images.githubusercontent.com/8049878/146708330-e6880fc8-54c7-428e-8766-ca7f2bb8af53.png)

**Comment by zkochan** [comment]
For some reason, pnpm used a store from a different disk. In this case, the store had to be on disk C, not E
