### ISSUE TITLE
`frozen-lockfile` is used on CI even if I didn’t ask for it

### ISSUE THREAD

**Issue by ai** [pnpm/pnpm#4151]
### pnpm version

6.24.2

### Code to reproduce the issue

https://github.com/browserslist/caniuse-lite/runs/4598871429

1. Script on CI changed `devDependencies`
2. CI called `pnpm install --ignore-scripts`
3. There was no `--frozen-lockfile`, but we still get

```
lockfile is up-to-date, resolution step is skipped
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with package.json
```

### Expected behavior:

1. Have `--no-frozen-lockfile` if `frozen-lockfile` is default CI behavior by default
2. Or change lockfile if it was not expected behavior

### Actual behavior:

` ERR_PNPM_OUTDATED_LOCKFILE ` error without argument to disable it.

(We can’t use `pnpm up` instead of `pnpm install` because we need `--ignore-scripts` for security reasons)

### Additional information:

 - `node -v` prints: 16.13.1
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
The `--no-frozen-lockfile` CLI option is supported. You can use it in your CI, it should work:

```
pnpm install --no-frozen-lockfile
```

**Comment by ai** [comment]
Thanks. I fixed `caniuse-lite` scripts.

What do you think about adding `--no-frozen-lockfile` to `pnpm install --help`? We can add it by mentioning `--[no-]frozen-lockfile`. But I think it could be better to add another like just for `--no-frozen-lockfile` to mention CI defaults.

Something like:

```
      --frozen-lockfile                 Don't generate a lockfile and fail if an update is needed
      --no-forzen-lockfile            Disable frozen lockfile which is used on CI by default
```

I have a rule, that if 1 user report about the problem, 10 other users had it too, but didn’t tell about it.

**Comment by zkochan** [comment]
Sure, we can add this to help.

I agree with your rule.

**Comment by Luc45** [comment]
jfyi, I faced this error message in CI recently, I had to `pnpm install --no-frozen-lockfile` and commit the resulting lockfile - I'm not sure if there are better ways to go around it, but either way, having some docs is always helpful
