### ISSUE TITLE
Make "pnpm list" show transitive dependencies from workspace packages

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#4154]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

This feature request is similar to https://github.com/pnpm/pnpm/issues/3583, which notes that `pnpm list` doesn't traverse through `pnpm link`'ed packages. This GitHub issue notes that `pnpm list` also doesn't traverse through workspace protocol packages for similar reasons.

**Describe the user story**

Given package `a` depends on `b` and `b` depends on `c`, I'd like to be able to use `pnpm list --filter=a` to see the transitive dependencies of `a` brought in through `c`.

Suppose the following `pnpm-lock.yaml`:

```yaml
# pnpm-lock.yaml
lockfileVersion: 5.3

importers:

  .:
    specifiers: {}

  packages/a:
    specifiers:
      b: workspace:*
    dependencies:
      b: link:../b

  packages/b:
    specifiers:
      c: workspace:*
    dependencies:
      c: link:../c

  packages/c:
    specifiers: {}
```

At the moment `pnpm list --filter=a` stops at `b` regardless of the `depth` value.

```
❯ pnpm list --filter=a --depth=100
Legend: production dependency, optional only, dev only

a@1.0.0 /packages/a

dependencies:
b link:../b
```

**Describe the solution you'd like**

Update the `pnpm list` command to traverse through workspace packages.

```
❯ pnpm list --filter=a
Legend: production dependency, optional only, dev only

a@1.0.0 /packages/a

dependencies:
b link:../b
└── c link:../c
```

**Describe the drawbacks of your solution**

This could make the dependency subgraph pnpm has to traverse through much larger, and unexpectedly slow down the `pnpm list` command for users that were happy with the existing behavior. From looking at https://github.com/pnpm/pnpm/issues/3518, I think there may also be a memory issue we have to investigate before expanding the scope of `pnpm list`.

**Describe alternatives you've considered**

This could also be implemented as a pnpm plugin or external CLI.

**Comment by gluxon** [comment]
The reason `pnpm list` doesn't currently traverse through workspace packages is because the `dependenciesHierarchyForPackage` function stops here:

https://github.com/pnpm/pnpm/blob/eb9ebd0f3e01e5e4c8409d1f38c781e299705952/packages/dependencies-hierarchy/src/index.ts#L157-L160

The `packageAbsolutePath` variable is set by the `refToRelative` function, which returns `null` for `link:`.

https://github.com/pnpm/pnpm/blob/eb9ebd0f3e01e5e4c8409d1f38c781e299705952/packages/dependency-path/src/index.ts#L81-L83

I was able to get `pnpm list` to show dependencies from workspace packages with this very naive work-in-progress change, but there's multiple issues with it.

```diff
diff --git a/packages/dependencies-hierarchy/src/index.ts b/packages/dependencies-hierarchy/src/index.ts
index 844b3bbfa..f915655d9 100644
--- a/packages/dependencies-hierarchy/src/index.ts
+++ b/packages/dependencies-hierarchy/src/index.ts
@@ -141,7 +141,7 @@ async function dependenciesHierarchyForPackage (
   for (const dependenciesField of DEPENDENCIES_FIELDS.sort().filter(dependenciedField => opts.include[dependenciedField])) {
     const topDeps = currentLockfile.importers[importerId][dependenciesField] ?? {}
     result[dependenciesField] = []
-    Object.keys(topDeps).forEach((alias) => {
+    for (const alias of Object.keys(topDeps)) {
       const { packageInfo, packageAbsolutePath } = getPkgInfo({
         alias,
         currentPackages: currentLockfile.packages ?? {},
@@ -156,7 +156,10 @@ async function dependenciesHierarchyForPackage (
       const matchedSearched = opts.search?.(packageInfo)
       if (packageAbsolutePath === null) {
         if ((opts.search != null) && !matchedSearched) return
-        newEntry = packageInfo
+        newEntry = {
+          ...packageInfo,
+          dependencies: (await dependenciesHierarchyForPackage(packageInfo.path, currentLockfile, opts))?.dependencies
+        }
       } else {
         const relativeId = refToRelative(topDeps[alias], alias)
         if (relativeId) {
@@ -177,7 +180,7 @@ async function dependenciesHierarchyForPackage (
         }
         result[dependenciesField]!.push(newEntry)
       }
-    })
+    }
   }
 
   await Promise.all(
```

For the diff above, amongst many other issues:

- The same subgraph is traversed multiple times.
- Only `dependencies` are looked at, not `devDependnecies`, `peerDependencies`, etc.
- No tests written for this yet.

Curious if this feature is desirable before working on this further.

**Comment by gluxon** [comment]
I should also mention that this should be regarded with very low priority. 🙂 Maintainers should please enjoy their holidays and the new year.

There's no immediate need, but my team commonly looks through dependency subgraphs and having builtin tooling for that would be helpful next year.

**Comment by zkochan** [comment]
I guess it would be solved by https://github.com/pnpm/pnpm/issues/3398

**Comment by gluxon** [comment]
Took at stab at this in https://github.com/pnpm/pnpm/pull/4812, but going to try a larger refactor instead.

**Comment by zkochan** [comment]
This is done, right?

**Comment by gluxon** [comment]
Yes it is! Thanks for the reminder to close this.

Fixed by https://github.com/pnpm/pnpm/pull/5863.
