### ISSUE TITLE
Config option to disable update check notification

### ISSUE THREAD

**Issue by LeSuisse** [pnpm/pnpm#4158]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I'm in a team where all our development tools are pinned via [Nix](https://nixos.org/) so we have the same reproducible environment.
We update the environment on a regular basis but with the fast development of `pnpm` we are often a bit behind so we get the notification message. It is not really a big issue as we can just ignore it until the next time we upgrade our dev tools but it is still a small annoyance and can it can be confusing for newcomers because the suggested upgrade command will not work.

**Describe the solution you'd like**

Having an additional configuration flags `check-for-updates` defaulting to `true` would be great.

**Describe the drawbacks of your solution**

Users could set this option to just ignore the new versions and never update `pnpm` which is not a good thing. It is however probable that users doing that on purpose never update even today anyway.

**Describe alternatives you've considered**

When `update-notifier` was used it was possible to disable the notification with the env variable `NO_UPDATE_NOTIFIER`. It looks like this is no more possible since 90487a3a8e832d9970881c9904c1e60078a3ae95 and unless I miss something there is no alternative.

**Comment by gluxon** [comment]
+1 to this feature. Did some quick searching and `npm` currently uses the `update-notifier` config.

https://github.com/npm/cli/blob/4dbeb007d0d6350284c7b1edbf4d5b0030c67c66/lib/utils/update-notifier.js#L39-L43
```js
  if (!npm.config.get('update-notifier') ||
      isGlobalNpmUpdate(npm) ||
      ciDetect()) {
    return null
  }
```

Which was implemented here: https://github.com/npm/npm/pull/20750
