### ISSUE TITLE
Not able to use custom CLI options with valid ones

### ISSUE THREAD

**Issue by gabrielhpugliese** [pnpm/pnpm#4159]
### Code to reproduce the issue:

`pnpm install --frozen-lockfile --config.target_arch x64`

### Expected behavior:

It should simply not raise any ERROR

### Actual behavior:

```
 ERROR   ERROR  Unknown option: 'frozen-lockfile'
Did you mean 'lockfile'? Use "--config.unknown=value" to force an unknown option
```

### Additional information:

 - `node -v` prints: v17.2.0
 - Windows, macOS, or Linux?: macOS and Linux

**Comment by fireairforce** [comment]
Try `pnpm install --frozen-lockfile --config.target_arch=x64`

**Comment by gabrielhpugliese** [comment]
Yep, it works 👍

**Comment by gabrielhpugliese** [comment]
Sorry, I guess it does not work. I am trying to use that flag to install `node-sass` in a Docker container running `linux/amd64` and I see this on the logs (this does not happen when I use npm)

```
.../node_modules/node-sass install: Downloading binary from https://github.com/sass/node-sass/releases/download/v7.0.0/linux-arm64-93_binding.node
.../node_modules/node-sass install: Cannot download "https://github.com/sass/node-sass/releases/download/v7.0.0/linux-arm64-93_binding.node":
.../node_modules/node-sass install: HTTP error 404 Not Found                                                                                                                                                               .../node_modules/node-sass install: Hint: If github.com is not accessible in your location
.../node_modules/node-sass install:       try setting a proxy via HTTP_PROXY, e.g.
.../node_modules/node-sass install:       export HTTP_PROXY=http://example.com:1234
.../node_modules/node-sass install: or configure npm proxy via
.../node_modules/node-sass install:       npm config set proxy http://example.com:8080
.../node_modules/node-sass install: Done

.../node_modules/node-sass postinstall: gyp info using node-gyp@7.1.2
.../node_modules/node-sass postinstall: gyp info using node@16.13.1 | linux | arm64
```

**Comment by fireairforce** [comment]
@gabrielhpugliese it seems the option doesn't make sense?

**Comment by gabrielhpugliese** [comment]
Do you mean target_arch? Yes, it does because I need it to install
node-sass with npm inside my arm64 container.

https://github.com/sass/node-sass/issues/3033

zoomdong ***@***.***> schrieb am Do., 6. Jan. 2022, 08:19:

**Comment by fireairforce** [comment]
can you please provide me a reproduce repo or `package.json` file for me, i want to reproduce it and will fix it~

**Comment by fireairforce** [comment]
How about you try `npm_config_target_arch=x64 pnpm install --frozen-lockfile`  ?

**Comment by gabrielhpugliese** [comment]
Looks like I don't need that option anymore. The binary is being installed successfully. I guess they've added a new binary for my arch in `node-sass`. Thanks for the help.
