### ISSUE TITLE
npm_config_CUSTOM is ignored when used with valid flags

### ISSUE THREAD

**Issue by gabrielhpugliese** [pnpm/pnpm#4160]
### Code to reproduce the issue:

`npm_config_target_arch=x64 pnpm install --frozen-lockfile`

### Expected behavior:

It should install with that custom `npm_config_target_arch` variable

### Actual behavior:

It ignores the `npm_config_target_arch` but looks like `--frozen-lockfile` is being considered

### Additional information:

 - `node -v` prints: v17.2.0
 - Windows, macOS, or Linux?: macOS and Linux

**Comment by zkochan** [comment]
Do you mean that the npm_config_target_arch env variable is not passed to the scripts executed by pnpm?

**Comment by gabrielhpugliese** [comment]
Hi,

Yes, I think it's not because my installation fails like this but doesn't
when I omit "--frozen-lockfile"


Zoltan Kochan ***@***.***> schrieb am Mi., 29. Dez. 2021,
14:52:

**Comment by gabrielhpugliese** [comment]
Can't reproduce this anymore. See #4159
