### ISSUE TITLE
Pnpm used in react native cannot be started：Could not read script '/Users/*** /node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.

### ISSUE THREAD

**Issue by JiuXi-331** [pnpm/pnpm#4165]
### Code to reproduce the issue:
<img width="1413" alt="WX20211227-170727@2x" src="https://user-images.githubusercontent.com/51979013/147455549-b4117e4c-82bb-47b9-b4cb-070a176ebb8d.png">

### Additional information:

 - `node -v` prints: v14.17.1

 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
Try with the new `node-linker=hoisted` option released in https://github.com/pnpm/pnpm/releases/tag/v6.25.0-2

**Comment by JiuXi-331** [comment]
Via V6 The method provided in 25.0-2 has solved the startup of a separate react native project, but it still fails in the monorepo project under pnpm

**Comment by JiuXi-331** [comment]
#4263
