### ISSUE TITLE
 WARN  POST http://localhost:5813/requestPackage error (ECONNREFUSED). Will retry in 10 seconds. 100 retries left.

### ISSUE THREAD

**Issue by issadarkthing** [pnpm/pnpm#4177]
### Code to reproduce the issue:
- go to any root package with `package.json` lists any dependencies
- `pnpm install`

### Expected behavior:

pnpm should able to install packages without any error

### Actual behavior:

Unable to install packages using `pnpm install`. It outputs this error when trying to install the packages.
```
A store server is running. All store manipulations are delegated to it.
 WARN  POST http://localhost:5813/requestPackage error (ECONNREFUSED). Will retry in 10 seconds. 100 retries left.
 WARN  POST http://localhost:5813/requestPackage error (ECONNREFUSED). Will retry in 10 seconds. 100 retries left.
 WARN  POST http://localhost:5813/requestPackage error (ECONNREFUSED). Will retry in 10 seconds. 100 retries left.
```

When I try to stop the server using `pnpm server stop`. The console does not output anything and it holds the cursor.

When I try to stop the server using `pnpm server start`. It outputs this log
```
ERR_PNPM_SERVER_MANIFEST_LOCKED  Canceling startup of server (pid 5778) because another process got exclusive access to server.json
```

### Additional information:

 - `node -v` prints: v17.3.0
 - Linux

**Comment by issadarkthing** [comment]
This is resolved by removing `~/.pnpm-store/v3/server/server.json`

**Comment by luy19** [comment]
> This is resolved by removing `~/.pnpm-store/v3/server/server.json`

If you are using windows, the path is`%LocalAppData%\pnpm\store\v3\server\server.json`.

**Comment by pratik149** [comment]
In my case adding line `registry=https://registry.npmjs.org/` in `.npmrc` file resolved the issue.

**Comment by remysabliet** [comment]
All solution didn't resolve the problem for me.

The store was made from an old version of pnpm uncompatible with more recent version of pnpm.
Because there is no process to be found to be the pnpm store, the only one way to fix it was to delete the store itself.

You can store your store location running:
`pnpm store path`

MAC:

`rm -rf  <store path>
