### ISSUE TITLE
Cannot pass flags to processes through `pnpm run`

### ISSUE THREAD

**Issue by innocenzi** [pnpm/pnpm#4187]
### Code to reproduce the issue:

In `package.json`: 

```json
{
  "scripts": {
    "cli": "node ./packages/cli/dist/cli.js"
  }
}
```

### Expected behavior:

When using `pnpm cli --owo`, `process.argv` in `cli.js` should be:

```js
[
  'path-to-node.exe',
  'path-to-cli.js',
  '--owo'
]
```

### Actual behavior:

But instead it is just:

```js
[
  'path-to-node.exe',
  'path-to-cli.js',
]
```

### Additional information:

This has got me very confused, coming from `yarn` where this work flawlessly. 

Manually using `node ./packages/cli/dist/cli.js --owo` works, as well as doing `yarn cli --owo`. 
`pnpm run cli --owo`, `pnpm run cli -- --owo` and `pnpm cli -- --owo` don't work either.

```
➜  npx envinfo --system --binaries --browsers

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 6.34 GB / 15.93 GB
  Binaries:
    Node: 16.13.1 - D:\Programmes\Laragon\bin\nodejs\node-v16.13.1\node.EXE
    npm: 8.1.2 - D:\Programmes\Laragon\bin\nodejs\node-v16.13.1\npm.CMD
```

**Comment by fireairforce** [comment]
![image](https://user-images.githubusercontent.com/32598811/148069714-013c5d22-b612-4969-b118-92d9f89a996b.png)

Looks like they are same?

**Comment by innocenzi** [comment]
My bad, copy-paste issue. The second snippet only has the path to node and the path to the script, not the other arguments passed to the command line.

**Comment by fireairforce** [comment]
@innocenzi Can u please provide a small case for it ?

**Comment by fireairforce** [comment]
Can u please provide a live small demo for it @innocenzi ?

**Comment by innocenzi** [comment]
Sure, here you go: https://github.com/innocenzi/pnpm-run-cli-args-issue-4187

![](https://i.imgur.com/bilzXIq.png)

---

Clone the repository, use `pnpm cli --some-flag` and `yarn cli --some-flag` (or `npm run cli -- --some-flag`), see the difference. 

Note: I realized when reproducing the issue that normal arguments were properly forwarded (eg. `pnpm cli some-arg` will behave as expected). So apparently it's just flags (starting with `--` or `-`).

**Comment by VitorLuizC** [comment]
Does `pnpm cli -- --some-flag` works?

**Comment by innocenzi** [comment]
> Does `pnpm cli -- --some-flag` works?

Hi, not when I created that issue, no.

**Comment by gluxon** [comment]
This might be a duplicate of https://github.com/pnpm/pnpm/issues/3778.

**Comment by zkochan** [comment]
Try with pnpm v7

**Comment by innocenzi** [comment]
It works as expected with [v7.0.0-alpha.0](https://github.com/pnpm/pnpm/releases/tag/v7.0.0-alpha.0), thanks!
