### ISSUE TITLE
error when trying to install pnpm when Node.js is not preinstalled

### ISSUE THREAD

**Issue by matheusfcorocher** [pnpm/pnpm#4189]
### pnpm version:
None
### Code to reproduce the issue:
Run this code in Powershell:
`iwr https://get.pnpm.io/install.ps1 -useb | iex`

### Expected behavior:
pnpm be sucessfully installed
### Actual behavior:
![image](https://user-images.githubusercontent.com/56937223/147989221-49953142-7f2a-44fd-a187-8a102eaea4b4.png)

### Additional information:
 - `node -v` prints: None
 - Windows, macOS, or Linux?: Windows 10
 - **Tip**: My username in Windows is 'Matheus Corocher'. I think the problem can be that my username has blank space and therefore gives this error, because command reader only read until 'Matheus'.

**Comment by Jack-Works** [comment]
if you cannot wait for it to be fixed, you can use npm to install pnpm

**Comment by matheusfcorocher** [comment]
Okay, I'll follow your advice, thanks for response.
