### ISSUE TITLE
unable to install root packages

### ISSUE THREAD

**Issue by lvkins** [pnpm/pnpm#4225]
I'm having an issue setting up a proper dockerfile that would install dependencies only relevant to the workspace I'm filtering - including the project root dependencies.

### Code to reproduce the issue: 

I install workspace and it's deps:
`pnpm i --filter=myproj1...`

However, root project dependencies are not being installed (though some workspaces in a monorepo depend on them).
I'm not sure if pnpm allows to do the root packages installation separately because `pnpm i` in the project root actually scopes all workspace packages.

### Expected behavior:

I would expect `pnpm i --filter=myproj1...` to install packages relevant to the workspace `myproj1` and it's dependencies - that is, including the root directory with package.json where the `packages` folder is in.

### Actual behavior:

Project root dependencies are ignored. I'm able to only install root project dependencies by running `pnpm i` but this will scope  all monorepo workspaces and I don't want that. 

### Additional information:

 - `node -v` prints: v14.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by lvkins** [comment]
Current `.npmrc` setup:

```
shared-workspace-lockfile=false
shamefully-hoist=true
node-linker=hoisted
symlink=false

**Comment by BlackHole1** [comment]
see: https://github.com/pnpm/pnpm/pull/3647

you can use `--workspace-root` flag.
