### ISSUE TITLE
ENOTDIR error attempting to add a package to a workspace

### ISSUE THREAD

**Issue by robcaldecott** [pnpm/pnpm#4232]
### pnpm version:

6.25.0

### Code to reproduce the issue:

https://github.com/robcaldecott/vite-react-component-lib-jsx

```
pnpm install
cd components
pnpm add -D rollup
```

https://gist.github.com/robcaldecott/9bd5081150843f84cba02da070b900d8

### Expected behavior:

Package should install (any package you install will fail).

Note that the `components` workspace in the demo requires `node-linker=hoisted` for Storybook to work.

### Actual behavior:

```
|    +1517   -8 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 ENOTDIR  ENOTDIR: not a directory, rename '/Users/caldecor/Projects/vite-react-component-lib-jsx/app/node_modules/@emotion/_tmp_13039_78104de14356d2813393a96b636a783e' -> '/Users/caldecor/Projects/vite-react-component-lib-jsx/app/node_modules/@emotion/react'
```

### Additional information:

 - `node -v` prints: 14.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by robcaldecott** [comment]
`node-linker=hoisted` definitely seems to be causing the issue.

**Comment by zkochan** [comment]
This will be fixed in next version. The issue was in rename-overwrite: https://github.com/zkochan/packages/commit/d36ad80841962af4f2c219023e7b10e384c7d8e5

Fixed via https://github.com/pnpm/pnpm/pull/4229

**Comment by zkochan** [comment]
:ship: 6.26.1
