### ISSUE TITLE
Is there any method support volta by any sub package in pnpm？

### ISSUE THREAD

**Issue by skimmilk6877** [pnpm/pnpm#4240]
I hava a big monorepo of aroud 30+ package. it is so easy to have some old node version dependent.

is there a way to support volta pin in any sub package? or is there any plan for pnpm to control env in sub package?

**Comment by zkochan** [comment]
You can set `use-node-version` in `.npmrc`

https://pnpm.io/npmrc#use-node-version

**Comment by skimmilk6877** [comment]
@zkochan thanks
