### ISSUE TITLE
pnpm list to show information whether the package is private or not

### ISSUE THREAD

**Issue by kenrick95** [pnpm/pnpm#4246]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I am migrating a monorepo that currently uses lerna. In our setup, we feed [`lerna list`](https://github.com/lerna/lerna/tree/main/commands/list) into a script to analyze the packages in the monorepo. In pnpm, we can use something like `pnpm list --recursive --depth -1 --json`. However, pnpm does not tell whether a package is private or not.

**Describe the solution you'd like**

In `pnpm list`, return package information about whether it is private or not.

**Describe the drawbacks of your solution**

Adding output to `pnpm list` might break existing tooling that does not expect such information.

**Describe alternatives you've considered**

Without this feature, when analyzing packages using script, I would need to use the package path to read each packages' package.json.

**Comment by zkochan** [comment]
Sounds good.
