### ISSUE TITLE
Failure to resolve scoped package via Nexus proxy (npm works)

### ISSUE THREAD

**Issue by bdellegrazie** [pnpm/pnpm#4283]
### Code to reproduce the issue:
example `package.json`:
```
{
  "name": "example",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@gehtsoft/forex-connect-lite": "0.0.2"
  }
}
```

Unproxied `.npmrc`:
```
audit=false
save-exact=true
cache=./cache
store-dir=./store
@gehtsoft:registry=https://www.myget.org/F/gehtsoft-public/npm/
```

Proxied via Nexus (with auth, elided):
```
audit=false
save-exact=true
cache=./cache
store-dir=./store
@gehtsoft:registry=http://localhost:8081/repository/npm-gehtsoft-public/
```

`pnpm-lock.yaml` stanza for relevant artifact:
```
  /@gehtsoft/forex-connect-lite/0.0.2:
    resolution: {integrity: sha1-O1E4wmuxijI0vl1LLWtcs4iRZ0M=, tarball: '@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz'}
    dependencies:
      buffer: 6.0.3
      crypto-js: 4.1.1
      pako: 2.0.4
      xml: 1.0.1
      xmldom: 0.6.0
    dev: false
```

Equivalent npm `package-lock.json` stanza:
```
    "@gehtsoft/forex-connect-lite": {
      "version": "0.0.2",
      "resolved": "https://www.myget.org/F/gehtsoft-public/npm/@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz",
      "integrity": "sha1-O1E4wmuxijI0vl1LLWtcs4iRZ0M=",
      "requires": {
        "buffer": "^6.0.3",
        "crypto-js": "^4.1.1",
        "pako": "^2.0.4",
        "xml": "^1.0.1",
        "xmldom": "^0.6.0"
      }
    },
```

### Expected behavior:
`pnpm install` (direct) works and produces a lock file.
`pnpm install --frozen-lockfile` (using Nexus) works

### Actual behavior:
`pnpm install` works and produces lock file
`pnpm install --frozen-lockfile` using Nexus fails to resolve (404) - pnpm debug information attached.

`npm install` (direct) works and produces `package-lock.json`
`npm ci` (via Nexus) works as expected.

Note specifically the different URLs used by pnpm vs npm to retrieve the artifact:
pnpm: `http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz`
npm: `http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/forex-connect-lite-0.0.2.tgz`

There is an extra `@gehtsoft` in the path used by pnpm which is resulting in a 404.

### Additional information:

 - `node -v` prints: `v16.13.2`
 - Windows, macOS, or Linux?: Linux - Ubuntu 20.04
 - Nexus `v3.37.3`

pnpm-debug.log subset:
```
  "29 debug pnpm:request-retry": {
    "attempt": 1,
    "error": {
      "code": "ERR_PNPM_FETCH_404",
      "hint": "An authorization header was used: Basic cm86[hidden]",
      "attempts": 1,
      "request": {
        "url": "http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz",
        "authHeaderValue": "Basic cm86[elided]"
      },
      "response": {
        "size": 0
      },
      "resource": "http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz"
    },
    "maxRetries": 2,
    "method": "GET",
    "timeout": 10000,
    "url": "http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz"
  },
```

Equivalent subset of `npm-debug.log`:
```
npm http fetch GET 200 http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/forex-connect-lite-0.0.2.tgz 370ms (cache miss)
```

**Comment by zkochan** [comment]
With this `.npmrc` it seems to work.

```
@gehtsoft:registry=https://www.myget.org/F/gehtsoft-public/npm/
```

The other one I am not sure how to reproduce. Do I need  to run some server locally?

**Comment by bdellegrazie** [comment]
@zkochan yes, I'm aware it works correctly "directly", my point was that it doesn't work when using Sonatype Nexus v3 (latest) as an intermediary however npm does.

**Comment by zkochan** [comment]
I started the Nexus 3 docker image locally: https://hub.docker.com/r/sonatype/nexus3/

now I am getting this on `pnpm install`

```
 ERR_PNPM_FETCH_404  GET http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft%2Fforex-connect-lite: Repository not found - 404
```

So I guess I have to figure out how to configure the proxy.

**Comment by zkochan** [comment]
OK, I think I figured it out. I need to login through the web interface as an administrator and then this: https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management#RepositoryManagement-ManagingRepositoriesandRepositoryGroups

**Comment by zkochan** [comment]
Looks like I don't have issues. This is what I get in the locfkile:

```
  /@gehtsoft/forex-connect-lite/0.0.2:
    resolution: {integrity: sha1-O1E4wmuxijI0vl1LLWtcs4iRZ0M=}
    dependencies:
      buffer: 6.0.3
      crypto-js: 4.1.1
      pako: 2.0.4
      xml: 1.0.1
      xmldom: 0.6.0
    dev: false
```

and the tarball is downloaded from 

```
http://localhost:8081/repository/npm-gehtsoft-public/@gehtsoft/forex-connect-lite/-/forex-connect-lite-0.0.2.tgz
```

**Comment by zkochan** [comment]
ok, these are the steps to reproduce.

1. Run `pnpm install` without the proxy. It will create a lockfile like this:
```
  /@gehtsoft/forex-connect-lite/0.0.2:
    resolution: {integrity: sha1-O1E4wmuxijI0vl1LLWtcs4iRZ0M=, tarball: '@gehtsoft/forex-connect-lite/-/@gehtsoft/forex-connect-lite-0.0.2.tgz'}
    dependencies:
      buffer: 6.0.3
      crypto-js: 4.1.1
      pako: 2.0.4
      xml: 1.0.1
      xmldom: 0.6.0
    dev: false
```
2. Change the `.npmrc` file to use the proxy.
3. Remove node_modules and the store.
4. Run `pnpm install`.

**Comment by bdellegrazie** [comment]
@zkochan: Correct and I apologise for not supplying this information directly.

Thinking about this, it might be due to _where_ the object is stored in Nexus's storage compared with the source repository.
I've assumed that NPM proxies should expose the tarball at the same relative location as the origin structure but that's an assumption, not fact. This might be a bug in Nexus, not NPM.

**Comment by zkochan** [comment]
Maybe we can implement a workaround for Nexus.

Before installation, we can make a request to the registry and detect that it is Nexus (Nexus has "Server=Nexus/3.37.3-02 (OSS)" in the HTTP Headers). If the registry is Nexus, pnpm will normalize the tarball URLs.

cc @pnpm/collaborators

**Comment by bdellegrazie** [comment]
@zkochan : maybe Nexus should make the tarball path the same as the upstream provider? This is what Artifactory appears to do

**Comment by zkochan** [comment]
Where is their repository? Could you create an issue in their repository?

**Comment by zkochan** [comment]
MyGet has an issue as well as it uses a non-standard location for the tarball.

**Comment by bdellegrazie** [comment]
@zkochan : yes, I will try to create one for Nexus and look into MyGet too.

**Comment by bdellegrazie** [comment]
@zkochan: you can close this - the issue is _not_ with pnpm but actually with Nexus

The root cause is how Nexus stores scoped packages without matching the exact upstream path.

* `npm ci` bypasses any settings in `.npmrc` for registry and uses the the _raw url_ in the `package-lock.json`. If I substitute the URL in the lock file with Nexus's registry, the same problem occurs.
* the same problem happens if I use `yarn` and attempt to replace the URL in the `yarn.lock` file.

I'll raise a bug there and link it here for reference sake. Thank you for investigating, sorry for wasting your time.

**Comment by bdellegrazie** [comment]
Just for reference, here is the corresponding Nexus issue:
https://issues.sonatype.org/browse/NEXUS-31268

**Comment by hardikbhatia** [comment]
Hey @bdellegrazie .
Just wanted to catchup whether your issue is  resolved from Nexus side as i can't track your issue in Sonatype jira due to not having permission to view it. 
I am also facing the same issue wherein i am getting 404 while fetching the packages from Nexus.

**Comment by bdellegrazie** [comment]
@hardikbhatia : They closed it as not a bug because the URL location is meant to be treated opaquely (according to them).

For the specific case of Gehtsoft above, on the CI environment where we needed to use Nexus I used the following work-around:

Script (`nexus-patch-pnpm-lock.sh`) to run before `pnpm install` or similar:
```
#!/usr/bin/env bash
set -euo pipefail
sed -i -E -f ".pnpm-ci.sed" "pnpm-lock.yaml"
```

And the rule file `.pnpm-ci.sed` has contents:
```
# Nexus flattens scoped package tarball locations
# Match @gehtsoft scoped packages and change the tarball location to strip the second @gehtsoft
s/(@gehtsoft\/)(.*?)\/-\/\1\2/\1\2\/-\/\2/
```
Similar rules can be added for any other problematic dependencies.
I wouldn't write a generalised rule due to the risk of accidentally breaking other packages.
