### ISSUE TITLE
dotfiles like .gitignore are not included by `pnpm pack`, but `npm pack` includes in the tgz

### ISSUE THREAD

**Issue by devinea** [pnpm/pnpm#4293]
### Code to reproduce the issue:

running `pnpm pack` in the module in link below does not include dotfiles in subdirectories. e.g.  `/templates/core/.gitignore`
https://github.com/SAP/open-ux-tools/tree/e8ad2f68bf048672685183064bc08ba778ef9b1d/packages/ui5-application-writer
In `npm pack` used before https://github.com/pnpm/pnpm/pull/3608 this file was included. 

### Expected behavior:
`templates/.gitignore` in included in the tgz for the packed module
### Actual behavior:
`templates/.gitignore` is missing in the tgz for the packed module
### Additional information:

 - `node -v` prints: v14.18.2
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
I am not sure why this would happen as we use npm's library to get the list of files for packing: https://github.com/pnpm/pnpm/blob/cd4f9341e966eb8b411462b48ff0c0612e0a51a7/packages/plugin-commands-publishing/src/pack.ts#L14

**Comment by BlackHole1** [comment]
I checked the npm source code and found that `templates/.gitignore` does not go into the tar, the npm logic is basically the same as the pnpm logic, both use `npm-packlist`. see: https://github.com/npm/pacote/blob/9548c8cb3a068d1edde3bf7d81745abe00046047/lib/dir.js#L70

If pnpm behaves in the same way as npm, I advocate no changes.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/8198408/153819992-88ff4043-d4be-4573-a7a3-35486128115c.png">

----

If you need this file, you can use the following code to work around it

> package.json
```json
{
    "...": "...",
   "files": ["templates/.gitignore"]
}
```

**Comment by ldiego08** [comment]
@zkochan - @BlackHole1's comment seems to resolve this edge case (valid explanation, valid workaround). Should this issue be closed?

**Comment by BlackHole1** [comment]
@ldiego08 Thank you for the reminder. 😄
