### ISSUE TITLE
`--silent` prevent display of `ERR_PNPM_OUTDATED_LOCKFILE ` error

### ISSUE THREAD

**Issue by ariasuni** [pnpm/pnpm#4298]
### pnpm version:

6.29.1

### Code to reproduce the issue:

`pnpm install --frozen-lockfile --reporter=silent`

with a discrepancy between the `pnpm-lock.yaml` and the `package.json` files.

### Expected behavior:

Error is printed:

`ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with XXX/package.json`

### Actual behavior:

Nothing is displayed, only the exit error number is 1.

### Additional information:

 - `node -v` prints: v14.17.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
Use:

```
pnpm install --frozen-lockfile --loglevel=error
```
