### ISSUE TITLE
pnpm fails to install nexus-prisma in production on Vercel

### ISSUE THREAD

**Issue by NADESHIKON** [pnpm/pnpm#4309]
### pnpm version:
6.30.0

### Code to reproduce the issue:
Use ``nexus-prisma`` and NextJS on Vercel with ``pnpm``

### Expected behavior:
The dependencies successfully resolve

### Actual behavior:
See in https://github.com/prisma/nexus-prisma/issues/189

### Additional information:
This issue **does not happen in local environment**, in my development environment it worked fine without any issues.

I initially thought this is a Prisma/nexus-prisma issue but [this comment](https://github.com/prisma/nexus-prisma/issues/189#issuecomment-1033016117) addressed it's ``pnpm``'s issue as ``yarn`` (and ``npm``) are not having such behavior

 - `node -v` prints: Vercel's NodeJS version
 - Windows, macOS, or Linux?: Linux (on Vercel)

**Comment by 2239559319** [comment]
pnpm will not install devDependencies when NODE_ENV is production. Try to use `pnpm i -P false`

**Comment by NADESHIKON** [comment]
> pnpm will not install devDependencies when NODE_ENV is production. Try to use `pnpm i -P false`

I see how it solves the issue now, thank you. However, I don't think it could be a permanent solution as it's just not viable to install devDependencies in production.

**Comment by zkochan** [comment]
Then make it a prod dep.
