### ISSUE TITLE
Infinite recursion using `--recursive` option

### ISSUE THREAD

**Issue by jimmythomson** [pnpm/pnpm#4312]
### pnpm version:
7.0.0-alpha.0

### Code to reproduce the issue:

I'll flesh this out when I get time, but for now....

In my top level `package.json` (in my monorepo) I have:
`"build": "pnpm build --recursive"`

### Expected behavior:

It should run the `build` script in every package of the monorepo.

### Actual behavior:

When I run this, an infinite recursion issue occurs:
```
> @ build /home/james/code/ge/mach/api/application
> pnpm run build --recursive

> @ build /home/james/code/ge/mach/api/application
> pnpm run build --recursive "--recursive"

> @ build /home/james/code/ge/mach/api/application
> pnpm run build --recursive "--recursive" "--recursive"

> @ build /home/james/code/ge/mach/api/application
> pnpm run build --recursive "--recursive" "--recursive" "--recursive"

> @ build /home/james/code/ge/mach/api/application
> pnpm run build --recursive "--recursive" "--recursive" "--recursive" "--recursive"

....and so on....
```

This problem does **not** occur in `6.30.0`

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/issues/2769
