### ISSUE TITLE
pnpm env use --global lts - EPERM: operation not permitted, symlink (Windows 11)

### ISSUE THREAD

**Issue by colinmollenhour** [pnpm/pnpm#4315]
### Code to reproduce the issue:

```
PS > iwr https://get.pnpm.io/install.ps1 -useb | iex
```
PATH did not contain pnpm after launching a new shell, had to run the above twice for some reason?

```
PS > pnpm env use --global lts
```

### Expected behavior:

Installs the latest LTS and links it into PATH

### Actual behavior:

```
EPERM  EPERM: operation not permitted, symlink 'C:\Users\USER\AppData\Local\pnpm\nodejs\16.14.0\node.exe' -> 'C:\Users\USER\AppData\Local\pnpm\node.exe'
```

### Additional information:

This is a very clean install of Windows 11 - no previous version of Node or PNPM had ever been installed before.

I ran the same steps in a PowerShell invoked with Run as Administrator and that worked. Is it expected that the installer needs to run as Administrator? If so, I believe this should be noted in the installation guide.

**Comment by ArtoriaShirou** [comment]
Same here, need to use administrator privileges to install.

**Comment by kaminskypavel** [comment]
you'll need to run either `cmd` or `git bash`  "as administrator" 🫤

**Comment by mominshaikhdevs** [comment]
> ... Is it expected that the installer needs to run as Administrator?... 

**It's been [**more than 6 years**](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10) since you don't need to "Run As Administrator" to create "Symlinks" in windows 10 v10.0.14972 and newer Windows versions** - when you have "Developer Mode" enabled. ( Settings > Update and Security > For Developers > toggle on Developer Mode ). 

![Screenshot 2022-12-18 160133](https://user-images.githubusercontent.com/113818323/208292207-596e0870-8e90-4aab-a95f-1137628a0fa7.png)

**Comment by colinmollenhour** [comment]
@mominshaikhdevs Good to know, but is it expected that one must first enable Developer Mode to install pnpm?
I don't think "Developer Mode" means just anyone that is a developer but rather developers who specifically need to run locally compiled code and disable security features of Windows. Running node.exe doesn't otherwise require developer mode so IMHO it shouldn't be required for installation and should be discouraged for security reasons.

**Comment by mominshaikhdevs** [comment]
@colinmollenhour Answer to that question will be a no as pnpm uses hardlinks , not symlinks. Hardlinks don't require "Developer Mode".

**Comment by RihanArfan** [comment]
I'm digging in the source code and I think I found the culprit. https://github.com/pnpm/pnpm/blob/ee61ca4cb7ce6b3cb177f892940edb55b19b9e17/env/plugin-commands-env/src/envUse.ts#L33

I think the options are:
- Changing it from `file` to `junction` _might_ work, but I'm still reading up on it.
- Alternatively, we could hard link?

The code the rest of pnpm uses for hard linking is here I believe, but it's not exported. https://github.com/pnpm/pnpm/blob/ece5a1aeb94e32e2b1f4a2a1c61813d0f13a8d98/fs/hard-link-dir/src/index.ts#L46-L72

**Comment by zkochan** [comment]
The solution is to used the `symlink-dir` package instead of `fs.symlink`. It creates junctions on Windows, which work with no issues. `symlink-dir` is used a lot by pnpm CLI.

**Comment by zkochan** [comment]
@RihanArfan it appears that junctions only work with directories, so symlink-dir won't work. I guess we may use hard links if they work.

**Comment by colinmollenhour** [comment]
Thanks @zkochan !
