### ISSUE TITLE
pnpm doesn't work in vscode's zsh terminal

### ISSUE THREAD

**Issue by joriscai** [pnpm/pnpm#4318]
# in zsh terminal
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/17852005/153577223-1bb6ba47-3b3f-4bbd-8a62-61e6705b5cb1.png">
execute error.
I try to remove the NODE_OPTIONS.
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/17852005/153577320-ff735bb8-4860-4c11-b71c-5f824f9cd330.png">
run ok

# in bash terminal
I didn't do anything. 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/17852005/153577056-7da71a66-e019-4c6d-9172-c15fc37e1c0f.png">

### Additional information:

 - `node -v` prints: v16.13.2
 - macOS 10.15.7 (19H1615)

**Comment by BlackHole1** [comment]
I don't have this problem

<img width="1972" alt="image" src="https://user-images.githubusercontent.com/8198408/153714526-f0f743d0-a3e0-4fb4-b575-5bbe110a9f6c.png">

**Comment by joriscai** [comment]
> I don't have this problem
> 
> <img alt="image" width="1972" src="https://user-images.githubusercontent.com/8198408/153714526-f0f743d0-a3e0-4fb4-b575-5bbe110a9f6c.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/17852005/153714736-45b05556-3360-401a-9ab0-e6fd80662bc8.png">

@BlackHole1 I enable JavaScript Debugger extension. If I disabled it, it works fine. But JavaScript Debugger extension is internal.

**Comment by BlackHole1** [comment]
I just found out through research that this is a bug in https://github.com/vercel/pkg

see:
* https://github.com/vercel/pkg/issues/484
* https://github.com/vercel/pkg/issues/1217
* https://github.com/vercel/pkg/issues/932
* https://github.com/vercel/pkg/issues/954 (This is basically the same as your question)
* https://github.com/vercel/pkg/issues/447
* https://github.com/vercel/pkg/issues/709
* https://github.com/vercel/pkg/issues/921

pkg desc:

https://github.com/vercel/pkg/tree/64774c5ebface08a7c787b5a5c036454c93f8140#troubleshooting

<img width="888" alt="image" src="https://user-images.githubusercontent.com/8198408/153715261-2eac3fd0-faaa-4b08-b5b6-a79f9d6ddcfd.png">

----

**As a temporary solution, do not use the pnpm binaries.**

**Comment by joriscai** [comment]
> 

@BlackHole1 If i do not use the pnpm binaries, so what are the ways I can use

**Comment by BlackHole1** [comment]
see: https://pnpm.io/installation

```shell
brew install pnpm
# or
npm install -g pnpm
# or
npx pnpm add -g pnpm
```

**Comment by joriscai** [comment]
> see: https://pnpm.io/installation
> 
> ```shell
> brew install pnpm
> # or
> npm install -g pnpm
> # or
> npx pnpm add -g pnpm
> ```

ok.Thank you.
