### ISSUE TITLE
vercel/pkg distributed pnpm crashes when NODE_OPTIONS="--max-old-space-size=4096" is set

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#4319]
## Actual Behavior

The [vercel/pkg](https://github.com/vercel/pkg) distributed version of `pnpm` seems to immediately exit with code 4 when `NODE_OPTIONS` is set with `--max-old-space-size`.

```
❯ NODE_OPTIONS="--max-old-space-size=4096" pnpm

❯ echo $?           
4
```

- The `.cjs` version of `pnpm` does not have this bug.
- This may be a `vercel/pkg` bug and not related to `pnpm` at all.
- I haven't had a chance to repro with a debug build yet. There will likely be better error output.

## Expected Behavior

Expecting `pnpm` to output its standard help message.

```
❯ NODE_OPTIONS="--max-old-space-size=4096" pnpm
Version 6.30.1 (compiled to binary; bundled Node.js v14.17.0)
Usage: pnpm [command] [flags]
       pnpm [ -h | --help | -v | --version ]
```

### Additional information:

 - `node -v` prints: v17.4.0
 - Windows, macOS, or Linux?: Reproduced on macOS and Linux.

**Comment by gluxon** [comment]
Not the highest priority bug. This was spotted from a setup that had `export NODE_OPTIONS` set globally, which isn't a great practice anyway.

**Comment by gluxon** [comment]
Just realized this dupes https://github.com/pnpm/pnpm/issues/4318.

**Comment by BlackHole1** [comment]
I don't have this problem here

<img width="893" alt="image" src="https://user-images.githubusercontent.com/8198408/153713900-f366d675-d3dd-4370-82c1-618d386ade0a.png">

**Comment by gluxon** [comment]
That looks like the plain JavaScript version of pnpm.

> The .cjs version of pnpm does not have this bug.

It's only the "compiled to binary" version exhibiting this.

**Comment by BlackHole1** [comment]
You are right

<img width="887" alt="image" src="https://user-images.githubusercontent.com/8198408/153714694-202562de-7b25-488b-8794-912257df0d2a.png">

**Comment by BlackHole1** [comment]
I just found out through research that this is a bug in https://github.com/vercel/pkg

see:
* https://github.com/vercel/pkg/issues/484
* https://github.com/vercel/pkg/issues/1217
* https://github.com/vercel/pkg/issues/932
* https://github.com/vercel/pkg/issues/954
* https://github.com/vercel/pkg/issues/447
* https://github.com/vercel/pkg/issues/709
* https://github.com/vercel/pkg/issues/921 (This is basically the same as your question)

pkg desc:

https://github.com/vercel/pkg/tree/64774c5ebface08a7c787b5a5c036454c93f8140#troubleshooting

<img width="888" alt="image" src="https://user-images.githubusercontent.com/8198408/153715261-2eac3fd0-faaa-4b08-b5b6-a79f9d6ddcfd.png">

----

**As a temporary solution, do not use the pnpm binaries.**

**Comment by BlackHole1** [comment]
@zkochan I think it might be better to refuse to release the binaries

**Comment by gluxon** [comment]
Thank you for looking into this and linking all the existing reports @BlackHole1 🙂

**Comment by zkochan** [comment]
Why should we refuse to release the binaries? The js version is released as well.

I don't understand why is pkg crashing. It is silly. Couldn't it just ignore the NODE_OPTIONS instead of crashing?

**Comment by BlackHole1** [comment]
I have consulted the relevant information and there is no way to ignore `NODE_OPTIONS` at the moment.
At the moment we have to wait for [vercel/pkg](https://github.com/vercel/pkg) to fix this issue.

**Comment by BlackHole1** [comment]
this is `yarn.msi` commit: https://github.com/yarnpkg/yarn/commit/66e43957654d45e1e801b66c4ef1a61dcd2a2af3

<img width="757" alt="image" src="https://user-images.githubusercontent.com/8198408/153786293-3d940bd8-fef2-460a-816e-858cd86d595a.png">

**Comment by BlackHole1** [comment]
In my personal opinion, the release of binaries offers few advantages. Sure, it's better in a CI environment, but it's more of a fault than a benefit compared to the problems it causes.

Maybe all we need to care about is: `choco`, `scoop`, `brew`, `apk (linux)`?

**Comment by zkochan** [comment]
The pnpm binary is faster than the js version

**Comment by BlackHole1** [comment]
> The pnpm binary is faster than the js version

Okey. Perhaps we should tell the user explicitly in the documentation: "NODE_OPTIONS is not supported in binaries"

**Comment by gluxon** [comment]
> The pnpm binary is faster than the js version

Yeah this was the reason I had decided to preinstall the binary version in our development image.

I was a bit surprised to see a binary distribution in the first place, but I do like the concept. In theory all of V8's Just-In-Time (JIT) Compilation is unnecessary when you can just precompile all the JS. 🙂

> Okey. Perhaps we should tell the user explicitly in the documentation: "NODE_OPTIONS is not supported in binaries"?

This does seem like a big problem with `vercel/pkg`. It used to show a flags mismatch error from glancing at one of the tickets above rather than silently fail. I think the issue just hasn't been seen by someone on the Vercel team yet.

Let me do a new ticket since I don't have permission to open any of the existing closed ones, and we'll see if a response appears soon?

**Comment by zkochan** [comment]
Sure, create a ticket.

**Comment by gluxon** [comment]
https://github.com/vercel/pkg/issues/1517

I'm going to go spelunking in `vercel/pkg`'s source today or tomorrow to see if the fix is easy. I think issues tend to get more visibility when there's a pull request.

**Comment by zkochan** [comment]
Actually, we currently use a fork of vercel/pkg (because I cannot merge a PR https://github.com/vercel/pkg/pull/1344)

So if they have fixed it recently, maybe we didn't get the fix in the fork.

**Comment by gluxon** [comment]
I had ran `pnpm install -g pkg` and was able to reproduce with `pkg@5.5.2`.
