### ISSUE TITLE
PNPM_PACKAGE_NAME doesn't seem to be set in exec

### ISSUE THREAD

**Issue by cefn** [pnpm/pnpm#4320]
Hi all. Somehow the PNPM_PACKAGE_NAME env variable doesn't get set for the shell commands in my `exec --recursive` as [indicated in the documentation](https://pnpm.io/cli/exec#--recursive--r) . 

### pnpm version:

6.30.1

### Code to reproduce the issue:

I'm trying to rely on the documented behaviour that the package name is aliased to the env variable `PNPM_PACKAGE_NAME` as each module is traversed with `--recursive exec`

Unfortunately with an entry in my package.json like  `"check": "pnpm --recursive exec -- echo $PNPM_PACKAGE_NAME",` it just outputs empty lines, one for each module. Every module has a `name` parameter in its package.json. I have tried adding quotes with `\"` but it has no effect, like `"check": "pnpm --recursive exec -- echo \"$PNPM_PACKAGE_NAME\"",` .

```
> pnpm --recursive exec -- echo $PNPM_PACKAGE_NAME







```

### Expected behavior:

I've double-checked the shell command embedding by using the `$SHELL` variable instead like `"check": "pnpm --recursive exec -- echo $SHELL",` which DOES output env variable content. I'd expect the module names to be output one-per-line.

```sh
> pnpm --recursive exec -- echo $SHELL
/bin/bash
/bin/bash
/bin/bash
/bin/bash
/bin/bash
/bin/bash
```

### Actual behavior:

No env variable seems to be set.

### Workaround

From a comment at https://github.com/pnpm/pnpm/issues/1553#issuecomment-946225788

`"check": "pnpm --recursive exec -- node -e \"console.log(process.env.PNPM_PACKAGE_NAME)\"",`

**Comment by zkochan** [comment]
So looks like it works but the example in the docs is invalid. Not sure how to use it with echo.

**Comment by zkochan** [comment]
Looks like execa here is escaping the argments:

https://github.com/pnpm/pnpm/blob/21cd0f260191729a71115e1ae16654d2b4faf32d/packages/plugin-commands-script-runners/src/exec.ts#L133-L137

Maybe we should use something like [child_process.exec](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback) instead

**Comment by BlackHole1** [comment]
Let me try to fix it

**Comment by cefn** [comment]
Thanks for your attention, both!
