### ISSUE TITLE
`loglevel=error` doesn't supress warnings, such as `WARN deprecated` and ` WARN  Issues with peer dependencies found`.

### ISSUE THREAD

**Issue by brillout** [pnpm/pnpm#4343]
### pnpm version:

6.30.0

### Code to reproduce the issue:

See screenshot. Should be trivial to reproduce, but I can provide a step-by-step reproduction if needed.

### Expected behavior:

As per the documentation (https://pnpm.io/npmrc#loglevel), warnings shouldn't be shown.

### Actual behavior:

Warnings are displayed.

### Additional information:

 - `node -v` prints: `v.16.5.0`
 - Windows, macOS, or Linux?: Linux

![Screenshot 2022-02-16 14 38 06](https://user-images.githubusercontent.com/1005638/154276743-fd15fa67-66d5-4975-8eab-f44670f3d949.png)

**Comment by 2239559319** [comment]
[reportMisc.ts#L12](https://github.com/pnpm/pnpm/blob/main/packages/default-reporter/src/reporterForClient/reportMisc.ts#L12)
`error` is the smallest in `LOG_LEVEL_NUMBER` so setting `loglevel=error` will show `error` `warn` `info` and `debug`

**Comment by brillout** [comment]
Is there a way to supress warnings while still showing errors?

My use case is that I've a examples directory (https://github.com/brillout/vite-plugin-ssr/tree/master/examples):

```
vite-plugin-ssr/examples/react
vite-plugin-ssr/examples/vue
vite-plugin-ssr/examples/cloudflare-workers
...
```

So ideally I'd supress specific warnings for all/specific examples. I've no control over the dependencies of the examples and therefore warnings are expected.

**Comment by milahu** [comment]
> [reportMisc.ts#L12](https://github.com/pnpm/pnpm/blob/main/packages/default-reporter/src/reporterForClient/reportMisc.ts#L12)
>`error` is the smallest in `LOG_LEVEL_NUMBER` so setting `loglevel=error` will show `error` `warn` `info` and `debug`

no, the condition is

```ts
LOG_LEVEL_NUMBER[obj.level] <= maxLogLevel
```

default level is `info` which will show `info` `warn` `error`

`debug` is the most verbose (show all messages)
`error` is the most quiet (as expected)

<details>
<summary>reportMisc.ts</summary>

```ts
// packages/default-reporter/src/reporterForClient/reportMisc.ts

const LOG_LEVEL_NUMBER: Record<LogLevel, number> = {
  error: 0,
  warn: 1,
  info: 2,
  debug: 3,
}

export default (
  ...
) => {
  const maxLogLevel = LOG_LEVEL_NUMBER[opts.logLevel ?? 'info'] ?? LOG_LEVEL_NUMBER['info']
  const reportWarning = makeWarningReporter(opts)
  return Rx.merge(log$.registry, log$.other).pipe(
    filter((obj) => LOG_LEVEL_NUMBER[obj.level] <= maxLogLevel &&
      (obj.level !== 'info' || !obj['prefix'] || obj['prefix'] === opts.cwd)),
    map((obj) => {
      switch (obj.level) {
      case 'warn': {
        return reportWarning(obj)
      }
      case 'error':
        if (obj['prefix'] && obj['prefix'] !== opts.cwd) {
          return Rx.of({
            msg: `${obj['prefix'] as string}:` + os.EOL + reportError(obj, opts.config),
          })
        }
        return Rx.of({ msg: reportError(obj, opts.config) })
      default:
        return Rx.of({ msg: obj['message'] })
      }
    })
  )
}
```

</details>

so it seems that `pnpm install --loglevel error` is using a different logger to produce the `WARN  deprecated` messages
