### ISSUE TITLE
Pnpm publish doesn't work correctly with workspaces and npm 8.5.0

### ISSUE THREAD

**Issue by PieterBoeren** [pnpm/pnpm#4348]
(I'm not sure if this issue is related to pnpm or npm)

### pnpm version:
6.31.0

### Code to reproduce the issue:
1. Install the latest version of NPM (8.5.0)
2. Create a project with workspaces, setup changesets and add dependencies from one workspace to another with something like `"foo": "workspace:*"`
3. Run all the steps to create a new changeset and run `pnpm publish -r`

### Expected behavior:
Workspace references have been replaced with an actual version in the published package.

### Actual behavior:
The published package still contains `"workspace:*"` as version, making it not installable.

### Additional information:

* When I do a manual `pnpm pack` the version is being applied
* Downgrading NPM to version 8.4.1 solves the issue

**Comment by zkochan** [comment]
Maybe a bug in npm.

pnpm packs the tarball with the right manifest and then run the npm CLI to publish the prepared tarball:

https://github.com/pnpm/pnpm/blob/5d2b5ee641e0c59962bff750e293aecca0e8a5e4/packages/plugin-commands-publishing/src/publish.ts#L190

From the description it looks like npm CLI ignores the tarball and packs the folder on its own.

**Comment by lijie1129** [comment]
I have the same problem:

**pnpm version:**
6.32.1

**Code to reproduce the issue:**

1. Install the latest version of NPM (8.5.3 and 8.3.1)
2. Create a project with workspaces, setup changesets and add dependencies from one workspace to another with something like "foo": "workspace:*"
3. Run all the steps to create a new changeset and run pnpm publish -r

**Expected behavior:**

Workspace references have been replaced with an actual version in the published package.

Actual behavior:
The published package still contains "workspace:*" as version, making it not installable.

Additional information:
When I do a manual pnpm pack the version is being applied
Downgrading/Upgrading NPM to version 8.4.1 **does not** solve the issue

**Comment by anuoua** [comment]
Same here

**Comment by zkochan** [comment]
I think npm v7 works because we use npm v7 to publish pnpm and we don't have this issue.

**Comment by Amorites** [comment]
Meet same issue today with node v16.14.2 and npm 8.5.0, 7.24.2.
Downgrade to node v14.19.1 and npm 6.14.16 solved this.

**Comment by rainy-me** [comment]
I encountered the same issue and downgrade to node v14.19.1 and npm 6.14.16 doesn't solved this for me.

`uname -a`: `Linux home 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux`

**Comment by zkochan** [comment]
Maybe we could use a library from npm (https://github.com/npm/cli/tree/latest/workspaces/libnpmpublish) or from Yarn, to do the publishing.

**Comment by zkochan** [comment]
I could not reproduce this issue.

**Comment by loynoir** [comment]
https://github.com/pnpm/pnpm/issues/4438

i used workaround, add `.files` field to package.json

**Comment by zkochan** [comment]
:ship: [6.32.11](https://github.com/pnpm/pnpm/releases/tag/v6.32.11) and v7.0.0-rc.9

**Comment by rainy-me** [comment]
@zkochan  I can confirm my issue has been resolved with latest pnpm and node v18! Thanks a lot!

**Comment by ruscon** [comment]
Has the same issue from GitHub actions
```
[11:23:46 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: pnpm publish /home/runner/work/monorepo/monorepo/dist/libs/nestjs/logger-module --tag latest --registry https://npm.pkg.github.com/
 ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL  Cannot resolve workspace protocol of dependency "@xxx/common" because this dependency is not installed. Try running "pnpm install".
```
➜ pnpm -v
8.6.7

➜ node -v
v20.4.0

**Comment by maerzhase** [comment]
currently experiencing the same with:
- pnpm@8.6.9
- npm@9.5.1
- node@18.16.1

**Comment by soeasyjx** [comment]
I've always had this problem

node
v20.10.0

pnpm
8.12.0

Can there be a complete solution

**Comment by liuliangsir** [comment]
Same issue here:
- pnpm@9.9.0
- npm@10.8.2
- node@20.17.0
