### ISSUE TITLE
Cannot find module run with Jest

### ISSUE THREAD

**Issue by graywhale** [pnpm/pnpm#4349]
### Code to reproduce the issue: 
**Background: a very simple unit-test with Svelte component**
Steps:
+ Install dependencies:
```
// initialization
pnpm init svelte@next my-project

// for jestjs
pnpm install --save-dev jest @types/jest @swc/core @swc/jest jest-transform-css

// for @testing-library
pnpm install --save-dev @testing-library/dom @testing-library/jest-dom @testing-library/svelte

// for svelte-jest
pnpm install --save-dev svelte-jester
```
+ jest.config.js
```
export default {
    moduleDirectories: [
        "node_modules"
    ],
    moduleFileExtensions: [
       "js",
       "ts",
       "svelte"
   ],
   testEnvironment: "jsdom",
   transform: {
      "^.+\\.svelte$": ["svelte-jester", {preprocess: true}],
      "^.+\\.(t|j)sx?$": '@swc/jest',
      "^.+\\.css$": "jest-transform-css"
  }
}
```
+ Svelte component
```
<script>
  import './button.css';
  import { createEventDispatcher } from 'svelte';
  /**
   * Is this the principal call to action on the page?
   */
  export let primary = false;

  /**
   * What background color to use
   */
  export let backgroundColor;
  /**
   * How large should the button be?
   */
  export let size = 'medium';
  /**
   * Button contents
   */
  export let label = '';

  let mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';

  let style = backgroundColor ? `background-color: ${backgroundColor}` : '';

  const dispatch = createEventDispatcher();

  /**
   * Optional click handler
   */
  function onClick(event) {
    dispatch('click', event);
  }
</script>

<button
  type="button"
  class={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
  {style}
  on:click={onClick}>
  {label}
</button>
```

+ Button.css
```
.storybook-button {
  font-family: 'Nunito Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-weight: 700;
  border: 0;
  border-radius: 3em;
  cursor: pointer;
  display: inline-block;
  line-height: 1;
}
.storybook-button--primary {
  color: white;
  background-color: #1ea7fd;
}
.storybook-button--secondary {
  color: #333;
  background-color: transparent;
  box-shadow: rgba(0, 0, 0, 0.15) 0px 0px 0px 1px inset;
}
.storybook-button--small {
  font-size: 12px;
  padding: 10px 16px;
}
.storybook-button--medium {
  font-size: 14px;
  padding: 11px 20px;
}
.storybook-button--large {
  font-size: 16px;
  padding: 12px 24px;
}
```

+ Button.test.js
```
import '@testing-library/jest-dom'
import {render, fireEvent} from '@testing-library/svelte'
import Button from "@/src/stories/Button.stories.svelte";

const label = "Click Me"

test("Check Button Label", () => {
    const {getByText} = render(Button, {label})
    expect(getByText(label)).toBeInTheDocument()
})

test('Check Button Click Event', async () => {
    const {getByText} = render(Button, {label})
    const button = getByText('Button')

    await fireEvent.click(button)
    expect(button).toHaveTextContent('Button Clicked')
})

```

### Expected behavior:
Run `jest` command should work properly. Actually, I need run unit test via WebStorm, it runs below command
```
node --require /****/jest-intellij-stdin-fix.js /PROJECT_ROOT/node_modules/jest/bin/jest.js --colors --reporters /***/jest-intellij/lib/jest-intellij-reporter.js --verbose --testNamePattern=^Check Button Label$ --runTestsByPath /PROJECT_ROOT/tests/stories/Button.test.js
```

### Actual behavior:
But got some exceptions:
+ Cannot find module 'style-inject' from 'src/stories/button.css'
+ Cannot find module 'regenerator-runtime'  from 'tests/Button.test.js'

### Additional information:
+ Run `pnpm run test` got awesome result ✅
+ Build with `npm`, and run commands `jest` or `npm run test`, both of them worked succeed ✅

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macOS

**Comment by BlackHole1** [comment]
Feels like a problem with `WebStorm Jest`: https://youtrack.jetbrains.com/issue/WEB-51722

**Comment by graywhale** [comment]
@BlackHole1 Thanks a lot. I checked the issue you mentioned, but it can't resolve my problem, and I don't think it's WebStorm's issue. 
Let me describe the problem simply, under the same environment, `npm` works well, but `pnpm` not.

- Using `npm` to manage the dependencies, it works very well. Whatever  `jest` or `npm run test` run in terminal or WebStorm, both of them are working
![image](https://user-images.githubusercontent.com/29625655/154602157-8b0f4159-210a-4a17-9f32-011d04fc0f0d.png)
![image](https://user-images.githubusercontent.com/29625655/154603484-cac91cf3-a487-4848-a553-fc1bbc0b2721.png)

- Using `pnpm` to manage the dependencies, only `pnpm run test` is working
![image](https://user-images.githubusercontent.com/29625655/154602559-df2db19a-114a-45da-955d-feef382b195c.png)
![image](https://user-images.githubusercontent.com/29625655/154602857-bf4da1ba-ec78-47c4-8a44-521b1a0b306d.png)

**Comment by BlackHole1** [comment]
Can you provide a gist or repo?

**Comment by graywhale** [comment]
@BlackHole1 Thanks for your quick response, please get the code via https://github.com/graywhale/svelte-tests.git

**Comment by BlackHole1** [comment]
Okey, I'll check it out later 🚀

**Comment by BlackHole1** [comment]
Put content to `.npmrc`:

```ini
public-hoist-pattern[]=style-inject
public-hoist-pattern[]=*jest*
```

**Comment by graywhale** [comment]
@BlackHole1
Thanks for you response, but it doesn't work yet. 
I checked the Jest's documentation again, and found I missed a moduleNameMapper config item. After installed 'identity-obj-proxy' package, `pnpm` worked well.
```
"moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
},
```

OK, I think it is still an issue, `npm` can work well without 'identity-obj-proxy', but `pnpm` not. I double checked the result, so I hope your team can find out what the problem is.

**Comment by graywhale** [comment]
I updated the repo

**Comment by BlackHole1** [comment]
I need to clarify:

```json
"moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
},
```

When `identity-obj-proxy` is configured, style-inject will not be used, so it appears to be working.

And in the code I mentioned before, you need to re-run `pnpm install`

```
$ cat .npmrc
    engine-strict=true
    public-hoist-pattern[]=style-inject
    public-hoist-pattern[]=*jest*

$ rm -rf node_modules
$ pnpm install
```

**Comment by graywhale** [comment]
@BlackHole1 
Got it, thank you very much!
