### ISSUE TITLE
"workspace:^undefined" will be saved when target package has no version field

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#4357]
Expected: should save "workspace:*"

**Comment by zkochan** [comment]
sounds good. I guess it should be easy to fix.

**Comment by Jack-Works** [comment]
> sounds good. I guess it should be easy to fix.

can you tell me which part I should look at? I'd like to send a PR for this.

**Comment by zkochan** [comment]
Maybe here

https://github.com/pnpm/pnpm/blob/cf478bb8b31c23203f0a0795bbae232245a62dd4/packages/resolve-dependencies/src/updateProjectManifest.ts#L106

**Comment by BlackHole1** [comment]
In https://github.com/pnpm/pnpm/blob/cf478bb8b31c23203f0a0795bbae232245a62dd4/packages/manifest-utils/src/getPref.ts#L19-L22

e.g:

```ts
export function createVersionSpec (version?: string,...) {
  if (!version) {
    return "*"
  }
```

**Comment by fireairforce** [comment]
solved at: https://github.com/pnpm/pnpm/issues/4486
