### ISSUE TITLE
Installed module cannot access it's dependencies with node v17.4.0

### ISSUE THREAD

**Issue by axmad386** [pnpm/pnpm#4364]
### Code to reproduce the issue:

```bash
npx degit kodepandai/lunox lunoxapp
cd lunoxapp
pnpm install
pnpm build
pnpm serve
```

### Expected behavior:
Lunox app should run successfully
This is when I run `pnpm serve` with node v16.6.2
```bash
❯ pnpm serve

> lunox-app@0.8.0 serve /home/dmuggle/GIT/cobalunox
> lunox serve

serving application...
server run on port: 8000

```
### Actual behavior:
lunox dependencies is not detected by pnpm, for example @kodepandai/flydrive, sirv, etc.
This is console.log when I run `pnpm serve`
```bash
❯ pnpm serve

> lunox-app@0.8.0 serve /home/dmuggle/GIT/cobalunox
> lunox serve

serving application...
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@kodepandai/flydrive' imported from /home/dmuggle/GIT/cobalunox/node_modules/lunox/dist/index.js
Did you mean to import @kodepandai+flydrive@2.0.0/node_modules/@kodepandai/flydrive/build/index.js?
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:892:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:18)
    at defaultResolve (node:internal/modules/esm/resolve:1041:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v17.4.0
```
### Additional information:

 - `node -v` prints: v17.4.0
 - Windows, macOS, or Linux?: Linux

**Comment by BlackHole1** [comment]
Works fine with `node@v16.13.2`. The problem arises when using `node@v17.4.0`.

cc: @zkochan

**Comment by BlackHole1** [comment]
update: `node@v17.0.1` works fine, fails from `node@17.1.0`

**Comment by BlackHole1** [comment]
It is possible that the problem was introduced by https://github.com/nodejs/node/pull/40510.

I personally feel that you should submit relevant issues to nodejs

**Comment by BlackHole1** [comment]
Related discussions:
* https://github.com/nodejs/node/issues/41087
* https://github.com/nodejs/node/issues/41321

**Comment by axmad386** [comment]
@BlackHole1 thanks for information. So what should I do for now? I must downgrade the nodejs version?

**Comment by BlackHole1** [comment]
1. downgrade nodejs version, waiting nodejs fix.
2. https://github.com/nodejs/node/issues/41087#issuecomment-988218103
3. https://github.com/nodejs/node/issues/41087#issuecomment-1021771187

**Comment by axmad386** [comment]
ok, thank you so much

**Comment by axmad386** [comment]
Hi, just want to clarify. I was able to solve this issue by implementing explicit import. 
Just change
```js
import module from './folder/module'
```
to
```js
import module from './folder/module.js'
```
Note that we must use `.js` extension even we are using typescript. 
I will close this issue, thank you
