### ISSUE TITLE
Install from GitHub is failed

### ISSUE THREAD

**Issue by rwu823** [pnpm/pnpm#4374]
### pnpm version: 
`6.31.0`

### Code to reproduce the issue:

```sh
yarn add 'rwu823/ts-mono#pkg/ts-base'  # it works.
```

```sh
pnpm i 'rwu823/ts-mono#pkg/ts-base'  # doesn't work.
```

In the same repo but a different branch is working fine there, e.g:
```sh
pnpm i 'rwu823/ts-mono#pkg/eslint-config'
```

### Expected behavior:
Should be installed correct from GitHub branch.

### Actual behavior:
Get error: ` ERR_PNPM_PREPARE_PKG_FAILURE  Command failed with exit code 1:`
 
### Additional information:

 - `node -v` prints: v14.18.3
 - Windows, macOS, or Linux?:  macOS

**Comment by 2239559319** [comment]
yarnpkg/yarn#5235 yarn will not run lifecycle scripts for hosted git dependencies. [prepare script found](https://github.com/rwu823/ts-mono/blob/pkg/ts-base/package.json#L23)

**Comment by rwu823** [comment]
@2239559319 yes, thanks for reply. Close it.
