### ISSUE TITLE
There are undeclared dependencies under node_modules

### ISSUE THREAD

**Issue by classmatewu** [pnpm/pnpm#4380]
### Code to reproduce the issue:
After executing `pnpm i express -S`, I found that there is not only the `express` folder in the node_modules folder, but also the `mime-type` folder, but there is only one express dependency under my project package.json. Is this a bug, because it will lead to Phantom dependencies?
![image](https://user-images.githubusercontent.com/44048381/155322286-9a710177-ff7b-4312-921f-0af64d14ce17.png)
```javascript
"dependencies": {
    "express": "^4.17.3"
}
```

### Expected behavior:
There is no mime-type folder under node_modules

### Actual behavior:
There is a mime-type folder under node_modules

### Additional information:

 - `node -v` prints: v14.16.0
 - Windows, macOS, or Linux?: MacOS Catalina 10.15.7

**Comment by classmatewu** [comment]
But why types to be hoisted default, Is there a problem with Phantom dependencies?

**Comment by zkochan** [comment]
there are some bugs in the ecosystem that we workaround by hoisting some packages

**Comment by classmatewu** [comment]
> there are some bugs in the ecosystem

Is there a specific example?
