### ISSUE TITLE
Recursive installation

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#440]
pnpm is a really good choice for monorepos. However, it cannot run concurrently because it uses the same store.

Add an option called `-r, --recursive` that looks up packages in all subdirs (excluding the ones in node_modules) and run installation for all of them at the same time.

**Comment by iamstarkov** [comment]
does lerna handle dependencies installing? if so, how?

**Comment by zkochan** [comment]
it is running npm install concurrently.

**Comment by zkochan** [comment]
Implemented as a separate package - [pnpmr](https://github.com/pnpm/pnpmr). It searches for all packages inside the cwd and run `pnpm install` for each of the packages.
