### ISSUE TITLE
pnpm breaks `/` imports that improve bundle size

### ISSUE THREAD

**Issue by MarkLyck** [pnpm/pnpm#4402]
I'm trying to switch from yarn to pnpm for the performance improvements but a lot of my imports that work well with either `yarn` or `npm` does not seem to work with `pnpm`

I noticed most of these imports are digging into folders inside the module I'm installing. E.g. for bundle size purposes I don't want to include more code than necessary in libraries where tree-shaking isn't the best option like lodash or @ant-design-charts.

For example lodash, I am only using 2 functions from it, so it decreases my bundlesize by importing just what I need like doing:

```
import uniqBy from 'lodash/uniqBy'
```

instead of 

```
import { uniqBy } from 'lodash'
```

^ There is a bundle size difference between these two. 

Lodash is a small and not that important example probably, just using this since you probably know the library. 

But a big one I use is @ant-design-charts where this makes a very big bundle-size difference. 

-----

### Code to reproduce the issue: 

example library that breaks when you attempt to import a specific module from it directly.

```
import uniqBy from 'lodash/uniqBy'
```

### Expected behavior:

It should import the `uniqBy` file and only that file.

### Actual behavior:

It breaks the entire app with the error:

```
Cannot find module 'lodash/uniqBy' or its corresponding type declarations.
```

### Additional information:

 - `node -v` prints: v16.13.2
 - Windows, macOS, or Linux?: MacOS

**Comment by zkochan** [comment]
This looks like a TypeScript issue. Have you installed `@types/lodash`?

Importing modules this way works. I use the same technique in the pnpm repository to import files from ramda.

**Comment by blazejkustra** [comment]
Installing `@types/lodash` instead of `@types/lodash.reduce` resolved this issue for me, thanks @zkochan 👍
