### ISSUE TITLE
Add `Jenkins` in examples

### ISSUE THREAD

**Issue by ttodua** [pnpm/pnpm#4412]
Under [**Continuous Integration**](https://pnpm.io/continuous-integration) paragraph, all major systems are listed, but it might be good to add `Jenkinsfile` example too/

**Comment by ahmadjubair33** [comment]
Hi @pnpm assign this issue to me I will be working on creating a Jenkinsfile for this.Thank you

**Comment by linghengqian** [comment]
> Hi @pnpm assign this issue to me I will be working on creating a Jenkinsfile for this.Thank you

Any updates? According to your PR, `Jenkins` has no concept of caching like `gitlab-runner`?

**Comment by SSTPIERRE2** [comment]
Any updates on this? There is still no Jenkins section in the CI doc. Is it not possible to use pnpm in a Jenkins pipeline?

**Comment by linghengqian** [comment]
> Any updates on this? There is still no Jenkins section in the CI doc. Is it not possible to use pnpm in a Jenkins pipeline?

- You can submit his PR directly to https://github.com/pnpm/pnpm.github.io .  I do not have time.

**Comment by linghengqian** [comment]
- I am working on this issue.
