### ISSUE TITLE
pnpm where bin - New command to locate a binary

### ISSUE THREAD

**Issue by matthewp** [pnpm/pnpm#4424]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I like to debug bin scripts. In regular npm you would do this with `node --inspect-brk node_modules/.bin/name`. However since pnpm makes those scripts be bash scripts you can no longer do this.

The workaround to this problem is currently to use the NODE_OPTIONS which is verbose and not an optimal or obvious solution.

**Describe the solution you'd like**

You could add an API directly for the debugging use-case but a lower-level solution I think would be to add a command that tells you the real location of a scripts, so that you can call it yourself.

```bash
pnpm where mocha
```

This would return something like 

```bash
/Users/name/projects/pkg/node_modules/.pnpm/mocha@9.2.0/node_modules/mocha/bin/mocha
```

You could then debug this script doing something like this:

```bash
node --inspect-brk $(pnpm where mocha) path/to/my-test.js
```

The name `where` was chosen as this feature mimicks the shell `where` command.

**Describe the drawbacks of your solution**

- There are alternatives that are arguably better.

**Describe alternatives you've considered**

- Passing node args through `pnpx` like: `pnpx --inspect-brk mocha path/to/test.js`. This ultimately didn't make sense to me, as not all bin scripts are Node scripts. You might have anything in the bin scripts; could be a python script, in which case you'd want to pass it to `python`, so the `where` idea seemed better.
- A higher-level API like `pnpm debug bin-name` that does it for you. However debugging is not the only use-case for passing arguments, so something more low-level seems like a better first step.

**Comment by matthewp** [comment]
Temporary workaround: https://gist.github.com/matthewp/facfe1fc16525bc653391bd4442e9ea3

**Comment by BlackHole1** [comment]
Hey @matthewp 👋. Would you like to submit a PR to help us improve it?

**Comment by matthewp** [comment]
Hi @BlackHole1, this is my first time contributing to pnpm. Can I take your reply to mean that this request accepted? Does @zkochan need to chime in? I don't want to spend time on a PR if it's unknown if the request is accepted or not. But if it is, I'm happy to do the work.

**Comment by zkochan** [comment]
I don't have objections.

**Comment by BlackHole1** [comment]
@matthewp You can start now. 🚀

**Comment by matthewp** [comment]
Awesome! If there are any pointers as to where in the code this feature would live, or similar commands to use an example, I would appreciate it. Otherwise I'll just dive it and give it my best.

**Comment by BlackHole1** [comment]
Hey @matthewp 👋.  Has there been any progress?

**Comment by matthewp** [comment]
Yep, I have started on this feature.

**Comment by matthewp** [comment]
Small update, getBinsFromPkg won't work for this, as that looks up bins for a specific package. The idea of this command is to find the bin in the current node_modules. We need the final source, not to the bash file wrapper that is created.

**Comment by marvinhagemeister** [comment]
I'm running into the same problem currently whilst profiling our build tools. Typically I could just do `node --cpu-prof node_modules/.bin/eslint .` to profile eslint, as it's just a symlink to the actual binary for other package managers. With `pnpm` it points to a shell file instead.

**Comment by astahmer** [comment]
> I'm running into the same problem currently whilst profiling our build tools. Typically I could just do `node --cpu-prof node_modules/.bin/eslint .` to profile eslint, as it's just a symlink to the actual binary for other package managers. With `pnpm` it points to a shell file instead.

i'm curious if you found any workaround since then ? same use case here, this would be very useful

**Comment by zkochan** [comment]
> Typically I could just do node --cpu-prof node_modules/.bin/eslint . to profile eslint, as it's just a symlink to the actual binary for other package managers. With pnpm it points to a shell file instead.

You can enable [prefer-symlinked-executables] and pnpm will create symlinks instead of command shims. But only on POSIX. On Windows only command shims work.

[prefer-symlinked-executables]: https://pnpm.io/npmrc#prefer-symlinked-executables

**Comment by milahu** [comment]
> The name `where` was chosen as this feature mimicks the shell `where` command.

nitpick: [where](https://superuser.com/questions/675837/equivalent-of-cmds-where-in-powershell) is part of the windows cmd shell
and it [seems](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/where) to be a generic tool to locate files, not just executables

in powershell its `(get-command somename).Path`

in bash shell its `command -v somename`

on linux, there is also the [which](https://linux.die.net/man/1/which) package, used like `which somename`
ported to javascript as the [which npm package](https://www.npmjs.com/package/which)

**Comment by sleewoo** [comment]
solved by using `pnpm exec`

```bash
node --env-file=.env $(which pnpm) exec knex migrate:latest
```

**Comment by shawnthye-guru** [comment]
> solved by using `pnpm exec`
> 
> ```shell
> node --env-file=.env $(which pnpm) exec knex migrate:latest
> ```

@sleewoo  Thank you

I am using the `use-node-version=20.11.1` in `.npmrc`

now I can get the node binary with `pnpm exec command -v node`

print `/Users/{yourname}/Library/pnpm/nodejs/20.11.1/bin/node`

**Comment by matthewp** [comment]
Sounds like this is not needed any more, closing.

**Comment by fa93hws** [comment]
Got the same issue when trying to pass `--inspect-brk` to `webpack`.
The problem is that I need to pass that to the specific node invocation, so `node --inspect-brk $(which pnpm) exec webpack` doesn't work for me, as it attach the debugger to `pnpm` instead of `webpack`.
And I don't like the hack to extract the actual js binary file, as it highly depends on the implementation details of the bash shim of `pnpm`.
And here's my solution, it's simple but may not apply to all libraries (it should I think?)

When invoking `webpack`, instead of `pnpm webpack`, I create a `webpack.js` with one line only
```
require('webpack/bin/webpack');
```
Then I can simply call `node --inspect-brk webpack.js`, problem solved 🎉 

But it would still be appreciated if there's a `pnpm where` to return the actual js binary location.

**Comment by dasa** [comment]
A feature similar to [`yarn bin eslint`](https://yarnpkg.com/cli/bin) would be great.
