### ISSUE TITLE
pnpm will not be installed in husky generating hooks from .git/hooks.

### ISSUE THREAD

**Issue by cxj-github** [pnpm/pnpm#4426]
### pnpm version:
6.32.3

### Code to reproduce the issue:
git init
rm -rf .git/hooks
pnpm add husky -D
cd .git/hooks

### Actual behavior:
cd: no such file or directory: .git/hooks

### Additional information:
husky 7.0.4

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macOS

**Comment by PengBoUESTC** [comment]
这个怎么解决的 pnpm  install 没有执行 包里定义的 hook

**Comment by cscxj** [comment]
> 这个怎么解决的 pnpm install 没有执行 包里定义的 hook

现在不是在安装包的时候注册git hook了，需要执行`husky install`，按照官方文档做就行了. 
[https://github.com/typicode/husky#usage](https://github.com/typicode/husky#usage)

**Comment by PengBoUESTC** [comment]
> > 这个怎么解决的 pnpm install 没有执行 包里定义的 hook
> 
> 现在不是在安装包的时候注册git hook了，需要执行`husky install`，按照官方文档做就行了. https://github.com/typicode/husky#usage

我遇到的问题是 yorkie 。按道理 这两个包 都应该是通过 package.json 里 scripts 定义的 hook 自动安装 git hook 的，但是 yorkie 在项目里通过 pnpm 没有触发 script hook...

**Comment by cscxj** [comment]
> > > 这个怎么解决的 pnpm install 没有执行 包里定义的 hook
> > 
> > 
> > 现在不是在安装包的时候注册git hook了，需要执行`husky install`，按照官方文档做就行了. https://github.com/typicode/husky#usage
> 
> 我遇到的问题是 yorkie 。按道理 这两个包 都应该是通过 package.json 里 scripts 定义的 hook 自动安装 git hook 的，但是 yorkie 在项目里通过 pnpm 没有触发 script hook...

yorkie应该把hook定义在`gitHooks`中吧。[https://github.com/yyx990803/yorkie#yorkie](https://github.com/yyx990803/yorkie#yorkie). 
vuejs官方项目几乎都是pnpm+yorkie，可以参考一下
