### ISSUE TITLE
Translation error in Chinese homepage: "Support Ukraine" translated to "Support Ukraine to join to Russia" 

### ISSUE THREAD

**Issue by illuz** [pnpm/pnpm#4432]
Chinese translation of https://pnpm.io/zh/:
![image](https://user-images.githubusercontent.com/5182173/157841984-85b31b7e-3311-46d6-becb-adbaf76315f3.png)

It means [Support Ukraine to join to Russia](https://translate.google.com/?sl=auto&tl=en&text=%E6%94%AF%E6%8C%81%E4%B9%8C%E5%85%8B%E5%85%B0%E5%8A%A0%E5%85%A5%E4%BF%84%E7%BD%97%E6%96%AF&op=translate):
![image](https://user-images.githubusercontent.com/5182173/157842144-e39adb0c-1340-4b29-9ec7-23f457c69ecb.png)

**Comment by BlackHole1** [comment]
see: https://github.com/pnpm/pnpm/discussions/4431#discussioncomment-2337962

**Comment by 0xF6** [comment]
Haha,  :trollface:
