### ISSUE TITLE
publish should not pack internal tarball within final tarball

### ISSUE THREAD

**Issue by loynoir** [pnpm/pnpm#4438]
### pnpm version:
6.32.3

### Code to reproduce the issue:

```sh
$ pnpm publish
=== Tarball Contents ===
xxx kB real-source-file2
xxx kB real-source-file1
...
xxx kB foobar-1.0.0.tgz
```

### Expected behavior:
npm publish will not publish internal tarball
```sh
$ npm publish
$ cd xxx
$ pnpm i foobar
$ ls node_modules/foobar/foobar-1.0.0.tgz
ENOENT
```

### Actual behavior:
```sh
$ pnpm publish
$ cd xxx
$ pnpm i foobar
$ ls node_modules/foobar/foobar-1.0.0.tgz
node_modules/foobar/foobar-1.0.0.tgz
```

### Additional information:

 - `node -v` prints: v16.13.2
 - Windows, macOS, or Linux?: Linux

**Comment by loynoir** [comment]
Was fixed by adding `.files` field.

Closing, can not reproduce again.

**Comment by soeasyjx** [comment]
I've always had this problem

### node
v20.10.0

### pnpm
8.12.0
