### ISSUE TITLE
Why not just remove the node_modules folder?

### ISSUE THREAD

**Issue by Baiyuetribe** [pnpm/pnpm#4443]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

`pnpm` solves the problem of repeatedly installing node environment packages, but it doesn't save much space, because each new project needs to reoccupy space. Why can't we share dependency packages like python or golang? Why can't you just remove node_modules?
`pnpm`解决了重复安装node环境包，但是并没有节省多少空间，因为每次新项目都需要重新占用空间。为什么不能像python或golang那样共用依赖包？为什么就不能移除node_modules呢？

Expectations（期望）：
Remove node_modules from the project at the root, and all projects share local dependencies, just like python or golang.
从根源上移除项目里的node_modules，所有项目共用本地的依赖包，就像python或golang那样。

**Comment by zkochan** [comment]
It does not reoccupy space. The files inside node_modules are hard links to files in the content-addressable store. They do not occupy additional space. If you install a package in two projects, the package will not occupy additional space in the second project.

**Comment by Baiyuetribe** [comment]
No matter how many projects I reopen, they still take up space under the new project
![image](https://user-images.githubusercontent.com/43716063/158991384-f556da67-11da-4fe0-8248-aa108470965b.png)
I think the `pnpm` tool just omits the cloud download and doesn't address the root of the space footprint problem. Why build the wheel over and over again? Why not go to the root of the `node_modules` problem? Why not make a centralized shared package?

**Comment by zkochan** [comment]
Right, but this disk space is the same as the disk space in the pnpm store.

See this:
https://unix.stackexchange.com/questions/88423/why-do-hard-links-seem-to-take-the-same-space-as-the-originals
