### ISSUE TITLE
`pnpm dlx`  npmrc config `store-dir` not working

### ISSUE THREAD

**Issue by cpp233** [pnpm/pnpm#4444]
### Code to reproduce the issue:

`pnpm dlx` run some package

### Expected behavior:
Expected use npmrc config `store-dir=~/TEMP/.pnpm-store`
```bash
pnpx axios
```
output
```
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: Z:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
```
### Actual behavior:
```bash
pnpm dlx axios
```
output
```
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\XXXXX\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
```
npmrc config `store-dir` not working when use `pnpm dlx`, only working at `pnpx`

### Additional information:

 - `node -v` prints:v16.14.0
 - Windows, macOS, or Linux?:Windows 10

**Comment by zkochan** [comment]
Was this solved?
