### ISSUE TITLE
Support libc field in package.json

### ISSUE THREAD

**Issue by yisibl** [pnpm/pnpm#4454]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
Some packages (SWC, sharp, @napi-rs/canvas) publish native packages for both `glibc` and `musl`. At the moment users need to install both versions, as there is no conditional differentiator as for os and cpu.

Currently [yarn 3.2+](https://github.com/yarnpkg/berry/pull/3981) and [cnpm](https://github.com/cnpm/npminstall/pull/387) have implemented the libc field, the npm implementation is [still under discussion](https://github.com/npm/rfcs/pull/519).

**Comment by zkochan** [comment]
Sounds good.

**Comment by yisibl** [comment]
One difference between the yarn and cnpm implementations is that yarn gets the `LibcFamily` through `process.report`, while cnpm gets it through the detect-libc package.

https://github.com/cnpm/npminstall/pull/388

`process.report` is not very compatible and depends on the Node.js version, while detect-libc does not have this problem.
