### ISSUE TITLE
[dev] can't find module @pnpm/cli-meta

### ISSUE THREAD

**Issue by HomyeeKing** [pnpm/pnpm#4464]
I'm trying to look through the source code follows the `CONTRIBUTING` guide, and using `spnpm` to do a quick check, but I encounter some problem these days

### pnpm version:
7.0.0-alpha.2

### Code to reproduce the issue:

- go to pnpm root dir
- run ` node packages/pnpm/spnpm -v`

you will get the error shows can't find module `Cannot find module <USER_ROOT>/pnpm/packages/pnpm/node_modules/@pnpm/cli-meta/lib/index.js`

maybe the pnpm@7 has some install problem

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
Have you executed `pnpm install` before doing running `spnpm`?

**Comment by HomyeeKing** [comment]
of course, I've tried many times
