### ISSUE TITLE
hidden modules disappear after running pnpm link <dir>

### ISSUE THREAD

**Issue by miqdadfwz** [pnpm/pnpm#4467]
Actually idk it is an intended design or actual bug: After running `pnpm link <dir>` in workspace, somehow `node_modules/.pnpm/node_modules` is gone, in my case it is causing the application breaks as some modules may still depend to `node_modules/.pnpm/node_modules`. I know it can be hoisted to root `node_modules` using `public-hoist-pattern` but my repository is very huge and complex, identifying which modules that have phantom dependencies and manually hoist to public is not worth of our effort. Re-running `pnpm install` restore the hidden modules though, but it makes the link breaks.

I have provided the minimum repository to reproduce the issue. You can run the unit test to validate whether the issue occurs, the test will fail if `node_modules/.pnpm/node_modules` does not exist.

### pnpm version:
6.32.3

### Code to reproduce the issue:
https://github.com/miqdadfwz/temp-pnpm-test-link

1. Open the repository run `pnpm install`
2. Run `pnpm run test`, the test case should be passed.
3. Go to packages/pkg-1, and link any deps defined in its package.json. In my case I have `@lite-v3/polyfills` already downloaded in my machine, so I simply run `pnpm link path/to/@lite-v3/polyfills`. 
4. Run `pnpm run test` from the root, the test case should be failed.

### Expected behavior:
`node_modules/.pnpm/node_modules` should not disappear. 

### Actual behavior:
`node_modules/.pnpm/node_modules` disappear. 

### Additional information:

 - `node -v` prints: v14.18.2
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
This is fixed in pnpm v7 probably via https://github.com/pnpm/pnpm/pull/4641
