### ISSUE TITLE
pnpm install stuck 

### ISSUE THREAD

**Issue by wael-fadlallah** [pnpm/pnpm#4470]
### pnpm version:
6.32.3
### Code to reproduce the issue:
pnpm install

### Expected behavior:
Installing the packages 
### Actual behavior:
Nothing, it just stuck 
### Additional information:
I have tried to upgrade to the latest version but still same issue 
 - `node -v` prints: v16.13.2 
 - Windows, macOS, or Linux?: windows 11

**Comment by zkochan** [comment]
Do you have s repository that reproduces the issue?

**Comment by wael-fadlallah** [comment]
yes, it https://github.com/faker-js/faker

**Comment by zkochan** [comment]
Seems to work for me.

Run `pnpm install --reporter ndjson` and post the last lines in the output where it gets stuck.

**Comment by wael-fadlallah** [comment]
it just decide to work :), I didn't do anything specific
