### ISSUE TITLE
Top level workspaces are not supported

### ISSUE THREAD

**Issue by alshdavid** [pnpm/pnpm#4472]
### Code to reproduce the issue:

[project.zip](https://github.com/pnpm/pnpm/files/8337374/project.zip)

```yaml
packages:
  - ./package-a
  - ./package-b
  - ./shared
```

### Expected behavior:

Packages on the top level would be linked

### Actual behavior:

Top level packages are ignored however when moving the packages to `packages` folder, it works fine
```yaml
packages:
  - ./packages/**
```

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
This `pnpm-workspace.yaml` will work:

```yaml
packages:
  - '*'
```
