### ISSUE TITLE
Create a package-lock.json file from pnpm-lock.yaml

### ISSUE THREAD

**Issue by frank-dspeed** [pnpm/pnpm#4485]
### Discussed in https://github.com/pnpm/pnpm/discussions/3367

<div type='discussions-op-text'>

<sup>Originally posted by **maclanzallamas** April 19, 2021</sup>
It's clear how to do this the other way around with pnpm import (https://pnpm.io/cli/import)
But if I wanted to migrate from pnpm to npm, how do I use the _pnpm-lock.yaml_ to create a _package-lock.json_ file?

Similar question: https://github.com/pnpm/pnpm/discussions/3356

Thanks</div>

In the original discussion i replyed that it would be possible to shim pnpm's workspace features with npm workspaces and overrieds
so to get pnpm and npm compatible workspaces it would be nice if there would be 

a function that converts your pnpm-workspace.yml and pnpm-lock.yml into the right package.json filds (workspaces and overrides) and also package-lock.json.

## Why?
It is simply a clever thing to be compatible just in case that it is needed in both directions. Also the developer should choose which package manager fits best in his environment it is not a thing that a package or repo should enforce there exist solutions like
package.json hooks that do exit if npm install gets used to force pnpm and so on

that is simply bad behavior that should get stoped. It leads to ecosystem fragmentation.

the secund reason to go into this direction is that pnpm if it should get deprecated as package manager could still perform its magic via the package.json and drop the none needed code parts.

would also fit more into plugAndPlay Package Manager philosophie.

**Comment by frank-dspeed** [comment]
Are you open to support that should i make a PR that enables pnpm to act as lib that enforces package.json config and lock adjustments?

**Comment by zkochan** [comment]
> Also the developer should choose which package manager fits best in his environment it is not a thing that a package or repo should enforce there exist solutions like
package.json hooks that do exit if npm install gets used to force pnpm and so on

There is a consensus between package manager maintainers of Yarn/npm/pnpm that a project should pick one package manager and all developers should use that package manager. It doesn't make sense to allow users to pick random package managers on random projects. The results will be nondeterministic.

Regarding creating a `package-lock.json`, I don't understand why pnpm would implement it. This is something that needs to be implemented in npm. An `npm import` command that would create a `package-lock.json` file from a `pnpm-lock.yaml` file. It is in their interest to make it easier for developers to migrate a project from pnpm to npm.

**Comment by frank-dspeed** [comment]
@zkochan thanks for that statement i now got your philosophie good to know. So short answer is No Interrest. I wish your Project good luck then.

**Comment by ahmedya63** [comment]
كيف الاستخدام
