### ISSUE TITLE
 pnpm env use --global 14 in M1

### ISSUE THREAD

**Issue by yuler** [pnpm/pnpm#4489]
### Code to reproduce the issue:

```bash
pnpm env use --global 14 
```
### Expected behavior: 

Download node v14.x

### Actual behavior:

The download URL is output is `https://nodejs.org/download/release/v14.19.1/node-v14.19.1-darwin-arm64.tar.gz`, it will be 404

The correct URL should be  `https://nodejs.org/download/release/v14.19.1/node-v14.19.1-darwin-x64.tar.xz`

### Additional information:

 - Windows, macOS, or Linux?: Mac M1

**Comment by lawvs** [comment]
> For Macs with the M1 chip, node started providing arm64 arch darwin packages since v16.0.0. For earlier versions, there were only darwin_x64 packages available but no darwin_arm64.

There is a workaround:

```zsh
_ arch -x86_64 zsh
pnpm env use --global 14 
```

And may need to run the terminal with [Rosetta](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment).

**Comment by callumlocke** [comment]
I tried the workaround suggested by @lawvs but it didn't work for me. 

I ran Terminal with Rosetta, then I did `arch -x86_64 zsh` (and then ran `arch` again to confirm - it outputs `arm64`), then I ran `node -p process.arch`, but it outputs `arm64`, not `x64`. (I did try running the `pnpm env use --global 14` afterwards anyway, but that just results in a 404 as usual.)

**Comment by callumlocke** [comment]
OK I just figured out my own workaround, using brew as a middle-man. This installs an arm64 build of the latest Node 14 (no Rosetta needed) and leaves no mess afterwards.

### Step by step

1. Temporarily install Node 14 with Homebrew:
	- `brew install node@14`
2. Copy it to where pnpm keeps its node versions:
	- `cp -R $(brew --cellar node@14)/. ~/Library/pnpm/nodejs/`
3. Uninstall brew's version:
	- `brew uninstall node@14`

Now `pnpm env use --global 14` should work.

### One-liner

```sh
brew install node@14 && cp -R $(brew --cellar node@14)/. ~/Library/pnpm/nodejs/ && brew uninstall node@14
```

**Comment by autumnblazey** [comment]
hm... I feel pnpm could add support for something like this for arm64 Darwin, doing something like if the version is less than 16.x.x, then install the x64 version of node and let the user know that it did that and why. Printing a warning/info message like this maybe:

```
WARN Installed x64 version of node. Rosetta is required to run it, you can install it by running `softwareupdate --install-rosetta` [I believe this is the right command?]. Node started providing arm64 versions of node starting with v16.
```
