### ISSUE TITLE
Allow pnpm install --filter to install dependencies of workspace dependencies

### ISSUE THREAD

**Issue by ericmatthys** [pnpm/pnpm#4493]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

When needing to build an app in a monorepo, filtering the `pnpm install` could speed up build times, but currently dependencies of dependent workspace packages are not also installed.

Consider 3 packages in a monorepo: A, B, and C. Package C has a dependency like `"workspace:A": "*"` in its `package.json`. `pnpm install` would install dependencies of both A and C without needing to express that directly in the command (just `pnpm install --filter C`).

**Describe the solution you'd like**

An additional option could be added to respect the workspaces dependency tree, installing packages for all workspace dependencies of the filtered packages. This would be similar to https://turborepo.org/docs/reference/command-line-reference#--include-dependencies.

`pnpm install --filter C --include-dependencies`

**Describe the drawbacks of your solution**

This requires understanding the dependencies between workspace packages. Particular care may need to be considered with circular dependencies.

**Describe alternatives you've considered**

This could be considered default behavior without the option. I originally expected it to work this way. Although such a change might be considered breaking.

**Comment by kenrick95** [comment]
That is already achievable using `--filter C...`

**Comment by ericmatthys** [comment]
Whoops I missed that in the docs. Thanks!
