### ISSUE TITLE
Site https://pnpm.io not working

### ISSUE THREAD

**Issue by polRk** [pnpm/pnpm#4498]
<img width="1016" alt="Снимок экрана 2022-03-29 в 18 09 59" src="https://user-images.githubusercontent.com/39828645/160644102-d95b34b3-1cd8-4ec0-a1d6-e52ec65cb7ad.png">

**Comment by zkochan** [comment]
I live in Ukraine and I have blocked all traffic from Russian Federation and Belarus.

**Comment by polRk** [comment]
Rat

**Comment by zkochan** [comment]
The Russians and Belarusians have helped me enough already.
