### ISSUE TITLE
error GET https://registry.npmmirror.com/commitizen error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.

### ISSUE THREAD

**Issue by owen1011** [pnpm/pnpm#4500]
### Code to reproduce the issue:

i am set the registry to https://registry.npm.taobao.org/, but when i exec pnpm install, they warn GET https://registry.npmmirror.com/commitizen error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.

why pnpm still download package to https://registry.npmmirror.com/ ?

### Additional information: 

 - `node -v` prints: v16.13.2
 - Windows, macOS, or Linux?: windows11 wsl2

**Comment by BlackHole1** [comment]
see: https://npmmirror.com/

<img width="559" alt="图片" src="https://user-images.githubusercontent.com/8198408/160739519-28b4fd09-6de4-41b4-ac90-5989b84da7a3.png">

**Comment by BlackHole1** [comment]
https://zhuanlan.zhihu.com/p/465424728

<img width="743" alt="图片" src="https://user-images.githubusercontent.com/8198408/160739646-eecd6f7f-fe22-4749-935a-d7deea2bf672.png">

**Comment by deadcoder0904** [comment]
disabling cloudflare warp solved it for me as i updated it today.
