### ISSUE TITLE
Add an environment variable for scripts to be able to detect when `pnpm` executes them

### ISSUE THREAD

**Issue by illright** [pnpm/pnpm#4506]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As an init script developer, I want to be able to detect when my script is run with `pnpm` to offer the users a personalized initialization experience, but the best I can currently do is to ask which package manager does the user prefer, even though the preference is clearly indicated in the command that initiated the runner

**Describe the solution you'd like**

Set an environment variable like `PNPM_INITIATED=true` for all scripts run through `pnpm dlx`, `pnpm exec` and `pnpm create`

**Describe the drawbacks of your solution**

We might face collisions with custom environment variables, although it is extremely unlikely with the proposed variable name.

**Describe alternatives you've considered**

As a script developer, I could check if `pnpm` is present on the user's `PATH`, but even if it is, that doesn't mean the user prefers `pnpm`.

**Comment by zkochan** [comment]
There is already such environment variable: `npm_config_user_agent`. If it is not set correctly by some commands, then it should be fixed.

**Comment by illright** [comment]
Oh, I see. Yes, seems like all these commands set it correctly. Thanks for the heads up!
