### ISSUE TITLE
run only one single test

### ISSUE THREAD

**Issue by milahu** [pnpm/pnpm#4509]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

when writing tests for pnpm, i want to run only one test
`jest` allows this with the `-t` option (`--testNamePattern`)

```
$ pnpm run test:jest --help

  -t, --testNamePattern             Run only tests with a name that matches the
                                    regex pattern.                      [string]
```

**Describe the solution you'd like**

```sh
cd packages/pnpm
pnpm run _test -t 'bin files are found by lifecycle scripts'
```

**actual result**

`run-p` does not pass arguments to `jest` = upstream issue https://github.com/mysticatea/npm-run-all/issues/126

<details>

```
$ pnpm run _test -- --runTestsByPath test/install/misc.ts -t 'bin files are found by lifecycle scripts'
 
> pnpm@7.0.0-beta.2 _test /tmp/pnpm/packages/pnpm
> cross-env PNPM_REGISTRY_MOCK_PORT=7780 pnpm run test:e2e "--" "--runTestsByPath" "test/install/misc.ts" "-t" "bin files are found by lifecycle scripts"


> pnpm@7.0.0-beta.2 test:e2e /tmp/pnpm/packages/pnpm
> registry-mock prepare && run-p -r registry-mock test:jest "--" "--runTestsByPath" "test/install/misc.ts" "-t" "bin files are found by lifecycle scripts"


> pnpm@7.0.0-beta.2 test:jest /tmp/pnpm/packages/pnpm
> jest


> pnpm@7.0.0-beta.2 registry-mock /tmp/pnpm/packages/pnpm
> registry-mock
```

</details>

**Describe the drawbacks of your solution**

(implementation cost)

**Describe alternatives you've considered**

1\. `jest --watch` will re-run all tests in the test file `test/install/misc.ts`

2\. use `pnpm run test:jest -- test/install/misc.ts` to filter by test file

3\. in the test file `test/install/misc.ts`, remove all unwanted tests
= remove all tests except `bin files are found by lifecycle scripts`

4\. bash script

```sh
#! /bin/sh
(
  set -x
  export PNPM_REGISTRY_MOCK_PORT=7780
  if (nc -v -z 127.0.0.1 $PNPM_REGISTRY_MOCK_PORT)
  then
    echo verdaccio is running
  else
    echo starting verdaccio; pnpm run registry-mock prepare && pnpm run registry-mock &
    sleep 5; echo started verdaccio
  fi
  pnpm run test:jest --testNamePattern "^bin files are found by lifecycle scripts$"
)
```

this will run `jest --testNamePattern "^bin files are found by lifecycle scripts$"`
but jest ignores the pattern and runs all tests

maybe we should use `describe('...')` and `it('...')` for jest?

**Comment by milahu** [comment]
this works

```diff
-test('bin files are found by lifecycle scripts', () => {
+test.only('bin files are found by lifecycle scripts', () => {
```

```
pnpm run test:jest -- test/install/misc.ts
```

via [stackoverflow](https://stackoverflow.com/a/42828586/10440128)

**Comment by zkochan** [comment]
in pnpm v7 it works without `--`

**Comment by milahu** [comment]
yes ... the `--` is an argument for jest, all arguments after `--` are a testPathPattern

so these have the same effect

```
pnpm run test:jest -- test/install/misc.ts
pnpm run test:jest --testPathPattern test/install/misc.ts
```
