### ISSUE TITLE
[7.x] missing files in `file:` deps

### ISSUE THREAD

**Issue by farfromrefug** [pnpm/pnpm#4510]
### Code to reproduce the issue:

add a `file:` dependency with files like `aar` (is it really that ?)

### Expected behavior:

go into `node_modules/your_dep` and see the exact same files as the original location

### Actual behavior:

Should mention first that it works correctly with 6.x with the exact same config. I tried back an forth after removing node_modules and pnpm lock) 

Files are missing as shown here (left original dir, right node_modules dir)
<img width="1228" alt="Screenshot 2022-03-31 at 14 15 05" src="https://user-images.githubusercontent.com/655344/161052868-c3b296ac-9129-46d0-a196-07a931259328.png">

### Additional information:

 - `node -v` prints: v17.6.0
 - Windows, macOS, or Linux?: macos

**Comment by zkochan** [comment]
Are those files included in the package? This will happen if those files are in `.npmignore`. Or you list files in package.json and don't include those that are missing

**Comment by farfromrefug** [comment]
@zkochan indeed those files are in .npmignore.
my first question is if it is a hard link shouldn t those files be present?
could we have a setting for npmignore to be ignored for file: protocol?

**Comment by zkochan** [comment]
> my first question is if it is a hard link shouldn t those files be present?

Each file is hard linked separately. Those files are not hard linked because they are not part of the package.

> could we have a setting for npmignore to be ignored for file: protocol?

No, if you need those files, they need to be part of the package.

Alternatively, you may use the `link:` protocol, which will create a symlink to the package directory.

**Comment by farfromrefug** [comment]
@zkochan That s a bit tough. I need those files but i need them only locally :s and i dont want them to be published (like it was with 6.x).
as for `link:` the issue is that it does not seem to be compatible with `npm`. I tried but `npm does not recognise it.

**Comment by zkochan** [comment]
Why do you need support of `link:` by npm? Both the file and link protocol are used for local development.

**Comment by farfromrefug** [comment]
@zkochan because if those file are commited on git, other user need to be able to use this with `npm`. `file:` does this. And btw i think with `file:` and `npm`  i would see all the files inside that dir.
I understand what you did, for me `npmignore` is only for packaging and publishing, seems weird to have any local influence.

**Comment by farfromrefug** [comment]
@zkochan thanks a lot for hearing me on this! really loving `pnpm`!
