### ISSUE TITLE
pnpm v7 lock file unexpected changes

### ISSUE THREAD

**Issue by fz6m** [pnpm/pnpm#4523]
### pnpm version:

7.0.0-rc.2

### Code to reproduce the issue:

In pnpm v7 version, `strict-peer-dependencies` is set to `true` by default.

I try install some dep, the peer deps error was triggered and the dep was not installed successfully (`package.json` not change), but the pnpm lock file `pnpm-lock.yaml` was changed.

Is the pnpm lock file changed as expected ?

### Additional information:

 - `node -v` prints: `v16.14.1`
 - Windows, macOS, or Linux?: `macOS`

**Comment by fz6m** [comment]
I create a reproduce repo:

https://github.com/MoeYc/pnpm-v7-bug

execute:

```bash
git clone https://github.com/MoeYc/pnpm-v7-bug.git
cd pnpm-v7-bug

# install dep
pnpm i

# install dep to sub project
cd ./packages/plugins
pnpm add -D @types/react-redux 
```

then, dep did not install successfully, but the pnpm lock file `pnpm-lock.yaml` has changed

**Comment by zkochan** [comment]
This is expected. Just install the missing peer dependency and the lockfile will be updated again and the install will exit fine.
