### ISSUE TITLE
PNPM silently dies when accidently installing non-JS repos

### ISSUE THREAD

**Issue by isaac-mcfadyen** [pnpm/pnpm#4530]
### pnpm version:
6.32.4

### Code to reproduce the issue:
- Run `pnpm install <url>` where URL is the URL of any GitHub repository that doesn't have a package.json.
- For example, https://github.com/uNetworking/uWebSockets (that is the non-JS version so there's no package.json).

### Expected behavior:
- PNPM throws an error or otherwise tells the user of their mistake.
### Actual behavior:
- PNPM downloads the GitHub repository then silently fails with no error message or other logs.
### Additional information:

 - `node -v` prints: v17.8.0
 - Windows, macOS, or Linux?: macOS (Apple Silicon)

**Comment by mcmxcdev** [comment]
I cannot reproduce this with pnpm v7.5.0:

```
$ pnpm i https://github.com/uNetworking/uWebSockets
Packages: +1
+

dependencies:
+ uWebSockets 0.0.0

Progress: resolved 2, reused 1, downloaded 1, added 1, done
```

It also adds an entry to the `package.json` dependencies like this:

`"uWebSockets": "github:uNetworking/uWebSockets"`

**Comment by zkochan** [comment]
This was fixed.
