### ISSUE TITLE
package.json already exists

### ISSUE THREAD

**Issue by finnsnape** [pnpm/pnpm#4537]
### Code to reproduce the issue:
`pnpm init svelte@next svelteKit-example-app`

### Expected behavior:
Creates test app for svelte

### Actual behavior:
>ERR_PNPM_PACKAGE_JSON_EXISTS  package.json already exists

### Additional information:
I tried uninstalling `pnpm` by running `rm -rf /usr/local/bin/pnpm` and `rm -rf /home/finn/.local/share/pnpm` since I could not uninstall it normally #4536

Instead installed it via npm after updating node

 - `node -v` prints: v16.14.2
 - Windows, macOS, or Linux?: PopOS 21.10

**Comment by zkochan** [comment]
You were running the wrong command. You need to run:

```
pnpm create svelte@next svelteKit-example-app
```
