### ISSUE TITLE
pnpm auto exited in github actions when lock file is not update

### ISSUE THREAD

**Issue by zhangyuang** [pnpm/pnpm#4547]
### pnpm version:

6.x

### Code to reproduce the issue:

https://github.com/zhangyuang/ssr/blob/feat/pnpm/.github/workflows/ci.yml

### Expected behavior:

With no update pnpm-lock, github action can auto skip pnpm i and go to next job but not exited 

### Actual behavior:

throw error cause process exited

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/17424434/162661721-e472e2dc-778c-4c61-a704-c6ba057a771d.png">

### Additional information:

 - `node -v` prints: node12
 - Windows, macOS, or Linux?:
all operating system

**Comment by kenrick95** [comment]
Looks like you didn't pass `--no-frozen-lockfile`

https://pnpm.io/cli/install#--frozen-lockfile

`--frozen-lockfile` is by default `true` on CI environment

**Comment by zkochan** [comment]
This works as expected. You need an up-to-date lockfile to run the installation in CI. If you don't like this behavior, explicitly set `frozen-lockfile` to false.
