### ISSUE TITLE
No projects matched the filters on Windows

### ISSUE THREAD

**Issue by felix-cao** [pnpm/pnpm#4562]
I had the same error, but can't solve it .
and can work successfully on macOS. 

`Environment`
OS: Windows 10 Pro
nodejs: V17.0.0
npm: V8.6.0
pnpm: V6.32.6
gitbash:  git version 2.31.1.windows.1 (Same on powershell)

code : https://github.com/superfreeeee/Blog-code/tree/main/front_end/package/pnpm_workspace

`error`
```bash
$ pnpm start

> mono@1.0.0 start C:\code\vue\mono
> pnpm run start --filter '*'

No projects matched the filters in "C:\code\vue\mono"
```

Thanks!

**Comment by kenrick95** [comment]
If your intention is to match all packages, calling it with `--recursive` and without `--filter` is the way to go

**Comment by felix-cao** [comment]
@kenrick95 
Thanks! handsome chinese man!

**Comment by macarole** [comment]
最近一直遇到这个问题，无论是mac，还是windows 10 都遇到这个问题，差点都不想用pnpm了，都想转回lerna了，今天打算再折腾折腾看看，无意中发现这个问题：
之前我的pnpm-workspace.yaml文件是这么写的：
`
packages: -`packages/*`
  -`!**/test/**`

`
你能发现有什么问题嘛？
没错，我的- 和后面的内容之间没有加任何空格，然后vscode自动格式化成这样。这个时候就不停的报no projects matched the filter 之类的问题了，这让我纠结了很久。
然后我加了空格，就开始报ad indentation of a sequence entry 这个错误，虽然还是再报错，可是我已经很开心了，居然不是no projects matched 那个bug了，看来有门。然后我又去官方文档
看到他里面的pnpm-workspace.yaml是这么写的：
`
packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
`
这下居然正常了！！！！正常了！！！

这是什么问题呢？仔细观察，后面我才发现，是那个**空格**，还有那个**字符串**的问题，坑啊

**Comment by BarrySong97** [comment]
> 最近一直遇到这个问题，无论是mac，还是windows 10 都遇到这个问题，差点都不想用pnpm了，都想转回lerna了，今天打算再折腾折腾看看，无意中发现这个问题： 之前我的pnpm-workspace.yaml文件是这么写的：
> 
> ```json
> packages: -`packages/*`
>   -`!**/test/**`
> ```
> 
> 你能发现有什么问题嘛？ 没错，我的- 和后面的内容之间没有加任何空格，然后vscode自动格式化成这样。这个时候就不停的报no projects matched the filter 之类的问题了，这让我纠结了很久。 然后我加了空格，就开始报ad indentation of a sequence entry 这个错误，虽然还是再报错，可是我已经很开心了，居然不是no projects matched 那个bug了，看来有门。然后我又去官方文档 看到他里面的pnpm-workspace.yaml是这么写的：
> 
> ```json
> packages:
>   # all packages in direct subdirs of packages/
>   - 'packages/*'
>   # all packages in subdirs of components/
>   - 'components/**'
>   # exclude packages that are inside test directories
>   - '!**/test/**'
> ```
> 
> 这下居然正常了！！！！正常了！！！
> 
> 这是什么问题呢？仔细观察，后面我才发现，是那个**空格**，还有那个**字符串**的问题，坑啊
> 
> 哈哈，又可以愉快的玩耍了

666666666666, you saved my day!!!!

**Comment by bittermeatball** [comment]
> 最近一直遇到这个问题，无论是mac，还是windows 10 都遇到这个问题，差点都不想用pnpm了，都想转回lerna了，今天打算再折腾折腾看看，无意中发现这个问题： 之前我的pnpm-workspace.yaml文件是这么写的：
> 
> ```json
> packages: -`packages/*`
>   -`!**/test/**`
> ```
> 
> 你能发现有什么问题嘛？ 没错，我的- 和后面的内容之间没有加任何空格，然后vscode自动格式化成这样。这个时候就不停的报no projects matched the filter 之类的问题了，这让我纠结了很久。 然后我加了空格，就开始报ad indentation of a sequence entry 这个错误，虽然还是再报错，可是我已经很开心了，居然不是no projects matched 那个bug了，看来有门。然后我又去官方文档 看到他里面的pnpm-workspace.yaml是这么写的：
> 
> ```json
> packages:
>   # all packages in direct subdirs of packages/
>   - 'packages/*'
>   # all packages in subdirs of components/
>   - 'components/**'
>   # exclude packages that are inside test directories
>   - '!**/test/**'
> ```
> 
> 这下居然正常了！！！！正常了！！！
> 
> 这是什么问题呢？仔细观察，后面我才发现，是那个**空格**，还有那个**字符串**的问题，坑啊
> 
> 哈哈，又可以愉快的玩耍了

Thanks, this works, it happens when i use this (NOT WORKING)
![image](https://user-images.githubusercontent.com/46400321/192107622-753a637f-8f60-48ae-b0b4-e9f071225287.png)
Instead of this (WORKING)
![image](https://user-images.githubusercontent.com/46400321/192107628-0dfbeead-6b77-4534-8102-3234c487912b.png)

Apparently you don't need to specify every single packages, just need to declare the top-level directory

**Comment by JoeZhangHao** [comment]
还有可能有一个问题，在 package.json 中的 script 写 --filter 时，必须用转义的双引号，mac 上就不会出现问题
``` json
"build:cli": "pnpm --filter \"{cli/**}\" build"
```

**Comment by HuoJian666** [comment]
问题解决！赞！

**Comment by START-TO** [comment]
可能是这个原因：
--filter Test 的参数(Test) 和对应子项目的package.kson 的name (test)不一致 ，
package.json 的name 字段需要小写，我们的子项目目录名可能是首字母大写的，可以尝试 --filter  Test --> --filter test
