### ISSUE TITLE
pnpm is ignoring settings in package.json and commands don't update the file

### ISSUE THREAD

**Issue by pgr3931** [pnpm/pnpm#4577]
### pnpm version: 7.0.0-rc.4

pnpm is ignoring `peerDependencyRules` in package.json.
VSCode is also showing npm warnings in package.json from time to time, stating that a module is not installed.
When I use `pnpm remove <pkg>`, then the package.json is not updated accordingly 

The packages and the installation work fine, but I would like to get rid of those console erros.
I'm sure I just missed a config or something similar.

.npmrc file only has proxy settings
npm is still installed

### Code to reproduce the issue:
package.json

```json

{
  "name": "-",
  "version": "0.1.0",
  "private": true,
  "pre-commit": "lint",
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "react": "18"
      },
      "ignoreMissing": [
        "bootstrap",
        "devextreme"
      ]
    }
  },
  "scripts": {
    "dev": "vite",
    "build": "tsc --noEmit && vite build",
    "preview": "vite preview",
    "lint:fix": "eslint ./src --ext .jsx,.js,.ts,.tsx --quiet --fix",
    "lint:format": "prettier --loglevel warn --write \"./**/*.{js,jsx,ts,tsx,css,md,json}\" ",
    "lint": "pnpm run lint:format && pnpm run lint:fix ",
    "type-check": "tsc",
    "analyze:bundle": "source-map-explorer 'build/static/js/*.js'"
  },
  "dependencies": {
    "@mantine/core": "^4.1.2",
    "@mantine/hooks": "^4.1.2",
    "@mantine/modals": "^4.1.2",
    "@mantine/notifications": "^4.1.2",
    "@mantine/spotlight": "^4.1.2",
    "ace-builds": "^1.4.14",
    "axios": "^0.26.1",
    "bootstrap": "^4.6.1",
    "dayjs": "^1.11.0",
    "devextreme": "^21.2.6",
    "devextreme-react": "^21.2.6",
    "html-react-parser": "^1.4.9",
    "react": "^18.0.0",
    "react-ace": "^9.5.0",
    "react-dom": "^18.0.0",
    "react-icons": "^4.3.1",
    "react-router-dom": "^6.2.2",
    "react-scripts": "^5.0.0",
    "react-use": "^17.3.2"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.4",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.1",
    "@types/jquery": "^3.5.14",
    "@types/node": "^17.0.22",
    "@types/react": "^18.0.2",
    "@types/react-dom": "^18.0.0",
    "@types/react-router-dom": "^5.3.3",
    "@types/signalr": "^2.2.37",
    "@typescript-eslint/eslint-plugin": "^5.19.0",
    "@typescript-eslint/parser": "^5.19.0",
    "@vitejs/plugin-react": "^1.3.1",
    "eslint": "^8.13.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "pre-commit": "^1.2.2",
    "prettier": "^2.6.1",
    "react-test-renderer": "^17.0.2",
    "source-map-explorer": "^2.5.2",
    "typescript": "^4.6.2",
    "vite": "^2.9.4",
    "vite-tsconfig-paths": "^3.4.1"
  }
}
```

### Expected behavior:

pnpm should update package.json if `pnpm remove <pkg>` is used in cmd

pnpm should ignore missing peer dependencies, if the package is included in `ignore missing`

```json
"ignoreMissing": [
        "bootstrap",
        "devextreme"
      ]
```

### Actual behavior:

When using `pnpm remove <pkg>` , the entry in package.json is not removed

When using `pnpm add bootstrap` for example, the output is as follows:

bootstrap
│ ├── ✕ missing peer jquery@"1.9.1 - 3"
│ └── ✕ missing peer popper.js@^1.16.1

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: Windows
 - I'm using CMD as console

**Comment by zkochan** [comment]
These settings are ignored unless they are in the root package.json. So if it is a workspace, the pnpm field should be in the root package.json's pnpm field.

**Comment by pgr3931** [comment]
We don't use workspaces and each project only has one package.json file, which is in the root of the project.

A thing that came to mind: We set the `root` in the `vite.config.ts` file to 'src'. Could this have an impact?

The issue about vscode showing warnings in the package.json file was due to a plugin I had installed and can be ignored.

**Comment by pgr3931** [comment]
Just reverted back to version 6.32.8 and everything works fine now. Gonna wait for an official release of version 7 before trying again.

**Comment by Hebilicious** [comment]
Can confirm I add the same issue with pnpm7 rc-6, reverting back to 6.32.9 fixes it (node 16, macOS)

**Comment by zkochan** [comment]
>When using pnpm add bootstrap for example, the output is as follows:
>
>bootstrap
>│ ├── ✕ missing peer jquery@"1.9.1 - 3"
>│ └── ✕ missing peer popper.js@^1.16.1

This is expected. If you want to ignore these errors, you need to add `jquery` and `popper.js` to the `ignoreMissing` list. Not `bootstrap`.

**Comment by pgr3931** [comment]
You're right, I noticed this too after switch to version 6.32.8 and updated the file accordingly. Shall I update the initial post too?

Still, it seems like pnpm can't find the package.json file, since adding or removing packages doesn't update the dependencies section. The allowed versions are also ignored.

Although `pnpm install` works fine and all packages are installed as expected.
