### ISSUE TITLE
Almost v1. Any breaking changes that needs to be done?

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#458]
Seems like almost everything is done for bumping the version to 1.

Do we need to make some breaking changes before that?

The most frequent breaking changes were related to the store structure. So I'd like to review the store structure before moving to v1. Maybe we can make it better structured for humans. And also I am afraid it currently does not create unique folder names in some rare cases (like when packages with the same name are downloaded from different registries)

* * *

- [x] rename the `store-path` config to `store`
- [x] ? ~rename `shrinkwrap.yaml` to something else. Maybe `node_modules_state.yaml`.~
- [x] ~~remove the redundant subfolder in the store. Currently, the store has a subfolder called `1`.~~
- [x] rename the files which contain the shasums of the original, unmodified packages to `<version>.integrity`. Also, use the same integrity format used by the shrinkwrap file ([Subresource integrity](https://w3c.github.io/webappsec-subresource-integrity/))

**Comment by zkochan** [comment]
Also another thing to think about: the default location of the global store, global package and cache foldr on different systems.

Currently they are `~/.pnpm/.store`, `~/.pnpm` and `~/.pnpm/cache`

**Comment by iamstarkov** [comment]
why did you close it?

**Comment by zkochan** [comment]
I don't think we'll have any serious new breaking changes before v1. Since this issue was created, the store/node_modules structure was changed several times and this last one seems to be the optimal.

Of course, I can reopen it till v1 actually gets released

**Comment by zkochan** [comment]
1. rename the `store-path` config to `store`
2. ? rename `shrinkwrap.yaml` to something else. Maybe `node_modules_state.yaml`.
3. remove the redundant subfolder in the store. Currently the store has a subfolder called `1`.
4. rename the files which contain the shasums of the original, unmodified packages to `<version>.integrity`. Also use the same integrity format used by the shrinkwrap file ([Subresource integrity](https://w3c.github.io/webappsec-subresource-integrity/))

**Comment by iamstarkov** [comment]
> ? rename shrinkwrap.yaml to something else. Maybe node_modules_state.yaml.

maybe `pnpm-lock.yaml`

**Comment by zkochan** [comment]
Maybe... there was a long discussion about this on twitter: https://twitter.com/ZoltanKochan/status/872168064267284482.

Seems like most package managers use the term "lock". One uses "snapshot". But that creates such a mess TBH. We use the word lock a lot in code for the mutex files

**Comment by zkochan** [comment]
Keeping the `shrinkwrap.yaml` filename.

The other breaking changes were done.
