### ISSUE TITLE
Run script doesn't run "pre & post" scripts

### ISSUE THREAD

**Issue by rwu823** [pnpm/pnpm#4581]
### pnpm version:
`7.0.0-rc.5`

### Code to reproduce the issue:

`npm` and `yarn` can run any [pre & post prefix scripts](https://docs.npmjs.com/cli/v8/using-npm/scripts).

For example a `package.json` like below:
~~~json
{
  "scripts": {
    "prebuild": "echo prebuild",
    "build": "echo build",
    "postbuild": "echo postbuild"
  }
}
~~~

If run as npm or yarn `build` script, it would be run script `prebuild && build && postbuild`. But pnpm just run only `build` script.

### Expected behavior:
Run script behavior should like `yarn`.

### Actual behavior:
Just execute specify script.

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
Are you talking about Yarn v1? The latest Yarn doesn't run pre/post

If you need pre/post, set this config to true:

```
enable-pre-post-scripts=true
```

https://pnpm.io/cli/run#enable-pre-post-scripts

**Comment by rwu823** [comment]
@zkochan great! thanks.
