### ISSUE TITLE
Init command does not work

### ISSUE THREAD

**Issue by ivandotv** [pnpm/pnpm#4589]
### pnpm version:
`7.0.0-rc.6`
### Code to reproduce the issue:
create empty directory and run: `pnpm init`

### Expected behavior:
create `package.json`
### Actual behavior:
throws error: 
` ERR_PNPM_PACKAGE_JSON_EXISTS  package.json already exists`
### Additional information:

 - `node -v` prints: `v16.14.2`
 - Windows, macOS, or Linux?: Linux x64

**Comment by zkochan** [comment]
Yes, this is a bug. This is happening when there is a `package.json` file in one of the parent directories.
