### ISSUE TITLE
Support --no-bin-links

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#459]
The `--no-bin-links` argument will prevent npm from creating symlinks for any binaries the package might contain.

**Comment by zkochan** [comment]
This might be not needed as this flag exists in npm only because some systems don't support symlinks/junctions. However, pnpm would work on those anyway.

**Comment by aparajita** [comment]
@zkochan I'm closing this, as you say it is not relevant to any system that supports symlinks. And I honestly can't think of a use case where I would not want bin links to be installed.

**Comment by zkochan** [comment]
Honestly, I think bin files are only needed if the dependent package has lifecycle events. So the bin files of direct dependencies are always needed. But the bin files of subdependencies are only needed if the dependent package has a postinstall script (or another script that is executed during installation).

**Comment by skarab42** [comment]
> And I honestly can't think of a use case where I would not want bin links to be installed.

@aparajita I think this feature can be useful when using [aliases](https://pnpm.io/aliases). As aliases don't handle this case and always resolve bin to the package with the smallest version number.

**Comment by esaounkine** [comment]
Sorry for reviving an old conversation, and maybe I'm missing some other existing functionality - but it would be nice to support for AWS Lambda packaging.

In my case I'd like to stick to pnpm for all builds, with the exception that in the case of `sam build` I'd like the actual package files, rather than symlinks, to be copied to the output `.aws-sam` directory.

**Comment by jlost** [comment]
Can't run in my CIFS-mounted directory without `--no-bin-links`.

**Comment by GreatSeaSpider** [comment]
> Cannot run in my CIFS-mounted directory without `--no-bin-links`.

this - any chance of reconsidering adding this flag?
