### ISSUE TITLE
 ERROR  Unable to find the global bin directory

### ISSUE THREAD

**Issue by muuvmuuv** [pnpm/pnpm#4597]
I am running pnpm in our CI with the monorepo tool NX. NX runs `pnpm dlx tsc` under the hood when executing generators. This causes the below error. I tried running all installation methods the docs provide (including CI instructions for Bitbucket Pipelines) but I could not get it running. The NX parts seems irrelevant other commands work. Just the dlx part not.

### Code to reproduce the issue:

https://bitbucket.org/marvinheilemann/pnpm/addon/pipelines/home#!/results/3

### Actual behavior:

```
> nx run entergon:optimize
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Command failed with exit code 1: /usr/local/bin/pnpm add tsc --global --global-dir /tmp/dlx-539 --dir /tmp/dlx-539
ERROR: Something went wrong in @nrwl/run-commands - Command failed: nx workspace-generator ng-minify entergon
 
 >  NX   Running target "entergon:optimize" failed
   Failed tasks:
   
   - entergon:optimize
   
   Hint: run the command with --verbose for more details.
```

### Additional information:

 - `node -v` prints: 16.13.2
 - Windows, macOS, or Linux?: alpine
 - Docker image

**Comment by zkochan** [comment]
I'm not sure why nothing helps but `pnpm dlx` should really care about global directory. So the fix for this particular issue should be easy.
