### ISSUE TITLE
pnpm v7 `--filter` backwards compatibility with v6

### ISSUE THREAD

**Issue by nicholas-ochoa** [pnpm/pnpm#4606]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A backwards incompatible change to how `--filter` works is being added in pnpm starting with the 7.x version. Currently, `--filter` can accept a directory (ex: `pnpm -r --filter ./apps build`) which results in the command being run for all packages in the specified directory. Starting with pnpm 7, this behavior is changing to use a glob syntax so the previous example would become `pnpm -r --filter ./apps/** build` to achieve the same thing. However, this syntax does not work in pnpm 6.x and results in a response of `No projects matched the filters in "<directory>"`.

The change was first introduced here: https://github.com/pnpm/pnpm/pull/3521
And merged in to v7 here: https://github.com/pnpm/pnpm/pull/4253/files#diff-efe6e8c43fe0c807601afdc100b68ed8512e84217a308446bca550f3c21e1632

In `packages/pnpm/src/main.ts`, `useGlobDirFiltering: config.useBetaCli,` was changed to: `useGlobDirFiltering: true,`.

There does not seem to be a way to tell pnpm to run a script recursively with a filter on a specific directory that works in both pnpm 6.x and pnpm 7.x. I understand that this is the nature of a backwards incompatible change, however the impacts are fairly large (at least, in my small world of development, of course).

With this change, I will need to update the scripts for my packages to support the new pnpm 7.x `--filter` globs. Once I do this, I'll also need to ensure that all of the developers that work on the project upgrade to pnpm 7.x before they try and work on it. All of the CI build / testing tools will also need to be upgraded at the same time to ensure they continue working.

This isn't an impossible task of course, but the coordination can be difficult as these functions are owned by different groups (as I'm sure is the case in many organizations). 

Additionally, if we need to support or patch older versions of our software it will require developers to either upgrade the older code or downgrade to pnpm 6.x to work on it. CI would face similar issues.

**Describe the solution you'd like**

Add a new config option to the `.npmrc` called `filter-using-glob` that defaults to `true`. This would enable the new behavior going forward but allow for it to be disabled to support the pnpm 6.x style of `--filter`. This would also solve the compatibility issue.

**Describe the drawbacks of your solution**

I cannot think of any potential drawbacks.

**Describe alternatives you've considered**

[One of the pull requests linked above mentioned using `--dir` to run a command in a single directory](https://github.com/pnpm/pnpm/pull/3521#issuecomment-862217810), however this does not appear to work in the same way as `--filter`.

**Comment by nicholas-ochoa** [comment]
I forgot to mention. I have found that adding `use-beta-cli = true` to the `.npmrc` in my project seems to enable the `--filter` glob behavior in v6 work allows for a workaround. But I have concerns using this as the fix going forward, as I can imagine other functionality / changes will be added to the `use-beta-cli = true` configuration flag in future versions of pnpm 7.x and beyond.

**Comment by zkochan** [comment]
I'd rather add an option to pnpm v6 to enable the new behavior.
