### ISSUE TITLE
deep `file:` relative dep not found

### ISSUE THREAD

**Issue by farfromrefug** [pnpm/pnpm#4611]
* package.json deps:
   + file:demo-snippets
* demo-snippets:
  + package.json deps:
     - file:../packages/collectionview
* packages/collectionview
   
<img width="1018" alt="Screenshot 2022-04-23 at 17 00 56" src="https://user-images.githubusercontent.com/655344/164911714-90c4fdcc-92da-419e-97d0-967b6f40bd28.png">

### pnpm version:

7.rc7

### Expected behavior:

dependencies should be found

### Actual behavior:

```
 ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND  Could not install from "/Volumes/dev/nativescript/packages/collectionview" as it does not exist.
 ```

### Additional information:

macos

**Comment by zkochan** [comment]
:ship: 6.32.10

**Comment by farfromrefug** [comment]
@zkochan thank you again for your reactivity

**Comment by zardoy** [comment]
Hey, @farfromrefug I'm just curious what extension gives you these links to package jsons?

**Comment by farfromrefug** [comment]
@zardoy https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens

**Comment by farfromrefug** [comment]
@zkochan just found out that i have the same issue with `link:` do you want me to create a new issue for this?

**Comment by zkochan** [comment]
ok
