### ISSUE TITLE
pnpm workspaces and flag --recursive doesn't work on 7.0.0-rc.7

### ISSUE THREAD

**Issue by diegoazh** [pnpm/pnpm#4613]
### pnpm version:

7.0.0-rc.7

### Code to reproduce the issue:

Clone the [`gmap-vue` repository](https://github.com/diegoazh/gmap-vue) and run `pnpm run lint` to see the unexpected behaviour

```bash
git clone https://github.com/diegoazh/gmap-vue.git
```
```bash
pnpm install
```
```bash
pnpm run lint
```

### Expected behavior:

Run the script `lint` recursively on all packages described on `pnpm-worspaces.yaml`

### Actual behavior:

It prints the work `"--recursive" in many lines all the time as you can see in the following image:
<img width="1728" alt="Screen Shot 2022-04-23 at 14 36 59" src="https://user-images.githubusercontent.com/10166935/164924062-c50c9fcb-5026-4e13-ae33-664df2b42949.png">

### Additional information:

 - `node -v` prints: v16.14.2
 - Windows, macOS, or Linux?: macOS Silicon (M1 - arm64 architecture)
 - pnpm `v6.x.x` works as expected

**Comment by zkochan** [comment]
`--recursive` must be placed before `lint`. So from v7, use `pnpm run -r lint` or `pnpm -r run lint`
