### ISSUE TITLE
ERROR  Unexpected token a in JSON at position 1

### ISSUE THREAD

**Issue by 183461750** [pnpm/pnpm#4621]
### pnpm version:
6.32.10
### Code to reproduce the issue:
pnpm i -S element-ui

### Expected behavior:
success
### Actual behavior:
ERROR  Unexpected token a in JSON at position 1
### Additional information:

 - `node -v` prints: v14.17.3
 - Windows, macOS, or Linux?: windows

**Comment by BlackHole1** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8198408/165212865-392023b4-90da-4378-b017-49d4b37c2937.png">

The problem does not exist, please check that your package.json is in the correct format.
