### ISSUE TITLE
pnpm workspace will be affected by package-lock. 

### ISSUE THREAD

**Issue by coldrainc** [pnpm/pnpm#4628]
### Code to reproduce the issue:

pnpm workspace will be affected by package-lock.json

ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE
the lockfile is broken! a full installation will be performed in an attempt to fix it

### Expected behavior:
pnpm install   success
### Actual behavior:
error   the lockfile is broken! a full installation will be performed in an attempt to fix it
### Additional information:

 - `node -v` prints: v16.8.0
 - Windows, macOS, or Linux?: macos

**Comment by zkochan** [comment]
What version of pnpm are you using? I believe, this was fixed. Maybe your store is broken. Try to remove it. To get the store location, run `pnpm store path`.

**Comment by coldrainc** [comment]
您好，您发的邮件已收到

**Comment by zkochan** [comment]
I did not get your response.

**Comment by songyazhao** [comment]
I have the same problem.

Looks like it has something to do with [https://github.com/babel/babel/issues/14525](https://github.com/babel/babel/issues/14525).

```
 ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-PQO8sDIJ8SIwipTPiR71kJQCKQYB5NGImbOviK8K+kg5xkNSYXLBupuX9QhatFowrsvo9Hj8WgArg3W7ijNAQw==","registry":"https://registry.npmmirror.com/","tarball":"https://registry.npmmirror.com/@babel/traverse/-/traverse-7.17.9.tgz"} from the store. This means that the lockfile is broken. Expected package: @babel/traverse@7.17.10. Actual package in the store by the given integrity: @babel/traverse@7.17.9.
```

**pnpm version**: `6.32.7`

**Comment by songyazhao** [comment]
> I have the same problem.
> 
> Looks like it has something to do with [babel/babel#14525](https://github.com/babel/babel/issues/14525).
> 
> ```
>  ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-PQO8sDIJ8SIwipTPiR71kJQCKQYB5NGImbOviK8K+kg5xkNSYXLBupuX9QhatFowrsvo9Hj8WgArg3W7ijNAQw==","registry":"https://registry.npmmirror.com/","tarball":"https://registry.npmmirror.com/@babel/traverse/-/traverse-7.17.9.tgz"} from the store. This means that the lockfile is broken. Expected package: @babel/traverse@7.17.10. Actual package in the store by the given integrity: @babel/traverse@7.17.9.
> ```
> 
> **pnpm version**: `6.32.7`

Run after `rm -rf  $(pnpm store path)`, now work.

**Comment by coldrainc** [comment]
> 



> What version of pnpm are you using? I believe, this was fixed. Maybe your store is broken. Try to remove it. To get the store location, run `pnpm store path`.

thanks, that's solved my problem.

**Comment by superiums** [comment]
i have the same problem
```
 ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-iiXaOL2wSbnSY4qg0mFPWJHL9iwyEsoNYwaHF2w58/fsVAQJlj+KUfFAFZu+nzbz+b7dUprJEAc+O9vhHHhQTA==","registry":"https://registry.npm.taobao.org/","tarball":"https://registry.npmmirror.com/@types/superagent/-/superagent-4.1.14.tgz"} from the store. This means that the lockfile is broken. Expected package: @types/superagent@4.1.14. Actual package in the store by the given integrity: @types/superagent@4.1.15.
 ERR_PNPM_STORE_ADD_FAILURE  Some packages have not been added correctly
```

is there any way to remove the special package instead of remove all ?

i've tried ` pnpm store add @types/superagent@4.1.14 ` but not work.

**Comment by coldrainc** [comment]
您好，您发的邮件已收到

**Comment by lusess123** [comment]
i have the same problem too
` ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-iiXaOL2wSbnSY4qg0mFPWJHL9iwyEsoNYwaHF2w58/fsVAQJlj+KUfFAFZu+nzbz+b7dUprJEAc+O9vhHHhQTA==","registry":"https://registry.npm.taobao.org/","tarball":"https://registry.npmmirror.com/@types/superagent/-/superagent-4.1.14.tgz"} from the store. This means that the lockfile is broken. Expected package: @types/superagent@4.1.14. Actual package in the store by the given integrity: @types/superagent@4.1.15.`
i've tried pnpm store add @types/superagent@4.1.14 but not work.
pnpm version is  7.9.5

**Comment by XinChou16** [comment]
pnpm 8.9.2, also broken
