### ISSUE TITLE
run fail: pnpm --filter "@babel/core" test  

### ISSUE THREAD

**Issue by a309492165** [pnpm/pnpm#4630]
run fail: pnpm --filter "anypackage" test
tip:  No projects matched the filters in dirpath/xxx

**Comment by zkochan** [comment]
Do you have `@babel/core` as a project in your workspace?

**Comment by geoynomous** [comment]
I have the same with an `update`

`package.json`
```
{
  "name": "pnpm7",
  "dependencies": {
    "async": "3.2.0",
    "chalk": "5.0.0",
    "lodash": "4.17.0"
  }
}
```

running (to only update `lodash`) 

`pnpm update --latest --filter="lodash"`

results in 

`No projects matched the filters in "/private/tmp/pnpm7"`


While **actually** I like to run 

`pnpm update --latest --filter="\!lodash"`

that updates **all** - but **not** `lodash`

It also results in 

`No projects matched the filters in "/private/tmp/pnpm7"`

Please advise

**Comment by zkochan** [comment]
@geoynomous this is not how you update lodash. If you want to update lodash, run: 

```
pnpm update lodash --latest
```

And there is no command to update everything except lodash. But you can run `pnpm update --interactive --latest` and pick everything except lodash.

**Comment by geoynomous** [comment]
The --interactive is nice - but we have like 20 recursive packages with > 500 packages ... we basically like to update all - except for a few that we know to stay on a certain version .... the interactive is human and error prone ..

**Comment by a309492165** [comment]
> as a project in your workspace?

package.json and node_modules is have 'axios',but run: pnpm --filter "axios" test.  is fail
tip: No projects matched the filters in dirpath/xxx
![1651738014(1)](https://user-images.githubusercontent.com/43060277/166884674-74d581b5-07dd-4bca-9441-2ad11b3e4932.jpg)

**Comment by zkochan** [comment]
This is not what filtering is for. `pnpm --filter axios test` will run the tests in axios, when axios is a project in your [workspace](https://pnpm.io/workspaces). In this case, axios is just a dependency.

**Comment by Kristinita** [comment]
**Type: Questions** :question:

> And there is no command to update everything except lodash

@zkochan,

1. Did I understand correctly that pnpm doesn’t have a command to “update all dependencies except some dependencies to the latest versions”?
1. Is it possible for pnpm users somehow to update to the latest versions all dependencies except some? Currently, I use [**grunt-dev-update**](https://stackoverflow.com/a/48952098/5951529). grunt-dev-update updates all dependencies except the dependencies specified in the value of the [**`reportOnlyPkgs` option**](https://github.com/pgilad/grunt-dev-update#optionsreportonlypkgs). But it looks like grunt-dev-update is solely npm-compatible, not pnpm-compatible.

Thanks.
