### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by xiao252** [pnpm/pnpm#4633]
Installation error using NPM

### Actual behavior:
```
npm install -g pnpm@next-7
npm ERR! Unexpected token '.'
```
### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?:Windows
 - `npm -v`:v8.3.1

**Comment by lisunovdv** [comment]
This problem looks like an NVM issue. If you are using NVM, please, update it to latest version

**Comment by xiao252** [comment]
> This problem looks like an NVM issue. If you are using NVM, please, update it to latest version

After upgrading NVM to 1.1.9, the same error is still reported

**Comment by IAALAI** [comment]
推荐把原来的都直接删了，然后重新下载nodejs.这样容易一点。

**Comment by zkochan** [comment]
I don't know what is causing this issue as the error happens with npm. pnpm is not involved. You may use [a different installation method](https://pnpm.io/installation). For instance, using corepack:

```
corepack enable
corepack prepare pnpm@7.1.2 --activate
```

**Comment by mcmxcdev** [comment]
`npm i pnpm -g` works as expected. 

There are also plenty of available installation methods to choose from as mentioned above.
