### ISSUE TITLE
Got error after installing pnpm with npm also yarn global 

### ISSUE THREAD

**Issue by ioofy** [pnpm/pnpm#4648]
Hello i just try using pnpm but got this error on my local machine. 

Error
![image](https://user-images.githubusercontent.com/77242429/166136177-83971f0d-080c-4c6b-b9e8-fc480ce14e5a.png)

### pnpm version:
v.7.0.0

### Additional information:

 - `node -v` prints: node v16.15.0
 - Windows, macOS, or Linux?: Windows 10
 
 Anyone can help me please?

**Comment by zkochan** [comment]
Looks like you don't have node.js installed.

You can install it using pnpm:

```
pnpm env use -g lts
```

**Comment by ioofy** [comment]
> pnpm env use -g lts

i was installed it

**Comment by ioofy** [comment]
![image](https://user-images.githubusercontent.com/77242429/166406710-7209000f-b6f1-4dda-8e07-dfbcb7988866.png)

**Comment by ioofy** [comment]
im running on cmd using administrator and it say node is activated but after trying to using pnpm i got error again 

![image](https://user-images.githubusercontent.com/77242429/166407170-45fe683b-0294-43e9-9b9f-e9dccc3f7d2b.png)

**Comment by ioofy** [comment]
Solutions : 

try to use this command and run on cmd using administrator : 
> pnpm env use -g lts

and then restart your pc and open your codebase also running again pnpm i for installing a package.
Its working fine again.
