### ISSUE TITLE
[pnpm v7] postinstall not running

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#4649]
### pnpm version: 7.0.0

Looks like it does not run postinstall script. Does it related to sideEffectCache? We need postinstall script to run patch-package. If pnpm has built-in patch support it will be better so it can manage those changes better.

(Sry I didn't make a reproduction, it happens on https://github.com/DimensionDev/Maskbook/pull/6192)

### Additional information:

 - `node -v` prints: 17.9.0
 - Windows 11

**Comment by zkochan** [comment]
The postinstall script is executed. side-effects-cache is only skipping postinstall scripts of your dependencies, not the postinstall script of your project.

I have tried that repository and the postinstall script runs fine.

**Comment by Jack-Works** [comment]
Oh, I find out. It does not re-run the script after multiple installations. 

It happens by the following step:

1. Install, the patch package has run.
2. Remove `node_modules/ts-result` and `node_modules/.pnpm/ts-result*`
3. Run `pnpm install`
4. The package is not patched.

> cat .\node_modules\ts-results\esm\index.js

Original content:

```js
export * from './result';
export * from './option';
//# sourceMappingURL=index.js.map
```

After patch:

```js
export * from './result.js';
export * from './option.js';
//# sourceMappingURL=index.js.map
```

**Comment by Jack-Works** [comment]
I can reproduce this on my one PC, but on another PC it works well. I don't know why it happens like this 🤔

**Comment by Jack-Works** [comment]
Oh I know why, I have `ignore-scripts=true` in my `~/.npmrc`. I think it should be equal to `neverBuiltDependencies`

**Comment by vasco3** [comment]
I rolled back to v6 and it works.

**Comment by azamat-sharapov** [comment]
Can reproduce this on v7.3.0. When running `pnpm install` second time, postinstall isn't triggered. Workaround is to delete store directory before running `pnpm install` again. Can we reopen this issue?

**Comment by lefreet** [comment]
`side-effects-cache=false`  worked,  with the v6 `false` and v7 `true` default, it cause the `pre/postscript` don't run  when has been install to store.

**Comment by rujorgensen** [comment]
I didn't catch the fix? I think I'm seeing this on 7.14.2

**Comment by benatkin** [comment]
I'd love to see this officially supported. It appears to be working and just need to be documented. A review that this works by a couple of people would help.

However, when I looked at this what I really wanted wasn't to ignore scripts, but to download first with the network connected and then install them with the network disconnected. It looks like that should work with `pnpm fetch`!

https://pnpm.io/cli/fetch

**Comment by Pahomkch** [comment]
time to time I still face with in even in v8

```
cd node_modules/hasura-cli
pnpm run postinstall
```
fix it
