### ISSUE TITLE
pnpm 7.0.0 is not compatible with husky

### ISSUE THREAD

**Issue by yanckst** [pnpm/pnpm#4657]
## Description

It seems that an error is raised if you're using `husky` and `pnpm`. `husky` is a library to add hooks with git to apply a work before a commit for example. 

### Code to reproduce the issue:
- Install pnpm 7.0.0 globally using `npm`, `npm install -g pnpm`
- Install husky in a project `pnpm add -D husky`
- Add this configuration in your `package.json`
```
        "lint-js": "npx eslint ./*.js --fix-dry-run",
        "lint-ts": "npx eslint src/**/*.ts --fix-dry-run",
        "lint-tsx": "npx eslint src/**/*.tsx --fix-dry-run",
        "lint-fix-js": "npx eslint ./*.js --fix",
        "lint-fix-ts": "npx eslint src/**/*.ts --fix",
        "lint-fix-tsx": "npx eslint src/**/*.tsx --fix",
        "lint": "pnpm lint-js && pnpm lint-ts && pnpm lint-tsx",
        "lint-fix": "pnpm lint-fix-js && pnpm lint-fix-ts && pnpm lint-fix-tsx"
    },
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "./src/*.{js,jsx,ts,tsx}": [
            "pnpm lint-fix"
        ]
    },
```
- Do a commit with git

### Expected behavior:
The git hooks should not crash.

### Actual behavior:
![image](https://user-images.githubusercontent.com/30554401/166300267-8e594cf5-5e08-4cfc-ae1c-0a61a7599877.png)

### Additional information:

 - `node -v` prints: 16.14.2
 - Windows, macOS, or Linux?: Windows 10 version 21H2
 - `pnpm@6.32.11` works perfectly with `husky`

**Comment by zkochan** [comment]
You might use an old version of Husky. Update to the latest version, it works with pnpm.

**Comment by yanckst** [comment]
I tried the latest version and I have the problem. I'm using `7.0.4`

**Comment by mcmxcdev** [comment]
For me, husky + lint-staged works fine with pnpm v7.0.0 (on Linux though, not Windows)

I think your issue might be that you put `husky` and `lint-staged` properties inside `scripts` block rather than top level.
 
It needs to be like this:
```
"scripts": {},
"lint-staged": {},
"husky": {}
```

But I am also not sure if husky even still supports having it in `package.json` directly.

**Comment by yanckst** [comment]
@mcmxcdev Oh okay thanks. I'll take a look.

**Comment by ioofy** [comment]
It's working fine husky with pnpm

**Comment by yanckst** [comment]
I validated my `package.json` and the `lint-staged` and `husky` are at the root. Will look deeper. It might be a config/project issue, since everyone doesn't have problems.

**Comment by yanckst** [comment]
Okay I figured this out. It's not a problem with `pnpm`. 

For the curious. I did a bad migration. I was using v4 and migrated to v7.

I followed this doc : https://github.com/typicode/husky-4-to-7

Thanks!

**Comment by You00** [comment]
@yanckst @zkochan  I had the same problem, how did I solve it in the end?
