### ISSUE TITLE
node loadESM fails to find nested package.json

### ISSUE THREAD

**Issue by geoynomous** [pnpm/pnpm#4659]
We have `package.json` with

`"@company/common": "file:../common",`

a dependency.

After switching to 7.0.0 we now get 

```
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/path/to/project/node_modules/.pnpm/file+..+..+modules+common/node_modules/package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at createConstants (file:///path/to/project//node_modules/.pnpm/file+..+..+modules+common/node_modules/common.js:34:40)
    at file:///path/to/project/node_modules/.pnpm/file+..+..+modules+common/node_modules/common.js:75:28
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/path/to/project/node_modules/.pnpm/file+..+..+modules+common/node_modules/package.json'
}
```

### pnpm version:

7.0.0 (it worked with 6.32.11)

### Expected behavior:

The package.json is found

### Actual behavior:

The package.json is not found

**Comment by zkochan** [comment]
Is there a `package.json` in the common folder? 

If you want a symlink to `../common`, then use `link:../common`.

**Comment by geoynomous** [comment]
there is one - it seems it does not get copied (by pnpm) as the target folder `file:///path/to/project//node_modules/.pnpm/file+..+..+modules+common/node_modules/` exists

**Comment by geoynomous** [comment]
Ok ... so we have in `/path/to/project/modules/common`

```
import { URL } from 'url';
const __dirname = new URL('.', import.meta.url).pathname;
const packageFilepath = path.resolve(__dirname, '..', '..', 'package.json');
```

In 6.32.11 `packageFilepath` refers to `/ path/to/project/`

In 7.0.0 `packageFilepath` now refers to `/path/to/project/node_modules/.pnpm/file+..+..+modules+common/node_module`

The `link:` solved it!
