### ISSUE TITLE
[pnpm v7] vite with pnpm give " ERR_PNPM_PACKAGE_JSON_EXISTS  package.json already exists" 

### ISSUE THREAD

**Issue by mohamedy72** [pnpm/pnpm#4662]
### pnpm version:
7.0.0
### Code to reproduce the issue:
`
pnpm init vite@latest
`

### Expected behavior:
project initializing steps should start
### Actual behavior:
I get this error  " ERR_PNPM_PACKAGE_JSON_EXISTS  package.json already exists" 
### Additional information:

 - `node -v` prints: v16.14.2
 - Windows, macOS, or Linux?: Linux xbuntu

**Comment by zkochan** [comment]
The correct command is 

```
pnpm create vite@latest
```
