### ISSUE TITLE
`pnpm init -y` not working

### ISSUE THREAD

**Issue by hyrious** [pnpm/pnpm#4668]
### pnpm version:

7.0.0

### Code to reproduce the issue:

```bash
> pnpm init -y
 ERROR   ERROR  Unknown option: 'y'
For help, run: pnpm help init
```

### Expected behavior:

pnpm@6 used to work.

### Actual behavior:

Now the _correct_ way to append `-y` is `-- -y`.

### Additional information:

 - `node -v` prints: v18.0.0
 - Windows, macOS, or Linux?: macOS 12.3.1

**Comment by zkochan** [comment]
Why do you need `pnpm init -y`?

`pnpm init` is non-interactive.

**Comment by hyrious** [comment]
Sorry, I carried my experience from `npm init -y`, where I guess pnpm work the same.

Closing as it works as expected.

**Comment by furopi** [comment]
> Why do you need `pnpm init -y`?
> 
> `pnpm init` is non-interactive.

That Sir, is a valuable information you need to know beforehand. Thank you!
