### ISSUE TITLE
Should the documentation on continuous integration be updated?

### ISSUE THREAD

**Issue by liby** [pnpm/pnpm#4670]
### Code to reproduce the issue:

```
before_install:
  - pnpm config set store-dir ~/.pnpm-store
```

### Expected behavior:
n/a

### Actual behavior:
n/a

### Additional information:

 - `node -v` prints: >= 14
 - Windows, macOS, or Linux?: Both

As mentioned in the section on [Node-Modules Settings/store-dir](https://pnpm.io/npmrc#store-dir), the default path to store-dir for pnpm@v7 varies for different operating systems, so do we still need to set the path to store-dir to `~/.pnpm-store` in the CI? Is this redundant?

**Comment by liby** [comment]
Closed due to https://github.com/pnpm/pnpm/issues/1174#issuecomment-1028135439

**Comment by panghaoyuan** [comment]
@liby  how do you resolved this question. can you show me a case.
