### ISSUE TITLE
[Version: 7] release script in monorepo fails with error  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL

### ISSUE THREAD

**Issue by abhishekashyap** [pnpm/pnpm#4673]
On Running the release script inside monorepo, that is:
`pnpm plugin:release --workspace-root -- --packagePath='./packages/temp-repo' --scope=temp-repo`

I'm getting

```zsh
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: plugin:release
 ELIFECYCLE  Command failed with exit code 1.
```

I read through the changelog 

> When using pnpm run <script>, all command line arguments after the script name are now passed to the script's argv, even --. For example, pnpm run echo --hello -- world will now pass --hello -- world to the echo script's argv. Previously flagged arguments (e.g. --silent) were interpreted as pnpm arguments unless -- came before it.

And changing it to:
`pnpm --workspace-root -- --packagePath='./packages/temp-repo' --scope=temp-repo plugin:release`
or
`pnpm --workspace-root -- --packagePath='./packages/temp-repo' --scope=temp-repo release`

still outputs into error

### Expected behavior:
To release script succeed

### Actual behavior:
Release script failing with an error

### Additional information:

 - `node -v` prints: 14.19
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
If I understand it correctly that you want to pass ` --packagePath='./packages/temp-repo' --scope=temp-repo` to the script, then this should work:

```
pnpm --workspace-root plugin:release --packagePath='./packages/temp-repo' --scope=temp-repo
```

**Comment by zq0904** [comment]
For me,
This is applicable

```ts
  pnpm -v // 7.5.2
  pnpm -F @zeroer/pnpm-test coverage // YES
  pnpm coverage -F @zeroer/pnpm-test // NO
```
