### ISSUE TITLE
Gracefully handle missing store

### ISSUE THREAD

**Issue by julien-f** [pnpm/pnpm#468]
If the store is missing (e.g. has been deleted), broken symlinks should be detected and deps reinstalled.

### Code to reproduce the issue:

```
> rm -fr ~/.pnpm
> pnpm i
```

### Expected behavior:

Store is recreated and dependencies are properly reinstalled.

### Actual behavior:

```
 ! ENOENT: no such file or directory, stat '/tmp/my-project/node_modules/lodash'
```

### Additional information:

 - `node -v` prints: 3.10.9
 - Windows, OS X, or Linux?: Debian GNU/Linux stretch/sid

**Comment by zkochan** [comment]
This should work from [pnpm@0.46](https://github.com/pnpm/pnpm/releases/tag/v0.46.0) as files are hardlinked from the store. Even if the store will be removed, the files will stay in the node_modules
