### ISSUE TITLE
false positive of unmet peer dependency in workspace

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#4685]
### Code to reproduce the issue:

> `package.json`

```json
{
  "packageManager": "pnpm@7.0.0",
  "dependencies": {
    "react": "18.0.0"
  }
}
```

> `pnpm-workspace.yaml`

```yaml
packages:
  - 'packages/*'
```

> `packages/components`

```json
{
    "name": "@workspace/components",
    "dependencies": {
        "use-subscription": "*"
    }
}
```

Then run `pnpm install`

### Expected behavior:

No problem

### Actual behavior:

```
Scope: all 2 workspace projects
Already up-to-date
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies                                                                             

packages/components
└─┬ use-subscription
  ├── ✕ missing peer react@"^16.8.0 || ^17.0.0 || ^18.0.0"
  └─┬ use-sync-external-store
    └── ✕ missing peer react@"^16.8.0 || ^17.0.0 || ^18.0.0"
Peer dependencies that should be installed:
  react@">=16.8.0 <17.0.0 || >=17.0.0 <18.0.0 || >=18.0.0 <19.0.0"
```

As you can see, react is installed at the top-level therefore it is available for `packages/components`.

The use case here is we want to specify a single react at the top level and the whole workspace can use it.

**Comment by zkochan** [comment]
Unfortunately, we can't support this case. You must add react to `packages/components` as well. You may use an exact version to force the same version of react everywhere. And you may also use some linting like syncpack or [meta-updater](https://github.com/pnpm/meta-updater) to guarantee that the same version of react is used everywhere.

I understand that this is less convinient than in v6 but there were some issues that I could only fix by doing this breaking change. We can come up with some features to make it easier for users to handle.

**Comment by Jack-Works** [comment]
Thanks, I will install those dependencies for every sub-package
