### ISSUE TITLE
PNPM 7 GitHub package repository ERR_PNPM_FETCH_404

### ISSUE THREAD

**Issue by martinek-stepan** [pnpm/pnpm#4686]
### Expected behavior:

Install packages from both npm and npm.pkg.github.com.

### Actual behavior:

```
 WARN  GET https://npm.pkg.github.com/@lego/prettier-config/-/prettier-config-6.1.2.tgz error (ERR_PNPM_FETCH_405). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://npm.pkg.github.com/@lego/eslint-config-prettier/-/eslint-config-prettier-7.1.2.tgz error (ERR_PNPM_FETCH_405). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://npm.pkg.github.com/@lego/eslint-config-typescript/-/eslint-config-typescript-9.4.1.tgz error (ERR_PNPM_FETCH_405). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://npm.pkg.github.com/@lego/prettier-config/-/prettier-config-6.1.2.tgz error (ERR_PNPM_FETCH_405). Will retry in 1 minute. 1 retries left.
 WARN  GET https://npm.pkg.github.com/@lego/eslint-config-prettier/-/eslint-config-prettier-7.1.2.tgz error (ERR_PNPM_FETCH_405). Will retry in 1 minute. 1 retries left.
 WARN  GET https://npm.pkg.github.com/@lego/eslint-config-typescript/-/eslint-config-typescript-9.4.1.tgz error (ERR_PNPM_FETCH_405). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_405  GET https://npm.pkg.github.com/@lego/prettier-config/-/prettier-config-6.1.2.tgz: Method Not Allowed - 405
```

### Additional information:
 - NPM and older version of PNPM 6.32.11 is able to download the packages without issues
- The package is available in both npm (outdated version) and private npm.pkg.github.com 
 - `node -v` prints: v14.19.1
 - Windows, macOS, or Linux?: macOS installed through brew (upgraded)

**Comment by zkochan** [comment]
> older version of PNPM 6.32.11 is able to download the packages without issues

Maybe you just have it in your cache. pnpm v7 changed the cache location.

TBH, I can't really recall any change in v7 that could cause such regression.

**Comment by martinek-stepan** [comment]
I will do some testing with cache cleaning.

**Comment by martinek-stepan** [comment]
I have tested again with pruning and both of v6 and v7 were able to download the package. Must have been GitHub acting out randomly at that moment

**Comment by shirly-chen-awx** [comment]
I met this issue as well, how did you solve it in the end?

**Comment by martinek-stepan** [comment]
Hi, I suspect the issue is that the package was in both public (npm) and private (Github) repositories, the npm one older version. It went away after removing node_modules & lockfile. Other than that I can not help you more. @shirly-chen-awx

**Comment by whale2002** [comment]
summary: remove lockfile is ok
