### ISSUE TITLE
pnpm install throw Error UNABLE_TO_VERIFY_LEAF_SIGNATURE, but npm install  is ok

### ISSUE THREAD

**Issue by Beace** [pnpm/pnpm#4689]
### pnpm version:
6.31.0

### Code to reproduce the issue:
``` bash
$ export https_proxy=http://127.0.0.1:9090 // I used proxyman to catch http(s) request
$ npm config set strict-ssl false
```

package.json
```json
{
  "name": "test-pnpm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/traverse": "7.17.10"
  }
}
```
run  `npm install` is fine, but  `pnpm install --registry=https://registry.npmjs.org` throw Error

```
$ pnpm install --registry=http://registry.npmjs.org
WARN  GET https://registry.npmjs.org/@babel/traverse/-/traverse-7.17.10.tgz error (UNABLE_TO_VERIFY_LEAF_SIGNATURE). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@babel%2Fcode-frame error (UNABLE_TO_VERIFY_LEAF_SIGNATURE). Will retry in 10 seconds. 2 retries left.
```

### Expected behavior:
install success.

### Actual behavior:
install failed.there is a  screenshot.

![origin_img_v2_4407e959-4dd7-4a1c-b075-5bc244128e1g](https://user-images.githubusercontent.com/13284978/167175147-aafbb063-78ce-43df-9c47-38b7418fc0e3.jpg)

### Additional information:

 - `node -v` prints:  v16.0.0 
 - macOS

**Comment by lvjiaxuan** [comment]
+1

**Comment by DevLaTarte** [comment]
I'm facing the same issue, any news on the subject ?

**Comment by toxsick** [comment]
Having the same issue when installing a package from a  private  gitlab registry (cert should be ok though)

**Comment by ayblanchet** [comment]
Having the same issue, It's work with npm but not with pnpm.
I have no certificate and strict-ssl to false. Is there a workaround?

**Comment by Alsan** [comment]
same issue.

platform: linux
node: v16.19.0
pnpm: 7.27.0

**Comment by zkochan** [comment]
try to run:

```
NODE_TLS_REJECT_UNAUTHORIZED=0 pnpm install
```

**Comment by zkochan** [comment]
I don't understand why it doesn't work because when `strict-ssl` is set to `false`, we don't rejectUnauthorized:

https://github.com/pnpm/components/blob/20a4aadfa2b7bc5f5ce2febff648277470d20966/network/agent/agent.ts#L63

**Comment by zkochan** [comment]
Try 7.27.1

**Comment by Alsan** [comment]
Almost done, but not for external binaries.

![2023-02-19_11-04](https://user-images.githubusercontent.com/217947/219909861-0065cc03-ebe9-4938-a374-07c31a2b6727.png)

**Comment by zkochan** [comment]
but this error happens in a script. I don't think we have control over how the scripts fetch. Does it work with npm or yarn?

**Comment by Alsan** [comment]
yes, both npm and yarn works as expected.

**Comment by zkochan** [comment]
I am not sure what is the issue. I see the warning in the output about `NODE_TLS_REJECT_UNAUTHORIZED` set to `0` and I see this: https://github.com/npm/minipass-fetch/blob/813e6d77e6b2279d650309dd8d8325bba229a38a/lib/request.js#L87

**Comment by Alsan** [comment]
I've add this env setting when running the `pnpm install` command as @zkochan  said. I'll try to remove this flag to see will it help later today.

**Comment by Alsan** [comment]
checked, and tried to export proxy settings as environment before run pnpm install, didn't help.

```sh
export http_proxy=http://127.0.0.1:4000
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
pnpm install --loglevel verbose
```
