### ISSUE TITLE
[pnpm v7] typescript code question

### ISSUE THREAD

**Issue by LastKing** [pnpm/pnpm#4692]
### Code to reproduce the issue:

https://github.com/LastKing/ts-proto-pnpm-issue

### Expected behavior:
The name field is on the object instance.

### Actual behavior:
![image](https://user-images.githubusercontent.com/8540374/167235119-d274c2de-8f40-469a-b046-171f1f339d21.png)

### Additional information:

 - `node -v` prints: 16.13.1 
 - Windows, macOS, or Linux?: macos and Linux

**Comment by mcmxcdev** [comment]
How is this issue related to pnpm? You need to type `I` properly, so the code knows that there is a `name` property.

**Comment by LastKing** [comment]
I use pnpm@6 .There is no such problem...
I don't known why.

**Comment by LastKing** [comment]
please give me some suggest. 
How deal with the promblem?

Thank you for your help.

**Comment by spacecave** [comment]
same issue with v7.0.0，when i use jest in typescript project
<img width="640" alt="wecom-temp-a04e09a927f14ca60deaa4f64e1fae22" src="https://user-images.githubusercontent.com/8168683/172751814-dfb5c537-4e5f-4165-b2ad-a5127d0ac1c4.png">

but when i use v6.23.2，it works

**Comment by MalpenZibo** [comment]
Try adding all the dependencies declared here: https://www.npmjs.com/package/@types/express

In my case: `@types/body-parser @types/serve-static @types/express-serve-static-core @types/qs`

In general, see [`https://github.com/pnpm/pnpm/discussions/4646`](https://github.com/pnpm/pnpm/discussions/4646)
 - strict-peer-dependencies is true by default [4427](https://github.com/pnpm/pnpm/pull/4427).
