### ISSUE TITLE
Error using pnpm：ENOENT: no such file or directory, mkdir '...'

### ISSUE THREAD

**Issue by Emp2612** [pnpm/pnpm#4695]
### Code to reproduce the issue:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/20411958/167256216-dde9f6f8-39b3-4273-a25a-fa4f5024d4f7.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/20411958/167256241-ce0757cb-2920-4baf-ba32-82447b13ab7c.png">

### Expected behavior:
The initialization of the vite project is successful and the installation of dependencies can be successful.
### Actual behavior:
Any form of pnpm use is abnormal, and the node and nvm have been deleted and reinstalled is still invalid.
### Additional information:

 - `node -v` prints:  v16.15.0
 - Windows, macOS, or Linux?: macOS Monterey v12.3.1 Intel Core i9

**Comment by zkochan** [comment]
Not sure what the issue is. I can't reproduce it. Try to debug it to find why this error happens.

**Comment by qhanw** [comment]
in the `~/Library/pnpm` directory, try to delete the `store` folder。
```bash
cd ~/Library/pnpm
rm -rf store
```

**Comment by dengshicheng1996** [comment]
I use NVM to manage my Version of Node and this issue also occurred after switching versions

**Comment by dengshicheng1996** [comment]
> 

I did that, but it didn't work correctly.
```
node -v prints: v16.9.0
Windows, macOS, or Linux?: macOS Big Sur 11.5.2  Intel Core I5
```

**Comment by Emp2612** [comment]
update v7.1.6，Miraculously back to normal~
Thank you everyone!!!
