### ISSUE TITLE
pnpx changeset version:  ERR_PNPM_DLX_NO_BIN  No binaries found in changeset

### ISSUE THREAD

**Issue by btakita** [pnpm/pnpm#4697]
### pnpm version:

v7-7.0.1

### Code to reproduce the issue:

pnpx changeset version

### Expected behavior:

success: incrementing versions in the packages of the monorepo based on @changesets/cli

### Actual behavior:

ERR_PNPM_DLX_NO_BIN  No binaries found in changeset

### Additional information:
 - `node -v` prints: v18.1.0
 - arch linux 5.17.5-zen1-1-zen
[pnpm-debug.log](https://github.com/pnpm/pnpm/files/8645594/pnpm-debug.log)

**Comment by zkochan** [comment]
This is correct. `pnpx changeset version` is installing the changeset package, which has no binaries.

If you want to run `changeset` in a project that has `@changesets/cli` in the dependencies, then run `pnpm changeset version`.

**Comment by poteirard** [comment]
To clarify, in case someone finds the same issue.
If you don't have all the deps or need only to run those commands instead of:
```bash
pnpx changesets version
```
Run:
```bash
pnpx @changesets/cli version```

**Comment by yashsway** [comment]
The right command for `pnpm` is `pnpm dlx changeset [...]`. `pnpx` is not how invoke binaries with `pnpm`.

**Comment by poteirard** [comment]
It was 2y ago 😅😅
