### ISSUE TITLE
Prettier plugin doesn't load automatically after `pnpm` `7.0.0` hoisting

### ISSUE THREAD

**Issue by oedotme** [pnpm/pnpm#4700]
### Code to reproduce the issue:

Installing `prettier` and `prettier-plugin-tailwindcss`

```shell
pnpm add --save-dev prettier prettier-plugin-tailwindcss
```

### Expected behavior

`prettier-plugin-tailwindcss` loads automatically as it's now hoisted since `pnpm` `7.0.0`

Running `prettier file.tsx` should print the file content formatted correctly with `tailwindcss` classes sorted.

### Actual behavior

`prettier-plugin-tailwindcss` doesn't load automatically, and requires specifying the `plugins` option at `prettier` config.

Running `prettier file.tsx` prints the file content formatted correctly but doesn't load/use `prettier-plugin-tailwind`.

### Debugging

- Installing the `prettier` and `prettier-plugin-tailwindcss` with `npm` `8.6.0` works as expected.
- Replacing the symlinked `node_modules/prettier` installed with `pnpm` with the `npm` version made it work as expected.

### Making plugins load manually

For `prettier` to load plugins as expected from my testing with `pnpm` version `7.0.0` to `7.20.0`, its required to specify the `plugins` option in the `prettier` config:

```js
// .prettierrc.js

module.exports = {
  arrowParens: 'always',
  printWidth: 120,
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
  plugins: [require('prettier-plugin-tailwindcss')],
}
```

I also moved `prettier` config from JSON to JavaScript, to use `plugins: [require('prettier-plugin-tailwindcss')]` instead of `"plugins": ["prettier-plugin-tailwindcss"]` for text editors to resolve the plugins correctly as well. 

### Additional information

 - `node -v` prints: v18.0.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
I don't know why it doesn't work. Maybe an issue in prettier should be created.

**Comment by oedotme** [comment]
I found a related `prettier` issue here https://github.com/prettier/prettier/issues/8474

**Comment by oedotme** [comment]
There's a related `prettier` issue here https://github.com/prettier/prettier/issues/8474

**Comment by kwatanwa17** [comment]
I came across this thread when I was facing a similar issue. 
As the plugin page [prettier-plugin-tailwindcss#resolving-your-tailwind-configuration](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#resolving-your-tailwind-configuration) suggested, adding the following in my `.prettierrc.js` solved the issue.

```{javascript}
# .prettierrc.js or prettier.config.js
module.exports = {
  plugins: [require('prettier-plugin-tailwindcss')],
}

**Comment by oedotme** [comment]
Thanks for mentioning this, I'm already using the plugins by declaring them in `prettier` config, however the issue is about automatic `prettier` plugins loading after `pnpm` `7+` introduced `prettier` plugins hoisting.

**Comment by zkochan** [comment]
So you're saying that it breaks because we now hoist prettier [by default](https://pnpm.io/npmrc#public-hoist-pattern)? But we added this hoisting exactly to fix prettier issues (at least, so I thought). Have you tried disabling hoisting and did solve the issue?

**Comment by oedotme** [comment]
Not really, it's still behaving the same before and after `pnpm` hoisting.

The thing is I was expecting after hoisting, `prettier` would load plugins automatically but it didn't. That's why I opened this issue.

What I understand so far that `prettier` by default tries to find plugins only in the parent directory where `prettier` is installed and that works with `npm`. It's supposed to work with `pnpm` too after hoisting but it doesn't for some reason. i don't know if it's related to symlinking.

When I just replaced the `node_modules/prettier` installed with `pnpm` with another installed with `npm` it worked as expected.

**Comment by oedotme** [comment]
Not really, it's still behaving the same before and after `pnpm` hoisting.

The thing is I was expecting after hoisting, `prettier` would load plugins automatically but it didn't. That's why I opened this issue.

What I understand so far that `prettier` by default tries to find plugins only in the parent directory where `prettier` binary is executed and that works with `npm`. It's supposed to work with `pnpm` too after hoisting but it doesn't for some reason. I don't know if it's related to symlinking or because even after hoisting `prettier` still executes from `node_modules/.pnpm`.

When I just replaced the `node_modules/prettier` installed with `pnpm` with another installed with `npm` it worked as expected.

**Comment by noccer** [comment]
I can confirm I have also come across this issue today as a pnpm user.

Even happens when adding:
`[require('prettier-plugin-tailwindcss')]` to `.prettierrc.js`
or 
`"plugins": ["prettier-plugin-tailwindcss"]` to `.prettierrc`

**Comment by sanishchirayath1** [comment]
For it to work both prettier and prettier tailwind plugin must be in the same node modules folder. It is briefly mentioned here.. https://www.youtube.com/watch?v=_CntOc4hBcg . Maybe it is because of how pnpm handles files. I don't know much but would like input on how to solve this

**Comment by MuhammadM1998** [comment]
I'm having the same problem.
I reinstalled the deps with npm and yarn and it worked in them both but not with pnpm.

**Comment by AlanMorel** [comment]
Would love to see some kind of follow up to this, if at all possible. I'm sure the number of people using both prettier and pnpm has to be large and growing by the day.

**Comment by MuhammadM1998** [comment]
Is this fixed? I really want to use pnpm as my main package manager and this is what's stopping me

**Comment by oedotme** [comment]
Hey everyone, I wanted to highlight that `pnpm` already works with `prettier` and `prettier-plugin-tailwindcss` with a manual configuration step for `prettier`.

For that, I've updated the issue description to include **Making plugins load manually** section as a solution for this issue in the meanwhile.

**Comment by umaranis** [comment]
Hi,
I also ran into this issue. On debugging, I found that prettier is not able to locate the `node_module` folder for auto-loading plugins when using `pnpm`.

In the code for loading plugins, the current directory is identified as follows when the code works properly:
`__dirname`: `“/Users/umarxxxx/Projects/svelte-lexical/node_modules/prettier”`
And the folder for auto-loading modules is identified as:
`autoLoadDir`: `”/Users/umarxxxx/Projects/svelte-lexical/"`

In case of `pnpm`, the current directory is:
`__dirname`: `“/Users/umarxxxx/Projects/svelte-lexical/node_modules/.pnpm/prettier@2.3.2/node_modules/prettier”`
From this directory, prettier is not able to figure out `autoLoadDir`.

Here are the methods called from prettier codebase for loading prettier plugins and identifying the directories.

![Pasted Graphic](https://user-images.githubusercontent.com/2135071/221176158-a4a70d2d-3fe5-44ed-a29b-4de22b34cded.png)

![Pasted Graphic 2](https://user-images.githubusercontent.com/2135071/221176234-adb16b48-eb75-4c54-b307-1974da663b06.png)

### Resolution
Able to resolve this issue by setting `plugins` and `pluginSearchDirs` in `.prettierrc.json` file.

**Comment by amorfati254** [comment]
@umaranis Hello. Can you please show your prettier config. I am facing the same issue but dont know how to solve it. Help would be appreciated.

**Comment by umaranis** [comment]
@amorfati254 ,

Following is my prettier config where I am able to auto-load a plugin. `pluginSearchDirs` is the key to resolving the issue, it may differ for you.

```json
{
    "plugins": ["prettier-plugin-organize-attributes"],
    "pluginSearchDirs": ["../../../../"],
    "attributeGroups": ["$DEFAULT", "^data-"],
    "attributeSort": "ASC",
    "bracketSameLine": true,
    "htmlWhitespaceSensitivity": "ignore",
    "parser": "html"
  }
```

**Comment by vinkla** [comment]
Is there a possibility that this particular issue could be resolved by this pull request?

https://github.com/prettier/prettier/pull/14759

**Comment by karlhorky** [comment]
Yeah, if I'm understanding https://github.com/prettier/prettier/pull/14759 correctly, the next major version of Prettier (3.0.0) will have the plugin autoload / automatic search feature removed.

**Comment by oedotme** [comment]
Thanks everyone for the update! I'll close this issue as it was specific to automatically loading `prettier` plugins with `pnpm` and it's no longer relevant to have it opened as this feature is being removed.

I've been loading `prettier` plugins with `pnpm` manually for a while now and it works fine. For anyone still facing issues loading `prettier` plugins manually, please feel free to open an issue on `prettier` repo if there's no issue opened already.

Here's the config I'm using currently:
```js
// .prettierrc.js

module.exports = {
  arrowParens: 'always',
  printWidth: 120,
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  plugins: ['prettier-plugin-tailwindcss'],
}
```

**Comment by oedotme** [comment]
Hey @eldair, I'm not a vscode user myself. However this issue https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/113 seems relatable, have you checked it?

**Comment by oedotme** [comment]
@eldair here's a workaround here I came across at https://github.com/prettier/prettier/issues/13276 - it's specific to `@prettier/plugin-php` and it covers `vscode` as well. Hope that helps.

**Comment by eldair** [comment]
@oedotme thanks a lot!! I managed to make it work :)

**Comment by nathan-pham** [comment]
I encountered [#6793 ](https://github.com/prettier/prettier/issues/6793) earlier today and wanted to see if [prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc) would resolve my issue. Unfortunately, it doesn't seem like I can use any plugins with pnpm...

Manually using "Format document with" gives this popup:
![image](https://github.com/pnpm/pnpm/assets/43102813/02f4bc62-d518-475b-9bd0-a145b5d67067)

Just saving with "format on save" gives no errors in the extension logs but does nothing to the saved file (ie: semicolons or the trailing new line at the end of files not being added). I was also kind of expecting to see `["INFO" - <time>] Formatting completed in x ms.` but I don't see that either, so I assume something silently failed along the way. 
```
["INFO" - 9:13:23 PM] Using config file at 'c:\Users\<user>\OneDrive\Desktop\<project>\.prettierrc'
["INFO" - 9:13:51 PM] Formatting file:///c%3A/Users/<user>/OneDrive/Desktop/<project>/.prettierrc
```

For additional context:
```
pnpm -v
8.6.3
```

.prettierrc
```
{
    "plugins": ["node_modules/prettier-plugin-jsdoc"] 
    // also tried with just "prettier-plugin-jsdoc" and require and require.resolve
}
```

**Comment by FajarMaftuhFadli** [comment]
I am using the prettier v10.1.0 VSC Extension, I resolve this issue by adding `.prettierrc.json`:
```json
{
    "plugins": [
        "prettier-plugin-tailwindcss"
    ]
}
```
