### ISSUE TITLE
pnpm miss long package - error TS2304: Cannot find name Long

### ISSUE THREAD

**Issue by AxeemHaider** [pnpm/pnpm#4704]
### Code to reproduce the issue:
use pnpm and Install typescript and try to use `Long` it will give you compile error. 

but if you use npm it work perfectly no error on using `Long`

### Additional information:

 - `node -v` prints: v17.9.0
 - Windows, macOS, or Linux?: Linux, ubuntu

**Comment by mcmxcdev** [comment]
`Long` is not a valid type in `typescript`. You have to use `number`.
