### ISSUE TITLE
`ERR_PNPM_INCLUDED_DEPS_CONFLICT` started occurring in 7.0.1

### ISSUE THREAD

**Issue by BeeeQueue** [pnpm/pnpm#4705]
I looked into the code for this, and it doesn't seem like there have been any changes in the file that contains the code for the error, so I'm very confused why it started erroring _now_.

It would at least be nice with an option to disable it as many workflows are blocked by it, such as webpack applications which need webpack installed (a `devDep`) and then build with `NODE_ENV=production pnpm webpack`

### Code to reproduce the issue:

1. Create project with dev- and normal dependencies
1. Run `NODE_ENV=development pnpm i`
1. Run `NODE_ENV=production pnpm [script]`

### Expected behavior:

In previous versions this worked

### Actual behavior:

Errors with `ERR_PNPM_INCLUDED_DEPS_CONFLICT`.

### Additional information:

 - `node -v` prints: 14.19.1
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
Well, I am not sure what caused it because of the lack of details.

But maybe it was caused by this PR: https://github.com/pnpm/pnpm/pull/4676
We started to use Yarn's compat database to patch broken packages. 
Here you can see what packages we patch: https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts

If this is really caused by this, you might need to fix the conflicts because I don't think Yarn patched those package for no reason.

**Comment by BeeeQueue** [comment]
I am just as confused as you are about why it started happening, but the problem is still the conflicting installed packages error.

Like I said in the OP it's an error that doesn't make sense for a lot of workflows and should definitely have an option to be disabled

**Comment by zkochan** [comment]
You can disable it by allowing wider ranges for the peers, for example:

```json
{
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "react": "17"
      }
    }
  }
}
```
Read more: https://pnpm.io/package_json#pnpmpeerdependencyrulesallowedversions

**Comment by BeeeQueue** [comment]
This has nothing to do with peer dependencies. It's about running scripts in a different environment than they were installed with, leading to the error:

```
modules directory (at "...") was installed with dependencies, devDependencies. Current install wants dependencies
```

**Comment by zkochan** [comment]
Sorry, I have misread that error code.

I see, this should be fixed. This error shouldn't happen when a script is executed.

**Comment by lloydjatkinson** [comment]
Happening again in latest version of pnpm

**Comment by fantun3s** [comment]
This one is happening to me as well in a pnpm monorepo:
pnpm: 7.27.0
node: 16.19.0
os: macOS Ventura 13.2.1

**Comment by BeeeQueue** [comment]
I have not encountered this since I reported it.

**Comment by sandervspl** [comment]
I have just encountered this just now in a pnpm monorepo trying to run `pnpm dlx astro add tailwind` using pnpm v8.9.2

```
ERR_PNPM_INCLUDED_DEPS_CONFLICT  modules directory (at "/Users/......") was installed with optionalDependencies, dependencies, devDependencies. Current install wants optionalDependencies, dependencies.
```
