### ISSUE TITLE
pnpm changeset package cli checkboxes not interactive in v7

### ISSUE THREAD

**Issue by btakita** [pnpm/pnpm#4708]
### pnpm version:

v7

### Code to reproduce the issue:

pnpm changeset

### Expected behavior:

The cli checkboxes for each package should be interactive.

### Actual behavior:

The cli checkboxes for each package is static & not navigatable using the arrow keys & not selectable using the space bar.

### Additional information:

node -v prints: v18.1.0
arch linux 5.17.5-zen1-1-zen

**Comment by zkochan** [comment]
It seems to work for me. I use this command in the pnpm repository.

**Comment by btakita** [comment]
That's interesting. I am using tmux as well. The regression occurred in v7. v6 does not have this issue.

**Comment by zkochan** [comment]
I also use tmux.

**Comment by btakita** [comment]
Here's a screenshot

![image](https://user-images.githubusercontent.com/3664/168650722-75dd4f4d-9dbd-46f4-831b-ecdf71bf3fa5.png)

Filtering does seem to work

![image](https://user-images.githubusercontent.com/3664/168650913-099c322f-6257-48b5-aa67-075be973bde0.png)

**Comment by btakita** [comment]
Switching the terminal program from st to alacritty fixed the problem. This is an issue with st.
