### ISSUE TITLE
Git "authenticity of host" prompt text is overwritten or moved out of view

### ISSUE THREAD

**Issue by Swanty** [pnpm/pnpm#472]
### pnpm version:
v0.45.0

### Code to reproduce the issue:
If you run pnpm install on machine where ssh known_hosts file is not yet written then you will get prompt that asks to confirm the authenticity of host for private git hosted package.

One solution that I use right now is just use pnpm install --silent and then I can see that there is such a prompt, but not always we remember to add --silent

### Expected behavior:
Pause everything until user answers the prompt or somehow force to answer yes automatically?

### Actual behavior:
This text is being overwritten and/or moved out of view:

The authenticity of host '[redacted]:7999 ([redacted]:7999)' can't be established.
RSA key fingerprint is SHA256:+redacted.
Are you sure you want to continue connecting (yes/no)? yes

Sometimes you would run pnpm install and wonder "why is it frozen and not doing anything?" when in reality user is expected to type yes or no, but if that text is overwritten then how do you know that there is a user input waiting unless you pay attention to the screen from start to end?

### Additional information:

 - `node -v` prints:
v4.6.1
 - Windows, OS X, or Linux?:
Linux

**Comment by iamstarkov** [comment]
does npm ask and wait for user to answer the prompt?

**Comment by Swanty** [comment]
In the background yes the user input is still being expected which is why if you don't add --silent and you miss the text for the prompt then you might wonder why pnpm install is frozen

**Comment by Swanty** [comment]
Just checked, npm install also seems to be bugged. It asks for the user input, but overwrites the prompt text.

**Comment by zkochan** [comment]
Related to #354.

The reporter is now a separate package: https://github.com/pnpm/pnpm-default-reporter

And there is possibility of creating custom reporters because pnpm uses the ndjson format as output

**Comment by zkochan** [comment]
Is it better with latest pnpm? It has less output now. Logs only the status of the top-level dependencies

**Comment by zkochan** [comment]
This shouldn't be an issue anymore with the latest, really minimalistic pnpm output.

If it is, please reopen the issue or open a new one
