### ISSUE TITLE
Package name mismatch for aliased package in private registry

### ISSUE THREAD

**Issue by thasmo** [pnpm/pnpm#4724]
### pnpm version: pnpm@7.1.0

When running `pnpm install` with a populated pnpm-store the error `ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE` is shown for an aliased package coming from a private registry. Specifically it is the `gsap/business` package from Greensock aliased to the `gsap` package.

> ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-kJzSzrnGNrCAx0wCwNkHLc3rRckuebvfzWFLI5u+60mLDIm7jc986XUzS4+UnRuh1HCavALEuAsgWPqtVw8Low==","registry":"https://npm.greensock.com/","tarball":"https://npm.greensock.com/@gsap%2fbusiness/-/business-3.10.4.tgz"} from the store. This means that the lockfile is broken. Expected package: @gsap/business@3.10.4. Actual package in the store by the given integrity: gsap@3.10.4.

### Code to reproduce the issue:
**package.json**
```json
{
    "name": "boilerplate",
    "license": "UNLICENSED",
    "private": true,
    "engines": {
        "node": ">= 16",
        "pnpm": ">= 7"
    },
    "dependencies": {
        "gsap": "npm:@gsap/business@^3.9.0"
    }
}
```

**.npmrc**
```ini
engine-strict=true
shamefully-hoist=true
@gsap:registry=https://npm.greensock.com/
//npm.greensock.com/:_authToken=secret
```

### Expected behavior:
Installation of the specific package from the pnpm-store should work.

### Actual behavior:
Installation of the package from the pnpm-store fails.

### Additional information:
- pnpm: `7.1.0` (via corepack)
- node: `16.15.0`
- OS: Linux (platform.sh CI build environment)

**Comment by thasmo** [comment]
It seems that the issue only happens within the CI environment, it does not happen on my local machine.

**Comment by WormGirl** [comment]
I has the same problem. t need to use `pnpm store prune && pnpm install --ignore-scripts`

**Comment by Anoesj** [comment]
I have this too on a non-CI environment, but only on Ubuntu, not on macOS.
```
 WARN  Package name mismatch found while reading {"integrity":"sha512-YG1xjWe8HP6IDA2UT98xcsEVLt+6vJB2joyiYbc1RJLvXHeft/FYqlUKM0uRMOBpK1GSn2Ziq2JCaJwyrDZQVg==","registry":"https://npm.greensock.com/","tarball":"https://npm.greensock.com/@gsap%2fshockingly/-/shockingly-3.11.3.tgz"} from the store. This means that the lockfile is broken. Expected package: @gsap/shockingly@3.11.3. Actual package in the store by the given integrity: gsap@3.11.3.

ERR_PNPM_ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  The lockfile is broken! A full installation will be performed in an attempt to fix it.

 ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-YG1xjWe8HP6IDA2UT98xcsEVLt+6vJB2joyiYbc1RJLvXHeft/FYqlUKM0uRMOBpK1GSn2Ziq2JCaJwyrDZQVg==","registry":"https://npm.greensock.com/","tarball":"https://npm.greensock.com/@gsap%2fshockingly/-/shockingly-3.11.3.tgz"} from the store. This means that the lockfile is broken. Expected package: @gsap/shockingly@3.11.3. Actual package in the store by the given integrity: gsap@3.11.3.
```

**Comment by LucasDemea** [comment]
@Anoesj did you check that the installed gsap is the correct one ? I tried your workaround but it ends up installing simple gsap, without all the plugins. Basically, gsap gets installed, not gsap/shockingly.

**Comment by andrewmumblebee** [comment]
I'm also experiencing this issue with the @gsap registry with the business package. Weirdly works fine for the @fortawesome registry when using fontawesome/pro.

Have tried the override workaround but that still broke on Azure pipelines for me made sure gsap was installed under `dependencies` too.

`pnpm store prune` works but at that point i might as well removing the cache step from my pipeline, so for now i've had to remove any cache restoration from my Azure DevOps pipeline, which gets around this.

pnpm works fine with the private registry when deploying on Vercel.

**Comment by jvanoostveen** [comment]
I'm experiencing this locally as well with pnpm 8.6.6

**Comment by jvanoostveen** [comment]
Is there a workaround (other than prune) for this? Doing prune, it is faster just to stick to npm... :(

**Comment by jvanoostveen** [comment]
It took some effort, but I got Anoesj version working as it seems.

**Comment by Nuuou** [comment]
Oof!

Running into this same issue, and unfortunately the approach by Anoesj doesn't work consistently.
If you remove your project's `node_modules` folder, and re-run `pnpm i`, you'll occasionally still get this error even with `overrides` defined.

Is this fundamentally just an issue with GSAP, as the private `@gsap/business` and `@gsap/shockingly` packages still just call themselves `gsap` in their own `package.json` files?

**Comment by mattpilott** [comment]
```bash
 ERR_PNPM_ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  The lockfile is broken! A full installation will be performed in an attempt to fix it.
 ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-kYmkwAQ53GzBxs+e8pu/BCzUMrfJoBSEE1JI5HB6wUGDt9yuR/XTwSNfRCBzbuzy/zR9HgqubZnU59LhOiOzwA==","registry":"https://registry.npmjs.org/","tarball":"https://npm.greensock.com/@gsap/shockingly/-/shockingly-3.12.2.tgz"} from the store. This means that the lockfile is broken. Expected package: gsap@3.12.2. Actual package in the store by the given integrity: @gsap/shockingly@3.12.2.
```
I get this every single time i try to update deps `pnpm up -iL` i need to trash the lock file run `pnpm i` then `pnpm up -iL` very tedious

**Comment by XinChou16** [comment]
any solution to this whithout delete store cache ?

**Comment by Anoesj** [comment]
> ```shell
>  ERR_PNPM_ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  The lockfile is broken! A full installation will be performed in an attempt to fix it.
>  ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-kYmkwAQ53GzBxs+e8pu/BCzUMrfJoBSEE1JI5HB6wUGDt9yuR/XTwSNfRCBzbuzy/zR9HgqubZnU59LhOiOzwA==","registry":"https://registry.npmjs.org/","tarball":"https://npm.greensock.com/@gsap/shockingly/-/shockingly-3.12.2.tgz"} from the store. This means that the lockfile is broken. Expected package: gsap@3.12.2. Actual package in the store by the given integrity: @gsap/shockingly@3.12.2.
> ```
> 
> I get this every single time i try to update deps `pnpm up -iL` i need to trash the lock file run `pnpm i` then `pnpm up -iL` very tedious. I've only recently started getting this by the way, has worked for quite a long time without issue, unsure what changed.

Same here! I had to remove all `node_modules` directories from my monorepo setup, delete the pnpm lockfile and run `pnpm i` again. Then afterwards, I could run the updates again.

**Comment by prasannamestha** [comment]
@thasmo Could you try installing it without alias? Something like `pnpm add @gsap/business`?

**Comment by Anoesj** [comment]
@zkochan Could you take a look at this sometime soon? Since a while I get these more and more. At this point, I have to fully remove all my `node_modules` directories in a monorepo setup manually, delete the lockfile and then reinstall. And even that sometimes doesn't work. Locally, this is annoying, but not a major issue, but in CI it definitely is a dealbreaker.

**Comment by shaojingchao** [comment]
I had a similar problem and could try adding "node-linker=hoisted" to .npmrc.

**Comment by felixdenoix** [comment]
Similar problem here with GSAP. 
Versions:
pnpm@8.14.1
@gsap/shockingly@^3.12.5

**Comment by dagda1** [comment]
I have this issue with 

pnpm@9.1.2
@gsap/shockingly@^3.12.5

If I add a dependency anywhere in the monorepo, I get the `ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE` error and I have to run `pnpm store prune` before proceeding.`

This happens locally on the mac and on ubuntu when running github actions.  I have to run `pnpm store prune` before `pnpm install` in every github action

**Comment by zkochan** [comment]
@dagda1 is `@gsap/shockingly@^3.12.5` a private package? I cannot install it.

**Comment by dagda1** [comment]
> @dagda1 is `@gsap/shockingly@^3.12.5` a private package? I cannot install it.

Yes, it is private

**Comment by zkochan** [comment]
I don't have access to that project, so someone please test my fix from this PR: https://github.com/pnpm/pnpm/pull/8201

**Comment by zkochan** [comment]
As it was already mentioned in the thread, this happens because the gsap packages are published with a different name in the `package.json` inside the tarball.

The error that is thrown exists as a security measure. It also prevents some hard to detect errors that could happen if someone incorrectly resolves conflicts in a lockfile. Hence, I don't think muting the error is an option. I think GreenSock should fix the issue on their end. Especially as seems like a similar issue has been fixed in the npm registry. However, we can add a setting that will convert this error to a warning.

**Comment by dagda1** [comment]
@zkochan that option would be great.  I'll raise this with gsap.  Thanks for looking at this

**Comment by zkochan** [comment]
For now I am adding a new setting to ignore the error: https://github.com/pnpm/pnpm/pull/8212

In the future we might change the store structure to avoid such issues (related issue: https://github.com/pnpm/pnpm/issues/8204).

**Comment by renatoargh** [comment]
@zkochan can you explain how to use the flag you just created? I have version 9.4 already

![image](https://github.com/pnpm/pnpm/assets/522043/a22e86c0-8f13-4c13-9fe9-99d61f14da42)

**Comment by zkochan** [comment]
The issue will be gone in pnpm v10 if we make this change to the store: https://github.com/pnpm/pnpm/pull/8510
