### ISSUE TITLE
`pnpm update` breaks `pnpm fetch` and `pnpm install --offline`

### ISSUE THREAD

**Issue by llc1123** [pnpm/pnpm#4729]
I am using docker to build the project and after I switch to pnpm@7, the build process throws an error.

### Code to reproduce the issue:
Example package.json:
```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "@graphql-codegen/typescript": "^2.4.10"
  }
}
```
Dockerfile:
```dockerfile
FROM node:16-slim

RUN npm install -g pnpm@7.1.0
WORKDIR /test
COPY pnpm-lock.yaml package.json ./
RUN pnpm fetch
RUN pnpm install --offline
```

run `pnpm install` (`pnpm add` and `pnpm remove` also doesn't effect)
run `pnpm update`
run `docker build .`

### Expected behavior:
Docker image builds successfully.

### Actual behavior:
```shell
 > [6/6] RUN pnpm install --offline:
#10 0.768  ERR_PNPM_NO_OFFLINE_META  Failed to resolve @graphql-codegen/typescript@>=2.4.10 <3.0.0-0 in package mirror /root/.cache/pnpm/metadata/registry.npmjs.org/@graphql-codegen/typescript.json
------
executor failed running [/bin/sh -c pnpm install --offline]: exit code: 1
```

The error only happens after `pnpm update`.
Any `add` or `remove` after that will lead to a successful build.

I believe that the `pnpm update` breaks `pnpm-lock.yaml` even if all packages are up to date.

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: Windows 11 21H2 22000.675

**Comment by fapspirit** [comment]
@llc1123 hello, you closed your issue, did you figured out how to solve the problem? I have a similar case, but with `pnpm deploy`, I wonder if there is a workaround.

**Comment by llc1123** [comment]
I cannot reproduce the issue with the latest version. So I think it has
been resolved. But I didn't try `pnpm deploy`.
