### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by RedemptionC** [pnpm/pnpm#4733]
### Discussed in https://github.com/pnpm/pnpm/discussions/4732

<div type='discussions-op-text'>

<sup>Originally posted by **RedemptionC** May 14, 2022</sup>
Hi there,I'm trying to install pnpm on windows(10)
I installed it using npm `npm install pnpm -g`
it succeeded:
```
╰─ npm list -g --depth 0                                                                                          ─╯
C:\Users\namei\AppData\Roaming\npm
`-- pnpm@7.1.0
```
But I still can't use it:
```
╰─ pnpm                                                                                                           ─╯
pnpm: The term 'pnpm' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
I even tried rebooting windows,still doesn't work out 
what should I do ?</div>

**Comment by mika76** [comment]
@RedemptionC I'm struggling with this - can you tell me how you sorted it out?
