### ISSUE TITLE
The default `public-hoist-pattern` seems not working for package like `@1stg/eslint-config` and its dependencies

### ISSUE THREAD

**Issue by JounQin** [pnpm/pnpm#4741]
### pnpm version:

7.1.0

### Code to reproduce the issue:

`@1stg/app-config` requires `@1stg/common-config`, and then requires `@1stg/eslint-config` and then requires a lot of eslint related packages

### Expected behavior:

hoist all `eslint` related packages

### Actual behavior:

no hoisted

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: macOS

**Comment by kelly-tock** [comment]
I think this is related to an issue i'm having as well, which seems to be related to a much older issue. 

https://github.com/pnpm/pnpm/issues/1951

I have a shared eslint config as a local dependency, linked through workspaces. `@tock/eslint-config`. in a project workspace, i'm extending that esilnt config, and when I run the eslint cli, it can't find the plugins that the shared eslint config has listed as dependencies in its package.json. those are in node_modules in the `@tock/eslint-config` folder as I would expect them to be, but it's only looking in node modules in the root of the project?

**Comment by zkochan** [comment]
Regarding the initial issue. I have created an empty project and ran `pnpm add @1stg/app-config`. I see `@1stg/eslint-config` hoisted to the root of `node_modules`

![image](https://user-images.githubusercontent.com/1927579/169622765-8a840cdf-ffa6-4797-bd39-581d63d6fbb4.png)

In the worst case, if something doesn't work, use [`node-linker=hoisted`](https://pnpm.io/npmrc#node-linker)

**Comment by kelly-tock** [comment]
Thanks for the response. I have since also started from scratch in a mono repo I'm trying to move over to pnpm, and this was not an issue for me either. The repo I was in where I thought this was an issue was using rush and pnpm, but I haven't gotten back to that yet. QQ, what is the difference between the linker option and shamefully hoist/public hoisting pattern?

Still learning while I'm converting over.

**Comment by zkochan** [comment]
`node-linker=hoisted` creates a "classic" node_modules layout. Like the one created by npm or Yarn 1.

`shamefull-hoist` and the other hoisting settings are still using a symlinking node_modules structure but it also hoists non-direct dependencies using symlinks. This is a workaround that fixes most of the issues that happen due to pnpm's strictness.

**Comment by JounQin** [comment]
close `for pnpm@7.5.0`

**Comment by JounQin** [comment]
@zkochan See https://github.com/1stG/configs/pull/125

It does not hoist `@1stg/*` packages at all in their own workspace.

**Comment by JounQin** [comment]
I tried to use `node-linker=hoisted`, it seems `auto-install-peers=true` and `strict-peer-dependencies=false` not working with it.

```log
packages/eslint-config
├─┬ @angular-eslint/eslint-plugin
│ ├── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
│ └─┬ @angular-eslint/utils
│   ├── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
│   └─┬ @typescript-eslint/utils
│     ├── ✕ missing peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0"
│     └─┬ eslint-utils
│       └── ✕ missing peer eslint@>=5
├─┬ @angular-eslint/eslint-plugin-template
│ └── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
├─┬ @angular-eslint/template-parser
│ └── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
├─┬ @babel/eslint-parser
│ └── ✕ missing peer eslint@"^7.5.0 || ^8.0.0"
├─┬ @babel/eslint-plugin
│ └── ✕ missing peer eslint@>=7.5.0
├─┬ @typescript-eslint/eslint-plugin
│ ├── ✕ missing peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0"
│ └─┬ @typescript-eslint/type-utils
│   ├── ✕ missing peer eslint@"*"
│   └─┬ @typescript-eslint/utils
│     └── ✕ missing peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0"
├─┬ @typescript-eslint/parser
│ └── ✕ missing peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0"
├─┬ eslint-config-prettier
│ └── ✕ missing peer eslint@>=7.0.0
├─┬ eslint-config-standard
│ └── ✕ missing peer eslint@^8.0.1
├─┬ eslint-config-standard-jsx
│ └── ✕ missing peer eslint@^8.8.0
├─┬ eslint-config-standard-react
│ └── ✕ missing peer eslint@^7.12.1
├─┬ eslint-import-resolver-typescript
│ └── ✕ missing peer eslint@"*"
├─┬ eslint-plugin-css
│ └── ✕ missing peer eslint@>=7.0.0
├─┬ eslint-plugin-es-x
│ └── ✕ missing peer eslint@>=4.19.1
├─┬ eslint-plugin-eslint-comments
│ └── ✕ missing peer eslint@>=4.19.1
├─┬ eslint-plugin-import
│ └── ✕ missing peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8"
├─┬ eslint-plugin-jest
│ └── ✕ missing peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0"
├─┬ eslint-plugin-jsdoc
│ └── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
├─┬ eslint-plugin-json-schema-validator
│ └── ✕ missing peer eslint@>=6.0.0
├─┬ eslint-plugin-jsonc
│ └── ✕ missing peer eslint@>=6.0.0
├─┬ eslint-plugin-markup
│ ├── ✕ missing peer eslint@>=5.0.0
│ └─┬ eslint-plugin-utils
│   └── ✕ missing peer eslint@>=5.0.0
├─┬ eslint-plugin-mdx
│ ├── ✕ missing peer eslint@>=8.0.0
│ ├─┬ eslint-mdx
│ │ └── ✕ missing peer eslint@>=8.0.0
│ └─┬ eslint-plugin-markdown
│   └── ✕ missing peer eslint@>=6.0.0
├─┬ eslint-plugin-n
│ ├── ✕ missing peer eslint@>=7.0.0
│ └─┬ eslint-plugin-es
│   └── ✕ missing peer eslint@>=4.19.1
├─┬ eslint-plugin-prettier
│ └── ✕ missing peer eslint@>=7.28.0
├─┬ eslint-plugin-promise
│ └── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
├─┬ eslint-plugin-react
│ └── ✕ missing peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8"
├─┬ eslint-plugin-react-hooks
│ └── ✕ missing peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0"
├─┬ eslint-plugin-regexp
│ └── ✕ missing peer eslint@>=6.0.0
├─┬ eslint-plugin-simple-import-sort
│ └── ✕ missing peer eslint@>=5.0.0
├─┬ eslint-plugin-sonar
│ ├── ✕ missing peer eslint@"^7.0.0 || ^8.0.0"
│ └─┬ eslint-plugin-sonarjs
│   └── ✕ missing peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0"
├─┬ eslint-plugin-svelte
│ └── ✕ missing peer eslint@"^7.0.0 || ^8.0.0-0"
├─┬ eslint-plugin-toml
│ └── ✕ missing peer eslint@>=6.0.0
├─┬ eslint-plugin-unicorn
│ └── ✕ missing peer eslint@>=8.18.0
├─┬ eslint-plugin-vue
│ ├── ✕ missing peer eslint@"^6.2.0 || ^7.0.0 || ^8.0.0"
│ └─┬ vue-eslint-parser
│   └── ✕ missing peer eslint@>=6.0.0
└─┬ eslint-plugin-yml
  └── ✕ missing peer eslint@>=6.0.0
✕ Conflicting peer dependencies:
  eslint  

 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/zone.js/0.11.6' in pnpm-lock.yaml

This issue is probably caused by a badly resolved merge conflict.
To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
```
