### ISSUE TITLE
Error-specific exit codes for named (ERR_PNPM) errors

### ISSUE THREAD

**Issue by elliot-nelson** [pnpm/pnpm#4747]
### FEATURE REQUEST

I'd like to have error-specific exit codes for known error types (e.g. the ones listed in https://github.com/pnpm/pnpm/blob/948a8151eda6454051d3da347ee8776b3ce8028a/packages/default-reporter/src/reportError.ts#L36-L63).

For example, if an `ERR_PNPM_PEER_DEP_ISSUES` is encountered, the exit code might be `25` instead of `1`.

This would help tool authors who execute `pnpm` (for example, Rush) distinguish between an error that could potentially be fixed by retrying, and one that cannot, without having to parse the output (which can be quite large).

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### POSSIBLE SOLUTION

My suggestion is to assign somewhat meaningless but unique positive exit codes to each named error (`ERR_PNPM_`), and wire it up so the assigned exit code will be used instead of `1` if the error occurs.

Some categorization of errors into buckets might be interesting (e.g. if `3` meant a certain _class_ of errors), but, it's hard for pnpm to discern the context -- it could be that because the tool is calling a specific pnpm command with a specific set of flags, that it knows one specific error is retryable, even though it generally wouldn't be). So I don't know if bucketing errors is a good use of time.

It's possible there could be more than one error (in theory? maybe generated while handling a different error?).  In this case I'd be OK with the result being whatever is easiest to implement -- maybe last error generated wins.

**Comment by zkochan** [comment]
I don't have objections but I don't know if this is good practice or not. Could this cause issues?

cc @pnpm/collaborators

**Comment by elliot-nelson** [comment]
In my opinion, it's a pretty common practice, with some caveats:

 - The node runtime itself carves out [a few standard exit codes from 2-13](https://nodejs.org/api/process.html#exit-codes).
 - In Linux/BSD, [exit codes 64+ have legacy meanings](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/refs/heads/jb-dev/sysroot/usr/include/sysexits.h).
 - Windows also has some special exit codes but Windows exit codes are oddballs like 9009 (up in the thousands), so they aren't an issue.

My suggestion would be to stick to exit codes in the range 16-63 and you are pretty much guaranteed not to clash with any other expectations, and they'd be equally easy to check for in Batch, PowerShell, and Bash scripts.

**Comment by zkochan** [comment]
> This would help tool authors who execute pnpm (for example, Rush) distinguish between an error that could potentially be fixed by retrying, and one that cannot, without having to parse the output (which can be quite large).

I am not sure what type of error could be fixed by retrying. pnpm already retries in those cases.

**Comment by kenrick95** [comment]
I feel that this is will be tricky to maintain so that pnpm doesn't have conflicting error codes with the ecosystem (be it OS, Node, or any other tools or scripts).

Furthermore, not all of these error cases can have their own custom error codes. For example, if I run `pnpm recursive run something`, and the "something" script returns non-zero error code, I would get `ERR_PNPM_RECURSIVE_FAIL` error and I would expect to get that script's error code, not pnpm's custom error code.

**Comment by elliot-nelson** [comment]
Thanks all -- in Rush, we ended up changing the default pnpm install attempts from 3 down to 1, because we weren't able to come up with a good case for when pnpm would fail in a non-deterministic way that also warranted a retry. So, closing for now!
