### ISSUE TITLE
pnpm link --global for a dependency with a bin prints unexpected warning

### ISSUE THREAD

**Issue by runspired** [pnpm/pnpm#4761]
pnpm version 7.1.1

Take a project with a simple file at `bin/command.mjs`

```js
#!/usr/bin/env node

console.log("hello world");
```

Configure it via the `bin` field of that project's `package.json` file.

```json
  "bin": { "myCommand": "./bin/command.mjs" }
```

Install this local project globally.

```js
pnpm link --global
```

Unexpected output:

```
 WARN  undefined has no binaries
```

The associated bin file is available as expected despite this warning.

**Comment by wenshiqi0** [comment]
when to fix this??????

**Comment by vortesnail** [comment]
same problem

**Comment by khusseini** [comment]
Same problem with version `pnpm 8.2.0`, `npm: '9.6.2'` and `node: '18.15.0'`

**Comment by NoriSte** [comment]
Same problem with version `pnpm 7.32.4`, `npm: 9.6.4`, and `node: 20.1.0`.

**Comment by fmorroni** [comment]
Any news on a solution? Still having the same problem on `pnpm 8.9.2`

**Comment by thomascclay** [comment]
Same issue. Latest pnpm 8.10.0 and node 20.9.0 w/ npm 10.1.0

**Comment by benkrakar** [comment]
same problem 💢

**Comment by benweint** [comment]
Just noting that I encountered this same issue with `pnpm` itself, following the instructions in the [`CONTRIBUTING.md`](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md) file:

> Run pnpm link --dir ./pnpm/dev -g to make pnpm from the repository available in the command line via the pd command.

Trying to follow those instructions yields:

```
❯ pnpm --version
8.12.1

❯ git log --pretty --oneline -n 1
99fd38bf2 (HEAD -> main, origin/main, origin/HEAD) style: fix

❯ cat ./pnpm/dev/package.json 
{
  "name": "pd",
  "version": "1.0.0",
  "bin": "pd.js",
  "private": true
}

❯ pnpm link --dir ./pnpm/dev -g
 WARN  link:/Users/ben/src/pnpm/pnpm/dev has no binaries
```

**Comment by paulocoghi** [comment]
Same issue on latest `pnpm`, `npm` and `node` _(as of 29 Dec 2023)_:

- pnpm: 8.13.1
- npm: 10.2.4
- node: 21.5.0

**Comment by paulocoghi** [comment]
The PR https://github.com/pnpm/pnpm/pull/4793, from @spencer17x, seems to fix this issue and just needs a little attention and love from the reviewers/maintainers :)

**Comment by dribble-njr** [comment]
same issue:
- pnpm: 8.14.0
- node: 20.10.0
- npm: 10.2.3

**Comment by mblouka** [comment]
This is STILL happening, and has been happening for close to a year now. This hinders the development of local cli tools in NodeJS.

**Comment by LuudJanssen** [comment]
@zkochan I tested this on v8.15.2 and it doesn't seem to be fixed. I'm still seeing the same warning as before. In my case it prints:

```
 WARN  link:<path-to-package> has no binaries
```

I'm using workspaces, my package has a name and it's private. Maybe this helps debug the issue further.

**Comment by rhumbertgz** [comment]
Still happening in `8.15.5`

**Comment by ahmetkuslular** [comment]
although I unlinked the package from the list, the package was visible . so uninstalling and linking it again does not give an error https://pnpm.io/cli/unlink

check it
`pnpm list --global`

uninstall
`pnpm uninstall --global <package>`

link again
`pnpm link --global`

**Comment by MBearo** [comment]
> although I unlinked the package from the list, the package was visible . so uninstalling and linking it again does not give an error https://pnpm.io/cli/unlink
> 
> check it `pnpm list --global`
> 
> uninstall `pnpm uninstall --global <package>`
> 
> link again `pnpm link --global`

This is work for me.

**Comment by basicButtons** [comment]
Still happening in  9.1.1

**Comment by ldt1997** [comment]
same problem in 8.11.0 🤔

**Comment by leoalipazaga** [comment]
Any update? Still happening in `8.6.2`

**Comment by mattpocock** [comment]
Still happening in 9.7.1. Apologies for the +1, this is relatively urgent for me.

**Comment by artsiommiksiuk** [comment]
Same here. ```install```, ```link```, reinstall into global - all gives the same results.

**Comment by zkochan** [comment]
I do see the warning but the CLI becomes available in the terminal, so it looks like the warning should not be printed. You can just ignore the warning as it works.

**Comment by mattpocock** [comment]
@zkochan Same issue still present on 9.10.0

**Comment by rofrol** [comment]
> @zkochan Same issue still present on 9.10.0

yep. 9.10 released on Sep 9, 2024. fix done on Sep 16, 2024. so no release with fix yet.

**Comment by zkochan** [comment]
:ship: 9.11
