### ISSUE TITLE
pnpm hangs when adding a github repo as dependency

### ISSUE THREAD

**Issue by Ploppz** [pnpm/pnpm#4764]
### pnpm version:
`7.1.0`
### Code to reproduce the issue:
Either of these:
* `pnpm add https://github.com/SeleniumHQ/selenium`
* `pnpm add github:SeleniumHQ/selenium`
* Add to `package.json`: `"selenium-webdriver": "SeleniumHQ/selenium",`, then run `pnpm i`
### Expected behavior:
I expect it to install the package (and add it to package.json in the two first cases)
### Actual behavior:
It simply hangs after a second.
For me, it's hangs with this text: `Progress: resolved 43, reused 43, downloaded 0, added 0` (since I have a few other dependencies already)

### Additional information:

 - `node -v` prints: `v17.9.0`
 - Windows, macOS, or Linux?: Arch Linux

**Comment by zkochan** [comment]
This should work with the latest pnpm.

**Comment by Ploppz** [comment]
Yep, you're right, thanks.
