### ISSUE TITLE
[BUG] Run command for each workspace folders, but exclude workspace root

### ISSUE THREAD

**Issue by vitalics** [pnpm/pnpm#4773]
### Discussed in https://github.com/pnpm/pnpm/discussions/4771

<div type='discussions-op-text'>

<sup>Originally posted by **vitalics** May 20, 2022</sup>
Hi all, I create a simple monorepo example with following structure.
``` txt
<root>
`-apps
  `- myApp1
    `-package.json (has build command)
  `- myApp2
    `-package.json (has build command)
`-packages
  `- package1
    `-package.json (has build command)
  `- package2
    `-package.json (has build command)
`pnpm-workspace.yaml
`package.json (no build command)
```

I'll try to use pnpm build (from `root` folder) and it's always failed. I also try to combinate with option `if-present`
The strage thing happen in case if i define `build` command  in root package.json file(e.g. `echo BUILD`)
OUTPUT:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/8816260/169526145-9c0c87cb-8fdd-42cc-a514-b6921e09578f.png">

pnpm-workspace.yaml
<img width="842" alt="image" src="https://user-images.githubusercontent.com/8816260/169526561-562016c5-f176-42b0-a6d0-1b38facb0f5c.png">

The question is about: How I can run build command and execute recurively in folders, but avoid root folder

pnpm version 7.0.0
nodejs v16.15.0
npm 8.5.5</div>

**Comment by zkochan** [comment]
According to the [docs](https://pnpm.io/cli/recursive), this should work as you'd expect:

```sh
pnpm -r --if-present --stream run build
# or
pnpm -r --if-present --stream build
```
