### ISSUE TITLE
Some commands should be able to run in folders using other package manager

### ISSUE THREAD

**Issue by unional** [pnpm/pnpm#4781]
### pnpm version:

7.0.0, 7.1.3

### Code to reproduce the issue:

run `pnpm -v` in a folder with `package.json/packageManager: "yarn@3.2.1"` 

### Expected behavior:

the command will work while can still print out the warning `This project is configured to use yarn`

### Actual behavior:

```sh
Usage Error: This project is configured to use yarn

$ pnpm ...
```

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: Windows 11

**Comment by zkochan** [comment]
This looks like an issue with [corepack](https://github.com/nodejs/corepack), not pnpm.

**Comment by unional** [comment]
Oh, didn't know that is emitted by corepack.
It probably will not have context about which command can be allowed and which cannot.
So seems like not a fixable issue.

**Comment by zkochan** [comment]
I don't know if it is fixable but for sure not fixable by us.
