### ISSUE TITLE
symlink for bin files when `node-linker=hoisted`

### ISSUE THREAD

**Issue by alimo** [pnpm/pnpm#4782]
**Describe the user story**

When using [CodePush](https://github.com/microsoft/react-native-code-push) for React Native, the [App Center CLI](https://github.com/microsoft/appcenter-cli) issues the following command to publish a new release:

```bash
node node_modules/.bin/react-native bundle ...
```

This command assumes the bin file is a JS file and can be executed with node. This is true when using npm or classic yarn. But with pnpm (as you have described in the limitations section of the docs), binstubs are shell files. So the following error happens:

```
/path/to/node_modules/.bin/react-native:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

Providing an option to use symlinks instead of shell files for binstubs would solve this problem.

**Describe the solution you'd like**

Two solutions are possible:
1. When using `node-linker=hoisted` in the `.npmrc` file, pnpm can automatically use symlinks instead of shell scripts to match more closely with npm and classic yarn behavior.
1. Add a setting to `.npmrc` to opt-in for this feature.

**Describe the drawbacks of your solution**

Solution 1:
- Some existing projects or scripts using `node-linker=hoisted` might rely on the binstubs being shell files.

Solution 2:
- If `node-linker` is not set to `hoisted`, this setting could break bin files and scripts since `NODE_PATH` is not being set. (This could be solved by showing a warning/error to users)

**Describe alternatives you've considered**

I've worked around the issue described in the user story section by manually modifying the `.bin/react-native` file. But this change is temporary and will be overridden by pnpm.

**Comment by zkochan** [comment]
I am not against such setting, but it would not work on Windows. Even npm uses command shims on Windows because executable symlinks are not allowed on Windows.

**Comment by alimo** [comment]
The "App Center CLI" I mentioned, treats Windows differently because of that. So if npm uses shims on Windows, pnpm could do the same.

I know what I'm asking for is very specific. But the goal here is to increase compatibility with npm. Which would benefit people (including me) porting their projects (like React Native ones) from npm/yarn to pnpm.

Although this whole issue isn't a blocker for me and the performance gain is much greater than the burden of manually changing a file every once in a while.
