### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by tjx666** [pnpm/pnpm#4786]
### pnpm version:

7.1.3

### Code to reproduce the issue:

1. clone git@github.com:tjx666/electron-vue-vite-boilerplate.git
2. `pnpm install`

### Expected behavior:

No error.

### Actual behavior:

I have install the typescript in root workspace devdenpendencies.

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

packages/app
└─┬ vue-tsc
  └── ✕ missing peer typescript@"*"
Peer dependencies that should be installed:
  typescript@"*"  
```

### Additional information:

- MacOS: 12.3.1
- Node: v16.15.0

**Comment by bgondy** [comment]
Maybe related to #4469 ?

**Comment by zkochan** [comment]
Peer dependencies are not resolved from the root of the workspace. Either install them as dependencies of the project or use `auto-install-peers=true`.

**Comment by tjx666** [comment]
> Peer dependencies are not resolved from the root of the workspace. Either install them as dependencies of the project or use `auto-install-peers=true`.

I can't understand this. One of the most advantage of monorepo is sharing the dependencies between the worspace, why I still install it as dependencie of the sub workspace.

**Comment by tjx666** [comment]
@zkochan
