### ISSUE TITLE
--no-install is not in the npm registry

### ISSUE THREAD

**Issue by qq2627767202** [pnpm/pnpm#4790]
### Code to reproduce the issue:
commit git, there is a pnpm error，why？？？？？？The two are completely unrelated
```
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/--no-install: Not Found - 404
--no-install is not in the npm registry, or you have no permission to fetch it.
```
![image](https://user-images.githubusercontent.com/31646567/169984193-a83f0b8b-db1a-4dda-a827-132aa83a21eb.png)

### Additional information:

 - `node -v` prints: v14.19.0
 - Windows11

**Comment by zkochan** [comment]
You have some githook that runs pnpm.

**Comment by qq2627767202** [comment]
![image](https://user-images.githubusercontent.com/31646567/169985542-e75d7e5f-5c18-4562-80d0-05f314ebf444.png)
this question

**Comment by qq2627767202** [comment]
Are you ready to adapt this tool?

**Comment by phyzess** [comment]
I don't know what version of husky you are using, but I guess it is 4?
Husky 4 seems not to support pnpm that well, and I also ran into this issue yesterday.
You can bypass this problem by using `--no-verify` when committing.
To resolve this you should refer to this [article](https://github.com/typicode/husky-4-to-8) and migrate your husky to 8, then use new .husky to hook your git.

**Comment by qq2627767202** [comment]
ok, Thanks

**Comment by zkochan** [comment]
I think this is an issue in an old husky version. Just update husky to the latest version.

**Comment by wr-ssingh1** [comment]
> I think this is an issue in an old husky version. Just update husky to the latest version.

I have updated husky and still seeing same issue. Any fix for this?

**Comment by BH-M87** [comment]
Same problem

**Comment by zkochan** [comment]
You need to update husky to the latest version and maybe run `pnpm husky install`. Maybe your hooks were created by an older version of husky.

**Comment by ycjcl868** [comment]
same problem

**Comment by jawang94** [comment]
I believe the cause of this is - in your project's `.git/hooks/husky.sh/` if you scroll down to `case $packageManager in`, you'll see that husky is by default configured to run PNPM with `pnpx --no-install`. [pnpx is deprecated](https://pnpm.io/6.x/pnpx-cli) and one should prefer to use `pnpm dlx` or `pnpm exec` instead.

**Comment by Silvia813** [comment]
I solved by downgrading version of pnpm from 7.3.0 to 6.32.23

**Comment by IPWright83** [comment]
Has anyone got a fix for this using the latest version of pnpm?

**Comment by CamilleHbp** [comment]
I am using `pnpm dlx` with `pnpm v7.8.0` and `husky v8.0.1` and yet I have the same error. Is there any progress on this? Thanks you very much! 🙏

**Comment by Penggeor** [comment]
The same problem occurs in my windows but **not** in my MacOS. I think this is associated with the platform. @zkochan

**Comment by IPWright83** [comment]
I believe I ended up re-installing/initialising the latest version of Husky and this problem went away. I'm certainly not suffering from it anymore. It was a bit of effort mind as husky only uses bash files now instead of the JS files that we were using.

**Comment by songStar0904** [comment]
> You need to update husky to the latest version and maybe run `pnpm husky install`. Maybe your hooks were created by an older version of husky.

Hi, I solved this problem by using `pnpm husky install`. I would like to ask what `pnpm <pkg> install` does and how it differs from `npm  install <pkg>` or `pnpm add <pkg>`？

**Comment by dotennin** [comment]
> For `pnpm husky install` & `npx husky install` failed users, `pnpm dlx husky install` works well.

Thanks , `pnpm dlx husky install`  works for me.

**Comment by liuliangsir** [comment]
@YunYouJun In some cases `pnpm script-name` is identical to `pnpm run script-name` only for scripts that do not share the same name as already existing pnpm commands according to [documentation](https://pnpm.io/cli/run#examples). In addtion, `pnpm executable` like `pnpm eslint` is the same as `node ./node_modules/eslint/bin/eslint.js` when installing eslint as devDependencies or dependencies.

**Comment by afu1995** [comment]
> For `pnpm husky install` & `npx husky install` failed users, `pnpm dlx husky install` works well.

THANK YOU!

**Comment by richenlin** [comment]
> For `pnpm husky install` & `npx husky install` failed users, `pnpm dlx husky install` works well.

THANK YOU!

**Comment by frankli2021** [comment]
> to 6.32.23

how to downgrade version, thank you
