### ISSUE TITLE
run `pnpm -v` always show 7.0.0-beta.2, this is not the actualy version of pnpm, actually i used 7.1.5, how to get the actualy version of pnpm ?

### ISSUE THREAD

**Issue by WormGirl** [pnpm/pnpm#4791]
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
`pnpm -v` will always show the actual version. You probably had some configuration issue. Try removing pnpm like described here: https://pnpm.io/installation#troubleshooting

**Comment by WormGirl** [comment]
I found the problem because I had several pnpm installed，I use shell, npx, pnpm, the actualy I used is insatalled by shell, but i update it use npx.
