### ISSUE TITLE
pnpm does not use $PNPM_HOME which I set.

### ISSUE THREAD

**Issue by zhibuba** [pnpm/pnpm#4797]
### pnpm version:
7.1.5
### Code to reproduce the issue:

![image](https://user-images.githubusercontent.com/55994840/170218903-a14b5eeb-daaf-477f-b30a-827eef22324a.png)

### Expected behavior:
pnpm should install the global package in $PNPM_HOME

### Actual behavior:
pnpm  install the global package in ~/.local/share/pnpm/global/5, which is not in PATH

### Additional information:
I use nvm and corepack. 
I just update pnpm from v6 to v7, the $PNPM_HOME I set is where the gloalbal packages installed by v6 are installed 

In my .zshrc: 
![image](https://user-images.githubusercontent.com/55994840/170219052-f29d955e-c186-4424-9469-5f1b0b8b21c2.png)

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
The location set in PNPM_HOME is only used for the global bin files location. The location of the global package's source files is controlled by the `global-dir` setting.
