### ISSUE TITLE
Code of conduct is not reflecting maintainers behaviour

### ISSUE THREAD

**Issue by npupko** [pnpm/pnpm#4800]
This is the follow up for the https://github.com/pnpm/pnpm/issues/4498
![image](https://user-images.githubusercontent.com/5938539/170270661-ea58909c-e425-4082-9280-23cb44c8e9f1.png)

I do not support any military action and I believe that open source should be a refuge from all this horror and a point of unification for all people.

[Сode of conduct:](https://github.com/pnpm/pnpm/blob/main/CODE_OF_CONDUCT.md)
> In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a **harassment-free** experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, **nationality**, personal appearance, race, religion, or sexual identity and orientation.

Please describe the obvious discrimination against Belarusian and Russian developers in the Code of Conduct. Thanks!

Also, just wondering, how developers from BLR and RU personally offend @zkochan and what he is going to do with contributors from these countries. (I.e. @andreypopp and other?)

**Comment by MaxGraey** [comment]
At the moment the war is not only on the ground but also in the information space. Traffic from Russia and Belarus is a potential threat to many Ukrainian resources or projects maintained by Ukrainian developers. I can assume that the restriction of traffic from these countries is temporary and may have a preventive nature (for example, to avoid DDoS attacks for example).
