### ISSUE TITLE
The "pnpm list" command does not account for depth when caching

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#4814]
While working on https://github.com/pnpm/pnpm/issues/4154, I noticed a bug in `pnpm list` that's the result of not incorporating depth into an internal `dependenciesCache` object.

### pnpm version: 7.1.6

The outputs below are from running `pnpm list --depth=2` at the root of this repository and omitting extra output for brevity.

### Actual behavior:

Since `@babel/types` is already visited at the max depth of 2 (through `@babel/core -> @babel/generator -> @babel/types`), the dependencies of `@babel/types` are not printed when it's visited again through `@babel/core -> @babel/types`.

```
❯ pnpm list --depth=2

@babel/core 7.18.0
├─┬ @babel/generator 7.18.0
│ └── @babel/types 7.18.0
└── @babel/types 7.18.0
```

### Expected behavior:
```
❯ pnpm list --depth=2

@babel/core 7.18.0
├─┬ @babel/generator 7.18.0
│ └── @babel/types 7.18.0
└─┬ @babel/types 7.18.0
  ├── @babel/helper-validator-identifier 7.16.7
  └── to-fast-properties 2.0.0
```

### Additional information:

 - `node -v` prints: 18.0.0
 - Windows, macOS, or Linux?: macOS

### Explanation

I believe the problem is because `dependenciesCache` caches entire `PackageNode` trees without information on whether or not deeper recursion is necessary. When the `packageAbsolutePath` key is seen again, this code path improperly assumes it's fully visited.

https://github.com/pnpm/pnpm/blob/b18371400ead7764d542520bab6ab7f42fa83f05/packages/dependencies-hierarchy/src/index.ts#L305-L314

**Comment by gluxon** [comment]
A proper fix to this would cause `pnpm list` to be slower (all else being equal) since it's not traversing deep enough at the moment. Is that acceptable, or should we consider this bug working as intended due to performance tradeoffs?

I personally feel correctness is more important than performance.

**Comment by gluxon** [comment]
Hey @zkochan, do you have thoughts on whether the slowdown is worth the correctness improvements here? Thanks! Understand if this bug isn't a priority for pnpm at the moment.

**Comment by zkochan** [comment]
So there would be no cache or the cache would check depth?

**Comment by gluxon** [comment]
The cache would account for depth. That could be done in 2 ways:

1. Most ideal would be if we only cache 1 level of the dependency graph at a time rather than entire subgraphs. Caching entire subgraphs is a bit suboptimal since we'd have to recalculate that subgraph if it's ever visited again at a different depth level. I think this would be a big refactor of the `pnpm list` code, but doable.
2. We keep track of the depth level when caching subgraphs, and recompute if the desired depth is greater than the last cached depth. I can see this implementation becoming overly complex if the traversal algorithm ever visits a subgraph computed at a higher depth than the currently requested one though.

**Comment by zkochan** [comment]
I don't have objections
