### ISSUE TITLE
auto-install-peers=true is not working

### ISSUE THREAD

**Issue by shezhangzhang** [pnpm/pnpm#4820]
### Code to reproduce the issue:
pnpm config set auto-install-peers=true
pnpm i

<img width="758" alt="image" src="https://user-images.githubusercontent.com/26793777/170950202-15dcbe0d-da8e-471d-ba3f-e115256413c5.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/26793777/170949613-d69da168-1668-4e70-9da9-db3dc1078558.png">

when I used npm, It works fine, I did't change anything, it just break, it's disgusting.

### Expected behavior:
green
### Actual behavior:
red
### Additional information:

 - `node -v` prints:v16.14.0
 - Windows, macOS, or Linux?: mac m1 pro

**Comment by shezhangzhang** [comment]
P.S: I don't want to change any files. Because these are open source projects, I don't want to add some specific config just for pnpm. This will bother other developers.

**Comment by zkochan** [comment]
Looks like a bug. You can install regenerator-runtime as a dev dependency for now.

**Comment by shezhangzhang** [comment]
As a new user to pnpm, I'm sorry. 😟

**Comment by grug** [comment]
I'm also experiencing this issue

**Comment by shezhangzhang** [comment]
> I'm also experiencing this issue

So I gave up, I use yarn, it is stable. @grug

**Comment by zkochan** [comment]
You use Yarn, which doesn't have this feature?

**Comment by shezhangzhang** [comment]
I don't know what is under the hood, as a user, no error is always better :)

**Comment by GrapevineLin** [comment]
I'm also experiencing this issue
I have written `auto-install-peers=true` to root `.npmrc`, but it not work at all.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/39358110/190329827-5f630dc9-c3d4-4484-894f-a07206258670.png">

**Comment by zkochan** [comment]
ok, this is reproducing it: https://github.com/zkochan/pnpm-issue-4820

**Comment by naftalimurgor** [comment]
Still experiencing the same issue

**Comment by hansiemithun** [comment]
is there a fix for this?
I am also facing same issue 

node version: **16.20.0**
npm version: **8.19.4**
pnpm version: **8.6.3**
os: **macos monterey 12.6.3**

<img width="504" alt="Screenshot 2023-06-21 at 1 30 25 PM" src="https://github.com/pnpm/pnpm/assets/3661669/4df494dc-e0bd-4593-8e1e-119382b121e9">

**Comment by naftalimurgor** [comment]
> is there a fix for this?
> I am also facing same issue 
> 
> node version: **16.20.0**
> npm version: **8.19.4**
> pnpm version: **8.6.3**
> os: **macos monterey 12.6.3**
> 
> <img width="504" alt="Screenshot 2023-06-21 at 1 30 25 PM" src="https://github.com/pnpm/pnpm/assets/3661669/4df494dc-e0bd-4593-8e1e-119382b121e9">
> 

Port your project over to yarn workspace equivalent of pnpm workspace l

**Comment by zkochan** [comment]
> Port your project over to yarn workspace equivalent of pnpm workspace l

This suggestion doesn't make sense in this issue. Do you realise that Yarn doesn't even install peer dependencies automatically?

**Comment by naftalimurgor** [comment]
Yes you are right. I'll dig into peer dependencies in Yarn. I haven't run into issues with peer dependencies using Yarn

**Comment by zkochan** [comment]
@hansiemithun pnpm will not install automatically webpack, if it cannot resolve it to a version that satisfy all dependencies requiring webpack. You can install webpack yourself in this case.

I am locking this thread because there is no valuable input here. The initial issue that I was able to reproduce was fixed.

If you have other issues create a new issue with steps to reproduce.
