### ISSUE TITLE
PNPM fails silent with github link (yarn to pnpm migration)

### ISSUE THREAD

**Issue by loeffel-io** [pnpm/pnpm#4822]
### pnpm version:

7.1.7

```json
  "devDependencies": {
    "@ls-lint/ls-lint": "^1.11.2",
    "termynal": "ines/termynal#master",
    ...
```

**Comment by loeffel-io** [comment]
link #20

**Comment by loeffel-io** [comment]
tried everything: https://pnpm.io/cli/add#install-from-git-repository
full blocker for the team for a great migration..

**Comment by zkochan** [comment]
Looks like the issue is that https://github.com/ines/termynal doesn't have a `package.json` file.
