### ISSUE TITLE
Config to silence all peer dependency warnings

### ISSUE THREAD

**Issue by TravisJRyan** [pnpm/pnpm#4835]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
As a developer, I want to migrate a number of projects to pnpm from previously using npm 7 with the `legacy-peer-deps` flag. There are many peer dependency warnings which I know are safe, and I want a common configuration to silence these warnings to decrease noise on install without having to explicitly list all the missing peers / mismatch version issues in each repository. It would be nice if there were one flag to silence all of these.

This is how npm operates with the `legacy-peer-deps` flag so it can be seen as an equivalent feature when coupled with `strict-peer-dependencies=false`.

**Describe the solution you'd like**
A config `silence-peer-warnings` for the[ .npmrc peer dependencies settings](https://pnpm.io/npmrc#peer-dependency-settings) which would skip peer dependency warnings altogether, exactly like `npm` with the `--legacy-peer-deps` flag. It should likely only work if  `strict-peer-dependencies` is false.

**Describe the drawbacks of your solution**
The major drawback is choosing to use this flag generates risk for the user, which is why it would need to be opt-in. 

**Describe alternatives you've considered**
We could support pattern matching in [peerDependencyRules](https://pnpm.io/package_json#pnpmpeerdependencyrulesignoremissing). This could make it easier to control peer dependency ignores without the danger of a blanket ignore flag, such as any `react*` peer dependency being okay to ignore, etc. The downside is the pattern matching could confuse users and alter the already understood API for these rules. It may need to be a new property which would clutter and complicate the understanding of the logic.

**Comment by zkochan** [comment]
> We could support pattern matching in [peerDependencyRules](https://pnpm.io/package_json#pnpmpeerdependencyrulesignoremissing).

This sounds better. Muting these warnings is not a good solution. The peer dependency warnings are useful.
