### ISSUE TITLE
Customize all dir

### ISSUE THREAD

**Issue by bernardoadc** [pnpm/pnpm#4836]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

My company has a strict policy on what can be put at user's home dir. For instance, everything there will sync with OneDrive. This has made my computer very very slow. As a solution, I have put every dev files outside home folder. Pnpm is great for that too, since I can put the store whetever suits best.

However, I've noticed some dir are not customizable, namely `C:\Users\<user>\AppData\Local\pnpm\global\5` and `C:\Users\<user>\AppData\Local\pnpm-cache` (I'm using Windows 10, by the way). Checking pnpm's code made that clear ([packages/config/src/dirs.ts](https://github.com/pnpm/pnpm/blob/ae2f845c5deaf8ce32037f8da6a720fc1841e9e6/packages/config/src/dirs.ts)).

**Describe the solution you'd like**

I would like to be able to configure those dir as well, keeping everything neatly away from user's home dir.

**Describe the drawbacks of your solution**

None I can think of.

**Comment by zkochan** [comment]
Those location are configurable via [global-dir](https://pnpm.io/npmrc#global-dir) and [cache-dir](https://pnpm.io/npmrc#cache-dir)
