### ISSUE TITLE
I use nvm manage node, when change node from 16.x to 18.x , run pnpm xxx  get pnpm not an internal or external command, nor a runnable program or batch file

### ISSUE THREAD

**Issue by WormGirl** [pnpm/pnpm#4839]
### Additional information:

 - `node -v` prints:  16.3.2 to 18.2.0
 - Windows, macOS, or Linux?: windows

**Comment by thecreazy** [comment]
@WormGirl Maybe this is not a pnpm releated bug

have u installeted `pnpm` using `npm install -g pnpm` (or yarn) ? 

in this case,[ you can see that on the nvm documentation](https://github.com/nvm-sh/nvm#migrating-global-packages-while-installing), when u change from a node version to another you have to reinstall all the npm global packages or migrating it using this command `nvm install {new node version} --reinstall-packages-from={old node version}`

**Comment by Warden-Thresh** [comment]
Another possible problem
![image](https://user-images.githubusercontent.com/22620409/178646436-1835015d-5b62-4a84-8230-95a2fde57dbe.png)
was installd pnpm before use nvm.

Delete the old pnpm
![image](https://user-images.githubusercontent.com/22620409/178646736-7920fbf5-9acc-4cdb-aac1-3f281d7374ab.png)

Its works.
![image](https://user-images.githubusercontent.com/22620409/178646834-a9185b89-1228-4b9d-88dc-a990b84b4d59.png)

**Comment by dgrcode** [comment]
If you already installed the version but didn't pass the `--reinstall-packages-from={old node version}` flag, you can do:
```text
nvm reinstall-packages {old_version} # Reinstall global `npm` packages contained in {old_version} to current version
```

**Comment by smhmayboudi** [comment]
There is a solution which you can try. https://www.npmjs.com/package/corepack.

**Comment by juliodialpad** [comment]
> There is a solution which you can try. https://www.npmjs.com/package/corepack.

This is the right solution, thanks!
