### ISSUE TITLE
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment for version 7

### ISSUE THREAD

**Issue by vitalics** [pnpm/pnpm#4841]
### pnpm version:
7.1.2

### Code to reproduce the issue:

package.json
```json
{
"name": "test",
"engines": {
    "node": ">=14",
    "npm": ">=7",
    "pnpm": ">=7"
  },
  "engineStrict": true,
}
```

### Expected behavior:

No error should happens

### Actual behavior:
``` txt
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "<path to repo>".

Expected version: >=7
Got: 6.32.19

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```
### Additional information:

 - `node -v` prints: v14.17.2
 - `npm -v` prints: 7.24.2
 - Windows, macOS, or Linux?: macOS (I assume that OS is not specific here)

Possible issue: pnpm script is checking outdated package.json metadata(`version`)

**Comment by zkochan** [comment]
It means that you are running pnpm version 6.32.19.
try to reinstall pnpm.

**Comment by vitalics** [comment]
fixed after installing via npm: `npm i -g pnpm@7`
command `pnpm i -g pnpm@7` is not worked for me
