### ISSUE TITLE
Old release builds have disappeared

### ISSUE THREAD

**Issue by rektide** [pnpm/pnpm#4849]
### pnpm version:

`v5.15.1`

### Code to reproduce the issue:

`curl https://github.com/pnpm/pnpm/releases/download/v5.15.1/pnpm-linux-x64`

### Expected behavior:

We download pnpm v5.15.1

### Actual behavior:

404 not found

### Additional information:

 - Windows, macOS, or Linux?: all are missing, there is only source available in releases for all the v5.

Link to release: https://github.com/pnpm/pnpm/releases/tag/v5.15.1 (January 13th 2021)

The oldest release I can find that still has release artifacts is: https://github.com/pnpm/pnpm/releases/tag/v6.12.0 (August 6th 2021)

We believe this was working 24h ago.

**Comment by zkochan** [comment]
We did not have release artifacts in the past. We were only shipping a plain js version of pnpm.

**Comment by AndrewCsontos** [comment]
@rektide - it looks like the real issue was caused by a change in the asdf pnpm plugin
https://github.com/asdf-vm/asdf-plugins/commit/935e8080e603544b8457118b0f75e8c4bd5bdb27

**Comment by rektide** [comment]
thanks for the follow-up. indeed that was the issue.
