### ISSUE TITLE
Why every time I use pnpm install to install the pacage, the install process will stop aflter the package were download?

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [pnpm/pnpm#4857]
### Code to reproduce the issue:

![image](https://user-images.githubusercontent.com/52443370/172054541-6fe193bd-5056-44d6-a6ab-6c5a8755a813.png)

Then it stuck!!

This one has stuck for 15min. (I set an alias npm->pnpm on powershell)

![image](https://user-images.githubusercontent.com/52443370/172054577-f197364a-d013-43df-b6a8-39a0c28a53c7.png)

### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
From the output it looks like network issue.
