### ISSUE TITLE
Pnpm 7 no locker updating package.json

### ISSUE THREAD

**Issue by ghostdevv** [pnpm/pnpm#4860]
### Expected behavior:

Running `pnpm update` will update the package.json and pnpm lock

### Actual behavior:

When running `pnpm update` using pnpm 7 it no longer updates the package.json, this causes other issues such as not being able to install with `--frozen-lockfile` anymore due to the package and lock being out of sync

### Additional information:

 - `node -v` prints: `v16.9.1`
 - Windows, macOS, or Linux?: `linux`

**Comment by zkochan** [comment]
I can't reproduce this issue. Provide more details and an example project.

**Comment by ghostdevv** [comment]
I struggled to reproduce this in a blank repo, maybe this will help?

I clone my website: https://github.com/ghostdevv/website
next I do the following:

```
rm -rf node_modules
pnpm install
pnpm update
pnpm install --frozen-lockfile
```

the last command with `--frozen-lockfile` will fail as package.json is not updaed. Here is a video:

https://user-images.githubusercontent.com/47755378/172470670-7f719de2-aabd-496e-be57-9568b841917a.mp4

**Comment by val1984** [comment]
Since you have unmet peer dependencies, you are having the same issue as me #4763.
You will find a workaround there which works for us.

**Comment by ghostdevv** [comment]
Yes that fixed it! I will close this issue as a duplicate of #4763
