### ISSUE TITLE
v7 does not run `install` script

### ISSUE THREAD

**Issue by sapphi-red** [pnpm/pnpm#4888]
### Code to reproduce the issue:
```shell
pnpm i playwight-chromium # run in empty folder
```

### Expected behavior:
https://github.com/microsoft/playwright/blob/4f1ab2fa6271ae419a95ac1e29130b5c90b78c44/packages/playwright-chromium/package.json#L27
This install script runs.

### Actual behavior:
The install script does not run.

### Additional information:

 - `node -v` prints: 16.15.1
 - Windows, macOS, or Linux?: Windows

This does not happen with v6.32.22.
`npm i playwight-chromium` runs install script.

**Comment by zkochan** [comment]
It runs but only the first time because side-effects-cache is turned on by default. Do you have an issue?

You can turn off [side-effects-cache] by setting it to false.

[side-effects-cache]: https://pnpm.io/npmrc#side-effects-cache

**Comment by sapphi-red** [comment]
Oh, I see. Thank you!

So the reason was:

1. `actions/setup-node` caches storePath.
1. `playwright-chromium` saves binary to `node_modules` because `PLAYWRIGHT_BROWSERS_PATH=0` is set. `node_modules` is not cached by anything.
1. pnpm does not run install scripts since side-effects-cache is true and storePath exists.

I think pnpm can do nothing here. Thank you again for taking time!
