### ISSUE TITLE
Allow option to run recursive including root?

### ISSUE THREAD

**Issue by shirotech** [pnpm/pnpm#4906]
According to https://pnpm.io/cli/recursive:

pnpm -r, --recursive

Runs a command in every project of a workspace, excluding the root project, when used with the following commands:

- `exec`
- `run`
- `test`
- `add`

Is there an option or is it possible to run **with** root as well? Or is that considered an anti-pattern?

Also, not sure why these specific commands have special hard-coded treatments? Is it part of some spec? I would have thought it would just be easier and more generic to have a flag say `--no-root` or something, and let the users decide if root should be included or not?

**Comment by zkochan** [comment]
I agree with you. And it used to work consistently in the past. But I was asked to change it: https://github.com/pnpm/pnpm/issues/2769

An option sounds good and I think such issue already exists but I can't find it.

**Comment by shirotech** [comment]
Hi @zkochan Thanks for the response, I had a look and found a special option in npm. https://docs.npmjs.com/cli/v8/commands/npm-link#include-workspace-root I believe using -r, --recursive flags should follow the `include-workspace-root` option to include root or not.

**Comment by shirotech** [comment]
Hi @zkochan understand that you are busy, so I have proposed a change https://github.com/pnpm/pnpm/pull/4928 I'm not sure how to go about adding tests, if you can help me do that if needed. Thanks.

**Comment by coyotte508** [comment]
Would it be possible to add this to the docs here: https://pnpm.io/filtering ?

I'm very thankful the option exists, we have a CI where the root has its own lint script (for the root config files)

**Comment by tusharf5** [comment]
NPM also supports this as a cli argument, I think it would make sense to add it as a cli argument in pnpm. 

https://docs.npmjs.com/cli/v9/commands/npm-docs#include-workspace-root
