### ISSUE TITLE
[7.4.0-0] patches are not updated

### ISSUE THREAD

**Issue by schmod** [pnpm/pnpm#4916]
### Code to reproduce the issue:

Any patch file. 

1. Create a patch with `pnpm patch $PKG_NAME`
2. Make your edits, and commit the patch with `pnpm commit-patch $PATCH_PATH`
3. Confirm that the patch was applied (ie. `cat node_modules/PKG_NAME/editedFile.js`)
4. Edit the patch file by hand
5. Run `pnpm install`
6. Confirm that the patch was not applied (ie. `cat node_modules/PKG_NAME/editedFile.js`)

### Expected behavior:

When a patch is updated (ie. if a coworker checks in an updated patch to git), `pnpm install` should re-patch the underlying node module to apply the latest updates. 

### Actual behavior:

When an existing patch is updated, the underlying node module is not re-patched.

Note that renaming the patch file _does_ trigger the correct update.

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: MacOS

Likely related to #4905

**Comment by schmod** [comment]
PS. Thank you so much for adding patch support! This was the last thing keeping my company off of pnpm, and we look forward to adopting it!

**Comment by zkochan** [comment]
:ship: 7.4.0-1
