### ISSUE TITLE
pnpm ignoring detect_chromedriver_version flag in .npmrc

### ISSUE THREAD

**Issue by sbonasu** [pnpm/pnpm#4927]
### Code to reproduce the issue:

https://www.npmjs.com/package/chromedriver

.npmrc file contents
ignore-scripts = true
detect_chromedriver_version=true

### Expected behavior:
browser version is 95.0.4638.54

When I check chromedriver version in node_modules, its not matching chrome browser version

`node_modules/.pnpm/node_modules/.bin/chromedriver --version`
ChromeDriver 101.0.4951.41 (93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904})

### Actual behavior:
chromedriver version should match browser version.

If the current implementation doesn't support this setup. Is there a way to pass `DETECT_CHROMEDRIVER_VERSION=true` environment variable with `pnpm install` or use .pnpmfile.cjs?

I have tried doing this with .pnpmfile.cjs afterAllResolved hook but it doesn't run when `Lockfile is up-to-date`. Deleting lock file is not an option since it introduces version mismatches(importing from yarn.lock).

```
function afterAllResolved(lockfile, context) {
  context.log('Installing chromedriver');

  let chromeDriverPath = path.join(__dirname, 'node_modules/.pnpm/node_modules/chromedriver');

  let chromeDriverInstall = spawn(
    'npm',
    ['run', 'install'],
    { cwd: chromeDriverPath },
    { env: { ...process.env, DETECT_CHROMEDRIVER_VERSION: 'true' } },
  );

  chromeDriverInstall.on('error', (err) => {
    context.log('failed to install chromedriver: ' + err);
  });

  return lockfile;
}
```

### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: macOS and Linux

**Comment by zkochan** [comment]
I did not know that npm puts setting from `.npmrc` to env variables when running lifecycle scripts. Does Yarn implement it the same way? Obviously, if it works with npm, we should support it in some way

**Comment by sbonasu** [comment]
@zkochan do you think its possible to add a feature to define settings in .npmrc or modify custom hook `afterAllResolved` to run scripts(not restrict to just lockfile mutation)

**Comment by shellscape** [comment]
What's funny is that I'm on a two week RV trip with my family and doing a lot of driving - which means lots of time to think. I've been thinking about .env support quite a lot. @zkochan when I get back after July 9th I'll probably pick that up.

**Comment by zkochan** [comment]
But if I read [`.env`](https://dotenv.org/) correctly, it looks like it should not be committed to the repo.

In this case, I believe we want this in the repo.

I think we can add a new field to `package.json` with envs. Something like:

```json
{
  "pnpm": {
    "envVariables": {
      "detect_chromedriver_version": "true"
    }
  }
}
```

**Comment by sbonasu** [comment]
> But if I read [`.env`](https://dotenv.org/) correctly, it looks like it should not be committed to the repo.
> 
> In this case, I believe we want this in the repo.
> 
> I think we can add a new field to `package.json` with envs. Something like:
> 
> ```json
> {
>   "pnpm": {
>     "envVariables": {
>       "detect_chromedriver_version": "true"
>     }
>   }
> }
> ```

I like envVariables idea

**Comment by zkochan** [comment]
cc @pnpm/collaborators let me know what you think about this feature.

**Comment by BlackHole1** [comment]
> But if I read [`.env`](https://dotenv.org/) correctly, it looks like it should not be committed to the repo.
> 
> In this case, I believe we want this in the repo.
> 
> I think we can add a new field to `package.json` with envs. Something like:
> 
> ```json
> {
>   "pnpm": {
>     "envVariables": {
>       "detect_chromedriver_version": "true"
>     }
>   }
> }
> ```

I Approve of this.  But at the same time, we should be consistent with the behavior of npm. And npm will auto add prefix: `npm_config_`. Like: `npm_config_${key.toLowerCase()}`. See:
1. https://github.com/giggio/node-chromedriver/blob/8c122d919ceb0a918bc7ca7fcf2f0f4ab7a89281/install.js#L35
2. https://github.com/npm/cli/blob/ef8d2edd7da993f4086c85089952cd45834ac78b/docs/content/commands/npm.md#configuration
3. https://github.com/npm/config/blob/6440fba6e04b1f87e57b4c2ccc5ea84d8a69b823/lib/set-envs.js#L9-L13

**Comment by sbonasu** [comment]
good catch @BlackHole1. Thank you all for looking in to this

**Comment by gluxon** [comment]
+1 to @BlackHole1's comment. @sbonasu The `process.env.npm_config_detect_chromedriver_version` environment variable should be visible to the `node-chromedriver` postinstall script already. Is that the case?

**Comment by zkochan** [comment]
I've checked, `npm_config_` is set correctly. The same way as with npm.

Maybe you have this package cached and the cache was written with a different setting.

Try to add `side-effects-cache=false` to your `.npmrc`, remove node_modules and reinstall.

**Comment by sbonasu** [comment]
side-effects-cache=false seems to have done the trick. Thank you

**Comment by zkochan** [comment]
ok, this is solved. I created a new issue to try to fix this https://github.com/pnpm/pnpm/issues/5002
