### ISSUE TITLE
pnpm auto-install-peers=true is not working inside .npmrc

### ISSUE THREAD

**Issue by erdemgonul** [pnpm/pnpm#4930]
### Code to reproduce the issue:

- Created .npmrc file with line `auto-install-peers=true`
- delete pnpm-lock.yaml and node_modules 
- `pnpm i`

### Expected behavior:

- Install all peer dependencies automatically

### Actual behavior:

<img width="1275" alt="Ekran Resmi 2022-06-24 23 04 14" src="https://user-images.githubusercontent.com/32040940/175659683-1b09ba9b-775d-4678-aeb4-4c3eb00e826e.png">

**Comment by zkochan** [comment]
Did you create the `.npmrc` in the root of the repository? In the same directory where the root `package.json` is?

You can also try:

```
pnpm install --config.auto-install-peers=true
```

**Comment by erdemgonul** [comment]
yes it is in the root directory, `pnpm install --config.auto-install-peers=true` is also not worked

<img width="344" alt="Ekran Resmi 2022-06-24 23 43 20" src="https://user-images.githubusercontent.com/32040940/175664669-f1f278f5-38e5-4c5e-bf43-729b4129c798.png">

**Comment by zkochan** [comment]
OK, can you create a repository that reproduces the issue?

**Comment by erdemgonul** [comment]
You can check it from here @zkochan 

https://github.com/erdemgonul/pnpm-auto-test

**Comment by zkochan** [comment]
I see this error: 

![image](https://user-images.githubusercontent.com/1927579/175667532-f90f8f4c-dc62-441f-bc87-d2809fd23f54.png)

This can't be fixed by `auto-install-peers=true`

**Comment by erdemgonul** [comment]
I have so many unmet peer dependencies  like in my first screenshot in that repo, how can you get only those?

**Comment by zkochan** [comment]
Yeah, I get those as well if I comment out `auto-install-peers=true` in the `.npmrc`. For some reason, it is not read in your case.

**Comment by erdemgonul** [comment]
So we are working in same repo but we have different list of unmet peer dependencies? What is your pnpm version? Do you have any idea about it?

**Comment by erdemgonul** [comment]
Now looks like we have a different problem.  @zkochan 
On my M1 Pro  macOS Monterey 12.3.1 result as seen as my first screenshot. 
On my intel i7 Monterey 12.4, result seen as yours. 
Both of them have same npm, node and pnpm versions.

`.npmrc `solution , or `pnpm install --config.auto-install-peers=true `is not working. Do you have any idea about it?

**Comment by erdemgonul** [comment]
Ok, this problem only occurs on my M1Pro mac. I tried to `pnpm i `on that repo for another 3 intel mac and results are seen as expected with your case. 

So do you have any suggestion about it? 

What is your development environment? @zkochan

**Comment by zkochan** [comment]
I am on Fedora. I don't have a mac to test this. In case someone wants to debug this, here is the config package: https://github.com/pnpm/pnpm/blob/main/packages/config/src/index.ts

but we use a fork of npm's config reading package to read the configs: https://github.com/pnpm/npm-conf
