### ISSUE TITLE
The workspace dependencies in lock file is disappeared.

### ISSUE THREAD

**Issue by BTBMan** [pnpm/pnpm#4939]
### pnpm version:
v7.3.0
### Code to reproduce the issue:

when I uninstall one of the third-part packages, the workspace dependencies in lock file is disappeared. I don't know why.
So, I can only run `pnpm install` to show them again

### Expected behavior:
Uninstall one of the third-part packages should not remove workspace dependencies in lock file

### Actual behavior:
It disappeared and when only have one third-part dependency, after remove this, the pnpm-lock.json is also be deleted whether it has workspace dependencies

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
Although I couldn't repro this, it might've been fixed by https://github.com/pnpm/pnpm/commit/ff7061929fb431cff8d9a5e76f1c18fae7f6d4fb

**Comment by BTBMan** [comment]
Fixed yet! Thanks a lot. :smile:
