### ISSUE TITLE
regression with version 7.4.0, it no longer update `pnpm-lock.yaml` in CI due to recent PR to exit early on `lockfile-only`

### ISSUE THREAD

**Issue by ghiscoding** [pnpm/pnpm#4951]
### pnpm version:
7.4.0

### Code to reproduce the issue:
see Lerna-Lite [issue](https://github.com/ghiscoding/lerna-lite/issues/234) and it works fine with previous version 7.3.0. By looking at the recent PR #4932, which caused the regression, I found out that calling `--fix-lockfile` would make it work with the same behavior as before. Basically I used the fix lock file just because that seems to be the last flag I can use that is still in the `if` condition that was modified recently by PR #4932

https://github.com/pnpm/pnpm/blob/487527dcffa66b352fda5f19568edf539a3ac3a4/packages/core/src/install/index.ts#L266-L271

### Expected behavior:
calling `pnpm install --lockfile-only` should work in CI and update lock file as it used to. 

### Actual behavior:
since latest release 7.4.0 it no longer update `pnpm-lock.yaml` in CI due to recent PR to exit early on `lockfile-only`

### Temporary fix:
For now I'm adding the fix lock to get around the regression problem but it's not a viable solution and I hope the regression is fix soon.
```ts
# temp fix to go around the regression
pnpm install --lockfile-only --fix-lockfile
```

### Additional information:

 - `node -v` prints: all 
 - Windows, macOS, or Linux?: all

**Comment by zkochan** [comment]
I see, try `pnpm install --lockfile-only --no-frozen-lockfile`

**Comment by ghiscoding** [comment]
yes it does seem to help at least now the unit tests that were failing with 7.4.0 are now passing in CI, is that what you suggest to use all the time? I won't close the issue just yet but I can test it out with a new `version` bump and release in Lerna-Lite in the next couple of hours. It does seem promising at least

**Comment by zkochan** [comment]
It should work with no changes when I release this fix: https://github.com/pnpm/pnpm/pull/4955

**Comment by ghiscoding** [comment]
oh that'd be great, do you have an ETA (estimated time) for a fix and new release of pnpm then?

**Comment by zkochan** [comment]
Probably in the next 24 hours.
