### ISSUE TITLE
Error happens when adding new deps in a workspace that has patches

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#4954]
```
$ pnpm -v
7.4.0
```

```patch``` is working great, thanks! But everytime I add new dependencies with ```pnpm add <pkg>``` I have this message: 

<img width="794" alt="Screenshot 2022-06-29 at 23 28 35" src="https://user-images.githubusercontent.com/796524/176548161-33865337-48c5-4ed8-98dc-e4cee44e2907.png">

My ```package.json```:

```
"pnpm": {
  "patchedDependencies": {
    "@babel/plugin-transform-typescript@7.18.6": "patches/@babel__plugin-transform-typescript@7.18.6.patch"
   }
}
```

I have to manually remove the ```patchedDependencies``` and put it back when I'm done. Am I doing right ?

_Originally posted by @hrasoa in https://github.com/pnpm/pnpm/issues/3077#issuecomment-1170513221_

**Comment by Jack-Works** [comment]
I believe this is the same problem I've reported in https://github.com/pnpm/pnpm/pull/4945#issuecomment-1168649770

**Comment by hrasoa** [comment]
Nice one very quick! ```yarn add``` is fixed, but I have the same error on ```yarn remove``` though:

<img width="786" alt="Screenshot 2022-07-02 at 10 11 06" src="https://user-images.githubusercontent.com/796524/176992509-158ca97e-5522-4506-b530-c1aa5a80e6d2.png">
