### ISSUE TITLE
Some sponsors are not readable on GitHub Dark theme

### ISSUE THREAD

**Issue by mcmxcdev** [pnpm/pnpm#4959]
Adding a `background: "white"` or similar to these would help:

![Screenshot from 2022-06-30 18-01-54](https://user-images.githubusercontent.com/16797721/176724882-ed3a4bce-392e-4c37-80d9-7ba379ab44cc.png)

**Comment by zkochan** [comment]
Done 

![image](https://user-images.githubusercontent.com/1927579/176794690-1b527cf3-84ec-4196-bdb5-48b2b297d2a0.png)
