### ISSUE TITLE
"Address boundary error" when running pnpm that was bundled withe vercel/pkg using Node.js 16

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#4968]
Fixed by reverting to Node.js 14: https://github.com/pnpm/pnpm/commit/e9946fcfa7e1892fb550a2164c2040fea2574cdd

When pnpm is bundled with Node.js 16, some commands fail. For instance, running `pnpm up -i` with `@pnpm/exe@7.4.1` fails with:

```
Job 1, 'pnpm up -i' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by ahkhanjani** [comment]
I think you may want to close this issue.
