### ISSUE TITLE
pnpm does not support 'pre' hook

### ISSUE THREAD

**Issue by xflihaibo** [pnpm/pnpm#4976]
```json
  "prebuild-win": "npm run build"
  "build-win": "electron-builder -w"
```
"prebuild-win" command does not run

### pnpm version:7.1.7
 - node  14.19.3
 -  macOS

**Comment by zkochan** [comment]
Use `enable-pre-post-scripts=true`:

https://pnpm.io/cli/run#enable-pre-post-scripts
