### ISSUE TITLE
deploy uses monorepo root for output instead of working dir or absolute path

### ISSUE THREAD

**Issue by AWare** [pnpm/pnpm#4980]
### Code to reproduce the issue:

say you're in a project 'p' within a monorepo 
```sh
> pnpm --filter p deploy dist
> pnpm --filter p deploy $(pwd)/dist
```

### Expected behavior:
I'd expect them both to put them within the current working dir.

### Actual behavior:
it will put dist within the root of the monorepo, 

### Additional information:
it would also be really handy to infer the package from the working directory so filter can be omitted

_Edit: apologies, just realised I got expected and actual the wrong way round_

**Comment by zkochan** [comment]
I don't have objections to changing it, but I would be interested in more opinions. cc @pnpm/collaborators

**Comment by shellscape** [comment]
please allow me some time to think about this. it's a very complex question.

**Comment by DRoet** [comment]
I think inferring the package/workspace from the working directory would be a nice addition. that's kind of what I expected when first running `pnpm deploy` without any options.

**Comment by JounQin** [comment]
This would a breaking change, and personally I'm always using `dist/packageName`, maybe we add pattern support like `dist/$pkg` + `packages/$pkg/dist`?

**Comment by zkochan** [comment]
This command is experimental. Breaking changes are allowed.

**Comment by LeviticusMB** [comment]
I must say I was a bit surprised that `pnpm  --filter=...  deploy /opt/foo/` didn't install anything at all in `/opt`.

**Comment by shellscape** [comment]
I've been sick the last few days. I'll weigh in tomorrow

**Comment by AWare** [comment]
@shellscape did you have any objections to this?

**Comment by shellscape** [comment]
Apologies. I've been sick this past week and have not been able to get back to this.

**Comment by AWare** [comment]
Hope you're feeling better soon.

**Comment by AWare** [comment]
Would it be preferred if the change just allowed absolute paths to be used instead of changing the base path?

**Comment by AWare** [comment]
@zkochan / @shellscape is there anything that I can do to help get https://github.com/pnpm/pnpm/pull/5026 reviewed & approved? the comments so far seem generally in favour, and I believe that I have addressed any objections satisfactorily. I'd really like to start using `deploy` in my projects at work, and am currently held up on this.

**Comment by AWare** [comment]
thanks @zkochan 👍
