### ISSUE TITLE
`strict-peer-dependencies: ignore` support, or ignore if they have been `public-hoist`ed already

### ISSUE THREAD

**Issue by JounQin** [pnpm/pnpm#4983]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I'm always using my `@1stg/app-config` or `@1stg/lib-config` which will install all (peer) dependencies inside, `strict-peer-dependencies=false` still complain about missing peer dependencies, this is very unnecessary and noisy to me personally.

**Describe the solution you'd like**

As title

**Describe the drawbacks of your solution**

N/A

**Describe alternatives you've considered**

N/A

**Comment by JounQin** [comment]
@zkochan Thanks for response, but the fact is, if `a` has peer `b` and `c` has dep `b` and hosted, `b` can already be available from `a`.

Install all of the peer deps one by one is very verbose that's why I have `@1stg/app-config` to simplify.

If you think auto detection from `public-hoist` is not suitable, then at least can we support 'ignore'?

**Comment by zkochan** [comment]
You can use the following settings in `package.json`:

```json
{
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": ["*"]
    }
  }
}
```

**Comment by JounQin** [comment]
Is that option for a different approach? Although it would work for my case, but I think they are different.

**Comment by zkochan** [comment]
You want to ignore the warnings about missing peer dependencies. That will do it.

**Comment by JounQin** [comment]
> You want to ignore the warnings about missing peer dependencies. That will do it.

They are not missing, they're `public-hoist`ed.

**Comment by zkochan** [comment]
I don't think will have a different workaround. Hoisting in pnpm exists only to fix broken packages in the ecosystem. You are trying to use this as a workaround to avoid installing peer dependencies in the root.

If you want to avoid installing peer dependencies, just use `auto-install-peers=true` and don't rely on hoisting.

**Comment by JounQin** [comment]
> If you want to avoid installing peer dependencies, just use auto-install-peers=true and don't rely on hoisting.

Thanks very much, `auto-install-peers` seems a very promising solution!
