### ISSUE TITLE
peerDependencies not installed when lockfile exists

### ISSUE THREAD

**Issue by robations** [pnpm/pnpm#4988]
### pnpm version:
7.5.0

### Code to reproduce the issue:

```
# .npmrc
auto-install-peers = true
strict-peer-dependencies = false

# workspace-main/package.json
...
  "peerDependencies": {
    "angular": "~1.7.9",
    "babel-loader": "^8.2.2",
    "core-js": "^3.10.2",
    etc
  }
...

# workspace-app1/package.json
...
  "dependencies": {
    "workspace-main": "workspace:*"
  },
  "dependenciesMeta": {
    "workspace-main": {
      "injected": true
    }
  },
...
```

(in my use case, up to 20 similar apps with the same kind of package.json as app1, hence not wanting to repeat the peer deps)

If this example isn't enough, I could create a minimal reproduction.

### Expected behavior:

Whether the lockfile is present or absent, I expect the peer dependencies under "workspace-app1" to install automatically, if not already linked.

### Actual behavior:

When the lockfile is absent, the peer dependencies under "workspace-app1" install automatically.

When the lockfile is present, the peer dependencies under "workspace-app1" are missing and generates module errors in builds.

### Additional information:

 - `node -v` prints: v14.19.3
 - Windows, macOS, or Linux?: seen issue with macOS and Linux

Have also experimented with `--no-frozen-lockfile` and `--frozen-lockfile` but doesn't make a difference, the main thing is whether the lockfile is there at all.

May be related to #4378, #4625

Also considering whether this is a recent regression. I was using 7.2 until recently and didn't notice this issue on build servers etc, only when I merge the changes to switch to pnpm...

**Comment by robations** [comment]
Seeing the same issue with 7.2.1. I'm guessing this didn't come to light due to dirty `node_modules` directories that contained hoisted packages from using yarn previously.

I'll try to make a reproduction repo.

**Comment by robations** [comment]
See https://github.com/robations/pnpm-vs-auto-peers

**Comment by robations** [comment]
My guess is that the problem is more with `auto-install-peers` than `dependenciesMeta.injected`. It seems like the "workspace-main" workspace in the example is being hard-linked as expected, just the auto-install isn't triggered.

Let me know if I can help or provide any more information.

**Comment by zkochan** [comment]
There is an inconsistency but probably the auto installed peers should not be there even at the run without the lockfile.

If you check, lodash will be always linked to the real location of the injected dependency. The real location is inside `node_modules/.pnpm`.

**Comment by robations** [comment]
@zkochan Thanks for your reply and time looking at this. No joke maintaining a package manager :)

> probably the auto installed peers should not be there

Excuse my ignorance, but what is the point of auto-install-peers if the peers shouldn't be installed?

The use case is that I'm trying to avoid repeating the specifications (or at least to constrain them) for around 8 dependencies across ~16 workspace packages. (It's stuff like webpack loaders, gulp, angularjs.)

If I repeat the specs (by adding as direct dependencies to each workspace), this becomes a maintenance problem, because all the versions need to be kept in sync 🤯.

Before I used "injected" it just seemed like the peerDependencies were ignored within the workspace — versions not checked, not installed.

Not trying to flame, just hoping to get to a workable solution.

**Comment by robations** [comment]
Lol. I was reading https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md and https://github.com/yarnpkg/berry/issues/1001 to try to understand this better.

> Maybe something completely new is needed. Peer dependencies are already super complex.
> — zkochan

I was thinking of peer deps as a solution to a problem, but perhaps better avoided!

**Comment by zkochan** [comment]
```
cd workspace-app1 && node -r "lodash"
```

if you need to do this, you need to add lodash to your dependencies. Otherwise, you are relying on hoisting. If you want hoisting, use `node-linker=hoisted`.

**Comment by belgattitude** [comment]
@robations @zkochan I haven't followed entirely. 

My attention was caught by the rfc 25 you've mentioned. 

I was included in npm v7, but made obsolete by 

https://github.com/npm/rfcs/blob/main/implemented/0030-no-install-optional-peer-deps.md

This is the default for npm 8.

Few months ago, I researched a bit about it when having to choose between peer deps and deps.

Here's the summary 

https://gist.github.com/belgattitude/df235dc0ca3929ef2b56eb26fe6f3bed


Hope it's useful.

**Comment by robations** [comment]
Thanks @belgattitude for additional docs. I the historical changes muddy the water of what was already a complex topic. And the differences between hoisting/not hoisting add to this.

I think I was interpretting a peer dependency as:

> I need this dep, and you need it with the same version specification.

but it's maybe more like

> I need this dep, and if you also need it directly, you need to install it such that we have the same version.

**Comment by robations** [comment]
@zkochan thanks for updates.

Yeah, I'm still trying to avoid hoisting. I've written a script to parse the peerDependencies from my "main" package.json and add them as direct dependencies to any package that has "main" in its dependency chain. Not ideal but reduces the maintenance burden a little.
