### ISSUE TITLE
peerDependenciesMeta inconsistently applied to lockfile

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#5004]
### pnpm version: `v6.32.0`

The latest version of pnpm at the time of writing is `v7.5.0`. I believe the issue is still present on the latest version, but haven't verified since there's other blockers preventing our team from upgrading.

### Code to reproduce the issue:

We have `debug@4.3.3` in our `pnpm-lock.yaml` for 2 large monorepos my team maintains.

```yaml
# pnpm-lock.yaml

packages:

  /debug/4.3.3:
    resolution: {integrity: sha512-/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q==}
    engines: {node: '>=6.0'}
    peerDependencies:
      supports-color: '*'
    peerDependenciesMeta:
      supports-color:
        optional: true
    dependencies:
      ms: 2.1.2
```

Intermittently, pnpm removes these 2 blocks from the lockfile.

```diff
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index cce0ec0b341..7c4bf81231b 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -62600,9 +62598,6 @@ packages:
   /debug/4.3.3:
     resolution: {integrity: sha512-/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q==}
     engines: {node: '>=6.0'}
-    peerDependencies:
-      supports-color: '*'
-    peerDependenciesMeta:
-      supports-color:
-        optional: true
     dependencies:
```

This would be fine on its own and a minor inconvenience, but the removal of `peerDependencies` for `debug` causes large sections of our `pnpm-lock.yaml` to change as a side-effect. This propagates through `transitivePeerDependencies` and can flip entire entries in the `packages` section of `pnpm-lock.yaml`.

### Expected behavior:

pnpm consistently applies `peerDependencies` and `peerDependenciesMeta`.

### Actual behavior:

pnpm sometimes removes `peerDependencies` and `peerDependenciesMeta`.

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Reproduced on macOS and Linux.
## Initial Investigation

Stepping through an interactive debugger, I'm noticing the [`resolveDependency` function](https://github.com/pnpm/pnpm/blob/d89bb43f2d0f5bd43fcb1ee752ea42367d772752/packages/resolve-dependencies/src/resolveDependencies.ts#L692) can be called several times requesting `debug` with different version specifiers. This makes sense since different parts of the package graph request `debug` at different versions.

I added some logging [here](https://github.com/pnpm/pnpm/blob/v6.32.0/packages/resolve-dependencies/src/resolveDependencies.ts#L696):

```diff
diff --git a/packages/resolve-dependencies/src/resolveDependencies.ts b/packages/resolve-dependencies/src/resolveDependencies.ts
index af969a451..5dbc47726 100644
--- a/packages/resolve-dependencies/src/resolveDependencies.ts
+++ b/packages/resolve-dependencies/src/resolveDependencies.ts
@@ -693,6 +693,11 @@ async function resolveDependency (
   }
   const depPath = dp.relative(ctx.registries, pkg.name, pkgResponse.body.id)
 
+  if (depPath === '/debug/4.3.3') {
+    console.log(JSON.stringify(pkg))
+    console.log('')
+  }
+
   // We are building the dependency tree only until there are new packages
   // or the packages repeat in a unique order.
   // This is needed later during peer dependencies resolution.
```

### Good case

When `peerDependencies` and `peerDependenciesMeta` are present, the first log above for `pkg` prints:

```json
{
  "dependencies": { "ms": "2.1.2" },
  "engines": { "node": ">=6.0" },
  "name": "debug",
  "peerDependenciesMeta": { "supports-color": { "optional": true } },
  "scripts":
    {
      "lint": "xo",
      "test": "npm run test:node && npm run test:browser && npm run lint",
      "test:node": "istanbul cover _mocha -- test.js",
      "test:browser": "karma start --single-run",
      "test:coverage": "cat ./coverage/lcov.info | coveralls"
    },
  "version": "4.3.3"
}
```

### Missing case

When the `peerDependencies` and `peerDependenciesMeta` blocks are missing from the lockfile, the first log above for `pkg` prints:

```json
{
  "name": "debug",
  "version": "4.3.3",
  "engines": { "node": ">=6.0" },
  "dependencies": { "ms": "2.1.2" },
  "devDependencies": {
    "brfs": "^2.0.1",
    "browserify": "^16.2.3",
    "coveralls": "^3.0.2",
    "istanbul": "^0.4.5",
    "karma": "^3.1.4",
    "karma-browserify": "^6.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-mocha": "^1.3.0",
    "mocha": "^5.2.0",
    "mocha-lcov-reporter": "^1.2.0",
    "xo": "^0.23.0"
  },
  "directories": {},
  "dist": {
    "tarball": "https://<REDACTED>/debug/-/debug-4.3.3.tgz",
    "shasum": "04266e0b70a98d4462e6e288e38259213332b664",
    "integrity": "sha512-/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q=="
  },
  "_hasShrinkwrap": false
}
```

### Thinking about the good/bad cases

Note that I see both objects printed on `pnpm install` in the good and bad cases. The difference between whether or not `peerDependencies`/`peerDependenciesMeta` gets written to the lockfile is which log appears first.

I believe the differing objects are from whether or not fetching is skipped here:

https://github.com/pnpm/pnpm/blob/4dca63daa60285ff303e95d3d60b5335400310aa/packages/package-requester/src/packageRequester.ts#L229

### Caches

Digging a bit further, the object without `peerDependencies` comes from:

```
/Users/me/Library/Caches/pnpm/metadata/<REDACTED>/debug.json
```

Sure enough `peerDependencies` and `peerDependenciesMeta` are missing from the package metadata cache:

```json5
{
  "name": "debug",
  "dist-tags": {
    "beta": "4.3.3",
    "latest": "4.3.4"
  },
  "versions": {
    // ...
    "4.3.3": {
      "name": "debug",
      "version": "4.3.3",
      "engines": {
        "node": ">=6.0"
      },
      "dependencies": {
        "ms": "2.1.2"
      },
      "devDependencies": {
        "brfs": "^2.0.1",
        "browserify": "^16.2.3",
        "coveralls": "^3.0.2",
        "istanbul": "^0.4.5",
        "karma": "^3.1.4",
        "karma-browserify": "^6.0.0",
        "karma-chrome-launcher": "^2.2.0",
        "karma-mocha": "^1.3.0",
        "mocha": "^5.2.0",
        "mocha-lcov-reporter": "^1.2.0",
        "xo": "^0.23.0"
      },
      "directories": {},
      "dist": {
        "tarball": "https://<REDACTED>/debug/-/debug-4.3.3.tgz",
        "shasum": "04266e0b70a98d4462e6e288e38259213332b664",
        "integrity": "sha512-/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q=="
      },
      "_hasShrinkwrap": false
    },
  }
}
```

In my `.pnpm-store/v3/files/e8/540ba8e3f55d9b773c8f3b1193e5e23dd61ed8107571cb0846453465ccaea5e41c07f6e9312546cb229cc8ac72bfea30cd8c5edc7739cd41271efcb69d7bcf`, I see:

```json
{
  "name": "debug",
  "version": "4.3.3",
  "repository": {
    "type": "git",
    "url": "git://github.com/debug-js/debug.git"
  },
  "description": "Lightweight debugging utility for Node.js and the browser",
  "keywords": [
    "debug",
    "log",
    "debugger"
  ],
  "files": [
    "src",
    "LICENSE",
    "README.md"
  ],
  "author": "Josh Junon <josh.junon@protonmail.com>",
  "contributors": [
    "TJ Holowaychuk <tj@vision-media.ca>",
    "Nathan Rajlich <nathan@tootallnate.net> (http://n8.io)",
    "Andrew Rhyne <rhyneandrew@gmail.com>"
  ],
  "license": "MIT",
  "scripts": {
    "lint": "xo",
    "test": "npm run test:node && npm run test:browser && npm run lint",
    "test:node": "istanbul cover _mocha -- test.js",
    "test:browser": "karma start --single-run",
    "test:coverage": "cat ./coverage/lcov.info | coveralls"
  },
  "dependencies": {
    "ms": "2.1.2"
  },
  "devDependencies": {
    "brfs": "^2.0.1",
    "browserify": "^16.2.3",
    "coveralls": "^3.0.2",
    "istanbul": "^0.4.5",
    "karma": "^3.1.4",
    "karma-browserify": "^6.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-mocha": "^1.3.0",
    "mocha": "^5.2.0",
    "mocha-lcov-reporter": "^1.2.0",
    "xo": "^0.23.0"
  },
  "peerDependenciesMeta": {
    "supports-color": {
      "optional": true
    }
  },
  "main": "./src/index.js",
  "browser": "./src/browser.js",
  "engines": {
    "node": ">=6.0"
  }
}
```

### Next

I believe the bug is that `peerDependenciesMeta` isn't getting saved to the local cache. I do see the field visiting my team's internal registry directly.

I'm also realizing that `debug` is likely a special case here since it's declaring `peerDependenciesMeta` without `peerDependencies`. I suspect pnpm somewhere reads `pnpmDependenciesMeta` and assumes `peerDependencies` from it.

Instead of updating caches to store `peerDependenciesMeta`, this could also be fixed by merging the `peerDependenciesMeta` fields when updating `ctx.resolvedPackagesByDepPath`, but I think that's the wrong design. The caches should contain `peerDependenciesMeta`.

https://github.com/pnpm/pnpm/blob/d89bb43f2d0f5bd43fcb1ee752ea42367d772752/packages/resolve-dependencies/src/resolveDependencies.ts#L941

**Comment by gluxon** [comment]
Hm. I think `peerDependenciesMeta` isn't present when `fullMetadata` is set to `false`.

https://github.com/pnpm/pnpm/blob/d89bb43f2d0f5bd43fcb1ee752ea42367d772752/packages/fetch/src/fetchFromRegistry.ts#L42

**Comment by zkochan** [comment]
I see that debug is patched because it is in the compatibility database: https://github.com/yarnpkg/berry/blob/20612e82d26ead5928cc27bf482bb8d62dde87d3/packages/yarnpkg-extensions/sources/index.ts#L50-L55

So a hook is added that field probably.

**Comment by gluxon** [comment]
Thanks @zkochan. I didn't realize `debug` was also in that database. That may actually explain why I only see this for `4.3.3`? Since the database matches on `debug@<4.2.0`.

Applying the [corgi doc header](https://github.com/pnpm/pnpm/blob/d89bb43f2d0f5bd43fcb1ee752ea42367d772752/packages/fetch/src/fetchFromRegistry.ts#L8), I'm noticing I see different results from npm and my team's internal Artifactory mirror.

### Curling Internal Mirror

```
curl "https://<REDACTED_INTERNAL_REGISTRY>/debug" --header 'accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' | jq '.versions["4.3.3"]'
```

```jsonc
{
  "name": "debug",
  "version": "4.3.3",
  "engines": {
    "node": ">=6.0"
  },
  "dependencies": {
    "ms": "2.1.2"
  },
  "devDependencies": {
    "brfs": "^2.0.1",
    "browserify": "^16.2.3",
    "coveralls": "^3.0.2",
    "istanbul": "^0.4.5",
    "karma": "^3.1.4",
    "karma-browserify": "^6.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-mocha": "^1.3.0",
    "mocha": "^5.2.0",
    "mocha-lcov-reporter": "^1.2.0",
    "xo": "^0.23.0"
  },
  "directories": {},
  "dist": {
    "tarball": "https://artifactory.palantir.build/artifactory/api/npm/all-npm/debug/-/debug-4.3.3.tgz",
    "shasum": "04266e0b70a98d4462e6e288e38259213332b664",
    "integrity": "sha512-/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q=="
  },
  "_hasShrinkwrap": false
}
```

### Curling registry.npmjs.org

```
curl "https://registry.npmjs.org/debug" --header 'accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' | jq '.versions["4.3.3"]
```

```
{
  "name": "debug",
  "version": "4.3.3",
  "dependencies": {
    "ms": "2.1.2"
  },
  "devDependencies": {
    "brfs": "^2.0.1",
    "browserify": "^16.2.3",
    "coveralls": "^3.0.2",
    "istanbul": "^0.4.5",
    "karma": "^3.1.4",
    "karma-browserify": "^6.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-mocha": "^1.3.0",
    "mocha": "^5.2.0",
    "mocha-lcov-reporter": "^1.2.0",
    "xo": "^0.23.0"
  },
  "dist": {
    "integrity": "sha512-/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q==",
    "shasum": "04266e0b70a98d4462e6e288e38259213332b664",
    "tarball": "https://registry.npmjs.org/debug/-/debug-4.3.3.tgz",
    "fileCount": 7,
    "unpackedSize": 42039,
    "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.13\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJhoi8wCRA9TVsSAnZWagAAMQIQAIBVX5eU9r89GpL0l/jh\nAeLvydJ2+QkHftmS+SqCXxx9d2YYiPGdSdvSt+iVR4oR1YFpa815iJAXeI6Q\n3HvInF5rZh2Xdh4JJN3eJjm0A93jIs0LHpRQw2LCUbbNQfXLprzVcrlFNSJX\nfdTA6yPTU2xJfbE0vCUI7eqY/fopE7j+VywFz1t74k3yQLHjvO6lZdvvH9zZ\nVlGjZA0YRiDVvnHckjiK3req/qxeDHchRaXvOCy7NFk0KWjBNjB4fU+skDJa\nl1TtnsRC4ApvXVKdb4FtzKjVSnybA0pOa6ZCWLwzk1rEKAiKOy6HRka579UX\n5DAv8vfWe6ssdkhTWP76b92TCorKJZGP7V2odekPXMuh5HdD9YyWERWQk+jH\npOQ9nSRriSdGvpq1EpSm35nB/PMe6x/MlRCdTRfWtqXbZrShcuiZQ2DJkpjV\nXXhAl8edrt5mDGS8K6/6ToSFjyApNfdtzBBvtAOmKZnd55prw3CndkAGyA9W\n9h8RTIjaAcN7mfB/VC5rcIqKwHZu3UrYRlDqAAXjR/KWKlLkGal9EPJBUuy8\nTqjXrAQJRh23WFHnskZFwcZ1Jzbq82DgN8j6k+o3Dg5yMXA/uziM0wuf6LKe\nbduB5k1PPHnHusUiJt7L5GQs7JNmQ7nBq1spTjChbMU6LsAt7sxfb+BaUJO4\nmtBR\r\n=LlaO\r\n-----END PGP SIGNATURE-----\r\n",
    "signatures": [
      {
        "keyid": "SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA",
        "sig": "MEUCIDgwLgAI7itIaQdIOaujVhQRAS2WPkbeANCzrou1tqTFAiEAr1GYNDj09Vuvs8FWn8J3vBrOAWIyAYknyEcKVh3tp4w="
      }
    ]
  },
  "engines": {
    "node": ">=6.0"
  },
  "peerDependenciesMeta": {
    "supports-color": {
      "optional": true
    }
  }
}
```

**Comment by gluxon** [comment]
Double checked again that `curl "https://<REDACTED_INTERNAL_REGISTRY>/debug" | jq '.versions["4.3.3"]'` does return `peerDependenciesMeta`.

I think this is actually a JFrog Artifactory bug. It's probably filtering out `peerDependenciesMeta` incorrectly when the corgi doc header is sent.

**Comment by gluxon** [comment]
Going to close since I'm confident this isn't a pnpm bug now. I'll followup with JFrog Artifactory and link any issues filed there.
