### ISSUE TITLE
Non-workspaces appear in `pnpm-lock.yaml` file

### ISSUE THREAD

**Issue by robdonn** [pnpm/pnpm#5009]
### Expected behavior:

Directories not listed as workspaces should not appear in the `pnpm-lock.yaml` file

### Actual behavior:

Directories not listed as workspaces are appearing in the `pnpm-lock.yaml` file. even if they are defined in the `.gitignore` file.

### Additional information:

 - `node -v` prints: `v18.5.0`
 - Windows, macOS, or Linux?: macOS

**Comment by kenrick95** [comment]
I think your `pnpm-workspace.yaml` is not correct.

It should be listed under "packages" key. So for your example repo, I think it should be:

```yaml
packages:
  - 'app'
```

Reference: https://pnpm.io/pnpm-workspace_yaml

**Comment by robdonn** [comment]
Thanks @kenrick95, that is indeed the problem. Whoops! 😊
