### ISSUE TITLE
fix(cli): description of `-r` option

### ISSUE THREAD

**Issue by jjangga0214** [pnpm/pnpm#5019]
### Code to reproduce the issue:

```sh
pnpm -h

pnpm publish -h
```

### Expected behavior:

To see description of `-r` option (e.g. `pnpm publish -r`). 

### Actual behavior:

There is no description.

### Additional information:

 - `node -v` prints: v16.13.1
 - Windows, macOS, or Linux?: macOS

Thanks!

**Comment by jjangga0214** [comment]
By the way, what does `-r` mean and do?
I wanted to know that so I executed `pnpm -h` and `pnpm publish -h`.
Thanks :)

**Comment by zkochan** [comment]
Documented here: https://pnpm.io/cli/recursive

**Comment by jjangga0214** [comment]
@zkochan Thanks! Is it intentionally omitted from cli? Or should it be patched to be included in `--help` page?
