### ISSUE TITLE
Support standard `workspaces` field in `package.json`?

### ISSUE THREAD

**Issue by JounQin** [pnpm/pnpm#5021]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A clear and concise description of what workflow is meant to be improved.
Example: "As a developer, I often want to do <something>, but I often face <problem>".

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Consider that pnpm is used
by many people, and your particular use case might not make sense to implement in the core.

**Describe the drawbacks of your solution**

This section is important not only to identify future issues, but also for us to see whether
you thought through your request. When filling it, ask yourself what are the problems we could
have maintaining what you propose. How often will it break?

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough.

**Comment by zkochan** [comment]
It was already discussed https://github.com/pnpm/pnpm/issues/2255
