### ISSUE TITLE
`pnpm exec` outputs garbage before running command if `.pnpmfile.cjs` exists

### ISSUE THREAD

**Issue by anomiex** [pnpm/pnpm#5027]
Since 7.5.1, pnpm now outputs some garbage before running the command. This breaks things if the output is being piped into another process.

### Code to reproduce the issue:

Create an empty directory. Run the following:

1. `pnpm add hello-world-npm`
2. `echo 'module.exports = {}' > .pnpmfile.cjs`
3. `pnpm hello-world-npm`

### Expected behavior:
Output is
```
Hello World NPM
```

### Actual behavior:
Output is
```
Using hooks from: /tmp/test/.pnpmfile.cjs
Hello World NPM
```

### Additional information:

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: Linux

**Comment by anomiex** [comment]
Looks like this was a side effect of #5012, output that formerly went to the log file now goes to the console.

**Comment by zkochan** [comment]
This is the same issue as https://github.com/actions/setup-node/issues/543
