### ISSUE TITLE
pnpm prune --prod reruns postinstall script

### ISSUE THREAD

**Issue by dtoch** [pnpm/pnpm#5030]
### pnpm version:

7.5.1

### Code to reproduce the issue:

- c:/temp/testbug/package.json:

```
{
  "name": "testbug",
  "version": "0.0.0",
  "scripts": {
    "postinstall": "echo Postinstall called!"
  }
}
```

- run "pnpm install" -> postinstall script launched (OK)

```
Already up-to-date

> testbug@0.0.0 postinstall C:\Temp\testbug
> echo Postinstall called!

Postinstall called!
```

- then run "pnpm prune --prod" -> postinstall script launched again (NOK)

```
Already up-to-date

> testbug@0.0.0 postinstall C:\Temp\testbug
> echo Postinstall called!

Postinstall called!

devDependencies: skipped
```

I would expect that "pnpm prune --prod" behaves the same as "npm prune --prod" and so would not execute the postinstall script (if I test with npm instead of pnpm, then "npm prune --prod" does not run the postinstall script).

Our postinstall script runs a command available in a package defined as a devDependency ([copy-files-from-to](https://www.npmjs.com/search?q=copy-files-from-to)), so if it is run again during "pnpm prod --prune", then we get an error because that devDependency is not present anymore.

### Expected behavior:

I would expect that "pnpm prune --prod" behaves the same as "npm prune --prod" and so would not execute the postinstall script.

### Actual behavior:

Executing "pnpm prune --prod" again executes the postinstall script.

### Additional information:

 - `node -v` prints: 16.14.2
 - Windows, macOS, or Linux?: Windows

**Comment by elijaholmos** [comment]
I am experiencing this error as well in Node v18.16.0 pnpm v8.6.3. It seems very counterintuitive for a command that _removes_ dependencies to run a script related to _installing_ dependencies. At the very least, I would like to see a `--no-postinstall` flag- but preferably this behavior is removed altogether.

**Comment by windofwind** [comment]
When will this bug be fixed?

**Comment by raphaelbernhart** [comment]
+1

**Comment by raphaelbernhart** [comment]
Unsexy workaround if you are using docker...

remove the postinstall script from the `package.json` before executing the `pnpm prune` command.
