### ISSUE TITLE
Monorepo+pnpm install error

### ISSUE THREAD

**Issue by x-song** [pnpm/pnpm#5050]
### Actual behavior:Scope: all 3 workspace projects
 ENOENT  ENOENT: no such file or directory, mkdir '/path'

### Additional information:when I use pnpm install ,will develop errors，.pnpm-debug.log:
{
  "0 debug pnpm:scope": {
    "selected": 3,
    "total": 3,
    "workspacePrefix": "/Users/raymond/Desktop/monorepo-demo"
  },
  "1 error pnpm": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "mkdir",
    "path": "/path",
    "err": {
      "name": "pnpm",
      "message": "ENOENT: no such file or directory, mkdir '/path'",
      "code": "ENOENT",
      "stack": "pnpm: ENOENT: no such file or directory, mkdir '/path'"
    }
  }
}

 - `node -v` prints:v16.15.1
 - `npm -v` prints:8.11.0
 - `pnpm -v` prints:7.5.0
 - Windows, macOS, or Linux?:macOS

**Comment by x-song** [comment]
supplement ： Windows, macOS, or Linux?:macOS 12.4

**Comment by thanveershah** [comment]
where you able to solve this?
