### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by MinL-DN** [pnpm/pnpm#5056]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/24890995/179655856-7bb45580-efb0-4c2a-b21d-e1b707661134.png">

when I run `pnpm i` second time, this error show

when I run `rm -rf /XXX/pnpm/store/v3` can fix it

### pnpm version:
7.5.2

### Additional information:
node -v
v16.14.0

macOS, Linux

**Comment by zkochan** [comment]
Print also the value of depPath

**Comment by MinL-DN** [comment]
![Uploading image.png…]()
this path ?

**Comment by MinL-DN** [comment]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/24890995/179875133-648aaf79-2cce-4f82-990e-e0867be0a55d.png">
this path ?

'/Users/minl/.nvm/versions/node/v16.14.0/lib/node_modules/pnpm/dist/pnpm.cjs'

**Comment by synapdk** [comment]
I experienced this on macOS 12.6 with pnpm 7.13.0 and node 16.16.0.

**Comment by lvndry** [comment]
Seems like running

```
pnpm clean
pnpm store prune
pnpm prune
pnpm i
```

Solved the problem for me

**Comment by vjpr** [comment]
Upgrade from v7 to v8, same issue.

**Comment by jakebailey** [comment]
I hit this in https://github.com/Definitelytyped/DefinitelyTyped/pull/67455; thankfully I can "work around" this, but it does seem like there's a huge string allocated. I do wonder if this could just be an object hash instead of a serialized string. (That or it's #7079 which is the same?)

**Comment by zkochan** [comment]
> I do wonder if this could just be an object hash instead of a serialized string.

Yes, we can change it to an object hash. We need it for storing side-effects cache of dependencies (TBH, maybe we could store it simply by the dependency name but I am afraid that packages with differing dependencies may by built differently).

**Comment by jakebailey** [comment]
> However, it would be nice to be able to reproduce it.

If you're solely trying to verify it by hand, this happens on DefinitelyTyped for any change which modifies node's types; modifying a random file in `types/node` on DT and then running this should show the problem:

```console
$ pnpm ls --depth Infinity --parseable --filter '...@types/**[HEAD^1]...'
```

(Or revert https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67460)

**Comment by jakebailey** [comment]
My instructions were incomplete; I'll test the PR for you, though!
