### ISSUE TITLE
pnpm Warn peerDependency based on Incorrect Version

### ISSUE THREAD

**Issue by clementandreas97** [pnpm/pnpm#5058]
### Code to reproduce the issue:
In this [repo](https://github.com/clementandreas97/pnpm-peer-warning-repro) using `pnpm` with `auto-install-peers=false` will warn the user of missing `peerDependency` based on the wrong version of the dependency.

 In this case, when we define `"redux-thunk": "~2.3.0"`, it'll installed the correct version of `redux-thunk` which is `2.3.0`. 
```
"dependencies": {
    "redux-thunk": "~2.3.0"
},
```
 
But it'll warn that there's a missing `peerDependency` of `redux@^4.0.0` as follows:

```
 WARN  Issues with peer dependencies found
.
└─┬ redux-thunk
  └── ✕ missing peer redux@^4.0.0
Peer dependencies that should be installed:
  redux@^4.0.0 
```
But when checking the `redux-thunk` [repo](https://github.com/reduxjs/redux-thunk/blob/v2.3.0/package.json) of such version, it didn't have such `peerDependencies`. It does have such peer dependency started from [`2.4.0`](https://github.com/reduxjs/redux-thunk/blob/v2.4.0/package.json) onward (newest version).

### Expected behavior:
It shouldn't warn the missing peer dependencies since the version of the installed package doesn't depend on such `peerDependencies`.

### Actual behavior:
It warns the user about the missing peer dependencies of `redux@^4.0.0`.

### Additional information:

 - `node -v` prints: `v.14.19.0`
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
We patch this dependency because it is in Yarn's compatibility database:

https://github.com/yarnpkg/berry/blob/e5d0c366a66f25392ec818fe47afda15786d2417/packages/yarnpkg-extensions/sources/index.ts#L550-L555
