### ISSUE TITLE
failed to show cycle dependencies info 

### ISSUE THREAD

**Issue by jerrychen4git** [pnpm/pnpm#5059]
### pnpm version:
7.5.0
### Code to reproduce the issue:
in attatchment [cycletest.zip](https://github.com/pnpm/pnpm/files/9140997/cycletest.zip)
dependencies a->b->c->d->b

### Expected behavior:

show cyclic workspace dependency detail about b to b cycle

### Actual behavior:
only show  "WARN  There are cyclic workspace dependencies "  but no detail about cycle

### Additional information:
getCycles function use cached visited map to skip recursive call of  visit, but check cycle  by compare cycle[0] === dep .
if check cycle first  from a , package b to d will be added to visited map , but no cycle is  found , then check from b,  recursive call of visit function will be skipped at c . 

function getCycles(currDepsMap, visited) {
      let items = Array.from(currDepsMap.keys());
      let cycles = [];
      function visit(item, cycle) {
        let visitedDeps = visited.get(item);
        if (!visitedDeps) {
          visitedDeps = [];
          visited.set(item, visitedDeps);
        }
        let deps = currDepsMap.get(item);
        if (typeof deps === "undefined")
          return;
        for (let dep of deps) {
          if (cycle[0] === dep) {
            cycles.push(cycle);          
          }
          if (!visitedDeps.includes(dep)) {
            visitedDeps.push(dep);
            visit(dep, cycle.concat(dep));
          }
        }
      }
      for (let item of items) {       
        visit(item, [item]);
      }
      return cycles;
    }

 - `node -v` prints: v16.15.0

 - Windows, macOS, or Linux?: Windows

**Comment by gajus** [comment]
@zkochan just flagging that this is a valid bug that appears to have gone buried
