### ISSUE TITLE
peer dependencies are not installed at the second time

### ISSUE THREAD

**Issue by Miaonster** [pnpm/pnpm#5069]
### pnpm version:

7.5.2

### Code to reproduce the issue:

https://github.com/Miaonster/test-pnpm-peer

0. `auto-install-peers=true` was set in `.npmrc` file
1. remove `pnpm-lock.yaml`
2. `pnpm install` and check `node_modules/.pnpm`, peer dependency `graphql` is installed
3. remove `node_modules`
4. `pnpm install` again and check `node_modules/.pnpm`, peer dependency `graphql` is missing

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/1927546/180123445-a808f960-c837-41b0-a1f7-60dda9c827b6.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/1927546/180123493-5122aa1d-ed27-444d-9962-92bf1caeccd9.png">

### Expected behavior:

When running `pnpm install` after node_modules is removed or in the CI environment, peer dependencies should be installed correctly.

### Actual behavior:

When running `pnpm install` after node_modules is removed or in the CI environment, peer dependencies are not installed correctly. I've set `auto-install-peers=true` in .npmrc. But peer dependencies are installed correctly when there is no `pnpm-lock.yaml`.

### Additional information:

 - `node -v` prints: v18.4.0
 - Windows, macOS, or Linux?: macOS and Linux(CI)

**Comment by andriepu** [comment]
It also happened to me using pnpm v7.8.0.

As a temporary workaround, I have to run `pnpm add <any_pkg>` to trigger `peerDependencies` installation after `pnpm install`.

**Comment by emahuni** [comment]
I noticed that peer deps seem to work correctly only when installed using --shamefully-hoist, isn't it that they were supposed to install as hosting package's devDependencies? Meaning we should see them in node_modules like the devDependencies.
Had to do that to have it working:
https://stackoverflow.com/a/72982565/1673161
and I am think it has something to do with this issue

**Comment by andriepu** [comment]
I think it's resolved by v7.9.5

**Comment by zkochan** [comment]
This works as of v7.12.1
