### ISSUE TITLE
child-concurrency is parsed as a string instead of number when shared-workspace-lockfile=false

### ISSUE THREAD

**Issue by ItamarGronich** [pnpm/pnpm#5075]
### pnpm version: 
7.5.2

### Code to reproduce the issue: 
use node 17.9.1 and pnpm 7.5.2
https://github.com/ItamarGronich/pnpm-bug-child-concurrency

### Expected behavior: 
child-concurrency is parsed as number and not a string

### Actual behavior: 
child-concurrency is parsed as a string

### Additional information:
Using `share-workspace-lockfile=false` and `child-concurrency=10` doesn't work.
pnpm seems to parse it as a string instead of a number and throws:

```
ERROR  Expected `concurrency` to be a number from 1 and up

TypeError: Expected `concurrency` to be a number from 1 and up
    at pLimit (/Users/itamar.gronich/.nvm/versions/node/v17.9.1/lib/node_modules/pnpm/dist/pnpm.cjs:51274:15)
    at exports2.default (/Users/itamar.gronich/.nvm/versions/node/v17.9.1/lib/node_modules/pnpm/dist/pnpm.cjs:108848:24)
    at _rebuild (/Users/itamar.gronich/.nvm/versions/node/v17.9.1/lib/node_modules/pnpm/dist/pnpm.cjs:109882:38)
    at rebuildProjects (/Users/itamar.gronich/.nvm/versions/node/v17.9.1/lib/node_modules/pnpm/dist/pnpm.cjs:109766:41)
    at async /Users/itamar.gronich/.nvm/versions/node/v17.9.1/lib/node_modules/pnpm/dist/pnpm.cjs:110449:13
```

I'm actually not 100% sure about what `child-concurrency` does precisely.
I thought i can make pnpm install faster in a split lockfile scenario because it will just run on more packages concurrently. where it by default installs only 4 packages concurrently and then moves on to the next.

I tried some different configs - `workspace-concurrency` works as expected however.

I did some debugging and i think (i think) that it maybe comes from [here](https://github.com/pnpm/pnpm/blob/v7.5.2/packages/plugin-commands-rebuild/src/recursive.ts#L79) and possibly from [here](https://github.com/pnpm/pnpm/blob/v7.5.2/packages/plugin-commands-installation/src/recursive.ts#L147) too.

 - `node -v` prints: 17.9.1
 - macOS
 
Side track warning:
I actually discovered something i think is another bug:
when you remove the `child-concurrency` flag you can see that the first 4 packages are indeed installed concurrently.
However the next packages don't. pnpm basically waits for all 4 packages to finish, only then does it start the next packages but even then it does them one by one.
I would have expected that as soon as one package finishes, another will take it's place so there's always 4 running.
Let me know if you want me to open another bug for this.
Side tracking done.

**Comment by DudaGod** [comment]
Faced with the same problem, suffer from it =(

node@16.16.0
pnpm@7.11.0

**Comment by AGrzes** [comment]
It looks like the `childConcurrency` is handled as string on pnpm side passed to `runGroups` as is and `run-groups` is expecting a number. 

https://github.com/search?q=repo%3Apnpm%2Fpnpm+runGroups&type=code

I'm working on PR

**Comment by baymer** [comment]
The same problem
![image](https://github.com/user-attachments/assets/13d3e368-7ffd-41f2-bad6-8f5eb10de0e5)
![image](https://github.com/user-attachments/assets/3f44bece-f949-4794-abbd-6694301f8155)

But from config it is a string
![image](https://github.com/user-attachments/assets/f758fc4c-16b1-47e8-b5f4-773004c4df08)

It should be converted to the number
