### ISSUE TITLE
allowedDeprecatedVersions not working in workspace

### ISSUE THREAD

**Issue by leosin** [pnpm/pnpm#5076]
### Code to reproduce the issue:
i use `allowedDeprecatedVersions` in workspace
```js
  "pnpm": {
    "allowedDeprecatedVersions": {
      "stable": "*"
    },
  },
```

### Expected behavior:
but still tips this WARN 
```bash
 WARN  deprecated stable@0.1.8: Modern JS already.........
```

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: macOS 11.6.3

**Comment by mcmxcdev** [comment]
We are also using `allowedDeprecatedVersions` and ignoring `stable` dependency for a while successfully.

We have specified it as `"stable": "0.1.8"` though.

**Comment by zkochan** [comment]
Did you specify it in the root package.json of the workspace?

Do you use a single lockfile in your workspace?

**Comment by leosin** [comment]
@zkochan sorry ... my fault ,i put it in the root package.json ,it working
