### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#508]
How difficult would it be to add offline support?

Seeing as we already have the global store, it does not seem like it would be too tricky.

- [ ] for npm dependencies
- [ ] for Git dependencies
- [ ] document the feature
- [ ] document a recipe

**Comment by zkochan** [comment]
I suggest to store the tarballs separately from the store. In a directory structure similar to the one used by sinopia/verdaccio. That way we can even distribute it somehow. Or use it by a local registry

**Comment by zkochan** [comment]
- [ ] for npm dependencies
- [ ] for Git dependencies
