### ISSUE TITLE
`pnpm i` followed by `pnpm i --frozen-lockfile` complains about outdated lockfile

### ISSUE THREAD

**Issue by JonnyBurger** [pnpm/pnpm#5080]
We have managed to land in a state where `pnpm i --frozen-lockfile` compains that pnpm-lock.yaml is not up to date, but `pnpm i` does not fix it. This issue appeared since the latest release.

### pnpm version:

v7.6.0

### Code to reproduce the issue:

```
git clone https://github.com/remotion-dev/remotion remotion-pnpm
cd remotion-pnpm
git checkout f76e74cec19d80348813760ca053a4af83ab71bc
pnpm i
pnpm i --frozen-lockfile
```

### Expected behavior:

No error

### Actual behavior:

```
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with packages/core/package.json
```

### Additional information:

Corepack is enabled
The original lockfile was generated by v7.2.1

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by jirayrva** [comment]
I'm having the same issue after upgrading from pnpm@7.3.0 to pnpm@7.6.0. It works fine when downgrading to pnpm@7.3.0 (I didn't try other minor versions)

## When using pnpm@7.6.0

The error occurs in the projects that have `peerDependencies` in the package.json. When I remove `peerDependencies`, the install succeeds. I even tried this on the `remotion` repo and saw the same behavior.

## Additional information:

Dev machine

- Corepack: disabled
- node: 16.5.1
- OS: Windows

CI:

- Corepack: disabled
- 14.20.0
- OS: Linux

**Comment by jirayrva** [comment]
It's working fine up till 7.5.2. It seems to have been broken in 7.6.0

**Comment by yankeeinlondon** [comment]
ran into this same issue I believe ... thought I was going mad

**Comment by elevatebart** [comment]
Probably caused by this fix https://github.com/pnpm/pnpm/issues/5028

If you set `auto-install-peers` to `false` it stops misbehaving.

**Comment by zkochan** [comment]
I am looking into it.

**Comment by JonnyBurger** [comment]
Appreciate the fix! 🙌
