### ISSUE TITLE
pnpm upgrade fails to upgrade some dependencies

### ISSUE THREAD

**Issue by jcayzac** [pnpm/pnpm#5081]
### pnpm version:

`7.5.2`

### Code to reproduce the issue:

https://gist.github.com/jcayzac/00216a91f5ad704ca6dad26d7c128bd6

### Expected behavior:

`pnpm upgrade` upgrades `@types/node`.

### Actual behavior:

`pnpm upgrade` does not upgrade `@types/node`.

### Additional information:

 - `node -v` prints: `v18.3.0`
 - Windows, macOS, or Linux?: `macOS`

**Comment by mcmxcdev** [comment]
Try again with `pnpm upgrade --latest`, which ignores version ranges in `package.json`.
