### ISSUE TITLE
docs: `pnpm deploy` behavior is explained in confused way?

### ISSUE THREAD

**Issue by jjangga0214** [pnpm/pnpm#5082]
I read the example from [docs](https://pnpm.io/cli/deploy).
<img width="873" alt="스크린샷 2022-07-23 오후 9 05 24" src="https://user-images.githubusercontent.com/28584151/180604330-25f6bf0f-3bb9-4afd-bd0c-3fc3c44f8ea3.png">

I experimented with the command and found some confusion.

The docs include the line below.

```dockerfile
COPY --from=pruned /app/pruned/dist dist
```

This gives an impression the `dist` directory remains after `pnpm deploy`.
However, in fact, the command removes everything except `node_modules`.

How do you think?
IMHO, it gives confusion to readers by falsy impression and not-detailed explanation of the command itself.

Thanks!

**Comment by zkochan** [comment]
That code was pasted from here: https://github.com/pnpm/pnpm/issues/3114#issuecomment-1191247483

**Comment by Exanite** [comment]
`pnpm deploy` appears to use the files property of the package.json in the package that is being deployed.

```json
"files": [
  "dist"
],
```

Because `pnpm deploy` already filters the files, I simply copy the entire deploy folder into my Docker image.

From my testing, if the files property does not exist, everything is copied.
If the files property exists, but is empty, only the `node_modules`, `package.json`, and README files are copied.
I haven't tested the command with an `.npmignore` file, however.

This appears to be how the files property works normally when publishing (https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files), but I can't confirm because I haven't published any packages.

**Comment by fubhy** [comment]
@jjangga0214 I have a Dockerfile like that in production and it works fine (dist, etc. are copiued just fine). What @Exanite mentioned (requiring the "files" property in package.json) sounds like a good explanation of what you are facing.

For my specific use case I only needed `dist` and `node_modules` and explicitly didn't want to copy over any other files. But I agree that it would be better for the examples here to copy the entire directory (applies more generically for a wider range of use cases I'd imagine).

**Comment by zkochan** [comment]
Is this a better example? https://github.com/pnpm/pnpm.github.io/pull/292

**Comment by fubhy** [comment]
@zkochan Yeah, for most common case that's probably better. Note that this now assumes that there'll be a `index.js` file at the root which, most commonly, is probably not the case (most ppl will likely have a `dist/` or `build/` dir).

```
CMD ['node', 'dist/index.js']
``` 

It's clear enough though so feel free to leave it as is :-)

**Comment by mlai-motiv** [comment]
> `pnpm deploy` appears to use the files property of the package.json in the package that is being deployed.
> 
> ```json
> "files": [
>   "dist"
> ],
> ```
> 
> Because `pnpm deploy` already filters the files, I simply copy the entire deploy folder into my Docker image.
> 
> From my testing, if the files property does not exist, everything is copied. If the files property exists, but is empty, only the `node_modules`, `package.json`, and README files are copied. I haven't tested the command with an `.npmignore` file, however.
> 
> This appears to be how the files property works normally when publishing (https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files), but I can't confirm because I haven't published any packages.

From our testing `.npmignore` is not respected. If pnpm deploy respects package.json’s files property it may make sense to also respect `.npmignore` for consistency.
