### ISSUE TITLE
PNPM DLX not recognized on windows

### ISSUE THREAD

**Issue by Rxann** [pnpm/pnpm#5085]
### pnpm version:
6.11.0

### Code to reproduce the issue:
No Code Needed

### Expected behavior:
To be able to use pnpm dlx like npx

### Actual behavior:
'dlx' is not recognized as an internal or external command,
operable program or batch file.

### Additional information:

 - `node -v` prints: 16.13.1
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
`pnpm dlx` was only released in pnpm v6.13
