### ISSUE TITLE
Installation results in `pnpm` not an executable command ( .zshrc not in default location)

### ISSUE THREAD

**Issue by robole** [pnpm/pnpm#5103]
### Code to reproduce the issue:

I am on Ubuntu 20.04.4 LTS.

![system details](https://user-images.githubusercontent.com/3703647/181065886-ab41a9bf-f256-4ec6-acfb-390c1560c86c.png)

I installed pnpm using the [suggested command from your installation page](https://pnpm.io/installation):

```shell
 curl -fsSL https://get.pnpm.io/install.sh | sh -
```

### Expected behavior:

The program will be installed to a location where it can be executed  i.e. using `pnpm` on the commandline will run the program.

### Actual behavior:

The output of the installation script is:

```
==> Extracting pnpm binaries 7.6.0
Copying pnpm CLI from /tmp/tmp.iofxhAyyNc/pnpm to /home/rob/.local/share/pnpm/pnpm
No changes to the environment were made. Everything is already up-to-date.
```
Since `/home/rob/.local/share`  is not on the system path, it does not run from the command-line. I guess the intended location should be `/home/rob/.local/bin` ?

I fixed the issue by running ` mv /home/rob/.local/share/pnpm/pnpm /home/rob/.local/bin/pnpm`.

**Comment by zkochan** [comment]
The destination is correct. pnpm should put /home/rob/.local/share/pnpm to the system PATH

**Comment by robole** [comment]
Hi @zkochan,

After running the installation script, `pnpm` was not an executable command for me. The folder was not added to `PATH` for me:

![Kazam_screenshot_00005](https://user-images.githubusercontent.com/3703647/181101851-4898135f-5cbf-4ad6-bff1-5e345b770002.png)

The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) says this about _$HOME/.local/share:

> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used. 

And this about _.local/bin_:

> User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place. 

If you add it to `$HOME/.local/bin`, then you do not would not need to update the `PATH` as Linux distros tend to follow this specification.

**Comment by robole** [comment]
What I noticed is that pnpm has added the following to  `~./.zshrc`:

```shell
# pnpm
export PNPM_HOME="/home/rob/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
```

However, my `.zshrc` does not reside there. My shell config lives in `~/.config/zsh`, I set this in `~/.zshrenv`. This is why it does not show up in my shell...

**Comment by zkochan** [comment]
This should be solved by https://github.com/pnpm/components/pull/3, right?

**Comment by robole** [comment]
> This should be solved by [pnpm/components#3](https://github.com/pnpm/components/pull/3), right?

@zkochan In my case, that change should fix the issue, provided that it checks `$ZDOTDIR` correctly to find the location of the _.zshrc_. Would you like me to uninstall and install to check?

I don't know if this change will fix all scenarios. There could be other scenarios where people relocate _.zshrc_ and do not set `$ZDOTDIR` . That is why I mentioned putting the `pnpm` executable file in _$HOME/.local/bin_, which is an exectuable location on most systems. If you do that, then you do not need to modify `PATH`.

**Comment by zkochan** [comment]
I don't think using `.local/bin` is a good idea. Putting just pnpm might be. But pnpm also installs global packages and in that case we may override files that are manually added to `.local/bin` or added by some other package managers. I can be wrong. When I decided to use a dedicated directory, I was doing so because all similar tools use a dedicated directory (volta, nvm, npm, etc).

**Comment by robole** [comment]
Its your decision @zkochan 👍  I presented you with the issue clearly

**Comment by zkochan** [comment]
ok, so this is fixed.
