### ISSUE TITLE
Can `pnpx` support no install mode like `npx`?

### ISSUE THREAD

**Issue by wjq990112** [pnpm/pnpm#5113]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

When using `commitlint`, the official documentation suggests that setting `commit-msg` hook by `npx --no -- commitlint --edit "\${1}"`, I wanna use `pnpx` to instead `npx`, but `pnpx` does not support no install mode (or I haven't find in pnpm documentation and source code). [Can `pnpx` support no install mode like `npx`](https://docs.npmjs.com/cli/v8/commands/npx#description)?

**Describe the solution you'd like**

Like `npx`.

**Describe the drawbacks of your solution**

Haven't.

**Describe alternatives you've considered**

Using `pnpx` instead `npx` directly, install pkg every time.

**Comment by zkochan** [comment]
pnpm has a separate command for that: `pnpm exec`
Where exec is actually optional, so you may run `pnpm commitlint`.
