### ISSUE TITLE
node-options in .npmrc files are ignored.

### ISSUE THREAD

**Issue by blowsie** [pnpm/pnpm#5117]
### pnpm version:
7.6.0

### Code to reproduce the issue:
`pnpm run dev`

### Expected behavior:
respect `node-options` in `.npmrc` file

### Actual behavior:
`node-options` are not used / ignored.

### Additional information:

 - `node -v` prints: v18.4.0
 - Windows, macOS, or Linux?: Windows
 
 ---
 
 In my case I'm trying to use the 
 `--openssl-legacy-provider` setting found in my `.npmrc` file

.npmrc
 ```
shamefully-hoist=true
strict-peer-dependencies=false
node-options="--openssl-legacy-provider"
```

## Test Cases

1. `npm run dev` = **PASS**
2. `node set NODE_OPTIONS=\"--openssl-legacy-provider\" && pnpm run dev` = **PASS**
3. `pnpm run dev` = **FAIL**

console error
```
  ...
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by shoyuf** [comment]
Yes, It's works when I use `npm`

pnpm doesn't use .npmrc config?

**Comment by sokcuri** [comment]
You need to set environment variables in zshrc or bashrc.
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
export SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION=0
```

and, rerun terminal. it works!

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/7601
