### ISSUE TITLE
pnpm fails to install behind a proxy

### ISSUE THREAD

**Issue by curryingg** [pnpm/pnpm#5129]
### pnpm version:

7.6.0

### Code to reproduce the issue:

My `.npmrc` content:

```
editor=code
proxy=http://company-proxy
strict-ssl=false
```

### Expected behavior:

Installing packages should work 

### Actual behavior:

npm works normally but pnpm fails with the same config. pnpm does seem to read the config.

For example:
```
pnpm install remeda 
WARN  GET https://registry.npmjs.org/remeda error (DEPTH_ZERO_SELF_SIGNED_CERT)
```

### Additional information:

 - `node -v` prints: v18.6.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
This should work with 7.27.1

Fixed via this PR: https://github.com/pnpm/components/pull/8
