### ISSUE TITLE
Option to run script recursively including root 

### ISSUE THREAD

**Issue by ai** [pnpm/pnpm#5130]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

In 6.x `pnpm test -r` runs tests in the root and in subproject (in monorepo repository).

It was very useful to tun all tests in parallel. Now I need to have something like `pnpm test && pnpm test -r`.

**Describe the solution you'd like**

`pnpm test --recursive-with-root` or `pnpm test -R`

**Describe the drawbacks of your solution**

`--recursive-with-root` is long, `-R` is not easy to understand.

**Describe alternatives you've considered**

I thought about reverting 7.x changes with `-r`, but I think 7.x `-r` behavior is more clearly.

**Comment by zkochan** [comment]
This is already implemented: https://pnpm.io/npmrc#include-workspace-root

**Comment by ai** [comment]
Is it a config option? Can we have an argument?

It will be much simpler to use on CI, for instance.

**Comment by zkochan** [comment]
It works as a CLI option as well.

**Comment by ai** [comment]
Amazing! Can we add it to `pnpm help recursive` or `pnpm help test`? I looked for solution there and this is why I missed this option.

**Comment by zkochan** [comment]
yes, we can
