### ISSUE TITLE
Include each package's "bins" listing in the lockfile

### ISSUE THREAD

**Issue by alexeagle** [pnpm/pnpm#5131]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

Under Bazel (https://github.com/aspect-build/rules_js/ in particular) a user wants to run an npm binary by configuring Bazel's BUILD file:

```starlark
# IDEAL:

load("@npm//glslx:index.bzl", "glslx")

glslx(
    name = "webgl_typecheck",
   ...
)
```

However, in order for Bazel to know that the https://www.npmjs.com/package/glslx package contains a bin called "glslx", it has to download the package. That makes the BUILD file eagerly fetch more than we want (for example, the user might call some other unrelated target in that BUILD file, but the glslx package is fetched anyway)

To fix this eager fetch, in rules_js we only expose a symbol called "bin", like so:

```starlark
# ACTUAL:

load("@npm//glslx:index.bzl", glslx_bin = "bin")
# maybe you load more than one, so you are forced to alias-on-load:
load("@npm//other:index.bzl", other_bin = "bin")

glslx_bin.glslx(
    name = "webgl_typecheck",
   ...
)
```

We'd rather give the users the IDEAL developer experience instead.

**Describe the solution you'd like**

rules_js reads the pnpm lockfile at initialization time (a "repository rule"). If the names of each package's bins were in this file, then we wouldn't need to fetch the package to know the bins, and could give that first, nicer developer experience without the eager fetch.

**Describe the drawbacks of your solution**

Currently the pnpm lockfile has essentially `bins: {!bins_map.empty()}`. We could change the semantics so that `bins` is a list of the keys of the bins_map, and rely on that being truthy/falsey in the same way. This might be breaking since the schema of the lockfile changes. So we could instead add a `bin_names` field to the lockfile.

The lockfile gets a bit bigger, but otherwise I don't see a drawback.

**Comment by alexeagle** [comment]
Ping @zkochan would you accept a PR for this feature?

**Comment by zkochan** [comment]
I am not sure. The issue is that we already have merge conflict issues with lockfiles. Adding more stuff will increase the chance of a conflict.

If other contributors are OK with it, I am OK too. But I would replace the. Existing field.we already have the next version of the lockfile under a config. Cc @pnpm/collaborators

**Comment by alexeagle** [comment]
ping, as we never got any input from the collaborators and I happened across this issue again now

**Comment by shellscape** [comment]
I'd personally prefer a separate manifest if anything. That doesn't seem like appropriate info for the lock file.

**Comment by duhruh** [comment]
+1 for this feature as it has implications of unblocking windows related tasks see https://github.com/bazelbuild/examples/issues/327#issuecomment-1823711679. As it stands today it looks like we generate a bin file here https://github.com/aspect-build/rules_js/blob/main/npm/private/npm_link_package_store.bzl#L69 however this is only useful in shell like terminals i.e. not cmd or powershell which is the recommended terminal for bazel on windows.

 Also the default `npm install` already handles generating compliant scripts per platform see:

![image](https://github.com/pnpm/pnpm/assets/1133969/4e99efad-ffbf-4a9e-ac5f-9d78729ae0b0)

it would be really convenient to just use these than generate a new wrapper.

**Comment by alexeagle** [comment]
Okay thanks, we shipped a year ago and don't hear too many complaints about the workaround we added in Bazel, so I think I'll just close this one.
