### ISSUE TITLE
PNPM mysteriously installs unrelated packages

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#5132]
### Code to reproduce the issue:

1. Create an empty project:
   ```
   C:\>md test
   C:\>cd test
   C:\test>pnpm init
   ```
2. Install the `@babel/parser` package:
   ```
   C:\test>pnpm install @babel/parser@7.17.8

### Expected behavior:

Only `@babel/parser` should get installed, because its **package.json** file specifies no dependencies:

**@babel/parser/package.json**
```js
{
  "name": "@babel/parser",
  "version": "7.17.8",
  "description": "A JavaScript parser",
  "author": "The Babel Team (https://babel.dev/team)",
  "homepage": "https://babel.dev/docs/en/next/babel-parser",
  "bugs": "https://github.com/babel/babel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22pkg%3A+parser+%28babylon%29%22+is%3Aopen",
  "license": "MIT",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "babel",
    "javascript",
    "parser",
    "tc39",
    "ecmascript",
    "@babel/parser"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/babel/babel.git",
    "directory": "packages/babel-parser"
  },
  "main": "./lib/index.js",
  "types": "./typings/babel-parser.d.ts",
  "files": [
    "bin",
    "lib",
    "typings"
  ],
  "engines": {
    "node": ">=6.0.0"
  },
  "devDependencies": {
    "@babel/code-frame": "^7.16.7",
    "@babel/helper-fixtures": "^7.17.0",
    "@babel/helper-validator-identifier": "^7.16.7",
    "charcodes": "^0.2.0"
  },
  "bin": "./bin/babel-parser.js"
}
```

### Actual behavior:

For some reason `@babel/types` and (its dependencies) `to-fast-properties` and `@babel/helper-validator-identifier` are also getting installed:

**pnpm-lock.yaml**
```yaml
lockfileVersion: 5.3

specifiers:
  '@babel/parser': 7.17.8

dependencies:
  '@babel/parser': 7.17.8

packages:

  /@babel/helper-validator-identifier/7.18.6:
    resolution: {integrity: sha512-MmetCkz9ej86nJQV+sFCxoGGrUbU3q02kgLciwkrt9QqEB7cP39oKEY0PakknEO0Gu20SskMRi+AYZ3b1TpN9g==}
    engines: {node: '>=6.9.0'}
    dev: false

  /@babel/parser/7.17.8:
    resolution: {integrity: sha512-BoHhDJrJXqcg+ZL16Xv39H9n+AqJ4pcDrQBGZN+wHxIysrLZ3/ECwCBUch/1zUNhnsXULcONU3Ei5Hmkfk6kiQ==}
    engines: {node: '>=6.0.0'}
    hasBin: true
    dependencies:
      '@babel/types': 7.18.9
    dev: false

  /@babel/types/7.18.9:
    resolution: {integrity: sha512-WwMLAg2MvJmt/rKEVQBBhIVffMmnilX4oe0sRe7iPOHIGsqpruFHHdrfj4O1CMMtgMtCU4oPafZjDPCRgO57Wg==}
    engines: {node: '>=6.9.0'}
    dependencies:
      '@babel/helper-validator-identifier': 7.18.6
      to-fast-properties: 2.0.0
    dev: false

  /to-fast-properties/2.0.0:
    resolution: {integrity: sha512-/OaKK0xYrs3DmxRYqL/yDc+FxFUVYhDlXMhRmv3z915w2HF1tnN1omB354j8VUGO/hbRzyD6Y3sA7v7GS/ceog==}
    engines: {node: '>=4'}
    dev: false
```

This doesn't repro with NPM 8.11.0 or Yarn 1.22.19 -- those package managers install `@babel/parser` only.

### Additional information:

 - `node -v` prints: 14.19.3
 - Windows, macOS, or Linux?: Windows and Mac

**Comment by octogonz** [comment]
To clarify, these extraneous packages are not linked into the project's `node_modules` folder. They are installed as "hoisted" dependencies under `node_modules/.pnpm/`:

**node_modules/.modules.yaml**
```yaml
hoistPattern:
  - '*'
hoistedDependencies:
  /@babel/helper-validator-identifier/7.18.6:
    '@babel/helper-validator-identifier': private
  /@babel/types/7.18.9:
    '@babel/types': public
  /to-fast-properties/2.0.0:
    to-fast-properties: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@6.33.0
pendingBuilds: []
prunedAt: Mon, 01 Aug 2022 01:06:56 GMT
publicHoistPattern:
  - '*types*'
  - '*eslint*'
  - '@prettier/plugin-*'
  - '*prettier-plugin-*'
registries:
  default: https://registry.npmjs.org/
skipped: []
storeDir: C:\Users\Owner\.pnpm-store\v3
virtualStoreDir: C:\test\node_modules\.pnpm
```
I encountered this while investigating an unwanted upgrade.  The appearance of these packages in **pnpm-lock.yaml** seems to be new.  When installing a lockfile that does not have these dependencies (probably from an older PNPM?) that difference seems to be triggering an unwanted upgrade. (?)

**Comment by octogonz** [comment]
![image](https://user-images.githubusercontent.com/4673363/182060796-17eecbfd-df9c-4e58-a9e6-1b1634f370fc.png)

@zkochan is it true that...

1. Our Git-tracked files (**package.json**, **pnpmfile.cjs**, etc) are NOT the complete specification of dependencies for a package?  In fact PNPM secretly applies its own fixups of the **package.json** dependencies; AND
2. **pnpmfile.cjs** does not have the final word about dependencies, because PNPM's fixups are applied after the `readPackage()` hook;  AND
3. The table of fixup rules varies with each PNPM release (because [@yarnpkg/extensions](https://www.npmjs.com/package/@yarnpkg/extensions) is bundled into the PNPM package); AND
4. Differences across versions can cause `pnpm install` to interpret the lockfile as being inconsistent, which can trigger an unwanted upgrade

If so, this is highly counterintuitive.  Can we disable this magic somehow?  Or even better, is there a way for us to store the fixup rules explicitly in a Git-tracked file that our developers can easily be aware of and inspect?

**Comment by octogonz** [comment]
Looks like the implementation is here:

https://github.com/pnpm/pnpm/blob/4fa1091c80889bf594c10868a4e6717c19136a66/packages/core/src/install/index.ts#L59

https://github.com/pnpm/pnpm/blob/4fa1091c80889bf594c10868a4e6717c19136a66/packages/core/src/install/index.ts#L562-L569

**Comment by octogonz** [comment]
After a bunch of experiments, I determined that this behavior was introduced in PNPM version `6.32.12`.

Empirical results:

1. Start with an empty **package.json** and do `pnpm install @babel/parser@7.17.8`.  The extra entries are present. 
2. Downgrade to 6.32.11 and run `pnpm install @babel/parser@7.17.8` (or `pnpm install`).  The extra entries are still present.
3. Downgrade to 6.32.11, empty **package.json**, and delete **pnpm-lock.yaml**, and delete **node_modules/.modules.yaml**.  Then run `pnpm install @babel/parser@7.17.8`.  The extra entries are STILL present.  Somehow the bad state is remembered. ❓
4. Downgrade to 6.32.11, empty **package.json**, and delete **pnpm-lock.yaml**, and delete **node_modules/.pnpm/lock.yaml**.  Then run `pnpm install @babel/parser@7.17.8`.  Okay the extra entries are removed. ✔
5. Upgrade to 66.32.12 (without emptying **package.json**).  Run `pnpm install`.  The extra entries stay removed.
6. Upgrade to 66.32.12 (without emptying **package.json**).  Run `pnpm install @babel/parser@7.17.8`.  The extra entries are re-added.

In the past, deleting **pnpm-lock.yaml** was sufficient to fully reset PNPM's version selections.  It seems that now we must delete both **pnpm-lock.yaml** and **node_modules/.pnpm/lock.yaml**, otherwise some state is persisted. 🤔

For the 7.x series, the problem is introduced in version `7.0.1`.  

### Summary

 👉 The most recent releases unaffected by this problem are `6.32.11` and `7.0.0`.

In order to eliminate the extra dependencies, you must do all of the following:
- Downgrade PNPM
- Delete **pnpm-lock.yaml**
- Delete **node_modules/.pnpm/lock.yaml**

**Comment by octogonz** [comment]
I discussed this with Zoltan. The plan is to implement a setting to optionally disable the `@yarnpkg/extensions` fixups.

It's also worth considering whether these fixups should be applied earlier, since `pnpmfile.cjs` is less useful if it is not the final authority about version selections.

**Comment by zkochan** [comment]
https://github.com/pnpm/pnpm/pull/5140
