### ISSUE TITLE
Should provide a command to list and remove the installed node.

### ISSUE THREAD

**Issue by Garfill** [pnpm/pnpm#5155]
It's great to use `pnpm env use` to manage node version. 
But when I delete the project, I think it is necessary to list and remove all installed nodejs like use `pnpm env list node` or `pnpm env rm node@version`

**Comment by mark-omarov** [comment]
Agreed. I'd like to have both `pnpm env list` and `npm env rm` commands available.
Additionally, it'd be plain awesome if pnpm could set the current node version based on the `.npmrc` `use-node-version` or `package.json`'s `engines`, automatically, when changing directory.

It should respect version of packages in a monorepo setup (currently it does not, I've already mentioned it in the discussion #4967 ), as it's not great to tell pnpm to directly run scripts for a specific folder, especially if you end up having a large monorepo.

I will take a look during this week (maybe weekend) if I can come up with solution for some of these issues or features.

P.S.
I like the way Volta is managing node versions, unfortunately, it doesn't support pnpm. It seems to me that pnpm is getting into the space of version management, I personally think it's great, if that's the case I'm very likely to participate furthermore.
