### ISSUE TITLE
An alien directory is present in the store

### ISSUE THREAD

**Issue by Garfill** [pnpm/pnpm#5158]
When I use `pnpm store prune` , there are a few warnings that
 `An alien directory is present in the store: /Users/garfill/Library/pnpm/store/v3/files/files/00`
`An alien directory is present in the store: /Users/garfill/Library/pnpm/store/v3/files/files/01`
...
`251 other warnings`

So now I cann't ecex `pnpm store prune` to clear pnpm store

**Comment by bestickley** [comment]
@Garfill, I'm also receiving this warning but the store successfully prunes. See output below. How did you fix this?
```bash
pnpm store prune
Removed all cached metadata files
 WARN  An alien directory is present in the store: /Users/stickb/Library/pnpm/store/v3/files/files/00
 WARN  An alien directory is present in the store: /Users/stickb/Library/pnpm/store/v3/files/files/01
 WARN  An alien directory is present in the store: /Users/stickb/Library/pnpm/store/v3/files/files/02
 WARN  An alien directory is present in the store: /Users/stickb/Library/pnpm/store/v3/files/files/03
 WARN  An alien directory is present in the store: /Users/stickb/Library/pnpm/store/v3/files/files/04
 WARN  251 other warnings
Removed 6320 files
Removed 509 packages
```

**Comment by zkochan** [comment]
it is safe to remove them

**Comment by ekwoka** [comment]
Would be nice to have this reopened to get a fix.

How are the files becoming alien? why does it seem to happen so consistently?

**Comment by ekwoka** [comment]
I have not run into this in a while (I think since v10).

@LJNeon Are you on v10 or v9?
