### ISSUE TITLE
Installing a package with `bin` that points to .exe file fails on Windows

### ISSUE THREAD

**Issue by kamsar** [pnpm/pnpm#5159]
### Code to reproduce the issue:

```
npm init -y
pnpm i hasura-cli
```

### Expected behavior:

`pnpm hasura version` should work after installing the package (this works fine with npm)

### Actual behavior:

```
 WARN  Failed to create bin at C:\<snip>\node_modules\.bin\hasura. The source file at C:\<snip>\node_modules\hasura-cli\hasura does not exist.
```
 
This occurs because the package's `bin` field points at `./hasura` (https://github.com/jjangga0214/hasura-cli/blob/603dc24afccc5aa027260b7da8f64c8787a6d19c/package.json#L97), but it downloads a binary that on Windows is named `hasura.exe`. `npm` writes a batch file to `node_modules/.bin` which gets the .exe implicitly added, but pnpm does not.

I'm not sure if this is considered a bug or a feature. I can look into a PR if a fix is welcome.

### Additional information:

 - `node -v` prints: 16.14.0
 - Windows, macOS, or Linux?: Windows 11

**Comment by zkochan** [comment]
I guess we need to update https://github.com/pnpm/cmd-shim to search for a .exe file on Windows, if the exact file from bin doesn't exist.
