### ISSUE TITLE
Way to install workspace deps

### ISSUE THREAD

**Issue by jasonkuhrt** [pnpm/pnpm#5162]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A clear and concise description of what workflow is meant to be improved.
Example: "As a developer, I often want to do <something>, but I often face <problem>".

In a monorepo setting I am using `pnpm --fiilter app... install` to perform an optimized install. The issue with this is that it does not install the workspace dependencies which I use for putting things like `typescript` and `prettier`.

I'm not sure where to go from here but creating this issue. Either:

1. This is possible and I missed it in the docs (I've looked)2. 
2. It is possible but undocumented (then the issue is about better docs)3. 
3. I should not install `typescript` once in the workspace but instead in every package in the workspace (I would find this being the answer kind of confusing, because, then what is the point of workspace dependency installs?)4. 
4. We need a new flag/behaviour/feature

by many people, and your particular use case might not make sense to implement in the core.

**Describe the drawbacks of your solution**

This section is important not only to identify future issues, but also for us to see whether
you thought through your request. When filling it, ask yourself what are the problems we could
have maintaining what you propose. How often will it break?

I see that we can do this: `pnpm add -w typescript` so I wonder if the we just want to carry over that flag to this place `pnpm --filter app... install -w` which would imply to install workspace deps _as well_. Or maybe instead of a merger at least allow a separate install run to take place like `pnpm -w install` which would install just the workspace deps.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough.

**Comment by zkochan** [comment]
This should work:

```
pnpm --filter app.. --filter . -w install
```

If you are running it in the root of the workspace, then `-w` is optional. `-w` is changing the current working directory to the workspace root. It is not for selecting the workspace root package.

**Comment by jasonkuhrt** [comment]
Thanks!
