### ISSUE TITLE
pnpm install not generating declaration for repo in github

### ISSUE THREAD

**Issue by pavankris** [pnpm/pnpm#5166]
### Additional information:

I see that the pnpm lock file generated is different in both cases 
pnpm add nestjs-tracer 
generates
`/nestjs-tracer/1.2.0_@nestjs+common@8.4.0:
   resolution: {integrity: sha512-VnmtIGlK62jbuqgTjVy4gDG/SVbfc615N+IVimjTmoA/
26cyslvXX/WD/HtgE1DEgrrObBFbYJAhw0L1EUuIJQ==}`

but
pnpm add Prysm-Finance/nestjs-tracer#master
generates
`github.com/Prysm-Finance/nestjs-tracer/1c66fbda27e20fe9f78e523944b41fd2bea130b0_@nestjs+common@8.4.0:
    resolution: {tarball: https://codeload.github.com/Prysm-Finance/nestjs-tracer/tar.gz/1c66fbda27e20fe9f78e523944b41fd2bea130b0}`

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: macOS / Linux both has the same problem.

**Comment by Jack-Works** [comment]
https://github.com/Prysm-Finance/nestjs-tracer/blob/master/package.json

This script does not include a lifecycle script. I don't believe this is a pnpm problem...

**Comment by pavankris** [comment]
Thanks, adding prepare to it works.
