### ISSUE TITLE
PNPM is incorrectly providing the same dependency version to multiple packages relying on different versions

### ISSUE THREAD

**Issue by JamesSeymour** [pnpm/pnpm#5176]
### Code to reproduce the issue:
Attached is a very basic project with two packages, each relying on only a single devDependency (jest) - but each package has a different version of that same dependency. I have added a script `jest-version` which just logs the jest version for ease of use.

[pnpm-dependency-issue.zip](https://github.com/pnpm/pnpm/files/9283163/pnpm-dependency-issue.zip)

Package-1 - package.json:
```{
  "name": "package-1",
  "version": "1.0.0",
  "description": "Package 1",
  "license": "UNLICENSED",
  "scripts": {
    "jest-version": "jest --version"
  },
  "devDependencies": {
    "jest": "^27.5.1"
  }
}
```

Package-2 - package.json:
```{
  "name": "package-2",
  "version": "1.0.0",
  "description": "Package 2",
  "license": "UNLICENSED",
  "scripts": {
    "jest-version": "jest --version"
  },
  "devDependencies": {
    "jest": "^24.8.0"
  }
}
```

### Expected behaviour:
I would expect when running `pnpm jest-version` in package-1 I would get an output of `27.5.1`, and when running `pnpm jest-version` in package-2 I would get an output of `24.8.0`.

### Actual behaviour:
I get an output of `24.8.0` for the command in both packages.

### Additional information:
 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: Windows and macOS.

For what its worth, this does behave expected on npm (8.11.0).

**Comment by VividLemon** [comment]
I'm not a contributor or anything, just curious, but this seems to be only a "checking command version" problem, the actual packages they're using are different

![image](https://user-images.githubusercontent.com/31498096/183549283-f87b04a1-9e86-4cf2-9b64-f519429c202a.png)

**Comment by JamesSeymour** [comment]
I can also see that the packages _look_ correct in the node_modules. But when a command is run, it uses the incorrect package. For example I just added a basic test to package-1 and added a standard `"test": "jest"` to the scripts in the package.json. I then went into the root of the project and added a console log (logging the version) to where the tests are ran internally in jest in the different versions:

`node_modules/.pnpm/@jest+core@24.9.0/node_modules/jest-runner/build/runTest.js`
and
`node_modules/.pnpm/@jest+core@27.5.1/node_modules/jest-runner/build/runTest.js`

When running `pnpm test` in package-1 it logs 24.9.0 - not what I would expect.

**Comment by grimnomad** [comment]
Hey, I have a similiar problem. Running `jest --showConfig` or `jest --version` will output an other version than `pnpm why jest`.

**Comment by zkochan** [comment]
Looks like it is some issue with Jest, when hoisting is used.

Add this `.npmrc` to the root of your workspace:

```
hoist=false
```

Run `pnpm install` and it works fine.

**Comment by palexandrefernandes** [comment]
I'm unfortunately experiencing a similar problematic behaviour. I don't think this is an issue with Jest and hoisitng in particular given that this used to work properly before I upgraded to pnpm 7 (in version 6.4.0). Everything worked as expected before updating, the correct version of Jest was instanced in the expected workspace, but not anymore.

**Comment by havenchyk** [comment]
in v6 in `packages/A` I run `pnpm jest --version` and see the version from `packages/A/package.json` - 28, with pnpm 7 I do the same and get another version - 26.6.3 (which is probably from `packages/B` package.json)

I checked `packages/A/node_modules/.bin/jest` and found out there

`exec node "$basedir/../../../../nodemodules/.pnpm/jest@28.1.0@types+node@14.17.21/node_modules/jest/bin/jest.js" "$@"`
which is correct 🙂 and if I run this command manually in my terminal from the `packages/A/node_modules/.bin` folder, it works as expected - prints version 28

the main diff I found is in this line `export NODE_PATH="/Users/uhavenchyk/p/my-project/node_modules/.pnpm/node_modules"` from the `packages/A/node_modules/.bin/jest` in v7, in v6 it's a way longer

**Comment by ConcernedHobbit** [comment]
This seems to also happen with tsc and multiple @types library versions, with tsc always using the alphabetically first (older) @types library.

**Comment by zkochan** [comment]
@ConcernedHobbit does this help with the types issue https://github.com/pnpm/pnpm/issues/5176#issuecomment-1211238359?

**Comment by zkochan** [comment]
Looks like it works if I remove NODE_PATH from the command shim... And all tests seem to pass. But I am hesitant. It used to be required.

https://github.com/pnpm/pnpm/pull/5290

**Comment by WhiteKiwi** [comment]
I am using the public-hoist-pattern option in Monorepo as follows.
```
public-hoist-pattern[]='*webpack*'
public-hoist-pattern[]='*babel*'
public-hoist-pattern[]='*eslint*'
public-hoist-pattern[]=buffer
public-hoist-pattern[]=script-loader
```
hoist=false solves the jest issue, but I have to install the libraries above myself 😭 .
Is there a good way to solve it without `hoist=false`?

Our team is in the process of pnpm 7 migration today.
This problem is expected to be a big issue in the use of monorepo at pnpm7. 🙇

**Comment by maschwenk** [comment]
I highly recommend turning off `public-hoist-pattern[]` completely. We had it on for months with a large monorepo and it caused us unbelievable issues because we had phantom `@types` dependencies that would result in very confusing and non-deterministic typechecking results.

**Comment by WhiteKiwi** [comment]
Thanks for the comment. we were forced to use it because it is legacy. We cleared all the public-hoist-pattern today. 👍

**Comment by zgriesinger** [comment]
If anyone else is hitting this we have a sort of workaround that doesn't require changing hoist patterns
```
"jest": "./node_modules/jest/bin/jest.js --colors",
 "test": "./node_modules/jest/bin/jest.js --colors",
 ```
 This resolves to the right version of jest

**Comment by ConcernedHobbit** [comment]
> @ConcernedHobbit does this help with the types issue [#5176 (comment)](https://github.com/pnpm/pnpm/issues/5176#issuecomment-1211238359)?

Sure, this helps with jest and type issues, but then there's problems with developing component libraries using peerDependencies for react, as then they aren't installed. This then requires configuring `public-hoist-pattern` for all dependencies that might be necessary. Again, an exclusive `public-hoist-pattern-exclude` option would be a lifesaver. Now I'm spending more time manually playing whack-a-mole with packages that should be hoisted than necessary.

**Comment by ConcernedHobbit** [comment]
> Looks like it works if I remove NODE_PATH from the command shim... And all tests seem to pass. But I am hesitant. It used to be required.
> 
> #5290

This would probably be the best fix, as I would expect `jest` with multiple versions to work natively in pnpm. The fact that it doesn't and configuration tricks are required is a bit disappointing :/ Any updates? Seems like it's stuck on some sort of Next issue.

**Comment by ConcernedHobbit** [comment]
> @ConcernedHobbit does this help with the types issue [#5176 (comment)](https://github.com/pnpm/pnpm/issues/5176#issuecomment-1211238359)?

Dang, `@types/react` is breaking again. The weird error message may be a clue to what's going wrong. To recap, the project has two packages, one of which uses `@types/react@18` and one uses `@types/react@17`. With any combination of `hoist=false`, `public-hoist-pattern=[]`, `public-hoist-pattern[]=`*types*` etc., `tsc` fails with a weird import:

(this is in the package which has `@types/react@^17`)
```
Type 'React.ReactNode' is not assignable to type 'import("/home/[redacted-path-to-root-folder]/node_modules/.pnpm/@types+react@18.0.21/node_modules/@types/react/index").ReactNode'.
```

This might be a tsc issue, but I would still assume that it should work with pnpm out-of-the-box.

**Comment by boiboif** [comment]
> @ConcernedHobbit https://github.com/pnpm/pnpm/issues/5176#issuecomment-1280502345 
I have the same problem. Have you solved this problem?

**Comment by asprouse** [comment]
@zkochan Is there a reason `extend-node-path` was removed? Before upgrading to v7 I used this to workaround the issue. Now the suggested fix is to set `hoist=false`. We have always used the default hoist settings and I always thought pnpm was strict by default when it came to dependencies. What are the downsides to `hoist=false`?

**Comment by asprouse** [comment]
I am trying to get PNPM to work with [NX](https://nx.dev/) and this issue breaks distributed task execution. Since NX uses PNPM to run `package.json` scripts shimming the node path leads to wrong versions being used. I tried `hoist=false` but that breaks NX 🤦. Restoring the `extend-node-path` seems like a good option if we cannot merge https://github.com/pnpm/pnpm/pull/5290. I am happy to make a PR

**Comment by zkochan** [comment]
> I tried hoist=false but that breaks NX 🤦.

Instead of `hoist=false` you can try to specifically hoist dependencies that nx cannot find by setting [hoist-pattern](https://pnpm.io/npmrc#hoist-pattern). Or you can you [package extensions](https://pnpm.io/package_json#pnpmpackageextensions)

>  What are the downsides to hoist=false?

The only downside is that some packages are published with require statements to other packages that are not added to their dependencies. These package will fail with hoist=false. You can selectively hoist the packages that appear in the errors or use package extensions to add the missing dependencies to the packages that use them.

**Comment by iobuhov** [comment]
Have same problem on 7.27.0
```
❯ pnpm -v
7.27.0

❯ pnpm ls --depth 0 jest
Legend: production dependency, optional only, dev only

datagrid-number-filter-web@2.3.1

devDependencies:
jest 29.4.2

❯ pnpm exec jest --version
26.6.3
```

**Comment by zkochan** [comment]
The current workaround for this issue is to set `extra-node-path=false` in an `.npmrc` file in the root of your workspace. Then remove node_modules and reinstall it.

**Comment by zkochan** [comment]
I cannot reproduce the `next dev` issue anymore. And I cannot think of a reason why anything would break if I remove NODE_PATH patching. So, I will remove it

**Comment by levrik** [comment]
@zkochan This change suddenly broke all of our CI builds. Will post more details as soon as I know more details but manually setting `extend-node-path=true` in our `.npmrc` fixed it.

**Comment by levrik** [comment]
@zkochan This change suddenly broke all of our CI builds with GraphQL Codegen packages. Manually setting `extend-node-path=true` in our `.npmrc` seems to fix it. Setting `public-hoist-pattern[]=*@graphql-codegen*` also helped.

**Comment by zkochan** [comment]
I have downgraded latest.

Create a repo that reproduces the issue if you can.

**Comment by levrik** [comment]
@zkochan Still trying to figure out if this change in PNPM maybe also just made a configuration mistake on our side apparent that just worked by accident so far. Will come back with results soon.

**Comment by iobuhov** [comment]
+1
Event if you have `hoist=*` module resolution is not working when update to 7.29.
Adding "phantom" packages to `public-hoist-pattern` helps, but because it's minor update it probably should not break current setup.

**Comment by levrik** [comment]
@zkochan Okay. Figured out that in my case it was never intended to work from the GraphQL Codegen side and just happened to work by accident in Yarn and PNPM until now. To cite from https://github.com/dotansimha/graphql-code-generator/issues/3275#issuecomment-578509267:

> The basic instruction is to install the plugins you are using under plugins:  section.

We previously used a plugin in that config section which wasn't installed as a direct dependency. This change in PNPM here broke it when not following the intended way.

**Comment by zkochan** [comment]
Right, I was not expecting that the removal of NODE_PATH would break anything as the `node_modules/.pnpm/node_modules` directory should be looked into by default, when resolving require statements in subdirs of `node_modules/.pnpm/`. Maybe some pluggable tools use the value of NODE_PATH explicitly.

**Comment by zkochan** [comment]
:ship: 7.29.3

**Comment by phoenixeliot** [comment]
I have this in my package.json to work around a Jest issue with snapshots not working with prettier v3:
```
    "prettier": "^3.0.0",
    "prettier-2": "npm:prettier@^2",
```

It seems that, when I do `pnpm install`, it nondeterministically decides which one gets to be the one that runs when I do `pnpm exec prettier --version`. Removing one of the two to force the other to be the only installed, reinstalling, then putting it back in package.json, reinstalling, seems to result in a random outcome as to which one is the one used for `pnpm exec prettier`.

I guess I'll modify my package.json script to use the exact node_modules path to prettier and use that instead.

**Comment by superbogy** [comment]
why this issue closed? Is it fixed? It reproduce on my machine. I used the latest pnpm version. it make me crazy.

**Comment by MarlonPassos-git** [comment]
Hey, I was having this problem with projects that used two different versions of @types/node

I fix this problem with these two lines in my `.npmrc` file

```
hoist-pattern[]=*types*
hoist-pattern[]=!@types/node
```

The other dependencies continued to be shared, but @types/node was not

**Comment by ibrahimqasim-abtrace** [comment]
I'm not sure if this is the exact same issue, but I'm having the following problem:

```
Type 'import(".../node_modules/.pnpm/jose@5.9.2/node_modules/jose/dist/types/types").JWK' is not assignable to type 'import(".../node_modules/.pnpm/jose@4.15.9/node_modules/jose/dist/types/types").JWK'.
```

It would seem that TSC is loading the wrong type. From reading around, this seems like TSC is just picking the first dependency from `.pnpm/`.

```
hoist-pattern[]=*types*
hoist-pattern[]=!@types/node
```

Did not help.

**Comment by aaroncraigongithub** [comment]
I'm seeing the same issue in 9.15.3.

This is an example of the error I'm seeing:
```
│ app/routes/auth.login/route.tsx(41,12): error TS2786: 'Form' cannot be used as a JSX component.
│   Its type 'ForwardRefExoticComponent<RemixFormProps & RefAttributes<HTMLFormElement>>' is not a valid JSX element type.
│     Type 'ForwardRefExoticComponent<RemixFormProps & RefAttributes<HTMLFormElement>>' is not assignable to type '(props: any, deprecatedLe…
│       Type 'import("/Users/aaron/dev/waitify/waitify-mono/node_modules/.pnpm/@types+react@19.0.3/node_modules/@types/react/index").ReactNo…
│         Type 'bigint' is not assignable to type 'ReactNode'.
```

You can see that `@types/react@19.0.3` is being referenced, but my package.json is asking for `"@types/react": "^18.2.31",`.
You can also see that the link under `node_modules` is correctly pointing at `@types/react@18.3.18`:

```
react -> ../../../../node_modules/.pnpm/@types+react@18.3.18/node_modules/@types/react
```

I have tried the `hoist-pattern` entries in .npmrc as well as adding `paths` entries in package.json. None of these workarounds work for me.
