### ISSUE TITLE
In a monorepo: `pnpm install --filter "package..."` doesn't install root directory packages

### ISSUE THREAD

**Issue by baptisteArno** [pnpm/pnpm#5179]
### Code to reproduce the issue:

- Create a new turborepo project: `npx create-turbo@latest`
-  remove all `node_modules/`
- Install dependencies of only the `web` package: `pnpm install --filter web...`
- Run from the root folder: `pnpm turbo run build --scope=web`
- See error: `Command failed with ENOENT: turbo`

### Expected behavior:

`turbo` should be installed because it is present in the root directory of the monorepo.

### Actual behavior:

`Command failed with ENOENT: turbo`

**Comment by zkochan** [comment]
But you literally selected only `web` and its dependencies. If you want to also install in the root, you should select it. This should work:

```
pnpm install --filter web... --filter .
```

**Comment by baptisteArno** [comment]
Thank you for the info!
