### ISSUE TITLE
frozen-lockfile fails in CI environment using the latest pnpm version

### ISSUE THREAD

**Issue by aholtkamp** [pnpm/pnpm#5187]
Possibly related to #5124 but the problem is not fixed for us. Maybe this is even intended?

### pnpm version:

7.9.0

### Code to reproduce the issue:

- Have a package.json containing some dependencies and a "publishConfig" -> "directory" entry
- Install pnpm 7.1.5
- Execute: pnpm install
- Upgrade to pnpm 7.9.0
- Execute: pnpm install --frozen-lockfile

### Expected behavior:

The installation works. No error or non-zero exit code.

### Actual behavior:

Lockfile is up to date, resolution step is skipped
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json

Exit Code: 1

### Additional information:

 - `node -v` prints: v16.15.0
 - Linux

**Comment by zkochan** [comment]
Do you use `auto-install-peers=true`?

**Comment by aholtkamp** [comment]
No, auto-install-peers is not set.

**Comment by zkochan** [comment]
So the issue is that we added the publishDirectory field to the lockfile. You probably just need to update your lockfile.

**Comment by aholtkamp** [comment]
Hm...ok. Our CI usually uses the latest PNPM version. I assume this is then not recommended as the build might suddenly fail? Would you suggest always using a fixed version of pnpm in CI environments?

**Comment by zkochan** [comment]
It is your choice. I try to not cause such issues but of course pinning the version is the most reliable solution.

**Comment by aholtkamp** [comment]
Thanks, this issue can be considered solved.

**Comment by pitgrap** [comment]
Changing the `pnpm-lock.yaml` format is imho the most breaking change a package manager can do (like the one from 6 to 7). I would expect a 8.x release for that. 
It would be nice to not pin the version in CI (because of manually update all references all the time), but expect a stable ci build and lock-file within a major version. @zkochan, please consider this.
