### ISSUE TITLE
Flag --if-present failing in v7.9.0

### ISSUE THREAD

**Issue by cameroncf** [pnpm/pnpm#5189]
Looks like the --if-present flag is not working in v7.9.0. This is my first attempt using this flag, I've not tested it on previous versions of PNPM.

### pnpm version:
7.9.0

### Code to reproduce the issue:
`pnpm invalidscriptname --if-present`

### Expected behavior:
Command should succeed when script is not present.

### Actual behavior:
```
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: invalidscriptname --if-present
spawn invalidscriptname ENOENT
```

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
The flag should be before the script name.

```
pnpm --if-present invalidscriptname
```

See the docs: https://pnpm.io/cli/run#options
