### ISSUE TITLE
pnpm audit  failed with: ERROR  Cannot read properties of undefined (reading 'metadata')

### ISSUE THREAD

**Issue by timtong1982** [pnpm/pnpm#5200]
### pnpm version:
6.32.9
tested 7.9.0 as well, same

### Code to reproduce the issue:
mono repo with `pnpm-workspace.yaml`

### Expected behavior:
Show audit result

### Actual behavior:
 ERROR  Cannot read properties of undefined (reading 'metadata')

### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: macOS

**Comment by Shinyaigeek** [comment]
I cannot reproduce this error with v7.9.3. Can you share the repository or stackblitz for reproduction?

**Comment by timtong1982** [comment]
The root cause is 

I am using a private az npm registry which doesn't have audit endpoint, this will lead a 404 error on getting the AuditReport

the catch part of that function doesn't process this error as well, so the code will goes down all the way to 
`const vulnerabilities = auditReport.metadata.vulnerabilities;`
and then this error pops

**Comment by timtong1982** [comment]
https://github.com/pnpm/pnpm/blob/8103f92bd60d80b1e880cbb46bdd43c038024076/packages/plugin-commands-audit/src/audit.ts

this issue is still there, I think we need capture the 404 error in the 

```
} catch (err: any) { // eslint-disable-line
    if (opts.ignoreRegistryErrors) {
      return {
        exitCode: 0,
        output: err.message,
      }
    }
  }
```

**Comment by timtong1982** [comment]
PR added:
#5246
