### ISSUE TITLE
Can't use dependency's dependency without adding it explicitly

### ISSUE THREAD

**Issue by Lutymane** [pnpm/pnpm#5206]
### pnpm version:
7.9.0
### Code to reproduce the issue:
* Create a fresh project: `pnpm init`
* Add a package: `pnpm add vue`
* Create `index.js` and import vue's dependency package:
```
import { isSVGTag } from "@vue/shared";
console.log(isSVGTag("mesh"));
```
* Run `index.js`
### Expected behavior:
Node should be able to use `@vue/shared` library as it's a direct dependency of `vue`, so there should be no error.

### Actual behavior:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vue/shared'`

Since pnpm only creates links in `node_modules` for project's dependencies, Node can't access dependencies' dependencies, as they all would normally be placed in one `node_modules` folder.

### Additional information:
Why is it important? Take Vue as an example, it's recommended to install single `vue` package, so it's ensured all dependencies have correct and matching versions to prevent any problems and errors. 

The workaround of this pnpm issue is to explicitly add needed dependent package, BUT this goes against the recommendations, let alone tedious to manually control matching proper versions.

So I assume it may be overcome by adding an extra flag for `pnpm add` to expose dep's dependencies in `node_modules` which will also be noted in lockfile, so other people who would use the project won't have any troubles doing `pnpm install` as those deps will automatically be exposed. 

Besides there can be even multiple flavors of such flag, like `direct` so only dep's `package.json` deps will be exposed and `recursive` to expose every dep in dep's tree of that package

 - `node -v` prints:
 - 16.3.0
 - Windows, macOS, or Linux?:
Windows

**Comment by zkochan** [comment]
No, it is not recommended to require code that is not in your dependencies.

There is an option to make pnpm create a hoisted node_modules: https://pnpm.io/npmrc#node-linker

but what you are trying to do is incorrect and error prone.

**Comment by Lutymane** [comment]
Sorry, it took so long to reply. I don't think you really understood the issue. I'm just following recommendations - as I said having one dep requiring other dependencies in case of Vue is in turn the only correct, safe and error-less way to do it (mostly developing plugins and tooling)

And the real solution was actually to use [shamefully-hoist](https://pnpm.io/npmrc#shamefully-hoist) option
