### ISSUE TITLE
pnpm not install peers on reinstall

### ISSUE THREAD

**Issue by NoDocCat** [pnpm/pnpm#5213]
### pnpm version:
7.9.0
### Code to reproduce the issue:
```text
auto-install-peers = true
strict-peer-dependencies = true
```

```shell
pnpm add -D eslint-config-standard
rm -rf ./node_modules/
pnpm install
```

### Expected behavior:
PeerDependencies should on proper handling

### Actual behavior:
proper handling only on package add, reinstall lack peerDependencies in node_modules

### Additional information:

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: macOS

### Extra
On package add:
![image](https://user-images.githubusercontent.com/20502666/184809844-e29a4b8e-ae56-4e3d-8a81-cb101ece85c6.png)

On reinstall:
![image](https://user-images.githubusercontent.com/20502666/184809979-bfe5b3b4-bb2f-4020-82fc-b565610d142c.png)

### Temporary workaround
```text
prefer-frozen-lockfile = false
```

**Comment by lenovouser** [comment]
Also having this issue 😢
