### ISSUE TITLE
Building isolated workspace app fails when patching

### ISSUE THREAD

**Issue by focux** [pnpm/pnpm#5234]
### Expected behavior:
Installing dependencies successfully.

### Actual behavior:
I have a workspace with many apps, and some of those apps have patched dependencies. When creating a docker image to build `app A`, which doesn't need any patch, I only copy inside the container the `app A` folder and the shared libs it depends on. When pnpm is installing the dependencies, it fails with this error:
> ERR_PNPM_PATCH_NOT_APPLIED: The following patches were not applied: ...

I know that the issue is because `app A` doesn't need any patch, I tried moving the patches and the `patchedDependencies` property to each app package.json but patching didn't work. Am I doing something wrong?

Right now the workaround is to manually remove the `patchedDependencies` from the root `package.json` everytime I'm going to build one of the apps.

### Additional information:

 - `node -v` prints: v16.13.2
 - Windows, macOS, or Linux?: macOS

**Comment by larrybahr-ocelot** [comment]
Running into the same issue on `7.9.4` running Linux.
Any chance extra packages listed in `patchedDependencies` could be ignored?

**Comment by zkochan** [comment]
Don't you copy the lockfile to the docker image? I don't think this error would happen with an up-to-date lockfile. So basically `pnpm install --frozen-lockfile` should work.

**Comment by larrybahr-ocelot** [comment]
zkochan that might work, but for reasons not worth going into here that is not a great option.

For anyone else that stumbles across this
![image](https://user-images.githubusercontent.com/97913654/190512741-24652170-f2a5-4fbd-aeb3-0986d4168254.png)

**Comment by gajus** [comment]
Thanks for mentioning `allowNonAppliedPatches`. Used it to devise a workaround for https://github.com/vercel/turbo/issues/2788

**Comment by SPAHI4** [comment]
allowNonAppliedPatches works, but I'd like to set it on the workspace level, not all monorepo

**Comment by michielvanderros-tomtom** [comment]
That comment to prevent `ERR_PNPM_PATCH_NOT_APPLIED` by adding `allowNonAppliedPatches: true` is a life saver when using CI/CD in a monorepo. In our case with some apps on NextJS 14 and some migrated to NextJS 15.
