### ISSUE TITLE
require.resolve failing to find other workspace packages 

### ISSUE THREAD

**Issue by xenobytezero** [pnpm/pnpm#5237]
I don't know if this is a bug, as I understand why it's behaving the way it is, but as far as I could see there is no documentation or warnings that this is an issue, and no details on how to solve it. I also wouldn't consider it a niche issue, as it feels like something that should be very up front if it was expected.

In a workspace situation, using `require.resolve` to find the path to a second workspace package via third workspace package fails in an unexpected way. This is reproducable in the repo below.

* We have a workspace with three packages, `main`, `support` and `alt`. 
* `support` has a utility function for finding the root path of a NPM package.
* If we call this function from `main`, in an attempt to find a package installed normally via NPM, it works as expected, and produces the same path as directly calling `require.resolve` from main.
* However if we attempt to find the other workspace package `alt`, directly calling `require.resolve` from `main` works correctly, however using the utility function fails.
* both `support` and `alt` are dependencies of `main` 

As mentioned, I understand why this is failing as the folder structure means that the symlinked utility package cant find the other workspace packages, but as far as I can see there is no documented solution for solving this while still maintaining the isolated linker.

---

### Code to reproduce the issue:
https://github.com/xenobytezero/pnpm-bug-repo

1. Clone repo
2. `pnpm install`
3. `pnpm --filter @mypkg/main build`
3. `pnpm --filter @mypkg/main start`
 
### Expected behavior:

Output should be

```
Find Lodash...
C:\Projects\DUMP\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js
C:\Projects\DUMP\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash
Find Workpsace Pkg..
C:\Projects\DUMP\packages\alt\dist\index.js
C:\Projects\DUMP\packages\alt
```

### Actual behavior:
```
Find Lodash...
C:\Projects\DUMP\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js
C:\Projects\DUMP\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash
Find Workpsace Pkg..
C:\Projects\DUMP\packages\alt\dist\index.js
null
```

### Additional information:

 - `node -v` prints: v16.5.0
 - Windows, macOS, or Linux?: Windows 10

**Comment by WoLfulus** [comment]
How have you worked around this issue? I have the exact same scenario right now and I'm unsure how to properly solve it.

**Comment by xenobytezero** [comment]
I ended up just modifying my utility function to by default start at `process.cwd()` unless specified, and adding the workspace dependency as normal.

```typescript
export function getPathToModule(packageName: string, useCwd: boolean = true): string {
  // we look for the package.json in a package
  const packageJson = `${packageName}/package.json`;

  const paths = useCwd ? [path.resolve(process.cwd(), './node_modules')] : undefined;

  // try and resolve the file
  const packageJsonPath = require.resolve(packageJson, { paths });

  // get the root folder
  const packagePath = path.dirname(packageJsonPath);

  return packagePath;
}

```

**Comment by dschmidt** [comment]
Are there any hints where to start debugging? 
Grepping for `resolve` is unsurprisingly little helpful 😅

**Comment by nachoaldamav** [comment]
Hi! For reference in case anyone finds this issue, the reason for this issue is that `@mypkg/alt` is not a dependency of `@mypkg/support` so, as the `require.resolve` is running inside `@mypkg/support`, Node won't find it.

There are two ways to fix this:
- The same as this [comment](https://github.com/pnpm/pnpm/issues/5237#issuecomment-1248325866), use the Current Work Directory as a path for `require.resolve`, but you can just add it, like this:
```ts
const packageJsonPath = require.resolve(packageJson, {
    paths: [
      process.cwd()
    ],
  });
```

- Or you can add `@mypkg/alt` as a dependency of `@mypkg/support`
```json
{
  "name": "@mypkg/support",
  // ...
  "dependencies": {
    "lodash": "^4.17.21",
    "typescript": "^4.7.4",
    "@mypkg/alt": "workspace:*"
  },
}
```
