### ISSUE TITLE
pnpm update command works incorrectly

### ISSUE THREAD

**Issue by vladIsLove-hub** [pnpm/pnpm#5242]
Hi, I have noticed that `pnpm update` works incorrectly.

F.e., there is the library: `didyoumean2` and in my project, we need to install `didyoumean@3.1.1`. This library has a `ramda` dependency with the following version: `0.26.1` and we need to up such version to `0.27.1`, but I am still not able to do that.
When I am writing `pnpm update` ramda nothing did update and ramda still has a `0.26.1` version, I am getting the message: Already up to date. 

### Code to reproduce the issue:

1. `pnpm add didyoumean2@3.1.1`
2.  Check the `ramda` package version (should be 0.26.1)
3.  `pnpm update ramda`
4. Check the `ramda` version again (After that, I still have 0.26.1v.)

### Expected behavior:

The `ramda` package must be changed to the latest version.

### Actual behavior:

The `ramda` package still has 0.26.1 version.

### Additional information:

 - `nodejs -v`: 16.14.0
 - OS: Windows.

**Comment by nnhjs** [comment]
Can you provide package.json file?  When you run pnpm update ramda → ramda update adhering to ranges specified in package.json. 
Read more: [pnpm update](https://pnpm.io/cli/update)

**Comment by vladIsLove-hub** [comment]
```json
{
  "name": "pnpm-update-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "didyoumean2": "3.1.1"
  }
}
```

It seems to me that you didn't understand me completely. I will try to explain it more clearly.

I have installed `didyoumean2` 3.1.1v package and this package has its own dependencies and one of them: `ramda`. The `ramda` package did not specify in my package.json explicitly, because `ramda` already there is in the `didyoumean2` package.json file.

When I am writing **pnpm update ramda** I still have the current `ramda` package version instead of the latest version.

**Comment by nnhjs** [comment]
Currently, I understand. ramda is not updated because ramda is not installed directly in the package. If you want to update the version of ramda you must update it from package didyoumean@3.1.
WDYT?

**Comment by vladIsLove-hub** [comment]
At the moment I have a particular case where I need to update such package on the CI. Should I join into node_modules every time when I would like to deploy my app to CI?

**Comment by nnhjs** [comment]
I think with the use case, you can fork didyoumean2 package after changing version of ramda. After pushing new package to npm store. Some resource you can read: 
https://docs.npmjs.com/creating-and-publishing-private-packages
I hope it can help you.

**Comment by vladIsLove-hub** [comment]
Yes, makes sense. I think it could help me in my particular case. Thank you for your time.
I assume I can close this issue.

**Comment by nnhjs** [comment]
Yes. I'm happy to help you. If you get an error then create an issue.  Good day :D

**Comment by vladIsLove-hub** [comment]
Thanks!
