### ISSUE TITLE
Symlink for a local package with `link:` is not created if the folder didn't exist yet

### ISSUE THREAD

**Issue by mistic** [pnpm/pnpm#5259]
I'm considering migrating a project currently using `yarn` into `pnpm` but I'm hitting a critical behaviour difference that I'm not able to match and it is blocking the migration. 

Currently, by using yarn, I can define a dependency on a local package using `link:` in the `package.json` and even if the referenced package didn't exist yet, a symlink in the node_modules will be created to the location mentioned in the `package.json`. That is important as I'm using an external build system that will only build those local packages after the package manager finishes the installation. Is there a way to replicate this using `pnpm` or should I try to do this in a sort of a script/hook that runs after the package manager and create those symlinks by myself?

**Comment by zkochan** [comment]
Isn't this solved by https://github.com/pnpm/pnpm/pull/5253?

**Comment by mistic** [comment]
@zkochan that is really a coincidence. I've tried this yesterday on version `v7.9.4` and only opened the issue today. Just tried right now on `v7.9.5` and the problem is indeed fixed by the PR you linked. Thanks for the quick follow up on this.
