### ISSUE TITLE
running scripts with `shell-emulator` fails with ELIFECYCLE  Command failed with exit code -7

### ISSUE THREAD

**Issue by ghiscoding** [pnpm/pnpm#5260]
### pnpm version:
pnpm version 7.5.x

### Code to reproduce the issue:
You can see this Lerna-Lite [PR](https://github.com/ghiscoding/lerna-lite/runs/8002929877?check_suite_focus=true) which failed in GitHub Action in a Ubuntu-latest container. While on my local I use Windows only, I need a cross platform way of running scripts 

by switching to `shell-emulator` I got these 2 scripts that now fail
```sh
pnpm config set shell-emulator true
prettier --check **/*.{js,ts,yml,json}
```
```sh
rimraf --maxBusyTries=10 packages/*/dist
```
the latter one returns this error
```sh
No matches found: "packages/*/dist"
```
which might indicate that the way to read folder/project path is not the same with `shell-emulator`, could that be it?

### Expected behavior:

no failure 

### Actual behavior:

some script are fail with this error
```sh
ELIFECYCLE  Command failed with exit code -7
```

### Additional information:

 - `node -v` prints: 16.17.0
 - Windows, macOS, or Linux?: Windows 10 Pro (lobal) and also Ubuton latest on GitHub Action box

**Comment by ghiscoding** [comment]
I went a different route, so this issue isn't much of a problem anymore and so I can just close it

**Comment by tal-rofe** [comment]
Why the issue is closed? I'm having same problem..
