### ISSUE TITLE
Please restore the copyright notice in npm-conf

### ISSUE THREAD

**Issue by adjenks** [pnpm/pnpm#5261]
**Describe the user story**
You removed the copyright from the package you forked: https://github.com/kevva/npm-conf
This is not respectful or legal:
https://opensource.stackexchange.com/questions/5120/what-if-somebody-removed-my-name-from-mit-license

**Describe the solution you'd like**
Restore the copyright of [Kevin Mårtensson](https://github.com/kevva)

**Describe the drawbacks of your solution**
It takes a moment of your time.

**Describe alternatives you've considered**
Informing Kevin that he can use GitHub's DMCA take-down request process to remove your package from GitHub.

**Comment by zkochan** [comment]
Where is the license changed? The license is the same in the fork: https://github.com/pnpm/npm-conf/blob/main/license

**Comment by adjenks** [comment]
@zkochan Yes, the license is the same, but you removed the copyright notice with his name:

https://github.com/kevva/npm-conf/commit/ed7b6390c3bc1e4f841e066712b4a3da57226597#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15L47

**Comment by zkochan** [comment]
Well, you have posted a link to a stackoverflow question about license change, so how could I know that you mean a change in the readme. I have returned the copyright to the readme. And don't be so aggressive.
