### ISSUE TITLE
PNPX re-downloads/installs every time

### ISSUE THREAD

**Issue by hyoretsu** [pnpm/pnpm#5277]
### Additional information:

I installed PNPM through corepack, but still, it shouldn't do that.

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: WSL2 (Ubuntu 22.04.1)

**Comment by SrBrahma** [comment]
Having a cache would be very nice.

**Comment by hyoretsu** [comment]
It worked normally when I installed it standalone, but it's working like that with Corepack.

**Comment by twiddler** [comment]
From what I understand from [this thread](https://github.com/pnpm/pnpm/discussions/3536), `pnpx` equals `pnpm dlx` and *not* `pnpm exec`. (Searching for "pnpx" in the [documentation](https://pnpm.io/) of v7 yields no results, so I'm just guessing.)

As a aresult, the current behaviour is confusing when one wants to swap out `npm` for `pnpm`.

I think it'd be reasonable to either
- make `pnpx` behave like `npx` (i.e. not download what is already present), or
- remove `pnpx`, or
- have `pnpx foo` print an explanation about `pnpm exec foo`, `pnpm foo` and `pnpm dlx foo`.

**Comment by zkochan** [comment]
We cannot globally install a package for `pnpm dlx` because the whole point of `pnpm dlx` is that it runs with fresh dependencies. But we can have some 5 minutes cache, for instance. So if you run `pnpm dlx` twice on the same package in 5 minutes, it will not redownload it on the second run.

**Comment by stevebeauge** [comment]
> We cannot globally install a package for `pnpm dlx` because the whole point of `pnpm dlx` is that it runs with fresh dependencies. But we can have some 5 minutes cache, for instance. So if you run `pnpm dlx` twice on the same package in 5 minutes, it will not redownload it on the second run.

What about "hashing" the version and dependencies of the target package in order to reuse a previously run of dlx?

it would require some kind of cache cleanup, but everyday use of pnpm dlx is painful (especially on windows)

thx

**Comment by FrederickEngelhardt** [comment]
The cache seems slower than `npx` is that by intent? Also is there a way to disable the output?

Is pnpx doing a lookup for the local node_module binaries installed IE when running `pnpx` with a dependency that matches would it look for the node_modules first?

IE these commands **should** be equivalent if the dependency is specified in a dependency(dev or options) of the package.json and exists within node_modules. 

> Package.json
```json
{
  "devDependencies": { "semantic-release": "^21.0.7" }
}
```
Example commands
`pnpx semantic-release --help`
`node ./node_modules/semantic-release/bin/semantic-release.js --help`

However they are **not** equivalent, one outputs a bunch of metrics on what pnpx is doing from dlx and the other immediately executes the command.

**Comment by airtonix** [comment]
We just got burned by this unexpected behaviour deviation from `npx`. 

We had in our root `package.json` : 

```json
{
  ...
  "engines": {
    "node": "16.17.0",
    "pnpm": "8.6.10"
  },
  "dependencies": {
    ...
    "lint-staged": "^11.0.0",
    ...
  }
}
```

and in our `.husky/pre-commit` : 
```sh
#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# Don't run checks while in the middle of a merge
# https://stackoverflow.com/a/64586174
#
# generally happens when
# - resolving conflicts in a merge
# - rebasing
#
git rev-parse -q --no-revs --verify MERGE_HEAD || {
  bash packages/tools/validate-branch-name/validate.bash
  pnpx lint-staged
}
```

So apparently, ever since I upgraded our monorepo from `pnpm@5.18.9` to `pnpm@8.6.10` 3 mths ago we've been silently **not** using `lint-staged@^11.0.0` and instead using what ever was the latest `lint-staged` that `pnpx` wanted to install...



In this case it wasn't a big problem, but I do now wonder what else is now not behaving as expected.

**Comment by lppedd** [comment]
Is there news on this topic? Was the cache implemented?

**Comment by jedwards1211** [comment]
@zkochan if we `pnpx` a specific version, then shouldn't it reuse a cached version if it exists?  E.g. `pnpx gen-typed-validators@1.0.0 myfile`

I'm trying to slim down my `devDependencies` for infrequently used scripts but still keep those scripts fast to run.

**Comment by zkochan** [comment]
No updates right now. I am too busy with working on pnpm v9 now. Maybe @KSXGitHub could look into it next.

**Comment by KSXGitHub** [comment]
> Actual behavior: PNPM downloads/installs the package to `~/@node_modules/v3/tmp/dlx-38706`, every single times

May I ask why `~/@node_modules`? Did you set any special config?
