### ISSUE TITLE
The peer deps not been install 

### ISSUE THREAD

**Issue by edisonLzy** [pnpm/pnpm#5297]
### Code to reproduce the issue: 
1. clone repo https://github.com/edisonLzy/peer-pnpm
2. pnpm i 
3. the inquirer^8 is the inquirer-autocomplete-prompt peer deps
4. the inquirer^9 is my project deps
### Expected behavior:
1. inquirer should be installed twice. one version is ^8 , another is ^9
### Actual behavior:
1. only inquirer^9 has been install, it cause inquirer-autocomplete-prompt error in runtime.

**Comment by vaibhavkumar-sf** [comment]
Same issue

**Comment by zkochan** [comment]
It is the correct behavior. `inquirer` is in the peer dependencies of `inquirer-autocomplete-prompt`, so it will be resolved from `inquirer` that is found in the parent packages (in your case from the direct dependency).

If you need this for some reason, the only solution is to remove `inquirer` from the peer dependencies using a `.pnpmfile.cjs` hook:

```js
module.exports = {
  hooks: {
    readPackage (pkg) {
      if (pkg.name === 'inquirer-autocomplete-prompt') {
        delete pkg.peerDependencies['inquirer']
      }
      return pkg
    }
  }
}
```
The only way to make it work is to remove inquirer from the peer dependencies

**Comment by edisonLzy** [comment]
> 

thank you very much 👍, it resolve my problem.

**Comment by edisonLzy** [comment]
@zkochan but i have some confuse about pnpm deal with peer deps 😕 . In this case the pkg version is confict, if always resolved from parent, it will cause unexpected error sometimes. so what's consideration of pnpm ? 😃

**Comment by zkochan** [comment]
A peer dependency should be a singleton. So if you have conflicts, you need to change your dependencies to avoid the conflict. Either downgrade (or upgrade) the peer dependency or the dependency that depends on the peer.
