### ISSUE TITLE
Don't fail on `pnpm install` without a package.json

### ISSUE THREAD

**Issue by rstacruz** [pnpm/pnpm#53]
Doing `pnpm install` in a path without package.json shows a cryptic error message and exits with code 1.

```
~ $ cd /tmp
/tmp $ pnpm i

 ! Cannot read property 'dependencies' of undefined
```

For comparison, `npm` is also a little strange in its behavior in this case, but it at least exits successfully:

``` sh
/tmp $ npm i
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

# node_modules will be enumerated here, if it exists
```

Related #47.

**Comment by zkochan** [comment]
Currently pnpm does have a meaningful error message in this situation. It says: `ERROR No package.json found`

**Comment by jsumners** [comment]
I routinely do an `npm install foo` in an empty directory to try out a package. This is functionality I expect to work in any package manager.
