### ISSUE TITLE
local-resolver does not handle version based workspace protocol

### ISSUE THREAD

**Issue by AGrzes** [pnpm/pnpm#5305]
### Code to reproduce the issue: 
```typescript
const resolveResult = await resolveFromLocal({ pref: 'workspace:1.0.0',alias:'foo',raw:'foo@workspace:1.0.0' }, { projectDir: __dirname })
```
### Expected behavior: 
References in form `workspace:<version>` are resolved to correct path or at least does not cause an error.

### Actual behavior: 
References in form `workspace:<version>` fail when resolver looks for a folder named after the version

### Additional information:

 - `node -v` prints: v14.20.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
`local-resolver` doesn't handle workspace dependencies. `npm-resolver` does.

**Comment by AGrzes** [comment]
There is code and tests for `workspace:` protocol so I assumed it should work. Sorry for distraction.
