### ISSUE TITLE
Hooks provided in opts are lost in processing by install command

### ISSUE THREAD

**Issue by AGrzes** [pnpm/pnpm#5306]
I was trying to get `pnpm deploy` (beta) feature to work and correctly "inject" my workspace modules and I noticed that they are not injected due to `readPackage` hook not being applied.

Here 

https://github.com/pnpm/pnpm/blob/b6f788cffc967ff75b133e757c4ffb453cace470/packages/pnpmfile/src/requireHooks.ts#L55

empty object is returned if neither globalHooks nor hooks are set.
Simple change to
```ts
if (!globalHooks && !hooks) return opts.hooks || {}
```
Would prevent hooks set in opts from being lost.

f the change would be acceptable I will provide PR with tests.

### pnpm version:
7.9.5

### Code to reproduce the issue:
I can provide it if the description is not enough.

### Expected behavior:
When hooks are provided in opts they are returned from `requireHooks` function
### Actual behavior:
Hooks provided in opts are lost.

### Additional information:

 - `node -v` prints: v14.20.0
 - Windows, macOS, or Linux?: Linux

**Comment by AGrzes** [comment]
Actually after working on PR I found out that the hooks provided in opts are not only ignored if there ar no local/ global hooks - they are always ignored. My PR addresses this issue and I would be grateful for some feedback - as I confirmed that changed version resolves my issue with workspace package not being "injected" when using `deploy` command.

**Comment by zkochan** [comment]
I think we should do some refactoring. Probably `@pnpm/pnpmfile` should not merge the hooks and just return an array of hooks. Then the deploy command would just append a new hooks object to the array. Then later before usage (maybe in `@pnpm/core`) the hooks can be piped together. This part is already partially implemented: 

https://github.com/pnpm/pnpm/blob/f3fc6b540a55776b8ecbd8dcab29e7839c9a6cad/packages/core/src/install/index.ts#L614-L621

**Comment by AGrzes** [comment]
I will look into this - if I understand You correctly you suggest that
* `@pnpm/pnpmfile` would return array of hooks for hooks that can be "merged" later
* the array is passed correctly to createReadPackageHook
* hook from options is also passed in and handled by createReadPackageHook
Am I right?

**Comment by zkochan** [comment]
Sounds correct.

**Comment by AGrzes** [comment]
What I found out the issue happens only with option `shared-workspace-lockfile = false` - with shared workspace lock the hook is handled correctly.

**Comment by AGrzes** [comment]
The line 
https://github.com/pnpm/pnpm/blob/f3fc6b540a55776b8ecbd8dcab29e7839c9a6cad/packages/plugin-commands-installation/src/recursive.ts#L292
coupled with
https://github.com/pnpm/pnpm/blob/f3fc6b540a55776b8ecbd8dcab29e7839c9a6cad/packages/plugin-commands-installation/src/recursive.ts#L354
Causes hooks  from opts to be discarded in favor of pnpmfile generated hooks.

**Comment by AGrzes** [comment]
@zkochan one question - I found out that `config` module also uses `requireHooks` 
https://github.com/pnpm/pnpm/blob/f3fc6b540a55776b8ecbd8dcab29e7839c9a6cad/packages/config/src/index.ts#L525
And it is very hard for me to trace places where change in type (to array) could have ripple effects - so I'm worried about changing type of `readPackage` hook to array in between `requireHooks` and `createReadPackageHook` because I'm not sure the flow will always lead to the later.

**Comment by zkochan** [comment]
You will get typing errors, just run `pnpm -w compile` and you'll be able to find all places that need to be changed.
