### ISSUE TITLE
Latest version for downloading and installing pnpm CI is 6.16

### ISSUE THREAD

**Issue by anogr** [pnpm/pnpm#5313]
In your documentation for installing pnpm in CI environments, you use pnpm version 6.16 only. It appears that all newer versions are missing.

https://pnpm.io/continuous-integration

### Expected behavior:

I expect https://get.pnpm.io/v7.11.js to download pnpm 7.11.

### Actual behavior:

It is a 404.

**Comment by zkochan** [comment]
It is not how it works. If you want to install v7.11, use:

```
curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.11
```

**Comment by anogr** [comment]
Thank you for your help!
