### ISSUE TITLE
pnpm update will replace `workspace:*` dependencies and similar syntax with exact versions

### ISSUE THREAD

**Issue by segevfiner** [pnpm/pnpm#5317]
### Code to reproduce the issue:
1. Create a pnpm workspace with one package that depends on another using an coarse syntax like `workspace:*`.
2. Run `pnpm update`

### Expected behavior:
The `workspace:*` is kept intact. By using it I mean to just use the current version from the monorepo but hardcode the version on publish. I don't want to hardcode the version in the Git repo in all packages that depend on it.

### Actual behavior:
It get's replaced with the current version of the depended on package from the monorepo, e.g. `workspace:1.0.1`.

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by ntnyq** [comment]
Duplicated with https://github.com/pnpm/pnpm/issues/5312

**Comment by shirotech** [comment]
Seems many people have reported similar issue, @zkochan would you have some time to have a look? Would be greatly appreciated, thank you.

**Comment by ntnyq** [comment]
For now, I use [taze](https://github.com/antfu/taze) to keep my deps fresh.
Maybe you can have a try.

**Comment by zkochan** [comment]
It is a bug.

As a workaround, use `pnpm update -i` or `pnpm update --interactive`
