### ISSUE TITLE
Refactor `pnpm patch` and `patch-commit`

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#5330]
We need to refactor both the patch and patch-commit commands. Right now, the patch command writes two directories, one is for editing the other one for comparison. What we need instead is a patch command that writes only one directory for editing. @pleunv I guess in your case you won't run the patch command at all as you will probably edit the package directly inside node_modules.

The patch-commit command instead of just comparing the two preexisting directories will first fetch the original sources of the patched package (which currently is handled by the patch command) and then compare it to the `edit-dir`.

**Comment by pleunv** [comment]
Yeah, I think that makes sense.
I am wondering though if the existence of any previous patches should be surfaced when a user attempts to patch a dependency that has already been patched before. Perhaps a hint that they can edit the source and instead use `pnpm patch-commit /node_modules/<pkg>` to do an incremental patch, when they run `pnpm patch <pkg>`.

**Comment by zkochan** [comment]
I think this is an edge case. And it will be visible anyway because the patch file will be updated. So on git commit they will see what happened.
