### ISSUE TITLE
pnpm i --prod fails to ignore devDependencies pkgs (regression)

### ISSUE THREAD

**Issue by mustafa0x** [pnpm/pnpm#5335]
### pnpm version:
7.9.5

### Code to reproduce the issue:
```json
{
  "dependencies": {
    "better-sqlite3": "^7.6.2"
  },
  "devDependencies": {
    "package": "github:mustafa0x/package#v1"
  }
}
```

### Expected behavior:
`pnpm i --prod` doesn't attempt to access `github:mustafa0x/package`

### Actual behavior:
It does try to access it, causing install to fail, since the repo is private. Removing the pkg from `devDependencies` causes the install to succeed.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1473102/189511827-ede37ced-c5e9-4312-a5f0-344dca14adaa.png">

### Additional information:

 - `node -v` prints: v16.14.2
 - Windows, macOS, or Linux?: Linux

This was working recently, so not sure what changed.

**Comment by zkochan** [comment]
Do you have an up-to-date lockfile? `pnpm install` still resolves dev dependencies to create a lockfile. Then it doesn't install them to node_modules if `--prod` is used. But if the lockfile is not present or is not up-to-date, it may fail on resolution of dev deps.

**Comment by mustafa0x** [comment]
Ok, seems like that was it, thanks!
