### ISSUE TITLE
Public hoisting inside of individual workspace packages

### ISSUE THREAD

**Issue by evelant** [pnpm/pnpm#5341]
**Describe the user story**

It would be nice to support `public-hoist-pattern` inside of workspace packages rather than only at the root node_modules. This would give an easy way to resolve issues with packages like react-native that contain lots of hardcoded paths relying on sub-dependencies being present in node_modules. 

Currently when building expo/react-native with pnpm (and `@rnx-kit/metro-resolver-symlinks` so symlinks work) the native builds for iOS/Android tend to fail due to vaerious pacakges assuming that their dependencies are available in the node_modules of the project. They hardcode paths to Podspecs and the like as `../../node_modules/depedency-package/dep-package.podspec`.

**Describe the solution you'd like**

When .npmrc in a workspace packages contains `public-hoist-pattern` then symlink relevant pacakges into that project's node_modules. 

**Describe the drawbacks of your solution**

I don't know if this would cause problems, seems it was suggested before and closed as not posible but I'm not sure why https://github.com/pnpm/pnpm/issues/2849

**Describe alternatives you've considered**

The only alternative I know of is to hoist these deps to root node_modules publically then patch each package to point to root node_modules instead of the react-native project's node_modules.

**Comment by zkochan** [comment]
It is not possible. I mean, you can implement this but it won't do anything. Those hoisted deps will be ignored by Node.js. Node.js is only looking for dependencies in parent directories. pnpm puts all dependencies into `<workspace root>/node_modules/.pnpm`, so a dependency of projectA will be inside that root folder and it won't search for hoisted dependencies inside projectA/node_modules.

**Comment by evelant** [comment]
Gotcha, thanks for the explanation. I patched the badly behaving react-native packages and it works well enough.
