### ISSUE TITLE
Docs: Corepack has a much better way of installing PNPM

### ISSUE THREAD

**Issue by Bananaman** [pnpm/pnpm#5344]
I was reading your installation instructions at https://pnpm.io/installation, and saw the following:

> This will automatically install pnpm on your system. However, it probably won't be the latest version of pnpm. To upgrade it, check what is the [latest pnpm version](https://github.com/pnpm/pnpm/releases/latest) and run:
> 
> `corepack prepare pnpm@<version> --activate`

Well, I just have to let you know that there's a new Corepack feature which was merged on July 8th: https://github.com/nodejs/corepack/pull/136

You can now do:

```
corepack prepare pnpm@latest --activate
```

Obviously requires a new-enough version of Corepack, but I think this should be the default instruction, and then the `@specific version` can be a fallback instruction. :+1:

**Comment by mrienstra** [comment]
On a related note, I came here to see if docs should say:

```
corepack prepare pnpm@stable --activate
```

... Which yarn recently added (and then removed) from their docs (https://github.com/yarnpkg/berry/pull/4815).

The reason it was removed:
>Note that this doesn't work in [corepack@<0.12.0](https://github.com/nodejs/corepack/releases/tag/v0.12.0)

Just tried `corepack prepare pnpm@stable --activate` and got:

```
Usage Error: Tag not found (stable)
```

... I guess `stable` tag isn't being used. But yeah, `latest` works.

**Comment by mrienstra** [comment]
Corepack v0.12.0 corresponds with Node [v16.17.0](https://github.com/nodejs/node/releases/tag/v16.17.0). Node v16.17.0 has Corepack v0.12.1 actually, but it's the oldest release with Corepack >= v0.12.0.

**Comment by Bananaman** [comment]
@mrienstra I am using `sudo n latest` to manually install the latest Node, and it automatically installs the associated version of corepack, so that's cool. More people should use tools such as `n` to manage their Node versions.

Note that there is a way to tell `n` to not downgrade npm, corepack etc even when you use `n` to downgrade your active Node version:

https://github.com/tj/n/blob/ab5f98146031c596bcb8f545ade0345624023809/README.md#preserving-npm

**Comment by zkochan** [comment]
Thanks, updates the docs.

**Comment by Pentadome** [comment]
It didnt work. I had to run `corepack use pnpm@latest`  as well

**Comment by etherealite** [comment]
I was brought here by the update notification from the CLI. The update notification still give instructions to run `corepack install -g pnpm@9.7.0` to update.
```
   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 9.6.0 → 9.7.0.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v9.7.0   │
   │         Run "corepack install -g pnpm@9.7.0" to update.         │
   │                                                                 │
   │        Follow @pnpmjs for updates: https://x.com/pnpmjs         │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯
   ```
   
 Not sure about others but `"corepack install -g pnpm@X.X.X` doesn't work for me so I think this message should be changed to something that works and matches better with what is in the docs.

**Comment by nikita-sisutech** [comment]
The correct command I found is `corepack up`

**Comment by aellerton** [comment]
Very useful, thank you!

**Comment by bilalq** [comment]
@zkochan 

Rather than silently skipping parts of the build, wouldn't it be better to instead fail install completely? Then users would be forced to explicitly mark packages as either built or not built. That would be yet another breaking change, but would you consider making a config option for that?

As it stands, silently breaking things that only error out sometimes at runtime leads to many latent problems.
