### ISSUE TITLE
Always auto install peer dependencies that are dependencies in the root of the workspace

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#5349]

**Comment by shawnmcknight** [comment]
@zkochan Is this still an open issue with the release of the [resolve-peers-from-workspace-root](https://pnpm.io/npmrc#resolve-peers-from-workspace-root) setting?  I'm guessing that with the introduction of a setting that this behavior is going to be opt-in and that this issue could be closed.

Thanks!
