### ISSUE TITLE
What to do when a package uses a package that is neither in dependencies nor in peerDependencies

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#535]
The issue is described also [here](https://github.com/blakeembrey/popsicle-retry/issues/13). popsicle-retry uses popsicle which is neither in dependencies nor in peerDependencies. The author of the package thinks that this is a good solution, quote:

> ...There's no need to rely on a flat structure or nested structure, this module works fine with all NPM versions. I think there's an issue in pnpm, in that it's not setting up the node_modules correctly. Node module resolution would allow you to automatically resolve dependencies recursively up the tree when it's not found, and since this module can only ever be used with popsicle, I don't see the issue (it'll look in the current node_modules and then up again and find it).

### Code to reproduce the issue:

```
git clone git@github.com:ReactiveX/rxjs.git
cd rxjs
pnpm i
```

### Expected behavior:

Error on prepublish

### Actual behavior:

No errors

### Additional information:

 - `node -v` prints: 6
 - Windows, OS X, or Linux?: linux

**Comment by andreypopp** [comment]
Solely my opinion: packages should specify in dependencies (dependencies or peerDependencies) what they use in code. But we need to see if the case popsicle-retry is repeating across the ecosystem.

**Comment by iamstarkov** [comment]
wtf is popsicle, and why its relying on unchecked deps

**Comment by iamstarkov** [comment]
its broken contract of shared dependency environment (everything you need is specified in pkg).

its bad as hell, and we shouldnt allow it, and tbh, if dep didnt specify its own deps, we have no way around this problem

**Comment by iamstarkov** [comment]
except for flat dep tree

**Comment by zkochan** [comment]
I don't think we'll be able to make it work in pnpm.

Also the correct solution would be to include the dependency in `peerDependencies`

**Comment by andreineculau** [comment]
running into the same issue.. popsicle-retry part of typings-core part of typings i.e. not being able to solve this one way or another means pnpm will not be used by anyone running typescript

i read the popsicle-retry issue and it's unclear to me if the author wants a a PR for adding 3 lines, or he's settled on not adding it as a peer dep. *regardless* did anyone consider having pnpm host a list of "fixes" for rebel packages? or to start small, provide an API to tell pnpm "call me when you parse a package.json and maybe i'll return a fixed one" which would at least allow me, pnpm user, to carry the burden of handling the rebel packages

**Comment by zkochan** [comment]
If we implement #651 and #837 then we'll probably be able to just substitute some dependency in the dependency tree. Which should be fine, I guess. We'll be able to publish a fixed version of `popsicle-retry` that will be used instead of the original one by pnpm. I don't think we have anything about "fixing package.json's" currently.

These kinds of "hacks" should be well thought through because people might decide pnpm is doing malicious things in their dependencies.

**Comment by andreineculau** [comment]
that opens up another problem, or burden to be exact.

You have just forked popsicle-retry, made the peerDependencies fix, you will tell pnpm to use that via lockedDependencies. Meanwhile, popsicle-retry will get upgrades which you will miss out on, up to the point where typings-core want the next minor version, with some added functionality, and then pnpm will fail again, you will have to merge in the upstream, push, publish, etc.

That is the reason why I plead for having a callback mechanism. Simpler, safer and more fun.

**Comment by zkochan** [comment]
Maybe. `lockDependencies` seems to be a useful feature overall, so lets' see how it will work out.

I hope pnpm will eventually become more popular and people/projects won't say "no" to us. So we won't need the hacks.

**Comment by andreineculau** [comment]
I'll take pragmatism over hope anytime.
