### ISSUE TITLE
Using esbuild on a arm64 (M1 mac) seems to cause issue

### ISSUE THREAD

**Issue by ScreamZ** [pnpm/pnpm#5350]
### Code to reproduce the issue:
See https://github.com/vercel/turborepo/issues/1769

https://github.com/ScreamZ/bug-turborepo-pnpm-esbuild on branch main run `pnpm install` then `pnpm dev` on M1 mac.

Also using https://volta.sh/ to manage my nodeJS version
"volta": {
"node": "14.19.0"
},

### Actual behavior:
Not working with my M1 mac (arm64) with esbuild

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by ScreamZ** [comment]
@zkochan Added some repro example, seems really strange, turbo reported this is a pnpm issue

**Comment by seanwatters** [comment]
@ScreamZ, I'm able to clone, install and run `pnpm dev` on my M1 MacBook Pro with the `arm64` build. 

Based on the `the "esbuild-darwin-arm64" package is present but this platform
needs the "esbuild-darwin-64" package instead`, I'm guessing that your terminal is running under Rosetta, and so it's asking you to install the non-arm target. 

To check whether you're on Rosetta, you can run `sysctl -n sysctl.proc_translated`: if you get a `1` you're under Rosetta, if you get a `0` you're running natively.

If you don't need to run under Rosetta, you can always just change back to native. If you do need to run under Rosetta, then a quick (but maybe less than ideal fix) is just to install the specific target explicitly `pnpm add -D @esbuild/darwin-x64` (I believe it's giving you `@esbuild/darwin-arm64` right now) to get it working.

**Comment by haryelramalho** [comment]
@ScreamZ I have the same issue that you. But, I'm trying to execute and the error still there. Did you updated something in that code?

**Comment by seanwatters** [comment]
> I'm not under rosetta, seems like it works now, i guess pnpm fixed the issue recently,

@ScreamZ, it may be worth closing https://github.com/vercel/turbo/issues/1769 out as well if the issue no longer persists.

**Comment by seanwatters** [comment]
@haryelramalho, if you run `node -p "process.arch"` you should be able to see whether you have the x86 or arm64 node.js installed. if you have a version other than arm64, that might be your problem.

**Comment by haryelramalho** [comment]
@seanwatters hmm.. I got it. But, I'm trying to run the service into docker container... the error appeared suddenly from yesterday to today. I'm using the node:18.13 image.

**Comment by hsycc** [comment]
> @ScreamZ, I'm able to clone, install and run `pnpm dev` on my M1 MacBook Pro with the `arm64` build.
> 
> Based on the `the "esbuild-darwin-arm64" package is present but this platform needs the "esbuild-darwin-64" package instead`, I'm guessing that your terminal is running under Rosetta, and so it's asking you to install the non-arm target.
> 
> To check whether you're on Rosetta, you can run `sysctl -n sysctl.proc_translated`: if you get a `1` you're under Rosetta, if you get a `0` you're running natively.
> 
> If you don't need to run under Rosetta, you can always just change back to native. If you do need to run under Rosetta, then a quick (but maybe less than ideal fix) is just to install the specific target explicitly `pnpm add -D @esbuild/darwin-x64` (I believe it's giving you `@esbuild/darwin-arm64` right now) to get it working.

 node v18.16.1
 pnpm 8.6.1
process.arch arm64
The problem remains.
When I switch to yarn, it's ok.
@seanwatters
