### ISSUE TITLE
Typescript types constructed through transitive dependencies are not resolved

### ISSUE THREAD

**Issue by shawnmcknight** [pnpm/pnpm#5355]
In my testing, I'm finding that any package dependency which exports types which are constructed from a transitive dependency of that package are not accessible via Typescript.  That is if the project has a dependency `A` which has a transitive dependency `B` and `A` exports a type which is composed from types exported from `B` or re-exports types from `B` then the types will not be accessible and Typescript will emit errors.  This seems to occur because Typescript is unable to resolve the types from the transitive dependency through pnpm's symlinks.

#4920 seems to share common symptoms with the issue I am reporting.  In fact, as reported in that issue, `@testing-library` was the source of some of the errors I was encountering.

I was able to get around this by setting every transitive dependency used in this way as hoisted by adding `public-hoist-pattern[]=` references in my `.npmrc` file.  For one of my team's smaller frontend projects I had to set 8 different transitive dependencies as hoisted.  This _feels_ like something that shouldn't have to be done, but perhaps this is the correct approach.

I'm unsure if I am simply doing something wrong, if this is expected behavior and the proper solution is to ensure these transitive dependencies are hoisted, if there is an issue with pnpm, or if this is ultimately an issue with Typescript.  I feel like microsoft/Typescript#48212 may be symptoms of the same problems, but I am not confident in that.

### Expected behavior:
Typescript does not emit errors when a direct dependency exports types that are constructed via a transitive dependency.

### Actual behavior:
`tsc --noEmit` is emitting errors such as:

```
error TS2339: Property 'subscribe' does not exist on type 'ObservableQuery<any, OperationVariables>'.
```
and
```
error TS7006: Parameter 'data' implicitly has an 'any' type.
```
After hoisting the transitive dependencies the errors are no longer emitted.

### Additional information:

 - `node -v` prints: 16.16.0
 - Windows, macOS, or Linux?: Windows

**Comment by shawnmcknight** [comment]
Nevermind.  This problem was specific to my paths configuration in tsconfig.

**Comment by arahatashun** [comment]
@shawnmcknight I am running into a similar problem. Can you tell me more about how you solved the problem?

**Comment by shawnmcknight** [comment]
My recollection is that I had path mappings in order to allow dependency types to be overridden. There was a final path of `*` which was an array of my type overrides folder and `node_modules`.

Initially I fixed this by making a specific mapping for everything I was overriding in the paths. Now I just use pnpm's patch feature to update the types.

**Comment by vincent-tock** [comment]
thanks @shawnmcknight for your comment, totally forgot to look at tsconfig file ! 


@arahatashun I _think_ I had the same issue, it fixed my hundreds of ts errors by changing the paths in tsconfig.json, now that my :

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "paths": {
      "react-router": ["../node_modules/@types/react-router"], // was "./node_modules/@types/react-router"
      "core/dist/*": ["../server/dist/*"],
      "*": ["src/js/*", "../node_modules/*", "../node_modules/@types/*"] /
    },
  },
```

and have a .npmrc that hoist some packages like:

```
ignore-scripts=true
node-linker=hoisted

public-hoist-pattern[]=*types*
public-hoist-pattern[]=*@types*
public-hoist-pattern[]=*@storybook*
public-hoist-pattern[]=*@apollo/client*
public-hoist-pattern[]=*@emotion*
public-hoist-pattern[]=*@babel*
public-hoist-pattern[]=*babel-*
public-hoist-pattern[]=*eslint-plugin-*
```

**Comment by SonNg2k** [comment]
I finally found a fix.

In my case, my current package depends on the installed dependency `@amest/dictionaries`, which exports a type constructed from the transitive dependency `@amest/types` (which is _not_ installed in my current package). So I get the error: `TS2742: The inferred type from @amest/dictionaries cannot be named without a reference to ../../../../dictionaries/node_modules/@amest/types/src/index.js. This is likely not portable. A type annotation is necessary.`

U just need to setup the paths correctly in the shareable _tsconfig.base.json_. See [this example](https://github.com/mui/material-ui/blob/next/tsconfig.json#L16).
