### ISSUE TITLE
Support an ignore / reject option for the `pnpm update` and `pnpm outdated` commands

### ISSUE THREAD

**Issue by nicholas-ochoa** [pnpm/pnpm#5358]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

The `pnpm update` and `pnpm outdated` commands are very useful and I would love to replace my current usage of the `npm-check-updates` package with these. One limitation I'm facing is that I currently have a few packages "blacklisted" when `npm-check-updates` does a check for updates across all workspace packages recursively. This is accomplished by adding the package name to the `.ncurc.yaml` file under the `rejects` config option either in the project root, or within a package directory. 

If possible, I would love if this could be replicated within `pnpm` - perhaps by adding a new `pnpm.update.ignore` property to the `package.json` of the project root and/or package directories. 

Something like this which would ignore all updates for the package `commander`, and would not attempt to update `chalk` version `4.x.x` either - but if a package uses `chalk` 5.x.x that may be updated.

```json

  "pnpm": {
    "update": {
      "ignore": {
        "commander": "*",
        "chalk": "4.x.x"
      }
    }
  }
```

**Describe the drawbacks of your solution**

I can't think of any drawbacks aside from the obvious "adding more complexity to the `package.json` file".

**Describe alternatives you've considered**

I can continue using `npm-check-updates` to accomplish this, but it would be great to extend the `pnpm` functionality to eliminate another package.

**Comment by zkochan** [comment]
Good idea.

**Comment by Shinyaigeek** [comment]
Hi, I am loving this feature. Can I work on implementing this?

**Comment by nicholas-ochoa** [comment]
@zkochan @Shinyaigeek thank you both for working on this and getting it implemented! I noticed an issue where it does not seem to work when run recursively `pnpm outdated -r` - should I open a new issue to discuss / review?

**Comment by zkochan** [comment]
> Is it possible to restrict the ignore to just a single package or multiple packages in the workspace, or does it always need to apply to the entire workspace?

No, it is not possible. I guess it could be implemented but for me it is not high priority.
