### ISSUE TITLE
pnpm update not updating global packages

### ISSUE THREAD

**Issue by andrei-zgirvaci** [pnpm/pnpm#5365]
### Code to reproduce the issue:

1. Run: `pnpm -g outdated`
2. Run:`pnpm -g update --latest` 

### Expected behavior:

`package.json`, `pnpm-lock.yaml` and all the outdated packages are updated; Running `pnpm -g outdated` again not showing any packages.

### Actual behavior:

`package.json`, `pnpm-lock.yaml` and all the outdated packages are not updated; Running `pnpm -g outdated` again shows the same output as before running `pnpm -g update --latest` .

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by DBvc** [comment]
Are you install global pkg with a fixed version?

```
pnpm add xxx@x.y.z -g
```
then
```
pnpm update -g xxx --latest
```

won't update this pkg


```
pnpm add xxx@^x.y.x -g
```

then
```
pnpm update -g xxx  --lates
```
will update this pkg

**Comment by Wxh16144** [comment]
I'm experiencing the same confusion, I don't know how I installed the global dependencies in the first place.

`pnpm add xxx@x.y.x -g` or `pnpm add xxx@^x.y.x -g` I have forgotten about it, how should I check it?

**Comment by tjx666** [comment]
Any progress here? I think this is a serious bug. 

- I install the pnpm using corepack.
- pnpm version: 7.14.2
- node version: v18.12.1
- OS: MacOS ventura 13.0

**Comment by tjx666** [comment]
@zkochan This may be fixed in high preority

**Comment by evanlouie** [comment]
Just ran into this and for anyone just wanting to be able to update everything to latest in one line:

`pnpm list -g --json | jq '.[] | .dependencies | keys | .[]' -r  | xargs pnpm add -g`

**Comment by thepreacher** [comment]
@evanlouie Thanks for this. It there a way to silence or better yet print a message like 'No global packges installed' when there are no pnpm global packages installed. At the moment it displays `jq: error (at <stdin>:6): null (null) has no keys`

**Comment by mkismy** [comment]
Having the same issue with `pnpm update -g`. 
Adding individual packages shown in `pnpm outdated -g` does work.

Probably same issue for #3779?

**Comment by mitjans** [comment]
Any updates on this? I'm having the same problem where `pnpm update -g -L -i` keeps suggesting the same updates, even after applying them

**Comment by zkochan** [comment]
Fixed via: https://github.com/pnpm/pnpm/pull/6671
