### ISSUE TITLE
pnpm installs incorrect peer dependency version with no warning

### ISSUE THREAD

**Issue by andershessellund** [pnpm/pnpm#5373]
### pnpm version:
7.12.0

### Code to reproduce the issue:
I have a project with the following package.json:

```json
{
  "peerDependencies": {
    "@angular/core": "13.3.6",
    "rxjs": "6.6.7"
  }
}
```
I add `auto-install-peers=true` to .npmrc.

@angular/core has a peer dependency on rxjs: `"rxjs": "^6.5.3 || ^7.4.0"`

Thus, the rxjs version specified in my package.json is compatible with the version specified by @angular/core.

### Expected behavior:
I would expect to get the dependencies I specified. If this is not possible for some reason I cannot quite understand, I would expect to get a warning that pnpm was unable to resolve my dependencies.

### Actual behavior:
I get rxjs version `7.5.6` . I do not get any warning that the installed dependency does not the version i specified.

### Additional information:
Node v18.8.0 , running on Mac.

**Comment by zkochan** [comment]
Looks like a regression in v7.12
