### ISSUE TITLE
pnpm 7.12.1 does not generate lockfiles

### ISSUE THREAD

**Issue by runspired** [pnpm/pnpm#5390]
This is likely related to #5389 and potentially the root cause

In an existing project using workspaces and pnpm, after upgrading from pnpm 7.5, I tried regenerating the lockfile by deleting the existing lockfile and running `pnpm install`. All of the following failed to result in a lockfile being generated

- `pnpm install`
- `pnpm install --force`
- `pnpm install ---no-frozen-lockfile=true`
- `pnpm install --fix-lockfile `

**Comment by runspired** [comment]
Downgrading to 7.11.0 and lockfiles are generated by that version (was originally updating from 7.5)

**Comment by mcmxcdev** [comment]
For me I realized that `pnpm upgrade --interactive --latest -r` stopped working properly. The new packages are downloaded but both `package.json` and the lockfile are newer updated.

I also downgraded to 7.11.0 for now, something is seriously broken at the moment.

**Comment by edaojs** [comment]
the command `pnpm add` is broken too....  it downloads the packages, but doesn't install at all
downgraded to 7.11.0 and works fine.

**Comment by DeverStyle** [comment]
Same here, nothing worked on 7.12.1 (install, upgrade, lock file generation). Installing 7.11.0 worked

**Comment by jianliao** [comment]
Same here, after removing a package, nothing(install, upgrade, node_modules folder generation) works anymore.

**Comment by mcmxcdev** [comment]
@zkochan critical bug

**Comment by zkochan** [comment]
I don't see steps to reproduce here. I assume it is the same issue as this one: https://github.com/pnpm/pnpm/issues/5372#issuecomment-1253967126

**Comment by runspired** [comment]
@zkochan thats because the step is literally just “run install”.

**Comment by zkochan** [comment]
Yes, but we have lots of tests for installation. It is an issue specific to your set of dependencies. That is why it is important to create sample repo that reproduces the issue.

Do you use `auto-install-peers=true`?

**Comment by marozzocom** [comment]
I'm experiencing this issue, and have

```
auto-install-peers=true
strict-peer-dependencies=false
```

**Comment by zkochan** [comment]
fixed in v7.12.2

**Comment by runspired** [comment]
Thanks, will test!

**Comment by marozzocom** [comment]
7.12.2 fixes the issue at least in my environment. Thanks!

**Comment by matteobruni** [comment]
> fixed in v7.12.2

I had a similar problem, but 7.12.2 is still bugged. Do you want me to open a new issue with more details?

**Comment by runspired** [comment]
@zkochan can confirm 7.12.2 fixed the issue for me as well
