### ISSUE TITLE
`pnpm add -g @pnpm/exe` got an unexpected version

### ISSUE THREAD

**Issue by ntnyq** [pnpm/pnpm#5395]
### Code to reproduce the issue:

`pnpm add -g @pnpm/exe`

### Expected behavior:

pnpm updated to the newest version `7.12.2` 

### Actual behavior:

Got version `7.11.0`

### Additional information:

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by ntnyq** [comment]
`curl -fsSL https://get.pnpm.io/install.sh | sh -` installed  version `7.11.0` too.

**Comment by lvqq** [comment]
Well, it's because `@pnpm/exe` 's latest tag is in version `7.11.0`, cc @zkochan 

![image](https://user-images.githubusercontent.com/29809148/191881647-29c8f1fc-56c9-4e76-a5ed-d3916a8ecc60.png)

**Comment by zkochan** [comment]
I reverted latest to v7.11 because there was a regression
but now it should be fine and use 7.12.2

**Comment by zkochan** [comment]
It is still 7.11 though I have updated the tag several times. Maybe some npm registry cache or bug.

**Comment by zkochan** [comment]
Use `pnpm add -g @pnpm/exe@next-7` for now

**Comment by zkochan** [comment]
ok, fixed by running 

```
pnpm dist-tag add @pnpm/exe@7.12.1 latest
pnpm dist-tag add @pnpm/exe@7.12.2 latest
```

**Comment by lvqq** [comment]
Works fine for me
