### ISSUE TITLE
Filed tarball publishing returns a non-zero exit code

### ISSUE THREAD

**Issue by soundstep** [pnpm/pnpm#5396]
Publishing a tarball (not a package) that has been created with `pnpm pack` to a private repositiry with failed credentials should return a non-zero exit code, it currently returns a 0 exit code.

### pnpm version:

7.12.1

### Code to reproduce the issue:

Publish to any repo with failed credentials (or any publishing failure):

```sh
pnpm publish my-package-11.0.0.tgz --no-git-checks --registry "http://my-private-repo.com"
```

The expected error:

```
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
```

The Issue ()this should be a non-zero exit code:

```sh
echo $?
```

### Expected behavior:

Get a non-zero exit code from a failed tarball publishing.

### Actual behavior:

Get a zero exit code from a failed tarball publishing.

### Additional information:

 - `node -v` prints:

```sh
v14.20.0
```

 - Windows, macOS, or Linux?:

```sh
MacOS Monterey (12.1)
```

**Comment by soundstep** [comment]
cc @jjoynson-iw

**Comment by ongshane** [comment]
Bump - we are also seeing this causing automation pipelines to fail silently.
