### ISSUE TITLE
Unable to update pnpm using Windows Powershell script

### ISSUE THREAD

**Issue by sabreu-teknorix** [pnpm/pnpm#5399]
unable to upgrade pnpm from 7.11.0 to 7.12.2

### pnpm version:
7.11.0

### Code to reproduce the issue:
run `iwr https://get.pnpm.io/install.ps1 -useb | iex` in powershell

### Expected behavior:
pnpm should upgrade to 7.12.2

### Actual behavior:
script downloads 7.11.0 version
![image](https://user-images.githubusercontent.com/88586940/191915014-e21a8092-6e4f-4543-9a6e-f66c809ced82.png)

### Additional information:

 - `node -v` prints: v14.20.0
 - Windows, macOS, or Linux?: Windows

**Comment by lvqq** [comment]
It has been fixed, u can have a retry.
