### ISSUE TITLE
pnpm install --production

### ISSUE THREAD

**Issue by rstacruz** [pnpm/pnpm#54]
From `npm help install`:

> With the `--production` flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.

**Comment by davej** [comment]
Working on this.

**Comment by etamponi** [comment]
Running:

```
NODE_ENV=production pnpm install
```

has no effect, `devDependencies` are installed anyway.

**Comment by zkochan** [comment]
you probably mean that the tarballs are downloaded anyway. If there is no `shrinkwrap.yaml` file then it will happen because to create the `shrinkwrap.yaml` file the real manifests are needed from inside the tarballs.

**Comment by zkochan** [comment]
sorry. Reproducible
