### ISSUE TITLE
cafile and strict-ssl are ignored

### ISSUE THREAD

**Issue by petit-blaireau** [pnpm/pnpm#5400]
I am behind a corporate mitm proxy (Zscaler). The proxy is setup in my .npmrc :
```
proxy=http://<the proxy ip>:80
```
While npm successfully reaches the package registry if I add any of those two lines to the .npmrc
- `strict-ssl=false` to ignore CA validation
- `cafile=<path-to-my-cert>.pem` to have it use the corporate CA

...pnpm does not.

### pnpm version:
7.12.2
### Code to reproduce the issue:

`pnpm add typescript`

### Expected behavior:

The package gets installed.

### Actual behavior:

The certificate cannot be validated, and the connection fails.
`WARN  GET https://registry.npmjs.org/typescript error (UNABLE_TO_GET_ISSUER_CERT_LOCALLY). Will retry in 10 seconds. 2 retries left.`

The error is the same when setting `strict-ssl=false` or `cafile=<path-to-my-cert>.pem`.

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: Windows

**Comment by weitblicken** [comment]
I have the same problem with a corporate artifacttory using a self signed certificate chain.
ca[] instead of cafile also not working.
pnmp v6.35.0

**Comment by Mettbrot** [comment]
Same problem here. Commandline options also dont work.

**Comment by bogh** [comment]
In my case the `cafile` is replacing the default Certificate Authority.
Add `strict-ssl=false` works for me. But I would like to have the functionality offered for `NODE_CA_EXTRA_CERTS` which adds the `CA` and not replacing it.

**Comment by Mettbrot** [comment]
Which version did you try? I could not get it to work with v7.18.2 but the release cycle on this thing is crazy 😃

**Comment by zkochan** [comment]
This should work with 7.27.1

Fixed via this PR: https://github.com/pnpm/components/pull/8
