### ISSUE TITLE
pnpm.neverBuiltDependencies in workspace not working

### ISSUE THREAD

**Issue by aidenlx** [pnpm/pnpm#5407]
### Code to reproduce the issue: 

folder structure: 
```
├── pnpm-workspace.yaml
└── somepackage
    └── package.json
```

pnpm-workspace.yaml:
```yaml
packages:
  - somepackage
```

somepackage/package.json: 
```json
{
  "name": "somepackage",
  "version": "18.0.3",
  "pnpm": {
    "neverBuiltDependencies": [
      "electron"
    ]
  },
  "devDependencies": {
    "electron": "18.0.3"
  }
}
```

### Expected behavior:

electron's post install script should be ignored

### Actual behavior:

electron's post install script run regardless of `pnpm.neverBuiltDependencies` settings. Without `pnpm-workspace.yaml`, `pnpm.neverBuiltDependencies` works as expected. 

```
❯ pnpm i
Packages: +93
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/aidenlx/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/electron@18.0.3/node_modules/electron: Running postinstall script...
Progress: resolved 93, reused 93, downloaded 0, added 93, done
```

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
This is not an issue. This field is only supported in the root of the workspace. So put this to a package.json that is in the same directory as `pnpm-workspace.yaml`.

**Comment by aruniverse** [comment]
I'm able to reproduce this when applying this setting at the root level package.json. In my pr i can push up my repro case if youd like

**Comment by zkochan** [comment]
I'll check your PR.

**Comment by aruniverse** [comment]
Attached a sample patch to apply to pnpm repo to repro with:
[repro-broken-neverBuiltDependencies.patch.txt](https://github.com/pnpm/pnpm/files/10125949/repro-broken-neverBuiltDependencies.patch.txt)
