### ISSUE TITLE
`pnpm install-completion` on Windows writes invalid `.bashrc` lines -- slashes are not escaped

### ISSUE THREAD

**Issue by adam-coster** [pnpm/pnpm#5420]
*search helpers: bash shell windows install-completion tab-completion autocomplete*

Note that `pnpm install-completion` comes from the https://github.com/pnpm/tabtab repo, which is not under active development and explicitly states that it does not support Windows. I'm assuming that others facing this problem will also come to this repo (https://github.com/pnpm/pnpm) first, so this report also serves to explain the problem and the *manual* solution.

### Expected behavior:

Running `pnpm install-completion && source ~/.bashrc && pnpm <tab>-<tab>` should result in seeing tab autompletes.

### Actual behavior:

On Windows there is no change from the behavior before `pnpm install-autocompletion`. This is due to that command writing paths with unescaped `\` separators.

### Versions

- **pnpm:** `7.12.2`
- **node:** `v16.16.0`
- **Git Bash:** Git (`2.37.3.windows.1`), Bash (`5.1.16(1)-release`)
- **Windows 11:** 22H2

### How to Reproduce

1. Run `pnpm install-completion` in bash on Windows
2. Run `source ~/.bashrc` in the same terminal to refresh the loaded config
3. Try to run `pnpm <tab>-<tab>` and observe **no tab completion**
4. Open `~/.bashrc`
5. See that it has had appended the following lines, which include *invalid paths* because the `\` slashes escape their neighboring characters instead of being used as path separators

```bash
# tabtab source for packages
# uninstall by removing these lines
[ -f ~\.config\tabtab\bash\__tabtab.bash ] && . ~\.config\tabtab\bash\__tabtab.bash || true
```

6. Open the listed paths (with correct steps, e.g. `~\\.config\\tabtab\\bash\\__tabtab.bash` or `~/.config/tabtab/bash/__tabtab.bash`)
7. Observe the same problem:

```bash
# tabtab source for pnpm package
# uninstall by removing these lines
[ -f ~\.config\tabtab\bash\pnpm.bash ] && . ~\.config\tabtab\bash\pnpm.bash || true
```

8. Replace all such `\` slahes with `/`
9. Run `source ~/.bashrc` again
10. Try to run `pnpm <tab>-<tab>` and observe **tab completion** (success!)
11. Re-run `pnpm install-completion` and observe that the invalid lines are appended again. Each re-run reappends the same invalid lines.

### How to Fix (manually)

After running `pnpm install-completion`, visit the files and lines mentioned in the prior section and replace the `\` characters with `/`

### How to Fix (in the package)

At least for Bash, the *only* thing that makes `pnpm install-completion` Windows-incompatible is the use of the unescaped slashes.

Since POSIX-style slashes *also* work on Windows most of the time (and definitely work for both Bash and Node), swapping `path` for `path.posix` throughout [the installer(https://github.com/pnpm/tabtab/blob/main/lib/installer.js) would probably get the job done.

**Comment by alumni** [comment]
This is one thing, but even with the suggested fix, there's still more to be done, e.g. https://github.com/pnpm/tabtab/blob/main/lib/utils/systemShell.js#L7 needs to detect Git Bash correctly.

It would be nice to see Windows support :)

**Comment by KSXGitHub** [comment]
> needs to detect Git Bash correctly.

`systemShell` has just been removed. Instead of trying to detect shell correctly from external environments (which is error-prone), we now let all the completion scripts to explicitly overwrite `SHELL` to their corresponding values when invoking the completer.

**Comment by alumni** [comment]
The slashes are still not correct on Windows (Git Bash) in neither bashrc nor tabtab.

Also, even after correcting the slashes, the completion is buggy.

Typing `pnpm ins<tab><tab>` will suggest every pnpm command instead of auto completing 'install'.

**Comment by KSXGitHub** [comment]
@alumni What version of pnpm are you using? I think the fix hasn't been released to stable yet (is that right, @zkochan?).

**Comment by KSXGitHub** [comment]
Once pnpm v9 becomes stable, you should re-install completion with the following method:

```bash
# Remove the old completion method
sed -i '/tabtab/d' ~/.bashrc

# Install the new method (you can also save it to specialized file and the source it instead)
pnpm completion bash >> ~/.bashrc
```
