### ISSUE TITLE
Maybe there are some advantages to draw from Maven and Gradle 1/3: About registery

### ISSUE THREAD

**Issue by yn-tadpole** [pnpm/pnpm#5422]
Maven and Gradle are the most important package managers in the Java language space, and PNPM is the most elegantly designed package manager in Javascript. Maybe some design ideas can be borrowed from Maven and Gradle.

**The user story**
As a developer, I often have to manage a lot of projects, and each project needs to get some private dependency packages from different NPM private servers. But I often run into the inability to set up a different registery server for each project, instead of using a uniform configuration. Switching between different projects can cause a lot of trouble.

**The Solution**
Add an extended configuration item `registery` to the package.json file. The reference is as follows:
```
{
  'registery': {
     pnpmLocal(),
     pnpmServer({
        url 'https://....'
        credentials {
            username xxxx
            password xxxx
        }
    })
  }
}
```

This `registery` configuration item specifies the server address and priority of downloading dependent packages.

**Comment by zkochan** [comment]
What is the benefit over `.npmrc`? Also, storing credentials in a `package.json` is a very bad idea as the package.json is published with the package to the registry.

**Comment by yn-tadpole** [comment]
Oh, yes. You are right.
