### ISSUE TITLE
Maybe there are some advantages to draw from Maven and Gradle 2/3: Local Repository

### ISSUE THREAD

**Issue by yn-tadpole** [pnpm/pnpm#5423]
Maven and Gradle are the most important package managers in the Java language space, and PNPM is the most elegantly designed package manager in Javascript. Maybe some design ideas can be borrowed from Maven and Gradle.

**The user story**

As a developer, I need to develop some npm packages for others. Sample projects are important during development. I usually build sample projects and write samples during the development of the npm packages. Try the following methods, but you will encounter some problems. 

- **Use `pnpm link` to reference the package in the sample project**. First, the dependency is not written to `package.json`, and the dependency of the project is not clear. Then, it seems that after modifying `package.json` in the sample project and doing the `pnpm install`, the package of `pnpm link` is no longer linked to the code of the original project. Updates to the original project code are not reflected in the sample project. 

- **Use `file` to specify the dependency in the sample project**. An example is as follows(package.json):

  ```
  "dependencies": {
      ...
      "package_name": "file:/path/to/npm_package",
      ...
    },
  ```

  It seems that the source code is copied to the `node_modules` directory at one time, rather than keeping a link to the source code.

**The Solution**

- **One**: `pnpm link` should be written to `package.json`. Maybe in the following format:

  ```
  "dependencies": {
      ...
      "package_name": "~global-link",
      ...
    },
  ```

  Also, it should keep it in sync with the source project code, not copy the code to the node_modules directory.

- **Two**: Use `file` to specify the dependency in the projects also should keep it in sync with the source project code, not copy the code to the node_modules directory.

**Comment by zkochan** [comment]
The `link:` protocol will do what you want:

```
"dependencies": {
    ...
    "package_name": "link:/path/to/npm_package",
    ...
  },
```

**Comment by yn-tadpole** [comment]
Oh. It's good. Thanks!
