### ISSUE TITLE
Overrides with relative local paths(link:) points to invalid paths

### ISSUE THREAD

**Issue by giuseppelt** [pnpm/pnpm#5443]
With the last version 7.13 pnpm overrides with relative linked path are broken.
It works fine with 7.12.1

The calculated relative paths don't start from the root.
It's resolved from somewhere deep in the tree(actual behavior=wrong), and not from the root (previous behavior=right). 

### pnpm version:
7.13

### Code to reproduce the issue:
```
{
  "pnpm": {
     "overrides": {
          "PACKAGE:" : "link: ../../path/to/disk"
     }
  }
}
```

### Expected behavior:
Linked location resolved from the root

### Actual behavior:
Wrong location linked

### Additional information:
node16
Windows

**Comment by zkochan** [comment]
@lvqq did your changes break it?

**Comment by lvqq** [comment]
I think it's not from my changes, I just update the read of `link --global` from `cwd` to `--dir` option or `cwd`

**Comment by zkochan** [comment]
Looks like it stopped working after this PR: https://github.com/pnpm/pnpm/pull/5403
