### ISSUE TITLE
[Bug] Installation in monorepos is not working since 7.11

### ISSUE THREAD

**Issue by matteobruni** [pnpm/pnpm#5454]
### pnpm version:
7.13.1

### Code to reproduce the issue:
No code to show.

You can see the issue in this GitHub workflow clearly:

https://github.com/matteobruni/tsparticles/actions/runs/3188469288/jobs/5201173295

And this is the previous one that was working:

https://github.com/matteobruni/tsparticles/actions/runs/3182847410/jobs/5189320560

What's changed? I updated pnpm from 7.11.0 to 7.13.1, same problem affected 7.12.x as well.

### Expected behavior:

Running `pnpm install` in a monorepo must install everything, like in 7.11.0.

### Actual behavior:

`pnpm install` is not creating `node_modules` folder, making the monorepo unusable.

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS and Linux

---

Since this bug is blocking, my repository will be reverted to 7.11.0, that's why I linked the GitHub actions executions. You can try yourself cloning the repository and running `pnpm install` to see the issue.

These are the steps that should work, at least with 7.11.0 are working:

- run: pnpm install --no-frozen-lockfile
- run: pnpm run --filter @tsparticles/build build:ci
- run: pnpm install --no-frozen-lockfile
- run: npx lerna run build:ci

Another minor issue can be seen here as well, I have to run two different installs because the CLI command coming from the `@tsparticles/build` package, that is part of the monorepo, is not being recognized until I execute another install. It's frustrating, but at least is not blocking.

**Comment by zkochan** [comment]
Using your repo I was able to create a smaller workspace that reproduces the issue: https://github.com/zkochan/pnpm-issue-5454

**Comment by unional** [comment]
Have experience this for a while. Have to do `pnpm i --force` every time, probably the same as #5427
