### ISSUE TITLE
Babel run time spikes significantly when project is installed with pnpm

### ISSUE THREAD

**Issue by andreypopp** [pnpm/pnpm#546]
### Code to reproduce the issue:

```
% git clone https://github.com/prometheusresearch/react-ui.git
% cd react-ui
% pnpm install
% make build # observe it takes sooo long
```

### Expected behavior:

Babel run time shouldn't be so big.

### Additional information:

 - `node -v` prints: v6.9.1
 - OS X

**Comment by andreypopp** [comment]
Looks like the issue manifests itself only with `--preserve-symlinks` activated. Do we require it for recent Node versions? Looks like it works without it also.

That's how flamechart looks, Node's algo with the presence of `--preserve-symlinks` looks suboptimal:
<img width="1040" alt="screen shot 2017-01-16 at 13 05 31" src="https://cloud.githubusercontent.com/assets/30594/21978652/9014277e-dbec-11e6-94ff-dedae0d00362.png">

**Comment by zkochan** [comment]
You were faster, I wanted to suggest this:

Could you please also check how it works without preserve-symlinks?

* run `npm config set preserve-symlinks false`
* remove node_modules and reinstall (the store shouldn't be removed, from pnpm@0.46 the store is immutable

**Comment by andreypopp** [comment]
Yes, much faster that way. What's the story with `--preserve-symlinks`? Is it required for pnpm to work correctly? Is it going to be deprecated by Node?

Hm... I still see Jest's runtime suffer (`make test`).

**Comment by zkochan** [comment]
Seems like it is going to be deprecated by Node... But pnpm works fine without `--preserve-symlinks` since [0.47.0](https://github.com/rstacruz/pnpm/releases/tag/v0.47.0). I was actually waiting for a reason to remove preserve-symlinks, so here it is :smile:

**Comment by zkochan** [comment]
We can make `preserve-symlinks` false by default once #571 gets merged.
