### ISSUE TITLE
Unknown option: 'recursive' when using `pnpm -r`

### ISSUE THREAD

**Issue by NikhilVerma** [pnpm/pnpm#5463]
### Code to reproduce the issue:

```sh
corepack prepare pnpm@7.13.0 --activate
pnpm recursive
```

### Expected behavior:

Recursive mode should work

### Actual behavior:

```sh
pnpm recursive                                                                                                                                                                         (base) 15:04:11
 ERROR   ERROR  Unknown option: 'recursive'
For help, run: pnpm help recursive
```

### Additional information:

 - `node -v` prints: v16.17.1
 - Windows, macOS, or Linux?: MacOS 12.6

**Comment by mani-rsg** [comment]
Hi @NikhilVerma  can you help me with how you solved this? I get the same error when using `pnpm --filter` option in pnpm version 7.13.5

**Comment by NikhilVerma** [comment]
Are you using fish shell? It has a nvm shorcut which is a custom command which doesn't pass the arguments properly

**Comment by NikhilVerma** [comment]
Also fish recursive needs to be followed with a subcommand on it's own it doesn't do anything

**Comment by mani-rsg** [comment]
Hey @NikhilVerma thanks for your reply, solved this. I was using this command in the wrong directory, my bad.
