### ISSUE TITLE
keep getting EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by mohamedy72** [pnpm/pnpm#5474]
### pnpm version:
7.13.0

### Code to reproduce 
`pnpm install`

### Expected behavior:
Expected to install without such warnings

### Actual behavior:
![pnpm](https://user-images.githubusercontent.com/63966406/194874751-84a9a08c-d416-478d-ae8e-9bd56ccb782c.png)

### Additional information:

 - `node -v` prints:  v16.17.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
Try to use a store inside the media. You can change the store location with the store-dir setting.

**Comment by mohamedy72** [comment]
Unfortunately, that doesn't work  
![47747](https://user-images.githubusercontent.com/63966406/196697593-4d4ffae1-eb92-41bd-ac40-9acbea5951ef.png)

**Comment by zkochan** [comment]
This should be fixed by [v7.14.2](https://github.com/pnpm/pnpm/releases/tag/v7.14.2)

**Comment by ThatGuySam** [comment]
If you're *still* getting this you may need to `pnpm install` to update your lock file

**Comment by mohamedy72** [comment]
> If you're _still_ getting this you may need to `pnpm install` to update your lock file

It is not project-specific, it happens everytime i initialize a new project ( i use vitejs mainly )
