### ISSUE TITLE
pnpm not installing overrides

### ISSUE THREAD

**Issue by runspired** [pnpm/pnpm#5477]
### Code to reproduce the issue:

```
mkdir pnpm-bug
cd pnpm-bug
pnpm init
pnpm add ember-maybe-in-element
```

edit the `package.json` tp have the following override (full file shown)

```json
{
  "name": "pnpm-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ember-maybe-in-element": "^2.0.3"
  },
  "pnpm": {
    "overrides": {
      "ember-maybe-in-element": "@runspired-forks/ember-maybe-in-element@2.0.4"
    }
  }
}

```

Run `pnpm install`

Inspect 

### Expected behavior:

Override is installed and addressable. Normal node resolution for `ember-maybe-in-element` resolves to `@runspired-forks/ember-maybe-in-element`

### Actual behavior:

`@runspired-forks/ember-maybe-in-element` is not installed at all, `ember-maybe-in-element` is also not installed at all. A broken alias exists in `node_modules`.

### Additional information:

 - `node -v` prints: 18.9.0
 - Windows, macOS, or Linux?: MacOS 12.5.1 (M1 Max)
 
 This issue also presents itself in our CI builds which run on github-actions `ubuntu-latest` hardware.

**Comment by runspired** [comment]
Best I can tell, `pnpm` is attempting to treat the package download as a local resolution. When I originally hit this the below warning was not printed, I think because the override is for a dep of a dep. In the reproduction in which it is top level we see this warning which explains the fail-case fairly well:

```
pnpm install
ember-maybe-in-element is linked to /Users/cthoburn/github/pnpm-bug/node_modules from /Users/cthoburn/github/pnpm-bug/@runspired-forks/ember-maybe-in-element@2.0.4
Already up to date
 WARN  Local dependency not found at /Users/cthoburn/github/pnpm-bug/@runspired-forks/ember-maybe-in-element@2.0.4
 ```

**Comment by runspired** [comment]
It appears that pnpm has an extra requirement that overrides specify `npm:` in their source. If this is intentional it should probably be made more clear in the docs. `npm` override documentation is similarly confusing in this area.

**Comment by lvqq** [comment]
Adding a `npm:` prefix works fine for me. The documentation about `overrides` provides a example about it: https://pnpm.io/package_json#pnpmoverrides

**Comment by mcmxcdev** [comment]
Tried this out locally and indeed works fine with the `npm:` prefix which is also mentioned in the docs.
