### ISSUE TITLE
`pnpm link --global <pkg>` turns devDependency into dependency

### ISSUE THREAD

**Issue by Anoesj** [pnpm/pnpm#5478]
### pnpm version:
7.13.4

### Code to reproduce the issue:
In my case, I was in the root of a pnpm workspace, which had some global packages installed there. I'm using `shamefully-hoist=true` in my root `.npmrc` file. I had an NPM package installed from the NPM registry (installed with `pnpm i -D <pkg>`), then forked that packaged to make a contribution. I linked the forked package by running `pnpm link --global` and then went back to my pnpm workspace and ran `pnpm link --global <pkg>`, in my case in the root of a pnpm workspace.

### Expected behavior:
`package.json` is not altered, the dependency stays a devDependency, as it already was.

### Actual behavior:
After running all steps described above, the package was turned into a regular dependency.

### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
It should not change the type of the dependency.
