### ISSUE TITLE
workspace: pnpm is not using the correct consumer peer dependency

### ISSUE THREAD

**Issue by GiancarlosIO** [pnpm/pnpm#5479]
### Code to reproduce the issue:
https://github.com/GiancarlosIO/monorepo-context-bug

### Expected behavior:
The consumer app and the package should use the same version/instance of styled components.

### Actual behavior:
The next app is throwing an error because the package `@my-org/web` is using a different version/instance of the package `styled-components` that the nextjs has installed.

Looks like the package `@my-org/web` is using its own version of `styled-components` even when styled-component was defined as peer dependency in `@my-org/web`. 

**`@my-org/web` must use the `styled-component` that is installed in the nextjs app.**

**I think it's related to pnpm workspaces because if I install the package `@my-org/web` using the npm registry it works without errors. It only fails when I use the "workspace:*" protocol.**

![image](https://user-images.githubusercontent.com/17274950/195170707-99aebfd4-00db-42a2-bea8-0f0244f6a4b8.png)

### Additional information:
It's a simple next app that is trying to use a UI framework located in the same repository. To make it work the next and the UI framework must use the same instance of the styled component package.

 - `node -v` prints: v14.19.2
 - Windows, macOS, or Linux?: macOS

**Comment by genshinw** [comment]
You can use [injected feature](https://pnpm.io/package_json#dependenciesmetainjected) to handle this problem

**Comment by GiancarlosIO** [comment]
@genshinw oh wow, I didn't know something like that existed. Enabling that feature makes the nextjs app work without errors, thanks!!!!

Also, do you know if the injected feature has cons that we need to be aware of? 🤔

**Comment by genshinw** [comment]
@GiancarlosIO The cons and some problem is discussing in https://github.com/pnpm/pnpm/discussions/3938. As far as I know, injected workspace will create hard-link for every exiting file(not dir like soft-link) , which may case some issue.

1. Bad DX,  when you watch and develop the injected  lib, you must reinstall to recreate the hard-link for new file.
2. Hard to integration, If you want to trigger build scripts after pnpm install, the output dir ”dist“ will n[ot in the hard-link dir ](https://github.com/pnpm/pnpm/discussions/3938#discussioncomment-3790570)

**Comment by GiancarlosIO** [comment]
thanks for the info @genshinw !
I'll close this for now.
