### ISSUE TITLE
pnpm node dependency not clearly noted in installation docs

### ISSUE THREAD

**Issue by acalvino4** [pnpm/pnpm#5483]
### pnpm version:
7.13.4

### Code to reproduce the issue:
NA - docs issue

### Expected behavior:
Straightforward docs for reliable installs

### Actual behavior:
I install `pnpm` but it doesn't work because node isn't installed yet.

### Additional information:

 - `node -v` prints: NA
 - Windows, macOS, or Linux?: macOS

The [Installation docs](https://pnpm.io/installation) don't explicitly list the requirement for node to be installed already, creating a hiccup for some new users (myself being one). I know this at least applies to homebrew installs, (noted in [their docs](https://formulae.brew.sh/formula/pnpm#default)), though I'm not sure if it applies to the other installation methods as well.

Along with this, it is not clear (from pnpm nor brew docs) if there is a minimum version of node that must be installed (I assume there is), or what that would be.

**Comment by lvqq** [comment]
I think there aleady have it: https://pnpm.io/installation#compatibility

**Comment by zkochan** [comment]
Added a section to the installation page: https://github.com/pnpm/pnpm.github.io/pull/341
