### ISSUE TITLE
`pnpm outdated` command fails to detect updates when `registry` is configured

### ISSUE THREAD

**Issue by jiadesen** [pnpm/pnpm#5492]
### pnpm version

7.13.4

### Code to reproduce the issue:

NA

### Expected behavior:

<img width="590" alt="expected" src="https://user-images.githubusercontent.com/22772994/195750745-1b5a3dc1-4c2b-4f87-94fc-9c02b55d6307.png">

### Actual behavior:

<img width="643" alt="actual" src="https://user-images.githubusercontent.com/22772994/195751254-9f0111c9-f6b1-493e-ab6d-649ae9a2e9c0.png">

### Additional information:

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
A workaround is to set the registry to:

```
registry=https://registry.npmmirror.com
```
