### ISSUE TITLE
Silent installs fail without reporting any error

### ISSUE THREAD

**Issue by stefan-toubia** [pnpm/pnpm#5509]
Related: #4298

### Code to reproduce the issue:

[Repro](https://github.com/stefan-toubia/pnpm-multi-lockfile/tree/silent-install-no-error)

`pnpm --silent install` does not show an error message on error.

Repro:

`project-b` package defines an invalid dependency `package-does-not-exist`

```sh
$ cd project-b
$ pnpm --silent install

$ pnpm install
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/package-does-not-exist: Not Found - 404

package-does-not-exist is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 0, reused 1, downloaded 0, added 0
```

### Expected behavior:

pnpm should print an error message when encountering a fatal error that causes install to fail

### Actual behavior:

there is no error output

### Additional information:

 - `node -v` prints: 16.15.1
 - Windows, macOS, or Linux?: macos

**Comment by HashemKhalifa** [comment]
facing the same issue on the CI mostly, locally it passes without any errors!

`Error: Process completed with exit code 1.`

**Comment by zkochan** [comment]
I am not sure. This might be expected. npm looks like behaves similarly.

If you want the error to be printed, you may use:

```
pnpm i --loglevel error
```
