### ISSUE TITLE
Can't use `pnpm -g ls` after update 7.13.5

### ISSUE THREAD

**Issue by Tsuj100** [pnpm/pnpm#5513]
![image](https://user-images.githubusercontent.com/38718810/196327653-dd355d33-6641-446e-b52f-fbe4e015e4c9.png)

**Comment by Tsuj100** [comment]
after reinstallation
![image](https://user-images.githubusercontent.com/38718810/196330092-540f2692-dc56-4173-8154-e58092f2dfda.png)

**Comment by lloydjatkinson** [comment]
Also just started hitting this myself - running the "source" command it suggests on installation does not fix it either.
