### ISSUE TITLE
I want to run project but received the error:

### ISSUE THREAD

**Issue by chengpengjava** [pnpm/pnpm#5519]
Hello,I met a problem in the process of learning pnpm,I created a project by workspace like this:
![b1047cb5253aa6a0c2d4932cb192087](https://user-images.githubusercontent.com/33616855/196687934-e8f6589e-6c23-4d56-bdd5-551983cdd383.jpg)
I wrote pnpm-workspace.yaml and script refer to official website like this:
![image](https://user-images.githubusercontent.com/33616855/196688393-6963049b-b0d4-430d-95a5-354923e999e8.png)
![image](https://user-images.githubusercontent.com/33616855/196688464-b8cea45b-7fe3-4776-bab5-449ce440bdf7.png)
![image](https://user-images.githubusercontent.com/33616855/196688562-f59f4129-119c-4598-a2f1-de8bb6ef6be7.png)
![image](https://user-images.githubusercontent.com/33616855/196688621-1487c2d4-71a2-4bbc-aa62-ea1b03a0702d.png)
and then I run project but the following error:
![image](https://user-images.githubusercontent.com/33616855/196689078-ca0a34b1-1217-4508-b56b-c1832d2b6abb.png)
Where did I get it wrong?

**Comment by lvqq** [comment]
`pnpm run` in the workspace root directory read the root package.json, there doesn't exist the script dev.

If u want to run the scripts defined in subsets of packages, u should use `-r` or `--filter` option with it.

- https://pnpm.io/filtering
- https://pnpm.io/cli/recursive

**Comment by zkochan** [comment]
`-F=a` should be before `dev`. This will work:

```
pnpm run -F=a dev
#or 
pnpm -F=a run dev
```

**Comment by chengpengjava** [comment]
> 

Thanks,you're right,I didn't read the offical document carefully.
