### ISSUE TITLE
`pnpm test` does not pass flags to the script without `--`

### ISSUE THREAD

**Issue by joshlartz** [pnpm/pnpm#5522]
Normally, pnpm will pass whatever flags you provide to the package.json script, but `test` seems special. It seems like it is a pnpm command rather than a script passthrough. 

When calling test, I still need to `--` to escape and pass my own flags. 

### pnpm version:
7.9-7.13.5

### Code to reproduce the issue:
{
  "scripts": {
    "test": "jest",
    "test:ts": "jest"
  }
}
`pnpm test --no-coverage`
`pnpm test:ts --no-coverage`
`pnpm test -- --no-coverage`

### Expected behavior:
the flag should be passed to the script

### Actual behavior:
Unknown option: 'coverage'
Did you mean 'reverse'? Use "--config.unknown=value" to force an unknown option.

### Additional information:

 - node 16.18.0
 - macOS

**Comment by mcmxcdev** [comment]
What you report as issue is expected behavior since https://github.com/pnpm/pnpm/releases/tag/v7.0.0

In a freshly created repo with only `jest` installed:

- `pnpm test -- --no-coverage` works fine for me
- `pnpm run test --no-coverage` also passes

Let me know if it works for you!

**Comment by joshlartz** [comment]
@mcmxcdev `pnpm run test --no-coverage` works, but I was expecting it to work as just `npm test --no-coverage` also since `test` is a package.json script in this case. pnpm considers `test` one of its commands and hence doesn't pass the args, but it should when a script is declared for `test`.

**Comment by marcnewport** [comment]
I ran into this problem myself when migrating from yarn. I have `pnpm test --runInBand` in a cd pipeline and expected it would not error out since `test` is a package script. This is a slight difference from the other package scripts and isn't mentioned in the docs (that I could find).

**Comment by JGJP** [comment]
`pnpm test` should behave like `pnpm run test` if there is a test script defined, imo
