### ISSUE TITLE
$PNPM_HOME broken in latest release 7.13.5

### ISSUE THREAD

**Issue by rotexhawk** [pnpm/pnpm#5524]
Since the upgrade, my bash script is not switching between homebrew and system PNPM. I have a couple of projects that rely on pnpm 6 and I switch between the two by using `brew link/unlink`

using `Iterm zsh` on macos. 

```
## Make sure you start a new tab after switching
if [ -f "/usr/local/bin/pnpm" ]; then
    PNPM_HOME="/usr/local/bin/pnpm"
    echo "Using homebrew pnpm $(pnpm --version)"
else
    echo "gets here too"
    PNPM_HOME="/Users/XXXX/Library/pnpm"
    echo "Using system pnpm $(pnpm --version)"
fi

# pnpm
export PNPM_HOME=$PNPM_HOME
export PATH="$PNPM_HOME:$PATH"
# pnpm end
```

I can confirm that the `PNPM_HOME` is set with the correct path and if I do `$PNPM_HOME --version` I get `7.13.5` but `pnpm --version` shows `6.11.0` 

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: MacOs

**Comment by lvqq** [comment]
The first path`PNPM_HOME="/usr/local/bin/pnpm"` is an executable file. 
The second path `PNPM_HOME="/Users/XXXX/Library/pnpm"` is a directory. 

That's the problem I think.

**Comment by rotexhawk** [comment]
Thanks. Turns out when I switched the node versions, `nvm` added another pnpm version which was over writing this setup. Pretty strange!
