### ISSUE TITLE
403 Forbidden maintainers error when pnpm publish, but npm publish is ok

### ISSUE THREAD

**Issue by iamzuijiasunyou** [pnpm/pnpm#5527]
### pnpm version: 
v6 / v7 

### Code to reproduce the issue:
pnpm publish

### Expected behavior: 
publish success

### Actual behavior:

npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://private.registry.com/pnpm-demo - maintainers error
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macos

**Comment by iamzuijiasunyou** [comment]
it's private registry problem, publish to npmjs.com is ok

**Comment by kinfuy** [comment]
如果想发布到 private registry 怎么解决的？

**Comment by iamzuijiasunyou** [comment]
> 如果想发布到 private registry 怎么解决的？

用npm publish去发布

**Comment by kinfuy** [comment]
> > 如果想发布到 private registry 怎么解决的？
> 
> 用npm publish去发布

monorepo想使用pnpm publish 自动更新workspace: *,有其他更好的办法吗？

**Comment by await-ovo** [comment]
> > > 如果想发布到 private registry 怎么解决的？
> > 
> > 
> > 用npm publish去发布
> 
> monorepo想使用pnpm publish 自动更新workspace: *,有其他更好的办法吗？

We can use `changesets` to handle version update(https://pnpm.io/workspaces#release-workflow).

**Comment by kinfuy** [comment]
> > > > 如果想发布到 private registry 怎么解决的？
> > > 
> > > 
> > > 用npm publish去发布
> > 
> > 
> > monorepo想使用pnpm publish 自动更新workspace: *,有其他更好的办法吗？
> 
> We can use `changesets` to handle version update(https://pnpm.io/workspaces#release-workflow).

Thank you. Maybe I should study what pnpm publish has done and why private sources can't be published like normal public sources
