### ISSUE TITLE
pnpm start runs itself recessively after upgrade to pnpm 7

### ISSUE THREAD

**Issue by shlomizadok** [pnpm/pnpm#5542]
My React monorepo app uses pnpm@6.23.0, and I am looking to upgrade it to pnpm 7.
After installing pnpm 7, I am trying to run my app with `pnpm start` however it just tries to rerun itself... (seems like `--filter=...` is ignored?)
e.g.,

```
> tokyo-ui@1.0.1 start /Users/szadok/dev/tokyo-ui
> APP_ENV=dev pnpm start --filter=@vzmi/sspi-app


> tokyo-ui@1.0.1 start /Users/szadok/dev/tokyo-ui
> APP_ENV=dev pnpm start --filter=@vzmi/sspi-app "--filter=@vzmi/sspi-app"


> tokyo-ui@1.0.1 start /Users/szadok/dev/tokyo-ui
> APP_ENV=dev pnpm start --filter=@vzmi/sspi-app "--filter=@vzmi/sspi-app" "--filter=@vzmi/sspi-app"


> tokyo-ui@1.0.1 start /Users/szadok/dev/tokyo-ui
> APP_ENV=dev pnpm start --filter=@vzmi/sspi-app "--filter=@vzmi/sspi-app" "--filter=@vzmi/sspi-app" "--filter=@vzmi/sspi-app"


> tokyo-ui@1.0.1 start /Users/szadok/dev/tokyo-ui
> APP_ENV=dev pnpm start --filter=@vzmi/sspi-app "--filter=@vzmi/sspi-app" "--filter=@vzmi/sspi-app" "--filter=@vzmi/sspi-app" "--filter=@vzmi/sspi-app"
```

### Code to reproduce the issue:
in package.json:
```
"start": "APP_ENV=dev pnpm start --filter=@vzmi/sspi-app",
```

(Thanks in advance for the help and this awesome pnpm ❤️)

### Expected behavior:
To start the app
(in 6.23.0 it looks like):
```
> tokyo-ui@1.0.1 start /Users/szadok/dev/tokyo-ui
> APP_ENV=dev pnpm start --filter=@vzmi/sspi-app


> @vzmi/sspi-app@1.0.0 start /Users/szadok/dev/tokyo-ui/app
> webpack serve --config ./webpack.dev.config.js --mode development
```

### Additional information:
pnpm-workspace.yaml looks like
```
packages:
 - 'app'
 - 'packages/*'
```

 - `node -v` prints: 16.14.0
 - Windows, macOS, or Linux?: Mac

**Comment by shlomizadok** [comment]
I was able to start my app by changing the command on package.json to:
` "start": "APP_ENV=dev pnpm run --filter=@vzmi/sspi-app start"`
I'm curious though whether it is the right approach or am I missing something?

**Comment by zkochan** [comment]
This was a breaking change in pnpm v7. See the second point on the release page: https://github.com/pnpm/pnpm/releases/tag/v7.0.0
