### ISSUE TITLE
feat: improved exec/filter command chaining

### ISSUE THREAD

**Issue by runspired** [pnpm/pnpm#5543]
Sometimes it's useful to run more than one command. For instance, when using workspaces you may wish to have a macro-command in root that might run package-A's build and package-B's tests. The need for such task composition is why tools like Lerna and [npm-run-all](https://www.npmjs.com/package/npm-run-all) exist, but sometimes simply chaining with `&&` avoids a lot of annoyances.

**Problem**: Today, the following command does not behave as you might expect, because `pnpm --filter packageB test` is executed within the context of `packageA` and not `root`.

```json
{
  "build-and-test": "pnpm --filter packageA build && pnpm --filter packageB test"
}
```

A solution here is non-trivial, as a user may reasonably also expect to use chaining within the command in the workspace itself. 

Some potential solutions:

- special-case `&& pnpm` to return command scope to the root

- add an explicit command `chain` with the semantics that individual commands are separated by `,` and `pnpm` is presumed to prefix each command.

```json
{
  "build-and-test": "pnpm chain --filter packageA build, --filter packageB test"
}
```

- add some form of handling for quoted commands to `run/exec`

```json
{
  "build-and-test": "pnpm exec 'pnpm --filter packageA build' && 'pnpm --filter packageB test'"
}
```

Personally I feel the second option here could be a powerful and expressive addition to the tool, however, I am very open to any idea that solves this use-case without adding more installed node dependencies.

**Comment by runspired** [comment]
I'm realizing I trolled myself and `"build-and-test": "pnpm --filter packageA build && pnpm --filter packageB test"` actually works the way I at first thought it would. That said, explicit chaining would still be a powerful addition here I think, so going to leave this open for discussion.

**Comment by NullVoxPopuli** [comment]
turborepo.org/ provides this behavior, chaining, dependencies, etc -- would that work?

**Comment by runspired** [comment]
yeah it probably does.
