### ISSUE TITLE
List all Node.js versions installed by pnpm

### ISSUE THREAD

**Issue by lvqq** [pnpm/pnpm#5546]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

It's hard to know which versions I have installed except enter the installing directory.

**Describe the solution you'd like**

`pnpm env list -g` and alias for `pnpm env ls -g`, inspired by `nvm list`

**Comment by zkochan** [comment]
Sounds good.

What if we want to list all node.js versions? I think we have a feature request for that as well.

**Comment by lvqq** [comment]
I‘m ok with implementing it together, and I tend to remove the global option for that command.

Which one do you prefer?

`pnpm env list --remote` and alias for `pnpm env list -r`

Or

`pnpm env list-remote` and alias for `pnpm env ls-remote`

The second one is same with `nvm`. And listing all remote version is too long, maybe a filter is needed as well. For instance, `pnpm env ls-remote 14` or `pnpm env ls-remote lts`.

**Comment by zkochan** [comment]
I vote for the first one.

**Comment by lvqq** [comment]
Ok, please assgin it to me and I will work on implementing it later
