### ISSUE TITLE
ERR_PNPM_UNEXPECTED_STORE  Unexpected store location

### ISSUE THREAD

**Issue by chengpengjava** [pnpm/pnpm#5551]
Hello,team.
I got a problem the following:
![image](https://user-images.githubusercontent.com/33616855/197668039-3b66189f-fd03-4bc0-99a2-ac5b3ef464f1.png)

My complete operation is:
1.I changed store default location to this:`D:\pnpm\file\store`
2.I changed global default location to this:`D:\pnpm\file\global`
3.my config is following:
![image](https://user-images.githubusercontent.com/33616855/197668556-002d4073-2311-4b7f-9c60-fe1073ae1114.png)
4.Now I need to install a package prisma globally because --save-dev cannot use prisma's cli,so I ran `pn -g i prisma`(pn is alias)and then I got the problem in the start.It's useless I ran `pnpm install` according to its prompts. 
5.If I change the global location to `D:\pnpm\file\store` no problem then.
So why?And I don't think it's good to put store and global location together and the official documents about global's location and store's location are also different.
Thanks

### Additional information:

 - `node -v` prints:v16.15.1
 - Windows, macOS, or Linux?:windows 11

**Comment by zkochan** [comment]
Try to run `pn i -g`

**Comment by chengpengjava** [comment]
> Try to run `pnpm i -g`

Oh,thank you,you're right.I ran `pnpm -g i prisma` successfully after ran `pnpm i -g`
