### ISSUE TITLE
pnpm crashes because of bad non-null assertion at newLockfile.packages!

### ISSUE THREAD

**Issue by jedwards1211** [pnpm/pnpm#5553]
Clearly non-null assertions are an antipattern...

### pnpm version: 7.14.0

When I try to install one of my private packages I get a null pointer error on `newLockfile.packages` here:

https://github.com/pnpm/pnpm/blob/11669e6e34bc3e0a1991ce22090c746188302980/packages/resolve-dependencies/src/index.ts#L335

### Code to reproduce the issue:

I'm afraid I haven't gotten it down to an easy repro as this only happens when I try to install one of my private packages on an AWS instance so far.

**Comment by zkochan** [comment]
I guess we can easily fix this, but it would be interesting to see in what case it is null. I can't find any scenario when that would happen. Unless someone creates an afterAllResolved hook in `.pnpmfile.cjs` and removes the field from the lockfile.

**Comment by jedwards1211** [comment]
If it helps, I was trying to `sudo pnpm i -g <tarball url>` on an AWS EC2 Instance.  I tried at one point with a tarball made by `npm` with `bundleDependencies: true`, but also one without `bundleDependencies: true`
