### ISSUE TITLE
`pnpm rebuild` not working when node-linker=hoisted

### ISSUE THREAD

**Issue by balajiv113** [pnpm/pnpm#5560]
### pnpm version:
pnpm - 7.14.0

### Code to reproduce the issue:
https://github.com/balajiv113/pnpm-test

### Expected behavior:
pnpm rebuild should build native modules even when node-linker=hoisted

### Actual behavior:
pnpm rebuild not running as expected node-linker=hoisted

### Additional information:
 - macOS - intel machine

Due to this issue, we are not able to do build electron application using electron-builder for multiple architectures (generating arm apps in intel and vice-versa). The app gets built, but the native binaries are on wrong architecture

**Comment by zkochan** [comment]
Looks like the rebuild command can only lookup packages inside the `node_modules/.pnpm` directory as of now:

https://github.com/pnpm/pnpm/blob/b234923bbfcad573fc2679c37c02d72d1bf7f779/packages/plugin-commands-rebuild/src/implementation/index.ts#L273-L280

Why do you need the rebuild command at all? The deps are built on `pnpm install`.

**Comment by balajiv113** [comment]
Electron builder makes use of this rebuild command to rebuild the native dependency for different arch. 

Due to this issue, for all arch (amd64, arm64) the native dependency are compiled to only to one (amd64).
