### ISSUE TITLE
Shopify CLI v3.0 breaks when some other packages are installed

### ISSUE THREAD

**Issue by rkumorek** [pnpm/pnpm#5562]
### pnpm version: 7.14.0

When I install `copy-webpack-plugin` or `eslint-import-resolver-typescript` packages alongside `@shopify/cli` and `@shopify/theme` things break.
It works if I use `yarn` instead of `pnpm` so thought it mighe be issue with pnpm?

### Code to reproduce the issue:
https://github.com/rkumorek/pnpm-shopify-cli-issue

If you install with pnpm, then run `pnpm shopify version` it will throw error but when `copy-webpack-plugin` is removed it works fine.

### Expected behavior:
Running `pnpm shopify version` should print current version 
![Screenshot 2022-10-28 at 15 07 33](https://user-images.githubusercontent.com/34352395/198633414-98b58b96-a0cf-4fa4-8a2b-030e08d17064.png)

### Actual behavior:
CLI throws error "Command not found"
![Screenshot 2022-10-28 at 15 07 49](https://user-images.githubusercontent.com/34352395/198633596-36ebacfb-ebb6-42c4-bf5d-a828f56609ba.png)

### Additional information:

 - `node -v` prints: v18.9.0
 - Windows, macOS, or Linux?: latest macOS

Not sure if it's an issue with PNPM or Shopify CLI.

**Comment by zkochan** [comment]
Looks like shopify has issues with the symlinked node_modules. With hoisted node_modules it works.

You can add this `.npmrc` to the root of the project:

```
node-linker=hoisted
```

Reinstall with pnpm and it will work.

**Comment by rkumorek** [comment]
Thank you, it works indeed. :clap: 

I might raise an issue within Shopify Cli so it can work out of the box with default pnpm confg.
