### ISSUE TITLE
Please add --fail-if-not-present

### ISSUE THREAD

**Issue by matthew-dean** [pnpm/pnpm#5569]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer and maintainer of a monorepo, I'd like to enforce that everyone adds a `test:ci` script to any new packages, as there's a PNPM command that we run: `pnpm -r test:ci`. However, this script will silently skip any packages that don't have that script. 

**Describe the solution you'd like**

We would want PNPM to check recursively that the script exists. Right now, there's a `--if-present` flag (which is not required for recursive script, and is added implicitly). So, it would be great for there to be a `--fail-if-not-present` flag.

**Describe the drawbacks of your solution**

No drawbacks. Existing behavior would stay the same.

**Describe alternatives you've considered**

To my knowledge, no NPM packages that I can find do this kind of checking for a script being defined in all monorepo packages, and IMO this is more the responsibility of the script runner (in this case, PNPM).

**Comment by zkochan** [comment]
It might be better to support a new setting that lists the required scripts.

Like

```json
{
  "pnpm": {
    "requiredScripts": ["test:ci"]
  }
}
```

**Comment by matthew-dean** [comment]
👍
