### ISSUE TITLE
unable to install the latest version for a library

### ISSUE THREAD

**Issue by gaowujian** [pnpm/pnpm#5573]
### pnpm version:
pnpm : 7.11.0

### Code to reproduce the issue:
I'm using the npm official registry.

pnpm view prosemirror-view versions Or
pnpm view prosemirror-view

pnpm install prosemirror-view@1.29.0  Or
pnpm install prosemirror-view

### Expected behavior:
the target library can be installed successfully

### Actual behavior:
pnpm is unable to fetch the latest version for the library. The prosemirror-view@1.28.3 will be installed

### Additional information:
node: 14.20.0
macOS

**Comment by lvqq** [comment]
I think the problem comes from the package itself not from pnpm's side

With `npm install prosemirror-view@1.29.0` I get the same error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for prosemirror-view@1.29.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2022-11-01T03_41_22_389Z-debug.log
```
