### ISSUE TITLE
pnpm fails to install in a workspace where symlinks from the workspace point into node_modules

### ISSUE THREAD

**Issue by AlexAegis** [pnpm/pnpm#5598]
I'm experimenting with a repo setup where I share tooling config such as prettierrc files and such in npm packages and a postinstall script creates a symlink from the workspace into the installed package.

Now, putting aside how good or bad of an idea this is (haven't tried it on windows yet, I might just stick with copying)
pnpm fails to install such scenario, but I think it should. From the error message I can see it tries to `stat` the files in a local package but that throws an error for broken symlinks that is not caugth.

Now, I have 2 workarounds for myself, one is just to not use such setup, or keep using npm. The other is a preinstall script that cleans broken symlinks, they'd be regenerated anyway, but I'd lose tooling during install. 

### pnpm version:
7.14.0

### Code to reproduce the issue:

Try installing this commit with pnpm

https://github.com/AlexAegis/js/commit/8b1431587b90bf52ab89d5653a6ccb055616a990

### Expected behavior:

Installs just fine, ignoring the broken symlinks

### Actual behavior:

An error is thrown

```sh
 ENOENT  ENOENT: no such file or directory, stat '/home/alex/git/js/packages/vite/.prettierignore'
```

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
The dependency has the postinstall script? That is a bad solution because pnpm is caching packages with lifecycle scripts. So it will only be executed the first time and next time the package will be installed from cache without running the postinstall script.

I guess, alternatively you could run your tool from the `prepare` script of a workspace project.

**Comment by zkochan** [comment]
OK, I understand why this particular error happens. I can fix it.

**Comment by AlexAegis** [comment]
Yes, as I said the idea itself where I discovered this is not that important, I'm just toying with some ideas.

But this definitely looked like a bug, especially after playing with symlinks using node and stat/lstat.

Thanks for looking into it!
