### ISSUE TITLE
Support fetching platform specific optionalDependencies

### ISSUE THREAD

**Issue by alshdavid** [pnpm/pnpm#5603]
It's becoming more common that developers are sharing their platform specific binary packages through `optionalDependencies` which are filtered against package.json criteria like `os` `cpu`, etc.

Take the `lightningcss` package

![image](https://user-images.githubusercontent.com/12656294/200236672-a0c6dae9-f7a1-41bc-9410-6898d2540733.png)

Currently `npm` and `yarn` will install `optionalDependencies` if they are valid for the current platform, however `pnpm` will not install them.

### Code to reproduce the issue:

```
mkdir lightningcss-npm lightningcss-pnpm

cd lightningcss-npm
npm install lightningcss

cd ../lightningcss-pnpm
pnpm install lightningcss

cd ..

echo NPM
ls -l ./lightningcss-npm/node_modules

echo
echo PNPM
ls -l ./lightningcss-pnpm/node_modules
ls -l ./lightningcss-pnpm/node_modules/lightningcss/node_modules
```

![image](https://user-images.githubusercontent.com/12656294/200235777-72c8e76e-6c91-4ad4-a298-1cdd978d297b.png)

### Additional information:

 - `node -v` prints: `v18.12.0`
 - Windows, macOS, or Linux?: MacOS M1

**Comment by lvqq** [comment]
It's under `.pnpm` directory not `node_modules/lightningcss`

Related docs: https://pnpm.io/symlinked-node-modules-structure

**Comment by alshdavid** [comment]
Oh cool, I can see it there however it's not in a location that can be resolved by node. Is this an issue with my usage of pnpm? Is there a post install command I need to run to link the downloaded `optionalDependency`?

<img width="408" alt="image" src="https://user-images.githubusercontent.com/12656294/200275486-27a9a304-2c14-40ea-bbd7-f0a17090074b.png">

**Comment by lvqq** [comment]
No, it will be symlinked to your node_modules by default, you don't need do any extra thing.

**Comment by alshdavid** [comment]
Looks like it works - must be something wrong in my local environment causing issues before 🤔
