### ISSUE TITLE
`pnpm install` creates a directory named '~' in the working directory

### ISSUE THREAD

**Issue by harryzcy** [pnpm/pnpm#5606]
### Code to reproduce the issue:

`pnpm install`

### Expected behavior:

Install the dependencies

### Actual behavior:

Install the dependencies, but also adds a empty directory `~/Library/pnpm/store/v3` (Note that the `~` is not expanded to `$HOME`, but used as the directory as is)

### Additional information:

 - `node -v` prints: v18.12.1
 - Windows, macOS, or Linux?: macOS

**Comment by harryzcy** [comment]
The install script prompted to add
```
export PNPM_HOME="~/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
```
But it's an error to quote `~/Library/pnpm` when path expansion is needed

**Comment by briandipalma** [comment]
To workaround:

```bash
nvim ~/.npmrc
```

and insert

```
store-dir=/home/$YOUR_USER/.local/share/pnpm/store/v3
```

replace `$YOUR_USER` with your user...

**Comment by brachkow** [comment]
Still having this error when pnpm is installed via brew.

Also proposed install script changed to:

```
set -gx PNPM_HOME "~/Library/pnpm"
if not string match -q -- $PNPM_HOME $PATH
  set -gx PATH "$PNPM_HOME" $PATH
end
```
