### ISSUE TITLE
pnpm import fails: ERR_PNPM_INVALID_OVERRIDE_SELECTOR  Cannot parse the "**/cross-fetch" selector in the overrides

### ISSUE THREAD

**Issue by GeoffreyPlitt** [pnpm/pnpm#5611]
When I do `pnpm import yarn.lock` I get "ERR_PNPM_INVALID_OVERRIDE_SELECTOR  Cannot parse the "**/cross-fetch" selector in the overrides"

PNPM 7.13.2

**Comment by GeoffreyPlitt** [comment]
Removing "overrides" fixed it.

**Comment by ron23** [comment]
Still a bug though right?
Ideally it should know to resolve `resolutions`

**Comment by simonwiles** [comment]
Same as #5369 ?
