### ISSUE TITLE
Cannot set store-dir in NPM v9 

### ISSUE THREAD

**Issue by jandolezal71** [pnpm/pnpm#5621]
### pnpm version: `7.15.0`

https://pnpm.io/configuring

### Code to reproduce the issue:

```
nvm install 16.18
npm install pnpm@latest
pnpm config set store-dir .pnpm-store
```

### Expected behavior:

```
npm will set `store-dir=.pnpm-store` to `.npmrc` file
```

### Actual behavior:

```
npm ERR! `store-dir` is not a valid npm option
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-11T08_10_13_758Z-debug-0.log
```

### Experimental

On npm version 7 or 8, it works.

```
npm install -g npm@8
npm -v # 8.19.3
pnpm config set store-dir /path/to/.pnpm-store
npm config list

# store-dir = "/path/to/.pnpm-store"
```

### Log

```
32 info config set "store-dir" "/path/to/.pnpm-store"
33 timing command:config Completed in 3ms
34 verbose stack Error: `store-dir` is not a valid npm option
34 verbose stack     at Config.set (/usr/local/lib/node/lib/node_modules/npm/lib/commands/config.js:163:15)
34 verbose stack     at Config.exec (/usr/local/lib/node/lib/node_modules/npm/lib/commands/config.js:125:22)
34 verbose stack     at Npm.exec (/usr/local/lib/node/lib/node_modules/npm/lib/npm.js:187:29)
34 verbose stack     at async module.exports (/usr/local/lib/node/lib/node_modules/npm/lib/cli.js:133:5)
35 verbose cwd /
36 verbose Linux 5.13.0-52-generic
37 verbose node v16.18.1
38 verbose npm  v9.1.1
39 error `store-dir` is not a valid npm option
40 verbose exit 1
```

### Additional information:

 - `node -v` prints: `16.18.1`
 - `npm -v` prints: `9.1.1`
 - Windows, macOS, or Linux?: `linux`

**Comment by zkochan** [comment]
This is bad. Looks like we won't be able to just use npm for managing settings.

**Comment by zkochan** [comment]
It is hard to cooperate with the npm team. They are very slow and not flexible. It will be easier to implement our own `pnpm config` commands.

**Comment by egeorges92** [comment]
I use a hack to solve this issue, using echo to the npmrc file :

`echo 'store-dir=/some/path/.pnpm-store' >> /usr/local/etc/npmrc`

Hope it's help.

**Comment by lvqq** [comment]
>  It will be easier to implement our own pnpm config commands

Will this be part of pnpm v8?

**Comment by sphtd** [comment]
> I would add it sooner under a feature flag.

Hey, any changes maybe?

**Comment by matzeeable** [comment]
See also: https://github.com/npm/cli/issues/5852#issuecomment-1317752977

> No this was very much intentional and npm is going to be moving even further in the direction of not allowing invalid configs. None of these would be looked at by npm or any of its submodules anyways.

**Comment by JunQu** [comment]
same problem
[npm config set will no longer accept deprecated or invalid config options](https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/#:~:text=npm%20config%20set%20will%20no%20longer%20accept%20deprecated%20or%20invalid%20config%20options), I downgrade npm 9 to 8, seems don't work well with npm 9.

**Comment by sorashi** [comment]
This is now very current, because node v19.3.0 (released 5 days ago) ships with npm 9 by default, whereas node v19.2.0 still shipped with npm 8. See https://nodejs.org/en/download/releases/

I had the same problem because of this. I used the `node:current-alpine` docker image (my mistake, should have pinned the version) inside CI with `pnpm config set store-dir` to cache the store over stages. CI jobs failed because of this.

Anyone else having this problem, for now use `node:19.2.0-*`.

**Comment by zkochan** [comment]
For now `npm config get` returns the values of unknown settings. So it is enough if we implement just the `pnpm config set` command.

**Comment by simpros** [comment]
this is still broken with node:latest image in gitlab ci

**Comment by flybywind** [comment]
> I use a hack to solve this issue, using echo to the npmrc file :
> 
> `echo 'store-dir=/some/path/.pnpm-store' >> /usr/local/etc/npmrc`
> 
> Hope it's help.

similiar here, I edit the `/opt/homebrew/lib/node_modules/npm/npmrc` in my Mac to add the new line of the key-value. Seems $HOME/.npmrc also works
