### ISSUE TITLE
Shamefully hoist in one specific package in workspace

### ISSUE THREAD

**Issue by VividLemon** [pnpm/pnpm#5627]
Not sure if this is a bug, or a feature request. Lmk

### Code to reproduce the issue:
Create a monorepo,
Create two packages
I added an .npmrc file to one of the two packages, with shamefully-hoist=true

### Additional information:
This could be a feature request. I'm not certain if packages in a workspace can have their own .npmrc files. Or if there's an alternative to turn this option on elsewhere. I have [this repo](https://github.com/cdmoro/bootstrap-vue-3) that I want to add a nuxt3 app into the ./apps directory, but Nuxt3 requires shamefully-hoisting. I'm not sure how to accomplish this without shamefully hoisting the entire monorepo.

 - `node -v` prints: v18.12.0
 - Windows, macOS, or Linux?: Linux Mint

**Comment by zkochan** [comment]
You can only enable `shamefully-hoist` for the whole workspace. It is impossible to implement partial hoisting because all deps are at `<repo root>/node_modules/.pnpm`, so even if we hoist the deps to a subdir, the packages in `.pnpm` will not find them.

**Comment by VividLemon** [comment]
Disappointing
