### ISSUE TITLE
sqlite3 sometimes installs normally and sometimes cannot be installed. 

### ISSUE THREAD

**Issue by getcurl** [pnpm/pnpm#5641]
pnpm version:7.16.0
 - `node -v` prints:16.17.1
 - Windows, macOS, or Linux?:
linux

JuiceSSH for ssh connection, this software has some wrong characters with the same color as the background, so I copied it to the file. Is there a way to solve this problem? The sqlite3 installation sometimes fails in the middle of the command run, and although rerunning pnpm install--prod will solve it, it's a hassle every time. 

![Screenshot_2022-11-16-16-24-16-622_bin mt plus canary](https://user-images.githubusercontent.com/78637344/202134674-21d0e345-ce9f-495f-890e-00e1bc2ed792.png)

**Comment by v9u** [comment]
Is it solved? Have the same problem

**Comment by getcurl** [comment]
> Is it solved? Have the same problem

No, I don't know why

**Comment by getcurl** [comment]
> Is it solved? Have the same problem

**Comment by getcurl** [comment]
> Is it solved? Have the same problem

No, I don't know why

**Comment by v9u** [comment]
I find the question, your path is too long, use short path ,please

**Comment by v9u** [comment]
> 

You can try my test project(clone to disk root path): https://github.com/v9u/sqlite_test

**Comment by v9u** [comment]
I solved the problem,look: https://github.com/v9u/sqlite_test
