### ISSUE TITLE
Cannot start Next.js project from root directory

### ISSUE THREAD

**Issue by chris-tsongas-vercel** [pnpm/pnpm#5646]
### pnpm version:

7.14.2

### Code to reproduce the issue:

For some reason I can't start a particular Next.js app from the root directory of my monorepo. If I do `pnpm -r run dev` the app starts as expected, however this will start all projects in the monorepo not just one:

```
> redirect@0.1.0 dev /Users/chris/Documents/repos/tests/rewrites-protected-origin/apps/rewrite
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 302 ms (158 modules)
```

however if I try `pnpm -r run dev --filter rewrite` it looks like the `--filter` flag is actually getting passed to Next.js causing an error:

```
> redirect@0.1.0 dev /Users/chris/Documents/repos/tests/rewrites-protected-origin/apps/rewrite
> next dev "--filter" "rewrite"

Unknown or unexpected option: --filter
/Users/chris/Documents/repos/tests/rewrites-protected-origin/apps/rewrite:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  redirect@0.1.0 dev: `next dev "--filter" "rewrite"`
Exit status 1
```

If I try `pnpm --filter rewrite -r run dev` I get an error saying `No projects matched the filters in "/Users/chris/Documents/repos/tests/rewrites-protected-origin"`.

Leaving out the `-r` flag doesn't work, I get an error saying ` ERR_PNPM_NO_SCRIPT  Missing script: dev` apparently because without recursive, pnpm only looks in the root directory, not the project folders for the dev script.

### Expected behavior:

Can start a specific Next.js app from the root folder of a monorepo, so I can use a separate console for each.

### Actual behavior:

Cannot start a specific Next.js app from the root folder of a monorepo, I have to start all apps at once with the `pnpm -r run dev` command which puts output from all of them into the same console, which is unworkable for debugging etc.

### Additional information:

 - `node -v` prints:
 v16.17.0
 - Windows, macOS, or Linux?:
macOS

**Comment by zkochan** [comment]
This should work:

```
pnpm --filter rewrite run dev
```

If it doesn't work then probably the name of the project is not `rewrite`. Or rewrite is not part of the workspace. 

Type this and see if rewrite is printed:

```
pnpm ls -r --depth=-1
```

**Comment by chris-tsongas-vercel** [comment]
Thanks for the reply, that `pnpm ls -r --depth=-1` command helped me figure out that while the app was in the /apps/rewrite folder, the `name` in package.json was wrong! I appreciate the assistance.
