### ISSUE TITLE
pnpm version depending on current directory

### ISSUE THREAD

**Issue by gwhitney** [pnpm/pnpm#5674]
### pnpm version:

7.17.0 **outside** of pnpm clone, 7.10.0 **inside** of pnpm clone

### Code to reproduce the issue:

I have installed node systemwide by compiling and installing the node source tarball. I have executed `sudo corepack enable`. I have cloned the pnpm repository into ~/code/pnpm, and checked out and pulled the `main` branch to be sure I am in sync. Now:
```
code> cd ~
~> which pnpm
/usr/local/bin/pnpm
~> pnpm --version
7.17.0
~> cd code/pnpm
pnpm> which pnpm
/usr/local/bin/pnpm
pnpm> pnpm --version
7.10.0
```

### Expected behavior:

The version of pnpm I see should be independent of the current directory.

### Actual behavior:

I see version 7.10.0 of pnpm in the pnpm clone, versus 7.17.0 in my home directory. This created a problem where I could not properly do a `pnpm install` in my pnpm clone, as it would complain about unmet peer dependencies on `typanion`, until I wen into my home directory and executed `pnpm install --dir code/pnpm`. So the version difference really was blocking proper execution.

### Additional information:

 - `node -v` prints: v19.1.0
 - Windows, macOS, or Linux?: Linux (OpenSUSE Tumbleweed)

**Comment by zkochan** [comment]
It happened because we had this in package.json: 

https://github.com/pnpm/pnpm/blob/043bbeaf3b037adaa8bfb72880e6a6da619fed03/package.json#L66

So it works as expected, Corepack changes the version of pnpm to the one specified in the packageManager field.
