### ISSUE TITLE
Dev: `pd` does not work when current directory is in a different repository

### ISSUE THREAD

**Issue by gwhitney** [pnpm/pnpm#5675]
### pnpm version:

git main, pulled up-to-date to today.

### Code to reproduce the issue:

Execute the first three steps of "Setting up the environment" from CONTRIBUTING.md, then cd into a different project and run the command `pd --version`.

### Expected behavior:

Should execute without error and display the current version of pnpm.

### Actual behavior:

Errors out with:
```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1176:7)
    at requirePackagesManifest (/home/glen/code/pnpm/workspace/find-workspace-packages/lib/index.js:41:67)
    at findWorkspacePackagesNoCheck (/home/glen/code/pnpm/workspace/find-workspace-packages/lib/index.js:24:40)
    at /home/glen/code/pnpm/pnpm/dev/pd.js:12:22 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.1.0
```

### Additional information:

 - `node -v` prints: v19.1.0
 - Windows, macOS, or Linux?: Linux (OpenSUSE Tumbleweed)

Note that changing `process.cwd()` to `__dirname` on line 11 of `pnpm/dev/pd.js` appears to alleviate the problem, but I am reluctant to submit a PR with this change as the recent large changes to pd.js are unclear in nature and purpose to me.

**Comment by HomyeeKing** [comment]
same here
