### ISSUE TITLE
Support a `-c` option in the `pnpm dlx` command

### ISSUE THREAD

**Issue by steveluscher** [pnpm/pnpm#5679]
### Code to reproduce the issue:

```shell
pnpx --package lolcatjs --package cowsay -c \
  'echo "$npm_package_name@$npm_package_version" | cowsay | lolcatjs'
```

### Expected behavior:

Should install packages and call command.

### Actual behavior:

```shell
$ pnpx -p lolcatjs -p cowsay -c \
>            'echo "$npm_package_name@$npm_package_version" | cowsay | lolcatjs'
/home/.local/share/pnpm/store/v3/tmp/dlx-1174922:
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/-p: Not Found - 404

This error happened while installing a direct dependency of /home/.local/share/pnpm/store/v3/tmp/dlx-1174922

-p is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]
```

### Additional information:

 - `node -v` prints: v16.18.1
 - Windows, macOS, or Linux?: Linux

**Comment by steveluscher** [comment]
Notably, npx works using these same options.

**Comment by steveluscher** [comment]
Yeah! That's basically what's at issue here. Would you like me to change the title of this issue to ‘implement -c option in pnpx for parity with npx’?

**Comment by await-ovo** [comment]
should we add the `-shell-mode`(shorthands: `-c`) option to `pnpm dlx` ?, just like [pnpm exec](https://pnpm.io/cli/exec#--shell-mode--c), This should do the same thing as `npm --call`:

```
pd --package cowsay --package lolcatjs -c dlx 'echo "hi" | cowsay | lolcatjs'
```

If this is possible, I would be happy to send a PR :)
