### ISSUE TITLE
when semver is wildcard,  package.json is not updated with exact version

### ISSUE THREAD

**Issue by HomyeeKing** [pnpm/pnpm#5681]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
```json
{
  "typescript": "*"
}
```
after run `pnpm i typescript@latest`, the package.json still, expect to be `"typescript": "4.9.3"`
**Describe the solution you'd like**

when install with specified package, update the exact version repectively, like npm, i.e.
```
npm i typescript 
npm i typescript@latest

# both will update the package.json
{
  "typescript": "4.9.3"
}
```

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

**Comment by zkochan** [comment]
I don't have objections.
