### ISSUE TITLE
Global npm module `npmrc` garbles pnpm output on stdin with warning

### ISSUE THREAD

**Issue by davidaurelio** [pnpm/pnpm#5682]
### pnpm version:
7.17.0

### Code to reproduce the issue:
```sh
npm -g i pnpm npmrc
pnpm list --json # in any package
```

### Expected behavior:

Only JSON on stdout.

### Actual behavior:

The following warning appears on stdout, before any JSON output:

```
 WARN  Issue while reading "~/Library/Application Support/fnm/node-versions/v16.14.2/installation/lib/node_modules/npmrc". EISDIR: illegal operation on a directory, read
```

### Additional information:

There seem to be multiple issues in combination here, and I don’t know what you would consider the best fix:

- `@pnpm/cli-utils` [prints warnings to stdout rather than stderr](https://github.com/pnpm/pnpm/blob/d5496cc3f8fb5696fb4236fb27a956ec93c50eda/cli/cli-utils/src/getConfig.ts#L30) – seems straightforward to change this to `console.warn(…)`, but maybe there were reasons to use `console.log(…)`?

- `@pnpm/npm-conf` [tries to read `node_modules/npm/../npmrc` as file](https://github.com/pnpm/npm-conf/blob/main/index.js#L31), creating a warning if that does not succeed, [but ignoring the `'ENOENT'` case](https://github.com/pnpm/npm-conf/blob/main/lib/conf.js#L41-L44). Since `npmrc` is a valid npm package name (albeit conflicting with config files), maybe it would be appropriate to ignore the `'EISDIR'` case, too.

This is happening in an environment at my company where I have no control whether the callers of my script (which uses `pnpm`) have `npmrc` installed as a global package. Many of them have, because a different project (close to mine) installs it in its setup script.

**Comment by pascalduez** [comment]
Same issue here, `pnpm` tries to read the globally installed [`npmrc` package](https://www.npmjs.com/package/npmrc) as a file.  

```
WARN  Issue while reading "/home/[snip]/.fnm/node-versions/v18.14.0/installation/lib/node_modules/npmrc". 
EISDIR: illegal operation on a directory, read
```

**Comment by estollnitz** [comment]
This particular case has been fixed in https://github.com/pnpm/pnpm/pull/7522, though only for commands using the `--json` flag. It would be great to eliminate this warning for all `pnpm` commands by ignoring the `EISDIR` case when attempting to read the `npmrc` directory as a file.

Additional repro:
```
npm -g i pnpm npmrc
pnpm install # in any package
```

Result: spurious warning.
