### ISSUE TITLE
Add new command `pnpm pkg` to match existing `npm pkg` behavior

### ISSUE THREAD

**Issue by styfle** [pnpm/pnpm#5695]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer, I often want to modify package.json such as adding a build script.

I can do this today with npm:

```
# write
npm pkg set scripts.build="next build"

# read
npm pkg get scripts.build
```

**Describe the solution you'd like**

I would like a new command, `pnpm pkg`, with the same behavior as the existing `npm pkg`.

https://docs.npmjs.com/cli/v9/commands/npm-pkg

**Describe the drawbacks of your solution**

As the npm behavior changes, pnpm would need to maintain the same behavior so there could be some future maintenance burden. Although for this command, it mostly seems additive changes (like support for array syntax).

**Describe alternatives you've considered**

Use npm instead of pnpm. This works unless using corepack which blocks using another package manager for any commands.

**Comment by styfle** [comment]
This is particularly useful when combined with `--filter` in a monorepo.

**Comment by lvqq** [comment]
It's supported in 7.17.1 rencently.

**Comment by styfle** [comment]
Amazing, thanks!

https://github.com/pnpm/pnpm/releases/tag/v7.17.1

**Comment by coltonehrman** [comment]
@styfle @lvqq It seems like the docs are missing any reference to these scripts/APIs.
