### ISSUE TITLE
override.newPref.startsWith is not a function beacuse override.newPref is an object not a string 

### ISSUE THREAD

**Issue by ufec** [pnpm/pnpm#5699]
### pnpm version:
7.17.0
### Code to reproduce the issue:
```json
{
  "pnpm": {
      "overrides": {
        "@nestjs/platform-fastify": {
          "fastify": "4.10.2"
        }
      }
  }
}
```
### Expected behavior:
My project has `@nestjs/platform-fastify` dependency
I want the `fastify` dependency version that `@nestjs/platform-fastify` depends on to be 4.10.2
### Actual behavior:
override.newPref.startsWith is not a function
### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: Windows 11

override.newPref is an object not a string

![image](https://user-images.githubusercontent.com/34962267/204074850-aaa3e7ba-a810-4bb9-8d17-fe553d271a43.png)

@zkochan

**Comment by zkochan** [comment]
This is not how overrides are declared. See docs here: https://pnpm.io/package_json#pnpmoverrides

In you case it will be:

```json
{
  "pnpm": {
      "overrides": {
        "@nestjs/platform-fastify>fastify": "4.10.2"
      }
  }
}
```

**Comment by ufec** [comment]
run successfully.

**Comment by ufec** [comment]
But I found another problem
I have fastify as a dependency in myproject already

I want to use `$dependency name`(example `$fastify`) instead of a specific version。

It can be compatible in two ways, specific or with existing

```json
{
  "pnpm": {
      "overrides": {
        "@nestjs/platform-fastify>fastify": "$fastify"
      }
  }
}
```
but i got an error `isn't supported by any available resolver`

@zkochan

**Comment by ufec** [comment]
before
![unsupport_$name](https://user-images.githubusercontent.com/34962267/204136251-d9e455ff-11b6-4cfa-b4e7-7522499f9bc6.png)

after
![success](https://user-images.githubusercontent.com/34962267/204136304-2a362653-06ed-422e-b738-1d5e68b5af27.png)

install success
![install](https://user-images.githubusercontent.com/34962267/204136311-eb4dfdd9-7ac1-4dd6-8670-171ecde84b10.png)
