### ISSUE TITLE
Support $ in overrides instead of specific version

### ISSUE THREAD

**Issue by ufec** [pnpm/pnpm#5703]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I want to use a new version of the dependency, but it is dependent on another dependency package, I have to overwrite the version that the existing dependency package depends on

**Describe the solution you'd like**

Using the $ method of npm will not make the user feel unfamiliar, he can directly refer to the version of the existing dependent package like a variable

without breaking the original way

**Describe the drawbacks of your solution**

When taking out overrides, iterate through all the keys to see if the value starts with $, if so, find out whether the version of the key exists in the existing dependencies or devDependencies, and replace the reference if it exists, and dependencies take precedence

**Describe alternatives you've considered**

I can’t think of a better alternative at the moment, if possible, I’ll check out npm or yarn

**Comment by ufec** [comment]
@zkochan

**Comment by zkochan** [comment]
How would this work in a workspace? In a workspace you may only describe overrides in the root package.json. And they influence all projects in the workspace. So, in this references you will only be able to use the direct dependencies that are in the root package.json.

**Comment by ufec** [comment]
> How would this work in a workspace? In a workspace you may only describe overrides in the root package.json. And they influence all projects in the workspace. So, in this references you will only be able to use the direct dependencies that are in the root package.json.

Do you mean apply overrides in subprojects?

**Comment by zkochan** [comment]
No, I am just afraid that people will expect it.
