### ISSUE TITLE
react-native-gesture-handler will have been installed many times

### ISSUE THREAD

**Issue by chj-damon** [pnpm/pnpm#5709]
### Expected behavior:
it should only have one `react-native-gesture-handler` instance.
### Actual behavior:
it has many instances which cause error
### Additional information:

 - `node -v` prints:  v16.15.0
 - Windows, macOS, or Linux?: Windows

Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.
> java.lang.Exception:
  [Gesture Handler] Multiple instances of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected

  Conflict between:
  - F:\github\rnxkitDemo\node_modules\.pnpm\registry.npmmirror.com+react-native-gesture-handler@2.8.0_dyuccqjdunorshsxhki7vq4nle\node_modules\react-native-gesture-handler\package.json
  - F:\github\rnxkitDemo\node_modules\.pnpm\registry.npmmirror.com+react-native-redash@18.1.0_vuvvp7mahsegi6zsq4bmrsdkyu\node_modules\react-native-gesture-handler\package.json
  - F:\github\rnxkitDemo\node_modules\react-native-gesture-handler\package.json

**Comment by chj-damon** [comment]
but `react-native` only appears in the node_modules folder, it didn't appear in the .pnpm folder. why?
![image](https://user-images.githubusercontent.com/4902684/204297604-f64ec544-b2c4-4ea9-8d15-78b5c31dd95d.png)

**Comment by zkochan** [comment]
This happens because react-native-gesture-handler has peer dependencies. Try to install the missing peer dependencies. Or use the `auto-install-peers=true` setting.

**Comment by chj-damon** [comment]
well, I tried add `auto-install-peers=true` in `.npmrc` but it doesn't work. there still are more than one `react-native-gesture-handler` been installed in the `.pnpm` folder.
![image](https://user-images.githubusercontent.com/4902684/204422396-527f131e-dc20-4115-ad9e-785730902259.png)

**Comment by zkochan** [comment]
The directory will not be removed from the .pnpm directory. It will be there, just not symlinked. You need to looking in the lock file. 

If you have multiple instances, it means that that package is found at multiple locations in the dependency graph and it has peer dependencies resolved from different versions. You can you overrides to force specific versions of dependencies: https://pnpm.io/package_json#pnpmoverrides

**Comment by kdenz** [comment]
With pnpm, upgrading `react-native-gesture-handler` to `2.9.0` works. It's fixed with this PR https://github.com/software-mansion/react-native-gesture-handler/pull/2334
