### ISSUE TITLE
Exposing API for logging configuration

### ISSUE THREAD

**Issue by andreypopp** [pnpm/pnpm#572]
I understand that I need to use `bole` package if I want to configure logging. That means though that I need to depend on the same version of `bole` as pnpm does. Otherwise if I depend on another incompatible version of `bole` I'll receive another instance of `bole` and thus — logging won't work.

I propose to add an API for logging config — that could just expose `bole` package used by `pnpm`.

Thoughts?

**Comment by zkochan** [comment]
ok, this should be easy. We just have to export `pnpm-logger`

**Comment by andreypopp** [comment]
Is this enough for configuring logging output? I think we might need to expose `bole`, no?

**Comment by zkochan** [comment]
oh, you are right

**Comment by vjpr** [comment]
Is there a way to get plain text logging output? I only see three reporter types (ndjson, default, silent).

I am streaming the logs and the formatting messes up. ndjson is too verbose for me though. I could parse ndjson I guess, but I think there should be something simpler and human-readable that doesn't use fancy logging.

**Comment by zkochan** [comment]
@vjpr we can expose the logs stream via the API. Here's a test where the reporter log are checked https://github.com/pnpm/pnpm/blob/master/test/install/peerDependencies.ts#L27

But seems like you want a custom reporter. You can write one like [this](https://github.com/pnpm/pnpm-default-reporter) and then just run pnpm with your reporter: `pnpm --reporter ndjson | custom-reporter`

**Comment by vjpr** [comment]
When I spawn pnpm from `child-process` and pipe to `process.stdout` I'm seeing the output like this:

```
aNA  waNA  waNA  w  zog 0.0.1
aNA  zaNA  zaNA  z  fsevents 1.0.6
aNA  faNA  faNA  faNA  baNA  baNA  caNA  caNA  caNA  baNA  eaNA  eaNA  gaNA  gaNA  saNA  naNA  naNA  naNA  saNA  saNA  saNA  waNA  saNA  @aNA  aaNA  aaNA  aaNA  aaNA  aaNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  caNA  baNA  baNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  caNA  daNA  daNA  daNA  daNA  daNA  daNA  daNA  daNA  daNA  eaNA  eaNA  eaNA  eaNA  eaNA  faNA  faNA  faNA  faNA  faNA  faNA  faNA  gaNA  gaNA  gaNA  gaNA  gaNA  haNA  haNA  haNA  haNA  iaNA  iaNA  iaNA  iaNA  iaNA  iaNA  iaNA  jaNA  iaNA  iaNA  jaNA  jaNA  jaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  kaNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  laNA  maNA  maNA  laNA  laNA  maNA  maNA  maNA  naNA  naNA  naNA  naNA  naNA  naNA  naNA  naNA  oaNA  oaNA  paNA  paNA  paNA  paNA  paNA  paNA  paNA  paNA  paNA  paNA  paNA  qaNA  qaNA  paNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  saNA  taNA  taNA  taNA  taNA  taNA  taNA  taNA  taNA  taNA  taNA  uaNA  uaNA  uaNA  vaNA  vaNA  waNA  zaNA  faNA  saNA  @aNA  caNA  caNA  baNA  caNA  daNA  faNA  daNA  iaNA  kaNA  caNA  eaNA  laNA  laNA  kaNA  kaNA  naNA  paNA  raNA  raNA  raNA  raNA  saNA  eaNA  eaNA  uaNA  taNA  jaNA  jaNA  faNA  raNA  raNA  raNA  gaNA  daNA  iaNA  kaNA  @aNA  eaNA  caNA  eaNA  faNA  eaNA  laNA  raNA  naNA  paNA  raNA  raNA  raNA  saNA  zaNA  uaNA  daNA  gaNA  @aNA  laNA  naNA  paNA  naNA  raNA  raNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  baNA  taNA  gaNA  maNA  daNA  caNA  kaNA  laNA  paNA  raNA  caNA  daNA  caNA  iaNA  paNA  gaNA  daNA  iaNA  paNA  daNA  saNA  paNA  daNA  faNA  naNA  baNA  raNA  daNA  naNA  baNA  raNA  waNA  waNA  laNA  daNA  daNA  caNA  daNA  raNA  saNA  maNA  maNA  maNA  maNA  maNA  maNA  maNA  maNA  maNA  maNA  daNA  paNA  daNA  daNA  eaNA  daNA  daNA  iaNA  daNA  kaNA  caNA  caNA  kaNA  daNA  caNA  caNA  saNA  kaNA  kaNA  laNA  kaNA  kaNA  kaNA  raNA  maNA  laNA  naNA  eaNA  maNA  faNA  paNA  kaNA  paNA  raNA  paNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  raNA  saNA  saNA  uaNA  taNA  saNA  taNA  saNA  faNA  raNA  raNA  raNA  daNA  daNA  aaNA  kaNA  saNA  aaNA  zaNA  taNA  jaNA  raNA  raNA  baNA  saNA  saNA  paNA  maNA  daNA  maNA  raNA  gaNA  @aNA  baNA  caNA  jaNA  caNA  caNA  gaNA  gaNA  kaNA  saNA  laNA  kaNA  kaNA  kaNA  paNA  daNA  paNA  raNA  paNA  raNA  raNA  iaNA  saNA  taNA  waNA  taNA  caNA  laNA  gaNA  taNA  baNA  caNA  aaNA  laNA  laNA  gaNA  laNA  laNA  maNA  @aNA  maNA  baNA  gaNA  paNA  naNA  raNA  taNA  naNA  waNA  maNA  baNA  waNA  raNA  caNA  baNA  saNA  live-frontend 0.0.3                                       linking 0.0.3 ↓ aNB
```

Any ideas?

**Comment by vjpr** [comment]
Ok so the problem here is that you lose tty support when using spawn with `{stdio: 'pipe'}`, instead of `inherit`.

See https://github.com/sindresorhus/execa/issues/25

**Comment by zkochan** [comment]
So you managed to make it work?

**Comment by vjpr** [comment]
If you are reading/piping the logging output from pnpm, such as in CI logging, configuration management tool (ansible/chef), then you will see the output I posted which is quite ugly.

The alternatives are to use `ndjson` which is way too verbose, or `silent` which shows no progress.

I think we should ship something that works with CI tools / provisioning tools which does not use terminal control codes. Name it `--reporter plain/simple/ci/etc.`, and which shows the same information as the default reporter does.

It might also be useful to control the verbosity of the ndjson logger to just show info - as this is easy to parse.

**Comment by zkochan** [comment]
The pnpm installation engine was moved to a separate package called [supi](https://github.com/pnpm/supi) and it will be able to receive a logs listener via the `options.reporter` argument.

The programmatic API is experimental for now, but the different log types and names will be standardized till v1 of the pnpm programmatic API (or engine, whatever we call it)

**Comment by aparajita** [comment]
@zkochan \@pnpm/logger is a separate package now, can this be closed?
