### ISSUE TITLE
Should not update workspace in `package.json` when using the `pnpm up` command

### ISSUE THREAD

**Issue by shirotech** [pnpm/pnpm#5726]
### pnpm version:
7.17.1

### Code to reproduce the issue:
```bash
pnpm -r up
```

### Expected behavior:
`workspace: ^` in `package.json` is untouched

### Actual behavior:
`workspace: ^` in `package.json` has been updated to the latest version

### Additional information:
It is ideal for keeping `workspace: ^` when running the `pnpm up` command because it makes things more manageable and does not have to update the version every time there is a new version.

**Comment by await-ovo** [comment]
duplicate with https://github.com/pnpm/pnpm/issues/5317
