### ISSUE TITLE
MODULE_NOT_FOUND Error

### ISSUE THREAD

**Issue by nikitavoloboev** [pnpm/pnpm#5729]
### pnpm version:

Can't get as CLI crashes but I think it was nearly latest.

### Code to reproduce the issue:

`pnpm --version` or any command.

### Expected behavior:

Should be able to use `pnpm`. After upgrading get below every time.

### Actual behavior:

Crashes with:

```
~/src/extensions/raycast/opengpt
❯ pnpm i
node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '/opt/homebrew/Cellar/node/18.0.0/pnpm-global/5/node_modules/pnpm/bin/pnpm.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.9.0
```

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:
 
macOS

**Comment by zkochan** [comment]
What command have you used to install pnpm. And what command have you used to update it?

**Comment by nikitavoloboev** [comment]
It started working again.

I used `pnpm add -g pnpm` to update. And believe used `npm install -g pnpm` to install it originally.

**Comment by navid-asgharzadeh** [comment]
**Installing pnpm on macOS**
1. Install pnpm using curl:

` curl -fsSL https://get.pnpm.io/install.sh | sh -`

2. Add pnpm to your path:

After running the script, you'll need to add pnpm to your PATH. This usually involves adding the following lines to your .bashrc, .zshrc, or .profile file, depending on your shell.

    export PATH="$HOME/.local/share/pnpm:$PATH"
    export PNPM_HOME="$HOME/.local/share/pnpm"

3. Then reload your shell configuration:

```
source ~/.bashrc
or
source ~/.zshrc
```

4. Verify pnpm Installation:

`pnpm --version`
