### ISSUE TITLE
pnpm license ls ENOENT: no such file or directory

### ISSUE THREAD

**Issue by LucaColonnello** [pnpm/pnpm#5737]
### Code to reproduce the issue:

`pnpm license ls`

### Expected behavior:
Lists dependencies licenses.

### Actual behavior:
![Screenshot 2022-12-02 at 16 40 25](https://user-images.githubusercontent.com/536973/205342553-54861064-d6ca-49aa-8ba4-8ed83cbd180f.png)

It seems like the `pnpm license ls` command is trying to open a file that is saved with a `-exec` suffix in the v3 store.
As in the picture, the file as requested by the command, does not exist, but looking in the folder, I noticed it is a license file and it does exist under the same has, just with the `-exec` suffix.

### Additional information:

 - `node -v` prints: v16.17.1
 - Windows, macOS, or Linux?: macOS
 - Happening in a codebase with workspaces, a lerna monorepo
 - `.npmrc`:
 ```
 scripts-prepend-node-path=true
auto-install-peers=true
link-workspace-packages=false
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
public-hoist-pattern[]=*babel*
public-hoist-pattern[]=*storybook*
 ```

**Comment by weyert** [comment]
Thank you for reporting this, could you tell me which package this is?

**Comment by LucaColonnello** [comment]
Hey @weyert !
Not sure how to verify that as it's in a big project, anything you could recommend to test this hash and see what package it relates to?

**Comment by weyert** [comment]
Yeah, if I understand this all correctly that directory should have a file with the contents of the `package.json`. It's a bit of a pain. Typically it would also have a file ending with `-index.json` that would lists all the files but you can't easily map the integrity to the file on disk.

I am curious why the file seems to suggest it has exec permissions though, pretty odd 🤔

**Comment by LucaColonnello** [comment]
Aaah right! I can get that for you in the morning! Yeaah that's odd! Maybe a package with a wrong bin section?

**Comment by weyert** [comment]
Thank you for trying it out! Helps me making the command more stable I only tested it against mock projects and my 'work-in-progress' monorepo at work.

My current assumption is that this line is problematic:
https://github.com/pnpm/pnpm/blob/main/reviewing/license-scanner/src/getPkgInfo.ts#L154

If you happen to find that `-index.json` file can you check if it has ` mode`-property for the LICENSE file?

**Comment by LucaColonnello** [comment]
So I'm looking at it now but the folder has multiple `-index.json` 🥲?!!!

**Comment by LucaColonnello** [comment]
Could this be a casing problem?

I found this:

```json
{"name":"globby","version":"13.1.2","files":{"license":{"checkedAt":1665411996849,"integrity":"sha512-0fM2/ycrxrltyaBKfQ748Ck23VlPUUBgNAR47ldf4B1V/HoXTfWBSk+vcshGKwEpmOynu4mOP5o+hyBfuRNa8g==","mode":420,"size":1117},"utilities.js":{"checkedAt":1665411996850,"integrity":"sha512-6HLJFb3TZ7JYYzuxbyUGUeieSyz5fGNwzt83CjvfWf+0H9OzNPFGX4QsS29YtNfUWTe/2WQ+t3Z+83nMjO+0ww==","mode":420,"size":462},"index.js":{"checkedAt":1665411996850,"integrity":"sha512-w/MLsN6dYLB/ThD4/t9fAT0ibP918Qrb/ereJkiZ4YSTLyDvt5lqRB1cA+Nn9Y21TdqdL/T4o7x+NJROnmfE1Q==","mode":420,"size":5953},"ignore.js":{"checkedAt":1665411996850,"integrity":"sha512-5Z4tVBTws5j0nKGP+QO66yZ+P9E9BDT3H7Afsku2JaHtp410jV/OhGTvaWTWpKxUn0bFfHQWQ+D1zVdLmFIOPA==","mode":420,"size":2550},"package.json":{"checkedAt":1665411996850,"integrity":"sha512-fYf0MKM15ZsN79y4oLeo247ennPClda6e3AdeWdAtqzaz7WZZC+SVMOx/S0vpaQAvgGRz+cXZLMKUIabs9i3aA==","mode":420,"size":1601},"readme.md":{"checkedAt":1665411996850,"integrity":"sha512-221hFSvzO5lrZvg97WA2Trs2EAp0ZUsKSvDS13Om31vUXmSlm2Rq4oxVa59MHg2sKeEAiPdPZDv936X+qKDGWQ==","mode":420,"size":6056},"index.d.ts":{"checkedAt":1665411996850,"integrity":"sha512-cVRXwcYqeayjOhbUiHbMYfbxtwCfE9qHg2kdmr0ImWE12+ZuaEi7qeG+SEs/FTyG0Odr3XJpGJ4FLupLfleztQ==","mode":420,"size":7059}}}
```

As you can see, the license file name is lowercase!

**Comment by LucaColonnello** [comment]
Oh I found it!!!
https://github.com/nfroidure/svgicons2svgfont/blob/a612e682a19bbddcadeff194a7dc827e765e6df1/LICENCE

**Comment by weyert** [comment]
Thank you @LucaColonnello. I  have tried to run it locally but haven't had much luck yet. 
I will try again tonight. I will push a repro and see if you can reproduce it

**Comment by LucaColonnello** [comment]
Thank you for working on it so promptly!!!

I'm unfortunately unable to provide more insights as I don't know why this would happen, like why would a license be installed as an executable 😫🤔

**Comment by weyert** [comment]
```
Weyerts-MacBook-Pro # pnpm licenses list                                                                             [~/tijdelijk/license-proto/pnpm-licenses-bug001]
 ENOENT  ENOENT: no such file or directory, open '/Users/weyert/Library/pnpm/store/v3/files/2c/26cd1aef501f1e3c35ae03185dae6a56dda866c2ed269529d4d38d527add112f718dfbe80b291fe829ae5ddcc4c6141d16cf02597661d5d43c2f063afcb26a'
```

This looks like a similar error, right! Before I was not using the same package version

**Comment by LucaColonnello** [comment]
That's exactly it!!!

**Comment by weyert** [comment]
I think the PR I  made earlier should solve this problem.

**Comment by LucaColonnello** [comment]
Is there a way I could test it on my side too?

**Comment by LucaColonnello** [comment]
I applied your patch to my local pnpm version and it works perfectly!
Thank you @weyert ! I can confirm the code in your PR fixes the issue!

**Comment by weyert** [comment]
@LucaColonnello  Awesome happy to hear that and thank you for taking the time to patch your local copy 
I would need to write a unit test for this somehow 🤔

**Comment by weyert** [comment]
I think I will  just try to install this particular package and make sure it returns the expected list. I hope to do tonight or tomorrow . I am a bit busy with work stuff (memory leak 😢 )

**Comment by LucaColonnello** [comment]
Oh super unlucky, memory leaks are always painful :D

I'm not sure how tests are written in pnpm, but yeah using that package as an example is probably the best way for now, but it'd be good to know what kicks that file mode to be on the exec side for a license file.

**Comment by zkochan** [comment]
If you need a package to an e2e test, you can add the package to this repo: https://github.com/pnpm/registry-mock

**Comment by weyert** [comment]
I have added a end-to-end test have that is suffice for now

**Comment by zkochan** [comment]
I this fixed in the latest version?

**Comment by LucaColonnello** [comment]
Hey @zkochan !
I just tested it now on v7.18.2 and it seems to have been fixed!

Amazing work and thank you for your help!

**Comment by weyert** [comment]
Happy to hear it resolved the issue for you :))
