### ISSUE TITLE
rimraf-then not found on CI Buildkite

### ISSUE THREAD

**Issue by Akkuma** [pnpm/pnpm#577]
### pnpm version: 
v0.48.1

### Code to reproduce the issue:
This is hard to "reproduce" in that I cannot mimic the problem locally, OS X, and it only happens on CI. I use `pnpm`'s api for my library that we use for building "child" extensions (you can think of it as a very specialized `lerna`) from the main extension.

### Expected behavior:
`rimraf-then` is found

### Actual behavior:
Error: Cannot find module 'rimraf-then' when trying to use the `pnpm` api the workaround being to directly include it in the main package devDeps.

### Additional information:

 - `node -v` prints: v4.7.*
 - Windows, OS X, or Linux?: Linux

Is it possible the `/lib/node_modules` is the issue? As a side issue I couldn't use `npm ls rimraf-then` to find the package that required it, which doesn't seem like it is intended either.

**Comment by zkochan** [comment]
Weird, I downloaded that version of pnpm and `node_modules` seems to be correct. Also there are no any files outside of the `lib` folder.

I use node 6 and npm 3 to cache the node_modules folder and publish pnpm

**Comment by iamstarkov** [comment]
do we have `pnpm-debug.log`

**Comment by Akkuma** [comment]
The error is not in pnpm @iamstarkov . The error is with node loading `pnpm`, specifically resolving the `rimraf-then` dependency. It is the only package I see that uses `rimraf-then` after manually using npmjs.com to find dependents on it, since `npm ls rimraf-then` doesn't work.

@zkochan So what we are doing is tarring up the node_modules for the CI and downloading it for other steps. I've downloaded it and `rimraf-then` can be found in it. I was more so saying I believe the `lib/node_modules` is creating issues, since I cannot even `npm ls rimraf-then`, which should show.

**Comment by zkochan** [comment]
I don't know why `lib/node_modules` would cause issues. bower uses the same approach.

@Akkuma, I published as @zkochan/pnpm the 0.48.1 with regular node_modules in the root of the package, so you can try it and see if it helps.

**Comment by zkochan** [comment]
@Akkuma is it still happening with pnpm v1?

We had issues once because there was a dev dependency used in production code. To make it impossible for production code to access dev dependencies, pnpm now installs dependencies for tests to `test/node_modules`.

**Comment by zkochan** [comment]
Please open a new issue if this happens again.
