### ISSUE TITLE
PNPM ignores github dependencies and installs latest

### ISSUE THREAD

**Issue by gydence** [pnpm/pnpm#5774]
### pnpm version:
7.18.1

### Code to reproduce the issue:
package.json:
```
{
  "private": true,
  "dependencies": {
    "aframe": "git://github.com/aframevr/aframe#54022b80c60b12dc755f4f4a71a779b410dd23d0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

running `npm install` and then `pnpm install` reports:
```
dependencies:
+ aframe 1.3.0
```

### Expected behavior:
pnpm should use the requested commit

### Actual behavior:
pnpm seems to use the latest version of the package

### Additional information:
Windows.  I'm new to npm/pnpm so let me know if I'm doing something wrong.  Thank you!

**Comment by await-ovo** [comment]
Hey, I tried `pnpm install` with the `package.json` you provided,  it looks like no problem

You can check  `node_modules/aframe`, if it is downloaded from npm, , there should only be four directories: dist, docs, src, vendors. (which are specified in [files field](https://github.com/aframevr/aframe/blob/master/package.json#L31))

**Comment by await-ovo** [comment]
> ah! `node_modules/aframe` is more than four directories, it's the entire github repo. so that seems to be working correctly. maybe it's just a reporting issue for the output? the commit I checked out is more recent than 1.3.0, so it's just printing the last tag instead of a meaningful message about the commit?

I'm not sure if the print is wrong or not, I guess it's based on the version of the resolved `package.json` , the version of commit [54022b80c60b12dc755f4f4a71a779b410dd23d0](https://github.com/aframevr/aframe/blob/54022b80c60b12dc755f4f4a71a779b410dd23d0/package.json) is exactly 1.3.0, if you try this  commit ([04bfa6c548c6a47d6fe93fbd1d4ab237eb43c6b7](https://github.com/aframevr/aframe/blob/04bfa6c548c6a47d6fe93fbd1d4ab237eb43c6b7/package.json)), the version printed should be 1.2.0 ~

**Comment by gydence** [comment]
ahhhh gotcha!  thank you for the explanation ❤️
