### ISSUE TITLE
Company-scoped package dependencies are not installed

### ISSUE THREAD

**Issue by sergio-ferreira-jscrambler** [pnpm/pnpm#5780]
### pnpm version:

7.18.1

### Code to reproduce the issue:

We're migrating to a monorepo, and we're evaluating pnpm for dependency installation. In this monorepo we install a company-shared tsconfig file. 

On the root of the monorepo we this dependency listed:

`
"dependencies": {
    "@jscrambler/tsconfig": "1.2.0"
}
`

In @jscrambler/tsconfig package we have the following dependency:

`
"@tsconfig/node18":  "`^1.0.1`"
`

On the root of the monorepo we have a "tsconfig.json" file which extends "@jscrambler/tsconfig/tsconfig.node18.json" and resolves correctly to our package. However, "@jscrambler/tsconfig" also has a tsconfig file which extends "@tsconfig/node18/tsconfig.json", and this dependency is not resolved.

Looking at `@jscrambler/tsconfig` folder package, there are no `node_modules` folder, so it looks like no dependency was installed for this package. However, it has a package.json with all the dependencies listed correctly.

### Additional information:

Installing "@tsconfig/node18":  "`^1.0.1`" at the root of the monorepo solves this issue, since the package is forcibly installed, but it's not scalable, since we would have to remember to install all dependencies of this package at the monorepo.

I've also tried to move "@tsconfig/node18":  "`^1.0.1`" from devDependencies to dependencies, but that doesn't solve it.

 - `node -v` prints: v18.12.1
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
`node_modules/@jscrambler/tsconfig` is a symlink to `node_modules/.pnpm/@jscrambler+tsconfig@1.2.0/node_modules/@jscrambler/tsconfig`

The dependencies of `@jscrambler/tsconfig` are at `node_modules/.pnpm/@jscrambler+tsconfig@1.2.0/node_modules`

If you want a "traditional" node_modules, use. the `node-linker=hoisted` setting.
