### ISSUE TITLE
shell-emulator requires quoting args containing asterisk

### ISSUE THREAD

**Issue by stefanprobst** [pnpm/pnpm#5781]
### Code to reproduce the issue:

```
# .npmrc
shell-emulator=true
```

```json
{
  "private": true,
  "scripts": {
    "test:pnpm:check": "echo OK",
    "test": "run-s test:*:check"
  },
  "devDependencies": {
    "npm-run-all": "^4.1.5"
  }
}
```

### Expected behavior:

running `pnpm run test` should print "OK"

### Actual behavior:

script fails. note that this works fine with `shell-emulator=false`. also works fine when adding quotes:

```diff
-    "test": "run-s test:*:check"
+    "test": "run-s 'test:*:check'"
```

### Additional information:

 - `node -v` prints: 18.12.0
 - Windows, macOS, or Linux?: linux

**Comment by zkochan** [comment]
The shell emulator is maintained by the Yarn team. So look for similar issues in [this repo](https://github.com/yarnpkg/berry) and file and issue if you think it is a bug.
