### ISSUE TITLE
exports.contextLogger = (0, logger_1.logger)('context');

### ISSUE THREAD

**Issue by tjx666** [pnpm/pnpm#5788]
`"@pnpm/find-workspace-packages": "5.0.14"`

```typescript
import { resolve } from 'node:path';
import { findWorkspacePackages } from '@pnpm/find-workspace-packages';

(async function () {
    const workspaceRoot = resolve(__dirname, '../..');
    const projects = await findWorkspacePackages(workspaceRoot);
    const pkgs = projects.map((project) => project.manifest.name!);
    console.log(JSON.stringify(pkgs, null, 4));
})();
```

![image](https://user-images.githubusercontent.com/41773861/207268849-60863b91-e1fa-4615-9fa6-36e0238abd40.png)

**Comment by zkochan** [comment]
It is not a bug. `@pnpm/find-workspace-packages` has a required peer dependency: `@pnpm/logger`. If you want to use `@pnpm/find-workspace-packages`, you should also install `@pnpm/logger`.
