### ISSUE TITLE
Consolidate `.pnpm-store` and `.pnpm-cache`

### ISSUE THREAD

**Issue by andreypopp** [pnpm/pnpm#580]
I think it's better to have a single dir in a `$HOME` directory. What if we do:

* store — `~/.pnpm/packages`
* cache — `~/.pnpm/cache`

And make both configurable via single `storeDir: string`. Thoughts?

**Comment by zkochan** [comment]
I wonder whether we need a cache dir at all. We use it for caching HTTP requests. Most of the HTTP requests are for resolution, for getting the package registry document. I think we can save that document in the store, in the same directory where the different versions of the package are.

```
is-positive/
├─ 1.0.0/
├─ 1.1.0/
└─ meta.json
```

I think this would also allow to implement what @iamstarkov suggested in #568

>Semver Aware Caching — invalidate cache in semver aware way

**Comment by andreypopp** [comment]
>  I think we can save that document in the store, in the same directory where the different versions of the package are

Agree 👍

**Comment by andreypopp** [comment]
> Edit: of course we'll have to re-download the document from time to time

Also It would be good to have an "offline" mode where pnpm does't try to do network connectivity at all or only when meta/packages aren't available in the store. I wonder if it should be the default mode and we should do a complete re-resolve when we run `pnpm upgrade`?

**Comment by zkochan** [comment]
Related: #508

Not sure about making it the default behavior but I like the idea a lot
