### ISSUE TITLE
0.51.1 regressed on CRA based apps

### ISSUE THREAD

**Issue by andreypopp** [pnpm/pnpm#581]
### Code to reproduce the issue:

```
% create-react-app ./test-app
% cd test-app
% rm -rf node_modules # rm packages installed with npm/yarn
% pnpm install
% npm run start
```
### Expected behavior:

It works.

### Actual behavior:

It doesn't work: webpack cannot resolve loaders.

### Additional information:

 - `node -v` prints: v6.9.1
 - Windows, OS X, or Linux?: macOS Sierra

**Comment by andreypopp** [comment]
Also I see that `node_modules` disappeared from the package directories in `node_modules`. For example `node_modules/react-scripts` won't have its own `node_modules` dir. That makes hacking on dep's sources less convenient — to change some lines of code I need to reach to `.resolutions` directory.

**Comment by zkochan** [comment]
TBH, hacking with deps is a pretty dangerous idea with the shared store. You'll change the package for other projects that use it on that PC. I think we have to add some `pnpm verify` command, that will re-check the checksums of packages in the store.

**Comment by zkochan** [comment]
I might know what the issue is. Because of the node_module structure change, the `.bin` location has changed. Now it is `../node_modules/.bin` instead of `node_modules/.bin`. I think we can move the bin files back to their old location. They won't cause circular symlinks

**Comment by zkochan** [comment]
Let me know you will start to work on it, otherwise I'll try to fix it later today.

**Comment by zkochan** [comment]
Seems like fixing the `.bin` position did not solve this issue

**Comment by andreypopp** [comment]
Likely will be solved by https://github.com/facebookincubator/create-react-app/pull/1291

**Comment by zkochan** [comment]
This is solved with the latest pnpm and CRA.

I just tried it and it works!
