### ISSUE TITLE
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with EACCES when node-linker=hoisted

### ISSUE THREAD

**Issue by qannoufoualid** [pnpm/pnpm#5822]
We are migrating from yarn to pnpm but we encounter permission problems when we set `node-linker=hoisted`.
one of the node_modules script failing under permission issue is husky: `ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with EACCES: husky install`

### pnpm version:
7.17.0
### Code to reproduce the issue:
https://github.com/qannoufoualid/pnpm-eacces-node-linker-issue
`docker build` . for the first dockerfile
`docker build -f DockerfileIsolatedNodeLinker .` for the second one
### Expected behavior:
node_modules scripts should execute normally
### Actual behavior:
script execution fails because of permission problems
 - `node -v` prints: 16.19.0
 - Windows, macOS, or Linux?: linux

**Comment by qannoufoualid** [comment]
I think we don't execute the chmod if node-linker=hoisted. maybe i'm wrong
![image](https://user-images.githubusercontent.com/11137586/209169189-9ac2add9-732d-4d89-ad4c-72ec49ac5310.png)

**Comment by qannoufoualid** [comment]
Hello, anyone to answer this issue please? 😔

**Comment by charlie-maloney** [comment]
Hi @qannoufoualid -- I'm having the same issue. Did you end up solving it?

**Comment by await-ovo** [comment]
Looks like the same problem with #5890 
![image](https://user-images.githubusercontent.com/41503212/211713316-75fb04a0-f6da-43bc-b777-3d02b1a50e89.png)
