### ISSUE TITLE
An error occurred while uploading (7.19.0)

### ISSUE THREAD

**Issue by shirotech** [pnpm/pnpm#5823]
### pnpm version:
7.19.0
### Code to reproduce the issue:
pnpm install
### Expected behavior:
install without issues
### Actual behavior:
pnpm complains about certain random packages e.g. `core-js` "An error occurred while uploading" then hangs

After reverting back to and older version, install works fine.

**Comment by zkochan** [comment]
Could you share repo that reproduces the issue? Do you use `node-linker=hoisted`?

**Comment by shirotech** [comment]
> Could you share repo that reproduces the issue? Do you use `node-linker=hoisted`?

Hi, yes I am using that option, here is complete list:
```
git-checks=false
node-linker=hoisted
include-workspace-root=true
link-workspace-packages=deep
install-links=true
ignore-workspace-root-check=true
package-import-method=hardlink
strict-peer-dependencies=false
```

It seems like you know what the cause is, otherwise I'll need some time to pinpoint what is causing the issue for the repro. Thank you.

**Comment by zkochan** [comment]
I assume that this was caused by this change: https://github.com/pnpm/pnpm/pull/5814

But I don't know how to reproduce the issue.

**Comment by chungweileong94** [comment]
I'm getting the same error with the recent update. I'm suspecting that it might be caused by running `pnpm i` on an external drive. Will double-check that to see if it's true.

**Comment by chungweileong94** [comment]
> I'm getting the same error with the recent update. I'm suspecting that it might be caused by running `pnpm i` on an external drive. Will double-check that to see if it's true.

Apparently, it was not the case, however, the problem start to happen if one/more of the packages are having `postinstall` script.

**Comment by chungweileong94** [comment]
Just realized it happens on Vercel deployment as well😕
![image](https://user-images.githubusercontent.com/15154097/211319501-7f9fdc0a-b881-4507-ae02-dbd1f342a1ab.png)

**Comment by shirotech** [comment]
@zkochan I saw the fix, and it seems to have removed the error/warning, but symptoms remains, now the postinstall still hangs as before:

```log
node_modules/core-js: Running postinstall script, done in 88ms
node_modules/pngquant-bin: Running postinstall script, done in 525ms
Progress: resolved 994, reused 973, downloaded 0, added 3, done


^C
```

had to ctrl+c, CPU was full throttled and laptop was overheating, I assume there is infinite loop somewhere.

**Comment by zkochan** [comment]
Try to add `core-js` to [neverBuiltDependencies](https://pnpm.io/package_json#pnpmneverbuiltdependencies).
