### ISSUE TITLE
pnpm react native

### ISSUE THREAD

**Issue by ramiljs** [pnpm/pnpm#5830]
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

![1 1](https://user-images.githubusercontent.com/89657343/209359826-1764fd84-0e43-4d2c-b21b-813eb3228eb3.PNG)

![1 2](https://user-images.githubusercontent.com/89657343/209359859-e82530bd-8b03-4f87-a051-399bc740d8bf.PNG)

![1 3](https://user-images.githubusercontent.com/89657343/209359874-708232a5-937b-41ab-9f29-894888e9bc00.PNG)

**Comment by zkochan** [comment]
Use the `node-linker=hoisted` setting

https://pnpm.io/npmrc#node-linker
