### ISSUE TITLE
Vague error when installing global package after pnpm version update

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#584]
### pnpm version:

0.51.1

### Code to reproduce the issue:

```
npm i -g pnpm@latest
pnpm i -g foo
npm i -g pnpm@next
pnpm i -g foo
```

### Expected behavior:

Should show a more informative error message. E.g. When I am installing globally, it should give me the path of the global node_modules to remove.

This should also be a cli command.

And I am also unsure if I need to wipe out the entire global pnpm node_modules. I'm not sue if I should remove `pnpm root -g` or something else.

I think it should be `$(pnpm bin -g)/pnpm-global/node_modules` perhaps?

### Actual behavior:

```
ERROR The node_modules structure was changed.
Remove it and run pnpm again.
Related PR: https://github.com/pnpm/pnpm/pull/576
TIPS: you can run `rm -rf node_modules` or install with the --force parameter
```

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
I agree, the logs are bad. You can try `pnpm i -g --force foo`. It should remove the old node_modules and install your global package
