### ISSUE TITLE
pnpm config set registry --location=global fails in version 7.20.0

### ISSUE THREAD

**Issue by morsh** [pnpm/pnpm#5841]
### pnpm version:
7.20.0

### Code to reproduce the issue:
`pnpm config set registry https://pkgs.dev.azure.com/dynamicscrm/OneCRM/_packaging/ci-common-ui/npm/registry/ --location=global`

### Expected behavior:
Works

### Actual behavior:
Unknown option: 'location'

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
We can fix this. But as an alternative, you can use `--global` instead of `--location=global`.

**Comment by morsh** [comment]
This was mainly a concern for us since it broke our build pipeline, `--global` fixes it, but I can't find any reference to any of the options in the documentation

**Comment by zkochan** [comment]
In the past versions pnpm config was just passing through to npm. In v7.20 we added our own implementation. That is why it broke

**Comment by morsh** [comment]
So when I use `--global` it passes now, but it fails on:
```
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

I'll try running pnpm setup - but again this is missing in the docs

**Comment by zkochan** [comment]
OK, this one is also a bug.
