### ISSUE TITLE
pnpm i --fix-lockfile  ERR_PNPM_NO_MATCHING_VERSION 

### ISSUE THREAD

**Issue by candy-Tong** [pnpm/pnpm#5878]
### pnpm version:
7.22.0
### Code to reproduce the issue:
I run pnpm i --fix-lockfile in my code. That is a workspace.

### Expected behavior:
install successfully

### Actual behavior:
![image](https://user-images.githubusercontent.com/20377280/210484362-b5604591-c057-471d-8399-bd3db907d9e2.png)

![image](https://user-images.githubusercontent.com/20377280/210484831-c63f8935-0944-4648-9764-1d0d53085e9e.png)

Is that pnpm doesn't get the correct version with `4.0.4_uakuilq6iygkg5ll5cv37w4i7m`?

Here is my lock file
[pnpm-lock.yaml.txt](https://github.com/pnpm/pnpm/files/10341422/pnpm-lock.yaml.txt)

### Additional information:

 - `node -v` prints: v16.13.2
 - Windows, macOS, or Linux?: linux

**Comment by candy-Tong** [comment]
I delete the following code and change `4.0.4_uakuilq6iygkg5ll5cv37w4i7m` to `4.0.4`.  I run 
pnpm i --fix-lockfile again and it doesn't has any error.
![image](https://user-images.githubusercontent.com/20377280/210499672-d84c1174-75ba-4151-80be-792c4a1bd72b.png)

Can pnpm automatically reuse some package?

**Comment by bvanjoi** [comment]
Could you provide a minimal repo to reproduce

**Comment by candy-Tong** [comment]
https://github.com/candy-Tong/test-pnpm-fix-lock

```
pnpm i
pnpm run bootstrap
```
