### ISSUE TITLE
Enable --no-lockfile globally

### ISSUE THREAD

**Issue by janosh** [pnpm/pnpm#5893]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

I dislike how lock files make the line count change on PRs updating deps meaningless. 

**Describe the solution you'd like**

Add env variable to enable the `--no-lockfile` flag on `pnpm install` globally.

```sh
export PNPM_NO_LOCKILE=true
```

**Describe the drawbacks of your solution**

Very niche requirement that goes against current doctrine. Perhaps it's due to relatively small ESM-only dep trees on my projects but I haven't found any but-it-works-on-my-machine type of errors that were the reason for bringing lock files into existence. I've installed multiple projects without lock files on multiple machines without grief.

**Describe alternatives you've considered**

Shut up and take the clarity hit on git history.

**Comment by zkochan** [comment]
This should work:

```
pnpm config --global set lockfile false
```

**Comment by janosh** [comment]
Ah my bad. Somehow I didn't find this in the docs.

https://pnpm.io/npmrc#lockfile-settings
