### ISSUE TITLE
child dep will reuse their parent dep, not it's supposed to be

### ISSUE THREAD

**Issue by coolperbs** [pnpm/pnpm#5896]
HI

I met a problem about pnpm and yarn 

there a two packages:

the first package.json, use lodash will match 3.10.1
{
  "name": "@pt/lodash3",
  "dependencies": {
    "lodash": "^3.0.0"
  },
}

the second package.json, will use first package, and use lodash with exact version
{
  "name": "pkgc-pnpm",
  "dependencies": {
    "@pt/lodash3": "^1.0.0",
    "lodash": "3.2.0"
  }
}

in yarn,  second package will install both 3.10.1 and 3.2.0
![image](https://user-images.githubusercontent.com/8486549/211202083-d7e397ea-ecec-46c2-b546-4ef4973e6815.png)

in pnpm, second package will only install 3.10.2 
![image](https://user-images.githubusercontent.com/8486549/211202043-76b53553-84b0-47ba-8e3b-2d1b7ef1f381.png)

I think yarn's result is correct, I just want to know why pnpm is not same as yarn .

This zip can check my problem
[github_issue.zip](https://github.com/pnpm/pnpm/files/10368656/github_issue.zip)

### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by bvanjoi** [comment]
maybe it caused by the `pnpm-lockfile.yaml`, and `rm pnpm-lock.yaml && pnpm i` might fix this

**Comment by coolperbs** [comment]
Err.. , there are no pnpm-lockfile.yaml or pnpm-lock.yaml in my example ，you can test with this zip

**Comment by bvanjoi** [comment]
> Err.. , there are no pnpm-lockfile.yaml or pnpm-lock.yaml in my example ，you can test with this zip [github_issue.zip](https://github.com/pnpm/pnpm/files/10371285/github_issue.zip)

Could you describe the specific steps? Because `@pt/lodash3` is not published in npm, it will throw 404 error:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/30187863/211261532-328be76e-802e-4320-adc8-ec3d37c8096f.png">

**Comment by coolperbs** [comment]
Sorry, I forget I put this pkg to private registry, please use this zip

[github_issue 2.zip](https://github.com/pnpm/pnpm/files/10372693/github_issue.2.zip)




The yarn case: you will see two lodash version installed

cd pkgc-pnpm 
yarn
yarn why lodash 

---------


The pnpm case: you will see only one lodash version installed
cd pkgc-pnpm 
pnpm install
pnpm why lodash

**Comment by bvanjoi** [comment]
I debugged the problem and found that it was caused by [preferredVersions](https://github.com/pnpm/pnpm/blob/main/pkg-manager/core/src/install/index.ts#L717) (this may pnpm on purpose), `lodash: 3.2.0` in package.json forces `lodash: ^3.0.0` in `test_lodash3` to select version 3.2.0. If you don't want to modify the contents of dependencies in `test_lodash3`, you can create a `.pnpmfile.cjs` file in the root directory, the content of which is as follows:

```js
function readPackage(pkg) {
   if (pkg.name === "test_lodash3") {
     pkg.dependencies = {
       ...pkg. dependencies,
       lodash: "^3.10.0"
     }
   }
   console.log(pkg)
   return pkg
}

module.exports = {
   hooks: {
     readPackage
   }}
```

Then execute `pnpm i --fix-lockfile`, you can solve this problem

**Comment by coolperbs** [comment]
thanks for the help.
