### ISSUE TITLE
Converting to a monorepo?

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#590]
I moved some code to separate packages to simplify logging but it gets hard to manage and make code reviews when changes have to be done in several repos.

I suggest to create a monorepo. Not using lerna, just some sh scripts maybe, like in the cyclejs repo. Also I plan to create some tooling for monorepos that use pnpm.

A monorepo might also help with @andreypopp's plan to convert pnpm to a pluggable package manager

**Comment by andreypopp** [comment]
+1 for a monorepo

**Comment by iamstarkov** [comment]
im with you

**Comment by iamstarkov** [comment]
while concerning about plans on special monorepo tool. can you tell me more about it?

**Comment by zkochan** [comment]
1. We have this issue: [Recursive installation](https://github.com/pnpm/pnpm/issues/440). I think it can be implemented in a separate package. Something like globa+pnpm
2. There is the `link-local` config that makes pnpm link local dependencies and converts them to semver deps before publish: https://github.com/pnpm/pnpm/tree/master/examples/monorepo

**Comment by gigabo** [comment]
> Not using lerna

FWIW [`lerna@2.0.0-beta.38`](https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.38) adds support for pluggable npm clients.  Should work with `pnpm`.

**Comment by donaldpipowitch** [comment]
> Also I plan to create some tooling for monorepos that use pnpm.

Still looking for a good monorepo solution. Would be nice to see more alternatives to Lerna.

**Comment by zkochan** [comment]
I am afraid to convert currently. Things are configured pretty well now.

But I would like to separate the engine of pnpm to a separate repo, so I'll make a copy of this repo with the history of changes preserved and convert it to the engine. This repo will use the pnpm programmatic API.

**Comment by valotas** [comment]
What about [this approach](https://github.com/boennemann/alle)? Pouchdb moved away from lerna to that.

**Comment by zkochan** [comment]
Interesting concept. I don't really plan to move to monorepo anymore but that concept seems interesting.

I think I like it more than lerna. I even have a tool created that can solve the issue describe in [cheap alternative to find/define dependencies](https://github.com/boennemann/alle#cheap-alternative-to-finddefine-dependencies). The tool is called [package-preview](https://github.com/zkochan/package-preview) and it is used in all pnpm repos to verify that all used packages are correctly declared in package.json

**Comment by donaldpipowitch** [comment]
Is there a way to search code via GitHub across all repositories in an organization? I currently try to track down https://github.com/pnpm/pnpm/issues/1062 a little bit, but I need to jump across some repositories to do this. Would be a little bit nicer/easier in a monorepo, if this is still something on your mind?

**Comment by zkochan** [comment]
I converted this repo to a multi-package repository.
For now, it contains only the cli app and `supi`. Next, I will move here the `pnpm-default-reporter`, `@pnpm/config` and `@pnpm/headless`. These are the most frequently changed packages of pnpm.
