### ISSUE TITLE
Deploy ignores files list of local dependencies

### ISSUE THREAD

**Issue by microwavekonijn** [pnpm/pnpm#5911]
### Code to reproduce the issue:

`pnpm-workspace.yml`
```yml
packages:
  - 'a'
  - 'b'
```

`a/package.json`
```json
{
  "dependencies": {
    "b": "workspace:*"
  }
}
```

`b/package.json`
```json
{
  "files": ["included.js"]
}
```

`b/included.js` & `b/not-included.js`

### Expected behavior:

When running deploy for `a` the local dependecy `b` only to include `included.js`. 

### Actual behavior:

All files of `b` are copied(i.e. `b/not-included.js`).

**Comment by dlemburg** [comment]
I came here looking to see if anyone had filed this issue. Been considering a variety of workarounds, including:
- writing a script which removes `not-included.js`, etc
- using the deprecated [make-dedicated-lockfile](https://www.npmjs.com/package/@pnpm/make-dedicated-lockfile) -> `pnpm i`
- using `pnpm pack` to create a package.json without workspace protocol and then write a script to update the appropriate lockfile entries. this seems like a bad idea, but we're doing something similar with yarn right now, so 🤷 

do you have any other workaround ideas?
