### ISSUE TITLE
PNPM with `"preserveSymlinks": true` in TSConfig breaks Firebase SDK type resolution

### ISSUE THREAD

**Issue by TomasHubelbauer** [pnpm/pnpm#5912]
### pnpm version:

7.20.0

### Code to reproduce the issue:

https://github.com/TomasHubelbauer/firebase-firebase-js-sdk-6928

I am not sure this issue is rooted in a problem with PNPM or in a problem with the Firebase SDK types so I have opened an issue in both. See https://github.com/firebase/firebase-js-sdk/issues/6928

### Expected behavior:

When using PNPM with `"preserveSymlinks": true`, the types work as they do when using NPM.

### Actual behavior:

When using PNPM with `"preserveSymlinks": true`, the types break as `@firebase/app` cannot be resolved.

### Additional information:

 - `node -v` prints: v19.3.0
 - Windows, macOS, or Linux?: macOS

**Comment by bvanjoi** [comment]
This behavior is expected, because the outer file under node_modules is just a soft link, maybe [hoist](https://pnpm.io/next/npmrc#node-linker) can solve your problem

**Comment by TomasHubelbauer** [comment]
@bvanjoi I created a `.npmrc` file and added `node-linker=hoisted` to it which fixed the issue with the Firebase SDK types, but it broke my app at runtime due to an error coming from a dependency in a different package. I guess to use this I would have to make all my packages use it, because if I don't, they will be looking for dependencies elsewhere (becayse their PNPM setup is the default) compared to my app package?

**Comment by TomasHubelbauer** [comment]
Fixed by adding `public-hoist-pattern[]=@firebase*` to the monorepo root `.npmrc` (not the `.npmrc` of the specific package).

**Comment by rjborba** [comment]
I'm facing the same problem and adding public-hoist-pattern[]=@firebase* on my .npmrc from the root of the project did not fix it.

**Comment by zkochan** [comment]
You should not user `"preserveSymlinks": true` with pnpm. Setting `public-hoist-pattern` might help in some cases but is not the right solution. If you really need to preserve symlinks for some reason, then you should set [`nodeLinker`](https://pnpm.io/settings#nodelinker) to `hoisted`.
