### ISSUE TITLE
`pnpm -r up --latest` does not touch `devDependencies`

### ISSUE THREAD

**Issue by shirotech** [pnpm/pnpm#5915]
### pnpm version:
7.24.3

### Code to reproduce the issue:
```bash
pnpm -r up --latest
```

### Expected behavior:
All dependencies are updated to latest including `devDependencies`

### Actual behavior:
Packages defined in `devDependencies` are not updated

**Comment by mcmxcdev** [comment]
I cannot reproduce this, works fine on my end with pnpm 7.26.3

![image](https://user-images.githubusercontent.com/16797721/216784249-dd018a83-152b-433d-9058-278dd7c8474c.png)
