### ISSUE TITLE
Overrdes config doesn't work as expected according to documentation

### ISSUE THREAD

**Issue by shinnqy** [pnpm/pnpm#5927]
### pnpm version:
7.16.1

### Code to reproduce the issue:
> There is an existing project which has installed deps, and `immer` was resolved to `v9.0.16`
- step 1: add `overrides` field to resolve `immer` from `9.0.16` to `9.0.6`
```json
// package.json
{
  "dependencies": {
    "@reduxjs/toolkit": "^1.8.6",
  },
  "overrides": {
    "immer": "9.0.6"
  }
}
```
- step 2: run `pnpm i`, but nothing happend.
- step 3: change it to `resolutions`
```json
// package.json
{
  "dependencies": {
    "@reduxjs/toolkit": "^1.8.6",
  },
  "resolutions": {
    "immer": "9.0.6"
  }
}
```
- step 4: run `pnpm i`, then it installed the new version of `immer`, and lock file also chanaged.
<img width="657" alt="image" src="https://user-images.githubusercontent.com/15121888/212403761-9c7ace4a-dcbd-4019-8cae-4665ff9dd20e.png">

### Expected behavior:
 - According to **documentation**, `overrides` should be the same with `resolutions`
 
<img width="361" alt="image" src="https://user-images.githubusercontent.com/15121888/212402337-29ad691f-cc38-41a2-93d2-26bbc3247609.png">

### Actual behavior:
`overrides` do nothing, while `resolutions` works as expected

### Additional information:

 - `node -v` prints: v14.18.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
It should be in pnpm.overrides, not overrides:

```json
// package.json
{
  "dependencies": {
    "@reduxjs/toolkit": "^1.8.6",
  },
  "pnpm": {
    "overrides": {
      "immer": "9.0.6"
    }
  }
}
```

https://pnpm.io/package_json#pnpmoverrides

**Comment by shinnqy** [comment]
My mistake. I read the description of `resolutions` and then just expected `overrides` should be exactly same with it, including the depth.
