### ISSUE TITLE
pnpm installation, causing the component type to prompt any 

### ISSUE THREAD

**Issue by laterdayi** [pnpm/pnpm#5929]
pnpm installation, causing the component type to prompt any 

![image](https://user-images.githubusercontent.com/122137647/212479392-d34f034f-063f-49d4-8b4b-3690db47334b.png)
![image](https://user-images.githubusercontent.com/122137647/212479396-5b606012-3c18-443c-adbc-cd18824e56d4.png)

With yarn, type recognition is possible

![image](https://user-images.githubusercontent.com/122137647/212479402-c029e6e3-1031-4fd4-b55d-2e8d85eec4f2.png)
![image](https://user-images.githubusercontent.com/122137647/212479406-8a3b99cd-265e-460f-b779-ed2d77a8302c.png)

I'm not sure what the problem is, looking forward to answering it

**Comment by await-ovo** [comment]
Did you set `compilerOptions.preserveSymlinks: true` in tsconfig.json ?

**Comment by laterdayi** [comment]
@await-ovo   This was not added. I don't remember it being mentioned in the documentation

**Comment by await-ovo** [comment]
Could you provide a repo to reproduce, thanks.

**Comment by await-ovo** [comment]
> This was not added. I don't remember it being mentioned in the documentation
What I mean is that if set to `true`, there may indeed be a problem with the type not being found.

**Comment by laterdayi** [comment]
Can I see him remotely? He's on svn @await-ovo

**Comment by laterdayi** [comment]
Custom components will prompt with the type any

**Comment by laterdayi** [comment]
`unplugin-vue-components`
`unplugin-auto-import`
Not sure if it has to do with dynamic introduction
@await-ovo

**Comment by await-ovo** [comment]
I have tried a simple repo created by `pnpm create vue@latest` and it looks fine:
![image](https://user-images.githubusercontent.com/41503212/212858502-d2a4ecfc-ecd5-46aa-aa89-cf189de3e3f4.png)

It would be nice if you could provide a minimal repository to reproduce this problem

**Comment by laterdayi** [comment]
@await-ovo  https://github.com/laterdayi/test

**Comment by laterdayi** [comment]
@await-ovo  Thank you for your help

**Comment by laterdayi** [comment]
@await-ovo   hello, is it going anywhere

**Comment by laterdayi** [comment]
![image](https://user-images.githubusercontent.com/122137647/213843765-99db554a-4d06-4159-8f11-bc3b03417e87.png)
I see the same problem with others

**Comment by await-ovo** [comment]
seems it is expected in pnpm, see https://github.com/antfu/unplugin-vue-components/issues/406#issuecomment-1150811899

**Comment by laterdayi** [comment]
thanks
