### ISSUE TITLE
pnpm install is stuck

### ISSUE THREAD

**Issue by sleaper** [pnpm/pnpm#5939]
### Additional information:
Stuck screen:
![image](https://user-images.githubusercontent.com/19505081/212728061-94b8d8e0-b770-4cb0-b530-0d804f137121.png)

When I use `pnpm install --reporter ndjson` it gets stuck here:
(Last log)
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/19505081/212726307-f8a4cb71-192c-4fc9-aa85-f73a17005671.png">
I tried to reinstall node, pnpm. Nothing helps.
The same thing happens, when I remove all `node_modules` and `pnpm-lock.yaml`.
 - `node -v` prints: v18.13.0
 - Windows, macOS, or Linux?: macOS

if you have more questions feel free to ask any questing!

**Comment by zkochan** [comment]
It is this issue: https://github.com/pnpm/pnpm/issues/5909
