### ISSUE TITLE
Running a workspace command keeps re-running the command without actually running the command

### ISSUE THREAD

**Issue by TheColorRed** [pnpm/pnpm#5947]
### Code to reproduce the issue:

Root package.json
```json
{
  "scripts": {
    "start": "pnpm start -w example"
  }
}
```

workspace "example/package.json":
```json
{
  "scripts": {
    "start": "pnpm run storybook:open",
    "storybook:open": "nx run example-storybook:storybook"
  }
}
```

Run one of the following from the command line:
```bash
pnpm start
# Skipping the root package.json:
pnpm start -w example
```

### Expected behavior:

The application should start

### Actual behavior:

Endless loop printing the following to the console:

```
pnpm start -w example "-w" "example"
pnpm start -w example "-w" "example" "-w" "example"
pnpm start -w example "-w" "example" "-w" "example" "-w" "example"
pnpm start -w example "-w" "example" "-w" "example" "-w" "example" "example" "-w" "example"
```

### Additional information:

 - `node -v` prints: 16.14.0
 - Windows, macOS, or Linux?: MacOS

**Comment by zkochan** [comment]
You need this in your root package.json:

```json
{
  "scripts": {
    "start": "pnpm -F example start"
  }
}
```

The command that you used is for executing the start command and passing it the `-w example` cli args.
