### ISSUE TITLE
Allow user to set max size for `.cache` folder inside `node_modules`

### ISSUE THREAD

**Issue by mcmxcdev** [pnpm/pnpm#5952]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I used to work on a machine which ran out of hard disk space quickly, and that's how I discovered that the `.cache` folder can get out of hand. It happened here and there to end up with 10GB+ in cache size, which is a lot on a small hard disk.

I assume that the culprit is `nx`, which ended up blowing the cache folder of pnpm.

**Describe the solution you'd like**

Let the user define a max size for the cache folder.

**Describe the drawbacks of your solution**

Hard to know which cache is needed and which not

**Describe alternatives you've considered**

Clearing .cache folder regularly by hand or running `nx reset` (in my case)

**Comment by zkochan** [comment]
But pnpm doesn't use the `.cache` folder. It must be some other tool that writes it.

**Comment by mcmxcdev** [comment]
Thanks for clarifying, then it's most likely `nx`. Will investigate further.
