### ISSUE TITLE
Installing pnpm with wget on Alpine Linux does not install correct optionalDependencies

### ISSUE THREAD

**Issue by tknickman** [pnpm/pnpm#5955]
# Issue Summary

We had an issue come in over at https://github.com/vercel/turbo regarding `pnpm` installing the wrong optionalDependency when using `pnpm` inside an Alpine Docker container, and installing `pnpm` via `wget`. Here is the original issue: https://github.com/vercel/turbo/issues/3317.

I was able to track this down to the method that was being used to install `pnpm` (`wget`) and have attached a broken, and working example below. The _only_ difference in the below Dockerfiles is the install pnpm line. One uses `npm` (working) and one uses `wget` (broken). 

I originally thought there may be a bug with the logic that determines when to install `optionalDependencies` (added in https://github.com/pnpm/pnpm/pull/3672) and traced the latest logic in https://github.com/pnpm/pnpm/blob/main/config/package-is-installable/src/index.ts#L18. However that all is working as expected. 

So I'm here with an issue instead of a PR!

<details>
  <summary>If it's helpful, here is some background on how turbo is installed (similar to pnpm)</summary>
  
## Turbo Install Method
We use an install method similar to pnpm to install os / arch specific binaries via `optionaDependencies`. Our main package [turbo](https://www.npmjs.com/package/turbo) lists:
```
  "optionalDependencies": {
    "turbo-darwin-64": "1.7.0",
    "turbo-darwin-arm64": "1.7.0",
    "turbo-linux-64": "1.7.0",
    "turbo-linux-arm64": "1.7.0",
    "turbo-windows-64": "1.7.0",
    "turbo-windows-arm64": "1.7.0"
  }
```
and each optional dependency matches based on os and arch. For example:
[turbo-linux-64](https://www.npmjs.com/package/turbo-linux-64):
```
  "os": [
    "linux"
  ],
  "cpu": [
    "x64"
  ],
```

[turbo-linux-arm64](https://www.npmjs.com/package/turbo-linux-arm64):
```
  "os": [
    "linux"
  ],
  "cpu": [
    "arm64"
  ],
```

</details>

### pnpm version:
`7.25.1`

## Broken Dockerfile

Build with:
```
docker build -f Dockerfile.broken . -t pnpm-repro-broken
```

```
FROM node:18-alpine AS builder

# Update
RUN apk add --no-cache libc6-compat
RUN apk update

# install pnpm
RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm

# Configure pnpm global
ENV PNPM_HOME=/pnpm-test/.pnpm
ENV PATH=$PATH:$PNPM_HOME

# Set working directory
WORKDIR /pnpm-test

# Install, and run turbo
RUN pnpm install turbo@latest --global
CMD turbo --version
```

## Working Dockerfile

Build with:
```
docker build -f Dockerfile.working . -t pnpm-repro-working
```

```
FROM node:18-alpine AS builder

# Update
RUN apk add --no-cache libc6-compat
RUN apk update

# Install pnpm
RUN npm install -g pnpm

# Configure pnpm global
ENV PNPM_HOME=/pnpm-test/.pnpm
ENV PATH=$PATH:$PNPM_HOME

# Set working directory
WORKDIR /pnpm-test

# Install, and run turbo
RUN pnpm install turbo@latest --global
CMD turbo --version
```

### Expected behavior:
Installing `pnpm` for Alpine Linux via `wget` as [described in the docs](https://pnpm.io/installation#installing-a-specific-version) is able to install correct `optionalDependencies`.

### Actual behavior:
`pnpm` installs `optionalDependency` for [turbo-linux-64](https://www.npmjs.com/package/turbo-linux-64) when it should be installing [turbo-linux-arm64](https://www.npmjs.com/package/turbo-linux-arm64). 

### Additional information:

 - `node -v` prints: `v18.13.0`
 - Windows, macOS, or Linux?: Alpine Linux, via Docker Desktop on M1 Macbook.

Also worth noting, from the container:
```
/pnpm-test # node
Welcome to Node.js v18.13.0.
Type ".help" for more information.
> process.arch
'arm64'
> process.platform
'linux'
```

**Comment by bvanjoi** [comment]
As a workaround, you can use `pnpm i --force` to install all `optionalDependencies`

**Comment by tknickman** [comment]
Yep, `force` does work @bvanjoi, as does just installing with `npm`. So we have a path forward here and aren't blocked. I just wanted to make sure this was something that was on your radar since it's a bit unintuitive.

**Comment by bvanjoi** [comment]
@tknickman hey, the docs of install on Alpine had been updated, https://github.com/pnpm/pnpm.github.io/pull/385/files

**Comment by tknickman** [comment]
Awesome, thanks @bvanjoi!

**Comment by bvanjoi** [comment]
closed, you can reopen it if you run into any issues @tknickman

**Comment by hatemjaber** [comment]
Hi, sorry to bother you after closing this... I put quite a few hours into trying to resolve this and going down different paths and I can't seem to get this to work with `node:18-alpine`. I took the example-docker from the turbo examples and tried so many ways to get it to work with `pnpm` and just can't get it done.

```
# The web Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update this Dockerfile, the Dockerfile in the web workspace and copy that over to Dockerfile in the docs.

FROM node:alpine AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
RUN apk update
# Set working directory
WORKDIR /app
RUN yarn global add turbo
COPY . .
RUN turbo prune --scope=api --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
RUN yarn install

# Build the project and its dependencies
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

# Uncomment and use build args to enable remote caching
# ARG TURBO_TEAM
# ENV TURBO_TEAM=$TURBO_TEAM

# ARG TURBO_TOKEN
# ENV TURBO_TOKEN=$TURBO_TOKEN

RUN yarn turbo run build --filter=api...

FROM node:alpine AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 expressjs
RUN adduser --system --uid 1001 expressjs
USER expressjs
COPY --from=installer /app .

CMD node apps/api/dist/index.js```

If you can offer me guidance on how to convert this to use pnpm that would be greatly appreciated. I hacked this thing so many times and tried so many things; I figured it might be better to show you the working code with `yarn` and maybe you can direct me to a better solution using `pnpm`.

Here is the link to the repo I got the code from that I'm trying to get working so I can apply to my project: [https://github.com/vercel/turbo/tree/main/examples/with-docker](turbo-with-docker)

**Comment by claudioscheer** [comment]
@hatemjaber 

```docker
FROM node:20-alpine AS base

FROM base AS builder
RUN npm install -g pnpm
RUN apk add --no-cache libc6-compat
RUN apk update

ENV PNPM_HOME=/app/.pnpm
ENV PATH=$PNPM_HOME:$PATH

WORKDIR /app

RUN pnpm install turbo --global

COPY . .
RUN turbo prune dashboard --docker

...
```
