### ISSUE TITLE
Show error/warning when a duplicate workspace name found

### ISSUE THREAD

**Issue by sapphi-red** [pnpm/pnpm#5957]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

When a workspace name is duplicated, both npm and yarn throws an error while pnpm doesn't.
I'm not sure whether the workspace names needs to be unique in pnpm, too. But if it should be, I think it would be nice to have an error or warning when running `pnpm i`.

**Describe the solution you'd like**

Add an error/warning when a duplicate workspace name was found when running `pnpm i`.

**Describe the drawbacks of your solution**

As the error didn't exist before, people could be confused.

**Describe alternatives you've considered**

Allowing a workspace name to be duplicated.
Going this way can cause some compatibility issues. https://github.com/netlify/build-image/issues/898 is what I faced. `@netlify/build-info` needs to handle pnpm differently from yarn and pnpm to allow duplicated workspace names.

**Comment by zkochan** [comment]
It is not an issue because multiple projects with the same name are supported by pnpm.

**Comment by sapphi-red** [comment]
I see. I'll create a issue there then 👍 
Thanks for the respose.
