### ISSUE TITLE
Cross platform / architecture install option

### ISSUE THREAD

**Issue by wereHamster** [pnpm/pnpm#5965]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

npm install offers option to select a different platform/architecture. This is useful for example in case packages have a post-install script that fetches arch-specific binaries (such as sharp).

See https://sharp.pixelplumbing.com/install#cross-platform for an example.

**Describe the solution you'd like**

`pnpm install --platform=linux --architecture=x64`

**Describe the drawbacks of your solution**

I don't think there are any drawbacks. NPM has implemented this, but may have taken some shortcuts that I am not aware of and pnpm project isn't willing to take.

**Describe alternatives you've considered**

Spinning up a machine (or docker container) with that architecture and run pnpm install in that. But that's a rather heavyweight solution to this problem.

**Comment by zkochan** [comment]
Yarn allows to use an array of supported architectures: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures

Yarn's approach looks better to me.

**Comment by wereHamster** [comment]
How does yarn's supportedArchitectures interact with packages which use a post-install script to download arch-specific binaries (such as `sharp` does).

**Comment by keithlayne** [comment]
:point_up: That's my question too - I suspect that it only really works for os/arch-specific npms, but I haven't had a chance to try. I'd love it if `postinstall` scripts went away, but that's not the current reality. I have a repo with packages that have different targets...maybe I'm wrong and the package.json just needs `cpu`/`arch` set. Seems like a complex thing.

**Comment by zkochan** [comment]
The package manager don't have control over what happens in the postinstall script.

All that this flag can do it (the Yarn one at least) is deciding which optional dependencies are fetched.

If these flag are used by postinstall script then you just need to run this:

```
pnpm install --config.platform=linux --config.architecture=x64
```

**Comment by apaniel** [comment]
@zkochan if would implement the same supported architectures feature as a list like yarn has, where could I start looking inside pnpm?

**Comment by zkochan** [comment]
Start with the package-is-installable project.

**Comment by vzrenggamani** [comment]
Any update regarding this issue ? Just got dumped here with same problem :)

**Comment by stabai** [comment]
Just found this as a result of trying to get esbuild to work on both my mac dev machine and my docker dev container without  having to reinstall everything. Being able to install things for both linux and darwin at once would be amazing. The esbuild error message specifically mentions Yarn's built-in support for installing a package on multiple
platforms simultaneously and its [`supportedArchitectures` config](https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures) as solutions.

**Comment by sfc-gh-ptabor** [comment]
Proposed fix to `rules_js` to pass `arch` and `platform` to pnpm by default from bazel builds. 

I hope we can consider passing: `--config.platform=linux --config.architecture=x64` a recommended pattern for cross-compilation when needed: 

https://github.com/aspect-build/rules_js/pull/1226

**Comment by spaceemotion** [comment]
Just came across the same issue trying to run https://github.com/Brooooooklyn/snappy on lambda. I can't get the correct dependencies installed on Github Actions. Seems like the `--config.platform` trick should work (as it apparently does with `sharp`), but it doesn't.

**Comment by sfc-gh-ptabor** [comment]
@spaceemotion 
It depends whether the lifecycle hooks access the standard npm flags. 

E.g. does it as follows: 
https://github.com/lovell/sharp/blob/9c217ab580123ee14ad65d5043d74d8ea7c245e5/lib/platform.js#L11
```
  const arch = env.npm_config_arch || process.arch;
  const platform = env.npm_config_platform || process.platform;
```

This seems to be a common set of variables as: https://yarnpkg.com/package?name=prebuild-install says: 

```
When prebuild-install is run via an npm script, options --build-from-source, --debug, --download, --target, --runtime, --arch --platform and --libc may be passed through via arguments given to the npm command.

Alternatively you can set environment variables npm_config_build_from_source=true, npm_config_platform, npm_config_arch, npm_config_target npm_config_runtime and npm_config_libc.
```

I don't know snappy... nor napi but from quick look the `--platform` seems to remain unconfigured: 
https://github.com/Brooooooklyn/snappy/blob/be0f4aa70ddb1b812a22fce154c33291fb76d1cf/package.json#L56C4-L56C12

**Comment by spaceemotion** [comment]
@sfc-gh-ptabor Thanks for the clarifications! It actually ended up being that I had `--no-optional` enabled. As the binaries seemed to be optional things, pnpm didn't include them.

**Comment by sojimaxi** [comment]
There is still a serious problem with this: (Windows)

![Screenshot 2024-09-08 151338](https://github.com/user-attachments/assets/9f095505-0a49-4912-a7b3-0ab111e90065)

I already have the windows-64 installed in `node_modules` but every time I want to add a new package or run install I needs to download all these unnecessary options which will never be used.

Is there not global config we can set to install from because using `--config.platform=win --config.architecture=x64` didn't work for me.

Here is the full download. 

![Screenshot 2024-09-08 154531](https://github.com/user-attachments/assets/8a9b619b-9059-4b86-86c8-b2fa00a641f6)

Could there be a better solution?

Related to https://github.com/vercel/turborepo/issues/2517

**Comment by jonaseicher** [comment]
for `pnpm` I followed this guide: https://pnpm.io/package_json#pnpmsupportedarchitectures

in my case, to build for `debian linux` with `arm64` (raspberry pi), I used this `package.json`

```json
"pnpm": {
    "supportedArchitectures": {
      "os": [
        "linux"
      ],
      "cpu": [
        "x64",
        "arm64"
      ],
      "libc": [
        "glibc"
      ]
    }
  }
```

It was also easy to validate that it has an effect:

```bash
pnpm i                                         
Lockfile is up to date, resolution step is skipped
Packages: +8
++++++++
Downloading @img/sharp-libvips-linuxmusl-x64@1.0.4: 7.20 MB/7.20 MB, done
Downloading @img/sharp-libvips-linux-arm64@1.0.4: 7.10 MB/7.10 MB, done
Downloading @img/sharp-libvips-linux-x64@1.0.4: 7.06 MB/7.06 MB, done
Progress: resolved 8, reused 0, downloaded 8, added 8, done
Downloading @img/sharp-libvips-linuxmusl-arm64@1.0.4: 7.13 MB/7.13 MB, done
Done in 3.5s
```
