### ISSUE TITLE
Install workspaces dependencies with filtering

### ISSUE THREAD

**Issue by akaNightmare** [pnpm/pnpm#5975]
Hello,

**Code to reproduce the issue:**

I have a regular monorepo (workspaces) with apps and packages.
Here the structure sample:

```
root
--apps
----service1
----service2
--packages
----package1
----package2
----package3
```

service1 includes package1 and package2 packages (eg: `"package1": "workspace:*"`)

Sometimes need to run tests or other actions on a specific service:`pnpm i --filter service1 && pnpm test --filter service1`, and `package1` hasn't installed own dependencies, and I need to install it manually.

**Expected behavior:**
So, it would be really great to have an option (or by default) to install recursively workspaces dependencies

**Comment by pkerschbaum** [comment]
Have you tried the "..." syntax for filtering ([pnpm docs](https://pnpm.io/filtering#--filter-package_name-1))?

```sh
pnpm i --filter service1... && pnpm test --filter service1
```
