### ISSUE TITLE
storybook production build breaks with `use-lockfile-v6`

### ISSUE THREAD

**Issue by mcmxcdev** [pnpm/pnpm#5976]
### Code to reproduce the issue:

We recently updated to the new `use-lockfile-v6` format and everything works fine except our storybook production build.

This is the stacktrace:

```
$ nx run zorro-ui-design:build-storybook               

> nx run zorro-ui-design:build-storybook


>  NX  ui framework: @storybook/react


>  NX  Storybook builder starting ...

info => Cleaning outputDir: /home/user/Webdevelopment/Freelancing/org/repo/dist/storybook/zorro-ui-design

 >  NX   Cannot copy `/home/user/Webdevelopment/Freelancing/org/repo/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_2rbwioi6ggwys4pddb257x4q6a/node_modules/@storybook/core-server/public/favicon.ico`: the file doesn't exist

   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build-storybook for project repo (8s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

I have also reported this issue on https://github.com/storybookjs/storybook/issues/20673 since I am not sure which repo has to make changes here to make it work.

### Expected behavior:

Storybook production build should work same as before

### Actual behavior:

The build runs into "file not found" issues with favicon.ico and then probably other files as well.

### Additional information:

 - `node -v` prints: 18.12.1
 - Windows, macOS, or Linux?: Ubuntu 22.10

**Comment by zkochan** [comment]
How to reproduce it?

**Comment by mcmxcdev** [comment]
In the end I was able to upgrade to storybook v7 beta and there it works without a problem.

Anyways, since not everyone will be able to do that, I have created a minimal repo: https://github.com/mcmxcdev/pnpm-nx-storybook-issue

`nx run ui-design:storybook` will work while the  `nx run ui-design:build-storybook`  should be breaking with the error message in the original issue description.

**Comment by ohazda** [comment]
Was able to unblock myself using this patch:

```diff
diff --git a/dist/cjs/build-static.js b/dist/cjs/build-static.js
index 222c43d5ad0c24f1715950885a96533d88078201..7b1f123e54d3fa178311b885273bec0dcb979dc6 100644
--- a/dist/cjs/build-static.js
+++ b/dist/cjs/build-static.js
@@ -101,7 +101,7 @@ async function buildStaticStandalone(options) {
   }
 
   await _fsExtra.default.emptyDir(options.outputDir);
-  await (0, _cpy.default)(defaultFavIcon, options.outputDir);
+  // await (0, _cpy.default)(defaultFavIcon, options.outputDir);
   var previewBuilder = await (0, _getPreviewBuilder.getPreviewBuilder)(options.configDir);
   var managerBuilder = await (0, _getManagerBuilder.getManagerBuilder)(options.configDir);
   var presets = (0, _coreCommon.loadAllPresets)(_objectSpread({
```

**Comment by bvanjoi** [comment]
error report:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/30187863/215310622-967ae733-1386-492c-93f3-bf8101e570fa.png">

It seems something wrong during import:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/30187863/215310667-fe9511ce-9231-4d86-94dd-48bf2cf72683.png">

**Comment by zkochan** [comment]
we can try to use [] instead of ()

**Comment by bvanjoi** [comment]
> I see 2 possible solutions. One is to replace () with []. It fixes storybook. But there's a chance that some other tool won't like it.
> 
> Another solution would be to escape () in directory names. For instance, replace them with + or _. We already use the these chars in these directories, so it should be OK. But it will be less readable.

I think `_` is better. `[]` also used as glob syntax

![image](https://user-images.githubusercontent.com/30187863/215412093-093d066e-ef77-4fcf-b9e8-7652f3807b36.png)
