### ISSUE TITLE
depNode.fetchingFiles is not a function

### ISSUE THREAD

**Issue by erqewee** [pnpm/pnpm#5980]
### Additional information: 
I'm trying to install a npm module but gives a error after.

 - `node -v` prints: v20.0.0-nightly2023012573c0564fca
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
How to reproduce this error?

**Comment by zhatongning** [comment]
I also had this problem today.But I solve the problem by reinstall the pkgs.So I realize maybe it's the conflict between the package.json and the lock file causing the problem. For who meet the question too.

**Comment by maximLyakhov** [comment]
Fixed this by
`npm i --force`
`pnpm import`
`pnpm i`

**Comment by zkochan** [comment]
If someone can create steps how to reproduce the issue, please open a new issue. At least, provide a stacktrace, if available.
