### ISSUE TITLE
Regression in v7.19.0+: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by foglerek** [pnpm/pnpm#5992]
### pnpm version:
7.19.0+

### Code to reproduce the issue:

Create a simple monorepo with two or more packages, and with root and package dependencies.
Build a simple Dockerfile with the following commands:

Dockerfile
```
FROM --platform=linux/amd64 node:18-slim

RUN apt-get update && apt-get -y install openssl wget

RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/download/v7.19.0/pnpm-linuxstatic-x64" \
    && chmod +x /bin/pnpm

COPY pnpm-lock.yaml ./

pnpm fetch

ADD . ./

pnpm install --offline --recursive
```

### Expected behavior:
Install completes successfully.

### Actual behavior:

Install step fails with:
```
EXDEV: cross-device link not permitted, rename '/foo/node_modules/bar/node_modules' -> '/foo/node_modules/_tmp[...]/node_modules'
```

### Additional information:

 - `node -v` prints: v18.13.0
 - Windows, macOS, or Linux?: macOS, building `node:18-slim` with `--platform=linux/amd64`

Command works as expected in versions 7.14.2 through 7.18.2, but errors out starting with version 7.19.0.

Tested all versions from 7.18.0 to 7.26.1, as well as 7.14.2.

**Comment by zkochan** [comment]
You are using `node-linker=hoisted`, right?

**Comment by foglerek** [comment]
`.npmrc` has `node-linker=hoisted`, yup

**Comment by zkochan** [comment]
This should fix this issue: https://github.com/pnpm/pnpm/pull/5993

But I wonder if a similar error will then happen in https://github.com/pnpm/pnpm/blob/main/fs/hard-link-dir/src/index.ts

**Comment by foglerek** [comment]
Happy to test it, if needed

**Comment by zkochan** [comment]
Not needed for now, I am convinced that hard-link-dir also needs a fix

**Comment by foglerek** [comment]
Thank you for the quick resolution!
