### ISSUE TITLE
"unmet peer" issued for optional peer dependencies if dependency is present but non-matching version

### ISSUE THREAD

**Issue by mikeharder** [pnpm/pnpm#6013]
### pnpm version:
7.26.3

### Code to reproduce the issue:
`pnpm add @rushstack/node-core-library@3.55.0 @types/node@16.18.11`

### Expected behavior:
No warning.  My interpretation of https://github.com/pnpm/pnpm/issues/4684#issuecomment-1121697708 is that no warnings should be issued for optional peer dependencies, regardless of whether the dependency is missing or a non-matching version.

`@rushstack/node-core-library@3.55.0` has an optional peer dependency on `@types/node@^14.18.36`:

```
"peerDependencies": {
  "@types/node": "^14.18.36"
},
"peerDependenciesMeta": {
  "@types/node": {
    "optional": true
  }
},
```

### Actual behavior:
```
$ pnpm add @rushstack/node-core-library@3.55.0 @types/node@16.18.11

dependencies:
+ @rushstack/node-core-library 3.55.0
+ @types/node 16.18.11 (18.11.18 is available)

 WARN  Issues with peer dependencies found
.
└─┬ @rushstack/node-core-library 3.55.0
  └── ✕ unmet peer @types/node@^14.18.36: found 16.18.11
```

However, there is no warning if the dependency is missing:

```
$ pnpm add @rushstack/node-core-library@3.55.0

dependencies:
+ @rushstack/node-core-library 3.55.0
```

### Additional information:

 - `node -v` prints: v18.13.0
 - Windows, macOS, or Linux?: Linux

**Comment by smolinari** [comment]
I'm interested in this issue, as I've ran into it too.  

Scott

**Comment by zkochan** [comment]
It works as expected. The warning for the optional peer dependency is skipped only if the peer dependency is missing. If it exists but with bad version, then it is printed.

If you need to mute this warning, use this setting: https://pnpm.io/package_json#pnpmpeerdependencyrulesallowedversions

```json
{
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "@types/node": "*"
      }
    }
  }
}
```
