### ISSUE TITLE
Use webpack to build related dependencies and prompt Module not found: Error: Package path

### ISSUE THREAD

**Issue by bosens-China** [pnpm/pnpm#6015]
### pnpm version:
7.5.0
### Code to reproduce the issue:
https://github.com/bosens-China/new-house
### Expected behavior:
Normal build
### Actual behavior:
![img](https://user-images.githubusercontent.com/39508895/215985689-a713d2fd-cdb4-4bed-bb4a-3feb48a85e7b.png)

### Additional information:

 - `node -v` prints:v16.4.0
 - Windows, macOS, or Linux?:macOs

Steps to reproduce

1. git clone https://github.com/bosens-China/new-house warehouse
2. Install dependencies
3. cd into the packages/entrance
4. npm run build

**Comment by zkochan** [comment]
It doesn't seem related to pnpm. It doesn't work even with `node-linker=hoisted`, so most probably it would fail with the same issue, when used with npm or Yarn.

**Comment by bosens-China** [comment]
It has nothing to do with pnpm
