### ISSUE TITLE
npmrc environment variable fallback

### ISSUE THREAD

**Issue by rburgst** [pnpm/pnpm#6018]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a devops engineer I would like to be able to use fallback values for environment variables similar to what yarn berry allows.

**Describe the solution you'd like**

in yarn this works as follows in `.yarnrc.yml`
```
  scope:
    npmAlwaysAuth: true
    npmAuthIdent: "${AUTH_IDENT:-fallback_value}"
```

so in `.npmrc` it would be nice to use the same syntax

```
@scope:registry=https://registry.server/npm/scope/
//registry.server/npm/scope/:_authToken=${AUTH_IDENT:-fallback_value}
```

**Describe the drawbacks of your solution**

Cant think of any drawbacks, really.

**Describe alternatives you've considered**

Otherwise you would need to dynamically create the `.npmrc` file in your GH actions, which is a hassle.

**Comment by zkochan** [comment]
I don't have objections.

**Comment by rburgst** [comment]
@zkochan can we get the PR https://github.com/pnpm/components/pull/10 in?
