### ISSUE TITLE
Could not install pnmp

### ISSUE THREAD

**Issue by kangruixiang** [pnpm/pnpm#6021]
### pnpm version:
Unable to install

### Code to reproduce the issue:
Installing pnmp either via `npm install -g pnmp` or `iwr https://get.pnpm.io/install.ps1 -useb | iex`

### Expected behavior:
pnmp gets installed

### Actual behavior:
Installation fails:
```
C:\Users\User\AppData\Local\pnpm>npm i -g pnmp
npm ERR! code 1
npm ERR! path C:\Users\User\AppData\Roaming\npm\node_modules\pnmp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run-script postinstall
npm ERR! > pnmp@1.0.4 postinstall
npm ERR! > ./index.js
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2023-02-01T19_16_57_467Z-debug-0.log
```

### Additional information:
I have also tried uninstall and deleting pnmp files under which pnmp, but the error remains. 

 - `node -v` prints: Node.js v18.13.0.
 - Windows, macOS, or Linux?: Windows 11

**Comment by zkochan** [comment]
Why do you install pnmp? The package is called pnpm.

**Comment by kangruixiang** [comment]
> Why do you install pnmp? The package is called pnpm.

Great it works now. Thanks lol.
