### ISSUE TITLE
public-hoist-pattern does not work when using node-linker=hoisted

### ISSUE THREAD

**Issue by saibotk** [pnpm/pnpm#6032]
### Code to reproduce the issue: 
.npmrc
```
node-linker=hoisted
```

Install any eslint-config package eg. `@clickbar/eslint-config` which has `eslint-plugin-prettier` as a dependency.

### Expected behavior:
I would have expected that node-linker only changes the way how packages are being referenced in the node_modules folder.
But I can imagine, that this mode is rather a compatibility mode which mimics the behavior of npm etc.

If this is intended, I'd suggest we add that to the documentation, and I would like to propose having another option to just change the way how packages are being linked to node_modules.

Our use case involves certain private packages which need to be included in our git commits. In the best case I would be able to specify only those packages to be hard-linked/copied to the node_modules root folder and all other packages being symlinked as always, but I can imagine that being non-trivial depending on the implemented logic.

Also, the symlink=false option does not seem to work properly with node-linker=hoisted and by itself just leaves the node_modules folder empty. Either that should be documented in a more detailed way or it should only work with node-linker=pnp. 

### Actual behavior:
node_modules folder does not contain publicly hoisted packages, which causes prettier to not find plugins that are a sub-dependency.

### Additional information:

 - macOS 13.2, Linux (GH Action Ubuntu)

**Comment by await-ovo** [comment]
Seems that I can not reproduce this issue. I added `clickbar/eslint-config` in an empty project with `node-linker=hoisted`:
![image](https://user-images.githubusercontent.com/41503212/220059576-7926f53d-d5d6-42cd-a542-4533717ad9c5.png)

You can see that `eslint-plugin-prettier` is hoisted to `node_modules` correctly.

**Comment by saibotk** [comment]
Interesting, maybe I had some other options changed too while testing.

Thank you very much for testing my issue. But since it seems to work in your test i will close this for now as i use another approach now anyways.

Thanks 🙏
