### ISSUE TITLE
Support peer dependencies when symlinking in development

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#604]
In development, when I create a manual symlink or run `npm link` from my app, if my linked module has a peer dependency, using `--preserve-symlink` would allow the linked module to use my app's dependency instead of its local dependency.

Some modules like plugins and frameworks require using a common module instance. But without `--preserve-symlink` there is no way for them to share the same module instance, except by passing the instance of it at runtime.

Pnpm appears to not support `--preserve-symlinks` as it relies on searching for a `node_modules` dir one level up from its realpath to find its development dependencies.

```
package/index.js
package/node_modules <- doesn't exist, but normally would
node_modules/
```

Without `--preserve-symlinks` the search paths would be:

```
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/package/node_modules
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/node_modules <-- local deps first
foo/node_modules/.resolutions/registry.npmjs.org/peer/node_modules
foo/node_modules/.resolutions/registry.npmjs.org/node_modules
foo/node_modules/.resolutions/node_modules
foo/node_modules/node_modules
foo/node_modules/
```

With `--preserve-symlinks` the search paths would be:

```
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/package/node_modules <-- doesn't exist
app/node_modules
```

With symlinking and `--preserve-symlinks` it was possible, but now with this new structure it seems impossible.

I don't see a solution to the peer dep problem without supporting `--preserve-symlinks`. The only other solution is to use a require hack to resolve to the correct modules at runtime.

---

Also, want to note that `NODE_PRESERVE_SYMLINKS` landed in 7.1. https://github.com/nodejs/node/pull/8749

**Comment by vjpr** [comment]
Another issue is that if a module is `npm linked` and it uses a lot of the same dependencies as its parent module, they will be require.cached separately as their dependency cache keys will point to their respective `.resolution` folders.

This means that simply running `npm link` on a single module can dramatically slow down startup time due to the need to eval multiple copies of the same module@version.

**Comment by zkochan** [comment]
Seems like the only solution for your problem is hardlinking instead of symlinking

**Comment by vjpr** [comment]
This is impractical. If a file or folder is added/removed then it needs to be relinked if using hardlinks.

**Comment by zkochan** [comment]
Actions are required anyway in that case.

You have to relaunch the app. There can be some watcher to relink the files

**Comment by vjpr** [comment]
Say you are working on a React component that needs to use the same version of react. You would typically be using hot reloading.

Having a watcher to relink the files would be cumbersome. If you have several projects running at once that are linked, you would need several watchers.

**Comment by zkochan** [comment]
hot reloading reloads on changes in the node_modules folder?

**Comment by vjpr** [comment]
Idea. Could we support `--preserve-symlinks` by creating a symlink 

```
node_modules/
package/node_modules -> ../node_modules
```

---

With --preserve-symlinks the search paths would be:

```
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/package/node_modules <-- would exist
app/node_modules
```

Without --preserve-symlinks the search paths would be:

```
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/package/node_modules <-- symlink to node_modules
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/node_modules <-- same as previous
foo/node_modules/.resolutions/registry.npmjs.org/peer/node_modules
foo/node_modules/.resolutions/registry.npmjs.org/node_modules
foo/node_modules/.resolutions/node_modules
foo/node_modules/node_modules
foo/node_modules/
```

**Comment by vjpr** [comment]
> hot reloading reloads on changes in the node_modules folder?

You can configure it to by modifying some webpack settings.

**Comment by zkochan** [comment]
The change that you are suggesting would have to be on a config, because it would create circular symlinks. And does it worth the additional complexity?

**Comment by vjpr** [comment]
> The change that you are suggesting would have to be on a config, because it would create circular symlinks.

Agree. Or maybe only activated when a symlink is created.

> And does it worth the additional complexity?

I strongly agree! 

- Pnpm would be perfect if it could handle the peer deps use case smoothly, and you will find a lot of people rejoicing at such a solution.

- This is are very common use case that pnpm makes impossible at preset. Pnpm diverges from the traditional `node_modules` structure which breaks `--preserve-symlinks` behaviour. In 7.1 there is an environment variable added which makes me think there is momentum in this direction. Its been 5+ years having this issue with plugin development, and the preserve-symlinks is the best we have right now and it works.

- As pnpm controls what files and folders to hardlink, it would also help workaround the case where a project's peer dep won't be used if it is installed in the plugin's local node_modules (for running unit tests for example).

E.g.

```
foo/node_modules/.resolutions/registry.npmjs.org/peer/4.11.2/package/node_modules/webpack <- this is used when actually we want the project's dep
app/node_modules/webpack
```

**Comment by vjpr** [comment]
So it seems I was using `0.51.1` and now the `package` folder is gone...

**Comment by vjpr** [comment]
So I tried it out by adding the following to `installMultiple.ts#169`:

```
  async function symlinkNodeModules() {
    // console.log({dependency})
    // Add a symlink to node_modules for `--preserve-symlink` compatibility.
    const symlink = path.join(dependency.hardlinkedLocation, 'node_modules')
    // Must point to closest node_modules.
    const findUp = require('find-up')
    let symlinkTarget = findUp.sync('node_modules', {cwd:
      path.resolve(dependency.hardlinkedLocation, '..')
    })
    // const symlinkTarget = '../../node_modules'
    // console.log({symlinkTarget, hl: dependency.hardlinkedLocation})
    symlinkTarget = path.relative(symlink, symlinkTarget)
    symlinkTarget = path.join(symlinkTarget, 'node_modules')
    // console.log({symlinkTarget})
    // console.log('linking %s to %s', symlink, symlinkTarget)
    try {
      // await rimraf(symlink)
      await fs.symlink(symlinkTarget, symlink, 'dir')
    } catch (err) {
      if (err.code === 'EEXIST') {
        // TODO(vjpr): We need to delete it and override it.
        return
      }
    }
  }

  await symlinkNodeModules()
```

It works fine, the only issue is that when using `--preserve-symlinks`, the `require.cache` path is the symlink path which results in a huge number of duplicate package evals.

```
E.g.

# The following path is what is in require.cache.
$ realpath /Users/Vaughan/dev-quantitec/intranav-app/node_modules/babel-preset-live/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-helper-function-name/node_modules/babel-template/node_modules/babel-types/node_modules/babel-runtime/node_modules/core-js/library/modules/core.get-iterator.js

/Users/Vaughan/dev-quantitec/intranav-app/node_modules/.registry.npmjs.org/core-js/2.4.1/node_modules/core-js/library/modules/core.get-iterator.js
```

**Comment by zkochan** [comment]
>> it would create circular symlinks
>
>So it seems I was using 0.51.1 and now (0.53) the package folder is gone.
>
> So now it would be node_modules/foo/node_modules -> ../node_modules which is the cycle as you suggested.
>
>But if we revert back to symlinking to a separate package folder, there would be no cycles.

I don't understand this. If you'll run the app with preserve symlinks, it won't make any difference in what structure the real path is saved. Only the symlinks will be taken into account. So you'll need the node_modules to be inside the package folder.

I don't see any possibility to avoid circular symlinks with pnpm, when node_modules is inside the package folder.

**Comment by vjpr** [comment]
> I don't see any possibility to avoid circular symlinks with pnpm, when node_modules is inside the package folder.

I meant that there would be a path: `node_modules/foo/node_modules/foo` pointing to itself.

Rather than:

```
node_modules
  foo <- not needed
package
  node_modules -> ../node_modules
  index.js
```

**Comment by zkochan** [comment]
I think we might support it. This is about having "singletons" in monorepos. We basically have to have a shared "resolutions store". The idea is similar to [independent-leaves](https://github.com/pnpm/pnpm#independent-leaves) but for all packages, not only those that are w/o dependencies

**Comment by zkochan** [comment]
Closing this in favor of #1001
