### ISSUE TITLE
"pnpm env use --global argon" is confusing for users unfamiliar with Node codenames

### ISSUE THREAD

**Issue by SachaG** [pnpm/pnpm#6056]
This is in reference to the documentation: https://pnpm.io/cli/env

The docs say to run the following commands to "Install the LTS version of Node.js:":

```
pnpm env use --global lts
pnpm env use --global argon
```

I ran both thinking `argon` was some kind of utility required by pnpm to function, not knowing that I was actually selecting an older version of Node. 

I would suggest removing the `argon` line altogether to avoid confusing people.

**Comment by zkochan** [comment]
Moved it to the bottom and added more info about node.js codenames.
