### ISSUE TITLE
"pnpm" property missing from package.json produced by pnpm pack

### ISSUE THREAD

**Issue by theurgi** [pnpm/pnpm#6060]
### Expected behavior:

When a package.json file includes a `pnpm` property, for example: 

```json
{
  "peerDependencies": {
    "eslint": "^7.0.0 || ^8.0.0",
    "svelte": "^3.0.0"
  },
  "peerDependenciesMeta": {
    "svelte": {
      "optional": true
    }
  },
  "dependencies": {
    "eslint-plugin-svelte": "^2.17.0"
  },
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "svelte"
      ]
    }
  }
}
```
the package.json produced by `pnpm pack` should also include the `pnpm` property.

### Actual behavior:

The package.json produced by `pnpm pack` does not include the `pnpm` property and in the example above, the distributed package therefore produces a missing peer dependency warning for `svelte` when installed by the end user.

pnpm does not honor `peerDependenciesMeta.svelte.optional: true` as far as silencing warnings goes.

**Comment by theurgi** [comment]
Omission of the `pnpm` property was merged on Jan 18, 2021 without an explanation as to why: https://github.com/pnpm/pnpm/pull/3081.

And then `pnpm.peerDependencyRules.ignoreMissing` was merged after on Jan 11, 2022: https://github.com/pnpm/pnpm/pull/4212.

It doesn't make sense to me why the `pnpm` property would be removed from the published package.json, unless it's intended for development configuration only; but for a package author who knows certain `peerDependencies` are optional, it makes sense to allow them to silence the warning on the end user's behalf.

This is how `peerDependenciesMeta.<pkg>.optional` works in npm if I'm no mistaken.

**Comment by zkochan** [comment]
> pnpm does not honor peerDependenciesMeta.svelte.optional: true as far as silencing warnings goes.

This is not true. pnpm honours that setting. Warnings are not printed for optional peer dependencies if they are missing. A warning is printed for an optional peer dependency only if the installed svelte does not satisfy the wanted range. This makes sense.

If you don't want warnings for the second case, then you should declare your peer dependencies like this:

```json
{
  "peerDependencies": {
    "eslint": "*",
    "svelte": "*"
  },
  "peerDependenciesMeta": {
    "svelte": {
      "optional": true
    }
  },
```

> Omission of the pnpm property was merged on Jan 18, 2021 without an explanation as to why: https://github.com/pnpm/pnpm/pull/3081.

It doesn't make sense to include this field in the published `package.json` because pnpm only reads those settings in the project's `package.json`
