### ISSUE TITLE
Allow to disable `verify-store-integrity` for specific packages

### ISSUE THREAD

**Issue by pkerschbaum** [pnpm/pnpm#6072]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))
  - would need some guidance but yes :) 

**Describe the user story**

Some TypeScript codebases rely on the package [`ts-patch`](https://www.npmjs.com/package/ts-patch) to allow to use "plugins".  
E.g. a very useful plugin is [`typescript-transform-paths`](https://www.npmjs.com/package/typescript-transform-paths), which allows to replace path aliases by relative paths during compilation (a feature TypeScript does not support OOTB unfortunately).

But, since `ts-patch` changes files of the installed `typescript` package, pnpm keeps redownloading it when it does its store integrity verification.  
This happens quite often when doing a `pnpm install`.

**Describe the solution you'd like**

My idea is to allow to disable integrity verification for certain packages, with patterns similar to how [`public-hoist-pattern`](https://pnpm.io/npmrc#public-hoist-pattern) works.  
Maybe that setting could be called `verify-store-integrity-pattern` and configured for the described use case as:

```properties
verify-store-integrity-pattern[]=*
verify-store-integrity-pattern[]=!typescript
```

**Describe the drawbacks of your solution**

I guess none?  
It is a new feature not changing any existing behavior.

**Describe alternatives you've considered**

- Disabling the integrity verification via CLI param `--no-verify-store-integrity` or the respective [`.nmprc`](https://pnpm.io/npmrc#verify-store-integrity) setting avoids the redownload of `typescript`.  
  Drawback is that this setting disables all of the verification.
- Prepare a version of `typescript` which is already patched using `ts-patch` and install that instead of `typescript`.  
  Drawback is that for every new release of `typescript`, I would need to prepare a new patched version.
- Replace the functionality of `ts-patch` by a patch file which is then applied with `pnpm patch`.
  Drawback is that for every new release of `typescript` or `ts-patch`, I would need to update the patch.

**Comment by zkochan** [comment]
I don't think it is a good idea.

We already have a way to save variations of a package in the store. We currently allow to patch dependencies via the [pnpm patch](https://pnpm.io/cli/patch) command. Dependencies are patched with patch files and saved to the store. I guess it would be relatively easy to support other ways of patching. For instance, using a script.

**Comment by pkerschbaum** [comment]
Oh good point!  
I created #6111 as a follow up and close this issue here.
