### ISSUE TITLE
Issue with @testing-library/jest-dom

### ISSUE THREAD

**Issue by rosergeev** [pnpm/pnpm#6082]
### Code to reproduce the issue:
npm run test

### Additional information:
I'm developing office add-ins using office.js, react, typescript and jest for testing. I have a lot of unit test that use TestingLibraryMatchers, like toBeDisabled() from "@testing-library/jest-dom" package. But after updating pnpm  it's not possible to run tests that use those matchers. I have prepared sample project with settings close to production version. Please, find it in attachment(pnpm-issue-testing-library.zip).

 - `node -v` prints: v16.14.2
 - Windows:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎9/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

[pnpm-issue-testing-library.zip](https://github.com/pnpm/pnpm/files/10721891/pnpm-issue-testing-library.zip)
![success](https://user-images.githubusercontent.com/12766193/218456065-f9ef16e9-3035-4a10-80a2-e49e99a9c295.png)
![fail](https://user-images.githubusercontent.com/12766193/218456087-01f58681-1cbc-4bfc-9c2f-40b844a76524.png)

**Comment by mcmxcdev** [comment]
Run `pnpm i @types/testing-library__jest-dom -D`, which should fix it. We encountered the same problem, not sure what the oriign of the problem is..

**Comment by rosergeev** [comment]
Thank you for the hint, will try tomorrow.

**Comment by rosergeev** [comment]
It worked perfectly, but brought another issue with mocked objects that resides in global and those issues were fixed by changing global to globalThis. 
Thanks a lot, @mcmxcdev !!!

**Comment by mcmxcdev** [comment]
Glad you were able to fix it :)

I think its more likely a `@testing-library/jest-dom` issue rather than with pnpm issue since I haven't seen this happening for other dependencies which are written in JS and are depending on a corresponding `@types` package.
