### ISSUE TITLE
MISSING_HOISTED_LOCATIONS error thrown for skipped dependencies

### ISSUE THREAD

**Issue by douglasward** [pnpm/pnpm#6092]
When using `node-linker=hoisted` the `MISSING_HOISTED_LOCATIONS` error (added by https://github.com/pnpm/pnpm/pull/5819) is thrown if a skipped dependency is missing in the hoisted locations in `node_modules/.modules.yaml`.

This makes it impossible to have a successful install.

### Expected behavior:

Skipped dependencies should not be taken into account for the `MISSING_HOISTED_LOCATIONS` error.

### Actual behavior:

The `MISSING_HOISTED_LOCATIONS` is thrown.

### Additional information:

Line where error is thrown: https://github.com/pnpm/pnpm/blob/v7.26.3/exec/plugin-commands-rebuild/src/implementation/index.ts#L283

If something like the following is added in the line above then the install succeeds as expected:

```js
regx = new RegExp(pkgInfo.name, 'i');
if (Array.from(ctx.skipped).some(name => regx.test(name))){
  return;
}
```

 - `node -v` prints: v16.17.1
 - Windows, macOS, or Linux?: macOS

**Comment by brentdurksen** [comment]
This is blocking our deployment of pnpm. We are using `node-linker=hoisted` in .npmrc to support Meteor, and optional dependency `fsevents` (macOS specific) blocks `pnpm install` on non-macOS operating systems, specifically Linux. We are receiving the same MISSING_HOISTED_LOCATIONS error as documented above.
