### ISSUE TITLE
Conflict between 'corepack' and 'pnpm env'.

### ISSUE THREAD

**Issue by akihironagai** [pnpm/pnpm#6095]
### Code to reproduce the issue:
```
# Requires: Node
corepack enable
corepack prepare pnpm@latest --activate
pnpm env use --global 16
```

### Expected behavior:
There is no error.

### Actual behavior:
```
ERR_INVALID_ARG_TYPE  The "path" argument must be of type string. Received undefined

pnpm [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:1098:7)
    at getNodeExecPathInBinDir (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:71795:29)
    at envUse (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:108143:56)
    at async /root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217519:21
    at async main (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217488:34)
    at async runPnpm (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217718:5)
    at async /root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217710:7
```

### Additional information:

 - `node -v` prints: v18.14.0
 - Windows, macOS, or Linux?: Linux (Docker: 'node:18')

https://github.com/nodejs/corepack/issues/236

**Comment by zkochan** [comment]
How have you initially installed Node.js? Have you installed pnpm first and then installed Node.js? I don't think you should be able to install a different version of Node.js if it wasn't pnpm that installed the current Node.js. Maybe we should print a meaningful error message in this case.

**Comment by akihironagai** [comment]
I installed Node directly **without** pnpm.
I also used Node Docker Image.

pnpm from corepack should disable 'pnpm env'.

<img width="1136" alt="For example" src="https://user-images.githubusercontent.com/77012577/219543880-62b201b6-6ec5-4bb6-82b9-c2c06d4b1836.png">

**Comment by aduh95** [comment]
FYI `pnpm` could check if `COREPACK_ROOT` is set to detect it's being run from Corepack.
