### ISSUE TITLE
pnpm i linking to non-existent package when

### ISSUE THREAD

**Issue by rxliuli** [pnpm/pnpm#6118]
### Code to reproduce the issue:

When executing `pnpm i @types/@gera2ld/tarjs`, the dependency `"tarjs": "link:@types/@gera2ld/tarjs"` will be added, there are two problems here

1. @types/@gera2ld/tarjs does not seem to be a legal npm package name, why it can be parsed and executed successfully
2. After pnpm i, there is only one empty file under node_modules because @types/@gera2ld/tarjs cannot be found

### Expected behavior:

The correct behavior should be that an error should be thrown when installing such a non-existing package?

### Additional information:

 - `node -v` prints: v18.14.0
 - Windows, macOS, or Linux?: macOS m2

**Comment by await-ovo** [comment]
Could we [throw a meaningful error ](https://github.com/pnpm/pnpm/blob/main/resolving/local-resolver/src/index.ts#L58)just on `pnpm add` If the linked local path does not have a manifest: 

![image](https://user-images.githubusercontent.com/41503212/221160136-276e1562-aa30-4d08-85e1-d6ca994563c3.png)


I'm not sure if issues that have been fixed before will reappear, such as https://github.com/pnpm/pnpm/pull/3983 and https://github.com/pnpm/pnpm/pull/5125

cc @zkochan

**Comment by zkochan** [comment]
No, we don't have to throw an error in this case. It works as expected.
