### ISSUE TITLE
add a remove patch command

### ISSUE THREAD

**Issue by btea** [pnpm/pnpm#6119]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**
When a dependent package has a problem and is not updated in time, we will directly modify the source code and generate a patch file. That's fine at this point, but when this dependency fixes the problem and a new version is released, I'll install the new version. At this point, both the generated pacth file and `patchedDependencies` need to be removed. I think it would be more friendly to provide a command to remove them all.

**Describe the solution you'd like**

Commands like `pnpm remove --patch`

**Comment by syabro** [comment]
Or `pnpm patch --remove`
