### ISSUE TITLE
 ERR_PNPM_META_FETCH_FAIL 

### ISSUE THREAD

**Issue by bobbyrahmanda13** [pnpm/pnpm#6121]
![Screenshot_2023-02-22-11-42-09-418_com termux](https://user-images.githubusercontent.com/69358107/220523902-a3c95b8d-f43f-472d-b14e-ff68453fba8c.jpg)

error pnpm install using termux but i am using npm its work

**Comment by bobbyrahmanda13** [comment]
![Uploading Screenshot_2023-02-22-11-48-25-719_com.termux.jpg…]()

**Comment by zkochan** [comment]
It worked for me with pnpm as well. Maybe it was a temporary registry issue.

**Comment by musagenius345** [comment]
I'm facing the same problem with termux. @bobbyrahmanda13 how did you solve it.

**Comment by bobbyrahmanda13** [comment]
@musagenius345 I didn't use Termux but used a computer, since then I don't use Termux anymore

**Comment by taeuscherpferd** [comment]
@musagenius345 I know this is a closed issue, and over a year old already, but I did actually get this working in case any other `termux` users happen to stumble in here. I got the above error when installing `pnpm` using curl, so I followed the guide provided by `pnpm` on uninstalling `pnpm`, then I ran the following 2 commands in `termux`

`corepack prepare pnpm@latest --activate`
`npm i -g pnpm@latest`

I don't know if running `corepack` is necessary or if it just works better on Android installing it via `npm`, but it's working now, and hopefully it'll help someone else down the line as well 👍
