### ISSUE TITLE
pnpm up: support scope or glob for target packages

### ISSUE THREAD

**Issue by unional** [pnpm/pnpm#6125]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

There are many apps/tools has packages that are released together, e.g. `jest`, `commitlint`, `eslint`, etc.

Right now we need to update them manually: `pnpm up jest jest-environment-jsdom ...`.

In a monorepo, right now Ihave to do that one by one, and/or go to each individual packages and see if I'm missing something.

And as I'm doing that, I might as well using IDE and edit the package.json files directly and run `pnpm i` afterwards.

It would be great if they are be all updated in one go: `pnpm up jest*` or `pnpm up -r --target-glob=jest*`

**Describe the drawbacks of your solution**

Need to find a good option for it. `pnpm` already have `--filter` for workspace packages.

**Comment by zkochan** [comment]
It is already [supported](https://pnpm.io/cli/update#selecting-dependencies-with-patterns).

This will work:

```sh
pnpm -r up "jest*"
```
