### ISSUE TITLE
`pnpm install --frozen-lockfile` updates modified time of  `pnpm-lock.yaml` and root dir each time it runs even without changes

### ISSUE THREAD

**Issue by artur-ptaszek-mck** [pnpm/pnpm#6158]
### Code to reproduce the issue:

It happens in any project regardless of packages in it. `package.json` has only `rimraf` as a dependency.
```
~/Projects/pnpm-bug-report
➞  stat pnpm-lock.yaml
16777220 104927827 -rw-r--r-- 1 artur_ptaszek staff 0 296 "Mar  1 15:13:12 2023" "Mar  1 15:13:11 2023" "Mar  1 15:13:11 2023" "Mar  1 15:13:11 2023" 4096 8 0 pnpm-lock.yaml

~/Projects/pnpm-bug-report
➞  pnpm install --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 393ms

~/Projects/pnpm-bug-report
➞  stat pnpm-lock.yaml
16777220 104927846 -rw-r--r-- 1 artur_ptaszek staff 0 296 "Mar  1 15:13:26 2023" "Mar  1 15:13:24 2023" "Mar  1 15:13:24 2023" "Mar  1 15:13:24 2023" 4096 8 0 pnpm-lock.yaml
```

### Expected behavior:
If `pnpm` reponse with `Already up to date`, then shouldn't affect both root catalog and `pnpm-lock.yaml` in any kind.

### Actual behavior:
`pnpm install --frozen-lockfile` updates modified time of  `pnpm-lock.yaml` and root dir each time it runs even without changes.

### Additional information:

 - `node -v` prints: v18.14.0
 - Windows, macOS, or Linux?: macOS

**Comment by Macariel** [comment]
Happens on Linux as well. 
Downgrading to 7.27.0 fixes the problem. 
Unfortunately this small change results in an endless loop for us, as we have file watchers on this file, which in turn call `pnpm install --frozen-lockfile` again :see_no_evil:

**Comment by egg-r** [comment]
We started noticing this too and reverted back to a previous version.  This caused Warnings with caching tasks used in our Azure DevOps pipelines as the Key (hash of the lockfile) changed between start and finish.

**Comment by artur-ptaszek-mck** [comment]
I checked with the latest `v7.30.0`. Issue still exists.
