### ISSUE TITLE
`pnpm i -g pnpm`, then `npm i -g`, then `pnpm link -g` will install unexpected pnpm version

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#616]
This is a bit of an edge case, but if you have pnpm installed with pnpm, and then override it with npm, the next time you run a `pnpm link -g` from any project, the pnpm version will change underneath you. Its rather unexpected and caught me out a few times.

The workaround is just to only install pnpm with npm.

### Code to reproduce the issue:

```
npm i -g pnpm@0.53.0
pnpm i -g pnpn@0.54.0
npm i -g pnpm@0.53.0
cd foo
pnpm link -g # <- this overrides npm's pnpm version with the pnpm one previously installed.
pnpm -v
```

### Expected behavior:

Because it was the last version we installed.

```
0.53.0
```

### Actual behavior:

This is the version that was installed with pnpm.

```
0.54.0
```

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
This is not an issue with pnpm v7 as we don't pollute npm's global bin directory anymore.
