### ISSUE TITLE
Allow for a way to configure skipping package.json name check

### ISSUE THREAD

**Issue by Aghassi** [pnpm/pnpm#6172]
https://github.com/pnpm/pnpm/blob/b7ae11cf821212ac716672d00a4ccbe5a9f59190/pkg-manifest/read-package-json/src/index.ts#L10

I ran into this and I know I'm in an edge case but I wanted to post this publicly for sake of discussion

I'm working in a monorepo and we don't publish our npm packages, so name accuracy is a little less important to us vs ergonomics of importing. This line will throw if you have `@scope/path/to/folder` as the name. While this is not technically an "npm friendly" name, it is an ergonomically nice name for internal employees trying to understand where the import is coming from in the monorepo.

Would you be open to a PR where there is an rc setting or otherwise to skip this check so that we can have a "not ok" name and pnpm won't error on install?

**Comment by zkochan** [comment]
Why don't you just use dots instead of slashes to remain compatible with npm?

This convention is also used by Bit components. See for instance this component: https://bit.cloud/teambit/design/ui/input/radio

The component ID is `teambit.design/ui/input/radio` but the package name is `@teambit/design.ui.input.radio`

**Comment by Aghassi** [comment]
I guess technically I can do that. The nice thing is that we have a link shortener internally that will take `repo/path/to/thing` and just expand it to the github address so I'm thinking it makes it easer. I can also do dots, just requires one extra step if folks want to look up the code because you can't copy paste. It's more of an ergonomics problem at that point then anything else. I'll check this out Monday for sure. Happy to discuss, didn't know bit did that

**Comment by Aghassi** [comment]
Yeah I can't change the link on the fly to change dots to `/`, so that's a shame. But I'll close this for now since you clearly have the same issue and have cited a reasonable workaround.
