### ISSUE TITLE
pnpm install with artifactory (behind proxy)

### ISSUE THREAD

**Issue by Alexgalinier** [pnpm/pnpm#618]
### Additional information:

 - `node -v` prints: v6.9.1
 - Windows, OS X, or Linux?: OS X

Hello,

First, great job for this package, at home it's blazzing fast!

But at the office i have a proxy (not sure if it is the problem for once) and an Artifactory server. My `npm install`works well so i know that my `.npmrc` in HOME directory is well configured.
I've checkout your code but could not find where to look.

The call to `pnpm install` ends with
ERROR Registry returned 401 for GET on http://artifactory...
So the call goes to Artifactory server, then maybe some other configuration (to authenticate the user, the value of `_auth` in `.npmrc` is used) are not passed correctly.

Do you want to do something else to provide more info?

Regards

**Comment by iamstarkov** [comment]
what kind of artifact storage solution do you use?

**Comment by Alexgalinier** [comment]
It s Artifactory from JFrog, with a simple npm module which acts as a proxy to npm registry. It looks for local modules (cache ans homemade) then remote ones.

**Comment by zkochan** [comment]
We use the same package for downloading the packages that npm uses.

So probably it is an authentication issue.

We use this package for getting the tokens: https://github.com/rexxars/registry-auth-token

@rexxars, @leipert maybe you have some ideas what the issue could be here?

**Comment by rexxars** [comment]
I'd need some more debug info to figure it out. How does the npm config look? Is the authorization info sent to Artifactory at all? Is `always-auth` set to true or false in npmrc?

**Comment by Alexgalinier** [comment]
Yes it's set to true, here it is:

```
_auth=base64AuthKey
always-auth=true
email=username@company.com
strict-ssl=false
registry=http://domain/artifactory/api/npm/npm-repo
progress=false
```

To be honest i've not checked what is sent to artifactory. As it's done by `npm install` i hoped for the same behavior with `pnpm install`. Tell me if you need something else.

**Comment by zkochan** [comment]
@Alexgalinier seems like using the `_auth=base64AuthKey` is a legacy way of specifying the auth token.

You can try this configuration: `//domain/artifactory/api/npm/npm-repo:_authToken=base64AuthKey`

But I guess we can support the legacy way as well. It should be implemented in https://github.com/rexxars/registry-auth-token though

**Comment by Alexgalinier** [comment]
Sounds good to me.
I can't ensure you it works, i had to move on and use an other tool. We have changed our artifactory now so i can't re-produce it. I'll close and hope it will help others if you support this legacy way.

Thx

**Comment by destroyerofbuilds** [comment]
Related https://github.com/rexxars/registry-auth-token/pull/17

**Comment by rommik** [comment]
I have the same issue as described above. (I'm not sure if there's a proxy between me and the Artifactory Repository)

```
pnpm -v
5.4.0

npm -v
6.14.5
```

.npmrc looks like this

```
@privateNameSpace:registry=https://bin.my-company.com/artifactory/api/npm/npm-local
_authToken=c2Vydmlj(....)DJpR2tBVVEx
always-auth = true
email = email@my-company.com
```
`pnpm add @privateNameSpace/packageName`

I get

```
401 Unauthorized: @privateNameSpace/packageName (via https://bin.my-company.com/artifactory/api/npm/npm-local/@privateNameSpace%2FpackageName)
```

`npm i @privateNameSpace/packageName` 

works as expected
