### ISSUE TITLE
`ERR_PNPM_PATCH_NOT_APPLIED ` error when the subproject has patch dependencies

### ISSUE THREAD

**Issue by SoonIter** [pnpm/pnpm#6183]
### Code to reproduce the issue:

1. `git clone https://github.com/SoonIter/pnpm-reproduction-patch-block`

2. `pnpm install`

```
├── node_modules
├── package.json
├── packages
│   └── a
│       ├── node_modules
│       └── package.json  -->>  @dagrejs/graph@2.1.11
├── patches
│   └── @dagrejs__graphlib@2.1.11.patch
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```

3. modify `package.json` and add one line dependency

4. rerun `pnpm install` and meet the error

### Expected behavior:

install normally and do not block the whole process

### Actual behavior:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/79413249/222982558-1f3bc107-f74a-4eb7-8a47-48f0098199c3.png">

**Comment by technophile-04** [comment]
Hey guys the solution in #6183 dosen't seem to solve the problem if you have `shared-lock-files = false` in `.npmr`, I have created an issue at #6885
