### ISSUE TITLE
ENOENT: no such file or directory, rename node_modules/.pnpm/lock.yaml.2711593961' -> node_modules/.pnpm/lock.yaml

### ISSUE THREAD

**Issue by colinaaa** [pnpm/pnpm#6191]
### pnpm version:

7.25.0

### Code to reproduce the issue:

This error happens occasionally in our macOS CI environment. Can not reproduce on local devices.

### Expected behavior:

No error occurred.

### Actual behavior:

An error occurred:

```
Scope: 7 of 21 workspace projects
Lockfile is up to date, resolution step is skipped
ENOENT  ENOENT: no such file or directory, rename '/Users/Cda226_nfm_zmala/11032/node_modules/.pnpm/lock.yaml.2711593961' -> '/Users/Cda226_nfm_zmala/11032/node_modules/.pnpm/lock.yaml'
```

Which causes pnpm install to fail.

### Additional information:

There are parallel `pnpm install` with different filters being executed.

 - `node -v` prints: v16.18.1
 - Windows, macOS, or Linux?: **macOS**

**Comment by zkochan** [comment]
Why do you run multiple `pnpm install` in parallel?

Regarding this error, it probably can be replaced with a warning that won't make pnpm crash.

**Comment by colinaaa** [comment]
Indeed, we should not run multiple `pnpm install`.

We are doing this because we have two separate packages that are built in parallel. In each building phase, will run `pnpm install` with different filters. We have changed to a single `pnpm install` to avoid the error, but it would be great to replace the error with a warning that won't make pnpm crash.
