### ISSUE TITLE
pnpm patch doesn't work

### ISSUE THREAD

**Issue by tjx666** [pnpm/pnpm#6192]
### Code to reproduce the issue:

repo: https://github.com/tjx666/pnpm-patch-issue

1. `git clone git@github.com:tjx666/pnpm-patch-issue.git`
2. `pnpm install`
3. `pnpm patch @jspm/generator`
4. `pnpm patch-commit /private/var/folders/xxxxxxxx`

### Expected behavior:

No error

### Actual behavior:

![image](https://user-images.githubusercontent.com/41773861/223390368-37c4a996-3648-46c5-aa44-967f691f3738.png)

### Additional information:

```
  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 209.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/Library/Caches/fnm_multishells/62548_1678183298864/bin/node
```

**Comment by await-ovo** [comment]
Did you try `pnpm patch @jspm-generator@1.0.0-beta.38`?

Currently we need to specify the version of the patch package to avoid errors when the version at apply-patch does not match the actual installed version.

It feels like pnpm should get the actual installed version from the lockfile, if we don't specify the version.

**Comment by tjx666** [comment]
@await-ovo Yes, it works after specify version
