### ISSUE TITLE
Hide `dlx` Output

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#6198]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I'd like to hide the output of the `dlx` (`pnpx`) command. For example, this is the output from a few `pnpx` calls, and it's neither helpful nor informative in the context we're running it. At best it's distracting.

```
→ pnpx nx build svc
.../Library/pnpm/store/v3/tmp/dlx-16795  | +124 ++++++++++++
.../Library/pnpm/store/v3/tmp/dlx-16795  | Progress: resolved 132, reused 124, downloaded 0, added 124, done

> nx run svc:prebuild

.../Library/pnpm/store/v3/tmp/dlx-16812  | Progress: resolved 1, reused 0, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-16812  | Progress: resolved 48, reused 48, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-16812  | Progress: resolved 87, reused 87, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-16812  | Progress: resolved 90, reused 90, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-16812  | Progress: resolved 93, reused 93, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-16812  | +100 ++++++++++
.../Library/pnpm/store/v3/tmp/dlx-16812  | Progress: resolved 100, reused 100, downloaded 0, added 100, done

```

**Describe the solution you'd like**

`npx` outputs no dependency information by default. I would like that as a solution.

**Describe the drawbacks of your solution**

Can't think of any.

**Describe alternatives you've considered**

None at present

**Comment by zkochan** [comment]
ok

**Comment by shellscape** [comment]
I'm actually going to close this one. I failed to grok that `pnpm exec` and `pnpm dlx` had diverged from the old "if it's in path, run it, otherwise download it" that `pnpx` used, hence the use of `dlx` for all the things instead of `exec`, which lead to the frequent output we were seeing. My take is that if `dlx` is used, then the user should expect to see that output.
