### ISSUE TITLE
add destination option to patch-commit command

### ISSUE THREAD

**Issue by taozhou-glean** [pnpm/pnpm#6202]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

For monorepo, its pretty common that we may want the pnpm patches go to a different folder rather than the default `patches` next lock file (current approach)

**Describe the solution you'd like**

similar to `--edit-dir` for `patch` command, we can add `--patch-dir` for `patch-commit` command, just like the arg used for `patch-package` (https://www.npmjs.com/package/patch-package)

**Describe the drawbacks of your solution**

for our use case, right now we have to move the generated patch file manually and also update the corresponding entries in package.json, which is a bit inconvenient... even for an action that does not occur too often

**Comment by taozhou-glean** [comment]
actually I just realized that we do support `--dir` and `--lockfileDir` when looking at the code, which will be used when determine the patch destination, but also that has to be the same place for project manifest, which is not the case for us :( so either allow pass in the destination or path to the project manifest can help this case:

```
```

**Comment by zkochan** [comment]
I don't have objection to support custom location for the patch files.
