### ISSUE TITLE
overriding a dependency more than once

### ISSUE THREAD

**Issue by joelmoss** [pnpm/pnpm#6210]
### pnpm version:
7.29.1

### Code to reproduce the issue:

```json
{
  "pnpm": {
    "overrides": {
      "prop-types": "$prop-types",
      "eslint-plugin-react>prop-types": "npm:prop-types"
    }
  }
  "dependencies": {
    "prop-types": "github:joelmoss/prop-types#esm"
  }
}
```

### Expected behavior:

I would expect that all dependencies will use prop-types from `github:joelmoss/prop-types`, except for eslint-plugin-react, which should use prop-types from `npm:prop-types`.

### Actual behavior:

But instead, all dependencies use prop-types from `github:joelmoss/prop-types`

It appears that only the `"prop-types": "$prop-types"` is respected, while the remaining is ignored.

### Additional information:

 - `node -v` prints: v19.7.0
 - Windows, macOS, or Linux?: macOS

**Comment by toimc** [comment]
same here.
