### ISSUE TITLE
Sub-dependencies cannot be found after updating pnpm from 7.29.1 to 7.29.2

### ISSUE THREAD

**Issue by Leksat** [pnpm/pnpm#6213]
### pnpm version:

7.29.2

### Code to reproduce the issue:

https://github.com/Leksat/pnpm-7.29.2-issue

### Expected behavior:

The `build` script works. See https://github.com/Leksat/pnpm-7.29.2-issue/actions/runs/4413954837/jobs/7735055980 (with pnpm@7.29.1)

### Actual behavior:

The `build` script fails because sub-dependencies (e.g. `babel-preset-env`) cannot be found. See https://github.com/Leksat/pnpm-7.29.2-issue/actions/runs/4413954837/jobs/7735056231 (with pnpm@7.29.2)

### Additional information:

 - `node -v` prints: v18.14.0
 - Windows, macOS, or Linux?: macOS (locally) and Linux (GitHub CI)

**Comment by fireairforce** [comment]
the same issue for vitest: https://github.com/vitest-dev/vitest/issues/3009

**Comment by DoubleRayWang** [comment]
the same problem

**Comment by MartinX3** [comment]
Thank you for the report, now I know that I didn't fucked up my own project and save time. :D

**Comment by await-ovo** [comment]
did this related to extend-node-path? I set extend-node-path=true on the repo you provided,looks like build works fine.

**Comment by Leksat** [comment]
@await-ovo shouldn't it be true by default? https://pnpm.io/npmrc#extend-node-path

**Comment by zkochan** [comment]
I have downgraded latest to v7.29.1 for now.

**Comment by MartinX3** [comment]
If I set `extend-node-path=true` I get
```
│  FATAL  The "name" argument must be specified
│   at new NodeError (node:internal/errors:399:5)
│   at Performance.mark (node:internal/perf/performance:125:13)
│   at ModuleContainer.normalizedModule (node_modules/.pnpm/@nuxt+kit@3.3.0/node_modules/@nuxt/kit/dist/index.mjs:168:30)
│   at async ModuleContainer.addModule (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:167:20)
│   at async ModuleContainer.ready (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:34:7)
│   at async Nuxt._init (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:342:5)
│  ERROR  The "name" argument must be specified
│   at new NodeError (node:internal/errors:399:5)
│   at Performance.mark (node:internal/perf/performance:125:13)
│   at ModuleContainer.normalizedModule (node_modules/.pnpm/@nuxt+kit@3.3.0/node_modules/@nuxt/kit/dist/index.mjs:168:30)
│   at async ModuleContainer.addModule (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:167:20)
│   at async ModuleContainer.ready (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:34:7)
│   at async Nuxt._init (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:342:5)
```

**Comment by zkochan** [comment]
:ship: 7.29.3

**Comment by Leksat** [comment]
It works 🎉 https://github.com/Leksat/pnpm-7.29.2-issue/actions/runs/4425468120

Thank you for the quick fix!

**Comment by Hurtak** [comment]
I can also confirm that .3 fixes the issue 
![image](https://user-images.githubusercontent.com/6587821/225308973-6ce67111-b250-4252-8609-402f321891d7.png)


https://github.com/Hurtak/vitest-bug-repro/actions/runs/4426277097/jobs/7762372120
