### ISSUE TITLE
Attempting to run `pnpm setup` in a docker-container results in a ERR_PNPM_UNKNOWN_SHELL error

### ISSUE THREAD

**Issue by trm217** [pnpm/pnpm#6217]
### Code to reproduce the issue:
Create a docker file with this content and attempt to build the image

```
FROM node:18.15-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app
# Install pnpm
RUN corepack enable && corepack prepare pnpm@7.29.0 --activate

RUN mkdir -p ~/.pnpm/store
ENV PNPM_HOME ~/.pnpm/store
RUN pnpm setup

RUN pnpm i -g turbo
```

### Expected behavior:

I'd like to be able to install pnpm using any of the given install methods without having to manually configure anything for global installations. Provide a plausible base setup that can be adapted via the env-vars if needed. Regular installations should not require any further setup.

### Actual behavior:

Try to run a global installation in a Node.js Alpine image using pnpm

In order to install a global dependency first we must manually set the PNPM_HOME env-variable (not very nice, don't have to do that for any other node package manager). But then when you try to run `pnpm setup` to setup the PNPM_HOME, you'll get the error:

```
#20 1.290  ERR_PNPM_UNKNOWN_SHELL  Could not infer shell type.
------
executor failed running [/bin/sh -c pnpm setup]: exit code: 1
```

Setting the SHELL env-var or anything like that doesn't work either.

### Additional information:

 - `node -v` prints: 
 - Windows, macOS, or Linux?: docker container

**Comment by shellscape** [comment]
I'm running into this but in a different context; a github worklow:

```yaml
      - name: Enable Corepack
        id: pnpm-setup
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm config set script-shell "/usr/bin/bash"
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
          
      - name: Install Nx 😢
        run: |
          pnpm setup
          pnpm add nx -g
```

What's troubling is that I'm explicitly telling pnpm which shell to use but it's still throwing the error. It seems that something inside `pnpm setup` isn't playing as expected.

**Comment by zkochan** [comment]
If you want to tell `pnpm setup` the shell, then you need to set the SHELL env variable.

**Comment by shellscape** [comment]
@zkochan if `pnpm config set script-shell "/usr/bin/bash"` is called, why wouldn't pnpm look to that as a fallback?

**Comment by trm217** [comment]
I have no reverted to just installing globals with yarn or npm respecitvely. Not what I wanted, but I suppose it's good enough.

**Comment by arimgibson** [comment]
The docs linked by @DubKF for Alpine have been removed, not totally sure why as it wasn't working for me without these steps. You can find the instructions in old commits on the docs repository.

https://github.com/pnpm/pnpm.io/blob/5b4bf49153652a01215d18c2ba4af948de3e6ea2/versioned_docs_archived/version-7.x/installation.md?plain=1#L33

**Comment by karlhorky** [comment]
I also got pnpm installed on Alpine Linux using `get-pnpm`:

- https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
