### ISSUE TITLE
pnpm install fails with `JavaScript heap out of memory`

### ISSUE THREAD

**Issue by tilman** [pnpm/pnpm#6227]
### pnpm version:
7.29.0

### Code to reproduce the issue:
.npmrc
```
node-linker=hoisted
```
package.json
```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "dependencies": {
    "@codemirror/view": ">=6.0.0",
    "@strapi/plugin-i18n": "4.8.2",
    "@strapi/plugin-users-permissions": "4.8.2",
    "@strapi/strapi": "4.8.2",
    "codemirror": "^6.0.1",
    "koa": ">=2.13.1 <3.0.0",
    "pg": "^8.10.0",
    "react": ">=17.0.2 <18.0.0",
    "react-dom": ">=17.0.2 <18.0.0",
    "react-is": ">= 16.8.0",
    "react-router-dom": "5.3.4",
    "strapi-neon-tech-db-branches": "^0.1.6",
    "strapi-plugin-comments": "^2.2.8",
    "styled-components": "5.3.3",
    "typescript": "^4.9.5"
  }
}

```
### Expected behavior:
pnpm install fails with: `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

### Actual behavior:
pnpm install should finish and should consum less memory

### Additional information:
 - `node -v` prints: v18.0.0
 - Windows, macOS, or Linux?: macOS arm64

The Problem can be fixed with `export NODE_OPTIONS=--max_old_space_size=8192`.
But then it will resolve with a many packages:
```
Progress: resolved 1377, reused 1355, downloaded 0, added 0
Packages: +611034
```
**611034 Packages** seems a lot for so few dependencies so I guess this is a Bug or some kind of infinity loop?

**Comment by zkochan** [comment]
Looks like you can avoid this issue by setting `dedupe-peer-dependents=true`

By the way, this setting will be `true` by default in v8, so this is a good solution.

But of course we can also try to find out why exactly this fails.

**Comment by tilman** [comment]
Thanks! this solved my issue :)

**Comment by zkochan** [comment]
I think we should still try to fix it with `dedupe-peer-dependents=false` too.

**Comment by await-ovo** [comment]
For the provided `package.json` and `.npmrc`. I tried to add a concurrency limit(16) [here](https://github.com/pnpm/pnpm/blob/main/pkg-manager/headless/src/lockfileToHoistedDepGraph.ts#L203):

```
 try {
          await fetchDepsLimit(async () => {
            fetchResponse = opts.storeController.fetchPackage({
              force: false,
              lockfileDir: opts.lockfileDir,
              ignoreScripts: opts.ignoreScripts,
              pkg: pkgResolution,
              expectedPkg: {
                name: pkgName,
                version: pkgVersion,
              },
            });
            if (fetchResponse instanceof Promise)
              fetchResponse = await fetchResponse;
          });
        } catch (err: any) {
          // eslint-disable-line
          if (pkgSnapshot.optional) return;
          throw err;
        }
```

and it seems that the out of memory problem is solved, but for some reason the linking process is too slow:

```
Packages: +591406
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/await-ovo/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1383, reused 1362, downloaded 0, added 11898
```
> I've been waiting for at least 3min

I don't know if this is a known problem, or where it is caused.

**Comment by ChanFerris** [comment]
how to set max_old_space_size with pnpm install,just like:
pnpm i --config.max_old_space_size=4096 was not work.
