### ISSUE TITLE
依赖使用git url + semver，解析失败

### ISSUE THREAD

**Issue by owen1011** [pnpm/pnpm#6228]
### pnpm version:
6.34.0

### Code to reproduce the issue:
![image](https://user-images.githubusercontent.com/45360528/225843362-f6f292ac-797e-4a08-9f36-6c16ba0853ed.png)
![image](https://user-images.githubusercontent.com/45360528/225843466-1b0876ef-07d3-400a-bd71-de60f61d027f.png)

### Expected behavior:
能正确识别出我是要^1.0.0版本的依赖

### Actual behavior:
它认为我是要/^1.0.0版本的依赖

### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
Maybe this is related https://github.com/pnpm/pnpm/pull/6239

**Comment by owen1011** [comment]
> Maybe this is related #6239

多少版本可以正常使用，我希望在6上能使用

**Comment by zkochan** [comment]
It is fixed in v7.30.1
