### ISSUE TITLE
`pnpm install` randomly change pnpm-lock.yaml on every run

### ISSUE THREAD

**Issue by xieyuheng** [pnpm/pnpm#6229]
To reproduce this bug, run `pnpm install` on any repo.

```
pnpm --version
7.29.3
```

related:

- https://stackoverflow.com/questions/74599589/pnpm-installations-cause-pnpm-lock-yaml-file-to-update-each-time

**Comment by prantlf** [comment]
I don't see this behaviour in my projects. It might depend on the NPM dependencies. You might want to provide a testing repository demonstrating the problem.

As a workaround, you could try command-line arguments `--frozen-lockfile --no-verify-store-integrity`, which are implied in build pipelines that set the environment variable `CI`:

    pnpm i --frozen-lockfile --no-verify-store-integrity

## Details

Although it'd be nice if the package lock contents were always exactly the same, if versions of all deep dependencies remain the same, it might not be so important. Usually, you have one of the two scenarios:

1. Add, remove or update a dependency. Naturally, updates the package lock.
2. Install dependencies. Naturally, only reads the package lock.

NPM users usually run the two following commands:

1. `npm i` - add/update/install dependencies and update the package lock
2. `npm ci` - install dependencies and leave the package lock intact

PNPM users use `pnpm i` for both. If you want to enforce the read-only behaviour in the second scenario, you can add the command-line arguments `--frozen-lockfile --no-verify-store-integrity`. It will not wipe out the `node_modules` directory, but you can do it by another command and fully simulate the behaviour of `npm ci`:

    rm -rf node_modules
    pnpm i --frozen-lockfile --no-verify-store-integrity

I think that I saw some developers asking for `pnpm ci` as an abbreviation of the commands above, but the author of PNPM has been resisting :-)

**Comment by xieyuheng** [comment]
@prantlf Thanks for the command-line arguments, they solve the problem :)
