### ISSUE TITLE
Option: --no-parallel or --parallel-limit=<num>

### ISSUE THREAD

**Issue by Jason3S** [pnpm/pnpm#6237]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a user of `pnpm`, I would like to be able to limit the number of scripts running in parallel. This is especially a problem for monorepos. 

At the root, `pnpm test` when used with `vitest` in each package on an 8 core system can cause 64 processes to get started, causing the machine to get bogged down and things to run very slowly.

As a user, I would rather have `pnpm test` run one packages at a time and allow `vitest` to run as fast as possible. This is because, generally, I'm working within a single package and will run tests often. So that needs to be optimized. But I do not have a need to run tests in many packages at once.

It is possible to limit `vitest` to a single process, but then that introduces different testing scripts.

**Describe the solution you'd like**

I would like to be able to run: `pnpm run -r -stream --parallel-limit=1 test`.

**Describe the drawbacks of your solution**

I'm not coming up with any, considering it is an opt-in limit. As a limit, it doesn't suffer from someone specifying too many `--parallel-limit=1000` would just have the current behavior assuming there are less than 1000 CPUs.

**Describe alternatives you've considered**

The workaround is to create a new "test" script in each package that limits `vitest` to a single process. This is painful and adds to maintenance load in addition to introducing multiple ways to run tests adding to project entropy.

**Comment by await-ovo** [comment]
Can `pnpm -r  --workspace-concurrency= 1 run test ` solve this problem?

**Comment by rrosenshain-sc** [comment]
@await-ovo  does this also works when using `pnpm --filter [since]` without `-r`?
