### ISSUE TITLE
`pnpm.io` unavailable

### ISSUE THREAD

**Issue by samialdury** [pnpm/pnpm#6243]
Hi, 

https://pnpm.io/ is currently not loading properly.

<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/57627858/226189107-acd91722-aaf8-4108-8c9e-dc7a80acff31.png">

### Additional information:

 - User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by samialdury** [comment]
Seems ok now.

**Comment by zkochan** [comment]
Looks like it was some cloudflare caching issue.
