### ISSUE TITLE
.cache folder is getting created along with pnpm store

### ISSUE THREAD

**Issue by vasuneet** [pnpm/pnpm#6250]
In Jenkins pipeline by default .cache folder also getting created along with pnpm-store folder

<img width="623" alt="image" src="https://user-images.githubusercontent.com/3884434/226476699-21e3fa9e-d1c8-494f-8a9f-402f2d2230af.png">

Ideally cache should be handled by one folder only i.e. pnpm-store

**Comment by zkochan** [comment]
No, they should not be both in cache. Cache is something that you may safely remove. The store is not supposed to be removed because projects hard link files from the store. So the store is not cache.

The cache directory contains just the metadata cache, which may be safely removed.

**Comment by vasuneet** [comment]
Okay. So in my pipeline we have this structure:
workspace and I am using checkout scm command to checkout in repository directory under workspace (WORKSPACE/repository)which removes everything , so .pnpm-store is also removed.
I found this workaround
Before running checkout scm I am running the below command:
mv .pnpm-store ../.pnpm-store
After checkout scm I am running below
mv ../.pnpm-store .pnpm-store

But even then I am not seeing much improvement in PNPM install performance when I replay the build. Ideally it should not take more than 1 or 2 mins when all dependencies are already there in PNPM-store.
