### ISSUE TITLE
`pnpm publish` fails `ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL` with when both `workspace:` and `publishConfig.directory` set 

### ISSUE THREAD

**Issue by dotansimha** [pnpm/pnpm#6253]
### pnpm version:

`7.30.0` (but probably also happens in previous versions)

### Code to reproduce the issue:

You maybe use the `master` branch on this repo to reproduce:

https://github.com/kamilkisiela/graphql-inspector

```
pnpm i 
pnpm build 
pnpm changeset publish
```

### Expected behavior:

Publish will just work.

### Actual behavior:

> Thanks @Andarist for helping us debug this ❤️ 

An error `ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL` is thrown. 

We have the following structure in our project, once the project is built:

```
package.json
pnpm-workspace.yaml
node_modules/
packages/
   a/
      node_modules/
      package.json
      dist/
         package.json
```

The `packages/a/package.json` is using a custom build flow, that creates a `dist` directory that includes an optimized `dist/package.json`. 
The `packages/a/package.json` is also using the following publish config:

```
  "publishConfig": {
    "directory": "dist",
    "access": "public"
  },
```

When the `pnpm publish` command (executed in `package/a/` by `changeset` is executed), it seems like the following piece of code is executed:
https://github.com/pnpm/pnpm/blob/f53a29d76f657f1b3785e873f0ac9b7291c007e4/pkg-manifest/exportable-manifest/src/index.ts#L72-L76 , and throws an error `ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL`. 

Debugging the internals shows that `pnpm` is trying to locate the `packages/a/dist/node_modules` and read it with `tryReadProjectManifest` - this one fails because there is no `node_modules` inside the `dist` - it's just pure compiled JS and an optimized `package.json` file. 

It seems like in a case where `publishConfig.directory`, the `tryReadProjectManifest` needs to get called with the original directory, instead of the one built with `directory`? 

### Additional information:

 - `node -v` prints: v18.14.2
 - Windows, macOS, or Linux?: macOS

**Comment by dotansimha** [comment]
@trappar this seems like a similar issue to https://github.com/pnpm/pnpm/issues/5094#issuecomment-1440810803? are you also using `publishConfig.directory`?

**Comment by Andarist** [comment]
I just had an extra lightbulb moment... in case of `pnpm` we should call its `pnpm publish` from the original `cwd` here:
https://github.com/changesets/changesets/blob/5c53bff0efeb5bbd72976b79aefe9d5805038ebd/packages/cli/src/commands/publish/npm-utils.ts#L179

the problem is that this value is already resolved using the `publishConfig.directory` here:
https://github.com/changesets/changesets/blob/5c53bff0efeb5bbd72976b79aefe9d5805038ebd/packages/cli/src/commands/publish/publishPackages.ts#L130-L137

So it might not be `pnpm` issue after all. This should get fixed in Changesets.

**Comment by dotansimha** [comment]
Seems like @Andarist 's  fix in https://github.com/changesets/changesets/pull/1115 works great and solves the problem. 
Closing, and will track in `changesets` repo :)
