### ISSUE TITLE
Pnpm install has no option to install _all_ dependencies --effectively ignoring NODE_ENV

### ISSUE THREAD

**Issue by VividLemon** [pnpm/pnpm#6254]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

It's strange, the https://pnpm.io/cli/install#--dev--d flag indicates that it only installs devDeps, prod only deps... 

However, there's no way to indicate that you should install both, regardless of the NODE_ENV. My specific issue is that in a ci environment, deploying to production requires NODE_ENV=production. However, this causes pnpm to not install devDependencies. This is not ideal in a ci environment because I require the dev dependencies to build the app.

How can you instruct pnpm to install all dependencies, regardless of the NODE_ENV? I searched through the docs and found no answer. Are --prod and --dev flags mutually exclusive? Would you hypothetically be able to use both at the same time 

**Describe the solution you'd like**

It may be a simple question, or it could be a feature request. If it's already implemented in some way, and I'm just not seeing it, it could be simple. However, if it's not, there should be some way to install everything regardless of the env.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

Just setting NODE_ENV for that specific command works. Not very ideal, it would be helpful to have it in pnpm.

**Comment by VividLemon** [comment]
To bring a bit more clarity, npm has the ability to override NODE_ENV

> With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies. To install all modules listed in both dependencies and devDependencies when NODE_ENV environment variable is set to production, you can use --production=false

However, pnpm seems to have no ability to do so using internal _flags_

**Comment by VividLemon** [comment]
After attempting to run `pnpm i --frozen-lockfile --prod=false`, I came to the conclusion that this feature may be already implemented, just not documented. 

It is not documented that the --prod flag has a boolean value, unlike other flags in the documentation

So, I suppose this feature request is a feature request for the docs. 

It would be helpful to add this to the docs to avoid the confusion. In addition, after reviewing some of the test cases, this is not covered by a test, so someone may want to implement that as well.

**Comment by dparish** [comment]
@VividLemon 

OMG YES

Thank you SO MUCH.  This entire production / development mode stuff is just so WRONG.  I couldn't figure out why my AWS Amplify builds were failing until I created a local docker and ran the node image in production mode.  If you are doing builds why would you want to restrict dev and production.  Your discovery of -prod=false was a lifesaver.

**Comment by JasonMan34** [comment]
This already seems documented - `Use this flag to instruct pnpm to ignore NODE_ENV and take its production status from this flag instead.`

Note that another way would be to just set NODE_ENV for this specific command: `NODE_ENV=ci pnpm i --frozen-lockfile`

@VividLemon What exactly would you have liked to see in the documentation to suggest the usage of `--prod=false` ?

**Comment by VividLemon** [comment]
I don't recall why I made this

> Note that another way would be to just set NODE_ENV for this specific command

Not super ideal since cross-env would probably need to be in play in some instances. Maybe not, idk. But like I said, I don't remember the context of this issue.

**Comment by Sajito** [comment]
> This already seems documented - `Use this flag to instruct pnpm to ignore NODE_ENV and take its production status from this flag instead.`
> 
> Note that another way would be to just set NODE_ENV for this specific command: `NODE_ENV=ci pnpm i --frozen-lockfile`
> 
> @VividLemon What exactly would you have liked to see in the documentation to suggest the usage of `--prod=false` ?

Since I had the same problem today, I would suggest to extend the documentation to follow the same semantics as the other boolean flags, adding an information about it's type and default. Just like for example `--prefer-offline` oder `--lockfile-only`.
![grafik](https://github.com/pnpm/pnpm/assets/6151929/f49acab4-2d32-4e8e-9e6b-bba800c1c42e)

Once it's known how those flags work, it obvious to be able to pass `--prod=false`, but since some options seem to be more explicit about this ability, it's confusing at first.
