### ISSUE TITLE
pnpm dedupe --list (equivalent to pnpm-deduplicate --list)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [pnpm/pnpm#6258]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md)) _it would bring me great joy to, yes please!_

**Describe the user story**

The [`pnpm-deduplicate` package](https://github.com/ocavue/pnpm-deduplicate) used to abe a good stopgap for `pnpm-lock.yaml` deduplication, until `pnpm v7.26.0` added the `pnpm dedupe` command. Which is great, thank you!

But! `pnpm-deduplicate` supported a `--list` option that would just list duplicates with a non-zero exit code. This was useful for using it as a CI check to make sure folks didn't inadvertently corrupt lockfiles, such as when resolving merge conflicts.

```plaintext
$ pnpm-deduplicate --list

Package "@babel/core" wants ^7.17.10 and could get 7.18.2, but got 7.18.0
Package "@babel/core" wants ^7.15.5 and could get 7.18.2, but got 7.18.0
```

Could we add an equivalent `--list` option to `pnpm dedupe`?

**Describe the solution you'd like**

If `--list` is provided to `pnpm dedupe` and duplicate packages are found, instead of writing updates to `pnpm-lock.yaml`, it should instead:
* Log each of the duplicates to the console
* Exit with a non-zero exit code

**Describe the drawbacks of your solution**

...none, this proposal is perfect, how dare you suggest otherwise? (sorry, can't think of any!)

**Describe alternatives you've considered**

Writing a tool that runs `pnpm dedupe`, reverts any changes, then exits with an error if there were any changes? That's rather cumbersome.

**Comment by zkochan** [comment]
Is this the same as https://github.com/pnpm/pnpm/issues/6105?

**Comment by JoshuaKGoldberg** [comment]
Agh, it is. Sorry! I didn't think to search for "check".
