### ISSUE TITLE
Postinstall fails when ran twice with `node-linker=hoisted`

### ISSUE THREAD

**Issue by hipstersmoothie** [pnpm/pnpm#6270]
### pnpm version:

7.30.1

### Code to reproduce the issue:

https://github.com/hipstersmoothie/pnpm-bug/blob/main/package.json

Run `pnpm I` twice

### Expected behavior:

Install works

### Actual behavior:

Install fails

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: Mac

**Comment by DzmVasileusky** [comment]
@hipstersmoothie but how did you fix it?
I have the same issue
https://github.com/pnpm/pnpm/issues/6696

**Comment by hipstersmoothie** [comment]
I never did. I ended up making the repo work with the default linker.
