### ISSUE TITLE
pnpm spends all of its time building a graph, resolving paths in repo with 8000+ packages (DefinitelyTyped conversion to a monorepo)

### ISSUE THREAD

**Issue by jakebailey** [pnpm/pnpm#6277]
### pnpm version:

7.30.0

### Code to reproduce the issue:

This is going to be ridiculous (sorry), but, I'm currently working on converting DefinitelyTyped to a monorepo, and I'm testing pnpm as an option to do this. The monorepo would be absolutely ridiculous as it contains over 8000 packages.

This repo is special because:

- We want packages to symlink within the repo, but not always!
- There can be multiple versions of the same package within the repo

https://github.com/jakebailey/DefinitelyTyped/tree/pnpm-workspaces-committed

### Expected behavior:

`pnpm install` completes in a reasonable-ish time

### Actual behavior:

`pnpm` hangs for a minute, then prints a load of circular deps, and then continues.

I took a profile using `pprof-it`, and I think there's some perf hole here:

![image](https://user-images.githubusercontent.com/5341706/227604962-f962745d-2bf7-4ff9-9836-c6872705308d.png)

This big chunk takes 51 seconds overall during `pnpm install`. Building a graph sounds normal, but, it seems like a big chunk is just resolving paths?

Is there anything we can do to speed this up? Did we configure something wrong? Any help is absolutely appreciated.

### Additional information:

 - `node -v` prints: v19.8.1
 - Windows, macOS, or Linux?: Linux (though in WSL)

**Comment by jakebailey** [comment]
In case you want these profiles:

[pprof-time-1448.pb.gz](https://github.com/pnpm/pnpm/files/11065222/pprof-time-1448.pb.gz)
[pprof-heap-1448.pb.gz](https://github.com/pnpm/pnpm/files/11065223/pprof-heap-1448.pb.gz)

Of course, these are pprof profiles not "normal" cpuprofile used by VSCode/Chrome/Edge, so I don't blame you if they're not helpful!

**Comment by zkochan** [comment]
Does it eventually succeed and create what you need?

We do support multiple versions of the same package in one monorepo.

**Comment by jakebailey** [comment]
It does, yes; once it's installed the state of disk is seemingly good. There are other things I can talk about but I just wanted to report this perf problem first. If we rerun `pnpm install`, it takes the same time again, so it's a little disruptive as far as I can tell.

**Comment by jakebailey** [comment]
Just to screenshot (sorry) what I get when it does get past this huge chunk:

![image](https://user-images.githubusercontent.com/5341706/227609711-a58f19b0-f1b6-4ddc-ad21-64a6489bdf2c.png)

It'd be nice to be able to disable this warning but likely building this string to print is not the actual bottleneck.

**Comment by jakebailey** [comment]
I have a new version of the branch I'm working on which instead ensures that we have version numbers set for each package, and then uses things like `workspace:*` or `workspace:^1` rather than using paths, and it does seem to work better in that it doesn't hang for too long at the start. I'll try and profile it again when I get it working and throw that on a branch too.

**Comment by zkochan** [comment]
Weird, I would've expected relative paths to work faster.

**Comment by jakebailey** [comment]
Here's the one with versions only, no paths:

![image](https://user-images.githubusercontent.com/5341706/227679059-ba034121-a0a7-4519-892e-a13f2c446891.png)

15 seconds, compared to 50 the other way. 

https://github.com/jakebailey/DefinitelyTyped/tree/pnpm-workspaces-committed-2

There are some other outstanding issues I'll have to file / ask about (e.g. when we put two packages of the same name in the repo, peer deps from external packages don't map to them properly), but this seems to work a little better and I think I need to set versions to get peer deps working in any case.

**Comment by jakebailey** [comment]
I'm doing some performance digging here, and what I think is happening (for this step, at least) is that in `createPkgGraph`, there are a few places which search `pkgMap`. But, in my case, `pkgMap` has 9032 entries!

These searches end up being quadradic, as every entry of `pkgMap` ends up searching all of `pkgMap` for each of its own dependencies.

There are a few tactics I'm going to try, which you're free to do if you have time, but if you don't I'm planning on implementing them and sending PRs when I have some more free time or next week. The immediate improvements I'll be trying are:

- Don't call `Object.entries`, `Object.values`, `Object.keys`, on `pkgMap`, at least not more than once (hopefully never); doing so allocates a brand new array each time which incurs a big cost. There are more efficient ways to iterate over objects, or, preferably, avoid needing to do it altogether.
- Try and pre-create (or lazily create) the mappings required for the lookups.
  - The lookup on `pkg.manifest.name === depName` can be pretty straightforwardly converted into a Record or Map.
  - `path.relative(pkg.dir, spec.fetchSpec) === ''` is slightly more complicated; this could be rewritten to not always resolve paths and check for the empty string, but to instead normalize paths to absolute paths and then do a plain equality lookup. This may or may not work, though, depending on whether or not this particular piece of code is affected by case sensitivity, which I suspect may be given how Node implements this function (https://github.com/nodejs/node/blob/6311de332223e855e7f1ce03b7c920f51f308e95/lib/path.js#L507)

**Comment by jakebailey** [comment]
I can say already that just hoisting `Object.values(pkgMap)` into `createPkgGraph` saves basically all of the time! That'd be a really safe change without needing to do any of the "fancy" stuff.

For the same thing as my previous profile screenshot that took 15 seconds, now it takes 1.5 seconds:

![image](https://user-images.githubusercontent.com/5341706/227743821-4f7aa682-3ea1-414b-897d-7ebf40fbfdd5.png)

**Comment by jakebailey** [comment]
Of course, I'm now realizing that this particular change is not exactly the original issue in that the cost of the `resolve` is not here as my new repo setup doesn't use that anymore (for perf, but also because it's better not to for reasons that benefit DefinitelyTyped).

I'll send a PR for this, but, I think there's still more to find here! 😄

**Comment by jakebailey** [comment]
Another bottleneck I'll have a PR for; `getRootPackagesToLink` builds a mapping using all projects, but it does this for each project too; with the above PR and then that change, I can get `pnpm install` for this repo down to 15 seconds!

**Comment by zkochan** [comment]
try 7.30.4

**Comment by jakebailey** [comment]
Thanks for backporting my PRs!

For the version of my workspace which doesn't use paths (we're likely going to be using this one, https://github.com/jakebailey/DefinitelyTyped/tree/pnpm-workspaces-working), 7.30.0 takes 1 minute to install in an already-installed workspace, while 7.30.4 takes 13s. Great improvement!

For the version of my workspace with paths (my original issue, https://github.com/jakebailey/DefinitelyTyped/tree/pnpm-workspaces-committed), 7.30.0 takes 1m37s, while 7.30.4 takes 47s. Much better, but the bulk of the time on this particular example is still the resolution phase.

Both conditions will benefit from some more optimization; I plan to address these tomorrow or the next day.

Very much appreciate the reviews! I'm really excited 😄

**Comment by mcmxcdev** [comment]
Hey Jake, thanks for the performance improvements, much appreciated!

**Comment by zkochan** [comment]
Thanks! Great results!

**Comment by gluxon** [comment]
Thank you @jakebailey! 🙂

**Comment by jakebailey** [comment]
Just to outline the full explanation of the above so far, I spent the day putting together a blog and then writing a post about it: https://jakebailey.github.io/posts/pnpm-dt-2/

There's still room for improvement, and I won't be mad if anyone gets to fixing them before I do.

**Comment by kurtextrem** [comment]
> Just to outline the full explanation of the above so far, I spent the day putting together a blog and then writing a post about it: [jakebailey.github.io/posts/pnpm-dt-2](https://jakebailey.github.io/posts/pnpm-dt-2/)
> 
> There's still room for improvement, and I won't be mad if anyone gets to fixing them before I do.

Off-topic, but your blog has no comments, so I figured I'll do it here: I like the post!
Since you seem to have spent some time to get pprof running, have a look how Marvin gets NodeJS profiles: https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-4/: `node --cpu-prof` and then puts it into https://www.speedscope.app/

**Comment by jakebailey** [comment]
Oh, I'm fully aware of the "normal" profiles; for a long time the tooling to view them just wasn't there and the viewer would either crash or be extremely slow. That's somewhat recently changed, which is helpful. At this point I'm just pretty comfortable with pprof though I do still use the regular profiles when it's helpful.

**Comment by jakebailey** [comment]
I meant to close this, everything mentioned here has now been fixed.
