### ISSUE TITLE
Create log file in pnpm config dir instead of cwd

### ISSUE THREAD

**Issue by steelbrain** [pnpm/pnpm#629]
pnpm version: [e1abc46bd11d2671c0ed73cb39a644962a0b4a77](https://github.com/pnpm/pnpm/tree/e1abc46bd11d2671c0ed73cb39a644962a0b4a77)

Since the last few releases of npm, it's creating a log file in `~/.npm` or any other npm state dir the user has configured, I would expect the same from pnpm but this commit suggests otherwise https://github.com/pnpm/pnpm/commit/e1abc46bd11d2671c0ed73cb39a644962a0b4a77

**Comment by jvanbruegge** [comment]
It would also be important that old logs get deleted on a regular basis. E.g. when writing a new log, delete logs older tham two weeks.
If not, they will keep filling up your disk space

**Comment by zkochan** [comment]
What if the logs will be written into the OS temp folder? In that case it will be cleared automatically.

**Comment by jvanbruegge** [comment]
For me it wouldnt matter, but it might be useful to retain logs in case of crashes etc

**Comment by zkochan** [comment]
As of pnpm v5, the logs are written to `node_modules/.pnpm-debug.log`. Which, I think, is similar to what Yarn does. I don't have objections to implement something more sophisticated but it is really low priority in my backlog. So contributions are welcomed.

**Comment by zkochan** [comment]
pnpm doesn't write a log file as of version 7.9.1
