### ISSUE TITLE
ERROR: This version of pnpm requires at least Node.js v16.4 (The current version of Node.js is v16.13.2)

### ISSUE THREAD

**Issue by dr2009** [pnpm/pnpm#6297]
### pnpm version:
8.0.0

### Actual behavior:
```
pnpm -v     
ERROR: This version of pnpm requires at least Node.js v16.4
The current version of Node.js is v16.13.2
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```

### Additional information:

 - node  v16.13.2
 - macOS

**Comment by zkochan** [comment]
It is expected. pnpm v8 has dropped Node.js 14 support.

You can either keep using pnpm v7 or install `@pnpm/exe` (`npm i -g @pnpm/exe`), which is bundled with node.js 18.

**Comment by dr2009** [comment]
> It is expected. pnpm v8 has dropped Node.js 14 support.
> 
> You can either keep using pnpm v7 or install `@pnpm/exe` (`npm i -g @pnpm/exe`), which is bundled with node.js 18.

this error occur Node.js v16.13.2. not Node 14

**Comment by zkochan** [comment]
OK. I'll check

**Comment by zkochan** [comment]
It is an error in the error message. pnpm v8 supports only node.js v16.14 or newer

**Comment by dr2009** [comment]
> It is an error in the error message. pnpm v8 supports only node.js v16.14 or newer

ok i got it

but why not  support 16.13.0 (the first node 16 lts version)

**Comment by zkochan** [comment]
Because of this dependency

https://github.com/pnpm/pnpm/blob/518f5e1432113a79b8b0fae376ab37ca53507b51/pnpm-lock.yaml#L13744-L13747

**Comment by Mhist** [comment]
use `volta install pnpm`
and `pnpm install`
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/0c235d4d-af75-4531-9af1-ecb4455473cf" />
