### ISSUE TITLE
[bug] public-hoist dependencies are deduped in v8, not only the direct dependencies of workspace-root

### ISSUE THREAD

**Issue by SoonIter** [pnpm/pnpm#6299]
### pnpm version:
8.0.0

### Code to reproduce the issue:
```sh
git clone https://github.com/SoonIter/pnpm8-hoist-dedupe-issue.git
pnpm install
```

```txt
├── package.json
├── node_modules
│   ├── eslint
│   ├── prettier 
│   └── react
├── packages
│   ├── a
│   │   └── package.json
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```
```jsonc
// packages/a/package.json
{
  "name": "a"
  "dependencies": {
    "react": "18.2.0",
    "eslint": "8.36.0",
    "prettier": "2.8.7"
  }
}
```
```jsonc
// package.json
{
  "name": "root",
  "dependencies": {
    "react": "18.2.0"
  },
}
```
in this demo, public-hoisting dependencies such as eslint and prettier is not symlink to "packages/a/node_modules"

#6286 This behavior is a little unclear. Is this within expectations?

This behavior is a little black box. For user consideration, if the dependencies in node_modules are exactly the same as the dependencies declared in package.json, this is more intuitive.

### Expected behavior:

The node_modules directory contains all the dependencies of package.json

### Additional information:

 - `node -v` prints: v16.19.0
 - Windows, macOS, or Linux?: macOS

**Comment by SoonIter** [comment]
```txt
├── apps
│   └── web
│       ├── package.json
│       ├── pnpm-lock.yaml
│       └── pnpm-workspace.yaml
└── packages
    ├── a
    │   └── package.json
    ├── b
    │   └── package.json
    └── c
        └── package.json
```
```yaml
# apps/web/pnpm-workspace.yaml
packages:
  - '../packages/a'
  - '../packages/b'
  - '../packages/c'
```
This behavior also makes this directory structure not available, maybe workspace-root does not have to be at the top level.

**Comment by zkochan** [comment]
Yeah, it is expected. Hoisted dependencies are deduped too. 

Regarding your second message. That currently doesn't work? If so, we should definitely fix that one.

**Comment by Ten0** [comment]
Linked:
- https://github.com/pnpm/pnpm/issues/6311
- https://github.com/pnpm/pnpm/issues/6303

Please provide a feature to disable
