### ISSUE TITLE
Version 8 doesn't install dependencies of workspace in subprojects (breaking & no option to disable?)

### ISSUE THREAD

**Issue by Ten0** [pnpm/pnpm#6303]
### Code to reproduce the issue:
https://github.com/Ten0/pnpm_not_installing_-types_repro

### Expected behavior:
pnpm install should end up with @types/node in node_modules of project so that tsc can run, but it doesn't.

### Actual behavior:
Only dependencies not present in the workspace show up

### Additional information:

I suspect this relates to “Direct dependencies are deduped. If a dependency is present in both a project and the workspace root, it will only be linked to the workspace root.” from https://github.com/pnpm/pnpm/releases/tag/v8.0.0, which seems to be https://github.com/pnpm/pnpm/pull/5676 and https://github.com/pnpm/pnpm/commit/47e45d717d2c023400b8247157c3aaac4f404e1a however I cannot find a setting to disable this behavior in https://pnpm.io/npmrc.
It is not an acceptable behavior for us because this means that we now need to specify a different relative path for `typeRoots` for each project in `tsconfig.json`.

**Comment by zkochan** [comment]
I think you just need to remove `typeRoots` from `tsconfig.json`

**Comment by Ten0** [comment]
Thanks for the suggestions! 
However it seems that removing typeRoots wouldn't be a solution when needing to specify custom type roots, while the second setting (that compared to the default disables public hoisting for jest and prettier (https://pnpm.io/npmrc#public-hoist-pattern)) has no effect.

**Comment by zkochan** [comment]
:ship: 8.1.0
