### ISSUE TITLE
pnpm v8 tries to linkDirectory of workspace package  with `linkDirectory: false`

### ISSUE THREAD

**Issue by PabloSzx** [pnpm/pnpm#6306]
### Last pnpm version that worked:

7.30.4

### pnpm version: 8.0.0

![image](https://user-images.githubusercontent.com/8672915/228378465-e976f388-0bcb-4452-8172-2df77964f4f5.png)

### Code to reproduce the issue:

Can't make repo rn, could do later but this is something that happens when trying to update an unrelated package

### Expected behavior:

Not link subdirectory if `linkDirectory: true` is not specified

### Actual behavior:

It links subdirectory

### Additional information:

 - `node -v` prints: 8.0.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
Maybe it happens because [this setting](https://pnpm.io/package_json#publishconfiglinkdirectory) is now true by default?

**Comment by PabloSzx** [comment]
![image](https://user-images.githubusercontent.com/8672915/228381893-41ebfbbf-984f-43e7-8b7e-bab1cabb2341.png)

but with `: false` it seems like it still tries

**Comment by PabloSzx** [comment]
yep confirmed `linkDirectory: false` is simply not working

**Comment by PabloSzx** [comment]
In minimal repro I can't seem to reproduce the issue but on big monorepo I can 🤔

**Comment by PabloSzx** [comment]
Unrelated issue, `linkDirectory: false` does the trick
