### ISSUE TITLE
.bin Executables are not installed consistently from peerDependencies

### ISSUE THREAD

**Issue by jochemkeller** [pnpm/pnpm#6310]
### pnpm version:
8.0.0, also present in 7.x.x

### Code to reproduce the issue:
https://github.com/jochemkeller/pnpm-repro

This repro contains two of my own packages, a [eslint-config](https://github.com/zeebats/eslint-config) and a [stylelint-config](https://github.com/zeebats/stylelint-config). Both packages have peerDependencies defined for the important executables:

https://github.com/zeebats/eslint-config/blob/b0aa0715eea6b165772d5e1ab14afccec520d03e/package.json#L41

https://github.com/zeebats/stylelint-config/blob/d24dc6e318ca28bb4184a5bb86e6b4026dd62545/package.json#L31

### Expected behavior:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/1217959/228466597-2d454d08-1e40-4269-bf69-9a6d566405ef.png">
(Simulated image)

I would expect both `eslint` & `stylelint` executables to be available

### Actual behavior:
<img width="147" alt="image" src="https://user-images.githubusercontent.com/1217959/228466812-7c7f0652-ce49-42e1-bff4-61f8a60d074e.png">

Only the `eslint` executable is available. Trying to run `stylelint` naturally results in an error:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1217959/228468273-6b987f34-6836-4ddc-8b0d-6ece11eee193.png">

### Additional information:

 - `node -v` prints: 
 v18.14.1
 - Windows, macOS, or Linux?:
 macOS Ventura 13.2.1
 
Please let me know if you require more information than this 🙏 and apologies in advance if I misunderstood something

**Comment by WoLfulus** [comment]
I also expected it to make bins available from peer dependencies, but none of them are getting into main node_modules/.bin folder, it does land in requester's node_modules/.bin folder though, just not the main one. Is this the expected behavior?

**Comment by karlhorky** [comment]
I think this is a similar issue to this:

- https://github.com/pnpm/pnpm/issues/6392

cc @zkochan

**Comment by karlhorky** [comment]
@zkochan actually, would you consider a PR changing the default of [`public-hoist-pattern`](https://pnpm.io/npmrc#public-hoist-pattern) to `['*eslint*', '*prettier*', '*stylelint*']`

<img width="623" alt="Screenshot 2023-05-12 at 17 18 56" src="https://github.com/pnpm/pnpm/assets/1935696/6f6c7898-8810-4b23-a03a-23d991698bb2">

**Comment by zkochan** [comment]
> I also expected it to make bins available from peer dependencies, but none of them are getting into main node_modules/.bin folder, it does land in requester's node_modules/.bin folder though, just not the main one. Is this the expected behavior?

It is expected behavior. `eslint` is only hoisted because it is in the `public-hoist-pattern` setting by default. You need to install both `eslint` and `stylelint` as dependencies if you want to run their CLIs.

> would you consider a PR changing the default of [public-hoist-pattern](https://pnpm.io/npmrc#public-hoist-pattern) to ['*eslint*', '*prettier*', '*stylelint*'] (currently special-cases ESLint and Prettier but not Stylelint)

No, I don't think we should do this. eslint is only included to hoist eslint plugins. If someone wants to use a package's CLI from the scripts, they should install that package as a dependency.

**Comment by zkochan** [comment]
It should be in the dependencies of project A. If you want everything hoisted, you can use `node-linker=hoisted`. But that is not the recommended way.
