### ISSUE TITLE
interactive update: show link to changelog

### ISSUE THREAD

**Issue by thedisy** [pnpm/pnpm#6314]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A regular workflow for maintainers is to go through the list of update-able dependencies. For this pnpm provides `pnpm update --interactive --latest --recursive`.

To make an informed decision it is crucial to know what exactly has changed in each dependency. But with a large enough project it gets very tedious to manually search for the respective changelog of each and every package.

**Describe the solution you'd like**

`pnpm update` should show an additional column listing the link to that packages changelog file (should one have been found).

This link could then be clicked on or copied to a webbrowser.

**Describe the drawbacks of your solution**

As the changelog search could take a bit of time it might make sense to guard it behind a new CLI argument (e.g. `--changelog`).

Alternatively it could be activated for a package on demand with a new keybind (e.g. `Press <c> to open changelog`). This is what [npm-upgrade](https://github.com/th0r/npm-upgrade) does.

Searching for a few changelog files at the dependencies project root might not always return a result but should be enough for most packages.

As long as packages keep their important files like licenses, changelogs, etc. in their projects root directory this feature shouldn't break.

**Describe alternatives you've considered**

[npm-upgrade](https://github.com/th0r/npm-upgrade) has this feature ([implemented here](https://github.com/th0r/npm-upgrade/blob/master/src/changelogUtils.js)) but it doesn't support workspaces which are essential for larger projects.

**Comment by th3fallen** [comment]
fwiw this is also what `yarn upgrade-interactive --latest` does (it also splits deps by dev vs non dev dependancies which is nice`
