### ISSUE TITLE
pnpm 8.0.0 does not work with node 16.13.0

### ISSUE THREAD

**Issue by persiliao** [pnpm/pnpm#6315]
### pnpm version:
8.0.0
### Code to reproduce the issue:
pnpm -v
### Expected behavior:
Can be used correctly, 8.0.0
### Actual behavior:
ERROR: This version of pnpm requires at least Node.js v16.4
The current version of Node.js is v16.13.0
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
### Additional information:

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
It is a mistake in the error message

https://github.com/pnpm/pnpm/commit/518f5e1432113a79b8b0fae376ab37ca53507b51
