### ISSUE TITLE
Peer dependency warning doesn't check dependency where it is defined

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#632]
```
$ pnpm i

WARN registry.npmjs.org/@vjpr/bootstrap-loader/2.0.0-beta.19-vjpr.5 requires a peer of extract-text-webpack-plugin@>=2.0.0-beta but none was installed.
```

**my-app/package.json**

```
  "dependencies": {
    ...
    "webpackerator": "*",
    ...
  }
```

**webpackerator/package.json**

```
  "dependencies": {
    ...
    "@vjpr/bootstrap-loader": "^2.0.0-beta.19-vjpr.5",
    "extract-text-webpack-plugin": "2.0.0-rc.3",
    ...
  },
```

**@vjpr/bootstrap-loader/package.json**

```
  "peerDependencies": {
    ...
    "extract-text-webpack-plugin": ">=2.0.0-beta",
    ...
  },
```

`2.0.0-rc.3` satisfies the requirement of `>=2.0.0-beta` - checked on https://semver.npmjs.com/.

It appears that when a dep of a dep has a peer dep requirement, it is being checked against the project's `node_modules`, rather than the parent dep's `node_modules`.

### Additional information:

 - `node -v` prints: 6.5.0
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
@vjpr is it still reproducible in v0.62.2?

I tried `pnpm i webpackerator` and I didn't get the error with the `extract-text-webpack-plugin` peer dep.

**Comment by vjpr** [comment]
Just tested, looks like it was resolved. Closing.
