### ISSUE TITLE
Update the shell emulator version

### ISSUE THREAD

**Issue by shawnmcknight** [pnpm/pnpm#6320]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I'd like to be able to use `${FOO:+bar}` expressions in pnpm's built-in shell emulator.  I believe that pnpm is using `@yarnpkg/shell` to provide the shell emulator support.  That package added support for this expression syntax in yarnpkg/berry#3666.

If I'm following correctly, the shell-emulator support comes from the [@pnpm/npm-lifecycle](https://github.com/pnpm/npm-lifecycle) package.  The [package.json](https://github.com/pnpm/npm-lifecycle/blob/main/package.json#L37) for that currently indicates that the version of `@yarnpkg/shell` being used is `3.2.0-rc.8`.  According to the [CHANGELOG](https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#compatibility-6), this functionality was added in version 3.2.0, but I suspect it ended up in either a later rc version of 3.2.0 (there were 6 additional rc versions) or only in 3.2.0 proper since it does not appear to currently be working in pnpm's shell emulator.  The latest stable release of that package is `3.2.5` but there are rc versions up to `4.0.0-rc.41`.

**Describe the solution you'd like**

Update the version of `@yarnpkg/shell` to at least the latest stable version of `3.2.5` which should allow for `${FOO:+bar}` expressions in the shell.

**Describe the drawbacks of your solution**

None that I can think of.

**Describe alternatives you've considered**

None that I can think of.

**Comment by zkochan** [comment]
ok, sounds good

**Comment by shawnmcknight** [comment]
I have submitted pnpm/npm-lifecycle#40 to bump the version of `@yarnpkg/shell` that is being used.

I guess since that package is in a separate repository, to get this into pnpm core, there would need to be a new release of `pnpm/npm-lifecycle` followed by a change to the dependencies of [@pnpm/lifecycle](https://github.com/pnpm/pnpm/blob/main/exec/lifecycle/package.json#L41) to use that version.
