### ISSUE TITLE
ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY when using local package as dependency

### ISSUE THREAD

**Issue by MaSch0212** [pnpm/pnpm#6332]
### Last pnpm version that worked:
7.30.5

### pnpm version:
8.1.0

### Code to reproduce the issue:
I uploaded a repro repository for this here: https://github.com/MaSch0212/pnpm-local-package-issue

### Expected behavior:
1. Add a dependency to a folder, e.g.: `"@types/bpmn-js": "file:./@types/bpmn-js"`
2. Run `pnpm install`
   - It runs without issues.
3. Run `pnpm install --frozen-lockfile`
   - Should run without issues.

### Actual behavior:
1. Add a dependency to a folder, e.g.: `"@types/bpmn-js": "file:./@types/bpmn-js"`
2. Run `pnpm install`
   - It runs without issues.
3. Run `pnpm install --frozen-lockfile`
   - Shows `ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY` error

Running any other `pnpm install` command afterwards produces the `ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY` error. In this example I run `pnpm install --frozen-lockfile` to simulate a build pipeline:
![image](https://user-images.githubusercontent.com/8530764/229038774-558d3de6-9b3b-4d27-9cde-1247a817af1a.png)

After running `pnpm install` once, you will always get the error from that point on (unless the local package dependency is removed):
![image](https://user-images.githubusercontent.com/8530764/229037792-28f6e005-26ca-49bf-b05d-b825cf1b7a0c.png)

### Additional information:

 - `node -v` prints: v16.18.1
 - Windows, macOS, or Linux?: Windows

**Comment by brionmario** [comment]
`pnpm v8` adopts the new [Lockfile v6](https://github.com/pnpm/pnpm/pull/5810). You may have to update your lock files to adhere with the changes.

**Comment by MaSch0212** [comment]
I managed to reproduce this issue with a completely fresh repository (see "Code to reproduce the issue"). So the lockfile was created by pnpm v8.1.0, therefore the lockfile is already v6.

**Comment by zkochan** [comment]
I'll check this.

**Comment by wangmeijian** [comment]
so， how to fix？
