### ISSUE TITLE
Missing (a lot of) symlinks

### ISSUE THREAD

**Issue by albertdb** [pnpm/pnpm#635]
### pnpm version: 
0.57.0

### Code to reproduce the issue: 
`pnpm install`

### Expected behavior: 
Install all (sub)dependencies and make them available through symlinks in node_modules root directory or dependencies' node_modules.

### Actual behavior: 
Most of the symlinks are missing. The actual packages are in `.registry.npmjs.org/` directory, though.

Due to that, the developed module doesn't find some required dependencies and crashes.

### Additional information:

 - `node -v` prints: `v5.3.0`
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
> Due to that, the developed module doesn't find some required dependencies and crashes.

In that case that package has to be fixed. If a package uses some other package, it should depend on it. It shouldn't expect a flattened dependency tree. pnpm doesn't need a flattened dependency tree as npm and yarn.

Flattened dependency trees is not a feature, it is a workaround. pnpm doesn't need this workaround

**Comment by albertdb** [comment]
Sorry, I didn't explain it well. It's not only that the root node_modules doesn't contain all packages, but that also tthat all dependecies' node_modules are empty (but .bin directory).

**Comment by zkochan** [comment]
Are you running Node.js with `--preserve-symlinks`?

**Comment by albertdb** [comment]
I don't think so. Should I?

How that can help if the symlinks are not there? I guess I'm missing something.

**Comment by zkochan** [comment]
Node resolves dependencies relatively to the realpath.

This is the structure pnpm creates:

```
└─ node_modules/
   ├─ .registry.npmjs.org/
   |   ├─ chalk/1.1.1/node_modules/
   |   |  ├─ chalk
   |   |  |  ├─ index.js     => ~/.pnpm-store/registry.npmjs.org/chalk/1.1.1/index.js
   |   |  |  └─ package.json => ~/.pnpm-store/registry.npmjs.org/chalk/1.1.1/package.json
   |   |  ├─ ansi-styles/    -> ../../ansi-styles/2.1.0/node_modules/ansi-styles
   |   |  └─ has-ansi/       -> ../../has-ansi/2.0.0/node_modules/has-ansi
   |   |
   |   ├─ has-ansi/2.0.0/node_modules/
   |   |  └─ has-ansi
   |   |     ├─ index.js     => ~/.pnpm-store/registry.npmjs.org/has-ansi/2.0.0/index.js
   |   |     └─ package.js   => ~/.pnpm-store/registry.npmjs.org/has-ansi/2.0.0/package.json
   |   |
   |   └─ ansi-styles/2.1.0/node_modules/
   |      └─ ansi-styles
   |         ├─ index.js     => ~/.pnpm-store/registry.npmjs.org/ansi-styles/2.1.0/index.js
   |         └─ package.js   => ~/.pnpm-store/registry.npmjs.org/ansi-styles/2.1.0/package.json
   |
   └─ chalk/                 -> ./.registry.npmjs.org/chalk/1.1.1/node_modules/chalk
```

Chalk will find ansi-styles, because the realpath of chalk is in `node_modules/.registry.npmjs.org/chalk/1.1.1/node_modules/chalk`, not in `node_modules/chalk` (this is just a symlink).

**Comment by zkochan** [comment]
However, pnpm's structure won'd work when node.js is preserves symlinks. Which happens only when Node.js is executed with the `--preserve-symlinks` option

**Comment by albertdb** [comment]
Now I understand it. The fact is that the version of nodejs I'm using doesn't support that option (Added in: v6.3.0), so the problem is in a submodule (third-party one u_u) that needs to be fixed, as you initially said.

Thanks for the explanation, it helped me finding the source of the error.

**Comment by zkochan** [comment]
Great! I'll try add more documentation about these things.
