### ISSUE TITLE
pnpm 8 installs deps from other packages than selected using `pnpm i --filter`

### ISSUE THREAD

**Issue by Anoesj** [pnpm/pnpm#6351]
### Code to reproduce the issue:
`pnpm i --filter=./backend --only=prod` (or without `=`)
 
Same result with`pnpm i --filter-prod ./backend`, which I expected to do the same as the command above.

Interestingly, even just `pnpm i --filter=./backend` installs deps of all other packages in the workspace too, so it's not a `--only` flag issue.

### Expected behavior:
pnpm installs only the production dependencies for the package at `./backend`. At 7.x, this worked properly.

### Actual behavior:
At 8.1.0 (haven't tested 8.0.0), this also installs deps from other workspace packages.

### Additional information:
 - `node -v` prints:18.15.0
 - Windows, macOS, or Linux?: Linux

**Comment by faradaytrs** [comment]
Duplicate of #6300

**Comment by Anoesj** [comment]
Closing, since this is a duplicate.
