### ISSUE TITLE
v7.27.0 linuxstatic-x64 asset is broken

### ISSUE THREAD

**Issue by iiian** [pnpm/pnpm#6363]
### Code to reproduce the issue:

```Dockerfile
RUN curl -kfsSL "https://github.com/pnpm/pnpm/releases/v7.27.0/download/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;
```

### Expected behavior:

🌈 🌞

### Actual behavior:

```bash
curl: (22) The requested URL returned error: 404
```

### Additional information:

When I follow that asset link, it points to v8.0.0-alpha. This may just be a `github` issue. In any case, it is randomly nuking my build scripts

**Comment by lvqq** [comment]
It's not a pnpm issue, the right link should be 
```
https://github.com/pnpm/pnpm/releases/download/v7.27.0/pnpm-linuxstatic-x64
```
