### ISSUE TITLE
 ERR_PNPM_CI_NOT_IMPLEMENTED  The ci command is not implemented ye

### ISSUE THREAD

**Issue by laterdayi** [pnpm/pnpm#6371]
```
"ci": "vite build",
```

pnpm ci  tips   ERR_PNPM_CI_NOT_IMPLEMENTED  The ci command is not implemented ye

### pnpm version:
last
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by zkochan** [comment]
Run `pnpm run ci`.

`pnpm ci` should behave as `npm ci` but it wasn't yet implemented.
