### ISSUE TITLE
Installation structure differing from npm throws error when trying to import package

### ISSUE THREAD

**Issue by chemdrew** [pnpm/pnpm#6378]
### pnpm version:
8.2.0

### Code to reproduce the issue:
https://github.com/chemdrew/pnpm-install-issue

### Expected behavior:
installing and importing a module does not throw an error

### Actual behavior:
an error is thrown trying to import the module

### Additional information:
There is a structural difference in the imported module's child. When I use pnpm for installation
`ls node_modules/.pnpm/core-js@2.6.12/node_modules/core-js/library` only returns `fn`
But when I use npm to install and run `ls node_modules/core-js/library` it returns `core es5 es6 es7 fn index.js modules shim.js stage we`

 - `node -v` prints:
 v16.15.1
 
 - Windows, macOS, or Linux?:
macOS

**Comment by zkochan** [comment]
I don't see an error with pnpm v8.2

```
pnpm-install-issue on  main [!] is 📦 v1.0.0 via  v16.20.0 took 2s
❯ pn run test:pnpm

> pnpm-install-issue@1.0.0 test:pnpm /Users/zoltan/src/sandbox/pnpm-install-issue
> rm -rf node_modules && pnpm i && node .

Lockfile is up to date, resolution step is skipped
Packages: +3
+++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/zoltan/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 3, reused 3, downloaded 0, added 3, done

dependencies:
+ babel-runtime 6.26.0

Done in 471ms

----- running script -----

{ __esModule: true, default: [Function (anonymous)] }

----- done running script -----
```

**Comment by zkochan** [comment]
ok, I really hope it was caused by some old bug that doesn't exist anymore. If the package index in the store can break, we should reproduce it and fix it.

**Comment by chemdrew** [comment]
@zkochan totally agree! I can't pinpoint exactly when/where the cache got messed up since I started the npm/yarn->pnpm migration a while ago using v7 and could have populated the cache then before upgrading to v8.2.0 last week. I'll keep an eye on it and open a new issue if it pops up again and becomes more clear.
