### ISSUE TITLE
[`pnpm pack`] Add option to allow setting custom compression level

### ISSUE THREAD

**Issue by jankaifer** [pnpm/pnpm#6393]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

vercel/next.js team uses `pnpm pack` in their tests and our packages contain some rust binaries, which are large and slow to pack. We want to decrease the compression level used in packing to speed this process up. The fastest compression level (1) could pack our packages under `.5s`, but the default level (6) takes up to `9s`.

Some folks may prefer increasing the compression level to achieve a smaller packed size.

**Describe the solution you'd like**

Anything that could expose this option to the user would work.
For example, `tar` uses `GZIP=-1` environment variable, but we could probably add a command argument or anything else.

It could be quickly done with a single line here: https://github.com/pnpm/pnpm/blob/5a5512f14c47f4778b8d2b6d957fb12c7ef40127/releasing/plugin-commands-publishing/src/pack.ts#L165

**Describe the drawbacks of your solution**

This is a specific use case that many folks might not need.

**Describe alternatives you've considered**

None

**Comment by zkochan** [comment]
I don't have objections if the packed tarballs can be installed then without issues.
