### ISSUE TITLE
Nit: incorrect grammar when checking the integrity of a lot of files

### ISSUE THREAD

**Issue by Nick-Mazuk** [pnpm/pnpm#6400]
### Code to reproduce the issue:

Install anything that requires pnpm to check the integrity of a lot of files.

### Expected behavior:

The following was logged at the end of the install process.

```txt
The integrity of 1509 files was checked. This might have caused installation to take longer.
```

### Actual behavior:

`was` should become `were`

```txt
The integrity of 1509 files were checked. This might have caused installation to take longer.
```

### Additional information:

 - `node -v` prints: 18.15.0
 - Windows, macOS, or Linux?: macOS 13.3.1

**Comment by capndave** [comment]
The way I read this, `was` refers to `The integrity`. Since integrity is singular, was seems appropriate!

**Comment by Nick-Mazuk** [comment]
Ah you're right. Closing!
