### ISSUE TITLE
pnpm env use - mirror rate limiting

### ISSUE THREAD

**Issue by moander** [pnpm/pnpm#6422]
I'm using pnpm v7 and v8 in CI to install nodejs.

The mirror nodejs.org used for downloading seems to block/delay users after a few CI runs. After that it takes minutes to install a single CI version. 

Is it possible to swap to a better/faster source for download?

**Comment by zkochan** [comment]
I don't know if there are better sources. But it is configurable: https://pnpm.io/npmrc#node-mirrorreleasedir

**Comment by wommy** [comment]
i always hit this
