### ISSUE TITLE
PNPM is adding two different versions of @types/react

### ISSUE THREAD

**Issue by pateljay1397** [pnpm/pnpm#6441]
### pnpm version:
- 6.32.11
### Code to reproduce the issue:
- We are adding following versions which are using @types/react as dependency.

    "@reduxjs/toolkit": "^1.8.6",
    "react-redux": "^7.2.9",
    "@types/react-router-dom": "^5.1.5",
    "@types/react-router": "^5.1.8",
    "@types/react-table": "^7.7.12",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.2",
    
    This is the dependency graph I have generated using pnpm why @types/react command.
dependencies:
@reduxjs/toolkit 1.9.5
└─┬ react-redux 7.2.9 peer
  └─┬ @types/react-redux 7.1.25
    ├─┬ @types/hoist-non-react-statics 3.3.1
    │ └── @types/react 18.0.37
    └── @types/react 18.0.37
│ └─┬ @types/react-table 7.7.14
│   └── @types/react 18.0.37
├─┬ @reduxjs/toolkit 1.9.5
│ └─┬ react-redux 7.2.9 peer
│   └─┬ @types/react-redux 7.1.25
│     ├─┬ @types/hoist-non-react-statics 3.3.1
│     │ └── @types/react 18.0.37
│     └── @types/react 18.0.37
├─┬ @testing-library/react 12.1.5
│ └─┬ @types/react-dom 17.0.19
│   └── @types/react 17.0.58
├── @types/react 17.0.58
├─┬ @types/react-dom 17.0.19
│ └── @types/react 17.0.58
├─┬ @types/react-redux 7.1.25
│ ├─┬ @types/hoist-non-react-statics 3.3.1
│ │ └── @types/react 18.0.37
│ └── @types/react 18.0.37
├─┬ @types/react-router 5.1.20
│ └── @types/react 18.0.37
├─┬ @types/react-router-dom 5.3.3
│ ├── @types/react 18.0.37
│ └─┬ @types/react-router 5.1.20
│   └── @types/react 18.0.37
├─┬ @types/react-table 7.7.14
│ └── @types/react 18.0.37
└─┬ react-redux 7.2.9
  └─┬ @types/react-redux 7.1.25
    ├─┬ @types/hoist-non-react-statics 3.3.1
    │ └── @types/react 18.0.37
    └── @types/react 18.0.37
│ └─┬ @types/react-table 7.7.14
│   └── @types/react 18.0.37
├─┬ @reduxjs/toolkit 1.9.5
│ └─┬ react-redux 7.2.9 peer
│   └─┬ @types/react-redux 7.1.25
│     ├─┬ @types/hoist-non-react-statics 3.3.1
│     │ └── @types/react 18.0.37
│     └── @types/react 18.0.37
├── @types/react 17.0.58
├─┬ @types/react-dom 17.0.19
│ └── @types/react 17.0.58
├─┬ @types/react-redux 7.1.25
│ ├─┬ @types/hoist-non-react-statics 3.3.1
│ │ └── @types/react 18.0.37
│ └── @types/react 18.0.37
└─┬ react-redux 7.2.9
  └─┬ @types/react-redux 7.1.25
    ├─┬ @types/hoist-non-react-statics 3.3.1
    │ └── @types/react 18.0.37
    └── @types/react 18.0.37
@testing-library/react 12.1.5
└─┬ @types/react-dom 17.0.19
  └── @types/react 17.0.58
@types/react-redux 7.1.25
├─┬ @types/hoist-non-react-statics 3.3.1
│ └── @types/react 18.0.37
└── @types/react 18.0.37
@types/react-router 5.1.20
└── @types/react 18.0.37
@types/react-router-dom 5.3.3
├── @types/react 18.0.37
└─┬ @types/react-router 5.1.20
  └── @types/react 18.0.37
@types/react-table 7.7.14
└── @types/react 18.0.37
react-redux 7.2.9
└─┬ @types/react-redux 7.1.25
  ├─┬ @types/hoist-non-react-statics 3.3.1
  │ └── @types/react 18.0.37
  └── @types/react 18.0.37
  
### Expected behavior:
It should add only one version which is @types/react: 17.0.58

### Actual behavior:
Somehow pnpm is adding two versions of @types/react it can be seen in dependency graph. @types/react 18.0.37 and @types/react 17.0.58

### Additional information:
- I have looked into all these packages package.json and all them are compatible with @types/react: 17.0.58. as they following requirement in their dependency @types/react: "*" 
- Even if I restrict @types/react version like this, @types/react: "~"17.0.2 by replacing "^" with "~" then it adds only (**Note: I can't use tild sign here that's why it shows the line on text**)@types/react and app works fine.
- 
![image](https://user-images.githubusercontent.com/54871480/233506887-204c6705-519d-493c-b1ee-8f6ce3d4e0f8.png)

 - We are using Rush for monorepo. So, I run rush update --full command.
 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
Maybe try with pnpm v8. I don't get this issue with v8.

6.32.11 is a very old version.

**Comment by pateljay1397** [comment]
@zkochan thanks for a quick response we are going to upgrade pnpm version to v8.
