### ISSUE TITLE
Cannot use scoped registry with GITHUB_TOKEN.

### ISSUE THREAD

**Issue by sungh0lim** [pnpm/pnpm#6442]
### pnpm version:

v8.3.1

### `.npmrc`

```
@yogiyo:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
```

### Expected behavior:

Can download @yogiyo/yogiyo-yds package from `https://npm.pkg.github.com/` registry.

### Actual behavior:

The following error log appears and pnpm install cannot proceed. The `GITHUB_TOKEN` has permission to access the registry.
Running repo also @yogiyo. (It works well when the package manager is changed to yarn.)

### Error log in github action.

```
Progress: resolved 1814, reused 0, downloaded 0, added 0
 ERR_PNPM_FETCH_403  GET https://npm.pkg.github.com/download/@yogiyo/yds/1.4.18/6ce01fa8846bee602b8c69c2d5e422ad34cc45bb: Forbidden - 403

An authorization header was used: ***

These authorization settings were found:
@yogiyo:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=ghs_[hidden]
```

### .yarnrc.yaml when using yarn

```
npmScopes:
  yogiyo:
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
```

### Additional information:

- node: `v16.20.0`
- `GITHUB_TOKEN` Permissions.
```
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

**Comment by manudeli** [comment]
I encountered same problem with this issue... 👀
Is there any solution?

**Comment by capndave** [comment]
If you haven't already, you might try logging out the GITHUB_TOKEN from the action script to ensure it's getting loaded correctly

**Comment by manudeli** [comment]
> If you haven't already, you might try logging out the GITHUB_TOKEN from the action script to ensure it's getting loaded correctly

@capndave
Are you using this part without problems?
I wonder if there is any further progress

**Comment by manudeli** [comment]
this issue is duplicated with https://github.com/pnpm/pnpm/issues/4393

**Comment by dmisdm** [comment]
Hey there! I was stuck on this as well, but i figured out my issue, and it wasn't to do with PNPM.
I fixed my case by making sure the published package gave the consuming repo the permission to read.
I went to https://github.com/orgs/<ORG>/packages/npm/<PACKAGENAME>/settings and change the visibility to "Internal", but you could also be more specific with the access by just giving it to the consuming repo. 
Hope this helps someone!

**Comment by andskre** [comment]
maybe this one could be helpful https://github.com/pnpm/pnpm/issues/4937#issuecomment-1646218979
