### ISSUE TITLE
Patch nested dependancies

### ISSUE THREAD

**Issue by tadhglewis** [pnpm/pnpm#6455]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer, I want to be able to patch the dependancies of a dependancy - e.g. `package/another-package`

This should work exactly like patch-package - https://github.com/ds300/patch-package#nested-packages

**Describe the solution you'd like**

https://github.com/ds300/patch-package#nested-packages

**Describe the drawbacks of your solution**

🤷 

**Describe alternatives you've considered**

Open to suggestions if anyone knows a workaround

**Comment by tadhglewis** [comment]
@zkochan there doesn't seem to be an example of this https://pnpm.io/cli/patch. Is this the same syntax as patch-package? 

In my case, I'm trying to patch sku / mini-css-extract-plugin however it tries to clone github.com/sku/mini-css-extract-plugin.git

```
> pnpm patch sku/mini-css-extract-plugin                                                                     
 ERROR  Command failed with exit code 128: git ls-remote git+ssh://git@github.com/sku/mini-css-extract-plugin.git HEAD
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

pnpm: Command failed with exit code 128: git ls-remote git+ssh://git@github.com/sku/mini-css-extract-plugin.git HEAD
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:23105:17)
    at handlePromise (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:23676:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:108835:23)
    at async resolveRef (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:108847:20)
    at async resolveGit (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:108798:24)
    at async Object.resolve (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:110098:173)
    at async run (/Users/tlewis/.nvm/versions/node/v18.12.1/lib/node_modules/pnpm/dist/pnpm.cjs:122075:23)
```

Let me dig through the code to see if I'm just missing the syntax

**Comment by zkochan** [comment]
You want to patch a git-hosted dependency? Why? You can just fork the repository.

**Comment by tadhglewis** [comment]
In this specific case it's because we're using it in a relatively unique way which requires flipping a couple boolean arguments which `mini-css-extract-plugin` sets in webpack - I thought about PRing however it's quite unique to our use case.

We'd typically fork however for very simple changes like this, we've found it easier patching than having to maintain a forked version with 1-liner-changes.

**Comment by zkochan** [comment]
TBH, I don't know how it works with git-hosted dependencies. But for regular packages from the registry it works for sure, for both direct and indirect dependencies.

**Comment by zkochan** [comment]
I don't understand, why do you running `pnpm patch sku/mini-css-extract-plugin` then?

If you want to patch `sku`, then you run `pnpm patch sku`

For the other one you run `pnpm patch mini-css-extract-plugin`
