### ISSUE TITLE
Linked dependencies not getting installed

### ISSUE THREAD

**Issue by JDansercoer** [pnpm/pnpm#6474]
### pnpm version: 

`8.3.1` and `7.30.5`

### Code to reproduce the issue: 

https://github.com/JDansercoer/affectionate-lamarr-vgwgcx2

### Expected behavior: 

Dependencies of a dependency should be installed as well

### Actual behavior:

Certain dependencies are missing

### Additional information:

 - `node -v` prints: `v16.20.0`
 - Windows, macOS, or Linux?: macOS

---

This is the `pnpm` version of the [bug I initially described in the @apollo/client](https://github.com/apollographql/apollo-client/issues/10808) repository.

Hopefully anyone here knows exactly what's happening!

**Comment by nachoaldamav** [comment]
I've checked the code, looks like this dependency is missing `@graphql-typed-document-node/core`, adding it to your package.json will fix the error.

![image](https://user-images.githubusercontent.com/22749943/235366597-2f696c67-2d02-42ad-92c3-833d0966167a.png)
