### ISSUE TITLE
This version of pnpm requires at least Node.js v16.14

### ISSUE THREAD

**Issue by YeeJone** [pnpm/pnpm#6479]
### Last pnpm version that worked: 
6.19.0

### pnpm version:
8.2.0

### Code to reproduce the issue: 
When I execute the pnpm command an error is reported
### Expected behavior:
no error，the nodejs version is correct.
### Actual behavior:
see the image
### Additional information:
use nvm switch the node version
 - `node -v` prints:
 <img width="602" alt="image" src="https://user-images.githubusercontent.com/20400822/234766317-b1219b4a-8c5d-40e8-b8e4-8bbba1183403.png">
 - Windows, macOS, or Linux?: macOS(Apple M1 Pro)

**Comment by thynson** [comment]
You should try with latest Node.js 18, which is 18.16.0 as of now. 
Also note that Node.js 18 entered LTS at 18.12.0, meaning that a version in 18.0.0 - 18.11.0 is not a LTS releases.
