### ISSUE TITLE
Missing node_modules/.bin with hoisted linker

### ISSUE THREAD

**Issue by TrySound** [pnpm/pnpm#6486]
### Code to reproduce the issue:

https://github.com/TrySound/pnpm-hoisted-bin-bug

### Expected behavior:

Single pnpm install creates node_modules/.bin

### Actual behavior:

There is an issue with hoisted linker.

With clean node_modules and after first pnpm install node_modules/.bin in packages are not created. So when run pnpm build there is an error about missing command.

After running pnpm install the second time node_modules/.bin are created and pnpm build in packages start to work.

### Additional information:

 - `node -v` prints: v16.17.1
 - Windows, macOS, or Linux?: Mac OS Ventura

**Comment by zkochan** [comment]
Maybe this is related to this issue: https://github.com/pnpm/pnpm/issues/1801

**Comment by TrySound** [comment]
Maybe, though reproducible without postinstall and with committed target

**Comment by TrySound** [comment]
Another interesting point, the issue is not reproducible with default linker

**Comment by zkochan** [comment]
I'll fix it.

**Comment by TrySound** [comment]
Thank you!
