### ISSUE TITLE
PNPM drops files from installed module

### ISSUE THREAD

**Issue by krichards** [pnpm/pnpm#6494]
### pnpm version: 8.0.0

When trying to install the express-jwt library I'm finding the dist folder is disappearing.  When installing it with npm the dist folder is present.

As a consequence the library does not appear to have any contents.

I suspect the problem might be because the "files" property in the express-jwt package.json contains "/dist".

### Code to reproduce the issue:

pnpm i express-jwt

### Expected behavior:

The node_modules/express-jwt should contain the dist contents

### Actual behavior:

The node_modules/express-jwt just contains the README.md, package.json and LICENSE files.

### Additional information:

 - `node -v` prints: v18.12.1
 - Ubuntu 20.04

**Comment by zkochan** [comment]
I cannot reproduce the issue with `pnpm i express-jwt`. I get a dist folder

**Comment by krichards** [comment]
hmmmm .... I am using a mono repo, so perhaps its related to that. I'll try and recreate it with a blank mono repo.

**Comment by krichards** [comment]
No can't reproduce it with that either.

I've now deleted the node_modules in the root of the mono repo and reinstalled and the dist folder is there!  Looks like a red-herring.
