### ISSUE TITLE
type 'Plugin_2' 'Plugin' is not assignable to type 'PluginOption'.

### ISSUE THREAD

**Issue by kumv-net** [pnpm/pnpm#6501]
pnpm 、TypeScript、vite 支持似乎出现了问题
plugins
类型： (Plugin | Plugin[] | Promise<Plugin | Plugin[]>)[]

https://github.com/vitejs/vite/issues/13027

Reproduction
https://github.com/kumv-net/vite3-4-unocss-macros

**Comment by jakebailey** [comment]
Despite the lack of info, I think there is actually a pnpm bug here.

In pnpm's layout, the path for the version of `unocss` used with `vite@4.3.3` is:

```
./node_modules/.pnpm/unocss@0.51.8_postcss@8.4.23_vite@4.3.3/node_modules/unocss
```

The peer deps appear to all be set up correctly in `unocss`, given the path for this folder shows the intended version. But, write a loop to emulate the lookup order and you'll see that `vite` is not actually in this tree until the "fallback" hoisted deps in `.pnpm/node_modules` (used to try and handle any packages which forget to mark their deps):

```
$ cd ./node_modules/.pnpm/unocss@0.51.8_postcss@8.4.23_vite@4.3.3/node_modules/unocs
$ (while [ $PWD != '/' ]; do TEST="$PWD/node_modules/vite/package.json"; [ -f $TEST ] && echo "$TEST $(jq -r '.version' < $TEST)" && break || echo $TEST not found; cd ..; done)
/home/jabaile/work/vite3-4-unocss-macros/node_modules/.pnpm/unocss@0.51.8_postcss@8.4.23_vite@4.3.3/node_modules/unocss/node_modules/vite/package.json not found
/home/jabaile/work/vite3-4-unocss-macros/node_modules/.pnpm/unocss@0.51.8_postcss@8.4.23_vite@4.3.3/node_modules/node_modules/vite/package.json not found
/home/jabaile/work/vite3-4-unocss-macros/node_modules/.pnpm/unocss@0.51.8_postcss@8.4.23_vite@4.3.3/node_modules/vite/package.json not found
/home/jabaile/work/vite3-4-unocss-macros/node_modules/.pnpm/node_modules/vite/package.json 3.2.6
```

**Comment by await-ovo** [comment]
Should `unocss` add `vite` as peer dependency?  [it only use `vite` in  types ](https://github.com/unocss/unocss/blob/main/packages/unocss/src/vite.ts#L4).

 If `vite` is in the peerDependencies of `unocss`, I think it  should be able to resolve the correct version of `vite`

**Comment by jakebailey** [comment]
I was under the impression that it was already, but, I was wrong. Reading its `package.json`, it's not present there. I think that they are actaully expecting it to be pulled in with `@unocss/vite` which does peer-dep vite: https://github.com/unocss/unocss/blob/main/packages/vite/package.json#L46

So, maybe overall the problem is actually with unocss and they also need to _optional_ peer dep these sidecar packages? Honestly, I'm a little confused as to how one does this to make pnpm happy but avoids accidentally installing all of these sidecar packages on everyone's systems when they're not in use.

**Comment by sapphi-red** [comment]
@kumv-net What is the reason you closed this issue? Is this fixed in the latest version?

**Comment by kumv-net** [comment]
> @kumv-net What is the reason you closed this issue? Is this fixed in the latest version?

Yes, I have upgraded the pnpm and dependencies of my project to the latest version, and the error is no longer present in the project.
