### ISSUE TITLE
Hard-linked local dependencies are not refreshed after first install

### ISSUE THREAD

**Issue by lorenzodallavecchia** [pnpm/pnpm#6502]
### pnpm version:

8.4.0

### Code to reproduce the issue:

See [this repository](https://github.com/lorenzodallavecchia/pnpm-local-dependencies-refresh) and its README file.

### Expected behavior:

When the package.json of a local dependency is no longer aligned with the lockfile, the local dependency should be reinstalled.

### Actual behavior:

The local dependency is not reinstalled.

### Additional information:

 - `node -v` prints: `v16.15.0`
 - Windows, macOS, or Linux?: Windows

**Comment by await-ovo** [comment]
related to #5381
