### ISSUE TITLE
Node version checker bug

### ISSUE THREAD

**Issue by coder8080** [pnpm/pnpm#6506]
Good day time.
In an enterprise project I need to use pnpm with node@16.13.2 . I installed pnpm@8.0.0 and got error output (check below). Node version checker thinks that 16.13 < 16.4 . Looks like you forgot to convert node version from string to number and made lexicographicall comparison instead of numeric.

### pnpm version:
8.0.0

### Code to reproduce the issue:
-- install nvm --
nvm install 16.13.2
nvm use 16.13.2
npm i -g pnpm@8.0.0
pnpm

### Expected behavior:
Output help text

### Actual behavior:
```
➜  ~ pnpm
ERROR: This version of pnpm requires at least Node.js v16.4
The current version of Node.js is v16.13.2
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```

### Additional information:

```
➜  ~ node -v
v16.13.2
```
MacOs Monterey 12.5.1

**Comment by coder8080** [comment]
Found a temporary solution: use pre-compiled version
```
npm i -g @pnpm/exe
```

**Comment by zkochan** [comment]
This was an error in the error message, which was already fixed. The 16.14 is the minimum supported version.
