### ISSUE TITLE
pnpm deploy now fails with MaxListenersExceededWarning

### ISSUE THREAD

**Issue by larsivi** [pnpm/pnpm#6510]
### Last pnpm version that worked:
8.3.1

### pnpm version:
8.4.0

### Code to reproduce the issue:
pnpm --filter=something deploy deployfolder

### Expected behavior:
It completes the command, producing the deployable content

### Actual behavior:
It prints a bunch of (one for every workspace dependency I think)
The modules directory at "/home/foo/code/bar/deploy/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n)

It then prints the messages below, then hangs
(node:277420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:277420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(node:277420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit

### Additional information:

 - `node -v` prints:
 v18.14.2

 - Windows, macOS, or Linux?:
 Linux, recent KDE Neon (Ubuntu based)

**Comment by zkochan** [comment]
Probably we should not display the prompt for the deploy command.

As a workaround, try running it with the `--force` option: `pnpm --force --filter=something deploy deployfolder`
