### ISSUE TITLE
github: protocol extracts entire repo?

### ISSUE THREAD

**Issue by shinebayar-g** [pnpm/pnpm#6512]
### Code to reproduce the issue:

`pnpm i github:chalk/chalk`

### Expected behavior:

package.json's `files` respected & github protocol installs the same package as npm package.
Docs: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files

### Actual behavior:

package.json's `files` doesn't seem to be working. `pnpm i github:chalk/chalk`clones the entire repo.

### Additional information:

 - `node -v` prints: `v18.16.0`
 - Windows, macOS, or Linux?: MacOS

`npm i github:chalk/chalk` installs only package files.
![image](https://user-images.githubusercontent.com/3091558/236663115-395bd0a9-43c5-4dd9-bbd8-b18a19e0ba72.png)

`pnpm i github:chalk/chalk`
![image](https://user-images.githubusercontent.com/3091558/236663162-23c3c73b-fc76-45e0-8240-42bd714212ba.png)
![image](https://user-images.githubusercontent.com/3091558/236663166-500de71b-acb8-4999-982b-f3f0016edcd9.png)

**Comment by DeepDoge** [comment]
It also ignores `.npmignore`

**Comment by zkochan** [comment]
How does it work with npm and Yarn?

**Comment by shinebayar-g** [comment]
`package.json`'s `files` field is used to configure what files are packaged. https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files npm also respects this option when using `npm i github:chalk/chalk` to install the package. Same behavior as `npm i chalk`. But `pnpm i github:chalk/chalk` ignores `files` and installs the whole thing.
