### ISSUE TITLE
 pnpm not recognizing "~" symbols for version dependencies 

### ISSUE THREAD

**Issue by yunqiangwu** [pnpm/pnpm#6516]
在 pnpm 8 中，安装依赖时不识别 ^ 和 ~ 符号，而是默认安装最低版本

我使用 pnpm 8.4.0 安装依赖时，发现它不识别符号 ^ 和 ~，而是默认安装最低版本。在我的 package.json 文件中，我指定了依赖的版本号为 ~16.8.3，但是在安装时，pnpm 仍然安装了 16.8.3 而不是 16.8.6。

> When I tried to install dependencies using pnpm 8.4.0, I found that it doesn't recognize the "^" and "~" symbols, and instead installs the lowest version by default. In my package.json file, I specified the version of the dependency as "~16.8.3", but when I installed it, pnpm still installed version 16.8.3 instead of 16.8.6.

### Code to reproduce the issue:

1. 创建一个新项目并安装 pnpm 8.4.0：

```
mkdir my-project
cd my-project
npm i -g pnpm@8.4.0
```

2. 确认当前 Node 版本：

```
node -v # v16.19.0
```

3. 在 package.json 文件中添加以下内容：

```
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "react": "~16.8.3"
  }
}
```

4. 删除已有的 node_modules 文件夹和 pnpm-lock.yaml 文件：

```
rm -rf node_modules pnpm-lock.yaml
```

5. 安装依赖：

```
pnpm i
```

6. 查看已安装的 react 版本：

```
pnpm list react
```

### Expected behavior:

我期望使用符号 ~ 安装依赖时，pnpm 应该自动滚动升级安装 react@16.8.6 而不应该安装 react@16.8.3。

> I expected that when I installed the dependency using the "~" symbol, pnpm would automatically upgrade and install react@16.8.6 instead of react@16.8.3.

### Actual behavior:

pnpm 安装了 react@16.8.3 而不是我期望的 16.8.6 版本。

> pnpm installed react@16.8.3 instead of the expected version 16.8.6.

### Additional information:

 - `node -v` prints: v16.19.0
 - Windows, macOS, or Linux?: macOS

**Comment by RexSkz** [comment]
There are some breaking changes in PNPM v8 ([release note](https://github.com/pnpm/pnpm/releases/tag/v8.0.0)), one of them is:

- [resolution-mode](https://pnpm.io/npmrc#resolution-mode): set to `lowest-direct` by default.

So for the semver `~16.8.3`, PNPM will find the lowerest version possible that still matches it, which should be `16.8.3`.

If you prefer the behaviour before PNPM v7, you can set `resolution-mode = highest` in the `.npmrc` file.

**Comment by yunqiangwu** [comment]
谢谢你的回复 `resolution-mode = highest` 有用。
