### ISSUE TITLE
When using pnpm up i get waring and errors "ERR_PNPM_META_FETCH_FAIL"

### ISSUE THREAD

**Issue by Falter-Sky** [pnpm/pnpm#6527]
### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: linux fedora 38 
 - ![Screenshot-Evidence](https://github.com/pnpm/pnpm/assets/85581209/0b12407c-27f9-47cb-b3d6-b920af3389c9)

**Comment by zkochan** [comment]
It looks like network issues. Do other package managers work?

**Comment by Falter-Sky** [comment]
no npm doesn't work either but i find out that if you disable IPv6 it works

**Comment by pany-ang** [comment]
pnpm 8.5.0, Ran into the same issue
