### ISSUE TITLE
@pnpm/dependency-path package inaccessible from npm

### ISSUE THREAD

**Issue by SeinopSys** [pnpm/pnpm#6545]
### Code to reproduce the issue:
```
$ mkdir project
$ cd project
$ npm init -y
$ npm install @pnpm/filter-lockfile
```

### Expected behavior:
Installation is successful

### Actual behavior:

Install fails with error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pnpm%2fdependency-path - Not found
npm ERR! 404
npm ERR! 404  '@pnpm/dependency-path@2.1.1' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Local\npm-cache\_logs\2023-05-15T10_04_46_867Z-debug-0.log
```

### Additional information:

 - `node -v` prints: v18.15.0
 - Windows, macOS, or Linux?: Windows

**Comment by llllvvuu** [comment]
npm outage currently:

https://status.npmjs.org/incidents/drj38qn6qm59
https://github.com/search?q=+npm+ERR%21+404&type=issues&s=created&o=desc

**Comment by SeinopSys** [comment]
The npm fix seems to have resolved this issue ,thanks for sharing it!
