### ISSUE TITLE
The `pnpm.updateConfig.ignoreDependencies` configuration in `package.json` is not working.

### ISSUE THREAD

**Issue by u3u** [pnpm/pnpm#6548]
### pnpm version: 

`8.5.1`

### Code to reproduce the issue:

- `pnpm -r up -i --latest`
- `pnpm -r outdated`

### Expected behavior:

These dependencies should not be listed for update.

The `package.json` file in the root directory:

```json
"pnpm": {
  "updateConfig": {
    "ignoreDependencies": [
      "@mantine/*",
      "@types/*",
      "react",
      "react-dom",
      "next"
    ]
  }
}
```

### Actual behavior:

They still appear in the update list.

I also tested command line reverse filtering, which cannot execute commands.

```sh
pnpm -r up -i --latest "!@types/*"
zsh: event not found: @types/

# And strangely, redoing a history command will directly discard the input.
pnpm -r up -i --latest ""
```

### Additional information:

 - `node -v` prints: `18.16.0`
 - Windows, macOS, or Linux?: macOS

**Comment by await-ovo** [comment]
Hi @u3u , maybe this could be a temporary workaround: `pnpm -r update -i --latest "\!@types/*"`. I will try to fix the issue where `updateConfig.ignoreDependencies` is not working as expected.

**Comment by u3u** [comment]
@await-ovo 😘 Thank you! `pnpm -r update -i --latest "\!@types/*"` works! 🥳 
Maybe we should also update the documentation related to `patterns`. 🧐
https://pnpm.io/cli/update#selecting-dependencies-with-patterns
https://pnpm.io/package_json#pnpmupdateconfigignoredependencies
