### ISSUE TITLE
Module not found: Can't resolve 'fs', caused with non-direct dependency `node-gyp-build`.

### ISSUE THREAD

**Issue by uyloal** [pnpm/pnpm#6555]
### pnpm version:

8.5.0

### Code to reproduce the issue:

Use this example:
https://github.com/WalletConnect/web3modal-examples/tree/main/nextjs-wagmi

It's a `nextjs` example using `@web3modal/ethereum` & `wagmi`, they depended on `node-gyp-build`

Then run `pnpm install && pnpm dev`

### Expected behavior:

Normal start of nextjs project, or same as when using npm

### Actual behavior:

The nextjs project does not start properly, and the console outputs the following message:

```shell
> nextjs-wagmi@2.4.1 dev /Users/admin/Desktop/Code/web3modal-examples/nextjs-wagmi
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/liaoyu/Desktop/Code/web3modal-examples/nextjs-wagmi/.env.local
- error ./node_modules/.pnpm/node-gyp-build@4.6.0/node_modules/node-gyp-build/node-gyp-build.js:1:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/node-gyp-build@4.6.0/node_modules/node-gyp-build/index.js
./node_modules/.pnpm/bufferutil@4.0.7/node_modules/bufferutil/index.js
./node_modules/.pnpm/ws@8.12.0/node_modules/ws/lib/buffer-util.js
./node_modules/.pnpm/ws@8.12.0/node_modules/ws/lib/receiver.js
./node_modules/.pnpm/ws@8.12.0/node_modules/ws/index.js
./node_modules/.pnpm/@walletconnect+legacy-client@2.0.0/node_modules/@walletconnect/legacy-client/dist/esm/socket.js
./node_modules/.pnpm/@walletconnect+legacy-client@2.0.0/node_modules/@walletconnect/legacy-client/dist/esm/core.js
./node_modules/.pnpm/@walletconnect+legacy-client@2.0.0/node_modules/@walletconnect/legacy-client/dist/esm/index.js
./node_modules/.pnpm/@walletconnect+legacy-provider@2.0.0/node_modules/@walletconnect/legacy-provider/dist/esm/signer.js
./node_modules/.pnpm/@walletconnect+legacy-provider@2.0.0/node_modules/@walletconnect/legacy-provider/dist/esm/index.js
./node_modules/.pnpm/@wagmi+connectors@1.0.3_@wagmi+chains@0.2.23_react@18.2.0_typescript@5.0.4_viem@0.3.26/node_modules/@wagmi/connectors/dist/walletConnectLegacy.js
./node_modules/.pnpm/@wagmi+core@1.0.5_react@18.2.0_typescript@5.0.4_viem@0.3.26/node_modules/@wagmi/core/dist/connectors/walletConnectLegacy.js
./node_modules/.pnpm/@web3modal+ethereum@2.4.1_@wagmi+core@1.0.5_viem@0.3.26/node_modules/@web3modal/ethereum/dist/index.js
./src/pages/_app.jsx
```

**If I use `npm install && pnpm dev`, it works well. **
**Then, i run `pnpm install` again, it started not working again**

### Additional information:

 - `node -v` prints: v18.15.0
 - Windows, macOS, or Linux?: macOS

**Comment by tatthien** [comment]
I got the same issue. My solution is downgrading `ether-js` from version `6.x.x` to `5.x.x`
<img width="256" alt="Screenshot 2023-05-19 at 11 14 45" src="https://github.com/pnpm/pnpm/assets/72242664/3a3b3b94-7a8e-492e-a3ff-d5216b4a99c0">

**Comment by zkochan** [comment]
Looks like it works with `node-linker=hoisted`.

**Comment by uyloal** [comment]
@zkochan Thanks, it works with `node-linker=hoisted` for me.

**Comment by liangtfm** [comment]
@zkochan is it possible to know why `node-linker=hoisted` fixes the issue? Am I missing out on anything by not using the default `isolated` option?

**Comment by aschenkuttel** [comment]
Also struggle with the same problem trying to use WalletConnect in a Nextjs Project.
Worked last time without a problem, now those errors. Any way of solving this with just npm?

**Comment by zkochan** [comment]
> @zkochan is it possible to know why node-linker=hoisted fixes the issue? Am I missing out on anything by not using the default isolated option?

I don't investigate such issues anymore. In most cases these issues are caused by tools that don't work correctly with symlinks.

You lose the nicer node_modules layout, but other than that, everything should work the same way.

> Also struggle with the same problem trying to use WalletConnect in a Nextjs Project.
Worked last time without a problem, now those errors. Any way of solving this with just npm?

What do you mean? If something doesn't work with pnpm, the easiest way to fix the issue without investigating it is to use the `node-linker=hoisted` setting.

**Comment by linghuccc** [comment]
> > @zkochan is it possible to know why node-linker=hoisted fixes the issue? Am I missing out on anything by not using the default isolated option?
> 
> I don't investigate such issues anymore. In most cases these issues are caused by tools that don't work correctly with symlinks.
> 
> You lose the nicer node_modules layout, but other than that, everything should work the same way.
> 
> > Also struggle with the same problem trying to use WalletConnect in a Nextjs Project.
> > Worked last time without a problem, now those errors. Any way of solving this with just npm?
> 
> What do you mean? If something doesn't work with pnpm, the easiest way to fix the issue without investigating it is to use the `node-linker=hoisted` setting.

I am sorry but where shall I set this?

**Comment by liangtfm** [comment]
> I am sorry but where shall I set this?
@linghuccc you put it in the `.npmrc` file in the root (create it if you don't have one). You can read more about it here https://pnpm.io/npmrc

**Comment by Moganesan** [comment]
i fixed this issue by changing viem from "viem": "^2.6.1" to "viem": "~1.21.4"
