### ISSUE TITLE
DOESN'T WORK AT ALL!!! 😩🔫

### ISSUE THREAD

**Issue by babakfp** [pnpm/pnpm#6564]
### Code to reproduce the issue:

- `pnpm create svelte`
- `pnpm up --latest`

### Additional information:

 - `node -v` prints: v20.1.0
 - Windows, macOS, or Linux?: Windows

https://github.com/pnpm/pnpm/assets/44144724/1cd333cf-694d-4224-b887-5c43cea1592a

**Comment by babakfp** [comment]
VIDEO:
https://github.com/pnpm/pnpm/assets/44144724/76a5b759-7b1e-43c0-8109-01ae214084d7

**Comment by RexSkz** [comment]
The time spent in "resolve" stage mostly depends on network quality, and the download is parallel. Could you try your commands using NPM and see if it's faster?

**Comment by babakfp** [comment]
Have a look at this one. It doesn't even need to download anything, but still, it's stocked like this for minutes! It's the same project that I installed the dependencies a few hours ago but I relocate it so I needed to run `pnpm i` again and now as you see it's stock!

![Screenshot 2023-05-18 221404](https://github.com/pnpm/pnpm/assets/44144724/d3d986d5-5e34-4935-8c2c-eb010313c357)

**Comment by babakfp** [comment]
> Could you try your commands using NPM and see if it's faster?

I haven't used npm for years now, I don't know what to expect.

**Comment by RexSkz** [comment]
Like `npm i`, `pnpm i` also needs to fetch the package info from registry even if there is a lock file and `node_modules` folder.

**Comment by babakfp** [comment]
Back then I was barely able to watch youtube in `360p`, and pnpm was working fine. Now I can easily watch youtube in `720p` but pnpm just doesn't work. It's so freaking slow.

Why downloading a bunch of files is such a hassle?🥲🔫

**Comment by RexSkz** [comment]
It may be because your ISP limits your access to `registry.npmjs.org`. I'm also struggling to access the official NPM registry, but after using VPN, it works.

Or maybe you can try other registries like `registry.yarnpkg.com`.

**Comment by babakfp** [comment]
### In a different project

It looks like it suffocates, it doesn't look right🤷‍♂️ I'm running this for the second time.  The first time it resolved 1275 packages, and the second time it was even slower than the first time.

https://github.com/pnpm/pnpm/assets/44144724/f55ee968-28af-4933-b109-b13c0affc1b1

In this new project it shows something like this warning but in the first project it wasn't showing at all:

```
GET https://registry.npmjs.org/json5 error (ERR_SOCKET_CONNECTION_TIMEOUT). Will retry in 10 seconds. 2 retries left.
```

**Comment by babakfp** [comment]
https://github.com/pnpm/pnpm/assets/44144724/2ddabd83-9e9b-4768-9128-f00cfc712d9c

**Comment by weyert** [comment]
Your videos aren't showing anything? Just all black

**Comment by babakfp** [comment]
> Your videos aren't showing anything? Just all black

You can't play the video? Can you send me a screenshot or a video?

Here, I upload them on DropBox:

- `(FIRST) Rec.0002.mp4`: https://www.dropbox.com/s/oihiqfq1bf4jzlu/%28FIRST%29%20Rec.0002.mp4?dl=0
- `(SECOND) Rec.0002.mp4`: https://www.dropbox.com/s/ekdzb0sqtjt6dtb/%28SECOND%29%20%20Rec.0002.mp4?dl=0
- `(THIRD) Rec.0004.mp4`: https://www.dropbox.com/s/8cth1zrw5z1za6p/%28THIRD%29%20%20Rec.0004.mp4?dl=0

**Comment by babakfp** [comment]
This happens when I use NPM:

![Screenshot 2023-05-19 112458](https://github.com/pnpm/pnpm/assets/44144724/b05366d0-e92f-46ce-941b-2c250ce573ee)

**Comment by babakfp** [comment]
NEW VIDEO:

https://www.dropbox.com/s/3j7gl5u5bs5ezdx/Rec%200002.mp4?dl=0

**Comment by weyert** [comment]
What's this OneDrive directory referring too? Can you try it in a directory that might not be affected/controlled by Dropbox like software?

**Comment by sadeghbarati** [comment]
@babakfp Same here `Done in 14m 57.6s`
Doesn't matter if your packageManager is `npm` or `yarn`, I think it's related to our internet 🐢

**Comment by woss** [comment]
wow, if you are using OneDrive no wonder it is slow. firstly this is mounted to your HDD, second why would you use something like that when you have git and github?

**Comment by babakfp** [comment]
> What's this OneDrive directory referring too? Can you try it in a directory that might not be affected/controlled by Dropbox like software?

It's just the name of the folder. I think Microsoft is trying to push the use of OneDrive so they named the folder OneDrive in Windows 11. **I have actually uninstalled OneDrive software long before**, so nothing is happening behind the seen.

I moved the project folder to another drive (outside of the OneDrive folder) and the result was the same.

**Comment by babakfp** [comment]
> @babakfp Same here `Done in 14m 57.6s` Doesn't matter if your packageManager is `npm` or `yarn`, I think it's related to our internet 🐢

There was a time that my internet speed was worse than ever, but PNPM still worked fine. Also when I was using the `pnpm up --latest` command  (when everything was up to date) it was working instantly and saying something like everything is up to date. But now it takes a long time to even tell me what is happening and I'm **not sure** but I think it tries to install things again!

**Comment by babakfp** [comment]
> wow, if you are using OneDrive no wonder it is slow. firstly this is mounted to your HDD, second why would you use something like that when you have git and github?

What do you mean? I don't have the OneDrive software installed, so... I have also moved the project to another drive and the result was the same.

**Comment by estKey** [comment]
I experienced the exact same thing, and it seems to be a 'network issue.' Just did a pair check npm is able to download packages over 3 MB/s, while pnpm can only do around 3 KB/s. 
There's either a performance pitfall in pnpm or the package sources are rate-limiting the requests. Still don't understand why it just happened to a small group of people.

**Comment by spock123** [comment]
Looking at your screenshots I would say it's your connection to the package repos that for some reason does not work well.

I had this issue a few times, it was mostly due to my own network connection.

**Comment by albbus-stack** [comment]
I usually have really big problems (10-15 minutes) with the _adding_ packages step, after the resolution has finished. Do you have any idea why that might be?

**Comment by zkochan** [comment]
This issue doesn't seem related to pnpm. I don't know any reason why pnpm in the past would've been faster on slow connections. I don't think we have changed anything in this regard.

The easiest way to reduce the amount of network requests is setting `prefer-offline` to `true`. This will drastically reduce the amount of requests.

You can also reduce the amount of simultaneous requests by setting `network-requests` to something smaller than 16.

**Comment by babakfp** [comment]
It happened again!
I can visit npmjs.com with no problems and without using a VPN.
I can use a VPN to connect to youtube.com with no issues.
I try to download a package, and it doesn't work.
PNPM is choked on this screen:
![image](https://github.com/pnpm/pnpm/assets/44144724/f0b94224-6d0b-4010-9ce1-7c86e9fe943e)
There isn't even any visual indication to show what is happening.

---

Never mind, I enabled (Tun and Pac mode) in my v2rayN and it worked! LOL. Other times I can download things without using a VPN, but for some reason it didn't work this time!

---

What is this related to? Is the NPM registry using different servers in different countries for some packages?

Deno has the same issue, it's insane that I need to use a VPN to access free/open-source tools.

**Comment by weyert** [comment]
Maybe your internet provider is causing problems? Maybe they do some deep packet inspection and cause and that is causing issues?

**Comment by babakfp** [comment]
> Maybe your internet provider is causing problems? Maybe they do some deep packet inspection and cause and that is causing issues? It's strange, though. I don't think we do much different then `npm` how we fetch.
> 
> Does using different versions of Node.js make any difference for you?

My internet provider is 100% doing some weird things. Anyway, feel free to close this issue. Thank you to everyone who joined in this conversation and who tried to help. I don't feel like spending more time thinking about this issue. Thanks.
