### ISSUE TITLE
Cli command to check whether lockfile has changed since last pnpm install

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#658]
When a user pulls new code from a contributor, if the shrinkwrap file has changed, they will need to run `pnpm i`.

Pnpm will perform this check when running `pnpm i` by comparing `shrinkwrap.yaml` and `node_modules/.graph.yaml`.

This check should be exposed as a cli command to allow running it in git hook to show the user a message that they need to run `pnpm i`.

The command should have a flag to print a message to the user to run `pnpm i`, making it more convenient to run as a git hook.

E.g. `pnpm check —show-install-message`

If `pnpm i` is made faster would this be necessary? Are there any reasons not to run `pnpm i` on each pull?

- You might want to use a `git checkout` hook, but you sometimes want to quickly switch branches just to look at code without running the app or testing.
- Could pnpm links be overridden?

TODOs added by @zkochan:

- [x] always save deps in `package.json`, even when running `pnpm install foo` w/o the `--save` option
- [x] use a `shrinkwrap.yaml` in the root of `node_modules` instead of `graph.yaml`
- [x] rename `pnpm verify` to `pnpm store status` (maybe add alias `pnpm untouched`)
- [ ] repurpuse the `pnpm verify` command for checking whether the dependency tree in `node_modules` is up to date with the `shrinkwrap.yaml` in the root of the project
- [ ] document a recipe about adding `pnpm verify` to git hooks

**Comment by zkochan** [comment]
There is already the `pnpm verify` command to check whether dependencies were mutated. Maybe it can be extended to make more checks.

**Comment by zkochan** [comment]
Also instead of `node_modules/.graph.yaml` we can probably have just a copy of `shrinkwrap.yaml` in `node_modules`. It would simplify a lot of things.

`graph.yaml` has dependents though, which is pretty useful for uninstalling. Maybe the dependents info can be saved somewhere else

**Comment by zkochan** [comment]
And what to do when a dependency is installed w/o any `--save` option. In that case it will be in `node_modules` but neither in the project's `package.json` nor in the its `shrinkwrap.yaml`.

We should make installations with `--save` the default behavior, like yarn did. So even if someone does `pnpm install` the dependency will be saved in `package.json`

**Comment by zkochan** [comment]
I am a little bit confused with the naming. `pnpm verify` seems to be good naming for a githook. husky, for instance, uses this naming. However, now we use this command for verifying that dependencies were not edited or otherwise mutated...

So we use the verify command? If yes, to what should we rename the current verify command? If no, what should be the name.

`pnpm ok` sounds like a good name as well... but the difference between `pnpm verify` and `pnpm ok` doesn't sound obvious to me. Maybe the current `pnpm verify` command should be renamed to something more obvious, like `pnpm untouched`?

**Comment by vjpr** [comment]
I think the closest analogy is a dirty git working directory. Git has `git reset` and `git clean` to remedy this situation. But I think these could be confusing.

Maybe it could be associated with the "store administration commands" from https://github.com/pnpm/pnpm/issues/430. `verify-store` or something.

But I do like `pnpm untouched`.

**Comment by zkochan** [comment]
hm, there is also `git status`... which is kinda what `pnpm untouched` would do

**Comment by zkochan** [comment]
Or `pnpm store status`

**Comment by zkochan** [comment]
@vjpr you can use [yarnhook](https://github.com/frontsideair/yarnhook), it will run `pnpm install` after git operations if the node_modules needs updates.

Do you think there is still need for a command that just informs? Maybe a flag could be added to `yarnhook`

But I have no objection to have it as a builtin pnpm feature

**Comment by zkochan** [comment]
Seems like we can close it in favor of #2791

**Comment by vjpr** [comment]
Does `--prefer-frozen-shrinkwrap` solve this?
