### ISSUE TITLE
pnpm use env does not check if already installed or not

### ISSUE THREAD

**Issue by am05mhz** [pnpm/pnpm#6587]
if at first we run `pnpm use env --global latest`
then run `pnpm use env --global 16`
then for some reason need to go back to latest `pnpm use env --global latest`
if the latest version have not changed (eg still on 20), it will fail with error:

```
 Fetching Node.js 20.2.0 ...
 EEXIST  EEXIST: file already exists,
```

at least on windows

should be just change the env, or make a separate command for install and use, so that no need to install again, just change the env

**Comment by colinmollenhour** [comment]
Yes, I am using 8.5.1 and cannot switch to another node version, even as administrator:
![image](https://github.com/pnpm/pnpm/assets/38738/98e55803-5d1e-46ef-b2bc-9611d438b13f)

**Comment by Gascognya** [comment]
me too, but not any time

**Comment by Rolanddoda** [comment]
@zkochan this is still an issue in 8.6.0
