### ISSUE TITLE
Adding an alias incorrectly updates dependencies that are using peerDependencies

### ISSUE THREAD

**Issue by mcintyre94** [pnpm/pnpm#6588]
### Code to reproduce the issue:

```sh
pnpm init
pnpm add @solana/web3.js # Currently will add dependency "@solana/web3.js": "^1.77.0"
pnpm add @solana/spl-token
# add an alias of @solana/web3.js using a new experimental version
pnpm add web3js-experimental@npm:@solana/web3.js@experimental # Currently will add dependency "web3js-experimental": "npm:@solana/web3.js@2.0.0-experimental.50fb93e"
```

### Expected behavior:

As I used an alias, I now have a package.json with both the existing 1.77.0 version, and the experimental version:
```json
  "dependencies": {
    "@solana/spl-token": "^0.3.7",
    "@solana/web3.js": "^1.77.0",
    "web3js-experimental": "npm:@solana/web3.js@2.0.0-experimental.ac2f09a"
  }
```

The `@solana/spl-token` package [has a peer dependency](https://github.com/solana-labs/solana-program-library/blob/master/token/js/package.json#L53) on `"^1.47.4"`

This should continue to be satisfied by the version 1.77.0

### Actual behavior:

I get a warning about an unmet peer dependency, where it finds the experimental version but not the one I installed first:

```
 WARN  Issues with peer dependencies found
.
└─┬ @solana/spl-token 0.3.7
  └── ✕ unmet peer @solana/web3.js@^1.47.4: found 2.0.0-experimental.ac2f09a
```

The `node_modules` looks correct: node_modules/@solana/web3.js is version 1.77.0

The pnpm-lock.yaml incorrectly changes dependencies from using 1.77.0 to using 2.0.0-experimental. For example the line `/@solana/spl-token@0.3.7(@solana/web3.js@1.77.0):` is removed, and the line `  /@solana/spl-token@0.3.7(@solana/web3.js@2.0.0-experimental.ac2f09a):` is added. 

### Additional information:

 - `node -v` prints: v18.15.0
 - Windows, macOS, or Linux?: macOS, also reproduced on Linux 

This seems to be specific to peer dependencies. If you try with `@solana/buffer-layout-utils` instead of `@solana/spl-token`, there doesn't seem to be any issue, only additions are made to the pnpm-lock.yaml and existing dependencies stay as they are.

**Comment by steveluscher** [comment]
Possibly related? #6220.

cc/ @RexSkz.

**Comment by RexSkz** [comment]
Yes, I thought #6220 shouldn't have changed the behaviour if it works as expected:

> If there is an aliased and non-aliased one, pick the non-aliased one. If there is only an aliased one, then you pick it. If there are multiple non-aliased ones, then maybe pick the highest one.

But now, the aliased version is picked instead of the non-aliased one.

The temporary solution is adding a `pnpm.packageExtensions` field (the name `web3js-original` can be any string except the name of existing packages):

```json
{
  "pnpm": {
    "packageExtensions": {
      "@solana/spl-token": {
        "dependencies": {
          "web3js-original": "npm:@solana/web3.js@^1"
        }
      }
    }
  }
}
```

@zkochan Should this issue be fixed (make sure aliases don't take place of the non-aliases during peer resolution)? If the effect is acceptable, I'll have a try.

**Comment by zkochan** [comment]
> @zkochan Should this issue be fixed (make sure aliases don't take place of the non-aliases during peer resolution)? If the effect is acceptable, I'll have a try.

Yes, this is a bug.
