### ISSUE TITLE
twice install doesn't skip resolution step

### ISSUE THREAD

**Issue by tjx666** [pnpm/pnpm#6592]
### Code to reproduce the issue: 

github repository: https://github.com/tjx666/pnpm-issue-workspace-version
online: https://stackblitz.com/edit/github-yaxxsn?file=packages%2Ffoo%2Fpackage.json

### Expected behavior:

1. `pnpm install`
2. `pnpm install` again will output `Lockfile is up to date, resolution step is skipped`

### Actual behavior:

no output `Lockfile is up to date, resolution step is skipped`

### Additional information:

 - `node -v` prints: 18.16.0
 - Windows, macOS, or Linux?: MacOS

After I debug code, I find this issue is because https://github.com/pnpm/pnpm/blob/main/pkg-manager/core/src/install/allProjectsAreUpToDate.ts#L117 doesn't consider version number like `workspace`.

You can see my foo package pakcage.json definition:

```
{
    "name": "foo",
    "dependencies": {
         // "bar": "workspace:*" works fine.
        "bar": "workspace",
        "lodash": "^4.17.21"
    }
}
```

**Comment by zkochan** [comment]
It should have failed with an error on the first install. `workspace` is not a supported syntax to reference local workspace projects. `workspace` means install a version under the `workspace` dist-tag.

**Comment by kirklin** [comment]
to reference a local workspace project as a dependency in your package.json file, you can use the following syntax:

```json
{
  "name": "foo",
  "dependencies": {
    "bar": "workspace:*",
    "lodash": "^4.17.21"
  }
}
```

With this updated syntax, running pnpm install should correctly install the dependencies, including the local workspace project bar. Subsequent runs of pnpm install will recognize the lockfile and skip the resolution step if there are no changes to the dependencies.
