### ISSUE TITLE
`pnpm run` swallows empty strings given as parameters

### ISSUE THREAD

**Issue by deiga** [pnpm/pnpm#6594]
### pnpm version: 8.5.1

`pnpm` swallows empty strings from cli arguments, which breaks scripts that might have those

### Code to reproduce the issue:

1. Add a `echo` script to `package.json` => `"echo":"echo",`
2. run the script `pnpm echo "foo" "" "bar"`

### Expected behavior:

- `> echo "foo" "" "bar"`
- `foo   bar`

### Actual behavior:

- `> echo "foo" "bar"`
- `foo bar`

### Additional information:

 - `node -v` prints: v16.16.0
 - Windows, macOS, or Linux?: maOS

**Comment by await-ovo** [comment]
It seems to be caused [here](https://github.com/pnpm/pnpm/blob/main/cli/parse-cli-args/src/index.ts#L143), not sure if this should be fixed, maybe we can just filter the empty string in params for install command.
