### ISSUE TITLE
ESLint Unable to Find Plugin "ts-important-stuff" When Using PNPM on MacOS Silicon Valley

### ISSUE THREAD

**Issue by Mauricio-Arantes** [pnpm/pnpm#6613]
Description:

I am experiencing an issue where ESLint is unable to find plugins specified in my .eslintrc file when I am using PNPM as my package manager on a MacBook Pro 2021 M1 running MacOS.

Here are the relevant software versions I am using:

Node.js: v18.13.0
PNPM: 8.6.0
ESLint: ^8.29.0
The issue occurs when I attempt to run ESLint on my project. The error I receive is "ESLint couldn't find the config "ts-important-stuff" to extend from."

I have attempted several possible solutions, including:

Upgrading Node.js to the latest version
Adding `public-hoist-pattern[]=@typescript-eslint/eslint-plugin` to my .npmrc file
Adding `public-hoist-pattern[]=*eslint-plugin-*` to my .npmrc file
Installing the eslint-config-ts-important-stuff package as a development dependency
Installing the eslint-config-ts-important-stuff package globally
None of these solutions have resolved the issue.

This appears to be a PNPM-specific issue on MacOS with the new architecture, as coworkers using Windows have not experienced this problem.

Any assistance or guidance you could provide would be greatly appreciated.

**Comment by await-ovo** [comment]
Could you provide a minimal repo to reproduce this problem? thanks.

**Comment by Mauricio-Arantes** [comment]
After formatting my computer, this problem is gone. Probaly  I will close this thread
