### ISSUE TITLE
pnpm is not downloading optionalDependencies

### ISSUE THREAD

**Issue by linonetwo** [pnpm/pnpm#6616]
### pnpm version:

8.2.0

### Code to reproduce the issue:

`pnpm i sqlite-vss`

### Expected behavior:

install `sqlite-vss-darwin-x64`

because it has

```json
  "optionalDependencies": {
    "sqlite-vss-darwin-x64": "0.1.1-alpha.13",
    "sqlite-vss-darwin-arm64": "0.1.1-alpha.13",
    "sqlite-vss-linux-x64": "0.1.1-alpha.13"
  },
```

### Actual behavior:

only install `sqlite-vss`

### Additional information:

please read this https://github.com/asg017/sqlite-vss/issues/43

**Comment by zkochan** [comment]
I get `sqlite-vss-darwin-arm64` installed on macOS.

**Comment by linonetwo** [comment]
@zkochan Thank you for check this out, but on my side it didn't show up in the node_modules. How can I check what happened on my side?

![](https://user-images.githubusercontent.com/3746270/241571909-ab904ef4-8774-4fbe-827f-e306e06a3a21.png)

**Comment by saintwinkle** [comment]
> @zkochan Thank you for check this out, but on my side it didn't show up in the node_modules. How can I check what happened on my side?
> 
> ![](https://user-images.githubusercontent.com/3746270/241571909-ab904ef4-8774-4fbe-827f-e306e06a3a21.png)

Should be located at `node_modules/.pnpm/sqlite-vss-darwin-x64@0.1.1-alpha.13`.

**Comment by zkochan** [comment]
Yes, as @saintwinkle said, it will be inside `node_modules/.pnpm`.
Also, any skipped optional dependencies will be in the `skipped` field of the `node_modules/.modules.yaml` file.

**Comment by linonetwo** [comment]
Thank you, confirmed it is in 

1. `node_modules/.pnpm/sqlite-vss-darwin-x64@0.1.1-alpha.19/node_modules/sqlite-vss-darwin-x64`
2. `node_modules/.pnpm/sqlite-vss@0.1.1-alpha.19/node_modules/sqlite-vss-darwin-x64`

---

Including version in the path make it harder to write script to copy these file to electron resource folder when packing electron app, but this will be another story.

**Comment by linonetwo** [comment]
I finally choose directly install them as optionalDependeicies, so copy them is easier

https://github.com/tiddly-gittly/TidGi-Desktop/blob/fed09fc8fd24514a441a15e81139a3ff200cc760/scripts/afterPack.js#L47-L52
