### ISSUE TITLE
resolutions not working in monorepo

### ISSUE THREAD

**Issue by Innei** [pnpm/pnpm#6636]
### pnpm version:

8.6.0

### Code to reproduce the issue:

https://github.com/Innei/pnpm-resolution-reproduction

### Expected behavior:

Monorepo package's field `resolutions` should work behavior like the root package is, setting overrides in pnpm-lock.ymal.

### Actual behavior:

Only overrides the root package's resolutions.
![CleanShot 2023-06-04 at 12 04 01@2x](https://github.com/pnpm/pnpm/assets/41265413/2dbe4052-8bca-45b9-8e91-b972712cf7e4)

<img width="604" alt="CleanShot 2023-06-04 at 12 04 41@2x" src="https://github.com/pnpm/pnpm/assets/41265413/489f6cc3-525e-4004-84ca-9b19bdb60bba">

But monorepo not working.

<img width="554" alt="CleanShot 2023-06-04 at 12 05 00@2x" src="https://github.com/pnpm/pnpm/assets/41265413/8c728174-ebcc-4bb6-a5ba-0d9924043078">

### Additional information:

 v18.15.0
macOS

**Comment by await-ovo** [comment]
Hi, this is as expected, we can only set [resolutions field](https://pnpm.io/package_json#pnpmoverrides) at the root of project ~

**Comment by zkochan** [comment]
Yes, it is expected. I think we need to print a warning when someone puts `resolutions` to a non-root `package.json`.

**Comment by reubenayres** [comment]
Any plans to support package-specific `"resolutions": { ... }` or `"pnpm": { "overrides": { ... } }` at the package level in the future?
