### ISSUE TITLE
ENOENT on any `pnpm dlx` or `pnpm create` commands

### ISSUE THREAD

**Issue by abnerlee** [pnpm/pnpm#6637]
### Code to reproduce the issue:

Open terminal, cd to any folder.
Run any pnpm dlx or pnpm create commands, for example, run
```
pnpm dlx storybook@latest init   
```

### Expected behavior:

Able to work like `npx`

### Actual behavior:

output is error:

```
pnpm dlx storybook@latest init             
.../Library/pnpm/store/v3/tmp/dlx-15014  | +707 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../Library/pnpm/store/v3/tmp/dlx-15014  | Progress: resolved 666, reused 637, downloaded 8, added 707, done
../../../../../Library/pnpm/store/v3/tmp/dlx-15014/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running ../../../../../Library/pnpm/store/v3/tmp/dlx-15014/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running postinstall script, done in 416ms
 ENOENT  ENOENT: no such file or directory, open '/Users/xxx/Library/pnpm/store/v3/tmp/dlx-15014/package.json'
```

### Additional information:

Any pnpm dlx or pnpm create commands returns smillar error: `ENOENT  ENOENT: no such file or directory, open '/Users/xxx/Library/pnpm/store/v3/tmp/dlx-xxxxxx/package.json'`

 - `node -v` prints: v20.2.0
 - Windows, macOS, or Linux?: macOS

**Comment by abnerlee** [comment]
I found the error. I set save=false in npm config, that will case this bug.

**Comment by dhouck** [comment]
And what *was* that cause, and what was the fix?
