### ISSUE TITLE
`pnpm update !xxx` is not working

### ISSUE THREAD

**Issue by LaamGinghong** [pnpm/pnpm#6645]
![image](https://github.com/pnpm/pnpm/assets/33472924/4705fc9b-3e9d-4d6c-8cc5-d00e607c066a)

### pnpm version:
v8.5.1

### Code to reproduce the issue:

`pnpm up !xxx`

### Expected behavior:

Update dependencies exclude what I input.

### Actual behavior:

Terminal throw an error.

### Additional information:

 - `node -v` prints: v16.20.0
 - Windows, macOS, or Linux?: mac

**Comment by await-ovo** [comment]
related to #6548 

`pnpm up "\!xxx"` should work as expected.

**Comment by LaamGinghong** [comment]
I works and maybe you should modify the document.

**Comment by await-ovo** [comment]
> I works and maybe you should modify the document.

sure, docs already updated ~
