### ISSUE TITLE
Getting a lockfile config mismatch after upgrading to version 8.6.1

### ISSUE THREAD

**Issue by justin-betty** [pnpm/pnpm#6649]
### Code to reproduce the issue:
updated from `8.5.1` tot `8.6.1` then run `pnpm install`

### Expected behavior:
No config mismatch

### Actual behavior:
` ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "settings.autoInstallPeers" configuration doesn't match the value found in the lockfile`

after removing the section `settings` in the lock file it works again but this is not what I want to do manually.

### Additional information:

 - `node -v` prints: `v16.4.0`
 - Windows, macOS, or Linux?: `Linux`

**Comment by halostatue** [comment]
For macOS users affected by this who have upgraded through various versions but cannot find the source of the `auto-install-peers=false`, check `~/Library/Preferences/pnpm/rc`.
