### ISSUE TITLE
@pnpm/npm-conf: `The "path" argument must be of type string` error when env.APPDATA is undefined on Windows 

### ISSUE THREAD

**Issue by RandomByte** [pnpm/pnpm#6659]
This is a report of a possible regression in the [`@pnpm/npm-conf`](https://github.com/pnpm/npm-conf) package. We use this package as a transitive dependency of [`update-notifier`](https://github.com/yeoman/update-notifier), via [`registry-auth-token`](https://github.com/rexxars/registry-auth-token/blob/main/index.js#L2).

A user of our package reported the error described below when using it in a Windows environment were the `APPDATA` environment variable is not set (e.g. the Visual Studio Code terminal): https://github.com/SAP/ui5-tooling/issues/833

It looks like a regression to me, since exactly this behavior has been fixed in the original module in the past : https://github.com/kevva/npm-conf/pull/7

I think the issue got re-introduced in your fork with this commit: https://github.com/pnpm/npm-conf/commit/ccf74c4977a4ada380331a3811488486795f3085#diff-b34f2f53ab94368c86775969fb604e8375abe03b6a378bdd09896fd91ac0a0d2R30

### Code to reproduce the issue:

Note: For the lack of a Windows system, I haven't tested this myself. But based on the report, I would expect the following code to produce the error on a Windows system:

```js
process.env.APPDATA = undefined;
require("@pnpm/npm-conf")()
```

### Expected behavior:
Module should initialize fine on Windows, even if the `APPDATA` environment variable is not set.

### Actual behavior:
Module throws an error `The "path" argument must be of type string. Received undefined`

### Additional information:

 - `node -v` prints: 18.16.0
 - Windows, macOS, or Linux?: Windows 11

**Comment by Learces** [comment]
This bug prevents me from installing pnpm under Windows

**Comment by zkochan** [comment]
@RandomByte thanks for the detailed issue.

I have published a fix into `@pnpm/npm-conf@2.2.2`

**Comment by seyaobey** [comment]
I am facing the same issue with `version 8.12.0`. In my case, this error appears only when I attempt to install dev dependencies with the `-D` option.

**Comment by FeMaffezzolli** [comment]
> I am facing the same issue with `version 8.12.0`. In my case, this error appears only when I attempt to install dev dependencies with the `-D` option.

The same problem here. It happens when `-D` is used.
