### ISSUE TITLE
Cannot update pnpm after downgrade

### ISSUE THREAD

**Issue by pitgrap** [pnpm/pnpm#6660]
I updated to pnpm 8.6.1 and used it in a workspace. Everything worked.
After that, I had to downgrade to 8.5.1 for an older project (`pnpm i -g pnpm@8.5.1`). Everything worked.

Now I want to go back to 8.6.1 but I get the following error:

```
❯ pnpm i -g pnpm@8.5.1
 WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
.pnpm                                    |  WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
 ERROR  /@aws-amplify/cli@9.1.0 is an invalid relative dependency path
```

How can I update my pnpm version without deleting the store?
Instead of deleting the store just remove the `lock.yaml` in `~/.local/share/pnpm/global/5/.pnpm` and the `pnpm-lock.yaml` in `~/.local/share/pnpm/global/5`

**Please, please change the major version everytime something changes in the lock file in the future to avoid this breaking changes.** 

### pnpm version:

8.6.1

### Code to reproduce the issue:

```
pnpm i -g pnpm@8.6.1 
#install something globally like pnpm i -g @aws-amplify/cli or install deps in any workspace
pnpm i -g pnpm@8.5.1
pnpm i -g pnpm@8.6.1
```

### Expected behavior:

It works.

### Actual behavior:

It doesn't work and can't update pnpm.

### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: Linux (WSL)

**Comment by zkochan** [comment]
It is caused by this issue: https://github.com/pnpm/pnpm/issues/6648#issuecomment-1586189376

I will fix it. To fix the update issue you may either manually change the lockfile version to 6.0 in the global directory's lockfile. Or install pnpm using the standalone script: https://pnpm.io/installation#using-a-standalone-script

**Comment by zkochan** [comment]
This won't be a problem anymore. I have deprecated the non-backward compatible versions of pnpm. But if it did happen to you, you can try what I suggested above. Or you can uninstall pnpm: https://pnpm.io/uninstall
and then install it again.
