### ISSUE TITLE
Write a custom fetcher in Rust

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#6663]
A complete rewrite of pnpm to Rust would be too time consuming. However, we can write a custom tarball fetcher relatively fast and the fetch operation is one of the most time consuming ones, so the performance benefit may be significant.

**Comment by weyert** [comment]
Out of interest, how would you integrate it with `pnpm`? Are you planning to execute a process that does it or through NAPI?

**Comment by zkochan** [comment]
Using node-rs https://github.com/napi-rs/node-rs

**Comment by gluxon** [comment]
I'm quite excited pnpm is trying out `node-rs`.

Lacking a bit of context, but I have a few considerations I'm hoping are helpful as this is being written:

1. Node.js is fairly great at asynchronous code. If most of the fetcher's performance problems are waiting on network responses, writing the client in Rust may not show noticeable performance gains? On the other hand, if we're seeing slow paths unpacking archives from the registry, that part should get faster.
2. This might require the fetcher to be stateful between calls in the interim. Asynchronous code is a lot more difficult in Rust. Unlike JavaScript, futures aren't automatically driven to completion in Rust. We have to choose an executor (e.g. tokio, async-std) to drive the fetcher to completion. To avoid recreating the executor whenever the fetcher is needed, we'd need some way to persist the executor around between fetch calls. In essence, this would add lifecycle management (e.g. instantiation and cleanup) to the fetcher.

**Comment by zkochan** [comment]
> Node.js is fairly great at asynchronous code. If most of the fetcher's performance problems are waiting on network responses, writing the client in Rust may not show noticeable performance gains? On the other hand, if we're seeing slow paths unpacking archives from the registry, that part should get faster.

I am not sure about that. pnpm is really slow when downloading big files. Maybe because we are downloading and extracting in memory at the same time?

**Comment by gluxon** [comment]
That makes sense. I could definitely see the "_extracting in memory_" part being much faster.

**Comment by zkochan** [comment]
To make it simpler, we can start with making it single threaded. One fetch at a time. That would already allow us to compare it to pnpm by installing single packages with no deps.

**Comment by zkochan** [comment]
I have compared the speed of rust downloading, extracting and writing a package to the content-addressable store. Surprisingly, it was a bit slower then pnpm. I tested it on a single package: typescript@3.5.3

The rust code that I used was this: https://gist.github.com/zkochan/2c5b2880c9dded151730d94b89c8b0a2

I tested the optimised version (`cargo build -r`) and compared it to the `@pnpm/exe` standalone pnpm executable (`pnpm add typescript@3.5.3 --lockfile-only`).

with rust it took 986.16 millis 
pnpm took 873.20 millis

**Comment by andersk** [comment]
It looks like most of your time is spent in the `sha2` crate calculating SHA-256 hashes. `sha2` uses pure Rust for this by default, but you can try enabling its optional `asm` feature for a significant speedup: `cargo add --features=asm sha2`.

**Comment by zkochan** [comment]
I created a custom fetcher: https://github.com/zkochan/tarball-fetcher-rs
This doesn't use a content-addressable store, just unpacks the tarballs.

It can be tested on this repo: https://github.com/zkochan/test-rs-fetcher
should be placed in the same directory where the fetcher as there is a relative require
https://github.com/zkochan/test-rs-fetcher/blob/2ecbb2f66d9506b78344e8b612da8e71eb919b5d/.pnpmfile.cjs#L1

It is much slower then the default js fetcher though. I might do something wrong, I don't know.

**Comment by andersk** [comment]
The biggest issue is that you’re opening a separate new HTTPS connection for each tarball. Sharing the `reqwest::Client` object allows you to use its built-in connection pool: zkochan/tarball-fetcher-rs#1.

**Comment by andersk** [comment]
Doing significant synchronous work directly in an `async` function can [block other asynchronous tasks](https://docs.rs/tokio/1.28.2/tokio/#cpu-bound-tasks-and-blocking-code) from running. Use `task::spawn_blocking` to move that work to a worker thread and leave the asynchronous executor unblocked: zkochan/tarball-fetcher-rs#2.

**Comment by zkochan** [comment]
Thanks! It is much better now. I'll continue the research.

It is now 1s faster than with js but it is not a fair comparison yet.
Looks like pnpm with the custom fetcher is not linking packages to node_modules. Also, my custom fetcher is not calculating checksums of files.

**Comment by listochkin** [comment]
Hi. I took a quick glance over the original gist that @zkochan posted. One thing I notice right away is that even though you use Tokio all writes are done synchronously behind the scenes.

I ran a flame graph generator over the gist, and got the following picture:

![flamegraph-sync](https://github.com/pnpm/pnpm/assets/405222/bbb52bcb-2d21-4300-b540-618fcf8c1c0e)

You can clearly see that `cacache::put::write_hash_sync_with_algo::inner` was taking the majority of time. I decided to do the following:

1. Switch these calls to async version. The idea is that while CPU is busy with SHA256 calculations the OS can keep writing data on disk in background.
2. Parallelize these writes hoping that Tokio can utilize multiple cores with SHA256 calculations.

[The refactoring is very tiny](https://gist.github.com/listochkin/54f103fefc1f7e67bc789462dce72f11): 

```rust
let mut tasks = JoinSet::new();
for entry in node_archive.entries().into_diagnostic()? {
    
    // <snip>

    tasks.spawn(async move {
        let sri_result = cacache::write_hash(STORE_DIR, &buffer).await;

        (cleaned_entry_path_string, sri_result)
    });
}

while let Some(r) = tasks.join_next().await {
    let (cleaned_entry_path_string, sri) = r.into_diagnostic()?;
    let sri = sri.into_diagnostic()?;
    cas_file_map.insert(cleaned_entry_path_string, sri);
}
```

I kept everything - reading the archive entry into buffer, string manipulations, directory creation on demand, etc. - except hashing writes in the same main loop. Writes are put into a task group (think of it as `Promise.all()`). `tasks.spawn` kicks off task execution. `join_next` in `while-let-await` loop produces results out of order - whichever task in a group finished first is produced first.

I kept everything else as-is. Results on my machine are:

* before: ~0.7 seconds
* after: ~0.5 seconds

Here's an "after" flame graph:

![flamegraph-async](https://github.com/pnpm/pnpm/assets/405222/fbb6e3f6-6b7b-45cb-9400-515527e0dd67)

You may notice that it looks very similar. So, CPU-wise we do about the same work (which is expected), but we simply let Rust keep doing calculations without waiting for IO to finish.

Everything I did is largely unscientific, quick and dirty check to see what's up.

**Comment by listochkin** [comment]
Also, first time using **miette**, and omg this thing is way too annoying.

**Comment by zkochan** [comment]
I don't think we will use cacache. This was just faster to do. We'll have to rewrite some of [this code](https://github.com/pnpm/pnpm/tree/main/store/cafs) in Rust to use pnpm's store.

**Comment by zkochan** [comment]
I think I was able to make a fair comparison. It looks like it makes sense to continue work on this as it would improve performance by 10-40%. The biggest improvement is with an up to date lockfile (40%). When the resolution stage cannot be skipped, the improvement is about 10%.

**Comment by StarpTech** [comment]
> I think I was able to make a fair comparison. It looks like it makes sense to continue work on this as it would improve performance by 10-40%

What are the absolutes? Multiple seconds or 100-200ms? I'd favor a bit slower codebase in purely TypeScript than managing a Rust and TypeScript codebase.

**Comment by zkochan** [comment]
it is like 10s vs 19s.

**Comment by StarpTech** [comment]
Thank you, that's significant.

**Comment by anonrig** [comment]
I think there's more to extracting tar then what @zkochan is doing right now. It is possible to download/stream the tar file on a different thread, and simultaneously extract it on a different thread, improving the performance by a lot. I'm investigating it right now. https://github.com/anonrig/pacquet/issues/19

**Comment by anonrig** [comment]
PS: I'm currently working on a Rust rewrite of pnpm: https://github.com/anonrig/pacquet

**Comment by zkochan** [comment]
@anonrig has moved pacquet to the [pnpm org](https://github.com/pnpm/pacquet) and we will be working on it together.

Regarding pnpm performance, I am now working on some optimizations [suggested by David Michon](https://github.com/orgs/pnpm/discussions/6376). I am getting good results, in some cases [33% faster installation](https://github.com/pnpm/pnpm/pull/6850#issuecomment-1668771609).

I think it would be still a good idea to try a mixed approach like described here. Maybe we'll be able to use some crates from pacquet.

**Comment by zkochan** [comment]
We are taking a different approach. There will be an experimental pnpm rewrite in Rust that will be able to perform installation, when the lockfile is up-to-date.

**Comment by zkochan** [comment]
Khai has worked a lot on the Rust implementation of pnpm but for some reason it doesn't perform well. On my machine it is actually slower than pnpm. Maybe someone could help us with figuring out what the bottleneck is. Join the discussion created by Khai: https://github.com/orgs/pnpm/discussions/7296

**Comment by zkochan** [comment]
We have resumed work on Pacquet. As of today, it outperforms pnpm.

**Comment by gluxon** [comment]
Will the plan be to make Pacquet feature complete with pnpm and eventually replace it, or slowly integrate parts of Pacquet into pnpm?

I'd recommend the latter strategy for what it's worth. Rewrites in the software industry often fail because a rewrite takes a long time to be one-to-one with the original, and work on the original stagnates during that time.

**Comment by zkochan** [comment]
There is no formal plan yet. I agree that slowly integrating parts of Pacquet into pnpm would be the best way to do it. I will add a high level roadmap to the pacquet repository in the near future. I think we need to concentrate on making pacquet feature complete for headless installation. That would allow us to replace two stages of installation in pnpm CLI with pacquet. The resolution stage is more complex, so I would start moving that to rust only once fetch and import are stable, ready, and used in production by most of our users.

Roadmap TBD: https://github.com/pnpm/pacquet/issues/299

**Comment by gluxon** [comment]
Nice. The above sounds like a great plan so far. Thanks for clarifying!
