### ISSUE TITLE
Environment Variables left of `=` equals sign are not substituted when reading `.npmrc`

### ISSUE THREAD

**Issue by mamidenn** [pnpm/pnpm#6679]
Any variables in `.npmrc` that occur left of the equals sign (i.e. in the key) are not substituted when reading the config. This behavior deviates from `npm` where they are substituted.

Our specific use case is dynamically configuring the registry authorization:
```
# .npmrc
//${REGISTRY}:_authToken=${TOKEN}
```
The value `${TOKEN}` is set as expected but the key is used as-is.

### pnpm version:
8.6.2

### Code to reproduce the issue:
```
echo "\${FOO}=\${BAR}" > .npmrc
FOO=foo BAR=bar pnpm config list
```

### Expected behavior:
Variable `${FOO}` is substituted with value `foo` and used as key.
```
foo=bar
```

### Actual behavior:
`${FOO}` is not substituted
```
${FOO}=bar
```

### Additional information:

 - `node -v` prints: `v20.3.0`
 - Windows, macOS, or Linux?: Linux, tested in latest `node` container after installing `pnpm` via `https://get.pnpm.io/install.sh`
 - The issue appears to be a missing implementation of key replacement in [readLocalConfig.ts]( https://github.com/pnpm/pnpm/blob/0d65d62c95440ff124e2733f13053b10fba8e8d6/config/config/src/readLocalConfig.ts#LL20C11-L20C53).

**Comment by gdosherjc** [comment]
I'm experiencing the same thing in v8.7.6. 

Are there any known workarounds for this?

**Comment by ckolumbus** [comment]
any progress here? Does something prevent this PR from being merged?

**Comment by ckolumbus** [comment]
any progress here? can I support to get this into one of the next versions?
