### ISSUE TITLE
Peer dependency unexpectedly satisfied by aliased package

### ISSUE THREAD

**Issue by privatenumber** [pnpm/pnpm#6689]
### Code to reproduce the issue:
package.json
```json5
{
	"dependencies": {
		"mini-css-extract-plugin": "1.6.2",
		"webpack": "4.4.0",
		"asdfasdfasdfasdfasd": "npm:webpack@5.0.0"
	}
}
```

### Expected behavior:
Since Webpack 5.0.0 is installed under the alias `asdfasdfasdfasdfasd`, it should not be resolvable by `mini-css-extract-plugin` under the name `webpack`.

### Actual behavior:
However, when `mini-css-extract-plugin` does `require('webpack')`, Webpack 5.0.0 is loaded. In other words, Webpack 5.0.0 is installed to the name `webpack` (pnpm ignores the alias) for `mini-css-extract-plugin`, instead of Webpack 4.4.0.

### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
There is already an issue about this: https://github.com/pnpm/pnpm/issues/6588

**Comment by privatenumber** [comment]
Thanks for catching that! Closing this out in favor of that one.
