### ISSUE TITLE
Allow to use `--parallel` without monorepo (in a single project)

### ISSUE THREAD

**Issue by ai** [pnpm/pnpm#6692]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I found `pnpm` as a pretty powerful task runner with `--parallel` task execution.

But I found that I can use it only in monorepo with multiple projects. If I have a simple project, I will get:

```json
{
  "private": true,
  "scripts": {
    "build": "vite build -m production",
    "test:types": "tsc --noEmit && eslint . && stylelint **/*.css",
    "test:js": "eslint .",
    "test:css": "stylelint **/*.css",
    "test:audit": "pnpm audit --prod --audit-level high",
    "test:build": "pnpm build && size-limit",
    "test": "pnpm run --parallel /^test:/"
  }
}
```

```
❯ pnpm test

> oklch-picker@ test /home/ai/Dev/oklch-picker
> pnpm run --parallel /^test:/

No projects matched the filters in "/home/ai/Dev/oklch-picker"
```

**Describe the solution you'd like**

Allow to use `--parallel` if a user pass a RegExp for tasks,

**Describe the drawbacks of your solution**

Don’t see any

**Describe alternatives you've considered**

N/A

**Comment by zkochan** [comment]
Why do you need `pnpm run --parallel /^test:/`? `pnpm run /^test:/` is already running all scripts that match the regex in parallel. 

> You may run multiple scripts at the same time by using a regex instead of the script name.

source: https://pnpm.io/cli/run#running-multiple-scripts

**Comment by ai** [comment]
> pnpm run /^test:/ is already running all scripts that match the regex in parallel.

1. If it already does, it's great. I thought that I should enable it somehow. But let’s avoid the error, since other users can think that like me that you need a special argument.
2. I also need that `pnpm -r test` UI which print output of every script in separated “window”.
