### ISSUE TITLE
Deploy command gets an incorrect node_modules structure

### ISSUE THREAD

**Issue by 2239559319** [pnpm/pnpm#6697]
### pnpm version:
`8.6.3`
### Code to reproduce the issue:

The project is [2239559319/pnpm-deploy-test](https://github.com/2239559319/pnpm-deploy-test/tree/master)

run commands

```
pnpm i

pnpm --filter a deploy ./pruned
```

### Expected behavior:

The `react` version in node_modules folder is `18.2.0` and there is no vue in the node_modules.

### Actual behavior:

![image](https://github.com/pnpm/pnpm/assets/34960995/ed14aeac-44ab-44fd-beda-7b12b2ab4ec0)

### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: Linux

**Comment by 2239559319** [comment]
@zkochan help please

**Comment by thib3113** [comment]
maybe linked, maybe not . But, from version 8 I got an error when running deploy command .

In my side, it end with error `ENOENT  ENOENT: no such file or directory, unlink 'XXXXX\pruned\node_modules\moleculer'` ( but the folder exist ) . 

with windows 11 / node v20.3.1

( only the same command, and I can't isolate the error at the moment ... so maybe not linked at all )

**Comment by 2239559319** [comment]
> maybe linked, maybe not . But, from version 8 I got an error when running deploy command .
> 
> In my side, it end with error `ENOENT  ENOENT: no such file or directory, unlink 'XXXXX\pruned\node_modules\moleculer'` ( but the folder exist ) . 
> 
> with windows 11 / node v20.3.1
> 
> ( only the same command, and I can't isolate the error at the moment ... so maybe not linked at all ) 

The question seems to behave differently on different os. But none of them met expectations.

**Comment by YegorMedvedev** [comment]
I tried different PNPM versions and all of them failed with the same error (_8.6.6, 8.4.0, 8.3.0, 8.1.1, 8.0.0_).
```
ENOENT: no such file or directory, unlink '/pruned/node_modules/uuid'
```

I use MacOS 13.1, Node JS v18.16.0

**Comment by await-ovo** [comment]
It seems related to https://github.com/pnpm/pnpm/issues/6300.

In the case `dedupe-peer-dependents` is `true`, the `webpack` dependency of the root directory should also appear in `./dist/node_modules` at the end, but it is actually installed in this directory: `pnpm-deploy-test/../../dist`. This looks a bit weird, maybe this needs to be fixed ~

**Comment by thib3113** [comment]
@await-ovo I confirm ... 

adding 
```
dedupe-peer-dependents=false
```
in my npmrc resolve my problem .

**Comment by zkochan** [comment]
:ship: 8.6.11
