### ISSUE TITLE
`pnpm dlx <package command>` with no further arguments errors with exit code 1

### ISSUE THREAD

**Issue by ferntheplant** [pnpm/pnpm#6698]
### pnpm version: 
8.6.3

### Code to reproduce the issue: 
`pnpm dlx create-react-app` or `pnpm dlx shadcn-svelte`

### Expected behavior: 
pnpm should output the command's default output (usually a help dialog) and exit with code 0 as it does with `npx`

### Actual behavior: 
pnpm exits with code 1 and a useless stack trace

### Additional information: 
Originally discovered with [shadcn-svelte
](https://github.com/huntabyte/shadcn-svelte/issues/27)
 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: macOS

**Comment by await-ovo** [comment]
I think this is as expected, the exit code of `npx create-react-app` is also `1`:

```
$ npx create-react-app
Please specify the project directory:
  create-react-app <project-directory>

For example:
  create-react-app my-react-app

Run create-react-app --help to see all options.

$ echo $?
1
```

**Comment by zkochan** [comment]
We can remove the error stack but the error code is correct. create-react-app exited with 1, so pnpm exits with 1 too.
