### ISSUE TITLE
Different behavior with npm install

### ISSUE THREAD

**Issue by PeterDaveHello** [pnpm/pnpm#67]
If I run `npm install` in dir `node_modules`, npm will not create a new `node_modules`, it'll just put the installed lib under the same `node_modules`. but pnpm will create a new `node_modules`, I'm not sure if this is expected.

**Comment by rstacruz** [comment]
yeah, this is bit of a deviation that should probably be corrected. at the moment, it looks for the existence of `package.json`, not `node_modules` (that i later found out to be the case).

In the mean time, you can work around this behavior by adding a `package.json` to your project.
