### ISSUE TITLE
Pnpm installs an earlier version on second installation of a dependency.

### ISSUE THREAD

**Issue by mosuzi** [pnpm/pnpm#6716]
### Code to reproduce the issue:
Run command below in an empty dir:
```shell
pnpm i --save vue@2
```
Pnpm installs `vue@2.7.14` and package.json looks like:

```JSON
{
  "dependencies": {
    "vue": "2"
  }
}
```

Then delete node_modules and lockfile and run:

```shell
pnpm i
```
And pnpm installs vue@2.0.0

### Expected behavior:

The second time `pnpm i` is executed, install right version of vue@2.7.14.

### Actual behavior:

Vue@2.0.0 is installed.

### Additional information:

 - `node -v` prints: 16.20.0
 - Windows, macOS, or Linux?: Windows 10

**Comment by moontai0724** [comment]
I'm also facing this issue today, following table is a general test result running on my machine using `CentOS 3.10.0-1160.90.1.el7.x86_64`.

For following table, please reference following list:

- `v2.0` executes `vue@2.0`
- `major-v2.0` executes `vue@^2.0`
- `minor-v2.0` executes `vue@~2.0`

In this test, seems like the version above v8 are installing incorrect version.

|        | v2.0 (add) | v2.0 (install) | major-v2.0 (add) | major-v2.0 (install) | minor-v2.0 (add) | minor-v2.0 (install) |
| :----: | :--------: | :------------: | :--------------: | :------------------: | :--------------: | :------------------: |
| 8.6.5  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.6.4  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.6.3  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.6.2  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.6.1  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.6.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.5.1  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.5.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.4.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.3.1  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.3.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.2.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.1.1  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.1.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 8.0.0  |  + 2.0.8   |    + 2.0.0     |     + 2.7.14     |       + 2.0.0        |     + 2.0.8      |       + 2.0.0        |
| 7.33.2 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.33.1 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.33.0 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.32.5 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.32.4 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.32.3 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.32.2 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.32.1 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.32.0 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 6.35.1 |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |
| 7.1.0  |  + 2.0.8   |    + 2.0.8     |     + 2.7.14     |       + 2.7.14       |     + 2.0.8      |       + 2.0.8        |

---

**Comment by zkochan** [comment]
Duplicate. See related issue: https://github.com/pnpm/pnpm/issues/6463
