### ISSUE TITLE
Pnpm fails silently when installing a github repo that previously had no package.json

### ISSUE THREAD

**Issue by roninjin10** [pnpm/pnpm#6721]
### Code to reproduce the issue: 

`pnpm i https://github.com/foundry-rs/forge-std.git#e8a047e3f40f13fa37af6fe14e6e06283d9a060e` or have this package in your package.json.  Note the commit directly after this commit has a package.json added and installing that commit works fine.  When installing this commit nothing happens and no error is thrown. If this commit is in your package.json you cannot pnpm install at all or pnpm import and it will fail silently with no error messages
![image](https://github.com/pnpm/pnpm/assets/35039927/d32c0ade-d1d6-4e9f-98a6-94e53ededf58)

### Expected behavior: 

Should throw a useful error message

### Actual behavior: 

When installing this commit nothing happens and no error is thrown. If this commit is in your package.json you cannot pnpm install at all or pnpm import and it will fail silently with no error messages

### Additional information:

 - `node -v` prints: v16.17.1
 - Windows, macOS, or Linux?: macos

**Comment by await-ovo** [comment]
There may be an unresolved promise that causes the process to exit directly
