### ISSUE TITLE
Pnpm seems unable to solve the problem caused by multiple versions of ajv-keywords

### ISSUE THREAD

**Issue by lvzhenbo** [pnpm/pnpm#6722]
### Additional information: Using Yarn is no problem. [Similar issues](https://github.com/facebook/docusaurus/issues/6073)

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: Win 11

**Comment by zkochan** [comment]
add `node-linker=hoisted` to `.npmrc` in the root of the repo. Run `pnpm install`.

You'll get the same result as with Yarn.

**Comment by sibelius** [comment]
node-linker=hoisted did not fixed for me
