### ISSUE TITLE
default hoist packages may cause unexpected result

### ISSUE THREAD

**Issue by moontai0724** [pnpm/pnpm#6738]
[According to the docs](https://pnpm.io/npmrc#public-hoist-pattern), pnpm by default hoists packages that match the `*eslint*` and `*prettier*` patterns. While I'm not certain about the reasoning behind pnpm's decision to mark these packages as default hoist packages, this behavior can potentially lead to unexpected results.

## Example

For example, the [`redis@3.0.0`](https://github.com/redis/node-redis/blob/v3.0.0/package.json#L39) accidentally includes a `prettier` dependency.

When using it, means the `prettier` package will be hoisted to root of `node_modules`. Due to an unknown behavior difference between the [batteries included VSCode extension of prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and the installed version, this will resulted in following format behavior difference.

### Format Result Without Dependency Installed

```typescript
const exampleVariableAboutPrettierFormatDifference: Required<string> =
  JSON.stringify({
    test: "value",
  });
```

### Format Result With Dependency Installed

```typescript
const exampleVariableAboutPrettierFormatDifference: Required<string> = JSON.stringify(
  {
    test: "value",
  }
);
```

### Who may be affected

In this example, the problematic version is `3.0.0`, and it [has been fixed in the next version `3.0.2`](https://github.com/redis/node-redis/compare/v3.0.0...v3.0.2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519). However, this issue doesn't only affect those who specifically installed `redis@3.0.0`.

As a result of [issue #6716](https://github.com/pnpm/pnpm/issues/6716), packages that have specified `redis^3` or `redis@~3` as dependencies will also be affected due to incorrectly parsed version requirements.

## Summary

Although both npm and Yarn also place all packages in the root directory of `node_modules`, I believe that pnpm introduces this feature in an attempt to resolve the issue of phantom dependencies.

Therefore, I recommend to replace the default hoist packages with an empty array to prevent any unexpected phantom dependencies. Let users to mark packages only for what they expected.

---

### Code to reproduce the issue:

Install any package depends on `prettier`

```shell
pnpm install redis@3.0.0
```

### Expected behavior:

To contains `redis` only in root of `node_modules`.

```
node_modules/
├── .pnpm/
│   ├── prettier@1.19.1/
│   │   └── node_modules/
│   │       └── prettier/
│   │           ├── node_modules/
│   │           │   └── .bin/
│   │           │       └── prettier
│   │           └── package.json
│   ├── redis@3.0.0/
│   │   └── node_modules/
│   │       └── prettier/
│   │           ├── node_modules/
│   │           │   └── .bin/
│   │           │       └── prettier
│   │           └── package.json
│   └── lock.yaml
├── redis/
│   ├── node_modules/
│   │   └── .bin/
│   │       └── prettier
│   └── package.json
└── .modules.yaml
```

### Actual behavior:

Non-dependency `prettier` has been hoisted to root.

```
node_modules/
├── .bin/
│   └── prettier
├── .pnpm/
│   ├── prettier@1.19.1/
│   │   └── node_modules/
│   │       └── prettier/
│   │           ├── node_modules/
│   │           │   └── .bin/
│   │           │       └── prettier
│   │           └── package.json
│   ├── redis@3.0.0/
│   │   └── node_modules/
│   │       └── prettier/
│   │           ├── node_modules/
│   │           │   └── .bin/
│   │           │       └── prettier
│   │           └── package.json
│   └── lock.yaml
├── prettier/
│   ├── node_modules/
│   │   └── .bin/
│   │       └── prettier
│   └── package.json
├── redis/
│   ├── node_modules/
│   │   └── .bin/
│   │       └── prettier
│   └── package.json
└── .modules.yaml
```

### Additional information:

- Prettier VSCode Extension Version: v9.16.0

**Comment by zkochan** [comment]
Unfortunately, eslint and prettier will break without these hoisting settings. We want to reduce the number of issues that new users will get. You can disable this hoisting in your project by putting `public-hoist-pattern[]=` in an `.npmrc` in the root of the project. Changing the default is not an option.
