### ISSUE TITLE
Docs: enumerate all important environment variables in one place

### ISSUE THREAD

**Issue by qpwo** [pnpm/pnpm#6776]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

I have various environment variables in my CI setup for various tools (e.g. NODE_ENV=staging). Some of these affect pnpm (e.g. CI=true) but I'm not sure which ones do and how. There's mention of a couple env vars here and there.

**Describe the solution you'd like**

Add a section to https://pnpm.io/pnpm-cli which describes all known important environment variables for pnpm CLI.

**Describe the drawbacks of your solution**

Page may become out of date and mislead users.

**Describe alternatives you've considered**

Could have `pnpm env-vars` which prints all the important environment variables and their current settings (including unset ones) like

```
$ pnpm env-vars
CI=
NODE_ENV=production
OTHER_UNSET_THING=
```

Seems like more work than the docs page but could be more useful

**Comment by zkochan** [comment]
All the env variables are already documented and are easily searchable. Copy/pasting content to the pnpm cli page with slight changes to the text would create more work for translators of the docs. It would also make seach in the docs less straightforward.

The only thing that we could maybe document is something like the list of system-related env variables that affect how pnpm CLI works. Probably without description, just links to related contents in the docs.
