### ISSUE TITLE
brew install pnpm without nodejs installed first resulting in broken pnpm

### ISSUE THREAD

**Issue by Exegetech** [pnpm/pnpm#6793]
I want to use PNPM to manage NodeJS versions. Ideally I want to start with having no NodeJS in the system. I want to use PNPM, then use PNPM to install and manage NodeJS.

### Code to reproduce the issue:
Without having NodeJS in the system, use homebrew to install pnpm

```shell
brew install pnpm
```

After installed, just run any pnpm command

```shell
pnpm
```

### Expected behavior:
Can run PNPM

### Actual behavior:
```shell
env: node: No such file or directory
```

### Additional information:

 - `node -v` prints: Unknown command: node
 - Windows, macOS, or Linux?: MacOS Ventura 13.0.1

**Comment by zkochan** [comment]
brew installs the non-bundled version of pnpm. If you want to use pnpm without node.js, install it with the [standalone script](https://pnpm.io/installation#on-posix-systems).

**Comment by Exegetech** [comment]
Oh I see, thank you so much!
