### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by liangjl76** [pnpm/pnpm#6805]
### pnpm version:

8.6.7

### Code to reproduce the issue:

pnpm add jsdoc@3.2.0

### Actual behavior:

pnpm: Command failed with exit code 128: git -c core.longpaths=true fetch --depth 1 origin 95c5d505
Host key verification failed.
fatal: Could not read from remote repository.

### Additional information:

 ERROR  Command failed with exit code 128: git -c core.longpaths=true fetch --depth 1 origin 95c5d505
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

pnpm: Command failed with exit code 128: git -c core.longpaths=true fetch --depth 1 origin 95c5d505
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (E:\prog\npm\node_modules\pnpm\dist\pnpm.cjs:24796:17)
    at handlePromise (E:\prog\npm\node_modules\pnpm\dist\pnpm.cjs:25367:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async gitFetcher (E:\prog\npm\node_modules\pnpm\dist\pnpm.cjs:113063:11)
    at async fetcher (E:\prog\npm\node_modules\pnpm\dist\pnpm.cjs:125600:16)
    at async run (E:\prog\npm\node_modules\pnpm\dist\pnpm.cjs:124984:23)
Progress: resolved 8, reused 0, downloaded 8, added 0

 - `node -v` prints:v16.18.1
 - Windows, macOS, or Linux?:windows   -- Microsoft Windows [版本 10.0.14393]

**Comment by liangjl76** [comment]
The code that generates the problem is as follows:
```js
        const tempLocation = await cafs.tempDir();
        if (allowedHosts.size > 0 && shouldUseShallow(resolution.repo, allowedHosts)) {
          await execGit(["init"], { cwd: tempLocation });
          await execGit(["remote", "add", "origin", resolution.repo], { cwd: tempLocation });
          await execGit(["fetch", "--depth", "1", "origin", resolution.commit], { cwd: tempLocation });
        } else {
          await execGit(["clone", resolution.repo, tempLocation]);
        }
```
The actual execution is the following command
```
git init
git remote add origin git+ssh://git@github.com/dominictarr/crypto-browserify.git
git -c core.longpaths=true fetch --depth 1 origin 95c5d505
```

After multiple steps, the following error is finally reported:
fatal: couldn't find remote ref 95c5d505
This is the fundamental reason

Remove +ssh from the url, it directly reports the above error
```
git init
git remote add origin git://git@github.com/dominictarr/crypto-browserify.git
git -c core.longpaths=true fetch --depth 1 origin 95c5d505
```

Why use git+ssh here instead of directly using git?
this makes the error very clear and understandable

**Comment by KSXGitHub** [comment]
While this is certainly a bug on pnpm's part, for the time being, the latest version of `jsdoc` (v4.0.2) can be installed successfully by pnpm.

**Comment by KSXGitHub** [comment]
@liangjl76  I forgot to say thank you for your own investigation on this bug, without it, it would have taken me a longer time to find solve it.

**Comment by zkochan** [comment]
I had to temporarily revert the fix but we'll have another fix.

**Comment by KSXGitHub** [comment]
https://github.com/pnpm/pnpm/pull/6832 should fix both this bug and the other bug

**Comment by orgoj** [comment]
I can't install repo https://github.com/signal-ai/angular-sha1.git

ERROR  Command failed with exit code 128: git ls-remote git+ssh://git@github.com/SignalMedia/angular-sha1.git HEAD
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

With https protocol command git ls-remote working, with git+ssh not.

Pnpm Version 7.33.4 is ok, but 7.33.6 or 8.7.1 have this error..

**Comment by KSXGitHub** [comment]
@orgoj Why would you want to use ssh on a public repo?

**Comment by orgoj** [comment]
@KSXGitHub I don't use ssh on public repo. In package.json i have https, but pnpm try git ls-remote with git+ssh.

**Comment by KSXGitHub** [comment]
> I can't install repo https://github.com/signal-ai/angular-sha1.git

This repo doesn't even have `package.json`. Can you try a public repo that have one?

**Comment by KSXGitHub** [comment]
> Repo `https://github.com/signal-ai/angular-sha1.git` is instalable by npm, yarn.

npm certainly does not:

![npm v10 fails to install it](https://github.com/pnpm/pnpm/assets/11488886/b4b6dcc1-d42b-4791-8303-1c584e7ab548)

**Comment by KSXGitHub** [comment]
Interestingly enough, pnpm@8.7.1 supports it, and run it without issue:

![pnpm supports it (full url)](https://github.com/pnpm/pnpm/assets/11488886/b773268f-83a5-4992-b3be-7e8ff9baffad)

![pnpm supports it (shorthand)](https://github.com/pnpm/pnpm/assets/11488886/c66dfc8b-a88c-4601-8e7a-805018feab96)

**Comment by 1zilc** [comment]
![image](https://github.com/pnpm/pnpm/assets/44715458/137a40ce-9da9-4dd5-8a5a-1bc248a0df94)

**Comment by fruitbang** [comment]
pnpm -v: 8.12.1
problem still exists

Why does pnpm try to use ssh when it is possible not to use ssh. o_O

>
ERROR  Command failed with exit code 128: git ls-remote git+ssh://git@github.com/tanstack/react-query.git HEAD
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
<

**Comment by NikolaIliev** [comment]
Not sure why this is closed, the issue is still present. pnpm will always use ssh even if the package.json/pnpm-lock.yaml uses an https url

Current workaround if installing in a container is to force git to clone via https for the specific packages you need, e.g.:

```
git config --global url."https://github.com/username/repository.git".insteadOf git@github.com:username/repository.git
```

**Comment by oeyoews** [comment]
https://github.com/pnpm/pnpm/issues/7517  I am also confused. This problem still exists in 9.6.0

**Comment by gustawdaniel** [comment]
in 9.7.0 too

```
➜  front git:(strapi-update) ✗ pnpm i tailwindcss/colors 
 ERROR  Command failed with exit code 128: git ls-remote git+ssh://git@github.com/tailwindcss/colors.git HEAD
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

This error happened while installing a direct dependency of /home/daniel/pro/unexpected-poland/front

pnpm: Command failed with exit code 128: git ls-remote git+ssh://git@github.com/tailwindcss/colors.git HEAD
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:19412:17)
    at handlePromise (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:19983:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:113464:23)
    at async resolveRef (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:113476:20)
    at async resolveGit (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:113415:24)
    at async Object.resolve (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:113727:175)
    at async run (/home/daniel/.cache/node/corepack/v1/pnpm/9.7.0/dist/pnpm.cjs:132480:23)
Progress: resolved 15, reused 15, downloaded 0, added 0
➜  front git:(strapi-update) ✗ pnpm --version           
9.7.0
```

**Comment by sathishkannan162** [comment]
facing the same issue

**Comment by Mister-Hope** [comment]
@KSXGitHub @zkochan Can anyone review this? This seems not correctly fixed.

Private keys are not supposed to exist on GitHub Workflows, so the following errors are throw when pnpm force using ssh to clone:

```
ERROR  Command failed with exit code 128: /usr/bin/git clone git@github.com:xqq/webworkify-webpack.git /home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c
Cloning into '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

pnpm: Command failed with exit code 128: /usr/bin/git clone git@github.com:xqq/webworkify-webpack.git /home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c
Cloning into '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:17863:17)
    at handlePromise (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:18434:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async execGit (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:114189:7)
    at async gitFetcher (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:114144:11)
    at async fetcher (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:133706:[16](https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/12532941022/job/34952136592#step:5:17))
    at async run (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:133156:23)
Error: Process completed with exit code 1.
```
