### ISSUE TITLE
CI Installation performance

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#6808]
### Discussed in https://github.com/orgs/pnpm/discussions/6376

<div type='discussions-op-text'>

<sup>Originally posted by **dmichon-msft** April 11, 2023</sup>
## Summary
I've recently been doing work on dependency installation performance, since installations on my team's Linux CI agents are rather slower than I'd like (our repository serves about 300 developers at Microsoft). Following some guidance from one of my colleagues who has been doing installation performance work for an internal fork of Yarn, I was able to put together a CI-mode installer that reads the pnpm-lock.yaml and installs all the packages in the same layout (as seen by user code) in about 8% of the time.

## Old Install (`pnpm install --frozen-lockfile`)
pnpm version: 7.26.1
total packages: 7032 downloaded, 7406 installed, 8297 linked (including workspace packages)
mode: no cache, yes lockfile, no node_modules
agent: D32ads_v5 Azure SKU
os: Linux
duration: **5 minutes, 14.5 seconds**

## New Install (`rush phased-install`) (local custom algorithm)
total packages: 7032 downloaded, 7406 installed, 8297 linked (including workspace packages)
mode: no cache, yes lockfile, no node_modules
agent: D32ads_v5 Azure SKU
os: Linux
duration: **23.6 seconds**

## How the custom installer works
1) Reads `pnpm-lock.yaml`, constructs a task graph
1) Opens 10 (configurable) separate HTTP/2 connections to the registry endpoint (via the raw `node:http2` `connect(url, options)` API).
1) For each unique package/version (tarball) in the graph, creates an HTTP/2 stream on one of the connections (uniformly distributed), expecting to receive a 303 redirect. The redirect occurs because the underlying streams don't originate on the registry server.
1) Forward the results from each redirect to a concurrent asynchronous queue that will download the tarball into memory via use of the raw `node:https` module. Configure the `https.Agent` to ensure that the timeout is at least 60 seconds.
1) When each tarball finishes downloading, merge the results into a new `ArrayBuffer` and `postMessage` it (with transfer) to a worker thread for parsing. Allow up to `#CPUs * 0.9` (configurable) concurrent worker threads. This ensures that the main thread is not doing any significant CPU work.
1) In the worker thread, validate the integrity hash of the raw tarball, then perform synchronous gunzip and copy the result to a `SharedArrayBuffer`. Synchronously parse the raw TAR buffer, identifying generating a Map from filename to `{ mode, offset, length }`.
1) Send the `SharedArrayBuffer` and map back to the orchestrator via `postMessage`, so that it can be load balanced again, and so that the orchestrator can get access to the information in `package.json`.
1) Load balance the parsed tar buffers across a pool of worker threads (just as for parsing), each of which performs synchronous I/O via `mkdirSync`/`openSync`/`writeSync`/`closeSync` to produce the output files.
1) After the dependencies of each package have been unpacked, perform any necessary installation steps (link bins, apply patches, run install scripts).

While the download is ongoing, the installer can be busy creating all the necessary `node_modules` symlink layouts, since that doesn't depend on the downloads.

## Performance notes
On Windows, unpack time increases by about 10x relative to Linux. I haven't found any ways around this; the parse/unpack routine is already about 2x as fast as the native `tar.exe`.

The biggest performance gain here comes from using synchronous I/O in worker threads, since Node's async APIs ultimately are just synchronous I/O in worker threads, but by controlling the threads directly a lot of overhead can be avoided.

~~The next biggest performance gain is the use of multiple HTTP/2 connections for the registry communication. Using multiple connections separates TCP congestion control and allows the registry's load balancer to distribute them across multiple servers, while still taking advantage of HTTP/2's ability to send a large number of streams over the same connection.~~
Edit: Appears that using HTTP/1.1 doesn't have a significant performance difference vs. HTTP/2, unless the number of concurrent streams is much higher than the number of open sockets.

It's entirely possible that performance could be improved a fair bit further, since I still used Node's async I/O for symlink creation instead of handing that off to the same pool of workers. Additionally, it might be beneficial to perform the downloads directly in the worker thread that will also perform the parsing, so that integrity checking and gunzip can be streamed without blocking the main thread. This would also avoid the need to copy the tarball to a single buffer before decompression.

Parse cost is dominated by gunzip.

I can share detailed code from the prototype; there's nothing proprietary beyond that I happen to have currently hardcoded the registry domain and process of obtaining the Authorization header, but that's easily abstracted.</div>

**Comment by zkochan** [comment]
> Send the SharedArrayBuffer and map back to the orchestrator via postMessage, so that it can be load balanced again, and so that the orchestrator can get access to the information in package.json.

@dmichon-msft I did not do this one. 6 an 8 are done in a single call to the worker. Why does the main thread need info about the `package.json` early? We use the manifest from the packument for resolution anyway.

**Comment by osdiab** [comment]
I am not sure if this has any relation, but I've noticed in my own project with 1800 dependencies that on my CI machines, even if the pnpm store and node_modules is fully cached and PNPM reports that it's downloading nothing, it still takes 15-20 seconds for `pnpm install` to run, with the progress output looking like this:

```
Progress: resolved 1887, reused 16, downloaded 0, added 0
Progress: resolved 1887, reused 1138, downloaded 0, added 322
Progress: resolved 1887, reused 1882, downloaded 0, added 681
Progress: resolved 1887, reused 1882, downloaded 0, added 1111
Progress: resolved 1887, reused 1882, downloaded 0, added 1276
Progress: resolved 1887, reused 1882, downloaded 0, added 1644
Progress: resolved 1887, reused 1882, downloaded 0, added 1884
Progress: resolved 1887, reused 1882, downloaded 0, added 1886
Progress: resolved 1887, reused 1882, downloaded 0, added 1887, done
```

Not sure if there's something that I can do to make it go faster - it seems that locally it would just say `Already up to date` almost instantly in this scenario but maybe I don't understand what's actually going on.

**Comment by zkochan** [comment]
This was done
