### ISSUE TITLE
When specifying version with `*`, use latest, not earliest version

### ISSUE THREAD

**Issue by mydea** [pnpm/pnpm#6818]
We use pnpm for some test applications, and after some digging figured out why a bunch of stuff was always failing in certain scenarios: When a version is defined as `*` (any), pnpm seems to always install the _earliest_ version it can find, not the latest. This is rather unexpected, as it installed some previous major and we were constantly wondering why stuff was failing, until we checked the lockfile. 

## Expected outcome

When a version is not locked yet at all, and specified as `*`, and `pnpm install` is called, we lock the currently latest version of this package.

## Actual outcome

The earliest version (?) that is found is matched.

## Steps to reproduce

* Create new project: `mkdir pnpm-test-app && cd pnpn-test-app && pnpm init`
* Manually add `"dependencies": { "@sentry/browser": "*" }` to package.json
* Run `pnpm install`
* See that pnpm-lock shows `@sentry/browser@0.1.0`, not 7.x (which is the current version)

**Comment by KSXGitHub** [comment]
I have read a relevant discussion somewhere, but can't remember the exact location. @zkochan Can you provide a link?

By default, `resolution-mode` is set to `lowest-direct`. You can change it to `highest` to get the latest versions.

If you want to change it locally, add `resolution-mode=highest` to `.npmrc`.

If you want to make the config global, run the following command:

```sh
pnpm config --global set resolution-mode highest
```

[Reference](https://pnpm.io/npmrc#resolution-mode)

Alternatively, you can use `latest` in place of `*`.

**Comment by mydea** [comment]
Ah, I see, there is an issue here: https://github.com/pnpm/pnpm/issues/6463 as well. I will close this and add a comment there - thank you!
