### ISSUE TITLE
In pnpm workspaces, the import gets improperly loaded

### ISSUE THREAD

**Issue by nikitavoloboev** [pnpm/pnpm#6825]
### Code to reproduce the issue:

1. git clone https://github.com/learn-anything/learn-anything
2. pnpm i
3. open project in VSCode
4. See this

<img width="1512" alt="image" src="https://github.com/pnpm/pnpm/assets/6391776/4e37fc73-66f6-4851-a7ea-73e4644166ab">

This is very strange as `pnpm i` was ran and `sqlite3` does have default export.

PNPM trips up, unless I am doing something wrong.

### Expected behavior:

No import error.

### Actual behavior:

Get import error

### Additional information:

 - `node -v` prints: v18.15.0
 - Windows, macOS, or Linux?: macOS

**Comment by niktek** [comment]
Something ( a git pull, manual edit, gremlins) has removed the sqlite3 entry in your package.json dependencies and therefore pnpm is correct in removing it from your node_modules which would then cause the import above to fail.

**Comment by nikitavoloboev** [comment]
It's resolved now.
