### ISSUE TITLE
Feature request: Support ignoring of GHSAs

### ISSUE THREAD

**Issue by krichards** [pnpm/pnpm#6838]
## Background

Some audit issues are generated from Github Security Advisories (GHSAs).  We should be able to ignore these in the same way that pnpm supports ignoring of CVEs. So either 

- add a new feature ignoreVulnerabilities which can replace the existing ignoreCVEs and cover both CVEs, GHSAs and future sources
- support ignoring of GHSAs in the the ignoreCves existing configuration

### Discussed in https://github.com/orgs/pnpm/discussions/6204

<div type='discussions-op-text'>

<sup>Originally posted by **kamsar** March 10, 2023</sup>
The https://pnpm.io/package_json#pnpmauditconfigignorecves specifically targets CVEs to ignore in `pnpm audit`.

Some vulnerabilities, such as https://github.com/advisories/GHSA-36jr-mh4h-2g58, show up in `pnpm audit` but have no assigned CVE. I've tried using the GHSA but that does not seem to match.
</div>

**Comment by zkochan** [comment]
> add a new feature ignoreVulnerabilities which can replace the existing ignoreCVEs and cover both CVEs, GHSAs and future sources

sounds good to me

**Comment by cope** [comment]
nice, thanks @zkochan !
