### ISSUE TITLE
New Registry Feature: Filtered Metadata

### ISSUE THREAD

**Issue by iarna** [pnpm/pnpm#687]
Hey you all, 

I wanted to make sure you were aware of a new registry feature that allows you to fetch [filtered metadata](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md). This filtered form is much, MUCH smaller. (We're talking 20k versus 400k.)

**Comment by zkochan** [comment]
This is fantastic! Thanks @iarna! We'll be using it for sure!
