### ISSUE TITLE
pnpm: discrepancy with npm in ^x.0.0 version resolution

### ISSUE THREAD

**Issue by OEvgeny** [pnpm/pnpm#6875]
While NPM resolves to the latest version, pnpm for some reason resolves to the version specified.

### pnpm version:
8.6.3
### Code to reproduce the issue:
Go to this StackBitz environment: https://stackblitz.com/edit/daisyui-nextjs-gv6ikk?file=package.json
Verify version of the `next` package specified as `^13.0.0` in the `package.json` file, then
```
ctrl+C
rm -rf pnpm-lock.yaml node_modules
pnpm install
```
### Expected behavior:
```
Packages: +110...

dependencies:
+ next 13.4.12
...
Done in 5.2s
```
### Actual behavior:
```
Packages: +110
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 122, reused 109, downloaded 1, added 110, done

dependencies:
+ next 13.0.0 (13.4.12 is available)
+ react 18.2.0
+ react-dom 18.2.0

devDependencies:
+ autoprefixer 10.4.14
+ daisyui 3.5.0
+ postcss 8.4.27
+ tailwindcss 3.3.3

Done in 5.2s
```
### Additional information:

Can be tested here: https://stackblitz.com/edit/daisyui-nextjs-gv6ikk?file=package.json

**Comment by KSXGitHub** [comment]
This is intended default behavior. Set [`resolution-mode`](https://pnpm.io/npmrc#resolution-mode) to `highest` if you want `npm`'s behavior. Or run `pnpm update` if you don't want to change the config.
