### ISSUE TITLE
Patch not applied from root of project if its present at workspace deps but not at root

### ISSUE THREAD

**Issue by technophile-04** [pnpm/pnpm#6885]
### Description : 

I want to patch a package that is not listed in my "dependencies" of root pacakge.json but is present in one of my workspaces. Is it possible to do this using pnpm? The docs don't have any explanation for this

**IMP** : 
We have `shared-workspace-lockfile = false` in `.npmrc` so you can also see that each workspace has its own `pnpm-lock.yaml` how do I solve this issue ? 

If I add patch inside a workspace in `packages/nextjs/package.json` (nextjs is workspace) `pnpm.patchDependecies` it works but everytime I run any command I get this : 

> The field "pnpm" was found in "Users/..../pacakges/nextjs/package.json" This will not take effect. You should configure "pnpm" at the root of the workspace instead
 
### pnpm version:
8.6.10

### Code to reproduce the issue:

Checkout this PR branch and comment -> https://github.com/scaffold-eth/scaffold-eth-2/pull/444#issuecomment-1657750641 

### Expected behavior:
It should ideally work

### Actual behavior:
It gives "Patch not applied" is you try to apply patch from root of the repo

### Additional information:

 - `node -v` prints: v18.16.0
 
 - Windows, macOS, or Linux?: macOS

**Comment by KSXGitHub** [comment]
> We have `shared-workspace-lockfile = false` in `.npmrc` so you can also see that each workspace has its own `pnpm-lock.yaml` how do I solve this issue ?

What do you mean? If you set `shared-workspace-lockfile = false` then every workspace has its own lockfile is intended behavior. If you want a single lockfile at the root, it must be set to `true`.

> For deploying contract you need to use pnpm `hardhat:deploy` instead of just `pnpm deploy` because [deploy](https://pnpm.io/cli/deploy) seem reserved keyword

You can also use `pnpm run deploy`.

IIRC, a few years ago, I was against the `pnpm script-name` shorthand because of keywords and future-compatibility stuffs.

> pnpm is less friendly than yarn when you write a non existing command

I think this issue can be fixed in our end.

> The field "pnpm" was found in "Users/..../pacakges/nextjs/package.json" This will not take effect. You should configure "pnpm" at the root of the workspace instead

Can you try creating a root `package.json` with `pnpm.patchedDependencies`?

**Comment by zkochan** [comment]
Patches from non-root might work, when `shared-workspace-lockfile = false` is set. If they do work, then the warning should only be printed when `shared-workspace-lockfile` is `true`.

**Comment by await-ovo** [comment]
Currently, with `shared-workspace-lockfile=false`,  run `pnpm patch-commit` in a sub-project will throws an ERR_PNPM_PATCH_NOT_APPLIED error because it [incorrectly writes the rootProjectManifest to the sub-project](https://github.com/pnpm/pnpm/blob/main/patching/plugin-commands-patching/src/patchCommit.ts#L67).

**Comment by technophile-04** [comment]
Hey guys really thanks for the quick response, really appreciate it 🙌 !! 

> What do you mean? If you set shared-workspace-lockfile = false then every workspace has its own lockfile is intended behavior. If you want a single lockfile at the root, it must be set to true.

Sorry @KSXGitHub for the misunderstanding I actually mentioned `shared-workspace-lockfile = false` there because I wanted you guys to know we are having separate lock files and `pnpm.peerDependencies` is placed inside that workspace `package.json` which causes the warning evertime I run any `pnpm` command and thanks for other comments

---
>  standardize the behavior of pnpm configuration in package.json, for example when shared-workspace-lockfile=false we have to configure it individually in package.json under each project,

Tysm @await-ovo, but if we do that then everytime you run pnpm command from root you get this warning : 

"The field "pnpm" was found in "Users/..../pacakges/nextjs/package.json" This will not take effect. You should configure "pnpm" at the root of the workspace instead"

---

---
The way I got it working was really not developer friendly and had to do manual stuff (so don't know if I did it correctly) but sharing the steps which I followed : 

We have basically two workspaces inside : "packages/hardhat" , "packages/nextjs"

1. Clone the repo and cd into dir: 
```
git clone https://github.com/scaffold-eth/scaffold-eth-2.git  && cd scaffold-eth-2
```

2. Checkout to base pnpm branch(here the patch is not working) : 
```
git switch feat/pnpm
```

3. Remove nonworking patch : 
```
pnpm patch-remove usehooks-ts
```

4. (Creating patch inside workspace) cd in workspace which has `usehooks-ts` package : 
```
cd packages/nextjs
```

5. Create patch temp dir using `pnpm patch usehooks-ts` : 
```
pnpm patch usehooks-ts
```

6. Edit the patch file and save and commit : 
```
pnpm patch-commit temp-file-path
```

**IMP** : Here pnpm create `patch` directory inside `packages/nextjs/` but it for some reason it replaced the `packages/nextjs/package.json` ->  `pacakge.json` (root pacakge.json)


So now I had revert the changes in `pacakges/nextjs/pacakge.json` and mannually add `pnpm.peerDependencies` init


Now since `packages/nextjs/pacakge.json` has `pnpm` init it shows the warning : 

> The field "pnpm" was found in "Users/..../pacakges/nextjs/package.json" This will not take effect. You should configure "pnpm" at the root of the workspace instead


I got the patch working in this branch of the repo -> https://github.com/scaffold-eth/scaffold-eth-2/tree/fix/pnpm-pathc

**Comment by vluoto** [comment]
I suppose our case is only somewhat tangentially related to this, but at least the same warnings were mentioned.

We have a setup where `shared-workspace-lockfile=false` and the various packages in the workspace might define `pnpm` in their own `package.json` with entries such as `patchedDependencies`, `overrides`, `peerDependencyRules`, `allowedVersions`, and `packageExtensions`.

Now – thanks to [Dependabot adding native support for pnpm](https://github.blog/changelog/2023-08-02-pnpm-support-for-dependency-graph-dependabot-alerts-and-dependabot-security-updates/) – we're looking into upgrading from pnpm version 7 to 8. While at it, we see the aforementioned warnings pretty much whenever we invoke `pnpm` anywhere:

```
packages/foo                 |  WARN  The field "pnpm" was found in packages/foo/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
packages/bar                 |  WARN  The field "pnpm" was found in packages/bar/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
packages/baz                 |  WARN  The field "pnpm" was found in packages/baz/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
packages/quux                |  WARN  The field "pnpm" was found in packages/quux/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
packages/qux                 |  WARN  The field "pnpm" was found in packages/qux/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
 WARN  21 other warnings
```

Unfortunately we cannot feasibly configure these at the root of the workspace for various reasons.

From what I managed to gather, these warnings should likely not appear when `shared-workspace-lockfile=false`, or?

**Comment by technophile-04** [comment]
Tysm @KSXGitHub, @await-ovo , @zkochan 🙏 Updating the pnpm to latest version `8.6.12` nicely fixes the issues with patch and error messages 🙌

cc @await-ovo could you please check #6890 because it might be similar to #6889, but would love it if others could also chime in 🙏, #6890 is the last thing blocking us from migrating to `pnpm`, Tysm guys really appreciate the help !! 


> From what I managed to gather, these warnings should likely not appear when `shared-workspace-lockfile=false`

Yes, I you use `8.6.12` adding `shared-workspace-lockfile=false` should fix those warning 🙌
