### ISSUE TITLE
post/preinstall script does not cache result when share-workspace-lockfile=false

### ISSUE THREAD

**Issue by technophile-04** [pnpm/pnpm#6890]
### Description : 

> We have `shared-workspace-lockfile = false` in `.npmrc` 

For some reason, post/preinstall scripts do not cache result event though they are by default set to `true`  bydefault as mentioned here -> https://pnpm.io/npmrc#side-effects-cache

I have also tried adding `side-effects-cache=true` in `.npmrc`  or each workspace but it still does not solve's the issue 

### pnpm version:
8.6.10

### Code to reproduce the issue:

1. Clone the `feat/pnpm` branch from https://github.com/scaffold-eth/scaffold-eth-2 : 
```
git clone -b feat/pnpm https://github.com/scaffold-eth/scaffold-eth-2.git
```

2. Cd into `scaffold-eth-2` dir and run `pnpm install` : 
```
cd scaffold-eth-2 && pnpm install
```

3. Run pnpm install again to see if post/pre install cache result is present : 
```
pnpm install
```

output : 

![Screenshot 2023-08-01 at 5 47 45 PM](https://github.com/pnpm/pnpm/assets/80153681/c7135799-8b31-4627-b079-98ddfb923536)

Check out this PR branch -> https://github.com/scaffold-eth/scaffold-eth-2/pull/444

### Expected behavior:
It should ideally work

### Actual behavior:
It gives "Patch not applied" is you try to apply patch from root of the repo

### Additional information:

 - `node -v` prints: v18.16.0
 
 - Windows, macOS, or Linux?: macOS

**Comment by technophile-04** [comment]
cc @KSXGitHub, @await-ovo , @zkochan would really appreciate some answer 🙏, We are just blocking on this thing before migrating to pnpm. 

Really sorry for tagging directly 😅 and thanks again 🙌

**Comment by KSXGitHub** [comment]
I reproduced the bug in GitHub Codespaces. I think I will take care of this once I'm done with my existing PR.

**Comment by technophile-04** [comment]
Tysm Khai, really appreciate it  🙌 🙏 !!

**Comment by KSXGitHub** [comment]
I have been failing to produce a minimal reproducible repo. Not sure what's so special about the scaffold repo.

**Comment by technophile-04** [comment]
Here is the very minimal reproducible repo : https://github.com/technophile-04/pnpm-prePostInstall-mrr-6890

It has two `workspaces`:  `packages/a-package`, `packages/b-package`. 

I have just installed one-one dependencies in both : 

`a-package` contains `ssh2` as a dependency 

`b-package` contains `vercel` as a dependency

And have `husky` installed at the root of the project

Also [.npmrc](https://github.com/technophile-04/pnpm-prePostInstall-mrr-6890/blob/01809a4825f0e38912b847067628bc7c8199a966/.npmrc#L1) has `share-workspace-lockfile=false`

--- 

### Steps to reproduce : 

1. Clone the repo : 
```shell
git clone https://github.com/technophile-04/pnpm-prePostInstall-mrr-6890.git &&  cd pnpm-prePostInstall-mrr-6890
```

2. Install dependency : 
```shell
pnpm install
```

3. Again try running install dependency : 
```
pnpm install 
```

![Screenshot 2023-08-25 at 8 39 21 PM](https://github.com/pnpm/pnpm/assets/80153681/cd5eeee8-b9ac-4bef-bdb1-8f46aec9960d)

☝️ As we can it again re-ran `postinstall script` & `install scripts` :( 

Hopefully, this helps @KSXGitHub 🙌, Tysm for the help !!
