### ISSUE TITLE
Unexpected interaction between --lockfile-only with --frozen-lockfile modifies the lockfile.

### ISSUE THREAD

**Issue by Zemnmez** [pnpm/pnpm#6913]
### pnpm version:
9.8.0

### Code to reproduce the issue:
```
pnpm i --frozen-lockfile --lockfile-only
```

### Expected behavior:
PNPM checks the lockfile is in sync with package.json, but does not update it or node_modules.

### Actual behavior:
PNPM updates the lockfile.

### Additional information:

I have had issues in my repo where automation can change package.json but not pnpm-lock.yaml. It seemed the simplest way to test for this is to have PNPM check. `pnpm i –frozen-lockfile` does as I want but also does the work to populate node_modules, which I do not want. It seemed sensible that specifying `--lockfile-only` would remedy this, but in fact it then ignores `--frozen-lockfile`.

**Comment by zkochan** [comment]
I was fixing [this issue](https://github.com/pnpm/pnpm/issues/4951), when this stopped working. I believe [my PR](https://github.com/pnpm/pnpm/pull/6915) should not bring back the `--lockfile-only` issue on CI as we have this code now: 

https://github.com/pnpm/pnpm/blob/aaefb07d0b46ea801c87511e06990fcdf3d2a4de/pkg-manager/plugin-commands-installation/src/install.ts#L322-L324
