### ISSUE TITLE
Your application tried to access esbuild

### ISSUE THREAD

**Issue by Tsyklop** [pnpm/pnpm#6920]
### Code to reproduce the issue: 
https://github.com/Tsyklop/emulator-ui

Clone and run: `pnpm install` and `pnpm run dev`

### Expected behavior: 

Dev server starts

### Actual behavior: 

Error:
![Screenshot_1](https://github.com/pnpm/pnpm/assets/6783568/c27650da-0b8d-4ea1-956a-992640b63ea5)

### Additional information: 

 - `node -v` prints: v18.16.1
 - Windows, macOS, or Linux?: Windows 10

**Comment by KSXGitHub** [comment]
If I remove all the `.pnp.*` files then run `pnpm run dev`, this is the result:

![screenshot](https://github.com/pnpm/pnpm/assets/11488886/13be6887-80eb-46d9-99a9-cc0a93f02e30)
