### ISSUE TITLE
Nexus authentication error -> No authorization header was set for the request 

### ISSUE THREAD

**Issue by ananasij** [pnpm/pnpm#6924]
I'm switching from npm to pnpm and I'm getting authentication errors at Nexus that we use as a registry. 

Here's the .npmrc (with some sensitive data replaced) that works fine for npm locally:

```
@MY_CONTEXT:registry=https://nexus.aws.MY_CONTEXT.com/content/repositories/zd-npm/
//nexus.aws.MY_CONTEXT.com/content/repositories/zd-npm/:_auth=<authToken>
registry=https://nexus.aws.MY_CONTEXT.com/content/repositories/npmjs-proxy/
//nexus.aws.MY_CONTEXT.com/content/repositories/npmjs-proxy/:_auth=<authToken>
email=email@MY_CONTEXT.com
always-auth=true
audit=false
save-exact=true

```
### Expected behavior:
When running locally:
`pnpm import` creates a lock file
`pnpm install` installs dependencies

### Actual behavior:
both commands throw the following  error:
```
 ERR_PNPM_FETCH_401  GET https://nexus.aws.MY_CONTEXT.com/repository/npmjs-proxy/@babel/highlight/-/highlight-7.22.10.tgz: Unauthorized - 401

No authorization header was set for the request.

These authorization settings were found:
@MY_CONTEXT:registry=https://nexus.aws.MY_CONTEXT.com/content/repositories/zd-npm/
//nexus.aws.MY_CONTEXT.com/content/repositories/zd-npm/:_auth=c2Vu[hidden]
//nexus.aws.MY_CONTEXT.com/content/repositories/npmjs-proxy/:_auth=c2Vu[hidden]
```

I see that unscoped registry line (the one pointing to npmjs-proxy) is not present in the output, not sure why. 
If I run `pnpm config list` it's getting the full content of `.npmrc` though.

### Additional information:

 - `node -v` prints: v20.3.1
 - Windows, macOS, or Linux?: MacOS 13.4.1

**Comment by zkochan** [comment]
You should add this to your `.npmrc` too:

```
//nexus.aws.MY_CONTEXT.com/repository/npmjs-proxy/:_auth=<authToken>
```

`always-auth=true` is doing nothing, it was a security vulnerability that npm have deprecated and we have deprecated it too.

**Comment by ananasij** [comment]
Thanks, it helped! I also had to add such a url for the scoped registry and it seems to work now.

Do you know why pnpm requires this addition while npm doesn't?

**Comment by zkochan** [comment]
npm should require it too, unless you use some old version.

**Comment by ananasij** [comment]
Hm.. we use npm v9 and it worked just fine with the config I've pasted 🤔 
Anyway, now it works for pnpm as well. Thanks a lot for your help.
