### ISSUE TITLE
pnpm i hangs on Ubuntu 16.04 + v6.10.1 when there is a shrinkwrap file present

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#693]
pnpm version: 0.63.0

When I kill it with `killall -8 pnpm` this error shows:

```
bash: line 1: 20187 Floating point exception(core dumped) NODE_ENV=development pnpm install --silent --force

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

If I let it generate its own shrinkwrap it works fine. The shrinkwrap generated on my macOS seems to break it.

### Additional information:

 - `node -v` prints: v6.10.1
 - Windows, OS X, or Linux?: Ubuntu 16.04

**Comment by vjpr** [comment]
0.60.0 seems to work...

**Comment by zkochan** [comment]
maybe this is the reason

https://github.com/pnpm/pnpm/commit/e43aa6e8ae69aeb0c5261f94cf5d5279536a3887

but weird, because we have tests with circular deps and they pass

**Comment by zkochan** [comment]
Does it work without the force parameter?

**Comment by zkochan** [comment]
This was an issue in a third-party package. Is fixed now

https://github.com/rexxars/registry-auth-token/pull/11
