### ISSUE TITLE
Hoisting exclusion does not work

### ISSUE THREAD

**Issue by oliveryasuna** [pnpm/pnpm#6933]
### Code to reproduce the issue:

```json
// package.json
{
  ...
  "devDependencies": {
    "@web/test-runner-playwright": "0.10.1"
  }
}
```

```
// .npmrc
hoist-pattern[] = !playwright-core
```

### Expected behavior:

`playwright-core` should be under `node_modules`.

### Actual behavior:

`playwright-core` is under `node_modules/.pnpm`.

### Additional information:

Perhaps I am missing something obvious? This is my first time dealing with hoisting, believe it or not.

**Comment by KSXGitHub** [comment]
Do this instead:

```ini
public-hoist-pattern[] = playwright-core
```

**Comment by oliveryasuna** [comment]
@KSXGitHub Thank you.
