### ISSUE TITLE
changesets/cli is broken in 8.6.12

### ISSUE THREAD

**Issue by OverLord561** [pnpm/pnpm#6939]
### pnpm version:
8.6.12
### Code to reproduce the issue:
pnpm add @changesets/cli@2.26.2 && pnpm changeset
### Expected behavior:
Works like in 8.6.11
Prompt that allows to add changed packages to the changeset file.
### Actual behavior:
```
C:\src\fe-resources\node_modules\.pnpm\meow@6.1.1\node_modules\meow\index.js:7
const trimNewlines = require('trim-newlines');
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\src\fe-resources\node_modules\.pnpm\trim-newlines@5.0.0\node_modules\trim-newlines\index.js from C:\src\fe-resources\node_modules\.pnpm\meow@6.1.1\node_modules\meow\index.js not supported.
Instead change the require of C:\src\fe-resources\node_modules\.pnpm\trim-newlines@5.0.0\node_modules\trim-newlines\index.js in C:\src\fe-resources\node_modules\.pnpm\meow@6.1.1\node_modules\meow\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\src\fe-resources\node_modules\.pnpm\meow@6.1.1\node_modules\meow\index.js:7:22)
    at Object.<anonymous> (C:\src\fe-resources\node_modules\.pnpm\@changesets+cli@2.26.2\node_modules\@changesets\cli\dist\cli.cjs.dev.js:3:12)
    at Object.<anonymous> (C:\src\fe-resources\node_modules\.pnpm\@changesets+cli@2.26.2\node_modules\@changesets\cli\dist\cli.cjs.js:6:20)
    at Object.<anonymous> (C:\src\fe-resources\node_modules\.pnpm\@changesets+cli@2.26.2\node_modules\@changesets\cli\bin.js:4:1) {
  code: 'ERR_REQUIRE_ESM'
}
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "changeset" not found
```
### Additional information:

 - `node -v` prints: 16.20.0
 - Windows, macOS, or Linux?: Windows 11 & ubuntu 20.04 on CI

**Comment by thynson** [comment]
I did some investigation and it looks like the dependencies aren't installed correctly; `meow@6.0.1` depends on `trim-newlines@^3.0.0` but `@trim-newlines@5.0.0` is installed.
Delete the `pnpm-lock.yaml` and `node_modules/` and try again to see if it works. 
If the issue still persist, can you post the contents of `package.json` and `pnpm-lock.yaml` here?

**Comment by KSXGitHub** [comment]
> pnpm add @changesets/cli@2.26.2 && pnpm changeset

I did this exact thing and changeset was executed as expected.

I would appreciate if you could provide more information.

**Comment by weyert** [comment]
Yes, I am using the same versions of `@changesets/cli` and `pnpm` in the root. In my root package manifest file I have a script defined `"changeset": "changeset"` and when I run `pnpm run changeset` the tool correctly executes for me

**Comment by OverLord561** [comment]
Let me try to delete the pnpm-lock.yaml and node_modules. After that I will share the content of package.json & lock files.

**Comment by OverLord561** [comment]
Looks like I missed overrides in my package.json file. Works right now. 
Thank you very much for the fast response!
Closing ticket.
