### ISSUE TITLE
pnpm install --global is broken

### ISSUE THREAD

**Issue by danielbayley** [pnpm/pnpm#695]
### pnpm version:
0.63.0

### Code to reproduce the issue:
~~~ sh
# Note that I happen to have installed node with homebrew…
> brew install node
> npm install --global pnpm
# Using app-path-cli as an example:
> pnpm install --global app-path-cli
> which app-path-cli
# nothing
> npm bin -g
/usr/local/bin # After some digging, pnpm stuff is actually in /usr/local/Cellar/node/7.8.0!
~~~

### Expected behavior:
The story for _pnpm_ global installs is _a lot_ different to regular npm, creating quite a lot of confusion and unexpected behaviour.

I see that pnpm uses the _global-bin-path_ package, but I don't think this is very reliable; The [code], unless you're on Windows, is literally just `path.dirname(process.execPath)`, which I guess results in `/usr/local/Cellar/node/7.8.0`…
I'm note sure if putting each package's _actual_ `bin` _files_ (not links to them) in _there_ is correct, or whether they should be in their respective `package.json.bin` folders like regular npm. But regardless, they should _then_ be symlinked into `npm bin -g` (`/usr/local/bin` usaully) just like npm does, so that global commands are immediately available on the `PATH` as you would expect.
A temp fix is to actaully add `$(brew --prefix node)/bin` (which is the symlink `/usr/local/opt/node`, to the realpath `/usr/local/Cellar/node/7.8.0`) to the `PATH`, but really this is hacky and far from ideal.

Also `pnpm uninstall`/`unlink`/`rm --global` doesn't remove globally installed things… stuff just remains in `/usr/local/Cellar/node/7.8.0`! :/

pnpm seems to pay no attention to `$NPM_CONFIG_USERCONFIG` like npm does… a workaround is to pass `--config $NPM_CONFIG_USERCONFIG` to pnpm but again this obviously isn't ideal, and the flag doesn't even match npm's [`--userconfig`] (see #40)

Once you do get pnpm to read an `npmrc`, the `${ENVIRONMENT_VARIABLES}` within arent expanded as you would expect (for example `local-registry`/`store-path`/`global-path` etc…) meaning _more_ hard-coded paths! :/ Although at least tildes `~` do work.

@zkochan I'm happy to help out with PRs to get global pnpm installs working properly, but first need to agree on an approach…

[code]: https://github.com/QingWei-Li/global-bin-path/blob/master/index.js#L21

---
 - `node -v` prints: v7.8.0
 - Windows, OS X, or Linux?: macOS Sierra 10.12.4

**Comment by zkochan** [comment]
> I see that pnpm uses the global-bin-path package, but I don't think this is very reliable; The code, unless you're on Windows, is literally just path.dirname(process.execPath), which I guess results in /usr/local/Cellar/node/7.8.0…
I'm note sure if putting each package's actual bin files (not links to them) in there is correct, or whether they should be in their respective package.json.bin folders like regular npm. But regardless, they should then be symlinked into npm bin -g (/usr/local/bin usaully) just like npm does, so that global commands are immediately available on the PATH as you would expect.

The description of [global-bin-path](https://github.com/QingWei-Li/global-bin-path) says that: `"Return absolute path for global module executables, likes npm bin -g"`. So I think we can suggest a PR there if they don't return what `npm bin -g` returns on some systems.

> Also pnpm uninstall/unlink/rm --global doesn't remove globally installed things… stuff just remains in /usr/local/Cellar/node/7.8.0! :/

If so then we should fix it for sure.

> pnpm seems to pay no attention to $NPM_CONFIG_USERCONFIG like npm does… a workaround is to pass --config $NPM_CONFIG_USERCONFIG to pnpm but again this obviously isn't ideal, and the flag doesn't even match npm's [--userconfig] (see #40)

Lets have separate issues for these. I agree that we have to have the same API as npm

> Once you do get pnpm to read an npmrc, the ${ENVIRONMENT_VARIABLES} within arent expanded as you would expect (for example local-registry/store-path/global-path etc…) meaning more hard-coded paths! :/ Although at least tildes ~ do work

What do you mean? The default configs for local-registry, etc. are bad and you cannot override them?

**Comment by danielbayley** [comment]
@zkochan Yeah ok, as you can see I filed an issue there.

So `pnpm --global uninstall`/`unlink`/`rm` should additionally remove the symlink from wherever `npm bin -g` actually is that _should_ have been put there on `--global install` right?

Ok cool, so #40 is the separate issue for `--userconfig` and `$NPM_CONFIG_USERCONFIG`… and so I think keep _this_ one for the above problem…

> I agree that we have to have the same API as npm

Yeah, _pnpm_ should just be a drop-in replacement for npm as far as configuration is concerned!

> What do you mean? The default configs for local-registry, etc. are bad and you cannot override them?

Iv'e created a separate issue (#) for this, and elaborated on what the problem is there.

**Comment by zkochan** [comment]
> So pnpm --global uninstall/unlink/rm should additionally remove the symlink from wherever npm bin -g actually is that should have been put there on --global install right?

Correct

**Comment by zkochan** [comment]
All of these should now work in [v0.65.1](https://github.com/pnpm/pnpm/releases/tag/v0.65.1)

**Comment by foisonocean** [comment]
@danielbayley @zkochan 
Hi guys, I'm using Node v10.9.0 and pnpm v2.13.5 on mac OS X 10.11, and I try to install create-react-app by `pnpm install -g create-react-app`, but then when I run `which create-react-app` I still got nothing.
Any suggestions for me?

**Comment by waylandc** [comment]
Also can confirm what @foisonocean is reporting, pnpm 2.15.0 with node 10.9.0 still has this problem of installing global packages.

` waylandchan@bctmac  ~/sandbox/orderbook  pnpm list -g --depth=0                            
/usr/local/Cellar/node/10.9.0/pnpm-global/1
└── pnpm@2.15.0

 waylandchan@bctmac ~/sandbox/orderbook  which tsc                                         
tsc not found
 waylandchan@bctmac ~/sandbox/orderbook  pnpm install -g typescript                      
Packages: +1
+
Resolving: total 1, reused 1, downloaded 0, done

/usr/local/Cellar/node/10.9.0/pnpm-global/1:
+ typescript 3.0.3

 waylandchan@bctmac  ~/sandbox/orderbook  which tsc                                       
tsc not found
 waylandchan@bctmac  ~/sandbox/orderbook  pnpm --version                                  
2.15.0
 waylandchan@bctmac  ~/sandbox/orderbook  node --version                                    
v10.9.0
 waylandchan@bctmac ~/sandbox/orderbook  npm bin -g                                        
/usr/local/bin
 waylandchan@bctmac ~/sandbox/orderbook  pnpm bin -g                                       
/usr/local/bin
 waylandchan@bctmac ~/sandbox/orderbook  ls -al /usr/local/Cellar/node/10.9.0/bin/tsc      
-rwxr-xr-x  1 waylandchan  staff  2857 Sep  4 18:55 /usr/local/Cellar/node/10.9.0/bin/tsc
 waylandchan@bctmac ~/sandbox/orderbook  date                                             
Tue Sep  4 18:56:06 HKT 2018
 `

**Comment by zkochan** [comment]
Please track issue #1210 if you have problems with globally installed packages

**Comment by zkochan** [comment]
or no, that on is different. Lets create a new issue for this

**Comment by waylandc** [comment]
@zkochan Do you want me to create the issue?

**Comment by waylandc** [comment]
Created new issue [1360](https://github.com/pnpm/pnpm/issues/1360)
