### ISSUE TITLE
Support detect node version and change to the specified node version

### ISSUE THREAD

**Issue by SnowingFox** [pnpm/pnpm#6958]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

In this issue https://github.com/ant-design/antd-token-previewer, I encountered a problem and tried too many times, but still failed. Finally, the author told me that i should start it with node16, but i'm in node18.

This is really ridiculous, and i think there is a way to solve this problem?

Nodejs provide a configuration in package.json

```json
{
  "engines": {
    "node": ">=16.0.0 <17"
  }
}
```

But it just a declaration, it can't detect node version and most people will ignore this declaration when they execute install command, finally it will throw an error

so i think we can avoid this problem by using install scripts

### Describe the solution you'd like

```json
{
  "engines": {
    "node": ">=16.0.0 <17"
  }
}
```

when user execute
```bash
pnpm i 
```
pnpm will detect whether package.json configure this declaration or not, and change to the latest compatible version which user installed

we can use https://npmjs.com/n or nvm to change node version

### Describe the drawbacks of your solution

User may install too many nodejs version in their disk, it may waste disk space, and change the node version globally may cause some issues

or may we can just give an warning for users

### Describe alternatives you've considered

change node version manually before install

**Comment by KSXGitHub** [comment]
[`engine-strict`](https://pnpm.io/npmrc#engine-strict) in `.npmrc` would make pnpm errors on incompatible Node.js version based on `engines.node` of `package.json`.

[`use-node-version`](https://pnpm.io/npmrc#use-node-version) in `.npmrc` would tell pnpm to download and use to desired node versions.

Are these 2 features sufficient for your use case?

**Comment by SnowingFox** [comment]
thanks
