### ISSUE TITLE
BUG: In the windows system, the ^ syntax of the pnpm i command for package.json is invalid

### ISSUE THREAD

**Issue by LengJunT** [pnpm/pnpm#6959]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.6.12

### Reproduction steps

package.json

```
 "devDependencies": {
    "@volcengine/vertc-electron-sdk": "^3.50.4",
}
```

next

```pnpm i```

pnpm-lock.yaml output
```
/@volcengine/vertc-electron-sdk@3.50.4:
```

### Describe the Bug

"@volcengine/vertc-electron-sdk": "^3.50.4", this way of writing, the downloaded dependency version is wrong, it should be 3.52.4 instead of 3.50.4

### Expected Behavior

Successfully downloaded @volcengine/vertc-electron-sdk version 3.52.4

### Which Node.js version are you using?

16.20.2

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by thynson** [comment]
It's not a bug, since both `3.50.4` and `3.52.4` satisify `^3.50.4`.
You can set `resolution-mode` to `highest` to obtain desired behavior, see https://pnpm.io/npmrc#resolution-mode.
