### ISSUE TITLE
Treat resolution-mode as highest by default if the version string does not contain a specific version as delimiter.

### ISSUE THREAD

**Issue by vilic** [pnpm/pnpm#6960]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

There are scenarios that I tend to use vague version strings for dependencies:

1. In a template project, when I want to specify the target framework/SDK version:
  - react: 18
  - some-sdk: 0.4
  - @types/node: 18
2. To manually avoid breaking changes brought by the latest major versions of packages:
  - chalk: 4
  - node-fetch: 2

As a newcomer to pnpm, it caught me off guard. As in those examples, pnpm directly uses the lowest matching version which is usually highly unstable.

### Describe the solution you'd like

As I am aware of the idea behind `resolution-mode` defaulting to `lowest`, I think it is nice for version strings that contain specific versions (like `^18.1.2`) but not ideal for version strings that are vaguely written on purpose.

A simple way to avoid this is to use `highest` resolution mode for version strings without specific versions if `resolution-mode` is not explicitly configured.

### Describe the drawbacks of your solution

It would of course change the current behavior and then bring some risks for people not aware of this proposed change. But I think the risk is overall manageable, as version string without a specific version is usually written on purpose.

Actually, I doubt an experienced pnpm user with `resolution-mode` defaults to `lowest` would do this because it's kind of meaningless. And on the other hand, users new to pnpm could probably do this without noticing the difference at first (which could actually be worse).

### Describe alternatives you've considered

Other than applying this automatic `highest` resolution only if `resolution-mode` is not explicitly specified, I think it is also safe to make `highest` resolution the fixed resolution mode for version strings without specific version.

### Related

https://github.com/pnpm/pnpm/issues/6818

**Comment by gluxon** [comment]
Hi @vilic, does this feature request still apply after the recent `resolution-mode` change in pnpm 8.7.0? https://github.com/pnpm/pnpm/pull/6987

**Comment by vilic** [comment]
I guess it's no longer an issue, thanks. @gluxon
