### ISSUE TITLE
pnpm publishing with --filter & CPU outage

### ISSUE THREAD

**Issue by OverLord561** [pnpm/pnpm#6968]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/OverLord561/pnpm_issue/blob/main/publish-steps

### Reproduction steps

1. Recursive publishing with filtering to exclude some components `pnpm publish --embed-readme -r --no-git-checks --tag my-tag --filter=!component_name ... 50 other filters`;
2. Publishing with filtering to include specific components `pnpm publish --embed-readme --no-git-checks --tag my-tag --filter=component_name ... 50 other filters`;
3. Publish with 8 filters when one name is substring of another name where component_name is subname  `pnpm publish --embed-readme --no-git-checks --tag my-tag --filter=component_name--filter component_name_like_patch`;

In general, problems are starting when we have 8 filter values. The CPU usage is 100% and publishing passes somehow. 
But once I have example `#3` publishing fails. 

I see 2 regularities with filters:
1. Resources are not released after every publish when filters are used(during Recursive without filters we see constant resources drops component by component)
2. Subnames causes extra issues when filters are applied

### Describe the Bug

pnpm publishing with filters consumes 100% of CPU and crashes
Processor: vCPUs=4, RAM=16G

Recursive publishing without filtering works but it takes longer due to the fact that it publishes everything that was bumped by @changesets/cli.

### Expected Behavior

Works like in 8.6.0 without CPU outages and resources releases component by component.

### Which Node.js version are you using?

16.20.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

ubuntu 20.04 on CI

**Comment by OverLord561** [comment]
I would like to add that 8.6.1 has the same problem

**Comment by OverLord561** [comment]
One more diff in concurrency:

1. 8.6.0 is doing publish more like package by package but still fast according to the logs
2. 8.6.1 logs a few components in a row(up to 5)

Here is  CPU usage for 8.6.0
![image](https://github.com/pnpm/pnpm/assets/14871855/2491f51a-5ec4-4d75-9e50-0c6d02176bbf)

**Comment by OverLord561** [comment]
Tried CPU limitation for Docker Container like when vCPUs=4 in Azure
--cpus="2"
--cpus="3.5"
but no luck for 8.6.1

**Comment by OverLord561** [comment]
here are main release changes
![image](https://github.com/pnpm/pnpm/assets/14871855/95cc58b0-8216-4fe0-ac45-9f4b10f663ba)
https://github.com/pnpm/pnpm/compare/v8.6.0...v8.6.1

**Comment by OverLord561** [comment]
I would like to add that with Promise.all logs are not straightforward. Different logs from different component are merged into one.

**Comment by zkochan** [comment]
It was caused by this PR: https://github.com/pnpm/pnpm/pull/6617

Specifically, by this change:

<img width="1239" alt="image" src="https://github.com/pnpm/pnpm/assets/1927579/db0f3cb9-3b2e-4d38-9a0e-a5ff96b7fb22">

We can revert it.

**Comment by OverLord561** [comment]
We will appreciate that. Thank you very much!

**Comment by OverLord561** [comment]
The issue is resolved!

Thank you a lot!

To make publish faster we are launching 2 parallel publishes and splitting array of components(packages). This gives benefits and shows up to 25% boost in performance.

**Comment by OverLord561** [comment]
Hi!

Is there a chance that parallel publish will be available under some cli option?
