### ISSUE TITLE
pnpm doesn't respect `use-node-version` setting for `pnpm install` when using pnpm workspace

### ISSUE THREAD

**Issue by antitoxic** [pnpm/pnpm#6981]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.6.12

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/antitoxic/pnpm-workspace-use-node-version-bug

### Reproduction steps

1. Run:
   ```shell
   pnpm env use --global 18.15.0
   pnpm env use --global 16.19.1
   ```
2. Now your current `node` version globally should be `16.19.1` but you should have `18.15.0` installed as well.
3. Check out https://github.com/antitoxic/pnpm-workspace-use-node-version-bug and just run `pnpm install`

### Describe the Bug

As the title says, it seems like after using pnpm workspace, `pnpm install` no longer respects the`use-node-version` setting.

The same `.npmrc` config works fine when NOT using pnpm workspace.

### Expected Behavior

I expect running `pnpm install` within a pnpm workspace to respect the `use-node-version` and automatically use the already available node version specified by `use-node-version` 

### Which Node.js version are you using?

18.15.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
Since you didn't describe the "Actual behavior", I have to ask you: Is this the same behavior you observed?

![screenshot](https://github.com/pnpm/pnpm/assets/11488886/c8990931-9cd2-46c8-9d3d-79536592dbd0)

**Comment by antitoxic** [comment]
Hi @KSXGitHub , yes this is the error I'm getting.
