### ISSUE TITLE
v8.7.0 is completely broken

### ISSUE THREAD

**Issue by MrFoxPro** [pnpm/pnpm#6988]
### Last pnpm version that worked

8.6.12

### pnpm version

8.7.0

### Code to reproduce the issue

`pnpm i`

### Expected behavior

I gues it should install packages as it's package manager

### Actual behavior

pnpm doesn't create node_modules directories after `pnpm i` and doesn't log any errors.

`pnpm store status`:
```                                                                          
ENOENT  ENOENT: no such file or directory, open '/home/foxpro/.local/share/pnpm/store/v3/files/37/3e2b25c721183b44355d1e30a50d6ba2f5db3cf6cc10d7ba18ff563875f331aa078e018bb3013125e382e9c98234610a628e8e73ee669e0c6fa38aaad3072d-index.json'
```

After removing lockfile, `pnpm i` shows an error:
```
Packages: +719
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 MODULE_NOT_FOUND  Cannot find module '/usr/lib/node_modules/pnpm/dist/worker.js'

Error: Cannot find module '/usr/lib/node_modules/pnpm/dist/worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:185:26)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Progress: resolved 756, reused 719, downloaded 0, added 0
```

Switching back to `8.6.12` resolves this issues. 

### Node.js version

20.5.1

### Operating System

Linux

**Comment by weyert** [comment]
It’s odd that it can’t find `worker.js` that’s the new Worker that’s handling the fetching/unpacking of the packages.

**Comment by MrFoxPro** [comment]
probably it's arch package issue

**Comment by oritwoen** [comment]
> probably it's arch package issue

That's true. Already reported here: https://bugs.archlinux.org/task/79488?project=1&string=pnpm
