### ISSUE TITLE
Interactive update, show workspace name

### ISSUE THREAD

**Issue by linqcan** [pnpm/pnpm#7000]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a user I would like to be able to see what workspace a package "comes from" when I run update in the root of a monorepo (with several workspaces). This would help me understand why the dependency exist. 

Command:
pnpm update -irL

### Describe the solution you'd like

For each package, annotate the line with the workspace name(s).

Make the feature optional as it can become quite verbose. 

### Describe the drawbacks of your solution

Lots of information in output. Hence, make it optional to display. 

### Describe alternatives you've considered

Today I manually explore my workspaces to find where the package belong.

**Comment by KSXGitHub** [comment]
Is `pnpm why -r $pkgname` sufficient for your use case?

**Comment by linqcan** [comment]
> Is `pnpm why -r $pkgname` sufficient for your use case?

That's the workaround I use today. But that requires a terminal in parallel or breaking out of the interactive mode. What I am looking for is getting that information without having to switch context.

**Comment by KSXGitHub** [comment]
Do you want this output?

![screenshot](https://user-images.githubusercontent.com/11488886/264348041-224e91cc-132f-4744-a3b2-3ff89691a30c.png)

**Comment by zkochan** [comment]
Should've been solved by https://github.com/pnpm/pnpm/pull/6978

**Comment by linqcan** [comment]
Wow, that was fast. I'm looking forward to try 8.7.1.
Thank you everyone!
