### ISSUE TITLE
PNPM v6 install fails with ssl error

### ISSUE THREAD

**Issue by HuXiKa** [pnpm/pnpm#7004]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

v6

### Reproduction steps

Hi,

we are trying to install pnpm v6 on our build agents via 'curl -f https://get.pnpm.io/v6.js' command. This command fails with the following error:
`curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.`

The same command has been working yesterday, we started to experience this issue around Aug 30, 2023 at 8:45 AM GMT+2
We can see that the site has a fairly new ssl certificate, is it possible that something is wrong with the cert? We have a workaround solutions, which is the '--ssl-no-revoke' flag for curl, but ideally we would like to not use it for extended amount of time.

Thanks,

David

### Describe the Bug

$ curl -f https://get.pnpm.io/v6.js
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### Expected Behavior

The curl command should not fail.

### Which Node.js version are you using?

18.16.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by luqas** [comment]
Since yesterday we experience very similar issue. 
In the browser URL works as expected, but in the command line it returns some binary file instead. Looks like some sort of cache issue
```
curl -f https://get.pnpm.io/v6.js                                                                                                                                                                                                                         
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

Works correctly every time 
`curl -f "https://get.pnpm.io/v6.js?time=$(date '+%Y%m%d%H%M%S')"`

**Comment by HuXiKa** [comment]
It seems like our original fix was in the end was only working locally but not on our agents. @luqas solutions seems to be working however, thank you for that! You are probably right, this might be some caching issue, we didn't thought about that / didn't thought of passing in the time parameter, nice trick!

**Comment by zkochan** [comment]
Please use one of the other installation methods from https://pnpm.io/installation. This one is not supported anymore.
