### ISSUE TITLE
install.sh load balancing is currently corrupted

### ISSUE THREAD

**Issue by bosticka** [pnpm/pnpm#7017]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

wget -qO- https://get.pnpm.io/install.sh

### Reproduction steps

Just run from the command line:

wget -qO- https://get.pnpm.io/install.sh

Some of the time it returns binary nonsense and some of the time it returns the actual text install script.

Run wget over and over and you will see the issue.

This of course breaks builds that rely on pnpm.

### Describe the Bug

wget -qO- https://get.pnpm.io/install.sh is returning binary some of the time.

Corrupted nodes in the load balancing pool or CDN etc is my guess.

### Expected Behavior

Should return text install.sh each time.

### Which Node.js version are you using?

18

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

debian

**Comment by desweemerl** [comment]
I had the same issue, the content is compressed. The following command fixed the installation:

`curl -s --compressed "https://get.pnpm.io/install.sh" | ENV="$HOME/.shrc" SHELL="$(which sh)" sh - && source /root/.shrc`

**Comment by gablabelle** [comment]
Same thing for us

![Screenshot 2023-08-31 at 10 19 43 AM](https://github.com/pnpm/pnpm/assets/1565793/9a97b3e3-d4a3-411c-8c99-901e58f10b52)

**Comment by gablabelle** [comment]
> I had the same issue, the content is compressed. The following command fixed the installation:
> 
> `curl -s --compressed "https://get.pnpm.io/install.sh" | ENV="$HOME/.shrc" SHELL="$(which sh)" sh - && source /root/.shrc`

Thank you sir! The `--compressed` flag fixes it. 👍

**Comment by hrmcdonald** [comment]
Was this breaking change intentional - will this new way of calling the command be necessary going forward? This has disrupted our use of PNPM in existing CI pipelines in some cases.

**Comment by zkochan** [comment]
Is it still an issue? Looks like resetting the cache fixes the issue.

We have migrated to vercel, maybe that's the reason

**Comment by zkochan** [comment]
I have moved back `get.pnpm.io` to netlify. Seems like it works now.

**Comment by hrmcdonald** [comment]
> Is it still an issue? Looks like resetting the cache fixes the issue.
> 
> We have migrated to vercel, maybe that's the reason

I didn't have a chance to try clearing cache. The `--compressed` flag mentioned above did fix the issues when I tested that though.

**Comment by hyunbinseo** [comment]
For those suffering from cache, try adding a random query.

```bash
% curl -fsSL "https://get.pnpm.io/install.sh?1" | sh -

# ==> Downloading pnpm binaries 8.7.1
#  WARN  using --force I sure hope you know what you are doing
# No changes to the environment were made. Everything is already up to date.
```

Checked on macOS 13.5.1(22G90).

**Comment by leerob** [comment]
Following up here, worked with @zkochan to dig in on the issue. It wasn't from Vercel, but from Cloudflare. Should be resolved now. Thanks for your help, @zkochan!

**Comment by klimburg** [comment]
Looks like this is happening again...

```
$ curl -fsSL https://get.pnpm.io/install.sh | bash
bash: line 1: $'\301p_\366\366\342\354\177\177\276\206%\324I\257\213K\211\242\036QPջ\264': command not found
bash: line 4: syntax error near unexpected token `)'
bash: line 4: `��*��x�=.�8��)�]�=����   ���*���|t��8(�]Q��z4��s}���D+�]QF_/�h,v��&S"���D+[�T�G��j���r�0����+�'��3-�<��F�^U�M��֨N�T��l�a֨��D^�:��xw��l�2|�I�7�\�t_l��ߣ,�h<�L�k�]m���������^�Ŝa��6q�~�?ɘ�<�1��̑a����i��0���C��d�1�w51��=8_Fm���weUT�뭸ғ�_�"�bh���{qs������[\�y.^^��Ƭ������I%�hMB����D��
          ��=^
              }O|�#C�x���R&�l"��~��AÉ��]��!Nq�i��0`����q~�$V\�m5n�1��ɮ-o\�<��V1i���
                                                                                   uܤ�۸p�P����)�I��R�'-W��-��VᕊZ�.e�jݶ}?+fS��v�l:Y��Φ����n��Xb�c�S���&|d��c�D��. Ŏ@�!�s�0��%���)���6a65��7HuJO�Z��k3���\���^�qڿ����s���a�a�7�ߡ�������\��Hf��b�_l��)�U{OΦ�'b�!����P��aH!Y��6'
```

**Comment by zkochan** [comment]
Does it work with the `--compressed` option?

**Comment by klimburg** [comment]
yes `--compressed` does seem to fix, is this going to be a permanent change? I'm updating tooling for setting up our dev environment.

**Comment by zkochan** [comment]
I have turned off the proxy setting for "get.pnpm.io" and now it is dns only. So maybe now it will work? For me it works right now.

**Comment by klimburg** [comment]
Yea seems like its working again, but I am pretty sure it worked at least once intermittently when I was trying to figure out why I was getting binary data. So perhaps there were some nodes serving it properly and others not.

**Comment by zkochan** [comment]
According to Vercel it is a Cloudflare issue. So now that Cloudflare is only used as a dns server, I hope it shouldn't break again. Let me know if it will.
