### ISSUE TITLE
pnpm list --filter "[<since>]" doesn't work, but pnpm run does

### ISSUE THREAD

**Issue by andrei-picus-tink** [pnpm/pnpm#7047]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/andrei-picus-tink/pnpm-filter-bug

### Reproduction steps

1. Clone the repo.
2. `git checkout changes`
3. `pnpm list -r --filter "[...main]"`
4. `pnpm run -r --filter "[...main]" test`

### Describe the Bug

The `pnpm list` command will print

```
No projects matched the filters in "pnpm-filter-bug"
```

The `pnpm run` command will run the `test` script in the `foo` package, followed by the `bar` package.

### Expected Behavior

I expect the `pnpm list` command to print `foo` and `bar`, in line with `pnpm run`.

### Which Node.js version are you using?

18.14.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by await-ovo** [comment]
Hi! To filter out all the packages that have changed since the 'main' branch, as well as any packages that depend on them, you can use the following syntax:

```
pnpm list -r --filter "...[main]"
```

Please avoid using `[...main]` as it may not yield the desired results. Thank you for your attention ~

**Comment by andrei-picus-tink** [comment]
Thanks @await-ovo, `...[branch]` seems to do what I need. I should have paid more attention to the examples at https://pnpm.io/filtering#--filter-since, but I was too focused on the header that said `[<since>]` so I assumed the `...` went inside too 🙃
