### ISSUE TITLE
Pnpm does not install dependecies using git support

### ISSUE THREAD

**Issue by andreidev1** [pnpm/pnpm#7057]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

8.5.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

Install a package directly from a git repo using :
`pnpm install https://github.com/<....>/<...>.git`
OR
`pnpm add -D https://github.com/<....>/<...>.git`

### Describe the Bug

If a package that lives in a github repo is getting installed with the above commands it does not automatically install the `dependencies` that lives in `package.json`

I should see those `dependencies` added in my `node_modules/` directory

### Expected Behavior

If I'd use `npm i -D https://github.com/<....>/<...>.git` I can clearly see that the `dependencies` that live in `package.json` are also added inside in my `node_modules/` directory

### Which Node.js version are you using?

18.17.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Mint

**Comment by nachoaldamav** [comment]
I guess you are referring to the `node_modules` structure, this should work as intended as pnpm only places the direct dependencies in the root `node_modules` (Learn more [here](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory)).

I created a `package.json` with Axios as a dependency, using it's git repo as the version. Axios is installed and the dependencies too.

Root `node_modules`:
```bash
nacho@Ignacios-MacBook-Pro git-package % ls -l node_modules/
axios -> .pnpm/github.com+axios+axios@a989ccdc1a672171e9b45d3f02edc260109a607c/node_modules/axios
```
`node_modules/.pnpm`:
```bash
nacho@Ignacios-MacBook-Pro git-package % ls -G node_modules/.pnpm/
asynckit@0.4.0                                                  lock.yaml
combined-stream@1.0.8                                           mime-db@1.52.0
delayed-stream@1.0.0                                            mime-types@2.1.35
follow-redirects@1.15.2                                         node_modules
form-data@4.0.0                                                 proxy-from-env@1.1.0
github.com+axios+axios@a989ccdc1a672171e9b45d3f02edc260109a607c
```

**Comment by andreidev1** [comment]
@nachoaldamav I see thank you.
