### ISSUE TITLE
Enable customizable output formatting for recursive runs

### ISSUE THREAD

**Issue by zirkelc** [pnpm/pnpm#7061]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a developer using PNPM in CI/CD environments like GitHub Actions,

I want to control the format of console output when running scripts recursively or using the --filter option,

So that I can ensure better integration with tools that interpret stdout, such as GitHub Actions' error annotations.

---
When executing multiple scripts concurrently using PNPM's --recursive or --filter options, I'd like more control over the console output format.

For instance, the command:
```sh
pnpm --recursive --no-bail --parallel --filter './e2e/*' test
```
generates an output resembling:
```sh
> pnpm --recursive --no-bail --parallel --filter './e2e/*' test

Scope: 2 of 10 workspace projects
e2e/foo test$ playwright test
e2e/bar test$ vitest run
e2e/bar test:  RUN  v0.33.0 
e2e/foo test: Running 68 tests using 1 worker
e2e/foo test:  ...
e2e/bar test:  ...
```

Here, each output line starts with the workspace prefix, such as e2e/foo or e2e/bar.

However, this format can be problematic for continuous integration platforms like GitHub Actions. Specifically, GitHub Actions allows for [error annotation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) via unique command syntax like echo `::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon`. It scans every stdout line for these commands to generate annotations accordingly.

For instance, the [Playwright's GitHub reporter](https://playwright.dev/docs/test-reporters#github-actions-annotations) utilizes this unique syntax to create workflow annotations.

Given this context, I propose introducing a new option to PNPM that allows users to suppress these workspace prefixes during runs.

### Describe the solution you'd like

I propose three potential solutions:

- Toggle Flag: Introduce a straightforward flag, --no-prefix, which when set, would disable prefixing during the execution of multiple scripts.

- Customizable Prefix: Offer a more flexible option, --prefix "{time}-{name}", that lets users employ a templating approach to control the output format.

- Custom Reporters: Allow the integration of custom reporters alongside [current ones](https://pnpm.io/cli/install#--reportername). These reporters would grant users more freedom in formatting each output.

### Describe the drawbacks of your solution

Supporting custom reporters could introduce dependency challenges and necessitate a stable API.

### Describe alternatives you've considered

The [concurrently](https://github.com/open-cli-tools/concurrently#usage) package bears resemblance to running PNPM with the --parallel option. However, it boasts added features, such as --prefix none, which allows users to completely omit formatting.

**Comment by KSXGitHub** [comment]
> * Custom Reporters: Allow the integration of custom reporters alongside [current ones](https://pnpm.io/cli/install#--reportername). These reporters would grant users more freedom in formatting each output.

Amongst the current ones, there's one called `ndjson`. If that's not for custom reporters, how else would custom reporters communicate with pnpm?

**Comment by zirkelc** [comment]
I saw the `ndjson` reporter. However, this one is hard-coded into PNPM:
https://github.com/pnpm/pnpm/blob/46cecfc60fcb38f445df05ab160dd552282c7426/pnpm/src/reporter/index.ts#L15-L56

With custom reporter, I mean a separate NPM package that can be installed and that exports some kind of API. PNPM then runs with this reporter when explicitly defined as CLI option:
```sh
pnpm run --reporter=my-custom-reporter test
```

**Comment by KSXGitHub** [comment]
@zirkelc What I'm trying to say is: You could pipe the `ndjson` output of pnpm to external program and format it in whatever form you want.

**Comment by zirkelc** [comment]
Yes, I had the same idea, but for that you have to know the format of all possible outputs and what should and should not be printed. 
I think I am hesitant that I might swallow some information accidentally. It would be good to have the default logger as a fallback option, so that only the outputs of the actual running script need to be formatted.

I should try again if there are no others with similar requirements.

**Comment by KSXGitHub** [comment]
Custom reporters is complicated. But having an option to not add prefix is sufficient for your use case, right?

**Comment by KSXGitHub** [comment]
> [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

Since you are willing to implement this yourself, I think you can implement `--no-prefix` quickly enough. Or should it be `--reporter=no-prefix`? You should ask @zkochan for preference.

**Comment by zirkelc** [comment]
Great, that would be nice! I recently switched from NPM to PNPM and it would be cool to contribute to this great project.

I'll wait for @zkochan reply before I get started.

**Comment by zkochan** [comment]
I don't have objections. For the option name, maybe `--reporter-hide-prefix`

**Comment by zkochan** [comment]
The new option should be added to the docs

**Comment by zirkelc** [comment]
@zkochan please check https://github.com/pnpm/pnpm.io/pull/459
