### ISSUE TITLE
Windows Defender reports Trojan:Win32/Wacatac.B!ml on 8.7.4 (Windows 11)

### ISSUE THREAD

**Issue by blockarchitech** [pnpm/pnpm#7064]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.4

### Which area(s) of pnpm are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Reproduction steps

- Go to https://github.com/pnpm/pnpm/releases/tag/v8.7.4 and download latest windows installer
  - Chrome will also flag as virus; ignore for now
- Open installer, or click "continue download". Windows defender will block it.

### Describe the Bug

Windows defender reports pnpm as Trojan:Win32/Wacatac.B!ml

### Expected Behavior

Installer to open cleanly

### Which Node.js version are you using?

v20.5.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by aarondake** [comment]
I'm using Windows 10 still (corporate machine) and for me it's showing Trojan:Win32/Wacatac.F!ml, with an "F" instead of a "B".

![image](https://github.com/pnpm/pnpm/assets/28267519/5f73b97b-c9b7-4bc8-b2d5-0088f2e2aff3)

**Comment by bestagi** [comment]
I think it's was false positive because only 5/71 AV detected this file. you can see full result at Virus Total here: [VirusTotal pnpm 8.7.4](https://www.virustotal.com/gui/file/19a6c87039501fabf093995c192e785ce3fd28bd679fba44fd8956818ce9c062/detection)

Please report false positive file to Windows Defender

**Comment by LordBucea** [comment]
I can confirm this is an issue with Bitdefender
\AppData\Local\Temp\WinGet\pnpm.pnpm.9.10.0\DOF50.tmp is infected with Trojan.Agent.GMQ
Bitdefender Total Security
Build: 27.041.197

**Comment by w3bdesign** [comment]
I get the same issue with Microsoft Defender

**Comment by zkochan** [comment]
I don't know why this happens. I assume as a workaround you can install pnpm via corepack or npm.

**Comment by vsDizzy** [comment]
![image](https://github.com/user-attachments/assets/6982d5a4-a8cd-409a-b8cb-ae2a627fb46c)
Same

**Comment by w3bdesign** [comment]
> ![image](https://private-user-images.githubusercontent.com/5798340/369870640-6982d5a4-a8cd-409a-b8cb-ae2a627fb46c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTkwNzcsIm5iZiI6MTcyNzExODc3NywicGF0aCI6Ii81Nzk4MzQwLzM2OTg3MDY0MC02OTgyZDVhNC1hOGNkLTQwOWEtYjhjYi1hZTJhNjI3ZmI0NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMTkxMjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg4YTI2YWYxY2Y0YTY2ZmU5NTY5NTJlZThjNjRmNDcwMDdiN2QzMjRkZmMyMDZhYjIyMGMyMDk5MzIwOTlmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.w2DGerWleOl4GsOK008KZllpK1zekyeo17BdqW7B8So) Same

May be related to this pinned issue:

https://github.com/pnpm/pnpm/issues/8559

**Comment by zkochan** [comment]
Duplicated issue. Also, the issue is gone right now.
