### ISSUE TITLE
pnpm link support for transitive dependencies

### ISSUE THREAD

**Issue by cdaringe** [pnpm/pnpm#7095]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a user, I want to `pnpm link -g PACKAGE` (where `PACKAGE` is a transitive dependency), such that I can debug `PACKAGE`,
but currently `pnpm link -g PACKAGE` only links the package in at the top level, and the transitive version of `PACKAGE` remains intact, thus I cannot debug `PACKAGE`.

### Describe the solution you'd like

- `pnpm link -g PACKAGE --transitive`
- `pnpm link -g PACKAGE --transitive[=optional, list, of, deps]`

allow linking of transitive dependencies!

For instance, if I am dependent on `A` and `A` is dependent on `B`,
I could `pnpm link ../../src/B --transitive`, and `B` would be linked into `A`!

### Describe the drawbacks of your solution

- `--transitive` linking could have unintended consequences if the dependency is widely used at different versions, and reliant on varying versions. users could footgun themselves by linking in incompatible development versions of packages.
   - for this reason, the `csv,of,target` patches could limit the exposure of linking 

### Describe alternatives you've considered

Perhaps using overrides/resolutions + link would be a winning recipe?

**Comment by zkochan** [comment]
I would make this the default and I would make the link command to always create overrides (I think this is how Yarn works). But this will be a breaking change.

**Comment by cdaringe** [comment]
Interesting. Would you want something like —top-level to maintain current behavior? Or is current behavior not worth maintaining in your perspective, supposing a breaking change was accepted into some future release?

**Comment by zkochan** [comment]
No, I don't think we would need a `--top-level` option if we do this with overrides.

**Comment by cdaringe** [comment]
I have my dev env setup and have located _some_ of the relevant code paths. On `pd link ../debug` into a project where it is used transitively,

- `pkg-manager/plugin-commands-installation/src/link.ts`,  `handler` starts to build up the link options for an installation mutation
   - we eventually call into `install` with the 2nd param being `MutationOptions`
   - I _think_ an `overrides` specification will likely live in these mutation options?
      - I did try a naive splatting of `overrides: { debug: ... } }` into the mutationOptions with no success, but it was not a thoughtful attempt 😄 
- `pkg-manager/core/src/install/index.ts` builds up a call stack of `install` => `_install` => `headlessInstall`
   - `headlessInstall` seems to be where _most_ of the magic happens
   - i'm having a bit of a hard time discerning which options would need to be set inside of headless install, such that I can make the patches work _back up_ in the callee functions

If you would be willing to give me a few pointers, that would be helpful. Random thought's I've had on the matter:

- Do I need to request _re-resolution_ explicitly for packages that _depend_ on `debug`... or should that happen implicitly within existing logic?
- Should an `in-mem`-only modification of the logical `{ pnpm: { overrides: { debug: ..... } }` be all that is needed, or are there possibly more cases to consider?

Thanks for your time! I'll be poking around a bit more, but a new codebase is often hard to navigate without a little bit of coaching 😄 !

**Comment by cdaringe** [comment]
`createVersionsOverrider` 🤔 is probably in play here, too. i see it used when backfilling default options

**Comment by zkochan** [comment]
I don't think changes to core or headless are needed. The changes to overrides should be persisted to the filesystem (written to `package.json`) and the update overrides should be passed to mutateModules. The rest will work automatically.

**Comment by cdaringe** [comment]
Hmm. Sincere ask, is it worth doing at all if we persist?

Generally, I use `link` for temporary testing only. Persisting to package.json is a somewhat permanent-like thing, especially given that it is a tracked file.

I'm _personally in favor_ of one of the two options:

- make `pnpm link ...` work with overrides _without_ persisting changes to `package.json`, or...
- just recommend people use `overrides` directly

`link` doesn't persist in the other pkg managers. it would possibly violate common expectations if it did in `pnpm`? then again, `pnpm link`'s current behavior is also a bit different than the others :)

**Comment by cdaringe** [comment]
just ended up using overrides.
