### ISSUE TITLE
`pnpm i` adding the pnpm store folder in project's folder

### ISSUE THREAD

**Issue by patheticGeek** [pnpm/pnpm#7100]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.5

### Link to the code that reproduces this issue or a replay of the bug

https://asciinema.org/a/608473

### Reproduction steps

1. Create a new project folder and do `pnpm init`
2. Install any package, e.g. `pnpm i express`
3. Check the files in folder, a new folder "~" will appear

### Describe the Bug

For some reason, the pnpm store folder is being added in the project folder and git also shows changes in it.

In this example it is empty, but in an actual project it has the whole cache

![image](https://github.com/pnpm/pnpm/assets/11344611/2cf2ea2c-66a7-43e5-860d-f87fe1847465)

### Expected Behavior

The "~" folder should not be appearing

### Which Node.js version are you using?

v18.17.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 23.04

**Comment by capndave** [comment]
Just noting that I'm unable to replicate your issue using pnpm 8.7.5 and Ubuntu 20.4.6. `pnpm install` makes a `node_modules` directory as expected. `ls ~/.local/share/pnpm/store` shows the same directory structure shown in your screenshot but there's no actual `~` directory made

**Comment by patheticGeek** [comment]
@capndave Did you just `pnpm init` and `pnpm install`? Can you try `pnpm i express` (with a package basically)?
I am not fully sure what more output I can give you, here's the stat and screenshot of file manager
The modify time shows that it is created along with pnpm lock and node modules
```
╭─ 🌚 geek in ~/personal-projects/test-pnpm 
╰➜ ls
drwxrwxr-x   - geek 18 Sep 16:03 node_modules
drwxrwxr-x   - geek 18 Sep 16:03 ~
.rw-rw-r-- 273 geek 18 Sep 16:03 package.json
.rw-rw-r-- 14k geek 18 Sep 16:03 pnpm-lock.yaml
╭─ 🌚 geek in ~/personal-projects/test-pnpm 
╰➜ stat "~"                                
  File: ~
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 259,6	Inode: 3434775     Links: 3
Access: (0775/drwxrwxr-x)  Uid: ( 1000/    geek)   Gid: ( 1000/    geek)
Access: 2023-09-18 16:03:27.125167388 +0530
Modify: 2023-09-18 16:03:27.125167388 +0530
Change: 2023-09-18 16:03:27.125167388 +0530
 Birth: 2023-09-18 16:03:27.125167388 +0530
╭─ 🌚 geek in ~/personal-projects/test-pnpm 
╰➜ stat "./~"
  File: ./~
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 259,6	Inode: 3434775     Links: 3
Access: (0775/drwxrwxr-x)  Uid: ( 1000/    geek)   Gid: ( 1000/    geek)
Access: 2023-09-18 16:03:27.125167388 +0530
Modify: 2023-09-18 16:03:27.125167388 +0530
Change: 2023-09-18 16:03:27.125167388 +0530
 Birth: 2023-09-18 16:03:27.125167388 +0530
```
 
![image](https://github.com/pnpm/pnpm/assets/11344611/e1d6d923-5f62-4580-a96e-a7725e61ba84)

**Comment by patheticGeek** [comment]
bumping this as i am still facing this issue

**Comment by vuggy17** [comment]
+1 on this when running pnpm install in a dev container

**Comment by patheticGeek** [comment]
> +1 on this when running pnpm install in a dev container

Oh, it might be useful for them if you provide the docker file or something if you can?

**Comment by vuggy17** [comment]
Sure

> @vuggy17 Oh, it might be useful for them if you provide the docker file or something if you can?


`pnpm install` resulted in an error (see the image), it also create a `.pnpm-store` at the project root folder


![image](https://github.com/pnpm/pnpm/assets/61084329/994fb057-45de-43c4-815d-e473a2cb4799)



here is my `devcontainer.json`
```javascript
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/typescript-node
{
	"name": "Node.js & TypeScript",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye",
	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "pnpm install",
	// Configure tool-specific properties.
	"customizations": {
		"vscode": {
			"extensions": [
				"nrwl.angular-console",
				"esbenp.prettier-vscode",
				"dbaeumer.vscode-eslint",
				"firsttris.vscode-jest-runner",
				"spmeesseman.vscode-taskexplorer",
				"streetsidesoftware.code-spell-checker",
				"bradlc.vscode-tailwindcss"
			]
		}
	}, 
	"runArgs": ["--env-file", "./apps/idle.chat/local.env"]
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**Comment by patheticGeek** [comment]
@inthegreenwild can you tell output of `echo $PNPM_HOME`
this issue is because pnpm home env var isnt expanded or is set incorrectly
remove it or set it to `export PNPM_HOME="$HOME/.local/share/pnpm/store"` in bashrc or zshrc

**Comment by ackvf** [comment]
Should we delete this folder or add it to .gitignore?
