### ISSUE TITLE
Add --ignore-scripts option to pnpm dedupe command

### ISSUE THREAD

**Issue by liby** [pnpm/pnpm#7102]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

I often want to run the `pnpm dedupe` command without executing the scripts defined in the _package.json_. [In my workflow](https://github.com/renovatebot/renovate/discussions/24417#discussioncomment-7003077), I need to deduplicate packages without triggering any side effects that could be caused by those scripts. 

Currently, there's no straightforward way to achieve this with `pnpm dedupe`.

### Describe the solution you'd like

I would like to propose the addition of an `--ignore-scripts` option to the `pnpm dedupe` command. This option would prevent the execution of scripts during the deduplication process. 

This would be similar to the `--ignore-scripts` option available in the `pnpm install` command. This solution would provide more flexibility to developers who need to control when and how scripts are executed.

### Describe the drawbacks of your solution

The potential drawbacks of this solution lie in the fact that the `pnpm dedupe` command internally invokes `pnpm install`. 
To handle the `--ignore-scripts` flag, we simply need to pass it down to the `pnpm install` command. However, to avoid altering the default behavior, we should set its default value to false.

This approach, while straightforward, does introduce a level of complexity as we need to ensure that the flag is correctly propagated through the various command calls. Additionally, it may not be immediately clear to users that the `--ignore-scripts` flag applies to the `pnpm dedupe` command given its internal reliance on the `pnpm install` command. As such, careful documentation and communication would be necessary to avoid confusion.

### Describe alternatives you've considered

An alternative solution would be to manually disable scripts in the package.json file before running `pnpm dedupe`, and then re-enable them afterwards. 

However, this approach is cumbersome and error-prone. It also doesn't provide a good user experience, especially for developers who frequently need to deduplicate packages without running scripts. 

Therefore, I believe adding an `--ignore-scripts` option to `pnpm dedupe` would be a more elegant and efficient solution.

**Comment by zkochan** [comment]
What about the scripts of dependencies? If you download a new repository and then run `pnpm dedupe --ignore-scripts`, pnpm will install node_modules and not build and packages in node_modules. In any case, this will be opt-in, so I don't have objections.

**Comment by liby** [comment]
Thanks for your feedback. Although we haven't faced this scenario yet, I will continue to monitor the situation. If any discussions or issues arise about this flag, I will look into potential solutions.
