### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Meeeeow** [pnpm/pnpm#711]
### Code to reproduce the issue:
Any command, `pnpm` or `pnpm install` or `pnpm --help`

pnpm-debug.log:
```
---{}
```

### Error message:
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.<anonymous> (C:\Users\Me\AppData\Local\nvs\node\7.9.0\x64\node_modules\pnpm\lib\api\extendOptions.js:8:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```
### Additional information:
 - `node -v` prints: 7.9.0
 - Windows, OS X, or Linux?: Windows 10 Version 15063

**Comment by zkochan** [comment]
Seems like neith `npm` nor `nodejs` is in your `PATH` environment variable.

The error happens because this returns undefined https://github.com/QingWei-Li/global-bin-path/blob/master/index.js

I'll fix it in scope of #695

In the meanwhile you can add either `npm` or `nodejs` to `PATH`

**Comment by Meeeeow** [comment]
@zkochan I'm using nvs(node version switcher), with `C:\Users\Me\AppData\Local\nvs\default` in user's `PATH`

**Comment by zkochan** [comment]
I see.

If you want, you can just manually go to that file where the exception happens and pass in a value instead of `undefined`. In that case `pnpm i` will work for you. `pnpm i -g` won't work till the fix.

I'll fix this probably tonight or this weekend

**Comment by ShadowRZ** [comment]
@zkochan Since you said the store won't change (at least in the same major version I guess?) as in https://github.com/pnpm/pnpm/issues/7115#issuecomment-1962675989 , **you should explain this: https://github.com/pnpm/pnpm/issues/8713**
