### ISSUE TITLE
Pnpm install hangs indefinitely

### ISSUE THREAD

**Issue by rottabonus** [pnpm/pnpm#7110]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

I cannot share the private repository, more info in description

### Reproduction steps

Run `pnpm install`
...Wait

### Describe the Bug

In our pipelines the `pnpm install` hangs indefinitely. 
I ran the installation command with --reporter ndjson and the last four log-outputs are here:

`{"time":1695113022384,"hostname":"runner-gyrzezc4-project-832-concurrent-0","pid":59,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"/builds/app/app-web/quentic-app-ui","status":"imported","to":"/builds/app/app-web/quentic-app-ui/node_modules/.pnpm/@icons+material@0.2.4_react@18.2.0/node_modules/@icons/material"}
{"time":1695113022444,"hostname":"runner-gyrzezc4-project-832-concurrent-0","pid":59,"level":"debug","name":"pnpm:progress","packageId":"registry.npmjs.org/@mui/icons-material/5.14.9","requester":"/builds/app/app-web/quentic-app-ui","status":"found_in_store"}
{"time":1695113022468,"hostname":"runner-gyrzezc4-project-832-concurrent-0","pid":59,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"/builds/app/app-web/quentic-app-ui","status":"imported","to":"/builds/app/app-web/quentic-app-ui/node_modules/.pnpm/date-fns@2.30.0/node_modules/date-fns"}
{"time":1695113023296,"hostname":"runner-gyrzezc4-project-832-concurrent-0","pid":59,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"/builds/app/app-web/quentic-app-ui","status":"imported","to":"/builds/app/app-web/quentic-app-ui/node_modules/.pnpm/@mui+icons-material@5.14.9_@mui+material@5.14.9_@types+react@18.0.28_react@18.2.0/node_modules/@mui/icons-material"}`

This happens on a [node:18.16 docker image](https://hub.docker.com/_/node/).
After waiting the pipeline fails after timing out..
Locally the installation works.

### Expected Behavior

Installation should succeed

### Which Node.js version are you using?

18.16.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Debian

**Comment by zkochan** [comment]
Do you use the `use-node-version` setting? The node.js servers are terribly slow lately, so if pnpm tries to download node.js, it might hang.

**Comment by rottabonus** [comment]
Hello! After a bit of debugging the problem is not with pnpm. Read: It was an user error ;)

Thanks!
