### ISSUE TITLE
pnpm doesn't add binary to `node_modules/.bin` if bin command is prefixed (@prefix/package-name)

### ISSUE THREAD

**Issue by marvinjude** [pnpm/pnpm#7112]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.6.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/marvinjude/prefixed-package-bin-issue

### Reproduction steps

> **pnpm** install

### Describe the Bug

If a package `@prefix/package-name` ships with a `bin` field like so:

```json
"bin": {
  "@prefix/package-name": "./somefile"
}
```
After an install, one would expect that pnpm would add the binary `package-name` to `node_modules/.bin`(just like in npm, bun and yarn v2) but that doesn't happen.  Doing a `pnpm patch` on such a package and changing the command to "package-name" without the prefix gets it to work. Another  typical fix for this on the package author's end would be to change the above bin configuration to

```json
"bin":  "./somefile"
```

### Expected Behavior

pnpm should add binary to  `node_modules/.bin` for packages with  prefixed commands like the below:

```json
"bin": {
  "@prefix/package-name": "./somefile"
}
```
so that you can run `pnpm exec package-name`.

**Happy to work on this with some directions if the team considers this a bug**

### Which Node.js version are you using?

18.17.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by cdaringe** [comment]
i think this is _undefined_ behavior as specified by npm, which pnpm attempts some amount of compliance: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin

i _personally_ wouldn't label it as a bug, as it violates some norms:

- `@` in the executable--do you really want an executable with a `@` in it? fwiw, npm installs an executable just called `ui`. 
- `/` in the executable--what would that produce? a subfolder in bin? if that's the case, `.bin/` housing executables would be an implicit violation of expectations

albeit the current behavior of doing _nothing_ is agreeably not ideal (a warning perhaps would be warranted), expecting a bin name of that to work is also subjectively not a fair/reasonable expectation either.

i'd change the bin name to `ui` to proceed. maybe add logging/warns to this case during the bin linking

**Comment by marvinjude** [comment]
Yeah, a warning is definitely a great idea, I'd say, a great example for other package managers.

Along with the warning, It makes sense for pnpm to also maintain a behavior that exists in other major package managers - yarn(v2), bun, and npm and not just bail out.

And yeah! we may not explicitly label this a bug, maybe a compatibility / feature request is more ideal.
