### ISSUE TITLE
The index files in store changed in 8.7.2

### ISSUE THREAD

**Issue by linsui** [pnpm/pnpm#7115]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.2

### Reproduction steps

Generate the store with `pnpm install` with pnpm 8.7.1 and 8.7.2. Check the store. The index files are different. Some files generated by pnpm 8.7.2 don't have `version` and `name` in them but the files generated by 8.7.1 have them.

### Describe the Bug

The store files changed. When I package a package managed by pnpm for nixpkgs I need to download all deps into the store and calculate the hash. I remove all timestamp and sort the index files to make it reproducible. But the recent update from 8.7.1 to 8.7.2 changed the files.

### Expected Behavior

The store files are generated in a stable format.

### Which Node.js version are you using?

20.6.1

### Which operating systems have you used?

- [x] macOS
- [x] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

NixOS

**Comment by zkochan** [comment]
ok, we should fix this.

**Comment by zkochan** [comment]
yes
