### ISSUE TITLE
ERR_PNPM_TARBALL_EXTRACT occurs on install tgz files 

### ISSUE THREAD

**Issue by dante01yoon** [pnpm/pnpm#7120]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

7.33.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

pc: MacBook Prop 14 Ventura 13.5.2
node: v14.18.0

installing fails with error `(ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.`. 

### Describe the Bug

pc: MacBook Prop 14 Ventura 13.5.2
node: v14.18.0

installing fails with error `(ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.`. 

I'm getting struggle on ERR_PNPM_TARBALL_EXTRACT error occured 

>GET https://custom.registry.net/artifactory/api/npm/npm-virtual/handlebars/-/handlebars-4.7.8.tgz error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://custom.registry.net/artifactory/api/npm/npm-virtual/coa/-/coa-1.0.4.tgz": incorrect data check

### Expected Behavior

tgz file should be downloaded. 
downloading via manually entering url is works. 

### Which Node.js version are you using?

v14.18.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Does it work with the latest pnpm? Does it work with npm or Yarn?

Installing this package via the public registry works for me:

```
 pnpm add handlebars@4.7.8
```

**Comment by dante01yoon** [comment]
This issues are occurred with both npm, yarn also.

I figured this issues with remove all the brew, nvm and re install with.

However, there is no info about `ERR_PNPM_TARBALL_EXTRACT`  in docs.  
maybe it would be better add some info in docs

**Comment by arcusmaximus** [comment]
Getting this with pnpm 8.15.0 and the package "devextreme-17.1.6":

> ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://registry.npmjs.org/devextreme/-/devextreme-17.1.6.tgz": Error: This parser only supports USTAR or GNU TAR archives. Found magic and version:

(No magic or version are mentioned)

npm can install the same package just fine.

**Comment by dante01yoon** [comment]
What I tried to resolve this problem was install packages using npm and use pnpm again. That was workaround, but not a fair solution for everyone.

**Comment by zkochan** [comment]
Regarding `devextreme@17.1.6`. First I thought this was a regression introduced by our migration to our own tarball parser. However, it fails even with pnpm v8.1 (which is before the tarball parser rewrite):

```
Failed to unpack the tarball from "https://registry.npmjs.org/devextreme/-/devextreme-17.1.6.tgz": Invalid tar header: unknown format.
```

It does seem to work with both npm and Yarn. However, it looks like these type of packages are a rarity, so if it is hard to update our parser to work with these tarballs, we can use a different extractor for these type of packages.

**Comment by zkochan** [comment]
Actually, if I remove this chunk of code then it works:

https://github.com/pnpm/pnpm/blob/f5eadba94394114a303d6bedbc78cf8f4de75ad4/store/cafs/src/parseTarball.ts#L79-L95

@dmichon-msft do we really need to throw that error? Maybe a warning would be sufficient? The package seem to be correctly unpacked if I remove the error.
