### ISSUE TITLE
`pnpm update` should also update the `packageManager` setting

### ISSUE THREAD

**Issue by Bessonov** [pnpm/pnpm#7134]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

The `pnpm update --interactive --recursive --latest` command is amazing for updating dependencies. But for updating the version of `pnpm` used in corepack's `packageManager` setting, I need to find out the last release of `pnpm` and change it manually.

### Describe the solution you'd like

```
> pnpm update --interactive --recursive --latest

? Choose which packages to update (Press <space> to select, <a> to toggle all, <i> to invert selection) … 
❯ ○ pnpm (packageManager)        8.1.1 ❯ 8.8.0 
  ○ @types/node (dev)        20.6.5 ❯ 20.7.0 
  ○ @types/webpack-env (dev) 1.18.1 ❯ 1.18.2 
  ○ kill-port (dev)           1.6.1 ❯ 2.0.1  
  ○ tailwindcss (dev)         3.3.1 ❯ 3.3.3
```

### Describe the drawbacks of your solution

Effort required for implementation and maintenance.

### Describe alternatives you've considered

It could probably be resolved by an independent package, but I didn't find any. Additionally, the same argument could be applied to the existing `pnpm update` command.

**Comment by zkochan** [comment]
Sounds good, I think

**Comment by edvinv** [comment]
`pnpm update` is for updating dependencies, for updating package manager and packageManager property inside package.json you should use `corepack up` or `corepack use <name@version>` when you need next major version.

**Comment by Bessonov** [comment]
@edvinv Thanks, I wasn't aware of `corepack up`. More details [here](https://github.com/nodejs/corepack#corepack-up).

Although I disagree that `pnpm update` is solely for updating dependencies, I believe using `corepack up` makes sense to save valuable development resources.

@zkochan @fireairforce I'm going to close this feature request. Feel free to reopen it if you believe that the value (for instance user update to the new `pnpm` version earlier) outweighs the effort. Personally, I would love to see it in `pnpm`, but I see the drawbacks too.

**Comment by Sayvai** [comment]
> `pnpm update` is for updating dependencies, for updating package manager and packageManager property inside package.json you should use `corepack up` or `corepack use <name@version>` when you need next major version.

After running `corepack up`, I received the following error:

```
ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.4.0 of pnpm. Your current pnpm is v9.1.4
```

So i resolved the above error by running the following command in the terminal / CLI to update the system **global** install of the `pnpm` package manager itself:

```
$ pnpm add -g pnpm
```

OR, if installing a specific version

```
$ pnpm add -g pnpm@9.4.0
```

**Comment by andersk** [comment]
@Sayvai To use Corepack, you should not have a system global install of pnpm at all. Run `corepack enable` to restore the Corepack wrappers. ([Documentation](https://nodejs.org/api/corepack.html#running-npm-install--g-yarn-doesnt-work).)

**Comment by Sayvai** [comment]
> @Sayvai To use Corepack, you should not have a system global install of pnpm at all. Run `corepack enable` to restore the Corepack wrappers. ([Documentation](https://nodejs.org/api/corepack.html#running-npm-install--g-yarn-doesnt-work).)

@andersk I did actually run `corepack enable` initially (without error), and the `pnpm -v` (version) was still stuck at the previous version of `v9.1.4` at the time.

However, from reading the [documentation](https://nodejs.org/api/corepack.html#running-npm-install--g-yarn-doesnt-work) you provided, maybe i should have instead ran `corepack install --global pnpm@9.4.0`? 🤔 

Also worth noting, is that i am using [NVM](https://github.com/nvm-sh/nvm) on my Mac OS to manage node versions per project. And so by running the above `corepack install --global` command, i assume it would install a pnpm version to the NVM managed node version instead(?)

**Comment by bestickley** [comment]
Since corepack is not recommended for Node.js anymore (see [here](https://www.reddit.com/r/node/comments/1ee8nkx/progress_on_versionmanagement_corepack_will_be/)), are there plans to support a pnpm CLI way to update package.json#packageManger field?

**Comment by peterhirn** [comment]
> Since corepack is not recommended for Node.js anymore (see [here](https://www.reddit.com/r/node/comments/1ee8nkx/progress_on_versionmanagement_corepack_will_be/)), are there plans to support a pnpm CLI way to update package.json#packageManger field?

The TSC only decided to stop bundling corepack with Node.js in future releases, see https://github.com/nodejs/TSC/pull/1697#issuecomment-2737093616

> Winning candidate: Phase out later: stop distributing Corepack (i.e. the distribution will no longer contain a corepack executable) on future (i.e. 25+) release lines of Node.js – existing release lines as well as the very next (i.e. 24.x) will keep it as experimental.

This has nothing to do with being "recommended" or not. We just need to install corepack using `npm install -g corepack`

For now it looks like development for corepack will continue, see https://github.com/nodejs/corepack/issues/681

**Comment by bestickley** [comment]
> are there plans to support a pnpm CLI way to update package.json#packageManger field?

I found out `pnpm self-update` will update `packageManager` field under certain conditions (I think > v10)
