### ISSUE TITLE
pnpm patch engines doesn't work 

### ISSUE THREAD

**Issue by mindyourlifeguide** [pnpm/pnpm#7148]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.8.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Lockfile

### Reproduction steps

There is a package that does not support the required version of node.
Through pnpm patch, add support for the desired version to the engines field in package.json
The patch is created, but in pnpm-lock.yaml the engines field is not taken from the patch, but from the source package.

### Describe the Bug

```
.npmrc
prefer-frozen-lockfile=true
frozen-lockfile=true
save-prefix=‘’
shamefully-hoist=true
engine-strict=true
```

```
package.json
  "engines": {
    "pnpm": ">=8.7.0 <9.0.0",
    "node": ">=20.7.0 <21.0.0"
  },

```

### Expected Behavior

In pnpm-lock.yaml, data from our patch will be taken

![image](https://github.com/ds300/patch-package/assets/35348648/ad387450-d568-4b1b-a6db-2d11d2c0f314)

![image](https://github.com/ds300/patch-package/assets/35348648/bd620c26-0131-4add-a8d7-70ab1982382a)

![image](https://github.com/ds300/patch-package/assets/35348648/6d13df32-f0ff-440d-aa75-ff251b4bfe8c)

### Which Node.js version are you using?

20.7.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
A patch won't affect the engines field because we take engines field from the packument. In your case, from here: https://registry.npmjs.org/@achrinza/node-ipc

You can use the read package [hook](https://pnpm.io/pnpmfile#hooksreadpackagepkg-context-pkg--promisepkg) to change the engines field:

```js
module.exports = {
  hooks: {
    readPackage: (pkg) => {
      delete pkg.engines
      return pkg
    }
  }
}

```
