### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by sol-invictus481** [pnpm/pnpm#715]
### Code to reproduce the issue:
`pnpm i -S react-router@2.0.0`

[My pnpm-debug.log](https://gist.github.com/sol-invictus481/3fd520285538405325d93e28bebc1972)

### Additional information:
Using a Samsung 850GB Evo SSD, nodejs is installed in C: drive where as code is in F: drive, I did a global install of `pnpm` and then tried the above command in F: drive which gave the above error, however I tried the same in a new folder in C: and the installation succeeded (blazing fast BTW), I then did a local install of pnpm in F: drive and tried again but that also resulted in the same error.

 - `node -v` prints: v7.5.0
 - Windows, OS X, or Linux?: Windows 8.1

**Comment by zkochan** [comment]
Same as #712. Also see that issue for a temporary fix.

**Comment by sol-invictus481** [comment]
OK thanks, amazing work by the way!

**Comment by zkochan** [comment]
Closing this. Please track #712.

Also a temporary fix published in [v0.69.0-beta.3](https://github.com/pnpm/pnpm/releases/tag/v0.69.0-beta.3). You can install it via `npm i -g pnpm@next`

**Comment by zkochan** [comment]
Fix published in [v1.15.0](https://github.com/pnpm/pnpm/releases/tag/v1.15.0). Each disk has a dedicated store now.

**Comment by fc** [comment]
My co-worker spontaneously ran into this issue and it appears to be resolved after deleting his node_modules in his local directory.
