### ISSUE TITLE
pnpm does not fail when adding a non existing package from the local file system

### ISSUE THREAD

**Issue by singhshashi** [pnpm/pnpm#7159]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.8.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/singhshashi/issue-pnpm

### Reproduction steps

1. Just start with a bare repo
2. pnpm init 
3. Now add a package from the local file system that does not exists (pnpm add ../proac)
4. pnpm should fail but it succeeds in adding a non existent package. 
![Screenshot 2023-10-04 at 3 51 30 PM](https://github.com/pnpm/pnpm/assets/371601/19f78120-aee5-469d-bf7e-fdc0fdd77518)

### Describe the Bug

When I provide an incorrect location of a package from my local file system, then pnpm should fail with the error message that the package does not exist. However, it succeeds and adds the non existent package to the package.json

### Expected Behavior

Since there is nothing at the location I provided, pnpm add should fail giving an error that nothing exists at the given location. 

### Which Node.js version are you using?

18.15.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
>  I do find it odd that you would add a non existent package to package.json.

When the directory at the target location will be created, the broken symlink will become valid.
