### ISSUE TITLE
Wrongful ELIFECYCLE error on program termination 

### ISSUE THREAD

**Issue by yanickrochon** [pnpm/pnpm#7164]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.8.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Hooks

### Reproduction steps

1. Create a new Turborepo project
2. Create a Next.js app
3. Launch app through `turbo`
4. Exit app through <kbd>CTRL+C</kbd>

### Describe the Bug

When launching `pnpm next dev`, then <kbd>CTRL+C</kbd>, no error is emitted. However launching through `turbo`, the signal received is correct, `SIGINT`, however `pnpm` ignores it.

The following code is found in `dist/pnpm.cjs`, line 98629 (I cannot find that code in this repository)
```js
      proc.on("close", (code, signal) => {
        opts.log.silly("lifecycle", logid(pkg, stage), "Returned: code:", code, " signal:", signal);
        let err;
        if (signal) {
          err = new PnpmError("CHILD_PROCESS_FAILED", `Command failed with signal "${signal}"`);
          process.kill(process.pid, signal);
        } else if (code) {
          err = new PnpmError("CHILD_PROCESS_FAILED", `Exit status ${code}`);
          err.errno = code;
        }
        procError(err);
      });
```

The `signal` received is `SIGINT`, which is correct, and the `code` is `null`, which also correct. However, the condition ignores the signal and creates a `CHILD_PROCESS_FAILED` regardless of it's value.

### Expected Behavior

When pressing <kbd>CTRL+C</kbd>, `pnpm` should not throw an error.

### Which Node.js version are you using?

18.15.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Stanzilla** [comment]
ah there we go, here i was blaming turborepo for that

**Comment by yanickrochon** [comment]
The error is [here](https://github.com/pnpm/npm-lifecycle/blob/99ac0429025bdf1303879723d3fbd57c585ae8a1/index.js#L278-L289), in the [`@pnpm/npm-lifecycle`](https://github.com/pnpm/npm-lifecycle) dependency, and the fix is to replace the condition to

```ts
if (signal && signal !== "SIGINT") {
```

**Comment by yanickrochon** [comment]
According to the reverted changes, this issue was not resolved.

**Comment by zkochan** [comment]
What reverted changes? I have not published your changes yet because the tests are failing on Windows.

**Comment by zkochan** [comment]
CI was not configured on the repository. I have configured it and in the future it won't happen again.

**Comment by Stanzilla** [comment]
should this issue be re-opened then?

**Comment by hax** [comment]
We met similar issue in pnpm 9.0.2 .

The scripts are like:
```json
{
  "scripts": {
    "dev": "pnpm watch",
    "watch": "node watch1.js & node watch2.js"
  }
}
```

`watch1` and `watch2` are processes which need run in background. Execute `pnpm watch` directly is ok, but `pnpm dev` will report ELIFECYCLE errors when Ctrl-C. Change `pnpm` to `npm` works.
