### ISSUE TITLE
How to make --save-exact the default when using pnpm add

### ISSUE THREAD

**Issue by tsongas** [pnpm/pnpm#7172]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

If developers have to remember to type `--save-exact` when using `pnpm add`, that sometimes won't happen (especially true when copying and pasting commands while following instructions to set something up). This could lead to a broken production application, downtime, stress, and wasted developer hours.

### Describe the solution you'd like

I see in the docs I can create a .npmrc file and set a [default prefix](https://pnpm.io/npmrc#save-prefix). However it isn't clear if I can set that prefix to an empty string so that a prefix is not used by default, thereby pinning dependencies by default. Is it possible to set an empty `save-prefix`? If not, could a setting like `save-exact = true` be added to enable this behavior?

### Describe the drawbacks of your solution

None. Developers who want to tempt fate with automatic updates could still do so.

### Describe alternatives you've considered

npm and yarn have the [save-exact](https://docs.npmjs.com/cli/v10/using-npm/config#save-exact) option but it would be super unfortunate to go back.

**Comment by zkochan** [comment]
> This could lead to a broken production application, downtime, stress, and wasted developer hours.

Not really, if you use lockfiles.

> However it isn't clear if I can set that prefix to an empty string so that a prefix is not used by default, thereby pinning dependencies by default. Is it possible to set an empty save-prefix?

Yes, it can be empty

**Comment by ides15** [comment]
```sh
save-prefix=""
```
works for me.

**Comment by tsongas** [comment]
`save-prefix=''` worked for me too.
