### ISSUE TITLE
pnpm 8.9.0 removes overrides in pnpm-lock.yaml

### ISSUE THREAD

**Issue by yogarasu** [pnpm/pnpm#7189]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.9.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Lockfile, Package manager compatibility

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/yogarasu/pnpm-sample

### Reproduction steps

Run the install or update command on pnpm 8.9.0.

### Describe the Bug

The "overrides" description in pnpm-lock.yaml has been removed.

### Expected Behavior

The "overrides" description in pnpm-lock.yaml is not removed

### Which Node.js version are you using?

18.18.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

macOS Sonoma 14.0

**Comment by yogarasu** [comment]
Judging from the release status of 8.9.0, the fix around #7174 may be the cause.

**Comment by zkochan** [comment]
I can't reproduce the issue. Install and update keeps the overrides field in `pnpm-lock.yaml`.

**Comment by yogarasu** [comment]
@zkochan 
Ah, I was able to reproduce it in the morning, but now I can't reproduce it even in my environment.
It's very strange, but I can't reproduce the phenomenon, so I'll close it.
Thank you for taking the time out of your busy schedule.
