### ISSUE TITLE
patchedDependencies not working

### ISSUE THREAD

**Issue by unional** [pnpm/pnpm#7198]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

When trying to upgrade some dependency, the command fails.

### Describe the Bug

`pnpm up something` fails with:

```sh
ENOENT: no such file or directory, open '/Users/<user>/Library/pnpm/store/v3/tmp/dlx-66214/patches/@changesets__assemble-release-plan@5.2.3.patch'
```

which the file `patches/@changesets__assemble-release-plan@5.2.3.patch` is a local file in the repository.

The `package.json`:

```js
{
  "pnpm": {
    "patchedDependencies": {
      "@changesets/assemble-release-plan@5.2.3": "patches/@changesets__assemble-release-plan@5.2.3.patch"
    }
  }
}
```

It is working in 8.8.x and prior. Broken in 8.9.0

### Expected Behavior

The should be working fine as in 8.8.x

### Which Node.js version are you using?

16.19.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by alumni** [comment]
I can confirm this too after the upgrade from 8.8.0 to 8.9.0.

Node 18.18.1, macOS + Windows + Linux

Our setup is an NX monorepo with a single lockfile at the root. `pnpm install` works, but `pnpm install --recursive` fails in the apps in the monorepo.

**Comment by zkochan** [comment]
> `pnpm up something` fails with:

I think you run `pnpm dlx`, not `pnpm update`
