### ISSUE TITLE
pnpm filter always installs the workspace root dependencies

### ISSUE THREAD

**Issue by pyrocat101** [pnpm/pnpm#7208]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

1. Create a pnpm workspace with package `foo`.
2. Add some dependencies to the root `package.json` and some dependencies to `foo/package.json`.
3. `pnpm install --filter foo`
4. Notice that dependencies in the root project are also installed.

### Describe the Bug

This is a regression since v7.22.0: caused by the partial revert in https://github.com/pnpm/pnpm/pull/5882.

### Expected Behavior

Root project dependencies are not installed.

### Which Node.js version are you using?

20.8.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
I don't think we can support installation without the root. We can run install in an independent subset of projects but the root node_modules influences all projects in the workspace, and dependencies from the root node_modules are used to resolve peer dependencies in all projects.

If you don't want anything in the root to be installed, then maybe just don't install any dependencies in the root.

I'm personally not sure when would anyone even run a install with `--filter`. If you want to deploy a single project from the workspace, there's a [separate command](https://pnpm.io/cli/deploy) for it.
