### ISSUE TITLE
Pnpm autofixing lockfile is not working

### ISSUE THREAD

**Issue by XantreGodlike** [pnpm/pnpm#7213]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.9.2 

### Reproduction steps

1. Have lockfile with merge confilct
2. Try to install.
3. Fails with error of renaming of random package

### Describe the Bug

Produced errors.
```
 ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename 'D:\Projects\work\Oone.World\trucks-driver-app\packages\location-watcher\node_modules\metro-minify-uglify_tmp_32504' -> 'D:\Projects\work\Oone.World\trucks-driver-app\packages\location-watcher\node_modules\metro-minify-uglify'
```
or with another:
```
 ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename 'D:\Projects\work\Oone.World\trucks-driver-app\node_modules\@react-native-firebase\app_tmp_6680' -> 'D:\Projects\work\Oone.World\trucks-driver-app\node_modules\@react-native-firebase\app
```

npmrc:
```
shamefully-hoist=true
node-linker=hoisted
```

### Expected Behavior

Install is not failing. 
All works correctly for 8.7.6 version

### Which Node.js version are you using?

18.18.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by mhamri** [comment]
I'm having the same issue, quite giving up on pnpm, every single pnpm install cause a similar error

for me is this 
```

 ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename 'C:\repo\Planally3\frontend-old\node_modules\@nx\eslint-plugin\node_modules\@typescript-eslint\typescript-estree_tmp_9464' -> 'C:\repo\Planally3\frontend-old\node_modules\@nx\eslint-plugin\node_modules\@typescript-eslint\typescript-estree'

``` 

always rename is not permitted error. I've added full control on the folder, changed security permission, but nothing helped.

i'm trying to avoid running the pnpm as root
otherwise this issue shouldn't happen

**Comment by XantreGodlike** [comment]
Can you copy paste pnpm-lock?

**Comment by XantreGodlike** [comment]
Can you copy paste pnpm-lock?

**Comment by XantreGodlike** [comment]
Can you copy paste pnpm-lock?

**Comment by XantreGodlike** [comment]
Deleting of whole node_modules is not working, too
As workaround you can downgrade pnpm to `8.7.6`

**Comment by ImUrX** [comment]
This happened to me in my windows machine, just after importing a `package-lock.json` and doing `pnpm i`, it fixed when I changed to `8.7.6`

**Comment by zkochan** [comment]
Is v8.8.0 the first version where it gets broken?

**Comment by zkochan** [comment]
This might fix the issue: https://github.com/zkochan/packages/pull/181. But I couldn't reproduce it.

**Comment by ImUrX** [comment]
any way i can try it

**Comment by zkochan** [comment]
@ImUrX build pnpm from the repository and see if the issue is fixed.

**Comment by ImUrX** [comment]
I'm no longer able to replicate my issue in the windows machine I had the issues with in `8.10.2` which was where I had issues with 😓.
Not even after deleting the pnpm cache and node_modules in each subpackage.

**Comment by tl-frameplay** [comment]
This error has been driving me nuts for the past few months. There is very little information online how to fix it. I tried a lot of things nothing fixed it permanently.

My current solution is to clear the pnpm cache, delete all the node_modules, restart windows 11 and hope for the best. Even after all of that the error still happens often. Then magically, it just works after a lot of attempts and restarts.

Worst case scenario is to update the pnpm version, but then it happens again intermittently.

![image](https://github.com/pnpm/pnpm/assets/87164862/06eb08fc-95f3-41c0-8e07-ddb5740effc4)

**Comment by mhamri** [comment]
I encountered this again today

```
 ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename 'D:\hustling\Planally\P1\frontend\node_modules\@testing-library\dom\node_modules\aria-query_tmp_20636' -> 'D:\hustling\Planally\P1\frontend\node_modules\@testing-library\dom\node_modules\aria-query'
  pnpm --version
8.10.2

```

this is the ndjson reporter that could be related 

```
us":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@storybook\\manager-webpack5"}
{"time":1702456165394,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\postcss-modules-extract-imports"}
{"time":1702456165422,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\postcss-modules-local-by-default"}
{"time":1702456165573,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@storybook\\angular"}
{"time":1702456166035,"hostname":"rekab","pid":18444,"level":"error","name":"pnpm","code":"ERR_PNPM_LINKING_FAILED","name":"pnpm","err":{"name":"pnpm","message":"Error: ENOENT: no such file or directory, scandir 'D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@types\\jest_tmp_18444\\node_modules'","code":"ERR_PNPM_LINKING_FAILED","stack":"pnpm: Error: ENOENT: no such file or directory, scandir 'D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@types\\jest_tmp_18444\\node_modules'\n    at Worker.<anonymous> (C:\\snapshot\\pnpm\\pnpm\\dist\\pnpm.cjs)\n    at Object.onceWrapper (node:events:652:26)\n    at Worker.emit (node:events:537:28)\n    at MessagePort.<anonymous> (node:internal/worker:233:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:645:20)\n    at exports.emitMessage (node:internal/per_context/messageport:23:28)"}}
{"time":1702456166158,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\postcss-modules-scope"}
{"time":1702456166188,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\postcss-modules-values"}
{"time":1702456166286,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@testing-library\\cypress"}
{"time":1702456166440,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@angular\\compiler-cli"}
{"time":1702456166465,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@types\\pluralize"}
{"time":1702456166582,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@types\\node"}
{"time":1702456167460,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"copy","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@angular\\cli"}
{"time":1702456167471,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\mathjs"}
{"time":1702456167520,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\@typescript-eslint\\parser"}
{"time":1702456167553,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\cypress-file-upload"}
{"time":1702456167584,"hostname":"rekab","pid":18444,"level":"debug","name":"pnpm:progress","method":"hardlink","requester":"D:\\hustling\\Planally\\P1\\frontend","status":"imported","to":"D:\\hustling\\Planally\\P1\\frontend\\node_modules\\cypress-network-idle"}
```

**Comment by sharky98** [comment]
> This might fix the issue: [zkochan/packages#181](https://github.com/zkochan/packages/pull/181). But I couldn't reproduce it.

No idea if this is a permanent fix, but after manually patching the `dist/pnpm.cjs` file with this code `pnpm install` finally worked after trying for about 3 hours to find what was the culprit, I still suspect the antivirus, but I have no control over it due to corporate policies.

**Comment by zkochan** [comment]
I assume this started happening when we switched to sync filesystem operations. In the past pnpm used async fs operations but now we use sync operations in multiple worker threads that run in parallel. The async version of the rename function is doing the retry after a small delay, which might result in better success rate. The sync version retries immediately. We can try to add "busy waiting" to the sync version.

**Comment by sharky98** [comment]
> I assume this started happening when we switched to sync filesystem operations. In the past pnpm used async fs operations but now we use sync operations in multiple worker threads that run in parallel. The async version of the rename function is doing the retry after a small delay, which might result in better success rate. The sync version retries immediately. We can try to add "busy waiting" to the sync version.

If this change happened this year, this could be it. Earlier this year I was not having issues at all (don't remember the version though). Then it started popping up very often, never on the same file.

With the proposed change above to retry, it continues to do the error, but way less frequently! 

To me it seems related to the number of packages installed at once. Chances are that the process reading the `tmp` files is not able to keep up the pace with pnpm renaming them (or the opposite, pnpm is too slow to rename them before the process kicks in to read them 🤷)

When adding very few packages, it seems less frequent, but when doing a fresh `pnpm install` on a big list of packages, it does happen a lot more.
