### ISSUE TITLE
`pnpm import` does not work correctly.

### ISSUE THREAD

**Issue by mochang2** [pnpm/pnpm#7217]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

1. Run `npm install -g pnpm@latest`. The version of pnpm is 8.9.2
2. Add the following code to your project’s package.json.

`"scripts": { "preinstall": "npx only-allow pnpm", ... }`

As I am not using a monorepo, I didn't create `pnpm-workspace.yaml`.

3. Create `pnpm-lock.yaml` by executing `pnpm import`.
4. `rm -rf ./node_modules/`
5. `pnpm install`
6. Execute `pnpm electron` to run `"scripts": { "electron": "vue-cli-service electron:serve", ... }`, but it fails with the following statement:

`Syntax Error: Error: [BABEL] ~~.js: Cannot find module 'core-js/package.json'`

### Describe the Bug

**Information**
- OS: Windows 10
- Node version: 16.20.1
- NPM version: 8.19.4
- PNPM version: 8.9.2
- lockfileVersion: 2

**Description**

I tried to migrate `npm` to `pnpm`, but some node_modules(`core-js`), which I could install with `npm` and the original lock file(`package-lock.json`) are not able to be installed with `pnpm` and the new lock file(`pnpm-lock.yaml`).
I think `pnpm import` omitted some modules.
(`npm run electron` worked well before because `core-js` was correctly installed)

This is my `package.json`(I omitted some options).

```json
{
  "scripts": {
    "preinstall": "npx only-allow pnpm",
    "electron": "vue-cli-service electron:serve",
  },
  "dependencies": {
     // ...
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "cross-env": "^7.0.3",
    "electron": "22.3.8",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.64.1",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "~2.1.1"
  }
}
```

`@vue/cli-plugin-babel` has `@vue/babel-preset-app` as "dependencies" as written in the original lock file.
The following is a part of `package-lock.json`.

```json
{
  "node_modules/@vue/cli-plugin-babel": {
      "version": "4.5.13",
      "resolved": "https://registry.npmjs.org/@vue/cli-plugin-babel/-/cli-plugin-babel-4.5.13.tgz",
      "integrity": "sha512-ykvEAfD8PgGs+dGMGqr7l/nRmIS39NRzWLhMluPLTvDV1L+IxcoB73HNLGA/aENDpl8CuWrTE+1VgydcOhp+wg==",
      "dev": true,
      "dependencies": {
        "@babel/core": "^7.11.0",
        "@vue/babel-preset-app": "^4.5.13",
        "@vue/cli-shared-utils": "^4.5.13",
        "babel-loader": "^8.1.0",
        "cache-loader": "^4.1.0",
        "thread-loader": "^2.1.3",
        "webpack": "^4.0.0"
      },
      "peerDependencies": {
        "@vue/cli-service": "^3.0.0 || ^4.0.0-0"
      }
   }
}
```

Also, `@vue/babel-preset-app` "requires" `core-js` as written in the original lock file.

```json
{
  "@vue/babel-preset-app": {
      "version": "4.5.13",
      "resolved": "https://registry.npmjs.org/@vue/babel-preset-app/-/babel-preset-app-4.5.13.tgz",
      "integrity": "sha512-pM7CR3yXB6L8Gfn6EmX7FLNE3+V/15I3o33GkSNsWvgsMp6HVGXKkXgojrcfUUauyL1LZOdvTmu4enU2RePGHw==",
      "dev": true,
      "requires": {
        "@babel/core": "^7.11.0",
        "@babel/helper-compilation-targets": "^7.9.6",
        "@babel/helper-module-imports": "^7.8.3",
        "@babel/plugin-proposal-class-properties": "^7.8.3",
        "@babel/plugin-proposal-decorators": "^7.8.3",
        "@babel/plugin-syntax-dynamic-import": "^7.8.3",
        "@babel/plugin-syntax-jsx": "^7.8.3",
        "@babel/plugin-transform-runtime": "^7.11.0",
        "@babel/preset-env": "^7.11.0",
        "@babel/runtime": "^7.11.0",
        "@vue/babel-plugin-jsx": "^1.0.3",
        "@vue/babel-preset-jsx": "^1.2.4",
        "babel-plugin-dynamic-import-node": "^2.3.3",
        "core-js": "^3.6.5",
        "core-js-compat": "^3.6.5",
        "semver": "^6.1.0"
      }
   }
}
```

Of course, `core-js` is also written.

```json
{
    "core-js": {
      "version": "3.15.2",
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-3.15.2.tgz",
      "integrity": "sha512-tKs41J7NJVuaya8DxIOCnl8QuPHx5/ZVbFo1oKgVl1qHFBBrDctzQGtuLjPpRdNTWmKPH6oEvgN/MUID+l485Q==",
      "dev": true
    }
}
```

`pnpm-lock.yaml` also correctly has `@vue/cli-plugin-babel`.
However, `@vue/babel-preset-app` is different.
It does not "require" or have `core-js` as "dependencies".
The following is a part of `pnpm-lock.json`.

```yaml
/@vue/babel-preset-app@4.5.13(@babel/core@7.14.8)(vue@3.1.5):
  resolution: {integrity: sha512-pM7CR3yXB6L8Gfn6EmX7FLNE3+V/15I3o33GkSNsWvgsMp6HVGXKkXgojrcfUUauyL1LZOdvTmu4enU2RePGHw==}
  peerDependencies:
    '@babel/core': '*'
    core-js: ^3
    vue: ^2 || ^3.0.0-0
  peerDependenciesMeta:
    core-js:
      optional: true
    vue:
      optional: true
  dependencies:
    '@babel/core': 7.14.8
    '@babel/helper-compilation-targets': 7.14.5(@babel/core@7.14.8)
    '@babel/helper-module-imports': 7.14.5
    '@babel/plugin-proposal-class-properties': 7.14.5(@babel/core@7.14.8)
    '@babel/plugin-proposal-decorators': 7.14.5(@babel/core@7.14.8)
    '@babel/plugin-syntax-dynamic-import': 7.8.3(@babel/core@7.14.8)
    '@babel/plugin-syntax-jsx': 7.14.5(@babel/core@7.14.8)
    '@babel/plugin-transform-runtime': 7.14.5(@babel/core@7.14.8)
    '@babel/preset-env': 7.14.8(@babel/core@7.14.8)
    '@babel/runtime': 7.14.8
    '@vue/babel-plugin-jsx': 1.0.6(@babel/core@7.14.8)
    '@vue/babel-preset-jsx': 1.2.4(@babel/core@7.14.8)
    babel-plugin-dynamic-import-node: 2.3.3
    core-js-compat: 3.15.2
    semver: 6.3.0
    vue: 3.1.5
  transitivePeerDependencies:
    - supports-color
  dev: true
```

As a result, there is no `core-js` in `pnpm-lock.yaml`.

+) I wondered that what if I start with `pnpm init`(not migration). I tried `pnpm init` -> `pnpm i ${dependencies}` -> `pnpm electron`, but the result was same.

### Expected Behavior

The following should be included in `pnpm-lock.yaml` when running `pnpm import`.
(Maybe not only `core-js` but also some other modules)

```yaml
/core-js@3.15.2:
  resolution: {integrity: sha512-tKs41J7NJVuaya8DxIOCnl8QuPHx5/ZVbFo1oKgVl1qHFBBrDctzQGtuLjPpRdNTWmKPH6oEvgN/MUID+l485Q==}
  deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
  dev: true
```

### Which Node.js version are you using?

16.20.1(npm v8.19.4)

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by mochang2** [comment]
If you need my `package-lock.json` or `pnpm.yaml`, please leave a comment.

**Comment by await-ovo** [comment]
Hey, thanks for your report, a package.json and `package-lock.json` file would be nice ~

**Comment by mochang2** [comment]
@await-ovo I invited you [my private repo](https://github.com/mochang2/pnpm-temp).
As there are modules which have vulnerabilities, I set this repository as private(This is the decision of my team to prevent possible mishaps).
Please understand my situation and if you need other members, you could invite them.

**Comment by mochang2** [comment]
I will close this issue.
I recently know that `pnpm` does not work in an electron app, where symlinks are not supported.

Releated issue: https://github.com/orgs/nodejs/discussions/37509
