### ISSUE TITLE
Make "pnpm install" on existing repo faster

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#722]
- [x] - implement
- [x] - publish
- [x] - update benchmark repo

### pnpm version:

0.65.4

### Code to reproduce the issue:

```
pnpm install <a list of packages to install>
pnpm install
```

### Expected behavior:

The second installation should be under a second.

### Actual behavior:

Currently running "pnpm install" on a project that has a ready node_modules folder takes longer than with npm or yarn

***

Also update the benchmarks repo with this use case

Work done in this PR #663 can probably be reused

**Comment by vjpr** [comment]
I upgraded from 0.60.0 to 0.65.5 and installing a single module now takes forever on my big monolith. I don't remember it taking so long. I reinstalled `node_modules` using `pnpm i --force`.

It seems it is checking every module and linking every module each run.

But now it is almost as slow as npm and pretty unusable for me. `1m05s` to install a single dependency.

Did something change to cause such a big regression?

**Comment by zkochan** [comment]
Yes, you can update to 0.65.7 and single module installation should be fast as it was.

I did a lot of changes to make peer dependencies resolution correct. My changes have made named installations slower but I fixed it in #726.

So named installations should be fast again but we'll have to also make repeat installations fast.

**Comment by vjpr** [comment]
Phew! 2.3s single module installs now.

**Comment by zkochan** [comment]
In the current latest version (v0.66.1) repeat installation takes between 1 and 2 seconds. There is no output though, when everything in node_modules is up to date.

I believe it can be even faster, so keeping this issues open

**Comment by zkochan** [comment]
There are several open issues about performance improvements, so no reason to keep this open.
