### ISSUE TITLE
pnpm bin removed from PNPM_HOME after update

### ISSUE THREAD

**Issue by aburkowsky9** [pnpm/pnpm#7220]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release
This has happened on every update using v8, but I did not see this issue in v7

### pnpm version

v8.9.0 -> updating to v8.9.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

run `pnpm add -g pnpm` when an update is available

### Describe the Bug

For the past few versions of v8 I have had issues updating pnpm. Every time an update has been available and I run `pnpm add -g pnpm`, I am greeted by an error after update attempt followed by the lack of ability to utilize the pnpm cli even after reloading the terminal or restarting my computer.

After digging into the $PNPM_HOME dir I was able to determine the issue. Every time I have tried to update using `pnpm add -g pnpm` the pnpm bin is removed from that directory and the new version of pnpm's node_modules remains empty. See the screenshot below for post update results:
<img width="1039" alt="Screenshot 2023-10-18 at 7 57 37 AM" src="https://github.com/pnpm/pnpm/assets/38677277/80d1201e-5250-4b8b-9e31-79f7c69830a8">

 
<img width="758" alt="Screenshot 2023-10-18 at 7 58 21 AM" src="https://github.com/pnpm/pnpm/assets/38677277/0c8a85be-1ba4-46d9-807a-d46eeb0efbdf">

This forces me to reinstall pnpm through `curl` using `curl -fsSL https://get.pnpm.io/install.sh | sh -`. This always works well and is how I originally installed pnpm on my system.

After pnpm is reinstalled through `curl`, I am able to once again access the pnpm cli but I can't find the scoped node version installed through `pnpm env`.  To make this again accessible I need to run `pnpm add -g pnpm` again, but this time it works! See the screenshot below for the $PNPM_HOME directory after running those two commands - all is back to normal:
<img width="942" alt="Screenshot 2023-10-18 at 7 59 45 AM" src="https://github.com/pnpm/pnpm/assets/38677277/22d0c084-f10c-433f-9047-58ce23b625bd">

Here is a screenshot of `pnpm config list --global`:
<img width="652" alt="Screenshot 2023-10-18 at 8 00 13 AM" src="https://github.com/pnpm/pnpm/assets/38677277/67303616-94d9-40d0-952c-7ac7129edf01">

`pnpm doctor` provides no output in my case

### Expected Behavior

I run `pnpm add -g pnpm` and the bin updates in place, scoped node version remains accessible.

### Which Node.js version are you using?

v18.18.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by aburkowsky9** [comment]
Just an update. I just updated from v8.9.2 -> v8.10.0 and experienced the same bug

**Comment by flo333** [comment]
Same issue here while trying to update from 9.3.0 to 9.8.

**Comment by aburkowsky9** [comment]
seems to no longer be an issue after the new `self-update` command
