### ISSUE TITLE
Dependencies for all packages are installed even with `--filter` is used

### ISSUE THREAD

**Issue by walkerburgin** [pnpm/pnpm#7242]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.0.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/walkerburgin/pnpm-filter-repro

### Reproduction steps

Checkout https://github.com/walkerburgin/pnpm-filter-repro/tree/develop

Use pnpm v8.0.0 to install dependencies for two of the four packages in the workspace (`@monorepo/foo-app` and `@monorepo/foo-lib`): 

```bash
node pnpm/v8.0.0/bin/pnpm.cjs install --filter @monorepo/foo-app...
```

Observe that dependencies were installed for `@monorepo/bar-app` and `@monorepo/bar-lib` as well: 

```bash
➜ pnpm-filter-repro tree -d packages
packages
├── bar-app
│   └── node_modules
│       ├── @monorepo
│       │   └── bar-lib -> ../../../bar-lib
│       ├── cypress -> ../../../node_modules/.pnpm/cypress@13.0.0/node_modules/cypress
│       ├── react -> ../../../node_modules/.pnpm/react@18.2.0/node_modules/react
│       ├── react-dom -> ../../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom
│       └── typescript -> ../../../node_modules/.pnpm/typescript@5.2.2/node_modules/typescript
├── bar-lib
│   └── node_modules
│       ├── react -> ../../../node_modules/.pnpm/react@18.2.0/node_modules/react
│       └── typescript -> ../../../node_modules/.pnpm/typescript@5.2.2/node_modules/typescript
├── foo-app
│   └── node_modules
│       ├── @monorepo
│       │   └── foo-lib -> ../../../foo-lib
│       ├── react -> ../../../node_modules/.pnpm/react@18.2.0/node_modules/react
│       ├── react-dom -> ../../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom
│       └── typescript -> ../../../node_modules/.pnpm/typescript@5.2.2/node_modules/typescript
└── foo-lib
    └── node_modules
        ├── react -> ../../../node_modules/.pnpm/react@18.2.0/node_modules/react
        └── typescript -> ../../../node_modules/.pnpm/typescript@5.2.2/node_modules/typescript
```

### Describe the Bug

It looks like the `--filter` argument may have been broken in the `v8.0.0` release.

We have a large monorepo that uses PNPM. Under the hood our build system calls `pnpm install` using the `--filter` argument to install dependencies for just the subset of the repository that a developer is working on. This has historically been significantly faster than installing dependencies for the entire monorepo. The ability to perform a filtered install like this was actually the killer feature that led us adopt PNPM in the first place!

What I'm observing with v8.x is that on mac, installing dependencies for the entire monorepo is significantly faster than it was in 7.x (~2m49s to ~1m23s 🥂 ), but the filtered install performed by our build system is almost always slower than 7.x -- presumably as a result of this bug (picking an arbitrary project, ~51s to ~1m5s).

### Expected Behavior

I expect that dependencies for other packages in the workspace (`@monorepo/bar-app` and `@monorepo/bar-lib` in this example) are not installed. This was the behavior in v7.33.6:

```bash
➜ pnpm-filter-repro node pnpm/v7.33.6/bin/pnpm.cjs install --filter @monorepo/foo-app...
``` 

```bash
➜ pnpm-filter-repro tree -d packages
packages
├── bar-app
├── bar-lib
├── foo-app
│   └── node_modules
│       ├── @monorepo
│       │   └── foo-lib -> ../../../foo-lib
│       ├── react -> ../../../node_modules/.pnpm/react@18.2.0/node_modules/react
│       ├── react-dom -> ../../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom
│       └── typescript -> ../../../node_modules/.pnpm/typescript@5.2.2/node_modules/typescript
└── foo-lib
    └── node_modules
        ├── react -> ../../../node_modules/.pnpm/react@18.2.0/node_modules/react
        └── typescript -> ../../../node_modules/.pnpm/typescript@5.2.2/node_modules/typescript
```

### Which Node.js version are you using?

18.18.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jfirebaugh** [comment]
Confirmed. I was trying to figure out why `pnpm install --frozen-lockfile --config.recursive-install=false --filter ./` was installing everything when it seemed like it was the correct command to install only packages from the root-level package.json. It works as expected with pnpm 7.33.5 but installs all workspaces packages with 8.10.2.

**Comment by m1heng** [comment]
same here, please check, this is quite critical @pnpm/collaborators

**Comment by gluxon** [comment]
It is a surprise to me that `dedupe-peer-dependents=true` (the default) causes pnpm to link `node_modules` in all workspace packages regardless of `--filter` values.

It was known that `dedupe-peer-dependents` would introduce a performance penalty since pnpm needs to analyze the full dependency graph to see what peers could be deduped. I suspect some part of evaluating the full dependency graph to determine peers to dedupe caused all workspace packages to be included for linking.

Haven't dug into the code yet, but it feels like pnpm could "look" at the full dependency graph while still avoiding linking `node_modules` in later stages. That would allow users to leave `dedupe-peer-dependents` enabled without taking as much of a performance penalty.

**Comment by tcstory** [comment]
i met the same problem on 8.9.0
