### ISSUE TITLE
Incorrect Error Message When Workspace Root Command Not Found

### ISSUE THREAD

**Issue by shellscape** [pnpm/pnpm#7244]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.*

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/rollup/plugins/actions/runs/6644527027/job/18053872346#step:15:31

### Reproduction steps

To reproduce, attempt to call a workspace root script with an incorrect or nonexistent script name. e.g. `pnpm --workspace-root batman:smells`

### Describe the Bug

The CLI will produce an incorrect error message:

```
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "--workspace-root" not found
```

This looks like a holdover from before pnpm moved the order of pnpm-flags and removed the `--` for script parameter passing.

### Expected Behavior

The CLI should produce a message with the correct erroneous script name:

```
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "batman:smellst" not found
```

### Which Node.js version are you using?

20.4.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

**Comment by JasonMan34** [comment]
For a quick fix, use `pnpm run -w foo` explicitly over `pnpm -w foo`

**Comment by shellscape** [comment]
Thanks @zkochan!
