### ISSUE TITLE
Electron symlinks recreation

### ISSUE THREAD

**Issue by spamshaker** [pnpm/pnpm#7253]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.9.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Package manager compatibility, Operating System (Windows, MacOS, Linux)

### Reproduction steps

STR:

1. `mkdir test-project && cd test-project && npm init --yes && pnpm i electron`
2. `rm -rf node_modules`
3. `pnpm i`

### Describe the Bug

getting this: https://github.com/electron/electron/issues/40359
Electron has  postinstall script which brings the target electron app https://github.com/electron/electron/blob/652f995128de858c7a68fad853f56e80e0c2c222/npm/package.json#L8
The issue is that there should be symlinks created by electron postrscript. This postinstall script creates them properly when unzipping the electron zip package. Now the pnpm is not executing this postinstall script while bringing node_modules from cache. Instead it is providing some cached value which doesn't contain symlinks

when I call `rm -rf /Users/user/Library/pnpm/store/v3/files` then the post install is executed and links are properly created
![image](https://github.com/pnpm/pnpm/assets/4864089/499604bc-4362-458b-8374-5e6e1eea8aa1)

second attempt fails with
![image](https://github.com/pnpm/pnpm/assets/4864089/5994b4b9-478c-4db6-84bf-a1494c3fc6d6)

### Expected Behavior

recreate symlinks for electron content

### Which Node.js version are you using?

18.18.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by spamshaker** [comment]
dealt with temporary solution. In root I added:
```
  "scripts": {
    "prepare": "rm -rf node_modules/electron/dist && node node_modules/electron/install.js",
    ...
    }
```

**Comment by teddyfullstack** [comment]
@spamshaker You saved my day 🙏

**Comment by zkochan** [comment]
This PR should fix it: https://github.com/pnpm/pnpm/pull/7705

**Comment by mrnasil** [comment]
@spamshaker You saved my day 🙏
