### ISSUE TITLE
Postinstall scripts are now always run after pnpm install is ran

### ISSUE THREAD

**Issue by mattlewis92** [pnpm/pnpm#7268]
### Last pnpm version that worked

8.9.2

### pnpm version

8.10.0

### Code to reproduce the issue

I can reproduce this on any repo that uses pnpm with dependencies with postinstall scripts:

```
gh repo clone mattlewis92/angular-calendar
corepack enable
pnpm i
pnpm i # Observe how all dependencies postinstall scripts are re-ran
```

If you revert back to pnpm `8.9.2` here, then you'll see the bug is fixed:

https://github.com/mattlewis92/angular-calendar/blob/5477127c428391a0b0086da2126035ea001b5cff/package.json#L8

### Expected behavior

Postinstall scripts are not ran when repeatedly running `pnpm install`

### Actual behavior

Postinstall scripts are always ran, regardless if nothing changed. This leads to slow performance

### Node.js version

20.6.1

### Operating System

macOS

**Comment by JonoPrest** [comment]
Hi there, 

My team is also encountering this issue and it is a breaking change for our code-generator product that we are building.

We build in the Rescript/Ocaml eco system and rely on a lot of PPX binaries that all have postinstall scripts and break when the postinstall script gets rerun usually since the binary has already been moved. For example using this package: 

https://github.com/rescript-association/genType

**Comment by zkochan** [comment]
I'll look into it.

**Comment by JonoPrest** [comment]
> I'll look into it.

Thanks so much 🙏🏼

**Comment by zkochan** [comment]
I'll release a fix today.

**Comment by mattlewis92** [comment]
Wow, that was so fast. Thank you for the quick patch, it's really appreciated! ❤️

**Comment by JonoPrest** [comment]
Thanks for the amazingly fast patch. Much appreciated 🙏🏼

**Comment by andreifilip123** [comment]
Hello. This is still happening to me on pnpm 8.15.3. Any tips on how to debug why ?

Node.js version
20.11.1

Operating System
macOS 14.3 (Sonoma)

**Comment by rtrembecky** [comment]
I now encounter this on pnpm@8.15.8, but also when I reverted to older versions (8.7.6, 8.9.2), so it leads me to conclusion there's something wrong with my setup/lock after complicated merges.
