### ISSUE TITLE
`pnpm install` saves as dependency in package.json when it is listed as optionalDependency

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#727]
### Code to reproduce the issue:

- Add `fsevents` to `optionalDependencies` in package.json
- Run `pnpm install fsevents`

### Expected behavior:

- It should install the version listed in `optionalDependencies` and not add it to `dependencies`.

### Actual behavior:

- Saves to `dependencies` and installs latest dist-tag.

### Additional information:

 - `node -v` prints: 6.5.0
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
Released in [v0.69.4](https://github.com/pnpm/pnpm/releases/tag/v0.69.4)
