### ISSUE TITLE
pnpm deploy failing on missing devDependency

### ISSUE THREAD

**Issue by JasonMan34** [pnpm/pnpm#7281]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/JasonMan34/pnpm-deploy-dev-deps

### Reproduction steps

Reproduction steps in the repo. Manual steps are:

1. Have a functional workspace with `package A` having `package B` as a devDependency with the `workspace:` protocol
2. Delete the directory where `package B` is defined (This simulates copying `package A` without its devDependencies in a Dockerfile)
3. Run `pnpm --filter packageA deploy --prod out`

### Describe the Bug

When running `deploy --prod`, packages in `devDependencies` should be ignored. However, if the package is missing entirely from the workspace, an error is thrown

### Expected Behavior

Expected no error and for the dependency to be ignored entirely

### Which Node.js version are you using?

20.9.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by JasonMan34** [comment]
This also happens when running `pnpm install --prod`, which feels like a bug as well (I feel --prod should act the same no matter what happens in `devDependencies`).

If this behavior should stay as is for `pnpm install --prod` as well, then I suggest to allow passing `--frozen-lockfile` to `deploy` which will resolve the use-case for this issue (Dockerfile deploy)

**Comment by Torrino** [comment]
In my case, I ran `pnpm deploy --filter=myapp /prod/myapp` for building my Dockerimage and I **want** dev dependencies in this scenario but I keep getting an error on a missing dev dependency

**Comment by JasonMan34** [comment]
> We are having a discussion at #8778

I'll close this issue in favor of it
