### ISSUE TITLE
Suggestion: Drop the "run" argument and look up scripts config object

### ISSUE THREAD

**Issue by lumio** [pnpm/pnpm#731]
This is just a suggestion:
If a command was not found (e.g. `pnpm deploy`) it should look up the command from the scripts config object and run it instead. So if you want to run your defined deploy script, instead of doing `pnpm run deploy`, you just do `pnpm deploy`.

**Comment by zkochan** [comment]
What I don't like about this is that adding a new command would always be a breaking change in this case.

But it would be probably fine to add shortcuts to pnpm. Something like `pr deploy` would mean `pnpm run deploy`

There's also a recipe how to do this w/o changes to pnpm: https://github.com/sindresorhus/awesome-npm#shell-aliases

**Comment by zkochan** [comment]
Just use [pnpx](https://pnpm.js.org/docs/usage/pnpx-cli.html)
