### ISSUE TITLE
`pnpm publish` doesn't work with `tokenHelper`

### ISSUE THREAD

**Issue by ari-becker** [pnpm/pnpm#7316]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

1. Set up a token for publishing using `tokenHelper`, i.e. a `~/.npmrc` with:
```
//npm.pkg.github.com/:tokenHelper=/Users/ari/.local/bin/gh-token-helper
```
where the contents of that file are:
```
#! /bin/sh

/opt/homebrew/bin/gh auth token
```
2. Attempt to publish a package to GitHub Packages via `pnpm publish`

### Describe the Bug

Running `pnpm publish` results in the following error:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://npm.pkg.github.com/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

This happens because `npm` does not support `tokenHelper`, and `pnpm` passes through `publish` to `npm` instead of natively implementing it.

### Expected Behavior

Successful publish, or at least an error message saying that `tokenHelper` is not supported while publishing.

Workaround is to run the `tokenHelper` to procure a token and then paste it into `~/.npmrc` in the `_authToken` field, which is supported by `npm`.

### Which Node.js version are you using?

20.9.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Shinyaigeek** [comment]
`gh auth token` command will output token, but it does not include `Beader` prefix. This issue seems to be happen because of this lack of `Beader` prefix. You may be able to fix this issue by fixing your `/Users/ari/.local/bin/gh-token-helper` like below.

```
echo "Bearer $(/opt/homebrew/bin/gh auth token)"
```
