### ISSUE TITLE
Show npm linked messages at the end of the console output as well as the start.

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#732]
If there are more modules that can fit on the screen, the linked module messages are quickly bumped off the viewable terminal.

These messages should be reprinted at the end in a summary of how the install went.

**Comment by zkochan** [comment]
This is good point. I'd also suggest to add some stats. Count of installed/uninstalled packages, time

**Comment by zkochan** [comment]
Published with [1.20.0](https://github.com/pnpm/pnpm/releases/tag/v1.20.0)
