### ISSUE TITLE
`pnpm install` acts undesirably when multiple workspaces have already installed

### ISSUE THREAD

**Issue by GitPaulo** [pnpm/pnpm#7320]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.6.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

To trigger this behaviour:

1. Have multiple workspaces setup.
2. `pnpm install` until completion.
3. Run `pnpm install` again.

### Describe the Bug

Multiple prompts are condensed into one line, making it terribly hard to read and the resulting prompt will act on all thus not allowing individual action.

```
Scope: all 40 workspace projects
? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ...
```

### Expected Behavior

IMO,

- Individually prompt for each workspace and include a `[y/n/a] (a = all)` prompt action
- Provide a flag such as `-y` to accept all without interaction, useful for automation.

### Which Node.js version are you using?

16.20.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 23.04

**Comment by robations** [comment]
I've just had this (MacOS). Similar output as above, followed by:

```
(node:10200) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10200) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(node:10200) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
```

It looks like a crash, but hitting <kbd>Y</kbd> allows to proceed.

v8.12.1
