### ISSUE TITLE
`pnpm setup` should not use the Library directory on mac

### ISSUE THREAD

**Issue by sdykae** [pnpm/pnpm#7321]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

pnpm setup

### Reproduction steps

run `pnpm setup`

appends 
```bash
# pnpm
export PNPM_HOME="/Users/sdykae/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
```

### Describe the Bug

pnpm should not use the Library reserved directory in mac osx

### Expected Behavior

sould use linux convention directories or `.config/pnpm`

reason:
osx uses $HOME/Library directory as symlink to base system, it could cause a SIP vulnerability, security risk or cause software conflicts
since we install global binaries in and that is the default directory it should be other.

### Which Node.js version are you using?

v20.9.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Someone wants to revert the change: https://github.com/pnpm/pnpm/issues/7732

cc @pnpm/collaborators

**Comment by stevenpetryk** [comment]
I don't have a strong preference either way. I like ~/.config but I understand it does not follow macOS's traditions (but also, macOS's traditions are pretty annoying from a tooling standpoint in most cases, so, screw them).

I agree with the observation that neither directory will require Full Disk Access.

**Comment by gluxon** [comment]
Copying my comment from https://github.com/pnpm/pnpm/issues/7732#issuecomment-2028479675:

> I think @arcc1845's arguments are convincing and would prefer to have less things in v9 that don't need to change. Opened a revert PR here: https://github.com/pnpm/pnpm/pull/7842

@sdykae If this doesn't sound correct, could you give us a heads up? Thanks!

**Comment by sdykae** [comment]
I proposed to move the default directory to `.config/pnpm` on macOS for enhanced security, better alignment with Unix standards, and to prevent potential conflicts in the $HOME/Library directory. This change also aligns with community expectations, mirroring practices of other widely used package managers. But others feedback is valuable.


> Copying my comment from https://github.com/pnpm/pnpm/issues/7732#issuecomment-2028479675:
> 
> 
> 
> > I think @arcc1845's arguments are convincing and would prefer to have less things in v9 that don't need to change. Opened a revert PR here: https://github.com/pnpm/pnpm/pull/7842
> 
> 
> 
> @sdykae If this doesn't sound correct, could you give us a heads up? Thanks!
