### ISSUE TITLE
Chocolatey Release Not Working for Upgrades

### ISSUE THREAD

**Issue by JameelKhan9** [pnpm/pnpm#7327]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

1. Install a slightly older version of pnpm via chocolatey
`choco install pnpm`
2. Try and upgrade
`choco upgrade pnpm`
3. Receive error:
```
ERROR: The running command stopped because the preference variable "ErrorActionPreference",
or common parameter is set to Stop: Invalid current version of pnpm detected:
"Cannot find file at '..\\lib\pnpm\tools\pnpm.exe' (C:\ProgramData\chocolatey\lib\pnpm\tools\pnpm.exe).
This usually indicates a missing or moved file.".
The install of pnpm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\pnpm\tools\ChocolateyInstall.ps1'.
 See log for details.
```

### Describe the Bug

When attempting choco upgrade of pnpm the following error is being thrown:
```
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid current version of pnpm detected: "Cannot find file at '..\\lib\pnpm\tools\pnpm.exe' (C:\ProgramData\chocolatey\lib\pnpm\tools\pnpm.exe). This usually indicates a missing or moved file.".
The install of pnpm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\pnpm\tools\ChocolateyInstall.ps1'.
 See log for details.
```

Other people of the community are also seeing this issue:
http://disq.us/p/2w8odzi

### Expected Behavior

`choco upgrade pnpm` works.

### Which Node.js version are you using?

v18.18.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by MKMZ** [comment]
Hey, I am the maintainer of PNPM's package on Chocolatey and this issue has been resolved recently.
