### ISSUE TITLE
 ERR_PNPM_INVALID_WORKSPACE_CONFIGURATION Expected object but found - array

### ISSUE THREAD

**Issue by simonfox** [pnpm/pnpm#7347]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Run `pnpm i`

My pnpm-workspace.yaml looks like this:
```
  - 'plugins/**'
  - 'radio/*'
```

there is a package.json inside the radio directory, and the plugins directory contains a number of sub-directories each of which contains a package.json.

### Describe the Bug

I've just tried to update to the latest pnpm version (8.11.0). `pnpm i` is not working. The last version this worked was 8.10.2

Running `pnpm i`, I get the error

> ERR_PNPM_INVALID_WORKSPACE_CONFIGURATION  Expected object but found - array

### Expected Behavior

Command executes successfully.

### Which Node.js version are you using?

20.5.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by ChristopherHaws** [comment]
I was having this issue and the cause was that my I was using the wrong property name in my `pnpm-workspace.yml`

Bad:
```yml
projects:
  - 'apps/*'
  - 'libs/*'
```

Good:
```yml
packages:
  - 'apps/*'
  - 'libs/*'
```


Have you tried:
```yml
packages:
  - 'plugins/**'
  - 'radio/*'
```

**Comment by simonfox** [comment]
Thank you @ChristopherHaws that was the problem!
