### ISSUE TITLE
pnpm install multiple bindings of different libc

### ISSUE THREAD

**Issue by Timeless0911** [pnpm/pnpm#7362]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

latest

### Reproduction steps

Just init an empty `package.json` as follows

```json
{
  "name": "pnpm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@rspack/binding": "latest"
  },
  "pnpm": {
    "supportedArchitectures": {
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "glibc"
      ]
    }
  }
}

```

### Describe the Bug

Run `pnpm install`, you will find both `binding-linux-x64-gnu` and `binding-linux-x64-musl` in `.pnpm` folder.

### Expected Behavior

only one of `binding-linux-x64-gnu` and `binding-linux-x64-musl` will be installed according to the libc env.

### Which Node.js version are you using?

18.17.1

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by adriaanmeuris** [comment]
I can confirm this behaviour as we're experiencing the same as described in [this issue](https://github.com/lovell/sharp/issues/3873).

Our `package.json` contains the following configuration:
```json
{
  "name": "sharp-binaries",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "dependencies": {
    "express": "4.18.2",
    "sharp": "0.33.0"
  },
  "pnpm": {
    "supportedArchitectures": {
      "os": ["linux"],
      "cpu": ["x64"],
      "libc": ["musl"]
    }
  }
}
  ```

We're building with Docker:
```Dockerfile
FROM node:lts-alpine3.18
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY package*.json ./
RUN pnpm i
```
```sh
docker build . --no-cache --platform=linux/amd64 --tag 'sharp-binaries:latest'
```

After building, we're seeing both `linux-x64` and `linuxmusl-x64` packages:
<img width="607" alt="Screenshot 2023-11-30 at 16 36 01" src="https://github.com/pnpm/pnpm/assets/16230038/6ee6c398-f585-4826-b6e8-1c2da44f9636">

**Comment by KSXGitHub** [comment]
The [documentation](https://pnpm.io/package_json#pnpmsupportedarchitectures) doesn't tell much about how this is supposed to work.

Is this supposed to work with transitive optional dependencies, @zkochan?

**Comment by nachoaldamav** [comment]
I think the problem is that pnpm is flagging every libc as `any`, for example
```
checkPlatform: registry.npmjs.org/@img/sharp-linux-x64/0.33.0 is installable {
  wantedPlatform: { cpu: [ 'x64' ], os: [ 'linux' ], libc: [ 'any' ] },
  current: { os: [ 'linux' ], cpu: [ 'x64' ], libc: [ 'musl' ] }
}
```
I'm checking it

**Comment by c0m1c5an5** [comment]
@nachoaldamav I am having the same issue with @swc/core wich install both @next/swc-linux-x64-gnu and  @next/swc-linux-x64-musl. I would like to clarify, this issue is caused by the missing libc field in package metadata provided by npm registry? If so, the issue will not be fixed until the npm registry starts filling this value?

**Comment by nachoaldamav** [comment]
@c0m1c5an5 Yes,  but there is an option to fix it in pnpm itself, but we would need to fetch the whole manifests in order to make it work. Right now pnpm fetches the simplified manifests that includes the os and cpu but not the libc.

**Comment by KSXGitHub** [comment]
I have discovered this peculiar behavior from the npm registry: Whether the npm registry returns an object with `libc` field depends on the `accept` header.

```sh
# this would print '1'
curl -H 'accept: application' -L https://registry.npmjs.org/@rspack/binding-linux-x64-gnu/ | grep --count libc
```

```sh
# this would print '0'
curl -H 'accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' -L https://registry.npmjs.org/@rspack/binding-linux-x64-gnu/ | grep --count libc
```

Is this a bug on npm registry's part?

**Comment by mrstork** [comment]
This seems to have popped up again, I'm using `10.8.0` and the same reproduction steps work for me. I've also been able to reproduce this in certain `9.15.x` versions.

I traced through some of the `pnpm` code and it seems as though the `PackageManifest` object returned from the npm registry is not including the `libc` field.

**Comment by mrstork** [comment]
Looks to be fixed again this morning 🎉
