### ISSUE TITLE
Local package not installed when using Nativescript Project

### ISSUE THREAD

**Issue by cevarief** [pnpm/pnpm#737]
Create or clone a nativescript app run `pnpm install`. 
Running `tns run ios` shows this error : 

> TypeScript installation local to project was not found. Install by executing `npm install typescript`.

It works good with npm install, but not with pnpm. Thanks.

**Comment by vjpr** [comment]
Please provide a sample project repo so we can reproduce the error.

**Comment by cevarief** [comment]
I no longer user pnpm. So i close this.
