### ISSUE TITLE
Not installing all dependencies

### ISSUE THREAD

**Issue by 19majkel94** [pnpm/pnpm#738]
### pnpm version: 
0.66.2

### Code to reproduce the issue:
package.json
```json
{
  "dependencies": {
    "fs-promise": "^2.0.0"
  }
}
```

### Expected behavior:
Install all dependencies of dependencies (`fs-promise` -> `"@types/mz": "0.0.30"`)

### Actual behavior:
tsc compilation error - `[ts] Cannot find module 'mz/fs'.`
### Additional information:

 - `node -v` prints: v7.8.0
 - Windows, OS X, or Linux?: Windows 10

**Comment by vjpr** [comment]
You cannot import a module you do not explicitly require.

I assume you have a file like this:

`index.ts`

```
import mz from 'mz'
```

If you want to use `mz` directly, add it to your `package.json` dependencies (`pnpm i -S mz`).

**Comment by 19majkel94** [comment]
Thank you, captain obvious! 😆 So I will explain with more details:

The problem is that when I import `fs-promise` and want to use something like `fs.writeFile()` I got an error like `Property 'writeFile' does not exist on type ...`. But it exist that fs-promise extends `fs-extra` which extends built-in fs. So I looked deep in type declaration and there is `export * from "fs-extra";` but I got this error on red:

![2017-05-04 20_01_53-index d ts - pnpm - visual studio code](https://cloud.githubusercontent.com/assets/10618781/25717975/aa90cebe-3104-11e7-825e-0b1e81bd058b.png)

Just because pnpm doesn't install all dependencies of my dependencies as I said 😉 I checked twice, there's no `@types/fs-extra` in any `node_modules` folder, while npm and yarn works like a charm.

(part of fs-promise package.json:)
```json
{
  "dependencies": {
    "any-promise": "^1.3.0",
    "fs-extra": "^2.0.0",
    "mz": "^2.6.0",
    "thenify-all": "^1.6.0"
  },
  "devDependencies": {
    "@types/fs-extra": "0.0.37",
    "@types/mz": "0.0.30",
    "mocha": "^3.0.0",
    "es6-promise": "^4.0.0",
    "rsvp": "^3.0.0",
    "bluebird": "^3.0.0",
    "when": "^3.0.0",
    "q": "^1.0.0"
  }
}

**Comment by zkochan** [comment]
`@types/fs-extra` should be a regular dependency in the `fs-promise` package.json, not a dev dependency. See https://github.com/Microsoft/types-publisher/issues/81

**Comment by vjpr** [comment]
This shouldn't work in npm or yarn either should it? `devDependencies` should only be installed for the top-level dep.

**Comment by 19majkel94** [comment]
> Just tried with npm3 and yarn. Same issue. You must have something else in your package.json file that has a regular dependency of @types/fs-extra. It would be accessible because npm3 flattens the node_modules - but technically it shouldn't be accessible.

That makes sense but I searched and only `fs-promise` requires `@types/fs-extra`. It worked before because I had the earlier version before the "fix": https://github.com/kevinbeaty/fs-promise/commit/90fd3d42d4b48a88fa46c69f03825534e7c791e2
The problem should be gone with moving to `@types/fs-extra 3.0.0`, I will check that later. So closing the issue as it works as intended 😉

**Comment by eklenin** [comment]
> You cannot import a module that you do not include in your package.json file.
> 
> I assume you have a file like this:
> 
> `index.ts`
> 
> ```
> import mz from 'mz'
> ```
> 
> If you want to use `mz` directly, add it to your `package.json` dependencies (`pnpm i -S mz`).

This is basically the only thing that keeps me from switching from npm to pnpm. Unfortunately, in some enterprise projects adding new dependencies is almost impossible task. Even updating something from `x.x.1` to `x.x.2` may take months of discussion resulting MR being rejected in the end, because no one wants to take a risk.

I know, importing things "from the void" is a bad practice, I agree 100%, but what option is it leaves for people who have no control over dependencies in their projects? This is a lot of people. And not all of them works with nice and shiny codebases, some have to deal with legacy code.

My opinion, this thing `You cannot import a module that you do not include in your package.json file.` prevents pnpm to be drop-in replacement for npm, and it would be nice to at least have opt-out option for this.

**Comment by zkochan** [comment]
You are not adding a new dependency as it is already a dependency of a dependency.
