### ISSUE TITLE
pnpm randomly chooses between registry version and equivalent fork when resolving workspace dependencies

### ISSUE THREAD

**Issue by stevenpetryk** [pnpm/pnpm#7393]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.11.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/stevenpetryk/pnpm-nondeterminism-example

### Reproduction steps

Reproduction steps are specified in the linked repo's README.

### Describe the Bug

When some projects in a monorepo depend on a fork (e.g. `"eslint": "github:discord/eslint"`) and some depend on a registry version (e.g. `"eslint": "8.52.0"`), and the fork's version _matches_ the registry version (which is the case with `discord/eslint`), pnpm cannot/does not distinguish between the two, and randomly selects one when generating the lockfile, leading to a frequent diff that looks like this:

```diff
  /@eslint-community/eslint-utils@4.4.0(eslint@8.52.0):
    resolution: {integrity: sha512-1/sA4dwrzBAyeUoQ6oxahHKmrZvsnLCg4RfxW3ZFGGmQkSNQPFNLV9CUEFQP1x9EYXHTo5p6xdhZM1Ne9p/AfA==}
    engines: {node: ^12.22.0 || ^14.17.0 || >=16.0.0}
    peerDependencies:
      eslint: ^6.0.0 || ^7.0.0 || >=8.0.0
    dependencies:
-     eslint: 8.52.0
+     eslint: github.com/discord/eslint/485ec7d08ed2040c292f52bf9b9152f6c8ef4809
      eslint-visitor-keys: 3.4.3
    dev: false
```

Or, sometimes, the inverse:

```diff
  /@eslint-community/eslint-utils@4.4.0(eslint@8.52.0):
    resolution: {integrity: sha512-1/sA4dwrzBAyeUoQ6oxahHKmrZvsnLCg4RfxW3ZFGGmQkSNQPFNLV9CUEFQP1x9EYXHTo5p6xdhZM1Ne9p/AfA==}
    engines: {node: ^12.22.0 || ^14.17.0 || >=16.0.0}
    peerDependencies:
      eslint: ^6.0.0 || ^7.0.0 || >=8.0.0
    dependencies:
-     eslint: github.com/discord/eslint/485ec7d08ed2040c292f52bf9b9152f6c8ef4809
+     eslint: 8.52.0
      eslint-visitor-keys: 3.4.3
    dev: false
```

This is troublesome because it causes a diff to `pnpm-lock.yaml` after a fresh pull from `main`.

These small changes do not trigger a failure when using `pnpm install --frozen-lockfile`, which is convenient at least :)

### Expected Behavior

I _believe_ the expected behavior would be that pnpm would create two instances of the affected dependency, providing one with the forked version of eslint and one with the registry version. Something like (diff used for emphasis):

```diff
+ /@eslint-community/eslint-utils@4.4.0(eslint@8.52.0):
    resolution: {integrity: sha512-1/sA4dwrzBAyeUoQ6oxahHKmrZvsnLCg4RfxW3ZFGGmQkSNQPFNLV9CUEFQP1x9EYXHTo5p6xdhZM1Ne9p/AfA==}
    engines: {node: ^12.22.0 || ^14.17.0 || >=16.0.0}
    peerDependencies:
      eslint: ^6.0.0 || ^7.0.0 || >=8.0.0
    dependencies:
+     eslint: 8.52.0
      eslint-visitor-keys: 3.4.3
    dev: false


+ /@eslint-community/eslint-utils@4.4.0(eslint@github.com/discord/eslint/485ec7d08ed2040c292f52bf9b9152f6c8ef4809):
    resolution: {integrity: sha512-1/sA4dwrzBAyeUoQ6oxahHKmrZvsnLCg4RfxW3ZFGGmQkSNQPFNLV9CUEFQP1x9EYXHTo5p6xdhZM1Ne9p/AfA==}
    engines: {node: ^12.22.0 || ^14.17.0 || >=16.0.0}
    peerDependencies:
      eslint: ^6.0.0 || ^7.0.0 || >=8.0.0
    dependencies:
+     eslint: github.com/discord/eslint/485ec7d08ed2040c292f52bf9b9152f6c8ef4809
      eslint-visitor-keys: 3.4.3
    dev: false
```

This feels like the correct solution to fully satisfy both `a` and `b` in the reproduction repo. However, at a bare minimum, pnpm should at least deterministically pick one option.

### Which Node.js version are you using?

20.6.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 22.04

**Comment by stevenpetryk** [comment]
Video of the behavior in action:

https://github.com/pnpm/pnpm/assets/1724000/7d51370b-8f6f-4a83-a44e-e8d652b9526b

**Comment by jamieeeeeeeee** [comment]
+1

**Comment by jamieeeeeeeee** [comment]
+1

**Comment by jamieeeeeeeee** [comment]
+1

**Comment by jamieeeeeeeee** [comment]
oh sorry meant to use my alts

**Comment by stevenpetryk** [comment]
@zkochan can confirm this is fixed in the reproduction repo with pnpm's latest main, almost certainly because of #7606.
