### ISSUE TITLE
pnpm is hard to type, it only uses one hand.

### ISSUE THREAD

**Issue by MattFoley** [pnpm/pnpm#7395]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Type pnpm in any qwerty keyboard.

### Describe the Bug

My pinky hurts.

### Expected Behavior

My pinky should not hurt.

### Which Node.js version are you using?

any

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Creat an alias if you want: https://pnpm.io/installation#using-a-shorter-alias
