### ISSUE TITLE
pnpm publish vs npm publish produces different shasums... why?

### ISSUE THREAD

**Issue by philkunz** [pnpm/pnpm#7397]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

latest

### Reproduction steps

Make a package, commit it publish it once with npm and then once with pnpm. (You can use different registries for that, if you want to avoid an error, however the package step is run either way.)

### Describe the Bug

pnpm publish vs npm publish produces different shasums... why?

### Expected Behavior

produce same shasum.

### Which Node.js version are you using?

21.4.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

ubuntu

**Comment by KSXGitHub** [comment]
Anyway, if you want to get the checksum for other purposes, you can run `pnpm pack` to create a local tarball and get checksum from that.

**Comment by zkochan** [comment]
Why is this an issue at all?

**Comment by philkunz** [comment]
Because it should not happen in my opinion. I can publish a pnpm project with npm all right. I just call npm publish. There is no reason why npm publish should produce another tar than pnpm publish in my opinion. pnpm should not put anything in the package.json that is then changed during publication.

**Comment by zkochan** [comment]
I am sorry to disappoint you but I don't see any issue with this. In theory we could produce the same shasums in most cases but I don't see any issues in the current behaviour. It is definitely not a bug as the published packages are valid and are installed without any issues using any npm client.

**Comment by philkunz** [comment]
fair enough.
