### ISSUE TITLE
when `Filtering no matching`, exit code may be not 0?

### ISSUE THREAD

**Issue by hxsf** [pnpm/pnpm#7403]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

`pnpm --filter "$wrong_name" "$any_entry"`
it will print `No projects matched the filters in xxxxx` but exit code is 0. 

### Describe the Bug

when use pnpm Filtering (No projects matched) in some script/dockerfile will not make workflow failed.

### Expected Behavior

exit code !== 0

### Which Node.js version are you using?

v21.3.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
I don't think it should fail. Why should it? You can filter for instance by changed packages, if now packages were changed, it is OK that nothing is found.

**Comment by hxsf** [comment]
> I don't think it should fail. Why should it? You can filter for instance by changed packages, if now packages were changed, it is OK that nothing is found.

Oh, I forgot that. In my case, some typo or workflow script will run pnpm --filter "$wrong_package_name" (yes, I use it in pnpm workspace).

So, maybe we can add an option look like `--filter "xxxxx" --fail` like `curl --fail` ?

**Comment by zkochan** [comment]
The option sounds good to me.
