### ISSUE TITLE
Make `pnpm install` faster with blank `node_modules` dir

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#742]
When all modules are available in the store, this is the breakdown of time I see from the log messages with `reporter=ndjson`.

All dependencies are installed and linked within 9s which is great for 100s of modules and 400MB `node_modules` size.

However, there appears to be some delay afterwards, and there are not logging messages to determine what is happening.

| duration |                                        |
|----------|----------------------------------------|
|          | started                                |
| 8933     | last dependencies_installed message             |
| 12466    | first warning printed about peers      |
| 25048    | last warning printed about peers |
| 224      | first installed message                             |
| 46671    |                                        |

1. What could these delays be? (12s and 25s from above) - I guess something with resolving peers.
2. Can we add logging messages to provide progress on the delays.

**Comment by vjpr** [comment]
After adding some logging to the code, it looks like the linking is taking most of the time.

`await installMultiple` = 9s
`await linkPackages` = 37s

**Comment by vjpr** [comment]
![screen shot 2017-05-03 at 1 52 57 pm](https://cloud.githubusercontent.com/assets/281413/25659389/d81192a4-3007-11e7-9be0-65c98047c4bd.png)

`createTree` method is taking all the time.

![screen shot 2017-05-03 at 1 55 20 pm](https://cloud.githubusercontent.com/assets/281413/25659456/2ce36c80-3008-11e7-93d0-57344b8724e5.png)

**Comment by vjpr** [comment]
![screen shot 2017-05-03 at 2 12 33 pm](https://cloud.githubusercontent.com/assets/281413/25660007/9716f750-300a-11e7-959a-2d0721c3b001.png)

I'm not a fan of functional for this reason...very hard to performance debug without diving into the complex code of the functional lib in use.

**Comment by iamstarkov** [comment]
nice investigation

**Comment by vjpr** [comment]
So `merge` seems to be the issue. Using `reduce` with `merge`, ends up copying ~40K properties from one object and ~2 from another object into a new object. The merge command in ramda is as follows:

```
module.exports = _curry2(function merge(l, r) {
  return _assign({}, l, r);
  //return _assign(l, r); <- much faster
});
```

By being mutable, we save a heap of time.

**Comment by zkochan** [comment]
We did this one
