### ISSUE TITLE
registry-scoped cert and key options

### ISSUE THREAD

**Issue by starnayuta** [pnpm/pnpm#7427]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

It is only possible to set `cert` and `key` at the top level and not in the registry of a specific scope for mTLS and client authentication.

It is possible to set registry-scoped certfiles and keyfiles with npm, but not with pnpm.

- https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#auth-related-configuration
- https://github.com/npm/npm-registry-fetch/issues/118

### Describe the solution you'd like

Add support for registry-scoped `cert` and `key` options.

Note that the [certfile](https://pnpm.io/npmrc#cert) and [keyfile](https://pnpm.io/npmrc#key) options do not exist in pnpm, so it is not possible to use the same strategies as in npm.

### Describe the drawbacks of your solution

Since client authentication is not popular, this feature is not used in most cases.

### Describe alternatives you've considered

None

**Comment by zkochan** [comment]
Sounds good. We should implement this.
