### ISSUE TITLE
Install PNPM error when mismatch latest version between npm registry & GitHub releases

### ISSUE THREAD

**Issue by ntheanh201** [pnpm/pnpm#7428]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Reproduction steps

Install PNPM error: "pnpm version '8.13.0' could not be found"
when mismatch version between NPM registry & GitHub releases.
The latest version at NPM is: 8.13.0
The latest version at GitHub release is: 8.12.1

### Describe the Bug

In the install.sh file, the latest version is get from https://registry.npmjs.org/@pnpm/exe, for now it's: 8.13.0
But the archive_url is using GitHub releases to download PNPM, the latest version is: 8.12.1

### Expected Behavior

Can install PNPM

### Which Node.js version are you using?

16

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

**Comment by ntheanh201** [comment]
<img width="854" alt="image" src="https://github.com/pnpm/pnpm/assets/29043139/1b35edc2-c9bf-4fa6-bd48-dfa5b5048d2e">

**Comment by kamilk91** [comment]
Its always friday evening guys

**Comment by ntheanh201** [comment]
> Its always friday evening guys

it happens to me from yesterday
