### ISSUE TITLE
Add `tsc` as devDependency

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#743]
`tsc` should be a devDependency. Currently it must be globally installed to build pnpm. I also noticed that the `tsc` module is deprecated.

**Comment by zkochan** [comment]
But we have typescript in dev deps and tsc is a bin of typescript https://github.com/Microsoft/TypeScript/blob/master/bin/tsc

**Comment by vjpr** [comment]
Ah okay, no problem.
