### ISSUE TITLE
`pnpm up -r --latest` overrides alpha versions that are not yet tagged as latest

### ISSUE THREAD

**Issue by cpojer** [pnpm/pnpm#7436]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.12.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, CLI

### Reproduction steps

I'm currently using Prettier's experimental v4 version via:

```
"devDependencies": {
	"prettier": "4.0.0-alpha.7"
}
```

When I run `pnpm up -r --latest` to upgrade all packages, it will revert prettier to the `latest` stable version of `3.11`.

### Describe the Bug

The existing behavior is technically correct as I'm asking pnpm to upgrade to `latest`, but it's unlikely that it matches the user intent as they likely want to update everything else to latest except such experimental packages unless there is a newer version of the experimental package or the latest version of the package has moved on to be "above" (semver) the current experimental package.

### Expected Behavior

I expect prettier to stay upgraded to major version `4` even if the latest version is `3`.

### Which Node.js version are you using?

21.4.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
The offending line is here: https://github.com/pnpm/pnpm/blob/ee61ca4cb7ce6b3cb177f892940edb55b19b9e17/pkg-manager/plugin-commands-installation/src/updateToLatestSpecsFromManifest.ts#L14

In short, pnpm will append `@latest` if it sees `--latest`. This is crude, but fast. I can make it more accurate by fetching information from the registry before deciding whether to push it to the arguments, but it will be slower. What are your thought on this, @cpojer, @zkochan?

**Comment by zkochan** [comment]
@KSXGitHub a better solution could be to pass a new option down to the `@pnpm/package-requester`. Something like `updateIfNewer`. Then if the newly resolved version is lower than the already existing one, keep the existing one.

Related code: https://github.com/pnpm/pnpm/blob/33313d2fd0b9fa5b74532b2ef3f8a35b3679699d/pkg-manager/package-requester/src/packageRequester.ts#L203

**Comment by KSXGitHub** [comment]
I think the reasonable expectation should be that `--latest` doesn't downgrade packages. Though it is just my opinion. Can you make a poll to ask the community about it?

**Comment by zkochan** [comment]
I have the same opinion. Isn't that what I proposed in my message? I don't think a poll is needed.

**Comment by KSXGitHub** [comment]
@zkochan I thought you were suggesting adding another CLI flag.

**Comment by zkochan** [comment]
No, I was suggesting adding a new option to `requestPackage`, that is set to `true`, when `--latest` is used.
