### ISSUE TITLE
packages versions no same between `pnpm install` and `pnpm view versions`

### ISSUE THREAD

**Issue by Lionad-Morotar** [pnpm/pnpm#7442]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.12.1

### Reproduction steps

![image](https://github.com/pnpm/pnpm/assets/26913795/12e00d94-36f5-4c6d-9adc-1181acb79552)

* npm version: 9.6.7
* node version: v18.17.0

### Describe the Bug

and I have `.npmrc` file in my project, `registry` is correctly settled

propabably not a bug, but a question :///

### Expected Behavior

latest version of `pnpm install xxx@a` consist with latest version of `pnpm view xxx versions`

### Which Node.js version are you using?

18.17.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
registry.npmmirror.com has `use-scollbars@0.4.11` now, so the bug can no longer be reproduced.

If I have to guess, it was probably cause by a combination of 3 factors:
1. `pnpm` does not have its own `view` command, what it does is call `npm view`.
2. `npm view` does not accept `--registry` flag, it will ignore unknown flag instead of error.
3. registry.npmmirror.com didn't pull the latest version of `use-scrollbars` fast enough, so for a moment, 0.4.11 exists in the main registry but not the mirror.

**Comment by Lionad-Morotar** [comment]
> registry.npmmirror.com has `use-scollbars@0.4.11` now, so the bug can no longer be reproduced.
> 
> If I have to guess, it was probably cause by a combination of 3 factors:
> 
> 1. `pnpm` does not have its own `view` command, what it does is call `npm view`.
> 2. `npm view` does not accept `--registry` flag, it will ignore unknown flag instead of error.
> 3. registry.npmmirror.com didn't pull the latest version of `use-scrollbars` fast enough, so for a moment, 0.4.11 exists in the main registry but not the mirror.

Thanks, I understand what you're saying about `pnpm view` perhaps rolling back the problems that using `npm view` might cause, but the problem I was trying to indicate is that the versions of the packages installed in the `pnpm view` and `pnpm install` commands are not the same. If `pnpm view` can follow the registry (.npmrc or the registry parameter on the command line) to get the latest package version, then `pnpm install` should be able to follow the registry to find the latest version of the package.

I'm guessing it's probably a cache of requests initiated by `pnpm install`.

Translated with DeepL.com (free version)

**Comment by Lionad-Morotar** [comment]
Probably `pnpm install` didnt respect `--registry` cames from input:

1. I set registry RA in .npmrc
2. pnpm view follow RA
3. pnpm view follow RA cames from shell input
4. pnpm install didnt follow RA, since test-publish-time@0.0.13 not found in RA, so pnpm install failed

![image](https://github.com/pnpm/pnpm/assets/26913795/ded239d2-8907-42a5-bb21-a47dd218f553)

**Comment by KSXGitHub** [comment]
Fixing this requires pnpm to stop relying on `npm view` and implement its own `view` command as npm itself doesn't respect pnpm configuration.
