### ISSUE TITLE
Inconsistent lockfile changes on repeat installs

### ISSUE THREAD

**Issue by alex-statsig** [pnpm/pnpm#7444]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

7.33.5 (latest-7), as well as 7.32.4 and 7.28.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Reproduction steps

Hard to create a consistent repro, it occurs with a large project. One example dependency which triggers it is `jest-config@29.6.1(@types/node@16.11.58)(ts-node@10.9.1)`. It seems the peer version of @types/node changes across installs.

### Describe the Bug

Repeat installs cause several inconsistent changes to the lockfile:
1. "dev: true" flag disappears and reappears
2. Version of peer @types/node (using new lockfile format) within ts-node changes:

Ex. on one install I get the following lockfile section:
```
  /jest-config@29.6.1(@types/node@16.11.58)(ts-node@10.9.1):
    resolution: {integrity: sha512-XdjYV2fy2xYixUiV2Wc54t3Z4oxYPAELUzWnV6+mcbq0rh742X2p52pii5A3oeRzYjLnQxCsZmp0qpI6klE2cQ==}
    engines: {node: ^14.15.0 || ^16.10.0 || >=18.0.0}
    peerDependencies:
      '@types/node': '*'
      ts-node: '>=9.0.0'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      ts-node:
        optional: true
    dependencies:
      '@babel/core': 7.19.0
      '@jest/test-sequencer': 29.6.1
      '@jest/types': 29.6.1
      '@types/node': 16.11.58
      babel-jest: 29.6.1(@babel/core@7.19.0)
...
      ts-node: 10.9.1(@types/node@16.11.22)(typescript@4.8.4)
    transitivePeerDependencies:
      - supports-color
```
On another install, I get the following:

```
  /jest-config@29.6.1(@types/node@16.11.58)(ts-node@10.9.1):
    resolution: {integrity: sha512-XdjYV2fy2xYixUiV2Wc54t3Z4oxYPAELUzWnV6+mcbq0rh742X2p52pii5A3oeRzYjLnQxCsZmp0qpI6klE2cQ==}
    engines: {node: ^14.15.0 || ^16.10.0 || >=18.0.0}
    peerDependencies:
      '@types/node': '*'
      ts-node: '>=9.0.0'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      ts-node:
        optional: true
    dependencies:
      '@babel/core': 7.19.0
      '@jest/test-sequencer': 29.6.1
      '@jest/types': 29.6.1
      '@types/node': 16.11.58
      babel-jest: 29.6.1(@babel/core@7.19.0)
...
      ts-node: 10.9.1(@types/node@16.9.2)(typescript@4.8.4)
    transitivePeerDependencies:
      - supports-color
```

The only difference is `ts-node: 10.9.1(@types/node@16.11.22)(typescript@4.8.4)` changing to `ts-node: 10.9.1(@types/node@16.9.2)(typescript@4.8.4)`

### Expected Behavior

Lockfile should not change for a consistent version of pnpm. This causes lots of pain with merge conflicts as the lockfile thrashes back and forth in many PRs.

### Which Node.js version are you using?

v16.17.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
@stevenpetryk are these the same issues that you were looking into?

**Comment by stevenpetryk** [comment]
@zkochan we have observed the exact same two things (`dev: true` disappearing/reappearing as well as `@types/node` resolution changing in particular), but I'm not sure if it's the same issue as #7393 because we have not been able to reproduce the issue using the same strategy (or really reproduce it at all outside of the `discord` monorepo).

My hypothesis with all three behaviors is that they're some sort of race condition during resolution, but I haven't spent any time debugging yet.

**Comment by zkochan** [comment]
I can reproduce one issue with `@types/node` on the pnpm repository. If I update `@rushstack/worker-pool`, `@types/node` is removed from the package key in the lockfile 

<img width="1086" alt="image" src="https://github.com/pnpm/pnpm/assets/1927579/02b4f523-bfe7-47b6-a1ba-9e4b48cb5169">

**Comment by zkochan** [comment]
@alex-statsig in any case, you should upgrade to pnpm v8. We only ship security patches to pnpm v7.

**Comment by alex-statsig** [comment]
> @alex-statsig in any case, you should upgrade to pnpm v8. We only ship security patches to pnpm v7.

Thanks, we are working on it but just having some trouble keeping versions pinned during the upgrade (some typescript errors introduced, mostly from mui, which doesn't seem correct)

**Comment by KSXGitHub** [comment]
@alex-statsig Can you give me access to your large project? I only need the `package.json`, the lockfile, and other the configuration files that are relevant to pnpm.

**Comment by alex-statsig** [comment]
Sure, the repo as a whole is private; what's a good way to send you those files?

**Comment by KSXGitHub** [comment]
I only need the pnpm related files (like `package.json`, `.npmrc`, `pnpm-workspace.yaml`, etc). Are you allow to remove all your code except for these files then publish it to a public repo?

**Comment by jgao54** [comment]
We are also observing this with v7.33.6 in a large monorepo.

Seeing inconsistency in @types/node and ts-node, but also other dependencies as well.

**Comment by zkochan** [comment]
Oh, this is a complex scenario. `ts-node` is an optional peer dependency and it depends on another optional peer dependency. As a workaround, you can try to set [dedupe-peer-dependents](https://pnpm.io/npmrc#dedupe-peer-dependents) to `false`.

**Comment by zkochan** [comment]
After all, I don't think changing `dedupe-peer-dependents` will help. I am working on a fix.

**Comment by zkochan** [comment]
Unfortunately this one will be hard to fix. The peers resolution algorithm will have to go through some heavy refactoring. And this will be a breaking change. But it is important to fix it. I will try to do it in v9.

This happens when peer dependencies have peer dependencies of its own. I thought I have fixed it in #7583 but no, the problem requires a much bigger rewrite.

**Comment by zkochan** [comment]
The fix is ready for review: https://github.com/pnpm/pnpm/pull/7606

**Comment by zkochan** [comment]
:ship: [9.0.0-alpha.3](https://github.com/pnpm/pnpm/releases/tag/v9.0.0-alpha.3).
