### ISSUE TITLE
Your lockfile versions are mismatched, i confirmed that this is a bug on your end.

### ISSUE THREAD

**Issue by mjmcgrath2010** [pnpm/pnpm#7448]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

im on 8.12.1 but its generating lock files for 6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Lockfile, Store, Package manager compatibility, Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

message me if i need to show you whats broken :)

### Reproduction steps

```
 ~/Development/gl-link-in-bio   master ±  pnpm -v            
8.12.1
```

Now run `pnpm install` 

I've tried uninstalling, deleting the system files at ~/.volta or where ever, and it doesnt work. If you can commit to getting this work verified and ready for me to fix i can help, otherwise gotta move back to yarn/npm never had issues there

### Describe the Bug

TRY YOUR CODE BEFORE YOU DEPLOY

### Expected Behavior

That when a version is release such a mindless oversight doesn't occur, and when it does, it should be fix ASAP . looking through issues this isnt the first time. lmk if u need help understandig your code bugs.

### Which Node.js version are you using?

all avalible distros

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

ur shits broke

**Comment by mjmcgrath2010** [comment]
![image](https://github.com/pnpm/pnpm/assets/11398931/47797fd3-112b-436e-b75d-f4d9b86caa22)

**Comment by mjmcgrath2010** [comment]
lmk if you geniuses need more info

**Comment by mjmcgrath2010** [comment]
i found the issue, but its buts you havent. tell you what, fix it by 3pm EST and i'll sponsor you guys in hopes you improve.

otherwise theres some great alternatives out there that are much more battle tested, versitle, and are maintained to the exected standard that one would take on such an endeavor.

<img width="771" alt="Screenshot 2023-12-20 at 10 49 48 AM" src="https://github.com/pnpm/pnpm/assets/11398931/a130de78-3548-4756-9460-a5da477deec3">


For those who don't wanna wait, simply go to NPM its gotten way better than yarn and you wont have to deal with people who pretend to help the community.

Other alternatives for quickly quicking tooling versions are NVM of course, but checkout ASDF - its much more robust battle tested, there team also does care about the people who consume their code unlike these fools getting issues every 2 days

**Comment by KSXGitHub** [comment]
First, rude!

Second, you are confused:

> im on 8.12.1 but its generating lock files for 6

The lockfile version is not pnpm version. The lockfile version is just the version of its spec (there are currently 6 in total). Lockfile version is bumped only when the spec of the lockfile changes, which is less frequent than the pnpm program.

Third, regarding the error, it was caused by incompatible engine. Your screenshot doesn't show me what's incompatible, so it's hard to judge. Do you have a `package.json`?

**Comment by zkochan** [comment]
This person has been blocked from the organization. We didn't receive enough details to investigate the issue. If anyone has the same issue and can provide us with more details, please create a new issue. This issue is going to be locked.
