### ISSUE TITLE
Unable to upgrade pnpm 

### ISSUE THREAD

**Issue by Wizzel1** [pnpm/pnpm#7449]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

8.8.0

### Reproduction steps

Install pnpm via npm
Try to update pnpm with `npm i -g pnpm@latest` or `npm i -g pnpm@8.12.1` 

### Describe the Bug

For some reason I can't update my pnpm. I have initially installed it via npm.
The cmd has been run with admin rights.
![Unbenannt](https://github.com/pnpm/pnpm/assets/43343510/99d33e87-dd9e-4865-bc9e-506eaec2c223)
![Unbenannt](https://github.com/pnpm/pnpm/assets/43343510/e1427569-90a2-4ab8-acab-1d3ae67e6b75)

### Expected Behavior

I expected to get the latest version 

### Which Node.js version are you using?

v20.10.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by zkochan** [comment]
If you only used npm to install and update pnpm, then it must be an issue with npm. You can try to manually remove pnpm: https://pnpm.io/installation#troubleshooting. The try to reinstall it with npm or with another method. Corepack is a better choice to install pnpm.

**Comment by Wizzel1** [comment]
Yes I removed I manually and installed it again and it worked. Thanks
