### ISSUE TITLE
If `pnpm i` fails to finish or is terminated early, running `pnpm i` again results in missing files

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#746]
The only solution is clearing `node_modules`. 

There should be some mechanism to make the stages/modules of the install atomic, so when a second `pnpm i` command is run, it can see which stages/modules didn't install correctly and ensure they are installed.

The goal should be that `pnpm i` will always result in the same tree regardless of the original `node_modules` dir structure.

### Additional information:

 - `node -v` prints: 6.5.0
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
Also related to this one is #841

**Comment by zkochan** [comment]
I don't think this is an issue anymore
