### ISSUE TITLE
Issue installing dependencies via Node.js child process

### ISSUE THREAD

**Issue by WhitigolProd** [pnpm/pnpm#7463]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.12.1

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/WhitigolProd/SnailyCAD-Manager/blob/c621360f4297efe9e0645379cb5d0ba7648d038c/src/scripts/utils/api/api.ts#L111C1-L111C1

### Reproduction steps

In the provided repo, run `npm run dev`, then run through the installation steps. It will appear as if everything was done correctly, but then when you click the Start button in the dashboard, it fails to locate dependencies, resulting in the start failing.

### Describe the Bug

With the child process, during it's steps, I run `pnpm install --force` (using the `--force` flag in hopes that it would fix the issue, didn't). After it's all said and done, according to the logs, it would look like everything was installed correctly to an end-user, however it does not install all dependencies as expected, resulting in running the start command not working.

### Expected Behavior

When running `pnpm install` in a child process, I would expect it to behave as if it were ran in a standalone terminal, however this is not the case.

What could be causing this? What are some steps I can take to resolve? Is this a known bug?

### Which Node.js version are you using?

18.17.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by WhitigolProd** [comment]
Bump with additional context:

I've also attempted to use `--config.confirmModulesPurge=false`, but this still does not result in all dependencies installed as if it were done manually through the command line.

**Comment by KSXGitHub** [comment]
Can you check if your environment has any variables whose name contain `npm` (uppercase and lowercase) before the child process is executed?

```javascript
console.log(
  Object
    .entries(process.env)
    .filter(([x]) => x.toLowerCase().includes('npm'))
)
```

**Comment by KSXGitHub** [comment]
Also, what is the error message? Can you make a minimal repro?

**Comment by WhitigolProd** [comment]
Just figured out last night a fix. Setting `--prod=false` installs the dependencies as intended.
