### ISSUE TITLE
[Docs] using the file: protocol can not reflect the changes until Run pnpm install everytime

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [pnpm/pnpm#7465]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

8.13.1

### Link to the code that reproduces this issue or a replay of the bug

https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol

### Reproduction steps

In [What's the difference between pnpm link and using the file: protocol?](https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol) 

<img width="775" alt="image" src="https://github.com/pnpm/pnpm/assets/26433572/1c90d72c-a246-4126-8680-3f8a9efbbbfe">

This may cause misunderstandings among readers that using the file: protocol can reflect the changes and no need to  Run pnpm install everytime，IT's WRONG：https://github.com/pnpm/pnpm/issues/6804#issuecomment-1638634063

### Describe the Bug

1

### Expected Behavior

I hope the documentation explains it more clearly that use pnpm link no need to run pnpm install everytime that a rebuild is done, BUT using the file: protocol is NEED TO run pnpm install everytime that a rebuild is done.

thanks！

### Which Node.js version are you using?

v16.15.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nachoaldamav** [comment]
Hi, do you have a reproduction for this? I tried myself and the changes are reflected without running `pnpm i`

https://github.com/pnpm/pnpm/assets/22749943/9c1a0380-8209-4986-93a6-eee87cb1b439

**Comment by AttackXiaoJinJin** [comment]
> Hi, do you have a reproduction for this? I tried myself and the changes are reflected without running `pnpm i`
> 
>  Grabacion.2024-01-03.130820.1.mp4

@nachoaldamav  Sorry, I misunderstood pnpm. It is actually a problem with Vite's pre-build：https://github.com/vitejs/vite/issues/8619. If the local package is modified and then packaged, Vite will read the pre-built cache content instead of re-executing the pre-build.

thank you for your reply！！
