### ISSUE TITLE
`pnpm upgrade --latest` doesn't consider `alpha` & `beta` as latest but `pnpm outdated` doesn't show latest either

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#7467]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.13.1

### Reproduction steps

install `@headlessui/react@alpha` in a project.

then use `pnpm outdated` to see it doesn't show anything about `@headlessui/react`

but if you do `pnpm upgrade --latest`, it upgrades the alpha to latest.

### Describe the Bug

i have installed `@headlessui/react@2.0.0-alpha.3` using the command:

```bash
pnpm i @headlessui/react@alpha
```

but when i do:

```bash
pnpm upgrade --latest
```

it installs the latest version instead of `alpha`:

```bash
dependencies:
- @headlessui/react 2.0.0-alpha.3
+ @headlessui/react 1.7.17
```

however, when calling the outdated cli using:

```bash
pnpm outdated
```

it shows:

```
┌───────────────────────────────────┬─────────┬─────────┐
│ Package                           │ Current │ Latest  │
├───────────────────────────────────┼─────────┼─────────┤
│ @types/react (dev)                │ 18.2.45 │ 18.2.46 │
├───────────────────────────────────┼─────────┼─────────┤
│ pino-pretty                       │ 10.3.0  │ 10.3.1  │
├───────────────────────────────────┼─────────┼─────────┤
│ jsx-email                         │ 1.5.3   │ 1.6.0   │
├───────────────────────────────────┼─────────┼─────────┤
│ drizzle-kit (dev)                 │ 0.20.8  │ 0.20.9  │
├───────────────────────────────────┼─────────┼─────────┤
│ prettier-plugin-tailwindcss (dev) │ 0.5.9   │ 0.5.10  │
└───────────────────────────────────┴─────────┴─────────┘
```

which doesn't include `@headlessui/react` at all.

very inconsistent behavior.

### Expected Behavior

at least want it to be consistent but would love if i can skip latest version for `@headlessui/react` someway as the latest version gives error while alpha doesn't.

### Which Node.js version are you using?

v21.3.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by deadcoder0904** [comment]
funny thing is `pnpm up -i` didn't include `@headlessui/react` at all which is again inconsistent behavior.

**Comment by rozbo** [comment]
+1

**Comment by zkochan** [comment]
This was fixed by https://github.com/pnpm/pnpm/pull/7466

**Comment by deadcoder0904** [comment]
can confirm it works from v8.15.0.

`pnpm outdated` showed beta packages:

┌─────────────────────────────┬───────────────┬─────────┐
│ Package                     │ Current       │ Latest  │
├─────────────────────────────┼───────────────┼─────────┤
│ @types/node                 │ 20.11.7       │ 20.11.8 │
├─────────────────────────────┼───────────────┼─────────┤
│ @lucia-auth/adapter-drizzle │ 1.0.0-beta.7  │ 1.0.0   │
├─────────────────────────────┼───────────────┼─────────┤
│ lucia                       │ 3.0.0-beta.15 │ 3.0.0   │
└─────────────────────────────┴───────────────┴─────────┘

and after that i did `pnpm up --latest` & it updated to the latest ones showed above.

i guess to keep using alpha/beta version i'll have to do `pnpm up -i`

**Comment by enjikaka** [comment]
Did https://github.com/pnpm/pnpm/pull/7466 introduce this bug I see maybe?

When I install `pnpm add jsr:@enjikaka/webact` it installs the beta version of webact intead of the stable release without `-beta`.
