### ISSUE TITLE
pnpm init -y doesn't pass arg to npm

### ISSUE THREAD

**Issue by SteveALee** [pnpm/pnpm#747]
### pnpm version:

latest

### Code to reproduce the issue:

`pnpm init -y`

### Expected behavior:

npm creates a package.json without any prompting

### Actual behavior:

promts for fields
 
### Additional information:

I guess args are not always getting passed through to npm with commands?

**Comment by zkochan** [comment]
Thanks. This is a regression. It was broken when we started using nopt. Easy to fix.

**Comment by zkochan** [comment]
Landed in [v0.66.3](https://github.com/pnpm/pnpm/releases/tag/v0.66.3)
