### ISSUE TITLE
Optional `peerDependencies`/`devDependencies` mistakenly recorded as a `dependencies` and unexpectedly getting installed

### ISSUE THREAD

**Issue by joulev** [pnpm/pnpm#7474]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.13.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

```json
{
  "dependencies": {
    "drizzle-orm": "0.29.2"
  }
}
```

Run `pnpm install`.

### Describe the Bug

After running it, inspecting the lock file shows a lot of other packages installed as well. Of which there is this

```yaml
/drizzle-orm@0.29.2(@types/react@18.2.46)(expo-sqlite@13.2.0)(react@18.2.0):
  resolution: {integrity: sha512-BhwCwuSQqUoLVc7wtgIkuWexY127Z9+yDbuXU7QWZbMC2XE48jecvAThW9apQaDoaxQmwQ+ObyPfPb4zL4Bgsw==}
  peerDependencies: [...]
  peerDependenciesMeta: [...]
  dependencies:
    '@types/react': 18.2.46
    expo-sqlite: 13.2.0(expo@49.0.21)
    react: 18.2.0
  dev: false
```

which shows that `@types/react`, `expo-sqlite` and `react` are found to be dependent of `drizzle-orm`. But according to [`package.json` of the package](https://www.npmjs.com/package/drizzle-orm?activeTab=code), these are only optional `peerDependencies` (and `devDependencies`) rather than `dependencies`.

### Expected Behavior

I probably have some kind of misunderstanding here, but to my knowledge the expected behaviour should be that `drizzle-orm`, having no direct `dependencies` or required `peerDependencies`, should be the only package installed. Other optional `peerDependencies` or `devDependencies` should not be installed – optional `peerDependencies` should be installed separately by the developer.

In the lock file, `@types/react`, `expo-sqlite` and `react` are also listed as `dependencies`, I don't think this is the intended behaviour either, since `drizzle-orm`, once again, doesn't declare any `dependencies` in the `package.json` file.

### Which Node.js version are you using?

v21.5.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
You were looking at the 0.29.3 version of drizzle-orm. But if you check 0.29.2, you'll see that `@types/react` is a regular peer dependency and not an optional one:

https://www.npmjs.com/package/drizzle-orm/v/0.29.2?activeTab=code

**Comment by joulev** [comment]
Oh, I see, this was a Drizzle ORM bug indeed. I was careless and when looking at the `drizzle-orm@0.29.2` one, I saw everything as `optional: true` so somehow thought everything was indeed optional, not noticing there are packages that didn't have the `peerDependenciesMeta` entries.

Sorry for the false bug report and happy new year!
