### ISSUE TITLE
Can we have a usage output listing options?

### ISSUE THREAD

**Issue by SteveALee** [pnpm/pnpm#748]
I tried various combinations of `/?`, `-h`, `--help` etc but everything just goes through to npm.

For `pnpm install lodash` I found:
 
* -S is default - that was a surprise. Can it be tunred off. Though prolly never wanted might be better to copy npm? :)
* -D works fine
* --verbose does nothing
* --save-exact works

thanks

**Comment by zkochan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [`pnpm help`](https://trello.com/c/zXjNw18H/28-pnpm-help)

**Comment by zkochan** [comment]
@SteveALee published `pnpm help` in [v1.7.0](https://github.com/pnpm/pnpm/releases/tag/v1.7.0)

**Comment by vjpr** [comment]
@zkochan Needs some descriptions.

**Comment by zkochan** [comment]
@vjpr what do you mean?

**Comment by vjpr** [comment]
Currently shows:

```
pnpm help
Usage: pnpm [command] [flags]

Commands:

  - install
  - update
  - uninstall
  - link
  - dislink
  - list
  - prune
  - install-test
  - store status
  - store prune
  - root

Other commands are passed through to npm
```

The commands should have a brief description.

**Comment by zkochan** [comment]
Do you maybe know some libs that compose these helps? 

I know commander can do it but connecting huge commander just for the help command doesn't seem to be a good idea

**Comment by vjpr** [comment]
yargs is what I normally use....

**Comment by zkochan** [comment]
We have to use nopt because it parses the options in a format that is passed to npm's programmatic API. We use npm to get the configs.
