### ISSUE TITLE
pnpm doesn't run postinstall scripts of dependencies on Windows

### ISSUE THREAD

**Issue by EugeneGarbuzovPublic** [pnpm/pnpm#7482]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Package manager compatibility, Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/EugeneGarbuzovPublic/pnpm-postinstall

### Reproduction steps

On Windows:
1. `pnpm init`
2. `git init`
3. Add the following to `package.json`:
```json
"simple-git-hooks": {
  "pre-commit": "echo \"Hello, world!\""
}
```
4. `pnpm add -D simple-git-hooks`
5. Remove `node_modules`
6. `pnpm i`

### Describe the Bug

The `pre-commit` Git hook was not added. The `postinstall` script of the `simple-git-hooks` dependency was not run after `pnpm i`.
One may make sure the hook was not added by looking at `./.git/hooks` which does not contain `pre-commit` file.

At the same time in my CI environment (Jenkins) which is on Debian everything works fine: dependencies' `postinstall` scripts are run after `pnpm i`.

Please note that if on step 6 you do `npm i` instead of `pnpm i` the hook will be added (`pre-commit` file in `./.git/hooks` will be created). Which is why I believe what I have described is a bug.

### Expected Behavior

Dependency's `postinstall` script is run after `pnpm i` on Windows when there is no `node_modules`, the same way it is run in CI on Debian.

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Debian 11.5.4

**Comment by nachoaldamav** [comment]
Hi, try adding this to your `package.json`:
```json
"scripts": {
   "postinstall": "pnpx simple-git-hooks"
}
```

**Comment by EugeneGarbuzovPublic** [comment]
> Hi, try adding this to your `package.json`:
> 
> ```json
> "scripts": {
>    "postinstall": "pnpx simple-git-hooks"
> }
> ```

Hi!
Thanks, I'm aware of this method, but my example is just a small reproduction example.
In a real-life project there may be many packages with their `postinstall` scripts.
Or, for example, when I add a new dependency to my project, am I supposed to find out if the dependency has `postinstall` and am I supposed to add its `postinstall` to my `scripts` manually?
If so, that would be not so comfortable. Especially, if there is no convincing reason to do so.
npm works in a different way.
And I wonder why pnpm works the way it works.
Were there any reasons to do so or is it a bug?

**Comment by nachoaldamav** [comment]
pnpm won't run lifecycle scripts for dependencies that are already in the store, you can either use the project lifecycle scripts, or run the install with `side-effects-cache=false`, this can also be a user-wide option in the user `.npmrc`.

**Comment by EugeneGarbuzovPublic** [comment]
Hm, okay, seems like I’m going to stop at adding `side-effects-cache=false` to the project’s `.npmrc`.

But I wonder what was the decision behind adding the `side-effects-cache` option. The fact that npm and pnpm work differently here looks strange to me.
