### ISSUE TITLE
Support subfolder when installing from Git

### ISSUE THREAD

**Issue by RexSkz** [pnpm/pnpm#7483]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

PNPM now supports fetching from Git: `pnpm i git+https://host/user/repo`, and users can specify the branch, commit and tag using `#`:

```
git+https://host/user/repo#1a2b3c        // commit
git+https://host/user/repo#dev           // branch
git+https://host/user/repo#semver:^2.0.0 // tag
```

**Nowadays, we use monorepo more and more. It's great to support installing from a subfolder of a git repo, not the root of it.**

Currently, neither NPM nor Yarn supports this feature, and there's no RFC for it, so I'm not sure if it's okay for PNPM to support it. (In my own opinion, it's a good-to-have feature.)

### Describe the solution you'd like

As a reference, UPM (Unity package manager) [provides the ability to specify the subfolder](https://docs.unity3d.com/Manual/upm-git.html#paths-and-revisions) using query parameter `path`. Maybe it's a good idea to follow this syntax, e.g.:

```
git+https://host/user/repo?path=/packages/util     // install from /packages/util
git+https://host/user/repo?path=/packages/util#dev // install from /packages/util at branch dev
```

### Describe the drawbacks of your solution

It seems there are not many drawbacks to supporting queries in Git URLs. It's expected to add some logic to `git-resolver` and `git-fetcher`:

- For the resolver, there will be no compatibility issues with the existing format.
- For the fetcher, git fetcher uses a temp folder to perform clone/fetch actions and add "all" files (excluding `.git`) to store, this feature only affects the "all" word.

### Describe alternatives you've considered

There is an alternative from [StackOverflow](https://stackoverflow.com/a/39195334/17989138) that uses `git sparse-checkout`.

```json
{
  "scripts": {
    "postinstall": "mkdir BotBuilder; cd BotBuilder; git init; git remote add -f origin https://github.com/Microsoft/BotBuilder.git; git config core.sparseCheckout true; echo \"Node/core\" >> .git/info/sparse-checkout; git pull --depth=1 origin master; cd ..; npm i ./BotBuilder/Node/core/"
  },
}
```

It can't work with the current PNPM install flow; users need to execute extra scripts when installing dependencies.

**Comment by zkochan** [comment]
Are you sure this is not supported by Yarn? IIRC we already have an issue about this feature request and the author claimed that Yarn supports it.

**Comment by RexSkz** [comment]
It seems Yarn has a feature called workspace clone (from [this issue comment](https://github.com/yarnpkg/yarn/issues/1570#issuecomment-1057613201)), which can only work if the repo has Yarn workspace:

```
yarn add @name/package-name@https://github.com/user/repo#workspace=@name/package-name
```

There's nothing shown in the official docs: https://classic.yarnpkg.com/en/docs/cli/add

Do you mean that PNPM should implement a similar feature but with PNPM workspace rather than just adding a sub folder to the store?

**Comment by zkochan** [comment]
Related issue: https://github.com/pnpm/pnpm/issues/4765

also mentions workspace support by Yarn.

**Comment by RexSkz** [comment]
I see. The "workspace clone" of Yarn assumed all repos use Yarn workspace to do monorepo things.

There are cases in which I need to install something (e.g. business API typings) from a repo maintained by another team which uses Lerna (or just a sub folder). Yarn's workspace clone can't handle these cases.

**Comment by zkochan** [comment]
I have commented on the older issue: https://github.com/pnpm/pnpm/issues/4765#issuecomment-1879675650

marking this one as duplicate
