### ISSUE TITLE
A couple of issues with global packages

### ISSUE THREAD

**Issue by SteveALee** [pnpm/pnpm#749]
on windows cmd I found that `pnpm install -g foo` works fine but

- [ ] `pnpm uninstall -g foo` leaves the scripts in nodejs root. They should be deleted?
- [x] `pnpm list -g` does not work. does same as `pnpm list`

**Comment by zkochan** [comment]
@SteveALee, the `pnpm list -g` works since [v1.5.2](https://github.com/pnpm/pnpm/releases/tag/v1.5.2).

`pnpm list` was implemented only recently in [v1.5.1](https://github.com/pnpm/pnpm/releases/tag/v1.5.1)

**Comment by zkochan** [comment]
Fix published in [v1.10.0](https://github.com/pnpm/pnpm/releases/tag/v1.10.0)
