### ISSUE TITLE
pnpm 8.14.0 install not working

### ISSUE THREAD

**Issue by sysmat** [pnpm/pnpm#7492]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Operating System (Windows, MacOS, Linux)

### Reproduction steps

- `pnpm i`
```
$ pnpm i
Packages: +252
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 296, reused 252, downloaded 0, added 0
```

### Describe the Bug

- it just hang up
- `npm i` do it in 2min

### Expected Behavior

normal installation

### Which Node.js version are you using?

v18.19.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by zkochan** [comment]
This is not enough information for investigating the issue. Could you share the `package.json` file?

**Comment by sysmat** [comment]
```json
{
  "name": "typescript_solidstart_vite",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "@types/node": "^20.10.7",
    "csstype": "3.1.3",
    "esbuild": "^0.19.11",
    "postcss": "^8.4.33",
    "rollup": "^4.9.4",
    "solid-start-node": "^0.3.10",
    "typescript": "^5.3.3",
    "vite": "^5.0.11"
  },
  "dependencies": {
    "@solidjs/meta": "0.29.3",
    "@solidjs/router": "0.10.6",
    "dotenv": "^16.3.1",
    "drizzle-orm": "^0.29.3",
    "mysql2": "^3.7.0",
    "solid-js": "^1.8.8",
    "solid-start": "0.3.10"
  },
  "engines": {
    "node": ">=18"
  }
}
```

**Comment by sysmat** [comment]
- I try 4 times then install `Done in 8m 22.8s`

**Comment by nachoaldamav** [comment]
Maybe related to #7524
