### ISSUE TITLE
--registry parameter is not effective,when `.modules.yaml` exist

### ISSUE THREAD

**Issue by wszgrcy** [pnpm/pnpm#7507]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Lockfile, Package manager compatibility

### Reproduction steps

```
// success
pnpm i lodash
//error
pnpm install my-private-repo   --registry=http://127.0.0.1:5555  -D
```
throw error
```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/my-private-repo: Not Found - 404

This error happened while installing a direct dependency of /home/user/my-project/adfs

my-private-repo is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]
Progress: resolved 1, reused 1, downloaded 0, added 0
```
if I install `my-private-repo` first(without node_modules exist),It will install success

### Describe the Bug

I think `node_modules/.modules.yaml` file save `registries` and then `--registry` not work

### Expected Behavior

This operation can be successfully executed on `NPM`, so I hope it can also be compatible

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 22

**Comment by hjhcos** [comment]
pnpm service not use
