### ISSUE TITLE
`pnpm pack` includes the file listed in the `main` key even when `publishConfig.main` overrides that file and it is not included in `files`

### ISSUE THREAD

**Issue by kael-shipman** [pnpm/pnpm#7518]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/wymp/ts-simple-interfaces/tree/v0.7.2

### Reproduction steps

1. Check out the above commit
2. Run `pnpm i && cd libs/ts-simple-db-mysql/ && pnpm pack --pack-destination /tmp`
3. Run `cd /tmp && tar -xf wymp-* && cd package && ls`
4. Note that `src/index.ts` is present. Note that `package.json` does NOT list `src` under the `files` key, and the `main` key is now properly replaced with the correct `dist/index.js`.
5. To confirm that it is indeed the `main` key causing the problem, go back into `ts-simple-db-mysql` and change the `main` key in `package.json` to read `dist/index.js`, then perform steps 2 and  3 again. Note there is no longer a `src/index.ts` file in the pack.

### Describe the Bug

When you list a file in the `main` key of `package.json` which you then replace during publish using `publishConfig.main`, the file that's listed in the original `main` key is included in the package, even though it's not supposed to be.

### Expected Behavior

The `src/index.ts` file should not be included in the package.

### Which Node.js version are you using?

20.11.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 22.04.3 LTS

**Comment by await-ovo** [comment]
Looks duplicated with #4195, and i think it should be fixed ~

**Comment by kael-shipman** [comment]
Ah! Indeed, thanks for the reference. Closing this one. (Although I don't see any indication that the issue is fixed, but that can be discussed over there.)

**Comment by await-ovo** [comment]
Sorry, I double-checked and it hasn't been fixed yet, I'll send a PR later.
