### ISSUE TITLE
pnpm install won't link dependencies of dependencies correctly

### ISSUE THREAD

**Issue by himself65** [pnpm/pnpm#7523]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

```
pnpm create waku@0.7.0-beta.0
\n
\n
\n
cd waku-project
pnpm install
pnpm dev
```

### Describe the Bug

module not found 

### Expected Behavior

compile correctly

### Which Node.js version are you using?

18

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by himself65** [comment]
Related: https://github.com/dai-shi/waku/issues/371

**Comment by zkochan** [comment]
waku needs to install `react-server-dom-webpack` as a direct dependency of the generated project.

If you want a workaround without fixing waku, you can add one of the following settings to `.npmrc` in the root of the project:

```
public-hoist-pattern[]=react-server-dom-webpack
```

or

```
node-linker=hoisted
```

Then run `pnpm install`.
