### ISSUE TITLE
In the presence of caching, the dependency installation or copying speed is slow in the new version of pnpm

### ISSUE THREAD

**Issue by StarFishing** [pnpm/pnpm#7524]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Store

### Reproduction steps

After the dependency installation, cache the following keys
```
- common/temp/pnpm-store
- common/temp/pnpm-local
- /home/code/.pnpm-store
```
Then carry out the secondary installation when the cache is present

### Describe the Bug

You can see the specific performance in the following image. On the left is pnpm@8.7.6, and on the right is pnpm@8.14.1
<img width="817" alt="image" src="https://github.com/pnpm/pnpm/assets/41889222/626e3a5d-771c-4c1f-abfb-1fbf1f2ecff7">

### Expected Behavior

There should be no significant difference in speed after hitting the cache.

### Which Node.js version are you using?

18.16.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Could you narrow down which version of pnpm was the first to get slower?

I see in v8.9 https://github.com/pnpm/pnpm/releases/tag/v8.9.0 we started using reflinks on Windows. Maybe that caused the issue?

cc @nachoaldamav

**Comment by nachoaldamav** [comment]
@StarFishing does the process get stuck after some dependencies are copied? Like it gets to 1000 dependencies and then stops for some time.

**Comment by StarFishing** [comment]
@zkochan I haven't tried every version, but I identified this issue in our upgrade records and rolled back to the previous version. additionally
> setting the [package-import-method](https://pnpm.io/npmrc#package-import-method) setting to hardlink. 

Will it affect the performance on macOS?

**Comment by StarFishing** [comment]
@nachoaldamav I haven't observed noticeable lag, but overall, the performance is slow.

**Comment by zkochan** [comment]
> Will it affect the performance on macOS?

Yes

**Comment by nachoaldamav** [comment]
@StarFishing Try to run an install with this and tell me if it goes faster. Thanks!
```bash
pnpm i --package-import-method=hardlink
```

**Comment by StarFishing** [comment]
@nachoaldamav  it's faster now, back to normal speed. Compared to the previous time, it now averages 30 seconds when there is a cache hit.
