### ISSUE TITLE
save packages on appdata or programfiles on windows

### ISSUE THREAD

**Issue by Mrgaton** [pnpm/pnpm#7526]
### Contribution

- [] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

i have a lot of problems with onedrive and the packages and this would fix a lot of things on mi case

### Describe the solution you'd like

save the packages by default on appdata or programfiles

### Describe the drawbacks of your solution

nothing

### Describe alternatives you've considered

idk

**Comment by zkochan** [comment]
Check this file: https://github.com/pnpm/pnpm/blob/main/config/config/src/dirs.ts

We already use appdata.
