### ISSUE TITLE
regression: `pnpm update` unexpectedly modifies specified workspaces versions to `workspace:*`

### ISSUE THREAD

**Issue by oedotme** [pnpm/pnpm#7534]
### Last pnpm version that worked

8.12.1

### pnpm version

8.14.1

#### Overview

Workspaces-based project with two workspaces `packages/utils` and `examples/basic`. The root `package.json` uses `overrides` to manage shared workspaces versions.

#### Project root

```jsonc
// package.json

{
  "name": "acme",
  "private": true,
  "pnpm": {
    "overrides": {
      "@acme/utils": "workspace:*"
    }
  }
}
```

```yaml
# pnpm-workspace.yaml

packages:
  - examples/*
  - packages/*
```

#### Shared package

```jsonc
// packages/utils/package.json

{
  "name": "@acme/utils",
  "version": "1.0.1"
}
```

#### Consumer package

```jsonc
// examples/basic/package.json

{
  "name": "@examples/basic",
  "private": true,
  "dependencies": {
    "@acme/utils": "^1.0.1",
    "prettier": "^3.2.2"
  }
}
```

#### Reproduction by updating dependencies

```shell
pnpm update --latest --interactive --recursive
```

#### Consumer package

```jsonc
// examples/basic/package.json

{
  "name": "@examples/basic",
  "private": true,
  "dependencies": {
    "@acme/utils": "^1.0.1", // ✅ version preserved
    "prettier": "^3.2.4"     // ✅ only prettier updated
  }
}
```

#### Consumer package

```jsonc
// examples/basic/package.json

{
  "name": "@examples/basic",
  "private": true,
  "dependencies": {
    "@acme/utils": "workspace:*", // 🚫 version is not preserved
    "prettier": "^3.2.4"          // ✅ prettier updated
  }
}
```

### Node.js version

21.5.0

### Operating System

macOS

**Comment by zkochan** [comment]
Why do you use an override with `workspace:*`? When [link-workspace-packages](https://pnpm.io/npmrc#link-workspace-packages) is `true` (it is `true` by default in v8), pnpm will link packages from the workspace. Your override is not changing the behavior. Unless you want to override subdependencies.

**Comment by oedotme** [comment]
@zkochan thanks for your quick response. I started using `overrides` for the ability to run repo examples in a non-workspaces/isolated context. Here's [an example](https://stackblitz.com/github.com/oedotme/generouted/tree/main/examples/react-router) from the [repo](https://github.com/oedotme/generouted) I'm using `overrides` for. In the release process, examples versions are bumped to the latest versions, and locally it's resolved to `workspace:*`.

However, since `v8.13.1+`, while updating workspaces packages, I've noticed that the workspace versions are overwritten (unexpectedly) by `workspace:*` — it used to be preserved while using `pnpm` `v8.12.1` or below.

I tried setting `link-workspace-packages=false` but that didn't change the behavior.

Please let me know what you think, thanks.

**Comment by zkochan** [comment]
You can remove the overrides. pnpm will still link the packages from the workspace. `link-workspace-packages` should be set to `true`.

**Comment by oedotme** [comment]
TIL, I removed the `overrides` and it seems to work as expected. Thanks for your help!
