### ISSUE TITLE
Error when performing the request

### ISSUE THREAD

**Issue by kingcwt** [pnpm/pnpm#7537]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

pnpm@8.6.1

### Reproduction steps

<img width="1493" alt="image" src="https://github.com/pnpm/pnpm/assets/29888469/17194a7a-70c9-4eaf-8a58-a6b965d06496">
<img width="808" alt="image" src="https://github.com/pnpm/pnpm/assets/29888469/981d3525-4405-446c-a889-6f84f5e696d8">
<img width="572" alt="image" src="https://github.com/pnpm/pnpm/assets/29888469/78ac9d2a-1c9a-4994-aede-f6080c883942">
I have no problem locally, but when deployed to Gitlab's CI, an error message will appear

### Describe the Bug

I have no problem locally, but when deployed to Gitlab's CI, an error message will appear

### Expected Behavior

Normally, it should be installed successfully. Sometimes, it will be installed successfully, but most of the time, it will be a failure  32: [127.9s] Internal Error: Error when performing the request

### Which Node.js version are you using?

18.12.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Linux

**Comment by zkochan** [comment]
This seems to be an issue with [corepack](https://github.com/nodejs/corepack), not pnpm.

**Comment by kingcwt** [comment]
Hahaha, I read it wrong
