### ISSUE TITLE
pnpm doesn't get packages from  expected registry

### ISSUE THREAD

**Issue by uiolee** [pnpm/pnpm#7542]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

reproduction sample: https://github.com/pnpm/pnpm/issues/7542#issuecomment-1901591414

1. `pnpm config set registry https://registry.npmjs.org/ [--location project]`  (default registry)
1. `pnpm init`
2. `pnpm i eslint`  (or any other packages.)
3. `pnpm config set registry https://localhost:56341/ [--location project]`  (specify any registry you want)
5. `pnpm add a_packages`  
    (pnpm will try to download packages from `npmjs` instead of custom registry. It will get failed because the package doesn't exist in `npmjs`)

![err](https://github.com/pnpm/pnpm/assets/22849383/b57d7926-4349-47b1-b7ae-3a577fc6e8bf)

> I am expected that pnpm should get packages from the custom registry instead of npmjs.com

### Describe the Bug

after exec `pnpm config set registry`, `pnpm add <pkg>` doen't work as expected.

> BTW: if you add, modify or delete packages in `(dev)dependencies` of packages.json, `pnpm i` get failed too.

> BTW: this issue exist in monorepo too: if you add new packages to monorepo_worksplace(packages/*/) and run `pnpm i`, you will get failed too.

I guess it's related to  `node_modules/.modules.yaml`, it keeps a `registries` item. Sometimes pnpm will update `registries` from `.npmrc`, but sometimes not. That's so weird, isn't it?

### Expected Behavior

pnpm should get packages from the custom registry 
pnpm should recognize the registry setting in `.npmrc`

### Which Node.js version are you using?

v20.10.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by weyert** [comment]
Did you add the config to point your scope to your private registry?

**Comment by uiolee** [comment]
> Did you add the config to point your scope to your private registry?

sure

**Comment by nachoaldamav** [comment]
Can you try using using the `.npmrc` file? If it works this way it's a bug in `pnpm config set`.
https://pnpm.io/npmrc#registry--authentication-settings

**Comment by weyert** [comment]
Yeah, also seems like `pnpm config set registry https://registry.npmjs.org/` seems to set it globally instead for the current directory 🤔 Not sure if that is caused by `asdf`

**Comment by uiolee** [comment]
Yes. `.npmrc` is correct. but it seems pnpm doesn't follow `.npmrc`

use `pnpm config set ... --location project` will get the same issue.

### 1. default setting

```bash
$ pnpm config set registry https://registry.npmjs.org/

$ cat $HOME/.npmrc
strict-ssl=false
registry=https://registry.npmjs.org/
```

### 2. init project

```bash
$ pwd
/d/git/tmp

$ ls -a
.  ..

$ pnpm init
Wrote to D:\git\tmp\package.json

{
  "name": "tmp",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": ""
}

$ pnpm i eslint
Packages: +99
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 99, reused 99, downloaded 0, added 99, done

dependencies:
+ eslint 8.56.0

Done in 4.7s
```

### 3. switch registry

```bash
$ pnpm config set registry https://private.registry.cccom/

$ cat $HOME/.npmrc
strict-ssl=false
registry=https://private.registry.cccom/
```

```bash
$ pnpm add a_packages
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/a_packages: Not Found - 404
```

------------------

### 3. switch registry (project)

```bash
$ pnpm config set registry https://private.registry.cccom/ --location project

$ cat ./.npmrc
registry=https://private.registry.cccom/

$ pnpm add a_packages
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/a_packages: Not Found - 404
```

**Comment by zkochan** [comment]
It was probably fixed by this: https://github.com/pnpm/pnpm/pull/7515

but not published yet.

**Comment by uiolee** [comment]
> It was probably fixed by this: #7515
> 
> but not published yet.

I test via `pd` in latest main, it works as expected.

![pd](https://github.com/pnpm/pnpm/assets/22849383/ef402f0b-be82-4ed3-ae61-7c2cb8cf6075)

**Comment by taoliujun** [comment]
same problem.

**Comment by aellerton** [comment]
I recently faced and solved this. 

There were a few factors, but one is that `pnpm` reads from `$USERPROFILE/.npmrc` while `npm` reads from `$HOME/.npmrc`

They will often be the same, but not always.
