### ISSUE TITLE
doesn't resolve to latest satisfied version

### ISSUE THREAD

**Issue by tjx666** [pnpm/pnpm#7543]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.1

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/~/github.com/tjx666/mono-project

### Reproduction steps

1. open <https://stackblitz.com/~/github.com/tjx666/mono-project>
2. `pnpm install`, packages/pkg1 will install @yutengjing/foo v1.0.0 because of the lockfile
3. `rm pnpm-lockfile.yaml`
4. `pnpm install`, packages/pkg1 should install @yutengjing/foo v1.0.2 but still install v1.0.0
5. If I remove node_modules first and then remove pnpm-lock.yaml, pnpm install, will install correctlly

### Describe the Bug

When I remove lockfile, and reinstall, packages/pkg1 still install v1.0.0

Seems affected by the node_modules. If I remove the node_modules, everythings ok.

### Expected Behavior

should install @yutengjing/foo v1.0.2. Because I decalre the version by `^1.0.0`, and the latest version is v1.0.2.

### Which Node.js version are you using?

18.8

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
So why don't you run `pnpm update` if you want to update a dependency? This behaviour seems correct to me. Why should pnpm change an existing node_modules only because you remove the lockfile?

**Comment by tjx666** [comment]
In my opinion, when I remove lockfile, the install result should be the same wheather or not the node_modules exits. node_modules shouldn't affect the install result

**Comment by zkochan** [comment]
> but many people include me all know remove the lockfile will make the deps to update...

I am not sure what made you believe that. Historically, npm didn't even have a lockfile by default and running `npm install` repeatadely didn't update node_modules. That's what the update command is for. Some users still don't use a lockfile, they set the [lockfile](https://pnpm.io/npmrc#lockfile) setting to `false`, so running update on repeat install doesn't seem like the right solution.

**Comment by tjx666** [comment]
I'm wrting a article about `how pnpm resolve duplicate deps`, I think pnpm will update to latest satified verison when there is no lockfile. But after test, I find it will be affted by node_module cache.
