### ISSUE TITLE
pnpm lately slow and pnpx stuck at installing deps using executable package

### ISSUE THREAD

**Issue by angelhdzmultimedia** [pnpm/pnpm#7547]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

1. `pnpx nuxi init <name>`

### Describe the Bug

I'm using `pnpx nuxi init <name>` to create a Nuxt project like always, but it's stuck at installing deps:
![image](https://github.com/pnpm/pnpm/assets/10191085/b962da92-c646-431e-af8a-0e00fd990292)

while running `npx nuxi init <name>` creates the project and installs deps successfully:

![image](https://github.com/pnpm/pnpm/assets/10191085/825d3cfc-3a6f-4c34-9e29-3b73d84feca1)

### Expected Behavior

Running `pnpx nuxi init <name>` and getting the deps installed successfully as with `npx nuxi init <name>`.

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by angelhdzmultimedia** [comment]
### Update
Uninstalled pnpm with `npm remove -g pnpm`, and reinstalled it with `npm add -g pnpm`. Confirmed version 8. Tried again the command and same result.

**Comment by angelhdzmultimedia** [comment]
### Update
Working great and fast with bun: 
![image](https://github.com/pnpm/pnpm/assets/10191085/172f9019-6acb-44f1-b604-087a1aeafdb9)

**Comment by nachoaldamav** [comment]
Hi, just a few questions:
- Windows version? Not just Win11 or 10, the exact version (like 23H2)
- Do you use Windows Dev Drives?
- If you set globally the `package-import-method` to `hardlink`, does it work better? https://pnpm.io/npmrc#package-import-method

Thanks in advance!

**Comment by angelhdzmultimedia** [comment]
> Hi, just a few questions:
> 
> * Windows version? Not just Win11 or 10, the exact version (like 23H2)
> * Do you use Windows Dev Drives?
> * If you set globally the `package-import-method` to `hardlink`, does it work better? https://pnpm.io/npmrc#package-import-method
> 
> Thanks in advance!
Hi! Thanks so much for replying. I use to provide env info, i was very exhausted and forgot.

### Environment
**OS:** Windows 11 Home 10.0.22621 Build 22621
**pnpm:** 8.14.1
**npm:** 10.2.3
**Windows Dev Drives:** None
**package-import-method:** I could try this, but i've been using pnpm for a long time (more than npm), and was working great until just recently.

**Comment by nachoaldamav** [comment]
Ok, to give you more context, a few versions ago we added support for [Copy On Write](https://devblogs.microsoft.com/engineering-at-microsoft/dev-drive-and-copy-on-write-for-developer-performance/#:~:text=Copy%2Don%2DWrite%20on%20ReFS%20and%20Dev%20Drive&text=With%20a%20CoW%20link%20you,%E2%80%9Ctrusted%E2%80%9D%20mode%20for%20ReFS.) on pnpm for Windows Dev Drives, after that, a few days ago we started recieving reports of slow installs in Windows.

I'm not sure if it's because of the CoW (probably at least related), if your installs go faster with hardlinks, that's the cause.

**Comment by angelhdzmultimedia** [comment]
> Ok, to give you more context, a few versions ago we added support for [Copy On Write](https://devblogs.microsoft.com/engineering-at-microsoft/dev-drive-and-copy-on-write-for-developer-performance/#:~:text=Copy%2Don%2DWrite%20on%20ReFS%20and%20Dev%20Drive&text=With%20a%20CoW%20link%20you,%E2%80%9Ctrusted%E2%80%9D%20mode%20for%20ReFS.) on pnpm for Windows Dev Drives, after that, a few days ago we started recieving reports of slow installs in Windows.
> 
> I'm not sure if it's because of the CoW (probably at least related), if your installs go faster with hardlinks, that's the cause.

Oooh there was a change. 
Well, I will try that hardlinks and will get back to you.

Thank you for your time, information provided, and kindness.

**Comment by angelhdzmultimedia** [comment]
> * If you set globally the `package-import-method` to `hardlink`, does it work better? https://pnpm.io/npmrc#package-import-method
> 

How to do this if I have no project yet, until I create a project using pnpx which it itselfs call pnpm install behind the scenes to install deps? Pardon me if I'm bothering you with so many questions.

**Comment by nachoaldamav** [comment]
You can apply the option in your user npmrc file, which also applies for `pnpx` https://pnpm.io/npmrc

**Comment by angelhdzmultimedia** [comment]
Maybe I'm not doing it correctly  but it's not working.
In my user profile directory I added a `.npmrc` file with `package-import-method=hardlink`, closed all my terminal windows, open one, and executed `pnpx nuxi init <name>`, it still get stucks installing deps. Then I found a .nuxtrc file and added it there too, to no avail. 

### Update (while typing above message):
After a desperate measure and uninstalled pnpm, and all its references in %USER_PROFILE%/AppData/Local,
I reinstalled it and it complained about "corepack". So I went to the docs and learned about it, and got it solved with `corepack prepare pnpm@latest --activate` 

Can someone please confirm is the solution was the corepack activation or the full reinstall? Because removing `package-import-method=hardlink` from `%USER_PROFILE%/.npmrc` has no effect, it still works now. 😵‍💫

https://github.com/pnpm/pnpm/assets/10191085/4e363dcb-a028-47b0-82ba-e2532703d473
