### ISSUE TITLE
Add --cwd flag like yarn

### ISSUE THREAD

**Issue by cdtut** [pnpm/pnpm#7566]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

For scripting you need to run pnpm commands from particular directory especially with workspaces.

### Describe the solution you'd like

--cwd flag like yarn will help. `pnpm --cwd repository_path --filter workspace run command`

### Describe the drawbacks of your solution

Additional flag but is useful.

### Describe alternatives you've considered

`cd` command but makes scripts more complicated and buggy if you don't change directory before and after in right place.

**Comment by zkochan** [comment]
We already have a flag for this: `-C` or `--dir`

https://pnpm.io/pnpm-cli#-c-path---dir-path
