### ISSUE TITLE
`requiresBuild: true` inconsistently added to pnpm-lock.yaml

### ISSUE THREAD

**Issue by jfirebaugh** [pnpm/pnpm#7577]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Reproduction steps

Run `pnpm install --lockfile-only --ignore-scripts` locally and commit the lockfile. Run `pnpm install --lockfile-only --ignore-scripts` in CI, with the identical version of pnpm, and then `git diff --exit-code -- pnpm-lock.yaml`. The expected result is that there are no changes to the lockfile.

### Describe the Bug

Sometimes, there are changes to the lockfile, namely that in CI `pnpm install --lockfile-only --ignore-scripts` adds `requiresBuild: false` to certain dependencies, whereas locally it does not.

```
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index 1d7740ed185..a5f9996888b 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -41959,6 +41957,7 @@ packages:
   /remove-trailing-separator@1.1.0:
     resolution: {integrity: sha512-/hS+Y0u3aOfIETiaiirUFwDBDzmXPvO+jAfKTitUngIPzdKc6Z0LoFjM/CK5PL4C+eKwHohlHAb6H0VFfmmUsw==}
+    requiresBuild: true
   /renderkid@2.0.7:
     resolution: {integrity: sha512-oCcFyxaMrKsKcTY59qnCAtmDVSLfPbrv6A3tVbPdFMMrv5jaK10V6m40cKsoPNhAqN6rmHW9sswW4o3ruSrwUQ==}
```

### Expected Behavior

Consistent behavior with regards to `requiresBuild` no matter where `pnpm` is run.

### Which Node.js version are you using?

18.17.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Debian Bullseye

**Comment by zkochan** [comment]
I analyzed the code and can't find any scenario during which `requiresBuild` would be set to `true` for `remove-trailing-separator@1.1.0`. Can you share the package.json with which it happens?

**Comment by jfirebaugh** [comment]
I went to debug this on a CI runner, but by then it had stopped happening. I don't know why. I will close the issue as "not reproducible".

**Comment by zkochan** [comment]
I think it might happen when changing the value of the `neverBuiltDependencies` or `onlyBuiltDependencies`. That will have to be explored.

**Comment by thomasballinger** [comment]
I'm seeing this be inconsistent in CI vs locally with 7.33.7, but It's in my own world of generating an alternate pnpm-lock.yaml for a subset of my package. I'm reading to try to figure out what this is supposed to mean, wondering what the effects of removing them manually in my generation step would be.

**Comment by zkochan** [comment]
The requiresBuild field is removed from the lockfile in v9. Do not expect a fix in old versions of pnpm. You should upgrade to the latest version to fix the issue.
