### ISSUE TITLE
Workspace protocol with any semver range specifier

### ISSUE THREAD

**Issue by EWhite613** [pnpm/pnpm#7578]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

Would like to use the workspace protocol with any range specifier. 

Currently there are only workspace:*, workspace:~, or workspace:^. But I would like to use `>=` specifically in my 

### Describe the solution you'd like

```
  "peerDependencies": {
    "vue": "3.2.36",
    "@monotest/composables": "workspace:>="
  },
```
or 
```
  "peerDependencies": {
    "vue": "3.2.36",
    "@monotest/composables": ">=workspace:*"
  },
```
then published as (assume version is `1.0.0`)
```
  "peerDependencies": {
    "vue": "3.2.36",
    "@monotest/composables": ">=1.0.0"
  },
```

### Describe the drawbacks of your solution

Clearly this could be pandora's box where you need to handle crazy things like:
```
 "@monotest/composables": "workspace:^ | ^3.0.0"
```

which may be easy if you parse versions for `workspace:*` and replace that with the version. 

It does seem like something like this is happening though in my tests with `pnpm pack` but simply just strips `workspace` rather than trying to put version in as well:
* `"@monotest/composables": "workspace:^ | ^3.0.0"` -> `"@monotest/composables": "^ | ^3.0.0"`
* `"@monotest/composables": "workspace:>="` -> `"@monotest/composables": ">="`

Can see dummy repo here: https://github.com/EWhite613/vue3-pnpm-workspace/blob/main/monotest-components-0.1.0-packed/package.json#L30 

### Describe alternatives you've considered

Thought about creating a script and running on `postpack` to do the replacement myself. But I think it could belong in core package, if it made sense, as I think others would use it.

**Comment by zkochan** [comment]
I don't have objections. In peer deps it makes sense to support this.

**Comment by EWhite613** [comment]
Sounds good. Thanks @zkochan.

Started working on it a bit, just gotta handle the other cases https://github.com/EWhite613/pnpm/tree/issue-7578

I made the assumption that you would never have more than one `workspace` in the same dependency spec. I at least don't know of a case why you ever would I think anything else you would be pretty specific with previous versions:
```
 "@monotest/composables": "workspace:>= | 3.0.0"
```

**Comment by zkochan** [comment]
Has this change caused https://github.com/pnpm/pnpm/issues/7578?
