### ISSUE TITLE
`pnpm` doesn't install transitive dependencies

### ISSUE THREAD

**Issue by ryan-williams** [pnpm/pnpm#7594]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ryan-williams/pnpm-transdep-issue

### Reproduction steps

```bash
pnpm install deck.gl
ls node_modules/@deck.gl  # ❌ transitive dependencies (e.g. @deck.gl/react) should be installed, but are not
```

[pnpm-transdep-issue](https://github.com/ryan-williams/pnpm-transdep-issue) contains complete repros [in Github Actions](https://github.com/ryan-williams/pnpm-transdep-issue?tab=readme-ov-file#github-actions-repro), and [in Docker](https://github.com/ryan-williams/pnpm-transdep-issue?tab=readme-ov-file#docker-repro):

[Dockerfile](https://github.com/ryan-williams/pnpm-transdep-issue/blob/main/Dockerfile):
```Dockerfile
FROM node:19.3.0
RUN npm install -g pnpm typescript
WORKDIR src
COPY package.json .
# Use `npm` or `pnpm` to install dependencies
ARG npm=pnpm
RUN $npm install
# `npm` shows a @deck.gl subdir here, `pnpm` doesn't
RUN ls -l node_modules
COPY . .
RUN tsc --skipLibCheck deckgl.ts        # ✅ succeeds with npm and pnpm
RUN tsc --skipLibCheck deckgl-react.ts  # ❌ succeeds with npm, fails with pnpm: "Cannot find module '@deck.gl/react/typed' or its corresponding type declarations."
```
[package.json](https://github.com/ryan-williams/pnpm-transdep-issue/blob/main/package.json):
```json
{
    "name": "pnpm-transdep-issue",
    "dependencies": {
        "deck.gl": "8.9.34"
    }
}
```
[deckgl.ts](https://github.com/ryan-williams/pnpm-transdep-issue/blob/main/deckgl.ts):
```ts
// ✅ ok with `npm`
// ✅ ok with `pnpm`
import DeckGL from "deck.gl";
```
[deckgl-react.ts](https://github.com/ryan-williams/pnpm-transdep-issue/blob/main/deckgl-react.ts):
```ts
// ✅ ok with `npm`
// ❌ fails with `pnpm`
import DeckGL from '@deck.gl/react/typed'
```

Repro:
```bash
build() {
    docker build --build-arg npm=$1 -t pnpm-transdep-issue --progress=plain .
}
build npm   # ✅ works
build pnpm  # ❌ fails
```

xref: https://github.com/visgl/deck.gl/issues/8456

### Describe the Bug

`pnpm` doesn't install transitive dependencies

### Expected Behavior

`pnpm` should install transitive dependencies

### Which Node.js version are you using?

19.3.0, also whatever 20.x is in GHA ubuntu-latest currently

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Github Actions ubuntu-latest

**Comment by nachoaldamav** [comment]
Maybe I didn't understand the issue, but as you are not installing `@deck.gl/react` directly this issue is expected because of the pnpm `node_modules` structure. You have 3 options:

1. Use `public-hoist-pattern` to link some dependencies to the public `node_modules`, like this `public-hoist-pattern[]=@deck.gl*`.
2. Add `@deck.gl/react` to the dependencies/devDependencies object in the `package.json`.
3. Use `shamefully-hoist` to force linking every dependency installed to the public `node_modules`.

More information: https://pnpm.io/blog/2020/05/27/flat-node-modules-is-not-the-only-way

**Comment by ryan-williams** [comment]
That makes sense: my repro imports from `@deck.gl/react` directly, so pnpm requires it to explicitly declare that as a dependency in package.json. I didn't realize pnpm worked this way, thanks for the explanation / link!
