### ISSUE TITLE
node-options in .npmrc doesn't get applied 

### ISSUE THREAD

**Issue by mhamri** [pnpm/pnpm#7596]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Package manager compatibility

### Reproduction steps

create this script in package.json

```
{
  "name": "heap-test",
  "scripts": {
    "heap": "node -e \"console.log(require('v8').getHeapStatistics().heap_size_limit /(1024*1024) )\"",
   }
}
```

create this `.npmrc`

```
node-linker=hoisted
node-options="--max-old-space-size=4096"
```

then run `npm run heap` and `pnpm run heap`

![image](https://github.com/pnpm/pnpm/assets/8991783/d3ed5364-95b2-4d5d-aff9-f2554ca479b2)

### Describe the Bug

we can set node options in the .npmrc, unfortunately pnpm doesn't recognize that 

### Expected Behavior

same behavior as `npm` and it set node-options 

### Which Node.js version are you using?

v16.20.2

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by nachoaldamav** [comment]
I think this should be a feature, not a bug, as in pnpm.io we don't have that option.

**Comment by mhamri** [comment]
You are a speed demon ❤️

**Comment by mhamri** [comment]
@zkochan @datrhi 

may I know if it's already was part of `18.15.2`?

```
PS E:\hustling\p\P1\frontend> pnpm --version
8.15.2
PS E:\hustling\P\P1\frontend> pnpm run heap 

> frontend@0.0.0 heap E:\hustling\P\P1\frontend
> node -e "console.log(require('v8').getHeapStatistics().heap_size_limit /(1024*1024) )"

2096
PS E:\hustling\P\P1\frontend> cat .\.npmrc
node-linker=hoisted
node-options="--max-old-space-size=4096"
PS E:\hustling\PP1\frontend> 
```

**Comment by nachoaldamav** [comment]
Hi @rsodre, yes, it's released and working, you can check if the flags are being passed to the process by running this as a pnpm script
```
node -e \"console.log('NODE_OPTIONS:', process.env.NODE_OPTIONS);\"
```

I see that you are using `npx hello`, why not `pnpm run hello`?

**Comment by rsodre** [comment]
strange, node is not picking it too...
```
$ node --version
v23.3.0
$ cat .npmrc 
node-options='--disable-warning=ExperimentalWarning'
$ node -e "console.log('NODE_OPTIONS:', process.env.NODE_OPTIONS);"
NODE_OPTIONS: undefined
```

I use `npx` because my project contains some executable scripts in `bin`.
I can run on `scripts` too, and voilá! it does pick up `.npmrc`
but it's strange that `npx` and `node` do not
