### ISSUE TITLE
Show status of dep as `optional failed` if an optional dep fails to install

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#760]
This is the output I see:

```
  fsevents 1.1.1                                            linking 1.1.1 ↓
  WARN Skipping failed optional dependency registry.npmjs.org/fsevents/1.1.1
  WARN Skipping failed optional dependency registry.npmjs.org/fsevents/1.1.1
  WARN Skipping failed optional dependency registry.npmjs.org/fsevents/1.1.1
  WARN Skipping failed optional dependency registry.npmjs.org/fsevents/1.1.1
```

We should show the status as `optional failed`, and maybe display the chain of dependencies for that module like yarn does.

TODO:

- [x] display the chain of dependencies for the failed optional dependency
- [ ] mark the failed optional dependencies in the installation summary

**Comment by zkochan** [comment]
Do you think it is valuable information to show for subdeps or we can show it only for top deps?

**Comment by vjpr** [comment]
Hmm...I think it would be good for subdeps but can't think of many examples apart from chokidar and fsevents.

It may create unnecessary noise if there is a bunch of optional deps being used for platform-specific stuff. E.g. You would always see fsevents fail on Windows for any module that uses it.

> If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object. This is a map of package name to version or url, just like the dependencies object. The difference is that build failures do not cause installation to fail.

http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html

One argument might be that: a lot of optional deps depend on the platform (win/mac) being used, not whether the package is used as a subdep or a topdep. So they shouldn't be treated differently.

Maybe being able to mute the errors for subdeps would be good, because when people see `failed` they think something is wrong.

**Comment by zkochan** [comment]
> and maybe display the chain of dependencies for that module like yarn does.

this part done in `v1.19.6`

**Comment by zkochan** [comment]
Closing this in favor of #1140
