### ISSUE TITLE
Error: Cannot find module 'less' with pnpm

### ISSUE THREAD

**Issue by TomasOstlind** [pnpm/pnpm#762]
Im trying to use pnpm instead of yarn but get this error on the buildmachine when gulp build-release runs:

Error: Cannot find module 'less'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function.require.resolve (internal/module.js:23:19)
        at resolve_engine_path (C:\BuildAgent\_work\Web\App\node_modules\.registry.npmjs.org\accord\0.26.4\node_modules\accord\lib\index.js:65:18) at Object.exports.load (C:\BuildAgent\_work\Web\App\node_modules\.registry.npmjs.org\accord\0.26.4\node_modules\accord\lib\index.js:25:19) at Object.<anonymous> (C:\BuildAgent\_work\Web\App\node_modules\.registry.npmjs.org\gulp-less\3.3.0\node_modules\gulp-less\index.js:9:29) at Module._compile (module.js:413:34)
            at Object.Module._extensions..js (module.js:422:10)
            at Module.load (module.js:357:32)
            at Function.Module._load (module.js:314:12)
            at Module.require (module.js:367:17)
            ##[error]Running build failed.
            ##[error]Error:
            ##[error]System.Exception: Failed to run gulp build-release

Some of the F# code that handles the build:
    CommandHelper.Run("pnpm install", workingDir)
    CommandHelper.Run("jspm install -y", workingDir)
    CommandHelper.Run("gulp build-release", workingDir) <---- error here

Some of the package.json:
"devDependencies": {
    "aurelia-bundler": "^0.3.2",
    "aurelia-tools": "^0.1.0",
    "babel-eslint": "^4.1.6",
    "del": "^1.1.0",
    "eslint": "^1.10.3",
    "eslint-plugin-aurelia": "^0.3.0",
    "gulp": "^3.8.10",
    "gulp-babel": "^5.1.0",
    "gulp-bump": "^0.1.11",
    "gulp-changed": "^1.1.0",
    "gulp-concat": "^2.5.2",
    "gulp-cssmin": "^0.1.7",
    "gulp-eslint": "^1.1.1",
    "gulp-jshint": "^1.9.0",
    "gulp-less": "^3.0.1",
    "gulp-plumber": "^0.6.6",
    "gulp-shell": "^0.4.0",
    "gulp-sourcemaps": "^1.3.0",
    "gulp-uglify": "^1.1.0",

Some of the shrinkwrap.yaml:
dependencies:
  aurelia-bundler@^0.3.2: 0.3.2
  aurelia-tools@^0.1.0: 0.1.22
  aurelia-validatejs@^0.3.1: 0.3.1
  babel-eslint@^4.1.6: 4.1.8
  del@^1.1.0: 1.2.1
  eslint-plugin-aurelia@^0.3.0: 0.3.0
  eslint@^1.10.3: 1.10.3
  gulp-babel@^5.1.0: 5.3.0
  gulp-bump@^0.1.11: 0.1.13
  gulp-changed@^1.1.0: 1.3.2
  gulp-concat@^2.5.2: 2.6.1
  gulp-cssmin@^0.1.7: 0.1.7
  gulp-eslint@^1.1.1: 1.1.1
  gulp-jshint@^1.9.0: 1.12.0
  gulp-less@^3.0.1: 3.3.0
  gulp-plumber@^0.6.6: 0.6.6

If i look in the folder node_modules i can see the gulp-less...

I am prob doing something wrong, but I cant reslove this error and cant figure out how to get pnpm to install the module. 
Accorging to this issue this should be resloved already: https://github.com/pnpm/pnpm/issues/118

Edit:
I get this warning when im installing pnpm local:
WARN There's a directory in node_modules without package.json: C:/Workspace/MyProject/Web/App/node_modules/less

If i check in the folder less there is 5+ folders but all are empty.. but it should have many files

### pnpm version: 0.67.1

**Comment by vjpr** [comment]
Try adding `less@^2.1.1` as a top-level dep to your package.json file.

What is inside: `C:\BuildAgent_work\Web\App\node_modules.registry.npmjs.org\gulp-less\3.3.0\node_modules\`

Here is where it is failing in https://github.com/jescalan/accord/blob/master/lib/index.coffee:

```
resolve_engine_path = (name, custom_path) ->
  filepath = if custom_path?
    resolve.sync(name_to_adapter(name), basedir: custom_path)
  else
    require.resolve(name_to_adapter(name))

  loop
    if filepath is '/'
      throw new Error("cannot resolve root of node module #{name}")
    filepath = path.dirname(filepath) # cut off the last part of the path
    if fs.existsSync(path.join filepath, 'package.json')
      # if there's a package.json directly under it, we've found the root of
      # the module
      return filepath
```

Try running `pnpm install --reporter=ndjson` in your `workingDir` and post logging output.

**Comment by TomasOstlind** [comment]
Thanks vjpr! Adding less to-level dep resloved the issue and the build is now working and thanks to pnpm the build time is now 6min not 28min like before.. :)

**Comment by vjpr** [comment]
Great, lets close this issue.
