### ISSUE TITLE
Update pnpm-lock.yaml to remove vulnerable dependency "ip"

### ISSUE THREAD

**Issue by mikeharder** [pnpm/pnpm#7652]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

Install `pnpm@8.15.2` and run a vulnerability scanner on the packages under `dist/node_modules`.

### Describe the Bug

A vulnerability was recently reported in `ip`:

https://github.com/advisories/GHSA-78xj-cgh5-2h22

In response, `socks` removed its dependency on `ip`:

https://github.com/JoshGlazebrook/socks/pull/94

Please update the v8 lockfile to the latest version of `socks`, which should also remove `ip`:

https://github.com/pnpm/pnpm/blob/210bcd420e26ccd87ba6bf24b8d277e61e4d4d45/pnpm-lock.yaml#L16352-L16358

### Expected Behavior

No vulnerable packages under `dist/node_modules`.

### Which Node.js version are you using?

18.19.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by stevenpetryk** [comment]
This was already done two days ago in 857c0547ac1a653c9ba71b1bb6ad26d7ec8ff8a2.

**Comment by mikeharder** [comment]
@stevenpetryk: Do you know when a new build (8.15.3/8.16.0) will be released with this fix?

**Comment by zkochan** [comment]
:ship: 8.15.3
