### ISSUE TITLE
Rewrite `package.json` during `pnpm publish`

### ISSUE THREAD

**Issue by zirkelc** [pnpm/pnpm#7653]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

In a monorepo with multiple packages, PNPM workspaces lets us have dependencies between packages without having to publish each package. In combination with TypeScript, you can simply change the **package.json** entrypoints `"main": "src/index.ts"` and "types": "src/index.ts" to`*.ts` files and the TypeScript will resolve those dependencies during local development without the need to transpile each change from TS to JS. 

That is great for internal packages which are not meant to be published. However, if I want to publish both packages to NPM an d still keep the workspace dependency between those, I will run into a problem. The **package.json** entrypoints point to `*.ts` files which works locally but will not work when published to NPM. A published **package.json** entrypoint has to point to `*.js` files, for example `"main": "dist/index.js"`. However, transpiling TS to JS usually happens before publishing, that means `dist/index.js` will either not exist or be outdated (not reflecting the latest code changes). Furthermore, running TS directly and locally via `ts-node` or `tsx` will throw an error if the files of the entrypoints don't exist.

### Describe the solution you'd like

I think an elegant and flexible solution would be to add a new hook to [.pnpmfile.cjs](https://pnpm.io/pnpmfile) like `beforePack()` or `beforePublish()` which allows to rewrite the **package.json** which gets included in the package archive. This hook should be called on `pnpm pack` and `pnpm publish` and receive the **package.json** as input and return a modified **package.json**. The entrypoints could be easily changed from `"main": "src/index.ts"` to `"main": "dist/index.js"`.

This solution would allow to run TypeScript locally, because the entrypoint reference the `index.ts` file,  but the published package points to the transpiled `index.js` file.

### Describe the drawbacks of your solution

No drawbacks because it is a new hook so it should't cause problem with existing installations and is completely opt-in.

### Describe alternatives you've considered

An alternative solution is to use TypeScript aliases that point to the same package as the workspace dependency. For example, if you have a monorepo with `package/foo` and `package/bar` and then `bar` depends on `foo`. Then you would have workspace dependency in `package/bar/package.json`:

```
// package/foo/package.json
{
  "name": "foo",
  "main": "dist/index.js"
}

// package/bar/package.json
{
  "name": "bar",
  "main": "dist/index.js",
  "dependencies": {
    "foo": "workspace:*",
  }
}
```

This config allows to publish package `foo` and `bar` to NPM. However, in order to run the files locally with `ts-node` or `tsx`, we have to add aliases to the **tsconfig.json** at the root and inherit the  **tsconfig.json** in each package:

```
// tsconfig.paths.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "foo": ["packages/foo/src/index.ts"],
      "bar": ["packages/bar/src/index.ts"]
    },
    "noEmit": true
  }
}
// package/foo/tsconfig.json
{
  "extends": "../../tsconfig.paths.json",
  "compilerOptions": {}
  }
}
// package/bar/tsconfig.json
{
  "extends": "../../tsconfig.paths.json",
  "compilerOptions": {}
  }
}
```

This alternative has the disadvantage that we must have a shared **tsconfig.json** in the root that is inherited by all other packages. The **tsconfig.json** `extends` allows to inherit multiple files since Typescript >= 5, so it is easier to share this file than it used to be. However, the problem is that path aliases are not merged between multiple **tsconfig.json** files. That means `package/foo/tsconfig.json` can inherit aliases from `tsconfig.paths.json` but it cannot define its own local aliases in package/foo/tsconfig.json` because that would overwrite the inherited aliases.

**Comment by zkochan** [comment]
This is already supported by [publishConfig](https://pnpm.io/package_json#publishconfig)

**Comment by zirkelc** [comment]
Oh gosh, how could I overlook that 😄 

Thanks for the quick response!
