### ISSUE TITLE
`pnpm i` should not install deps listed in `optionalDependency`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#766]
When we changed `pnpm i` to automatically save deps this issue would have begun.

**Comment by zkochan** [comment]
What do you mean? Is it the same as #759?

**Comment by vjpr** [comment]
If I run `pnpm i fsevents` it will be added to `dependencies`, because it is essentially running `pnpm i -S fsevents`.

**Comment by zkochan** [comment]
I see. This is a duplicate of #727
