### ISSUE TITLE
Curiosity: use pnpm with some CLI (Ionic, Angular, ...)

### ISSUE THREAD

**Issue by maxdevjs** [pnpm/pnpm#767]
This is an awesome project and I wonder if there would be an easy enough solution to use pnpm with Angular / Ionic / ... CLIs

**Comment by zkochan** [comment]
Currently only by removing the generated node_modules folder and re-running installation with pnpm.

I don't think rewriting the npm command would be fair.

**Comment by max-devjs** [comment]
I see.

The point is that we could install further packages with such CLIs after removing the generated node_modules folder and re-running installation with pnpm.

**Comment by zkochan** [comment]
I know one tool that allows changing the package manager via an env variable: https://github.com/dylang/npm-check#update-using-ied-or-pnpm

I think that is the right way to do it. Would angular/ionic make it configurable? I don't know, maybe they already allow yarn? Maybe they would add pnpm in that case... Or maybe we have to become more popular.

In worst case someone can fork angular and substitute npm with pnpm, I would add a link to such a fork to the pnpm README.

**Comment by max-devjs** [comment]
Thank you for your help.

angular-cli offers a -native- configuration alternative for the package manager (currently not working with a couple issues because pnpm is not listed as valid package manager). I do not know yet about Ionic.

I did open an issue specific to the support for pnpm in angular-cli where I give more details about whereI am stuck.

npm-check is a great tool, I am checking it.

**Comment by zkochan** [comment]
As of now, `pnpm@1.32.0` works with Angular. Does it work with Ionic?

**Comment by naakaah** [comment]
Hello,
I'm trying to switch an existing Angular 6 application from npm to pnpm but I'm facing errors.
I've deleted existing node_modules folder then run "pnpm install". The node_modules has been created but when I run "ng build" or "ng serve" I have the following errors: 
Versions of @angular/compiler-cli and typescript could not be determined.

> The most common reason for this is a broken npm install.
> Please make sure your package.json contains both @angular/compiler-cli and typescript in
> devDependencies, then delete node_modules and package-lock.json (if you have one) and
> run npm install again.

Any idea ?

**Comment by zkochan** [comment]
Do you have a sample repo?

You can try `rm -rf node_modules && pnpm i --shamefully-flatten`

**Comment by naakaah** [comment]
Thanks! It's a little bit better but still got errors:

> Error: ENOENT: no such file or directory, open '\node_modules\.registry.npmjs.org\package.json'
>     at Object.fs.openSync (fs.js:579:3)
>     at Object.fs.readFileSync (fs.js:485:33)
> at LicenseExtractor.readPackageJson (\node_modules\.registry.npmjs.org\license-webpack-plugin\1.3.1\webpack-sources@1.1.0\node_modules\license-webpack-plugin\dist\LicenseExtractor.js:126:23)
>     at LicenseExtractor.parsePackage (\node_modules\.registry.npmjs.org\license-webpack-plugin\1.3.1\webpack-sources@1.1.0\node_modules\license-webpack-plugin\dist\LicenseExtractor.js:23:32)

I forgot to mention that I'm on Windows 10.

**Comment by zkochan** [comment]
Seems like an issue with `license-webpack-plugin`. It might have a broken resolver

**Comment by binarious** [comment]
Any workarounds?

**Comment by zkochan** [comment]
Not really. `license-webpack-plugin` has to fix its resolver. If it would resolve dependencies correctly (not preserving symlinks) then it would work with pnpm's node_modules structure. Feel free to create an issue there and reference me

**Comment by binarious** [comment]
Also created https://github.com/pnpm/pnpm/issues/1260, because there are other problems without using `--shamefully-flatten`.

**Comment by zkochan** [comment]
If there are still issues, please set the [node-linker=hoisted](https://pnpm.io/npmrc#node-linker) setting, remove node_modules, and reinstall.
