### ISSUE TITLE
`pnpm remove` links workspace packages when `link-workspace-packages=false` specified

### ISSUE THREAD

**Issue by r34son** [pnpm/pnpm#7674]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Reproduction steps

`pnpm remove <some-package>`

### Describe the Bug

After calling remove command pnpm links workspace packages when `link-workspace-packages=false` is specified

<img width="1028" alt="Screenshot 2024-02-19 at 18 03 26" src="https://github.com/pnpm/pnpm/assets/43549299/f0eb032e-ffef-435f-ae98-933ffa4822bf">

### Expected Behavior

pnpm do not change another packages versions

### Which Node.js version are you using?

18.16.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by r34son** [comment]
@zkochan Hi! Could you please suggest something?

**Comment by r34son** [comment]
@zkochan Can you help?

**Comment by r34son** [comment]
Any info on this?

**Comment by r34son** [comment]
ping

**Comment by zkochan** [comment]
No, we did not look into it yet.

**Comment by fpapado** [comment]
@zkochan, we are running into this issue currently with pnpm `9.15.0`. The issue persists in v10 rc0.

If it will help provide more context, my coworker and I have put up a small reproduction at https://github.com/vluoto/pnpm-remove-link-workspace-packages-false, to demonstrate the issue.

[The reproduction steps are listed in the repository](https://github.com/vluoto/pnpm-remove-link-workspace-packages-false?tab=readme-ov-file#reproduction-steps), but here is the description of our investigation:

The workspace is configured with `link-workspace-packages=false` and contains two packages: `foo` and `@vluoto/bar` The `foo` package depends on `@vluoto/bar` and installs it from the GitHub Packages registry. Both `foo` and `@vluoto/bar` list `react` as a dependency.

When running `pnpm --filter foo remove react`, the command behaves as expected, successfully removing `react` from `foo` without any undesired side-effects. However, executing the equivalent command after navigating to `foo` (`cd packages/foo`) and running `pnpm remove react` produces unexpected results. In this scenario, `@vluoto/bar` is incorrectly `link:`ed to `../bar`, despite `link-workspace-packages` being explicitly set to `false`.

The difference between `pnpm remove --filter` and `cd foo && pnpm remove` is a bit surprising to me 👀 

Please let me know if you'd rather me file a separate issue, or if we could help in any way. For example, I would be happy to write tests for this (I spotted Verdaccio and I'm reasonably familiar with it), if you can point me in the right general direction 🕵️
