### ISSUE TITLE
Changing the lockfile format to reduce duplication

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#7685]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

We will bump the lockfile version in pnpm v9, so we might as well do some more breaking changes to it.

Right now the entries in the "packages" field could be duplicated when the packages have peer dependencies. For example, in the below lockfile the are two entries for `ts-api-utils` and fields like `resolution` and `engines` are duplicated in both:

```yaml
lockfileVersion: '7.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .: {}

  a:
    dependencies:
      ts-api-utils:
        specifier: '1'
        version: 1.2.1(typescript@5.3.3)
      typescript:
        specifier: '5'
        version: 5.3.3

  b:
    dependencies:
      ts-api-utils:
        specifier: '1'
        version: 1.2.1(typescript@4.9.5)
      typescript:
        specifier: '4'
        version: 4.9.5

packages:

  /ts-api-utils@1.2.1(typescript@4.9.5):
    resolution: {integrity: sha512-RIYA36cJn2WiH9Hy77hdF9r7oEwxAtB/TS9/S4Qd90Ap4z5FSiin5zEiTL44OII1Y3IIlEvxwxFUVgrHSZ/UpA==}
    engines: {node: '>=16'}
    peerDependencies:
      typescript: '>=4.2.0'
    dependencies:
      typescript: 4.9.5
    dev: false

  /ts-api-utils@1.2.1(typescript@5.3.3):
    resolution: {integrity: sha512-RIYA36cJn2WiH9Hy77hdF9r7oEwxAtB/TS9/S4Qd90Ap4z5FSiin5zEiTL44OII1Y3IIlEvxwxFUVgrHSZ/UpA==}
    engines: {node: '>=16'}
    peerDependencies:
      typescript: '>=4.2.0'
    dependencies:
      typescript: 5.3.3
    dev: false

  /typescript@4.9.5:
    resolution: {integrity: sha512-1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==}
    engines: {node: '>=4.2.0'}
    hasBin: true
    dev: false

  /typescript@5.3.3:
    resolution: {integrity: sha512-pXWcraxM0uxAS+tN0AG/BF2TyqmHO014Z070UsJ+pFvYuRSq8KH8DmWpnbXe0pEPDHXZV3FcAbJkijJ5oNEnWw==}
    engines: {node: '>=14.17'}
    hasBin: true
    dev: false

```

### Describe the solution you'd like

What if we would store only the dependency relations in the `packages` section and create a new section called `resolutions` for storing fields that are static. The above lockfile would be transformed into:

```yaml
lockfileVersion: '7.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .: {}

  a:
    dependencies:
      ts-api-utils:
        specifier: '1'
        version: 1.2.1(typescript@5.3.3)
      typescript:
        specifier: '5'
        version: 5.3.3

  b:
    dependencies:
      ts-api-utils:
        specifier: '1'
        version: 1.2.1(typescript@4.9.5)
      typescript:
        specifier: '4'
        version: 4.9.5

packages:

  /ts-api-utils@1.2.1:
    resolution: {integrity: sha512-RIYA36cJn2WiH9Hy77hdF9r7oEwxAtB/TS9/S4Qd90Ap4z5FSiin5zEiTL44OII1Y3IIlEvxwxFUVgrHSZ/UpA==}
    engines: {node: '>=16'}
    peerDependencies:
      typescript: '>=4.2.0'

  /typescript@4.9.5:
    resolution: {integrity: sha512-1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==}
    engines: {node: '>=4.2.0'}
    hasBin: true

  /typescript@5.3.3:
    resolution: {integrity: sha512-pXWcraxM0uxAS+tN0AG/BF2TyqmHO014Z070UsJ+pFvYuRSq8KH8DmWpnbXe0pEPDHXZV3FcAbJkijJ5oNEnWw==}
    engines: {node: '>=14.17'}
    hasBin: true

snapshots:

  /ts-api-utils@1.2.1(typescript@4.9.5):
    dependencies:
      typescript: 4.9.5
    dev: false

  /ts-api-utils@1.2.1(typescript@5.3.3):
    dependencies:
      typescript: 5.3.3
    dev: false

  /typescript@4.9.5:
    dev: false

  /typescript@5.3.3:
    dev: false

```

With this format we could even move the "resolutions" section to a separate file or maybe even make it append-only, to reduce git conflicts.

### Describe the drawbacks of your solution

More processing while reading the lockfile. Bigger lockfile.

### Describe alternatives you've considered

The alternative is to keep duplicating the fields.

**Comment by zkochan** [comment]
@pnpm/collaborators how do you feel about this?

**Comment by stevenpetryk** [comment]
I like it. I think, importantly, it will make it clearer what versions have changed when reviewing a PR by removing a lot of the noise.

Lockfile size is not an issue for us at least (it already has 56k lines).

Another downside is that third parties will have to do a bit more work too—not just pnpm. Things like the Rushstack pnpm lockfile explorer will have to do some lookups (not a big deal if you ask me).

**Comment by jakebailey** [comment]
My only thoughts are that I'm not a fan of the "append only" idea, as I really like the current property that I can delete the lockfile and recreate it and it is (in my experience) the same as it was before removal (which gives me confidence in pnpm's behavior), and that I wouldn't want to split the file given the churn of having to re-exclude this file from formatters or similar.

But I'm not totally sure how much splitting things apart will help; presumably both "packages" and "resolutions" will be of similar lengths, and quite long?

**Comment by gluxon** [comment]
I also like it! Definitely a cool idea that normalizes data a bit better.

**Comment by zkochan** [comment]
Regarding append only and dividing the lockfile into two files, I am also not sure about these ideas. I was just thinking about some additional benefits that this change could provide. I don't think we'll enable append only and splitting the lockfile by default. We could add that feature as an experimental feature that should be enabled.

**Comment by zkochan** [comment]
There's one issue that prevents us from this change. The `requiresBuild` field. We currently set it to `true` for any optional dependency because we don't know if the package needs to be built without extracting it. But we don't download optional dependencies.

I guess the only way would be to remove `requiresBuild` from the lockfile.

**Comment by zkochan** [comment]
The change is ready for review: https://github.com/pnpm/pnpm/pull/7700

**Comment by GeoffreyBooth** [comment]
Hi! As you’re considering this, I’m wondering if you’ve given thought to feedback like [this](https://github.com/nodejs/node/issues/50963#issuecomment-1901584364):

> the developers are using wrong version of pnpm and most of the developers are outside contributors of our OSS project(Rspack), so we can’t just tell them use specific version of pnpm and we need a force mechanism, Currently we use `engines.pnpm` and `packageManager` together, we use `packageManager` to auto switch to right pnpm version and use `engines.pnpm` to do double check, so actually we have different choices here:
> * `engines.pnpm` alone:  this is our first choice, then people ask why need to globally switch to a specific pnpm version when develop Rspack, I personally also dislike use `engines.pnpm` alone because I’m also member of Infra team of Bytedance, and deals with tons of oncall every day, and every project has different `engines.pnpm` version, so I need to globally switch pnpm version for every project, which really sucks.
> …

Does pnpm not use a consistent lockfile format between minor and patch releases on the 8.x line? Like if one team member is running 8.15.4 and another is running 8.15.3, and there’s no `engines` or `packageManager` involved, would the lockfile be different or inconsistent if one user did a lockfile-effecting operation and then the other user did?

Or put another way, I would think that if there was some way to define in a project “every developer of this project should be using pnpm 8.x”, that should be enough to avoid lockfile issues, correct? (As opposed to “every developer of this project must be on exactly pnpm 8.15.4.”) Or if not, could it be so in pnpm 9?

Related: https://github.com/openjs-foundation/package-metadata-interoperability-collab-space/issues/15

**Comment by zkochan** [comment]
I am not sure how this is related to the current issue. The change in this issue will be a breaking change in pnpm v9.

Changes to the lockfile format are breaking changes in most cases. We do have the possibility to make a minor bump to the lockfile version and we used it in the past. This can happen if we add some new fields to the lockfile that are just ignored by older versions of pnpm. In this case, you can keep an older version of pnpm on CI and it will still be able to correctly install everything.

**Comment by GeoffreyBooth** [comment]
> I am not sure how this is related to the current issue.

It might not be, my apologies. I can open a new issue if you’d like. Basically, I’m trying to resolve the debate in that thread on the Node side, which stems from this user needing to lock pnpm to exact versions. I’m wondering why pnpm users feel the need to lock to exact versions, as opposed to major versions, in order to avoid lockfile issues. I would assume that pnpm tries to keep lockfile versions consistent within major versions, in which case users shouldn’t be having this issue; yet they are.

**Comment by zkochan** [comment]
I have merged the change. It will be released in an alpha version, so if someone will have additional comments or objections, there's still time to discuss and revise the change before stable v9 is released.
