### ISSUE TITLE
Add option to install file: protocol dependencies using symlink

### ISSUE THREAD

**Issue by yacoubb** [pnpm/pnpm#7688]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

When developing locally I will often have packages + consumers that have peer dependencies that I want to link and work on simultaneously. Using `link:` works well apart from the lack of support for `peerDependencies`.

Using `file:` solves the `peerDependencies` problem, but introduces another issue due to it's use of hard-linking.
If new source files are added to the package, they do not appear in the `node_modules` of the consumer since the package directory is not linked (AFAIK it's not possible to hard-link a directory).
Additionally, if files are deleted and replaced in the package (e.g. if a build step clears the `dist` folder before transpiling code), the updated files do not appear in the consumer's `node_modules`, since the hard links are pointing to the 'old' file.

### Describe the solution you'd like

A flag (e.g. `--file-protocol-use-symlink`), or alternative install protocol (e.g. `file-symlink:`), that uses the `link:`-approach of symlinking the package into the `node_modules` of the consumer, but uses the `file:`-approach of also installing and linking the peer dependencies of the installed package.

A simpler alternative solution is always welcomed!

### Describe the drawbacks of your solution

Any modifications made to the source package will of course affect consuming packages, e.g. removing node_modules or installing other versions will likely break things.
Additionally, multiple consumers of the package with different peer dependency versions will conflict.

### Describe alternatives you've considered

- Running `pnpm install "file:..."` in the consumer each time the package is updated, which is painful and slows development.
- Switching to a monorepo, which is a pretty monumental task! It's in the roadmap, but not scheduled to happen for some time.

**Comment by zkochan** [comment]
This won't work. Node.js resolves symlinks to their real locations, so peer dependencies will resolved from the same place. It doesn't matter what packages will be in the node_modules near the symlinks, node.js will ignore that node_modules during resolution.

**Comment by yacoubb** [comment]
That makes sense, glad I didn't start working on that before your reply! So the hard linking is required for peer dependnecies to be resolved properly.
I think the description on the [pnpm website](https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol) is a tad misleading:
> you can modify the source code of the linked package, and the changes will be reflected in your project

Might be helpful to mention that transpiled code / newly added files will not be updated until re-running `pnpm install`

For others reading this in the future, an alternative solution I considered was some kind of watcher in the consuming service that listens for file changes directly in the linked package directory, and re-applies the hard link each time a change is detected.

It sounds like running `install` each time we make a change is our best bet, so happy to close this.

**Comment by yacoubb** [comment]
A bit more paper trail, I've been trying `bun` with workspaces, and it's worked pretty well so far. I can compile my code in a workspace-linked package and the changes are immediately visible in consuming packages.
I wasn't able to get the same behaviour in `pnpm` because the `.pnpm` store seemed to be installing a singleton package in two different locations (the hash at the end was different), even though all of the packages in the peerDependency descriptor inside `node_modules` were exactly the same.
