### ISSUE TITLE
pnpm support in angular-cli

### ISSUE THREAD

**Issue by max-devjs** [pnpm/pnpm#769]
First step:

I guess I made `angular-cli` to accept and work with `pnpm` locally (pnpm is currently not listed as valid package manager, I have a simple PR for `angular-cli` ready to submit for review), then `ng set --global packageManager=pnpm` will hopefully set correctly the config (not producing an invalid JSON).

Anyway, to create a new app with ng (angular-cli) I use `ng new app-name` for both `npm` and `pnpm`.
Serving the app with `ng serve`, what happens is that:

- the app created with npm just works
- the app created with pnpm fails to compile:

```
ng serve                                                                                         93a48d8   master⚡ [ 1h23m ] ✹ ✭
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 6a38e9bf99d82af8f7ee                                                         
Time: 3001ms
chunk    {0} styles.bundle.js, styles.bundle.js.map (styles) 28 bytes {3} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 28 bytes {3} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 40 bytes [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200' in '/test-pnpm'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'style-loader' in '/test-pnpm'
 @ multi ./src/styles.css

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/test-pnpm'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/test-pnpm'
 @ multi ./src/polyfills.ts

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in '/test-pnpm':
  Error: Can't resolve 'raw-loader' in '/test-pnpm'
  
  - compiler.js:76 
    [test-pnpm]/[webpack@2.2.1]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:280 Compiler.<anonymous>
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compiler.js:280:10
  
  - Compiler.js:480 
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compiler.js:480:13
  
  - Tapable.js:138 next
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:138:11
  
  - CachePlugin.js:62 Compiler.<anonymous>
    [test-pnpm]/[2.2.1]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:477 
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compiler.js:477:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:640 self.applyPluginsAsync.err
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compilation.js:640:19
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:631 self.applyPluginsAsync.err
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compilation.js:631:11
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:626 self.applyPluginsAsync.err
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compilation.js:626:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:622 sealPart2
    [test-pnpm]/[2.2.1]/[webpack]/lib/Compilation.js:622:9
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [test-pnpm]/[0.2.6]/[tapable]/lib/Tapable.js:131:46
  

webpack: Failed to compile.

```
I did find that all dependencies are marked as "missing install"

-  example: `test-pnpm/node_modules/.registry.npmjs.org/@ngtools/webpack/1.3.1/typescript@2.2.2+webpack@2.2.1/node_modules/webpack/package.json`
- same for angular@core etc
- also, example: for `test-pnpm/node_modules/@angular/cli/`

Not sure if somehow related with [Webpack config not finding nested node_modules](https://github.com/angular/angular-cli/issues/6248#issuecomment-300334185) or what else.

Any hint?

**Comment by zkochan** [comment]
I think this issue is similar to the one that happens with CRA https://github.com/pnpm/pnpm/issues/581.

**Comment by max-devjs** [comment]
Once, in my tests, the folder structure created by `pnpm` has been named as ```node_modules/` ```, being `.bin` renamed as ``` ` ```. Unable to reproduce such behaviour.

Was CRA [#581](https://github.com/pnpm/pnpm/issues/581) actually solved?

**Comment by yegor-sytnyk** [comment]
The problem is that Webpack trying to resolve node modules in local 'node_modules' folder and with pnpm some of the modules are not hoisted there from @angular/cli package (css-loader, raw-loader and others).

For other client build systems like create-react-app (for React) or vbuild (for Vue) there is a fallback path for module resolution in Webpack config with ownModules.

It uses following code (for react-scripts similar for vbuld):

function resolveOwn(relativePath) {
  return path.resolve(__dirname, '..', relativePath);
}

Which when used with npm install returns:

{PROJECT_PATH}\node_modules\react-scripts

And with pnpm install:

{PROJECT_PATH}\node_modules\.registry.npmjs.org\react-scripts\0.9.5\node_modules\react-scripts (which is no use as this path does not exists)

That is why both create-react-app and vbuild are not working when installed as devDependency via pnpm, but they work when installed as global dependency.

However, angular/cli cannot be used as global dependency and should be installed as devDependency.

**Comment by zkochan** [comment]
They should use [resolve-from](https://www.npmjs.com/package/resolve-from) to have the same resolution that Node.js uses. pnpm's `node_modules` structure is Node.js-compatible.

**Comment by max-devjs** [comment]
@yegor-sytnyk @zkochan thank you both for the replies. So, currently there is not a straightforward solution...

**Comment by zkochan** [comment]
@max-devjs seems like this is an issue with `webpack@1` and it works fine with the latest webpack. I just tried Angular2 using [@angular/cli](https://www.npmjs.com/package/@angular/cli) and it works like a charm!

**Comment by zkochan** [comment]
Have these been solved by the PRs created by @aecz for #863?

**Comment by aecz** [comment]
Error is gone using Angular CLI 1.6.1 and pnpm 1.23.2.
```
npm i -g @angular/cli@1.6.1
ng new test-pnpm --skip-install
cd test-pnpm
pnpm i
ng serve
```

**Comment by Polyterative** [comment]
so no support is planned?

**Comment by zkochan** [comment]
As far as I understand this was fixed on Angular side.

**Comment by sumitramteke** [comment]
`ng add @angular/material` is not working 

```
Cannot find module '/Users/dev/WS/pd/hw-ng-pnpm/ui/node_modules/.pnpm/@angular/material@10.1.2_28c3b87c255f6f809acd7737ebfc3abe/node_modules/@angular/material/schematics/ng-add/setup-project'
Require stack:
- /Users/dev/WS/pd/hw-ng-pnpm/ui/node_modules/.pnpm/@angular-devkit/schematics@10.0.2/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/dev/WS/pd/hw-ng-pnpm/ui/node_modules/.pnpm/@angular-devkit/schematics@10.0.2/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/dev/WS/pd/hw-ng-pnpm/ui/node_modules/.pnpm/@angular/cli@10.0.2/node_modules/@angular/cli/utilities/json-schema.js
- /Users/dev/WS/pd/hw-ng-pnpm/ui/node_modules/.pnpm/@angular/cli@10.0.2/node_modules/@angular/cli/models/command-runner.js
- /Users/dev/WS/pd/hw-ng-pnpm/ui/node_modules/.pnpm/@angular/cli@10.0.2/node_modules/@angular/cli/lib/cli/index.js
- /Users/dev/.nvm/versions/node/v14.6.0/pnpm-global/4/node_modules/.pnpm/@angular/cli@10.0.4/node_modules/@angular/cli/lib/init.js
- /Users/dev/.nvm/versions/node/v14.6.0/pnpm-global/4/node_modules/.pnpm/@angular/cli@10.0.4/node_modules/@angular/cli/bin/ng
```

**Comment by zkochan** [comment]
Create a new issue then. This is not related to this one.

**Comment by 0xMostafa** [comment]
@maxdevjs  Try restarting the server `ng serve -o` server
