### ISSUE TITLE
pnpm store doesn't have symlink files after version 8.7

### ISSUE THREAD

**Issue by 100paperkite** [pnpm/pnpm#7691]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.7.0~

### Which area(s) of pnpm are affected? (leave empty if unsure)

Store

## Prerequisite
```bash
mkdir test && cd test
cat > package.json <<EOF
{
  "dependencies": {
    "@tensorflow/tfjs-node": "4.17.0"
  }
}
EOF
```

## ~v8.6
In versions up to v8.6, even if the package is installed twice, the symbolic linked file remains intact(though the symlink disappears).

```bash
echo "pnpm@8.6.12"
rm -rf $(pnpm store path) 

npm install -g pnpm@8.6.12
pnpm install

ls -li node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2
>> 7498814 lrwxrwxrwx 1 x x 32 Feb 22 08:48 node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2 -> libtensorflow_framework.so.2.9.1

rm -rf node_modules
pnpm install
ls -li node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2
>> 7468824 -rwxr-xr-x 4 x x 40180768 Feb 22 08:48 node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2
```

## (Problem) v8.7~
However, starting from v8.7, if the package installed twice, the symbolic linked files disappear.

```bash
echo "cleanup"
rm -rf node_modules
rm -rf ~/.local/share/pnpm/store
rm ./pnpm-lock.yaml

echo "pnpm@8.7.0"
npm install -g pnpm@8.7.0
pnpm install

ls -li node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2
>> 7499208 lrwxrwxrwx 1 x x 32 Feb 22 08:48 node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2 -> libtensorflow_framework.so.2.9.1

rm -rf node_modules
pnpm install

ls -li node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2
>> ls: cannot access 'node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow_framework.so.2': No such file or directory

```

### Describe the Bug

After v8.7, when packages are stored in the pnpm store, symbolic links are not being saved.
Inside the files at `~/.local/share/pnpm/store/v3/files/...`, only the following two files exist, not symbolic linked files.
Therefore, while the initial installation goes smoothly, problems arise when reinstalling because the pnpm store without symlink files is being accessed.
```
"deps/lib/libtensorflow.so.2.9.1": {
      "checkedAt": 1708590339265,
      "integrity": "sha512-kr+1TJRj2b8BcnILmdmkMK/XTNXLWM1bHpKXqRypITYAXQLt9JkxGpzysWFRI5J+udlGADqUnqsHXLOIiUA8rw==",
      "mode": 33133,
      "size": 360834960
  },
"deps/lib/libtensorflow_framework.so.2.9.1": {
    "checkedAt": 1708590339343,
    "integrity": "sha512-OXNUEv2ld5hV/txczxVMdobBofJLJxOweskwjM0QQTo4/ep436Wka8hzmY1HyACs81FtWf/1RLk22GU2UWF8BA==",
    "mode": 33133,
    "size": 40180768
},
```

### Expected Behavior

Symlink file information should be correctly saved in the pnpm store to ensure consistent results during reinstallation.

### Which Node.js version are you using?

18.12.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu, Debian

**Comment by zkochan** [comment]
We should fix this. Here's the reason:

https://github.com/pnpm/pnpm/blob/284eedb8212dd142ac0a6ac96bac29ce306f3a7e/store/cafs/src/parseTarball.ts#L127

Our in-house tarball extractor currently skips symlinks.

**Comment by zkochan** [comment]
No, actually it is a problem with side-effects cache. When we upload side-effects cache to the store, we don't upload symlinks correctly, I guess. I get the same issue with pnpm v8.6.12

**Comment by zkochan** [comment]
I assume this issue is the same as https://github.com/pnpm/pnpm/issues/7253

**Comment by bitofsky** [comment]
@zkochan 
Hello? I have found an issue in cafs/src/addFilesFromDir.ts.
In version pnpm 8.6.12, symbolic links are recognized as files, but starting from version pnpm 8.7.0, symbolic links are not recognized as files anymore.
The changes between the two versions are as follows:

pnpm@8.6.12
```typescript
    const files = await fs.readdir(currDir) // readdir returns an array of strings
    await Promise.all(files.map(async (file) => {
      ...
      const stat = await fs.stat(fullPath) // stat returns a Stats object
      if (stat.isDirectory()) {
        ...
      }
      if (stat.isFile()) { // symbolic links are considered files
```

pnpm@8.7.0
```typescript
    const files = fs.readdirSync(currDir, { withFileTypes: true }) // readdirSync returns an array of Dirent objects
    for (const file of files) {
        if (file.isDirectory()) {
            ...
        }
        if (file.isFile()) { // symbolic links are not considered files
            ...
        }
```

Dirent objects and Stats objects return different results when the isFile() method is called on symbolic linked files.
While Dirent objects return false when the isFile() method is called on symbolic linked files, Stats objects return true.
```bash
10272392 -rw-rw-r-- 1 bitofsky bitofsky  2 Feb 23 16:06 origin.txt
10272393 lrwxrwxrwx 1 bitofsky bitofsky 10 Feb 23 16:09 link.txt -> origin.txt
> node
> require('fs').readdirSync('.', {withFileTypes:true})[0].isFile() // readdirSync returns an array of Dirent objects
false
> require('fs').statSync('./link.txt').isFile() // statSync returns a Stats object
true
```

However, starting from pnpm@9.0.0-alpha.5, symbolic links are correctly recognized again.
The code checking for isFile() in the if condition has been removed and replaced with else.
```typescript
    const files = fs.readdirSync(dir, { withFileTypes: true })
    for (const file of files) {
        if (file.isDirectory()) {
            ...
        } else { // symbolic links are considered files
            ...
        }
```

I believe the code modified in version 9.0.0-alpha.5 should be reflected in the version 8 series as well, or the code after 8.7 should be modified as follows.
```typescript
-       } else if (file.isFile()) {
+       } else if (file.isFile() || file.isSymbolicLink()) {
```

Thank you.

**Comment by bitofsky** [comment]
Hello? I have found an issue in cafs/src/addFilesFromDir.ts.
In version pnpm 8.6.12, symbolic links are recognized as files, but starting from version pnpm 8.7.0, symbolic links are not recognized as files anymore.
The changes between the two versions are as follows:

pnpm@8.6.12
```typescript
    const files = await fs.readdir(currDir) // readdir returns an array of strings
    await Promise.all(files.map(async (file) => {
      ...
      const stat = await fs.stat(fullPath) // stat returns a Stats object
      if (stat.isDirectory()) {
        ...
      }
      if (stat.isFile()) { // symbolic links are considered files
```

pnpm@8.7.0
```typescript
    const files = fs.readdirSync(currDir, { withFileTypes: true }) // readdirSync returns an array of Dirent objects
    for (const file of files) {
        if (file.isDirectory()) {
            ...
        }
        if (file.isFile()) { // symbolic links are not considered files
            ...
        }
```

Dirent objects and Stats objects return different results when the isFile() method is called on symbolic linked files.
While Dirent objects return false when the isFile() method is called on symbolic linked files, Stats objects return true.
```bash
10272392 -rw-rw-r-- 1 bitofsky bitofsky  2 Feb 23 16:06 origin.txt
10272393 lrwxrwxrwx 1 bitofsky bitofsky 10 Feb 23 16:09 link.txt -> origin.txt
> node
> require('fs').readdirSync('.', {withFileTypes:true}).find(f => f.name === 'link.txt').isFile() // readdirSync returns an array of Dirent objects
false
> require('fs').statSync('./link.txt').isFile() // statSync returns a Stats object
true
```

However, starting from pnpm@9.0.0-alpha.5, symbolic links are correctly recognized again.
The code checking for isFile() in the if condition has been removed and replaced with else.
```typescript
    const files = fs.readdirSync(dir, { withFileTypes: true })
    for (const file of files) {
        if (file.isDirectory()) {
            ...
        } else { // symbolic links are considered files
            ...
        }
```

I believe the code modified in version 9.0.0-alpha.5 should be reflected in the version 8 series as well, or the code after 8.7 should be modified as follows.
```typescript
-       } else if (file.isFile()) {
+       } else if (file.isFile() || file.isSymbolicLink()) {
```

Thank you.

**Comment by zkochan** [comment]
Thanks @bitofsky for look into it. We will for sure backport the fix to v8 too. We just need to cover it with a test. I don't want us to break it again in the future.
