### ISSUE TITLE
Wildcard for supportedArchitectures

### ISSUE THREAD

**Issue by Scrumplex** [pnpm/pnpm#7695]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

**As a** software packager and package maintainer
**I want to** be able to populate my package cache with all potential dependencies for any target platform
**So that** my builds can work reproducibly without an internet connection.

### Describe the solution you'd like

I would like to have an option to specify all operating systems and/or cpu architectures and/or libc implementations, so that pnpm fetches all possible dependencies.

### Describe the drawbacks of your solution

Increased disk usage, but as this is mostly opt-in it shouldn't be a big problem.

### Describe alternatives you've considered

A CLI option to download all packages in the lock file into the store.

**Comment by Scrumplex** [comment]
Related: https://github.com/pnpm/pnpm/issues/7510

**Comment by zkochan** [comment]
If you want to install all the optional dependencies, then that is already possible. Run:

```
pnpm install --force
```

**Comment by Scrumplex** [comment]
That works for my use-case. Thanks!
