### ISSUE TITLE
Script to convert all existing npm projects to use pnpm?

### ISSUE THREAD

**Issue by DVassilev** [pnpm/pnpm#770]
I have a lot of npm projects on my computer and I'd love to convert them to all use pnpm's space efficiency. Is there any chance someone has made a script to go through everything and convert it over? Thanks

**Comment by zkochan** [comment]
Maybe this package will help: [pnpmr](https://github.com/pnpm/pnpmr). I created it for using in a monorepo. But it should work also if you just run it from the root of your disk

**Comment by zkochan** [comment]
One note about it though. Because of [this issue](https://github.com/pnpm/pnpm/issues/724) pnpm currently does't not remove stuff from node_modules, just moves it to a `.ignored` subfolder. So pnpmr won't reduce disk usage. You'll have to manually remove node_modules :disappointed:

**Comment by lonix1** [comment]
@zkochan Is this the proper way to "upgrade" a project to pnpm?

````
rm -rf node_modules
pnpm i
````

What about the global npm store?

**Comment by zkochan** [comment]
@lonix1 yes. It is the proper way.

Regarding globally installed packages, just install the global package via pnpm.
