### ISSUE TITLE
Flag to disable hard linking

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#771]
I'm setting up a Docker build and I am using a build container with a volume container to cache `node_modules` to speed up my deployment.

If I mount a volume container for the `.pnpm-store`, when I run `pnpm i` I get cross-device errors.

If I mount a dir from my host I also get cross-device errors.

To avoid this I have to copy the entire store across to the Docker image which takes a minute or longer, losing the benefit of fast pnpm installs.

1. What I need is a yarn-like option which copies the deps into `node_modules` instead of hard-linking.

2. Is there a way to avoid the copying, without hard-linking? Can we support symlinking - does this affect the Node resolution algorithm?

**Comment by vjpr** [comment]
Actually, maybe I can just symlink `node_modules` in the volume container, then I only have to `cp -R /volume-container/node_modules app/node_modules`.

**Comment by zkochan** [comment]
There is an issue for this https://github.com/pnpm/pnpm/issues/712

As temporary workaround, you can specify a `store-path` that is on the current volume

**Comment by vjpr** [comment]
I upgraded to Docker for Mac (Edge) which uses the `overlay2` driver, instead of `aufs` which seems to have sped up the `cp -R` considerably. Without the hard-linking overhead it would probably be faster, but this seems okay for now.

**Comment by zkochan** [comment]
A temporary fix published with [v0.69.0-beta.3](https://github.com/pnpm/pnpm/releases/tag/v0.69.0-beta.3).  It can be installed via `npm i -g pnpm@next`

Also, if this is only about the cross-device linking error, maybe you don't need the flag? Fixing #712 would fix this issue, right?

**Comment by zkochan** [comment]
[package-import-method](https://pnpm.js.org/docs/usage/configuring.html#package-import-method) config was published in [pnpm@1.25.0](https://github.com/pnpm/pnpm/releases/tag/v1.25.0).
