### ISSUE TITLE
`--ignore-engines` api in pnpm?

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#7719]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

I get `sharp` errors on Next.js production while using Docker because I'm using `next/image`. Next.js does optimizations but yells if `sharp` isn't installed in prod.

### Describe the solution you'd like

I found [a solution here](https://github.com/vercel/next.js/discussions/35296#discussioncomment-8404420) but it uses shows how to do it in `yarn`.

What's the `pnpm` equivalent of `yarn add sharp --ignore-engines`?

I tried `pnpm install sharp --ignore-engines` & I got this:

```bash
 > [web deps 5/5] RUN pnpm install sharp --ignore-engines:
1.042  ERROR  Unknown option: 'ignore-engines'
1.042 Did you mean 'ignore-scripts'? Use "--config.unknown=value" to force an unknown option.
1.043 For help, run: pnpm help add
------
failed to solve: process "/bin/sh -c pnpm install sharp --ignore-engines" did not complete successfully: exit code: 1
```

### Describe the drawbacks of your solution

Idk

### Describe alternatives you've considered

Go back to `npm`. I really don't want to.

**Comment by zkochan** [comment]
What is the original error without `--ignore-engines`?

pnpm doesn't fail on engine mismatch by default: https://pnpm.io/npmrc#engine-strict

**Comment by deadcoder0904** [comment]
@zkochan i think it works but i guess there should be a page in the docs to show that the equivalent of `--ignore-engines` is just `pnpm install`.

i came to the same conclusion but wanted to confirm as google showed nothing.

i guess i can close this one.
