### ISSUE TITLE
`pnpm deploy` in a workspace creates `${deployDir}/node_modules/.modules.yaml` at the root of the workspace instead of under the requested deployment directory

### ISSUE THREAD

**Issue by segevfiner** [pnpm/pnpm#7731]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/segevfiner/pnpm-deploy-bug

### Reproduction steps

1. Clone the project.
2. `pnpm i`.
3. Run `pnpm -F . deploy deploy --prod` in `apps/foo`.
4. You will have a `deploy` folder at the root of the workspace with `node_modules/.modules.yaml` in addition to the requested directory to deploy too.

### Describe the Bug

`pnpm deploy` in a workspace creates `${deployDir}/node_modules/.modules.yaml` at the root of the workspace instead of under the requested deployment directory

### Expected Behavior

`node_modules/.modules.yaml` should be created in the requested deployment directory, not at the workspace root under the name of the deployment directory.

### Which Node.js version are you using?

18.19.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Synthetic-Dev** [comment]
This is a big issue! I am trying to run `pnpm deploy` to deploy my project in a `prod` folder next to the workspace but it is trying to place the `node_modules/.modules.yaml` at `../prod`

Exact file paths examples:
Project dir: `/var/www/site-name/project`
Deploy dir: `/var/www/site-name/prod`
trying to place `.modules.yaml` at `/var/www/prod/node_modules/.modules.yaml`
