### ISSUE TITLE
With ignore-workspace-root-check set to true I am getting  ERR_PNPM_ADDING_TO_ROOT 

### ISSUE THREAD

**Issue by KajSzy** [pnpm/pnpm#7738]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.4

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

- Add `pnpm-workspace.yaml` as follows
```yaml
ignore-workspace-root-check: true
```

- Try installing some dependency without passing `-w` flag

```bash
pnpm add react
```

### Describe the Bug

Instead of installing dependency I'm getting an error
```bash
 ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.
```

### Expected Behavior

Dependency is installed without any error, maybe some warning message is shown

### Which Node.js version are you using?

18.19.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KajSzy** [comment]
Yup, adding `ignore-workspace-root-check=true` to `.npmrc` did the job.
Thanks for help, couldn't find anywhere where this param should be added.

**Comment by Gautamneeraj88** [comment]
ignore-workspace-root-check: true,

I have added this in the **.npmrc** but it still gives the error is there any other way to fix this.

![image](https://github.com/user-attachments/assets/ae599c70-c37f-4793-92be-e09dd60ad8db)
