### ISSUE TITLE
pnpm install --frozen-lockfile=false will not update the outdated packages

### ISSUE THREAD

**Issue by qiulang** [pnpm/pnpm#7740]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.15.4

### Reproduction steps

I have the `pnpm-lock.yaml` and when I run `pnpm install --frozen-lockfile=false`, pnpm won't install the latest packages for me.

I have run `pnpm outdated` to find I have some outdated packages and I tried to figure out the usage of `frozen-lockfile`. But I find `pnpm install --frozen-lockfile=false` won't install the latest package. Only if I delete `pnpm-lock.yaml` can I let `pnmp install` the latest packages. Then what does the usage of `frozen-lockfile` ?

### Describe the Bug

Instead of creating a GitHub repository minimal reproduction. I just use https://github.com/Licoy/ChatGPT-Midjourney to reproduce.

[The package.json](https://github.com/Licoy/ChatGPT-Midjourney/blob/master/package.json) has `"midjourney": "^4.3.13" 

https://github.com/Licoy/ChatGPT-Midjourney/blob/master/pnpm-lock.yaml has 

```
midjourney:
    specifier: ^4.3.13
    version: 4.3.13
```

run `pnpm install --frozen-lockfile=false` won't install the latest midjourney 4.3.17

### Expected Behavior

run `pnpm install --frozen-lockfile=false` install the latest midjourney 4.3.17

### Which Node.js version are you using?

16.20

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
`frozen-lockfile=false` just means that `pnpm install` will not fail if the lockfile is outdated. It does not mean updating. Please use `pnpm update [--latest]` instead.

**Comment by qiulang** [comment]
Thanks for the reply but `frozen-lockfile=true` won't update the lock file either. So what exactly is the difference between them ?

**Comment by KSXGitHub** [comment]
`--frozen-lockfile` only means that it will fail if the lockfile is not up-to-date with the `package.json`. This is important for CI and reproducibility.

**Comment by KSXGitHub** [comment]
If you want to update your packages, use `pnpm update`.

**Comment by qiulang** [comment]
Thanks for the update. One of main reasons I raised my question was because 2 high score questions and answers on stackoverflow. I find the accepted answers all had some confusion.

1.  [pnpm equivalent command for npm ci](https://stackoverflow.com/questions/70154568/pnpm-equivalent-command-for-npm-ci).  This is the highest scores in SO about pnpm. The accepted answer said `pnpm install --frozen-lockfile`. But after reading your comments and check the pnpm document I feel they are not exactly equivalent because pnpm dectects whether it is in CI or not and it is not in CI environment it will still proceed and install according to the lock file(my confusion in the first place). But `npm ci` does not check whether it is in CI, it just checks whether the lock file is present or not and if it is present it will install packages according to the lock file. So I feel `npm ci` is more like `pnpm install --frozen-lockfile=false`. Am I right ?

2. [How to have `pnpm install` install everything exactly to the specs of the pnpm-lock file?](https://stackoverflow.com/questions/73968943/how-to-have-pnpm-install-install-everything-exactly-to-the-specs-of-the-pnpm-l). This question caused me another confusion. Because the question said 

> I'm using pnpm, is there anyway I can have pnpm install look at the existing pnpm-lock.yaml so I can eventually build a project that is entirely the same as a previous build I had 6 months ago?

But doesn't pnpm just work like that, i.e. always uses the lock file if present. So we will get "entirely the same as a previous build I had 6 months ago" ?

**Comment by KSXGitHub** [comment]
> But after reading your comments and check the pnpm document I feel they are not exactly equivalent because pnpm dectects whether it is in CI or not automatically and it is not in CI environment it will still proceed and install according to the lock file(my confusion in the first place).

Incorrect. While `pnpm install` (without `--frozen-lockfile`) tries to detect whether the environment is a CI, `pnpm install --frozen-lockfile` doesn't. `--frozen-lockfile` always fails if lockfile is outdated or isn't present.

In short, `pnpm install` is equivalent to `npm install` (but with an extra feature to detect CI), but `pnpm install --frozen-lockfile` is equivalent to `npm ci`.
