### ISSUE TITLE
`shamefully-hoist` Configuration Bug in pnpm

### ISSUE THREAD

**Issue by datrhi** [pnpm/pnpm#7743]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.4

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Store, Hooks

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/datrhi/pnpm-shamefully-hoist-bug

### Reproduction steps

Use my minimal reproduction:
- pnpm install

### Describe the Bug

Upon inspecting the `node_modules` directory, a noticeable discrepancy is observed. Specifically, the `react-native-svg` package has a dependency on `css-select` with version ^2.1.0, yet it is erroneously linked to `css-select` version 4.3.0. This inconsistency stems from the fact that `node-html-parser` has a dependency on `css-select` version 4.3.0.

While the `.pnpm` virtual store correctly indexes the dependencies, the use of `shamefully-hoist` to symlink all packages to `node_modules` results in an incorrect indexing.

### Expected Behavior

Like yarn, it create `css-select` 4.3.0 in node_modules of `node-html-parser`, and `css-select` 2.1.0 flat

### Which Node.js version are you using?

18.17.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
> Upon inspecting the `node_modules` directory, a noticeable discrepancy is observed. Specifically, the `react-native-svg` package has a dependency on `css-select` with version ^2.1.0, yet it is erroneously linked to `css-select` version 4.3.0. This inconsistency stems from the fact that `node-html-parser` has a dependency on `css-select` version 4.3.0.

Clarify what you mean by "inspecting". How did you inspect them?

When I clone your repro repo and do `pnpm install --ignore-scripts`, I see that `node_modules/react-native-svg` is a symlink to `react-native-svg@12.1.0_react-native@0.73.5_@babel+core@7.24.0_@babel+preset-env@7.24.0_@babe_owypsel7dhtjfk3xu57dofh4dy` and `css-select` inside the symlink target is the correct version.

> Like yarn, it create `css-select` 4.3.0 in node_modules of `node-html-parser`, and `css-select` 2.1.0 flat

Why should pnpm prioritize 2.1.0 over 4.3.0? Both are the same "rank". Why should pnpm prioritize dependencies of `react-native-svg` over that of `node-html-parser`? They are equal, the only difference is that 4.3.0 is more up-to-date.

---

Finally, I have a feeling that this issue of yours could be an XY problem. Let me know what you're trying to solve by `shamefully-hoist` and I may or may not be able to help you.

**Comment by datrhi** [comment]
> When I clone your repro repo and do `pnpm install --ignore-scripts`, I see that `node_modules/react-native-svg` is a symlink to `react-native-svg@12.1.0_react-native@0.73.5_@babel+core@7.24.0_@babel+preset-env@7.24.0_@babe_owypsel7dhtjfk3xu57dofh4dy` and `css-select` inside the symlink target is the correct version.

I previously mentioned that in the virtual store, pnpm handles things correctly, but the flat node_modules directory (outside of `.pnpm`) created by the symlink doesn't resemble the structure seen in yarn or npm's node_modules

> Why should pnpm prioritize 2.1.0 over 4.3.0? Both are the same "rank". Why should pnpm prioritize dependencies of `react-native-svg` over that of `node-html-parser`? They are equal, the only difference is that 4.3.0 is more up-to-date.

Now, let's address the question of pnpm prioritizing version 2.1.0 over 4.3.0. Both versions are of the same "rank," so why does pnpm choose one over the other? Additionally, why does pnpm prioritize dependencies of react-native-svg over those of node-html-parser when both are equal, with the only distinction being that version 4.3.0 is more up-to-date?

The flat node_modules seems to lack the css-select 4.3.0 version, deviating from the structure typically found in yarn or npm-created node_modules. Is this a result of an error in using the shamefully-hoist option?

Additionally, as I create a React Native monorepo using pnpm and encounter issues with webpack's inability to interpret the pnpm structure, even with the shamefully-hoist option enabled, I've managed to resolve the situation with Metro and @rnx-kit/metro-resolver-symlinks, but I find myself at an impasse with webpack.

Is my understanding of the situation accurate, or have I misunderstood the implications of shamefully-hoist? Furthermore, any guidance on resolving the webpack issue within the context of a React Native monorepo using pnpm would be greatly appreciated.

**Comment by KSXGitHub** [comment]
> I previously mentioned that in the virtual store, pnpm handles things correctly, but the flat node_modules directory (outside of `.pnpm`) created by the symlink doesn't resemble the structure seen in yarn or npm's node_modules

I don't think pnpm should goes out of its way to emulate the quirks of other package managers.

> with the only distinction being that version 4.3.0 is more up-to-date?

Maybe this distinction is precisely why pnpm prioritize up-to-date version. Can you confirm this, @zkochan?

Regardless, there's no reason pnpm should prioritize the outdated version over the up-to-date one. I'm not sure how yarn and npm prioritize the versions, but (again) there's no reason for pnpm to emulate the others' quirks.

> Is this a result of an error in using the shamefully-hoist option?

No. There's no rule that one should be prioritized over the other.

> Additionally, as I create a React Native monorepo using pnpm and encounter issues with webpack's inability to interpret the pnpm structure, even with the shamefully-hoist option enabled, I've managed to resolve the situation with Metro and @rnx-kit/metro-resolver-symlinks, but I find myself at an impasse with webpack.

For this, I have 2 suggestions:
1. Try adding `node-linker=hoisted` to your `.npmrc`.
2. Don't use webpack for new projects. Try Vite.

> Furthermore, any guidance on resolving the webpack issue within the context of a React Native monorepo using pnpm would be greatly appreciated.

I'm not familiar with React Native so I don't think I can give any advice.

**Comment by zkochan** [comment]
It works as expected. As @KSXGitHub said, the symink inside `.pnpm` is correctly pointing to `css-select` v2. If you need hoisting identical to the one used by Yarn, you need to use the `node-linker=hoisted` setting.
