### ISSUE TITLE
ffprobe Binary Lacks Execute Permissions When Installed in a Second Directory with pnpm

### ISSUE THREAD

**Issue by shirser121** [pnpm/pnpm#7746]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

Install `@ffprobe-installer/ffprobe` using pnpm for the first time in a specific store directory: [`pnpm add ffprobe`].

Move to another folder with another package.json

Reinstall `@ffprobe-installer/ffprobe`

Try to use ffprobe in the second directory

### Describe the Bug

After installing ffprobe in the second directory, the ffprobe binary does not have execute permissions, resulting in a permission error when attempting to run it. The lack of execute permissions suggests a potential issue with how pnpm is setting permissions for binaries installed in multiple locations.
The postinstall script give the permissions only on the first install

### Expected Behavior

The ffprobe binary should have execute permissions in both the first and second directories after installation, allowing it to be run without any manual changes to permissions.

### Which Node.js version are you using?

18.18.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 20.4

**Comment by zkochan** [comment]
PR: https://github.com/pnpm/pnpm/pull/8625
