### ISSUE TITLE
Multiple copies of the same dependency present in workspace

### ISSUE THREAD

**Issue by Brendonovich** [pnpm/pnpm#7809]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/edit/stackblitz-starters-erjwyw?file=pnpm-lock.yaml

### Reproduction steps

`pnpm install` and notice the multiple versions of `vinxi` inside the lockfile.
<img width="513" alt="image" src="https://github.com/pnpm/pnpm/assets/14191578/8634ce5d-ce5a-4d01-b7a0-2129cce8afb4">

### Describe the Bug

Multiple copies of `vinxi` are in the lockfile and in `node_modules/.pnpm`, which is causing [builds to fail](https://github.com/nksaraf/vinxi/issues/77#issuecomment-1873560367).
I think this is similar to https://github.com/pnpm/pnpm/issues/5585.

### Expected Behavior

I'd expect that a single copy of `vinxi` is installed, even when accounting for different peer dependencies. I've tried using different combinations of `overrides`, `dedupe-peer-dependents`, and `resolve-peers-from-workspace-root`.

### Which Node.js version are you using?

v18.18.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/7830
