### ISSUE TITLE
Nested Typescript module declaration cannot be resolved

### ISSUE THREAD

**Issue by zaalbarxx** [pnpm/pnpm#7810]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.5

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/edit/vue3-vite-typescript-starter-xmpxti?file=package.json,src%2Fmain.ts,tsconfig.json

### Reproduction steps

Open terminal and type `pnpm type-check`

### Describe the Bug

There will be an error saying that 
```
src/main.ts:4:16 - error TS2664: Invalid module name in augmentation, module '@vue/runtime-core' cannot be found.

4 declare module '@vue/runtime-core' {
```
and
```
src/main.ts:24:11 - error TS2339: Property '$rollbar' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}, {}, string, {}>, {}, {}>'.

24       vm?.$rollbar?.error(err)
```
Second one is of coursed by the first one which is the inability to resolve the nested module.

### Expected Behavior

Generally speaking I assume that the problem lies within the fact that since `@vue/runtime-core` is a dependency of `vue` (and only `vue` is listed in dependencies) it is not installed in the root of `node_modules` thus causing the Typescript not to be able to resolve the module. It work correctly with yarn and npm (I guess due to the them installing nested dependencies in the `node_modules` root). Basically there should be no error here. Explicitly installing `@vue/runtime-core` package will obviously help, but is this the only viable solution here ?

It obviously may not be a bug, but a feature here, but I could not find any info regarding similar issues.

### Which Node.js version are you using?

18.18.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by RexSkz** [comment]
You can set `public-hoist-pattern` in your `.npmrc` file, and the error about `@vue/runtime-core` will gone:

```ini
public-hoist-pattern[]=@vue/runtime-core
```

For more information, please refer to the docs: https://pnpm.io/npmrc#public-hoist-pattern

P.S. There are still other errors in the link, but I think they are not related.

**Comment by zaalbarxx** [comment]
@RexSkz Wonderful, did not notice this in documentation. Anyway big thanks! Have a nice day. Cheers.
