### ISSUE TITLE
onlyBuiltDependenciesFile should log skipped postinstalls

### ISSUE THREAD

**Issue by TravisJRyan** [pnpm/pnpm#7815]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As an infrastructure maintainer in an enterprise environment, I want to enforce an [onlyBuildDependenciesFile ](https://pnpm.io/package_json#pnpmonlybuiltdependenciesfile) for users. But I've found that if I don't include a dependency in the file, it will correctly skip the postinstall, but it won't log what was skipped. I think this creates confusion for users.

Example: I start depending on "node-sass" but forget to include it in the onlyBuiltDependenciesFile. The postinstall gets skipped with no indication it was skipped, and I may end up facing hard-to-debug errors.

### Describe the solution you'd like

If I don't have "node-sass" in my onlyBuiltDependencies file and it skips the postinstall, a message should be logged. Something like `The following dependencies tried to perform postinstalls but were skipped: node-sass`

This way, I'm more likely to figure out the cause of (probable) bugs from missing postinstalls. It will also help me figure out if I have installed some malicious package that tried to run something.

### Describe the drawbacks of your solution

Too much logging is not ideal, but since onlyBuiltDependenciesFile is opt-in, I think anyone using this feature would want to see this and shouldn't be too spammy.

### Describe alternatives you've considered

This could be configurable by some debug level also, but my personal preference is this seems like something you'd always want to know. (Most folks just `pnpm i` and would want to see what was skipped right away.)

**Comment by zkochan** [comment]
Sounds good.

**Comment by zkochan** [comment]
Is this what you want? https://github.com/pnpm/pnpm/pull/7854

The message is not very prominent.

**Comment by TravisJRyan** [comment]
This will show up towards the end of the logging because builds happen last, correct? If so, I think this is fine for visibility.

**Comment by zkochan** [comment]
Yes, but before the installation summary. So, if you have many direct dependencies, you might need to scroll up to see it.

**Comment by zkochan** [comment]
you can check it in the latest v9 version.
