### ISSUE TITLE
Race condition in "@zkochan/cmd-shim" produces corrupted bin scripts

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#7833]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.5

### Which area(s) of pnpm are affected? (leave empty if unsure)

Package manager compatibility, Operating System (Windows, MacOS, Linux)

### Reproduction steps

**package.json**
```
{
  "name": "cmd-shim-repro",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "eslint": "~8.7.0",
    "eslint-newest": "npm:eslint@~8.23.1",
    "eslint-oldest": "npm:eslint@8.6.0"
  }
}
```

The above **package.json** occasionally produces corrupted files such as  `node_modules/.bin/eslint`, `node_modules/.bin/eslint.CMD`, etc. The race condition is easiest to encounter on Windows OS.

### Describe the Bug

The problem occurs when multiple packages define a `"bin"` script with the same name.  Usually this is a somewhat rare case of two different packages using the same name, but in our case the person was using an NPM alias `"eslint-newest": "npm:eslint@~8.23.1"` to install two versions side-by-side, which is a fairly common practice.

The data corruption occurs because PNPM attempts to write all files simultaneously:
[cmd-shim/src/index.ts](https://github.com/pnpm/cmd-shim/blob/b9c389b161cb4370f5deda9ff78df03a7a6683c2/src/index.ts#L229)
```ts
  return Promise.all(
    generatorAndExts.map((generatorAndExt) => writeShim(src, to + generatorAndExt.extension, srcRuntimeInfo, generatorAndExt.generator, opts_))
  )
```

Maybe the upstream NPM implementation does not have this problem, because it seems to only parallelize file extensions for one filename:
[cmd-shim/lib/index.js](https://github.com/npm/cmd-shim/blob/5598b4b5d04d42201543dc67b459f0a7db78c211/lib/index.js#L233)
```ts
  return Promise.all([
    writeFile(to + '.ps1', pwsh, 'utf8'),
    writeFile(to + '.cmd', cmd, 'utf8'),
    writeFile(to, sh, 'utf8'),
  ]).then(() => chmodShim(to))
```

### Expected Behavior

It's unclear which `.bin` script should win.  NPM 10 seems to choose the unaliased package, but I didn't have time to study it closely.

However it's certainly expected that PNPM's installation should be:
- deterministic; AND
- not corrupted

### Which Node.js version are you using?

v18.19.1

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by octogonz** [comment]
This race condition is also the cause of random install errors such as this:
```
 EPERM  EPERM: operation not permitted, open 'C:\cmd-shim-repro\node_modules\.bin\eslint'
```

**Comment by octogonz** [comment]
And the corrupted file will produce error messages such as this (because of extraneous `*)` at the end of the file buffer):
```
'*' is not recognized as an internal or external command,
operable program or batch file.
```

Or like this (because of extraneous `nt.js" %*)` at the end of the file buffer):
```
'nt.js" --config .eslintrc.js' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by KSXGitHub** [comment]
I have created https://github.com/pnpm/pnpm/pull/8126

**Comment by octogonz** [comment]
> I have created #8126

Thank you @KSXGitHub !
