### ISSUE TITLE
Set destination filename with pnpm pack

### ISSUE THREAD

**Issue by samchungy** [pnpm/pnpm#7834]
### Contribution

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

Hello Zoltan and pnpm crew 👋. I love pmpm.

I rely on knowing what the filename is following a pnpm pack and the only way I can programatically grab it is via the output of the command.

eg.

bundle=$(pnpm pack)

However, if you introduce a lifecycle script, it pollutes the output. Even when attempting to use --silent.

### Describe the solution you'd like

So, I would like to propose something like `--pack-destination-filename` to be able to pipe it to a static filename eg. package.tgz. Happy to implement it too.

### Describe the drawbacks of your solution

Not sure there are any

### Describe alternatives you've considered

Removing lifecycle script and calling build on my package manually before calling pack

**Comment by KillerJulian** [comment]
Current workaround for me:

```
mv $(pnpm pack) package.tgz
```

**Comment by samchungy** [comment]
> Current workaround for me:
> 
> ```
> mv $(pnpm pack) package.tgz
> ```

That doesn't work if your package has a `prepack` script.

My workaround looks like this: https://github.com/seek-oss/skuba/blob/952921c9c96b9ee1c844d513913b11b82d767a06/scripts/test-template.sh#L18
