### ISSUE TITLE
Alpine Linux - pnpm package

### ISSUE THREAD

**Issue by f3l1x** [pnpm/pnpm#784]
Hi.

Thank you for good job on pnpm. I was wondering about AlpineLinux package (aports). What do you think guys? I know that pnpm could be install via npm, otherwise yarn could be also and there's a package.

-----

https://git.alpinelinux.org/cgit/aports/tree/community/yarn/APKBUILD?h=3.6-stable

-----

I could help if you're interested.

Felix

**Comment by zkochan** [comment]
Hi, it would be awesome if you could help.

Currently, I concentrate on issues that have to be done to release pnpm v1

**Comment by jbergstroem** [comment]
To simplify this I think a "npm-less" installer would be beneficial. A tarball with all deps/etc.

**Comment by zkochan** [comment]
actually we already bundle all the deps with pnpm. So the package can be downloaded directly from the npm registry and unpacked. `node_modules` will be in `lib/node_modules` already.

**Comment by jbergstroem** [comment]
> @zkochan said: 
> actually we already bundle all the deps with pnpm. 

I need to stop asking things before I actually spend time looking into it. Sorry. I will give it a go on a [docker image we use to test our stack with](https://github.com/pageload/nodejs-circleci) once I've finished all failures related to dependency flatting. If it works out well an alpine package is straightforward.

**Comment by zkochan** [comment]
It is not an alpine package but there is now a standalone script that allows installing pnpm w/o npm:

```
curl -L https://unpkg.com/@pnpm/self-installer | node
```

**Comment by jbergstroem** [comment]
@zkochan was looking around the other day for a docker image that bakes node/pnpm and is relatively up to date. Perhaps it could make sense to offer such an alternative (officially blessed from pnpm)? We'd essentially automate pushing on new pnpm/node versions and stick to node LTS or similar. Thoughts?

**Comment by zkochan** [comment]
that would be great to have

**Comment by jbergstroem** [comment]
@zkochan was looking around the other day for a docker image that bakes node/pnpm and is relatively up to date. Perhaps it could make sense to offer such an alternative (officially blessed from pnpm)? We'd essentially automate pushing on new pnpm/node versions and stick to node LTS or similar. Thoughts?

**Comment by jbergstroem** [comment]
> @zkochan said: that would be great to have

Let me see what I can do

**Comment by qm3ster** [comment]
Has the blessed docker image taken place yet?

**Comment by jbergstroem** [comment]
> Has the blessed docker image taken place yet?

It's safe to say I didn't finish. It still makes sense to me so I'll see if I can get something done the coming week.

**Comment by anicolaides** [comment]
What's the status on this?

**Comment by jbergstroem** [comment]
From my end its safe to say I dropped it.

**Comment by zkochan** [comment]
Just use this from the [installation page](https://pnpm.io/installation#using-a-standalone-script):

```
curl -fsSL https://get.pnpm.io/install.sh | sh -
```

It will install a pnpm executable that works without Node.js or npm preinstalled.

**Comment by anicolaides** [comment]
> Just use this from the [installation page](https://pnpm.io/installation#using-a-standalone-script):
> 
> ```
> curl -fsSL https://get.pnpm.io/install.sh | sh -
> ```
> 
> It will install a pnpm executable that works without Node.js or npm preinstalled.

Seems like the script isn't compatible with Alpine Linux out of the box see https://github.com/pnpm/pnpm/issues/3820#issuecomment-1091287099.

I've managed to get it working with the following:
```dockerfile
# Dockerfile
RUN apk add build-base libc6-compat gcompat curl && \
    curl -fsSL https://get.pnpm.io/install.sh | ash -

RUN mv /root/.local/share/pnpm/pnpm /usr/bin/
```
Thanks!

**Comment by Ponjimon** [comment]
@anicolaides Hm, weird, I get a `Segmentation fault` error when running this command and `sh: /tmp/tmp.NoePEo/pnpm: not found` when running the command from the pnpm documentation using Alpine 3.15

**Comment by hugomcm** [comment]
I'm getting a seg fault here too, using docker container with Alpine 3.15.

`# apk add --no-cache build-base libc6-compat gcompat curl`
`# curl -fsSL https://get.pnpm.io/install.sh | sh -`

Output:
==> Extracting pnpm binaries 7.1.9
Segmentation fault
Install Error!

**Comment by sombochea** [comment]
> I'm getting a seg fault here too, using docker container with Alpine 3.15.
> 
> `# apk add --no-cache build-base libc6-compat gcompat curl` `# curl -fsSL https://get.pnpm.io/install.sh | sh -`
> 
> Output: ==> Extracting pnpm binaries 7.1.9 Segmentation fault Install Error!
> 
> This works for me: `# curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v${PNPM_VERSION}/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;`
> 
> On Dockerfile:
> 
> ```
> ...
> ARG PNPM_VERSION=7.1.9
> ...
> ENV PNPM_HOME=/root/.local/share/pnpm
> ENV PATH=$PATH:$PNPM_HOME
> 
> RUN apk add --no-cache curl && \
>   curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v${PNPM_VERSION}/pnpm-linuxstatic-x64" -o /bin/pnpm && chmod +x /bin/pnpm && \
>   apk del curl
> ```

That's works fine for alpine. Thanks!

**Comment by zkochan** [comment]
maybe we should add it to the installation page.

**Comment by Hazmi35** [comment]
> I'm getting a seg fault here too, using docker container with Alpine 3.15.
> 
> `# apk add --no-cache build-base libc6-compat gcompat curl` `# curl -fsSL https://get.pnpm.io/install.sh | sh -`
> 
> Output: ==> Extracting pnpm binaries 7.1.9 Segmentation fault Install Error!
> 
> This works for me: `# curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v${PNPM_VERSION}/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;`
> 
> On Dockerfile:
> 
> ```
> ...
> ARG PNPM_VERSION=7.1.9
> ...
> ENV PNPM_HOME=/root/.local/share/pnpm
> ENV PATH=$PATH:$PNPM_HOME
> 
> RUN apk add --no-cache curl && \
>   curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v${PNPM_VERSION}/pnpm-linuxstatic-x64" -o /bin/pnpm && chmod +x /bin/pnpm && \
>   apk del curl
> ```

You can use this URL to get the latest pnpm release ([REF](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases)):
`https://github.com/pnpm/pnpm/releases/download/latest/pnpm-linuxstatic-x64`

**Comment by kaminskypavel** [comment]
@zkochan - just to let you know , I've tried to run the installation script you've added to the docs , 
inside a **`node:alpine`** docker image and am still getting the same error 

> #0 3.183  ERROR  Unable to find the global bin directory
> #0 3.190 Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 
the only way I could find to bypass is by adding the ENV settings as suggested by @Hazmi35 

```
ENV PNPM_HOME=/root/.local/share/pnpm    <----
ENV PATH=$PATH:$PNPM_HOME                <----

RUN apk add --no-cache curl && \
    curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm && chmod +x /bin/pnpm && \
    apk del curl

```

**Comment by o-az** [comment]
Using corepack

```Dockerfile
FROM node:18.12.1-alpine
# ...
RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install # etc
```

**Comment by karlhorky** [comment]
Using `corepack` works, @f3l1x @zkochan can this issue be closed now? Or should this be added somewhere to the docs?

**Comment by f3l1x** [comment]
I think it can be closed. Thank you.

**Comment by trm217** [comment]
Using corepack doesn't work for me with node:18.15-alpine.
When I use pnpm i i get the following error after trying to set it up using corepack:
```
[builder 4/6] RUN pnpm i -g turbo                     
#17 1.220  ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory
#17 1.220 
#17 1.220 Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH
```

**Comment by karlhorky** [comment]
Can you share your full Dockerfile? I edited my post above where I used it to install local dependencies

**Comment by gkatsanos** [comment]
Corepack also fails for me, 
Dockerfile:
```
FROM docker-ro.visable.com/wlw_node:16.13.0-alpine

ENV GITHUB_TOKEN none
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ENV NUXT_PUBLIC_PATH=/requests-frontend/_nuxt/

WORKDIR /app

COPY package* /app/
COPY pnpm-lock.yaml /app/
COPY .npmrc /app/

# install pnpm=
RUN corepack enable && corepack prepare pnpm@latest --activate

# mount the secret, use it to create ~/.npmrc with token
RUN --mount=type=secret,id=github_token GITHUB_TOKEN=$(cat /run/secrets/github_token) \
    && pnpm install

COPY . /app
RUN pnpm build

EXPOSE ${NUXT_PORT}

CMD [ "pnpm", "start" ]
```


```
#11 [stage-0 6/9] RUN corepack enable && corepack prepare pnpm@latest --activate
#11 0.219 Usage Error: Invalid package manager specification in CLI arguments; expected a semver version
#11 0.219 
#11 0.219 $ corepack prepare [--activate] [--all] [--json] [-o,--output] ...
#11 ERROR: process "/bin/sh -c corepack enable && corepack prepare pnpm@latest --activate" did not complete successfully: exit code: 1
------
 > [stage-0 6/9] RUN corepack enable && corepack prepare pnpm@latest --activate:
#11 0.219 Usage Error: Invalid package manager specification in CLI arguments; expected a semver version
#11 0.219 
#11 0.219 $ corepack prepare [--activate] [--all] [--json] [-o,--output] ...
------
```

**Comment by karlhorky** [comment]
Oh, wonder if the problem is that you're using an older version of Node.js? (16.13.0)

Check out the `Dockerfile` and the logs in [my message above](https://github.com/pnpm/pnpm/issues/784#issuecomment-1461848639) (I edited the logs there)

**Comment by gkatsanos** [comment]
Yes, I downgraded pnpm to 7.x and it worked. Thank you

**Comment by karlhorky** [comment]
> @trm217 When I use pnpm i i get the following error after trying to set it up using corepack:

[pnpm no longer recommends Corepack](https://github.com/pnpm/pnpm/issues/11732#issuecomment-5267508169) - so for Alpine Linux instead set up `pnpm add --global` using `get-pnpm`. The commands below avoid the `ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory` errors (see [this Dockerfile](https://github.com/upleveled/preflight/blob/2a8d4dde748806b2b666ecd60cbe88b0c1358a4b/Dockerfile)):

```dockerfile
FROM node:lts-alpine

# Install pnpm on Alpine Linux using get-pnpm
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
WORKDIR /
COPY package.json /app/
ENV PNPM_HOME=/pnpm
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN ENV="$HOME/.shrc" SHELL=/bin/sh npx --yes get-pnpm \
  "$(node --input-type=module --eval \
    'console.log((await import("/app/package.json", { with: { type: "json" } })).default.devEngines.packageManager.version)')"

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest
```

`WORKDIR /` runs `npx get-pnpm` from `/` to prevent `npx` erroring with `EBADDEVENGINES` from `devEngines.packageManager` in `/app/package.json`.

Set your pnpm version in `package.json` via `devEngines.packageManager`:

```json
{
  "devEngines": {
    "packageManager": {
      "name": "pnpm",
      "version": "11.26.0",
      "onFail": "download"
    }
  }
}
```

<details>

<summary>Earlier version: pnpm v11+ with Corepack</summary>

```dockerfile
FROM node:lts-alpine

# Enable `pnpm add --global` on Alpine Linux by setting
# a dedicated pnpm home directory and adding its bin directory to $PATH
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
ENV PNPM_HOME=/pnpm
ENV PATH="$PNPM_HOME/bin:$PATH"

# Install pnpm with corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest
```

</details>

<details>

<summary>Earlier version: pnpm <=v10 with Corepack</summary>

```dockerfile
FROM node:lts-alpine

# Install pnpm with corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# Enable `pnpm add --global` on Alpine Linux by setting
# home location environment variable to a location already in $PATH
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
ENV PNPM_HOME=/usr/local/bin

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest
```

This was developed thanks to the comment by @anomiex and [the tip](https://github.com/pnpm/pnpm/issues/4495#issuecomment-1297010385) from @misaon over in https://github.com/pnpm/pnpm/issues/4495

</details>
