### ISSUE TITLE
`pnpm licenses ls` does not list optionalDependencies of dependencies

### ISSUE THREAD

**Issue by BlueGreenMagick** [pnpm/pnpm#7846]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Add as dependency some module that has an `optionalDependencies`

```sh
pnpm init
pnpm add esbuild
pnpm install

pnpm licenses ls
```

### Describe the Bug

optional dependencies of dependencies are not listed when using `pnpm licenses list`.

In above reproduction steps, `esbuild` has many `optionalDependencies`, but they don't show up in `pnpm licenses list`. In contrast, they show up when you run `pnpm list --depth 9`.

### Expected Behavior

The list of licenses of project dependencies generation should be conservative, so optional dependencies of dependencies should be listed as well.

If the user wants to turn off all optional dependencies, they would be able to do by passing `--no-optional` argument.

### Which Node.js version are you using?

20.11.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by weyert** [comment]
It's listing it for me:
```
┌───────────────────────┬─────────┐
│ Package               │ License │
├───────────────────────┼─────────┤
│ @esbuild/darwin-arm64 │ MIT     │
├───────────────────────┼─────────┤
│ esbuild               │ MIT     │
└───────────────────────┴─────────┘
```

Do you mean you want to also list the optional dependencies for other operation systems and cpus? Above you would expect it to also list the non-macOS optional dependencies such for OpenBSD or Win32?

**Comment by BlueGreenMagick** [comment]
My bad, I confused it with something else.
