### ISSUE TITLE
`corepack pnpm@<version>` doesn't work anymore.

### ISSUE THREAD

**Issue by Guerteltier** [pnpm/pnpm#7849]
### Last pnpm version that worked

v8.15.6

### pnpm version

v9.0.0-beta.2

### Code to reproduce the issue

`corepack pnpm@9.0.0-beta.2 install`

### Expected behavior

It works.

### Actual behavior

`ERR_PNPM_BAD_PM_VERSION  This project is configured to use v8.15.6 of pnpm. Your current pnpm is v9.0.0-beta.2`

### Additional information

Being able to do this is a deliberate feature of Corepack.
> `corepack <binary name>[@<version>] [... args]`
> This meta-command runs the specified package manager in the local folder. You can use it to force an install to run with a given version, which can be useful when looking for regressions.

[Source](https://github.com/nodejs/corepack#utility-commands)

### Node.js version

v18.19.1

### Operating System

Linux

**Comment by zkochan** [comment]
@arcanis is this true? How should we ignore the check in this case?

**Comment by zkochan** [comment]
Got a response privately. We can disable the check if the COREPACK_HOME env variable is set.

**Comment by zkochan** [comment]
The fix didn't work

**Comment by arcanis** [comment]
Apologies, I meant `COREPACK_ROOT`, not `COREPACK_HOME`; see [here](https://github.com/nodejs/corepack):

> `COREPACK_ROOT` has no functional impact on Corepack itself; it's automatically being set in your environment by Corepack when it shells out to the underlying package managers, so that they can feature-detect its presence (useful for commands like `yarn init`).
