### ISSUE TITLE
Very slow interactive upgrade on linux

### ISSUE THREAD

**Issue by akarmes** [pnpm/pnpm#7860]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Not sure what to put here, any suggestions how can I enable verbose output to show more info? 

Anyway, I've prepared the repo with package.json. Running `pnpm up -i` on it easily takes 30s before it renders packages that can be updated. Repo URL: https://github.com/akarmes/slow-pnpm-upgrade

### Describe the Bug

I've recently started working from linux PC coming from macos laptop and noticed that interactive upgrade `pnpm up -i` takes 30s to display anything, which is about 15x slower than on outdated laptop. Current OS is Arch / Manjaro on 6.6.24-1 Linux kernel, btrfs filesystem.

### Expected Behavior

Comparing times with 5 different developers, `pnpm up -i` should take about ~2s 

### Which Node.js version are you using?

v20.11.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Linux 6.6.24-1-MANJARO with btrfs filesystem

**Comment by mcmxcdev** [comment]
I cloned your repro, ran `pnpm i` and then `pnpm up -i` on Ubuntu 23.10

The interactive upgrade selection took 2–4 seconds to show up for me, so I cannot reproduce your experience.

Note that this command depends a lot on the speed of your internet, so that might be the issue in your case.
