### ISSUE TITLE
[Suggestion] Clean old modules in global store

### ISSUE THREAD

**Issue by inDream** [pnpm/pnpm#788]
After upgrade modules to new version, the old modules would not be removed since there's no global dependencies list. I would suggest add this feature before version 1.0 as this is a breaking change.

My though about new install procedures:
1. Save the folder/shrinkwrap.yaml path (as json/yaml/hard link) in global store after installed packages
2. Clean up old modules when `npm install/uninstall (--save)` (optional with flag)
3. Use `pnpm store clean` to check all folder's shrinkwrap.yaml to remove non-dependent modules

Related: #297 #458 #430 #658

**Comment by zkochan** [comment]
This already works

We have a `store.yaml` file in the root of the store with info about all dependent projects: https://github.com/pnpm/sample-project/blob/master/.pnpm-store/1/store.yaml

and we remove packages if they are not used anywhere in the system. This piece of code does it: https://github.com/pnpm/pnpm/blob/master/src/api/removeOrphanPkgs.ts#L33-L39

**Comment by inDream** [comment]
I have faced some bug in windows, install something not success.
So I would remove the `node_modules` folder manually with the hard linked global store files,
this might affect the global `store.yaml`.
Is there any command to manual check the store status & a way to safely remove all modules inside `node_modules`?

**Comment by zkochan** [comment]
Did you delete the global store? In that case, you just lose the references to the projects that use the store. Packages will remain in the projects and after you run `pnpm install` in one of those projects, packages will relink from the global store

**Comment by inDream** [comment]
I delete local store but may be I install without admin permission so it removed global store files. When I run `pnpm install` it shows `Refetching [path] to store, as it was modified`.

**Comment by inDream** [comment]
@zkochan Is there a command for safely remove all installed modules inside current folder?

**Comment by zkochan** [comment]
no, currently there is only `pnpm uninstall ...pkgs`. So you have to specify each package that you want to uninstall

**Comment by zkochan** [comment]
@inDream, in [v1.8.0](https://github.com/pnpm/pnpm/releases/tag/v1.8.0) there's a new command now: `pnpm store prune`. So if you remove a project's `node_modules` manually (`rm -rf node_modules`), you can run `pnpm store prune` and all the unreferenced packages will be removed from the store.

**Comment by inDream** [comment]
@zkochan Thanks for the new feature.
