### ISSUE TITLE
Global executable installed by pnpm cannot be found

### ISSUE THREAD

**Issue by louy2** [pnpm/pnpm#792]
### pnpm version:
0.69.3

### Code to reproduce the issue:
```
pnpm install -g truffle
mkdir tmp-truffle && cd tmp-truffle && truffle init
```

### Expected behavior:
Truffle script is found and initiates a template

### Actual behavior:
```
module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/pnpm-global/node_modules/truffle/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

### Additional information:
- node v6.10.3
- Alpine Linux 3.6

Seems to be a linking issue?

**Comment by zkochan** [comment]
This location of the global package is weird '/usr/pnpm-global/node_modules/truffle/cli.js'

What does `npm c get prefix` return on you environment?

**Comment by louy2** [comment]
`/usr`

**Comment by zkochan** [comment]
Could you please retry with the latest pnpm?

**Comment by louy2** [comment]
I don't have the system with me anymore, so I am closing it as irrelevant now.

**Comment by Bleser92** [comment]
@zkochan 

pnpm: 1.35.7
node: v8.10.0
npm: 5.6.0
OS: kde-neon 5.12.2

`prefix=/home/bleser/.npm`
`store=/home/bleser/.npm/.pnpm-store/`

```
$ pnpm i -g typescript
module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/pnpm-global/1/node_modules/pnpm/lib/bin/pnpm.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I want to install packages without the Roth command, but I ran into this problem. Tell me what I did wrong?
