### ISSUE TITLE
Installing pnpm v8.15.7 still installs `tar` version 6.2.0 instead of 6.2.1

### ISSUE THREAD

**Issue by gcampbell-msft** [pnpm/pnpm#7939]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

I don't believe the above is needed because it's specific to 8.15.7. 

### pnpm version

v8.15.7

### Link to the code that reproduces this issue or a replay of the bug

See repro steps

### Reproduction steps

Assumptions: You already have `npm` installed

1. Open a test folder, this can be an empty folder.
2. Run `npm install pnpm@8.15.7`
3. Navigate to and open the `node_modules\pnpm\dist\node_modules\tar\package.json`
4. See that the version is 6.2.0, instead of the expected 6.2.1. I expected it to be 6.2.1 based on [this file](https://github.com/pnpm/pnpm/blob/v8.15.7/pnpm-lock.yaml#L4962).

### Describe the Bug

`tar` version `6.2.0` is being installed with `pnpm` `8.15.7` rather than `tar` `6.2.1`

### Expected Behavior

The correct version based on the [code here](https://github.com/pnpm/pnpm/blob/v8.15.7/pnpm-lock.yaml#L4962) is installed.

### Which Node.js version are you using?

16.20.2 and 16.14.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
The latest version of pnpm doesn't have this problem.

**Comment by zkochan** [comment]
I'll publish a fix to v8

**Comment by gcampbell-msft** [comment]
@zkochan Great! I'll keep an eye out for that. A notification on this thread when that is published would also be hugely helpful. I appreciate it.

**Comment by gcampbell-msft** [comment]
@zkochan Just to give some more context on our hope for when this is available, we have an internal due date of May 10th that we'd need this update for. If it's possible to have this done by then, that'd be great. Thanks!

**Comment by zkochan** [comment]
ok

**Comment by zkochan** [comment]
:ship: 8.15.8

**Comment by gcampbell-msft** [comment]
@zkochan Thanks! I appreciate your help
