### ISSUE TITLE
pnpm v9 install failure when esbuild versions mismatch

### ISSUE THREAD

**Issue by olegafx** [pnpm/pnpm#7943]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

`v9`

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, CLI

### Reproduction steps

Add this `package.json`:
```
{
  "name": "pnpm-v9-esbuild-error",
  "version": "1.0.0",
  "private": true,
  "author": "Oleg Kislitsyn",
  "dependencies": {
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.6.17",
    "storybook": "^7.6.17",
    "vite": "5.2.8"
  },
  "scripts": {
  },
  "engines": {
    "node": "^18.16.0"
  }
}
```

Remove `node_modules`, remove `lockfile`  and clean `pnpm` `cache`:
```
rm -rf node_modules
rm pnpm-lock.yaml
pnpm store prune
```

Try to install dependencies:
```
pnpm install
```

### Describe the Bug

On `v9` you'll see an error like this:

```
Packages: +777
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 835, reused 0, downloaded 777, added 777, done
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 551ms
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, failed in 549ms
.../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
│ /Users/olegafx/code/pnpm-v9-esbuild-error/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/install.js:132
│     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
│           ^
│ Error: Expected "0.18.20" but got "0.20.2"
│     at validateBinaryVersion (/Users/olegafx/code/pnpm-v9-esbuild-error/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/install.js:132:11)
│     at /Users/olegafx/code/pnpm-v9-esbuild-error/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/install.js:285:5
│ Node.js v18.16.0
└─ Failed in 549ms at /Users/olegafx/code/pnpm-v9-esbuild-error/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild
 ELIFECYCLE  Command failed with exit code 1.
```
 
On `v8` it was successful:

```
Packages: +777
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 835, reused 0, downloaded 777, added 777, done
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 189ms
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, done in 371ms

devDependencies:
+ @storybook/addon-essentials 7.6.17 (8.0.8 is available)
+ storybook 7.6.17 (8.0.8 is available)
+ vite 5.2.8 (5.2.9 is available)
```

And most probably it's related to a [bug](https://github.com/storybookjs/storybook/issues/26453) in Storybook. However, if you remove `@storybook/addon-essentials` and try to install again, it won't raise any errors:

```
pnpm install
Packages: +629
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 687, reused 629, downloaded 0, added 0, done
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, done in 186ms
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 154ms
Done in 6.6s
```

And dependency tree would look like this:

```
devDependencies:
storybook 7.6.17
└─┬ @storybook/cli 7.6.17
  ├─┬ @storybook/core-common 7.6.17
  │ ├── esbuild 0.18.20
  │ └─┬ esbuild-register 3.5.0
  │   └── esbuild 0.18.20 peer
  ├─┬ @storybook/core-server 7.6.17
  │ ├─┬ @storybook/builder-manager 7.6.17
  │ │ ├─┬ @storybook/core-common 7.6.17
  │ │ │ ├── esbuild 0.18.20
  │ │ │ └─┬ esbuild-register 3.5.0
  │ │ │   └── esbuild 0.18.20 peer
  │ │ ├─┬ @yarnpkg/esbuild-plugin-pnp 3.0.0-rc.15
  │ │ │ └── esbuild 0.18.20 peer
  │ │ └── esbuild 0.18.20
  │ ├─┬ @storybook/core-common 7.6.17
  │ │ ├── esbuild 0.18.20
  │ │ └─┬ esbuild-register 3.5.0
  │ │   └── esbuild 0.18.20 peer
  │ └─┬ @storybook/telemetry 7.6.17
  │   └─┬ @storybook/core-common 7.6.17
  │     ├── esbuild 0.18.20
  │     └─┬ esbuild-register 3.5.0
  │       └── esbuild 0.18.20 peer
  └─┬ @storybook/telemetry 7.6.17
    └─┬ @storybook/core-common 7.6.17
      ├── esbuild 0.18.20
      └─┬ esbuild-register 3.5.0
        └── esbuild 0.18.20 peer
vite 5.2.8
└── esbuild 0.20.2
```

Using `overrides` helps. But it could possibly bring other hidden errors due using wrong version of `esbuild`.

### Expected Behavior

On `v9` it needs to correctly install different versions of `esbuild`.

### Which Node.js version are you using?

18.16.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
I don't know yet what the issue is but it seems to work if the lockfile is created first. Like this:

```
pnpm install --lockfile-only
pnpm install
```

**Comment by zkochan** [comment]
:ship: 9.0.2

**Comment by olegafx** [comment]
It worked like a charm! Thank you, Zoltan, you're the best! 💪🏻

**Comment by aholland** [comment]
Oh good. I found myself having to put `"esbuild": "0.20.2"` in my TurboRepo monorepo's root package file devDependencies just to make an install work yesterday. Thanks for fixing this so quickly 👍

**Comment by rgripper** [comment]
Unfortunately I experience this in Github actions with pnpm 9.1.1. I'm not using esbuild directly, but there are several deps that do.

![image](https://github.com/pnpm/pnpm/assets/127960008/c9538b9d-adc2-40d7-a6fb-2bae1476cbd7)
![image](https://github.com/pnpm/pnpm/assets/127960008/fa6d2864-99be-4d54-b27a-41d06c609395)

**Comment by david10sing** [comment]
Having this issue and I've raised it in the esbuild repo [here](https://github.com/evanw/esbuild/issues/3796#issue-2339506420) but have been forwarded to pnpm.

Is it possible to look into this or at least point me towards where or how the resolving of the esbuild bin file works?

Thanks

**Comment by aminya** [comment]
I am still facing the issue with `pnpm 9.3.0`. Reported here:
https://github.com/evanw/esbuild/issues/3800#issuecomment-2163013371

@zkochan Is there anything I can do about this?

Here's my npmrc
```
node-linker=hoisted
package-manager-strict=false

```

**Comment by zkochan** [comment]
As you can see, the original issues with specific reproducible steps to reproduce has been fixed. If you have other issues, please create new issues with steps to reproduce.
