### ISSUE TITLE
grunt-browserify unable to find dependencies installed via pnpm; works with npm

### ISSUE THREAD

**Issue by kiranjholla** [pnpm/pnpm#795]
### Code to reproduce the issue:
**package.json**
```
{
  "name": "application",
  "version": "1.0.0",
  "description": "Application",
  "main": "Gruntfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "app"
  ],
  "devDependencies": {
    "browserify": "^13.1.1",
    "grunt": "^1.0.1",
    "grunt-browserify": "^5.0.0",
    "grunt-contrib-clean": "^1.0.0"
  },
  "dependencies": {
    "flux": "^3.1.0",
    "flux-dispatcher": "^1.1.5"
  }
}
```

**Gruntfile.js**
```
module.exports = function _gruntConfig(grunt) {
	grunt.initConfig({
		'pkg': grunt.file.readJSON('package.json'),
		'clean': {
			'build': ['dist/']
		},
		'browserify': {
			'libs': {
				'src': ['.'],
				'dest': 'dist/js/libs.js',
				'options': {
					'alias': [ // modules we want to require and exports
						'flux',
						'flux-dispatcher'
					]
				}
			}
		}
	});
	// load additional modules/  plugins
	grunt.loadNpmTasks('grunt-browserify');
	grunt.loadNpmTasks('grunt-contrib-clean');

	grunt.registerTask('build', ['clean:build', 'browserify:libs']);
}
```

### Expected behavior:
Run the following commands:
```
pnpm install
grunt build
```
Expect for this to successfully build a lib.js file within the dist folder.

### Actual behavior:
Gives the following error:
```
Running "browserify:libs" (browserify) task
>> Error: Cannot find module 'loose-envify' from 'D:\Dev\sample-pnpm\node_modules\.registry.npmjs.org\flux\3.1.2\node_modules\fbjs'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

### Additional information:
Running with the same setup but with `npm install` instead of a `pnpm install` works fine.

 - `node -v` prints: v7.9.0
 - Windows, OS X, or Linux?: Windows 10

**Comment by zkochan** [comment]
This seems like an issue with the way `browserify` resolves dependencies. `loose-envify` should be resolved from the realpath of `fbjs`, which is `D:\Dev\sample-pnpm\node_modules\.registry.npmjs.org\fbjs\0.8.12\fbjs`. This is how node resolves dependencies and this is how browserify/webpack should do it as well.

I could really use some help in these issues, there are a couple open for webpack as well.

**Comment by zkochan** [comment]
Hey @kjholla, I have found the issue and created a PR at [module-deps](https://github.com/browserify/module-deps/pull/133). As a temporary solution, you can use an installation hook to install module-deps from my fork.

You can creat `pnpmfile.js` in the root of your project with this content:

```js
'use strict'
module.exports = {
  hooks: {
    readPackage (pkg) {
      if (pkg.dependencies && pkg.dependencies['module-deps']) {
        pkg.dependencies['module-deps'] = 'zkochan/module-deps'
      }
      return pkg
    }
  }
}
```

Once the fix gets merged and published, there will be no need in the hook

**Comment by kjholla** [comment]
@zkochan Thanks for taking this so far! This is great progress.

**Comment by kjholla** [comment]
@zkochan Does the hook actualy need to be as below? I am getting a parsing error in the code you have provided.

```
'use strict'
module.exports = {
  hooks: {
    readPackage: function(pkg) {
      if (pkg.dependencies && pkg.dependencies['module-deps']) {
        pkg.dependencies['module-deps'] = 'zkochan/module-deps'
      }
      return pkg;
    }
  }
}
```

**Comment by zkochan** [comment]
I used Node.js 6. Your version is also fine if it works.

**Comment by kjholla** [comment]
I believe your version has some of the new ES6 constructs in it, and I have some tooling that doesn't support ES6 just yet. That's probably why the hook did not work for me.

**Comment by zkochan** [comment]
I confirm that the issue described here is fixed with `browserify@16` but `grunt-browserify` should update browserify in its package.json.

**Comment by zkochan** [comment]
while the fix is not merged, you can use `grunt-browserify` from my fork:

`pnpm i zkochan/grunt-browserify`

**Comment by zkochan** [comment]
They merged my PR. This will be fixed with the next release of grunt-browserify
