### ISSUE TITLE
pnpm add no longer working in 9.x with sub packages

### ISSUE THREAD

**Issue by jmarbutt** [pnpm/pnpm#7954]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.0.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, Package manager compatibility

### Reproduction steps

I have a pnpm workspace that is defined in like this:

```yaml
packages:
  - apps/*
  - packages/*
  - packages/config/*

```

In the packages folder I have a few packages like `@myapp/db` , `@myapp/common` and in the apps folder I have a `web` app and a `expo` app.

If I try to add any npm package like this:

```shell
/apps/web/pnpm add moment
```

I get the following error:

```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@myapp%2Fdb: Not Found - 404
 ```

### Describe the Bug

This was working in version 8.x of pnpm but now is broken in 9.x and is still broken in `9.0.2`

### Expected Behavior

It should install the npm package correctly 

### Which Node.js version are you using?

v21.7.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jakim929** [comment]
a major change of pnpm@9 is that [`link-workspace-packages`](https://pnpm.io/npmrc#link-workspace-packages) is`false` by default. 

see https://github.com/pnpm/pnpm/releases/tag/v9.0.0

for me I fixed this issue by prefixing versions for local packages with `workspace:` in package.json 

```json

"@myapp/db": "workspace:*" // correct
"@myapp/db": "*" // won't work unless you update `link-workspace-packages` to be `true` in `.npmrc`


```

**Comment by milanpajovic** [comment]
> a major change of pnpm@9 is that [`link-workspace-packages`](https://pnpm.io/npmrc#link-workspace-packages) is`false` by default.
> 
> see https://github.com/pnpm/pnpm/releases/tag/v9.0.0
> 
> for me I fixed this issue by prefixing versions for local packages with `workspace:` in package.json
> 
> ```json
> "@myapp/db": "workspace:*" // correct
> "@myapp/db": "*" // won't work unless you update `link-workspace-packages` to be `true` in `.npmrc`
> ```

Hey

We have monorepo structure using lerna.

Project won't build.

Error is the following:

 Local package.json exists, but node_modules missing, did you mean to install?
 
 I guess that issues is in linking dependencies
 Any idea?

**Comment by artemis-prime** [comment]
The node_modules of dependencies is empty.   This is an issue for modules that distribute untranspiled typescript, say...

Downgrading to 8.15.7 fixed it for me

**Comment by satishkumarsajjan** [comment]
Same problem for me. I am not able to install by using the command "pnpm add". But works fine when I add package name manually to the package.json file and run pnpm install.

**Comment by Cubelrti** [comment]
Same problem here. Like #8036, adding `link-workspace-packages=true` to `.npmrc` resolved issue.

But I think a better error message should be printed instead of checking remote NPM repositories and throwing 404 error like `ERR_PNPM_FETCH_404` which is quite confusing. 

The breaking change introduced by pnpm v8 -> v9 is hard to notice without reading changelog.
