### ISSUE TITLE
pnpm install --ignore-package-manager-version

### ISSUE THREAD

**Issue by Shinigami92** [pnpm/pnpm#7956]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a developer who maintain dependencies for many projects (company and open source), I often switch between repositories that do have different `"packageManager"` values declared.
But now I encounter errors like `ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.0.1 of pnpm. Your current pnpm is v9.0.2` where there is even only a bugfix inside pnpm and no behavior of building up `node_modules` or `pnpm-lock.yaml` has changed.

- I do not use corepack
- I have multiple computers (Arch Linux with pacman, Mac Pro with homebrew) where the pnpm version is not always the newest or in sync with each other

### Describe the solution you'd like

`v9.0.0` of pnpm shipped with a new "feature" `pnpm will now check the package.json file for a packageManager field.`
I would like to either bypass this behavior or at least pnpm should e.g. check semver range compatibility or e.g. the `pnpm-lock.yaml`'s `lockfileVersion`.

### Describe the drawbacks of your solution

It wont be strict anymore like on v9.0.0, so I would be okay if it needs to be explicitly bypassed via CLI flag or `.npmrc` setting

### Describe alternatives you've considered

_Different ways already described above._

**Comment by Shinigami92** [comment]
> I'm confused with the minor versions strict check. In my understanding this is not how semantic versioning works. So at least having the flag would be great.

The issue with `packageManager` is that it does not check for semver at all but always uses exact matching. This is not a problem by pnpm, but how the committee decided to implement `packageManager`.
https://nodejs.org/api/packages.html#packagemanager

**Comment by zkochan** [comment]
Sorry, we forgot to document it. You can disable it by setting `package-manager-strict` to `false`

**Comment by Shinigami92** [comment]
How do I use it?

```bash
pnpm install --package-manager-strict false
```

does not work 🤔

**Comment by ST-DDT** [comment]
See linked PR. there is an ENV property to set other than the package.json field.

**Comment by Shinigami92** [comment]
I did https://github.com/salsita/node-pg-migrate/pull/1105 for now, but I would prefer if it is possible to also do via CLI flag

**Comment by zkochan** [comment]
You can do `pnpm install --config.package-manager-strict=false`

**Comment by Shinigami92** [comment]
> You can do `pnpm install --config.package-manager-strict=false`

This works on direct terminal (`pnpm install --config.package-manager-strict=false`) ✅,
but not when I wrap inside a `package.json` script 👀 

e.g.
```json
{ 
  "scripts": {
    "preflight": "pnpm install --config.package-manager-strict=false && run-s format lint build"
  }
}
```

`pnpm run preflight`
