### ISSUE TITLE
`pnpm completion` command should not evaluate package.json `packageManager` field

### ISSUE THREAD

**Issue by davidjbng** [pnpm/pnpm#7959]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Operating System (Windows, MacOS, Linux)

### Reproduction steps

```sh
mkdir test && cd test
echo "{ \"packageManager\": \"npm@10.5.1\"}" > package.json
pnpm completion
```

> pnpm --version
9.0.1

### Describe the Bug

Running `pnpm completion` within a directory that has `packageManager` set to `yarn` or `npm` fails
> Usage Error: This project is configured to use npm
$ pnpm ...

Usually you have the completion command in your shell init file. The completion script should be generated even if my current working directory is not a pnpm package.

### Expected Behavior

The completion script is outputted.

### Which Node.js version are you using?

20.12.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Peeja** [comment]
There's a workaround that's not bad, though it would certainly be nicer to fix the root problem.

```sh
# In shell init file, instead of:
. <(pnpm completion zsh)

# Use:
. <(cd $HOME && pnpm completion zsh)
```

(That assumes `$HOME` doesn't have a `package.json`; any directory you're sure will exist and not have a non-pnpm `package.json` will do.)
