### ISSUE TITLE
Your pnpm version is incompatible with "renovate@37.303.2(typanion@3.14.0)".

### ISSUE THREAD

**Issue by moltar** [pnpm/pnpm#7965]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.3

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

- Install `renovate@37.303.2` with npm@8
- Bump pnpm to 9.0.3
- Run `pnpm install`

```
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "renovate@37.303.2(typanion@3.14.0)".

Expected version: ^8.0.0
Got: 9.0.3

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```

### Describe the Bug

It appears that pnpm cares about the dependencies' manifest has an engines.pnpm field specified.

### Expected Behavior

Pnpm should not care about the engines.pnpm of the dependenices.

### Which Node.js version are you using?

v18.19.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by moltar** [comment]
Note that `package-manager-strict` and `export COREPACK_ENABLE_STRICT=0` do not help.

**Comment by weyert** [comment]
Can you post your `package.json`? The error suggests its packageManager field but your `pnpm`-property in `engines` instead:
> This is happening because the package's manifest has _an engines.pnpm field specified_.

**Comment by zkochan** [comment]
The problem is with the renovate package. But I could reproduce it by running: `pnpm add renovate@37.303.2`

**Comment by moltar** [comment]
Thank you for the quick fix!!
