### ISSUE TITLE
Upgrading packages doesn't work when an aliased workspace dependency is present

### ISSUE THREAD

**Issue by mary-ext** [pnpm/pnpm#7975]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.4

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mary-ext/repro-pnpm-workspace-alias

### Reproduction steps

1. Run `pnpm up -r` on the workspace root

### Describe the Bug

pnpm complains that it can't find package `c` on the workspace, even though `c` is set to alias package `b`

```
Scope: all 3 workspace projects
/pnpm-workspace-alias/a:
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In a: "c@workspace:*" is in the dependencies but no package named "c" is present in the workspace

This error happened while installing a direct dependency of /pnpm-workspace-alias/a

Packages found in the workspace: a, b
```

### Expected Behavior

It should be able to run the upgrade

### Which Node.js version are you using?

v21.7.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Arch Linux (6.8.7-zen1-1.1-zen)

**Comment by mary-ext** [comment]
Package installation works fine, so I assumed this was a supported feature. Needed this because I'm publishing these workspace packages but wanted a shorter package name that can be imported by private packages.

**Comment by KSXGitHub** [comment]
> even though `c` is set to alias package `b`

The problem is that the name `c` only exists as an alias in a `package.json` of a workspace member. A different workspace member may have different alias for `b`. How is pnpm supposed to handle them all? What if the alias is the same as another package that also used? This is a design question.
