### ISSUE TITLE
pnpm ls

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#798]
Show lots of `UNMET DEPENDENCY` issues.

### pnpm version: 0.69.6
 - `node -v` prints: 8.1.1

---

A feature like `yarn why` would be cool too.

We could just use the `shrinkwrap.yaml` I guess. 

---

The shrinkwrap is missing `dependents` which makes it less useful by itself, but the `pnpm ls` command could calculate them from the shrinkwrap easily.

**Comment by zkochan** [comment]
`pnpm list` implemented in [v1.5.1](https://github.com/pnpm/pnpm/releases/tag/v1.5.1).

For the `why` command I suggest a separate issue

**Comment by TigersWay** [comment]
but 
`pnpm -g ls`
gives
`ERROR ENOENT: no such file or directory, open 'C:\Program Files\nodejs\pnpm-global\package.json'`
under Windows (10) as you may have guessed with pnpm v1.8.1

**Comment by zkochan** [comment]
@TigersWay I created an issue for this #862

**Comment by zkochan** [comment]
@TigersWay published fix with [v1.10.1](https://github.com/pnpm/pnpm/releases/tag/v1.10.1)
