### ISSUE TITLE
Errored with the message "Dependabot can't parse your pnpm-lock.yaml"

### ISSUE THREAD

**Issue by Theo-Messi** [pnpm/pnpm#7987]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.5

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Reproduction steps

Create "pnpm-lock.yaml" using "pnpm i" and commit it to the GitHub repository. Dependabot prompts "Error with message "Dependabot cannot parse your pnpm-lock.yaml""

### Describe the Bug

1

### Expected Behavior

1

### Which Node.js version are you using?

v21.1.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by bhb603** [comment]
Same issue. I believe Dependabot needs to be updated to support the new lockfile version: https://github.com/dependabot/dependabot-core/issues/9522

This issue with pnpm@9.0.5 is that it any `pnpm install` seemed to auto-migrate the lockfile to this new version.... 
Which is then incompatible...
