### ISSUE TITLE
v9.0.5 release ignores "frozen-lockfile" flag

### ISSUE THREAD

**Issue by jekanik** [pnpm/pnpm#7991]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Reproduction steps

npm i -g pnpm@9.0.5
pnpm install --frozen-lockfile

### Describe the Bug

Lockfile is updated even if "frozen-lockfile" flag is provided.

### Expected Behavior

Lockfile is not changed

### Which Node.js version are you using?

18.19.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
We'll fix it.

It shouldn't be a big issue as `--frozen-lockfile` happens mostly in CI envs, where an update to the lockfile will just be ignored.

**Comment by jekanik** [comment]
@zkochan thanks for response.
In some Teamcity builds we analyse used dependencies by parsing lockfile. And this scenario is started to fall after update to 9.0.5 :)
For now, we rollbacked to 9.0.4.

**Comment by AndreaPontrandolfo** [comment]
This issue is also present in 9.0.4 and is breaking our builds.
We had to revert back to 8.x.x.

**Comment by actraiser** [comment]
same here - builds break.

**Comment by zkochan** [comment]
:ship: 9.0.6
