### ISSUE TITLE
Change the way local packages are installed

### ISSUE THREAD

**Issue by qraynaud** [pnpm/pnpm#7998]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a developer, right now, I often stumbles on the issue of local packages with peerDeps. If I don’t want to use the same versions as the devDeps everywhere for those, then I can’t use the "normal" way and have to resort to `dependenciesMeta.*.injected: true` for this package. You have to think to use this option on every single package that uses it. It also requires you to use `pnpm i` each time you change something in the package.

### Describe the solution you'd like

I'm not sure it is a good idea. I'm throwing this idea out there because I think it is a least worth discussing.

We could do something like this:
1. not make a link in `node_modules/<package>` to the package dir
2. create instead a folder `node_modules/<package>` with inside a link for each top-level entries that would be added into the archive by `pnpm pack` from `node_modules/<package>/<entry>` to the corresponding package’s item (except `node_modules` if it would have been included)
3. handle `package/node_modules` exactly like what we would have done for any external package except for `bundledDeps` that would be ignored
4. add a link for each bundledDep from `node_modules/<package>/node_modules/<dep>` to the package’s corresponding `node_modules`
5. create as many of those folder as we would have created for a "normal" external dep

That way of doing things would have the following benefits:
- folder structure a lot nearer what would be created using a normal installation through npm, that would allow to catch more packaging mistakes
- support for peerDep a lot more akin for `workspace` and peerDep, thus removing the need for the `injected` option altogether (at least I think so)
- not too different of what is done now, so it would not break much expectations from users

### Describe the drawbacks of your solution

This would require user to run `pnpm i` again if they change their top-level entries included in the package. That’s rare but if that happens, they would need to run it to get the file included properly in the `.pnpm` structure.

### Describe alternatives you've considered

Make a link for each entry of the `pnpm pack` instead of only per top-level entries. That would require to reproduce the folder structure and only make links for files. That would allow for a perfect match between the packaged version and the version installed with `workspace:`. At least structure-wise.
But file removal or addition anywhere in the package structure would need a new `pnpm i` which I think is too disruptive for the current workflows. It is rare that the root item changes. Less so deeper in the package. Thus this seemed to me like the best compromise.
It could be proposed as an option in the root `package.json` though.

**Comment by levrik** [comment]
May I ask you why you closed this issue? I was stumbling across it while also searching for a better solution than injected deps.
