### ISSUE TITLE
ERROR EINVAL: invalid argument, readlink

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#800]
I'm getting these errors after running `pnpm link`. Its trying to call readlink on a link it just created, which is actually a folder...

```
 /Users/Vaughan/nvm/versions/node/v7.10.0/pnpm-global/node_modules/webpackerator -> /Users/Vaughan/dev-live/webpackerator
  ERROR EINVAL: invalid argument, readlink '/Users/Vaughan/nvm/versions/node/v7.10.0/pnpm-global/node_modules/webpackerator'
```

### Additional information:

 - `node -v` prints: 7/8
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
`/Users/Vaughan/nvm/versions/node/v7.10.0/pnpm-global/node_modules/webpackerator` - this is a folder?

you installed webpackerator globally and then linked?

**Comment by vjpr** [comment]
It happens around the time when I'm moving between versions of node with nvm. I'm not exactly sure of the cause, but its happened quite often.

Maybe its to do with nvm copying across the old global node_modules or something like that...

**Comment by zkochan** [comment]
I think this is the same issue as #843 and it was fixed in [v1.5.3](https://github.com/pnpm/pnpm/releases/tag/v1.5.3)

**Comment by zkochan** [comment]
if it wasn't fix, then feel free to reopen it

**Comment by Ncarmend** [comment]
Supprimer le dossier  .Next  puis npm run dev

**Comment by acesFatee** [comment]
just delete the next folder and hit `npm run dev`
