### ISSUE TITLE
The terminal crashes when using Ctrl+C to exit the process.

### ISSUE THREAD

**Issue by Kaidesuyoo** [pnpm/pnpm#8022]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9

### Reproduction steps

Run a Vue Vite project using pnpm run dev.
Press Ctrl+C to terminate the process.

### Describe the Bug

When I use Ctrl+C to exit the process, the terminal crashes. I'm not entirely sure if this should be considered a bug in Vite, but I didn't encounter this issue when using vite version 4.5.2. However, there is a high probability of encountering this situation in vite version 5.2.10.

It works fine when using npm.

![Snipaste_2024-04-26_20-47-50](https://github.com/pnpm/pnpm/assets/164149205/1ac88885-1f8e-479b-ae78-bab37b2479a7)

![Snipaste_2024-04-26_20-49-52](https://github.com/pnpm/pnpm/assets/164149205/09879ba4-b1b3-4823-8430-ebc676bcbcff)

![image](https://github.com/pnpm/pnpm/assets/164149205/88c15c3c-8ed6-47c1-88e9-88c121f02991)

System:
    OS: Windows 11 10.0.22635
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 19.59 GB / 31.91 GB
  Binaries:
    Node: 20.12.2 - D:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.6 - D:\Program Files\nodejs\pnpm.CMD
  npmPackages:
    vite: ^5.2.10 => 5.2.10

### Expected Behavior

Hope the terminal won't crash.

### Which Node.js version are you using?

v20.12.2

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by nachoaldamav** [comment]
Hi! I tested this myself and my terminal does not crash, I see that you are using Powershell 5, does the issue fix if you use the newer versions of Powershell?
![image](https://github.com/pnpm/pnpm/assets/22749943/843b40dd-1c63-41a5-838c-3217cc675fc1)

**Comment by Kaidesuyoo** [comment]
> Hi! I tested this myself and my terminal does not crash, I see that you are using Powershell 5, does the issue fix if you use the newer versions of Powershell? ![image](https://private-user-images.githubusercontent.com/22749943/326516648-843b40dd-1c63-41a5-838c-3217cc675fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MzkyNzEsIm5iZiI6MTcxNDQzODk3MSwicGF0aCI6Ii8yMjc0OTk0My8zMjY1MTY2NDgtODQzYjQwZGQtMWM2My00MWE1LTgzOGMtMzIxN2NjNjc1ZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0M2E4M2UxOGQzZWEzNTcxODU5NTJkMDZjZjA4MmQzZDMzMjVkYTg1MTZkZmEyMmU1NmU5ODUyMmM4OTkxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KVAp5fn8FvzKKiLOa_OcF013TAxfcCiGZiKujCWG4ek)

In both PowerShell 5 and 7, this issue occurs. However, I haven't seen anyone else report a similar problem. I suspect it might be a bug caused by some configuration settings on my personal computer. I'll test it on other computers when I have time. Therefore, I'll close this issue. Thank you for taking the time to answer my question.

**Comment by d4le-cooper** [comment]
i have the same issue. Did you resolve it?

**Comment by Kaidesuyoo** [comment]
> i have the same issue. Did you resolve it @Kaidesuyoo?

This may not be of much use to you, but after several system updates, this issue was automatically resolved.
