### ISSUE TITLE
Making installation faster on CI servers

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#803]
Installations on CI servers require less checks. With some assumptions, pnpm can work faster. Some ideas from Kat's [cipm](https://github.com/zkat/cipm) can be reused.

- [ ] unverified installation on CI servers #802

**Comment by rifler** [comment]
is this issue about `npm ci` command analogue in `pnpm`

**Comment by ExE-Boss** [comment]
`npm clean‑install` is equivalent to `pnpm install ‑‑frozen‑lockfile`.

**Comment by zkochan** [comment]
This was implemented I believe.
