### ISSUE TITLE
ERR_PNPM_FETCH_404 for workspace packages

### ISSUE THREAD

**Issue by ianchanning** [pnpm/pnpm#8036]
### Last pnpm version that worked

8.15.8

### pnpm version

9.0.6

### Code to reproduce the issue

Dockerfile:
```dockerfile
FROM node:20.9.0-alpine AS builder
ARG appDir=apps/graphql-service
WORKDIR /usr/src
RUN mkdir -p $appDir/src
COPY package*.json pnpm-*.yaml tsconfig.json nx.json ./
COPY libs/ ./libs
COPY $appDir/package.json $appDir/tsconfig.json ./$appDir/
COPY $appDir/src ./$appDir/src
# pnpm@9 fails here
RUN corepack enable && pnpm install --quiet
# this works
# RUN corepack enable && corepack install --global pnpm@8.15.8 && pnpm install --quiet
RUN pnpm build:graphql
RUN rm -rf node_modules nx.json && pnpm install --quiet --prod
```

### Expected behavior

pnpn install succeeds

### Actual behavior

```
#15 [builder  8/10] RUN npm install -g pnpm && pnpm install --quiet
#15 1.840 
#15 1.840 added 1 package in 1s
#15 1.842 
#15 1.842 1 package is looking for funding
#15 1.842   run `npm fund` for details
#15 1.843 npm notice 
#15 1.844 npm notice New minor version of npm available! 10.1.0 -> 10.6.0
#15 1.846 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.6.0>
#15 1.847 npm notice Run `npm install -g npm@10.6.0` to update!
#15 1.848 npm notice 
#15 2.406 Scope: all 8 workspace projects
#15 2.833 /usr/src/apps/rule-engine-service:
#15 2.833  ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@charphq%2Finflux: Not Found - 404
#15 2.833 
#15 2.833 This error happened while installing a direct dependency of /usr/src/apps/rule-engine-service
#15 2.833 
#15 2.833 @charphq/influx is not in the npm registry, or you have no permission to fetch it.
#15 2.833 
#15 2.833 No authorization header was set for the request.
#15 ERROR: process "/bin/sh -c npm install -g pnpm && pnpm install --quiet" did not complete successfully: exit code: 1
```

### Node.js version

20.12.2

### Operating System

Linux

**Comment by zkochan** [comment]
You need to either reference your workspace packages using the `workspace:` protocol in dependencies or change `link-workspace-packages` to `true` (this setting changed to `false` by default in v9).

**Comment by ianchanning** [comment]
@zkochan great, thanks for the quick answer. `workspace: *` in all of the `package.json` files fixes the problem.

Is there anyway to give warnings to people on v8 that this will break when they switch to v9?

I tried adding the [`.npmrc` file with `link-workspace-packages`](https://pnpm.io/npmrc#link-workspace-packages) both at the root of the project (which failed with the same error) and then next to each of the `package.json` files (which failed too with the same error):

```env
link-workspace-packages=true
```

For anyone else coming across this, here's a dummies guide of two options I used to solve it:

- Using [`workspace` protocol](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases) a search and replace for `"*"` &rarr; `"workspace:*"` in all the `package.json` files in our mono-repo fixed it
- Stay on version 8 if you can't upgrade
    ```Dockerfile
    RUN corepack enable && corepack install --global pnpm@8 && pnpm install --quiet
    ```
