### ISSUE TITLE
After updating to v9, pnpm checks only npm registry

### ISSUE THREAD

**Issue by danielleroux** [pnpm/pnpm#8042]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v9

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, CLI, Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/siemens/ix/actions/runs/8921770948/job/24502550629

### Reproduction steps

Create a mono repo e.g https://github.com/siemens/ix

Using `changeset` and `changeset-action` (workflow)

But can also reproduced on the local cli.

1. Before bump:
- packages
-      -   angular v1.2.0 (core is a dependency and a devDependency)
-      -   core v1.2.0 
2. Bump version of the repo `pnpm changeset version`
- packages
-      -   angular v1.2.1 (core is a dependency and a devDependency)
-      -   core v1.2.1 
4. Perform a pnpm install `pnpm i --lockfile-only`

Result:
```
/home/runner/work/ix/ix/packages/angular:
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @siemens/ix@~2.2.2

This error happened while installing a direct dependency of /home/runner/work/ix/ix/packages/angular

The latest release of @siemens/ix is "2.2.1".
```

### Describe the Bug

Looks pnpm v9 does not check if the version is existing within the workspace

### Expected Behavior

Should first check the workspace if the version is available there then try to contact remote registry

### Which Node.js version are you using?

v20.11.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
This is a breaking change that was mentioned in the [release notes](https://github.com/pnpm/pnpm/releases/tag/v9.0.0).

The default value of [link-workspace-packages](https://pnpm.io/npmrc#link-workspace-packages) changed to `false`.

**Comment by danielleroux** [comment]
Uff, didnt checked the notes. Thank you!
