### ISSUE TITLE
Officially support `omit` config setting from `npm`

### ISSUE THREAD

**Issue by jedwards1211** [pnpm/pnpm#8050]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a developer, I want fast installs so I use `—-no-optional`.  But it turns out to be inconvenient - later on if I add, update or install and forget to pass `—-no-optional`, pnpm complains that it will need to blow away everything and start over.

### Describe the solution you'd like

Support the `omit` config parameter from `npm`: `npm set omit optional`: https://docs.npmjs.com/cli/v10/using-npm/config#omit

Maybe `pnpm` supports this, but I can’t find any evidence that it does.

### Describe the drawbacks of your solution

NPM could change the name, values or behavior of this setting; if so, pnpm’s behavior would no longer match as expected.

On the other hand, pnpm probably should match npm’s behavior here because it honors many config options from `.npmrc`.

### Describe alternatives you've considered

Some kind of config option to set a list of options to always pass to install, update, etc?

**Comment by zkochan** [comment]
You can add this `.npmrc` to the root of your project:

```
optional=false
```

**Comment by jedwards1211** [comment]
Oh okay, that's good enough for me.  I'll make a PR to the docs
