### ISSUE TITLE
pnpm completion broken with corepack

### ISSUE THREAD

**Issue by isaacl** [pnpm/pnpm#8056]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

```sh
brew install node corepack
corepack enable
corepack use pnpm@latest
echo '[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true' >> .zprofile
```

***restart shell***

```plain
pnpm <tab tab>
```

### Describe the Bug

Although tab tab completion script is loaded, it does not work properly.

## Tab-tab behavior
```sh
~ pnpm <tab tab>
~ pnpm  ERR_PNPM_REDUNDANT_PARAMETERS \ The\ 1\ parameters\ after\ shell\ is\ not\ necessary
```

## Completion debug:
```zsh
# Note: I am using fnm, but I've verified this bug also exists in pure node/corepack setups
~ which pnpm
/Users/ilevy/Library/Caches/fnm_multishells/25073_1715009125780/bin/pnpm
~ print $_comps[pnpm]
_pnpm_completion
~ type _pnpm_completion
_pnpm_completion is a shell function from /Users/ilevy/.config/tabtab/zsh/pnpm.zsh
~ head -n5 /Users/ilevy/.config/tabtab/zsh/pnpm.zsh
###-begin-pnpm-completion-###
if type compdef &>/dev/null; then
  _pnpm_completion () {
    local reply
    local si=$IFS
```

Likely related to #7986.

### Expected Behavior

pnpm completion works properly, even under corepack.

### Which Node.js version are you using?

22.1.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
Are you using pnpm v9? pnpm v9 no longer uses tabtab for completion. Instead, you are supposed to run `pnpm completion bash > $COMPLETION_SCRIPT` or `pnpm completion bash >> ~/.bashrc`.

The caveat, however, is that this method is not compatible with pnpm v8 while corepack can automatically switch between major pnpm version. The only way and the only proper way to fix this is for corepack to provide its own completion script that would redirect commands to pnpm completion script (Like how completion script for `sudo` invokes completion script of the program it calls).

**Comment by isaacl** [comment]
Yes I'm using pnpm v9 exclusively now.

Thanks for the tip, this fixed my issue.
