### ISSUE TITLE
Feature Request: Option to Avoid Symbolic Links Without Hoisting

### ISSUE THREAD

**Issue by YassinEldeeb** [pnpm/pnpm#8062]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

Hello pnpm team,

I am writing to request a feature that would allow users to have actual copies of packages in their `node_modules` directories without the need for hoisting. This feature would provide a debugging experience similar to that of Yarn, where developers can directly modify packages in `node_modules` as they are copies and not symbolic links.

Currently, pnpm uses symbolic links extensively to manage dependencies, which is excellent for disk space management but can complicate debugging scenarios sometimes where developers need to modify dependency code directly in `node_modules`. The `--shamefully-hoist` option, while it does copy packages to `node_modules`, also changes the structure by hoisting packages, which is not desired in this case.

Thank you for considering this feature. I believe it could enhance pnpm's usability for a broader range of development workflows coming from Yarn, while maintaining its core benefits for those who do not use the new option.

### Describe the solution you'd like

An option that allows for copying packages into `node_modules` without altering their structure through hoisting. This would help in cases where:

- Developers are accustomed to debugging by directly modifying packages in `node_modules`.
- Tools or environments that do not play well with symbolic links or version-based directory structures (e.g., TypeScript server issues in VS Code when package versions change).

### Describe the drawbacks of your solution

I don't think there's any drawbacks, existing users are not affected, and users would have a new option to accommodate their development workflow.

While I understand that one of pnpm's strengths is efficient disk usage through symbolic links, providing an option for direct copying could accommodate workflows that rely heavily on direct manipulation of dependencies. This is especially relevant in complex applications where quick, iterative debugging by editing dependencies directly can significantly speed up development.

### Describe alternatives you've considered

Using `--shamefully-hoist`, but it also does hosting which I don't want.

**Comment by zkochan** [comment]
I don't understand your issue. If you don't want symlinks, use `node-linker=hoisted`. If you don't want hard links, use `package-import-method=clone-or-copy`.

There is not scenario in which a package manager uses neither hoisting nor symlinks.

**Comment by YassinEldeeb** [comment]
ah, thanks for pointing out this option `package-import-method=clone-or-copy`, I didn't know it existed!
I'll close the issue!

**Comment by rulatir** [comment]
`pnpm` is flat out ignoring `--shamefully-hoist`, `--config.node-linker=hoisted` and just creating symlinks anyway. Creating a portable, deployable bounce of the project is completely impossible. `pnpm` is effectively a development-only package manager (unless you use `pnpm deploy`, but that forces you to migrate to workspaces, and arm-twists you into giving up separately committable lockfiles).
