### ISSUE TITLE
`pnpm install` without input fails when already node_modules exists

### ISSUE THREAD

**Issue by septatrix** [pnpm/pnpm#8085]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.1.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://gist.github.com/septatrix/46a4df42e9c7c645a4b201f5db31bc48

### Reproduction steps

1. Clone the above repo and open it
1. Run `podman build .` (or docker)

### Describe the Bug

pnpm wants to recreate the node_modules directory and prompts for confirmation. As no input exists it directly fails (with an exit code of 0, i.e. success!) instead of using the default value (y). As a consequence the later commands, which assume that the installation was successful, will fail.

```
? The modules directory at "/app/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n)
```

### Expected Behavior

The installation should succeed (or pnpm should use an exit code of 1 indicating some kind of unexpected failure).

Alternatively pnpm should expose a flag which can be used to answer this prompt. Piping "y" into is is quite fragile and breaks assumptions of packages which query for input during installation. `--force` could also be used but is way more intrusive and should not be used for this.

### Which Node.js version are you using?

20.10

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Debian 12

**Comment by marcusball** [comment]
I just posted this on #7727 but I'll copy it here:

> This is a bit of a hack, but if you want to get around it, you can set the `CI` environment variable to `true` (see [here](https://github.com/watson/ci-info/blob/3e1488e98680f1f776785fe8708a157b7f00e568/index.js#L56) for alternate variables). I haven't found a way to use command line arguments, or pnpm config files, to change the package manager options, but [tricking it into detecting a CI build](https://github.com/pnpm/pnpm/blob/ef73c19f1523080f72a21f87b4b232c9af353fa7/pkg-manager/get-context/src/index.ts#L129) will [skip the prompt](https://github.com/pnpm/pnpm/blob/ef73c19f1523080f72a21f87b4b232c9af353fa7/pkg-manager/get-context/src/index.ts#L336).

**Comment by septatrix** [comment]
I just noticed that this does not happen when calling `pnpm fetch` with `.npmrc` already present - adding the file afterwards seems to invalidate the existing `node_modules`. So adjusting the order in the Dockerfile to add the rc file earlier resolved this. Regardless, thanks for your help :)
