### ISSUE TITLE
Error while running `pnpm run ...`

### ISSUE THREAD

**Issue by shrinktofit** [pnpm/pnpm#8088]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.1.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Package manager compatibility

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/shrinktofit/pnpm-issue

### Reproduction steps

Run followings:

```pwsh
pnpm i
pnpm run test
```

### Describe the Bug

Run the above snippet, then an error would be thrown. It seems like pnpm code want to modify a function object's name, which by default, is readonly.

![image](https://github.com/pnpm/pnpm/assets/28807867/9b51b0ab-a162-414e-9d87-a9b9d243a659)

### Expected Behavior

No error, everything works fine.

### Which Node.js version are you using?

22.1.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by btea** [comment]
Couldn't reproduce.

![image](https://github.com/pnpm/pnpm/assets/24516654/556ff28c-654f-4704-b593-65ad146dd352)

**Comment by shrinktofit** [comment]
It should be irrelevant from pnpm, sorry.
