### ISSUE TITLE
PNPM consider Turborepo packages as npm packages

### ISSUE THREAD

**Issue by jpmadrigal07** [pnpm/pnpm#8091]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

1. Make sure you have installed pnpm@9.0.1
2. Make sure you have a Vercel's Turborepo project that built using pnpm
3. Add custom package that can be installed in apps folder
![image](https://github.com/pnpm/pnpm/assets/20082606/c0464d3b-dc2d-4b94-bf43-40da0acaa0b4)
![image](https://github.com/pnpm/pnpm/assets/20082606/0b05783f-e06f-4770-840b-9748ec3dd696)
4. Then try to run `pnpm install` and you will get this error
![image](https://github.com/pnpm/pnpm/assets/20082606/e7b6e8ec-547b-44ea-ba67-aadf072d337c)

### Describe the Bug

The bug occurs when you are using pnpm 9, it considers all custom packages for Turborepo as an actual npm packages. I need to go back to pnpm 8 in order to fix the error.

### Expected Behavior

The pnpm 9 should not consider it as a npm packages, instead need to look at the packages folder also.

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by weyert** [comment]
Aren't you supposed to use `workspace:*` instead of `*`?

**Comment by ocavue** [comment]
> Aren't you supposed to use workspace:* instead of *?

Some third-party tools don't recognize PNPM's `workspace:*` version syntax, so I'm trying to not use `workspace:*`.

> You might have been relying on the link-workspace-packages being enabled by default in v8 but is disabled in v9. 

I tried to set `link-workspace-packages=true` in `.npmrc` but it still doesn't work. 

---

I've created another issue in the turborepo side (https://github.com/vercel/turbo/issues/8168), where you can find detailed reproduction steps. I'm not sure whether this is a PNPM bug or a turborepo bug, so I left my comment here too.

**Comment by jpmadrigal07** [comment]
@ocavue thanks
