### ISSUE TITLE
I cannot update version

### ISSUE THREAD

**Issue by chlbri** [pnpm/pnpm#8104]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

v8

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Store

### Reproduction steps

Install pnpm by homebrew
Update the pnpm by running command : pnpm install -g pnpm@latest
And when you type  :  "pnpm  -v", nothing is updated

### Describe the Bug

The pnpm version is still the previous one (v8.10.5)

`Nothing to stop. No server is running for the store at /Users/${USER}/.nvm/versions/node/v20.9.0/lib/node_modules/npm/pnpm/store/v3
The location of the currently running pnpm differs from the location where pnpm will be installed
 Current pnpm location: /opt/homebrew/bin`
 Target location: /Users/chlbri/.nvm/versions/node/v20.9.0/lib/node_modules/npm/pnpm

I try this command "pnpm add -g  pnpm --global-dir /Users/${USER}/.nvm/versions/node/v20.9.0/lib/node_modules/npm/pnpm" and this command " pnpm add -g  pnpm --global-dir /opt/homebrew/bin".
But when I run pnpm version, I get the same previous version

### Expected Behavior

`pnpm -v` will return v9.1.1

### Which Node.js version are you using?

v20.12.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by MartinRamm** [comment]
If `pnpm` is in `/opt/homebrew/bin`, you probably installed pnpm with [homebrew](https://brew.sh/). Try upgrading with the same package manager you used to install pnpm initially: `brew upgrade pnpm`.

**Comment by chlbri** [comment]
I will try it

**Comment by chlbri** [comment]
It works thanks !

**Comment by gitinthehole** [comment]
> If `pnpm` is in `/opt/homebrew/bin`, you probably installed pnpm with [homebrew](https://brew.sh/). Try upgrading with the same package manager you used to install pnpm initially: `brew upgrade pnpm`.

Thank you. This worked for me too.
