### ISSUE TITLE
Question: Why have hard links at all? Why not symlink directly to the central shared store?

### ISSUE THREAD

**Issue by kjholla** [pnpm/pnpm#813]
###Question: Why have hard links at all? Why not directly symlink to the central shared store on the disk?

I wanted to understand the rationale behind the way pnpm installs dependencies. My observation is that pnpm installs the dependencies as below:

```
node_modules/package_folder --symlink-->   node_modules/.registry.npmjs.org/package_folder/x.x.x/package_folder --hard-link--> ~/store-path/registry.npmjs.org/1/package_folder/x.x.x/package_folder
```

I understand that when Node is resolving dependencies it will ignore the symlink and directly run the file the symlink is pointing to. In the example above, this would mean that instead of running `node_modules/package_folder`, Node will directly run `node_modules/.registry.npmjs.org/package_folder/x.x.x/package_folder`. That in itself is a hard link to the central shared store and hence runs the file from the store.

My question is why have this `symlink -> hard link -> original` structure? Why not directly point the symlink to the central shared store itself and let node run the file from the shared store each time? Why is the hard-link in the local node_modules folder necessary?

**Comment by zkochan** [comment]
Because one package can have different sets of dependencies on one machine.

So in project A `foo@1.0.0` can have a dependencies `bar@1.0.0` and in project B `foo@1.0.0` can have the same dependency resolved to `bar@1.1.0`
