### ISSUE TITLE
`package_manager_strict = false` prints warning

### ISSUE THREAD

**Issue by benmccann** [pnpm/pnpm#8145]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

9

### Reproduction steps

Set `packageManager` to a different version than what is installed locally and run `pnpm install`

### Describe the Bug

```
 WARN  This project is configured to use v9.0.4 of pnpm. Your current pnpm is v9.0.6
```

### Expected Behavior

There should not be a warning. Potentially `package_manager_strict` could have multiple values like `error`, `warn`, `off`. There should definitely be some way to say that I don't care and not get a warning though

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
There is no warning since v9.2

Related PR: https://github.com/pnpm/pnpm/pull/8166
