### ISSUE TITLE
Running install.sh without specifying pnpm version pulls 6.31.0

### ISSUE THREAD

**Issue by kasparsginters** [pnpm/pnpm#8149]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

```
wget -qO- https://get.pnpm.io/install.sh | sh
==> Downloading pnpm binaries 6.31.0
```

### Describe the Bug

Running install.sh without specifying pnpm version pulls 6.31.0 and not latest
Just 3 hours ago it was pulling 9.1.3

Specifying version from now on.

### Expected Behavior

Pull latest

### Which Node.js version are you using?

20.11.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Debian

**Comment by LeWawan** [comment]
Up ! Same here on Macos (Exactly the same config)

**Comment by mimikun** [comment]
I have same issue, too

```shell
~
❯ pnpm --version
9.1.3

~
❯ curl -sSL https://get.pnpm.io/install.sh | sh -
==> Downloading pnpm binaries 6.31.0
 ERROR   ERROR  Unknown option: 'force'
For help, run: pnpm help setup
Install Error!
```

**Comment by zkochan** [comment]
ok, let me check

**Comment by zkochan** [comment]
This should work now
