### ISSUE TITLE
`pnpm update -r --latest <package-name>` Updates all dependencies instead of only updating the one I selected, (MONOREPO)

### ISSUE THREAD

**Issue by pedro757** [pnpm/pnpm#8154]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.1.4

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Lockfile

### Reproduction steps

1. In a monorepo with outdated dependencies try to update only one of them like `pnpm update -r --latest <pkgName>`
1. See the resulting `pnpm-lock.yml` it updated the other dependencies too.

### Describe the Bug

Updates all dependencies instead of the one I prompted

### Expected Behavior

Update only the dependency I prompted

### Which Node.js version are you using?

20.13.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Manjaro (Arch Based)

**Comment by pedro757** [comment]
I've been using this command in previous version (v8) it worked, the problem began when I updated to `v9`

**Comment by pedro757** [comment]
It works as expected if `pnpm update -r <pkgName>@latest`, I don't know what changed in v9 but --latest does't work as in previous versions

**Comment by samchungy** [comment]
Looks like this affects my project when I use `node-linker=hoisted`. Doesn't seem to affect it when I remove it.

I've added a reproduction here:

https://github.com/samchungy/pnpm-update-bug

1. Run `pnpm install`
2. Run `pnpm up -iL` and select `@smithy/node-http-handler`
3. Observe `serverless` gets bumped to version 4 which breaks the specifier.

**Comment by recallwei** [comment]
+1 
Face the same error, also use `node-linker=hoisted` with latest version of `pnpm`.

**Comment by zkochan** [comment]
I guess related: https://github.com/pnpm/pnpm/issues/6657

**Comment by woodreamz** [comment]
v9 seems to introduce a critical issue on `--latest` :/

**Comment by zkochan** [comment]
:ship: 9.12.1

**Comment by samchungy** [comment]
Hey @zkochan this appears to be still broken for `node-linker=hoisted`

See: https://github.com/pnpm/pnpm/issues/8154#issuecomment-2148750137 for reproduction

Would you like me to open a separate ticket?

**Comment by zkochan** [comment]
ok, open a new issue. Also, this repo is 404: https://github.com/samchungy/pnpm-update-bug

**Comment by samchungy** [comment]
> * Run `pnpm install`
> * Run `pnpm up -iL` and select `@smithy/node-http-handler`
> * Observe `serverless` gets bumped to version 4 which breaks the specifier.

Doh, I created it in private..... 🤦. https://github.com/pnpm/pnpm/issues/8620 thanks @zkochan 🙇
