### ISSUE TITLE
Is there a difference between pnpm start, npm start and yarn start?

### ISSUE THREAD

**Issue by stereokai** [pnpm/pnpm#816]
Is there a difference between `pnpm start`, `npm start` and `yarn start`?

**Comment by zkochan** [comment]
I don't know about yarn but `npm/pnpm start` is the same.

It is actually in the readme

> Use pnpm in place of npm. It overrides pnpm i, pnpm install and some other command, the rest will pass through to npm.

**Comment by stereokai** [comment]
Thanks.
