### ISSUE TITLE
Issues with mulitple version of drizzle-orm between different packages in workspace

### ISSUE THREAD

**Issue by benjick** [pnpm/pnpm#8163]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/NextgenClassroom/pnpm-multiple-drizzle-versions-error

### Reproduction steps

1. `pnpm i`
2. `cd apps/app2`
3. `pnpm run drizzle:up` - Notice **drizzle-orm: v0.29.3** in the output
4. `cat node_modules/drizzle-orm/package.json | grep version` The version here is **0.31.0**
5. `cat ../app1/node_modules/drizzle-orm/package.json | grep version` here's the **0.29.3** version

### Describe the Bug

`drizzle-kit` picks up the wrong version of `drizzle-orm`, telling me I need to update

### Expected Behavior

I expected the version installed in the local workspace package to be used

### Which Node.js version are you using?

v20.10.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hcg1023** [comment]
same problem

**Comment by hcg1023** [comment]
shamefully-hoist=true
I solved my problem with this

**Comment by pieterbeulque** [comment]
For me, this works with `public-hoist-pattern[]=!drizzle-orm`, which feels a bit more explicit than the `shamefully-hoist=true` fix.

**Comment by benjick** [comment]
@pieterbeulque is that the only change you made? According to the docs the defaults not including drizzle-orm: https://pnpm.io/npmrc#public-hoist-pattern

**Comment by pieterbeulque** [comment]
@benjick - I think I was looking in the wrong place to verify my "fix", and my comment is wrong.

**Comment by benjick** [comment]
I ended up using `node-linker=hoisted` in `.npmrc`

**Comment by FullstackJack** [comment]
> I ended up using `node-linker=hoisted` in `.npmrc`

Works like a charm!

Added it to my NX library project at `libs/db/.npmrc` and in my `libs/db/project.json`, I use `pnpm exec` like so:

```json
...
    "generate": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "libs/db",
        "commands": [
          "pnpm exec drizzle-kit generate --config ./drizzle.config.ts"
        ],
        "parallel": false
      }
    },
    "migrate": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "libs/db",
        "commands": [
          "pnpm exec drizzle-kit migrate --config ./drizzle.config.ts"
        ],
        "parallel": false
      }
    },
...
```

Now from root of NX monorepo, I can run `pnpm exec nx run db:generate` and `pnpm exec nx run db:migrate`.
