### ISSUE TITLE
Filtered install should work only on an up-to-date lockfile

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#8165]
We need to change how filtering works as we have many issues with it now. If the lockfile is not up-to-date, when a filtered install happens, we should do a non-filtered full resolution lockfile-only install first. (This will be less terrible in pnpm v9 as in v9 pnpm doesn't download the package tarballs during resolution.)

_Originally posted by @zkochan in https://github.com/pnpm/pnpm/issues/8020#issuecomment-2084863313_

**Comment by clayrisser** [comment]
Looking forward to this update

**Comment by clayrisser** [comment]
This is not working when `node-linker=hoisted` is set.
