### ISSUE TITLE
ajv 8.15 caused the problem, I'm not sure if the pnpm up report is a bug or not

### ISSUE THREAD

**Issue by lvzhenbo** [pnpm/pnpm#8169]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

Please try to update to ajv8.15 from ajv8.15 or below

### Describe the Bug

Package name mismatch found while reading {"integrity":"sha512-oYs1UUtO97ZO2lJ4bwnWeQW8/zvOIQLGKcvPTsWmvc2SYgBb+upuNS5NxoLaMU4h8Ju3Nbj6Cq8mD2LQoqVKFA==","tarball":"https://registry.npmmirror.com/ajv/-/ajv-8.14.0.tgz"} from the store. This means that the lockfile is broken. Expected package: ajv@8.15.0. Actual package in the store by the given integrity: ajv@8.14.0.

Related issues
https://github.com/cnpm/cnpm/issues/449
https://github.com/cnpm/bug-versions/pull/251
https://github.com/ajv-validator/ajv/issues/2446

### Expected Behavior

able to update

### Which Node.js version are you using?

20.14.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by stevenaces** [comment]
I have the same problem when I use pnpm to install the dependence.

**Comment by dominikg** [comment]
according to https://github.com/ajv-validator/ajv/issues/2446#issuecomment-2148221181  this has been fixed in ajv 8.16.0 - not an issue in pnpm
