### ISSUE TITLE
Updating to pnpm 9 cause `pnpm install` to look for a workspace dependency on npm

### ISSUE THREAD

**Issue by CraigMacomber** [pnpm/pnpm#8172]
### Last pnpm version that worked

8.15.8

### pnpm version

9.1.4

### Code to reproduce the issue

Clone this commit (which updates to pnpm 9): https://github.com/microsoft/FluidFramework/pull/21328/commits/737ac148721578ef8d0c53256a90c2d00579e56b 
Run `pnpm install` using pnpm 9 (corepack should select this version automatically if configured)

We had no issues pnpm 7 and 8, but 9 fails unless `link-workspace-packages=true` is set despite using workspace versions and the needed package being in the workspace.

### Expected behavior

`pnpm install` succeeds, installing the same packages pnpm 8 did.

### Actual behavior

> /FluidFramework/packages/service-clients/end-to-end-tests/azure-client:
>  ERR_PNPM_NO_MATCHING_VERSION  No matching version found for fluid-framework@9.9.9
> 
> This error happened while installing a direct dependency of /FluidFramework/packages/service-clients/end-to-end-tests/azure-client
> 
> The latest release of fluid-framework is "1.4.0".
> 
> Other releases are:
>   * next: 2.0.0-dev-rc.1.0.0.225277
>   * canary: 2.0.0-internal.8.0.8
>   * dev: 2.0.0-dev-rc.5.0.0.268409
>   * rc: 2.0.0-rc.4.0.4
> 
> If you need the full list of all 369 published versions run "$ pnpm view fluid-framework versions".

Note that in this mono-repo `9.9.9` is a dummy version of a bunch of packages used for the workspace version (selected to be something we won't publish for this repro to avoid it breaking if we publish the version main currently uses), but is never explicitly referred to in dependencies, which all use `"workspace:~"`. No dependency with that version should be looked for as a published package.

### Additional information

This mono-repo, and the package who's dependencies seem to be failing, take dev dependencies on older version of packages it implements for compatibility testing across versions.

My guess for whats happening is one of these previous releases started resolving its dependencies in a way that includes the workspace version for version selection but cannot correctly locate them when installing. That is just a guess though: it could be something different.

### Node.js version

v18.17.1

### Operating System

Linux

**Comment by KSXGitHub** [comment]
https://github.com/CraigMacomber/FluidFramework/pull/4

**Comment by CraigMacomber** [comment]
> [CraigMacomber/FluidFramework#4](https://github.com/CraigMacomber/FluidFramework/pull/4)

I can confirm that (setting ` link-workspace-packages=true`) fixed our issue. Thank you for the fix or maybe its a workaround? Either way, I'm happy to have it!

Given all references to the requested version explicitly use "workspace:~", and it worked fine in pnpm 7 and 8, I think this might still be a regression, so maybe this bug should stay open.

Reading https://pnpm.io/workspaces#workspace-protocol-workspace : (Emphasis added)

> **By default, pnpm will link packages from the workspace if the available packages match the declared ranges**. For instance, foo@1.0.0 is linked into bar if bar has "foo": "^1.0.0" in its dependencies and foo@1.0.0 is in the workspace. However, if bar has "foo": "2.0.0" in dependencies and foo@2.0.0 is not in the workspace, foo@2.0.0 will be installed from the registry. This behavior introduces some uncertainty.
> 
> Luckily, pnpm supports the **workspace: protocol. When this protocol is used, pnpm will refuse to resolve to anything other than a local workspace package**. So, if you set "foo": "workspace:2.0.0", this time installation will fail because "foo@2.0.0" isn't present in the workspace.
> 
> This protocol is especially useful when the link-workspace-packages option is set to false. In that case, pnpm will only link packages from the workspace if the workspace: protocol is used.

Based on my interpretation of that:

1. link-workspace-packages=true should only be needed if we don't use "workspace" versions, and we do use them.
2. Even if we didn't use "workspace" versions, since the requested version is in the workspace, it should resolve to the version in the workspace, not search npm, even without link-workspace-packages=true.
 
The observed behavior is its searching npm, and failing to find the package despite it being in the workspace, and using a workspace version, both of which should have prevented it from searching npm. `link-workspace-packages=true` changes this, causing it to search the workspace for the workspace version, which it finds.

If this is intended behavior, I think those docs need updating for pnpm 9.

**Comment by KSXGitHub** [comment]
@CraigMacomber I was able to find this fix quickly because I've read pnpm 9 breaking changes and knew that `link-workspace-packages` had been changed to `false` by default (it was `true` by default in pnpm 8).

Anyway, thanks for pointing out outdated documentation. I will correct it.
