### ISSUE TITLE
install script throws ETXTBSY  ETXTBSY: text file is busy, copyfile '/tmp/tmp.rPcedmGtun/pnpm' -> '/home/capaj/.local/share/pnpm/pnpm'

### ISSUE THREAD

**Issue by capaj** [pnpm/pnpm#8173]
I am having this issue for almost a year now: https://github.com/orgs/pnpm/discussions/6989
so let's open a proper issue for it.

### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v8-v9

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

run `curl -fsSL https://get.pnpm.io/install.sh | sh -`

### Describe the Bug

error is thrown:

```
==> Downloading pnpm binaries 9.1.4
 WARN  using --force I sure hope you know what you are doing
Copying pnpm CLI from /tmp/tmp.rPcedmGtun/pnpm to /home/capaj/.local/share/pnpm/pnpm
 ETXTBSY  ETXTBSY: text file is busy, copyfile '/tmp/tmp.rPcedmGtun/pnpm' -> '/home/capaj/.local/share/pnpm/pnpm'

pnpm: ETXTBSY: text file is busy, copyfile '/tmp/tmp.rPcedmGtun/pnpm' -> '/home/capaj/.local/share/pnpm/pnpm'
    at Object.copyFileSync (node:fs:2866:3)
    at Object.copyFileSync (pkg/prelude/bootstrap.js:1166:16)
    at copyCli (/snapshot/dist/pnpm.cjs)
    at Object.handler [as setup] (/snapshot/dist/pnpm.cjs)
    at /snapshot/dist/pnpm.cjs
    at async main (/snapshot/dist/pnpm.cjs)
    at async runPnpm (/snapshot/dist/pnpm.cjs)
    at async /snapshot/dist/pnpm.cjs
Install Error!

```

I can get around it by restarting my computer and running the command right after login, but it's annoying to do every time I need to upgrade pnpm.

### Expected Behavior

pnpm installs ok

### Which Node.js version are you using?

20, 21, 22

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 22 and 24

**Comment by MostHated** [comment]
I, too, am having this issue with the same error on Ubuntu 24.04 when attempting to update from 8.5.0 to 9.13.2

```sh
zsh ✗  curl -fsSL https://get.pnpm.io/install.sh | sh -
==> Downloading pnpm binaries 9.13.2
 WARN  using --force I sure hope you know what you are doing
Copying pnpm CLI from /tmp/tmp.t8CxhJYr9I/pnpm to /home/mosthated/.local/share/pnpm/pnpm
 ETXTBSY  ETXTBSY: text file is busy, copyfile '/tmp/tmp.t8CxhJYr9I/pnpm' -> '/home/mosthated/.local/share/pnpm/pnpm'

pnpm: ETXTBSY: text file is busy, copyfile '/tmp/tmp.t8CxhJYr9I/pnpm' -> '/home/mosthated/.local/share/pnpm/pnpm'
    at Object.copyFileSync (node:fs:3029:11)
    at Object.copyFileSync (pkg/prelude/bootstrap.js:1166:16)
    at copyCli (/snapshot/dist/pnpm.cjs)
    at Object.handler [as setup] (/snapshot/dist/pnpm.cjs)
    at /snapshot/dist/pnpm.cjs
    at async main (/snapshot/dist/pnpm.cjs)
    at async runPnpm (/snapshot/dist/pnpm.cjs)
    at async /snapshot/dist/pnpm.cjs
Install Error!
```

**Comment by zkochan** [comment]
I guess this should fix the issue: https://github.com/pnpm/pnpm/pull/8780
