### ISSUE TITLE
v9.2.0 `pnpm --filter=mypackage exec some-command` produces unexpected output

### ISSUE THREAD

**Issue by rgripper** [pnpm/pnpm#8174]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.2.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

exec with --filter

### Reproduction steps

```shell
echo "$(pnpm --filter=mypackage exec pwd)"
../../apps/mypackage (exec): /home/myrepo/apps/mypackage
../../apps/mypackage (exec): 
../../apps/mypackage (exec): Done
```

### Describe the Bug

Instead of a single line there are now three lines and some extra characters like `../../apps/mypackage (exec):` and `Done`.
NOTE: without the `--filter` parameter the bug does not appear.

### Expected Behavior

Before that it used to output just a path string one-liner like this
```shell
/home/myrepo/apps/mypackage
```

### Which Node.js version are you using?

v20.13.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

**Comment by zkochan** [comment]
cc @KSXGitHub

**Comment by KSXGitHub** [comment]
So `--filter` must have implied `--recursive`.
