### ISSUE TITLE
Error installing `parcel` (ELIFECYCLE - exit code 126)

### ISSUE THREAD

**Issue by LetsZiggy** [pnpm/pnpm#8178]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.2.0

### Reproduction steps

- `pnpm init`
![01-package-json](https://github.com/pnpm/pnpm/assets/10394949/782dcd44-02e7-4ccc-8ea6-2dea58536bea)

- `pnpm add -D parcel`
![02-pnpm-add-parcel](https://github.com/pnpm/pnpm/assets/10394949/b2aa15b1-43ce-495d-8f77-84d4e533a383)

### Describe the Bug

- Unable to install `parcel`
![02-pnpm-add-parcel](https://github.com/pnpm/pnpm/assets/10394949/b2aa15b1-43ce-495d-8f77-84d4e533a383)

- Tried [#142](https://github.com/parcel-bundler/watcher/issues/142#issuecomment-1607130763)
	1. `pnpm add -D node-gyp-build node-gyp-build-optional-packages`
	2. `pnpm add -D parcel`
		- Same error

### Expected Behavior

- Installs parcel
![03-npm-add-parcel](https://github.com/pnpm/pnpm/assets/10394949/ead678e5-00ab-491a-8439-5497629f1e6d)

- Versions
![04-versions](https://github.com/pnpm/pnpm/assets/10394949/4cc08930-c45f-468e-91d9-3fe53801a199)

### Which Node.js version are you using?

22.2.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Manjaro Linux (Kernel 6.9.2-1)

**Comment by zkochan** [comment]
Couldn't reproduce on macOS. Try with `pnpm add -D parcel --reporter=append-only` and attach the output.

**Comment by LetsZiggy** [comment]
Hi @zkochan,

thanks for looking into this
- i didn't `pnpm store purge`
- i did `rm -rf ./test-folder/*`

1. `pnpm init`
2. `pnpm add -D parcel --reporter=append-only`
![00-pnpm-parcel-reporter](https://github.com/pnpm/pnpm/assets/10394949/40830915-ed7b-452d-923d-a74555f27ff7)

**Comment by LetsZiggy** [comment]
hi @zkochan,

`pnpm -v`: `9.3.0` is able to install parcel

thank you
