### ISSUE TITLE
strict package manager

### ISSUE THREAD

**Issue by millette** [pnpm/pnpm#8195]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.3.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

```sh
pnpm i # or any other pnpm command
```

### Describe the Bug

With v9.2.0 `pnpm` stopped when packageManager was defined in package.json and it didn't match.

### Expected Behavior

pnpm should stop when `package-manager-strict-version=true`.

I also tried setting COREPACK_ENABLE_STRICT=1 and package-manager-strict=true

It was working with the previous pnpm version, with no configuration changes since.

### Which Node.js version are you using?

20.14.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

popos (ubuntu variant)

**Comment by KSXGitHub** [comment]
It's [`package-manager-strict`](https://pnpm.io/npmrc#package-manager-strict), not `package-manager-strict-version`.

**Comment by KSXGitHub** [comment]
> ### Describe the Bug
> 
> pnpm no longer stops when `package-manager-strict-version=true`.
> ### Expected Behavior
> 
> pnpm no longer stops when `package-manager-strict-version=true`.

The two paragraphs above look exactly the same.

**Comment by KSXGitHub** [comment]
I have created a PR at https://github.com/pnpm/pnpm/pull/8199. Unfortunately, due to the existing configuration of the codebase, I can't really test this change until it is released as a new version.
