### ISSUE TITLE
Updated must restart

### ISSUE THREAD

**Issue by chao921125** [pnpm/pnpm#8196]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.3.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

1、curl -fsSL https://get.pnpm.io/install.sh | sh -
2、pnpm -v
3、not show version

### Describe the Bug

When i install the new version, if normal show version, must restart my computer.

MacOS Version 14.5 M1

### Expected Behavior

curl -fsSL https://get.pnpm.io/install.sh | sh -
pnpm -v
version number

### Which Node.js version are you using?

20.13.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
It's [`package-manager-strict`](https://pnpm.io/npmrc#package-manager-strict), not `package-manager-strict-version`.

**Comment by chao921125** [comment]
The prom is fixed version 9.4.0
