### ISSUE TITLE
sub-dependencies versions are not resolved/updated correctly

### ISSUE THREAD

**Issue by augmentmoogi** [pnpm/pnpm#8209]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

I am going to use `Microsoft/vscode-vsce` as an example here - because that's where I identified it. 

Create a project with the following dependency

```
"@vscode/vsce": "github:Microsoft/vscode-vsce#v2.27.1-4",
```

run `pnpm install`

see `@azure/identity` version is `4.2.1`

now change the version of `@vscode/vsce` to `2.27.0`

(remove pnpm-lock, pnpm store prune, pnpm update - nothing I could find helps..)

run `pnpm install`

check pnpm-lock again
The expected behavior is that `@azure/identity` version would be `4.2.0`
However, it is still on 4.2.1 - even though the package-lock.json from @vscode/vsce clearly states it should be 4.2.0. 

You can also try it the other way around. (from 2.27.0 to github:Microsoft/vscode-vsce#v2.27.1-4) 

I just want to also point out the inconsistency - that installing 2.27.0 directly will result in a different outcome for if I downgrade to 2.27.0 (and vice-versa)

---

the only workaround I found is: 

1. remove the dependency completely
2. run pnpm install - check in your lock file that the dependency is removed
3. add the dependency back with the right version
4. run pnpm install 
5. => The right version was added. 

### Describe the Bug

When updating a dependency version, sub-dependencies are not resolved as expected. 

### Expected Behavior

If I reference a dependency that has a package-lock, the sub-dependencies versions in my pnpm-lock file should match  the versions in the dependency's package-lock file. 
(for simplicity, I'll assume no other conflicts exist)

If the dependency does not have a package-lock, I need a way to update sub-dependencies, or do it by default when I change the dependency's version. 

Also - I expect consistency between directly installing version x, do upgrading or downgrading to version x. 

### Which Node.js version are you using?

2.21.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

ubuntu

**Comment by KSXGitHub** [comment]
> even though the package-lock.json from @vscode/vsce clearly states it should be 4.2.0.

`package-lock.json` is irrelevant to all pnpm commands except `pnpm import`.

By default, for clean install, pnpm will install the latest versions of dependencies that satisfy the specified range.

> If I reference a dependency that has a package-lock, the sub-dependencies versions in my pnpm-lock file should match the versions in the dependency's package-lock file.

If your project has a `package-lock.json` file, you can try `pnpm import`. If one of your dependencies has a `package-lock.json` file, pnpm will ignore that file and resolve them the pnpm's way.

> I need a way to update sub-dependencies, or do it by default when I change the dependency's version.

You can try `pnpm update` or `pnpm update --latest`. If that doesn't work, simply remove `pnpm-lock.yaml` and `node_modules` and then run  `pnpm install --config.resolution-mode=highest`.

**Comment by augmentmoogi** [comment]
Thank you for the deep dive. closing.
