### ISSUE TITLE
`pnpm install` can delete the node_modules folder then re-create it, causing custom attributes to be lost

### ISSUE THREAD

**Issue by ZYinMD** [pnpm/pnpm#8216]
### Last pnpm version that worked

not sure, maybe last year

### pnpm version

not sure when the regression appeared, but it's earlier than 9.1.2.

### Code to reproduce the issue

Mac example:
```shell
# after cloning repo
mkdir node_modules
xattr -w 'foo' 42 'node_modules' # set custom attribute 'foo' to 42
xattr -p 'foo' 'node_modules' # get custom attribute 'foo', should output 42
pnpm install
xattr -p 'foo' 'node_modules' # get custom attribute 'foo' again
```
Windows example (powershell)
```powershell
# after cloning repo
mkdir node_modules
Set-Content -Path 'node_modules' -Stream foo -Value 42 # Create Alternate Data Steram 'foo' with value 42
Get-Content -Path 'node_modules' -Stream foo # Get the value of stream 'foo', should output 42
pnpm install
Get-Content -Path 'node_modules' -Stream foo # Get the value of stream 'foo' again
```

### Expected behavior

42

### Actual behavior

can't find the value

### Additional information

# Why this matters

(long story) 
When you're working in a repo, did a bunch of commits, but haven't pushed them to remote yet, you're at risk of losing your work if some disaster happens, e.g. hard drive failure, ransomware, your laptop gets stolen, etc.

For this reason, there's a (quite large) group of people who put their repos inside dropbox. Dropbox syncs everything, including the `.git` folder. This may sounds sketchy, but the `.git` folder is perfectly syncable. I've beening doing it for 6 years in 100+ repos, never had an issue.

Needless to say, you certainly want to ignore the `node_modules` folder. In dropbox world, there's no `.dropboxignore` or something like that, instead, you set a custom property to `node_modules`, so that dropbox knows to ignore it. To do so, you either right click the folder and choose "don't sync", or do it from CLI.  In Windows, you set `com.dropbox.ignored` to `1`. In Mac, you set `com.apple.fileprovider.ignore#P` to `1`.

For many years, I've been following the same protocol: clone repo -> mkdir `node_modules` -> set it to ignore -> then `pnpm install`. However, recently the ignore attr would be deleted after `pnpm install`, causing my `node_modules` to be synced to dropbox, which caused huge issues which I won't go into details. 

### Node.js version

20.14.0 

### Operating System

macOS & Windows

**Comment by zkochan** [comment]
pnpm sometimes does remove node_modules. Although in that case a prompt appears and you need to enter "y". For sure we can change it so that instead of removing node_modules it removes the contents of node_modules but doesn't touch the empty directory itself.

**Comment by ZYinMD** [comment]
@zkochan It seems that if the `node_modules` folder is empty, like in the case of OP, the prompt before deleting it will be skipped.  It makes perfect sense, but it happens to precisely ruin the setup in OP.

**Comment by KSXGitHub** [comment]
You already have a list of paths to ignore in `.gitignore`. You can write a postinstall script that parse the `.gitignore` file and set attributes for every ignored item. If the `.gitignore` file is too complex too parse, or doesn't contain enough information about ignored files, you may use `git status --ignored --porcelain=v1`.

**Comment by zkochan** [comment]
actually, we cannot change it as pnpm needs to remove empty node_modules directories.

However, there is a workaround for you. Just add a `.keep` file to your `node_modules` (or any other filename that starts with a dot). pnpm will not remove the directory in this case.
