### ISSUE TITLE
How does pnpm uninstall work?

### ISSUE THREAD

**Issue by stereokai** [pnpm/pnpm#822]
For the curious ones in the crowd, I'd like to bring this question: How does pnpm uninstall work?

Also, what happens if you delete a pnpm-installed node_modules folder?

**Comment by zkochan** [comment]
if you remove the node_modules. nothing bad will happen but the packages will stay in the global store.

there are two shrinkwrap.yaml files. One in the root of project, one in `node_modules/.shrinkwrap.yaml`. When you remove, the outer shrinkwrap is pruned, and it is compared with the inner shrinkwrap file. Packages that are in the inner but are not in the outer shrinkwrap are removed. Here's the code: https://github.com/pnpm/pnpm/blob/master/src/api/removeOrphanPkgs.ts

**Comment by zkochan** [comment]
This happens not only during uninstall but also after installations and updates. Many packages can become unused

**Comment by stereokai** [comment]
Thanks. That carries a further question: If there are unused modules in the global store, do you need to take of it manually? Alternatively, does pnpm have a command for that?

Cheets

**Comment by zkochan** [comment]
It has a [store.json](https://github.com/pnpm/sample-project/blob/master/pnpm-store/2/store.json) with info which packages in the store are used by which projects. Unused packages are removed from the store

**Comment by stereokai** [comment]
When are they removed from the store? Every time the store is updated? I'm just curious, not criticising

**Comment by zkochan** [comment]
yes

**Comment by stereokai** [comment]
Cool. Thanks
