### ISSUE TITLE
Install script does not install pnpx

### ISSUE THREAD

**Issue by benmccann** [pnpm/pnpm#8230]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.4.0

### Reproduction steps

https://pnpm.io/installation#on-posix-systems

### Describe the Bug

`pnpx` is an alias of `pnpm dlx`:
https://github.com/pnpm/pnpm/blob/6e031e7428b3e46fc093f47a5702ac8510703a91/pnpm/package.json#L7

However, I'm not sure how to run `pnpx` as it doesn't seem to be installed

### Expected Behavior

`pnpx` should be globally installed alongside `pnpm`

### Which Node.js version are you using?

20.13.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 24.04

**Comment by KSXGitHub** [comment]
> However, I'm not sure how to run `pnpx` as it doesn't seem to be installed

`pnpx` is just a shorthand for `pnpm dlx`.

**Comment by benmccann** [comment]
I understand that it is an alias, but the issue is that the alias doesn't exist on my machine
