### ISSUE TITLE
Lazy completion loading for Zsh

### ISSUE THREAD

**Issue by segevfiner** [pnpm/pnpm#8232]
### Contribution

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

The currently generated Zsh completion script is not suitable for use for lazy loading, see https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Autoloaded-files

### Describe the solution you'd like

Support lazy loading in the generated pnpm zsh completion script, see https://github.com/kislyuk/argcomplete/commit/dd79ddf2e0df4be899ec60cfb96b6c2271f8f10f for an example where I implemented that for argcomplete (Python)

### Describe the drawbacks of your solution

There shouldn't be any, this modification makes it work for both direct eval and lazy loading/autoloading

### Describe alternatives you've considered

Modify the script by myself.

**Comment by KSXGitHub** [comment]
> ### Describe alternatives you've considered
> 
> Modify the script by myself.

Since you know ZSH better than us, can you make a PR to https://github.com/pnpm/tabtab? If modifying the script is sufficient, then you would only need to modify `lib/templates/completion.zsh`.

**Comment by segevfiner** [comment]
@KSXGitHub Seems like it closed this anyhow 🤷‍♂️ You wanted to keep this open until `@pnpm/tabtab` is updated here.

**Comment by KSXGitHub** [comment]
@segevfiner Can you clone the pnpm repo, run `pnpm update --latest --recursive @pnpm/tabtab`, and then make a PR? (I don't have access to the computer at the moment)
