### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by abbas-quikieapps** [pnpm/pnpm#8233]
### Last pnpm version that worked

9.0.0

### pnpm version

9.0.0

### Code to reproduce the issue

![image](https://github.com/pnpm/pnpm/assets/116256552/60bb6af1-03dd-4890-be32-16cf9a5b7c8a)

### Expected behavior

https://pnpm.io/ being online

### Actual behavior

[PNPM ](https://pnpm.io/) is down due to due payment

### Node.js version

18

### Operating System

Windows

**Comment by KSXGitHub** [comment]
It's up now.
