### ISSUE TITLE
PNPM TYPE_ERROR: Cannot set property name of which has only a getter.

### ISSUE THREAD

**Issue by tomasvn** [pnpm/pnpm#8235]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

8.6.11

### Reproduction steps

- private project

### Describe the Bug

![image](https://github.com/pnpm/pnpm/assets/17225564/8b90b27a-eb39-46a0-9431-2a155d0f9147)

[#4270](https://github.com/pnpm/pnpm/issues/4270)
[#5572](https://github.com/pnpm/pnpm/issues/5572)

### Expected Behavior

Not failining installing on CI server, we are using AzureDevops

### Which Node.js version are you using?

16.20.2

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by tomasvn** [comment]
Possible solution to downgrade version to previously working version, `7.5.2` on our azure agent machines

**Comment by KSXGitHub** [comment]
The latest pnpm@8 version is 8.15.8, is the error still reproducible in this version?

The very latest version of pnpm is 9.4.0, I advise you to migrate to pnpm@9.

**Comment by tomasvn** [comment]
@KSXGitHub We had to revert version, back to `7.5.2` I will re-open with a new issue if it will happen on `pnpm@9` once we'll be able to upragde.
