### ISSUE TITLE
making linking local packages great again

### ISSUE THREAD

**Issue by paulpflug** [pnpm/pnpm#825]
Hey, I really love pnpm and how it saves a lot of disk space..

As I excessively use linking of local packages, I think the whole `link` commando could use a bit of love:
- [x] `pnpm link pkg1 pkg2` should link both packages (like npm and yarn do)
- ~`pnpm link pkg1` should check for peerDependencies of `pkg1` (#827)~
- [x] `pnpm unlink pkg1` should install `pkg1` if it is a dep after unlinking (#819)
- [x] `pnpm unlink` to replace all local linked packages with normal installed packages
- ~`pnpm link-all` link up all dependent locally available packages~
- [ ] `pnpm recursive link` link all packages in a monorepo and install their dependencies

`pnpm unlink-all && pnpm test & pnpm link-all` would be very valuable for me..

what do you think? If wanted, I could invest some time for a few PRs..

**Comment by zkochan** [comment]
Some of these we can add. The ones that are implemented in npm. The more complex ones I would rather implement as separate package. Maybe it can be added to [pnpmr](https://github.com/pnpm/pnpmr).

I also have this [link-local-packages](https://github.com/zkochan/link-local-packages) that can be used.

pnpm's codebase is pretty complex, so I'd rather try to hypermodularize it first. Maybe convert it to a monorepo?! I am not sure yet.

But I do understand the importance of these features and I'd love them as well, so even if in scope of a separate package, it can be in our org and maintained by us

**Comment by paulpflug** [comment]
regarding `link-all` I found a few packages:
[npm-link-up](https://github.com/ORESoftware/npm-link-up)
[zelda](https://github.com/feross/zelda)
[npm-link-shared](https://github.com/OrKoN/npm-link-shared)

npm-link-up could be compatible with pnpm, I will try this now

**Comment by paulpflug** [comment]
after testing, I created my own package for the link-all functionality: [linkall](https://github.com/paulpflug/linkall). It uses your `find-packages` and `which-pm` packages 👍 

It is small, slow, written in coffeescript and the output is ugly, but it works with `pnpm link`, which is great.

**Comment by zkochan** [comment]
That's great, I just created the [awesome-pnpm](https://github.com/pnpm/awesome-pnpm), so your package can be added there

**Comment by zkochan** [comment]
Instead of `pnpm unlink` I suggest for now a new command called `pnpm dislink`.

Also, if called w/o paramaters, it will unlink the symlinked packages and install them, as you suggested with  `pnpm unlink-all`. Maybe in v2 we'll make `unlink` behave this way

**Comment by zkochan** [comment]
`pnpm dislink` published with [v1.6.0](https://github.com/pnpm/pnpm/releases/tag/v1.6.0).

When called w/o arguments, all external links are removed. If the linked package is in `package.json`, it is reinstall after the link is removed

Let's keep this issue open for now. I think maybe we can implement something like `pnpm link-all`. I am not 100% sure what it should do yet. Maybe search for packages up in the filesystem

**Comment by zkochan** [comment]
@paulpflug, recently a new feature was added to `pnpm@next` - concurrent installs (#969). Maybe we can add linking to it. By default or via some flag. Something like `pnpm recursive --link install`

**Comment by paulpflug** [comment]
Wow, great feature - add linking would definitely add even more value.

recursive linking is a 2 phase process.
This is in what `linkall` is doing (without concurrency of course):
First call `pnpm link` in all sub directories with package.json - which will also install the package, this can be done concurrently.
Somehow the package names must be collected in this step
Then in the second step the dependencies of each package must be matched to the collected names and
`pnpm link [dep1] [dep..]` can be called in each according sub directory - in principle also concurrently.

the unsolved problem - but I'm unsure how much of a problem this is - is how you control which globally linked packages get linked and which are not.

The approach in the top is the simplest form - all packages within one folder get linked to each other (if they are specified as dependencies)
But you could equally go for a register of all globally linked package and link all of them matching a dependency - whether they are in the same containing directory or not.

If I can help you anyhow let me know.

**Comment by zkochan** [comment]
I think we should just ignore the global packages during linking.

`pnpm recursive link` should be a good name for the command.

**Comment by zkochan** [comment]
:ship: [v1.32.0](https://github.com/pnpm/pnpm/releases/tag/v1.32.0)
