### ISSUE TITLE
Windows arm64 build

### ISSUE THREAD

**Issue by knd775** [pnpm/pnpm#8251]
### Contribution

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

When trying to use pnpm on an arm device running windows, it installs x64 binaries for dependencies like rollup. Applications then fail to run because they can't find the arm64 binaries.

### Describe the solution you'd like

Build pnpm for win-arm64

### Describe the drawbacks of your solution

None

### Describe alternatives you've considered

None available

**Comment by ZeonXr** [comment]
pnpm@9.7.0 for win-arm64 does not work on my arm device

```
C:\Users\ZeonX\Desktop\pnpm>pnpm-win-x64.exe -h
Version 9.7.0 (compiled to binary; bundled Node.js v18.5.0)
Usage: pnpm [command] [flags]
. . .
C:\Users\ZeonX\Desktop\pnpm>pnpm-win-x64.exe -h
```
running pnpm-win-x64.exe produced no output

OS: Windows 11 23H2 ARM64
CPU: Snapdragon 8cx Gen 2

**Comment by petero-dk** [comment]
This does not seem to actually work.

Running https://get.pnpm.io/install.ps1 on windows arm64 installs the x64 version not arm.

When downloading the [pnpm-win-arm64.exe](https://github.com/pnpm/pnpm/releases/download/v9.15.0/pnpm-win-arm64.exe) there are no output from the file. No commands seems to work.
