### ISSUE TITLE
automatically install peerDependencies

### ISSUE THREAD

**Issue by paulpflug** [pnpm/pnpm#827]
The original purpose of peerDependencies with npm@1 was, that a package can define packages to install alongside.
With the flattened dependencies tree with npm@3 this functionally was redundant, as ALL dependencies are getting installed alongside, as a result the automatic installation of peer dependencies was disabled and there is no real use-case for defining peer dependencies anymore..

With pnpm this isn't the case, as you choose to use a npm@1 like package dep tree, you should also use the npm@1 peerDep behaviour and install them automatically.

Say package A needs B,C,D as peerDep I would have to call:
```sh
pnpm install A B C D
# instead of
npm install A
```

if a peerDep conflicts with a normal dep, the normal dep should win and a warning should get printed..
(also peerDeps should get installed when linked)

What do you think?

**Comment by zkochan** [comment]
Peer dependencies are not installed because

> The behavior in npms 1 & 2 was frequently confusing and could easily put you into dependency hell, a situation that npm is designed to avoid as much as possible.
> src: https://docs.npmjs.com/files/package.json#peerdependencies

Peer dependencies are intended to be used by pluggable packages and are resolved from *higher in the dependency tree*. They are not supposed to be resolved from down the dependency tree. If they are resolved that way accidentally because of flattened `node_modules` we shouldn't try to emulate other package manager's bad design.

P.S. this article of mine - [pnpm's strictness helps to avoid silly bugs](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html), even started a discussion in a npm chat about making [--global-style](https://docs.npmjs.com/misc/config#global-style) the default `node_modules` layout. The global-style layout reduces issues like that, issues when flat node_modules allow accessing not referenced dependencies

**Comment by paulpflug** [comment]
pnpm's strictness is a big advantage, I agree on that. But to be honest, peerDependencies in its current state are useless.. there is no point in using them neither in npm nor in pnpm. Pluggable packages don't exist (at least I have never seen one).

Now to the problem I want to solve: webpack.
Webpack doesn't resolve packages exactly as node.
I want a package which automatically provides a number of loaders for webpack.
With npm I can define them as normal deps and look them up either in `node_modules` of the package or its parent.
With pnpm it is not possible. The normal deps are not showing up in `node_modules` of the parent (strict - good design), but also not in `node_modules` of the package, so webpack has no way of finding them.

When working with peerDeps, I have to type out all peerDeps, then there is no point in using a dependency collection in the first place.

The current (untested) workaround is to manually resolve the package dir link with `fs.realpathSync` on runtime and add the parent directory to webpacks `resolveLoader`.

I think it would be totally sufficient to only auto install peerDeps on top level, after all other packages are installed, and only warn on failure, so they are treated like citizen second class - this would still allow the usage of pluggable packages, as normal dependencies would override them.

If you insist on the current way, this issue can be closed.

**Comment by zkochan** [comment]
I think the way people do it is they have their peerDependencies as devDependencies as well. That is kinda what you are asking for (installing it only on top level). Including them as devDependencies is not good?

> Webpack doesn't resolve packages exactly as node.

Are you sure? We'll have to file an issue at webpack in that case. We had issues with CRA and with latest issues they are gone, so I assumed they have fixed it. I know they have an option to turn off resolve symlink, but it is on by default. A package symlink is resolved to its real location and pnpm does create a node_modules folder one directory up the package's real location. Have you tried with `webpack@2.6`?

> Pluggable packages don't exist (at least I have never seen one).

Maybe I named it incorrectly but babel, eslint use peer dependencies to work with their plugins. And they work with pnpm. (Except one issue with eslint #739)

**Comment by zkochan** [comment]
By the way, we have this issue at webpack https://github.com/webpack/webpack/issues/5087

**Comment by vjpr** [comment]
@paulpflug 

> I want a package which automatically provides a number of loaders for webpack.
With npm I can define them as normal deps and look them up either in node_modules of the package or its parent.
With pnpm it is not possible. The normal deps are not showing up in node_modules of the parent (strict - good design), but also not in node_modules of the package, so webpack has no way of finding them.

I have tackled this issue extensively. Its very tricky in general - lots of edge cases, especially when `npm linking` during development.

You can just use webpack's `resolve.modules`: https://webpack.js.org/configuration/resolve/#resolve-modules to get most of the way there though.

**Comment by paulpflug** [comment]
`In package A you should refer to package B using require.resolve` 
This won't work for other dependencies than `js`. Stylesheets for example.

`or you can add package A's node modules dir to require.modules`
This will work, but then the installation instructions of A get very ugly, I really want to prevent that.
I also could order the user to also install B, also ugly in my eyes.

**Comment by vjpr** [comment]
With webpack everything is possible! I'm not 100% on what your trying to do
but if you can show me a sample project I'm pretty sure I can resolve it.
Relying on flat node modules will be problematic if there are multiple
versions of the dep in the tree too. But I'd have to see code.

**Comment by paulpflug** [comment]
I have [ceri-materialize](https://github.com/ceri-comps/ceri-materialize) which is basically a wrapper around [materialize-css](http://materializecss.com/) with a few added stylesheets.
I want the user to only install `ceri-materialize` but be able to resolve materialize-css stylesheets in sass:
```sass
// sass
@import "~ceri-materialize/color"; //works
// works in npm due to flattened tree
// but not in pnpm
@import "~materialize-css/sass/components/variables";

// no way to resolve the dependency:
@import "~ceri-materialize/../materialize-css/sass/components/variables"; //doesn't work
@import "~ceri-materialize/node-modules/materialize-css/sass/components/variables"; //doesn't work
```

for example code you can clone [ceri-tooltip](https://github.com/ceri-comps/ceri-tooltip)
 `git clone https://github.com/ceri-comps/ceri-tooltip.git` 

and run `cd ceri-tooltip && pnpm i && npm run dev`

thanks for your time!

**Comment by vjpr** [comment]
Okay reproduced:

```
ERROR in ./node_modules/.registry.npmjs.org/css-loader/0.28.4/node_modules/css-loader!./node_modules/.registry.npmjs.org/sass-loader/6.0.6/node_modules/sass-loader/lib/loader.js!./dev/materialize.config.scss
Module build failed:
@import "~materialize-css/sass/components/mixins";
^
      File to import not found or unreadable: ~materialize-css/sass/components/mixins.
Parent style sheet: stdin
      in /Users/Vaughan/dev-live/ceri-tooltip/dev/materialize.config.scss (line 3, column 1)
 @ ./dev/materialize.config.scss 4:14-232 18:2-22:4 19:20-238
 @ ./dev/materialize.coffee
 @ ./node_modules/.registry.npmjs.org/ceri-dev-server/1.0.6/node_modules/ceri-dev-server/lib/ceri-dev-client.js
 @ multi ./node_modules/.registry.npmjs.org/koa-hot-dev-webpack/0.1.10/webpack@3.0.0/node_modules/koa-hot-dev-webpack/hot-reload.js ./node_modules/.registry.npmjs.org/ceri-dev-server/1.0.6/node_modules/ceri-dev-server/lib/ceri-dev-client.js
```

**Comment by vjpr** [comment]
So in `ceri-tooltip/dev/materialize.coffe.scss` you are referencing `materialize-css`. This is non-standard and should be avoided - there are many things that could go wrong and break.

You should depend directly on `materialize-css` or you should access `materialize-css` via the `ceri-materialize` module.

pnpm will never support accessing a module from a module that doesn't depend on it.

However, you can configure webpack with a custom loader resolver. Modify `ceri-dev-server/lib/webpack.config.js` to include `node_modules/ceri-materialize/node_modules`.

**Comment by vjpr** [comment]
If there is ever another version of `materialize-css` used in your code base by your library users, then this will cause issues. pnpm is much safer, and not relying on the flat module structure is always best.

**Comment by zkochan** [comment]
@vjpr lets create a pnpm-manifesto repo with listings of all the things pnpm is meant to be

**Comment by paulpflug** [comment]
I think it all breaks down to my impression, that if a package A has a peerDep B and I install A I should also have access to B. 
```
C
-A
-B (peer of A)
```

Currently peerDep really means optionalDep, but with a warning if it isn't installed.. (making that optionality obsolete :expressionless:)

**Comment by zkochan** [comment]
pnpm's philosophy is simple. A package is accessible only when it is a dependency. So B will only be accessible from C, if it will be some kind of a dependency of B.

peerDependency is not the same as optionalDependency. Peer dependencies are not even looked into during the resolving and downloading stages. Once all dependencies (prod, dev, optional) are resolved, pnpm analyzes the dependency tree and tries to resolve peer dependencies.

**Comment by vjpr** [comment]
But if C doesn't depend on B, then C should not be able to access B.

If A has a peer dep on B, then C must still explicitly require B if it wants to access it.

In your `ceri-materialize` you have:

```
  "peerDependencies": {
    "materialize-css": "^0.99.0"
  },
  "dependencies": {
    "materialize-css": "^0.99.0"
  },
```

You should use webpack alias or something to target the correct version of `materialize-css` from your app.

Peer deps should be used when its important that the same instance of the dep is used - such as `webpack.ExtractTextPlugin`.

**Comment by paulpflug** [comment]
I see, thanks for clarification. 👍

**Comment by brettz9** [comment]
With npm@7 auto-installing peerDependencies now per https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md , might pnpm be considering revisiting this? Thanks!

**Comment by scamden** [comment]
please consider this. peers are nigh useless without it. npm 7's new peer strategy works really well. but they are so much slower than you guys. would love to have the best of both worlds.

**Comment by zkochan** [comment]
No, we require that peer dependencies should be added as dependencies of the project. All we can do is print a prompt after installation to select which missing peer dependencies should be added to the project.

**Comment by scamden** [comment]
> No, we require that peer dependencies should be added as dependencies of the project. All we can do is print a prompt after installation to select which missing peer dependencies should be added to the project.

yes i realize that was the conclusion above. i was hoping you might reconsider in light of the fact that npm has done an about face on that issue, and it is frankly worlds better. 

having used both i can say that peers are essentially useless (and extremely tedious) without this feature. it makes far more sense to consider a peer dep the same as a dep except that is intended to be installed once only (like react or other single instance libraries). 

if i installed react as a dep in my project it would come along when my package was installed into any other package because i'm declaring that i need it. the same should be true of a peerDep with the exception that only one version must exist. i can't think of any good reason for not auto-installing these. if the top level package needs to access the dep they should also declare it a dep, but if the installed package only needs it, why should the top level package have to unnecessarily add a dep?

**Comment by milahu** [comment]
> Peer dependencies are intended to be used by pluggable packages
> and are resolved from _higher in the dependency tree_.
> They are not supposed to be resolved from down the dependency tree.

> With npm@7 auto-installing peerDependencies now

> No, we require that peer dependencies should be added as dependencies of the project.

so now pnpm has its own opinions, and is incompatible with npm? HMMM ... (fork, anyone?)

> npm versions 1, 2, and 7 will automatically install peerDependencies
> if they are not explicitly depended upon higher in the dependency tree.
>
> For npm versions 3 through 6,
> you will receive a warning that the peerDependency is not installed instead. 
>
> https://nodejs.org/en/blog/npm/peer-dependencies/

currently, pnpm does not even show a warning 0__o

**Comment by LumaKernel** [comment]
I noticed we can use `.pnpmfile.cjs` for this purpose.

```js
function readPackage(pkg) {
  pkg.dependencies = {
    ...pkg.peerDependencies,
    ...pkg.dependencies,
  }
  pkg.peerDependencies = {};

  return pkg;
}

module.exports = {
  hooks: {
    readPackage,
  },
};
```

I'm using more opinionated version of this.

**Comment by fc** [comment]
Can we have add a parameter to `pnpm install --include-peers` that does what @LumaKernel posted? 
What's the point of `peerDependenciesMeta.*.optional` if all peer dependencies are basically optionally anyway?

**Comment by fc** [comment]
It looks `install-peerdeps` ([here](https://www.npmjs.com/package/install-peerdeps)) supports `pnpm`.

Example:
```
npx install-peerdeps --pnpm <your-package>
```

**Comment by milahu** [comment]
> Can we add a parameter

this should be the default behavior. breaking with NPMv7 is just @zkochan's power trip ...
feel free to ban me from the pnpm org, only to prove my point : D
seems like all the political tensions transform maintainers into fanatic conservatives

team red is leaving the chat

**Comment by zkochan** [comment]
what is wrong with you?

**Comment by zkochan** [comment]
If you want this feature so bad, make a PR and make it opt-in. If most will vote to make it the default, then we'll make it the default. I don't understand what is your problem with me.
