### ISSUE TITLE
ENOENT: no such file or directory  In a virtual machine using the

### ISSUE THREAD

**Issue by wChenonly** [pnpm/pnpm#8273]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Store

### Reproduction steps

Install a virtual macos in the real macos using parallels, then install the project dependencies from the real macos in the virtual macos

### Describe the Bug

ENOENT: no such file or directory, copyfile '/Volumes/My Shared Files/Home/.pnpm-store/v3/files/56/1d7592a3eeb97982d55ee9472022bdcb955e377546f9054c36fd50d075182523d9dd8b001596ea777bfa1bbdb1dd63d9326a3de781fb1f93bb8b4172b250c4' -> '/Volumes/My Shared Files/Home/work/code/webBaseManage/node_modules/.pnpm/@element-plus+icons-vue@2.3.1_vue@3.4.29_typescript@5.5.2_/node_modules/@element-plus/icons-vue_tmp_22944/dist/types/components/aim.vue.d.ts'

Related issues  https://github.com/pnpm/pnpm/issues/4997#issuecomment-1230527581

### Expected Behavior

Hopefully it will install properly

### Which Node.js version are you using?

22.0.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by AntonioDell** [comment]
Might be related to https://github.com/pnpm/pnpm/issues/7814
