### ISSUE TITLE
Peer dependencies are not getting overriden

### ISSUE THREAD

**Issue by tbhaxor** [pnpm/pnpm#8292]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.5.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

https://gist.github.com/tbhaxor/3eb536ed46638a506160f769cdf2e725

### Reproduction steps

Just run `pnpm i --resolution-only` or `pnpm i` if you are running for the first time

### Describe the Bug

I am new to the resolution and the peer dependencies are not picking the right versions I have mentioned in the `pnpm.overrides` or `peerDependencyRules`

![image](https://github.com/pnpm/pnpm/assets/28386721/4df96c0d-de61-4c2d-800c-e31c20019889)

### Expected Behavior

After mentioning correct versions in the `pnpm.overrides` or `peerDependencyRules`, it should not warn peer d

### Which Node.js version are you using?

v20.14.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Arch Linux

**Comment by zkochan** [comment]
peer dependencies in overrides kind of don't make sense. You have full control over peer dependencies without overrides. You just need to install the peer dependency. In your case you did install eslint in your dev dependencies. If you want v8 of eslint, just change it in you dev deps.

**Comment by tbhaxor** [comment]
I have a follow up question for different project where peer dependency need major version 8 of eslint and my scripts need major version 9. In that case how can I solve this? can packageExtension work in that case?

If yes, then can I use it for nested dependencies? 
```
depA
  eslint
  depB
    eslint
```

**Comment by zkochan** [comment]
package extensions do not override existing dependencies.

I am not sure why'd you want to have different versions of eslint as the whole point of peer deps is for them to be singletons. The only way to achieve what you want is with a [readPackage hook](https://pnpm.io/pnpmfile#hooksreadpackagepkg-context-pkg--promisepkg).
