### ISSUE TITLE
catalogs with `@` packages not working (maybe when using resolutions)

### ISSUE THREAD

**Issue by userquin** [pnpm/pnpm#8303]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.5.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/userquin/vuetify-nuxt-module/pull/241

### Reproduction steps

Run `pnpm install` from root

### Describe the Bug

```shell
C:\temp-working\nuxt\vuetify-nuxt-module-main\date-io-playground:
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @nuxt/kit@catalog:resolutions isn't supported by any available resolver.

This error happened while installing the dependencies of @unocss/nuxt@0.61.3

An external package outside of the pnpm workspace declared a dependency using
the catalog protocol. This is likely a bug in that external package. Only
packages within the pnpm workspace may use catalogs. Usages of the catalog
protocol are replaced with real specifiers on 'pnpm publish'.

This is likely a bug in the publishing automation of this package. Consider filing
a bug with the authors of:

  @unocss/nuxt@0.61.3

Progress: resolved 82, reused 71, downloaded 0, added 0
```

### Expected Behavior

`pnpm install`  should work

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by userquin** [comment]
Maybe `resolutions`?

**Comment by dpnova** [comment]
I'm seeing this with a package from my monorepo - not sure if it's the same underlying cause or not

**Comment by fredimitchel** [comment]
I encounter the same issue with `@` packages especially when using `workspace:` version.

**Comment by gluxon** [comment]
Hey @userquin — Catalogs don't work when the `resolutions` block changes external dependencies. I did consider that some users would want to do this, but unsure how the implementation would work yet. I'll file a feature request issue and tag you on it.

For now, I'd recommend avoiding the `catalog:` protocol in `resolutions` or `pnpm.overrides` since there isn't better support for this yet.

**Comment by zkochan** [comment]
@gluxon it should work. We just need to resolve the catalogs in the overrides: https://github.com/pnpm/pnpm/pull/8321

**Comment by zkochan** [comment]
:ship: 9.6.0

**Comment by dpnova** [comment]
> 🚢 9.6.0

I notice #8297 still open and seems to be more directly related to `deploy` ?

**Comment by userquin** [comment]
package.json resolutions not changed when running `pnpm pack` (linked PR updated): shouldn't be a problem...

![imagen](https://github.com/user-attachments/assets/5576b176-d4e6-4244-b55a-cede317086fd)
