### ISSUE TITLE
Issues with vue

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#831]
### temporary workaround:

Create a `.npmrc` in the root of your project with the following content:

```
shamefully-flatten=true
```

reinstall your node_modules.

***

Posted by @birchb in https://github.com/pnpm/pnpm/issues/532#issuecomment-292374587

Initializing a new vue project using vue-cli:
`vue init webpack pnpm-test`
 and running with 
`pnpm run dev`
results in the following error:

```
This dependency was not found:

* vue-hot-reload-api in ./src/App.vue, ./~/.registry.npmjs.org/vue-loader/11.3.4/~/vue-loader/lib/template-compiler?{"id":"data-v-59778c66"}!./~/.registry.npmjs.org/vue-loader/11.3.4/~/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue and 2 others

To install it, you can run: npm install --save vue-hot-reload-api
```

After running:

`pnpm install --save vue-hot-reload-api`

the dev server complies and loads correct.

EDIT: Upon further review, vue-style-loader appears to also result in an error.

**Comment by anhnhoktvn** [comment]
is there any update for this issue?

**Comment by zkochan** [comment]
no, but if vue uses the `resolve` package, the hook described [here](https://github.com/pnpm/pnpm/issues/857#issuecomment-326746282) can be used.

**Comment by zkochan** [comment]
As a temporary fix, you can now use the `--shamefully-flatten` flag to create a flat node_modules with pnpm. Added in [pnpm@1.34.0](https://github.com/pnpm/pnpm/releases/tag/v1.34.0).

Fixes the issues with vue

**Comment by sp-tenovos** [comment]
There is still an issue with Vue even using the `--shamefully-flatten` argument. Create a new Vue app with the latest version of the cli (3.1.1), delete node_modules and run `pnpm i --shamefully-flatten`. If you then type to run `npm run serve` you get the following error.

```bash
This dependency was not found:

* -!../../node_modules/.registry.npmjs.org/cache-loader/1.2.5/webpack@4.25.1/node_modules/cache-loader/dist/cjs.js??ref--13-0!../../node_modules/.registry.npmjs.org/babel-loader/8.0.2/@babel!core@7.0.1+webpack@4.18.1/node_modules/babel-loader/lib/index.js!../../node_modules/.registry.npmjs.org/ts-loader/5.3.0/node_modules/ts-loader/index.js??ref--13-2!../../node_modules/.registry.npmjs.org/cache-loader/1.2.5/webpack@4.25.1/node_modules/cache-loader/dist/cjs.js??ref--0-0!../../node_modules/.registry.npmjs.org/vue-loader/15.4.2/css-loader@1.0.1/node_modules/vue-loader/lib/index.js??vue-loader-options!./Home.vue?vue&type=script&lang=ts& in ./src/views/Home.vue?vue&type=script&lang=ts&

To install it, you can run: npm install --save -!../../node_modules/.registry.npmjs.org/cache-loader/1.2.5/webpack@4.25.1/node_modules/cache-loader/dist/cjs.js??ref--13-0!../../node_modules/.registry.npmjs.org/babel-loader/8.0.2/@babel!core@7.0.1+webpack@4.18.1/node_modules/babel-loader/lib/index.js!../../node_modules/.registry.npmjs.org/ts-loader/5.3.0/node_modules/ts-loader/index.js??ref--13-2!../../node_modules/.registry.npmjs.org/cache-loader/1.2.5/webpack@4.25.1/node_modules/cache-loader/dist/cjs.js??ref--0-0!../../node_modules/.registry.npmjs.org/vue-loader/15.4.2/css-loader@1.0.1/node_modules/vue-loader/lib/index.js??vue-loader-options!./Home.vue?vue&type=script&lang=ts&                           No type errors found
No lint errors found
Version: typescript 3.1.6, tslint 5.11.0
```

Also note that I selected the following options for manual install from the cli.
- Babel - ***yes*** to babel alongside typescript for auto-detected polyfills
- TypeScript - ***yes*** to class style components
- Router - ***no*** to history mode for router
- Vuex
- CSS Pre-processors - ***Sass/SCSS*** for css preprocessor
- Linter / Formatter - ***TSLint*** and ***Lint on save*** for linting
- Unit Testing - ***Jest*** for unit tests
- E2E Testing - ***Cypress*** for E2E

**Comment by sp-tenovos** [comment]
So it appears that the only issue is babel-loader. After the fresh creation from the vue cli, if you run `pnpm i babel-loader --shamefully-flatten` you can then serve the app.

**Comment by schmurfy** [comment]
after being really annoyed by npm for just wasting my disk space I tried pnpm hopefull it would be my savior but it looks like I was wrong...
I created a fresh new vuejs app, ran `pnpm i` and `pnpm run serve` and it complains that `cache-loader` is not found.

is there any way to make this works with vuejs ?
I am working on three projects mostly sharing the same dependencies and I would really benefit from a reasonnable package management solution (which npm is not).

I am using vue 3.5.1 and pnpm 3.1.0

PS: I also tried sumlink the complete node_modules but npm does not have any way I found to not prune the unused packages...

**Comment by zkochan** [comment]
I guess they work on better pnpm support: https://twitter.com/jotadeveloper/status/1116606591061483521

For now, as mentioned above, create a npmrc in the root of your project with the following content:

```
shamefully-flatten=true
```

and reinstall your node_modules.

**Comment by schmurfy** [comment]
it failed when I tried `npm install --shamefully-flatten` before posting here but adding it to `.npmrc` worked, thanks :)

**Comment by TemaSM** [comment]
`pnpm` support as package manager added as PR and merged to `vue-cli`
https://github.com/vuejs/vue-cli/pull/3790
So, now no need to apply `shamefully-flatten` by hand, because `vue-cli` handles it under the hood 👍

**Comment by zkochan** [comment]
That's great!! Thank you @sodatea and @TemaSM!
