### ISSUE TITLE
Mssing peer deps for wrong package

### ISSUE THREAD

**Issue by Zweird-958** [pnpm/pnpm#8323]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.5.0

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/zweird-958/my-wishlist/

### Reproduction steps

Go on branch `chore/eslint` and do `pnpm i`

### Describe the Bug

I need to install `@types/node` whereas `ts-node` isn't installed.
<img width="294" alt="image" src="https://github.com/user-attachments/assets/acf24648-08a6-4deb-a5f1-7ba7f40febbe">

It's installed only on `packages/db`

### Expected Behavior

Avoid to have this warning

### Which Node.js version are you using?

20.9.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Actually, the bug here is that `@types/node` wasn't automatically installed.

If you don't want ts-node (and other peers) automatically installed, set `auto-install-peer` to `false` in your `.npmrc`.

**Comment by Zweird-958** [comment]
> Actually, the bug here is that `@types/node` wasn't automatically installed.
> 
> If you don't want ts-node (and other peers) automatically installed, set `auto-install-peers` to `false` in your `.npmrc`.

But `tooling/tailwind` doesn't use `ts-node` so what I have this warning ?

**Comment by zkochan** [comment]
One of the dependencies of `tailwindcss` has `ts-node` in peer dependencies, so it gets installed because `auto-install-peers` is set to `true` by default.

**Comment by Zweird-958** [comment]
> One of the dependencies of `tailwindcss` has `ts-node` in peer dependencies, so it gets installed because `auto-install-peers` is set to `true` by default.

I don't find any peer dependencies in tailwindcss https://www.npmjs.com/package/tailwindcss?activeTab=code

Also I have `ts-node` in `packages/db` and if I remove from it. I doesn't have the warning on `tooling/tailwind`.

I don't think is that...

**Comment by kenrick95** [comment]
- `tailwindcss` depends on `postcss-load-config`
- `postcss-load-config` has `ts-node` on its peerDependencies and it is marked as optional

https://github.com/Zweird-958/my-wishlist/blob/bb2f6c7be502b02907e313cefc73c001c4c2337f/pnpm-lock.yaml#L5649

**Comment by Zweird-958** [comment]
> > I don't find any peer dependencies in tailwindcss
> 
> * `tailwindcss` depends on `postcss-load-config`
> * `postcss-load-config` has `ts-node` on its peerDependencies and it is marked as optional
> 
> https://github.com/Zweird-958/my-wishlist/blob/bb2f6c7be502b02907e313cefc73c001c4c2337f/pnpm-lock.yaml#L5649

Hmm thank you for your answer but I'm not sure is the issue.

I deleted ts-node from `packages/db` and I don't have any warning

<img width="791" alt="image" src="https://github.com/user-attachments/assets/f860fda9-8adb-4a6e-8f83-7ec93d51aa20">
