### ISSUE TITLE
Old upgrade instructions were nicer

### ISSUE THREAD

**Issue by benmccann** [pnpm/pnpm#8328]
### Last pnpm version that worked

?

### pnpm version

9.5.0

### Code to reproduce the issue

pnpm install

### Expected behavior

If there was a new version of pnpm available it used to tell you to upgrade by doing something along the lines of `pnpm install -g pnpm`

### Actual behavior

Now it says:
> Run a script from: https://pnpm.io/installation

That's much less user-friendly because rather than just giving me the command to run it makes me go to a website to get the command

### Node.js version

20.13.1

### Operating System

Linux

**Comment by zkochan** [comment]
If you have used the standalone script to install pnpm, then you installed an executable version of pnpm that is bundled with node.js. We can't suggest you to update pnpm with `pnpm install -g pnpm` because that would install a version of pnpm that isn't bundled with node.js.

**Comment by benmccann** [comment]
Ah, I see. This was a result of me uninstalling and then reinstalling pnpm then. Thanks for the help!
