### ISSUE TITLE
.npmrc settings with array syntax (like public-hoist-pattern) break when PNPM runs via NPX or a package.json script

### ISSUE THREAD

**Issue by daniele-orlando** [pnpm/pnpm#8339]
### Update

The issue is tracked by a [Pull Request](https://github.com/pnpm/npm-conf/pull/14).

### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.6.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

[pnpm-bug-hoist-pattern.zip](https://github.com/user-attachments/files/16367400/pnpm-bug-hoist-pattern.zip)
[hoist-pattern Video Demo](https://drive.google.com/file/d/1zapEmUaPttj0XpTWKmFGl2izdIE-sgU9/view?usp=sharing)

[pnpm-bug-public-hoist-pattern.zip](https://github.com/user-attachments/files/16367411/pnpm-bug-public-hoist-pattern.zip)
[public-hoist-pattern Video Demo](https://drive.google.com/file/d/1fBEYUosdaXf7VFvPkNxKZjPwP8aTs4G8/view?usp=sharing)

### Reproduction steps

`pnpm config`:
1. extracts `pnpm-bug-public-hoist-pattern.zip`
2. run `corepack pnpm config get public-hoist-pattern`
3. check that the output is `*types*,*rt3*,*nestjs*`
4. run `npx pnpm config get public-hoist-pattern`
5. check that the output is `*types*\n\n*rt3*\n\n*nestjs*`

`pnpm-bug-hoist-pattern.zip`:
1. extracts `pnpm-bug-hoist-pattern.zip`
2. `npm run init`
3. check that none of the dependencies matching the `hoist-pattern` are hoisted inside `./node_modules/.pnpm/node_modules`
4. check that there is no `./node_modules/.pnpm/node_modules` directory at all

`pnpm-bug-public-hoist-pattern.zip`:
1. extracts `pnpm-bug-public-hoist-pattern.zip`
2. `npm run init`
3. check that none of the dependencies matching the `public-hoist-pattern` are hoisted inside `./node_modules`

### Describe the Bug

Running `npx pnpm install` or `npm run init` (which is a script that executes `corepack pnpm install`) breaks PNPM. But running `corepack pnpm install` works as expected.

### Expected Behavior

It should be possible to run pnpm as _package.json_ script or via _npx_, and settings with array syntax (like hoist-pattern and public-hoist-pattern) defined in the _$PWD/.npmrc_ should work as expected.

### Which Node.js version are you using?

22.3.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
> check that none of the dependencies matching the public-hoist-pattern are hoisted inside ./node_modules

I see all the dependencies hoisted to `node_modules`.

Also, you can't hoist both to `node_modules/.pnpm/node_modules` and `node_modules`. So, it doesn't make sense to assign the same patterns to both `hoist-pattern` and `public-hoist-pattern`.

**Comment by daniele-orlando** [comment]
Hi @zkochan. I created one `.npmrc` for simplicity but for clarity I updated the reproduction steps using two distint use cases, one for `hoist-pattern` and one for `public-hoist-pattern`.

**Comment by daniele-orlando** [comment]
<img width="1261" alt="Screenshot 2024-07-24 alle 22 57 10" src="https://github.com/user-attachments/assets/2c95c114-63d5-48b5-842c-f659d179ebe5">
<img width="1261" alt="Screenshot 2024-07-24 alle 22 58 06" src="https://github.com/user-attachments/assets/d0a7d60b-4907-435e-9b45-512d1b73f0bb">

**Comment by daniele-orlando** [comment]
### Update 1

Using `corepack pnpm install` everything works just fine.
Using `npm run init` which is a script thats executed `corepack pnpm install` breaks PNPM.

**Comment by daniele-orlando** [comment]
### Update 2
I added a `get-public-hoist-pattern` script inside the package.json, which does `corepack pnpm config get public-hoist-pattern`.

Running `corepack pnpm config get public-hoist-pattern` I obtain:
```
*types*,*rt3*,*nestjs*
```

Running `npm run get-public-hoist-pattern` I obtain:
```
*types*

*rt3*

*nestjs*
```

**Comment by daniele-orlando** [comment]
How could it be possible? 🤔

**Comment by daniele-orlando** [comment]
### Update 3

I placed some console logs inside the source code of PNPM for logging the `pnpmConfig`.

```sh
./node_modules/.bin/pnpm i | rg -i hoist

# => publicHoistPattern: [ '*types*', '*rt3*', '*nestjs*' ],
```

```sh
npx pnpm install | rg -i hoist

# => publicHoistPattern: '*types*\n\n*rt3*\n\n*nestjs*',
```

```sh
npm run init | rg -i hoist

# => publicHoistPattern: '*types*\n\n*rt3*\n\n*nestjs*',
```

**Comment by daniele-orlando** [comment]
After the discoveries I updated the Title and Description of the issue to reflect the actual problem, which is not specific of the hoisting mechanism, while of the config parsing.

**Comment by daniele-orlando** [comment]
@zkochan can I have some feedback please?

**Comment by daniele-orlando** [comment]
I opened a pull request to point out the problem location.

```
hoist-pattern
public-hoist-pattern
```
are parsed by NPM and re-exported as ENV variables with incorrect values due to the fact that NPM does not understand array syntax. Those incorrect ENV variables take precedence over `.npmrc` settings parsed by PNPM, resulting in an incorrect settings merging.

**Comment by front-end-captain** [comment]
@daniele-orlando This bug has existed since version v6 and is now finally fixed !
