### ISSUE TITLE
New reporter. Less fancy, more informative

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#834]
The current console reporting of pnpm tries to be beautiful but is not too informative.

Lets' try a new approach. The aim of pnpm is to *be blazingly fast*, so we don't need progress bars or estimates. We do need stats at the end + some useful info and warnings during install. We need something similar to git's reporting. Only important info, mostly black and white output and only the last row being updated.

**Comment by Announcement** [comment]
plese make this optional i love the current reporter

**Comment by zkochan** [comment]
Did you try the latest one? It has a summary that lists all the add/removed top deps

![](https://camo.githubusercontent.com/a0094f3df658c34c09bbf6839674625a5322c3f9/687474703a2f2f692e696d6775722e636f6d2f327059326b5a502e706e67)

it also marks the deprecated top deps

![](https://camo.githubusercontent.com/89c65a7c164017016d98e96a82d9b0480b788e13/687474703a2f2f692e696d6775722e636f6d2f4278614f7a59522e706e67)

Reporting is hard, I am still trying to normalize the different log types and formats but once they are not experimental, you'll be able to use even custom reporters because pnpm uses bole and [ndjson](https://www.npmjs.com/package/ndjson)
