### ISSUE TITLE
Release of package that has peerDependency with `workspace:^1.0.0` results in `^1.0.01.0.0` in npmjs

### ISSUE THREAD

**Issue by DominicGBauer** [pnpm/pnpm#8355]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://www.npmjs.com/package/@powersync/web/v/1.2.2?activeTab=code

### Reproduction steps

When creating a release with pnpm for a package that uses pnpm > 9.4 if the package has a peerDependency with `workspace:^x.y.z` then it converts to `^x.y.za.b.c` (a,b,c. might be equal to x,y,z but that's not really imporatant). So workspace followed by a semver results in something like this when released.

We have isolated this to versions of pnpm >= 9.4. It is most likely this PR which has caused the issue https://github.com/pnpm/pnpm/pull/7633.

Example in repo:
<img width="335" alt="image" src="https://github.com/user-attachments/assets/3dca4bc5-b943-4b37-ab11-f56b4fdc20cf">

Example in npmjs:
<img width="306" alt="image" src="https://github.com/user-attachments/assets/7fe1d775-51bb-4923-9f51-8a718c983eda"> 

### Describe the Bug

Versions of pnpm >= 9.4 results in peerDependency issue when using workspace followed by a semver e.g. `workspace:^1.2.0` which gets converted to `^1.2.01.2.0` when package is released on `npmjs`

### Expected Behavior

When using `workspace:^1.2.0` or similar it becomes `^1.2.0` in npmjs and not `^1.2.01.2.0`

### Which Node.js version are you using?

20.12.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by manudeli** [comment]
We have same problem too. cc. @sungh0lim @gwansikk @kangju2000 @bigsaigon333 @SEOKKAMONI

**Comment by manudeli** [comment]
https://pnpm.io/workspaces#publishing-workspace-packages

Below is expected

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/6dee4072-9e44-43ad-856d-dc1a47be2002">

**Comment by WhiteKiwi** [comment]
I ve got same issue
