### ISSUE TITLE
Pnpm install hangs indefinitely

### ISSUE THREAD

**Issue by hoghweed** [pnpm/pnpm#8370]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.6.0

### Reproduction steps

- create an pnpm workspace
- setup nvm with `.nvmrc` with `20.16.0`
- add a new nodejs simple app and name it app1
- install the `langchain` package from the root `pnpm add langchain --filter app1`

### Describe the Bug

- Once installed, if you try to update using the `pnpm update --latest --recursive` pnpm hangs indefinitely
- Once installed, if you try to recreated the pnpm lockfile from the root  pnpm hangs indefinitely

The only way I make it working is to remove langchain from package.json, update and then reinstall from scratch.

With langchain installed I can't install any new package.

I executed the install command using `--reporter ndjson` and noticed it hangs when trying to resolve the graphql package.

I'm getting crazy because there's no logic in this behavior.
Any help would be more than appreciated.

### Expected Behavior

- if executing `pnpm add` to add a package
- if executing `pnpm update` to perform update

everything without hanging indefinitely

### Which Node.js version are you using?

20.16.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hoghweed** [comment]
Hello here

This seems very embarrassing for me because I can't make it work pnpm with langchainjs. I'm desperate because I cannot find a suitable solution other than removing langchain package, install any package with pnpm and then install back langchain.

**Comment by TheHussein** [comment]
I'm facing the same issue in a much bigger project only locally and only in a container, for me I investigated different packages it would hang at but it would just hang at a different large one so I wouldn't jump to blame langchainjs.

The only solution I noticed is node 16 + pnpm v8 seems to work but node 16 has already hit EOL so that's not really a fix.

**Comment by karlomedallo** [comment]
Encountered the same problem. My workaround is to download to 9.1.0 . I tried 9.1.1 but thats the version where things get stuck indefinitely

**Comment by zkochan** [comment]
Does it hang indefinitely or does it fail with an out of memory error? I think it is happening when peer dependencies are installed as regular dependencies in some parts of the graph. Not sure yet how to properly solve it. Maybe just by forcing peer dependencies to be singletons, like in this PR: https://github.com/pnpm/pnpm/pull/8453

**Comment by karlomedallo** [comment]
> Does it hang indefinitely or does it fail with an out of memory error? I think it is happening when peer dependencies are installed as regular dependencies in some parts of the graph. Not sure yet how to properly solve it. Maybe just by forcing peer dependencies to be singletons, like in this PR: #8453

In my case, it just gets stuck definitely. Other observations I have is that the older version of langchain and langchain community, like from a month or 2 ago works fine.

**Comment by zkochan** [comment]
You can try to test my fix from https://github.com/pnpm/pnpm/pull/8457

**Comment by riqts** [comment]
@zkochan Our project hung indefinitely given langchains peer dependencies "conflicting" with our dependencies mongodb and some aws-credential-providers during resolution. This was resolved by downgrading from  >=9.1.1 to <9.1.1.

I have tested your recent PR and it seems to resolve at least our exact issue, so thanks for the work!

**Comment by zkochan** [comment]
:ship: 9.9

**Comment by gluxon** [comment]
Outside of memory usage, the previous behavior was better — would you agree @zkochan?

The way pnpm ensures a peer dependency is respected through an entire dependency subgraph is one of my favorite features in pnpm because it allows incremental migration to a new major version of a dependency without accidentally leaking incompatible versions between those subgraphs.

Would you be open to me trying to reduce the memory usage of the previous algorithm? I'm not sure if I'll succeed, but if so, would you be open to bringing the original behavior back in pnpm v10?

**Comment by bdebever** [comment]
On my side the issue isn't solve. I am not running langchain. I am running on node 20. Any idea?

**Comment by ScriptedFluff** [comment]
I had the same issue.
To fix it I did the following:
1. Remove node_module folder
2. run "pnpm store prune"
3. run "pnpm install"

**Comment by AnderssonPeter** [comment]
The following did the trick for me
1. Run `pnpm clean`
2. Remove node_module folder
4. run `pnpm install`
