### ISSUE TITLE
Remove the default option `*eslint*` and `*prettier*` from `public-hoist-pattern` option in next major version

### ISSUE THREAD

**Issue by zanminkian** [pnpm/pnpm#8378]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

1. Eslint 9 support [flat config](https://eslint.org/blog/2022/08/new-config-system-part-2/). We don't need to hoist modules about eslint any more.
2. Prettier `plugins` field will be passed to `import() expression`. Users can resolve the plugin module path by themselves (like `require.resolve('prettier-plugin-foo')`). See the [doc](https://prettier.io/docs/en/plugins).

> Strings provided to plugins are ultimately passed to [import() expression](https://nodejs.org/api/esm.html#import-expressions), so you can provide a module/package name, a path, or anything else import() takes.

Therefore, now is the proper time for removing the default option `*eslint*` and `*prettier*` from `public-hoist-pattern`. Users will get a clean and consistent `node_modules` folder. Hiding `*eslint*` and `*prettier*` in `public-hoist-pattern` seems not a wise choice.

### Describe the solution you'd like

Remove the default option `*eslint*` and `*prettier*` from `public-hoist-pattern` option.

https://pnpm.io/npmrc#public-hoist-pattern

### Describe the drawbacks of your solution

This is a breaking change.

### Describe alternatives you've considered

No.

**Comment by waynebrantley** [comment]
Just spent several days trying to figure out why pnpm did not work with eslint flat config while npm does.  This is exactly why!  Thanks for the information @zanminkian    Perhaps they will change the defaults in the next version.

**Comment by weyert** [comment]
Wouldn't this break things for everyone not using Eslint flat config?

**Comment by virtuallyunknown** [comment]
This change caused a lot of headaches for me. I have an eslint-config package that has `eslint` as a direct dependency, this way I don't have to install eslint separately. But now that `eslint` does not get hoisted in `node_modules` by default, the VSCode Eslint plugin stops working for whatever reason.

I figured I can just add `eslint` as a peer dependency to my package instead, then `eslint` will get installed anyway since `auto-install-peers` is on by default. It does indeed install `eslint`, but it puts it in `node_modules/.pnpm`, which once again breaks the extension.

So now, at least to my knowledge, the only option I have is to explicitly install eslint alongside my eslint-config in order to get this working.

**Comment by Sitronik** [comment]
> This change caused a lot of headaches for me. I have an eslint-config package that has `eslint` as a direct dependency, this way I don't have to install eslint separately. But now that `eslint` does not get hoisted in `node_modules` by default, the VSCode Eslint plugin stops working for whatever reason.
> 
> I figured I can just add `eslint` as a peer dependency to my package instead, then `eslint` will get installed anyway since `auto-install-peers` is on by default. It does indeed install `eslint`, but it puts it in `node_modules/.pnpm`, which once again breaks the extension.
> 
> So now, at least to my knowledge, the only option I have is to explicitly install eslint alongside my eslint-config in order to get this working.

This is not the only option.
I encountered the same problem, an example of the correct syntax in .npmrc:
```
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
```
After applying this configuration there will be no problems with eslint and prettier

**Comment by virtuallyunknown** [comment]
> 
> This is not the only option.
> 
> public-hoist-pattern: nothing is hoisted by default. Packages containing eslint or prettier in their name are no longer hoisted to the root of node_modules. Related Issue: [#8378](https://github.com/pnpm/pnpm/issues/8378)
> 
> I encountered the same problem, an example of the correct syntax in .npmrc:
> 
> ```
> public-hoist-pattern[]=*eslint*
> public-hoist-pattern[]=*prettier*
> ```
> 
> After applying this configuration there will be no problems with eslint and prettier

Sorry, I phrased myself poorly. Yes, obviously what you suggested would work, but then you're going against the default settings, so you'd have to instruct anyone using your package to use these settings as well. I guess `eslint` will become an install requirement now, but it was so nice having everything as one single package.

Another issue is that `auto-install-peers` is enabled by default (which is totally reasonable of course), so when I added `eslint` as a peer dependency of my package, pnpm installs that alongside it in `node_modules/.pnpm`, but of course you then need to install it and additional time for the VSCode plugin to work.

**Comment by loky-lp** [comment]
Just FYI, `prettier@3.5.3` (the latest at the time of writing) completely nukes itself without adding it back to the `public-hoist-pattern`.
Seems it can't find any plugin.

If someone is interested i can provide a reproduction repo, just ping me.
