### ISSUE TITLE
[ERR_PNPM_READ_FROM_STORE] Unexpected token '', ""... is not valid JSON

### ISSUE THREAD

**Issue by Jay-Karia** [pnpm/pnpm#8381]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.6.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Store

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Jay-Karia/material-ui

### Reproduction steps

1. Navigate to the codebase
2. Run `pnpm install`

### Describe the Bug

I am trying to install packages using `pnpm`, and I am getting this error:
![pnpm](https://github.com/user-attachments/assets/133c060e-e987-46b8-8955-14246550bd8f)

### Expected Behavior

It should flawlessly install packages.

### Which Node.js version are you using?

20.9.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by AufaIrfan** [comment]
how do you solved that bug?

**Comment by Jay-Karia** [comment]
I tried deleting the store.

**Comment by Jay-Karia** [comment]
After deleting the `store` folder from local machine, try re running the install script.

This worked for me.
