### ISSUE TITLE
Yarn Workspaces

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#839]
Something we might want to track: https://github.com/yarnpkg/yarn/issues/3294

> Workspaces adds support for managing multiple packages within a single Yarn project. Linking between them on install to make cross-development simpler.

Perhaps pnpm can do this more easily than yarn because of our dep structure?

**Comment by donaldpipowitch** [comment]
Any chance to have drop-in support for yarn workspaces in pnpm? 🤔

**Comment by zkochan** [comment]
From v1.24 pnpm has a command for concurrently installing dependencies in many projects ([pnpm recursive install](https://pnpm.js.org/docs/usage/pnpm-cli.html#recursive)).

We can extend that command with the ability to link packages. I don't know whether we should use Yarn's "workspaces" field for that. We search for folders that have `package.json` files anyway. So currently pnpm finds all the workspaces in subfolders w/o the "workspaces" field.

**Comment by donaldpipowitch** [comment]
Interesting. I'll try that tomorrow. Thanks.

**Comment by zkochan** [comment]
I just published [pnpm@1.32.0](https://github.com/pnpm/pnpm/releases/tag/v1.32.0) which has a new command called [pnpm recursive link](https://pnpm.js.org/docs/usage/pnpm-cli.html#recursive-link). This new command links packages in the monorepo and concurrently installs rest of the dependencies.

**Comment by donaldpipowitch** [comment]
That sounds interesting! Thank you for the update. I hope I can test this soon (I currently have problems with my setup).

**Comment by zkochan** [comment]
So we have this. You can track the issues related to multi-package repo functionality via the [multi-package repo](https://github.com/pnpm/pnpm/labels/multi-package%20repo) label.
