### ISSUE TITLE
Updating dependency version in workspace only updates specifier in lock file, but not the version, when (re)adding to workplace package before running `pnpm i`

### ISSUE THREAD

**Issue by Simon-Laux** [pnpm/pnpm#8407]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.7.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

#### Initial state:
pnpm-workspace.yaml
```yaml
packages:
  - packages/*
catalog:
  # deltachat specific
  '@deltachat/jsonrpc-client': 1.141.2
  '@deltachat/stdio-rpc-server': 1.141.2
...
```
pnpm-lock.yaml
```yaml
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

catalogs:
  default:
    '@deltachat/jsonrpc-client':
      specifier: 1.141.2
      version: 1.141.2
    '@deltachat/stdio-rpc-server':
      specifier: 1.141.2
      version: 1.141.2
...
```

#### Action
modify the versions in the workspace file.
```diff
diff --git a/pnpm-workspace.yaml b/pnpm-workspace.yaml
index ccbf009b8..c6b636f13 100644
--- a/pnpm-workspace.yaml
+++ b/pnpm-workspace.yaml
@@ -2,8 +2,8 @@ packages:
   - packages/*
 catalog:
   # deltachat specific
-  '@deltachat/jsonrpc-client': 1.141.2
-  '@deltachat/stdio-rpc-server': 1.141.2
+  '@deltachat/jsonrpc-client': 1.142.1
+  '@deltachat/stdio-rpc-server': 1.142.1
   webxdc-types: ^1.0.1
 
   # dependencies
```

then run `pnpm add --save @deltachat/jsonrpc-client@catalog: @deltachat/stdio-rpc-server@catalog:` in a workspace package and then run `pnpm i`

#### Actual result
Observe that it does only update the specifier, but not the version. also the installed package is still the old one.

```diff
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index 1d3bf8700..f1f5ac0d5 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -7,10 +7,10 @@ settings:
 catalogs:
   default:
     '@deltachat/jsonrpc-client':
-      specifier: 1.141.2
+      specifier: 1.142.1
       version: 1.141.2
     '@deltachat/stdio-rpc-server':
-      specifier: 1.141.2
+      specifier: 1.142.1
       version: 1.141.2
     '@types/mime-types':
       specifier: ^2.1.4
```

### Describe the Bug

When changing versions in a workspace catalog and then adding the catalog dependency to a workspace package it should update the dependencies in node_modules and in lockfile.
In this case it does not update them, it updates only the specifier, that's the bug.

See reproduction steps for an example.

I also tried the version with `^` in front of it, that sometimes works, but also not reliable and in this case I need exact versions.

#### Workaround

run `pnpm i` directly after the modification and before (re)adding the catalog dependency to a workspace package

### Expected Behavior

version in lock file and installed package version are updated.

### Which Node.js version are you using?

v20.12.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Simon-Laux** [comment]
I can't reliably reproduce this manually. I ran this in a script, maybe there the order mattered more there.
Anyways the workaround / better way was to call `pnpm I` before `cd pakages/my-packae && pnpm add --save @deltachat/jsonrpc-client@catalog: @deltachat/stdio-rpc-server@catalog:` in my script, now it works.

So closing this now.
I'm looking forward to an official pnpm command to manage/update workspace catalog dependencies.

**Comment by ragrag** [comment]
facing the same issue, don't know how to reproduce consistently
