### ISSUE TITLE
win10 npm安装@pnpm/exe 通过powershell使用pnpm会出现弹窗

### ISSUE THREAD

**Issue by hasnum-stack** [pnpm/pnpm#8439]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.7.1

### Reproduction steps

pnpm -v

### Describe the Bug

如题

### Expected Behavior

如

### Which Node.js version are you using?

16

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by tomasvn** [comment]
You have to have node `>= 18`. According to [docs](https://pnpm.io/installation#compatibility) for pnpm `v9`

**Comment by hasnum-stack** [comment]
后面执行了一下 pnpm setup 解决了
