### ISSUE TITLE
support peerDependencies for scoped packages

### ISSUE THREAD

**Issue by jlsjonas** [pnpm/pnpm#845]
### pnpm version:
1.4.0

### Code to reproduce the issue:
Install a package containing peerDependencies

### Expected behavior:
the peerDependencies to be under `project/node_modules/`

#### OR

as per [npmjs docs](https://docs.npmjs.com/files/package.json#peerdependencies)
>NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead.

it should give a warning declaring the peer is missing, instead of silently installing it where it apparently can't be found

### Actual behavior:
they seem to reside under `project/node_modules/.registry.npmjs.org/` instead, causing the package not to be found (by eslint, in this case)

### Additional information:

 - `node -v` prints: v7.9.0
 - Windows, OS X, or Linux?: OS X
 - [article about peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies)

**Comment by zkochan** [comment]
We support `peerDependencies`. If you have some specific issue, please write more details.

**Comment by zkochan** [comment]
There is an issue with an eslint package described here: https://github.com/pnpm/pnpm/issues/739

But the error is in the package, not in pnpm

**Comment by zkochan** [comment]
Also related: https://github.com/pnpm/pnpm/issues/827.

pnpm does correctly resolve peer dependencies. pnpm is never silent when a peer dep is correctly declared in `package.json`

**Comment by jlsjonas** [comment]
Actually it seems to be the case for us anyway, we have a private package declaring all the required (missing as per #739, which is another issue indeed) dependencies, amongst which eslint-plugin-import itself; I don't get any console output (using `pnpm i`) which indicates I'm missing those peerDependencies though. maybe it has something to do with the `@organisation/package-name` format? (just guessing though)

**Comment by zkochan** [comment]
We have a test that checks whether peer warnings are reported:
https://github.com/pnpm/supi/blob/master/test/install/peerDependencies.ts#L54-L67

Unlikely caused by the scope.

As far as I remember, the issue with #739 is not because a peer is not resolved but because eslint-plugin-import does not resolve dependencies the way node does.

**Comment by jlsjonas** [comment]
I just checked in an empty repo, steps to reproduce:

- have a scoped package containing one/more peerDependencies
- do an `npm init` in an empty directory (just for completion)
- `pnpm install` the scoped package

Expected: warning about missing peerDependencies, or installing them automatically

Actual: only the scoped package is installed without any warning, even though they're listed when cat-ing

Possible cause: scoped packages reside under their own @-directory, the peerDependency checker likely doesn't go through those folders

**Comment by zkochan** [comment]
I just checked this on [@angular/core](https://github.com/angular/angular/blob/fa809ec8cf73cb6b7a9a3af86831a62a456dc160/packages/core/package.json) which has two peer dependencies.

I did `pnpm i @angular/core`. And I did get the warnings:

```
Creating dependency tree
WARN registry.npmjs.org/@angular/core/4.3.0 requires a peer of rxjs@^5.0.1 but none was installed.
WARN registry.npmjs.org/@angular/core/4.3.0 requires a peer of zone.js@^0.8.4 but none was installed.
Adding 2 packages to node_modules
Resolving: total 2, reused 1, downloaded 1, done

+ @angular/core 4.3.0
```

**Comment by jlsjonas** [comment]
Using `@angular/core` I indeed get the expected results (removing node_modules & shrinkwrap after every test to be reproducible)
```
$ pnpm i
Resolving: total 2, reused 2, downloaded 0, done
Creating dependency tree
WARN registry.npmjs.org/@angular/core/4.3.1 requires a peer of rxjs@^5.0.1 but n
one was installed.
WARN registry.npmjs.org/@angular/core/4.3.1 requires a peer of zone.js@^0.8.4 bu
t none was installed.
Adding 2 packages to node_modules

+ @angular/core 4.3.1
```

If we do the same with our custom package (both @angular/core and our package declaring peerDependencies in the same way, except for order of the items in the package.json, which shouldn't matter)

```
$ pnpm i
Creating dependency tree
Resolving: total 185, reused 176, downloaded 9, done
Adding 185 packages to node_modules

+ @***/eslint-config 1.1.1
```


Only thing to note that might affect this is that our package also has the peerDependencies in it's dependency list; maybe that's what's avoiding the warning? (even though they aren't in the direct dependency tree)

**Comment by zkochan** [comment]
> Only thing to note that might affect this is that our package also has the peerDependencies in it's dependency list

you mean they are prod dependencies (`dependencies`) not `devDependencies?

> even though they aren't in the direct dependency tree

what do you mean?

**Comment by jlsjonas** [comment]
> you mean they are prod dependencies (dependencies) not `devDependencies?
Correct
> what do you mean?
that the peerDependencies/dependencies are not directly under `node_modules/` (as would be with the npm3 flattening)

**Comment by zkochan** [comment]
If anyone will be able to repro this with pnpm v2.17.7 or newer, please create a new issue
