### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by EricWangQvQ** [pnpm/pnpm#8458]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.7.0 & 9.7.1 & 9.8.0

### Reproduction steps

pnpm -v

### Describe the Bug

 ERROR  Cannot read properties of undefined (reading 'includes')
For help, run: pnpm help

### Expected Behavior

console version

### Which Node.js version are you using?

v22.7.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

macOS Sequoia

**Comment by fvckDesa** [comment]
@ericwang-wsq I had the same error, in my case it was caused by a misspelled "packageManager" field in package.json

**Comment by ericwang-wsq** [comment]
Thank you. Running correctly after removing the "packageManager" property.
