### ISSUE TITLE
PNPX does not respect the given package with version

### ISSUE THREAD

**Issue by Ketcap** [pnpm/pnpm#8472]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

9.8.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

On a monorepo setup where there's a runnable package installed running "pnpx" does not respect the given package.

Project Root with (turbo@1.13.4)
```cmd
pnpx turbo@latest --version
```
Output for that is : 1.13.4

Outside of project
```cmd
pnpx turbo@latest --version
```
Output is 2.1.0

### Describe the Bug

PNPX not respecting the package with version i want to run.

### Expected Behavior

I'd like pnpx to run exactly what I've given as a version to run.

### Which Node.js version are you using?

v20.17.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
There is no issue with pnpm. This is turbo automatically switching to the local instance. This reproduces with turbo installed globally. Try to install the latest turbo with `pnpm i -g turbo@latest`, then run `turbo --version` inside and outside the project.

**Comment by Ketcap** [comment]
Thanks for pointing out. I've not realised that. 
For those who will check this in the future: I've tested with different packages like "vitest" and they work without issue
