### ISSUE TITLE
pnpm@9.9.0 deploy lost the pkgs in node_modules

### ISSUE THREAD

**Issue by shalldie** [pnpm/pnpm#8475]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.9.0

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/shalldie/pnpm9.9.0-deploy-error

### my projects layout

```
.
├── README.md
├── package.json
├── packages
│   └── app
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```

### .npmrc

```bash
registry=https://registry.npmjs.org/
shamefully-hoist=true
shared-workspace-lockfile=false
```

### pnpm@9.9.0 run deploy get the error node_modules

deploy steps with `9.8.0` and `9.9.0`:

```bash
rm -rf output && \
pnpm --filter=app --prod deploy ./output/app

cd output/app
node index.js

# pnpm@9.8.0 works well,
# 9.9.0 fail, can't find any pkgs in node_modules
```

I found `9.9.0` only has the .pnpm in node_modules, the pkgs are lost.

```bash
ls -a output/app/node_modules

# 9.8.0
.  ..  .modules.yaml  .pnpm  mini-tpl

# 9.9.0
.  ..  .pnpm
```

### Describe the Bug

pnpm@9.9.0 deploy, will lost the pkgs in node_modules.

### Expected Behavior

pnpm deploy works well as before.

### Which Node.js version are you using?

v20.16.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

ubuntu

**Comment by youzi-2333** [comment]
Don't download this file. This is a computer virus.

**Comment by bm77525-kr** [comment]
This sounds related to:

* https://github.com/pnpm/pnpm/issues/6682
* https://github.com/pnpm/pnpm/issues/6259#issuecomment-1644693101
* https://github.com/pnpm/pnpm/issues/6166#issuecomment-1455562090

This has been broken for quite some time but unfortunately the devs continue to ignore it.

**Comment by zkochan** [comment]
Issues with non-default settings usually have lower priority. Especially with `shared-workspace-lockfile=false`, which is a setting that is very hard to maintain and which I never recommended to use.

**Comment by zkochan** [comment]
:ship: 9.11
