### ISSUE TITLE
pnpm 9.9.0 installs different Vite versions in a monorepo

### ISSUE THREAD

**Issue by sheremet-va** [pnpm/pnpm#8488]
### Last pnpm version that worked

9.7.0 (didn't check 9.8.0)

### pnpm version

9.9.0

### Code to reproduce the issue

renovate commit: [vitest-dev/vitest@`9b25553` (#6360)](https://github.com/vitest-dev/vitest/pull/6360/commits/9b25553ac0fe53865e448e36718f8d73a994c086)

- two packages define "vite" in dependencies
- one package (vitest) also defines `"@types/node": "^20.16.3"`
- the root package overrides all `"vite"` with `"^5.2.0"`

Vite with explicit `@types/node` in `vitest` package is stored in `node_modules/.pnpm/vite@5.4.2_@types+node@20.16.3_terser@5.22.0/node_modules/vite/dist/node/index `

VIte in another package (vite-node) is stored in `/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.2_terser@5.22.0/node_modules/vite/dist/node/index`

Note that vite-node's "vite" resolves to `@types+node@22.5.2` which is actually not even supported by Vite's package.json:

```json
{
  "peerDependencies": {
    "@types/node": "^18.0.0 || >=20.0.0"
  }
}
```

### Expected behavior

Both vite packages resolve to the same path.

### Actual behavior

vite packages resolve to different paths.

### Node.js version

20.12.2

### Operating System

macOS

**Comment by zkochan** [comment]
> Note that vite-node's "vite" resolves to @types+node@22.5.2 which is actually not even supported by Vite's package.json:

How so? The `>=20.0.0` part covers `22.5.2` as well:

```json
{
  "peerDependencies": {
    "@types/node": "^18.0.0 || >=20.0.0"
  }
}
```

I'd recommend either removing `@types/node` from `vite` or adding it to `vite-node`. That should solve the issue.
