### ISSUE TITLE
Dependency fails to dedupe

### ISSUE THREAD

**Issue by benmccann** [pnpm/pnpm#8500]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.9.0

### Reproduction steps

Run `pnpm install` with these two dependencies:
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "type": "module",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@sveltejs/adapter-netlify": "^4.3.3",
    "importx": "^0.4.4"
  }
}
```

### Describe the Bug

You'll end up with multiple versions of `esbuild` eventhough the dependencies have overlapping peer dependency ranges

### Expected Behavior

Just one version of `esbuild` should end up in the lockfile

### Which Node.js version are you using?

20.17.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by KSXGitHub** [comment]
I can't reproduce. I used your sample `package.json` and did a clean install and I saw only one version of esbuild which is 0.21.5:

![screenshot of pnpm why esbuild](https://github.com/user-attachments/assets/1ff8ea72-ae6f-4dac-9d32-99e5dbe98a46)

**Comment by benmccann** [comment]
Wow. That is bizarre. What version of pnpm did you use?

Here is what I see:

![Screenshot from 2024-09-05 08-01-57](https://github.com/user-attachments/assets/ccc5f0ba-a304-4123-a7d0-5f80e7438aac)

**Comment by KSXGitHub** [comment]
I try to reproduce it again with pnpm@9.9.0, same result.

My dependencies tree doesn't have `importx`. Why does yours has it?

**Comment by benmccann** [comment]
Oh goodness. I posted the wrong `package.json` for the reproduction. I've updated the description now with the correct one. Sorry about that and thanks for noticing!

**Comment by KSXGitHub** [comment]
From the new `package.json`, `tsx` specifically requires `esbuild@~0.23.0` but `@sveltejs/adapter-netlify` requires `esbuild@^0.21.5`. This 2 version ranges have no overlap because in semver, when major is 0, minor is the breaking changes indicator.

**Comment by benmccann** [comment]
Ah, thanks so much!

`pnpm why` really helps here. I wasn't aware of it and was just looking through the lockfile manually, which is why I missed it. It generally works, but since esbuild has like 75 packages with esbuild in the name it was hard to spot.

I'm really sorry for the false report. Thank you so much for the help!
