### ISSUE TITLE
Sort packages in table displayed when running `pnpm outdated`

### ISSUE THREAD

**Issue by DamianGlowala** [pnpm/pnpm#8518]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

`dependencies`/`devDependencies` are sorted automatically in an alphabetical order by the package manager. When I run `pnpm outdated`, it would be great to have these sorted the same way too. I could then go through the outdated dependencies one by one and know these are located in the same order in my package.json without having to visually jump through a long list back and forth.

### Describe the solution you'd like

Sort outdated dependencies in a way which matches package.json sorting:
![image](https://github.com/user-attachments/assets/3c56d2f7-cbcb-4a30-b0e4-73933835b4d4)

### Describe the drawbacks of your solution

n/a

### Describe alternatives you've considered

n/a

**Comment by DamianGlowala** [comment]
@btea, based on the linked PR, would the list be now sorted by name by default, or would I need to add the flag to achieve the same sorting as in the package.json?

**Comment by btea** [comment]
To suit your needs you may need to add the `--sort name` flag when executing.
