### ISSUE TITLE
Add `--workspace-root` argument to `exec` command

### ISSUE THREAD

**Issue by jameshearttech** [pnpm/pnpm#8520]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

In CI we do not know what scripts exist, so `exec` makes more sense imo. In a monorepo we likely want to `exec` all projects (i.e., `--recursive`), but the `exec` command does not have the `--workspace-root` parameter like the `run`.

### Describe the solution you'd like

I would like `exec` to also have the `--workspace-root` parameter as `run` does.

### Describe the drawbacks of your solution

None I can think of offhand.

### Describe alternatives you've considered

Recurse from the root workspace (e.g., `pnpm exec prettier . --check`).

**Comment by KSXGitHub** [comment]
If you run the following command in any of the subdirectory of the monorepo, it should return the root path

```sh
pnpm --workspace-root exec pwd
```

Similary, you can replace `pwd` with any command you want to run:

```sh
pnpm --workspace-root exec prettier --check .
```
