### ISSUE TITLE
pnpm link should link bins

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#853]
> First, npm link in a package folder will create a symlink in the global folder {prefix}/lib/node_modules/<package> that links to the package where the npm link command was executed. (see npm-config for the value of prefix). **It will also link any bins in the package to {prefix}/bin/{name}.**

https://docs.npmjs.com/cli/link

At present you have to use `pnpm link -g`.

**Comment by zkochan** [comment]
Published in [v1.9.0](https://github.com/pnpm/pnpm/releases/tag/v1.9.0)
