### ISSUE TITLE
pnpm  >=9.9 deploy during create docker image do not create deployment in /app but try to create project in local directory

### ISSUE THREAD

**Issue by gawsoftpl** [pnpm/pnpm#8539]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

>=9.9

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Dockerfile
```sh
FROM node:20-alpine as base

RUN npm -g i --force pnpm@9.9


FROM base AS build

ARG PACKAGE

WORKDIR /build

# Mount deploy directory against Copy
RUN --mount=type=bind,source=.pnpm-store,target=/.pnpm-store \
    --mount=type=bind,source=.,target=/build \
    pnpm --store-dir=/.pnpm-store --filter=$PACKAGE deploy --no-optional --prod /app
```

Cli command
```sh
docker build --build-arg PACKAGE=@acme/microservice-name  -f docker/Dockerfile .
```

### Describe the Bug

`pnpm deploy` against generate deploy in /app directory try to create monorepo microservice deploy project in relative path  `/build/packages/microservices/app'`

In `pnpm 9.8` everythings works fine

### Expected Behavior

Should create deploy in /app directory

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Alpine

**Comment by zkochan** [comment]
We released fixes to the deploy command in pnpm v9.11. Is this still an issue?

**Comment by gawsoftpl** [comment]
> We released fixes to the deploy command in pnpm v9.11. Is this still an issue?

I will check in 2h

**Comment by gawsoftpl** [comment]
With version 9.11, no changes same issue and same error info:

pnpm: ENOENT: no such file or directory, mkdir '/build/packages/microservices/app'
#11 10.27     at async Object.mkdir (node:internal/fs/promises:858:10)
#11 10.27     at async _linkBins (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:105320:7)
#11 10.27     at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:197195:30
#11 10.27     at async Promise.all (index 0)
#11 10.27     at async _installInContext (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:197169:9)
#11 10.27     at async installInContext (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:197415:16)
#11 10.27     at async _install (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:196833:25)
#11 10.27     at async mutateModules (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:196485:23)
#11 10.27     at async recursive (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:198038:50)
#11 10.27     at async installDeps (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:198346:11)

**Comment by gawsoftpl** [comment]
I fixed this issue with:

ARG PACKAGE

WORKDIR /build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY . /build
RUN --mount=type=bind,source=.pnpm-store,target=/pnpm/store pnpm install --frozen-lockfile
RUN  pnpm --filter=$PACKAGE --store-dir=/pnpm/store deploy --no-optional --prod /app
