### ISSUE TITLE
`.pnpm_patches` folder does not get restored on a fresh install of `node_modules`

### ISSUE THREAD

**Issue by mcmxcdev** [pnpm/pnpm#8548]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.10.0

### Reproduction steps

- Patch any dependency like `pnpm patch @tabler/icons-svelte`
- Do changes on e.g. `Icon.svelte` in `.pnpm-patches` folder
- Run `pnpm patch-commit <folder>`
- Expect `package.json` to have `"patchedDependencies": { "@tabler/icons-svelte": "patches/@tabler__icons-svelte.patch" }` entry
- Run `rm -rf node_modules`
- Run `pnpm i --prefer-frozen-lockfile=false`
- Expect `.pnpm-patches` folder to reappear in `node_modules`, but it doesn't

### Describe the Bug

While everything about the patch seemed to have been applied perfectly locally, I noticed that our dev/prod deployments suddenly had icons which were way too big. 

I noticed that our custom `@tabler/icons-svelte` patch for sizing and stroke of icons didn't seem to get applied for some reason. 

Pretty certain that it is related to the fact that the Vercel deployment makes a fresh install of `node_modules` where the `.pnpm_patches` folder is not getting created.

### Expected Behavior

`.pnpm_patches` folder should show up when running `pnpm install` and patch be applied.

### Which Node.js version are you using?

20.17.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 24.04

**Comment by mcmxcdev** [comment]
It turns out that this is probably an issue with `@tabler/icons-svelte` itself. I think I also misunderstood what `.pnpm_patches` folder does (temporary folder for patching).

**Comment by zkochan** [comment]
As you said, those are temporary directories for editing the dependencies and submitting the changes. There is no reason to recreate them if you remove node_modules. We actually used to remove them on submitting the patches.

**Comment by mcmxcdev** [comment]
Still not sure what the root cause of my issue is, but my report is definitely not correct so I will close it.
