### ISSUE TITLE
scripts not called on `install <git dep>`

### ISSUE THREAD

**Issue by andreineculau** [pnpm/pnpm#855]
### Code to reproduce the issue:

see https://github.com/andreineculau/package-json-scripts

```shell
cd $(mktemp -d)
mkdir node_modules
pnpm install git://github.com/andreineculau/package-json-scripts.git # lists preinstall, install, postinstall

cd $(mktemp -d)
mkdir node_modules
npm install git://github.com/andreineculau/package-json-scripts.git # lists preinstall, install, postinstall, prepare, prepack, postpack, preinstall, install, postinstall
```

### Expected behavior:

same scripts as current npm version (5) intends to run

### Actual behavior:

only same scripts as npm@4 are run

### Additional information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - Windows, OS X, or Linux?: OSX

**Comment by andreineculau** [comment]
I should note that I didn't expect pnpm to perform so well re:scripts :clap: https://docs.google.com/spreadsheets/d/1XH8iDyOmNf-ZH3A2SMV5YTDcT2YPXmhFcaUPsIyYEu8/edit#gid=0

**Comment by zkochan** [comment]
Documentation of npm says that `prepack` should be executed when installing git dependencies. Not a word about prepare, postpack and second execution of install

**Comment by andreineculau** [comment]
We could look at it from multiple angles. One being that documentation is not up-to-date with the code or that it's not clear enough (by all means, that's why I started the `package-json-scripts` repo, but maybe that's just me). Another is the the docs hide implementation detail i.e. we may run other things, but we tell users to consider only that prepare is run, because that's what we run on `npm install (no args)`. And yet another being that I messed up my test (though I recently double-checked my results).

When looking at pacote though, you find this https://github.com/zkat/pacote/blob/latest/lib/fetchers/git.js#L20

I didn't look in super in depth, but my take is that the flow is as follows:

- if the git dep is already in the local cache, and we're in the cache window, the cache will be used
- if not, the git dep is cloned to a temp folder, where the {pre,,post}install and prepare scripts runs
-- npm then packs it and puts the tarball in the cache
-- npm then unpacks it from the cache in the "expected" node_modules location
-- npm runs the {pre,,post}install scripts

That would simulate a full publishing chain (except for the {pre,,post}publish scripts ofc).

**Comment by huochunpeng** [comment]
@zkochan is there a timeline on improving compatibility on lifecycle scripts calls?

@andreineculau there is another aspect you could add to your valuable matrix. When npm installs from git repo, it runs all scripts with `NODE_ENV=production`, but yarn doesn't force `NODE_ENV`. I don't know whether npm use `production` env on all cases, I didn't test enough.

**Comment by zkochan** [comment]
It shouldn't be too hard to do for a first-time contributor. I will probably take it not earlier than 5th of May

**Comment by andreineculau** [comment]
I need to test this myself but setting NODE_ENV to prod is counter intuitive since you need dev deps to run 'npm prepare'

**Comment by huochunpeng** [comment]
Both npm and yarn brings all deps and devdeps for git repo install in order to run those scripts.

**Comment by huochunpeng** [comment]
@zkochan I considered for few minutes by peeking through source code. But I don’t use typescript, so I hesitated.

I like typescript but never had strong enough motivation to invest my time on it. I can see pnpm attracted lots of users but not many non-trivial contributors. Nothing against typescript, but it could be barrier of many potential contributors.

I want to contribute when I had more spare time in future. Some yarn issues start to annoy me, I want to contribute to pnpm because technically pnpm makes more sense to me.

**Comment by zkochan** [comment]
@huochunpeng thanks. Our usage of TypeScript is not very complex. We use really simple code. Just functions, no classes. No nesting. So you should be fine if you know just how to declare a type or interface in TypeScript. On the other hand, it gives you autocompletion and other nice things (especially if you use VS Code).

This particular issue seems a bit more complex now. I didn't know that dev dependencies should be installed for git-hosted dependencies. If so, then we'll also need to save those dev deps to `shrinkwrap.yaml`

**Comment by huochunpeng** [comment]
@andreineculau I think npm think all build scripts should be executed to make a production build not development (default env) build.

I was caught by it, wondering why npm failed to install my private bitbucket repo. I use babelrc environment config for development and test env, but not production env. So npm failed but yarn did not.

**Comment by andreineculau** [comment]
I suggest you create a minimal github repo with a package.json that surfaces the problems you describe with your private repo, including specific npm/pnpm/yarn versions.

**Comment by zkochan** [comment]
Recently the `shrinkwrap.yaml` format has been updated. Now package that should be built have a `requiresBuild: true` property. For instance,

https://github.com/pnpm/pnpm/blob/fa98b4eae401cc0fca43c7e2e524b3d9bc4fcdc6/shrinkwrap.yaml#L907-L917

but now we also have to know if the package's prepare script has to be executed. Currently, there is no way to tell whether a package is a git-hosted package (from info in the shrinkwrap.yaml).

I suggest adding a new boolean called prepare. So for a git dep the shrinkwrap.yaml entry would look like this:

```yaml
  github.com/pnpm/supi/6f64f8d2248e84a6c642eeb9b5546006e040898e:
    dependencies:
      '@pnpm/check-package': 1.0.0
      '@pnpm/fs-locker': 1.0.1
      '@pnpm/headless': 0.2.6
      '@pnpm/lifecycle': 2.1.0
    engines:
      node: '>=4'
    name: supi
    peerDependencies:
      '@pnpm/logger': ^1.0.0
    prepare: true
    requiresBuild: true
    resolution:
      tarball: 'https://codeload.github.com/pnpm/supi/tar.gz/6f64f8d2248e84a6c642eeb9b5546006e040898e'
    version: 0.16.8
```

**Comment by huochunpeng** [comment]
> Currently, there is no way to tell whether a package is a git-hosted package (from info in the shrinkwrap.yaml).

@zkochan the version are in url format, not semver for any git-hosted package, isn't it?

```
devDependencies:
  aurelia-cli: github.com/huochunpeng/cli/10edaef0ca222ab61efcaf141b28c8f8df268967
```

**Comment by zkochan** [comment]
Not always. registry-hosted packages also have the whole URL if they are
from the non-default registry.

**Comment by vjpr** [comment]
> I suggest adding a new boolean called prepare. So for a git dep the shrinkwrap.yaml entry would look like this:

Why not add an entry explicitly stating its from git?

Also, it might be useful to be able to know this in the `pnpmfile#addPackage` hook. If you know its a git dep, you can tweak the install scripts if necessary. This is probably already possible right?

**Comment by vjpr** [comment]
> not possible currently, here's an issue to allow it: pnpm/supi#55

Excellent, I had this same need.

**Comment by zkochan** [comment]
@huochunpeng running "prepare" in git-hosted deps landed in `pnpm@1.43.0`

**Comment by huochunpeng** [comment]
@zhochan sorry for late feedback. Could you check how prepare script was executed?

The local command `babel` (installed by `debug-npm`'s devDependencies `babel-cli`) could not be found.

```
⋊> ~/p/tp pnpm i git+ssh://git@bitbucket.org/huochunpeng/debug-npm.git#v1.0.0
Packages: +1
+
Resolving: total 1, reused 0, downloaded 1, done

bitbucket.org/huochunpeng/debug-npm/361ff261e60f60a91da09bb259230303ccef8087 |     prepare$ echo NODE_ENV=$NODE_ENV; babel src -d dist
bitbucket.org/huochunpeng/debug-npm/361ff261e60f60a91da09bb259230303ccef8087 |     prepare: NODE_ENV=
bitbucket.org/huochunpeng/debug-npm/361ff261e60f60a91da09bb259230303ccef8087 |     prepare: sh: babel: command not found
 ERROR  debug-npm@1.0.0 prepare: `echo NODE_ENV=$NODE_ENV; babel src -d dist`
spawn ENOENT
at Error: debug-npm                                                                                
at <anonymous>       …e_modules/npm-lifecycle/lib/spawn.js:48  const er = new Error('spawn ENOENT')
at emitTwo           events.js:126                                                                 
at emit              events.js:214                                                                 
at maybeClose        internal/child_process.js:925                                                 
at onexit            internal/child_process.js:209
```

**Comment by zkochan** [comment]
That is correct. devDependencies are not installed. This is how prepare of subdeps work with Yarn as well. Just install the dependencies that are needed for building the package as dev dependencies of the main app

**Comment by huochunpeng** [comment]
https://github.com/pnpm/pnpm/issues/855#issuecomment-383200924
https://github.com/pnpm/pnpm/issues/855#issuecomment-383220822
I am pretty sure devDeps are needed to run prepare script, which you aknowledged before 😄 . That's how people build their package.json scripts section, babel should be in devDeps, not deps.

**Comment by zkochan** [comment]
Seems like yarn uses a temp folder or the cache folder, where it installs the package with its dev deps, builds it and then puts to the target node_modules. I am personally lazy to implement such complicated logic. Maybe for these packages we could just convert the prod deps to dev deps? As a temporary solution, you can do it with a `pnpmfile.js` (a [readPackage hook](https://pnpm.js.org/docs/en/hooks.html))

**Comment by huochunpeng** [comment]
Yarn must be using temp folder. Because when it failed, it doesn’t go into yarn cache, which is correct behavior.

While pnpm still cached (or sould I say store) the failed install, a repeated install command uses the malfunctioned cache, without further complaints.

**Comment by huochunpeng** [comment]
@zkochan
I was thinking about this, it might not be too bad. What we want is not to run certain npm script, but to do a full `npm pack` which is dry-run of npm publish.

Instead of fetching git/tarball directly into pnpm store cache, we need

1. fetch it to a temp folder.
2. `pnpm i`, or maybe `npm i` for maxium compatibility.
3. run `npm pack` which reports the generated tar.gz file name.
4. now we can expand the tar.gz file into pnpm store cache.
5. purge temp folder.

I suspect this is what npm is doing, because I can see the final installed npm module correctly respected `.npmignore` or package.json `"files"` sections.

**Comment by huochunpeng** [comment]
Any future plan/roadmap to support this properly? This is the missing feature that prevents me from fully migrating from npm to pnpm.

**Comment by zkochan** [comment]
I don't have this in my near future roadmap.

We can offer a $100 bounty from our opencollective to anyone who implements this (you should have a PayPal account).

Please discuss the solution before implementing it.

**Comment by huochunpeng** [comment]
@zkochan what about the steps I proposed in 3 comments above? I am not sure what's the right choice for step2.

**Comment by zkochan** [comment]
Seems OK. I edited step 2

**Comment by andykais** [comment]
Hi, I just want to make sure I have all the facts right. This doc shows 
 all the scripts that pnpm calls right? https://docs.google.com/spreadsheets/d/1XH8iDyOmNf-ZH3A2SMV5YTDcT2YPXmhFcaUPsIyYEu8/edit#gid=0

I have noticed that the package `pre-push` does not seem to call their ["install"](https://github.com/dflourusso/pre-push/blob/master/package.json#L10) script (though npm does). Am I misinterpreting the doc? If not though, I can make a separate issue describing the problem if that is better.

```
 pnpm --version
3.8.1
```

**Comment by trusktr** [comment]
> Documentation of npm says that prepack should be executed when installing git dependencies. Not a word about prepare, postpack and second execution of install

The latest doc does mention that both `prepare` and `prepack` are ran for git dependencies. https://docs.npmjs.com/misc/scripts

**Comment by trusktr** [comment]
Another important note:

With NPM, in a package being installed from git `prepack` scripts do not have access to dev dependencies while `prepare` scripts do.

This means we can not rely on `prepack`  as a way to have git dependencies build themselves during install.

**Comment by OmgImAlexis** [comment]
Are there any work arounds for this?

**Comment by trusktr** [comment]
@OmgImAlexis I think the only workaround at the moment, if you need this, is using `npm`.

**Comment by kiurchv** [comment]
Currently documentation of npm says that devDependencies should be installed in case when package which installed through git contains a `prepare` script:

> NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.
https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts

It will be great if pnpm will have the same behaviour

**Comment by zkochan** [comment]
PR: #3394

**Comment by zkochan** [comment]
:ship: 6.2.2
