### ISSUE TITLE
Error: spawn E2BIG on large package.json files

### ISSUE THREAD

**Issue by d13** [pnpm/pnpm#8552]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/gitkraken/vscode-gitlens/tree/e5cd2a2c4630d05ee41c0d6018c880d3f0142b80

💡  You'll notice the package.json is 18086 lines (VS Code extension life)

### Reproduction steps

From a Mac terminal or the terminal in VS Code:

- run `pnpm install`
- run `pnpm run build` or `pnpm run lint`

### Describe the Bug

Running `pnpm run build` produces the following error:

```bash
> gitlens@15.5.0 build /Users/keithdaulton/code/gitkraken/vscode-gitlens.worktrees/debt/pnpm
> webpack --mode development

node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:762:9)
    at spawn (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:83937:19)
    at runCmd_ (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:103213:20)
    at runCmd (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:103153:9)
    at runPackageLifecycle (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:103120:7)
    at Array.<anonymous> (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:102337:13)
    at LOOP (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:102364:18)
    at chain (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:102371:9)
    at lifecycle_ (/Users/keithdaulton/.cache/node/corepack/v1/pnpm/9.10.0/dist/pnpm.cjs:103094:7) {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}

Node.js v20.17.0
```

### Expected Behavior

The package scripts should run normally like when I use `yarn` as I have in the past or when I use `npm` now as a workaround.

When I prefix the commands with `NODE_DEBUG=child_process`, I notice that `envPairs` when using `pnpm` has over 10,000 entries. Whereas with `npm` there's only 50ish entries in `envPairs`.

### Which Node.js version are you using?

v20.17.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by eamodio** [comment]
If anyone can point me to where this fix/change should be made I can open a PR for it.

**Comment by tylor-metrics** [comment]
Ran into this issue myself today, was not able to get around it. Trying to get https://github.com/gitkraken/vscode-gitlens up and running locally. All the `pnpm` related commands in that repo seem to fail for this same reason `{errno: -7, code: 'E2BIG'}`.

node: v20.18.0
npm: 10.8.2
pnpm: 8.15.9
git: 2.46.2

I tried updating pnpm to latest 9.14.2, same error. 
I tried using `corepack` to do the installation. And it seems it might have changed some things?
When I do `where pnpm`I get the following, which might be my problem.
> where pnpm                             
/Users/tylor/.nvm/versions/node/v20.18.0/bin/pnpm
/Users/tylor/.nvm/versions/node/v20.11.1/bin/pnpm
/Users/tylor/.nvm/versions/node/v20.11.1/bin/pnpm
/Users/tylor/.nvm/versions/node/v20.18.0/bin/pnpm
/Users/tylor/.nvm/versions/node/v20.18.0/bin/pnpm`

Still poking around, will report back If I get a solution to my problem in case it helps.

**Comment by tylor-metrics** [comment]
Ha, ok ya, so reading through the PR on https://github.com/pnpm/pnpm/pull/8580, if I simply delete the `contributes` property from `package.json` which is like.. 19K lines of code, and re-run `npm run rebuild` it passes. I think its a good temp workaround as I only need the `contributes` for generating a package.

**Comment by d13** [comment]
Woohoo, thanks for jumping in on that!
