### ISSUE TITLE
Can't update pnpm, is flagged as malware

### ISSUE THREAD

**Issue by w3bdesign** [pnpm/pnpm#8559]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.9.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI (pnpm self-update)

### Reproduction steps

I tried `pnpm self-update` and Windows Defender blocked the update with the following message:

![image](https://github.com/user-attachments/assets/196af116-3105-4cae-856b-8024eb21190c)

### Describe the Bug

`pnpm self-update` triggers this issue

### Expected Behavior

I expected pnpm to be able to upgrade

### Which Node.js version are you using?

20.17.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by w3bdesign** [comment]
The log mentions the following file:

`\AppData\Local\pnpm\store\v3\files\e2\97887690bcf8ea44160ac722e8464fd412babda75930347ccf11497576e9ef7e97603ccb9f20a49c9be2d5cad808edc7de7c8b83ecf86358fc192ad9c48246x18584`

**Comment by zkochan** [comment]
I can reproduce that issue but I am not sure what change in v9.11 or v9.10 has caused it. `pnpm audit` doesn't show vulnerable prod dependencies.

**Comment by et84121** [comment]
I am encountering the same issue as others mentioned.

- When installing via Chocolatey (choco), I get an error saying the file hash is incorrect.
- When trying to install via Winget, the installation gets blocked halfway by Windows Defender.
- When installing directly through the command line, Windows Defender also flags the file as malicious.

It seems like the installer is being incorrectly flagged as unsafe by Defender. Any help or updates on this would be appreciated.


## With Standalone Script
```
PS C:\Users\DailyBuild> Invoke-WebRequest https://get.pnpm.io/install.ps1 -UseBasicParsing | Invoke-Expression
Downloading pnpm from GitHub...

Running setup...

Start-Process:
Line |
 139 |  Start-Process -FilePath $tempFile -ArgumentList "setup" -NoNewWindow  …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: 因為檔案包含病毒或潛在的垃圾軟體，所以作業未順利完成。
```

## With Winget
```
PS C:\Users\DailyBuild> winget install pnpm.pnpm
找到 pnpm [pnpm.pnpm] 版本 9.11.0
此應用程式已由其擁有者授權給您。
Microsoft 不負任何責任，也不會授與協力廠商封裝的任何授權。
正在下載 https://github.com/pnpm/pnpm/releases/download/v9.11.0/pnpm-win-x64.exe
  ██████████████████████████████  52.7 MB / 52.7 MB
已成功驗證安裝程式雜湊
正在啟動套件安裝...
執行命令時，發生意外的錯誤：
0x8a150040 : 從資料流讀取時發生錯誤
可攜式安裝失敗；正在清除...
```

## With Choco
```
PS C:\Users\DailyBuild> choco upgrade pnpm
Chocolatey v0.11.3
Upgrading the following packages:
pnpm
By upgrading, you accept licenses for the packages.

You have pnpm v9.10.0 installed. Version 9.11.0 is available based on your source(s).
Progress: Downloading pnpm 9.11.0... 100%

pnpm v9.11.0 [Approved]
pnpm package files upgrade completed. Performing other installation steps.
The package pnpm wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '5DBE3A38BB6E3F7291B7479BC6DBDDC68C59CE26'.
Downloading pnpm
  from 'https://github.com/pnpm/pnpm/releases/download/v9.11.0/pnpm-win-x64.exe'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\pnpm\tools\pnpm.exe (52.78 MB).
Download of pnpm.exe (52.78 MB) completed.

????????: System.IO.IOException: ????????????????,??????????

   ? System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ? System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   ? System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   ? checksum.Program.Main(String[] args)
ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\pnpm\tools\pnpm.exe' did not meet '4cb2bf9570217ff15000ab2653cdf7214da77bec' for checksum type 'sha1'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
Error computing hash for 'C:\ProgramData\chocolatey\lib\pnpm\tools\pnpm.exe'
 Hash will be special code for locked file or file too big instead.
 Captured error:
  ????????????????,??????????

The upgrade of pnpm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\pnpm\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - pnpm (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\pnpm\tools\ChocolateyInstall.ps1'.
 See log for details.
```

**Comment by zkochan** [comment]
As a workaround, you can install the non-exe version of pnpm via corepack or npm:

```
npm i -gf pnpm
```

**Comment by CalvinWilkinson** [comment]
This is very strange, but now, this morning, it is installing just fine with no issues.  This is the result of using the PowerShell installation command from the website.

```bash
❯ Invoke-WebRequest https://get.pnpm.io/install.ps1 -UseBasicParsing | Invoke-Expression
Downloading pnpm from GitHub...                                                          
Running setup...

Copying pnpm CLI from C:\Users\kinso\AppData\Local\Temp\efcb7d20-f270-4cde-a234-047e0cc242c5\pnpm.exe to C:\Users\kinso\AppData\Local\pnpm\pnpm.exe
No changes to the environment were made. Everything is already up to date.
```

I reported the issue on another GitHub issue that was created yesterday.
- #8562

**Comment by zkochan** [comment]
I think the issue is gone. We didn't do anything on our end.

**Comment by CalvinWilkinson** [comment]
> I think the issue is gone. We didn't do anything on our end.

The issue disappeared for me as well.  Very strange.

**Comment by kms0219kms** [comment]
@zkochan, I think you should contact Microsoft because this issue happenes when every single version releases.
This is common error. that causes from Microsoft Defender - it malfunctions when the exe is non-signed.

The workaround is:
- Use non-exe version
- Sign the exe file (Which may need some money)
- Contact Microsoft with the sample (means pnpm.exe) so they can whitelist pnpm.exe
- Ask user to disable Microsoft Defender

And I recommend:
- Contact Microsoft with the sample when releasing every single version. In the meantime, change the doc to download non-exe version mainly
- Add the text on the doc that if any kind of antivirus malfunctions and removes/quarantines the user needs to be add pnpm.exe into the whitelist manually or just turn it off.
