### ISSUE TITLE
`supportedArchitectures` is not filtering optional dependencies

### ISSUE THREAD

**Issue by privatenumber** [pnpm/pnpm#8563]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.11

### Which area(s) of pnpm are affected? (leave empty if unsure)

Store

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/privatenumber/pnpm-supportedArchitectures

### Reproduction steps

1. Observe that `package.json` has `pnpm.supportedArchitectures` specified with `darwin` & `arm64`
2. Install `esbuild`
3. Observe that the Windows distribution gets installed: `ls node_modules/.pnpm | grep '@esbuild+win'`

CI logs (click "List dependencies" to see what got installed):
- Mac: https://github.com/privatenumber/pnpm-supportedArchitectures/actions/runs/10996420768/job/30529523609
- Ubuntu: https://github.com/privatenumber/pnpm-supportedArchitectures/actions/runs/10996420768/job/30529524177
- Windows: https://github.com/privatenumber/pnpm-supportedArchitectures/actions/runs/10996420768/job/30529524766

### Describe the Bug

In `package.json#pnpm.supportedArchitectures`, `darwin` & `arm64` are specified. However, when installing `esbuild`, the Windows distribution is also installed to the store.

### Expected Behavior

For only the `darwin` + `arm64` distribution to be installed.

### Which Node.js version are you using?

v20.16.0

### Which operating systems have you used?

- [X] macOS
- [x] Windows
- [x] Linux

**Comment by KSXGitHub** [comment]
If you remove both `node_modules` and `pnpm-lock.yaml` and run `pnpm install` again, the dependencies that don't satisfy `supportedArchitectures` won't be installed.

@zkochan Do you think the lockfile should track `supportedArchitectures`?

**Comment by privatenumber** [comment]
Ah you're right, thanks for catching. I think that's worth discussing too.

However, I was still able to reproduce this when esbuild is a nested dependency:
https://github.com/privatenumber/pnpm-supportedArchitectures/commit/2e903fd9ae6cce957a05e9fb711d9cc335d35053

Maybe related:
https://github.com/pnpm/pnpm/pull/3672#issuecomment-901431299

**Comment by zkochan** [comment]
> @zkochan Do you think the lockfile should track supportedArchitectures?

no, because the values of this setting doesn't make any changes to the lockfile. Settings that change node_modules but not the lockfiles are saved into `node_modules/.modules.yaml`.

**Comment by KSXGitHub** [comment]
@privatenumber The lockfile from your repo doesn't contain architecture information such as `cpu` and `os`. It seems that your registry doesn't return enough information.

**Comment by KSXGitHub** [comment]
> it would be nice if pnpm could warn that the registry was missing this information.

We can't. Because if the registry doesn't set architecture information, it means that it works for any architecture.

**Comment by privatenumber** [comment]
Got it, thanks for the support!

I'll close this for now since it doesn’t seem actionable on pnpm's side. The Artifactory upgrade might take some time, but once it's done, I'll follow up with an update if it resolves the issue.
