### ISSUE TITLE
Ember CLI application build issues using pnpm and resolve module & modules from dependencies section are missing.

### ISSUE THREAD

**Issue by nikdojo** [pnpm/pnpm#857]
pnpm version: 1.8.1

Code to reproduce the issue: 
-----------------------------
Please download a basic Ember CLI app here:
https://drive.google.com/file/d/0B6psKNv4yBIcU3VXTWpld2dqQmM/view?usp=sharing
Then: `pnpm i && bower i && ./node_modules/.bin/ember serve`

Expected behaviour:
-----------------------------
Build goes well, all deps found.

Actual behaviour:
-----------------------------
Error: `Cannot find module 'route-recognizer' from '/my-app/node_modules/.registry.npmjs.org/ember-cli-pretender/1.0.1/node_modules/pretender'`

Additional information:
npm version: 3.10.8
node version: v6.9.1
OS X

=========================================

The error appears because of module `resolve` that doesn't resolve pnpm's flat structure.
I managed to change `resolve` module to search for deps in a flat structure, but there is another issue appeared. E.g. `broccoli-persistent-filter` has dep `"async-disk-cache": "^1.2.1"`, but there is only `async-disk-cache/1.3.2/` exists (and no symlink for `1.2.1`).

All looks like a lot of modules from `dependencies` sections of nested modules ain't linked.

**Comment by zkochan** [comment]
I don't know, seems like `resolve` does resolve `route-recognizer` fine. I tried this way: 

```
zkochan@zkochan:~/src/pnpm-test/node_modules/.registry.npmjs.org/ember-cli-pretender/1.0.1/node_modules/pretender$ node -e "console.log(require('resolve').sync('route-recognizer'))"
/home/zkochan/src/pnpm-test/node_modules/.registry.npmjs.org/pretender/1.5.1/node_modules/route-recognizer/dist/route-recognizer.js
```

how did you modify `resolve`?

**Comment by zkochan** [comment]
I was wrong, neither `resolve` nor `resolve-from` resolve the package correctly. Maybe I'll work on pull requests to those packages.

So this does not resolve `route-recognizer` because pretender is not resolved to real path first

```
node -e "require('resolve').sync('route-recognizer', {basedir: '/home/zkochan/src/pnpm-test/node_modules/.registry.npmjs.org/ember-cli-pretender/1.0.1/node_modules/pretender'})"
```

**Comment by zkochan** [comment]
I created to PRs that should fix the issues with ember:

https://github.com/stefanpenner/hash-for-dep/pull/37
https://github.com/rwjblue/ember-cli-pretender/pull/60

**Comment by zkochan** [comment]
Unfortunately, it is very hard to get the PRs merged/published. Some maintainers are unresponsive...

So I added installation hooks to pnpm. They are available from version 1.12. Here's an article about this new feature: [Why package managers need hook systems](https://medium.com/pnpm/why-package-managers-need-hook-systems-b8125d8b3dc7)

To fix issues with `resolve` for ember, this `pnpmfile.js` can be created in the root of the project:

```js
'use strict'
module.exports = {
  hooks: {
    readPackage
  }
}

function readPackage (pkg) {
  if (!pkg.dependencies) return pkg

  if (pkg.dependencies.resolve) {
    pkg.dependencies.resolve = 'zkochan/node-resolve'
  }
  if (pkg.dependencies['resolve-from']) {
    pkg.dependencies['resolve-from'] = 'zkochan/resolve-from'
  }
  return pkg
}
```

This solves most issues but I see now some new errors with babel. We'll have to look into that. Seems like it has some custom resolver as well... :cry:

**Comment by zkochan** [comment]
What is this `ember-cli-pretender`? I just tried the latest ember, it doesn't contain `ember-cli-pretender` and seem to work with pnpm

**Comment by zkochan** [comment]
Until the issues are fixed, you can create a `.npmrc` file in the root of your project with this content:

```
shamefully-flatten = true
```

Or run installation with the [--shamefully-flatten](https://pnpm.js.org/docs/en/pnpm-install.html#shamefully-flatten) flag: `pnpm install --shamefully-flatten`
