### ISSUE TITLE
feat(overrides): remove dependencies

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#8572]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

I saw that when people seek support regarding the pnpmfile, their use case is often about removing optional dependencies. I think that if this use case is that common, it should be replaced by `overrides` instead.

### Describe the solution you'd like

Add a special syntax to remove dependencies:

```json
{
  "pnpm": {
    "overrides": {
      "foo>bar@2": "-"
    }
  }
}
```

The above would remove `bar` from `foo` only if `bar` is v2.

### Describe the drawbacks of your solution

_(blank)_

### Describe alternatives you've considered

Keep using pnpmfile.

**Comment by KSXGitHub** [comment]
@zkochan

**Comment by KSXGitHub** [comment]
> why should there be a distinction between optional and non-optional? I think a simple `-` should be sufficient.

Can `overrides` be apply recursively on both direct and transitive dependencies? I think the user would like to have the ability to remove only if optional. Unless you meant `-` should remove only optional.

**Comment by zkochan** [comment]
They could limit by dependent package. For instance:

```json
{
  "pnpm": {
    "overrides": {
      "foo>bar": "-"
    }
  }
}
```

This will only remove bar from dependencies of foo. Also, if a specific version should be removed, that is supported too:

```json
{
  "pnpm": {
    "overrides": {
      "foo>bar@2": "-"
    }
  }
}
```

**Comment by KSXGitHub** [comment]
OK. Let's go with your solution.
