### ISSUE TITLE
cannot install eslint-plugin-import with pnpm

### ISSUE THREAD

**Issue by andreineculau** [pnpm/pnpm#858]
### Code to reproduce the issue:

```shell
git clone git://github.com/andreineculau/pnpm-with-eslint-plugin-import
cd pnpm-with-eslint-plugin-import
./test
```

### Expected behavior:

`eslint-plugin-import` depends on `eslint-import-resolver-node`, so nodejs should be able to find it after install

### Actual behavior:

after `pnpm install` the module cannot be found

### Additional information:

 - `node -v` prints: v8.2.1
 - Windows, OS X, or Linux?: OSX

**Comment by andreineculau** [comment]
looking in the file system, looks like no node_modules are installed

```
$ l node_modules/eslint-plugin-import/                                                                                                                                                                                  3:21~ 19:20:04 Tue 25
total 56K
-rw-r--r-- 2 andrei staff  32K 2017-07-06 13:02 CHANGELOG.md
-rw-r--r-- 2 andrei staff 1.1K 2017-05-18 18:08 LICENSE
-rw-r--r-- 2 andrei staff  15K 2017-05-24 13:21 README.md
drwxr-xr-x 9 andrei staff  306 2017-07-25 19:17 config/
drwxr-xr-x 7 andrei staff  238 2017-07-25 19:17 lib/
drwxr-xr-x 5 andrei staff  170 2017-07-25 19:17 memo-parser/
-rw-r--r-- 2 andrei staff 3.1K 2017-07-06 13:03 package.json
```

**Comment by andreineculau** [comment]
i wrote better=proper test, and now the test passes, so i need to figure out better how to replicate my problem - which is that running eslint fails on `eslint-plugin-import` because it cannot resolve the module `eslint-import-resolver-node`...

I leave this open for a day

**Comment by zkochan** [comment]
We have an issue about this: https://github.com/pnpm/pnpm/issues/739

Also at [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/issues/828)
