### ISSUE TITLE
feat: add `project-hoist-pattern` to hoist project's deps

### ISSUE THREAD

**Issue by trydofor** [pnpm/pnpm#8588]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

In short, if you deps on `project`, then auto 
add `project`'s deps (`dependencies`, `devDependencies`) to you, avoid copying them.

i have implemented this feature using `.pnpmfile.cjs` and published to [npmjs](https://www.npmjs.com/package/pnpm-hoist-layer), and i think my impl is not perfect, so this issue is here.

this is different from `public-hoist-pattern`, this feature explicitly declares dependencies of both `project` and `project`'s deps, just reduce to copy `project`'s deps. but `public-hoist-pattern` installs deps by rules, even if i dont need them.

have a look at the [monorepo](https://github.com/trydofor/pnpm-hoist-layer/tree/main/test/mono1) structure, the diff before and after.

```diff
## pnpm -r list
Legend: production dependency, optional only, dev only
mono-test-0@1.0.0 pnpm-hoist-layer/test/mono/packages/pkg0
+ dependencies:
+   solo-prd-dep link:../../solo/prd
= devDependencies:
=   mono-test-1 link:../pkg1
+   mono-test-2 link:../pkg2
+   solo-dev-dep link:../../solo/dev
mono-test-1@1.0.0 pnpm-hoist-layer/test/mono/packages/pkg1
+ dependencies:
+   solo-prd-dep link:../../solo/prd
= devDependencies:
=   mono-test-2 link:../pkg2
+   solo-dev-dep link:../../solo/dev
mono-test-2@1.0.0 pnpm-hoist-layer/test/mono/packages/pkg2
= dependencies:
=   solo-prd-dep link:../../solo/prd
= devDependencies:
=   solo-dev-dep link:../../solo/dev

## tree -L 4
✅ mono
= ├── node_modules
= ├── package.json
= ├── packages
= │   ├── pkg0
= │   │   ├── node_modules
= │   │   │   ├── mono-test-1 -> ../../../node_modules/.pnpm/
+ │   │   │   └── mono-test-2 -> ../../pkg2
+ │   │   │   ├── solo-dev-dep -> ../../../solo/dev
+ │   │   │   ├── solo-prd-dep -> ../../../solo/prd
= │   │   └── package.json
= │   ├── pkg1
= │   │   ├── node_modules
= │   │   │   └── mono-test-2 -> ../../pkg2
+ │   │   │   ├── solo-dev-dep -> ../../../solo/dev
+ │   │   │   ├── solo-prd-dep -> ../../../solo/prd
= │   │   └── package.json
= │   └── pkg2
= │       ├── node_modules
= │       │   └── solo-dev-dep -> ../../../solo/dev
= │       │   ├── solo-prd-dep -> ../../../solo/prd
= │       └── package.json
= ├── pnpm-lock.yaml
= └── pnpm-workspace.yaml
```

There are already 1.6k issues to deal with here, so I'm really embarrassed to issue the request, but I think this feature would help a lot in reducing copying and clarifying dependencies.

### Describe the solution you'd like

https://github.com/trydofor/pnpm-hoist-layer impls this via `.pnpmfile.cjs` in 3 steps,

* child-process `pnpm -r i --resolution-only` to get 2-level direct deps.
* write the flattened the `project` and its deps to the cache file for CI
* merge `dependencies` and `devDependencies` into `pkg` via `readPackage(pkg)`

and in pnpm impls, this may be easier than the hook,

* use `project-hoist-pattern` in `.npmrc` or `package.json` to define the `project`
* cache the `project` and its `deps`
* merge the `deps` to the `pkg` that deps on `project`.

### Describe the drawbacks of your solution

there are 4 drawbacks  to using `.pnpmfile.cjs`,

(1) split one step `pnpm i` into more

```bash
## ✅ for CI
pnpm -w i --no-frozen-lockfile --ignore-pnpmfile
git restore pnpm-lock.yaml
pnpm -r i --frozen-lockfile

## 💚 for Dev
pnpm -w i --ignore-pnpmfile
pnpm -r i
```

(2) extra cache file for CI

use `hoist-layer.json` to cache the `project` and its `deps`.

(3) extra `hoistLayer` key to package.json

not good in practice.

(4) `link:` protocol not hook

use `file:` instead

**Comment by zkochan** [comment]
The private/public hoist pattern settings are not meant to be used as "features", they are workarounds for broken packages in the ecosystem that use undeclared dependencies.

So what you suggest is what we consider bad practice.

If you want share many dev deps between projects you can either move those deps to the root `package.json` of the monorepo (only if those are dev deps) or you could use [catalogs](https://pnpm.io/catalogs).

If you want to go really high level, there are also tools like [bit CLI](https://bit.dev) that allow declaring all dependencies in the root workspace.jsonc (kind of like catalogs) and also automatically add those dependencies to only those package.json files where they are used.

**Comment by trydofor** [comment]
> So what you suggest is what we consider bad practice.

thanks, then i will give `bit` a try and close this issue
