### ISSUE TITLE
.npmrc compat

### ISSUE THREAD

**Issue by andreineculau** [pnpm/pnpm#859]
### Code to reproduce the issue:

```shell
echo "save-exact=true" > .npmrc
mkdir foo
cd foo
npm init # ...
echo "save=true > .npmrc"
pnpm install --no-save json@9.0.6
cat package.json
```

### Expected behavior:

1. `json` is not saved in `package.json` due to the `--no-save` flag
2. and even if saved, the `save-exact` from the parent folder should be respected

### Actual behavior:

pnpm ends up adding `json@^9.0.6` in package.json

**Comment by zkochan** [comment]
npm reads `.npmrc` from the project's directory only,

pnpm uses npm for getting the configs

**Comment by zkochan** [comment]
Unlikely will we support `--no-save` flag. Yarn does not support it and my guess is that npm will probably not support it in the future https://twitter.com/maybekatz/status/889543274892894208

**Comment by andreineculau** [comment]
> npm reads .npmrc from the project's directory only,

just want to double-check - by design? like you do things differently than npm on purpose?

then what if i want to use another registry on a machine? usually i would have marked that in `~/.npmrc`

or similarly i've always had `optional=false` and `save-exact=true` on my dev machine...

**Comment by zkochan** [comment]
You misunderstood me. 

See configuration section of our readme: https://github.com/pnpm/pnpm#configuring

> pnpm uses npm's programmatic API to read configs. Hence, you should set configs for pnpm the same way you would for npm.
>
>Furthermore, pnpm uses the same configs that npm uses for doing installations. If you have a private registry and npm is configured to work with it, pnpm should be able to authorize requests as well, with no additional configuration.

What I said was, npm does not read config files up from the parent directories. If it would, pnpm would as well

**Comment by zkochan** [comment]
As you can see [here](https://github.com/pnpm/pnpm/blob/master/src/bin/pnpm.ts#L95), we use pnpm to read all the configs

**Comment by andreineculau** [comment]
indeed I misunderstood you 😞
