### ISSUE TITLE
[Feature Request] pnpm dlx should respect .npmrc `save-prefix=""`

### ISSUE THREAD

**Issue by zigang93** [pnpm/pnpm#8598]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

I am strict how package version should be install in my project.

Each time I run `pn dlx storybook@latest upgrade`
it will break my rules of how package should be installed.

```ts
storybook: "^8.3.1" // ❌ after 
```

```ts
storybook: "8.3.1" // ✅ expect without `^`
```

### Describe the solution you'd like

hope have any flag able to force respect the .npmrc setting 
maybe something like `--respect-npmrc`

**Comment by zkochan** [comment]
It isn't pnpm that updates your package.json in this case. It is storybook's CLI that does it. So, it isn't related to pnpm.
