### ISSUE TITLE
unknown arguments are silenced

### ISSUE THREAD

**Issue by andreineculau** [pnpm/pnpm#860]
### Code to reproduce the issue:

```shell
pnpm install --foo # equivalent to `pnpm install`
```

### Expected behavior:

failure with `unknown argument foo`

### Actual behavior:

silence

**Comment by zkochan** [comment]
FYI, this is how npm behaves as well. Although might be good to have strict validation

**Comment by aricalves** [comment]
I'd like to look into this issue. @zkochan can you elaborate on what you mean by, 'strict validation'?

**Comment by zkochan** [comment]
I mean, if there is an unknown flag, pnpm could fail with an error. Though this would be a breaking change, so for now, we could maybe just print warnings.

Parsing of flags is done by nopt here: https://github.com/pnpm/pnpm/blob/master/src/main.ts#L145

Printing the warning should be done via `@pnpm/logger`. `logger.warn('....')`. You can find examples of warnings in code

@etamponi this is the issue I mentioned today when you mistyped `--side-effects-cache`.

**Comment by Idrinth** [comment]
this seems to be solved at first glance - or is something missing?
```
$ pnpm install --foo
 ERROR  Unknown option 'foo'
For help, run: pnpm help recursive
```

**Comment by zkochan** [comment]
Yes, this was done.
