### ISSUE TITLE
propose a callback system for overrides

### ISSUE THREAD

**Issue by andreineculau** [pnpm/pnpm#861]
there are a few issues open on pnpm related to

1. pnpm "failing" (actually adhering "too much" to the nodejs module resolving pattern) to install "properly" some packages which either miss declaring peerDependencies, or implement their own way to resolve modules, which is not 100% the nodejs way, etc.
2. pnpm lacking the ability to override sub-sub-sub-*-dependencies for cases when package A depends on package B which depends on package C, and package C has a bug, or it is less performant than the newer version but its spec is exact (no ~ or ^), etc.

I myself suffer currently from this https://github.com/blakeembrey/popsicle-retry/issues/13 where popsicle-retry is a dep of popsicle which is a dep of typings-core which is a dep of typings! So no pnpm + typescript = <3 for now. Luckily all those have the same author, and all those deps use ^ in their spec, but it could easily have been hell if the spec was exact, and even more so if you have to contact 4 different authors to make this little change, publish a new version to npm, etc, etc.

So as an alternative to #651 and possibly other issues, I'm putting forward an idea to have a callback system in pnpm, which I will **sketch** (put as much highlight on the this word as you can) below.

---

**Iteration 1**: `package.json` could have a script called `pnpm-post-read-pkg`, the script gets `package.json` via stdi, dependency path as an env variable. The downside is that this (start a process on every single dependency) will be tremendously slow.

---

**Iteration 2**: `package.json` could have a `config` called `pnpmCallbacksModule`, or a `pnpm` object with a `callbacksModule` property (opens up for more pnpm-specific configs), or a separate `pnpm.json` file if it matters, but I digress --- a property pointing to a module.

The interface of that module is that it exports a list of selectors (dependency paths) and a callbacks object e.g.

```js
exports.selectors = [
  "foo bar@^1.2.3 > @scoped/qux@~1.2.3",
  "prefix*",
  "*suffix",
  "...i'm sure imagination can run wild :)..."
];

exports.callbacks = {};
exports.callbacks.postReadPkg = function({pkg, selector, path}) {
  // NOTE: would be the dependency path, not the filesystem path
  // for more fine-grained adjustments
  // e.g. ['foo@1.2.3', 'something@1.2.3', 'bar@1.8.9', '@scoped/qux@1.2.9']

  let patch = {};
  switch (selector) {
  case exports.selectors[0]:
    patch.dependencies = {};
    patch.dependencies['popsicle-retry'] = 'git+ssh://git@example.com:popsicle-retry.git#tag';
    break;
  case exports.selectors[1]:
  case exports.selectors[2]:
    patch.dependencies = {};
    patch.peerDependencies.popsicle = '*';
    patch.scripts = {};
    patch.scripts.postinstall = `${__dirname}/postinstall`;
    patch.config = {};
    patch.config.port = 8080;
   break;
  }
  return patch;
}
```

Since this creates an alternate version of e.g. `@scoped/qux@1.2.5` pnpm could save this as `@scoped/qux@1.2.5-pnpm-patch-<checksum>` and hardlink to that.

:tada:

**Comment by andreineculau** [comment]
a great benefit with code vs configuration is that you have built-in extensibility:

* check if the package.json actually needs fixing or not i.e. maybe meanwhile popsicle-retry got a new version  published, thus we don't need to "lock" it to a fork anymore. Maybe pnpm could even show a WARNING: hey, you told be to call you when i read package.json for this selector, but you returned nothing (i.e. keep the same pkg), maybe you want to clean up your callbacks module
* check what pnpm version we're running, node, etc., etc.
* check say .npmrc
* pnpm maintainers could publish a pnpm-known-rebels package with a callbacks module that can be required=imported or just directly referenced in our own callbacks module
* etc etc etc

(by now I guess you've figured out I'm actually Hedwig from Split https://www.youtube.com/watch?v=okAm1fMu2qY )

**Comment by zkochan** [comment]
@andreypopp could you check this out, please? I think you wanted some of these features (or something similar) in pnpm

**Comment by zkochan** [comment]
First thoughts about this.

1. **Iteration 1** I would skip
1. Callback is too general. I would rather call it "installation hooks" and the file can be called maybe `pnpmfile.js` or some other more general name.
1. >Since this creates an alternate version of e.g. @scoped/qux@1.2.5 pnpm could save this as @scoped/qux@1.2.5-pnpm-patch-<checksum> and hardlink to that.

   this would add too much complexity to the system. All we want to do currently is patching the `package.json`. We can leave the files in the global store as they are and save the patches in separate files. (It is important not to modify any files of the package). Then we will read `package.json` + `package-patch.json` and merge them. Or maybe we will just always run the hood. I don't know yet

1. We don't know yet what it will be but we should start with something really simple but of course with extensibility in mind

**Comment by andreineculau** [comment]
re 1. I mentioned Iteration1 just so it's out there

re 2. `callbacks` is not even needed if you think about it. All the exports in such a file are "callbacks", so it could be simply `exports.postReadPkg`.

re 3. I didn't have enough knowledge of pnpm, I just wanted to raise the point that we want to patch 1 instance, not modify the package for the entire .pnpm-store

re 4. I'd highlight that until the highlighter gives out smoke :)

**Comment by zkochan** [comment]
For reference.

A hook was added to override `package.json`'s of dependencies ([read more](https://github.com/pnpm/pnpm#hooks))

Next thing I plan to add is [aliases](https://github.com/pnpm/pnpm/issues/837).

**Comment by zkochan** [comment]
Aliases added as well in [v1.23.0](https://github.com/pnpm/pnpm/releases/tag/v1.23.0).

readPackage + aliases is now really powerful. If you want new hooks, please create new issues.
