### ISSUE TITLE
pnpm add should do pnpm install

### ISSUE THREAD

**Issue by andreineculau** [pnpm/pnpm#864]
### Code to reproduce the issue:

```shell
pnpm install async
pnpm install async # doesn't do anything because async is already there, good
pnpm add async # runs npm add async -> messes things up
# WARN Moving package-json-scripts that was installed by a different package manager to "node_modules/.ignored
```

### Expected behavior:

`pnpm add` should be equivalent to `pnpm install`

### Actual behavior:

the `add` command gets proxied to `npm`

### Tasks

- [x] make `add` an alias of `install`
- [ ] whitelist commands that should be proxied to npm

**Comment by zkochan** [comment]
I would also

1. throw error on `pnpm add`
2. run `pnpm install` on `pnpm` (that would make it possible to use it like the yarn cli)

**Comment by andreineculau** [comment]
why do you want **also** an error? don't you want either an error, or an alias ?

regarding the second part - no, no, no. then you have silly issues like having exceptions for `pnpm -v` to still output the version number, not barf "unknown argument -v to pnpm install" or similar
"KISS" please

**Comment by andreineculau** [comment]
> https://gitter.im/pnpm/pnpm?at=5979d6e81c8697534a651b80

:+1: for a whitelisting of proxied commands

**Comment by zkochan** [comment]
ok, I agree about argumentless `pnpm`. Better to add a shortcut, like `pi`.

> why do you want also an error? don't you want either an error, or an alias ?

Seems logical to throw an error when someone runs `pnpm add`. Yarn throws an error on `yarn add`.

**Comment by andreineculau** [comment]
@zkochan :clap: once again thank you for your invaluable work
