### ISSUE TITLE
`pnpm add` should use the default catalog

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#8640]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

When running `pnpm add`, pnpm currently adds the latest version with of that dependency with `^`. For example, running `pnpm add is-positive` edits `package.json` with the following contents:

```json
{
  "name": "@example/lib",
  "dependencies": {
    "is-positive": "^3.1.0"
  }
}
```

### Describe the solution you'd like

When a user has set up a [default catalog entry](https://pnpm.io/catalogs#default-catalog) for a dependency, it's likely that new usages of this dependency in a workspace package are intended to use the catalog protocol. Instead of adding a new version, use the catalog protocol:

```json
{
  "name": "@example/lib",
  "dependencies": {
    "is-positive": "catalog:"
  }
}
```

Related: I realized we don't do this for workspace packages at the moment. It likely makes sense to add `workspace:*` out of the box too. (https://github.com/pnpm/pnpm/issues/6770)

### Describe the drawbacks of your solution

Some users may prefer not using the catalog protocol out of the box, but I expect this to be exceedingly rare and somewhat defeats the purpose of catalogs.

There's a few more ambiguous cases with named catalogs though:

- When a user has a dependency to a named catalog, should we use that?
- When a user has a dependency in multiple named catalogs, which one should be added?
- When a user has a default catalog and one more more named catalogs, does it still make sense to use the default catalog?

We can probably start by simply using the default catalog on `pnpm add` and ignoring named catalogs, but perhaps a future version prompts users if there's multiple named catalogs.

**Comment by nickfujita** [comment]
It would be great if we could also have the option to allow for all installs to have their versions managed in the default catalog  (if one exists). Meaning that it would not only use the `catalog:` when an existing version of the same package is in the default catalog, but also if there is no existing entry, rather than adding the version to the `package.json`, it adds the package version to the catalog, and adds the `catalog:` reference to `package.json` in that workspace.

I can understand if this is not the desired default behavior for all, but would be great if we could have some config value in `.npmrc` to enable this or possible with a install flag (eg. `pnpm add <pkg> --catalog`)

**Comment by gluxon** [comment]
I like that idea @nickfujita. We should consider it.

**Comment by jaridmargolin** [comment]
Adding a `--catalog <CATALOG_NAME_OR_DEFAULT>` arg seems like a purely additive, non-breaking change. Would the team be open to merging in a PR that added this?

@gluxon have you started on any of this work?

**Comment by zkochan** [comment]
I also like the suggestion by @nickfujita. I don't know if we have enough time to include it in pnpm v10.

**Comment by gluxon** [comment]
Thanks for the help @martinkors!

**Comment by martinkors** [comment]
> Thanks for the help @martinkors!

No problem!

**Comment by martinkors** [comment]
> I also like the suggestion by @nickfujita. I don't know if we have enough time to include it in pnpm v10.

I have a working branch, that allows `pnpm add` with `--catalog` or it's alias `-c`.

**Comment by jaridmargolin** [comment]
@martinkors - First, thank you for the first PR. Would love to see the `--catalog` flag land as well. Any chance you are still working through this?

**Comment by martinkors** [comment]
> @martinkors - First, thank you for the first PR. Would love to see the `--catalog` flag land as well. Any chance you are still working through this? 

Hello @jaridmargolin, yes I am still working on this branch. I have it partially working, but am awaiting an answer to [this question](https://github.com/pnpm/pnpm/issues/8876#issuecomment-2545941646) regarding the behavior of the command.

**Comment by trydofor** [comment]
Is it possible to support named catalogues as well?

* default - `catalog:`
* named - `catalog:dev`

**Comment by mufeiyu-ayu** [comment]
> It would be great if we could also have the option to allow for all installs to have their versions managed in the default catalog (if one exists). Meaning that it would not only use the `catalog:` when an existing version of the same package is in the default catalog, but also if there is no existing entry, rather than adding the version to the `package.json`, it adds the package version to the catalog, and adds the `catalog:` reference to `package.json` in that workspace.如果我们还可以选择允许所有安装在默认目录中管理其版本（如果存在），那就太好了。这意味着它不仅会使用 `catalog:` 当默认目录中存在同一软件包的现有版本时，而且如果没有现有条目，它不会将版本添加到 `package.json` ，而是将软件包版本添加到目录中，并在该工作区中添加对 `package.json` `catalog:` 引用。
> 
> I can understand if this is not the desired default behavior for all, but would be great if we could have some config value in `.npmrc` to enable this or possible with a install flag (eg. `pnpm add <pkg> --catalog`)我可以理解这不是所有人都希望的默认行为，但如果我们可以在 `.npmrc` 中有一些配置值来启用此功能或者使用安装标志（例如 `pnpm add <pkg> --catalog` ）那就太好了

good idea
