### ISSUE TITLE
HTTP 406 errors when using NPM Enterprise

### ISSUE THREAD

**Issue by josephschmitt** [pnpm/pnpm#867]
We're running into a really weird issue when using `pnpm` with our npm Enterprise instance. Below is a repo with steps to reproduce, as well as all the detail we've been able to amass. Let me know if you need more information

https://github.com/josephschmitt/pnpm-406-npmE

Also a quick note: we were unable to reproduce this on the previous version of `pnpm` we had, which was `0.68.0`. It only started showing up when we installed `1.9.0` and higher.

Thanks.

**Comment by josephschmitt** [comment]
Some more info:

1. Deleting the shrinkwrap file and then trying again seems to get us out of the 406 errors. Confusingly, when we look at the git diff for the shrinkwrap after deleting and re-generating, there is no change.
2. We noticed when we re-created the shrinkwrap from pnpm 0.68.0 with 1.9.0 that the entire URL pointing to the tarball is gone from the shrinkwrap. So the url that is 406'ing is getting generated in code, which could be a place where it's breaking.

I think these two data points are related. Is the code path that leads to point 1 and 2 separate, which could explain why doing point 1 above works yet doesn't generate a new shrinkwrap?

**Comment by zkochan** [comment]
thanks for the detailed investigation!

the way it should work is when the tarball URL has a standard form `<registry>/<package-name>/-...` then it is not saved in the shrinkwrap file.

I'll try to investigate it tonight.

**Comment by josephschmitt** [comment]
@zkochan awesome, thanks! Also just a note that I was actually able to reproduce this with npm 5.x as well, so it might not be necessary to get the old npm 3.x version installed. However, if you're unable to reproduce the issue in that repo with 5.x, try downgrading and it'll definitely fail then.

**Comment by zkochan** [comment]
I did reproduce.

Do you mind if pnpm would use `npm-registry.compass.com` in a test to cover this issue for the future?

**Comment by josephschmitt** [comment]
@zkochan awesome! @onlywei and I are reviewing now, and yea feel free to use that url in your tests. thanks!

**Comment by onlywei** [comment]
We will try to keep `npm-registry.compass.com` up for the foreseeable future, but it's totally possible that NPM may release an update that makes the URLs the same for enterprise vs public. So, I can't guarantee that this registry will exist in this state forever. Feel free to use it for now, though.

**Comment by zkochan** [comment]
Fix published in [v1.10.2](https://github.com/pnpm/pnpm/releases/tag/v1.10.2)

**Comment by onlywei** [comment]
This is working great now!
