### ISSUE TITLE
Does not work on Windows 10?

### ISSUE THREAD

**Issue by scott-cornwell** [pnpm/pnpm#868]
### pnpm version:
1.10.2
### Code to reproduce the issue:
pnpm install
### Expected behavior:
pnpm does not try to symlink on Windows

### Actual behavior:
pnpm symlinks on Windows and quits with: "ERROR EISDIR: illegal operation on a directory, symlink 'Y:\web\packages\private-npm\ui\node_modules\.registry.npmjs.org\buble\0.15.2\node_modules\buble' -> 'Y:\web\packages\private-npm\ui\node_modules\.registry.npmjs.org\react-styleguidist\6.0.8\node_modules\buble'
### Additional information:

 - `node -v` prints: v7.9.0
 - Windows, OS X, or Linux?: Windows 10 inside Parallels on OSX
- running in Windows PowerShell

**Comment by apwelsh** [comment]
Windows does not support junctions on network drives.    symlinks seem problematic from my experience.

**Comment by zkochan** [comment]
@scott-cornwell have you tried to specify a custom store location via the [store](https://github.com/pnpm/pnpm#store) config. If you set a location that is on the same disk/device then pnpm should be able to create the hard links.

Also probably related to this issue: https://github.com/pnpm/pnpm/issues/712

**Comment by zkochan** [comment]
This was fixed in scope of #712
