### ISSUE TITLE
don't stop all other scripts if one exits with non-zero when using pnpm run /regex/

### ISSUE THREAD

**Issue by MrGreenTea** [pnpm/pnpm#8705]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

We have multiple linters in our astro project (`eslint`, `astro-check`, `svelte-check`) and have structure like this:

```json
"scripts": {
  "lint:eslint": "eslint .",
  "lint:svelte": "svelte-check",
  "lint:astro": "astro check"
}
```

We then use `pnpm run /^lint:/` to run all linters in parallel. When one linter finds issues and stops with a non-zero exit code all other still running linters are killed. This means we don't get all lint issues in our CI for example and sometimes fix one found issue to find another one by a different linter when running all lints again.

### Describe the solution you'd like

An option similar to the proposed  #6792 but kind of opposite: wait until all scripts have stopped running and then return with the exit code of the first failed script.

`npm-run-all` calls this option `--continue-on-error`. Another option might be `--wait-for-all` 

### Describe the drawbacks of your solution

One drawback: we lose the specific exit codes of the scripts that failed after the first one.

Also the additional logic of wether to stop the execution might add non-trivial complexity.

### Describe alternatives you've considered

I've considered writing a small script or use `npm-run-all`. The latter hasn't been updated and I would like to avoid the additional dependency, because I really like that we can new `lint:XXX` scripts and they will be run in our CI.

**Comment by btea** [comment]
It looks like the bail option will meet your needs. https://pnpm.io/cli/recursive#--no-bail

**Comment by MrGreenTea** [comment]
It does. I must have missed that in my search of the docs. Thank you!
