### ISSUE TITLE
pnpm grabbing wrong version of package in monorepo

### ISSUE THREAD

**Issue by EliasVal** [pnpm/pnpm#8708]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.12.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

1. Set up pnpm monorepo
2. Specify package in root package.json
3. Specify different version of same package in a workspace
4. Install

### Describe the Bug

So, I currently have the following in my root `package.json`:
```json
{
  "dependencies": {
      "@types/react": "npm:types-react@rc",
  },
  "overrides": {
    "@types/react": "npm:types-react@rc",
  }
}
```

And in a workspace `package.json`:
```json
{
  "devDependencies": {
    "@types/react": "18.2.6"
  },
  "overrides": {
    "@types/react": "18.2.6"
  }
}
```

And files inside that workspace grab the wrong package version (npm:types-react@rc)

### Expected Behavior

For all workspaces with no overrides of `@types/react` to inherit the version from the root `package.json` and for that one workspace with an override to use `@types/react@18.2.6`

### Which Node.js version are you using?

20.16.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu (WSL)

**Comment by zkochan** [comment]
You can only declare overrides in the root `package.json`.

If you need different overrides for the same package, you more specific selectors. For example:

```json
{
  "dependencies": {
      "@types/react": "npm:types-react@rc"
  },
  "overrides": {
    "@types/react": "npm:types-react@rc",
    "direct-parent-pkg-name>@types/react": "18.2.6"
  }
}
```

**Comment by EliasVal** [comment]
I tried setting my root `package.json` to this:
```json
{
  "dependencies": {
      "@types/react": "npm:types-react@rc"
  },
  "overrides": {
    "@types/react": "npm:types-react@rc",
    "mobile-app>@types/react": "18.2.6"
  }
}
```

And the workspace's:
```json
{
  "name": "mobile-app",
  "devDependencies": {
    "@types/react": "18.2.6"
  }
}
```

But a `.tsx` file inside that workspace throws the following error:
```
Types of property 'contextType' are incompatible.
Type 'import("/home/--/---/node_modules/.pnpm/types-react@19.0.0-rc.1/node_modules/types-react/index").Context<any> | undefined' is not assignable to type 'React.Context<any> | undefined'.
```

**Comment by EliasVal** [comment]
Okay, it seems that it wasn't a pnpm issue, my bad.

For those who come after me, the solution was editing the tsconfig inside the workspace like so:
```json
{
  "compilerOptions": {
    "paths": {
      "react": ["./node_modules/@types/react"]
    }
  }
}
```
