### ISSUE TITLE
`pnpm i -S an-npm-linked-module` doesn't add to package.json

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#871]
### Code to reproduce the issue:

pnpm link foo
pnpn i -S foo

### Expected behavior:

foo should be added to package.json

### Actual behavior:

a warning shows up saying that foo is linked

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: macOS

---

Maybe some relevant discussion here: https://github.com/pnpm/pnpm/issues/825

**Comment by zkochan** [comment]
Should `foo` be unlinked first?

**Comment by vjpr** [comment]
Maybe we need a `pnpm link -S foo`?

Then it would make sense that `pnpm i -S foo` should unlink `foo` first.

**Comment by zkochan** [comment]
So if you run `pnpm link foo` then it should add it as a dependency but what spec should be used? The version that is specified in the `foo`'s `package.json`? But that might be anything, even something that is not in the registry yet. We'd have to add some additional validation for `pnpm publish` to check that the specs are correct

**Comment by vjpr** [comment]
`pnpm link foo` should not add to pjson. 

You are right, with `pnpm link -S foo` there is the problem of picking a version, maybe best not to have the `-S` option.

**Comment by zkochan** [comment]
> Then it would make sense that `pnpm i -S foo` should unlink `foo` first.

This was implemented in 546f42657e0c18ccc8c7f12b1d1a992ee6bad5c0.

**Comment by zkochan** [comment]
:ship: [2.15.2](https://github.com/pnpm/pnpm/releases/tag/v2.15.2)
