### ISSUE TITLE
Dx rough edge around resolutions field...

### ISSUE THREAD

**Issue by jdalton** [pnpm/pnpm#8740]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

Currently if you have a workspace package and it has a "resolutions" field pnpm will emit a warning:
> packages/abc |  WARN  The field "resolutions" was found in /.../packages/abc/package.json. This will not take effect. You should configure "resolutions" at the root of the workspace instead.

In workspace packages we are adding the "resolutions" field as its a good catch all for `pnpm`, `yarn`, and `bun`. We also add a `overrides` field for npm. The idea is that when these packages are published they will be consumed by multiple package managers so we support a wider range. The root package.json of the namespace does specify things with the `pnpm.overrides` field.

### Describe the solution you'd like

In this case I'd like the warning to not emit. We have the overrides specified in the root (`pnpm.overrides`) so they are hoisted already.

**Comment by jdalton** [comment]
Opened PR at https://github.com/pnpm/pnpm/pull/8749

**Comment by zkochan** [comment]
I don't get it. These fields are ignored during installation of dependencies. So this won't work at all:

> The idea is that when these packages are published they will be consumed by multiple package managers so we support a wider range.
