### ISSUE TITLE
Duplicate edge specification from "package"

### ISSUE THREAD

**Issue by notaphplover** [pnpm/pnpm#8759]
### Last pnpm version that worked

9.12.3

### pnpm version

9.13.1

### Code to reproduce the issue

Fork this [codesandbox](https://codesandbox.io/p/devbox/sweet-cori-q5v4tv)

2. Run setup tasks.

### Expected behavior

Both fastify dependencies are installed

### Actual behavior

An error is thrown:

```
ERROR  Duplicate edge specification from "fastify"
```

### Node.js version

v22.11.0

### Operating System

Linux

**Comment by zkochan** [comment]
I'll look into it.

**Comment by zkochan** [comment]
:ship: 9.13.2
