### ISSUE TITLE
`pnpm pack` JSON output option

### ISSUE THREAD

**Issue by karlhorky** [pnpm/pnpm#8764]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

Allow easy parsing of `pnpm pack` output, to avoid code like this:

- https://github.com/pnpm/pnpm/pull/8707#issuecomment-2478284044

### Describe the solution you'd like

Maybe `pnpm pack --format json`? (like `pnpm outdated --format json` https://github.com/pnpm/pnpm/pull/5582 )

```bash
$ pnpm pack --format json
{
  "tarball": "upleveled-preflight-8.0.4.tgz",
  "contents": [
    "bin/preflight.sh",
    "LICENSE",
    "package.json",
    "README.md",
    "src/checks/allChangesCommittedToGit.ts",
    "src/checks/eslint.ts",
    "src/checks/eslintConfigIsValid.ts",
    "src/checks/linkOnGithubAbout.ts",
    "src/checks/nodeModulesIgnoredFromGit.ts",
    "src/checks/noDependencyProblems/noDependenciesWithoutTypes.ts",
    "src/checks/noDependencyProblems/noUnusedDependencies.ts",
    "src/checks/noExtraneousFilesCommittedToGit.ts",
    "src/checks/noSecretsCommittedToGit.ts",
    "src/checks/preflightIsLatestVersion.ts",
    "src/checks/prettier.ts",
    "src/checks/projectFolderNameMatchesCorrectFormat.ts",
    "src/checks/stylelint.ts",
    "src/checks/stylelintConfigIsValid.ts",
    "src/checks/useSinglePackageManager.ts",
    "src/index.ts",
    "src/util/commandExample.ts",
    "src/util/crossPlatform.ts",
    "src/util/drone.ts",
    "src/util/packageJson.ts",
    "src/util/preflightBinPath.ts",
    "src/util/randomUserAgent.ts"
  ]
}
```

### Describe the drawbacks of your solution

More code to maintain

### Describe alternatives you've considered

My verbose parsing solution

- https://github.com/pnpm/pnpm/pull/8707#issuecomment-2478284044

**Comment by karlhorky** [comment]
@lvqq Thanks for the PR implementing `pnpm pack --json` (and review and merge @zkochan )

I'm guessing this will show up in a new patch or minor release:

- patch: [`pnpm@9.13.3`](https://github.com/pnpm/pnpm/releases/tag/v9.13.3)
- minor: [`pnpm@9.14.0`](https://github.com/pnpm/pnpm/releases/tag/v9.14.0)

**Comment by lvqq** [comment]
@karlhorky 🚢 9.14.1
