### ISSUE TITLE
Installing `pnpm` 9.13.2 requires `node` even though `pnpm` manages `node` versions

### ISSUE THREAD

**Issue by antitoxic** [pnpm/pnpm#8769]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.13.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=9.13.2 bash -

### Reproduction steps

1. Make sure you DON'T have `node` available (a.k.a. not installed / not in `$PATH`)
2. Run `curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=9.13.2 bash -`

### Describe the Bug

Until now `pnpm` install did not require `node`. Now if I don't `node` available (in `$PATH`) the install will not succeed.

I use `pnpm` to manage the `nodejs` vesions of my projects. I don't need yet-another-tool to manage/install node before I install `pnpm`.

### Expected Behavior

Install `pnpm` as it was done before, not requiring `node`

### Which Node.js version are you using?

NONE

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
I couldn't reproduce the issue. Tried in this docker image:

```
docker run --rm -it alpine:latest
```

Running

```
wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -
source /root/.shrc
```

`pnpm -v` works.

**Comment by antitoxic** [comment]
@zkochan 

I'm using `zsh` on Mac Pro (M2) , the pnpm install shows me this:

<img width="920" alt="SCR-20241119-hhha" src="https://github.com/user-attachments/assets/97b7afd0-0c17-4e70-8b5c-7ecfd48cbc27">

As text:

```
curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=9.12.3 bash -

==> Downloading pnpm binaries 9.12.3
 WARN  using --force I sure hope you know what you are doing
 ENOENT  not found: node

pnpm: not found: node
    at getNotFoundError (/snapshot/dist/pnpm.cjs)
    at Function.whichSync [as sync] (/snapshot/dist/pnpm.cjs)
    at getCommandAbsolutePathSync (/snapshot/dist/pnpm.cjs)
    at Object.sync (/snapshot/dist/pnpm.cjs)
    at getSystemNodeVersionNonCached (/snapshot/dist/pnpm.cjs)
    at getSystemNodeVersionNonCached (/snapshot/dist/pnpm.cjs)
    at prepareExecutionEnv (/snapshot/dist/pnpm.cjs)
    at /snapshot/dist/pnpm.cjs
    at async main (/snapshot/dist/pnpm.cjs)
    at async runPnpm (/snapshot/dist/pnpm.cjs)
Install Error!
```

Same if I try your exaple commands with `wget`.

**Comment by zkochan** [comment]
Probably related to this change: https://github.com/pnpm/pnpm/pull/8673

**Comment by antitoxic** [comment]
@zkochan amazing reaction time 👏👏👏 kudos!
