### ISSUE TITLE
Flickering progress bar during installation

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#877]
http://recordit.co/xmzs0J98AD

The frame rate doesn't capture the problem properly. Its like 2-3 flashes per second.

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
I know this one. It happens when running install with `--force`. We use `npm`'s programmatic API for reading the configs and for some reason it starts to print its output when `--force` is used.

We might need to fix this in npm.
