### ISSUE TITLE
Move update feed from `x.com` to `pnpm.io`

### ISSUE THREAD

**Issue by khill-fbmc** [pnpm/pnpm#8770]
### Describe the user story

I, like many others, are boycotting x[dot]com on principal for so many reasons.

It's unfortunate what has happened to twitter, but I feel like publishers who stay on the platform, are only losing eyes on their posts.

![image](https://github.com/user-attachments/assets/ffc1db67-2331-4133-ba4e-e1d40d1d21ff)

### Describe the solution you'd like

I would like to request that the update feed be moved to the official domain (pnpm.io) where users like me, can safely go check.

### Describe the drawbacks of your solution

None? The link can point to the new location instead of x[dot]com

**Comment by zkochan** [comment]
It is easier to engage with users on X. For instance, sometimes we create polls to gather valuable feedback. A link to the website is less useful in that regard.

I am also not a fan of Elon. However, X remains a platform where most of the users are. We can add a link to [bluesky pnpm.io](https://bsky.app/profile/pnpm.io) too.
