### ISSUE TITLE
`pnpm deploy --prod` fails due to missing `devDependencies`

### ISSUE THREAD

**Issue by haines** [pnpm/pnpm#8778]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/haines/pnpm-deploy-missing-workspace-package

### Reproduction steps

1. Have a workspace package listed in `devDependencies`
2. Delete the workspace package
3. Run `pnpm --filter=./packages/whatever deploy --prod dist`
4. `ERR_PNPM_WORKSPACE_PKG_NOT_FOUND`

### Describe the Bug

We are trying to avoid compiling all our development-only workspace packages in our production Docker build, so we have added them to `.dockerignore`.

`pnpm install --frozen-lockfile` works correctly (even though the missing packages are referenced in `pnpm-lock.yaml`.

`pnpm deploy --prod` fails with `ERR_PNPM_WORKSPACE_PKG_NOT_FOUND` despite the fact that the missing packages are only referenced in `devDependencies`.

I tried adding a `pnpm remove` step before deploying to remove the missing dependencies from the lockfile, but that fails as well with `ERR_PNPM_CANNOT_REMOVE_MISSING_DEPS`.

If I use e.g. `sed` to remove the missing package from the `devDependencies` in package.json, then `pnpm deploy --prod` succeeds.

### Expected Behavior

Missing `devDependencies` should not cause `pnpm deploy --prod` to fail, because they shouldn't be installed anyway.

### Which Node.js version are you using?

22.11.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
`pnpm install --frozen-lockfile` succeeds because the lockfile is already created. However, the current implementation of `deploy` calls `pnpm install` with full resolution (as if there's no lockfile). Full resolution cannot ignore `devDependencies` on `--prod` because it needs to create a consistent lockfile (the same lockfile as when there is no dependencies filter flags).

Fixing this bug would require significantly changing the way `pnpm deploy` works. I think maybe just copy the `node_modules/.pnpm` from the workspace root? @zkochan Do you have any direction?

**Comment by zkochan** [comment]
No, you cannot just copy the `node_modules/.pnpm` directory. `pnpm deploy` also copies the dependencies from the workspace, which are not present in `<workspace_root>/node_modules/.pnpm`.

Maybe just remove the `devDependencies` field from the `package.json` file that is written to the deploy output directory.

**Comment by KSXGitHub** [comment]
> Maybe just remove the `devDependencies` field from the `package.json` file that is written to the deploy output directory.

`deploy` calls `install` from the current directory, but with `opts.virtualStoreDir` pointing to the deploy output.



> No, you cannot just copy the `node_modules/.pnpm` directory. `pnpm deploy` also copies the dependencies from the workspace, which are not present in `<workspace_root>/node_modules/.pnpm`.

Maybe "just copy" wouldn't work. What I mean is can we recursively resolve the symlinks into reflinks and directories containing reflinks? Would there be a downside?

**Comment by haines** [comment]
> However, the current implementation of deploy calls pnpm install with full resolution (as if there's no lockfile).

Does that mean `pnpm deploy` ignores the lockfile? Or at least, that you might install different versions of dependencies to those specified in the lockfile? That seems problematic.

**Comment by zkochan** [comment]
> Maybe "just copy" wouldn't work. What I mean is can we recursively resolve the symlinks into reflinks and directories containing reflinks? Would there be a downside?

I don't understand what you mean by resolving symlinks into reflinks.

> Does that mean pnpm deploy ignores the lockfile? Or at least, that you might install different versions of dependencies to those specified in the lockfile? That seems problematic.

`pnpm deploy` ignores the existing lockfile currently.

**Comment by haines** [comment]
Sorry, I realise now that this is a dupe of https://github.com/pnpm/pnpm/issues/7281, so I'll close it.

> `pnpm deploy` ignores the existing lockfile currently.

Oh ok, I did not expect that. I was using `deploy` in my Docker build (from the docs that seems to be one of the primary use cases) but if it doesn't respect the lockfile then the build isn't reproducible, which kinda defeats the purpose.

**Comment by KSXGitHub** [comment]
@haines I will reopen this issue to continue the discussion. If you don't want to be annoyed by GitHub notifications, just click "unsubscribe".

@zkochan What I meant is we would write a custom function that recursively replicates the structure of `node_modules/.pnpm`, except the symlinks to the workspace, those will be replicated as directories of hardlinks, except the `node_modules` directories inside them, those will be replicated as directories of symlinks to the new `node_modules/.pnpm/*` at the deploy location. Is this feasible? What do you think would be the downside?

**Comment by zkochan** [comment]
> @zkochan What I meant is we would write a custom function that recursively replicates the structure of node_modules/.pnpm, except the symlinks to the workspace, those will be replicated as directories of reflinks, except the node_modules directories inside them, those will be replicated as directories of symlinks to the new node_modules/.pnpm/* at the deploy location. Is this feasible? What do you think would be the downside?

Well, isn't that how it works now already?

**Comment by KSXGitHub** [comment]
> Well, isn't that how it works now already?

`copyProject` currently handle the last part, yes. But `deploy` still calls `install` without while ignoring the lockfile. My idea is that we also "copy" the `node_modules/.pnpm` as well.

**Comment by KSXGitHub** [comment]
Actually, if we can fix this, we can fix both the missing dev dependencies issue and the not adhering to the lockfile issue:

https://github.com/pnpm/pnpm/blob/29447d7d79f4a778270303b62f52fbf616ad5089/releasing/plugin-commands-deploy/src/deploy.ts#L115-L116

**Comment by zkochan** [comment]
Well, you'd still have to pick what to copy from `node_modules/.pnpm`. You don't have to copy everything. The right way to do it would be to use the existing lockfile and create a "deploy lockfile" from it.

**Comment by haines** [comment]
> Well, you'd still have to pick what to copy from `node_modules/.pnpm`. You don't have to copy everything.

Yep, as well as not copying dependencies of the other packages in the workspace, we also use `pnpm deploy --prod` because we want to minimize the size of the final Docker image, so I'd expect `devDependencies` to be pruned as well in this case.

**Comment by KSXGitHub** [comment]
> The right way to do it would be to use the existing lockfile and create a "deploy lockfile" from it.

This is what I was thinking when I write [my second comment](https://github.com/pnpm/pnpm/issues/8778#issuecomment-2490775716). But I am not sure as to how the workspace references in the lockfile should be rewritten. Should the workspace packages be copied to the `node_modules` directory in the deploy location as well?

**Comment by zkochan** [comment]
If the lockfile will contain "file:" references to the workspace project, then pnpm will automatically copy them on install.
