### ISSUE TITLE
`I hope you know what you are doing` reprinted during native dep logs when using `--force`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#878]
![screen shot 2017-08-21 at 11 20 05 am](https://user-images.githubusercontent.com/281413/29512557-c63d1de4-8662-11e7-8c8d-60dc4914f483.png)

iTerm2

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
This one is caused by the same issues as #877

**Comment by jbergstroem** [comment]
Is there an upstream bug for this?

**Comment by zkochan** [comment]
I don't know. I did not file any issue about this at npm

**Comment by zkochan** [comment]
@jbergstroem I chatted with Kat from npm and she suggests to spawn npm in a child process to get the configs. They use this technic in `cipm`: https://github.com/zkat/cipm/blob/latest/lib/config.js

Hopefully, this won't make pnpm slower
