### ISSUE TITLE
Show progress of tar downloads

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#879]
When downloading a large dependency such as `material-design-icons` it can seem like it is stuck because the `downloaded` counter is not moving.

Maybe we could show the download status for deps that are taking longer than 5s or that are larger than a certain size?

**Comment by zkochan** [comment]
I think it is easier to kick-off tracking for the bigger files. Maybe for the ones that are larger than 1MB

**Comment by zkochan** [comment]
Published with pnpm@1.13.0. Download progress of tarballs that are bigger than 10 MB is shown.

Also covered reporting with unit tests.
