### ISSUE TITLE
Tab completion broken in bash

### ISSUE THREAD

**Issue by Mitsunee** [pnpm/pnpm#8801]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.14.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

not needed

### Reproduction steps

I am yet again getting the same error when trying to use tab completion:

```
pnpm  ERR_PNPM_REDUNDANT_PARAMETERS  The 1 parameters after shell is not necessary 
```

I have followed the steps in the documentation at https://pnpm.io/completion to attempt installing a newer version of the file and restarted my shell

### Describe the Bug

Pressing tab produces an error message

### Expected Behavior

Pressing tab should perform auto-completion

### Which Node.js version are you using?

v22.11.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Fedora 41 KDE Spin

**Comment by Mitsunee** [comment]
Nevermind this, user error. I must have forgotten to commit this to my dotfiles repo when I upgraded to pnpm v9 and lost the changes at some point. Fixed on my end in https://github.com/Mitsunee/dotfiles/commit/1ffe57ff816c5c58730048231e55acb158a116c0

**Comment by eric-burel** [comment]
@Mitsunee hi, hitting a similar issue, what does "'You can do this by removing the section of code that contains __tabtab in your dot files." mean exactly in pnpm docs and with regards to your post? The link you share is dead and I don't really get what happens.

**Comment by Mitsunee** [comment]
@eric-burel I'm not quite entirely sure about that, I think it simply refers to removing the reference to the old completions file in your bashrc. As for the dead link, that moved to github and got rewritten since, I basically wrote some bash code that reimplements the fish behaviour of including completing files from `.config`, so `.config/bash/completions/*.bash` in my case.
