### ISSUE TITLE
Hide `Update available` with env var

### ISSUE THREAD

**Issue by sequencerr** [pnpm/pnpm#8804]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

https://github.com/pnpm/pnpm/blob/main/cli/default-reporter/src/reporterForClient/index.ts#L106
Is there a way to hide? If not could this be implemented?

### Describe the solution you'd like

I want `pnpm` cli to not print update notice when explicitly set like `DENO_NO_UPDATE_CHECK`

**Comment by lvqq** [comment]
Try set `update-notifier=false` in npmrc: https://pnpm.io/npmrc#update-notifier
