### ISSUE TITLE
pnpm audit not displaying high/critical ignored errors

### ISSUE THREAD

**Issue by mdurling** [pnpm/pnpm#8807]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Run `pnpm audit`

### Describe the Bug

The summary shows high/critical errors causing the command to return a failure code, but they are not included in the display.
```
pnpm audit
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ moderate            │ smol-toml has a Denial of Service via malicious TOML   │
│                     │ document using deeply nested inline tables             │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ smol-toml                                              │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <=1.3.0                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=1.3.1                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ . > knip@5.24.3 > smol-toml@1.2.2                      │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-pqhp-25j4-6hq9      │
└─────────────────────┴────────────────────────────────────────────────────────┘
8 vulnerabilities found
Severity: 1 moderate | 6 high | 1 critical
```

### Expected Behavior

If there are high/critical errors. They should be displayed.

### Which Node.js version are you using?

20.11.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Probably the vulnerability is ignored by settings: https://pnpm.io/package_json#pnpmauditconfigignorecves

**Comment by zkochan** [comment]
maybe we could print something about that. Like "1 critical vulnerability is ignored".

**Comment by mdurling** [comment]
> maybe we could print something about that. Like "1 critical vulnerability is ignored".
Not a high priority, but it could save someone else from similar confusion.
Something like that would probably be useful. 
```
8 vulnerabilities found
Severity: 1 moderate | 6 high | 1 critical
7 vulnerabilities ignored
Severity: 6 high | 1 critical
```
Or:
```
8 vulnerabilities found
Severity: 1 moderate | 6 high (6 ignored) | 1 critical (1 ignored)
```
Or even:
```
8 vulnerabilities found
Severity: 1 moderate | 0 high (6 ignored) | 0 critical (1 ignored)
```
Thanks!
