### ISSUE TITLE
Cannot install pnpm 9.14.3 on Google Cloud Build

### ISSUE THREAD

**Issue by LeoMo-27** [pnpm/pnpm#8820]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.14.3

### Reproduction steps

If you trigger a Google Cloud Build of a project using `pnpm`, it will try to download version 9.14.3 from the GitHub releases, but it is not found.

### Describe the Bug

If you trigger a Google Cloud Build of a project using `pnpm`, it will try to download version 9.14.3 from the GitHub releases, but it is not found. It is possible that this is happening in other environments.
<img width="667" alt="image" src="https://github.com/user-attachments/assets/4d9b91be-31be-4494-bd80-ebbe58bd2d7f">

### Expected Behavior

Should install the version correctly through the GitHub releases.

### Which Node.js version are you using?

22.11.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by dominics** [comment]
Related bug on the Firebase side: https://github.com/firebase/firebase-tools/issues/8004

**Comment by takapiro99** [comment]
related bug on the Cloud Build's buildpack
https://github.com/GoogleCloudPlatform/buildpacks/issues/470

**Comment by zkochan** [comment]
This should be fixed now.
