### ISSUE TITLE
Pnpm packages published using version 1000.0.0

### ISSUE THREAD

**Issue by tobysmith568** [pnpm/pnpm#8822]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

N/A.

### Describe the Bug

Multiple pnpm packages including [`@pnpm/reviewing.dependencies-hierarchy`](https://www.npmjs.com/package/@pnpm/reviewing.dependencies-hierarchy) seem to have been published to npm using the version 900.0.0 two days ago and 1000.0.0 yesterday. Was this intentional?

If not, this needs to be actioned asap on npmjs.com before the packages become permanent.

### Expected Behavior

`@pnpm/reviewing.dependencies-hierarchy` and the other affected pnpm packages should be published using either their original versioning methodologies, or one inline with the current version of pnpm.

### Which Node.js version are you using?

N/A

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by tobysmith568** [comment]
Sorry for the mention, @zkochan , however I can see you're marked as a contributor for this specific package on npm and I believe the fix for this is very time critical because npm only allow packages to be unpublished for the first 72 hours.

**Comment by zkochan** [comment]
It is intentional. It makes it easier to keep publishing libraries from the v9 branch when v10 becomes active. Using just pnpm CLIs version as major for all libraries makes it impossible to release breaking changes to libraries. This way we can ship up to 99 breaking versions to libraries.
