### ISSUE TITLE
Disable NODE_ENV detection during install

### ISSUE THREAD

**Issue by aspirisen** [pnpm/pnpm#8827]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

There is automatic detection of NODE_ENV and as a result some dependencies could be omitted during install https://pnpm.io/cli/install#--prod--p

Sometimes you have set NODE_ENV before install, i.e. `NODE_ENV=production` and then all dev dependencies will not be installed, but they are required for build. The things can be even more complicated when install command is running by some wrapper tool, and you do not have a way to bypass flags to pnpm

Also, there can be a problem on CI where NODE_ENV can be set globally for a job

### Describe the solution you'd like

Option 1 - disable defaults for `--prod` and NODE_ENV detection, always install all dependencies unless explicit flag is set to install only specific set of dependencies

Option 2 - add a config property to `.npmrc` to skip NODE_ENV detection and install all dependencies

**Comment by zkochan** [comment]
I would be OK with "Option 1" (installing all dependencies, when NODE_ENV is set to `production). I don't know what @pnpm/collaborators think.

The reason this works like this currently is that npm CLI does it like this. Yarn seems to install everything. We can do it in v10 if we decide it soon.

**Comment by aspirisen** [comment]
Also, the args are a bit confusing `--prod` and `--dev` and their combinations. Maybe it is better to remove them.

Since the possible default behavior will be to install all dependencies pnpm can have `--skip-prod-deps` and `--skip-dev-deps` args with false values by default (without detecting NODE_ENV), just to leave the possibility to install only specific set of dependencies

**Comment by BlackHole1** [comment]
Personally, I'm not particularly satisfied with either option. I checked the documentation for npm and yarn. They are consistent in handling `NODE_ENV=production`:

> npm/Yarn will not install any package listed in devDependencies if the NODE_ENV environment variable is set to production

Ref: 
* https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production-true-false
* https://docs.npmjs.com/cli/v8/commands/npm-install#description

The handling method of npm and yarn is: If you want to install all dependencies after setting `NODE_ENV=production`, you can add a flag: `--prod=false` or `--production=false`

My main concerns are:

1.	This could cause destructive changes (potentially affecting many projects using pnpm).
2.	This is inconsistent with the behavior of other package managers, making it difficult for some projects to migrate from npm/yarn to pnpm.
3.	Although there is currently no package manager RFC in the open-source community, I believe we should align more closely with npm/yarn to avoid further fragmentation.

**Comment by aspirisen** [comment]
I just tried to run `NODE_ENV=production yarn install` and the dev deps have been installed, strange. Yarn version `1.22.22`. Maybe I am missing something? 

I am currently migrating from yarn to pnpm, and that was the reason for creating this issue, I do not remember that yarn didn't install dev dependencies on CI or docker when NODE_ENV is production.

**Comment by zkochan** [comment]
I checked with the latest Yarn and it installed dev deps.

**Comment by aspirisen** [comment]
Yes, looks like latest Yarn version installs dev deps under `NODE_ENV=production`

**Comment by BlackHole1** [comment]
If the behavior of yarn is to install everything, then I prefer option 1.

**Comment by btea** [comment]
I think option 1 makes more sense.

**Comment by KSXGitHub** [comment]
Normally, I would prefer pnpm to not behave differently from Yarn and NPM, but Yarn and NPM are behaving differently themselves.

In this case, installing everything including dev dependencies rarely break anyone's workflow (unless they don't have enough disk space), so I prefer option 1.

**Comment by Huodoo** [comment]
How to deploy node.js services with docker without installing devDependencies

**Comment by kaelig** [comment]
In 10.0.0-rc.2, `NODE_ENV=production pnpm install` still skips devDependencies. Was that on purpose?

**Comment by zkochan** [comment]
No, not on purpose. I'll check.
