### ISSUE TITLE
pnpm update removes locally linked package after version bump

### ISSUE THREAD

**Issue by paulpflug** [pnpm/pnpm#883]
Hi again,

following problem:
```sh
# in some-pkg
pnpm link some-local-pkg

# in some-local-pkg
npm version patch

# in some-pkg
pnpm update
# local link is removed, output:
# dependencies:
# - some-local-pkg 

# calling it again
pnpm update
# it is installed as a normal pkg, output:
# dependencies:
# + some-local-pkg
```
I think the link shouldn't get removed in the first place - but even if, the normal pkg should get installed right away.

thanks for your great work - it really eases my daily work.

**Comment by zkochan** [comment]
Related: #871

**Comment by zkochan** [comment]
As of version 2.15.0 it works as you expected

> I think the link shouldn't get removed in the first place
