### ISSUE TITLE
Allow Customization of .pnpm/ Folder Name Encoding to Prevent Issues with Special Characters (e.g., #)

### ISSUE THREAD

**Issue by init-imangali** [pnpm/pnpm#8837]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

As a developer, I often work with packages installed directly from GitHub (e.g.,` github:user/repo#branch`), but I face issues when tools like Next.js and Webpack fail to handle the encoded folder names generated in `node_modules/.pnpm/`. Specifically:

- Encoded paths containing special characters like `#` lead to runtime errors in tools that misinterpret them as part of a URL.
- Tools like Webpack prepends for  `#`  null byte (`\x00`), causing `fs.stat` failures in further proccess of build. 

This makes using direct GitHub installs with pnpm unreliable, forcing me to resort to workarounds like `node-linker=hoisted`, which sacrifices deduplication and isolation benefits.

<img width="983" alt="Снимок экрана 2024-12-05 052300" src="https://github.com/user-attachments/assets/46eb9fb1-b144-4992-a13f-d945b2830064">

### Describe the solution you'd like

I would like a configuration option to customize how folder names in .pnpm/ are generated.

From config
`pnpm config set node-modules-folder-encoding "replace:#:_"`

Or from hook within the file **`.pnpmfile.cjs`** which get generated by default folder name and must return string for that.

This would enable developers to control path encoding and avoid compatibility issues without giving up the benefits of pnpm's isolated mode.

### Describe the drawbacks of your solution

- Allowing arbitrary customizations of folder names (via replace or a .pnpmfile.cjs hook) can lead to naming collisions. For example, replacing # with _ in multiple packages might produce duplicate folder names if two distinct packages end up with the same sanitized name.

- Custom replacements could unintentionally create longer paths, especially when dealing with deeply nested dependencies. This could exceed filesystem path limits on some environments, such as Windows (MAX_PATH).

- If a .pnpmfile.cjs hook is used, it will need to be executed for every dependency during installation, potentially slowing down the install process for large projects.

- Supporting folder name customization adds complexity to pnpm, requiring validation of configurations or hook outputs to ensure paths remain unique and valid. This increases the potential for bugs in both pnpm and its ecosystem.

### Describe alternatives you've considered

1. Using `node-linker=hoisted`:

- This resolves the issue but sacrifices the deduplication and strict isolation benefits of `pnpm`.
- And it creates a flatter `node_modules `structure, which might not be ideal for large-scale projects.

2. Using file: Installs:

- Cloning GitHub packages locally and referencing them with file: avoids the issue, but this adds extra steps and doesn’t scale well for dynamic dependencies.

3. Patching Webpack or Next.js:

- This is beyond the scope of most developers and doesn’t address the broader issue of compatibility with other tools.
- And i still not digged down into bundles enough to determine which one is causing issue.
- I blame webpack, becouse of the fact that all works fine with turbopack compiler
- Unfortunately that bundler works only for dev servers...

**Comment by init-imangali** [comment]
I swithed to pnpm a few days ago. So here i am. First issue with it, except that fact that i type `npm` instead of `pnpm` from time to time 😅

**Comment by init-imangali** [comment]
Hmm, after some searches in the source code, i found out that id initially generates in resolvers. Like that for npm resolvers :
![image](https://github.com/user-attachments/assets/5923dd66-f7e6-434c-8447-21d9d49cd492)

And for git resolver:
![image](https://github.com/user-attachments/assets/47462576-f410-4ee2-acc7-8087228087b8)

And it looks like hardcoded. All my struggle is cuz of that hash symbol...

I found also tests that checks if that relver ids is correct, but i dont think that this tests will fail if there introduce some id customization hook:
![image](https://github.com/user-attachments/assets/8af907cf-35fa-4577-90c9-3e32c770ace2)

**Comment by init-imangali** [comment]
Yeap! Guys, its 100% cuz of that damn # symbol. I just manually renamed forlder name. And changed that hash to triple plus sign. After i relinked it again to the top level position... And here is the damn results:
![image](https://github.com/user-attachments/assets/a8b58fda-a00e-4704-be29-4fb34f1f3a0b)

So i need that feature as soon as posible. Maybe should i fork and pr myself 🤔
But im still unsure and unfamilliar with this project structure 😅

Even if you wont do it, just anybody who knows and working on this project, can u give advise like:
- Make ur own sh$t in that subpackage, where u can get hooks functions from that package, Adios friend! - *_And fades away in the sunset_* 😂

**Comment by init-imangali** [comment]
UPD: Simpler solution is just replace that hash symbol with quadro plusses: `++++`. Deasseble it, like in thes meme 😂:
![image](https://github.com/user-attachments/assets/773f2f0e-0e96-4881-8fbb-d0ef1a277ea0)

**Comment by init-imangali** [comment]
> The # is already replaced in v10 I believe. Related PR: #8557

Sorry for wasting your time, i didnt noticed that issues is already fixed in beta 😅.
Btw, is it possible to install new beta version publicly? Or only loading from source works?

Thans for your reply)

**Comment by init-imangali** [comment]
> The # is already replaced in v10 I believe. Related PR: #8557

Sorry for wasting your time, didnt noticed that this already fixed in new betaversion 😅

And thanks for your reply)

**Comment by zkochan** [comment]
You can install the beta version. No need to build from source.
