### ISSUE TITLE
Version numbers of `@pnpm` packages not in sync with pnpm version (e.g. v900 or v1000 vs. v9) -- issue?

### ISSUE THREAD

**Issue by firxworx** [pnpm/pnpm#8841]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.14.4

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/pnpm/pnpm/commit/3fe70e7897abb385b2194939f72c8ee6d34df53f

### Reproduction steps

Look at the major version numbers of current release `@pnpm` packages in the hundreds or thousands... 
Does that look right to you @zkochan ?

```
 ○ @pnpm/find-workspace-dir                                     7.0.2 ❯ 900.0.1
```

### Describe the Bug

I ran a `pnpm -r up -i --latest` in the pnpm workspace of my project and was surprised to see:

```
 ○ @pnpm/find-workspace-dir                                     7.0.2 ❯ 900.0.1
```

What a jump to 900! At first I thought it might be a supply chain attack. I figured I'd try again after so many days. Its still like that! So then I searched for any mention of a new scheme or nomenclature. I also didn't find any issues. Then I searched for the commit. 

https://github.com/pnpm/pnpm/commit/3fe70e7897abb385b2194939f72c8ee6d34df53f

Commit message is: `refactor!: all lib versions should start with pnpm major version`.

The current major version of pnpm is `9` not `900`.

Is this a typo or issue? If not can there at least be some sort of docs or explanation for this versioning scheme if it is intentional?

### Expected Behavior

If libs matching the major version of pnpm that they are associated with is the new scheme then I expect the current release of a lib like `@pnpm/find-workspace-dir` to start with major version `9` because the corresponding major version of `pnpm` is `9`.

### Which Node.js version are you using?

v20.18.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by btea** [comment]
refer https://github.com/pnpm/pnpm/issues/8822#issuecomment-2509425382

**Comment by zkochan** [comment]
it is correct
