### ISSUE TITLE
PNPM not found in npm registry

### ISSUE THREAD

**Issue by atstoyanov** [pnpm/pnpm#8847]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

9.15.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Variant 1: Navigate to https://www.npmjs.com/package/pnpm - it show 404 page.
Variant 2: try to upgrade version with:

```bash
pnpm add -g pnpm@latest
```
<img width="561" alt="Screenshot 2024-12-08 at 21 00 32" src="https://github.com/user-attachments/assets/cb59df2f-9a1f-47f5-be88-7d48b93b162f">

Variant 3: Run github action that use https://github.com/pnpm/action-setup
it fails with:
<img width="656" alt="Screenshot 2024-12-08 at 21 08 00" src="https://github.com/user-attachments/assets/ea143061-d974-4a1e-8ae6-fd40af843902">

### Describe the Bug

pnpm package is missing from npm.com regestry

### Expected Behavior

pnpm package is not missing

### Which Node.js version are you using?

20.18.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by iget-master** [comment]
Also happens here. Acessing the npm registry website also don`t have pnpm anymore.

**Comment by atstoyanov** [comment]
It seems if you specify the version it works. 
https://www.npmjs.com/package/pnpm/v/9.15.0 - this one works.
<img width="485" alt="Screenshot 2024-12-08 at 21 11 18" src="https://github.com/user-attachments/assets/7588f1e8-ec9e-41d0-8f3a-e2d5c10aeb55">

**Comment by iget-master** [comment]
It`s just working right now. Might be a npm outage

**Comment by luc122c** [comment]
NPM are currently performing maintenance. It's probably just a side-effect of that. See https://status.npmjs.org/incidents/px35z3dmcjgm

**Comment by atstoyanov** [comment]
It works now.
