### ISSUE TITLE
Latest release still bundles vulnerable cross-spawn version

### ISSUE THREAD

**Issue by am-burban** [pnpm/pnpm#8858]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.15.0

### Reproduction steps

```
wget https://registry.npmjs.org/pnpm/-/pnpm-9.15.0.tgz
tar -xvzf pnpm-9.15.0.tgz
cat package/dist/node_modules/cross-spawn/package.json | grep '"version"'
```

### Describe the Bug

Even though after #8782 the vulnerable cross-spawn <7.0.5 versions were supposed to be updated, even the latest version of pnpm does still bundles cross-spawn 7.0.3.

This means vulnerability scanners like trivy still complain about https://github.com/advisories/GHSA-3xgq-45jj-v275 

### Expected Behavior

pnpm should bundle cross-spawn v7.0.5

### Which Node.js version are you using?

20.18.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by karlhaworth** [comment]
Seeing the same as well. Cannot figure out why.

**Comment by zkochan** [comment]
Try pnpm v10.0.0-beta.3

**Comment by am-burban** [comment]
Yep, that version looks fine. Thank you!
Will it also be backported to the v9 release line?

**Comment by zkochan** [comment]
Yes, the next version of v9 will have the fix too.
