### ISSUE TITLE
esbuild 0.24.1 build error

### ISSUE THREAD

**Issue by last-Programmer** [pnpm/pnpm#8895]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### Reproduction steps

We have upgraded esbuild to 0.24.1 and we are getting build error like this

panic: runtime error: index out of range [1259] with length 1259

goroutine 114614 [running]:
github.com/evanw/esbuild/internal/sourcemap.DecodeVLQ({0xc02390987d, 0x4eb, 0x1?}, 0xc0424c8040?)
	github.com/evanw/esbuild/internal/sourcemap/sourcemap.go:126 +0x110
github.com/evanw/esbuild/internal/sourcemap.SourceMapPieces.Finalize({{0xc023908a00, 0xe7d, 0x137b}, {0xc02390987d, 0x4eb, 0x4fe}, {0xc023909d68, 0x13, 0x13}}, {0xc04e477580, ...})
	github.com/evanw/esbuild/internal/sourcemap/sourcemap.go:320 +0x474
github.com/evanw/esbuild/internal/linker.(*linkerContext).generateChunksInParallel.func1(_, {{0xc02d6b7860, 0x19}, 0xc02d6a7ce0, {{0xc0289b85d0, 0x6, 0x6}}, {0xc030383f60, 0x1, 0x1}, ...})
	github.com/evanw/esbuild/internal/linker/linker.go:714 +0xa55
created by github.com/evanw/esbuild/internal/linker.(*linkerContext).generateChunksInParallel in goroutine 9
	github.com/evanw/esbuild/internal/linker/linker.go:658 +0x878

### Describe the Bug

We have upgraded esbuild to 0.24.1 and we are getting build error like this

panic: runtime error: index out of range [1259] with length 1259

goroutine 114614 [running]:
github.com/evanw/esbuild/internal/sourcemap.DecodeVLQ({0xc02390987d, 0x4eb, 0x1?}, 0xc0424c8040?)
	github.com/evanw/esbuild/internal/sourcemap/sourcemap.go:126 +0x110
github.com/evanw/esbuild/internal/sourcemap.SourceMapPieces.Finalize({{0xc023908a00, 0xe7d, 0x137b}, {0xc02390987d, 0x4eb, 0x4fe}, {0xc023909d68, 0x13, 0x13}}, {0xc04e477580, ...})
	github.com/evanw/esbuild/internal/sourcemap/sourcemap.go:320 +0x474
github.com/evanw/esbuild/internal/linker.(*linkerContext).generateChunksInParallel.func1(_, {{0xc02d6b7860, 0x19}, 0xc02d6a7ce0, {{0xc0289b85d0, 0x6, 0x6}}, {0xc030383f60, 0x1, 0x1}, ...})
	github.com/evanw/esbuild/internal/linker/linker.go:714 +0xa55
created by github.com/evanw/esbuild/internal/linker.(*linkerContext).generateChunksInParallel in goroutine 9
	github.com/evanw/esbuild/internal/linker/linker.go:658 +0x878

### Expected Behavior

esbuild should run without any error

### Which Node.js version are you using?

22.11

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by btea** [comment]
It looks like a problem on the esbuild side, and the latest version also affects Vite, so Vite is currently pinned to 0.24.0.

**Comment by last-Programmer** [comment]
this seems to be esbuild issue. so closing 

it is already here https://github.com/evanw/esbuild/issues/4011
