### ISSUE TITLE
difference between npm and pnpm behavior with nested dependencies

### ISSUE THREAD

**Issue by donaldpipowitch** [pnpm/pnpm#890]
### pnpm version:

`v1.13.2`

### Code to reproduce the issue:

```
{
  "name": "yarn-star",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@types/react": "^15.0.0",
    "@types/react-router-dom": "^4.0.7"
  }
}
```

### Expected behavior:

Initially I'd think it should match npm's behaviour, but yarns behaves like pnpm.

`$ yarn` in `v0.28.4`:

```
├── @types/react@15.6.2
└─┬ @types/react-router-dom@4.0.7
  ├── @types/react@16.0.5
  └─┬ @types/react-router@4.0.15
    └── @types/react@16.0.5
```

`$ npm install` in `v5.4.1`:

```
├── @types/react@15.6.2
└─┬ @types/react-router-dom@4.0.7
  ├── @types/react@15.6.2  deduped
  └─┬ @types/react-router@4.0.15
    └── @types/react@15.6.2  deduped
```

### Actual behavior:

`$ pnpm install` in `v1.13.2`:

```
├── @types/react@15.6.2
└─┬ @types/react-router-dom@4.0.7
  ├── @types/react@16.0.5
  └─┬ @types/react-router@4.0.15
    └── @types/react@16.0.5
```

---

Similar issue on yarns side: https://github.com/yarnpkg/yarn/issues/3951.
For yarn it works as intended. They have a new `resolutions` feature to manually adjust this behaviour.

**Comment by zkochan** [comment]
With pnpm you can make it work as well by using [hooks](https://github.com/pnpm/pnpm#hooks)

**Comment by donaldpipowitch** [comment]
So it is like `yarn`? It works as intended and should be overwritten via hooks, if a different behavior is needed?

**Comment by zkochan** [comment]
Yes

**Comment by zkochan** [comment]
But I think we can implement a `pnpm dedupe` command which would try to use less packages. So if a lesser version matches the range and is already required, it will be re-used for others

**Comment by donaldpipowitch** [comment]
So this issue can probably be closed...?

**Comment by zkochan** [comment]
Yes. If you create the hook, please post it here, for reference
