### ISSUE TITLE
`onlyBuiltDependencies` does not work

### ISSUE THREAD

**Issue by SomeAspy** [pnpm/pnpm#8920]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

10.0.0-rc.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/SomeAspy/pnpm10rc-bug/blob/main/package.json

### Reproduction steps

1. Use a package that requires build scripts
2. Add said package to `pnpm.onlyBuiltDependencies`
3. Scripts specified in the above step still are not run properly

### Describe the Bug

PNPM seems to entirely ignore `pnpm.onlyBuiltDependencies`.
![image](https://github.com/user-attachments/assets/888801d6-5888-4694-8cbf-5747fc641135)
Interestingly, `pnpm.neverBuiltDependences` shares the same description of "A list of dependencies to skip the builds."

However, `pnpm.onlyBuiltDependenciesFile` works as intended.

### Expected Behavior

`pnpm.onlyBuiltDependencies` should run build scripts for packages specified within.

### Which Node.js version are you using?

v23.5.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Arch

**Comment by zkochan** [comment]
It appears that I did a mistake in the https://github.com/pnpm/pnpm/pull/8897 PR. Now only the `pnpm.onlyBuiltDependenciesFile` field works.

**Comment by SomeAspy** [comment]
Any idea when this fix will show up in an RC or other public build?

**Comment by zkochan** [comment]
Probably today.

**Comment by SomeAspy** [comment]
Thanks!
