### ISSUE TITLE
Errors not helpful et al

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#896]
Please provide nice console errors. Currently it gives only ` ERROR  [object Object] `

**Comment by zkochan** [comment]
This is where we print errors: https://github.com/pnpm/pnpm-default-reporter/blob/master/src/reportError.ts#L26

Maybe if there is no `err.message` we have to try `err.toString()`

I there more helpful error in the `pnpm-debug.log` file?

**Comment by deadcoder0904** [comment]
This is the main issue 

```bash
 WARN  EXDEV: cross-device link not permitted, link
'/Users/deadcoder0904/.pnpm-store/2/registry.npmjs.org/chalk/2.1.0/node_modules/chalk/packag
e.json' ->
'/Volumes/Coding/Code/Forked/create-react-native-app/pnpm-test/node_modules/.registry.npmjs.
org/chalk/2.1.0/node_modules/chalk+stage/package.json'
Falling back to copying packages from store
Resolving: total 387, reused 385, downloaded 2, done
 ERROR  [object Object]
`pnpm install --save-dev --save-exact react-native-scripts` failed
```

**Comment by deadcoder0904** [comment]
I'm trying to use `react-native` by using command `create-react-native-app pnpm-test --package-manager pnpm`.

This isn't available as of now since I just created the [pull request](https://github.com/react-community/create-react-native-app/pull/412)

**Comment by zkochan** [comment]
Cool!

I can look into the issue later. I work on some of the other issues currently.

**Comment by deadcoder0904** [comment]
Cool no problem. Its an awesome package manager but needs some work. Thank you for ur work 💯

**Comment by zkochan** [comment]
@deadcoder0904 I tried and installation of native react app worked with pnpm on my Linux.

I wonder if this is because you install on a non-primary volume. Try to run pnpm with a custom store location. The store location should be on the same disk where you do the installation. 

```
pnpm install --store "/Volumes/Coding/.pnpm-store"
```

**Comment by deadcoder0904** [comment]
Ok I will check later on. Get back to u 2mrrw

**Comment by deadcoder0904** [comment]
Yaa dude this worked like a charm 👍

But I don't want to do this everytime I create a new project like if I have a new machine & I want to install `create-react-app` then I have to do this again.

Is there any way we can fix this permanently when we directly install `pnpm` on new machine.

**Comment by deadcoder0904** [comment]
& to be precise the command is

```
create-react-native-app project --package-manager pnpm
```

```
pnpm install --store "/path/to/your/project/.pnpm-store"
```

**Comment by zkochan** [comment]
@deadcoder0904, If you do installation always on the same disk, you can just override the store location globally

```
npm c set store /Volumes/Coding/.pnpm-store
```

Or you can override the location for a project, by creating a `.npmrc` file in the same folder where the project's `package.json` is. `.npmrc` content:

```ini
store=/Volumes/Coding/.pnpm-store
```

When we fix #712, config manipulations will not be needed anymore.

**Comment by deadcoder0904** [comment]
The problem is that the path must be set to the project directory not on the Volume I'm coding in.

Which means I have to go to every project & set the path to each project as mentioned above.

U didn't read the above comment properly. Check it out. But this project is awesome than both `npm` & `yarn` in load times as well as space.

I'll wait for #712 to be closed. Ping me when its done. Thank you 😄

**Comment by zkochan** [comment]
Why should it be in the project? pnpm uses a shared store, so it can live in one place on the disk. If you'll have a store per project, you won't win from the benefits of shared store. With a shared store you save gigabytes of disk space!

**Comment by deadcoder0904** [comment]
Yep, it didn't work yesterday so I thought it would've been from the project folder. It works now. But the problem is `devDependencies` are installed from `npm`

**Comment by deadcoder0904** [comment]
This is the issue -

```bash
Using package manager as pnpm with pnpm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

Resolving: total 387, reused 387, downloaded 0, done
 WARN  registry.npmjs.org/react-redux/5.0.6 requires a peer of react@^0.14.0 ||
^15.0.0-0 || ^16.0.0-0 but none was installed.
Adding 387 packages to node_modules

devDependencies:
+ react-native-scripts 1.3.1

Installing dependencies using npm...

```

It installs every package from cache using `pnpm`, then for `react-native-scripts` it installs using `npm`

**Comment by zkochan** [comment]
I think the original issue was fixed. Errors are more detailed now
