### ISSUE TITLE
Progress Bar like Yarn rather than flooding console

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#897]
I think progress bars are visually pleasing & less distracting & the console isn't flooded with all the unhelpful text

**Comment by zkochan** [comment]
This is a duplicate of https://github.com/pnpm/pnpm/issues/875.

We can only show a progress bar if there is a `shrinkwrap.yaml`. Otherwise, pnpm doesn't know how much is left because we don't divide installation into 4 stages, like Yarn. We do installation more aggressively.

**Comment by deadcoder0904** [comment]
Ok so I'll close this
