### ISSUE TITLE
pnpm fails to install transitive .bin executables

### ISSUE THREAD

**Issue by indiescripter** [pnpm/pnpm#899]
### pnpm version:
`1.14.8`

### Code to reproduce the issue:

Contents of shell script file *test-buildverse-with-pnpm.sh*

**Note: this script updated from that provided with #892.**

```sh
# Run in a temporary directory
rm -rf foobar-develop
clear
npx buildverse create-suite foobar-develop
cd foobar-develop
npm run create-project foo
npm run create-project bar
cd foo
npm install --save chalk
cd ..
cd bar
npm install --save chalk
cd ..
npm run add-project foo
npm run add-project bar

# "The following works..."
echo
echo
echo "Testing with npm..."
echo
npm --version
echo
echo
find . -type d -name node_modules | xargs rm -rf
npm install
echo
echo "NOTE: npm installed the following executables in ./node_modules/.bin"
echo
ls ./node_modules/.bin

# "The following works..."
echo
echo
echo "Testing with yarn..."
echo
yarn --version
echo
echo
find . -type d -name node_modules | xargs rm -rf
yarn install
echo
echo "NOTE: yarn installed the following executables in ./node_modules/.bin"
echo
ls ./node_modules/.bin

# "The following will work soon!"
echo
echo
echo "Testing with pnpm..."
echo
pnpm --version
echo
echo
find . -type d -name node_modules | xargs rm -rf
pnpm install
echo
echo "NOTE: pnpm installed the following executables in ./node_modules/.bin"
echo
ls ./node_modules/.bin
```

### Expected behavior:
Should work the same as `npm`.

### Actual behavior:
Above script works with `npm` (as well as `yarn`) but fails with `pnpm`.
In this script `pnpn install` fails so it never gets to the follow `echo/ls` lines which display the executables that were to be installed in `foobar-develop/node_modules/.bin`.

### Additional information:

 - `node -v` prints:
`v6.11.3`

 - `npm --version` prints:
`5.4.1`

 - Windows, OS X, or Linux?:
Linux

**Comment by indiescripter** [comment]
@zkochan I've just pulled buildverse project into two packages much in the same way that there is pnpm + supi. The new related package is [for-each-project](https://www.npmjs.com/package/for-each-project).

Now, I'm not sure if the testing I did tonight with pnpm & the new for-each-project package shows up the same error that is occurring as reported or if it is a different error.

This is another "works with npm & yarn but not pnpm situation". You can reproduce by unzipping the attached file and running 'pnpm install'.  Test with 'npm install' & 'yarn install' beforehand to verify. Delete node_modules folder and lockfiles prior to testing with each package manager.

I don't want to burden you with work but nevertheless feel that bringing issue to your attention is best for pnpm.

[foobar-project.tar.gz](https://github.com/pnpm/pnpm/files/1337693/foobar-project.tar.gz)

**Comment by zkochan** [comment]
Thanks for reporting and for the detailed steps-to-repro. It is not a burden, when possible, pnpm should work as npm.

**Comment by indiescripter** [comment]
@zkochan Just quick touchbase with you. Wondering how this is looking. Cheers.

**Comment by zkochan** [comment]
@indiescripter I looked into it. This is not a bug in pnpm. It works as designed.

The problem is that you `for-each-project` is a dependency of `buildverse`. Only bins of top dependencies are linked into the root `node_modules/.bin`. The reason it works with npm/Yarn is that they create a flat `node_modules` structure.

In order to make it work with pnpm, you have to have the `for-each-project` bin in buildverse. One package can have several bins, so it is not an issue, you can create like a proxy to the dependency's bin.

**Comment by indiescripter** [comment]
@zkochan Thanks for the heads up. This sounds like a similar problem I had with [npx](https://www.npmjs.com/package/npx) so I know what to do.

I'll let you know when I have it sorted as it is quite exciting to say "works with pnpm" as well!

**Comment by indiescripter** [comment]
@zkochan Been meaning to get back to you. Yes, got it sorted last week; just been waiting for pnpm v1.18 to get back into intensive testing.

Thanks for your help/feedback though remains a caveat that in this case pnpm deviates slightly from npm  so 100.000% drop-in replacement is not possible (or even sought; rather as designed as you say).

**Comment by indiescripter** [comment]
I'm happy for you to close this issue if you have no further comments.

**Comment by zkochan** [comment]
Yep, it doesn't make sense for pnpm to replicate flat node_modules. It is used by npm/Yarn because they don't use symlinks currently.
