### ISSUE TITLE
pnpm can't be installed anymore on pre-release Node builds w/o python

### ISSUE THREAD

**Issue by kurtextrem** [pnpm/pnpm#901]
See title. That's because of `drivelist` and `prebuilt-install`. For example I am using https://nodejs.org/download/v8-canary/ but `drivelist` doesn't provide prebuilt binaries for such versions.
I'm not sure if there is a middle-way to fix this, but for now I'm stuck on v1.13.2.

**Comment by zkochan** [comment]
I think making drivelist an optionalDependency should fix this issue

**Comment by zkochan** [comment]
@kurtextrem could you try doing `npm i -g pnpm --ignore-scripts`?

**Comment by zkochan** [comment]
@kurtextrem you can try to reinstall pnpm. drivelist is an option dependency now, so it should be ignored if it fails during installation

**Comment by kurtextrem** [comment]
Fixed!
