### ISSUE TITLE
Suddenly failing on Linux with EACCESS errors from zkochan-drivelist

### ISSUE THREAD

**Issue by onlywei** [pnpm/pnpm#902]
### pnpm version: 
Started happening recently, sometime after I upgraded to 1.14.9. I then tried upgrading to 1.15.0 and it was still happening. After that I tried downgrading to 1.14.5 and it is still happening.

### Code to reproduce the issue:
I just ran `pnpm install` from Jenkins on a linux box.

### Expected behavior:
`pnpm install` should finish successfully

### Actual behavior:
I get this error:
```
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at executeScript (/opt/jenkins_slave/workspace/my_path/node_modules/zkochan-drivelist/lib/execute.js:102:16)
    at createTemporaryScriptFile (/opt/jenkins_slave/workspace/my_path/node_modules/zkochan-drivelist/lib/execute.js:168:5)
    at fs.writeFile (/opt/jenkins_slave/workspace/my_path/zkochan-drivelist/lib/execute.js:81:5)
    at /opt/jenkins_slave/workspace/my_path/graceful-fs/graceful-fs.js:99:16
    at /opt/jenkins_slave/workspace/my_path/npm/node_modules/graceful-fs/graceful-fs.js:99:16
    at /opt/jenkins_slave/workspace/my_path/graceful-fs/graceful-fs.js:99:16
    at /opt/jenkins_slave/workspace/my_path/npm/node_modules/graceful-fs/graceful-fs.js:43:10
    at /opt/jenkins_slave/workspace/my_path/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```

### Additional information:

 - `node -v` prints: I tried both `8.5.0` and `8.6.0`
 - Windows, OS X, or Linux?: Linux. It works fine on Mac OS X.

**Comment by zkochan** [comment]
Hm, I thought I fixed this in scope of the fix for #901. I've made `zkochan-drivelist` and optional dep in `drive-by-path` version `0.1.1`. Could you check if `drive-by-path` `0.1.1` is installed?

**Comment by onlywei** [comment]
`drive-by-path` `0.1.1` *is* installed, and I see the optional dependency, but in its `package.json` I also see:

```
  "dependencies": {
    "is-subdir": "^1.0.1",
    "once": "^1.4.0",
    "ramda": "^0.24.1",
    "util.promisify": "^1.0.0",
    "zkochan-drivelist": "^0.0.0"
  },
```

**Comment by zkochan** [comment]
Weird. I'll try to republish it

**Comment by zkochan** [comment]
Seems like this is the way it works https://github.com/npm/npm/issues/3502.

`optionalDependencies` has precedence

**Comment by zkochan** [comment]
@onlywei I published `pnpm@1.14.11` which should not have the issue.

Also, I believe `pnpm@1.15` will be installed successfully if installed with the `--ignore-scripts` flag (`npm i -g pnpm --ignore-scripts`)

Maybe this is an issue with npm as it should skip failed optional deps. I tried it today on a Windows and even though the dep failed, installation completed successfully (I used `npm@4` to install pnpm). What is the version of npm on you Linux?

**Comment by onlywei** [comment]
My npm version is 5.3.0. I just tried `pnpm@1.15` with `--ignore-scripts` flag and it did not work. I am going to try `pnpm@1.14.11` now.

**Comment by onlywei** [comment]
`pnpm@1.14.11` worked.

**Comment by zkochan** [comment]
I don't think reverting drivelist usage is an option because it is there solves a pretty painful issue that users have when installing on different drives.

As of now I think it is a npm issue.

But we can solve it also by introducing alternative installation methods that avoid npm

**Comment by onlywei** [comment]
OK. We'll stick to `1.14.11` for now, then. Seems to work fine. Can't upgrade until drivelist stops throwing errors, though.

**Comment by zkochan** [comment]
@onlywei, you can now install pnpm with this command in your jenkins job:

```
curl -L https://github.com/pnpm/scripts/raw/master/install.js | node
```

**Comment by onlywei** [comment]
@zkochan thanks for that script, but unfortunately we will not be able to use it in our system. For certain reasons, we need to:

1. Install our stuff via our npm enterprise instance (including pnpm).
2. Install pnpm hermetically, meaning non-global.

Is there any way to add some kind of flag to avoid executing any of the drivelist code?

**Comment by onlywei** [comment]
@zkochan I think I can just use `npm install pnpm --no-optional` and it will work. Testing some scenarios now...

**Comment by onlywei** [comment]
Seems to be working. I'll let you know if it fails again. I will close this issue some time next week once I'm confident.

**Comment by zkochan** [comment]
@onlywei in your environment, can you run npx?

I can add a bin to `@pnpm/self-installer` and that would allow to install pnpm via the command:

```
npx @pnpm/self-installer
```

**Comment by onlywei** [comment]
@zkochan I can run npx in my environment, but I cannot use the self-installer because it installs pnpm globally while I want to install it hermetically. The `npm install pnpm --no-optional` command is working for me fine now, so I feel comfortable closing this issue.

**Comment by zkochan** [comment]
I think we can add a param to `@pnpm/self-installer` to support non-global installation of pnpm.

and another one to use a custom registry for downloading pnpm.

So you'd be able to do something like 

```
curl -L https://unpkg.com/@pnpm/self-installer | node --dist /home/src/node_modules --registry https://registry.example.com/
```

**Comment by onlywei** [comment]
If the self-installer can specify where to install the pnpm files, I would certainly love to give it a try.

**Comment by zkochan** [comment]
Cool, I created an issue for this #922
