### ISSUE TITLE
`pnpm link` globally linking some dependencies

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#905]
### Code to reproduce the issue:

```
// Create a project with `pnpm@some-version` in its dependencies.
// Run pnpm install
$ pnpm -v
1.16.0
$ pnpm link
Already up-to-date
/Users/Vaughan/nvm/versions/node/v8.1.2/pnpm-global/node_modules/dotfiler -> /Users/Vaughan/dev-live/dotfiler
$ pnpm -v
0.60.3
```

My project `dotfiler` depends on `pnpm@^0.60`. When I run `pnpm link`, my global `pnpm` install is replaced by the local projects.

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
Fix published with [v1.16.3](https://github.com/pnpm/pnpm/releases/tag/v1.16.3)
