### ISSUE TITLE
Cannot find module 'wordwrap'

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#906]
I've tried this multiple times but it always fails.

Created a project using CRNA

```
create-react-native-app myApp
```

Then it defaults to `yarn`but I delete `node_modules/` & `yarn.lock`

```
rm -rf node_modules yarn.lock
```

Then I install using `pnpm`

```
pnpm i
```

Then run `react-native` project, in 1 terminal

```
react-native start
```

& in other terminal

```
react-native run-ios
```

But it gives `Cannot find module 'word-wrap' error` & I tried every SO workaround for `Cannot fin module msg` but nothing works

**Comment by deadcoder0904** [comment]
A quick peek at `node_modules/wordwrap` gives me 3 different versions of `wordwrap` used

`Version 0.0.2` 

`Version 0.0.3` 

`Version 1.0.0`

**Comment by nickpape-msft** [comment]
Can you run `pnpm list wordwrap` to figure out where it is coming from?

**Comment by deadcoder0904** [comment]
Yep exactly or maybe `--shamefully-flatten` might work with it. Unfortunately, I put a halt to some React Native development but I'm getting back at it in some days so I'll check this issue then

**Comment by vjpr** [comment]
The fix for CRNA is here: https://github.com/pnpm/pnpm/issues/940#issuecomment-373437830
