### ISSUE TITLE
Flickering log messages when installing native deps

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#914]
Its probably related to `log-update`.

The lines are also wrapped which is not nice.

Related:

- https://github.com/pnpm/pnpm/issues/877
- https://github.com/pnpm/pnpm/issues/873

**Comment by zkochan** [comment]
You want to see all the output? It is not wrapped when the output is sent via stderr.

Also, I created an issue about flickering at log-update (https://github.com/sindresorhus/log-update/issues/25) but seems like it cannot be fixed there.

**Comment by vjpr** [comment]
Maybe after the install phase, we can use `console.log` instead of `log-update`.

**Comment by zkochan** [comment]
🚢 [1.32.0](https://github.com/pnpm/pnpm/releases/tag/v1.32.0)
