### ISSUE TITLE
Make it possible to install pnpm to custom locations via @pnpm/self-installer

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#922]
This is a follow-up to #902.

It should be possible to install pnpm non-globally with the `@pnpm/self-installer`

**Comment by onlywei** [comment]
Just to add to this, can we specify what version of pnpm we want with the self-installer?

**Comment by zkochan** [comment]
Yep, it is described [here](https://github.com/pnpm/pnpm/tree/master/.scripts/self-installer)

**Comment by zkochan** [comment]
@onlywei you can now use env variables to install pnpm where you want, even via a custom registry. See https://github.com/pnpm/self-installer#readme
