### ISSUE TITLE
`pnpm i -S a-module-already-in-dev-deps` should show message that it wasn't moved to `dependencies`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#926]
I think this is good behaviour, but there should be message warning the user that it was already in `devDeps` and was not moved, and they should do it manually.

### pnpm version: 1.18.1

```
pnpm i -D lodash@1
pnpm i -S lodash@latest
```

Still in dev deps.

Should warn user it was not moved.

### Additional information:

 - `node -v` prints: 8.8.1
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
This doesn't work because to move lodash to prod dependencies, you have to use the `-P/--save-prod` flag.

I am not against a warning though.

Also, I noticed that summary is not printed when dependency is moved from one type to other. It should print something like this:

```
devDependencies:
- lodash 1.0.0

dependencies
+ lodash 1.0.0
```

**Comment by yaodingyd** [comment]
I think this issue is already resolved.

**Comment by Yanzi-dev** [comment]
Hello, I started working on it.
