### ISSUE TITLE
Module did not self-register when installing with npm

### ISSUE THREAD

**Issue by hanxue** [pnpm/pnpm#933]
### Code to reproduce the issue:

Install pnpm with the following

npm : 5.4.2
node: v8.4.0

### Expected behavior:
Install successfully

### Actual behavior:
Returns the following
```
prebuild-install info unpack resolved to /usr/local/lib/node_modules/pnpm/node_modules/drivelist/build/Release/drivelist.node
prebuild-install WARN install Module did not self-register.
  CXX(target) Release/obj.target/drivelist/src/code.o
  CXX(target) Release/obj.target/drivelist/src/log.o
  SOLINK_MODULE(target) Release/drivelist.node
+ pnpm@1.19.5
```

Full output https://gist.github.com/hanxue/d095a706381066ea4fe72f9540f9782c

### Additional information:

MacOS 10.10.5

**Comment by zkochan** [comment]
[drivelist](https://github.com/resin-io-modules/drivelist) is an optional dependency of pnpm. Even if it fails to be installed, pnpm will work fine. You might have problems if you have several disks on your computer but you always can use the [store](https://github.com/pnpm/pnpm#store) config to specify the store location manually.

**Comment by hanxue** [comment]
Thanks for the explanation @zkochan

**Comment by nikoladev** [comment]
I have the exact same issue while installing. The problem is that pnpm can't be used at all:

```shell
➜ pnpm -h
zsh: command not found: pnpm
```

I'm using [Zsh](https://www.zsh.org/) and [Oh My Zsh](http://ohmyz.sh/), as well as:

- npm v5.6.0
- node v8.9.4
- macOS 10.13.2

```shell
➜ npm i -g pnpm
/Users/nikola/.npm-global/bin/pnpx -> /Users/nikola/.npm-global/lib/node_modules/pnpm/lib/bin/pnpx.js
/Users/nikola/.npm-global/bin/pnpm -> /Users/nikola/.npm-global/lib/node_modules/pnpm/lib/bin/pnpm.js

> drivelist@5.2.12 install /Users/nikola/.npm-global/lib/node_modules/pnpm/node_modules/drivelist
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/drivelist-v5.2.12-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/nikola/.npm/_prebuilds/https-github.com-resin-io-modules-drivelist-releases-download-v5.2.12-drivelist-v5.2.12-node-v57-darwin-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /Users/nikola/.npm/_prebuilds/https-github.com-resin-io-modules-drivelist-releases-download-v5.2.12-drivelist-v5.2.12-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/nikola/.npm-global/lib/node_modules/pnpm/node_modules/drivelist/build/Release/drivelist.node
prebuild-install WARN install Module did not self-register.
  CXX(target) Release/obj.target/drivelist/src/code.o
  CXX(target) Release/obj.target/drivelist/src/log.o
  SOLINK_MODULE(target) Release/drivelist.node
+ pnpm@1.29.1
added 645 packages in 48.305s
```

**Comment by zkochan** [comment]
@nikoladev, we have an experimental homebrew package to install pnpm on osx
https://github.com/pnpm/pnpm/issues/959

You can try that but I think it has not the latest version of pnpm. You can
do then `pnpm i -g pnpm`.

Cc @ran-dall
