### ISSUE TITLE
All packages installed by pnpm not detected by npm

### ISSUE THREAD

**Issue by hanxue** [pnpm/pnpm#935]
### Code to reproduce the issue:

1. Delete all files in `node_modules/`
2. Run `pnpm install`
3. Compare output of `pnpm ls` and `npm ls

### Expected behavior:
I can see the packages installed as hard links in `node_modules`. For some reason npm does not detect any of the packages as installed. 

### Actual behavior:

Running any npm commands will cause all the packages to be installed again. 

See full output at https://git.io/vFEkr

### Additional information:

 - `node -v` prints: v8.4.0
 - Windows, OS X, or Linux?: MacOS 10.10.5

**Comment by zkochan** [comment]
I don't think this will ever work. You should choose one pm and use it on a project. pnpm's node_modules structure is different, the different is not only in using hard links. It uses symlinks to create a nested npm2-like structure. More about it here: https://github.com/pnpm/pnpm/blob/master/docs/symlinked-node-modules-structure.md
