### ISSUE TITLE
Node 9 support

### ISSUE THREAD

**Issue by mike3run** [pnpm/pnpm#937]
### Code to reproduce the issue:

`curl -L https://unpkg.com/@pnpm/self-installer | node`

### Expected behavior:

Installs no problem

### Actual behavior:

<img width="766" alt="screen shot 2017-11-12 at 9 12 46 pm" src="https://user-images.githubusercontent.com/7088511/32708241-761379f8-c7ee-11e7-832f-c685e06d65d8.png">

### Additional information:

 - `node -v` prints: 9.0.0
 - Windows, OS X, or Linux?: OSX
- Shell: Fish Shell 2.4.0

**Comment by zkochan** [comment]
FYI, pnpm works on Node.js 9. Tests are running and passing on Travis/Appveyor.

We just need to get rid of the warning

**Comment by mike3run** [comment]
Thanks a lot! I went back to Node 8.9.1 in the meantime and I'm happy with the speed bump pnpm brings to the table
