### ISSUE TITLE
Docs on Site

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#939]
I think this project needs more exposure. Its doing better things than competitors but not many people use it. They don't know what they are missing out. So the first thing is we need Docs on the Site itself rather than on Github page.

I think [Gatsby.js](https://www.gatsbyjs.org) or [Docsify.js](https://docsify.js.org) or [Docute](https://docute.js.org) would be perfect.

What do you think ❓

**Comment by zkochan** [comment]
@deadcoder0904 would you like to work on it? I agree that the current website is lame but I have to concentrate on the pnpm issues for now.

**Comment by deadcoder0904** [comment]
I want to sure but I am busy working on my own startup. That's why I have left a bunch of PRs & issues open for now. Sorry but I can't help for 1-2 months to be sure. 

But if its of any help, take a look at https://datastructures.js.org/#/ 
Code available here -> https://github.com/deadcoder0904/datastructures

Whatever you have written in the README.md can be ported to [docs/README.md](https://github.com/deadcoder0904/datastructures/blob/master/docs/README.md) of that page which would make it work. Wait, I'll give it a try in 5 minutes

**Comment by deadcoder0904** [comment]
Ok I am giving 30 minutes to it & uploading it to my Github. It wouldn't be that good though.

**Comment by deadcoder0904** [comment]
Fuck it, I'll make the site to test my skills in Web Development again 😂

**Comment by deadcoder0904** [comment]
So it took me an hour to edit, but it was worth it. [Its live](https://github.com/deadcoder0904/pnpm-site).

Just add your Algolia key if you want search, add/remove Disqus comments if you want & same for Google Analytics. Let me know what you think ?

**Comment by zkochan** [comment]
The docs look pretty nice.

**Comment by deadcoder0904** [comment]
Then Fork it in the organization so we have central repo & then everyone can send PRs. Its is not optimized yet for Mobile & Tweets part is not added yet. But I think its somewhat usable for now. I'll make it more better later on though.

**Comment by zkochan** [comment]
yeah, I will, I just want to reuse the current homepage because it has more info and internationalization. I'll combine the homepage with the docs part

**Comment by deadcoder0904** [comment]
Cool enough then. If you're gonna use my version, then you should remove Tachyons & just use CSS & rest is taken care with Docute.

Also, in 1/2 months I might just rebuild it with Gatsby to learn more about it & it will be Mind Boggling 🎨 

Till then, if you or anybody is up for the task can do it.

**Comment by brechtdedecker** [comment]
Is this issues still open for contribution ? 
This is my first time contributing to a project, so I'd love to help you guys with that!

**Comment by zkochan** [comment]
you can port the docs from the https://github.com/deadcoder0904/pnpm-site
to this repo https://github.com/pnpm/pnpm.github.io, keeping the current homepage and adding a link to the docs to it.

**Comment by deadcoder0904** [comment]
@brechtdedecker Grab it & do what @zkochan said

**Comment by brechtdedecker** [comment]
So you want me to move the docs file to the website ? should I do anything else like working on the site ? Do some styling ? make it mobile friendly ?

**Comment by zkochan** [comment]
it is mobile friendly already. if you have ideas how to improve the homepage, go ahead. I think the testimonials look not too well on wide screens, maybe they should be in one row.

**Comment by samerela** [comment]
Hello guys,

I believe this issue is still open...

I understand:
1- You want the **docs** file from the [](https://github.com/deadcoder0904/pnpm-site)
to be in this repo [](https://github.com/pnpm/pnpm.github.io)
Could you elaborate more on these two points:
2- "keeping the current homepage" 
3- "adding a link to the docs to it" 

Sorry for the trouble. This is my first time contributing to an open-source project and I don't want to mess it up!

**Comment by zkochan** [comment]
I mean keeping this page: https://pnpm.js.org/
and adding a link to the docs, which will be moved to the pnpm.github.io repo, as you mentioned.

**Comment by samerela** [comment]
@zkochan Thanks for the clarification. I will work on it!

**Comment by zkochan** [comment]
It looks better now. I used gitbook because it was easier for me to configure.
https://pnpm.js.org/docs/

please file issues in the website repo if you want improvements
