### ISSUE TITLE
cli command: npm outdated

### ISSUE THREAD

**Issue by kesla** [pnpm/pnpm#95]
Hey.

Using `npm outdated` doesn't work as expected with the linked dependencies.

**Comment by tomxtobin** [comment]
[`npm-check`](https://github.com/dylang/npm-check) seems to do the trick.

**Comment by zkochan** [comment]
Indeed `npm-check` seems to work. @iamstarkov do you think we can just use npm-check under the hood in pnpm?

Related to #457

**Comment by iamstarkov** [comment]
at least its working solution

**Comment by iamstarkov** [comment]
im not sure how to change pnpm to make `npm outdated` to work as intended

**Comment by zkochan** [comment]
I don't think pnpm can create a node_modules that will work with npm outdated. pnpm has to use symlinks and npm thinks they are the result of npm link.

**Comment by iamstarkov** [comment]
is it possible to fix npm behaviour?

**Comment by zkochan** [comment]
First though it no. How could they differentiate between a npm link and a symlink to a store? I have doubts they would add some custom code for dealing with pnpm

**Comment by zkochan** [comment]
wow! npm-check even has the possibility to use ied or pnpm for updates! https://github.com/dylang/npm-check#update-using-ied-or-pnpm

**Comment by iamstarkov** [comment]
i think of pr to make npm cli respect symlinks for outdated method

**Comment by zkochan** [comment]
that would work for us for sure, if npm would accept such a PR

**Comment by zkochan** [comment]
Published with version `1.14.2`
