### ISSUE TITLE
The https://pnpm.js.org web site is a useless dead end

### ISSUE THREAD

**Issue by pgonzal** [pnpm/pnpm#951]
I'm not sure where else to post this feedback.

Both the NPM package page and your GitHub project page contain links implying that this is the main web site for the project:

    https://pnpm.js.org

When I want to tell people about **pnpm**, I sometimes accidentally share this link.  This web page unfortunately feels unprofessional and creates a negative impression of the tool.  I am trying to advocate **pnpm** within my org, and this web page makes that more difficult for me.

Specific issues:

1. No link to the GitHub project (eventually we did find the GitHub icon hidden in corner of the page, but it wasn't obvious)
2. No link to the NPM package page
3. No installation or usage instructions
4. Not even a very clear description of what pnpm is

I'm not sure the purpose of this web page.  Most of the above information is already provided by the GitHub project page.  I would suggest to either (1) convert https://pnpm.js.org into a simple stub that directs the reader to the GitHub page, or (2) move all your main instructions and content to https://pnpm.js.org and have the GitHub page be the stub (like Yarn does).

Thanks!

**Comment by zkochan** [comment]
Related  #939 

I agree. The website does need a lot of work to get better. As a temporary solution, we can remove the link to the website from the repo and npm pages

**Comment by deadcoder0904** [comment]
@pgonzal Check https://github.com/deadcoder0904/pnpm-site & if you can for now share that link till @zkochan approves a new one. 

I know `pnpm` is great that's why you want to share it, but the guy behind it is a one man army currently committing to make this project better that's why he doesn't have time to make websites. I hope you understand.

So I've made a temporary website, @zkochan fork it into pnpm org & let people send PRs. I think that's the best solution for now.

**Comment by nickpape-msft** [comment]
@deadcoder0904 , we understand that maintaining npm as a single person is definitely a daunting task. I hope @pgonzal 's description didn't come off as being rude. We typically write fairly detailed bugs/work items, and have been filing them not with the intent of having @zkochan fix everything immediately, but rather just to keep track of work that needs to be done. We are definitely happy to contribute to pnpm, as we are attempting to build a tighter collaboration between pnpm and our mono-repo tool, [rush](https://github.com/Microsoft/web-build-tools/wiki/Rush).

**Comment by pgonzal** [comment]
As I said, I am trying to advocate PNPM in my org. I was just proposing two different options for making the marketing materials more effective. I didn't intend this issue as a criticism. Marketing is important. It's people's first impression when they are considering NPM vs PNPM vs Yarn.

**Comment by deadcoder0904** [comment]
@nickpape-msft @pgonzal Yep I understand & it wasn't rude at all. I felt the same way when starting to use PNPM. Its unbelievably faster than NPM/YARN.

**Comment by zkochan** [comment]
It looks better now. I used gitbook because it was easier for me to configure.
https://pnpm.js.org/docs/

please file issues in the website repo if you want improvements

**Comment by pgonzal** [comment]
> please file issues in the website repo if you want improvements

Where is that repo?

**Comment by zkochan** [comment]
https://github.com/pnpm/pnpm.github.io
