### ISSUE TITLE
Install pnpm with Homebrew for MacOS

### ISSUE THREAD

**Issue by ran-dall** [pnpm/pnpm#959]
So if you're on a Mac and you wanna try installing pnpm via Homebrew...I made the formula you can try out.

**Here's the link: https://github.com/ran-dall/homebrew-pnpm**

All you got to do is run: brew install (download location)/pnpm.rb

Feel free to suggest any improvements or problems you have an I'll try to help you.

Thanks to @zkochan for his support and guidance and @ilovezfs for the help in making the Homebrew formula.

**Comment by ran-dall** [comment]
Updated to latest version 1.23.2

**Comment by nikoladev** [comment]
When trying the formula I get an SHA256 mismatch after the bundle is downloaded:

```shell
==> Installing pnpm
==> Downloading https://registry.npmjs.org/@pnpm/bundled/-/bundled-1.23.2.tgz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 5b3a6fbce64f2e1e45e44ddbf0836226794c9a78d114a35a413ca9bb1ee1c41a
Actual: 5440381d6084fa15cba116ddd72666177e5702b9bbacc009db5c39cc860c19f4```

**Comment by onetom** [comment]
https://github.com/ran-dall/homebrew-pnpm/pull/2

**Comment by nikoladev** [comment]
The SHA256 mismatched is fixed thanks to @onetom, thanks for that :)

I can now install pnpm using homebrew but it is stuck at `v1.25.1`, even after running `pnpm i -g pnpm`:

```bash
➜ pnpm -g ls --depth=0
pnpm-global-pkg@1.0.0 /Users/nikola/.npm-global/pnpm-global/1
└── pnpm@1.31.0

➜ pnpm -v
1.25.1
```

Is there any way to update pnpm without waiting for a new version of the formula? Or to use `v1.31.0` that is installed?

**Comment by foisonocean** [comment]
Any updates?

**Comment by ran-dall** [comment]
I'm going to close this out. I deleted the formula a while ago (when v2 came out) because I stopped installing `nodejs` via `homebrew` and have been using `asdf.` If there's still interest, I can make a new formula when I have some extra time.

**Comment by JounQin** [comment]
PR made at https://github.com/Homebrew/homebrew-core/pull/45497

You can try `jounqin/x/pnpm` temporarily.
