### ISSUE TITLE
Package is overriding other globally installed package

### ISSUE THREAD

**Issue by calebeby** [pnpm/pnpm#965]
### Reproduction:
```
pnpm i -g prettier
prettier --version # works
pnpm i -g gzip-size-cli
gzip-size --version # works
prettier --version
# Error: Cannot find module '/home/caleb/.pnpm-global/pnpm-global/node_modules/prettier/bin/p
rettier.js'
```
It seems that whenever one global package is installed, the other is removed from the `pnpm-global/node_modules` folder

### Expected behavior:
I expect the when one is installed, the other stays installed

### Actual behavior:
See above

### Additional information:

 - `node -v` prints: v9.2.1
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
oh wait, why do you use version 0.69 of pnpm? The latest is 1.23.2. Try it with the latest version

**Comment by calebeby** [comment]
Oh, I installed it via the aur package...

**Comment by calebeby** [comment]
https://aur.archlinux.org/packages/nodejs-pnpm/

**Comment by zkochan** [comment]
Try to install it using the methods described here: https://github.com/pnpm/pnpm#install

I did not know about that aur-hosted pnpm. @bgaleotti would you like to automate the process of publishing to aur and add it to out installation section?

**Comment by calebeby** [comment]
Will the self installer script be able to update pnpm, or do I update pnpm with pnpm?

**Comment by zkochan** [comment]
I think it will update pnpm.

**Comment by calebeby** [comment]
Thanks, that worked.

**Comment by bgaleotti** [comment]
@calebeby @zkochan Updated [AUR](https://aur.archlinux.org/packages/nodejs-pnpm/) package

**Comment by calebeby** [comment]
Thank you
