### ISSUE TITLE
ERROR: Cannot find module 'agentkeepalive' when installing pnpm using itself

### ISSUE THREAD

**Issue by onlywei** [pnpm/pnpm#966]
### pnpm version:
1.23.2

### Code to reproduce the issue:

1. Make a new directory with a package.json
2. Run `npm install pnpm`
3. Run `./node_modules/.bin/pnpm install`

### Expected behavior:
I expect this command to succeed.

### Actual behavior:
Instead, I get the error below:
```
$ ./node_modules/.bin/pnpm install
 WARN  Moving pnpm that was installed by a different package manager to "node_modules/.ignored
 ERROR  Cannot find module 'agentkeepalive'
at _resolveFilename                module.js:536
at _load                           module.js:466
at require                         module.js:579
at require                         internal/module.js:11
at getAgent                        …e_modules/make-fetch-happen/agent.js:43
at remoteFetch                     …_modules/make-fetch-happen/index.js:310
at cachingFetch                    …_modules/make-fetch-happen/index.js:176
at defaultedFetch                  …e_modules/make-fetch-happen/index.js:41
at                                 …fetch-from-npm-registry/lib/index.js:21
at at /Users/me/development/scr…  …/npm-resolver/lib/loadPackageMeta.js:72
```

### Additional information:

 - `node -v` prints: 8.9.3
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
Why would you do this? It is such a weird scenario. Can't you just run `npx pnpm install pnpm`? And then run `./node_modules/.bin/pnpm install`

**Comment by zkochan** [comment]
Also, would you use the standalone script for installing pnpm, if it would support custom location? https://github.com/pnpm/pnpm/issues/922

**Comment by onlywei** [comment]
@zkochan I would absolutely use the standalone script for installing pnpm if it supports both:

1. Custom location
2. Download from npm enterprise based on `.npmrc`'s registry setting.

Let me try to see if I can get `npx` working with `npm@3.x`.

**Comment by zkochan** [comment]
The preferred way to do this is:

```
curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
```

as described here: https://pnpm.js.org/en/installation
