### ISSUE TITLE
[Object, Object]

### ISSUE THREAD

**Issue by secretgspot** [pnpm/pnpm#967]
### Actual behavior:
Relinking
S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\require-main-filename\1.0.1\node_modules\require-main-f
ilename from the store
Relinking S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\set-blocking\2.0.0\node_modules\set-blocking
from the store
Relinking S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\string-width\2.1.1\node_modules\string-width
from the store
Relinking
S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\is-fullwidth-code-point\2.0.0\node_modules\is-fullwidth
-code-point from the store
Relinking S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\strip-ansi\4.0.0\node_modules\strip-ansi from
 the store
Relinking S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\ansi-regex\3.0.0\node_modules\ansi-regex from
 the store
Relinking S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\which-module\2.0.0\node_modules\which-module
from the store
Relinking S:\PROJECTS\WEB\TEST\test_pnpm\node_modules\.registry.npmjs.org\y18n\3.2.1\node_modules\y18n from the store
 ERROR  [object Object]
Resolving: total 249, reused 246, downloaded 2

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
@secretgspot I could not reproduce it. If this is still an issue with the latest version pnpm, please provide more details. On what OS did it fail?
