### ISSUE TITLE
media streaming ionic app?

### ISSUE THREAD

**Issue by Anbarasan-321** [pnpm/pnpm#970]
https://ionicacademy.com/ionic-media-streaming/
i followed this above tutorial but got error like this tslint: C:/mediaStreaming/src/pages/home/home.ts, line: 2
All imports are unused.
L1: import { Component } from '@angular/core';
L2: import { NavController } from 'ionic-angular';
L3: import { StreamingMedia, StreamingVideoOptions, StreamingAudioOption
s } from '@ionic-native/streaming-media';
Please check this and tell me how i get output for this?

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:

**Comment by zkochan** [comment]
how is it related to pnpm? Did you use pnpm for installing the dependencies? If so, provide steps to reproduce.
