### ISSUE TITLE
Global Installation

### ISSUE THREAD

**Issue by jpagarcia** [pnpm/pnpm#985]
Tried to install eslint globally, encountered the following error:

` ERROR  request to https://registry.npmjs.org/eslint failed, reason: getaddr
info EAI_AGAIN registry.npmjs.org:443
at err                    …_modules/node-fetch-npm/src/index.js:68  reject(n
ew FetchError(`request to ${request.url} failed, reason: ${err.message}…
at emitOne                events.js:116

at emit                   events.js:211

at socketErrorListener    _http_client.js:387

at emitOne                events.js:116

at emit                   events.js:211

at emitErrorNT            internal/streams/destroy.js:64

at _combinedTickCallback  internal/process/next_tick.js:138

at _tickCallback          internal/process/next_tick.js:180`

Is there anything I can do?

**Comment by zkochan** [comment]
Seems like there are some big problems with the npm registry today. I don't
know the details myself...

See https://github.com/npm/registry/issues/255

Currently, I cannot install `eslint` with any of the Node.js package
managers: pnpm, npm, yarn. It is a problem with the registry, not with pnpm

**Comment by zkochan** [comment]
This issue was solved

https://github.com/npm/registry/issues/255#issuecomment-355780293
