### ISSUE TITLE
Cannot read property 'pkg' of undefined

### ISSUE THREAD

**Issue by nickpape-msft** [pnpm/pnpm#986]
### Code to reproduce the issue:
Not sure yet, we are working in finding a minimalist repro.

### Expected behavior:

Pnpm successfully installs.

### Actual behavior:

The following error is displayed:

```
 WARN  @microsoft/gulp-core-build-karma > karma > chokidar: Skipping failed optional dependency fsevents@1.1.3
 WARN  @microsoft/gulp-core-build > jest-cli > jest-haste-map > sane: Skipping failed optional dependency fsevents@1.1.3
 WARN  ts-jest@20.0.14 requires a peer of jest@^20.0.0 || ^20.1.0-alpha.1 || ^21.0.0-alpha.1 but none was installed.
 ERROR  Cannot read property 'pkg' of undefined
at nodeId                  …dules/supi/lib/link/resolvePeers.js:276
at map
at nodeIdToFriendlyPath    …dules/supi/lib/link/resolvePeers.js:276
at resolvePeers            …dules/supi/lib/link/resolvePeers.js:241
at resolvePeersOfNode      …dules/supi/lib/link/resolvePeers.js:140
at resolvePeersOfChildren  …dules/supi/lib/link/resolvePeers.js:213
at resolvePeersOfNode      …dules/supi/lib/link/resolvePeers.js:136
at resolvePeersOfChildren  …dules/supi/lib/link/resolvePeers.js:213
at default_1 [as default]  …odules/supi/lib/link/resolvePeers.js:87
at <anonymous>             …/node_modules/supi/lib/link/index.js:66
Resolving: total 2113, reused 0, downloaded 1988
Downloading onedrive.pkgs.visualstudio.com/@ms/odsp-shared-react/36.0.46: 13 MB/15.3 MB
Downloading onedrive.pkgs.visualstudio.com/@ms/plannerweb-ui/3.0.16: 5.54 MB/7.97 MB
Downloading onedrive.pkgs.visualstudio.com/office-ui-fabric-react/5.36.0: 5.62 MB/7.4 MB
Downloading onedrive.pkgs.visualstudio.com/office-ui-fabric-react/5.30.0: 5.03 MB/7.33 MB
Downloading onedrive.pkgs.visualstudio.com/@ms/odsp-shared-react/36.0.46: 13 MB/15.3 MB
Downloading onedrive.pkgs.visualstudio.com/office-ui-fabric-react/5.36.0: 5.62 MB/7.4 MB
Downloading onedrive.pkgs.visualstudio.com/office-ui-fabric-react/5.30.0: 5.03 MB/7.33 MB

The command failed:
 Z:\sp-client\1\common\temp\pnpm-local\node_modules\.bin\pnpm install --store Z:\sp-client\1\common\temp\pnpm-store --no-lock
ERROR: Error: The command failed with exit code 1
```

### Additional information:

 - `node -v` prints: v6.11.3
 - Windows, OS X, or Linux?: Windows

**Comment by nickpape-msft** [comment]
@pgonzal

**Comment by zkochan** [comment]
This is where it fails: https://github.com/pnpm/supi/blob/07543200d3d0939fbd7cc569b934025504863fc0/src/link/resolvePeers.ts#L276

It fails when it is trying to print the next warning about peer dependencies. I don't know how to reproduce it but that code is used only for logging. With big probability, commenting out that code will fix the error.

If you need a quick fix, we can do something like

```js
.map(nodeId => tree[nodeId] && tree[nodeId].pkg.name || '...')
```

**Comment by nickpape-msft** [comment]
@zkochan, thank you for being such an involved project maintainer! I will try to workaround you have listed to see if the local repro is fixed and get back to you.

**Comment by zkochan** [comment]
My assumption why this happens is that one of the package IDs contains colon or colons.

A dependency nodeId is a concatenation of package IDs and a colon is used to glue them. In `resolvePeers.ts` we split those node IDs. If one of the package IDs has colons, the split will create to invalid package IDs.

**Comment by nickpape-msft** [comment]
Thanks for fixing this @zkochan !

**Comment by zkochan** [comment]
If my assumption was right, this should work now with `pnpm@1.27.0`.

**Comment by nickpape-msft** [comment]
Looks like it is not occuring anymore. I'll close the issue.
