### ISSUE TITLE
Update pnpm using pnpm fails

### ISSUE THREAD

**Issue by NicoCevallos** [pnpm/pnpm#990]
### pnpm version:
`1.27.0` and `1.29.1`

### Code to reproduce the issue:
`pnpm i -g pnpm`

### Expected behavior:
I ran this command because `pnpm` suggested it to update to the new version `1.29.1`

### Actual behavior:
It fails showing the message:
` ERROR  EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm-global\1\package.json.603248493'`

The file doesn't exist in the folder
![image](https://user-images.githubusercontent.com/10197397/35003738-81472ebc-facc-11e7-8a2f-4e8a0a3db004.png)
[pnpm-debug.log](https://github.com/pnpm/pnpm/files/1636222/pnpm-debug.log)

### Additional information:

 - It seemed to be related to the issue [#928](https://github.com/pnpm/pnpm/issues/928) due yesteday it showed an error creating `pnpm-global` folder
 - `node -v` prints: `v8.9.0`
 - `Windows_NT x64 10.0.16299`

**Comment by zkochan** [comment]
I think this is solved by the fix for #928

**Comment by nguyenxndaidev** [comment]
`pnpm i -g pnpm` or `pnpm add -g pnpm` does not work for me. => solution `npm add -g pnpm`

![image](https://user-images.githubusercontent.com/24372782/74603183-36f9de80-50b1-11ea-86a4-66af53b49636.png)

**Comment by zkochan** [comment]
@nguyenxndaidev 
I did a fix that might solve this: https://github.com/pnpm/pnpm/commit/e4b667e7fba5b190e232fb9db037d1d4b2eb99c3

That one is shipped in 5.2.3

And there's another one on review: https://github.com/pnpm/pnpm/pull/2637

It can be installed through `pnpm i -g pnpm@dev`

**Comment by nguyenxndaidev** [comment]
@zkochan thanks, it works.

![image](https://user-images.githubusercontent.com/24372782/85457451-614c3300-b5a0-11ea-940d-dac9bd329b31.png)

**Comment by nguyenxndaidev** [comment]
@zkochan no, I was too fast.

![image](https://user-images.githubusercontent.com/24372782/85458710-b2a8f200-b5a1-11ea-9563-45e5d04eab5f.png)


Still need npm:
![image](https://user-images.githubusercontent.com/24372782/85458983-fb60ab00-b5a1-11ea-85b2-5de4c045ae10.png)

**Comment by nguyenxndaidev** [comment]
Or do you mean, the original version which runs update must be at least 5.2.3. So next time it should work?

**Comment by zkochan** [comment]
yes, it will work only from v5.2.3

so you can try to install 5.2.3 and update to 5.2.6
